### ISSUE TITLE
fp.isSubnormal is buggy

### ISSUE THREAD

**Issue by LeventErkok** [Z3Prover/z3#10]
This is on the unstable branch.

The following benchmark:

```
(set-option :produce-models true)
(set-logic QF_FP)
(declare-fun s0 () (_ FloatingPoint 11 53))
(assert
   (let ((s1 (fp.isSubnormal s0)))
   s1))
(check-sat)
(get-value (s0))
```

Results in:

```
sat
((s0 (_ +zero 11 53)))
```

which suggests `+0` is a sub-normal number, which isn't true.

**Comment by wintersteiger** [comment]
Thanks for catching that, the fp.is* function have not been tested very well yet, keep reporting them if something looks fishy!
