### ISSUE TITLE
Retrieving models for pareto objectives

### ISSUE THREAD

**Issue by LeventErkok** [Z3Prover/z3#1001]
In https://github.com/Z3Prover/z3/issues/955, you mentioned for pareto, "one simply issues a check-sat" command to retrieve the stream of models.

I'm trying to figure out how to do this in practice. I've tried the following:

```
(declare-const x Int)
(declare-const y Int)
(assert (>= 1 x))
(assert (>= x 0))
(assert (>= 1 y))
(assert (>= y 0))
(minimize x)
(maximize (+ x y))
(minimize y)
(set-option :opt.priority pareto)
(echo "******* 0")
(check-sat)
(get-model)
(echo "******* 1")
(check-sat)
(get-model)
(echo "******* 2")
(check-sat)
(get-model)
(echo "******* 3")
(check-sat)
(get-model)
(echo "******* 4")
(check-sat)
(get-model)
```

But, as far as I can see, z3 prints the exact same model in each of those `check-sat` calls. This does make sense to me since I didn't assert/remove any constraints.

I also tried the following:

```
(set-option :opt.priority pareto)
(check-sat)
(get-value (x) :model_index 0)
(get-value (y) :model_index 0)
(get-value (x) :model_index 1)
(get-value (y) :model_index 1)
```

which did not work either, as it says index is out-of-bounds.

Am I supposed to issue a negated-model before the next check-sat? How does that interact with pareto fronts?

**Comment by NikolajBjorner** [comment]
Pareto fronts from the SMT interface loop and generate models in a sequence without prompts.
You can print models as follows:

    (declare-const x Int)
    (declare-const y Int)
    (assert (>= 1 x))
    (assert (>= x 0))
    (assert (>= 1 y))
    (assert (>= y 0))
    (minimize x)
    (maximize (+ x y)) 
    (minimize y)
    (set-option :opt.priority pareto)
    (set-optin :opt.print_model true)
    (check-sat)

You would have to use the API to get the interactive behavior.

**Comment by LeventErkok** [comment]
Thanks Nikolaj. I wish there was a way to make `get-value` work in this case as well, but this isn't a high-priority item to warrant more work as of now.

I'll close this ticket and instead open a low-priority feature request.
