### ISSUE TITLE
Enabling unsat-cores yields wrong satisfiablity result on simple QF_UFLIRA formula

### ISSUE THREAD

**Issue by mikand** [Z3Prover/z3#1005]
Hi,
I bumped in a very strange behavior with z3 4.5.0 with unsat cores.

When I check the following simple formula:
```
(declare-fun p () Int)
(declare-fun q () Int)
(declare-fun r () Real)
(declare-fun ih (Real Int) Int)
(assert (! (not (=> (and (= (to_real (- p 3)) r) (= (to_real q) r)) (or (< p (ih (to_real (- p 3)) (+ q 3))) (<= (ih r p) p)))) :named a2))
(check-sat)
(exit)
```
I correctly get an `unsat` answer from z3. But just by adding the option `(set-option :produce-unsat-cores true)` at the beginning of the file, I get a `sat` answer from the `check-sat` command!

The very same issue arises when using the python API instead of the command line.

**Comment by wintersteiger** [comment]
Thanks for reporting this issue. We don't have a fix yet, but his is indeed a bug and in debug mode it also triggers an assertion failure:

```
ASSERTION VIOLATION
File: ..\src\model\func_interp.cpp
Line: 215
get_entry(args) == 0
```
