### ISSUE TITLE
Allow interrupts on individual solvers

### ISSUE THREAD

**Issue by PhilippWendler** [Z3Prover/z3#1006]
Currently it is only possible to interrupt whole Z3 contexts. Would it be possible to add a method that interrupts only a single solver instance? In certain cases, this would make it easier to work with multiple solvers in a single context.

**Comment by NikolajBjorner** [comment]
Not sure why this would make a difference. You have to use different contexts if running solvers in parallel. One context per solver.

**Comment by PhilippWendler** [comment]
Suppose there is a thread that uses several solvers for various operations. The solvers are used either sequentially or there could even be multiple solvers created, with only one being actually used for solving at each time (in order to have multiple solver stacks). Now we want to interrupt the solver, for example, to implement a time limit per operation, but do so only for specific solver instances (e.g., because some cheap but high-priority operations should always be able to finish, but other operations should be cancelled, or there are different timeouts per operation, or something similar).

Currently this can only be done checking before interrupting which operation the main thread is currently running, but this check is either racy or requires synchronization for all solver accesses. With the possibility to interrupt individual solvers, it would be much easier to implement this.

**Comment by NikolajBjorner** [comment]
Not sure why it is easier: whenever you have a handle to a solver you can have a handle to the context where the solver belongs to. Interrupting the solver is then equivalent to cancelling the context.

**Comment by PhilippWendler** [comment]
It is not about not having access to the context, it is about not affecting other solver instances unintentionally because the interrupting thread might not be sure which solver instance is currently solving.

**Comment by NikolajBjorner** [comment]
Ok, makes sense. it remains possible to use a critical section to track currently running instance.

**Comment by NikolajBjorner** [comment]
Race conditions remain in both approaches as far as I can see, though, so we may need some more thought.
