### ISSUE TITLE
Missing API methods to retrieve parsed sorts and function declarations (smtlib 2)?

### ISSUE THREAD

**Issue by facanferff** [Z3Prover/z3#1009]
Hi, I have a file .z3 that contains several sort and function declarations, as well several assertions.
In order to import this using the Java API I use 
```context.parseSMTLIB2String(<z3 code>, null, null, null, null)```
It correctly parses and the toString() of the solver (created previously from that context) shows indeed all sort declarations, etc.
However, after this I need to create on runtime new constants as well new assertions that make use of the parsed sort and function declarations.

In the API I saw there is one context.parseSMTLIBString, which has the same goal of parseSMTLIB2String, but it is intended for an older smtlib version, and also there is one context.getSMTLIBDecls and context.getSMTLIBSorts (only operational after using parseSMTLIBString/parseSMTLIBFile) that do what I needed respective to parseSMTLIB2String.

So, is the API missing a context.getSMTLIB2Decls and context.getSMTLIB2Sorts, or I'm just missing something?

Thanks.

**Comment by NikolajBjorner** [comment]
The API does not expose those methods for smtlib2. They were initially added for SMT-LIB1 where there was explicit tracking of these objects. The SMT-LIB2 parser does not track these objects.

You can still retrieve functions and sorts by walking the formulas returned by the parser and retrieving the sorts/functions, or even simpler by creating a sort/function directly using the API using the same names as in the files. Thus, these extra API methods are not necessary to extract this information.

**Comment by facanferff** [comment]
I see, I'll try to do like that, thanks for the ideas.
