### ISSUE TITLE
z3 basic question (python)

### ISSUE THREAD

**Issue by hdarwin** [Z3Prover/z3#101]
```
In [1]: from z3 import *

In [2]: x = Int('x')

In [3]: solve(x < 5, x > 0)
[x = 1]
```
I want to produce 1,2,3,4.

how should I do?

I dont want to repeat some routine. I mean is there any way to enumerate satisfiable results?

sorry for my english hehe

**Comment by wintersteiger** [comment]
The usual ways to get more than one solution are these:
  - Run `solve` again, with the additional constraint that  x shouldn't be the previous solution,
  - Rephrase the original problem to contain five variables, i.e., x_0... x_5 with the additional assertion that all of them must be distinct (see [Distinct](http://z3prover.github.io/api/html/namespacez3py.html#aa79af225f3b27b84fef346c257d2e406))

**Comment by NikolajBjorner** [comment]
For example,

    from z3 import *
    x = Int('x')

    s = Solver()
    s.add(x < 5, x > 0)

    while sat == s.check():
        m = s.model()
        print m
        decls = m.decls()
        fml = And([m.get_interp(d) == d() for d in decls])
        s.add(Not(fml))

**Comment by hdarwin** [comment]
@wintersteiger @NikolajBjorner 
thanks alot !
