### ISSUE TITLE
Am I misunderstanding arrays or is this a bug?

### ISSUE THREAD

**Issue by SMTStuck** [Z3Prover/z3#1014]
Consider the following SMT-Lib script:

http://rise4fun.com/Z3/LuRm4

    (declare-const x Int)
    (declare-const a1 (Array Int Int))
    (assert (= (select a1 0) 0))
    (assert (= (select a1 1) 1))
    (assert (= (select a1 2) 2))
    (assert (= (select a1 0) 2))
    (check-sat)

This is an unsatisfactory model as we are asserting that index 0 of a1 is both 0 and 2. This is expected.

Consider the following:

http://rise4fun.com/Z3/njxqM

    (declare-const x Int)
    (declare-const a1 (Array Int Int))
    (assert (= (select a1 x) x))
    (assert (= (select a1 2) 0))
    (check-sat)

This is a satisfactory model - why? We are asserting that an element at index x is equal to x - and as x has no conditions tied to it, we are essentially creating an array such as: [0] = 0, [1] = 1, [2] = 2 etc... But at the same time we are also asserting that element 2 is equal to 0.

Am I misunderstanding arrays or is this a bug? If I am misunderstanding them, are there any resources which may help me? The Z3 guide on rise4fun is a little sparse on these subjects, and the formal documentation on the ArraysEx theory is well over my head!

**Comment by delcypher** [comment]
@SMTStuck 
> This is a satisfactory model - why? We are asserting that an element at index x is equal to x - and as x has no conditions tied to it, we are essentially creating an array such as: [0] = 0, [1] = 1, [2] = 2 etc... But at the same time we are also asserting that element 2 is equal to 0.

Your reasoning here is wrong. In the SMT-LIBv2 query you provide are asserting that there **exists** an array element at index `x` that has value `x`. You are **not** asserting that *all** elements at index `x` have value `x`.

If you wanted to assert that you'd have to write something like

```
(declare-const x Int)
(declare-const a1 (Array Int Int))
(assert (= (select a1 x) x))
(assert (= (select a1 5) 0))
(assert (forall ((y (Int))) (= (select a1 y) y)))
(check-sat)
```

which Z3 will report as `unsat`.

Also the correct terminology is "satisfiable" not "satisfactory".

**Comment by SMTStuck** [comment]
Thank you - I appreciate your input. 😃
