### ISSUE TITLE
str.at fails with special charachter

### ISSUE THREAD

**Issue by PierreVDL** [Z3Prover/z3#1015]
Running z3 with the following smt2 code
```
(get-info :name)
(get-info :version)
(set-logic ALL)
(set-option :produce-models true)
(set-info :smt-lib-version 2.5)

(declare-fun s() String)
(assert (= "a" s))
(check-sat)
(get-value (s))
(assert (= (str.len s) 1))
(check-sat)
(declare-fun c() String)
(assert (= (str.at s 0) c))
(check-sat)
```
yields
```
(:name "Z3")
(:version "4.5.1 - build hashcode 66e61b8a31a0")
sat
((s "a"))
sat
sat
```
However a small change in code
```
(get-info :name)
(get-info :version)
(set-logic ALL)
(set-option :produce-models true)
(set-info :smt-lib-version 2.5)

(declare-fun s() String)
(assert (= "\x80" s))
(check-sat)
(get-value (s))
(assert (= (str.len s) 1))
(check-sat)
(declare-fun c() String)
(assert (= (str.at s 0) c))
(check-sat)
```
yields
```
(:name "Z3")
(:version "4.5.1 - build hashcode 66e61b8a31a0")
sat
((s "Ç"))
sat
unsat
```

In my humble opinion the last unsat is wrong.

Could you please look into this?

**Comment by NikolajBjorner** [comment]
It is not a matter of opinion. It is a bug.

**Comment by NikolajBjorner** [comment]
BTW, the z3str3 solver is being integrated. You can use this solver instead of the original solver by setting
(set-option :smt.string_solver z3str3)
It did not hit this bug. There are some bugs to weed out in that solver, but it is shaping nicely. Having regression tests integrated in our build would help reaching stability. I have checked in this bug report under the z3test repository under regressions\smt2\string14.smt2.

**Comment by PierreVDL** [comment]
Thanks for the info.
Is there also a command line option as alternative for (set-option :smt.string_solver z3str3)?

**Comment by NikolajBjorner** [comment]
Yes, smt.string_solver=z3str3. This is similar to all other options.

**Comment by NikolajBjorner** [comment]
Can I close this?

**Comment by PierreVDL** [comment]
Just downloaded the latest nightly build.
This yields
```
C:\Program Files Local\z3-4.5.1.d2ac59f238ca-x64-win\bin>z3 test.smt2
(:name "Z3")
(:version "4.5.1 - build hashcode d2ac59f238ca")
sat
((s "Ç"))
sat
sat
```
So indeed solved!
