### ISSUE TITLE
Z3 Build Issue

### ISSUE THREAD

**Issue by Edillower** [Z3Prover/z3#1016]
Hello,
I was trying to build Z3. but got the following error message.
```
$ make
...
src/util/gparams.cpp
src/util/hash.cpp
../src/util/hash.cpp:86:9: error: fallthrough annotation does not directly
      precede switch label
        Z3_fallthrough;
        ^
../src/util/util.h:82:26: note: expanded from macro 'Z3_fallthrough'
#  define Z3_fallthrough [[clang::fallthrough]]
                         ^
1 error generated.
make: *** [util/hash.o] Error 1
```

Thanks in advance.

**Comment by NikolajBjorner** [comment]
try to comment out the last fall through, or pull the update (but be cautious with the latest Z3 as we are currently integrating some C++11 dependencies and fixing build breaks in some older compilers at this point).

**Comment by Edillower** [comment]
Works well. Thanks for your prompt response.
