### ISSUE TITLE
fp - FP solver seems to have suffered a soundness issue

### ISSUE THREAD

**Issue by LeventErkok** [Z3Prover/z3#102]
@wintersteiger I was trying the recent fixes you put in, and it appears z3 pretty much always answers every query with `unsat`?

For instance, with a fresh build out of the `unstable` branch, I get `unsat` for the following query:
```
(set-logic QF_FP)
(define-fun s1 () (_ FloatingPoint 11 53) ((_ to_fp 11 53) roundNearestTiesToEven (/ 0 1)))
(declare-fun s0 () (_ FloatingPoint 11 53))
(assert
   (let ((s2 (fp.eq s0 s1)))
   s2))
(check-sat)
```

This query is clearly satisfiable when `s0` is `+0`.

**Comment by wintersteiger** [comment]
That's right, looks like I didn't quite finish that job before committing my changes. Everything should be okay now though.
