### ISSUE TITLE
Quantifier specification

### ISSUE THREAD

**Issue by mm95** [Z3Prover/z3#1025]
Hello, 
I want using quantifiers to check that if a special variable can get all values in a determined bounds according to formula. For example :
```
(declare-const a Int)
(declare-const b Int)
(declare-const c Int)
(assert (= a b))
(assert (forall ((x Int))
                (= b x)))
```
I want to state that if b can get all values in its domain. Although it can, but z3 returns "unsat". 
What's the problem with specification ?

Thanks so much.

**Comment by NikolajBjorner** [comment]
There are infinitely many integers, so for any integer b, there is a different integer b', therefore forall x: x = b is false. You could use an uninterpreted sort S, then declare a, b, c of sort S and assert forall x : S . x = b. In this case the domain of S has to be a singleton.
