### ISSUE TITLE
iZ3 - AST cannot be converted to Expr

### ISSUE THREAD

**Issue by MarcusVoelker** [Z3Prover/z3#103]
The new ComputeInterpolant function of the InterpolationContext indeed now returns its ASTVector. (#82). However, it appears to be impossible to convert an AST into an Expr, because the function  Expr.create used by GetInterpolant to do just that is package-private. I tried downcasting AST to Expr, but that does not work either. Is there any other way to accomplish that conversion?

**Comment by MarcusVoelker** [comment]
Fixed with acceptance of #104

**Comment by MarcusVoelker** [comment]
Reopened with acceptance of #106

**Comment by wintersteiger** [comment]
Thanks for reporting this issue. These functions really shouldn't expose ASTVectors to the outside. I've given the .NET, Java and ML APIs a bit of an overhaul for recent API changes, also including a fix for ComputeInterpolant. Closing this as fixed.
