### ISSUE TITLE
Is FOCI2 dead?

### ISSUE THREAD

**Issue by delcypher** [Z3Prover/z3#1032]
@kenmcmil is FOCI2 dead?

The old build system supports the `--foci2=` option. For the CMake build system I added the `USE_FOCI2` option but never implemented it.

I wanted to try implementing but I can't find the binaries for FOCI2. When I go to http://www.kenmcmil.com/foci.html the link at the bottom of the page it takes me to https://www.cadence.com/content/cadence-www/global/en_US/home/support/web-collaboration.html which does not seem very useful.

Are the binaries still available somewhere? If not we should probably remove the FOCI2 support because the code supporting it in Z3 is probably not being tested and rotting.

**Comment by NikolajBjorner** [comment]
mentions to foci2 can be deprecated. They predate Ken's implementation of interpolation within Z3.

**Comment by delcypher** [comment]
@NikolajBjorner Okay I won't bother adding support to the CMake build system for it then.

There are still some existing source files (other than `CMakeLists.txt` files) that seem to mention it.

* `scripts/mk_util.py`
* `src/interp/foci2.h`
* `src/interp/foci2stub/foci2.cpp`
* `src/interp/foci2stub/foci2.cpp`
* `src/interp/foci2stub/foci2.h`
* `src/interp/iz3foci.cpp`
* `src/interp/iz3translate.h`

They should be cleaned up or deleted.

**Comment by NikolajBjorner** [comment]
@kenmcmil - this seems unused, right?

**Comment by kenmcmil** [comment]
Yes, the dependency on foci2 is obsolete and can be removed. I can remove it from the code.

**Comment by kenmcmil** [comment]
I've put in a pull request that removes the dead code supporting FOCI2 in src/interp. You can also remove the support for FOCI2 in mk_util.py and any other files it might occur in.

**Comment by NikolajBjorner** [comment]
superb, thanks! Merged.
