### ISSUE TITLE
Parsing datatype sorts using Java API leading to redundant function declarations

### ISSUE THREAD

**Issue by facanferff** [Z3Prover/z3#1034]
Hi, I noticed that if I have in a .z3 file:
```
(declare-datatypes () ((General
    (G_Boolean (of_G_Boolean Bool))
    (G_Integer (of_G_Integer Int))
    (G_String (of_G_String String))
    G_Null
)))

(declare-const _v_ General)
(assert (= (of_G_String _v_) "test"))
```
and try to parse it using context.parseSMTLIB2String (without specifying additional sorts or function declarations) followed by adding it as an assertion to solver, the solver.toString() will return
```
(declare-datatypes () ((General (G_Boolean (of_G_Boolean Bool)) (G_Integer (of_G_Integer Int)) (G_String (of_G_String String)) (G_Null))))
(declare-fun G_Boolean (Bool) General)
(declare-fun of_G_Boolean (General) Bool)
(declare-fun G_Integer (Int) General)
(declare-fun of_G_Integer (General) Int)
(declare-fun G_String (String) General)
(declare-fun of_G_String (General) String)
(declare-fun G_Null () General)
(declare-fun _v_ () General)
(assert (= (of_G_String _v_) "test"))
```

Is this expected? I was expecting only the line 1 and 9-10. In more complex scenarios (with several assertions around the datatype) it ends generating invalid models (that don't respect some assertion), however when I remove those additional function declarations it produces completely correct models.

So, my question is whether it is supposed for the Java API to create those additional function declarations or not.

**Comment by NikolajBjorner** [comment]
Thanks. It seems the pretty printer is adding the auxiliary function declarations that are already covered by the data-type.

**Comment by facanferff** [comment]
Thanks, it is now behaving as expected.
