### ISSUE TITLE
wheel builds for osx

### ISSUE THREAD

**Issue by stephengroat** [Z3Prover/z3#1038]
i see builds for linux, any idea if `osx` builds could be offered? `travis-ci` could be used to make them

**Comment by NikolajBjorner** [comment]
On https://github.com/Z3Prover/bin/tree/master/nightly we have:

z3-4.5.1.cfd598fabba7-x64-osx-10.11.6.zip 
Automatic nightly build. 
an hour ago 
 
z3-4.5.1.cfd598fabba7-x64-osx-10.11.6.zip.log 
Automatic nightly build. 
an hour ago

**Comment by stephengroat** [comment]
thanks, sorry about that. just wondering why i didn't see they on pypi
