### ISSUE TITLE
z3str3 crashes

### ISSUE THREAD

**Issue by PierreVDL** [Z3Prover/z3#1039]
On this file:
[ColorFromString.zip](https://github.com/Z3Prover/z3/files/1021749/ColorFromString.zip)

With different solvers I get the correct answer:
```
c:\Users\pilaar\Desktop\TheMa\Experiments\Smt>cvc4 ColorFromString.smt2
(:name "cvc4")
(:version "1.5-prerelease")
ColorFromString.smt2:6.18: No set-logic command was given before this point.
ColorFromString.smt2:6.18: CVC4 will make all theories available.
ColorFromString.smt2:6.18: Consider setting a stricter logic for (likely) better performance
.
ColorFromString.smt2:6.18: To suppress this warning in the future use (set-logic ALL).
sat
((cw white))
sat
((cr red))
sat
((cb blue))
```
and
```
c:\Users\pilaar\Desktop\TheMa\Experiments\Smt>z3 ColorFromString.smt2
(:name "Z3")
(:version "4.5.1 - build hashcode 4069e76ab0ec")
sat
((cw white))
sat
((cr red))
sat
((cb blue))
```

However, with the z3str3 solver it crashes:
```
c:\Users\pilaar\Desktop\TheMa\Experiments\Smt>z3 smt.string_solver=z3str3 ColorFromString.smt2
(:name "Z3")
(:version "4.5.1 - build hashcode 4069e76ab0ec")
```
![crash](https://cloud.githubusercontent.com/assets/13330317/26349637/9e150668-3fb0-11e7-93f8-8403dc9d84fb.jpg)

**Comment by NikolajBjorner** [comment]
Thanks for trying it out.  
@mtrberzi: It crashes in  void theory_str::set_up_axioms(expr * ex). Likely as the result of traversing an if-then-else expression.

**Comment by mtrberzi** [comment]
Thanks, I'll take a look at this. I don't generally expect quantifiers to appear in these instances. If the code can be improved to take this into account without affecting the rest of the solver, or to give incrementality, I think we should explore that.

**Comment by NikolajBjorner** [comment]
I fixed this crash, I believe we can close this ticket.

**Comment by PierreVDL** [comment]
As this example shows:
```
c:\Users\pilaar\Desktop\TheMa\Experiments\Smt>z3 smt.string_solver=z3str3 ColorFromString.smt2
(:name "Z3")
(:version "4.5.1 - build hashcode 907899debe8b")
sat
((cw white))
sat
((cr red))
sat
((cb blue))
```
the problem is indeed solved!

Thanks!
