### ISSUE TITLE
Unexpected value change in multiple calls to check-sat

### ISSUE THREAD

**Issue by LeventErkok** [Z3Prover/z3#1041]
I'm observing something I haven't expected, using a freshly checked out copy of z3.

For this input:

```
(set-logic QF_BV)
(declare-fun s0 () (_ BitVec 8))
(check-sat)
(assert (bvsge s0 #x05))
(assert (bvslt s0 #x07))
(check-sat)
(get-value (s0))
(check-sat)
(get-value (s0))
```

Z3 says:

```
sat
sat
((s0 #x06))
sat
((s0 #x05))
```

Now, there's nothing really wrong here, as z3 is producing a valid value in each case. But I'm surprised to see that the value is changing between the second and the third call to `check-sat`, even though nothing changes in between.

The above script looks "weird" indeed, but it's the minimum I was able to reduce to from a more complicated scenario.

[Furthermore, if I use `Int` for the type (as opposed to `(_ BitVec 8)`), the model remains the same.]

Is this the expected behavior? While there isn't anything that says successive calls to `check-sat` with no assertions in between should produce the same model, I'm surprised to see that that does not happen.

Put slightly differently, I'd have expected two consecutive calls to `check-sat` with no intervening `assert`s in between to produce the precise same model, which doesn't seem to be the case in Z3. Perhaps that's a property it should have?

**Comment by NikolajBjorner** [comment]
The sat solver is called in incremental mode. The random seed isn't reset between calls, so the second call uses a different sequence of random numbers that are used to select variables and other random features for CDCL.

**Comment by LeventErkok** [comment]
I see. I guess my mental model of: "check-sat gives you a model, and it won't change unless you add new assertions" is too naive.

Thanks!
