### ISSUE TITLE
z3 parse dimacs input file in c++ API

### ISSUE THREAD

**Issue by mm95** [Z3Prover/z3#1042]
Hello,
How can I parse dimacs file as an input file via c++ api?

thanks,
Maryam.

**Comment by NikolajBjorner** [comment]
You can parse the dimacs file directly, then create a solver object and add the clauses to the solver object. 
The dimacs parser available from the shell command-line is not exposed over the API. The only supported text format over the API is SMT-LIB. The DIMACS format is well documented online and C parsers can be hoisted from several places (including Z3 source)
