### ISSUE TITLE
SMT-Lib compliant printing of literals

### ISSUE THREAD

**Issue by LeventErkok** [Z3Prover/z3#1043]
For the following input:

```
(get-info :reason-unknown)
```

z3 prints:

```
(:reason-unknown "(error "line 1 column 11: state of the most recent check-sat command is not known")
```

This isn't SMTLib compliant, since the new standard speculates quote characters should be escaped by using two of them. So, it should look something like:

```
(:reason-unknown "(error ""line 1 column 11: state of the most recent check-sat command is not known")
```

Even then, it looks rather _bizarre_, perhaps this should simply print as:

```
(:reason-unknown "line 1 column 11: state of the most recent check-sat command is not known")
```

which I guess was the original intent but the call to `error` seems to be leaking in somehow.

**Comment by LeventErkok** [comment]
@NikolajBjorner I did a fresh build, but the response I'm getting hasn't changed at all in this case. I'm still seeing the incorrectly formatted output.

**Comment by NikolajBjorner** [comment]
I don't have a repro for this on my end

**Comment by LeventErkok** [comment]
This seems to suffice for me:

```
(set-logic QF_BV)
(get-info :reason-unknown)
```

To which z3 (just built) responds:

```
(:reason-unknown "(error "line 2 column 10: state of the most recent check-sat command is not known")
```

I suspect the issue is the `throw` here: https://github.com/Z3Prover/z3/blob/master/src/cmd_context/cmd_context.cpp#L641

It seems the interaction between that and the `:reason-unknown` is making this go wrong?

**Comment by LeventErkok** [comment]
Fantastic! Works as advertised now.
