### ISSUE TITLE
Unexpected output when "produce-proofs" is given

### ISSUE THREAD

**Issue by LeventErkok** [Z3Prover/z3#1045]
I'm playing with proof-generation features in Z3. For this input:

```
(set-option :produce-models true)
(set-logic QF_FP)
(declare-fun s0 () Int)
(declare-fun s1 () (_ FloatingPoint  8 24))
(assert (>= s0 0))
(check-sat)
(get-value (s0))
```

Z3 happily produces:

```
sat
((s0 0))
```

Note that I'm using `QF_FP` for the logic, since I want to mix Integers and Floats. (Is there a logic that "officially" combines them? I couldn't find it.)

However, if I insert `(set-option :produce-proofs true)` at the very top, keeping everything else the same:

```
(set-option :produce-proofs true)
(set-option :produce-models true)
(set-logic QF_FP)
(declare-fun s0 () Int)
(declare-fun s1 () (_ FloatingPoint  8 24))
(assert (>= s0 0))
(check-sat)
(get-value (s0))
```

I get:

```
sat
((s0 Int!val!0))
```

So, it appears the `(set-option :produce-proofs true)` makes z3 decide to interpret `Int` as an uninterpreted sort in this case.

I think the setting of `QF_FP` can justify that decision, but why doesn't that happen in the original input? Or conversely, if the original is OK, why does setting `:produce-proofs` to `true` cause a different behavior here?

I'm not suggesting this is a bug, but it seems inconsistent.

**Comment by NikolajBjorner** [comment]
Z3 uses a larger repertoire of options when proofs are turned off. This includes an option that understands arithmetic even as QF_FP is specified. Pedantically it is an error to use integers, but we don't flag this.

**Comment by LeventErkok** [comment]
Right, I suspected as much. What's my option if I have both floats and integrers mixed for setting the logic? Is "ALL" the correct choice here?

**Comment by NikolajBjorner** [comment]
Yes. Qffp just ensures the minimal set of plugins are present

**Comment by wintersteiger** [comment]
QF_FP does not include integers (or reals), so "Int" is assumed to be uninterpreted. There is no official name for FP+Int yet and we don't have specalized tactics for that combination either, so may be best not to set any logic or "ALL" so that everything is enabled. 

(The reason for the difference in behaviour is rooted in the fact that many tactics don't support proofs and this is one of those cases where the "qffp" tactic immediately bails out and sends everything to the "most general" SMT solver. It's possible that we don't set the right logic declaration when that happens, will check.)

**Comment by LeventErkok** [comment]
Thanks Christoph! I think the logic-selection mechanism in SMT-Lib remains a thorny issue. The set of fixed combinations is just very hard to use. I wish we had a mechanism where the user can simply "request" features. Something like:

```
(require Floats)
(require Integers)
(require BitVectors)
```

(with some suitable syntax), and the solver can return `success`/`error` to each require line as it accumulates the requested features and internally sets up its logic. It can then dynamically reject combinations that it cannot support for whatever reason.

This is of course an SMT-Lib discussion, one I believe that comes up every so often but hasn't really been  addressed so far.

I'll close this ticket.

**Comment by LeventErkok** [comment]
I'm still having some issues in setting the logic correctly. I was under the impression that "ALL" meant I can use all features, but that does not seem to be the case:

```
(set-logic ALL)
(assert ((_ pbeq 1 1 1) true false))
(check-sat)
```

This produces:

```
(error "line 2 column 34: invalid use of indexed indentifier, unknown builtin function pbeq")
```

If I remove the setting of the logic, then the problem goes away.

Should `ALL` not imply that everything that z3 supports is fair game? Otherwise it becomes really hard to decide what logic to set.

**Comment by LeventErkok** [comment]
Works as advertised now. Thanks!

**Comment by wintersteiger** [comment]
Yes, the `(require ...)` feature is being discussed among SMT-LIB people... and it has been a recurrent topic for years. We'll see where it goes, but I'm starting to think about adding our own "draft" of that to Z3.
