### ISSUE TITLE
java bindings; decode Expr objects

### ISSUE THREAD

**Issue by proteusGIT** [Z3Prover/z3#1051]
Hi,

after applying some simplification I want to decode the resulting expression (beyond printing it as a String).

Using operations such as `Expr.isAnd` it is possible to determine the outermost operator.
Is this possible for `str.len` and the other string operations as well?

Is it possible to detect and extract string-constants?
It works for integers: `((IntNum) input).getInt64()`
I am generating the expression using `Context.MkString`

Best Regards

**Comment by proteusGIT** [comment]
for the `str.len` operation I am using now `if (input.isInt() && input.getFuncDecl().getName().isStringSymbol() && ((StringSymbol) input.getFuncDecl().getName()).getString().equals("str.len"))`
and for extracting the string I am using `if (input.isConst() && input.getFuncDecl().getName().isStringSymbol()) {
            String string = input.getSExpr();
            string = string.substring(1, string.length() - 1);`

Both solutions are imo somewhat embarrassing...

**Comment by NikolajBjorner** [comment]
It isn't the way it should be. The C API exposes Z3_is_string and Z3_get_string. 
They seem not leveraged in the .Net or Java APIs yet. This is a bug.

to test for str.len it is more robust to roll a version for:

boolean isSeqLen()
{
     return isApp() && getFuncDecl()..getDeclKind() == Z3_decl_kind.Z3_SEQ_LENGTH;
}

(see Expr.java for examples).

In Z3 strings are special cases of sequences.

**Comment by proteusGIT** [comment]
Here I get `Z3_OP_INTERNAL` instead of `Z3_SEQ_LENGTH`...

**Comment by proteusGIT** [comment]
I do not know why but now for `(str.indexof "" "" 0)` I get `Z3_OP_FPA_MAX_I` instead of `Z3_OP_SEQ_INDEX` ..

**Comment by NikolajBjorner** [comment]
This could be a matter of ensuring that dlls are in sync.

**Comment by proteusGIT** [comment]
pulled to the current version using git and recompiled z3 including the jar and *.so files.
Same thing happens to me..
I added
 ```     
public void stringExample(Context ctx) throws TestFailedException {             
     System.out.println("stringExample");
             Expr expression = ctx.mkIndexOf(ctx.mkString(""), ctx.mkString(""), ctx.mkInt(0));
             if (expression.getFuncDecl().getDeclKind() != Z3_decl_kind.Z3_OP_SEQ_INDEX)
                 throw new TestFailedException();
         }
```
as a test case to the java-example and also adding `p.stringExample(ctx);` before `p.optimizeExample(ctx);`.
The same thing happens there.
Does it work on your side?

**Comment by delcypher** [comment]
@proteusGIT Did you use the python/Makefile build system? That build system has know problems doing incremental builds. Did you try doing a fresh build (i.e. new build directory so that everything is built from scratch)?

**Comment by proteusGIT** [comment]
I removed the directory entirely.
I cloned it again.
I did `python scripts/mk_make.py --java; cd build; make` as before.
I restarted my IDE.
I even restarted my computer (which is ridiculous as I am on linux).
result: same problem.

Does it work for others?
Is there a `make clean` like procedure somewhere hidden?

**Comment by proteusGIT** [comment]
Besides the string issue, the java test program works fine..

**Comment by delcypher** [comment]
@proteusGIT 
> I even restarted my computer (which is ridiculous as I am on linux).

That's definitely unnecessary :p 

> Does it work for others?

I don't use the Java bindings so I don't know. I also haven't worked with the String solver support before.
If you provide a minimal example that I can build I can try.

> Is there a make clean like procedure somewhere hidden?

The python/Makefile build system doesn't have it AFAIK.

The replacement [CMake build system](https://github.com/Z3Prover/z3/blob/master/README-CMake.md) that I've been implementing does have a `clean` target and also because it's CMake you get other nice things like good integration with IDEs like Visual Studio/XCode/CLion and the ability to use `ninja` instead of `make` for really fast incremental builds :D

It does have some issues (#986) still but I implemented support for building Java bindings a while a go so hopefully that still works. You can see the documentation for this build system [here](https://github.com/Z3Prover/z3/blob/master/README-CMake.md).

**Comment by delcypher** [comment]
@proteusGIT Another thought? Do you have Z3 installed somewhere on your system? You might have a stale copy of `libz3.so` somewhere and that might be picked by your system's dynamic linker at run time.

**Comment by proteusGIT** [comment]
Must have been some build system thing.
Using the CMake build system the problem is resolved.

**Comment by delcypher** [comment]
@proteusGIT Awesome. A win for the new build system :) . Could please close this issue?

**Comment by NikolajBjorner** [comment]
It is (another) win.
Are there other issues with string recognizers that can be addressed? In principle we could add tester shorthands to the API similar to IsAnd. Is this important for your code?

**Comment by proteusGIT** [comment]
Well I would use more direct methods for identifying the different cases but as of now it is not really necessary I guess...
