### ISSUE TITLE
Support for sorts with constructors in Datalog is incomplete

### ISSUE THREAD

**Issue by ryzhyk** [Z3Prover/z3#1052]
A [recent commit](https://github.com/Z3Prover/z3/commit/2cbeedec690fbd89da1a4154ae96708af77cfe65) by @NikolajBjorner adds support for sorts with constructors in Datalog relations. Unfortunately, it appears to be incomplete. The following example illustrates two issues I've encountered so far. 

```
(set-option :fixedpoint.engine datalog)
(define-sort s () (_ BitVec 3))
(declare-datatypes () ( (Edge (ed (from s) (to s)) nil ) ))
(declare-rel edge (Edge))
(declare-rel path (s s))
(declare-var f s)
(declare-var t s)
(declare-var g s)
(declare-var e Edge)

;(rule (=> (and (edge e) (is-ed e)) (path (from e) (to e) )))
(rule (=> (edge (ed f t)) (path f t)))

(rule (=> (and (path f g) (path g t)) (path f t)))
(rule (edge (ed #b001 #b101)))
(rule (edge (ed #b101 #b111)))
(query path :print_answer true)
(query edge :print_answer true)
```

Issue 1: The first query above succeeds and prints the answer, while the second query fails, refusing to print a non-numeric sort:

```
sat
(or (and (= (:var 0) #b101) (= (:var 1) #b111))
    (and (= (:var 0) #b001) (= (:var 1) #b101))
    (and (= (:var 0) #b001) (= (:var 1) #b111)))
(error "query failed: sort 'Edge' is not recognized as a sort that contains numeric values.
Use Bool, BitVec, Int, Real, or a Finite domain sort")
unknown
```

Issue 2: The commented-out rule is logically equivalent to the one following it; however uncommenting this rule and removing the following line causes both queries to fail: 

```
(error "query failed: Uninterpreted 'from' in path(#1,#2) :- 
 edge(#0),
 (= (:var 2) (to (:var 0))),
 (= (:var 1) (from (:var 0))),
 (is-ed (:var 0)).
")
unknown
(error "query failed: Uninterpreted 'from' in path(#1,#2) :- 
 edge(#0),
 (= (:var 2) (to (:var 0))),
 (= (:var 1) (from (:var 0))),
 (is-ed (:var 0)).
")
unknown
```

Issue 2 goes away if I declare Edge with just one constructor (by removing the nil constructor)

**Comment by NikolajBjorner** [comment]
This is pushing the Datalog engine into a territory where it isn't suited. It takes flat relations and relies on the caller to flatten the encoding. The back-end engines are all table based. So they operate on a notion of relations over finite _enumeration_ domains. Algebraic datatypes allow finite types by nesting, but a representations as tables require an encoding that the backend does not address. 
Besides this, the error message that gets reported has to do with selector functions. These are uninterpreted when applied to constructors that don't match. For example car(nil) does not have a fixed interpretation. Similarly from(nil) and to(nil) do not. Even though the context enforces the variable to be an edge the sanity checking does not take this into account (it does not inspect the context constraints when rejecting the sub-term).

**Comment by NikolajBjorner** [comment]
will not support
