### ISSUE TITLE
What is the propagate-bv-bounds tactic supposed to do?

### ISSUE THREAD

**Issue by delcypher** [Z3Prover/z3#1054]
The description of the propagate-bv-bounds tactic is

```
propagate bit-vector bounds by simplifying implied or contradictory bounds.
```

So I thought I'd try this on a toy example.

```
(declare-fun a () (_ BitVec 8))
(assert (bvugt a #xfe))
(assert (bvult a #xff))
(apply (then propagate-bv-bounds) :print_benchmark true :print false)
```

It reports

```
(declare-fun a () (_ BitVec 8))
(assert (bvugt a #xfe))
(assert (bvult a #xff))
```

I was expecting this to be reduced to `(assert false)` because the bounds are contradictory.

Is this a bug or have I misunderstood the purpose of this tactic?

**Comment by wintersteiger** [comment]
This tactic currently supports only `bvule` and `bvsle`, see [here](https://github.com/Z3Prover/z3/blob/master/src/tactic/bv/bv_bounds_tactic.cpp#L194), so this example works:

```
(declare-fun a () (_ BitVec 8))
(assert (bvule #xff a))
(assert (bvule a #xfe))
(apply (then propagate-bv-bounds) :print_benchmark true :print false)
```

The `simplify` tactic will rewrite everything into `bvule`/`bvsle` form; just run it before running `bv-bounds-propagate`:

```
(apply (then simplify propagate-bv-bounds) :print_benchmark true :print false)
```

**Comment by delcypher** [comment]
@wintersteiger Thanks for clarifying!

**Comment by delcypher** [comment]
@wintersteiger Here's an example that might interest you

```
(declare-fun a () (_ BitVec 8))
(assert (bvule #xf0 a))
(assert (bvule a #x08))
(apply (then simplify propagate-bv-bounds))
```

Applying the tactics in this order does **not** produce `false`.

```
(goals                                         
(goal                                          
  (bvule #xf0 a)                               
  (= ((_ extract 7 4) a) #x0)                  
  (bvule ((_ extract 3 0) a) #x8)              
  :precision precise :depth 2)                 
) 
```

If I just apply `propagate-bv-bounds` then I get **false**

```
(goals
(goal
  false
  :precision precise :depth 1)
)
```

**Comment by NikolajBjorner** [comment]
The contracts of pre-processing tactics are generally not going to be rigid and not going to be confluent or exhibit other pleasing properties over other tactics. They are intended as best-effort. A few have properties, such as eliminating all occurrences of "distinct" or "implies", but these are the exception. We can improve the best-effort behavior based on useful applications for sure, but applications should not make assumptions on their scope.

**Comment by delcypher** [comment]
@NikolajBjorner Okay. Thanks for clarifying
