### ISSUE TITLE
Toggling warning messages through the API

### ISSUE THREAD

**Issue by gavrilovmiroslav** [Z3Prover/z3#1055]
Toggling warning messages through the API seems not to work (via the `Z3_toggle_warning_messages` function of the C api). I am trying to hide the warning caused by `Z3_global_param_set` reading in an unknown key:

        Z3_toggle_warning_messages(FALSE);
        Z3_global_param_set("old_simplify.bv.hi_div0", "false");

Despite the fact that the warnings are toggled off, the message keeps appearing. Also, as I am dynamically loading this function from multiple versions of Z3, I can tell that it appears to not work in a very wide range of versions, from 2012, 2015 and 2017.

**Comment by NikolajBjorner** [comment]
It works for me from python.

    from z3 import *
    Z3_toggle_warning_messages(False)
    Z3_global_param_set("old_simplify.bv.hi_div0", "false")

vs.

    from z3 import *
    #Z3_toggle_warning_messages(False)
    Z3_global_param_set("old_simplify.bv.hi_div0", "false")

**Comment by NikolajBjorner** [comment]
Sometimes these kinds of things are in plain sight, e.g., is your macro "FALSE" defined to be 0?
