### ISSUE TITLE
Z3_goal API breaks invariant I expected to hold

### ISSUE THREAD

**Issue by delcypher** [Z3Prover/z3#1058]
This is a minor issue.

I was playing with Z3's goal API over the weekend and I noticed that an invariant I expected to hold wasn't.

I expected that when I add a formula to a goal (via `Z3_goal_assert()`) the number of formulas in the goal (as reported by `Z3_goal_size()`) to increment by one.

This does not appear to be the case. It seems that the goal eagerly modifies inserted formulas before any tactic is applied to it.

This is what I've observed so far.

* If the inserted formula is a logical `and`  it gets split into separate formula (i.e. the goal size is incremented by `n` for a `n-ary` logical `and`, instead of by 1).
* If `true` is inserted into the goal it is ignored (i.e. increment is 0).
* If `false` is inserted into the goal all existing formulas are removed from the goal and the goal will only contain `false`. Attempting to add more formulas to this goal from now on does nothing.

From the user's perspective I wasn't expecting this to happen. I was expecting Z3 to add the formulas I asked to be inserted into the goal verbatim. I was expecting these changes to be made once a tactic was applied to the goal, not before.

Either the behaviour of `Z3_goal`s needs to be change or it should be documented what `Z3_goal_assert()` will do. My guess is changing the documentation would be the better option.

**Comment by delcypher** [comment]
@NikolajBjorner Thanks. 4f04301 doesn't mention that if the goal contains `false` then adding additional formulas is a no-op.

**Comment by delcypher** [comment]
@NikolajBjorner Thanks. I think this can be closed.

**Comment by delcypher** [comment]
I'm re-opening because I hit another issue today. It seems Z3's tactic API also eagerly applies de-morgan.

Adding the following formula to a goal

```
(not (or A B))
```

ends up inserting two formulas into the goal

* `(not A)`
* `(not B)`

**Comment by wintersteiger** [comment]
To take the guesswork out of it: [this](https://github.com/Z3Prover/z3/blob/master/src/tactic/goal.cpp#L139) is what Z3 does. It splits the input assertion according to not/and/or, puts things onto it's own todo-list (`todo.push_back(...)`) and it actually adds the remainder to the goal (just `push_back(...)`). (There's also a `slow_process` for when proofs are enabled.)

**Comment by delcypher** [comment]
@wintersteiger Thanks. I took a look at the code. I think there's a latent bug there.

This code is weird https://github.com/Z3Prover/z3/blob/master/src/tactic/goal.cpp#L177

* `tmp_exprs` gets assigned to but is never used
* `curr` on this branch will be lost because we don't call `push_back()` on it.

I think this bug is hidden because of this guard `(!m().is_and(f) && !(m().is_not(f) && m().is_or(to_app(f)->get_arg(0))))`.

Either way I guess I need to adjust the documentation on `Z3_goal_assert()` to also document this behaviour.

**Comment by NikolajBjorner** [comment]
It is subtle; tmp_exprs is used to retain reference counts. A fresh negation may get created but not used.
When curr is not pushed it is assigned to the output parameter 'f'. Documentation to be updated.

**Comment by delcypher** [comment]
> It is subtle; tmp_exprs is used to retain reference counts. A fresh negation may get created but not used.

That is subtle! Thanks for adding the additional documentation.
