### ISSUE TITLE
Questions on Z3.Model, get the value of variables one by one

### ISSUE THREAD

**Issue by gingeredder** [Z3Prover/z3#1059]
There are several consts in the model of Z3, and I can get the number through using the interface "get_num_consts". 
For example, a sample model is like,
"(define-fun c () Int 0)
(define-fun y () Int 0)
(define-fun r Int 0)
(define-fun x () Int 1)".
Now how could traverse all these consts in the model, and get the specific value for each const. (for example, get them one by one, and evaluate x to be 1)?

**Comment by wintersteiger** [comment]
This depends on the API (and language) you are using, but the rough idea is to get the function declaration of the constant, which is then used to index into the model. In C this is done via `Z3_model_get_const_interp`, which takes a `Z3_func_decl` as the last argument, that can be obtained via `Z3_model_get_const_decl`, taking an integer index. 

```
unsigned n = Z3_model_get_num_consts(...);
for (unsigned i = 0; i < n; i++) {
    Z3_func_decl fd = Z3_model_get_const_decl(..., i);
    ... Z3_model_get_const_interp(..., fd);
}
```

**Comment by gingeredder** [comment]
THX
