### ISSUE TITLE
SMTLib compliance: quotes for echo

### ISSUE THREAD

**Issue by LeventErkok** [Z3Prover/z3#1062]
Page 67 of http://smtlib.cs.uiowa.edu/papers/smt-lib-reference-v2.6-draft-3.pdf says:

> `(echo s)` where s is a string literal, simply prints back s as is—including the surrounding
> double-quotes.

Strictly speaking, z3 is violating this as it does not print the surrounding quotes. I think the motivation is that the output of all commands are valid s-expressions, and putting the quotes would ensure this invariant is always held.

Perhaps not the most important detail, but would be good to be compliant in this case as well.

**Comment by NikolajBjorner** [comment]
added quotes

**Comment by LeventErkok** [comment]
Thanks, works per the spec now.

**Comment by wintersteiger** [comment]
Breaks applications, will need refinement.
