### ISSUE TITLE
Strange result for problem with explicit to_int and to_reals

### ISSUE THREAD

**Issue by jawline** [Z3Prover/z3#1063]
When executing the query below, which is based on SMT designed to truncate a real to X DP, I get the output 

```
sat
(model 
  (define-fun y1 () Int
    15043231)
  (define-fun y2 () Real
    1504323.0)
  (define-fun x () Real
    (/ 940201957.0 6250000.0))
)
```

where I would expect 1504323.1 as I've coerced y1 into a real before dividing it. Why is this.

(Additionally - Is there a standard way to get a real to n DP or SF)

```
(declare-fun x () Real)
(declare-fun y1 () Int)
(declare-fun y2 () Real)

(assert (= y1 (to_real (to_int (* x (^ 10 5))))))
(assert (= x 150.43231312))
(assert (= y2 (div (to_real y1) 10.0)))

(check-sat)
(get-model)
```

**Comment by wintersteiger** [comment]
Could it be that the Real/Int types got mixed up a little here? E.g., `(= y1 (to_real ...` suggests that `y1` should be a Real, but it's an Int. By default, Z3 is lenient about that and it will coerce the types silently; it will be strict and complain about type mismatches when `(set-option :smtlib2-compliant true)` is added though.

**Comment by NikolajBjorner** [comment]
Note that Div adds implicit coercions to_int. Use / to get division over reals.

**Comment by jawline** [comment]
Awesome - swapping to / fixes the issue, I didn't realise / and div where different functions. Thanks for the tip to disable implicit type coercion.

Is there any better way that an approach like this to truncate or round a Real to X decimal places. This works well for Int only examples but seems a bit hacky.

**Comment by wintersteiger** [comment]
If it's just about the precision of model values, [Z3_get_numeral_decimal_string](http://z3prover.github.io/api/html/group__capi.html#gaf8e1ec34d62bb2c45a8aa7394593d7fb) would do the trick.

Z3 also supports floating-point numbers and bit-vectors that are easily rounded or truncated. Whether it makes sense to use those and whether they would perform well, depends on your application of course.

**Comment by jawline** [comment]
Ah - unfortunately we're mocking a library function (Number.toFixed) so Z3_get_numeral_decimal_string isn't really what we need.

Perhaps we'll move to FPA in the future.

Thanks
