### ISSUE TITLE
get-unsat-assumptions behaving incorrectly when :produce-unsat-cores is present

### ISSUE THREAD

**Issue by LeventErkok** [Z3Prover/z3#1065]
There seems to be an unintended interaction between `get-unsat-assumptions` and `:produce-unsat-cores`.

Consider this:

```
(set-logic QF_BV)
(set-option :produce-unsat-assumptions true)
; (set-option :produce-unsat-cores true)
(declare-const s0 Bool)
(assert (! false :named |absurd|))
(check-sat-assuming (s0))
(get-unsat-assumptions)
```

Note the commented out line for producing unsat cores, on line 3. Z3 *correctly* produces the following response:

```
unsat
()
```

The subset is empty because the constant `s0` really has nothing to do with the unsatisfiability of the problem. This is perfectly fine.

However, if I uncomment line 3 leaving everything else the same, z3 says:

```
unsat
(absurd)
```

Strictly speaking this is incorrect, since `get-unsat-assumptions` should always return a subset of the literals specified in `check-sat-assumptions` according to the spec:

> (get-unsat-assumptions) returns a subset a1, . . . , an of the assumptions in the most recent
> check-sat-assuming command. These assumptions are such that issuing the command
> (check-sat-assuming (a1 · · · an)) instead would have still produced an unsat response.
> The returned sequence is not required to be minimal.

Clearly, `(absurd)` is not a subset of `(s0)`. So this behavior does not seem to be SMTLib compliant.

It also appears that there must be a named assertion that causes the `unsat` for this behavior to exhibit itself. If I remove the name `absurd` on line 5, the problem goes away as well.

I suppose a simple fix would be to walk through the final output and filter out anything that wasn't in the last call to `check-sat-assuming`, provided that is the only issue here and there are no other unwanted interactions.

**Comment by wintersteiger** [comment]
Thanks for reporting this issue. I totally agree with you, we should clean that up. I'll check what exactly the standard says about this, but it should be easy to fix in any case.

**Comment by NikolajBjorner** [comment]
change reverted. It breaks cores in general.
I am inclined to say it is a won't fix because it is a question on what produce-unsat-cores means when it gets enabled.

**Comment by LeventErkok** [comment]
Thanks for looking into this @NikolajBjorner.

The suggestion was to simply filter the output as you print the response for `get-unsat-assumptions`, as opposed to any other internal change. A mere filtering before the output is sent back to the user, without changing anything else internally. Even that is problematic?

**Comment by NikolajBjorner** [comment]
I realize this. I don't have a direct handle on the assumptions by the time this call is made, so it amounts to adding some structures for this. That can end up being buggy.

**Comment by LeventErkok** [comment]
I see.. I do have a work-around on my side, so it's not a big deal then.

Do you think the interaction between `produce-unsat-cores` and `get-unsat-assumptions` is worthy of a discussion at the SMTLib level?

I'll close this ticket in any case.
