### ISSUE TITLE
End of assertion replaced by "..."

### ISSUE THREAD

**Issue by YutanpoFR** [Z3Prover/z3#1072]
Dear all,

I am using the Python Z3 API for solving path problems.  

I have a huge list of constraints, and when I want to log the assertions before solving, I have for example :

`[x1 + x2 + x3 + x4 + ... = 1, And(And(Implies(y1 == 1, y1 > 0),Implies(y1 > 0, y1 == 1)), ...)] `
There are 129 elements before the first `...`, 69 before the second, and a lot are supposed to be logged after them.
Why such choice ? Is it possible to force Z3 to log all of the assertions ?

Thank you very much.
Best regards,

Yutanpo

**Comment by NikolajBjorner** [comment]
You can either set the printing parameters from Python. See the file z3pringer.py and look for the options to Formatter. Use the function set_pp_option to set the depth. e.g., set_pp_option("max_depth", 10000000)  and possibly "max_args" and "max_visited".
You can also use the function sexpr() defined on expressions to print the expression in the SMT2 format.

**Comment by YutanpoFR** [comment]
Nikolaj Bjorner, thank you for your reply.

By looking at z3printer.py I could see, indeed, that it prints `...` (ellipses in the code) if `d > self.max_depth or self.visited > self.max_visited`
So I set both max parameters to 1 000 000, I am now stuck with 200 lines printed, that seems to be an attribute of PP : 
`class PP:
    def __init__(self):
        self.max_lines  = 200` 
I thus also set this parameter to 1 000 000.

Now, in total 11079 lines are printed, 40 of them are those `...`

11039 items are way more than enough for logging, so I consider this issue as solved.

Thank you again.
