### ISSUE TITLE
Z3 returns with Killed on this floating-point query

### ISSUE THREAD

**Issue by zvonimir** [Z3Prover/z3#1074]
Here is a simple query on which Z3 (release 4.5.0) returns with `Killed` message on Linux:
```
(declare-fun %lbl%+36 () Bool)
(declare-fun dr@0 () (_ FloatingPoint 11 53))
(declare-fun d () (_ FloatingPoint 11 53))
(declare-fun %lbl%@64 () Bool)
(declare-fun %lbl%+40 () Bool)
(push 1)
(assert (not
(let ((|anon0#1_correct|  (=> (! (and %lbl%+36 true) :lblpos +36) (=> (fp.eq dr@0 (fp.div RNE d (fp (_ bv0 1) (_ bv1025 11) (_ bv2251799813685248 52)))) (! (or %lbl%@64 false) :lblneg @64)))))
(let ((PreconditionGeneratedEntry_correct  (=> (! (and %lbl%+40 true) :lblpos +40) |anon0#1_correct|)))
PreconditionGeneratedEntry_correct))
))
(check-sat)
```
It seems to be something related to the floating-point division or floating-point constants. Thoughts?
Thanks!

**Comment by LeventErkok** [comment]
I cannot reproduce this. I wrapped around a `(set-option :produce-models true)` and added a `(get-model)` at the end. With a freshly-built z3 out of github, I get:

```
$ time z3 a.smt2
sat
(model
  (define-fun dr@0 () (_ FloatingPoint 11 53)
    (fp #b0 #b00000000000 #x008415bc81608))
  (define-fun %lbl%+40 () Bool
    true)
  (define-fun %lbl%+36 () Bool
    true)
  (define-fun d () (_ FloatingPoint 11 53)
    (fp #b0 #b00000000000 #x0318826b08430))
  (define-fun %lbl%@64 () Bool
    false)
)
z3 a.smt2  88.78s user 1.28s system 99% cpu 1:30.33 total
```

I haven't checked the validity of the output, but it surely isn't dying at least. I'm running on Mac OSX, if that matters.

**Comment by NikolajBjorner** [comment]
It hogs a *lot* of memory. Not safe for 32 bits.

**Comment by delcypher** [comment]
@zvonimir  I don't run into any problems running this benchmark on Linux using the latest Z3 build (d8a02bc0400e08786132779d1c81607cbc2109bb)

**Comment by wintersteiger** [comment]
Looks like `fp.div` explodes into space. In general, floating-point division is super expensive in terms of both, time and space, but in this particular case we may be able to do something against it. For instance, replacing `check-sat` with `(check-sat-using (then simplify fpa2bv propagate-values smt))` solves the problem quickly, but this is probably not a long-term solution.

**Comment by zvonimir** [comment]
Interesting. Is there an option we could pass to Z3 to achieve the same effect (instead of changing `check-sat`)?
Changing `check-sat` is not easy from Boogie, while passing an additional option to Z3 is trivial.

**Comment by wintersteiger** [comment]
Sorry, but I think at this time there's no way to do that via Boogie. Although it would probably be easy to add a flag/option to Boogie to make `check-sat-using` available.

**Comment by NikolajBjorner** [comment]
It saves replacing strings in files. Maybe a more general plan is to allow plugging in tactics to asserted_formulas preprocessing, but it's value depends on use cases.

**Comment by wintersteiger** [comment]
... and replacing strings in files that are never saved or otherwise modifiable, e.g. via Boogie or F*.

**Comment by NikolajBjorner** [comment]
Agree

**Comment by NikolajBjorner** [comment]
Note that there is now an option z3.exe tactic.default_tactic="(then simplify smt)".
