### ISSUE TITLE
Adding support for printing a query in DIMACS format

### ISSUE THREAD

**Issue by delcypher** [Z3Prover/z3#1075]
Recently a user (@awanish-pandey) of [klee](https://github.com/klee/klee) enquired about outputting queries (in the QF_ABV logic) in the [DIMACS format](http://www.domagoj-babic.com/uploads/ResearchProjects/Spear/dimacs-cnf.pdf).

Given that KLEE uses Z3 as one of its solvers I was wondering if it would possible to do this via Z3.

I had a quick grep through Z3's codebase and noticed that internally this is already supported in two places.

* [In the SAT solver](https://github.com/Z3Prover/z3/blob/5066bd01f799e8a7f2af006f205de0c0847bdeee/src/sat/sat_solver.cpp#L2912)

* [On Goals](
https://github.com/Z3Prover/z3/blob/5066bd01f799e8a7f2af006f205de0c0847bdeee/src/tactic/goal.cpp#L431)

I was wondering if it would be possible to expose this functionality from the C API, and if yes how this should be done.

A problem that immediately comes to mind is that assertions might not even be reducible to a SAT problem so if a new function was added to the C API it would need to deal with this case in some way.

One place this could go is as a function `Z3_goal_to_dimacs_string()` that operates on a goal and produces the string iff the goal is already in CNF form, otherwise raise the API error handler. This would require that the client apply the necessary tactics to get the problem into CNF first, this would also require a `is-cnf` probe to be implemented so that the client knows when they can use `Z3_goal_to_dimacs_string()` without raising an error.

This would probably quite cumbersome and error prone though so a function `Z3_solver_to_dimacs()` string could be implemented instead that applies the necessary tactics internally and just returns an empty string if the problem cannot be reduced to SAT.

Any thoughts?

@awanish-pandey if the Z3 developers seem keen on the idea maybe you could invest some time to work on this? If the C API function gets implemented I can implement the necessary parts in KLEE very easily.

**Comment by NikolajBjorner** [comment]
My immediate reaction is as follows: 
Since DIMACS only works for propositional problems it would not work with arrays unless you Ackermanize them. Once a goal is in CNF writing the serializer is standard and does not require
internal Z3 functionality. So between the DIMACS being so special purpose and that we seem to expose sufficient tactics I would suggest to have them outside. Should we miss a tactic or probe, then we could add it based on use scenarios.

**Comment by delcypher** [comment]
@NikolajBjorner Thanks for the response.

This seems reasonable.

@awanish-pandey It looks like you will have to implement the functionality you want in KLEE itself. We don't use tactics explicitly in KLEE yet but I've started looking into it. To get you started you might want to take a look at https://github.com/klee/klee/pull/659 . This PR builds a solver using a custom tactic. You should extend the tactic to add steps to convert the problem to SAT and then to CNF. From there you can walk the AST to print in the DIMACS format.

**Comment by rainoftime** [comment]
@delcypher  I just add a tactic 
~~~~
// bv_to_cnf_tactic.h
#include"params.h"
class ast_manager;
class tactic;

tactic * mk_bv_to_cnf_tactic(ast_manager & m, params_ref const & p = params_ref());
tactic * mk_cnf_output_tactic(ast_manager & m, params_ref const & p = params_ref());
/*
  ADD_TACTIC("bv-to-cnf", "convert bv into CNF.", "mk_bv_to_cnf_tactic(m, p)")
  ADD_TACTIC("cnf-output", "Output CNF.", "mk_cnf_output_tactic(m, p)")
*/
~~~~

~~~~
// bv_to_cnf_tactic.cpp
#include"tactical.h"
#include"simplify_tactic.h"
#include"propagate_values_tactic.h"
#include"solve_eqs_tactic.h"
#include"elim_uncnstr_tactic.h"
#include"bit_blaster_tactic.h"
#include"max_bv_sharing_tactic.h"
#include"tseitin_cnf_tactic.h"
#include<iostream>
#include<fstream>

static tactic * mk_bv_to_cnf_preamble(ast_manager& m, params_ref const& p) {
    params_ref solve_eq_p;
    solve_eq_p.set_uint("solve_eqs_max_occs", 2);
    params_ref simp2_p = p;
    simp2_p.set_bool("som", true);
    simp2_p.set_bool("pull_cheap_ite", true);
    simp2_p.set_bool("push_ite_bv", false);
    simp2_p.set_bool("local_ctx", true);
    simp2_p.set_uint("local_ctx_limit", 10000000);
    simp2_p.set_bool("flat", true);
    simp2_p.set_bool("hoist_mul", false);
    return
           // You can customize this
            and_then(
                mk_simplify_tactic(m),
                mk_propagate_values_tactic(m),
                using_params(mk_solve_eqs_tactic(m), solve_eq_p),
                mk_elim_uncnstr_tactic(m),
                using_params(mk_simplify_tactic(m), simp2_p),
                mk_max_bv_sharing_tactic(m)
                );
}

static tactic * main_pp(tactic* t) {
    params_ref p;
    p.set_bool("elim_and", true);
    p.set_bool("push_ite_bv", true);
    p.set_bool("blast_distinct", true);
    return using_params(t, p);
}

// Interface
tactic * mk_bv_to_cnf_tactic(ast_manager& m, params_ref const & p) {
    tactic* preamble_st = mk_bv_to_cnf_preamble(m, p);
    tactic * st = and_then(main_pp(and_then(preamble_st, mk_bit_blaster_tactic(m))), mk_tseitin_cnf_tactic(m, p));
    st->updt_params(p);
    return st;
}

class cnf_output_tactic : public tactic {
    ast_manager&  m;
    params_ref    m_params;
public:
    cnf_output_tactic(ast_manager& m, params_ref const& p):
        m(m), m_params(p) {}
    virtual tactic * translate(ast_manager & m) {
        return alloc(cnf_output_tactic, m, m_params);
    }
    virtual void updt_params(params_ref const & p) {
    }
    virtual void collect_param_descrs(param_descrs & r) {
    }
    virtual void operator()(goal_ref const & g,
                            goal_ref_buffer & result,
                            model_converter_ref & mc,
                            proof_converter_ref & pc,
                            expr_dependency_ref & core) {
        g->display_dimacs(std::cout);
    }
    virtual void cleanup() {
    }
};

// Interface
tactic * mk_cnf_output_tactic(ast_manager & m, params_ref const & p) {
    return alloc(cnf_output_tactic, m, p);
}
~~~~

Now we can use them with C++ API
~~~~
tactic bvt2cnfout = tactic(ctx, "bv-to-cnf") & tactic(ctx, "cnf-output");
~~~~
