### ISSUE TITLE
Calling Z3_get_sort on a Z3_func_decl will crash Z3

### ISSUE THREAD

**Issue by delcypher** [Z3Prover/z3#1081]
This is a minor issue.

I recently observed the following from Z3's C API.

If I have a `Z3_func_decl` (e.g. `(declare x (_ BitVec 32))`) if I can convert this to a `Z3_ast` and request its sort Z3 will crash.

```c++
// Sketch of how to trigger crash
void test (Z3_func_decl fd, Z3_context ctx) {
  Z3_ast asAst = Z3_func_decl_to_ast(ctx, fd);
  // EDIT: original post incorrectly said `Z3_to_sort()`.
  Z3_sort sort = Z3_get_sort(ctx, asAst); // crashes
}
```

The issue appears to be that in the `get_sort(expr const * n)` function in `src/ast/ast.cpp` (around line 398) the switch case doesn't handle `AST_FUNC_DECL`.

In some ways this is probably to be expected because there are a separate set of APIs for getting the sorts for from a `Z3_func_decl` (i.e. `Z3_get_domain()` and `Z3_get_range()`). However it would be nice if Z3 handled the misuse of the API slightly more gracefully by calling the error handler. Alternatively it could just return what `Z3_get_range()` returns on the `Z3_func_decl` which is what I was initially expecting.

**Comment by wintersteiger** [comment]
Hmm, something's been lost in the sketching stage here it seems. `Z3_to_sort` is not actually an API function (currently?) and [`Z3_get_sort`](https://github.com/Z3Prover/z3/blob/master/src/api/api_ast.cpp#L557) does check that the argument is an expression (`CHECK_IS_EXPR(a, 0)`). 

I suppose you got `get_sort()` (in ast.cpp) to reach the `UNREACHABLE();` default case, which probably indicates a real bug; can you expand your sketch a bit further so we can see how you got it to do that?

**Comment by NikolajBjorner** [comment]
the CHECK_IS_EXPR sneaked in yesterday when fixing a different bug and I forgot I had made that fix when formatting the check-in message.

**Comment by wintersteiger** [comment]
Oh, I see! In that case, does this fix your problem @delcypher ?

**Comment by delcypher** [comment]
@wintersteiger 
> Hmm, something's been lost in the sketching stage here it seems. Z3_to_sort is not actually an API function (currently?) and Z3_get_sort does check that the argument is an expression (CHECK_IS_EXPR(a, 0)).

Oops sorry. That was a typo on my part it should have said `Z3_get_sort()` rather than `Z3_to_sort()`.

I'll try to write a self contained program to reproduce the issue.

**Comment by delcypher** [comment]
@wintersteiger 

Here is a standalone program that reproduces the crash

```c++
#include "z3.h"
#include <assert.h>
#include <stdlib.h>
#include <stdio.h>

extern "C" void errorHandler(Z3_context ctx, Z3_error_code e) {
  printf("Z3 error: %s\n", ::Z3_get_error_msg(ctx, e));
  abort();
}

int main() {
  Z3_config cfg = ::Z3_mk_config();
  Z3_context ctx = ::Z3_mk_context_rc(cfg);
  ::Z3_del_config(cfg);
  ::Z3_set_error_handler(ctx, errorHandler);
  // Parser simple query
  Z3_ast constraint =
      ::Z3_parse_smtlib2_string(ctx, "(declare-fun x () (_ BitVec 32))\n"
                                     "(assert (= x (_ bv0 32) ) )\n",
                                /*num_sorts=*/0,
                                /*sort_names=*/0,
                                /*sorts=*/0,
                                /*num_decls=*/0,
                                /*decl_names=*/0,
                                /*decls=*/0);
  ::Z3_inc_ref(ctx, constraint);
  printf("Loaded constraint: %s\n", ::Z3_ast_to_string(ctx, constraint));

  // Check top level expr is application
  assert(::Z3_is_app(ctx, constraint));

  // Get the application
  Z3_app asApp = ::Z3_to_app(ctx, constraint);
  unsigned numArgs = ::Z3_get_app_num_args(ctx, asApp);
  assert(numArgs == 2);

  // Get first arg
  Z3_ast firstArg = ::Z3_get_app_arg(ctx, asApp, 0);
  // Print first args
  ::Z3_inc_ref(ctx, firstArg);
  printf("first arg: %s\n", ::Z3_ast_to_string(ctx, firstArg));

  // Check that the first arg is an application
  assert(::Z3_is_app(ctx, firstArg));
  Z3_app firstArgasApp = ::Z3_to_app(ctx, firstArg);

  // Get Z3_func_decl of application
  Z3_func_decl fnDecl = ::Z3_get_app_decl(ctx, firstArgasApp);
  ::Z3_inc_ref(ctx, ::Z3_func_decl_to_ast(ctx, fnDecl));
  // Check fnDecl takes no arguments
  assert(::Z3_get_domain_size(ctx, fnDecl) == 0);

  // Get sort of fnDecl's range
  Z3_sort rangeSort = ::Z3_get_range(ctx, fnDecl);
  ::Z3_inc_ref(ctx, ::Z3_sort_to_ast(ctx, rangeSort));
  assert(::Z3_get_sort_kind(ctx, rangeSort) == Z3_BV_SORT);
  printf("first arg funcDecl range sort: %s\n", ::Z3_sort_to_string(ctx, rangeSort));

  // Now convert the funcDecl to an AST (legal) and ask its sort
  Z3_ast fnDeclAsAST = ::Z3_func_decl_to_ast(ctx, fnDecl);
  // FIXME: Z3 will crash when we ask for the sort of the fnDeclAsAST
  Z3_sort fnDeclAsASTSort = ::Z3_get_sort(ctx, fnDeclAsAST);
  ::Z3_inc_ref(ctx, ::Z3_sort_to_ast(ctx, fnDeclAsASTSort));
  // What should this be?
  assert(::Z3_get_sort_kind(ctx, fnDeclAsASTSort) == Z3_BV_SORT);

  // Clean up
  ::Z3_dec_ref(ctx, ::Z3_sort_to_ast(ctx, fnDeclAsASTSort));
  ::Z3_dec_ref(ctx, ::Z3_sort_to_ast(ctx, rangeSort));
  ::Z3_dec_ref(ctx, ::Z3_func_decl_to_ast(ctx, fnDecl));
  ::Z3_dec_ref(ctx, constraint);
  ::Z3_dec_ref(ctx, firstArg);
  ::Z3_del_context(ctx);
}
```

Note I'm currently using an old version of Z3 ( 1db07f1189d6560316537ec4822d41e84f0a7105 ). I'm upgrading now to test with the latest build.

**Comment by delcypher** [comment]
I've just tried on the latest build ( 78e8e8b89345417fd1209eee3c3b87504e34ae12 ). The custom Z3 error handler is now called instead of the unexpected crash.

The output is now

```
Loaded constraint: (= x #x00000000)
first arg: x
first arg funcDecl range sort: (_ BitVec 32)
Z3 error: invalid argument
Aborted (core dumped)
```

I consider this to be reasonable behaviour. Although shouldn't every AST have a valid sort?

**Comment by NikolajBjorner** [comment]
> Although shouldn't every AST have a valid sort?
Maybe. 
There are expressions, sorts and function declarations. 
Expressions have sorts, sorts are sorts themselves, and function declarations use domains and ranges, so what is the sort of that? Is it the range? then there is a function to access that.

The C API overloads the use of AST: it is used consistently for expressions. For sorts, the API uses the Z3_sort and for function declarations it uses Z3_func_decl. So there are many contexts where API functions take Z3_ast as input and expect these to be expressions. The Z3_get_sort is one of these functions. Other functions include those that apply functions to a list of arguments.

**Comment by delcypher** [comment]
> Maybe.

> There are expressions, sorts and function declarations.
Expressions have sorts, sorts are sorts themselves, and function declarations use domains and ranges, so what is the sort of that? Is it the range? then there is a function to access that.

Makes sense.

> The C API overloads the use of AST: it is used consistently for expressions. For sorts, the API uses the Z3_sort and for function declarations it uses Z3_func_decl.

That's not entirely true. For reference counting it seems I have to use `Z3_inc_ref()` and `Z3_dec_ref()` on `Z3_sort` and `Z3_func_decl` but to do that I have to convert them to the `Z3_ast` type first.

Maybe I shouldn't be doing that but there's nothing in the documentation to indicate otherwise.

> So there are many contexts where API functions take Z3_ast as input and expect these to be expressions. The Z3_get_sort is one of these functions. Other functions include those that apply functions to a list of arguments.

Perhaps this is just a documentation issue now? The current docs don't state that the pre-condition for use is that the `Z3_ast` kind not be `Z3_SORT_AST` or `Z3_FUNC_DECL_AST` or `Z3_UNKNOWN_AST`

**Comment by NikolajBjorner** [comment]
- Right, inc-ref and dec-ref rely on the ast conversion.

- There are rather many functions that take Z3_ast objects as arguments and we assume they are expressions. This isn't documented directly. The higher-level APIs get the separation in a more systematic way and can be used as guides. 
More to the point of usability, the C++ API is so much more convenient to use and resilient against low level errors. Only environments that can't or will not benefit from C++ should have to deal with the C API. As for documentation, improvements continuously remain possible.

**Comment by NikolajBjorner** [comment]
can we close this?

**Comment by delcypher** [comment]
@NikolajBjorner Sure.
