### ISSUE TITLE
some links in wiki are obsoleted

### ISSUE THREAD

**Issue by Ddnirvana** [Z3Prover/z3#1085]
Hi, guys, 
it seems that some links in the wiki page(link:`https://github.com/Z3Prover/z3/wiki/Slides`) like `Z3: An Efficient SMT Solver (PDF)` are obsoleted, the link address of `Z3: An Efficient SMT Solver (PDF)` is `http://research.microsoft.com/projects/z3/Z3_System.pdf`, and it just redirect to MS Research's home page now.....

**Comment by NikolajBjorner** [comment]
Thanks for reporting. This is fixed now.
