### ISSUE TITLE
Huge vector sizes in theory_str

### ISSUE THREAD

**Issue by wintersteiger** [Z3Prover/z3#1087]
In 32-bit mode, my VS compiler complains about potential loss of data:

```
C:\dev\z3\src\util\vector.h(61): warning C4244: 'argument': conversion from '__int64' to '::size_t', possible loss of data
C:\dev\z3\src\util\vector.h(58): note: while compiling class template member function 'void vector<int_vector,true,__int64>::expand_vector(void)'
C:\dev\z3\src\util\vector.h(315): note: see reference to function template instantiation 'void vector<int_vector,true,__int64>::expand_vector(void)' being compiled
..\src\smt\theory_str.cpp(9197): note: see reference to class template instantiation 'vector<int_vector,true,__int64>' being compiled
C:\dev\z3\src\util\vector.h(77): warning C4244: 'argument': conversion from '__int64' to '::size_t', possible loss of data
```

Because of this:

    vector<int_vector, true, long long> options;

(long long is 64-bit but all involved size_t's are 32-bit). Can we adjust that to size_t's, or is there a reason for having huge vectors even if the system won't be able to use them?

**Comment by wintersteiger** [comment]
@mtrberzi @NikolajBjorner any thoughts on this?

**Comment by NikolajBjorner** [comment]
The memory_manager uses size_t for memory allocation, so the only reasonable options to the template arguments for vector would be size_t or unsigned.

**Comment by wintersteiger** [comment]
@NikolajBjorner Yeah, that was my thinking too. I was quite surprised to see a long long there and I don't know whether other parts of the code depend on this.

**Comment by mtrberzi** [comment]
Right, `size_t` is really the only thing that makes sense here. I don't think anything else should depend on that. I'll check on the behaviour of this and make sure it still works as intended.

**Comment by NikolajBjorner** [comment]
thanks

**Comment by wintersteiger** [comment]
Awesome, thanks @mtrberzi !

**Comment by mtrberzi** [comment]
I ran tests with 64-bit GCC and this change didn't seem to affect anything. I'll keep an eye on it for a while but it should be okay, as expected. Do you want me to re-test with a 32-bit binary?

**Comment by wintersteiger** [comment]
Sounds good, thanks for checking! The CI and nightly builds will also run some tests, but I don't expect anything to fail there.
