### ISSUE TITLE
how to runing / use the z3 build .cpp and show the result?

### ISSUE THREAD

**Issue by xiaoleiuta** [Z3Prover/z3#1088]
I already install z3（4.5.1） on Ubuntu 17.04,  and I have an example.cpp file, I don't know how to compile this file and how to use z3.  I use some commands in terminal , z3 help/-h，it show me some message as follows:
Z3 [version 4.5.1 - 64 bit]. (C) Copyright 2006-2016 Microsoft Corp.
Usage: z3 [options] [-file:]file

Input format:
  -smt        use parser for SMT input format.
  -smt2       use parser for SMT 2 input format.
  -dl         use parser for Datalog input format.
  -dimacs     use parser for DIMACS input format.
  -log        use parser for Z3 log input format.
  -in         read formula from standard input.

Miscellaneous:
  -h, -?      prints this message.
  -version    prints version number of Z3.
  -v:level    be verbose, where <level> is the verbosity level.
  -nw         disable warning messages.
  -p          display Z3 global (and module) parameters.
  -pd         display Z3 global (and module) parameter descriptions.
  -pm:name    display Z3 module ('name') parameters.
  -pp:name    display Z3 parameter description, if 'name' is not provided, then all module names are listed.
  --          all remaining arguments are assumed to be part of the input file name. This option allows Z3 to read files with strange names such as: -foo.smt2.

Resources:
  -T:timeout  set the timeout (in seconds).
  -t:timeout  set the soft timeout (in milli seconds). It only kills the current query.
  -memory:Megabytes  set a limit for virtual memory consumption

I try  z3 -file example.cpp /  z3 example.cpp, there will show some errors:
I don't know how to use z3, please help me.
..............................
(error "line 2 column 0: invalid command, '(' expected")
unsupported
; c line: 3 position: 12
(error "line 3 column 14: invalid command, '(' expected")
(error "line 7 column 1: invalid bit-vector literal, expecting 'x' or 'b'")
(error "line 8 column 1: invalid bit-vector literal, expecting 'x' or 'b'")
(error "line 17 column 12: unexpected character")
(error "line 17 column 28: unexpected character")
unsupported
..........................

**Comment by NikolajBjorner** [comment]
Z3 doesn't take C++ files as input. 
For compiling example.cpp see the README files for instructions on how to do this.

Z3 takes mainly "smt2" files as input. 
There is an extensive set of smt2 files and documentation on http://smtlib.org.

**Comment by xiaoleiuta** [comment]
g++ -c example.cpp
g++ -o example example.o -lz3
./example
