### ISSUE TITLE
unable to handle nested data-type expression 

### ISSUE THREAD

**Issue by ederJohannes** [Z3Prover/z3#1092]
Hi,

trying to use the the Java api with z3 opt, I get an 
_unable to handle nested data-type expression (:var 1)_ 
exception using the following code:

> 

		HashMap<String, String> ps = new HashMap<>();
		ps.put("timeout", "10");
		Context context = new Context(ps);
		Params params = context.mkParams();
		params.add("priority", "pareto");
		Optimize solver = context.mkOptimize();
		solver.setParameters(params);

		EnumSort sourceSort = context.mkEnumSort("Source", "s1", "s2", "s3", "s4");
		EnumSort destinationSort = context.mkEnumSort("Destination", "d1", "d2", "d3", "d4");
		FuncDecl funcDecl = context.mkFuncDecl("f_allocate", sourceSort, destinationSort);

		Expr x = context.mkConst("x", sourceSort);
		Expr y = context.mkConst("y", destinationSort);
		Expr f_allocation = funcDecl.apply(x);

		BoolExpr equal = context.mkEq(f_allocation, y);
		Quantifier innerExists = context.mkExists(new Expr[] {y}, equal, 1, null, null, null, null);
		Quantifier forAll =
				context.mkForall(new Expr[] {x}, innerExists, 1, null, null, null, null);

		solver.Add(forAll);
		solver.Check();
		

If I use the non optimizing solver then everything works fine. 
If I use z3 from command line it works, too:

> 
		(declare-datatypes () ((Destination (d1) (d2) (d3) (d4))))
		(declare-datatypes () ((Source (s1) (s2) (s3) (s4))))
		(declare-fun f_allocate (Source) Destination)
		(assert (forall ((x Source)) (exists ((y Destination)) (= (f_allocate x) y))))
		(set-option :opt.priority pareto)
		(check-sat)

Am I doing something wrong or is this a bug?

**Comment by NikolajBjorner** [comment]
this was a bug in one of the tactics used in optimization mode.

**Comment by ederJohannes** [comment]
Now it works:) Thanks!
