### ISSUE TITLE
Unexpected result in Z3 Java library

### ISSUE THREAD

**Issue by daparpon** [Z3Prover/z3#1097]
Hi! I have a conflict caused by a specific satisfiability problem in Z3: when passed to the Java library of Z3 (most recent version), the result obtained is "UNKNOWN"; however, the result that I expected was unsat, so I tried it out in the web application at rise4fun and the binary executable, and both of them gave "UNSAT" as a result.

The input affected by the issue is packed in the following attached files, both in SMTLib format and in Java code:
[z3implicationJava.txt](https://github.com/Z3Prover/z3/files/1094442/z3implicationJava.txt)
[z3implicationSMTLib.txt](https://github.com/Z3Prover/z3/files/1094443/z3implicationSMTLib.txt)

I am completely blocked since I need this satisfiability problem to be solved in order for my application to continue its process. Thanks in advance for your help.

**Comment by wintersteiger** [comment]
I just ran the Java code using the latest master of Z3 and the 4.5.0 release and both of them correctly return unsat. Try printing the solver just before the call to `solver.check()` to see whether it does indeed contain the right assertions. Also, check whether any global or solver parameters are being set, e.g., setting a timeout that's far too small would have similar effects.

**Comment by daparpon** [comment]
I tried printing the solver and moving the resulting SMTLib code to the Z3 web application, and the result remains the same (the web prints "unsat" whereas the library returns "unknown"). I am using macOS, but I tried moving it to another machine running Linux and I got exactly the same result. The application does not alter the default functioning of Z3 in any way, it just creates the query and then asks the solver...

**Comment by wintersteiger** [comment]
The version of Z3 on rise4fun is very old, so I expect differences between that and the latest master. Which version of Z3 are you using exactly? (Check `z3 -h`).

**Comment by NikolajBjorner** [comment]
I also get unsat with the current master branch.
