### ISSUE TITLE
fp - fp.isNormal fails on +0

### ISSUE THREAD

**Issue by LeventErkok** [Z3Prover/z3#110]
```
(set-logic QF_FP)
(assert (fp.isNormal (_ +zero 8 24)))
(check-sat)
```

Using unstable branch head, I get:

```
unsat
```

The documentation is rather sparse on `fp.isNormal` but I do believe `+0` is a normal number. Is that not the case?

**Comment by wintersteiger** [comment]
No, I think +0 is not normal, I came across that recently and I remember changing the implementation for isNormal.

**Comment by wintersteiger** [comment]
See [semantics](http://smtlib.cs.uiowa.edu/papers/BTRW14.pdf), Table X. If I'm not misreading it, I think this means isNormal checks whether the number is in FN, i.e., exponent != 0 (Pg. 4, IV A).

**Comment by LeventErkok** [comment]
Ah, good point. This isn't the first time I'm confused about 0 not being considered a normal. Very counter-intuitive; but you're right that's the semantics. (I always think of normal/denormal as indicative of if I can count on the precision guarantee, but that doesn't apply for +/-0.)
