### ISSUE TITLE
Setting the timeout to 0 delivers an immediate timeout on Linux, but is ignored on Windows

### ISSUE THREAD

**Issue by 0xabu** [Z3Prover/z3#1100]
I noticed by accident that the behaviour of
```
(set-option :TIMEOUT 0)
```
differs on Linux and Windows Z3 binaries. On Windows, this becomes an infinite timeout, whereas on Linux it's really a zero timeout (every query is immediately cancelled). From a quick guess at the code, I think the Windows version behaves the way it does is because CreateTimerQueueTimer() is called with a period of zero, which means that it's a one-shot timer, and the first callback is ignored.

I noticed this because Boogie sets the timeout to zero by default if you don't specify one, and evidently they are expecting it to be infinite.

**Comment by delcypher** [comment]
@0xabu Which version of Z3 is this? I believe I raised this issue in #791 and it was resolved.

**Comment by 0xabu** [comment]
Oops, yes, I was only testing the 4.5.0 release binaries. Should have looked for a dup!
