### ISSUE TITLE
objective values and smt-lib compliance

### ISSUE THREAD

**Issue by LeventErkok** [Z3Prover/z3#1101]
This is prompted by #1062 actually. With the most recent commit of @wintersteiger I am now explicitly putting

 `    (set-option :smtlib2_compliant true)`

in my scripts, as otherwise the `echo` doesn't work as expected. I'm OK with this actually, since I'd like to keep everything SMT-lib compliant.

However, I hit an issue. Consider this input:

```
; (set-option :smtlib2_compliant true)
(set-option :print-success false)
(set-logic ALL)
(declare-fun s0 () Real)
(assert (> s0 0.0))
(maximize (- 1.0 s0))
(check-sat)
```

Z3 nicely responds:

```
sat
(objectives
 ((- 1.0 s0) (+ (to_real 1) (* (to_real (- 1)) epsilon)))
)
```
But if I uncomment the very first line to make it smt-lib compliant, I get:

```
success
sat
(objectives
 ((- 1.0 s0)(error "line 7 column 10: Sort mismatch at argument #2 for function (declare-fun * (Int Int) Int) supplied sort is Real")
```

I'm not sure if this is a bug: Perhaps this is understandable, as I guess objective-values/optimization etc. is not strictly smt-lib compliant.

_But you see my dilemma now: If I want smt-lib compliance, then I don't get optimization. If I don't set smt-lib compliance, then `echo` doesn't work._

Is there a happy medium we can create? Ideally, I'd like to keep the smtlib-compilant flag true, but I definitely don't want to lose optimization either.

Perhaps allow for optimization/epsilon etc. even in the smt-lib mode, via a specific set-option:

`(set-option :support_optimization true)`

If that's not feasible, what would you recommend as a potential solution?

**Comment by NikolajBjorner** [comment]
I can't push to GitHub right now so can't push an update for this. 
It amounts to ensuring that results from optimization are mono-typed.

   expr_ref context::to_expr(inf_eps const& n) {
        rational inf = n.get_infinity();
        rational r   = n.get_rational();
        rational eps = n.get_infinitesimal();
        expr_ref_vector args(m);
        bool is_int = eps.is_zero() && r.is_int();
        if (!inf.is_zero()) {
            expr* oo = m.mk_const(symbol("oo"), is_int ? m_arith.mk_int() : m_arith.mk_real());
            if (inf.is_one()) {
                args.push_back(oo);
            }
            else {
                args.push_back(m_arith.mk_mul(m_arith.mk_numeral(inf, is_int), oo));
            }
        }
        if (!r.is_zero()) {
            args.push_back(m_arith.mk_numeral(r, is_int));
        }
        if (!eps.is_zero()) {
            expr* ep = m.mk_const(symbol("epsilon"), m_arith.mk_real());
            if (eps.is_one()) {
                args.push_back(ep);
            }
            else {
                args.push_back(m_arith.mk_mul(m_arith.mk_numeral(eps, is_int), ep));
            }
        }
        switch(args.size()) {
        case 0: return expr_ref(m_arith.mk_numeral(rational(0), true), m);
        case 1: return expr_ref(args[0].get(), m);
        default: return expr_ref(m_arith.mk_add(args.size(), args.c_ptr()), m);
        }
    }

**Comment by LeventErkok** [comment]
Thanks @NikolajBjorner Looking forward to trying this out soon as you can push it!

**Comment by LeventErkok** [comment]
Thanks @NikolajBjorner That did make progress. But I hit another one that's quite similar. Here's the input:

```
(set-option :smtlib2_compliant true)
(set-option :print-success false)
(set-logic ALL)
(define-fun s3 () Real (/ 10.0 1.0))
(define-fun s6 () Real (/ 3.0 1.0))
(define-fun s8 () Real (/ 5.0 1.0))
(define-fun s10 () Real (/ 4.0 1.0))
(define-fun s13 () Real (/ 35.0 1.0))
(define-fun s15 () Real 0.0)
(define-fun s18 () Real (/ 6.0 1.0))
(declare-fun s0 () Real)
(declare-fun s1 () Real)
(declare-fun s21 () Real)
(define-fun s2 () Real (+ s0 s1))
(define-fun s4 () Bool (<= s2 s3))
(define-fun s5 () Real (- s0 s1))
(define-fun s7 () Bool (>= s5 s6))
(define-fun s9 () Real (* s0 s8))
(define-fun s11 () Real (* s1 s10))
(define-fun s12 () Real (+ s9 s11))
(define-fun s14 () Bool (<= s12 s13))
(define-fun s16 () Bool (>= s0 s15))
(define-fun s17 () Bool (>= s1 s15))
(define-fun s19 () Real (* s1 s18))
(define-fun s20 () Real (+ s9 s19))
(assert s4)
(assert s7)
(assert s14)
(assert s16)
(assert s17)
(assert (= s20 s21))
(maximize s21)
(check-sat)
```

This results in:

```
success
(objectives
 (s21  (interval (* (- 1) oo) oo))
)
(error "line 33 column 10: Sort mismatch at argument #3 for function (declare-fun + (Real Real) Real) supplied sort is Int")
```

Surprisingly, Z3 also fails to print `sat` as the response to `check-sat` here first, before printing the objectives. Not sure if the two issues are related.

If I comment out the very first line I get the expected output:

```
sat
(objectives
 (s21 (/ 355.0 9.0))
)
```

Note that it also correctly prints the `sat` in this case, which is somehow missing when compliance flag is set.

**Comment by wintersteiger** [comment]
Yes, the `echo` issue is a tricky. The problem is that Z3 had that command before it became an official SMT command and some applications use it to synchronize their Z3 output parsers, and if the strings don't match they will just keep waiting for the right string forever. We could add an additional command `echoq` or something like that, but I don't really like that either. And, the other way round, we can't really throw a useful error or deprecation message because we don't know what applications expect (except if smtlib2_compliant=true). I'd be happy to change the default behavior at the next major (4.6.?) release, but we would have to find a way to notify applications and developers about this change in some way.

**Comment by NikolajBjorner** [comment]
Lots of other things broke when I added quotes causing grief in regressions. I would say I now prefer Christoph's solution, which is to print quotes when smt2 mode is set.

**Comment by LeventErkok** [comment]
I'm perfectly happy with Cristoph's solution, though maintaining the invariant "everything is an s-expr" can save headache down the road. Note that Z3 also breaks that when it prints objectives for optimization related check-sat calls. You first get a `sat` then `objectives`, which is really two s-exprs. But that's not that hard to deal with as the user knows it'll happen, I suppose.

Of course, so long as the smt-lib compliant flag doesn't turn off features make things behave too erratically. Right now I'm blocked with https://github.com/Z3Prover/z3/issues/1101#issuecomment-310593059, but I'm hoping it'll be easy to resolve too?

**Comment by wintersteiger** [comment]
Should we maybe add a `(get-objectives)` command akin to `(get-model)`?

**Comment by LeventErkok** [comment]
I think that would be a good thing to do!

**Comment by NikolajBjorner** [comment]
this was in a different piece of code

**Comment by LeventErkok** [comment]
Fantastic. I'll close this ticket, and created a new one (https://github.com/Z3Prover/z3/issues/1107) regarding the possibility of adding a separate `(get-objectives)` command.
