### ISSUE TITLE
Unexpected result in floating-point constraint

### ISSUE THREAD

**Issue by martin2011** [Z3Prover/z3#1103]
Hi, it seems that an unsatisfiable floating-point constraint is checked to be sat. The constraint is as followed:
 a x a+b x b+c x c+d x d < 0
 and all the variables can not be infinite and NAN.

 The constraint is translated as the SMTLIB format as following file,  
[fp-smt220160623.txt](https://github.com/Z3Prover/z3/files/1097278/fp-smt220160623.txt)
with the last version Z3-4.5.1  and ubuntu12.04-64 bit,  I get a sat result.
Thanks.

**Comment by wintersteiger** [comment]
The problem encoded in the SMT file does not assert that the result of the expression is less than 0, instead it asserts that the result is less than `((_ to_fp 11 53) RTZ 1.0 -127)`, which is not the same as 0. If we replace it with an actual 0 then Z3 reports unsat as expected, but if we assert that it must be less than even the smallest positive floating point number `(fp #b0 #b00000000000 #x0000000000001)` then there is the trivial solution a=b=c=0.

**Comment by martin2011** [comment]
Thanks. However, zero is translated as:
```
double dval = 0.0;
expr ze = to_expr(z3ctx,Z3_mk_fpa_numeral_float(z3ctx,dval,double_sort));
```
, and `ze` is printed by calling `std::cout` as:
```
(fp #b0 #b01110000000 #x0000000000000)
```

Further, all the consraint in `solver` is printed by call `solver.to_smt2(..)` as the SMTLIB fromat file at the beginning, from which, I get zero is translated as `((_ to_fp 11 53) RTZ 1.0 -127)`. But, from your answer, that is not same as zero.

Thus, I would want to known where is  the fault, can not I use api 'Z3_mk_fpa_numeral_float()' to create the zero?

**Comment by martin2011** [comment]
It seems that I  misuse  the api and the correct api is  `Z3_mk_fpa_numeral_double( )`. I made a new experiment and  the result is `unsat` as expected. Thanks, @wintersteiger.

**Comment by wintersteiger** [comment]
Yes, we have to be careful about the types of floating-point numbers; one very small number may round to zero in one type, but not in another. For some commonly used types, the API provides convenient functions (like those for double precision).
