### ISSUE TITLE
Z3's behavior seems to depend on the order in which formulas are asserted

### ISSUE THREAD

**Issue by gowthamk** [Z3Prover/z3#1106]
Consider the following two queries:

1. [http://rise4fun.com/Z3/Rvu0](http://rise4fun.com/Z3/Rvu0)
2. [http://rise4fun.com/Z3/XiB6](http://rise4fun.com/Z3/XiB6)

Both are exactly same, except for the order in which the following assertion occurs in each ([vimdiff screenshot](https://imagebin.ca/v/3Qz6AkIWpk2c)):

    (assert (forall ((bv0 Loc)) (not (in bv0 empty))))

However, first one gets decided quickly, while Z3 times out (`-T:20`) on the second one. This is puzzling, considering that both queries are equivalent.

A related question: If I `(assert (not soundG_w))`, then both timeout. It'd be great to know what I can do to help Z3 decide this query.

Thanks in advance!

**Comment by NikolajBjorner** [comment]
Thanks for the example.

You can trigger the fickleness by playing with the random seed.


(smt.restarting :propagations 3868119 :decisions 1061232 :conflicts 68179 :restart 150 :agility 0.0460853)
(smt.restarting :propagations 3899808 :decisions 1062729 :conflicts 68330 :restart 225 :agility 0.0340952)
(smt.restarting :propagations 3910646 :decisions 1066017 :conflicts 68556 :restart 337 :agility 0.0700058)
(smt.restarting :propagations 3938471 :decisions 1075363 :conflicts 68938 :restart 150 :agility 0.0353228)
(smt.restarting :propagations 3957461 :decisions 1077376 :conflicts 69118 :restart 225 :agility 0.0353376)
(smt.restarting :propagations 3970404 :decisions 1079609 :conflicts 69344 :restart 337 :agility 0.0695742)
unknown

z3 diff.smt2 /v:1 smt.random_seed=5
sat

z3 diff.smt2 /v:1 smt.random_seed=6
sat

z3 diff.smt2 /v:1 smt.random_seed=7
(smt.restarting :propagations 37 :decisions 60 :conflicts 4 :restart 100 :agility 0.000399171)
sat

z3 diff.smt2 /v:1 smt.random_seed=8
sat

z3 diff.smt2 /v:1 smt.random_seed=9
(smt.restarting :propagations 31 :decisions 57 :conflicts 2 :restart 100 :agility 9.99e-05)
(smt.restarting :propagations 48 :decisions 107 :conflicts 2 :restart 100 :agility 0.000897873)
sat

As a workaround you can spawn different copies of Z3 in parallel with different random seeds 
For example:

(check-sat-using (par-or smt (with smt :smt.random_seed 1) (with smt :smt.random_seed 2)))

**Comment by gowthamk** [comment]
Thanks very much Nikolaj! Would also appreciate any help with my second question (timeouts with `(assert (not soundG_w))`).

**Comment by NikolajBjorner** [comment]
regarding the second question: the models it can find have soundG_w set to "true". By asserting it to false, the previous model cannot be used (and the formula may be unsat). Z3 is not able to either establish unsat or find a model in these cases.
