### ISSUE TITLE
Consider adding a `(get-objectives)` command

### ISSUE THREAD

**Issue by LeventErkok** [Z3Prover/z3#1107]
As discussed [here](https://github.com/Z3Prover/z3/issues/1101#issuecomment-310680676) and [here](https://github.com/Z3Prover/z3/issues/1101#issuecomment-310686584)

Currently when we have an optimization problem Z3 prints `sat` followed by `objectives`. It would be nicer to stick to one s-expr per response rule that SMTLib2 adheres to. Adding a new command `(get-objectives)` as suggested by @wintersteiger might be a better choice.

Note that this would also unify the behavior of `lexicographic`, `boxed` and `pareto` modes: The first two do print objectives, but the last one doesn't. By implementing `(get-objectives)` as a separate command, Z3 can properly respond to the first two and say something appropriate for the `pareto` case. Right now, the client software has to manage that explicitly.

**Comment by NikolajBjorner** [comment]
agree, it would be a more consistent design this way.

**Comment by LeventErkok** [comment]
Works perfectly! Thanks..
