### ISSUE TITLE
Would be nice to upgrade the tutorial version of z3

### ISSUE THREAD

**Issue by LeventErkok** [Z3Prover/z3#1108]
The version of z3 running the tutorials is rather outdated:

     http://rise4fun.com/Z3/Qy6

I believe 4.4.2 is at least 7 months old by now? It's really nice to be able to tell people about Z3 and point them to the rise4fun website to play around on the web, only to find out that the version there is getting rather stale.

**Comment by NikolajBjorner** [comment]
If only it were 7 months :-)

**Comment by LeventErkok** [comment]
My bad! I think it's at least 2 years old, if not more!

**Comment by NikolajBjorner** [comment]
done

**Comment by LeventErkok** [comment]
Hmm.. http://rise4fun.com/Z3/Qy6 still says 4.4.2; but maybe it takes a while to switch over?

**Comment by NikolajBjorner** [comment]
rather, it is accessing the cache, and then the updated binary isn't properly linked with dependent dlls so it silently does nothing.

**Comment by NikolajBjorner** [comment]
dlls are fixed now

**Comment by LeventErkok** [comment]
still says 4.4.2.. tried from multiple browsers.

**Comment by NikolajBjorner** [comment]
Add some spaces so it doesn't use cache

**Comment by LeventErkok** [comment]
wow, that worked:

```
(:version "4.5.1 - build hashcode 5714f830b03208d8d47717d22963a4a8395d8364")
```

awesome! thanks..
