### ISSUE TITLE
Wrong library name of java bindings on Linux

### ISSUE THREAD

**Issue by nhnb** [Z3Prover/z3#111]
Hi, 

Native.java tries to load a native library named "libz3java". This causes Java to look for a file name liblibz3java.so on disk. The file is named libz3java.so, so java does not find it.

Workaround: Renamed libz3java.so to liblibz3java.so.

**Comment by wintersteiger** [comment]
The build scripts change that string depending on the platform that Z3 is built on. So, this problem only appears when compiled Java code is transferred between platforms. This being Native.* I think it can stay this way, but I'll take a look later to see whether there's an easy, but more general approach to resolve this.

**Comment by nhnb** [comment]
Yes, I picked the .jar file and windows libraries from the binary download and compiled the Linux libraries. 

I think the .jar file should not be platform independent. Just copying both linux and windows libraries into the same folder usually works on Java.

**Comment by wintersteiger** [comment]
I've fixed this by simply looking for both names, I hope that will be robust enough to avoid these problems. Closing the issue as fixed.
