### ISSUE TITLE
Segmentation fault 11

### ISSUE THREAD

**Issue by ederJohannes** [Z3Prover/z3#1113]
Hi,
If I try to run the following query using the command line, I get a _Segementation fault: 11_.
Here is the the file that produces the seg fault: [example.txt](https://github.com/Z3Prover/z3/files/1101661/example.txt)
If I remove the optimization section, everything works fine.

**Comment by NikolajBjorner** [comment]
Commit 244cbc263831823096359f4745db259f6de5845b addresses the segmentation fault

**Comment by ederJohannes** [comment]
Thanks. Now the segamentation fault does not appear, however, as you mentined in the commit message, the problem is still not solved after letting it run for more than 2 hours. 

Removing the quantifier and unfolding it manually, the problem is solved within milliseconds.
[example2.txt](https://github.com/Z3Prover/z3/files/1105274/example2.txt)

I created this example using the Java API. However the Java API returns _unknown_ for this example, whereas the command line tool returns _satisfiable_. This may be related to issues #1112 and #1097.

**Comment by NikolajBjorner** [comment]
Generally speaking, the heuristics under optimization are not tuned for quantifiers.

**Comment by NikolajBjorner** [comment]
There is a big difference between finding some solution to your problem and finding an optimal solution. With optimization it tries to find optimal solutions. 
For a single objective the pareto option doesn't make any difference.

You can try different strategies for finding optimal solutions. Your problem reduces to maxsat. For this example, it seems that the wmax strategy works pretty well:

      z3 ex.smt2 /v:1 opt.maxsat_engine=wmax

finishes quickly.
