### ISSUE TITLE
A problem when get model for a SMT-OPT problem by Z3

### ISSUE THREAD

**Issue by gingeredder** [Z3Prover/z3#1118]
I encode a ite-branch as following:
"
(declare-fun flag () Bool)
(declare-fun x () Int)
(declare-fun y () Int)
(declare-fun z () Int)
(assert 
  (let ((a!1 (and (> 50 z)
                  (= y (+ x 1))
                  (= flag true)))
       )
  (let ((a!3 (and (>= z 50)
                  (= y (- x 1))
                  (= flag false)))
       )
  (and true
       (or a!1 a!3)))))
**(assert (>= x 0))**
(maximize y)
(check-sat)
(get-model)
"
I get the model like this :
"
y |-> oo
sat
(model 
  **(define-fun flag () Bool
    false)**
  (define-fun z () Int
    50)
  (define-fun y () Int
    (- 1))
  (define-fun x () Int
    0)
)
"
**Why the interpretation for declare-fun "flag" is "false"?**
I think it should be "true", because "true" corresponds the branch "y = x + 1", while "false" is for the branch "y = x - 1".
When I delete the assertion "**(assert (>= x 0))**" in the constraint, I get the model like this :
"
y |-> oo
sat
(model 
  (define-fun flag () Bool
    true)
  (define-fun z () Int
    0)
  (define-fun y () Int
    0)
  (define-fun x () Int
    (- 1))
)
"
The interpretation for flag is "true" now (This model fit my expection). But I think this assertion "(assert (>= x 0))" is independent for the model. Is this a bug?

**Comment by NikolajBjorner** [comment]
There is no bug. for flag = false, your constraints require y = x - 1, which is compatible with y = -1, x = 0.

**Comment by gingeredder** [comment]
For the object expression "maximize y", I think Z3 should choose "y = x + 1" instead of "y = x - 1" from those two branches "y = x + 1 \/ y = x - 1".
However, z3 gives the model with "y = 0, x = -1".

**Comment by NikolajBjorner** [comment]
last time I checked -1 + 1 = 0, so plugging in x = -1 and y = 0 works.

**Comment by gingeredder** [comment]
I mean for "max y s.t (y = x + 1 \/ y = x - 1)", we should get the branch "y = x + 1", instead of "y = x - 1".
Though, when x is unbounded (negative infinity to positive infinity), y is positive infinity for both two branches.
