### ISSUE TITLE
Problem with generatiny explanations in Datalog engine

### ISSUE THREAD

**Issue by Flei** [Z3Prover/z3#1122]
I have tried to coax some explanations out of the muZ datalog engine, but my attempts so far have been unsuccessful. To illustrate the issue, here is a short Python example adapted from the tutorial:

```
from z3 import *

fp = Fixedpoint()
fp.set(engine='datalog')
fp.set('datalog.generate_explanations', True)

a, b, c = Bools('a b c')

fp.register_relation(a.decl(), b.decl(), c.decl())
fp.rule(a,b, name='r1')
fp.rule(b,c, name='r2')
fp.fact(c)
print fp.query(a)
print fp.get_answer()
```

When run using z3 4.5.0 on macOS, it produces the following output:

```
Traceback (most recent call last):
  File "datalog.py", line 13, in <module>
    print fp.query(a)
  File "/usr/local/lib/python2.7/site-packages/z3/z3.py", line 6431, in query
    r = Z3_fixedpoint_query(self.ctx.ref(), self.fixedpoint, query.as_ast())
  File "/usr/local/lib/python2.7/site-packages/z3/z3core.py", line 4629, in Z3_fixedpoint_query
    raise Z3Exception(lib().Z3_get_error_msg(a0, err))
z3.z3types.Z3Exception: Rule contains infinite sorts in rule a!expl!2(#0) :- 
 b!expl!1(#1),
 (= (:var 0) (r1 (:var 1))).
```

I also tried previous releases on macOS and on GNU/Linux, but received the same results. I have no idea what to make of it without diving into the source code. Perhaps this is not a bug, but simply the result of my limited understanding. In any case, I would be immensely grateful if you could help with this issue.

**Comment by NikolajBjorner** [comment]
Indeed, this was a regression.
You get a slightly better format by replacing fp.fact(c) by fp.rule(c, name='c'))
