### ISSUE TITLE
qprofdiff is not part of release

### ISSUE THREAD

**Issue by tchajed** [Z3Prover/z3#1123]
I'd like `contrib/qprofdiff` to be included as part of the released source code so I can add it as an option to the Homebrew package for non-git installs.

**Comment by delcypher** [comment]
@tchajed What do you mean by "included as part of the released source code"? Do you mean you want the source code for `contrib/qprofdiff` to be in the tarball of the next stable Z3 release?

**Comment by wintersteiger** [comment]
The _source_ tarball of the next release will automatically contain it, because GitHub builds those files based on a commit or tag in the history and it includes everything.

**Comment by tchajed** [comment]
@wintersteiger: thanks, that answers my question. I didn't realize qprofdiff just didn't exist at the time of the last release.

@delcypher: yes, sorry for the ambiguity - I really meant "as part of the source tarball release", referring to [these releases](https://github.com/Z3Prover/z3/releases).

**Comment by tchajed** [comment]
Closing - when a new version of Z3 is released I'll start including qprofdiff in the Homebrew formula for non-git builds and it'll be included by default in `brew install z3`.
