### ISSUE TITLE
[TravisCI] Build not fully enabled?

### ISSUE THREAD

**Issue by delcypher** [Z3Prover/z3#1127]
https://travis-ci.org/Z3Prover/z3 currently says "This is not an active repository" yet we currently have working builds.

A quick google search shows other people have hit this

https://stackoverflow.com/questions/32022899/seeing-this-is-not-an-active-repository-for-an-active-repository

It sounds like the TravisCI hooks were manually enable from inside github rather than enabling it from within TravisCI. This likely means we don't have GitHub integration properly setup.

@NikolajBjorner @wintersteiger 

Based on the response in the stackoverflow post I think one of you need to go to https://travis-ci.org/ , click "sign in with GitHub" if not already signed in and then go to your profile (i.e. https://travis-ci.org/profile/NikolaBjorner or https://travis-ci.org/profile/wintersteiger ) and manually enable TravisCI for the `Z3Prover/z3` repository.

**Comment by NikolajBjorner** [comment]
Looks like it for some reason is taking only GitHub.com/nikolajbjorner/z3.git instead of GitHub.com/Z3prover/z3.git. I cleared a checkbox for enabling nikolajbjorner/z3 but not z3prover/z3. I have so far been unable to figure out how to tease travis to accept z3prover/z3 or whom I should impersonate (not surprising, as I tend to not navigate these kinds of systems too well).

**Comment by delcypher** [comment]
If you go to https://travis-ci.org/profile/NikolaBjorner hopefully you see something like this (see image below). This your TravisCI profile it will show your own personal repositories as well as the organizations you are a member of.

![image](https://user-images.githubusercontent.com/511795/27772361-603ab406-5f58-11e7-99a7-e34dae7f6890.png)

Notice how the organizations you are a member of appear on the left hand side (in my example image you can see I'm part of the KLEE organization). Click the `Z3Prover` organization and hopefully you'll be able to find the `z3` repository and enable TravisCI from there. If you don't see it click the "Sync Account" button.

If you still have problems you may have a permissions issue. It's been a few years since I enabled TravisCI for a repository that's part of an organization.

**Comment by NikolajBjorner** [comment]
The Z3Prover organization is missing from this list. I followed the link to "is an organization missing", and I get to GitHub. There the UI pretends that Z3 is included. Sorry. We'll figure it out somehow at some point. The current obstacle seems to be the bad landing page. The builds do get kicked off.

![image](https://user-images.githubusercontent.com/3085284/27772761-a45de21a-5f1d-11e7-9bae-4b0c59f3a8c3.png)

**Comment by delcypher** [comment]
> The Z3Prover organization is missing from this list.

You may need to press the "sync account" button on TravisCI (see the image in my previous comment. It shows up on your TravisCI profile and is around the top right of the page).

**Comment by delcypher** [comment]
>  Sorry. We'll figure it out somehow at some point. The current obstacle seems to be the bad landing page. The builds do get kicked off.

Yes the builds do kicked off but I think the PR integration might be missing too. When TravisCI is set up correctly any pull request against Z3 should trigger a build and the status of the build will show up in GitHub's user interface on the PR.

**Comment by NikolajBjorner** [comment]
finally, somehow, the right icons appeared so that I could enable them. The link from the main GitHub page now points to the latest build.

**Comment by NikolajBjorner** [comment]
BTW, I am setting auto-cancellation on. Seems redundant to build on every check-in.

![image](https://user-images.githubusercontent.com/3085284/27774047-b56aa8c0-5f3d-11e7-9598-d0e71830f377.png)

**Comment by delcypher** [comment]
@NikolajBjorner Thanks for fixing. Looks like its working properly now.
