### ISSUE TITLE
Z3 Optimize timeout and interrupt

### ISSUE THREAD

**Issue by MrWoffles** [Z3Prover/z3#1128]
I want Optimize using Z3 in C#. When i use context.MkSolver() to solve my problem i get a solution where there is no optimization and when i use context.MkOptimize() it takes really long to compute the optimal solution. When i use context.MkSolver() i can set a timeout parameter so the solver interrupts after some time. The timeout is working correct but i cant use the so far found solution because solver.Check() is UNKNOWN ... i also cant set this parameter with context.MkOptimize(). 

So my question now is how do i get the best solution so far after the timeout and how can i use this with MkOptimize ? Another Question i have is if i can Interrupt the Solver manually and then get the best solution so far

```
	using(Context context = new Context(new Dictionary<string, string>() { { "model", "true" } })) {
		var solver = context.MkSolver(); // i actually want to use MkOptimize() 
		Params p = context.MkParams();
		p.Add("timeout", 1000);
		solver.Parameters = p; // When MkOptimize => unknown parameter exception
		IntExpr x = context.MkIntConst("x");
		// ...
		solver.Check();
		solver.Model.Evaluate(x);
	}
```

**Comment by NikolajBjorner** [comment]
You could set the timeout on the global parameters. 
The "Interrupt" method on contexts should also work.

The Optimize mode does not support search customization that the Solver objects do.
In particular, optimization with quantified formulas is not so far a tested scenario.
