### ISSUE TITLE
fp - possible bug around conversions?

### ISSUE THREAD

**Issue by LeventErkok** [Z3Prover/z3#113]
[I think this one is quite similar to #77, which is already fixed but perhaps there're still some issues. I've tried to simplify the benchmarks below, but generated code makes it hard to get good test cases..]

I've two benchmarks, which are almost identical. Here's the first one:

```
(set-option :produce-models true)
(set-logic QF_FPBV)
(define-fun s10 () (_ BitVec 32) #x00000000)
(define-fun s2 () (_ FloatingPoint  8 24) ((_ to_fp 8 24) roundNearestTiesToEven (/ 4419341 8388608)))
(declare-fun s0 () (_ FloatingPoint  8 24))
(declare-fun s1 () (_ BitVec 32))
(assert
   (let ((s3 (fp.eq s0 s2)))
   (let ((s5 (fp.isInfinite s2)))
   (let ((s7 (not s5)))
   (let ((s9 ((_ fp.to_sbv 32) roundNearestTiesToEven s2)))
   (let ((s11 (ite s7 s9 s10)))
   (let ((s12 (= (bvcomp s1 s11) #b1)))
   (let ((s13 (and s3 s12)))
   s13))))))))
(check-sat)
(get-value (s1))
```

Here's the second one:

```
(set-option :produce-models true)
(set-logic QF_FPBV)
(define-fun s10 () (_ BitVec 32) #x00000000)
(define-fun s2 () (_ FloatingPoint  8 24) ((_ to_fp 8 24) roundNearestTiesToEven (/ 4419341 8388608)))
(declare-fun s0 () (_ FloatingPoint  8 24))
(declare-fun s1 () (_ BitVec 32))
(assert
   (let ((s3 (fp.eq s0 s2)))
   (let ((s5 (fp.isInfinite s0)))
   (let ((s7 (not s5)))
   (let ((s9 ((_ fp.to_sbv 32) roundNearestTiesToEven s0)))
   (let ((s11 (ite s7 s9 s10)))
   (let ((s12 (= (bvcomp s1 s11) #b1)))
   (let ((s13 (and s3 s12)))
   s13))))))))
(check-sat)
(get-value (s1))
```
For the first one, z3 says:

```
sat
((s1 #x00000001))
```

For the second, I get:

```
sat
((s1 #x00000000))
```

I do believe both of these benchmarks are essentially equivalent, and the `((s1 #x00000001))` model is the correct answer, while the `((s1 #x00000000))` answer satisfies neither.

Note that the difference between these benchmarks is simply the use of the variable `s0` and `s2` in the conversion and the call to `fp.Infinite`. And there's an explicit requirement in each that `s0` and `s2` must be the same floating-point value (see the boolean `s3`), which is the constant `0.5268265`, i.e., `(/ 4419341 8388608)`

The problem is essentially converting this value to a signed-32-bit vector, and I expect the result to be `1` with the `RNE` rounding mode. So, both benchmarks should produce `1`.

**Comment by wintersteiger** [comment]
Thanks for catching this one! There was indeed a bug in the rounding for to_sbv. Should be fixed now so I'm closing this issue.
