### ISSUE TITLE
Semantics of `Z3_OP_*_NO_OVFL`, `Z3_OP_*_NO_UDFL`, and `Z3_OP_*_I` operators

### ISSUE THREAD

**Issue by delcypher** [Z3Prover/z3#1132]
Some of Z3's operators are not documented.

I ran into an issue today where Z3's simplifier replaces `(bvurem ... ...)` with `(bvurem_i ... ...)` which my code doesn't expect.

I can see a whole family of operators that aren't documented, e.g.

```
Z3_OP_BSMUL_NO_OVFL,
Z3_OP_BUMUL_NO_OVFL,
Z3_OP_BSMUL_NO_UDFL,
Z3_OP_BSDIV_I,
Z3_OP_BUDIV_I,
Z3_OP_BSREM_I,
Z3_OP_BUREM_I,
Z3_OP_BSMOD_I,
```

What are the semantics of the operators I give above?

**Comment by wintersteiger** [comment]
Those were supposed to be internal to Z3 and not visible to users at all, but that was before we added tactics that produce them in their output. The _i on div/rem/mod means that it is the actual interpretation, when the divisor is non-zero, and there are separate operators for the div/0 case. The others are no overflow/underflow predicates. There are more supposedly internal ones I think and we won't be able to consistently hide them from the user, so we should really clean that up and document them properly.

**Comment by NikolajBjorner** [comment]
Good catch, yes they should be documented. 
The no-overflow operators have matching functions, such as Z3_mk_bvmul_no_overflow. 
We can't avoid for the internal operators to leak.

**Comment by delcypher** [comment]
@wintersteiger Thanks for the explaination.

@NikolajBjorner Thanks for documenting
