### ISSUE TITLE
Typing (sort-ing) error - bug or expected?

### ISSUE THREAD

**Issue by mschwerhoff** [Z3Prover/z3#1134]
Z3 4.5.1 nightly (1f29cebd4df6) rejects the following program with `unknown constant bar`:

```text
(declare-sort S1)
(declare-sort S2)
(declare-sort S3)

(declare-fun foo (Bool) S1)
(declare-fun foo (Bool) S2)

(declare-fun bar (S2 S2) Bool)
(declare-fun bar (S3 S3) Bool)

(declare-const s2 S2)
(declare-const b Bool)

(assert (bar s2 (foo b))) ;;; ERROR
```

I can see that the overloaded `foo` can give rise to type/sort ambiguities in general, but in this example, I would expect that, in the final `assert`, the type system concludes that `bar: S2 ⨯ S2 → Bool` and `foo: Bool → S2` are to be applied. Is Z3's behaviour expected or is this a bug in the type-checker?

I tried working around the apparent ambiguity using SMT2's `as` terms, but didn't succeed: it seems that only constants can be sort-annotated via `as`. Is there another solution/work-around other than renaming `foo` (e.g. to `fooS1` and `fooS2`)?

**Comment by NikolajBjorner** [comment]
Basically, overloading on user-defined functions is _not_ supported from the text-based front-ends. Overloading on range sorts is furthermore going to lead to ambiguity, and Z3's SMT front-end is not the right place to wrestle with such questions.

**Comment by NikolajBjorner** [comment]
Z3 should have raised an error for the second definition of foo.

**Comment by NikolajBjorner** [comment]
So yes, contrary to my recollection Z3 does allow overloading, but did not check for overlapping signatures (declarations of functions with the same domain, same name, but different range sorts).

**Comment by NikolajBjorner** [comment]
I guess I should re-read the fine manual some day as well.
Overload disambiguation is handled in SMT2 using the construct "as". Supply the range type S2 to fish out the appropriate version of foo:

    (assert (bar s2 ((as foo S2) b)))

**Comment by mschwerhoff** [comment]
I had tried using `as`, but apparently didn't get the syntax right. Thanks for looking into this so quickly, Nikolaj!
