### ISSUE TITLE
Java API, Z3Exception: canceled

### ISSUE THREAD

**Issue by ederJohannes** [Z3Prover/z3#1135]
Hi,

I have the following problem encoded with and without quantifiers. Both problems are satifisfiable using the command line tool.
File without quantifiers:
[example_noQuantifiers.txt](https://github.com/Z3Prover/z3/files/1128576/example_noQuantifiers.txt)
File with quantifiers:
[example_quantifiers.txt](https://github.com/Z3Prover/z3/files/1128578/example_quantifiers.txt)

However, i created those two problems using the java api, which throws an _Z3Exception: canceled_ using the optimizing solver, and _UNKNOWN_ with reason _canceled_, using the non optimizing solver. 
Here is the api log file for the non optimizing solver (without quantifiers): 
[z3 log file, non opt, no quantifier.txt.zip](https://github.com/Z3Prover/z3/files/1128582/z3.log.file.non.opt.no.quantifier.txt.zip)
and here for the optimizing solver (without quantifiers): 
[z3 log file, opt, no quantifier.txt.zip](https://github.com/Z3Prover/z3/files/1128585/z3.log.file.opt.no.quantifier.txt.zip)

Do I have to use any additional settings to make these to programs executable?

**Comment by wintersteiger** [comment]
"canceled" is usually reported when a timeout expires or when a ctrl-c signal is caught. Are you sure those are not the reason? Doing things via the Java API can take a different amount of time (either way, smaller or larger), so you could see a timeout being triggered in one case but not in the other.

**Comment by ederJohannes** [comment]
Thanks! That seemed to be the problem. I missed playing around with timeout values.

**Comment by wintersteiger** [comment]
Awesome, thanks for reporting back!

If timeouts are inconvenient, try the `rlimit` option. It sets a limit on the number of "basic operations" (our definition) instead of time, which is deterministic as long as the Z3 binary (and our definition of basic operations) doesn't change.
