### ISSUE TITLE
fp - float to Int64 conversion

### ISSUE THREAD

**Issue by LeventErkok** [Z3Prover/z3#114]
The following benchmark uses an admittedly convoluted way of converting the single-precision float number `0.5` to a signed 64-bit value, using round-nearest-ties-to-even-mode:

```
(set-option :produce-models true)
(set-logic QF_FPBV)
(define-fun s2 () (_ FloatingPoint  8 24) ((_ to_fp 8 24) roundNearestTiesToEven (/ 1 2)))
(declare-fun s0 () (_ FloatingPoint  8 24))
(declare-fun s1 () (_ BitVec 64))
(assert
   (let ((s3 (fp.eq s0 s2)))
   (let ((s9 ((_ fp.to_sbv 64) roundNearestTiesToEven s0)))
   (let ((s12 (= (bvcomp s1 s9) #b1)))
   (let ((s13 (and s3 s12)))
   s13)))))
(check-sat)
(get-value (s1))
```

Z3 says:

```
sat
((s1 #x0000000000000001))
```

i.e., z3 converts the value to `1`. I believe the correct result should be `0` in this rounding-mode.

**Comment by LeventErkok** [comment]
Data point: I tried this very benchmark with the latest release of MathSAT and it did indeed produce `0` as the result.

**Comment by wintersteiger** [comment]
Thanks for the test case! to_sbv was indeed off by a factor of 2. This is now fixed, so I'm closing this issue.
