### ISSUE TITLE
Speed Up obtained by using (push)

### ISSUE THREAD

**Issue by Anzhit** [Z3Prover/z3#1143]
Hi,

This issue is sort of related to [https://github.com/Z3Prover/z3/issues/1141](url) , but in my case the opposite effect is observed.
Using a push statement before the only check-sat in my problem instance results in a huge speed-up.

[q1.smt.txt](https://github.com/Z3Prover/z3/files/1141087/q1.smt.txt)
[q2.smt.txt](https://github.com/Z3Prover/z3/files/1141088/q2.smt.txt)

Instance without push q1.smt 
(:added-eqs                   150774137
 :binary-propagations         593104073
 :bv-bit2core                 14294038
 :bv-conflicts                743
 :bv-dynamic-diseqs           30675445
 :bv-dynamic-eqs              43354478
 :bv->core-eq                 43354478
 :conflicts                   1546690
 :decisions                   5854169
 :del-clause                  143534041
 :dyn-ack                     1
 :final-checks                10755
 :lazy-quant-instantiations   3933183
 :max-generation              12
 :max-memory                  60.26
 :max-missed-qa-cost          12.00
 :memory                      32.51
 :min-missed-qa-cost          11.00
 :minimized-lits              34216377
 :missed-quant-instantiations 152
 :mk-bool-var                 128558207
 :mk-clause                   143572213
 :num-allocs                  8577210355946.00
 :propagations                1829017958
 :quant-instantiations        24796746
 :restarts                    10
 :rlimit-count                3033569560
 :time                        1915.37
 :total-time                  1915.08)

With push q2.smt
(:added-eqs            41834813
 :binary-propagations  10
 :bv-bit2core          5556369
 :bv-conflicts         403
 :bv-dynamic-diseqs    9882544
 :bv-dynamic-eqs       11387698
 :bv->core-eq          11387698
 :conflicts            478654
 :decisions            543308
 :del-clause           79057372
 :final-checks         9
 :max-generation       10
 :max-memory           24.86
 :memory               24.47
 :minimized-lits       9432841
 :mk-bool-var          45966081
 :mk-clause            79078660
 :num-allocs           265825475758.00
 :num-checks           1
 :propagations         487529436
 :quant-instantiations 7241591
 :restarts             863
 :rlimit-count         854657486
 :time                 404.09
 :total-time           404.03)

The non-incremental solver should be faster than the incremental solver but in this case it is ~5X slower. I was able to observe similar slow-downs on modified problem instances of the ones attached.

Is this due to some kind of bug in Z3, or is there some way to optimise the non-incremental solver for my query so that it solves it in much faster time than the incremental solver.

**Comment by NikolajBjorner** [comment]
a 5x difference of runtime isn't out of the ordinary. You can get fluctuations by trying different values of the setting smt.random_seed=<integer>
