### ISSUE TITLE
Z3 exception "bad state" (inconsistent models detected)

### ISSUE THREAD

**Issue by martin-neuhaeusser** [Z3Prover/z3#1148]
When using an AllSMT algorithm based on blocking clauses, we sometimes experience a "bad state" exception from within Z3. It seems as if an incorrect model was generated by Z3 which is subsequently detected by the solver.

The attached two log files reproduce the problem. Sadly, they are rather long - I was unable to obtain something like a minimal example; the error only occurs rarely.

[z3_models.zip](https://github.com/Z3Prover/z3/files/1148948/z3_models.zip)

**Comment by wintersteiger** [comment]
Thanks, fixed! 

@NikolajBjorner: my fix probably wastes a little bit of time. I think we could instead just ignore the clauses in `m_entries` at `sat::model_converter::operator()` when the variable has been eliminated (except perhaps in debug mode).
