### ISSUE TITLE
Would be nice to have a new "release"

### ISSUE THREAD

**Issue by LeventErkok** [Z3Prover/z3#1149]
The github releases are really useful for hooking up to Travis and other continuous integration systems, where one can download a binary on the fly. Alas, the latest one is rather old: https://github.com/Z3Prover/z3/releases, dating back to Nov 2016.

Any chance a new one can be put there? It'd be perfectly OK to label it `_dev_snapshot` or some such, and better yet have a scheduled releases like that on a weekly/monthly basis perhaps?

**Comment by LeventErkok** [comment]
Never mind! I just found this: https://github.com/Z3Prover/bin/tree/master/nightly

Which is exactly what I wanted..

**Comment by wintersteiger** [comment]
Yep, that's exactly what the nightly binaries are for. We put more effort into the official releases (e.g. performance testing), so those are done at a lower frequency.

**Comment by LeventErkok** [comment]
@wintersteiger  Thanks! That seems like a good strategy..

In case anyone else is on the same boat and is trying to get `z3` on travis, here's my experience:

I added the following to my `.travis.yaml` file to get the ubuntu version downloaded/unpacked:

```
before_install
  - export Z3=`wget -q -O- http://github.com/Z3Prover/bin/raw/master/nightly | grep 'z3.*x64.*ubuntu.*.zip<' | awk '{print $7}' | awk -F= '{print $2}' | awk -F\" '{print $2}'`
  - export Z3Base=`basename $Z3 .zip`
  - wget --quiet -L -O z3.zip http://github.com/Z3Prover/bin/raw/master/nightly/$Z3
  - unzip -q z3.zip -d z3_downloaded
  - /bin/rm z3.zip
  - export PATH=$PATH:$PWD/z3_downloaded/$Z3Base/bin
  - z3 --version
```

This was quite tricky to get right: Note how there's a sequence of `awk`/`grep` tricks to precisely find the version to download, since your releases have hash-numbers on them and `wget` is kind of finicky about wildcards. To solve that issue, I did two calls to `wget`: One to get the directory listing, and second to find out the exact name of the `.zip` file I want. I wonder if there's an easier and more robust way to do this.

When I did that, it would unpack `z3`, put it in the path etc., correctly; but it actually would give me an error in the last line when I actually ran it:

     $ z3 --version
     z3: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.18' not found (required by z3)

After googling around a bit, I found that the ubuntu images for regular travis is rather old by now. But there's an easy fix. I put the following at the top of my `.travis.yaml` file:

```
dist: trusty
```
It appears `trusty` is Travis's new image, which is modernized and comes with other bells and whistles. I cannot claim I understand all the implications, but the above did the trick for me.

_**A suggestion:**_ The above seems to work; though a bit clunky. It would be awesome if you can create a nightly release with the following naming schema:

```    
     z3-nightly-latest-ubuntu-x64.zip
```

And you can imagine a similar one for other OS's and architectures. That way there would be no guess work nor any fancy `awk`-`grep` lines to grab the latest, without having to figure out what the hash-code is. This is by no means essential, but could be nice for future deployments.
