### ISSUE TITLE
wrong result

### ISSUE THREAD

**Issue by hdarwin** [Z3Prover/z3#115]
![q7](https://cloud.githubusercontent.com/assets/4065436/7916791/0a0e0c6c-08c1-11e5-83e7-a407e3b80a77.png)  
I wanted to solve above expression.  
```
#!/usr/bin/env python
from z3 import *
s = Solver()
t = Int('t')
c = 4 / t - 5 / (t + 3)
s.add(c == 1)
while s.check() == sat:
    m = s.model()
    [s.add(d() != m[d]) for d in m.decls()]
    print m
```
```
[t = -3]
[t = 2]
[t = 3]
[t = 4]
[t = -6]
[t = -7]
[t = -8]
[t = 0]
```
how can I get only true satisfiable result????

**Comment by LeventErkok** [comment]
@hdarwin 

There's really nothing wrong with Z3's answers here. First note that you're using 'Int', which has a well-defined division rule, but maybe not what you would expect. It's outlined here: http://smtlib.cs.uiowa.edu/theories-Ints.shtml#cl-52

In particular, division by 0 is underspecified, meaning that there is a model for every Int value as the result.

Under those assumptions, all the answers you get are actually valid solutions to the equation you posed.

If you want to solve this system "mathematically," you should be using the `Real` type and explicitly disallow for division-by-0 cases. The following seems to do the trick:

```
#!/usr/bin/env python
from z3 import *
s = Solver()
t = Real('t')
c = 4 / t - 5 / (t + 3)
s.add(c == 1)
s.add(t != 0)
s.add(t != -3)
while s.check() == sat:
    m = s.model()
    [s.add(d() != m[d]) for d in m.decls()]
    print m
```

I get:

```
[t = -6]
[t = 2]
```

which is I believe the results you were looking for.

**Comment by hdarwin** [comment]
@LeventErkok 
Thank you very much! that is what I want to know!
