### ISSUE TITLE
How to check `y != 0 && (((x-1) * y) % y) == 1` ？

### ISSUE THREAD

**Issue by snowingsea** [Z3Prover/z3#1153]
I know the expression `y != 0 && (((x-1) * y) % y) == 1` is unsat，but when i use z3 to check,  it can't stop. I use the code below:
```
#include "z3++.h"
#include "z3_api.h"
using namespace z3;

void z3_example() {
  context c;
  expr x = c.int_const("x");
  expr y = c.int_const("y");
  solver s(c);

  expr mod = to_expr(c, Z3_mk_mod(c, (x - 1) * y, y));
  s.add(y != 0);
  s.add(mod == 1);
  std::cout << s.check() << "\n";
}

int main() {
  z3_example();
  return 0;
}
```
Help, I don't know what's wrong with it.

**Comment by NikolajBjorner** [comment]
Nothing is wrong. Z3 is not a decision procedure for non-linear integer arithmetic. It makes a best effort to find a satisfiable solution or establish that the formulas are unsat. In this case it doesn't converge.
