### ISSUE TITLE
Z3Opt tutorial needs updating

### ISSUE THREAD

**Issue by domainexpert** [Z3Prover/z3#1154]
The Z3Opt tutorial in http://rise4fun.com/z3opt/tutorialcontent/guide still mentions that the optimization feature is in the unstable branch. It seems from https://github.com/Z3Prover/z3/branches, it has been merged to master.

**Comment by NikolajBjorner** [comment]
I have moved z3opt under the main Z3 tutorial as a section and also removed the "note".
http://rise4fun.com/Z3/tutorial/optimization
