### ISSUE TITLE
Constructors of globally defined data types are no longer in scope after pop

### ISSUE THREAD

**Issue by JTiko** [Z3Prover/z3#1155]
Hi,

I want to apply Z3 for solving simple equational constraints on algebraic data terms.
I also intend to solve the generated constraints incrementally using push and pop commands.
Hence, I declare the necessary algebraic data types first. Then, I introduce a new scope for a sequence of constraints and the required declarations. Afterwards I remove this scope and repeat this procedure for the next sequence of constraints.

But it seems that by removing a scope also global information is lost, namely the constructors of the globally declared data types.
For instance, consider the following sequence of SMT-LIB commands:

~~~
; <global algebraic data type declarations>
(push)
(declare-const xs (List Bool))
(assert (not (= xs (as nil (List Bool)))))
(check-sat)
(get-value (xs))
(pop)
(push)
(declare-const xs (List Bool))
(declare-const y Bool)
(declare-const ys (List Bool))
(assert (and (= xs ((as insert (List Bool)) y ys)) (not (= y false))))
(check-sat)
~~~

Running Z3 on that script, I receive the following outputs/errors:

~~~
sat
((xs (insert false nil)))
(error "line 26 column 48: unknown function/constant insert")
sat
~~~

The same problem occurs, whenever I try to use constructor terms of polymorphic algebraic data types (which are globally declared) after the first removal of a scope via pop.
For simple (monomorphic) types like Color (see below) everything works just fine.

~~~
(declare-datatypes () ((Color red blue yellow)))
~~~

Although the information on the constructors of polymorphic types seems to be lost after leaving a scope, the corresponding types are still globally visible. Any attempt to redeclare them, results in an error.

I use Z3 version 4.4.2 running the binary directly on an SMT-LIB script with the `-smt2` option.

**Comment by wintersteiger** [comment]
Just to make sure we're working on the same problem, could you add your datatype definition for the first example?

Here's a simple one that I think suffers from the same problem:

```
(declare-datatypes (T) ((Color red blue yellow)))

(push)
(declare-const c (Color Bool))
(assert (= c red))
(check-sat)
(pop)
(push)
(declare-const c (Color Bool))
(assert (= c blue))
(check-sat)
```

says

```
(error "line 10 column 13: unknown constant blue")
```

It works without the `T` though. @nbjorner could you take a look at this?

**Comment by JTiko** [comment]
For the first example I used the predefined list definition provided by Z3.
But here is the example from above using a self-defined maybe type instead of lists.

~~~
(declare-datatypes (T) ((Maybe nothing (just (fromJust T)))))
(push)
(declare-const xs (Maybe Bool))
(assert (not (= xs (as nothing (Maybe Bool)))))
(check-sat)
(get-value (xs))
(pop)
(push)
(declare-const xs (Maybe Bool))
(declare-const y Bool)
(assert (and (= xs ((as just (Maybe Bool)) y)) (not (= y false))))
(check-sat)
~~~

This results in:

~~~
sat
((xs (just false)))
(error "line 26 column 44: unknown function/constant just")
sat
~~~

**Comment by NikolajBjorner** [comment]
It's a bug in the way parametric sorts are instantiated. It doesn't work with scoping.
For the first declaration of 'c', it creates an instantiation for the sort parameter Bool, 
These instantiations are removed when popping the scope, but the data-type factory method doesn't "know" this so it doesn't re-create the terms.

**Comment by NikolajBjorner** [comment]
I believe this was fixed by the updates reported above.
