### ISSUE TITLE
z3 python not  working on windows

### ISSUE THREAD

**Issue by rrbarioni** [Z3Prover/z3#1165]
I have build z3 on linux, tested the script below and it worked. However, when I tried to run the same py script on windows, I got the following error:

![image](https://user-images.githubusercontent.com/13512712/28642707-b39fa014-7229-11e7-8332-857db73469be.png)

To build z3 on windows, I've done all steps described on readme:

$ python scripts/mk_make.py --python
$ cd build
$ nmake

The script is at "build/python/", and this is the code:

![image](https://user-images.githubusercontent.com/13512712/28642888-4aa727e8-722a-11e7-9003-575c7304f33b.png)

**Comment by NikolajBjorner** [comment]
Your python installation is probably for 64bit vs a 32 bit build or the other way around

**Comment by wintersteiger** [comment]
What @NikolajBjorner said, or your Python can't see libz3.dll at all, in which case you need to add the build directory to your PATH.

**Comment by rrbarioni** [comment]
Yeah, I installed python 32bit and it worked for me. Thank you!

**Comment by wintersteiger** [comment]
No problem, thanks for reporting back!
