### ISSUE TITLE
Make get-interpolant output smtlib compliant

### ISSUE THREAD

**Issue by LeventErkok** [Z3Prover/z3#1172]
This is in similar vein to making all output from Z3 be s-expressions:

```
(set-option :produce-interpolants true)
(declare-const a Int)
(declare-const b Int)
(declare-const c Int)
(declare-const d Int)
(declare-const e Int)
(assert (! (and (= a b) (= a c))       :named f1))
(assert (! (= c d)                     :named f2))
(assert (! (and (= b e) (not (= d e))) :named f3))
(check-sat)
(get-interpolant f1 f2 f3)
```

This produces:

```
unsat
(= b c)
(= b d)
```
Can we have it so that it actually produces:

```
unsat
(interpolants (= b c) (= b d))
```

I think it would be nice if the `interpolants` keyword was kept even if there was only one interpolant produced, i.e., when only two formulas are given to `get-interpolant`. In that case the output would look like:

```
(interpolants (= a b))
```

for instance. I'm not tied to the word `interpolants` in any way, in case there's a better choice!

**Comment by wintersteiger** [comment]
Makes sense to me! Not sure how much of a disruption that change would be for existing applications though.

**Comment by NikolajBjorner** [comment]
> 

> is case there's a better choice!
How about "dude" or "Nikolaj-Bjorner-is-super-amazing-and-here-is-your-interpolant-or-interpolants"?

**Comment by LeventErkok** [comment]
@NikolajBjorner I don't see why not :-)

But more seriously, I fixed the typo in my original message. Using `interpolants` as the only keyword, regardless there's one or many.

**Comment by LeventErkok** [comment]
@NikolajBjorner Thanks! Just tested. Works as advertised..

**Comment by LeventErkok** [comment]
Hmm, I spoke too soon! This isn't really Z3's fault, but for some queries I do get the following as the output:

```
(let ((a!1 (<= 0 (+ (div s1 2) (div (* (- 1) s1) 2)))))
  (interpolants a!1))
```

This is of-course a valid output, but it doesn't have the simple structure that I was expecting to see.

Is there a way to make sure the `let` is pushed inside? Something like:

```
(interpolants (let ((a!1 (<= 0 (+ (div s1 2) (div (* (- 1) s1) 2))))) a!1)
```

perhaps? This isn't the end of the world, but it would simplify life!

**Comment by NikolajBjorner** [comment]
It's a valid s-expression :-)

Sure, so I will print them without let nesting outside of "interpolants". The indentation will not be consistent, but that is mascara.

**Comment by LeventErkok** [comment]
Yes, that'd work really well! Thanks.

**Comment by LeventErkok** [comment]
Thanks for the quick fix! Works great!
