### ISSUE TITLE
OSX nightly build is failing

### ISSUE THREAD

**Issue by LeventErkok** [Z3Prover/z3#1175]
@wintersteiger 

I'm now relying on the nightly builds for testing against Z3, alas the Mac build is failing: https://github.com/Z3Prover/bin/tree/master/nightly

Any chance it can be revived? Seems to be a benchmark issue?

**Comment by wintersteiger** [comment]
Sorry, nightly builds will fail sometimes and they'll sometimes be unsound and untested, that's what they are for. Also, they are not CI builds (see Travis or VSTS builds for those,) If you need a stable build, please use the releases, or a commit that you trust. 

In this case, there were a couple of benchmarks that timed out. Most of the time they'll pass fine, but sometimes the build machine is busy and they exceed the timeout. The two that timed out tonight were floating-point problems, which is currently work in progress, so nothing to be concerned about.

**Comment by LeventErkok** [comment]
Thanks @wintersteiger 

I'm actually perfectly happy to have it a bit old. The thing is the "interpolant" change Nikolaj put in https://github.com/Z3Prover/z3/commit/c8b5be48de0ea38a26effc0a71b003af77d91a52 never got a released model, neither stable nor nightly and thus causing test issues when I want to test it on the Mac. Perhaps there's a button to say "it's OK" so we can get a binary built for nightlies?

**Comment by wintersteiger** [comment]
Sorry, don't understand your question? Who has a button that does what and when?

The nightly binaries run a set of tests and if they fail the binary won't get published. You can build your own binaries at any time, but we won't be able to provide cherry-picked binaries of different hashes for cherry-picked customers, sorry.

**Comment by LeventErkok** [comment]
I understand.. Sorry for the confusion. And looks like OSX build went thru and there's a viable recent package, so it's all good! Much appreciated.
