### ISSUE TITLE
[../src/math/realclosure/realclosure.cpp:4078: possible bad if test ?

### ISSUE THREAD

**Issue by dcb314** [Z3Prover/z3#118]
[../src/math/realclosure/realclosure.cpp:4078]: (style) Same expression on both sides of '&&'.

 if (!i.lower_is_open() && !i.lower_is_open()) {

Maybe

 if (!i.lower_is_open() && !i.upper_is_open()) {

**Comment by NikolajBjorner** [comment]
symmetry reinstantiated
