### ISSUE TITLE
Failed to run Z3 unit test module "heap" in test-z3.exe

### ISSUE THREAD

**Issue by KarenHuang2016** [Z3Prover/z3#1184]
We tried to build Z3 and run its unit tests on Windows. The unit test module "heap" in test-z3.exe failed to run from master branch revision b1298d7. Could you please take a look at this? Thanks in advance!

Environment: Windows Server 2016 + VS2017 Update 2
Reproduce steps:
1.git clone https://github.com/Z3Prover/z3 D:\Z3\src
2.Open a VS 2017 x86 command prompt and browse to D:\Z3\src
3.cd D:\Z3
4.mkdir build_x86 && pushd build_x86
5.cmake -G "Visual Studio 15" -DCMAKE_SYSTEM_VERSION=10.0.15063.0 ..\src
6.msbuild Z3.sln /p:Configuration=Release;Platform=Win32 /t:Rebuild /m /p:BuildInParallel=true
7..\Release\test-z3.exe heap

Actual result:
Failed to verify: t.contains(val)

**Comment by NikolajBjorner** [comment]
The test uses "rand()", without initialization, so the behavior may not be reproducible directly if there is a slight change in platform. I instrumented the unit test for heaps locally to run the tests in a loop with different seeds and I don't get a repro.

**Comment by NikolajBjorner** [comment]
Does this still repro?

**Comment by KarenHuang2016** [comment]
@NikolajBjorner, yes, it still repro on latest revision 05c4ea8.

**Comment by NikolajBjorner** [comment]
I am unable to repro this.

**Comment by wintersteiger** [comment]
Still repros on my machine:

```
nmake test
...
C:\dev\z3\bld_rel>test-z3.exe heap
Failed to verify: t.contains(val)
```

This is with VS2017 (preview), release x86.

**Comment by NikolajBjorner** [comment]
Congratulations. As a special reward, Can you look into it? 😀

**Comment by wintersteiger** [comment]
LOL! Sure, no problem. No ETA though :)

**Comment by NikolajBjorner** [comment]
@KarenHuang2016 Can you check if this is possibly a compiler bug? It only reproduces in release mode and only on VS2017 preview release x86. No other platforms.

**Comment by NikolajBjorner** [comment]
I was able to repro this with VS 2017.
I changed t from a hash table to a dense set to avoid the bug in 0de514a8849fccec762bd5483068fc724b7029a.

There is something strange going on with the int_hash table in release mode under VS2017. The contains check fails, even though the entry is in the hash-table.
