### ISSUE TITLE
Counterintuitive behavior with Algebraic Datatypes

### ISSUE THREAD

**Issue by ranjitjhala** [Z3Prover/z3#1186]
Hi all, 

I get this somewhat counterintuitive behavior when using datatypes.

The following file 

```
(declare-datatypes (T0) ((LL emp (con (lHead T0) (lTail LL)))))

(declare-fun e () (LL Int))

(assert (and (= (con 2 emp) (con 1 emp))))
(check-sat)
```

works fine, as in:

```
$ z3 adt.smt2 
unsat
```

But if I _remove_ the declaration, e.g. comment it out, 

```
; (declare-fun e () (LL Int))
```

then I get:

```
$ z3 adt.smt2 
(error "line 8 column 30: unknown constant emp")
sat
```

Am guessing the right thing to do is to use `as emp (LL Int)` 
(which works fine) but was lulled into a false sense of security 
by the earlier example which led me to think that z3 was doing 
some local inference to make the explicit cast unnecessary...

**Comment by NikolajBjorner** [comment]
there isn't any inference: when you introduce 'e', it also instantiates the datatype for the type (LL Int) with a version of "emp" of that type. For good measure you should _always_ use type disambiguation and not rely on ad-hoc inference.
