### ISSUE TITLE
MBQI looping

### ISSUE THREAD

**Issue by kenmcmil** [Z3Prover/z3#1187]
I'm seeing a case where MBQI produces instances that are true in the model, which leads to an infinite loop generating the same instances. Unfortunately, I can't reproduce this in an smt2 file. 

I'm printing both the model and the instances in stm_model_checker.cpp. The output looks like this:

MODEL_CHECKER INVOKED
model:

...

(define __ts0_a true)

...

(define __prm:V0 nodeord.t!val!1)

...

(define (server.impl.current_inst x!0)
  (if (= x!0 nodeord.t!val!1) (configarr.end (server.impl.history nodeord.t!val!1))
    (__server.impl.current_inst x!0)))

...

(smt.mbqi "started")
(smt.mbqi :failed null)
(smt.mbqi :failed null)
(smt.mbqi :num-failures 2)
(assert (let ((a!1 (ite __ts0_a
                (ite (= |__prm:V0| |__prm:V0|)
                     (configarr.end (server.impl.history |__prm:V0|))
                     (__server.impl.current_inst |__prm:V0|))
                (__server.impl.current_inst |__prm:V0|))))
  (= (server.impl.current_inst |__prm:V0|) a!1)))

...

The last formula is one of the added instances (the one quantifier has been instantiated with |__prm:V0|). If you plug in the model values for __ts0_a and |__prm:V0| and simplify the outer ite, you see that it exactly matches the definition of server.impl.current_inst in the model, so this formula should evaluate to true in the model. One thing I noticed is that removing the outer ite on condition __tso_a makes this bug go away, so the bug might be related to the ite. 

Any thoughts on where to start looking for this problem?

Thanks -- Ken

**Comment by kenmcmil** [comment]
Another clue is that this doesn't occur with the option 'smt.macro_finder' enabled.

**Comment by NikolajBjorner** [comment]
Can you create a log file? Before invoking any Z3 functions call Z3_open_log("kml.log") or something similar from your favorite language.
Another way to debug locally is to change the line:

            if (!ProofGen && constant_fold(t, fr)) {

line 735 in ast/rewriter/rewriter_def.h
to something like:

            if (!ProofGen && false && constant_fold(t, fr)) {

which disables special purpose handling of if-then-else rewriting. This gets invoked by the model evaluator.
