### ISSUE TITLE
partial function not working correctly (fp.to_ubv)

### ISSUE THREAD

**Issue by florianschanda** [Z3Prover/z3#1191]
Hi Christoph,

Attached is a test-case that I think Z3 gives the wrong answer on.

```
(set-info :smt-lib-version 2.6)
(set-info :license |https://www.gnu.org/licenses/gpl-3.0.html|)
(set-logic QF_FPBV)
(set-option :produce-models true)
(set-info :source |Florian Schanda|)
(set-info :category crafted)
(set-info :status sat)

;; converting two unspecified things that may not be the same, may
;; give different answers

(declare-const x Float32)
(assert (fp.leq x ((_ to_fp 8 24) RNE (- 1.0))))

(declare-const y Float32)
(assert (fp.leq y ((_ to_fp 8 24) RNE (- 1.0))))

(define-const bv_x_8 (_ BitVec 8) ((_ fp.to_ubv 8) RNE x))
(define-const bv_y_8 (_ BitVec 8) ((_ fp.to_ubv 8) RNE y))

(assert (distinct bv_x_8 bv_y_8))
(check-sat)
(exit)
```

The way I read the standard it implies that converting a negative number (which when appropriately rounded to an integer would still be negative) to a unsigned bitvector should be an uninterpreted function.

Hence the above should be satisfiable but Z3 thinks it is not.

**Comment by wintersteiger** [comment]
Yes, it's also implemented as uninterpreted, but it's the same UF for every combination of ebits, sbits and bit-vector width. I guess for the conversion function we'll have to add their arguments too.

**Comment by wintersteiger** [comment]
This is now fixed, thanks for reporting this issue.
