### ISSUE TITLE
Java bindings; Difference between isIff() and isEq()

### ISSUE THREAD

**Issue by proteusGIT** [Z3Prover/z3#1192]
Hey,

is there a specific difference between `isIff()` and `isEq()`?
It seems that they should have the identical behaviour?
This occurred to me when translating back some results from Z3 using the java bindings.

Best Regards

**Comment by NikolajBjorner** [comment]
There is a difference, but the reasons are not good: the predicate "iff" is defined for Booleans, the predicate "=" is defined for all sorts including Booleans. When "=" is used with Booleans it has the same meaning as "iff".
