### ISSUE TITLE
rounding on conversion to unsigned (fp.to_ubv, RNE)

### ISSUE THREAD

**Issue by florianschanda** [Z3Prover/z3#1193]
Hi Christoph,

```
(set-info :smt-lib-version 2.6)
(set-info :license |https://www.gnu.org/licenses/gpl-3.0.html|)
(set-logic QF_FPBV)
(set-info :source |Florian Schanda|)
(set-info :category crafted)
(set-info :status unsat)

(define-const x Float32 ((_ to_fp 8 24) RNE (- 0.5)))
(define-const y (_ BitVec 8) ((_ fp.to_ubv 8) RNE x))
(define-const z (_ BitVec 8) #x00)

(assert (distinct y z))
(check-sat)
(exit)
```

This is  bit of a corner-case. The way I read IEEE suggest to me that even and odd when converting to integer refers to the integer, not the floating-point bit-pattern. So, -.5 should round to zero (since that is the nearest even number, not -1) and since 0 is representable in an unsigned bitvector the result should be 0 and not unspecified.

**Comment by NikolajBjorner** [comment]
We can't add GPL to our tests, sorry.

**Comment by wintersteiger** [comment]
@NikolajBjorner wrong window?

**Comment by wintersteiger** [comment]
For the rounding corner cases I'm not sure that IEEE is the right reference for this. There may be subtle differences between IEEE and SMT here, i.e., will take time to figure out.

**Comment by NikolajBjorner** [comment]
My comment is that it would be great to add regression tests to the z3test repository, but z3test is under MIT license and doesn't come with the requirements of GPL.

**Comment by florianschanda** [comment]
If it helps you I am happy to re-license that test for you under the MIT license.

**Comment by NikolajBjorner** [comment]
Cool

**Comment by wintersteiger** [comment]
Not really necessary in this particular case, but for future examples it would be nice.

**Comment by wintersteiger** [comment]
I'm afraid IEEE754 is not the reference here, but it's the SMT definition of the FP theory, which states:

> All fp.to_* functions are unspecified for NaN and infinity input values. In addition, fp.to_ubv and fp.to_sbv are unspecified for finite number inputs that are out of range (which includes all negative numbers for fp.to_ubv).

So, it looks to me like `fp.to_ubv` of a negative float is correctly unspecified. I'm not sure they intended to say "negative number" instead of "negative integer" here, so I'll send it on to the semantics people.

**Comment by wintersteiger** [comment]
I got a reply almost immediately: 

> There appear to be two bugs here. First the theory document says two inconsistent things [...] Worse, the definitive standards document says "NaN" where it should say undefined. [...]

I'll fix our implementation once that discussion has come to a conclusion!

**Comment by wintersteiger** [comment]
This should now be fixed; it came almost for free with recent other fixes. I'm expecting the SMT-LIB documents to be updated soon, but I don't expect that they'll want to keep different semantics (or they'll have to be _very_ clear about those differences).
