### ISSUE TITLE
How to use "benchmarkToSMTString" function to print out `SMT-LIB2` language?

### ISSUE THREAD

**Issue by computereasy** [Z3Prover/z3#1194]
Hello,

I am thinking to print out my `z3` formula into `SMT-LIB2` language with `QF_BV` logic. After some [googling](https://stackoverflow.com/questions/14628279/z3-convert-z3py-expression-to-smt-lib2) I am aware in `Python` I can use some APIs like `toSMT2Benchmark`. However, it is still unclear to me how to play with it in `Java`. 

So here is my code (it is actually in `Scala`):

        val xe : BitVecExpr = x.evaluate()
        ctx_z3.benchmarkToSMTString()          <----- what are the parameters for this function?

I notice the first parameter of `benchmarkToSMTString` is a string, not a `BitVecExpr`. I basically have no idea what `string` I need to give to this function.

Could anyone shed some lights on this? Thank you in advance!

**Comment by wintersteiger** [comment]
See the API documentation for [benchmarkToSMTString](http://z3prover.github.io/api/html/classcom_1_1microsoft_1_1z3_1_1_context.html#a488f610e80d019d26c6e13588f46a6e6).

Note that `SMT` in the function name means that this is an SMT 1.0 benchmark, not an SMT 2.0 benchmark.

However, just a `BitVecExpr` without anything else is not enough to make up benchmarks of either versions. What are you trying to achieve?

**Comment by rainoftime** [comment]
@computereasy If your goal is to dump the constraints to SMT-LIB2 files, perhaps you could use file redirection

Here is an example with C++ API:
~~~~
void test() {
    context c;
    expr x = c.bv_const("x", 32);
    expr y = c.bv_const("y", 32);
    solver s(c);
    s.add(x > 2);
    s.add(x + y < 5);
    // redirection herer 
    std::cout << s << std::endl;  // print the constraint in the solver in SMT-LIB2 format
}
~~~~

**Comment by NikolajBjorner** [comment]
I think this was answered.
