### ISSUE TITLE
Z3 string theory inconsistency

### ISSUE THREAD

**Issue by varming** [Z3Prover/z3#1196]
I run Z3 on
```
4c327592df23:two_wildcards varming$ cat c.z3 
(declare-const x String)

(assert (str.prefixof "http://www.example1.com/xx" x))
(assert (str.contains x "foobarbeer"))
(assert (str.suffixof "baz" x))

(assert (not (and (str.prefixof "http://www.example1.com/" x) (str.contains x "foobar") (str.suffixof "baz" x))))

(check-sat)
(get-model)
```
and I get the model
```
sat
(model 
  (define-fun x () String
    "http://www.example1.com/xx\x00\x00foobarbeerbaz")
)
```
But the fourth assert should prevent that model as "http://www.example1.com/" is a prefix of x, "foobar" is in x and "baz" is a suffix of x.

Now, I guess I could be doing something bad, but to the untrained eye this looks like a inconsistency in Z3.

**Comment by NikolajBjorner** [comment]
This is a smaller repro:

    (declare-const x String)
    (assert (str.prefixof "x" x))
    (assert (str.contains x "fo"))
    (assert (not (str.contains x "f")))
    (check-sat)
    (get-model)

**Comment by NikolajBjorner** [comment]
can we close this?

**Comment by NikolajBjorner** [comment]
there were bugs in some ad-hoc rewrites, but fixing these don't address the problem entirely.

this is a repro with random_seed=2

    (declare-const x String)
    (assert (str.prefixof "cx" x))
    (assert (str.contains x "fp"))
    (assert (str.suffixof "z" x))
    (assert (not  (str.contains x "f")))
    (check-sat)
    (get-model)

smt.string_solver=z3str3 seems to avoid the bug.

**Comment by NikolajBjorner** [comment]
this is fixed
