### ISSUE TITLE
Interaction between forall on a finite sort, and assertion involving str.++, fails to find solution

### ISSUE THREAD

**Issue by pfdietz** [Z3Prover/z3#1200]
(declare-sort S)
(declare-const c S)
(assert (forall ((x S)) (= x c)))  ;; S has just one value

(declare-const z String)
(assert (= (str.++ z z) "AA"))

(check-sat)
(get-model)

Although the sort S is not involved in the assertion, the presence of those lines causes (check-sat) to not find a model.

This is a reduced example from something that came up in a more "real" application.

**Comment by pfdietz** [comment]
When the option combined_solver.ignore_solver1 is set to true a model is successfully computed.  Otherwise, if verbose=100 then the following trace is produced:

(started "check-sat")
(combined-solver "using solver 1")
(simplifier :num-exprs 8 :num-asts 184 :time 0.00 :before-memory 2.21 :after-memory 2.21)
(smt.simplifying :time 0.00 :before-memory 2.39 :after-memory 2.39)
(smt.simplifying :time 0.00 :before-memory 2.39 :after-memory 2.39)
(smt.configuring)
(smt.collecting-features)
(smt.simplifier-done)
(smt.preprocessing :time 0.00 :before-memory 2.86 :after-memory 2.96)
(smt.searching)
(smt.final-check "arithmetic")
(smt.final-check "array")
(smt.final-check "datatype")
(smt.final-check "bit-vector")
(smt.final-check "datalog")
(smt.final-check "seq")
(smt.final-check "unknown")
(smt.final-check "fpa")
(smt.final-check "quantifiers")
[with the smt.final-check lines then being repeated endlessly.)

**Comment by NikolajBjorner** [comment]
The default solver does not solve the equation for z. 
Use smt.string_solver=z3str3 to solve the equation (and quantifier)
