### ISSUE TITLE
Segmentation fault for nested int.to.str and str.to.int

### ISSUE THREAD

**Issue by iwob** [Z3Prover/z3#1202]
Tested on HEAD: 082936b

The following commands produce segmentation fault and "NOT IMPLEMENTED YET!" message.
```
(set-logic QF_S)
(assert (= (int.to.str (str.to.int "a")) "a"))
(check-sat)
```

**Comment by NikolajBjorner** [comment]
@Murphy Berzish, this is using z3str3.

**Comment by mtrberzi** [comment]
I'll check this commit, thanks! (I didn't see the notification, it might work if you do @mtrberzi)

**Comment by mtrberzi** [comment]
This should do the right thing. I see the trick of adding a literal to force the theory solvers to pick up the term.

**Comment by iwob** [comment]
Z3 returns now unsat. Is this the expected answer? I would say that this should be sat (please correct me, if the string theory is not intuitive in this case).

**Comment by NikolajBjorner** [comment]
According to the definition draft for SMTLIB strings, str.to.int returns -1 when passed anything that isn't a (non-negative) integer. So str.to.int "a" = -1. So the equality is false.

**Comment by iwob** [comment]
Is this draft accessible online? str.to.int expects String sort as input, so I don't understand your remark about non-negative integers. Just now I tried to get the raw result of (str.to.int "a"), and solver works suspiciously long and haven't stopped yet:

```
(set-logic QF_S)
(declare-fun x () Int)
(assert (= x (str.to.int "a")))
(check-sat)(get-model)
```

**Comment by NikolajBjorner** [comment]
@mtrberzi - this loops

**Comment by NikolajBjorner** [comment]
Cesare Tinelli prepared a draft spec. It is circulated on https://groups.google.com/forum/#!forum/smt-lib

**Comment by iwob** [comment]
Thank you for the pointer. I checked your commit and it seems to work. I had wrong preconception as to what str.to.int does - I was expecting something like getting ASCII number. But in my experiments with scripts I stumbled upon one more related problematic input for the solver, which you may be interested in fixing (maybe your newest commit on master has fixed this, currently z3 is building):

```
(set-logic QF_S)
(declare-fun x () Int)
(assert (= x (str.to.int "a")))
(assert (not (= x -1)))
(check-sat)
```

**Comment by iwob** [comment]
All previous examples are solved correctly, but a simple modification causes another hang:
```
(set-logic QF_S)
(declare-fun x () String)
(declare-fun a () Int)
(assert (>= a 1))
(assert (= a (str.to.int x)))
(check-sat)(get-model)
```

**Comment by iwob** [comment]
Also looking at the commit 893bcbb5 it leaves some unused code. Just mentioning this in case it was not the desired effect.

**Comment by NikolajBjorner** [comment]
Correct, this is left so Murphy can continue the fix. The dead code triggers a bug.

**Comment by mtrberzi** [comment]
Thanks, I'll investigate this on my end.

**Comment by NikolajBjorner** [comment]
This does not hang any longer
