### ISSUE TITLE
Static native libraries for non-C++ APIs?

### ISSUE THREAD

**Issue by dhalperi** [Z3Prover/z3#1204]
Is there a way to build the JNI library for z3 statically? FWICT, when I turn on `--staticlib` it only statically links `libz3.so/a`, not `libz3java.so/a`.

**Comment by delcypher** [comment]
@dhalperi I didn't write the Java bindings so I can't give you a definitive answer.

For the new CMake build system using a static libz3 and building python/.NET/Java bindings is actually forbidden (the configure step will fail) because the way they are currently implemented requires a dynamic library. I know for certain that the Python bindings requiring a dynamic library because they use `ctypes.CDLL()` to load the library.

For the Java bindings the generated `Native.java` contains this code

```java
  static {
    try { System.loadLibrary("z3java"); }
    catch (UnsatisfiedLinkError ex) { System.loadLibrary("libz3java"); }
  }
```

`libz3java.so` is a small native code library (built from the generated `Native.cpp` file) that itself links to `libz3.so`. I don't know if Java can load a static library at runtime. My suspicion would be no but I don't have much expertise with Java so I could be wrong.

**Comment by wintersteiger** [comment]
I'm sure it's possible to do that for Java, but not necessarily for all APIs. I don't see a real reason or need for this, but if there is one, we could add it as an option, I suppose. 

`--staticlib` only adds `libz3.a` to the build (it doesn't change any linker commands), and `--staticbin` links the `z3(.exe)` binary statically, but not any of the other binaries or libraries.

**Comment by dhalperi** [comment]
Yes, exactly – I am trying to get libz3java to be statically linked and contain all of z3.

The reason is portability – if we ship a java application that requires z3, we could potentially put those two files in a jar. Then the system we use it on would not need to have any system libraries installed.

For an example of where this is done: http://netty.io/wiki/forked-tomcat-native.html

```
netty-tcnative-boringssl-static-{os_arch}

This artifact is statically linked against Google's boringssl, which is a fork of OpenSSL that has a reduced code footprint and additional features (such as ALPN) which at the time of this writing have not made an appearance in a stable release of linux. The static linking makes it easier to get started using tcnative on a system without having to worry about additional install steps. This library does not require APR.
```

**Comment by dhalperi** [comment]
for some reason, btw, libz3java.so + libz3.a did not seem to work.

**Comment by delcypher** [comment]
@dhalperi For that to work `libz3.a` will need to built as position independent code (`-fPIC`).

> The reason is portability – if we ship a java application that requires z3, we could potentially put those two files in a jar. Then the system we use it on would not need to have any system libraries installed.

Some what portable. `libz3.a` still needs the system's C library (not linked in) and the C++ standard library (not linked in either).

**Comment by wintersteiger** [comment]
I think that would just delay the problem. Native Z3 binaries (and libraries) are not portable, i.e., you will have to ship your Java application with x86, x64, Windows, Linux, OSX versions of libz3.dll/.so/.dylib. If they are linked statically into libz3java.dll/.so/.dylib, you will still have to provide the same number of combinations of architectures, just for a different file.

**Comment by dhalperi** [comment]
In this case, I am willing to do a lot of work to make it easier for my users to deploy. So building say 10 jars once is work for me.

But then my users just download the arch-appropriate jar rather than installing a bunch of C++ libraries. It's much less burden on users to have java and C++ installed than to also have libgomp, etc1.

**Comment by wintersteiger** [comment]
@dhalperi Not sure I understand your statement: does "is work for me" mean that you are going to do the work or does it mean that you will not do that work?

Our Windows binary packages should include all DLLs required, but the other platform binaries don't come with any system .so/.dylibs. You can try linking to them statically, but I expect that those binaries would only work on a very limited set of Linux flavors. E.g. I think Ubuntu 16.x binaries won't necessarily work on Ubuntu 14.x, even when linked statically, right?

Aside: OpenMP is one of those cases... Visual C++ doesn't support static linking, no way around it.

**Comment by dhalperi** [comment]
I meant "is work I can do once, and all customers will benefit."

Re static linking – it's true that newer static libraries often don't work on older *nixes, but the reverse seems to be true. From what I can tell, the Netty folks compile their static libraries on Centos 6 and the x86_64 libs work on newer Centos, Debian, etc.

**Comment by wintersteiger** [comment]
That's right, you'd only have to do it once, but for every system (or system family) your users want to run on. Once you've done that though, it really doesn't matter whether you ship two .so's or one big .so in your .jar.
