### ISSUE TITLE
regression: performing optimization queries with PROOF mode on (sometimes) crashes

### ISSUE THREAD

**Issue by cheshire** [Z3Prover/z3#121]
Hi, 

In many cases with the proofs on I get a crash from the optimization query.
The message I get back is "exception in tactic card2bv does not support proof production".

It sounds quite confusing, especially since I'm not calling any tactics manually, and I am not using bitvectors.

**Comment by NikolajBjorner** [comment]
Generally one should never use proof mode with optimization features because no proof will be generated for feasible queries (but instead models). The code that fails on proof mode in card2bv seemed superfluous, so I have removed it.
