### ISSUE TITLE
[TravisCI] Enable macOS builds

### ISSUE THREAD

**Issue by delcypher** [Z3Prover/z3#1211]
This issue is for continuing the discussion in PR #1207 .

The build is currently disabled (by 9dc332ae9d4e1650af47daafe9821bbd8a2edf59 ) due to @wintersteiger's concerns on the legal issues involved in running macOS builds on TravisCI's infrastructure. There are restrictions (e.g. [see 2B(iii) in OSX El Capitan of software license agreement](http://images.apple.com/legal/sla/docs/OSX1011.pdf)) on how OSX/macOS can be used.

I believe Travis use [MacStadium](https://www.macstadium.com/customers/travis-ci/) to run their macOS builds but this is not confirmed.

Personally I don't believe this is a problem because it is TravisCI running the infrastructure (and it looks like they are actually using a third party -- i.e. MacStadium -- to run this part of their infrastructure), not us so I would expect the onus to be on TravisCI (or the third party they use) to comply with Apple's software license agreement.

However @wintersteiger given that you are the one concerned with this issue could you reach out to TravisCI to clarify the situation?

**Comment by wintersteiger** [comment]
I didn't know MacStadium yet. Where did you find the information that Travis uses them to host the hardware?

**Comment by delcypher** [comment]
MacStadium proudly show it on their website

https://www.macstadium.com/customers/travis-ci/

However TravisCI themselves don't seem to mention it so I think it's best if you contact them to confirm what the situation is.

**Comment by wintersteiger** [comment]
In the meanwhile I received a reply to my email to the Travis support:

> 
> We virtualize macOS on Apple hardware (a mix of xServe and Mac Pro hardware) on a VMware vSphere based Private Cloud, which we've partnered with MacStadium to build and operate. As far as we're aware, this is sufficient to comply with Apple's EULA regarding how macOS can be virtualized.
> 
> We are not aware of any public documentation from Apple on specific rules for using macOS in a SaaS-based CI environment, but we've had multiple informal conversations with our peers at other CI providers and folks doing macOS CI for other organizations, and the approach we've taken seems to be the common one and the one that everyone feels is in the _spirit of the law_. 

I think that's good enough for us to enable the OSX CI builds.

**Comment by delcypher** [comment]
Great. Thanks for taking the time to check. Please revert 9dc332ae9d4e1650af47daafe9821bbd8a2edf59 when you have time.
