### ISSUE TITLE
Segmentation Fault

### ISSUE THREAD

**Issue by abetatsuya** [Z3Prover/z3#1213]
The [code](https://github.com/Z3Prover/z3/files/1226905/segfault.smt2.txt) (this is as small as I could go) causes z3 (fresh build) to produce a segmentation fault after about 5 seconds of running.

I invoke the z3 command with verbose=10 `$ z3 -v:10 -nw -smt2`.  This is a [result](https://github.com/Z3Prover/z3/files/1226909/segfault_verbose.txt).

If I comment out lines 38--43 `(not (and (>= s76 s15) (>= s77 s15)))`, then Z3 returns sat.

I appreciate if you would give any hint.

**Comment by wintersteiger** [comment]
Thanks for the report! I can reproduce it and I'm almost entirely sure that this is the exactly same problem as #1212 (which is in progress).

**Comment by abetatsuya** [comment]
Thank you so much for the quick reply.  I am looking forward to hearing that the progress goes well!
