### ISSUE TITLE
Solution to MaxSAT problem from Java API violates some assertions containing xor

### ISSUE THREAD

**Issue by agember** [Z3Prover/z3#1215]
I am using the Java API to formulate a MaxSAT problem. The problem contains some assertions of the form `(=> a (xor b (xor c (xor d ...))))` where all variables in the assertion are booleans (defined using `mkBoolConst`). An example is [formulation.txt](https://github.com/Z3Prover/z3/files/1229426/formulation.txt); I apologize for the length of the example.

I create the `Optimize` object as follows:
```java
Map<String, String> z3Config = new LinkedHashMap<String, String>();
z3Config.put("model", "true");
Context ctx = new Context(z3Config);
Optimize solver = ctx.mkOptimize();
```

I get the values of the desired boolean variables as follows:
```java
solver.Check();
solver.getModel().getConstInterp(...);
```

When obtaining the solution using the Java API, I get a solution that violates some of the assertions of the aforementioned form that appear in lines 4393 through 7312 of the example. However, if I save the output of `solver.toString()` to a file and run Z3 on the command line, then I get a valid solution.

I am using the latest version of `master` (commit `97e263`). 

This issue may be related to #1112. I tried to load in my saved file to see if I could reproduce the same behavior described in that issue:
```java
Map<String, String> z3Config = new LinkedHashMap<String, String>();
z3Config.put("model", "true");
Context newContext = new Context(z3Config);
Optimize newSolver = ctx.mkOptimize();
			
String code = FileUtils.readFileToString(new File("/tmp/formulation.z3"), Charset.defaultCharset());
BoolExpr assertions = newContext.parseSMTLIB2String(code, null, null, null, null);
newSolver.Add(assertions);
```
However, I get errors that assert-soft is unsupported.

I am happy to run more experiments or provide other output/code if it's useful. Just let me know what I should provide.

**Comment by NikolajBjorner** [comment]
The Optimize object has a method for parsing benchmarks directly. Use this one.
Here is a version from Python:

    from z3 import *

    opt = Optimize()
    opt.from_file("../formulation.txt")
    print opt.check()
    m = opt.model()
    for a in opt.assertions():
       e = m.eval(a)
       if not is_true(e):
          print a, e

    print opt.statistics()

Unfortunately, I don't get a repro this way (yet).

**Comment by NikolajBjorner** [comment]
or at least now there is a method for parsing benchmarks...

**Comment by agember** [comment]
Saving the formulation to a file and loading it back using the new `fromFile` function still causes the solver to produce a solution that violates an assertion.

For example, the solution contains:
```
(define-fun |disjoint0:agg1-1.IN->agg1-1.OUT| () Bool
  true)
(define-fun |disjoint0:agg1-1.OUT->c7.IN| () Bool
  true)
(define-fun |disjoint0:agg1-1.OUT->e1-1.IN| () Bool
  true)
```
which violates the assertion
```
(assert (=> |disjoint0:agg1-1.IN->agg1-1.OUT|
    (xor false
         |disjoint0:agg1-1.OUT->e1-3.IN|
         |disjoint0:agg1-1.OUT->e1-0.IN|
         |disjoint0:agg1-1.OUT->c4.IN|
         |disjoint0:agg1-1.OUT->c7.IN|
         |disjoint0:agg1-1.OUT->e1-1.IN|
         |disjoint0:agg1-1.OUT->c6.IN|
         |disjoint0:agg1-1.OUT->c5.IN|
         |disjoint0:agg1-1.OUT->e1-2.IN|)))
```

If I eval the assertion on the computed model, it says the assertion is true.

**Comment by NikolajBjorner** [comment]
xor is like parity. It is true if there is an odd number of arguments that are true.

xor(a,b,c) = xor(a, xor(b, c)):

a = 1, b = 1, c = 1 => result = 1
a = 0, b = 1, c = 1 => result = 0
a = 1, b = 0, c = 1 => result = 0
a = 0, b = 0, c = 1 => result = 1

reading from the name of your variable, perhaps you want a cardinality constraint like ((_ at-most 1) a b c).

**Comment by agember** [comment]
You are correct: I want cardinality constraint. I had not realized before that xor is like parity, but I see it now.

However, I am still curious why I got different results from the command line versus Java. Is this simply a matter of a random seed, or are some of their default settings different?

**Comment by NikolajBjorner** [comment]
I get different results depending on the order expressions are built, so you can expect different incompatible optima.
