### ISSUE TITLE
Definition of a recursive function triggers 'wrong number of arguments' error

### ISSUE THREAD

**Issue by iwob** [Z3Prover/z3#1221]
Tested on HEAD: bc8ae21ebee8a3451c9450a7add52289dc799a16

I'm trying to define recursive length function for the List algebraic datatype. The following script:

```
(define-fun-rec len ((x (List Int))) Int
    (ite (= x nil)
        0
        (+ 1 (len (tail x)))))

(declare-fun len0 () Int)
(declare-fun len1 () Int)
(declare-fun len2 () Int)

(assert (= (len0 (len nil))))
(assert (= (len1 (len (insert 1 nil)))))
(assert (= (len2 (len (insert 1 (insert 1 nil))))))

(check-sat)(get-model)
```

produces this:

```
(error "line 10 column 26: Wrong number of arguments (1) passed to function (declare-fun len0 () Int)")
(error "line 11 column 37: Wrong number of arguments (1) passed to function (declare-fun len1 () Int)")
(error "line 12 column 48: Wrong number of arguments (1) passed to function (declare-fun len2 () Int)")
sat
(model 
  (define-fun k!0 () (List Int)
    nil)
  (define-fun len ((x!0 (List Int))) Int
    (ite (= x!0 nil) 0
      (+ 1 (len (tail x!0)))))
)
```

Also: why k!0 was created and showed in the model?

**Comment by NikolajBjorner** [comment]
Thanks for pointing out the auxiliary k!0. A fix is in the works.
For the errors, you should rewrite the asserts to

    (assert (= len0 (len nil)))

etc.

**Comment by iwob** [comment]
Late night coding made me not see this obvious syntactic error in the assert. I'm sorry for the trouble. But maybe this issue was not a waste because of this k!0.

Btw in which logics List datatype is included? I tried some explicit logic declarations, but without success as of yet.

**Comment by NikolajBjorner** [comment]
List is not included in SMTLIB2 logics, at least not before version 2.5. 
It gets included if you don't specify a logic.

**Comment by NikolajBjorner** [comment]
k!0 is no longer part of the model

**Comment by iwob** [comment]
I just built the master and I still have k!0 (and also len!1):

```
sat
(model 
  (define-fun len0 () Int
    0)
  (define-fun len1 () Int
    1)
  (define-fun len2 () Int
    2)
  (define-fun k!0 ((x!0 (List Int))) (List Int)
    (ite (= x!0 (insert 1 nil)) (insert 1 nil)
    (ite (= x!0 nil) nil
      (insert 1 (insert 1 nil)))))
  (define-fun len ((x!0 (List Int))) Int
    (ite (= x!0 nil) 0
      (+ 1 (len (tail x!0)))))
  (define-fun len!1 ((x!0 (List Int))) Int
    (ite (= x!0 (insert 1 nil)) 1
    (ite (= x!0 (insert 1 (insert 1 nil))) 2
      0)))
)
```

**Comment by NikolajBjorner** [comment]
These auxiliary definitions escape for a different reason and we don't have a way to contain them: initially len is defined using k!0 and len!1. Later on, they are simplified away from the definition of len, but the information that they are auxiliary is no longer present. I will have to punt on this part until we have different features in place that will eventually make it a non-issue.
