### ISSUE TITLE
Poor performance dealing with regular expression which is always satisfiable

### ISSUE THREAD

**Issue by jawline** [Z3Prover/z3#1224]
Is there any way to make the regular expression problem below perform better. Z3 has trouble deciding that the regular expression (Which is essentially .*) accepts all characters.

```
(declare-fun X () String)  
(assert (not (str.in.re X (re.* (re.range "\x00" "\xFF")))))
(check-sat)
(get-model)
```

**Comment by NikolajBjorner** [comment]
Loris D'Antoni: can you code review the change I made to mk_deterministic? The empty set of states is accepting iff some epsilon reachable initial state is accepting, or complemented it is rejecting if it is the case. The prior solution would always tag the initial state as rejecting resp. accepting (when complementing).

**Comment by lorisdanto** [comment]
Looks correct. I would refactor as is_final_configuration of epsilon closure since the code is almost identical.

**Comment by NikolajBjorner** [comment]
To me it doesn't look right: the initial state set in the usual subset construction is the epsilon closure of initial states in the NFA. Here the initial state set is empty.

**Comment by NikolajBjorner** [comment]
Changed again to ensure initial states are in the epsilon closure.

**Comment by lorisdanto** [comment]
I'm not sure I understand. What line makes the initial state the empty set?

At least in the current version looks right. I see that early the variable set was incorrectly uninitialized

**Comment by NikolajBjorner** [comment]
The first fix wasn't right: the initial set should contain all epsilon reachable initial states, not just the designated initial state. The procedure should work for e-NFA as far as I recall.

**Comment by lorisdanto** [comment]
Yes, makes sense

**Comment by NikolajBjorner** [comment]
this was fixed, so closing
