### ISSUE TITLE
Trying to compile z3 example for ml api using ocaml 4.03.0

### ISSUE THREAD

**Issue by anmaped** [Z3Prover/z3#1230]
I'm using the last z3 git version and ocaml 4.03.0. I also have installed z3 with `make install`.

When I compile using 
```
ocamlfind ocamlc -o ml_example.byte -package Z3 -linkpkg ml_example.ml
```
it compiles, but stuck on `mk_context` infinitely.

When I compile a native binary I get
```
$ ocamlfind ocamlopt -o ml_example -package Z3 -linkpkg ml_example.ml
** Fatal error: Cannot find file "libz3"
File "caml_startup", line 1:
Error: Error during linking
```

I'm working with a fresh version of Andreas Hauptmann's installer.

**Comment by wintersteiger** [comment]
I'm not familiar with Andreas Hauptmann's installer. What system are you running on and is the installer specific to the system? Where does it put the files and which environment variables does it set/change? Looks to me like this issue should first be reported to Andreas Hauptmann in any case.

The error indicates the OCaml can find libz3ml.a (or similar), but the system can't find libz3.dll/.so/.dylib. You may have to add the path to that file to your `PATH`/`LD_LIBRARY_PATH`/`DYLD_LIBRARY_PATH`.

**Comment by anmaped** [comment]
@wintersteiger Thanks for the fast reply. If I copy libz3.dll.a to the lib directory it compiles (Is it supposed to do ?).

However, I get
```
$ ./ml_example
      3 [main] ml_example 340 child_copy: cygheap read copy failed, 0x612E8408..0x612F35E4, done 0, windows pid 340, Win32 error 6
    801 [main] ml_example 340 C:\Users\anmap\Desktop\test\ml_example.exe: *** fatal error - ccalloc would have returned NULL
```

**Comment by wintersteiger** [comment]
Are you using cygwin?

**Comment by anmaped** [comment]
yes.

**Comment by wintersteiger** [comment]
That will take a while to debug then. What version of OCaml and which compiler are you using?

**Comment by anmaped** [comment]
ocaml 4.03.0 that was installed from opam.
gcc-core version 5.4.0-1
gcc-g++ 5.4.0-1
cygwin i686 version 2.8.2

I have also tested with x86_64 and the same happens.

**Comment by wintersteiger** [comment]
Where can I find Andreas Hauptmann's installer?

**Comment by anmaped** [comment]
https://fdopen.github.io/opam-repository-mingw/installation/

**Comment by wintersteiger** [comment]
Sorry, I can't use that installer, it tries to download all users account data for the whole company and then can't parse the result of that. Please report your problem Andreas Hauptmann first; most likely the various paths are not set up correctly, and that has to be fixed in the installer in any case.

**Comment by anmaped** [comment]
@wintersteiger Thank you very much. I will try to solve the weird issue.

**Comment by anmaped** [comment]
I have discovered that replacing `libz3.dll` with the pre-compiled version 4.5.0 works well. So I suppose that the issue is when compiling z3 lib and not the ocaml bindings.

**Comment by wintersteiger** [comment]
Fantastic, thanks for reporting back!
