### ISSUE TITLE
A new official release is sorely needed..

### ISSUE THREAD

**Issue by LeventErkok** [Z3Prover/z3#1231]
The last official release of Z3 is now some ~1400 commits behind the master, according to https://github.com/Z3Prover/z3/releases.

Would it be at all possible to have a new official release out?

(Users of tools built on top of Z3 usually get the "official release" instead of nightly ones, and get quite confused when they see discrepancies/non-working items upstream. There have been many great changes to Z3 since the 4.5.0 release; would be really nice to have an official version out..)

**Comment by NikolajBjorner** [comment]
Understood. Is October 7 too late?

**Comment by LeventErkok** [comment]
I think October 7 would be fantastic! Thanks..

**Comment by delcypher** [comment]
@LeventErkok I agree that another release is needed but there are several things in the pipeline that it would be good to finish first (e.g. Testing the new `Z3_model` API). I imagine a lot of these things could be finished by October.

**Comment by wintersteiger** [comment]
I agree, a release is absolutely needed. For me, October 7 is completely impossible however. I'd have to push that closer to end of October to have enough time to look at the benchmarks and fix performance problems. And there are a _lot_ of them, e.g., all F* queries are significantly slower than in 4.5.0, and some of the new SMTLIB benchmarks have never been run through (they just released new benchmarks last month).

**Comment by wintersteiger** [comment]
(Aside: between previous releases we had more like 5k commits, so 1.4k would be unbelievably early!)

**Comment by delcypher** [comment]
@wintersteiger @NikolajBjorner How are the prospects of making a new Z3 release looking?

Maybe we should list what's blocking a new release here so can check them off as we go?

**Comment by wintersteiger** [comment]
It's in progress, but I've been blocked for most of the month. There are a number of items I'd like to get into the release, which all have issue numbers, but there's no list of them. Feel free to start collecting some of them though!

**Comment by delcypher** [comment]
@wintersteiger GitHub has the [milestones](https://help.github.com/articles/about-milestones/), [project boards](https://help.github.com/articles/about-project-boards/) features, either of which can be used to keep track of a group of issues/pull requests. Unfortunately I cannot create a milestone/project because that is only available to project maintainers.

You don't have to use these features to track release blockers but others (including myself) would find it useful.

**Comment by wintersteiger** [comment]
Done, the release is out, so I'm closing this issue.

**Comment by LeventErkok** [comment]
Congratulations!
