### ISSUE TITLE
Model based projection for UTVPI and bit-vector in qsat?

### ISSUE THREAD

**Issue by rainoftime** [Z3Prover/z3#1236]
Z3 has two new procedures`qsat_tactic` and `qe2_tactic` for quantified satisfiability and quantifier elimination, based on the paper "Playing with quantified satisfaction"(LPAR).   Do they have special support for theories of UTVPI(unit two variable per inequality)  or bit-vector, in the model based projection part now? Thank you!

**Comment by NikolajBjorner** [comment]
There isn't any particular support for UTVPI and bit-vectors are handled by a crude mechanism until there are application/benchmarks that show this has value.
