### ISSUE TITLE
Semantics of Z3_OP_FPA_MIN_I and Z3_OP_FPA_MAX_I plus simplifier bug?

### ISSUE THREAD

**Issue by delcypher** [Z3Prover/z3#1242]
This similar to #1132 . It seems Z3's simplifier is leaking more undocumented operators.

e.g. 

If we start with this

```
; Start decls (3)
(declare-fun r () (_ FloatingPoint 11 53))
(declare-fun x () (_ FloatingPoint 11 53))
(declare-fun y () (_ FloatingPoint 11 53))
; End decls
; Start constraints (4)
(assert (= x (fp #b0 #b00011111000 #xb0db2ac57d287)))
(assert (= y (fp #b1 #b00101101000 #x422c9af77f44c)))
(assert (= r (fp #b0 #b00011111000 #xb0db2ac57d287)))
(assert (= (fp.max x y) r))
; End constraints
```

and then run Z3's simplifier we get

```
; Start decls (3)
(declare-fun r () (_ FloatingPoint 11 53))
(declare-fun x () (_ FloatingPoint 11 53))
(declare-fun y () (_ FloatingPoint 11 53))
; End decls
; Start constraints (4)
(assert (= x (fp #b0 #b00011111000 #xb0db2ac57d287)))
(assert (= y (fp #b1 #b00101101000 #x422c9af77f44c)))
(assert (= r (fp #b0 #b00011111000 #xb0db2ac57d287)))
(assert (let ((a!1 (and (fp.isZero x)
                (fp.isZero y)
                (or (and (fp.isPositive x) (fp.isNegative y))
                    (and (fp.isNegative x) (fp.isPositive y))))))
  (= (ite a!1 (fp.max_unspecified x y) (fp.max_i x y)) r)))
; End constraints
```
`fp.max_i` appears to correspond to `Z3_OP_FPA_MAX_I` kind and `fp.max_unspecified` corresponds publicly to `Z3_OP_UNINTERPRETED` (internally `OP_FPA_INTERNAL_MAX_UNSPECIFIED`)

It would nice if `Z3_OP_FPA_MAX_I` and `Z3_OP_FPA_MIN_I` were documented. It looks like they are introduced by `fpa_rewriter::mk_max()` and `fpa_rewriter::mk_min()`. Reading the implementation I'm guessing the semantics of `Z3_OP_FPA_MAX_I` can be assumed to be that the arguments are not `(+zero)` and `(-zero)` (similar for` Z3_OP_FPA_MAX_I`).

It would be nice if `OP_FPA_INTERNAL_MAX_UNSPECIFIED` (and the others see `Z3_get_decl_kind()` implementation) had their own public separate kinds because I need to handle each of these specially if the simplifier is going to introduce them. `Z3_OP_UNINTERPRETED` isn't enough information for my use case. I could get the string value of the AST but that's kind of a hack.

On a related noted to me it seems like there's a bug (or missing feature) when the `propagate-values` and `simplifer` tactics are combined.

```
; Start decls (3)
(declare-fun r () (_ FloatingPoint 11 53))
(declare-fun x () (_ FloatingPoint 11 53))
(declare-fun y () (_ FloatingPoint 11 53))
; End decls
; Start constraints (4)
(assert (= x (fp #b0 #b00011111000 #xb0db2ac57d287)))
(assert (= y (fp #b1 #b00101101000 #x422c9af77f44c)))
(assert (= r (fp #b0 #b00011111000 #xb0db2ac57d287)))
(assert (= (fp.max x y) r))
; End constraints
(apply (and-then propagate-values simplify) :print_benchmark true :print false)
```

The result is

```
(declare-fun x () (_ FloatingPoint 11 53))
(declare-fun y () (_ FloatingPoint 11 53))
(declare-fun r () (_ FloatingPoint 11 53))
(assert (= x (fp #b0 #b00011111000 #xb0db2ac57d287)))
(assert (= y (fp #b1 #b00101101000 #x422c9af77f44c)))
(assert (= r (fp #b0 #b00011111000 #xb0db2ac57d287)))
(assert (= (fp.max_i (fp #b0 #b00011111000 #xb0db2ac57d287)
                     (fp #b1 #b00101101000 #x422c9af77f44c))
           (fp #b0 #b00011111000 #xb0db2ac57d287)))
(check-sat)
```

The `propagate-values` tactic replaces `fp.max` with `fp.max_i` but the `simplify` tactic does not constant fold `fp.max_i`.

I might try and tackle this missing constant folding myself because this looks relatively easy to fix.

**Comment by delcypher** [comment]
@wintersteiger 
Actually I won't implement folding `fp.max_i` and `fp.min_i` for now because there might be a reason these aren't folded (e.g. to test the translation to SAT)

I've come up with a much more general workaround in my tool to avoid this. I was previously assuming that repeated application of `propagate-values` and `simplify` would remove all constant expressions but this isn't guaranteed to hold so I've just been very lucky so far to not have hit this.

If you'd like me to implement simplification for `fp.max_i` and `fp.min_i` though please ask and I'll give it a go.

**Comment by wintersteiger** [comment]
Yep, everything's exactly as you expected. This should now be fixed. Ultimately I'd like to get rid of some of those supposed-to-be-internal functions, but that might take a little longer.

**Comment by delcypher** [comment]
@wintersteiger Great. Thanks for doing this.
