### ISSUE TITLE
Match binder not yet implemented

### ISSUE THREAD

**Issue by Muon** [Z3Prover/z3#1243]
I've been using algebraic datatypes quite a bit in my program analysis, and I saw that SMT-LIB 2.6 was finalized. The match binder would make my language axiomatization much clearer, and potentially more efficient to solve than endlessly nesting ite-expressions. When might we see this in Z3? Thanks!

**Comment by NikolajBjorner** [comment]
If supported it would foremost only be syntactic sugar for nested ifs, so it would be more of a way to make inputs convenient. It might be possible to use this to optimize how function definitions are matched, but I am not sure how far we can support this.

**Comment by NikolajBjorner** [comment]
See https://github.com/Z3Prover/z3/commit/caa02c3c0296fb531488b8549f36424a1656cc1a
