### ISSUE TITLE
z3 4.5.1 incorrectly returning "sat" (4.4.1 returns "unknown")

### ISSUE THREAD

**Issue by pmfcollings** [Z3Prover/z3#1245]
EDIT There is a good chance that I am using a snapshot of the trunk instead of an official release so I need to double check this bug.

If I create a solver from the tactic of "bit-blast" followed by "sat" and query the satisfiablity of the expression:

```
; benchmark
(set-info :status unknown)
(declare-fun k!7280 () (_ BitVec 32))
(declare-fun k!7270 () (_ BitVec 1))
(assert
 (let (($x61358 (= k!7280 (_ bv0 32))))
(let (($x61113 (= k!7270 (_ bv0 1))))
(let (($x61151 (not $x61113)))
(and $x61151 $x61358 (not (and $x61151 $x61358)))))))
(check-sat)
```

then I get different behavior in 4.4.1 versus 4.5.1. 

The behavior in 4.4.1 seems correct - it returns "unknown".
The behavior in 4.5.1 seems incorrect - it returns "sat".

The default solvers in both 4.4.1 and 4.5.1 return "unsat" (which is correct by inspection).

The following c++ snippet demonstrates the problem (it takes a command line argument which is the smt2 file which should contain the above expression to show the bug):

```
#include "z3++.h"
#include <iostream>  

z3::solver makeBitBlastSolver(z3::context &context) {
    z3::tactic t = 
        z3::tactic(context, "bit-blast") &
        z3::tactic(context, "sat");
    z3::solver solver = t.mk_solver();
    return solver;
}

void solve(std::string desc, z3::solver &solver, const z3::expr &expr) {
    z3::check_result z3result = z3::unknown;
    solver.add(expr);    
    z3result = solver.check();    
    std::cout << "result for " << desc << " = " << z3result << std::endl;
}

int main(int argc, char **argv)
{
    if(argc<2) {
        std::cout << "Usage: " << argv[0] << " <smt_benchmark0>" << std::endl;
        return 1;
    }   
    z3::context ctx;
    
    // read in expression from file given on command line
    z3::expr expr = z3::to_expr(ctx, Z3_parse_smtlib2_file(ctx.operator Z3_context(), argv[1], 0, 0, 0, 0, 0, 0));

    z3::solver solver = makeBitBlastSolver(ctx);
    solve("bit-blast-sat-solver", solver, expr);
    z3::solver defaultSolver = z3::solver(ctx);
    solve("default-solver      ", defaultSolver, expr);
    return 0;  
}
```

The output for 4.4.1 is:
```
result for bit-blast-sat-solver = unknown                  
result for default-solver       = unsat     

```
The output for 4.5.1 is:
```
result for bit-blast-sat-solver = sat                      
result for default-solver       = unsat  

```

**Comment by pmfcollings** [comment]
I have realized that I may be using a trunk snapshot instead of an official release, so I will mark this as closed until I have recreated it in an official version.

**Comment by NikolajBjorner** [comment]
turned out to be a bug in the SAT clausifier for conjunctions. Internal tactics always eliminate conjunctions by composition with the "rewriter" tactic and the clausifier used to not handle conjunctions at all. Should be fixed now

**Comment by pmfcollings** [comment]
Thanks very much for the prompt action.

**Comment by pmfcollings** [comment]
I have confirmed that the bug was fixed by your commit (and I confirmed that the bug was recreatable using the snapshot just before your fix). Is it my reponsibility to close this issue, or shall I leave that to you? Either way, thanks.

**Comment by NikolajBjorner** [comment]
thanks
