### ISSUE TITLE
Feature request: Which assert failed

### ISSUE THREAD

**Issue by SMTStuck** [Z3Prover/z3#1246]
I am currently feeding a Z3 script into Z3, and I ask Z3 to return sat/unsat with a model if available (check-sat) (get-model). I'm not au fait enough with the code to do it myself, but I'm wondering, would it be an easy change to allow for Z3 to also return which assertion caused the model to be unsatisfied?

**Comment by delcypher** [comment]
@SMTStuck You can use unsat core to do this. You need to annotate each assert with a unique name and then request the unsat-core `(get-unsat-core)`. Z3 will return the list of unique names you gave to each assert that contribute to unsatisfiability.

**Comment by delcypher** [comment]
@SMTStuck Here's an example http://rise4fun.com/z3/smtc_core

**Comment by NikolajBjorner** [comment]
Thanks @delcypher , this is the approach to take for identifying assertions involved in unsatisfiability.

**Comment by SMTStuck** [comment]
Thank you so much. :)
