### ISSUE TITLE
C API request: apply_result_as_ast

### ISSUE THREAD

**Issue by cheshire** [Z3Prover/z3#125]
Hi,

For historical reasons we are currently using C API.
Using that, the transformation from `Z3_tactic_apply_result` to `Z3_ast` is rather scary:

```
    long result = tactic_apply(z3context, tseitinTactic, goal);
    apply_result_inc_ref(z3context, result);

    int no_subgoals = apply_result_get_num_subgoals(z3context, result);
    long[] goal_formulas = new long[no_subgoals];

    for (int i=0; i<no_subgoals; i++) {
      long subgoal = apply_result_get_subgoal(z3context, result, i);
      int no_subgoal_f = goal_size(z3context, subgoal);

      long[] subgoal_formulas = new long[no_subgoal_f];
      for (int k=0; k<no_subgoal_f; k++) {
        long f = goal_formula(z3context, subgoal, k);
        inc_ref(z3context, f);
        subgoal_formulas[k] = f;
      }

      long subgoal_f = mk_and(z3context, subgoal_formulas.length,
          subgoal_formulas);
      inc_ref(z3context, subgoal_f);
      // Cleanup.
      for (int k=0; k<no_subgoal_f; k++) {
        dec_ref(z3context, subgoal_formulas[k]);
      }
      goal_formulas[i] = subgoal_f;
    }
    long out_formula = mk_and(z3context, goal_formulas.length, goal_formulas);
    inc_ref(z3context, out_formula);

    // More cleanup.
    for (int i=0; i<no_subgoals; i++) {
      dec_ref(z3context, goal_formulas[i]);
    }

    apply_result_dec_ref(z3context, result);
    goal_dec_ref(z3context, goal);
    tactic_dec_ref(z3context, tseitinTactic);
    return out_formula;
```

It is scary even if I remove the clean-up code.
Is it possible to request for `apply_result_as_ast` function (I can write the patch if required), so that C API will have such a conversion? (Python API and C++ API already have it, I believe).

**Comment by wintersteiger** [comment]
Hmm, not convinced we really want that. It wouldn't be hard to add, but we don't want to start adding all kinds of functionality at a higher level of abstraction, that is really what the other APIs are for. The C API is "scary" everywhere, so this would just be a tip of an iceberg. 

Indeed, the Python and the C++ API have an as_expr function on goals, but not on apply_results. I've now also added this on goals in .NET, Java, and ML.  

I think there may also be a problem with your implementation as subgoals in Z3 are disjunctive, i.e., 

    long out_formula = mk_and(z3context, goal_formulas.length, goal_formulas);

should be 

    long out_formula = mk_or(z3context, goal_formulas.length, goal_formulas);

**Comment by cheshire** [comment]
Thank you, there was indeed a bug!

As you wish, but after applying tactic on an expression (at least to me) it feels natural to be able to get an expression back without writing hundred lines of code.

**Comment by wintersteiger** [comment]
Not sure what you are referring to, is there a function that applies a tactic to directly to a Z3_ast? I can only find Z3_tactic_apply and Z3_tactic_apply_ex which both take a Z3_goal and return a Z3_apply_result.

In general, the C API will always require a larger number of lines of code than any other API, because of the code required for reference counting, and indeed that's also what makes up the bulk of your implementation. The C++ API is a shallow layer on top of that which relieves the user of those duties and it can be used alongside the C API, so my recommendation would be to use the C++ API where it makes things easier while keeping your legacy code in C.

**Comment by NikolajBjorner** [comment]
The code snippet in the bug report is already using C++, so you can use the C++ functionality from the Z3 C++ API. You will have to start out creating a "context" object. You can access Z3_context from this one (and live with the error handler it supplies), or you can write your own version of z3++.h where you initialize a context with a Z3_context pointer and assume external ownership, say. You will still have to reconcile error handling. Furthermore, you can create separate functions for separate functionality. For example, the function that extracts conjuncts from a resulting goal would be an example of a separate function that can be written on top of the API. There are many auxiliary functions that one can think of and baking them into the APIs will not be easy to maintain across supported languages.
