### ISSUE TITLE
z3-solver package on Python package index doesn't include Python 3 wheels

### ISSUE THREAD

**Issue by jfinkels** [Z3Prover/z3#1254]
https://pypi.python.org/pypi/z3-solver

The `z3-solver` package only has Python 2 wheels, but I expect it to have Python 3 wheels as well, since the documentation seems to suggest that there is Python 3 support.

**Comment by NikolajBjorner** [comment]
Seems the instructions are to post issues at https://github.com/angr/angr-z3

**Comment by jfinkels** [comment]
Great, thank you! I'll do that.
