### ISSUE TITLE
[Feature Request] Named function simplification

### ISSUE THREAD

**Issue by cchan** [Z3Prover/z3#1255]
Feature request. For example:

```python
from z3 import *
def Abs(x):
    return If(x>=0, x, -x)
a,b,c = Ints("a b c")
simplify(Abs(a*b*c + a*b**2 + a + b + c**2 ))
```
outputs
```
If(a*b*c + a*b**2 + a + b + c**2 >= 0,
   a*b*c + a*b**2 + a + b + c**2,
   -1*a*b*c + -1*a*b**2 + -1*a + -1*b + -1*c**2)
```
Which is for readability reasons rather suboptimal. It gets worse for real big equations.

If it were possible to assign a name to the function, for example by a decorator `@NamedFunction('Abs')` or something, and then to treat that function as native (like `If`) we can have a better, simpler output.

```
Abs(a*b*c + a*b**2 + a + b + c**2)
```

**Comment by NikolajBjorner** [comment]
I am not sure what this feature request really means. 
You somehow want Z3 to recognize sub-terms and reproduce macros in some bottom-up or top-down manner. In this case you would have to supply a set of macros and retrieve them over the term.
Such a function could be written outside of Z3 based on the API: It will have to implement a pattern matcher that matches modulo equalities that you can infer from using the simplifier. So to me it seems more like a nice opportunity to produce an example (in python) that realizes this functionality.

**Comment by wintersteiger** [comment]
(Also, the pretty-printer has an option to guide the introduction of let-terms called `pp.min_alias_size`, which may be helpful for this purpose.)

**Comment by NikolajBjorner** [comment]
declaring Abs as a _recursive_ function delays expansion until solving time. So this is one option.
