### ISSUE TITLE
Segfault when string in algebraic datatype

### ISSUE THREAD

**Issue by Muon** [Z3Prover/z3#1257]
```smt2
(declare-datatypes () ((Val (Str (str String)))))
```
causes a segmentation fault on current master.

**Comment by Muon** [comment]
Windows 7, 32-bit build, Release configuration using the VS 2015 compiler with the default build instructions. I've captured a dump with WinDbg, it seems to be something while setting up the bitvector theory?
[z3dump.zip](https://github.com/Z3Prover/z3/files/1309704/z3dump.zip)

**Comment by wintersteiger** [comment]
Is any parallelism involved? According to what I get from the dump, it crashed while trying to set an OpenMP lock.

**Comment by Muon** [comment]
There shouldn't be any, I think. I didn't enable OpenMP in the build (to my knowledge) and I didn't pass anything like that to Z3. I just ran the binary on the file.

**Comment by wintersteiger** [comment]
Hmm, sorry, I still can't reproduce it with VS2015/x86/release. Could you try building a debug binary on your end to get a bit more information out of it?

**Comment by NikolajBjorner** [comment]
Try a clean build. Sometimes it happens that builds that are based on previous versions of the code base behave badly. Issues like the ones you report are symptomatic of this. I am also unable to reproduce the problem.

**Comment by Muon** [comment]
Hmm, the issue disappeared when I made a clean build. I wonder what caused it originally, though!

**Comment by NikolajBjorner** [comment]
What I say is that a non-clean build can mix up incompatible object files. 
The format for algebraic datatypes recently changed dramatically. If you had any stale object files laying around that did not get rebuilt it would explain the crash.
