### ISSUE TITLE
Z3Py: weird behaviour

### ISSUE THREAD

**Issue by dennis714** [Z3Prover/z3#1264]
This innocently looking code can throw exception:

    from z3 import *

    def factor(n):
        print "factoring",n

        in1,in2,out=Ints('in1 in2 out')

        s=Solver()
        s.add(out==n)
        s.add(in1*in2==out)
        # inputs cannot be negative and must be non-1:
        s.add(in1>1)
        s.add(in2>1)

        if s.check()==unsat:
            print n,"is prime (unsat)"
            return [n]

        m=s.model()
        # get inputs of multiplier:
        in1_n=m[in1].as_long()
        in2_n=m[in2].as_long()

        print "factors of", n, "are", in1_n, "and", in2_n
        # factor factors recursively:
        rt=factor (in1_n) + factor (in2_n)
        return sorted(rt)

    #print factor(2147713027) # works
    print factor(1234567890123) # exception

Like this:

    factoring 1234567890123
    factors of 1234567890123 are 348649503 and 3541
    factoring 348649503
    factors of 348649503 are 3 and 116216501
    factoring 3
    3 is prime (unsat)
    factoring 116216501
    Traceback (most recent call last):
      File "MWE.py", line 31, in <module>
        print factor(1234567890123)
      File "MWE.py", line 26, in factor
        rt=factor (in1_n) + factor (in2_n)
      File "MWE.py", line 26, in factor
        rt=factor (in1_n) + factor (in2_n)
      File "MWE.py", line 19, in factor
        m=s.model()
      File "/usr/lib/python2.7/dist-packages/z3.py", line 5989, in model
        raise Z3Exception("model is not available")
    z3types.Z3Exception: model is not available

... but it works if to try first number to factor.
z3 v4.5.0.
Something with recursion?

**Comment by dennis714** [comment]
Same for commit cd24535e51263d8447efea9b917977863b97d8e5

**Comment by NikolajBjorner** [comment]
Z3 is incomplete for non-linear integer arithmetic. It can return "unknown". In this case there is no model. You can only expect a model if Z3 return "sat".

**Comment by dennis714** [comment]
Ah, I forgot to check against "unknown". My fault!
