### ISSUE TITLE
possible bug in z3 ddnf implementation

### ISSUE THREAD

**Issue by kheradmand** [Z3Prover/z3#1268]
There is some difference between the ddnf algorithm described in [ddnf's paper](https://www.microsoft.com/en-us/research/wp-content/uploads/2015/11/An-Efficient-Data-Structure-for-Header-Spaces.pdf) and the z3 implementation of it.
Due to [this line](https://github.com/Z3Prover/z3/blob/cd24535e51263d8447efea9b917977863b97d8e5/src/muz/ddnf/ddnf.cpp#L195) in the the implementation, the data structure that is created after inserting a list of ternary bit vectors (tbvs) might be different from what is described in the paper. 
For example, after inserting `11`, `1x`, `x1`, the expected data structure according to the paper (or at least my understanding of it) should look like this:
```
      xx
    /    \
   x1    1x
    \    /
      11
```

However, here is the result of calling `display` function on `ddnf_core` after inserting the above tbvs (in the given order): 
```
node[0: xx 2 3]
node[1: 11]
node[2: x1 1]
node[3: 1x]
```
As you can see the implementation does not add `11` as child of `1x`.
If I insert the tbvs in the reverse order, (`x1`, `1x`, `11`), the result is as expected:
```
node[0: xx 1 2]
node[1: x1 3]
node[2: 1x 3]
node[3: 11]
```

It looks like a bug in the implementation to me. I was wondering whether that is indeed the case or there is something that I am missing?

**Comment by kheradmand** [comment]
@NikolajBjorner I would be really thankful if you could share your opinion on this.

**Comment by NikolajBjorner** [comment]
Sorry, I have been deprived of bandwidth to take a look. It should be addressed now. Thanks

**Comment by kheradmand** [comment]
Thanks a lot for looking at it :)
