### ISSUE TITLE
z3str3 fails on problem z3 solves very quickly

### ISSUE THREAD

**Issue by pjljvandelaar** [Z3Prover/z3#1274]
With the attached (zipped) smt2 file, I had the following unexpected experience
[CustomersAndOrders.zip](https://github.com/Z3Prover/z3/files/1341108/CustomersAndOrders.zip)
Running with z3 gives almost immediately an answer:
```
C:\TorXakis>z3 CustomersAndOrders.smt2
(:name "Z3")
(:version "4.5.1 - build hashcode ed5058d225f6")
sat
```
Running with z3str3 takes forever....
```
C:\TorXakis>z3 smt.string_solver=z3str3 CustomersAndOrders.smt2
(:name "Z3")
(:version "4.5.1 - build hashcode ed5058d225f6")
```
I am not observing the claims in http://smt-workshop.cs.uiowa.edu/2017/slides/smt2017-Z3str3.pdf ... Should z3str3 not be faster than z3?

**Comment by pjljvandelaar** [comment]
I also observed a crash with z3str3 on files that are accepted by z3
[z3str3.crash.zip](https://github.com/Z3Prover/z3/files/1341296/z3str3.crash.zip)

**Comment by pjljvandelaar** [comment]
Both a crash and substantially longer calculation times for the last TorXakis example where undesired behavior was observed:
[z3str3.process12.zip](https://github.com/Z3Prover/z3/files/1341342/z3str3.process12.zip)

**Comment by NikolajBjorner** [comment]
@mtrberzi - can you take a look?

**Comment by pjljvandelaar** [comment]
@mtrberzi - Can you indicate how long it will take?

**Comment by mtrberzi** [comment]
@pjljvandelaar -- I have a few open issues at the moment, sorry for the long response, I will get to it this week.

**Comment by mtrberzi** [comment]
@pjljvandelaar -- I've diagnosed the crash on the instances in `z3str3.crash.zip`. I will upstream a patch once I have verified this doesn't break on other instances.

The crash in `z3str3.process12.zip` occurs with the sequence solver as well, and in the debugger it seems to be happening in the rewriter. 

@NikolajBjorner -- can you take a look at the instance `z3str3.process12Right.smt2` in `z3str3.process12.zip`? The failing assertion is in `ast/rewriter/rewriter_def.h:49` and occurs with `smt.string_solver=seq` as well as Z3str3.

The performance issues may be tricky and will take a bit longer to work on.

**Comment by pjljvandelaar** [comment]
@mtrberzi  Thanks for the update! 

Thanks for working on our issues!

**Comment by mtrberzi** [comment]
Opened #1341, this should fix the crash reported in `z3str3.crash.zip` for both instances.

**Comment by NikolajBjorner** [comment]
@mtrberzi, this still diverges, but for a new reason (MBQI keeps going). 
I fixed a divergence based on traversing an equivalence class.
This should generally be revisited: the equivalence class is on theory_var (integers) and not on expressions. The previous version would start with an expression that didn't occur in the equivalence class.

**Comment by pjljvandelaar** [comment]
Just tried with version "4.8.4 - build hashcode b40c2b2926ed".
All issues are gone!
