### ISSUE TITLE
Non-det. assertion violation in smt_internalizer.cpp

### ISSUE THREAD

**Issue by mschwerhoff** [Z3Prover/z3#1276]
[This SMT file](https://github.com/Z3Prover/z3/files/1343970/logfile-01.zip) non-deterministically (probably due to lots of timeouts) triggers an assertion violation:

```
ASSERTION VIOLATION
File: ..\src\smt\smt_internalizer.cpp
Line: 962
m_cg_table.contains_ptr(e)
```

Be warned: it took me about 30 invocations of Z3 revision bba0051 to trigger the assertion violation.

**Comment by NikolajBjorner** [comment]
It is very difficult to get solid repros using timeouts. The rlimit feature is much better. To get repros for this I am trying the following approach: [Fuzz.py](https://github.com/NikolajBjorner/nikolajbjorner.github.io/tree/master/z3bugs/fuzz.py)

on a variant of your file: [smtlib-01.smt2](https://github.com/NikolajBjorner/nikolajbjorner.github.io/tree/master/z3bugs/logfile-01.smt2)

While rather crude, it is effective in finding crashes (2 so far, 1 fixed locally).

**Comment by mschwerhoff** [comment]
Nifty trick, @NikolajBjorner :-) I'll keep your script in mind in case I run into a similar issue. Ditching timeouts in favour of rlimits is on my to-do list.

Thank you for fixing the issue so quickly!
