### ISSUE TITLE
Z3Exception is raised when accessing AccessorDecls of Constructor object.

### ISSUE THREAD

**Issue by SMTStuck** [Z3Prover/z3#1279]
**Edit:** Have just thought to run the examples, and have just tried running the ForrestExample and have the same error - this appears to be an issue with `AccessorDecls` on a `Constructor` object.

I am using the .NET bindings, and the latest nightly build (z3-4.5.1.05428314be0a-x64-win) and am trying to take the following SMT script to the API equilvalent:

> (declare-datatypes () ((Pair (mk-Pair (first Int) (second Int)))))
(declare-const p1 (Pair))
(assert (> (first p1) 50))
(assert (> (second p1) 100))
(check-sat)

I am trying to work out the required code using the examples, but am getting a Z3 exception. Although I am having great difficulty working out the required code from the examples given, which leads me to believe it is more than likely a user error! Nevertheless, I would appreciate a little input:

> Unhandled Exception: Microsoft.Z3.Z3Exception: invalid argument
   at Microsoft.Z3.Native.Z3_query_constructor(IntPtr a0, IntPtr a1, UInt32 a2, IntPtr& a3, IntPtr& a4, IntPtr[] a5)
   at Microsoft.Z3.Constructor.get_AccessorDecls()

The code I have is:

>//Create the mk-pair constructor.
var cons = ContextObj.MkConstructor("mk-pair", "is_mk-pair", new string[] { "first", "second" }, new Sort[] { ContextObj.IntSort, ContextObj.IntSort });
var cons_accessors = cons.AccessorDecls;				
>
>//Create the Pair DataTypeSort along with two constants - p1 and p2.
var datatypesort = ContextObj.MkDatatypeSort("Pair", new Constructor[] { cons });
var p1 = ContextObj.MkConst("p1", datatypesort);
var p2 = ContextObj.MkConst("p2", datatypesort);				
>
>//Access "first" of p1.
ContextObj.MkApp(cons_accessors[0], p1);

The exception is being raised on the line  `var cons_accessors = cons.AccessorDecls;`.

**Comment by NikolajBjorner** [comment]
Did you try to move the line var cons_accessors = cons.AccessorDecls; to _after_ the MkDatatypeSort call is made? The attributes associated with datatypes are not initialized until the entire datatype is created.

**Comment by NikolajBjorner** [comment]
Can you confirm that reordering the call to the accessor declerations solves this?

**Comment by SMTStuck** [comment]
Hi Nikola. Thanks for the reply, I've just tested your suggestion and yes, it would appear that changing the order solves this issue.
