### ISSUE TITLE
[UBSan] Multiple instances of undefined behaviour when running Z3 unit tests

### ISSUE THREAD

**Issue by delcypher** [Z3Prover/z3#1288]
When building Z3 with UBSan,  when the unit tests are executed (`./test-z3 /a`) the following errors are reported.

```
/home/user/z3_src/src/muz/rel/tbv.cpp:79:25: runtime error: shift exponent 69 is too large for 64-bit type 'unsigned long long'
/home/user/z3_src/src/util/mpz.cpp:564:26: runtime error: negation of -2147483648 cannot be represented in type 'int'; cast to an unsigned type to negate this value to itself
```

This is for 110d558ee4262721f3ab2c999d789eaf84ac15d6

**Comment by delcypher** [comment]
@NikolajBjorner Thanks. I don't see any reference to commit that also fixes the other reported error

```
/home/user/z3_src/src/util/mpz.cpp:564
```

Did you miss that one?

**Comment by NikolajBjorner** [comment]
Thanks, I didn't notice this was for something different.
