### ISSUE TITLE
Z3.mk_context is blocking

### ISSUE THREAD

**Issue by Drup** [Z3Prover/z3#129]
On unstable, for some reason, `Z3.mk_context` (from the OCaml API) is blocking and never returns. I'm not sure what's happening exactly. I can do a strace if you want (it's a bit long ...)

**Comment by wintersteiger** [comment]
Does this happen right from the start, or does it work for some number of times and only then it blocks? Also, is there any kind of parallelism/concurrency involved? An strace would definitely help; could you perhaps upload it into a [gist](https://gist.github.com) or something similar?

**Comment by Drup** [comment]
In the meantime, I rollbacked to an old version of Z3 unstable and now that I recompiled everything with a recent version, I can't reproduce anymore....

It was happening right from the start, without parallelism/concurrency. Literally just a file with `Z3.km_context []` in it was enough. 

If I get the same behavior, I will reopen.

**Comment by NikolajBjorner** [comment]
Yes, that might be it. Sometimes incremental builds don't link correctly, leading to inexplicable behavior. Clean builds help ruling this out.
