### ISSUE TITLE
The presence of an intermediate (check-sat) makes this query unknown.

### ISSUE THREAD

**Issue by percontation** [Z3Prover/z3#1291]
Z3 returns unknown for [test.smt2.txt](https://github.com/Z3Prover/z3/files/1364246/test.smt2.txt) (at least on the current master, 7e4f5322).

However, after removing the extra `(check-sat)`s on lines 20 and 21, Z3 returns satisfiable (for `(check-sat)` at the end of the file).

On 1d12a9c86de (from yesterday), removing only one of the two sequential `(check-sat)`s was sufficient to make the final query satisfiable. This seems even more surprising to me.

Apologies for the noise if issues like this are well-known; I just hadn't encountered this behavior before.

**Comment by percontation** [comment]
I have no idea if it's meaningful, but:

Prior to noticing that removing the intermediate (check-sat)s changes the result, I'd empirically guessed (via git bisect) that the issue was a regression introduced by 05447d61. The following patch that partially reverts 05447d61 makes the smt2 file in question work, even with the additional (check-sat)s. I did not attempt to determine why.

```
diff --git a/src/ast/fpa/bv2fpa_converter.cpp b/src/ast/fpa/bv2fpa_converter.cpp
index 93bd7957..b61ab2aa 100644
--- a/src/ast/fpa/bv2fpa_converter.cpp
+++ b/src/ast/fpa/bv2fpa_converter.cpp
@@ -290,16 +290,7 @@ func_interp * bv2fpa_converter::convert_func_interp(model_core * mc, func_decl *
                       tout << mk_ismt2_pp(bv_args[i], m) << " == " <<
                         mk_ismt2_pp(new_args[i], m) << std::endl;
                   tout << mk_ismt2_pp(bv_fres, m) << " == " << mk_ismt2_pp(ft_fres, m) << std::endl;);
-            func_entry * fe = result->get_entry(new_args.c_ptr());
-            if (fe == 0)
-                result->insert_new_entry(new_args.c_ptr(), ft_fres);
-            else {
-                // The BV model may have multiple equivalent entries using different
-                // representations of NaN. We can only keep one and we check that
-                // the results for all those entries are the same.
-                if (ft_fres != fe->get_result())
-                    throw default_exception("BUG: UF function entries disagree with each other");
-            }
+            result->insert_new_entry(new_args.c_ptr(), ft_fres);
         }

         app_ref bv_els(m);
```

**Comment by percontation** [comment]
Ah, also worth mentioning: I reproduced everything here consistently across separate linux and mac machines, using `z3/build/z3 -smt2 test.smt2.txt`. (So despite the fickle appearance of this issue, I'm pretty sure it's not just me.)

**Comment by wintersteiger** [comment]
That particular part of https://github.com/Z3Prover/z3/commit/05447d612a35af824212c696c3f899a11113093f contains a check for buggy NaN models. Reverting that bit of code just disables the check and admits buggy models. When Z3 throws an assertion like here, the end result is an unknown result down the line.

That said, I don't get the unknown result anymore, the latest master works fine and produces a correct model for me. I'm fairly sure I fixed all those issues shortly after https://github.com/Z3Prover/z3/commit/05447d612a35af824212c696c3f899a11113093f, so could you give this another try to see whether there still is a problem?

**Comment by NikolajBjorner** [comment]
you can ignore the above commit. It is unrelated to this issue

**Comment by percontation** [comment]
...every time I try minifying my example things get weird.

Currently on master (2cab1ccc) these two test cases return different results, but the only difference in them is a symbol name.

[test2.smt2.txt](https://github.com/Z3Prover/z3/files/1476165/test2.smt2.txt) gives me `sat; sat`
[test2_long_name.smt2.txt](https://github.com/Z3Prover/z3/files/1476168/test2_long_name.smt2.txt) gives me `sat; unknown`

**Comment by percontation** [comment]
...and when I attempted to confirm this on another platform, I appear to get the opposite: test2.smt2.txt yielding `sat; sat`, and test2_long_name.smt2.txt yielding `sat; unknown`.

So let me know if you have trouble reproducing this, and I can look for something more consistent.

**Comment by NikolajBjorner** [comment]
test2_long_name.smt2 reproduces on my end. 
It exposes a bug that is detected in bv2fpa_converter.cpp. 
It raises an exception and so the result is unknown.

**Comment by wintersteiger** [comment]
Got it! The bug check was indeed too strong, should be fine now.
