### ISSUE TITLE
speed up Optimize()

### ISSUE THREAD

**Issue by YueJiang-nj** [Z3Prover/z3#1292]
I want to solve a constraint system using z3py which contains soft constraints (they are not forced to be true) and hard constraint, with no quantifiers. 
I am using o = Optimize() to define it, and "add_soft" to add soft constraints and "add" to add hard constraints.
 However, it is too slow. How can i make the system be solved faster?

statistics() shows that:
(:added-eqs              2
 :arith-add-rows         144947
 :arith-assert-lower     925855
 :arith-assert-upper     768855
 :arith-bound-prop       7183
 :arith-conflicts        128
 :arith-gcd-tests        159
 :arith-gomory-cuts      1
 :arith-ineq-splits      8
 :arith-pivots           19308
 :binary-propagations    5220337
 :conflicts              8625
 :decisions              635248
 :del-clause             3
 :eliminated-vars        13
 :final-checks           2781
 :max-memory             4.18
 :maxres-cores           330
 :maxres-correction-sets 1
 :memory                 4.13
 :minimized-lits         11062
 :mk-bool-var            2792
 :mk-clause              15044
 :num-allocs             28254715
 :num-checks             4554
 :propagations           7691166
 :rlimit-count           15938039)

**Comment by NikolajBjorner** [comment]
I am not sure

**Comment by YueJiang-nj** [comment]
Is it possible to add soft constraints to Solver?
