### ISSUE TITLE
z3py question (dump_benchmarks)

### ISSUE THREAD

**Issue by YueJiang-nj** [Z3Prover/z3#1295]
How can i use dump_benchmarks in Optimize()?
I used 
o = Optimize()
o.dump_benchmarks = True

Then how can i see the profile?

**Comment by NikolajBjorner** [comment]
Regarding the first question: 
From Python you can just use the standard string serialization method on the optimize object to print the state. For example:

           o = Optimize()
           o.add(formula)
           o.add_soft(soft_constraint)
           print(o)


I am not sure about "Then how can i see the profile?" This question is too cryptic to understand. Please elaborate in your questions. The questions you have posed in the past few days have not been very actionable as they are generally not well posed.

**Comment by YueJiang-nj** [comment]
Sorry! I did not state my question clearly.
I am developing an interactive project. So the speed is very important. 
However, when I use z3py to solve the system in my project, if I added a lot of constraints to the system, it becomes super slow to solve it. 
So "Profile" means I want to know which part in my system is slow so that i can find out where I can modify.
And I also want to know whether there is any way to help me accelerate the speed provided a large number of constraints. (like if a direction is using a lot of time, whether we can stop it and find another direction to try to find a solution)

**Comment by wintersteiger** [comment]
There is no magical spell we can cast to "make it fast". This depends entirely on the number and nature of your constraints, the decision/optimization procedure Z3 decides to run on them, and its configuration. If you have reasons to believe that it should be faster on some particular queries, we can perhaps formalize those reasons to help the solver, but without that or concrete example queries it's neigh on impossible. 

You can always set a timeout or rlimit on solver calls, such that it won't exceed some pre-defined resource limits, and if it returns without a solution, you can then change your assertions before issuing another solver call.
