### ISSUE TITLE
[ASan] maxsat example leaks memory

### ISSUE THREAD

**Issue by delcypher** [Z3Prover/z3#1299]
The maxsat example is leaking a lot of memory. There are raw calls to `malloc()` that are not being freed.

Attached is the LeakSanitizer report for Z3 at commit cae414e575299d976899b764041195ff36f484e9.

[lsan-maxsat.zip](https://github.com/Z3Prover/z3/files/1370034/lsan-maxsat.zip). The report is rather large.

**Comment by NikolajBjorner** [comment]
This is definitely a "won't fix". The maxsat example was written well before there was a nice C++ wrapper.

**Comment by delcypher** [comment]
@NikolajBjorner Thanks for clarifying. In CI I will just not run leak checking on this example then.
