### ISSUE TITLE
fp.isNegative does not handle NaN properly

### ISSUE THREAD

**Issue by LeventErkok** [Z3Prover/z3#13]
This is on the unstable branch.

For this benchmark:

```
(set-option :produce-models true)
(set-logic QF_FP)
(declare-fun s0 () (_ FloatingPoint 11 53))
(assert
   (let ((s1 (and (fp.isNaN s0) (fp.isNegative s0))))
   s1))
(check-sat)
(get-value (s0))
```

Z3 produces:

```
sat
((s0 (_ NaN 11 53)))
```

Which suggests `NaN` is accepted by the predicate `fp.isNegative`. According to the formalization, `fp.isNegative` holds for `-0.0` and when the number `lt` compares to `0` successfully, neither of which is true for `NaN`.

**Comment by wintersteiger** [comment]
Fixed in unstable, thanks again!
