### ISSUE TITLE
[ASan] Leaks while running some string regression tests.

### ISSUE THREAD

**Issue by delcypher** [Z3Prover/z3#1309]
When building with ASan and running the following examples

```
regressions/smt2/string3.smt2
regressions/smt2/string4.smt2
```

leaks are reported. The attached
[string3_leak.txt.zip](https://github.com/Z3Prover/z3/files/1385400/string3_leak.txt.zip) contains the log when running the `string3.smt2` regression test. The log is rather big which is why it is not shown verbatim here.

**Comment by NikolajBjorner** [comment]
@mtrberzi could you take a look the report and my fix?

**Comment by delcypher** [comment]
@NikolajBjorner Your fix has stopped ASan reporting a leak.

**Comment by mtrberzi** [comment]
Should be fine.
