### ISSUE TITLE
Crash on 64-bit build run on Windows 8.1 when linked with /DYNAMICBASE and /HIGHENTROPYVA

### ISSUE THREAD

**Issue by dewtell** [Z3Prover/z3#131]
In a 64-bit Windows build of z3 with the link options /DYNAMICBASE and /HIGHENTROPYVA, z3 crashes on the following SMT2 input when run on a Windows 8.1 machine:

(set-info :status unknown)
(declare-fun out@0 () (_ BitVec 3))
(declare-fun reset_N@0 () Bool)
(declare-fun reset_N@1 () Bool)
(assert
(let ((?x16 (ite reset_N@0 (ite (bvule (_ bv4 3) out@0) (_ bv1 3) (bvadd out@0 (_ bv1 3))) (_ bv0 3))))
(let (($x21 (bvule (ite reset_N@1 (ite (bvule (_ bv4 3) ?x16) (_ bv1 3) (bvadd ?x16 (_ bv1 3))) (_ bv0 3)) (_ bv4 3))))
(not $x21))))
(check-sat)

The crash does not occur when the link option /HIGHENTROPYVA:NO is used instead, nor does it occur when the same executable is run on Windows 7.  As far as we can tell, the most likely cause of this is a 64 bit pointer->32 bit->64 bit conversion somewhere in the z3 code that is stripping the high-order bits of the pointer, combined with Windows 8 putting more data than Windows 7 does above the 32-bit barrier when /HIGHENTROPYVA is on.  We are concerned about this for our customers who require a 64-bit Windows version of our program to hold all their data - they may run into random crashes if z3 allocates data above the 32-bit barrier, regardless of the link settings used, unless this issue is addressed.  (In other words, our major concern isn't how to run this exact test case without crashing, but making sure that z3 is truly 64-bit clean.)

We are compiling with Visual C++ 2013.

**Comment by NikolajBjorner** [comment]
So, is this what your config.mk looks like?
CC=cl
CXX=cl
CXX_OUT_FLAG=/Fo
OBJ_EXT=.obj
LIB_EXT=.lib
AR=lib
AR_OUTFLAG=/OUT:
EXE_EXT=.exe
LINK=cl
LINK_OUT_FLAG=/Fe
SO_EXT=.dll
SLINK=cl
SLINK_OUT_FLAG=/Fe
OS_DEFINES=/D _WINDOWS
AR_FLAGS=/nologo
LINK_FLAGS=/nologo /MDd
SLINK_FLAGS=/nologo /LDd
CXXFLAGS=/c /Zi /nologo /W3 /WX- /Od /Oy- /D WIN32 /D _AMD64_ /D _DEBUG /D Z3DEBUG  /openmp /D _CONSOLE /D _TRACE /D _WINDOWS /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Gd /analyze-
LINK_EXTRA_FLAGS=/link /DEBUG /MACHINE:X64 /SUBSYSTEM:CONSOLE /INCREMENTAL:NO /STACK:8388608 /OPT:REF /OPT:ICF /TLBID:1 /DYNAMICBASE /NXCOMPAT /HIGHENTROPYVA
SLINK_EXTRA_FLAGS=/link /DEBUG /MACHINE:X64 /SUBSYSTEM:WINDOWS /INCREMENTAL:NO /STACK:8388608 /OPT:REF /OPT:ICF /TLBID:1 /DYNAMICBASE /HIGHENTROPYVA

**Comment by dewtell** [comment]
I just found out that this executable was compiled without the _AMD64_ option, and if the _AMD64_ option is enabled, the crash goes away.  So the issue may have been in our generation of a VS sln file for this executable without this option.  The nmake build for z3 out of the box on 64-bit seems to use this option.

**Comment by dewtell** [comment]
That should be with underscores, not italics, on the name of the option.

**Comment by NikolajBjorner** [comment]
Good, I will try to repro without the \_AMD64\_ option, because I could not repro it on my side so far.
It would also be consistent with 64bit specific behavior in src/sat/sat_clause.cpp and compatible with your benchmark that will use the sat engine.

**Comment by NikolajBjorner** [comment]
Yep, it crashes without \_AMD64\_ option for the reason I gave above. You should make sure to include it in the build.
