### ISSUE TITLE
Z3 does not correctly report unsat: missing modulo condition under quantifier

### ISSUE THREAD

**Issue by alexanderjsummers** [Z3Prover/z3#1311]
For the following small example, Z3 appears to instantiate the quantifier as expected, and knows the LHS of the implication to be true, but doesn't obtain the RHS (we get unknown).

```
(declare-fun bar (Int) Bool)
(declare-fun foo (Int) Bool)
(declare-fun i () Int)
(assert (forall ((x Int) ) (!  (and (=> (= (mod x 2) 0) (foo x)) (bar x))
 :qid |onlyQuant|
 :pattern ( (bar x))
)))
(assert (bar (* 2 i)))
;(assert (not (= (mod (* 2 i) 2) 0))) ; uncommenting results in unsat - Z3 knows 2*i mod 2 == 0
;(assert (not (bar (* 2 i)))); uncommenting results in unsat - quantifier is instantiated
(assert (not (foo (* 2 i)))); reports unknown
(check-sat)
```

**Comment by alexanderjsummers** [comment]
In case it's helpful, here is the (almost) analogous Boogie code:

```
function foo(i: int): bool;
function bar(i: int): bool;

procedure test(i:int) returns ()
{  
      assume (forall x: int ::
        { bar(x) }
        (x mod 2 == 0 ==> foo(x))
        && bar(x)
      );
    assert bar(2*i); // passes due to quantifier instantiation
    assert 2*i mod 2 == 0; // makes no difference (passes)
    assert foo(2*i); // fails
}
```

**Comment by NikolajBjorner** [comment]
Seems like this is a case where you get what you pay for.
Besides, the fact that Z3 is free, you must be using Z3 with MBQI turned off.
In this case it is bound to the patterns that you specify. Without specifying a pattern with foo, it has no way to instantiate the quantifier.
Either adding the pattern (foo x) or enabling MBQI (by default) generates unsat for me.

**Comment by alexanderjsummers** [comment]
Hi Nikolaj,

Thanks for the speedy reply. In this case, I think that the term ``(bar (* 2 i))`` should already match the existing pattern, so that e-matching should be enough. It does seem that the quantifier instantiation happens, as the commented-out assertions work as expected. Is there a reason why the implication from the quantifier body wouldn't be available for proving the desired property?

I'm indeed running with MBQI turned off - this is a heavily cut-down example from a verification problem (where MBQI isn't an option because of other quantifiers in the problem). For me, changing the pattern doesn't help, either (with the settings which Boogie uses). Here is the full file (with that change made):

```
(set-option :print-success false)
(set-info :smt-lib-version 2.0)
(set-option :AUTO_CONFIG false)
(set-option :pp.bv_literals false)
(set-option :MODEL.V2 true)
(set-option :smt.PHASE_SELECTION 0)
(set-option :smt.RESTART_STRATEGY 0)
(set-option :smt.RESTART_FACTOR |1.5|)
(set-option :smt.ARITH.RANDOM_INITIAL_VALUE true)
(set-option :smt.CASE_SPLIT 3)
(set-option :smt.DELAY_UNITS true)
(set-option :NNF.SK_HACK true)
(set-option :smt.MBQI false)
(set-option :smt.QI.EAGER_THRESHOLD 100)
(set-option :TYPE_CHECK true)
(set-option :smt.BV.REFLECT true)
; done setting options


(declare-fun bar (Int) Bool)
(declare-fun foo (Int) Bool)
(declare-fun i () Int)
(assert (forall ((x Int) ) (!  (and (=> (= (mod x 2) 0) (foo x)) (bar x))
 :qid |onlyQuant|
 :skolemid |0|
 :pattern ( (foo x))
)))
(assert (bar (* 2 i)))
(assert (not (foo (* 2 i))))
(check-sat)
```

**Comment by NikolajBjorner** [comment]
Doesn't repro on my side. Returns unsat.

**Comment by alexanderjsummers** [comment]
Hi Nikolaj,

Ok, I'll double-check the versions - thank you. I tried locally and on rise4fun so far, and saw the reported behaviour.

Is there a reason why the original example shouldn't work (i.e. without changing the pattern) with e-matching?

Thanks, Alex

**Comment by NikolajBjorner** [comment]
The original example should _not_ work if the pattern is "bar" and the assertion is about "foo" and requires quantifier instantiation (with MBQI disabled so quantifiers may only be instantiated if there is an active pattern that triggers it).

**Comment by alexanderjsummers** [comment]
Hi Nikolaj,

Shouldn't the line ``(assert (bar (* 2 i)))`` cause the quantifier instantiation to happen, with the pattern "bar"? It seems this should be in scope for the check-sat. Also, writing ``(assert (not (bar (* 2 i))))`` (as in the commented line) yields unsat, which I assumed meant that the instantiation does happen even with this pattern.

Thanks, Alex

**Comment by NikolajBjorner** [comment]
It's not necessarily the case: Boogie may ask Z3 to verify the conjunction of the two assertions, so the disjunction of their negations are unsat. For the branch where "bar" occurs, the quantifier is instantiated. This could get lost in other branches. Z3 limits quantifier instantiation based on an approach that resembles a tableau search, which is similar to what Simplify does. You can disable the tableau mode by setting relevancy propagation to other values than 2.

**Comment by alexanderjsummers** [comment]
Thanks again. The Boogie query is indeed a lot more complicated, but I tried running the smt queries above by hand - in particular, so that there's only one check-sat, then.

My understanding was (and we use this property fairly often, so I hope it's true) that the first``assert`` command will add the corresponding `bar` term to Z3's scope (and to the e-graph, for potential matching). Checking statistics for the run confirms that a quantifier instantiation happens; the body of the quantifier should be sufficient to get unsat.

It does seem that this works in most other situations - I have the impression that the unexpected behaviour has to do with the modulo condition inside the quantifier. In particular, it seems I can change this to something else, and I still get unsat as expected. For example, changing that line to
``(assert (forall ((x Int) ) (!  (and (=> (bar x) (foo x)) (bar x))`` 
(i.e. replacing the modulo condition with another occurrence of (bar x), as shown in the query below) gives me unsat, even with the old trigger (again, a single quantifier instantiation happens).
The modulo condition on the left of the implication is also one that Z3 can prove outside of the quantifier.
```
(declare-fun bar (Int) Bool)
(declare-fun foo (Int) Bool)
(declare-fun i () Int)
(assert (forall ((x Int) ) (!  (and (=> (bar x) (foo x)) (bar x))
 :qid |onlyQuant|
 :pattern ( (bar x))
)))
(assert (bar (* 2 i)))
(assert (not (foo (* 2 i)))); reports unsat for this version without modulo, as expected
(check-sat)
```

**Comment by alexanderjsummers** [comment]
Hi again. It seems this behaviour is indeed as I had hoped (also for the original smt input) in the latest Z3 master version (which I just compiled to check). Sorry for the confusion!

Thanks, Alex
