### ISSUE TITLE
Strange Unknown result with quantifiers.

### ISSUE THREAD

**Issue by skicombinator** [Z3Prover/z3#1313]
Considering following problem:
```
(declare-const p Bool)
(assert (=> p (forall ((a Int))
		       (=> (not (= a 0)) (= a 0)))))

(assert-soft p :weight 1)
(check-sat)
(get-info :reason-unknown)
```
Z3 gives answer: "(incomplete quantifiers)". But the quantifiers are not incomplete.

Just substituting 0 to 1 like following solves the problem.
```
(declare-const p Bool)
(assert (=> p (forall ((a Int))
		       (=> (not (= a 1)) (= a 1)))))

(assert-soft p :weight 1)
(check-sat)
(get-info :reason-unknown)
```
In this case, Z3 gives answer: SAT. 
I think both problems are the same, but I don't understand why Z3 behave differently.

**Comment by johnduck** [comment]
Does anybody have any clues about this issue?

**Comment by NikolajBjorner** [comment]
There is basically no tuning on the Z3 side for optimization + quantifiers, so you will likely end up with cases where Z3 takes forever on quantifiers + optimization or otherwise produces uneven results.
