### ISSUE TITLE
Unsupported (include ...) in Java library parser

### ISSUE THREAD

**Issue by facanferff** [Z3Prover/z3#1317]
When using context.parseSMTLIB2String with code that includes lines such as ```(include "other.z3")```, the parser says that "include" is unsupported.
However, using directly the executable it is supported.

**Comment by NikolajBjorner** [comment]
correct

**Comment by wintersteiger** [comment]
That's correct, SMT2 does not support `include`. This is a Z3-specific extension (and not very well tested anyways), so best to avoid if possible.
