### ISSUE TITLE
wrong result in optimization query

### ISSUE THREAD

**Issue by kfriedberger** [Z3Prover/z3#1326]
I have the following query and do not get the expected result. 
Is this a bug in Z3 or do I have wrong assumptions about optimization?

Query:
```
(declare-const x Int)
(declare-const y Int)
(declare-const z Int)
(assert (<= x 10))
(assert (<= y 10))
(assert (<= z 10))
(assert (= 10 (+ x y z)))
(maximize (+ 
  (ite (<= x 0) 10 0)
  (ite (<= x 4) 10 0)
  (ite (<= y 0) 4 0) 
  (ite (<= y 4) 4 0) 
  (ite (<= z 0) 2 0) 
  (ite (<= z 4) 10 0) 
))
(check-sat)
(get-model)
(get-objectives)
```

Output (z3 4.5.1 build on Ubuntu 16.04 64bit, from current master):
```
sat
(model 
  (define-fun y () Int
    10)
  (define-fun z () Int
    0)
  (define-fun x () Int
    0)
)
(objectives
 ((+ (ite (<= x 0) 10 0)
   (ite (<= x 4) 10 0)
   (ite (<= y 0) 4 0)
   (ite (<= y 4) 4 0)
   (ite (<= z 0) 2 0)
   (ite (<= z 4) 10 0)) 20)
)
```

I would expect that for the model-assignments the computed objective is `32` and not `20`.

If I use z3 4.4.1 (installed from Ubuntu 16.04 repository) instead of the self-compiled git-master, the expected value `32` is returned.

**Comment by LeventErkok** [comment]
I wonder if this is a mere "printing" problem? If you give your objective a name and explicitly ask for its value, you get the correct answer 32:

```
(declare-const x Int)
(declare-const y Int)
(declare-const z Int)
(assert (<= x 10))
(assert (<= y 10))
(assert (<= z 10))
(assert (= 10 (+ x y z)))
(define-fun goal () Int
   (+
     (ite (<= x 0) 10 0)
     (ite (<= x 4) 10 0)
     (ite (<= y 0) 4 0)
     (ite (<= y 4) 4 0)
     (ite (<= z 0) 2 0)
     (ite (<= z 4) 10 0)
   ))
(maximize goal)
(check-sat)
(get-model)
(get-objectives)
(get-value (goal))
```

To this, z3 says:

```
sat
(model
  (define-fun y () Int
    10)
  (define-fun z () Int
    0)
  (define-fun x () Int
    0)
)
(objectives
 ((+ (ite (<= x 0) 10 0)
   (ite (<= x 4) 10 0)
   (ite (<= y 0) 4 0)
   (ite (<= y 4) 4 0)
   (ite (<= z 0) 2 0)
   (ite (<= z 4) 10 0)) 20)
)
((goal 32))
```

which correctly says `goal` is `32`.

What's curious is if you play with the numbers a bit (change any of the `10`s to `12` or something else), the problem goes away.

Looks like a problem with the objective printing indeed.

**Comment by kfriedberger** [comment]
This is not just a "printing bug", but the objective (aka "handle") returns the wrong data.
We found the problem when using z3 via its API through our wrapper library.
A complete executable example can be found [here](https://github.com/sosy-lab/java-smt/blob/086b3e65a741d553788585c4688f7793fba49ad2/src/org/sosy_lab/java_smt/example/OptimizationFormulaWeights.java#L100).

**Comment by NikolajBjorner** [comment]
the bug was somewhat subtle and using an optimization that is somewhat rarely used, so this should explain why other constants didn't reproduce the problem.
