### ISSUE TITLE
expose constants "pi", "e", in java/C#/python wrappers

### ISSUE THREAD

**Issue by Groostav** [Z3Prover/z3#1327]
Currently there is no good way to to access the `pi` and `e` constants from the managed-language API wrappers.

Speaking only to the java API:

[api_ref.cpp](https://github.com/Z3Prover/z3/blob/7861cfcef28de2b2a71166da3be6d1c758ce5a04/src/api/api_rcf.cpp#L79) exposes to java a `long rcfMkPi(long var0)`, with public visibility. There are none of the traditional wrapper functions in `Context` that adapt this method from pointer-values to the traditional `Expr` java object wrappers one would expect. 

This means you either have to deal with pointer values yourself in an entirely un-idiomatic way, or you have to try and invoke the wrappers yourself with reflection. 

Alternatively, one can likely achieve the same ends by only using the SMT-lib (lisp) api. 

I created this issue in response to [this post on stackoverflow](https://stackoverflow.com/questions/46886468/using-pi-and-e-constants-from-z3-api?noredirect=1#comment80766015_46886468)

---

_to the latter idea_, my failed work-around can be found [here](https://gist.github.com/Groostav/a7aa6e0729734f6f94889c034074700b). Given the time pressures I'm under I will continue to hack my way around with reflection, with the intention of using the SMT-lib adapters if I cannot figure out what objects I need to wrap which pointer values. 

Specifically, it seems that `Expr.create(Native.rcfMkPi())` isn't quite right. Given that this issue cannot be immediately addressed, can somebody tell me which factory I would way to invoke to wrap the returned pointer?

**Comment by NikolajBjorner** [comment]
The rcf functionality is isolated from the rest of Z3. There are no methods for briding rcfs (Z3_rcf_num) with expressions (Z3_ast), so any untyped coercions should be expected to crash.

**Comment by Groostav** [comment]
@NikolajBjorner that sounds like a "wont-fix"

Before closing this issue, can you elaborate a little bit? What do you mean by "any untyped coercions"?

I'm trying to hack the value out via reflection --which might actually be illegal under java-9...

```kotlin
val exprCtor = Expr::class.staticFunctions
    .single { it.name == "create" && it.parameters.size == 2 }
    .apply { isAccessible = true }
val nCtxMember = Context::class.members
    .single { it.name == "nCtx" }
    .apply { isAccessible = true }
val nCtxPointer = nCtxMember.call(z3) as Long
val nativePiPointer = Native.rcfMkPi(nCtxPointer)
exprCtor.call(z3, nativePiPointer) as ArithExpr
```

This generates an invalid memory access (SIGSEGV) and kills the JVM. 

Any thoughts on what I should be doing?

**Comment by NikolajBjorner** [comment]
If you take a look at the C file called z3_rcf.h you will see that Z3_rcf_mk_pi returns a value of type Z3_rcf_num. There are no coercions available between Z3_ast and Z3_rcf_num. They live in different address spaces. So any code that pretends there is some coercion will crash. These RCF extensions are stand-alone and don't integrate with the rest of Z3.
