### ISSUE TITLE
theory not supported by interpolation or bad proof?

### ISSUE THREAD

**Issue by LeventErkok** [Z3Prover/z3#1330]
The following script used to work up till about a week ago, successfully returning an interpolant. But with a fresh build, I'm now getting:

```
(error "line 25 column 26: theory not supported by interpolation or bad proof")
```

Was this intentional? Or maybe it is indeed a case of `bad proof`?

Here's the script:

```
(set-option :produce-interpolants true)
(set-option :produce-models true)
(set-logic ALL) ; has unbounded values, using catch-all.
(define-fun s_2 () Bool false)
(define-fun s_1 () Bool true)
(define-fun s3 () Int 0)
(define-fun s7 () Int 1)
(declare-fun s0 () Int) ; tracks user variable "x"
(declare-fun s1 () Int) ; tracks user variable "y"
(declare-fun s2 () Int) ; tracks user variable "z"
(declare-fun array_0 () (Array Int Int))
(declare-fun array_1 () (Array Int Int))
(declare-fun array_2 () (Array Int Int))
(declare-fun array_3 () (Array Int Int))
(define-fun s4 () Bool (= array_1 array_3))
(define-fun s5 () Bool (= s0 s2))
(define-fun s6 () Int (select array_1 s2))
(define-fun s8 () Bool (= s6 s7))
(define-fun s9 () Bool (and s5 s8))
(assert (= array_2 (store array_0 s0 s3)))
(assert (= array_3 (store array_2 s1 s3)))
(assert (! s4 :named |c1|))
(assert (! s9 :named |c2|))
(check-sat)
(get-interpolant |c1| |c2|)
```

About a week ago, this used to successfully print:

```
(interpolants
        (and (= (select array_1 s0) (select (store array_2 s1 0) s0))
            (or (= 0 (select array_1 s0)) (not (= s0 s1)))))
```

but not any longer. Now I get:

```
(error "line 25 column 26: theory not supported by interpolation or bad proof")
```

**Comment by LeventErkok** [comment]
Works well now! Thanks..

**Comment by chomimi101** [comment]
Please tell me how this be solved, I have the same problem when I build z3 from the latest master branch or from the unstable-backup branch, but the same script can work well on iz3 rise4fun. @LeventErkok , Very thankful!

**Comment by LeventErkok** [comment]
@chomimi101 I just did a fresh build of Z3 from the master branch, and it works just fine on the script posted in this ticket. What problem are you having?

**Comment by chomimi101** [comment]
I also did a fresh build of Z3 from the master branch, the script I use as follows (ths style come frm Boogie):

`(set-option :produce-unsat-cores true)
(set-option :print-success false)
(set-info :smt-lib-version 2.0)
(set-option :produce-models true)
; done setting options


(declare-fun tickleBool (Bool) Bool)
(assert (and (tickleBool true) (tickleBool false)))
(declare-fun %lbl%+92 () Bool)
(declare-fun x@0 () Int)
(declare-fun x@1 () Int)
(declare-fun y@1 () Int)
(declare-fun y@0 () Int)
(declare-fun %lbl%@259 () Bool)
(declare-fun AbsHoudiniConstant2 () Bool)
(declare-fun %lbl%+94 () Bool)
(declare-fun %lbl%@227 () Bool)
(declare-fun n () Int)
(declare-fun %lbl%+90 () Bool)
(declare-fun %lbl%+212 () Bool)
(declare-fun AbsHoudiniConstant1 () Bool)
(declare-fun %lbl%+88 () Bool)
(declare-fun %lbl%@196 () Bool)
(declare-fun AbsHoudiniConstant0 () Bool)
(declare-fun %lbl%+166 () Bool)
(define-fun mainMacro () Bool (let ((anon3_LoopBody_correct (=> (! (and %lbl%+92 true) :lblpos +92) (=> (> x@0 0) (=> (and
(= x@1 (- x@0 1))
(= y@1 (+ y@0 1))) (and
(! (or %lbl%@259 (=> true AbsHoudiniConstant2)) :lblneg @259)
(=> (=> true AbsHoudiniConstant2) true)))))))
(let ((anon3_LoopDone_correct (=> (! (and %lbl%+94 true) :lblpos +94) (=> (>= 0 x@0) (and
(! (or %lbl%@227 (=> true (= y@0 n))) :lblneg @227)
(=> (=> true (= y@0 n)) true))))))
(let ((anon3_LoopHead_correct (=> (! (and %lbl%+90 true) :lblpos +90) (=> (! (and %lbl%+212 AbsHoudiniConstant1) :lblpos +212) (and
anon3_LoopDone_correct
anon3_LoopBody_correct)))))
(let ((anon0_correct (=> (! (and %lbl%+88 true) :lblpos +88) (=> (>= n 0) (and
(! (or %lbl%@196 (=> true AbsHoudiniConstant0)) :lblneg @196)
(=> (=> true AbsHoudiniConstant0) anon3_LoopHead_correct))))))
(let ((PreconditionGeneratedEntry_correct (=> (! (and %lbl%+166 true) :lblpos +166) anon0_correct)))
PreconditionGeneratedEntry_correct))))))
(declare-fun b0 (Int Int Int Int) Bool)
(assert (or
true
(b0 n 0 n (+ n 0))))
(assert (or
true
(b0 x@0 y@0 n (+ x@0 y@0))))
(assert (or
true
(b0 x@1 y@1 n (+ x@1 y@1))))
(push 1)
(assert (not (=> (and
(=> AbsHoudiniConstant0 true)
(=> true AbsHoudiniConstant0)
(=> AbsHoudiniConstant1 true)
(=> true AbsHoudiniConstant1)
(=> AbsHoudiniConstant2 true)
(=> true AbsHoudiniConstant2)) mainMacro)))
(check-sat)
(labels)
(get-model)
(get-value ((+ x@0 y@0)))
(assert %lbl%@227)
(check-sat)
(pop 1)
(push 1)
(define-fun mainNegMacro0 () Bool (let ((anon3_LoopDone_correct@@0 (=> (! (and %lbl%+94 true) :lblpos +94) (=> (>= 0 x@0) (and
(! (or %lbl%@227 (=> true (= y@0 n))) :lblneg @227)
(=> (=> true (= y@0 n)) true))))))
(let ((anon3_LoopHead_correct@@0 (=> (! (and %lbl%+90 true) :lblpos +90) (=> (! (and %lbl%+212 AbsHoudiniConstant1) :lblpos +212) anon3_LoopDone_correct@@0))))
(let ((anon0_correct@@0 (=> (! (and %lbl%+88 true) :lblpos +88) (=> (>= n 0) (and
(! (or %lbl%@196 (=> true AbsHoudiniConstant0)) :lblneg @196)
(=> (=> true AbsHoudiniConstant0) anon3_LoopHead_correct@@0))))))
(let ((PreconditionGeneratedEntry_correct@@0 (=> (! (and %lbl%+166 true) :lblpos +166) anon0_correct@@0)))
(compute-interpolant
	(and (= x@0 0) (= y@0 1) (= n 0))
	(and mainNegMacro0 (and (not %lbl%@227) %lbl%+166 %lbl%+88 %lbl%+90 %lbl%+212 %lbl%+94) (= AbsHoudiniConstant1 true) (= AbsHoudiniConstant0 true))
)
(pop)`

The strange thing is that when I run this script on https://www.rise4fun.com/iZ3 or https://www.riseforfun.com/iZ3/tutorial/guide it can work well ( output good results), but when I run the script on my local machine on which I built z3, the results show : theory not supported by interpolation or bad proof.(And I also buit another z3 from unstable branch, neither works)
Do you have some ideas?
Thanks for your help.

**Comment by LeventErkok** [comment]
I can't replicate this. When I run your test, it says:

```
(error "line 78 column 5: unknown constant mainNegMacro0")
```

And I think that's because it's actually incorrectly formatted. The open-parenthesis in:

```
(let ((PreconditionGeneratedEntry_correct@@0 (=> (! (and %lbl%+166 true) :lblpos +166) 
```
is never actually closed. Are you sure you're copying the SMTLib correctly?

**Comment by chomimi101** [comment]
Sorry, it's my fault, I just updated the script I copied, please try again. Thank you.

**Comment by LeventErkok** [comment]
Can you use proper code fragments? (Enclose them in triple backquotes.)

**Comment by LeventErkok** [comment]
I think you need named assertions if you are using Z3 in incremental mode. You can get z3 to produce an output by doing the following modifications:

First, add the following on top:

```
(set-option :produce-interpolants true)
```

Then, instead of using `compute-interpolants`, assert the facts with names and use `get-interpolant`, like this:

```
(assert (! (and (= x@0 0) (= y@0 1) (= n 0)) :named formula1))
(assert (! (and mainNegMacro0 (and (not %lbl%@227) %lbl%+166 %lbl%+88 %lbl%+90 %lbl%+212 %lbl%+94) (= AbsHoudiniConstant1 true) (= AbsHoudiniConstant0 true)) :named formula2))
(check-sat)
(get-interpolant formula1 formula2)
```

After these mods, Z3 responds:

```
(interpolants
 true)
```

Now, I can't opine on whether this output is correct or not; or whether it is what you intended. But this should get you going I think. See https://rise4fun.com/iZ3/tutorialcontent/guide#h24 for details on this.

**Comment by chomimi101** [comment]
Yes, yesterday after I saw carefully your issue, I modified just like you did now, but what confuse me is the result. Now it only return true, though online version and local version return the same result, which dose no help to me. I wonder why the original verison worked differently on iZ3 online version and local version. Actuallly, I want the original online version result.

**Comment by LeventErkok** [comment]
Well `true` would be the "correct" interpolant, if `formula2` is false in all possible models. Unfortunately, it's really hard to tell whether that's the case here since it's really hard to read what's going on. If you are sure this is a bug, I suggest you open a new ticket (with hopefully a simpler test case!), as this issue is now different from what the original ticket was going for.

**Comment by chomimi101** [comment]
Thank you very much for your suggestion, I will try to test some simpler cases, and open another issue if it's really a problem.
