### ISSUE TITLE
command line argument: smt.string_solver=z3str3 weird behaviour

### ISSUE THREAD

**Issue by OrenGitHub** [Z3Prover/z3#1331]
This issue refers to this post at SO: [extracting decimal value from a character in a Z3 string](https://stackoverflow.com/questions/46522705/extracting-decimal-value-from-a-character-in-a-z3-string)
------------------------------------------------------------------------------------------------------------------------------------------
I'm testing example.txt with 2 command line options:
[example.txt](https://github.com/Z3Prover/z3/files/1419424/example.txt)

[1] ./z3 -smt2 example.txt (OK)
[2] ./z3 smt.string_solver=z3str3 -smt2 example.txt (ERROR)

output for [1] (**correct**):
```
sat
((s1 "74g\x00!!###$$")
 (s2 "74G\x00!!###$$")
 (b1 true))

```
output for [2] (**wrong**):
```
sat
((s1 "74g\x00!!###$$")
 (s2 "74o\x00!!###$$")
 (b1 true))

```

**Comment by NikolajBjorner** [comment]
@mtrberzi Can you take a look?

**Comment by mtrberzi** [comment]
I'll take a look at it this week

**Comment by mtrberzi** [comment]
I suspect that there is some weird behaviour with regards to some of the bit-vector constraints that appear in this instance. The constants named `subSecElt` and `eltUpCase` are bit-vectors, which are interpreted as character constants under `seq.unit`, but Z3str3 doesn't represent characters as bit-vectors, so there is a miscommunication leading to the incorrect answer.

@NikolajBjorner -- do you think it would be sensible for Z3str3 to support a very basic version of `seq.unit` over width-8 bit-vectors, interpreting it as a single-character string with the corresponding ASCII character?

**Comment by NikolajBjorner** [comment]
More generally, there are users who would like a version of "at" to return an element instead. The nice thing with "at" is that it can be defined totally by returning an empty string/sequence when the index is out of bounds.

**Comment by LeventErkok** [comment]
@NikolajBjorner I'm confused by your comment. The version of `at` I was thinking has the type `Seq a -> Int -> a`; so out-of-bounds is indeed an issue. But perhaps it can just be underspecified; just like division by zero.

**Comment by NikolajBjorner** [comment]
Yes it can be underspecified, but other string operations are (often) designed so that they are not underspecified.

**Comment by LeventErkok** [comment]
Right. I guess I'm confused at your phrasing: "The nice thing with "at" is that..."

Given it'll return an element, I don't see how to make `at` "nice" in that sense.

**Comment by NikolajBjorner** [comment]
model is correct with latest version of z3str3
