### ISSUE TITLE
SSE trouble MSYS2 Mingw-w64

### ISSUE THREAD

**Issue by eactor** [Z3Prover/z3#1335]
During compile I end up with strange SSE compiler related compile errors:

/gcc/x86_64-w64-mingw32/4.9.3/include/fmaintrin.h:71:1: error: inlining failed in call to always_inline                                                                                   '__m128d _mm_fmadd_sd(__m128d, __m128d, __m128d)': target specific option mismatch
 _mm_fmadd_sd (__m128d __A, __m128d __B, __m128d __C)

/z3-master/src/util/hwf.cpp:275:105: error: called from here
       _mm_store_sd(&o.value, _mm_fmadd_sd(_mm_set_sd(x.value), _mm_set_sd(y.value), _mm_set_sd(z.value)));

Did someone came across them error`?

**Comment by wintersteiger** [comment]
Those are errors relating to compiler intrinsics for floating-point operators. Quite likely that we don't have the right #ifdefs in place for mingw, perhaps we need to include a different intrinsics header, or disable them completely on this platform. Although I thought others have successfully built Z3 using mingw before.

**Comment by wintersteiger** [comment]
I have no added detection of MSYS2 to the Python-build scripts (https://github.com/Z3Prover/z3/commit/e50470f2c4d561e42989d74b1a49e606c8e84415) and it builds fine with them.

On my machine, the scripts complained that the MSYS platform isn't recognized. Was that the same for you or did it pretend that it knows what it's doing?

**Comment by eactor** [comment]
Python had problems to detect the System so I changed the python as well to branch into the Linux branch -> 

elif sysname == 'Linux' or sysname.startswith('MINGW64')  :

But your patch looks way more complex, were you successful atthe end?

P.S. the SSE error come up while using CMake

**Comment by delcypher** [comment]
@eactor I'm the maintainer of the CMake build system. I've never tested using MSYS2. Could provide **precise** reproduction steps. I don't have a Windows VM right now so it might be a while before I get to this. Patches welcome.

**Comment by eactor** [comment]
@wintersteiger I added a PullRequest @2a459c5 to include MingW as well, since MSYS2 comes with different shells issuing different os.uname()) 

**Current  GCC 7.2:**
With the changes I can confirm that Z3 is building within MSYS2 in a MINGW64 shell.

**GCC 5.1**

With **cmake** (@delcypher) the SSE issue seems to be related to older gcc versions, but could not see the issue on Linux with older gcc's. 

The **python** flow issues a problem regarding missing sys/resource.h. 
../src/interp/iz3interp.cpp:558:26: fatal error: sys/resource.h: No such file or directory
compilation terminated.

Also the older  gcc versions issue warings about fPIC for each file with the **python** flow: 
../src/interp/iz3checker.cpp:1:0: warning: -fPIC ignored for target (all code is position independent)
 /*++

**Comment by eactor** [comment]
Precise repodctions steps:
1. Download current MSYS2 (http://www.msys2.org/) 
2. Update installation `pacman -Syu`
3. Restart MSYS update the rest `pacman -Su`
4. Start MSYS as MINGW 64 shell (shown in as shell _username_@_computer_ **MINGW64**)
5. Install packages to build Z3:
  `pacman -S git`
  `pacman -S make`
  `pacman -S python`
  `pacman -S mingw-w64-x86_64-cmake `
6. Install old gcc from repositor
6.1 Download gcc 5.1 and its libs from http://repo.msys2.org/mingw/x86_64/
([mingw-w64-x86_64-gcc-libs-5.1.0-1-any.pkg.tar.xz](http://repo.msys2.org/mingw/x86_64/mingw-w64-x86_64-gcc-libs-5.1.0-1-any.pkg.tar.xz))
([mingw-w64-x86_64-gcc-5.1.0-1-any.pkg.tar.xz](http://repo.msys2.org/mingw/x86_64/mingw-w64-x86_64-gcc-5.1.0-1-any.pkg.tar.xz))
6.2 Install them by browsing to the Download folder
pacman -U mingw-w64-x86_64-gcc-5.1.0-1-any.pkg.tar.xz
pacman -U mingw-w64-x86_64-gcc-5.1.0-1-any.pkg.tar.xz
7. Run python or cmake flow as described within the Z3 documentation.

**Comment by eactor** [comment]
Sorry for confusion but the current GCC only works if a MSYS2 compiler is installed not the MINGW 64 version.

Use the same steps as above but install the current current gcc via pacman in step 6:
`pacman -S mingw-w64-x86_64-gcc`

To check if the right compiler is used type `gcc -v`
it should issue: `Target: x86_64-w64-mingw32` in one of the first lines. 

General background on the difference between msys and mingw target: https://sourceforge.net/p/msys2/discussion/general/thread/dcf8f4d3/#8473/588e

**Comment by wintersteiger** [comment]
Did you mean to say that your `os.sysname()` starts with `MINGW64`?

**Comment by wintersteiger** [comment]
I recently added a bunch of build fixes for MSYS/MinGW and it now builds on my MSYS with old and new GCCs. @eactor, could you check whether this works for you?

**Comment by eactor** [comment]
@wintersteiger thanks for the update. I can confirm that I was able to build Z3 for MSYS2 within a mingw64 shell. I also ran make test but could not figure out what the supposed output should be.
Starting z3-test.exe did not echo anything on the console.

**Comment by delcypher** [comment]
@eactor The `z3-test` program runs no tests if you give no arguments (I learnt this the hard way). Run `z3-test.exe /a` to run all tests. Run `z3-test.exe /h` for help information.

**Comment by eactor** [comment]
@delcypher thanks. Ok test-z3.exe -a runs. I see a lot of PASS. To check I grep for error and fail since I didn't see a summary. 
I only found a couple parse errors within simple_parser test ... still issuing PASS in the end.
