### ISSUE TITLE
Optimization seems to confuse the sign

### ISSUE THREAD

**Issue by LeventErkok** [Z3Prover/z3#1340]
This is related to https://github.com/Z3Prover/z3/issues/1339 but is different in that I think Z3 is actually producing the wrong answer here.

Consider:

```
(set-option :produce-models true)
(set-logic QF_BV)
(define-fun  s1 () (_ BitVec 8) (bvneg #x14))
(declare-fun s3 () (_ BitVec 8))
(define-fun  s2 () Bool (bvsgt s3 s1))
(assert s2)
(maximize s3)
(check-sat)
(get-objectives)
(get-value (s3))
```

For this query, Z3 responds:

```
sat
(objectives
 (s3 255)
)
((s3 #xff))
```

But I'd argue that due to the call to `bvsgt` on line 5, Z3 should've figured out that `s3` is a signed quantity and hence the maximum value it can take can only be `127`.

Interestingly, a slight modification to the input where the constant s1 is not negated:

```
(set-option :produce-models true)
(set-logic QF_BV)
(define-fun  s1 () (_ BitVec 8) #x14)
(declare-fun s3 () (_ BitVec 8))
(define-fun  s2 () Bool (bvsgt s3 s1))
(assert s2)
(maximize s3)
(check-sat)
(get-objectives)
(get-value (s3))
```

We now get:

```
sat
(objectives
 (s3 127)
)
((s3 #x7f))
```

which is the correct response. So, something fishy is going on indeed.

**Comment by andersk** [comment]
Does Z3 ever try to do that kind of signed/unsigned inference? It seems all of these results are consistent with `maximize` always meaning `umaximize`. (`#xff` is signed-greater-than `-#x14`, but `#xff` is not signed-greater-than `#x14`.)

**Comment by LeventErkok** [comment]
This appears to be actually the same as in #1339, and z3 doesn't do any "inference." Closing.
