### ISSUE TITLE
[C API] How do I retrieve the values in a sequence?

### ISSUE THREAD

**Issue by arranf** [Z3Prover/z3#1343]
I'm using the Z3 C API to try and concretize my model into a C array. 

I've managed to get to the point where I can access each of the values in the sequence (by obtaining the sequence length and calling `mk_seq_at` for each value in the sequence) however they're returned as as `seq.unit` rather than a value and neither `simplify()` or `Z3_get_numeral_decimal_string` work on `seq.unit`.

Is there a way to access the value of a `seq.unit` or is there a better way to get the concrete values of a modelled sequence?

**Comment by NikolajBjorner** [comment]
This is a recurring feedback. There is no API method for retrieving elements in a sequence. The background is that the sequence/string functions are derived from a standards draft for SMT-LIB and it does not have a type for characters. In Z3 we can create a unit sequence and do have a type for characters (It is set to 8-bits, other widths can be accomplished using sequences over other bit-widths).

You can emulate a function that takes the nth' element of a list by adding the following for every occurrence of str.at(s, j):

      str.at(s,j) != "" => seq.unit(str.nth(s,j)) = str.at(s,j)

E.g., if str.at returns non-empty string, then the nth element at position j is that element.

There is a related GitHub issue on this somewhere.

**Comment by LeventErkok** [comment]
@NikolajBjorner Here's the ticket you are referring to: https://github.com/Z3Prover/z3/issues/1302
