### ISSUE TITLE
question: what's the alternative function to Z3_mk_context which is deprecated?

### ISSUE THREAD

**Issue by monperrus** [Z3Prover/z3#1345]
I read that Z3_mk_context is deprecated here <https://z3prover.github.io/api/html/group__capi.html#ga0ebc76c86d9cd5bc0a4ff89fcb25e79a>

What's the new function to be used?

**Comment by NikolajBjorner** [comment]
Z3_mk_context_rc is used by all APIs: C++, Java, ocaml. When using Z3_mk_context_rc you have to track reference counts to all Z3_ast objects. If you use Z3_mk_context, then references are persistent and will not be garbage collected until the context is deleted.

**Comment by monperrus** [comment]
thanks
