### ISSUE TITLE
Deprecate Open MP?

### ISSUE THREAD

**Issue by NikolajBjorner** [Z3Prover/z3#1346]
As pointed out somewhere else, with C++11's built in support for threading, the use of OpenMP seems as a good candidate for deprecation. Any caveats?

**Comment by wintersteiger** [comment]
The C++11 support for threading is not particularly nice, plus we have no idea how the different implementations behave on all involved platforms. I can guarantee that they won't behave the same and that not all (sub-) features will be available on all platforms. Realistically we will end up keeping some OpenMP code within #ifdefs anyway.

I started looking into that a while back, see `src\cmd_context\async_cmds.cpp` in the `async-cmds` branch. For now, I think it's not worth the effort that it would take.

**Comment by NikolajBjorner** [comment]
@levnach - could you look in into getting rid of the open-mp dependencies?
There are not too many uses of critical sections, and then there are a couple of parallel-for loops (in sat_solver.cpp and tacticals.cpp).
Each instance should be replaceable by C++11 variants, such as unique_lock, 
http://www.cplusplus.com/reference/mutex/unique_lock/
for suitable mutex objects.

A few would have to be global. If it is necesary to allocate these in the heap they would 
be de-allocated along with other global memory on resets.
There is a scheme for global initializers/finalizers in the build system and it may be required to add a global pool of pointers to mutexes that are allocated (on demand). See CMakeLists.txt for the util directory. It has MEMORY_INIT_FINALIZER_HEADERS. The python build scripts handle these macros as well. The _much_ simpler way could be to have the mutexes live on the global stack, if this plays well with dlls.

There are a few github issues open that relate to the use of OpenMP: on MacOS, linking dependencies.
Once the open MP dependencies are gone, the build systems can be cleared for OpenMP mentions and linking to dependent dlls.

@wintersteiger - I don't see the async-cmds branch under z3prover and I don't understand the comment why it would be required to keep open mp code under ifdefs.

**Comment by wintersteiger** [comment]
I think the async-cmds may be on my fork. The C++11 threads will behave differently on some/all/many platforms/toolsets, so there will be complaints about things not working anymore and we may have to tell users to re-enable the old OpenMP code. I don't think it's worth the effort, but if you're fine with it then go ahead!

**Comment by NikolajBjorner** [comment]
done
