### ISSUE TITLE
z3 segfaults on `(apply)`

### ISSUE THREAD

**Issue by danielschemmel** [Z3Prover/z3#1347]
Passing `(apply)` causes z3 4.5.0 to crash with a segmentation fault on arch linux:

```
$ z3 <(echo "(apply)")
Segmentation fault (core dumped)

$ z3 -in
(apply)
Segmentation fault (core dumped)
```

**Comment by NikolajBjorner** [comment]
The bug was reported before and has been fixed in the current branch.
