### ISSUE TITLE
Can we have README in binary releases?

### ISSUE THREAD

**Issue by pennyan** [Z3Prover/z3#1348]
Hi! I've always been using Z3 by building it myself, but today it was brought into my attention that there are actually binary releases. 

I found there are no REAME files in the binary releases telling us how to use them, or how they are supposed to be used. After some experiments, I found that two things are required to be done in order to use it. First, one needs to add /xxxxx/z3-4.5.0-some-binary-release/bin/python to PYTHONPATH or sys.path. Second, one needs to do call init('/xxxxx/z3-4.5.0-some-binary-release/bin') in Python, before actually using z3.

I'm not sure if this is the supposed way of using the binary releases. If so, can we have a README file in there describing what should be done? If not, what is the right way of using them?

**Comment by wintersteiger** [comment]
Sure, that sounds like a good idea. We can just add the README.md file from the source repository, does that cover enough of what you needed to know?

**Comment by pennyan** [comment]
The reason I mention this is because I don’t think the README in the source applies to the binary releases (or maybe I just doesn’t understand how the binary is supposed to be used?). My understanding is that, one doesn’t have to make anything in the binary, isn’t it?

**Comment by pennyan** [comment]
Hi @wintersteiger , what you described here is exactly what I think is needed. It will be better if such an instruction for using the binary releases exists, not just for Python but for other bindings as well. This probably won't help old users much but will be a great help to new users who are not familiar with Z3. Maybe you want the source README and the binary README to be the same one? If that's the case, maybe we can add a section in the source README with these instructions and then distribute that README to the binary releases?
