### ISSUE TITLE
bit2bool/mkbv functions in bitblasted floating-point formulas

### ISSUE THREAD

**Issue by MateusAraujoBorges** [Z3Prover/z3#1349]
_All tests conducted using Z3 4.5.1 64-bit (commit 3350f32e1f2c01c9df63b7d71899796a18ce2272, compiled with gcc  5.4.0) and Python 3 on a Ubuntu 16.04 system._

Hi all,

## Context

I want to "translate" floating-point formulas into CNF boolean formulas using the Z3 API. Here is my first attempt:

```python
from z3 import *

x = FP('x',Float16())
c = FPVal(1024,Float16())
formula = And(x < c, x > 0)
goal = Goal()
goal.add(formula)
# taken from https://stackoverflow.com/a/23932235
tacs = Then(Tactic('simplify'),Tactic('fpa2bv'),Tactic('simplify'),Tactic('bit-blast'),Tactic('tseitin-cnf'))

# track input bits
for i in range(16):
    b = Bool('b' + str(i))
    mapping = b == (Extract(i,i,fpToIEEEBV(x)) == BitVecVal(1,1))
    goal.add(mapping)
    
bitblasted = tacs(goal)[0]
for f in bitblasted:
    print(f)
```

The middle block (`for i in range(16)...`) maps a new boolean to each bit of the input ('x' in this example). The aim is to create a set of variables that, if used as a projection scope for a SAT model counter (e.g. sharpSAT), will make the model counter return the number of solutions for the original formula. 

## Problem

Here is a snippet of the output from the execution of the script above:

``` 
[...]
Or(k!36,
   bit2bool(k!19(mkbv(k!20, k!21,k!22, k!23,k!24,k!25, k!26, k!27, k!28,k!29, k!30, k!31, k!32, k!33,k!34,k!35))),
[...]
```

My expectation was that no functions (well, other than Or/And/Not) would appear in the bitblasted formula. Applying the same idea to bitvector variables directly (example code [here](https://gist.github.com/MateusAraujoBorges/cda62d905e2ae94f2b877450bd2d7478)) works as expected. Am I doing something wrong in the python code above? 

## Addendum

Executing the python code above with `rewriter.hi_fp_unspecified` set to `true` results in a segfault.

**Comment by wintersteiger** [comment]
I'm afraid your expectation can't  be met. The floating-point theory and the bit-vector theory need more than just Boolean variables. For instance, the behavior of some floating-point functions (e.g. fp.min/fp.max) and that of bit-vector functions (e.g., bvudiv by zero) is unspecified. For that reason, the output of fpa2bv and/or bit-blast will frequently contain uninterpreted functions. Those can be disabled by setting `rewriter.hi_fp_unspecified=true` (and `rewriter.hi_div0=true`, which is the default anyway). However, this means Z3 will not be SMT2-compliant (and unsound from that perspective). Also, note that `fpToIEEEBV` is a Z3-specific extension without reliable or documented semantics. 

`bit2bool` is a function that represents the translation of a one-bit value to a Boolean value, and it's used internally by the bit-blaster. I don't think this can be disabled at this time. 

The options previously mentioned may also have the effect that the SMT solver isn't used at all, but only the SAT solver and in that case, the output of the bit-blaster is translated into different implementations of literals/clauses/etc. There are debug-functions for dumping both of them in dimacs format, but afaik this can't be used from the outside at the moment.

**Comment by wintersteiger** [comment]
(segfault fixed)

**Comment by MateusAraujoBorges** [comment]
Thanks for the clarifications! I'll close the issue now.
