### ISSUE TITLE
Performance surprisingly slow: since it can be solved very fast...

### ISSUE THREAD

**Issue by pjljvandelaar** [Z3Prover/z3#1352]
Attached find two smt2 files. 
I added .txt extension to be able to upload to git.
[test.smt2.txt](https://github.com/Z3Prover/z3/files/1461591/test.smt2.txt)
[test-long.smt2.txt](https://github.com/Z3Prover/z3/files/1461592/test-long.smt2.txt)

On windows, test.smt2(.txt) is executed very fast.
```
C:\>z3 test.smt2
(:name "Z3")
(:version "4.5.1 - build hashcode abeaefa8fec1")
sat
sat
(($$$$t$3$10000003$-1$-1$ 7720))
sat
(($$$$t$3$10000003$-1$-1$ (- 7849198668475269121)))
sat
(($$$$t$0$10000000$-1$-1$ 5473541746938345921))
sat
(($$$$t$2$10000002$-1$-1$ (- 7849198668475269122)))
unsat
sat
sat
(($$$$t$9$10000009$-1$-1$ ""))
sat
```

test-long.smt2(.txt) ends with the same problems to be solved as test.smt2(.txt). 
However, it takes almost a hour to take the last step.

**Comment by pjljvandelaar** [comment]
Could you reproduce the issue?

**Comment by NikolajBjorner** [comment]
with the latest bits this seems to be sufficiently fast

**Comment by pjljvandelaar** [comment]
Thanks!
Will check probably tomorrow.

**Comment by pjljvandelaar** [comment]
Checked with Z3 version 4.8.4 - 64 bit - build hashcode b40c2b2926ed

Indeed the performance issue is solved!
I can't wait till the next release such that I can share it with the users of [TorXakis](https://github.com/TorXakis/TorXakis).
