### ISSUE TITLE
Question about function declaration in Python using Z3

### ISSUE THREAD

**Issue by leesanghun910701** [Z3Prover/z3#1353]
Dear everyone,

Hello. I am new to Z3 smt-solver and I am currently writing a tutorial codes in order to solve my problem.

However, I am having trouble with declaring the function in Python to use Z3.

Here is my code:

===========================================

from z3 import *
import time

def OP_MODE_23(OPMODE_1, OPMODE_2, OPMODE_3):
	if(
        OPMODE_1 == 2 or OPMODE_1 == 3 or
	    OPMODE_2 == 2 or OPMODE_2 == 3 or
	    OPMODE_3 == 2 or OPMODE_3 == 3
	  ):
	    return 1
	else:
		return 0
	
_2_OP_MODE, _3_OP_MODE = Ints('_2_OP_MODE _3_OP_MODE')
OP_MODE_23_SW = OP_MODE_23(1, _2_OP_MODE, _3_OP_MODE)

s = Solver()
s.add(OP_MODE_23_SW == 1)
s.add(_2_OP_MODE >= 1, _2_OP_MODE <= 6)
s.add(_3_OP_MODE >= 1, _3_OP_MODE <= 6)

result = []
start = time.clock()

while True:
    if s.check() == sat:
        m = s.model()
        print m
        result.append(m)
        block = []
        for d in m:
            if d.arity() > 0:
                raise Z3Exception("uninterpreted sorts are not supported")
            c = d()
            if is_array(c) or c.sort().kind() == Z3_UNINTERPRETED_SORT:
                raise Z3Exception("arrays and unterpreted sorts are not supported")
            block.append(c != m[d])
        s.add(Or(block))
    else:
        print len(result)
        print(time.clock() - start)
        break

===========================================

In this code, I would like to get the result of
[_2_OP_MODE = 2, _3_OP_MODE = 2]
[_2_OP_MODE = 2, _3_OP_MODE = 3]
[_2_OP_MODE = 3, _3_OP_MODE = 2]
[_2_OP_MODE = 3, _3_OP_MODE = 3]

but the code does not generate any result.
(It seems that the if-else in OP_MODE_23 function does not work.)

How can I correct this Python code to get the result of
[_2_OP_MODE = 2, _3_OP_MODE = 2]
[_2_OP_MODE = 2, _3_OP_MODE = 3]
[_2_OP_MODE = 3, _3_OP_MODE = 2]
[_2_OP_MODE = 3, _3_OP_MODE = 3]

(In this code, I want to declare the function OP_MODE_23, because it will be frequently used in the whole code which I will develop later)

Thank you very much in advance.

Best Regards,
Lee.

**Comment by NikolajBjorner** [comment]
You are mixing Z3 terms and Python statements in OP_MODE_23.
"if" is a python statement/expression builder. 
If you want a Z3 expression use the function "If" that takes three arguments.
