### ISSUE TITLE
Suspiciously hard LIA instance

### ISSUE THREAD

**Issue by iwob** [Z3Prover/z3#1354]
Hello, the following script tested on HEAD seems to run indefinitely and consumes continuously more and more memory. It can be a very hard instance or a bug.

```
(set-logic LIA)
(define-fun f ((x Int)) Int (mod (- (ite (= 8 x) (div x 9) 8) (+ (* 3 x) (div x 2))) 10))
(declare-fun x1 () Int)
(assert (not (and (= (f x1) x1))))
(check-sat)
(get-value (x1))
```

**Comment by NikolajBjorner** [comment]
Thanks, this one is/was a bug.
