### ISSUE TITLE
Z3 from KLEE -- Is this a bug?

### ISSUE THREAD

**Issue by OrenGitHub** [Z3Prover/z3#1359]
[1] While debugging KLEE symbolic executor,
I've encountered an **infinite loop** (didn't wait forever though :] ) in Z3.

[2] After some debug effort, I've managed to hit line 147 from file src/smt/asserted_formulas.cpp:

TRACE("**assert_expr_bug**", tout << r << "\n";);

[3a] Is this a proof existence of a bug? (I'm guessing it is, but want to be sure)
[3b] What will be the best way of debugging this??

**Comment by NikolajBjorner** [comment]
the log was created to chase an old bug that was fixed (I guess, quite a while ago). It does not imply a bug, but it does not rule out any bugs either. You can create a log file that can be replayed using Z3 by calling Z3_open_log before any other Z3 calls. The log could be used for reproducing bugs, it can be executing using z3 itself.

**Comment by OrenGitHub** [comment]
It seems that the following while loop from src/ast/rewriter/rewriter_def.h is **infinite**

    void rewriter_tpl<Config>::resume_core(expr_ref & result, proof_ref & result_pr) {
        SASSERT(!frame_stack().empty());
        while (!frame_stack().empty()) { // ... body omitted

When I back-trace I get to this line code from src/smt/asserted_formulas.cpp:

    m_rewriter(e, r, pr);

And e is an (expr *) with:

    (gdb) print e->get_kind()
    $1 = AST_APP
    (gdb) print ((app *) e)->m_decl
    $2 = (func_decl *) 0x2bd2c78

KLEE might have caused some "damage" to the original query,
But when it is first created it is simply: (= 173 (str.len "OREN")))
(meant to be false).
Any ideas how to continue? what to look for inside the expr e??

**Comment by NikolajBjorner** [comment]
You could compile Z3 for debug mode and enable tracing.
Seems your constraints use strings, which is relatively fresh, so you can trace for sequence/string related rewrites, e.g., -tr:seq (see the file ast/rewriter/seq_rewriter.cpp for logs). Otherwise, -tr:rewriter or -tr:rewrite.

**Comment by NikolajBjorner** [comment]
When you say KLEE may have cause "damage", the most likely place to look for is whether KLEE manages reference counting on expressions correctly. If only using the C++ API there should not be a danger, but if using the C API (functions that look like Z3_mk_...) it is very easy to get reference counting discipline wrongongong.

**Comment by OrenGitHub** [comment]
Thanks for the help --
I have compiled Z3 in debug mode, and called Z3_open_log("Z3LogFile.txt").
The log now contains repetitive memory addresses (here is a small fragment):

    P 0x2707088
    P 0x2351bb8
    $ |timeout|
    U 4294967295
    C 17
    R
    P 0x2707088
    P 0x2351bb8
    $ |timeout|
    U 4294967295
    C 17
    R

And I assume I should start logging stuff from interesting points in the code.
As far as I am concerned, **there is only 1 interesting thing to log -- the ast**.
However, **from the break-point inside the infinite loop** (src/ast/rewriter/rewriter_def.h line 679),
and back-trace-ing **all the way up to KLEE's API call**, I can't [ debug | log | see somehow ] the ast:

[1] I can't find the class _Z3_ast (found two different ast classes along my search, but no Z3_ast)
[2] Inside

    src/api/api_solver.cpp (line 247)

in

    void Z3_API Z3_solver_assert(Z3_context c, Z3_solver s, Z3_ast a)

I am not be able to use this function:

    LOG_Z3_ast_to_string(c, a)

Is this the right API function?

Thanks a lot in advance

**Comment by delcypher** [comment]
@OrenGitHub There's a flag in KLEE to log API calls by the way. Check the `-debug-z3-log-api-interaction=<path>` option. The file produced can be replayed by the `z3` binary. This can be helpful for the Z3 developers to replay KLEE's use of Z3.

**Comment by delcypher** [comment]
@NikolajBjorner 
> When you say KLEE may have cause "damage", the most likely place to look for is whether KLEE manages reference counting on expressions correctly.

KLEE uses the C API but uses wrapper classes to correctly do reference counting. However it sounds like @OrenGitHub is extending it to handle string constraints which is not in mainline KLEE, therefore @OrenGitHub might have changes that incorrectly use Z3's API.

**Comment by OrenGitHub** [comment]
Thanks @NikolajBjorner and @delcypher !
The problem was indeed that one of my dedicated string functions in my modified KLEE
**called the Z3 C API without using KLEE's wrapper class Z3ASTHandle**.
I would also like to thank KLEE's contributor @omeranson for helping -
This issue can be safely closed.
