### ISSUE TITLE
scripts/mk_make.py fails to run on Python 3 due to TAB/Space mixing in the file

### ISSUE THREAD

**Issue by progirep** [Z3Prover/z3#136]
Using the current unstable version and running 

    python3 scripts/mk_make.py

yields the error

    Traceback (most recent call last):
      File "scripts/mk_make.py", line 9, in <module>
        from mk_util import *
      File "/home/myusername/projects/z3/scripts/mk_util.py", line 568
        elif opt in ('--x86'):
                             ^
    TabError: inconsistent use of tabs and spaces in indentation

on Python 3.4. Replacing the tab in scripts/mk_util.py by a few spaces fixes the problem and should be easy to do.

**Comment by NikolajBjorner** [comment]
The line number is not consistent with the unstable branch. 
Github shows the following:
 https://github.com/Z3Prover/z3/blob/unstable/scripts/mk_util.py#L566


566  if not IS_WINDOWS: 
567         print("  CXX        C++ compiler") 
568         print("  CC         C compiler") 
569         print("  LDFLAGS    Linker flags, e.g., -L<lib dir> if you have libraries in a non-standard 

Furthermore, I am unable to reproduce any problem with my freshly installed version of Python3.4

**Comment by progirep** [comment]
Sorry for bothering you. The issue was that I was still pulling the unstable branch from codeplex.
