### ISSUE TITLE
How to get all the unsatisfiable assumptions?

### ISSUE THREAD

**Issue by sheeniya** [Z3Prover/z3#1362]
Hello,
In optimization mode,I want to know all the unsatisfiable assumptions with the model,for example:
(set-option:produce-models true)
(declare-const x Int)
(declare-const y Int)

(define-fun one () Bool (> x 1))
(define-fun two () Bool (< x 1))
(define-fun three () Bool (> y 1))
(define-fun four () Bool (< y 1))

(assert-soft (! one :named x1))
(assert-soft (! two :named x2))
(assert-soft (! three :named y1))
(assert-soft (! four :named y2))

(check-sat)
(get-model)
The model is:
sat
(model 
  (define-fun y () Int
    2)
  (define-fun x () Int
    0)
)
The x1,y2 is unsatisfiable,but how can I let the solver print it  on screen?
Thanks for your help!

**Comment by NikolajBjorner** [comment]
You can do the following:

    (get-model)
    (eval x1)
    (eval x2)
    (eval y1)
    (eval y2)
