### ISSUE TITLE
addition of axiom on unused symbol makes Z3 return unknown

### ISSUE THREAD

**Issue by yannickmoy** [Z3Prover/z3#1365]
Z3 (both master and unstable heads) manages to prove only one of the files attached: 

$ z3 quantifiers.z3.smt2
unsat
$ z3 quantifiers.z3.unknown.smt2
unknown

where the diff between these is simply an axiom on symbol "slide", with an explicit trigger that should prevent this axiom from ever being taken into account:

$ diff quantifiers.z3.smt2 quantifiers.z3.unknown.smt2
28a29,40
>
> (declare-fun slide ((Array Int integer) Int Int) (Array Int integer))
>
> ;; slide_def
>   (assert
>   (forall ((a (Array Int integer)))
>   (forall ((old_first Int))
>   (forall ((new_first Int))
>   (forall ((i Int))
>   (! (= (select (slide a old_first new_first) i) (select a (- i (- new_first old_first)))) :pattern ((select
>   (slide a old_first new_first) i)) ))))))
>

Is there a way (an option, or a different way to generate the above axiom) that would allow Z3 to also prove both files?

Let me know if I can perform other experiments.

**Comment by yannickmoy** [comment]
with the files...

[quantifiers.z3.unknown.smt2.txt](https://github.com/Z3Prover/z3/files/1496581/quantifiers.z3.unknown.smt2.txt)
[quantifiers.z3.smt2.txt](https://github.com/Z3Prover/z3/files/1496582/quantifiers.z3.smt2.txt)

**Comment by wintersteiger** [comment]
In general, Z3 interleaves quantifier instantiation with a search procedure, i.e. small changes to the input may have a huge impact on the result and the time required to get there. In this particular case, it's the array theory that gives up. 

The simplifier rewrites the additional quantifiers like so (run `(apply simplify)` instead of `(check-sat)`):

```
  (forall ((a (Array Int integer)) (old_first Int) (new_first Int))
    (forall ((i Int))
      (! (= (select (slide a old_first new_first) i)
            (select a (+ i (* (- 1) new_first) old_first)))
         :pattern ((select (slide a old_first new_first) i)))))
```

And the solver then proceeds to instantiate the _outer_ quantifier, for which it automatically inferred the pattern `((slide a old_first new_first))`. It then instantiates the (still outer) quantifier, resulting in an additional quantified term over `i` and containing an array term. Similarly, the inferred patterns for the quantifiers at lines 44 and 64 contain array terms (`((select tab x))` and `((select (select tab x) y))`).

**Comment by yannickmoy** [comment]
Thanks Christoph for the explanations. What surprises me is that Z3 manages to instantiate the axiom with the pattern ((slide a old_first new_first)) that it infers. What values does it take for this instantiation? Any combination of variables a, old_first and new_first that it finds? Can we pass an option to Z3 to restrict its instantiations to term-matching when a suitable pattern was found for an axiom? So that it only uses model-based instantiation when no pattern was found?

**Comment by NikolajBjorner** [comment]
MBQI has long standing limitations with respect to the theory of arrays. It instantiates 'a' with a function that is defined within a model, and this function definition is lost when the instance pollutes the models in other MBQI calls. This could be part of explaining the oddity, but I can't see trivially if this is really the case.
We are trying to address the array limitations in a dev branch, but so far the main approach with current MBQI is to not mix MBQI with arrays. So rewrite:

    (declare-sort A)
    (declare-fun slide (A Int Int) A)
    (declare-fun sel (A Int) integer)

    ;; slide_def
      (assert
      (forall ((a A)
               (old_first Int)
               (new_first Int)
               (i Int))
           (! (= (sel (slide a old_first new_first) i) (sel a (- i (- new_first old_first)))) :pattern ((sel
         (slide a old_first new_first) i)) )))

    ; (declare-const tab (Array Int (Array Int integer)))
    (declare-fun tab2 (Int Int) integer)
    ...

**Comment by yannickmoy** [comment]
Thanks Nikolaj. As such an aggressive rewriting is not possible in our case, I tried to play with options, but using smt.mbqi=false does not change the outcome, the VC is still unproved. Is it the right option to prevent MBQI?

**Comment by NikolajBjorner** [comment]
mbqi is enabled when auto-configuration is used. It is on by default. So applications that don't like MBQI also set auto_config=false.

That said, seems this example tells us that MBQI should simply avoid instantiations that contain these array skolems. It already has a filter for instantiations that expose private model values. It makes sense to extend this to model skolems that wreak havoc for later model checking.

**Comment by yannickmoy** [comment]
I tried but it gives the same results:
z3 smt.mbqi=false auto_config=false quantifiers.z3.unknown.smt2

**Comment by NikolajBjorner** [comment]
mbqi mode also uses patterns, so just disabling mbqi doesn't improve instantiations. 
Try the fix, though.

**Comment by yannickmoy** [comment]
Thx, fix does fix it!
