### ISSUE TITLE
[String] Both a formula and it's negation are unsatisfiable

### ISSUE THREAD

**Issue by iwob** [Z3Prover/z3#1366]
Hello, in the following script both a formula and it's negation are unsatisfiable.

```
(set-logic ALL)
(declare-fun name () String)
(assert (= (str.at name (str.indexof " " (str.substr name (str.len name) 1) 2)) ""))  ; this alone is unsat
;(assert (distinct (str.at name (str.indexof " " (str.substr name (str.len name) 1) 2)) ""))  ; this alone also is unsat
(check-sat)
(get-value (name))
```

**Comment by iwob** [comment]
I think I have found another unsoudness: [tmp5.txt](https://github.com/Z3Prover/z3/files/1503598/tmp5.txt)

Problem seems to be with: (str.indexof (str.++ "Dr." name) "1" 1)  in case name does not contain "1".

**Comment by NikolajBjorner** [comment]
thanks, it was a different bug
