### ISSUE TITLE
Z3 timeouts on an example 4.5.0 could decide

### ISSUE THREAD

**Issue by dailler** [Z3Prover/z3#1373]
Hello,

I think Z3 (master version, nightly binaries) is less efficient than earlier versions (4.4.2 and 4.5.0). On my [example.txt](https://github.com/Z3Prover/z3/files/1505833/example.txt), Z3 takes a lot of time. With previous version, it answered in less than 1 second.

Is it expected ?

**Comment by NikolajBjorner** [comment]
Thanks, the pre-processor simplification changed. It used to distribute multiplication over addition and doesn't do that any longer. It is solved quickly if adding the option rewriter.som=true.

**Comment by dailler** [comment]
Thank you: this solves the issue.
