### ISSUE TITLE
Z3 incompleteness example for non-matching types?

### ISSUE THREAD

**Issue by Fathardie** [Z3Prover/z3#1374]
Hi everyone!

Just came across an example which seems to be "difficult" for Z3 to handle:

The following returns unknown:
```
(declare-const i_0 Real)
(declare-const i_1 Real)

(declare-const k_0 Real)

(declare-const j_0 String)
(declare-const j_1 String)

(assert (and
          (>= i_0 0.0)
          (= i_1 (* i_0 k_0))

	  (= "0" j_0)
          (= j_0 j_1)
        )
)

(assert (not
          (and
            (>= i_1 0.0)
            (= "0" j_1)
          )
        )
)

(check-sat)
(get-model)
```

This also returns unknown:
```
(declare-const i_0 Real)
(declare-const i_1 Real)

(declare-const k_0 Real)

(declare-const j_0 Int)
(declare-const j_1 Int)

(assert (and
          (>= i_0 0.0)
          (= i_1 (* i_0 k_0))

	  (= 0 j_0)
          (= j_0 j_1)
        )
)

(assert (not
          (and
            (>= i_1 0.0)
            (= 0 j_1)
          )
        )
)

(check-sat)
(get-model)
```

While this returns sat:
```
(declare-const i_0 Real)
(declare-const i_1 Real)

(declare-const k_0 Real)

(declare-const j_0 Real)
(declare-const j_1 Real)

(assert (and
          (>= i_0 0.0)
          (= i_1 (* i_0 k_0))

	  (= 0 j_0)
          (= j_0 j_1)
        )
)

(assert (not
          (and
            (>= i_1 0.0)
            (= 0 j_1)
          )
        )
)

(check-sat)
(get-model)
```
With model:
```
i_0: 1.0
i_1: - 1.0
k_0: - 1.0
j_0: 0.0
j_1: 0.0
```

The differences between the examples is the type of `j_*` which is either String, Int or Real. Only when `j_*` matches the type of `i_*` as a Real is it able to find the satisfying model. To me this is confusing as the variables for `i_*` and `j_*`  do not share any relation and the model only changes in type and not value.

I strongly suspect this is a bug, hence the report. If I am doing something wrong, please tell me!

**Comment by Fathardie** [comment]
If I make the formula really unsatisfiable by adding
```
(assert (>= k_0 0)
```
The answer is unsat no matter the example. So it seems there is an issue with model generation after determining the formula is sat?

**Comment by NikolajBjorner** [comment]
The example mixes non-linear arithmetic with other theories. There is currently no good support for this. This will change in a future release.
