### ISSUE TITLE
Z3py: parsing smt2 file

### ISSUE THREAD

**Issue by alx441** [Z3Prover/z3#1378]
Hi,
I try the code below to parse a smt2 file, in python with z3, but I have an Z3Exception: parser error. Do you have an idea what I am supposed to do ?

import z3;
ctx = z3.Context()
s = z3.Solver(ctx=ctx)
f = z3.parse_smt2_file("file.smt2")
print(f)

**Comment by JasonPap** [comment]
I have the same problem but with the function `parse_smt2_string` given the query 
```(declare-const x Int)
(declare-const y Int)
(declare-const zz Int)
(assert (>= y -100 )  )
(assert ( <= y 100 )  )
(assert ( >= x 1)  )
(assert ( <= x 100 )  )
(assert ( >= zz -100 )  )
(assert ( <= zz 100 )  )
(assert ( > x  ( + ( - 21  87  )  ( div zz  2  )  )  ) )
(assert ( <= ( - ( * 45  y  )  12  )  ( - ( - 67  ( * 3  6  )  )  ( + 90  14  )  )  ))
(check-sat)```

while the same query returns `sat` on both rese4fun.com online tool and if I create a local file and call z3 from the command line as `z3 -smt2 query.smt2`

**Comment by NikolajBjorner** [comment]
Error reports from parsers over the API haven't been good. However, with https://github.com/Z3Prover/z3/commit/187998ae4d03562c4c4981000d5d40a6b6e1e3cf, this is improved as the exception that has to do with parsing errors includes the error message.
If the file cannot be read (because the wrong file location is given or it is not accessible), the error message should be an access (not a parsing) error.

**Comment by NikolajBjorner** [comment]
@JasonPap, @alx441 are the parsing issues better now?

**Comment by alx441** [comment]
It is good for me . Thank you.

**Comment by izlatkin** [comment]
Hello, 
Why sometime parse_smt2_file returns emty [] for valid smt2 file?

For example, for 
```
(define-sort s () (_ BitVec 3))
(declare-rel edge (s s))
(declare-rel path (s s))
(declare-var a s)
(declare-var b s)

(rule (=> (edge a b) (path a b)))

(rule (edge #b001 #b010))
(rule (edge #b001 #b011))
(rule (edge #b010 #b100))

(declare-rel q1 ())
(rule (=> (path #b001 #b100) q1))

(query q1)
```
f = z3.parse_smt2_file("1_test1.smt2")
print(f)

/usr/local/bin/python3.9 Optimizer.py
; declare-rel line: 2 position: 23
; declare-rel line: 3 position: 23
; declare-var line: 4 position: 16
; declare-var line: 5 position: 16
; rule line: 7 position: 32
; rule line: 9 position: 24
; rule line: 10 position: 24
; rule line: 11 position: 24
; declare-rel line: 13 position: 18
; rule line: 14 position: 32
; query line: 16 position: 9
[]
