### ISSUE TITLE
Optimization with recursive functions yield incorrect result

### ISSUE THREAD

**Issue by LeventErkok** [Z3Prover/z3#1382]
Thanks @NikolajBjorner Your recent fixes to recursive functions allowed me to make progress. Alas, I'm still seeing bizarre behavior.

This script:

```
(declare-datatypes  () ((Item (mk-item (size Int) (weight Int)))))
(declare-fun items  () (Array Int Item))
(declare-fun picked () (Array Int Bool))

(assert (= (select items 1) (mk-item 4 2)))
(assert (= (select items 2) (mk-item 4 2)))
(assert (= (select items 3) (mk-item 1 4)))
(assert (= (select items 4) (mk-item 5 5)))
(assert (= (select items 5) (mk-item 3 2)))
(assert (= (select items 6) (mk-item 1 9)))

(define-fun-rec computeSize ((lb Int) (ub Int)) Int
   (ite (> lb ub)
        0
        (+ (ite (select picked lb) (size (select items lb)) 0)
           (computeSize (+ lb 1) ub))))

(define-fun-rec computeWeight ((lb Int) (ub Int)) Int
   (ite (> lb ub)
        0
        (+ (ite (select picked lb) (weight (select items lb)) 0)
           (computeWeight (+ lb 1) ub))))

(define-fun totalSize   () Int (computeSize 1 6))
(define-fun totalWeight () Int (computeWeight 1 6))
(assert (< totalSize 10))
(maximize totalWeight)

(check-sat)
(get-value (totalSize))
(get-value (totalWeight))
(eval (select picked 1))
(eval (select picked 2))
(eval (select picked 3))
(eval (select picked 4))
(eval (select picked 5))
(eval (select picked 6))
```

produces:

```
sat
((totalSize 7))
((totalWeight 4))
false
true
false
false
true
false
```

Unfortunately, that is the incorrect answer. There is a solution such that the `totalWeight` is actually `18`, by picking items 3, 4, and 6.

When I code the whole thing without recursive functions, I get the correct answer indeed. In fact, if you remove:

```
(maximize totalWeight)
```

And replace it with:

```
(assert (>= totalWeight 18))
```

that also works as well, producing:

```
sat
((totalSize 7))
((totalWeight 18))
false
false
true
true
false
true
```

So, I'm not sure what to blame here; but seems to be an interaction between optimization and recursively defined functions.

**Comment by NikolajBjorner** [comment]
It is not a scenario that opt solver handles. Quantifiers will not work either. Perhaps I print a warning in this case, but there is no simple way to deal with quantified hard constraints when they influence the objective values.

**Comment by LeventErkok** [comment]
Thanks Nikolaj. An `error` would be better I think, since most upstream tools (mine definitely!) ignore warnings.

I understand that recursion/quantification is hard to deal with. But I'm curious if one particular use case can be supported: When the control path is completely concrete. In this example, the recursive calls `(computeSize 1 6)` are not only ground, their evaluation can be completely unrolled since the control-path is all concrete. It may be hard to detect this in general of course, but perhaps certain cases can be supported.

The underlying issue here isn't really that users need to reason about recursion really, but rather SMTLib simply has no way of writing a simple for-loop. So, it's just the programming aspect here to be able to express benchmarks that can be completely unrolled, instead of actually doing any fancy reasoning about recursion.

I understand this is hand-wavy, but I'm curious if there might be a middle ground that supports the programming aspects of specifications, without being terribly hard to implement.

**Comment by NikolajBjorner** [comment]
It's much easier for me to have you implement the unrolling before calling Z3 :-).

**Comment by LeventErkok** [comment]
Fair enough!

**Comment by NikolajBjorner** [comment]
have to deal with error messaging..
