### ISSUE TITLE
Supporting transcendental functions in NRA

### ISSUE THREAD

**Issue by rainoftime** [Z3Prover/z3#1383]
Hi~
Many practical applications require dealing with transcendental functions such as exponential, logarithm, sine and cosine[1] which are supported in the dReal SMT solver[2].  Is there any plan for supporting these functions?  

[1] Satisfiability Modulo Transcendental Functions via
Incremental Linearization, CADE 17.
[2] https://dreal.github.io/

**Comment by NikolajBjorner** [comment]
It's all interesting, but it would need a good set of applications, use cases and benchmarks before making it a priority.
