### ISSUE TITLE
(Z3Py, question) set time limit

### ISSUE THREAD

**Issue by dennis714** [Z3Prover/z3#1386]
How to set timeout from Z3Py?
I'm trying "set_option(timeout=n)".
Is $n$ in seconds?
Can't be sure yet.

**Comment by NikolajBjorner** [comment]
You can set it globally using set_option(timeout=n), where n is in milliseconds.
You can also set it locally on solver objects using the corresponding "set" method.

**Comment by dennis714** [comment]
Thanks!
