### ISSUE TITLE
BV2Int Overflow Problems?

### ISSUE THREAD

**Issue by bannsec** [Z3Prover/z3#1388]
So I've been looking at converting a BitVector object (with it's own constraints already), into an Integer object. However, there appears to be strangeness with the `BV2Int` method.

Example:
```python
In [39]:  x = BitVec('x', 3)

In [40]: x
Out[40]: x

In [41]:  prove(x <= 3)
proved

In [42]:  prove(BV2Int(x) <= 3)
counterexample
[x = 6]
```

My guess is z3 is allowing overflow in handling of BV2Int object, thus 6 would indeed be possible, however undesirable behavior in my case.

Is there a way to make it honor over/underflows?

**Comment by NikolajBjorner** [comment]
From python '<=' has the semantics of signed comparison, so x ranges over the signed bit-vector range -4..3. When using BV2Int, we treat 'x' as unsigned, so the values are 0..7.

**Comment by bannsec** [comment]
Ah. Is it possible to specify that the BitVec be unsigned/signed at creation time? I intrinsically think of them being unsigned so would be nice to default it to that behavior.

**Comment by NikolajBjorner** [comment]
Yes, you can use bv2int in signed mode.

<code>
       C:\opt\release\python>python
       Python 3.6.0 |Anaconda 4.3.0 (64-bit)| (default, Dec 23 2016, 11:57:41) [MSC v.1900 64 bit (AMD64)] on win32
       Type "help", "copyright", "credits" or "license" for more information.

    >>> from z3 import *
    >>> help(BV2Int)
    Help on function BV2Int in module z3.z3:

    BV2Int(a, is_signed=False)
        Return the Z3 expression BV2Int(a).

       >>> b = BitVec('b', 3)
       >>> BV2Int(b).sort()
       Int
       >>> x = Int('x')
       >>> x > BV2Int(b)
        x > BV2Int(b)
        >>> x > BV2Int(b, is_signed=False)
        x > BV2Int(b)
        >>> x > BV2Int(b, is_signed=True)
        x > If(b < 0, BV2Int(b) - 8, BV2Int(b))
        >>> solve(x > BV2Int(b), b == 1, x < 3)
        [b = 1, x = 2]

>>>
