### ISSUE TITLE
datatype declarations according to SMT v2.6 not possible

### ISSUE THREAD

**Issue by julianthome** [Z3Prover/z3#1390]
Datatype declarations such as 

```
(declare-datatype MyList (par (T) ((nelem) (cons (hd T) (tl (MyList T)))))) 
```

are not supported by z3 (version 4.5.1). When executed with this input, z3 will respond with the following message:

```
unsupported
; declare-datatype line: 1 position: 75

```

For more information please have a look at this [post](https://stackoverflow.com/questions/47620234/modelling-generic-datatypes-for-z3-and-or-smtv2-6/47623885#comment82276649_47623885).

**Comment by LeventErkok** [comment]
4.5.1 is pretty old. But even with a fresh build from master, this definition gets rejected, but with an error message saying MyList doesn’t exist in the recursive reference. At least that error message is suspicious.
