### ISSUE TITLE
Specific Z3 nightly versions (4.6.0)

### ISSUE THREAD

**Issue by facanferff** [Z3Prover/z3#1392]
There is somewhere a page where it is possible to obtain the binaries (for any platform) of a specific commit (some commit of 4.6.0)?

I noticed the repository https://github.com/Z3Prover/bin . However, if I am not mistaken those binaries are deleted whenever a new commit is done to master of Z3, making it impossible to retrieve the binaries of some specific old commit.

Somewhat related to this, there is a scheduled date for the release of the stable 4.6.0? Using a stable version of it would eliminate the need to use a specific nightly version.

**Comment by pjljvandelaar** [comment]
What about https://github.com/Z3Prover/z3/releases?

Can be reached from the main page: see releases (in blue) below

![release](https://user-images.githubusercontent.com/18348654/33719963-c9f9603c-db62-11e7-896a-daa419c08474.jpg)

**Comment by facanferff** [comment]
There is no release of 4.6.0 there.

**Comment by wintersteiger** [comment]
There is no official release of 4.6.0 (yet). You can get nightly binaries here: https://github.com/Z3Prover/bin/tree/master/nightly

We do not save binaries for old commits, but you can always build your own from sources if you need old versions. 

The next release is overdue, lots of other stuff came in the way. There is no specific date though.
