### ISSUE TITLE
Excluding specific nodes in a z3 simplification result

### ISSUE THREAD

**Issue by JonathanSalwan** [Z3Prover/z3#1394]
hey,

Is it possible to exclude a specific node in a z3 simplification result? For example, I would like to simplify an expression (`z3::expr.simplify()`) but don't want to find any `iff` node in the simplified result. Is there a way to do that?

thanks,

**Comment by NikolajBjorner** [comment]
It isn't very customizable, but you can write your own functions that rewrite subterms by walking expressions and re-building them. It is useful to use memorization so you make sure you traverse a DAG instead of a tree traversal.

**Comment by JonathanSalwan** [comment]
Got it, thanks =)
