### ISSUE TITLE
Possible bug in string operation indexof

### ISSUE THREAD

**Issue by OrenGitHub** [Z3Prover/z3#1397]
I have this query that **works just fine**:

    (declare-const sj String)
    (declare-const si String)
    (declare-const i     Int)
    (declare-const j     Int)
    (declare-const k     Int)
    
    (assert (= i  (str.indexof si "#"    0)))
    (assert (= j  (str.indexof si "$"    0)))
    (assert (= k  (str.indexof si "@"    0)))
    (assert (= (str.indexof si "\x00" 0)  4))
    (assert (< 3 i))
    (assert (< i j))
    (assert (< j k))
    (assert (= (= sj "TT8G") false))
    
    (check-sat)
    (get-value (sj si i j k))

With **correct output** (there are two spaces in the beginning of si)

    sat
    ((sj "!0!")
     (si "  \x04\x10\x00\x00#\x00$@")
     (i 6)
     (j 8)
     (k 9))

Then I changed the = to > in the index of \x00:

    (declare-const sj String)
    (declare-const si String)
    (declare-const i     Int)
    (declare-const j     Int)
    (declare-const k     Int)
    
    (assert (= i  (str.indexof si "#"    0)))
    (assert (= j  (str.indexof si "$"    0)))
    (assert (= k  (str.indexof si "@"    0)))
    (assert (> (str.indexof si "\x00" 0)  4))
    ;changed ^ to > instead of =            ;
    (assert (< 3 i))
    (assert (< i j))
    (assert (< j k))
    (assert (= (= sj "TT8G") false))
    
    (check-sat)
    (get-value (sj si i j k))

And I get this **incorrect output**:

    sat
    ((sj "!0!")
     (si "\x00\x00\x00\x00#�$�\x00\x00@")
     (i 4)
     (j 6)
     (k 10))

Is this really a bug? Am I missing something here? Thanks!

**Comment by NikolajBjorner** [comment]
this is fixed in current master
