### ISSUE TITLE
In Python, convert from integer to bitvector for Z3

### ISSUE THREAD

**Issue by leesanghun910701** [Z3Prover/z3#1398]
Dear all,

Hello. I am fairly new to the Z3 solver, and I want to know whether there is a way to convert from integer to bitvector form.

Below is my example code:

===============================================

from z3 import *
import time

x_int, y_int = Ints('x_int y_int')
x_bit, y_bit = BitVecs('x_bit y_bit', 16)

// # I want to convert integer 'x' and 'y' to bit vector 'x_bit' and 'y_bit' and estimate variable 'result'
// # how to convert integer 'x_int' to bit vector 'x_bit' ?
// # use "z3_mk_int2bv"?

result = x_bit + y_bit

s = Solver()
s.add(x_int >= 0)
s.add(y_int >= 0)
s.add(result == 3)

print(s.check())
result = s.model()
print(result)

===============================================

Here, I want to convert 'x_int' and 'y_int' variables into their bit vector forms ('x_bit', 'y_bit') so that I can do bitwise operators on them.

Thank you very much in advance.

Best,
Lee.

**Comment by sdasgup3** [comment]
@NikolajBjorner any lead on this?

**Comment by NikolajBjorner** [comment]
update in python bindings, follow commit link above exposes method.
