### ISSUE TITLE
In Python, problem with defining global variables using Z3

### ISSUE THREAD

**Issue by leesanghun910701** [Z3Prover/z3#1399]
Dear all, 

Hello, I am fairly new to Z3 smt-solver, and I would like to get your opinions on the below problem.

So I have below code (main.py and func.py),

In main.py,
=======================================
from z3 import *
from func import *

// # here, let's say i want to insist using main(), calculation_without_input1(), calculation_without_input2() for some reason

def main():
	calculation_without_input1() 
	calculation_without_input2()

global x, y, z, result1, result2

x, y, z, result1, result2 = Ints('x y z result1 result2')

main()

s = Solver()
s.add(x >= 0)
s.add(y >= 0)
s.add(z >= 0)
s.add(result2 == 100)

print(s.check())
result = s.model()
print(result)

=======================================

In func.py
=======================================
  
def calculation_without_input1():
  global x, y, z, result1, result2
  result1 = x^2 + y^2

def calculation_without_input2():
  global x, y, z, result1, result2	
  result2 = result1 + z^2

=======================================

But, if I run main.py, I get error such as:

Traceback (most recent call last):
  File "main.py", line 14, in <module>
    main()
  File "main.py", line 7, in main
    calculation_without_input1() 
  File "/home/relab-01/download/z3-master/build/python/func.py", line 5, in calculation_without_input1
    result1 = x^2 + y^2
NameError: global name 'x' is not defined
=======================================

So my question is,

-> is there any way to define Z3 variables (variables x, y, z, result1, result2 in main.py file) so that I can use those values in other functions in other file?
(Here, let's say I want to insist on using those functions and separate files)

I am very sorry about the newbie question.

Thank you very much in advance :)

Best,
Lee.

**Comment by wintersteiger** [comment]
This is a general Python question, there's nothing specific to Z3 or the Z3 Python API. As far as I understand, variables in other files would need to be imported into the namespace before they can be used (via `global`), but I'm not a Python expert by any stretch of the imagination. This particular question seems to be popular on StackOverflow though, e.g. here: https://stackoverflow.com/questions/13034496/using-global-variables-between-files
