### ISSUE TITLE
Fixpoint engine 0-ary predicate and COI filter

### ISSUE THREAD

**Issue by mschlaipfer** [Z3Prover/z3#140]
The following input, containing a 0-ary predicate, yields sat with the COI filter disabled and unsat otherwise.

(set-option :fixedpoint.engine datalog)
(define-sort s () (_ BitVec 2))
(declare-rel f ())
(declare-rel e (s))
(declare-var a s)
(rule (=> (not f) (e a)))
(query (e #b01))

**Comment by NikolajBjorner** [comment]
Thanks, fixed
