### ISSUE TITLE
Unknown result in checking a first-order formula from the real closed field.

### ISSUE THREAD

**Issue by clpombo** [Z3Prover/z3#1404]
I am sorry if this was already discussed but I am new as a Z3 user. I am using Z3 to theorem prove first-order formulae stating properties of the real numbers. I am not doing anything in particular except declaring the formula in which every symbol used is declared as Real. The first-order theory of the real numbers is decidable as it is isomorphic to the real closed field [Tarski 1951] for which many decision procedures have been proposed, at least two with double exponential elementary complexity [Monk 1974, Collins 1975] and one with exponential space or parallel exponential time elementary complexity [Ben-Or 1986]. Based on this, I do not understand why Z3 responds Unknown when it could take a lot, but answer Sat or Unsat. 

Best regards and thanks.

**Comment by NikolajBjorner** [comment]
If you specify QF_NRA or NRA as the logic (if using SMTLIB2), then Z3 uses a decision procedure for quantifier-free or quantified, respectively, theories of polynomial reals. In default mode, Z3 uses an incomplete procedure that interacts with other decision procedures.

**Comment by clpombo** [comment]
Thank you very much for your kind answer. I checked my case-study and the logic is correctly set to NRA, run it again in case I had made a mistake and the answer is still Unknown. The case study is copied below:

The idea is the following, there is a service that charges some money to processing information, the cost is formed by: 1) cost per megabyte, 2) cost per second (while the session is open); on the other hand there are me time constraints regarding the wait period to be served, the maximum amount of time to process the information per gigabyte and the network speed. Some of these attributes are functions that depend on time of the day at which the service is requested. Axioms establish boundaries for those values and the property says that there is bound for the total amount of money to be paid which cannot be satisfied because the amount of information to be transferred and processed is not bounded.

(set-logic NRA)

(declare-fun maxWait () Real)
(declare-fun maxTimexGb () Real)
(declare-fun perSec (Real) Real)
(declare-fun netSpeedMb () Real)
(declare-fun costMb (Real) Real)

(assert
        ;contrato de provision
        (and
        (< 0 maxWait)
        (<= maxWait 100)
        (<= 1000 maxTimexGb)
        (<= maxTimexGb 3000)
        (< 0.05 netSpeedMb)
        (<= netSpeedMb 0.15)
        ; Restricciones sobre costMb

        ;0000 hs - 0600 hs
        (forall ( (tiempo Real) )
        (=> (and (<= 0 (mod (to_int tiempo) 86400)) (< (mod (to_int tiempo) 86400) 21600) ) (= (costMb tiempo) (* 0.5 (/ (perSec tiempo) netSpeedMb) ) ) ) )

        ;0600 hs - 0900 hs
        (forall ( (tiempo Real) )
        (=> (and (<= 21600 (mod (to_int tiempo) 86400)) (< (mod (to_int tiempo) 86400) 32400) ) (= (costMb tiempo) (* 0.8 (/ (perSec tiempo) netSpeedMb) )) ) )

        ; 0900 hs - 1800 hs
        (forall ( (tiempo Real) )
        (=> (and (<= 32400 (mod (to_int tiempo) 86400)) (< (mod (to_int tiempo) 86400) 64800)) (= (costMb tiempo) (/ (perSec tiempo) netSpeedMb) ) ) )

         ; 1800 hs - 2200 hs
        (forall ( (tiempo Real) )
        (=> (and (<= 64800 (mod (to_int tiempo) 86400)) (< (mod (to_int tiempo) 86400) 79200)  )  (= (costMb tiempo) (* 0.7 (/ (perSec tiempo) netSpeedMb) )) ) )

        ; 2200 hs - 2400 hs
        (forall ( (tiempo Real) )
        (=> (and (<= 79200 (mod (to_int tiempo) 86400)) (< (mod (to_int tiempo) 86400) 86400)  )  (= (costMb tiempo) (* 0.6 (/ (perSec tiempo) netSpeedMb) )) ) )

        ; Restricciones sobre perSec

        ;0000 hs - 0600 hs
        (forall ( (tiempo Real) )
        (=> (and (<= 0 (mod (to_int tiempo) 86400)) (< (mod (to_int tiempo) 86400) 21600) ) (= (perSec tiempo) 0.01) ) )

        ;0060 hs - 2100 hs
        (forall ( (tiempo Real) )
        (=> (and (<= 21600 (mod (to_int tiempo) 86400)) (< (mod (to_int tiempo) 86400) 75600) ) (= (perSec tiempo) 0.3) ) )

        ;2100 hs - 2400 hs
        (forall ( (tiempo Real) )
        (=> (and (<= 75600 (mod (to_int tiempo) 86400)) (< (mod (to_int tiempo) 86400) 86400) ) (= (perSec tiempo) 0.2) ) )

        (exists ((cota Real)) (forall ( (tiempo Real) ) (forall ((cantMb Real)) (< (* cantMb (costMb tiempo ) ) cota) ) ) )
        )
)



(check-sat)


Best regards and thank you for ny help you could provide us.

**Comment by NikolajBjorner** [comment]
There are several aspects of this example that takes it outside of the NRA fragment.

1. It uses functions such as (declare-fun perSec (Real) Real). It would make it the theory UFNRA (uninterpreted functions and non-linear real arithmetic). It is undecidable.
2. It uses conversions to integers.

**Comment by clpombo** [comment]
You are absolutely right, I never took into account the role of uninterpreted functions. Best regards and thank you for your help.

**Comment by NikolajBjorner** [comment]
If your formulas only use constants and not functions that take arguments it is not going to be using features of "UF". There is a lot of documentation on smtlib.org about what defines the theories QF_NRA and NRA and other theories and Z3 follows this. So take a look at this and any question about what it means is generic and not specific to Z3.

One note: there is no UFNRA support in Z3. It will ignore this annotation and just use a default configuration.

**Comment by clpombo** [comment]
Thank you very much for your help.

—

meu avô me ensinou a ser feliz
cachaça e mulheres

mas eu só aprendi a sofrer
mulheres e cachaça

		(Jorge Petrucio Viana, inédito)

**Comment by NikolajBjorner** [comment]
Try Malbec or other fine red wine.

**Comment by clpombo** [comment]
I lived in Rio de Janeiro during a part go my PhD and Petrucio, the author, is a logician there and a good friend of mine. During that period I got fond on natural cachaça and he gave me that beautiful poem written by him as a present.

Regarding malbec wine, I always do! I promise you a good bottle of Argentine malbec if our roads get to cross somewhere. 

Thank you again for your kind help.
