### ISSUE TITLE
Question about finding all possible solution of simple equation using Z3 in Windows 10, VS2013

### ISSUE THREAD

**Issue by leesanghun910701** [Z3Prover/z3#1405]
Dear all,

I am a newcomer in Z3 solver, and using Windows 10, VS2013 command prompt.

I am trying to use C and I have tried to solve the below problem using Z3 solver.

*problem set: what is the possible combination of a, b, c that satisfies a + 2*b + 3*c = 7?

So I made below C code, based on the C code example of Z3,

![capture1](https://user-images.githubusercontent.com/32499009/34056489-314bee78-e1a1-11e7-840c-d59402e372b0.PNG)

In result, I got the below result (after building and running 'c_example.exe')

![capture2](https://user-images.githubusercontent.com/32499009/34056512-43b4fbf4-e1a1-11e7-9bf1-95c0ec452514.PNG)

But I want to ask how to revise my c code to get all possible combination of a, b, c?
(e.g. a= 1, b = 0, c = 2/
a = 0, b = 2, c = 1/ and so on)

Thank you very much for your time.

Best,
Lee.

**Comment by wintersteiger** [comment]
The straightforward way to enumerate all models is to ask the solver multiple times, in each iteration adding a new constraint that negates the last found model. I.e., assert a new constraint of the form `(not (= a 1) (= b 0) ...)` and then run `check` again, until the problem becomes unsatisfiable.

**Comment by leesanghun910701** [comment]
Dear wintersteiger,

Thank you very much for your reply.

Can you kindly provide an example of c code that does what you enumerated?

I am new to Z3 code so I unfortunately don't know very much about how to write the code you mentioned.

I know your time is very precious, but it would be very grateful if you can provide me the example c code.

Thank you very much.

Sincerely,
Lee.

**Comment by wintersteiger** [comment]
Sorry, I have no time to do that for at least the next three weeks. See previous questions, e.g. [here](https://stackoverflow.com/questions/11867611/z3py-checking-all-solutions-for-equation) or [here](https://stackoverflow.com/questions/13395391/z3-finding-all-satisfying-models) or [here](https://stackoverflow.com/questions/32574193/z3-finding-all-satisfying-models-in-c). You may find it useful to set up a draft in Python (or another language) before dropping down to the C API level.
