### ISSUE TITLE
Caching sat results?

### ISSUE THREAD

**Issue by bannsec** [Z3Prover/z3#1407]
So, in playing around with Z3 more, I've discovered that it does not appear to cache sat results. For instance, assuming I had a bunch of assertions in the solver, something like:

```python
solver.check() # Takes time
solver.check() # Takes same amount of time
```

However, in-between, i have not modified the solver in any way. While this seems small, in `pySym`, I may be repeatedly calling check on the same arguments many times. I can add caching on my side as well, but I think this would be beneficial for other projects too.

Also, it would be good to copy that with the `solver.translate` method.

Sorry if I'm missing it and it's already implemented somewhere!

Edit: Actually, it looks like because of how `translate` copies, even caching on my side won't fully solve the cache problem as I will have to re-model after translate.

**Comment by NikolajBjorner** [comment]
solver.translate will be revised in spring. 
I had to revise it heavily and currently testing this in a separate branch.

I (little) repro on solving time persistence would be useful, although it is also one of the things I need to test as the sat solver is revised. It could heavily depend on what underlying solver is used. If it is a tactics, then there is zero reuse between calls. m

**Comment by bannsec** [comment]
Good to know. I do use tactics, though I can look at only applying them when i run into a case that needs it.

So there's no way to tell the tactics that nothing has changed and no need to be run?

Also, is there a way to do `model.translate`? Basically, whenever i have to state split I use translate to quickly give me a copy of the solver. If I'm understanding correctly, each time I do that, solver would have to re-create a model.

**Comment by NikolajBjorner** [comment]
> Also, is there a way to do model.translate
Good point although I haven't seen a use case for this before. 
There isn't a translate method on models, and models are not preserved if you translate the solver so you can't translate the solver and get the right model afterwards.
Your usage would have to store the model in the format that you will use it in the translated context.

**Comment by NikolajBjorner** [comment]
Added shorthand to API/python/C++ for model translation.

**Comment by bannsec** [comment]
Ah nice. Thanks!
