### ISSUE TITLE
Python assertions negative index and slicing

### ISSUE THREAD

**Issue by bannsec** [Z3Prover/z3#1408]
It would be helpful to have the ability to negatively index and slice in assertions. For example:

```python
a = solver.assertions()[1] # This works
a = solver.assertions()[-1] # This currently does not
a = solver.assertions()[10:15] # Does not
# Etc
```

**Comment by NikolajBjorner** [comment]
@bannsec 
Could you add a pull request for supporting such operator overloading to AstVector in z3.py?

**Comment by bannsec** [comment]
Yep. Will do.
