### ISSUE TITLE
Z3 crashes while solving SAT formula

### ISSUE THREAD

**Issue by rvprasad** [Z3Prover/z3#1411]
For attached formula, z3 crashes with following exception: 

    Unhandled exception at 0x00007FF7EE15726D in z3.exe: 0xC0000005: Access violation reading location 0x000002328361591C.

The same behavior was observed intermittently for other formulae.

Z3 version: 4.5.0
Platform: Windows Pro 10 OS build 1709
File: [unif-k4-r9.931-v2150-c21352-S5626512439144494001.txt](https://github.com/Z3Prover/z3/files/1570380/unif-k4-r9.931-v2150-c21352-S5626512439144494001.txt)

**Comment by NikolajBjorner** [comment]
It reproduces on 4.5 but not 4.6. The sat solver will get an overhaul in a later release too. Not sure if this is actionable as we won't patch 4.5. It seems to be a random benchmark. No unit clauses are produced. Better to use other methods than pure CDCL on them.

**Comment by rvprasad** [comment]
@NikolajBjorner When using z3 with no flags/configs, the number of such "failures" is 1% across a collection of formulae.  So, version 4.5 will do for my current exercise.

That said, what would be the ideal set of flags/config to use z3 as merely a solver to determine the satisfiability of SAT formulae (independent of nature, e.g., randomness)?  Or would you recommend using another solver for this purpose?

**Comment by NikolajBjorner** [comment]
The "ideal" config is the default configuration. It is the one tested to work across benchmarks.
For random or combinatorial problems use a combination of lookahead solvers and CDCL. They are not mainstream, except Treengeling incorporates online lookahead, which means that it creates relatively few CDCL problems. For DIMACS formatted problems, use the SAT competition results as a guideline for what solvers are actively maintained.

**Comment by NikolajBjorner** [comment]
no repro in current version of Z3.

**Comment by rvprasad** [comment]
There were more than few instances of such failures and they were inconsistent.  So, when I switch to the new version of z3, I will verify these failures and open a new ticket.  BTW, the failure occurs within seconds of starting z3.

**Comment by NikolajBjorner** [comment]
yes, I verified that the old version of Z3 crashed and the new version did not.

**Comment by rvprasad** [comment]
z3 failed inconsistently on different formulae.  If you are interested, I can post a list of these formulae.  Since this is not a blocker for me, I will open a new ticket if I encounter the issue again in the next round of experiments.
