### ISSUE TITLE
z3 python install error

### ISSUE THREAD

**Issue by umangm** [Z3Prover/z3#1413]
I tried to install the newest release 4.6.0 on MacOS. I am encountering a strange 'duplicate symbols error'.
```
duplicate symbol __ZN11proof_utils9is_closedER11ast_managerP3app in:
    muz/base/muz.a(proof_utils.o)
    ast/proofs/proofs.a(proof_utils.o)
duplicate symbol __ZN11proof_utils17reduce_hypothesesER7obj_refI3app11ast_managerE in:
    muz/base/muz.a(proof_utils.o)
    ast/proofs/proofs.a(proof_utils.o)
duplicate symbol __ZN11proof_utils22push_instantiations_upER7obj_refI3app11ast_managerE in:
    muz/base/muz.a(proof_utils.o)
    ast/proofs/proofs.a(proof_utils.o)
duplicate symbol __ZN11proof_utils23permute_unit_resolutionER7obj_refI3app11ast_managerE in:
    muz/base/muz.a(proof_utils.o)
    ast/proofs/proofs.a(proof_utils.o)
ld: 4 duplicate symbols for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [z3] Error 1
```
Is there a quick fix for this?

My setup command looks like:
```
python3 scripts/mk_make.py --python --pypkgdir=/usr/local/lib/python3.5/site-packages/
```
PS: I wish to install the new version for python3. On another note, is there a known performance issue when using z3 inside python3.5 (as against with python2.7) ?

**Comment by NikolajBjorner** [comment]
You probably still have old object files in the build output. Proof utils was migrated to a different directory and the old files may not be overwritten with the new build. Clean the directory with object files and see if this takes care of it.

**Comment by umangm** [comment]
Thanks. I did a fresh clone and then did the build. It worked like a charm.

Before we close this issue, I would like to know if one of python2 (specifically 2.7) or python3 (specifically 3.5) is more advisable to use when working with z3. That is, are there known performance differences between different python versions ?

**Comment by NikolajBjorner** [comment]
I am not aware of performance tradeoffs between python 2/3. 
It is not going to be as fast as using C++/Java/C#/ocaml.

You can disable debug asserts, https://stackoverflow.com/questions/1273211/disable-assertions-in-python, to avoid overhead with the asserts. We caught one nasty performance issue in z3.py a while ago (and it should be fixed for some time) where a call-by-value debug statement would pretty print expressions.

**Comment by delcypher** [comment]
@umangm 
> Thanks. I did a fresh clone and then did the build. It worked like a charm.

You should try using the CMake build system. With the CMake build system incremental builds should work properly. They definitely don't work properly in the old build system as you've discovered.
