### ISSUE TITLE
Any chance you could release x64 version for Ubuntu 14.04?

### ISSUE THREAD

**Issue by zvonimir** [Z3Prover/z3#1414]
We would appreciate that since due to some dependency issues we are not ready to switch to Ubuntu 16.04. Thanks!

**Comment by NikolajBjorner** [comment]
Can you build and add a pull request to z3prover/bin?

**Comment by zvonimir** [comment]
Yep, let me give that a try.

**Comment by zvonimir** [comment]
Ok, I am having some doubts how exactly I should invoke the python make script. Do I need to select `--staticlib` and/or `--staticbin`?
I suspect I should enable both of these flags. Yes?
I guess if you could provide me with an example invocation that would be helpful.

**Comment by wintersteiger** [comment]
You don't need either option, but if you want them, neither of them should make any trouble. 

Default invocation:

```
python scripts/mk_make.py
cd build
make
```

You'll get z3 and libz3.so in ./build.

Default invocation for building a .zip like our release packages:

```
python scripts/mk_unix_dist.py
```

(package will be at dist/z3*.zip).

Note that we can't add those default-build packages to our releases, because the .NET API won't be signed with our private key. We've never had a request for an x64 Ubuntu-14.04 package before, but technically it's not at its end of life yet. Who would benefit from us adding this, or will you distribute your preferred package anyways?

**Comment by zvonimir** [comment]
Ah, I see.
Sorry, but what do you mean by "your preferred package"?
We rely on your official packages, and in particular we've been relying on your Z3 4.5.0 x64 Ubuntu 14.04 package. Now, you did not create the same kind of package for Z3 4.6.0, even though you did create its x86 version.
We (meaning team SMACK) still have some Ubuntu 14.04 dependencies that we'll be stuck with for now (Travis CI, my department machines, etc.), which is why it would be helpful for us to have the Z3 4.6.0 x64 Ubuntu 14.04 package.

**Comment by wintersteiger** [comment]
Your preferred package = whatever you build yourself. 

Yes, we removed Ubuntu 14.04 some time ago, when we switched to 16.x (and we removed FreeBSD as well). I just kept the x86 part so we have at least on 32-bit Linux in the mix. Adding it back would mean quite a bit of effort for me (personally), so I'd rather not go there if nobody has an actual need for it. Did you try using the x86 binary on your x64?

**Comment by zvonimir** [comment]
Got it, thanks. I run into some issues running x86, but I think I should be able to resolve these, and it might be easier then you supporting x86. Let me look into this.

**Comment by wintersteiger** [comment]
Ah, I see! Let me know what the issue is, we definitely want it to compile on those platforms, so if that doesn't work we should fix fit.

**Comment by wintersteiger** [comment]
Wait! The nightly builds still include 14.04 x64; I only switched the CI builds to 16.x. In that case it won't be much effort to compile a release package at all, should be up in a few hours.

**Comment by zvonimir** [comment]
Awesome! Thanks a lot!

**Comment by wintersteiger** [comment]
Done! It's here: https://github.com/Z3Prover/z3/releases/download/z3-4.6.0/z3-4.6.0-x64-ubuntu-14.04.zip
