### ISSUE TITLE
[Questions] Z3Py using  pypy + cffi?

### ISSUE THREAD

**Issue by YHZX2013** [Z3Prover/z3#1417]
Is it possible to rewrite Z3Py using cffi?
And will this has better efficiency with pypy? 
Because it seems that (pypy + ctypes) is slow with frequent calls...
@leodemoura 

Thanks a lot.

**Comment by YHZX2013** [comment]
Anyone has any advices? :)

**Comment by wintersteiger** [comment]
I'm sure it's possible, but it would essentially require a rewrite of the existing Python API. The critical parts are in scripts/update_api.py, which generates the lower-level (ctypes) interface functions. I'm not sure it's worth the effort, but if you have the time to implement this (and ideally optimize it for performance), we would definitely welcome the contribution!

**Comment by YHZX2013** [comment]
Thanks.
