### ISSUE TITLE
how to represent  sum integer with infinite limit with in z3py as constraint?

### ISSUE THREAD

**Issue by VerifierIntegerAssignment** [Z3Prover/z3#1418]
Hi, I am new to z3py and SMT. I have a constraint like ∑i f(i) == x, and i =N, f is a function which accepts an integer as the parameter and returns the integer value. I want to represent this constraint in python, I have found a previous issue by zhanghv(#694) which is for the finite limit. How to express that for the infinite limit. Please help me to represent that constraint.Thank you!

**Comment by NikolajBjorner** [comment]
It is outside the scope of Z3 to represent infinite limits as first-class entities.
