### ISSUE TITLE
unstable branch: build failure on Mac

### ISSUE THREAD

**Issue by LeventErkok** [Z3Prover/z3#142]
Fresh pull from the unstable branch at f29d82858f937ef2965eaffc552b9df0e0367c3b fails to compile with:

```
duplicate symbol __Z16set_soft_inc_satP6solverjPKP4exprPK8rational in:
    opt/opt.a(inc_sat_solver.o)
    sat/sat_solver/sat_solver.a(inc_sat_solver.o)
ld: 1 duplicate symbol for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [z3] Error 1
```

**Comment by NikolajBjorner** [comment]
This is on a clean build?

**Comment by LeventErkok** [comment]
I did a `git pull; cd build; make` when I got that message.

I just repeated the same but first issued a `rm -rf build`; and it now compiles fine.

I usually don't blow of the `build` directory; but perhaps that's the recommended method?

In any case, I'm closing the ticket! Thanks for the prompt response..

**Comment by NikolajBjorner** [comment]
I moved a file, so old object file was lingering.
