### ISSUE TITLE
Strange model behaviour

### ISSUE THREAD

**Issue by 22459** [Z3Prover/z3#1424]
Hi, I don't know if this is a bug or I made a mistake in modeling, but the following model seems to behave strangely:
```(declare-const input (Array Int (_ BitVec 8))) ;array of unknown input chars
(declare-const result (Array Int (_ BitVec 8)))

;convenience constants
(declare-const length Int)
(assert (= length 24))

(declare-const maxidx Int)
(assert (= maxidx (- length 1)))

;used to make some expressions look simpler
(define-fun between ((i Int)) Bool
  (and (>= i 0) (<= i maxidx)) )

;set magic result array
(assert (= (select result 0) #xa2))
(assert (= (select result 1) #xa3))
(assert (= (select result 2) #xb2))
(assert (= (select result 3) #xa2))
(assert (= (select result 4) #xc0))
(assert (= (select result 5) #xb7))
(assert (= (select result 6) #xd5))
(assert (= (select result 7) #xa4))
(assert (= (select result 8) #xf0))
(assert (= (select result 9) #x80))
(assert (= (select result 10) #xee))
(assert (= (select result 11) #xe0))
(assert (= (select result 12) #xde))
(assert (= (select result 13) #xd4))
(assert (= (select result 14) #x7e))
(assert (= (select result 15) #xd2))
(assert (= (select result 16) #x86))
(assert (= (select result 17) #xed))
(assert (= (select result 18) #xd7))
(assert (= (select result 19) #xbe))
(assert (= (select result 20) #xa0))
(assert (= (select result 21) #xd0))
(assert (= (select result 22) #x9b))
(assert (= (select result 23) #xa0))

;input starts with 34C3_
(assert (and    (= (select input 0) #x33)
		(= (select input 1) #x34)
		(= (select input 2) #x43)
		(= (select input 3) #x33)
		(= (select input 4) #x5f) ))

;contains tzzzz (implicit in the previous+operation constraint actually I think)
(define-fun zzz ((i Int)) Bool
	(and    (between i) (<= (+ i 4) maxidx)
		(= (select input (+ i 0)) #x74)
		(= (select input (+ i 1)) #x7a)
		(= (select input (+ i 2)) #x7a)
		(= (select input (+ i 3)) #x7a)
		(= (select input (+ i 4)) #x7a) ))
(assert (exists ((i Int)) ;starting index for string exists
	(zzz i) ))

;contains mo4r
(define-fun moar ((i Int)) Bool
	(and    (between i) (<= (+ i 3) maxidx)
		(= (select input (+ i 0)) #x6d)
		(= (select input (+ i 1)) #x6f)
		(= (select input (+ i 2)) #x34)
		(= (select input (+ i 3)) #x72)
	))
(assert (exists ((i Int)) ;starting index for string exists
	(moar i) ))

;characters should be printable ascii
(define-fun printable_char ((c (_ BitVec 8))) Bool
	(and (bvuge c #x20) (bvule c #x7E)) )
(assert (forall ((i Int))
	(or
		(and (between i) (printable_char (select input i)))
        	(not (between i)) ) ))


;essential constraint: the operation implemented on the input that yields the result
(define-fun plusxor ((a (_ BitVec 8)) (b (_ BitVec 8))) (_ BitVec 8)
	(bvadd a (bvxor b #x15)) )
(assert (forall ((i Int))
	(or
		(and (between i) (= (plusxor (select input i) (select input (- maxidx i))) (select result i)) )
		(not (between i)) ) ))

(check-sat)
(get-model)
```

This is the output I get:
```sat
(model
  (define-fun input () (Array Int (_ BitVec 8))
    (_ as-array k!3))
  (define-fun result () (Array Int (_ BitVec 8))
    (_ as-array k!2))
  (define-fun i!1 () Int
    5)
  (define-fun i!0 () Int
    19)
  (define-fun maxidx () Int
    23)
  (define-fun length () Int
    24)
  (define-fun k!3!5 ((x!0 Int)) (_ BitVec 8)
    (ite (= x!0 3) #x33
    (ite (= x!0 5) #x6d
    (ite (= x!0 18) #x5f
    (ite (= x!0 7) #x34
    (ite (= x!0 11) #x69
    (ite (= x!0 15) #x6b
    (ite (= x!0 10) #x7b
    (ite (= x!0 1) #x34
    (ite (= x!0 17) #x73
    (ite (= x!0 19) #x74
    (ite (= x!0 4) #x5f
    (ite (= x!0 16) #x65
    (ite (= x!0 9) #x21
    (ite (= x!0 14) #x4a
    (ite (= x!0 0) #x33
    (ite (= x!0 13) #x66
    (ite (= x!0 12) #x62
    (ite (= x!0 2) #x43
    (ite (= x!0 8) #x72
    (ite (= x!0 (- 1)) #x1b
    (ite (= x!0 6) #x6f
      #x7a))))))))))))))))))))))
  (define-fun k!4 ((x!0 Int)) Int
    (let ((a!1 (ite (<= 22 x!0) (ite (<= 23 x!0) (ite (<= 24 x!0) 24 23) 22) 21)))
    (let ((a!2 (ite (<= 19 x!0)
                    (ite (<= 20 x!0) (ite (<= 21 x!0) a!1 20) 19)
                    18)))
    (let ((a!3 (ite (<= 16 x!0)
                    (ite (<= 17 x!0) (ite (<= 18 x!0) a!2 17) 16)
                    15)))
    (let ((a!4 (ite (<= 13 x!0)
                    (ite (<= 14 x!0) (ite (<= 15 x!0) a!3 14) 13)
                    12)))
    (let ((a!5 (ite (<= 10 x!0) (ite (<= 11 x!0) (ite (<= 12 x!0) a!4 11) 10) 9)))
    (let ((a!6 (ite (<= 7 x!0) (ite (<= 8 x!0) (ite (<= 9 x!0) a!5 8) 7) 6)))
    (let ((a!7 (ite (<= 4 x!0) (ite (<= 5 x!0) (ite (<= 6 x!0) a!6 5) 4) 3)))
    (let ((a!8 (ite (<= 1 x!0) (ite (<= 2 x!0) (ite (<= 3 x!0) a!7 2) 1) 0)))
      (ite (<= 0 x!0) a!8 (- 1)))))))))))
  (define-fun k!3 ((x!0 Int)) (_ BitVec 8)
    (k!3!5 (k!4 x!0)))
  (define-fun k!2!6 ((x!0 Int)) (_ BitVec 8)
    (ite (= x!0 5) #xb7
    (ite (= x!0 11) #xe0
    (ite (= x!0 18) #xd7
    (ite (= x!0 22) #x9b
    (ite (= x!0 15) #xd2
    (ite (= x!0 10) #xee
    (ite (= x!0 1) #xa3
    (ite (= x!0 9) #x80
    (ite (= x!0 16) #x86
    (ite (= x!0 17) #xed
    (ite (= x!0 4) #xc0
    (ite (= x!0 19) #xbe
    (ite (= x!0 12) #xde
    (ite (= x!0 21) #xd0
    (ite (= x!0 14) #x7e
    (ite (= x!0 13) #xd4
    (ite (= x!0 23) #xa0
    (ite (= x!0 20) #xa0
    (ite (= x!0 2) #xb2
    (ite (= x!0 8) #xf0
    (ite (= x!0 (- 1)) #x00
    (ite (= x!0 7) #xa4
    (ite (= x!0 6) #xd5
      #xa2))))))))))))))))))))))))
  (define-fun k!2 ((x!0 Int)) (_ BitVec 8)
    (k!2!6 (k!4 x!0)))
)

```

Why do the arrays have the item at (- 1) index defined?
Why arent all array elements in input between index 0 and 24 defined? Such as 20.

Related to the model but not strictly to the issue;
- Is there a way to conveniently define arrays? (Like in other languages normally)
- Is it possible to have a set/interval as the range type for arrays? So something like  `(declare-const input (Array (range 0 24) (_ BitVec 8)))`?

**Comment by 22459** [comment]
The context for this model is [https://junior.34c3ctf.ccc.ac/challenges/#challenge-panel-body-6](https://junior.34c3ctf.ccc.ac/challenges/#challenge-panel-body-6) ;)

**Comment by NikolajBjorner** [comment]
The model may be difficult to read, but it does define (select result 20) correctly.
Try

       (eval (select result 20))

to get the value.
Arrays are defined for all elements in their domain. Since arrays over integers have all integers in their domain some value has to be assigned for arbitrary integers in the domains.

Related questions:

- There isn't much in terms of conveniences for defining arrays other than what you can do with SMT-LIB and defining first-order formulas.
- For intervals: this will be better handled when having lambdas, but you can always add quantified formulas that define a function on a range of values. Z3's current module for quantifier reasoning does not do well with arrays (this will be improved, but not for  a while). You will therefore be better off by defining "result" and other "arrays" as functions and constrain their values using axioms.

**Comment by 22459** [comment]
Hey, sorry for the short reply for the moment; the issue is 20 isn't defined for "input" as far as I can tell. Getting "input" is the point of the model.

**Comment by NikolajBjorner** [comment]
the spec is missing declarations for input and a couple of other variables.

**Comment by 22459** [comment]
I may not be understanding correctly how arrays work, but doesn't
```(assert (forall ((i Int))
	(or
		(and (between i) (printable_char (select input i)))
        	(not (between i)) ) ))
```
Constrain "input" to have a value for indices 0..23?

**Comment by 22459** [comment]
Meanwhile I've discovered Strings and #1302 ; being able to access the characters of a string as the underlying `(_ BitVec 8)` would make this model a lot nicer.

**Comment by 22459** [comment]
Where should I read more about quantified formulas?

Thanks for all the help.

**Comment by NikolajBjorner** [comment]
> So it's just that the indices I thought were missing are defined implicitly, not explicitly. Correct?
Correct

> However the reason for the (-1) index being explicitly defined still isn't clear to me, since it shouldn't be used.
The model construction is free to introduce a default index, which could end up being set to -1.

> Where should I read more about quantified formulas?
It is a broad question given that this is a very wide area. 
Did you start with http://rise4fun.com/z3/tutorial? 
Based on your questions, I believe the main things to understand are the 
assumptions around classical first-order model theory which is described in off-the-shelf logic textbooks.
For instance the textbook by Bradley and Manna and the textbook by Kroening and Strichman on decision procedures contain background material.
An advanced tutorial on algorithms is in https://theory.stanford.edu/~nikolaj/q.html.

**Comment by 22459** [comment]
Err, to clarify, I could certainly use more background on logic, but I didn't understand the relationship to functions and axioms.

Thanks. I'll be getting around to studying logic soon.
