### ISSUE TITLE
Suspiciously slow on simple example

### ISSUE THREAD

**Issue by ghost** [Z3Prover/z3#1425]
Now sure if this is important or not.
Z3 is suspiciously slow on this example:
https://github.com/DennisYurichev/ToySMT/blob/master/examples/xkcd287.smt
While other SMT-solvers (Boolector and CVC4) are faster by factor of ~10x.

**Comment by NikolajBjorner** [comment]
Thanks, there is always something to learn and having targeted examples help.
In this case Z3 exhibits quite different runtimes between 0.2s and 6s depending on which value of sat.random_seed I use.

**Comment by NikolajBjorner** [comment]
The example is no longer accessible
