### ISSUE TITLE
Feature Request: Support Enumerating Solutions (without restarting)

### ISSUE THREAD

**Issue by 22459** [Z3Prover/z3#1426]
The z3 CLI tool does not have a way to enumerate multiple possible solutions. There have been suggestions to just iteratively add constraints to exclude previous solutions, but since that would require rerunning the entire model from scratch every time, is extremely inefficient.

**Comment by NikolajBjorner** [comment]
There are some different definitions of what it means to enumerate. 
It could be 

- with respect to all values of all variables.
- with respect to a subset of variables (others are treated as don't care).
- with respect to a subset of Boolean variables.

There are some good ways to enumerate models depending on the problem class. They don't generalize well across classes of problems. 
We haven't moved to support any of this as native APIs given the numerous possible ways to define such an enumeration.

**Comment by 22459** [comment]
Of course I don't know about implementation, but if all three are valid use cases, why not support all three?

I think most commonly one would expect the first (wrt. all values of all variables). The first is "just" a special case of the second case. Why is the third case separate?

Naturally I defer to your expertise in all things SMT, I just feel like this would be a useful feature that's unwarrantedly dismissed. I suppose it could be deferred to an interface implementer to deal with, but is it possible to add more constraints at a given execution point without restarting?

**Comment by 22459** [comment]
I figured it might be possible to do this directly in smtlib2 with a recursive function and push/check-sat/get-model (which might be considered abusive), but this already fails on push not being accepted in a function. :)

**Comment by wintersteiger** [comment]
The Python API should not be hard to set up, please submit an issue with the problems it throws up for you. 

Supporting multiple versions of model enumeration is currently not feasible for us. It would require way too much maintenance for a small amount of users and each of the users would want their own "flavour" of enumeration. But, if you're interested in maintaining them (perhaps starting with just some simple examples), we're happy to accept contributions.

**Comment by 22459** [comment]
Fair enough.
