### ISSUE TITLE
Implement __copy__ in z3.py

### ISSUE THREAD

**Issue by bannsec** [Z3Prover/z3#1427]
So I think it would be beneficial to implement `__copy__` in z3.py. Basically, I'd want `__copy__` to call `solver.translate`. I was able to make a simple modification on my side to override `__copy__` and it worked as I expected:

```python
In [68]: z3.z3.Solver.__copy__ = lambda self: self.translate(self.ctx)
In [69]: s2 = copy(s)
```

Basically, instead of just creating a link (as it does currently), copy creates an independent copy. If one wants to make a link, they just need to assign a new variable. copy, on the other hand, would be very beneficial.

**Comment by NikolajBjorner** [comment]
Perhaps it is also appropriate for __deepcopy__ and for other objects that expose translate?

https://docs.python.org/2/library/copy.html

**Comment by bannsec** [comment]
Makes sense to me. In my experience, deepcopy is hella slow (built-in book keeping), so given it's the same call I'd recommend using copy instead. Regardless, it would work for both.

**Comment by NikolajBjorner** [comment]
I think this is taken care of
