### ISSUE TITLE
Pareto Optimization

### ISSUE THREAD

**Issue by PatrickTrentin88** [Z3Prover/z3#1439]
**Premise:** the new approach adopted by **z3** to handle *Pareto Optimization* is incremental, the user is expected to run `(check-sat)` multiple times and if any new *Pareto-front* solution exists the search returns `SAT`. When no other *Pareto-front* solution exists, wrt. those that have already been printed, **z3** returns `UNSAT`. Any additional call to `(check-sat)` after `UNSAT` restarts the *Pareto Optimization* engine, making it enumerate again all solutions.

**Issue:** if there is only one objective function on the stack, **z3** does not seem to print `UNSAT` at the second `(check-sat)` call to state that there isn't any other *Pareto-front* solution. 

On the one hand, *Pareto* search with only one objective obviously degenerates to normal optimization search. On the other hand, the solver behaviour silently changes, forcing the end-user to keep track of the number of objectives currently loaded on the formula stack in order to correctly handle the `SAT/UNSAT` result (e.g. normally an `UNSAT` would signal the end of the *Pareto-search*, but when only one objective is loaded it will not be returned so this case would need special handling).

**question:** wouldn't it be more consistent to return `UNSAT` (every other `check-sat` call) even when dealing with only one objective function, if the user has manually set the `opt.priority` setting to be equal to `pareto`? This would relieve the end-user from handling any *corner-case* when scripting/coding for problems that are highly incremental or dealing with a benchmark-set with a non-uniform (and unknown) distribution of objectives.

**Comment by NikolajBjorner** [comment]
sounds like a reasonable suggestion.
