### ISSUE TITLE
Microsoft CL 19.00.22816: tactical.cpp and gparams.cpp do not compile (OpenMP).

### ISSUE THREAD

**Issue by bxcsgithubxb** [Z3Prover/z3#144]
Branch z3 master
python scripts/mk_make.py --java

tactical.cpp
..\src\tactic\tactical.cpp(613): error C3009: "Bezeichner": Einsprung in strukturierten Block von OpenMP ist nicht zulässig
..\src\tactic\tactical.cpp(783): error C3009: "Bezeichner": Einsprung in strukturierten Block von OpenMP ist nicht zulässig
NMAKE : fatal error U1077: ""C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\cl.EXE"": Rückgabe-Code "0x2"
Stop.

--after workaround:

..\src\util\gparams.cpp(349): error C3009: "Bezeichner": Einsprung in strukturierten Block von OpenMP ist nicht zulässig.
..\src\util\gparams.cpp(408): error C3009: "Bezeichner": Einsprung in strukturierten Block von OpenMP ist nicht zulässig.
..\src\util\gparams.cpp(505): error C3009: "Bezeichner": Einsprung in strukturierten Block von OpenMP ist nicht zulässig.
..\src\util\gparams.cpp(543): error C3009: "Bezeichner": Einsprung in strukturierten Block von OpenMP ist nicht zulässig.
NMAKE : fatal error U1077: ""C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\cl.EXE"": Rückgabe-Code "0x2"

**Comment by wintersteiger** [comment]
This is a known bug in Visual Studio 2015, see for instance here: [Regression from 2013: Jump into OpenMP structured block not allowed](https://connect.microsoft.com/VisualStudio/feedback/details/1298242/regression-from-2013-jump-into-openmp-structured-block-not-allowed)).
