### ISSUE TITLE
bv_val("#x0...2", 256) returns expr with null m_ast member

### ISSUE THREAD

**Issue by matzke1** [Z3Prover/z3#1443]
In the following code, the calls to `bv_val` return expressions with null `m_ast` members, which causes future operations on those expressions to seg fault.

```#include <z3++.h>

int main() {
    using namespace z3;
    context *ctx = new context;
    expr e1 = ctx->bv_val("x0000000000000000000000000000000000000000000000000000000000000002", 256);
    expr e2 = ctx->bv_val("x0000000000000000000000000000000000000000000000000000000000000002", 256);
    expr product = e1 * e2; // segmentation fault (tested with z3-4.5.0 and 4.6.)
}
```

**Comment by NikolajBjorner** [comment]
"x..." isn't a legal bv_val identifier. Z3 now throws properly.

**Comment by matzke1** [comment]
Thanks for fixing.

On a related note, what is the best way to transfer a large (>64 bit) 
bit vector stored in memory as an array of some unsigned type to a Z3 
bv_val? I'm fine converting to a binary/octal/hexadecimal string if 
necessary, just not a decimal string.
