### ISSUE TITLE
Z3 doesn't stop with sort mismatch error

### ISSUE THREAD

**Issue by DennisYurichev** [Z3Prover/z3#1445]
This is simple alphametics puzzle.
H+E+L+L+O = W+O+R+L+D =25

First I coded it (incorrectly) in Z3Py like this:

    from z3 import *

    # H+E+L+L+O = W+O+R+L+D = 25

    H, E, L, O, W, R, D = Ints ('H E L O W R D')

    s=Solver()

    s.add(Distinct(H, E, L, O, W, R, D))
    s.add(And(H>=1, H<=9))
    s.add(And(E>=1, E<=9))
    s.add(And(L>=1, L<=9))
    s.add(And(O>=1, O<=9))
    s.add(And(W>=1, W<=9))
    s.add(And(R>=1, R<=9))
    s.add(And(D>=1, D<=9))

    # this is incorrect:

    s.add(H+E+L+L+O == W+O+R+L+D == 25)

    print s.check()
    print s.model()

It gives incorrect solution: W+O+R+L+D is 25, but H+E+L+L+O is not 25.
It seems, the expression "W+O+R+L+D == 25" has a Bool type, which is then (incorrectly?) compared with H+E+L+L+O.

IMHO, error message would be fine.

This is correct, of course:

    s.add(H+E+L+L+O == 25)
    s.add(W+O+R+L+D == 25)

Now if to encode it in SMT-LIB v2 way (thanks to @clayrat):

    (declare-const H Int)
    (declare-const E Int)
    (declare-const L Int)
    (declare-const O Int)
    (declare-const W Int)
    (declare-const R Int)
    (declare-const D Int)
    (assert (distinct H E L O W R D))
    (assert (and (<= 1 H) (<= H 9)))
    (assert (and (<= 1 E) (<= E 9)))
    (assert (and (<= 1 L) (<= L 9)))
    (assert (and (<= 1 O) (<= O 9)))
    (assert (and (<= 1 W) (<= W 9)))
    (assert (and (<= 1 R) (<= R 9)))
    (assert (and (<= 1 D) (<= D 9)))
    (assert (= 
	        	(= 
		        	(+ (+ (+ (+ H E) L) L) O) 
        			(+ (+ (+ (+ W O) R) L) D))
        	25))
    (check-sat)
    (get-model)

Z3 gives error, but proceed to (incorrect) solution:

    (error "line 20 column 3: Sorts Bool and Int are incompatible")
    sat
    (model
      (define-fun L () Int
        3)
      (define-fun R () Int
        6)
      (define-fun D () Int
        7)
      (define-fun O () Int
        4)
      (define-fun W () Int
        5)
      (define-fun E () Int
        2)
      (define-fun H () Int
        1)
    )

Would it be better to stop after error?
Or, should it be treated as warning (int can be casted to bool in C/C++ at least)?
Just IMHO.

**Comment by NikolajBjorner** [comment]
It's equivalent to a warning. The assert is ignored. So the model is independent of the offending assert.

**Comment by pjljvandelaar** [comment]
Z3 is right!
In smt (= 25 a b) states 25 equals a and 25 equals b (and hence a equals b).
In smt (= 25 (= a b)) is wrong since 25 is an integer that  cannot be compared to the Boolean value (is a equal to b?)

See page 29 and 30 of https://www.google.nl/url?sa=t&source=web&rct=j&url=http://smtlib.cs.uiowa.edu/papers/smt-lib-reference-v2.0-r10.12.21.pdf&ved=2ahUKEwi0jZbQhNPYAhXpD8AKHVjgC_4QFjAAegQIFBAB&usg=AOvVaw3nY7t9zTioqJ3Z5pmvbOGO

**Comment by NikolajBjorner** [comment]
I don't see what new to do here: python overloading is helpful in many cases for coercing types. In this case it wasn't what you first thought it would do.
