### ISSUE TITLE
get-interpolant error in 4.6.0

### ISSUE THREAD

**Issue by franck44** [Z3Prover/z3#1449]
Hi,

In the latest release the get-interpolant command produces an error. This did not happen in the previous release. Happens with z3-4.6.0-x64-osx-10.11.6 and also z3-4.6.0-ubuntu-xx.xx.
I have looked at the recent release notes but could not find any changes related to get-interpolant.

Example file is from iZ3 page, say it is in file inter.smt2:
```(set-option :produce-interpolants true)
(declare-const a Int)
(declare-const b Int)
(declare-const c Int)
(declare-const d Int)
(assert (! (= a b) :named f1))
(assert (! (= a c) :named f2))
(check-sat)
(assert (! (= b d) :named f3))
(assert (! (not (= c d)) :named f4))
(check-sat)
(get-interpolant f1 f2 f3 f4)
```

Results are as follows:
z3-4.6.0-osx:

```
franck:~/testz3 $ z3 -version
Z3 version 4.6.0 - 64 bit
franck:~/testz3 $ z3 inter.smt2
sat
unsat
(error "line 12 column 28: bad term position!")
```
Note: line 12 col 28 is the first "f" in (get-interpolant f1 f2 f3 f4) 

z3-4.5.0-osx:

```
franck:~/testz3 $ ~/Downloads/z3-4.5.0-x64-osx-10.11.6/bin/z3 -version
Z3 version 4.5.0 - 64 bit
franck:~/testz3 $ ~/Downloads/z3-4.5.0-x64-osx-10.11.6/bin/z3 -smt2 inter.smt2
sat
unsat
(= a b)
(= b c)
(= c d)
```

**Comment by NikolajBjorner** [comment]
Closing as the code that was exercised in this issue is no longer part of the code base, #1646.
