### ISSUE TITLE
z3py - Python if statement throws z3.z3types.Z3Exception when using (!=)

### ISSUE THREAD

**Issue by chocolatier** [Z3Prover/z3#1454]
The following code snippet is used to find the index some select statement in an expression is reading from. 

```
def find_select_index(expr):
    if is_app_of(expr, Z3_OP_SELECT):
        return expr.children()[1]
    else:
        for x in expr.children():
            i = find_select_index(x)
            # (i != -1) kept getting interpreted as a boolean expression and
            # throwing an error
            if (i != -1):
                return i
        return -1
```

produces 
[Full Traceback](https://github.com/Z3Prover/z3/files/1641414/traceback.txt)
```
    i = find_select_index(x)
  File "repro.py", line 11, in find_select_index
    if (i != -1):
  File "/usr/lib/python2.7/dist-packages/z3/z3.py", line 302, in __nonzero__
    return self.__bool__()
  File "/usr/lib/python2.7/dist-packages/z3/z3.py", line 312, in __bool__
    raise Z3Exception("Symbolic expressions cannot be cast to concrete Boolean values.")
z3.z3types.Z3Exception: Symbolic expressions cannot be cast to concrete Boolean values.
```

However, changing the if statement to ```if (not i == -1)``` works as expected. 

repro file: https://gist.github.com/chocolatier/20ee5c9509f1c5a959c53ec3cffb0ddc

**Comment by NikolajBjorner** [comment]
Operators == and != are overloaded. One of the overloads accepts an expression and an integer and produces an expression.
You should check the type of the variable "i" before comparing it in a test inside of python. Use "isinstance(i , AstRef)" or "isinstance(i, int)"
