### ISSUE TITLE
Optimization: odd behaviour

### ISSUE THREAD

**Issue by DennisYurichev** [Z3Prover/z3#1455]
Not sure if this is my nitpicking again or not.
This is a simple problem, and this source code gives correct results:

    from z3 import *

    # Pablo buys popsicles for his friends. The store sells single popsicles for $1 each, 
    # 3-popsicle boxes for $2, and 5-popsicle boxes for $3. 
    # What is the greatest number of popsicles that Pablo can buy with $8?
    # http://artofproblemsolving.com/wiki/index.php?title=2017_AMC_12A_Problems/Problem_1

    box1pop, box3pop, box5pop = Ints('box1pop box3pop box5pop')
    pop_total = Int('pop_total')
    cost_total = Int('cost_total')

    s=Optimize()

    s.add(pop_total == box1pop*1 + box3pop*3 + box5pop*5)
    s.add(cost_total == box1pop*1 + box3pop*2 + box5pop*3)

    s.add(cost_total==8)

    s.add(box1pop>=0)
    s.add(box3pop>=0)
    s.add(box5pop>=0)

    s.maximize(pop_total)

    print s.check()
    print s.model()

Correct solution:

    sat
    [box3pop = 1,
     box5pop = 2,
     cost_total = 8,
     pop_total = 13,
     box1pop = 0]

However, if to remove all 3 "boxXpop>=0" constraints, z3 (4.6.0) goes crazy:

    sat
    [box3pop = 0,
     box5pop = 0,
     cost_total = 8,
     pop_total = 8,
     box1pop = 8]

So these additional constraints are really necessary?

**Comment by DennisYurichev** [comment]
Another example:

8th problem at http://artofproblemsolving.com/wiki/index.php?title=1959_AHSME_Problems

```
The value of $x^2-6x+13$ can never be less than:
4, 4.5, 5, 7, 13
```

Let's see:

```python
from z3 import *

x, res=Ints('x res')

s=Optimize()

s.add(res==x*x - 6*x + 13)

s.minimize(res)

print s.check()
print s.model()
```

Correct asnwer is x=3, res=4, see also: https://www.wolframalpha.com/input/?i=minimize+x*x-6x%2B13+over+[-100,100]

However, z3 gave:

```
sat
[x = 0, res = 13]
```

**Comment by LeventErkok** [comment]
This must have something to do with the Python bindings, as opposed to Z3 itself.

If I use the Haskell bindings I get:

```
Prelude Data.SBV> optimize Lexicographic $ forSome ["x"] $ \x -> minimize "res" (x*x - 6*x + 13::SInteger)
Optimal model:
  x   = 3 :: Integer
  res = 4 :: Integer
```

which matches the answer expected. A straightforward SMT-Lib based coding also produces the same result:

```
[plxck5046]~>cat opt.smt2
(set-option :produce-models true)
(set-logic ALL)
(declare-fun x () Int)
(declare-fun res () Int)
(assert (= res (+ (- (* x x) (* 6 x)) 13)))
(minimize res)
(check-sat)
(get-value (x res))
```

Z3 produces:

```
sat
((x 3)
 (res 4))
```

**Comment by NikolajBjorner** [comment]
I will be rewriting the integer optimization code in a few months, but until then:

For the first example, it seems that pop_total is unbounded if you don't constrain the three parameters to be non-negative. For example:

(declare-fun box5pop () Int)
(declare-fun box3pop () Int)
(declare-fun box1pop () Int)
(declare-fun pop_total () Int)
(declare-fun cost_total () Int)
(assert (= pop_total (+ (* box1pop 1) (* box3pop 3) (* box5pop 5))))
(assert (= cost_total (+ (* box1pop 1) (* box3pop 2) (* box5pop 3))))
(assert (= cost_total 8))
(maximize pop_total)
(assert (< box1pop -10))
(check-sat)
(get-objectives)
(get-model)

produces the output:

sat
(objectives
 (pop_total oo)
)
(model
  (define-fun box3pop () Int
    0)
  (define-fun box5pop () Int
    7)
  (define-fun cost_total () Int
    8)
  (define-fun pop_total () Int
    22)
  (define-fun box1pop () Int
    (- 13))
)

The best indicator for unbounded objectives is to use the handle returned by the maximize method.

For example, 

h = s.maximize(pop_total)
print(s)
print(s.check())
print(s.model())
print(h.value())

The output will contain the characters "oo" used for infinity. It is represented as a dummy integer variable called "oo".

For the second (non-linear) example, I get the "correct" result locally, but generally Z3 is not tested (and checked) for non-linear objectives or optimization in the context of non-linear constraints.

**Comment by NikolajBjorner** [comment]
I believe we can close this one
