### ISSUE TITLE
MBQI chokes on the first check of a model and runs out of memory

### ISSUE THREAD

**Issue by Will-cert** [Z3Prover/z3#1456]
Z3 version tested: 4.6.0 release 32-bit and 64-bit binaries for Windows

This script, which declares a function from 1-bit bit vectors to 1-bit bit vectors and asserts a couple properties on it, hangs while eating more and more RAM until it gives an out of memory error or access violation.

                (set-logic UFBV)
                (declare-fun n ((_ BitVec 1)) (_ BitVec 1))
                (assert (forall ((i (_ BitVec 1))) (= (n i) (ite (= i #b1) #b0 (n #b1)))))
                (assert (= (n #b0) #b0))
                (check-sat)

Apparently the tactics that Z3 uses for UFBV choke on this simple example. However, if the first line of the script is changed to (set-logic ALL), Z3 returns sat almost immediately. Other slight variants of this script can result in Z3 returning a result quickly, running out of memory, or hanging seemingly indefinitely while pinning a CPU core, depending on the input problem.

As a user who doesn't know much about how Z3 works internally, I find this particularly strange because the documentation at https://rise4fun.com/Z3/tutorial/guide seems to suggest that Z3 is complete for QBVF problems such as this because it can, in the worst case, flatten everything out into a SAT problem and solve that. Clearly this example should not generate a very large SAT problem!

**Comment by Will-cert** [comment]
Also here is a case using (set-logic ALL) that blows up memory usage to about 28 GB and crashes x86 machines. 

```
(set-logic ALL)

(declare-fun n1 ((_ BitVec 1)) (_ BitVec 1))
(declare-fun n2 ((_ BitVec 1)) (_ BitVec 1))
(assert (forall ((i1 (_ BitVec 1))) (= (n2 i1) (n1 i1))))
(assert (forall ((i1 (_ BitVec 1))) (= (n1 i1) (bvadd #b1 (n2 i1)))))

(push 1)
(check-sat)
```

**Comment by NikolajBjorner** [comment]
@wintersteiger the first one seems like a non-termination bug in the ufbv_rewriter

**Comment by wintersteiger** [comment]
@NikolajBjorner Confirmed, non-termination bug in the demodulator code. Working on it.

**Comment by wintersteiger** [comment]
The second example is a completely different problem. MBQI chokes on the first check of a model and runs out of memory (on my machine) after a long time. This may require a bit more time to fix, but in case you are in a verification context where you only care about unsatisfiability, you can disable MBQI altogether by adding these options:

```
(set-option :auto_config false)
(set-option :smt.mbqi false)
```

**Comment by Will-cert** [comment]
Should I split the two problems into separate issues, so that you can close them separately?

**Comment by wintersteiger** [comment]
No worries, I'll change the title of the issue to make it easier to indentify

**Comment by NikolajBjorner** [comment]
These are fixed in current master.
