### ISSUE TITLE
Request for help with int2bv / bv2int and possible bug (???)

### ISSUE THREAD

**Issue by OrenGitHub** [Z3Prover/z3#1457]
Hi,
I have [this SO post](https://stackoverflow.com/questions/48317925/z3-converting-from-bit-vectors-to-integers) which summarizes some of the questions regarding **int2bv** and **bv2int**.
It seems that finding a simple example where int2bv and/or bv2int fail
to behave as the semantics implied from their name is not that easy.
For example, the following query:

    (declare-const s String)
    (declare-const someBitVec3    (_ BitVec 3))
    (declare-const anotherBitVec3 (_ BitVec 3))
    (declare-const someInt                   Int)
    (declare-const anotherInt                Int)
    
    (assert (= (str.len s) (+ someInt anotherInt)))
    
    (assert (= (bv2int someBitVec3   ) someInt   ))
    (assert (= (bv2int anotherBitVec3) anotherInt))
    
    (assert (= (str.substr  s  0  6) "abcdef"))
    (assert (= (str.indexof s "#" 0) someInt))
    (assert (= (str.indexof s "$" 0) anotherInt))
    
    (assert (bvslt someBitVec3 anotherBitVec3))
    
    (check-sat)
    (get-value (s someInt anotherInt someBitVec3 anotherBitVec3))

Returns the expected answer:

    sat
    ((s "abcdef#$\x00\x00\x00\x00\x00")
     (someInt 6)
     (anotherInt 7)
     (someBitVec10 #b110)
     (anotherBitVec10 #b111))

Then I try to fail bv2int and force an overflow with this query,
but it really looks like I've hit a bug (???):

    (declare-const s String)
    (declare-const someBitVec3    (_ BitVec 3))
    (declare-const anotherBitVec3 (_ BitVec 3))
    (declare-const someInt                   Int)
    (declare-const anotherInt                Int)
    
    (assert (= (str.len s) (+ someInt anotherInt)))
    
    (assert (= (bv2int someBitVec3   ) someInt   ))
    (assert (= (bv2int anotherBitVec3) anotherInt))
    ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;; change abcdef to abcdefg
    (assert (= (str.substr  s  0   7) "abcdefg"))
    (assert (= (str.indexof s "#" 0) someInt))
    (assert (= (str.indexof s "$" 0) anotherInt))
    
    (assert (bvslt someBitVec3 anotherBitVec3))
    
    (check-sat)
    (get-value (s someInt anotherInt someBitVec3 anotherBitVec3))
    
And the **weird** result is:

    sat
    ((s "\x00$\x00\x00#")
     (someInt 4)
     (anotherInt 1)
     (someBitVec3 #b100)
     (anotherBitVec3 #b001))

**Comment by NikolajBjorner** [comment]
smt.string_solver=z3str3 produces the correct answer Unsat.

**Comment by NikolajBjorner** [comment]
Should be fixed now
