### ISSUE TITLE
Ackermanization

### ISSUE THREAD

**Issue by umangm** [Z3Prover/z3#1460]
Hi,
I see [here](z3/src/ackermannization/lackr.cpp) that z3 implements some form of Ackermann's redution.
Can I use these functions outside of the solver, and if so is there a readable API that I can refer to ?

**Comment by NikolajBjorner** [comment]
Yes these are tactics you can apply by using their names.

**Comment by NikolajBjorner** [comment]
Here is an example.

(declare-const a Bool)
(declare-const b Bool)
(declare-const c Bool)
(declare-fun f (Bool) Bool)

(assert (not (= (f a) (f b))))
(assert (= a c))
(apply ackermannize_bv)
