### ISSUE TITLE
Crash due to unsupported proof rules 

### ISSUE THREAD

**Issue by danieldietsch** [Z3Prover/z3#1470]
In the .zip file [z3-bad-proofs.zip](https://github.com/Z3Prover/z3/files/1689954/z3-bad-proofs.zip) are 120 scripts that all fail with a similar error while trying to obtain sequence interpolants for error traces. 

I ran them on z3 54ba251 with 
<code>
./z3 SMTLIB2_COMPLIANT=true -smt2 <file> 
</code>

The failure looks like 
````
Unsupported proof rule: 
(let ((a!1 
    (= 
        (and 
            (not |push_#t~switch1_11|) 
            (not (= |old(~pc1)_10| 2)) 
            false)
        false)))
    (rewrite a!1))
(error "line 207 column 352: theory not supported by interpolation or bad proof")
````

This seems like a bug to me.

**Comment by NikolajBjorner** [comment]
Closing as the code that was exercised in this issue is no longer part of the code base, #1646.
