### ISSUE TITLE
re.allchar behaves differently than with CVC4

### ISSUE THREAD

**Issue by varming** [Z3Prover/z3#1475]
It appears that `re.allchar` accepts all strings, yet in CVC4 it only accepts strings consisting of a single character. I know `re.range "\x00" "\xFF"` is a workaround, but it would be better if SMTLIB programs have the same meaning with different solvers. Any chance of Z3 changing the meaning of `re.allchar` to match CVC4?

This issue was previously reported in https://github.com/Z3Prover/z3/issues/843

**Comment by NikolajBjorner** [comment]
I updated the "semantics". z3str3 would need patching @mtrberzi.

**Comment by mtrberzi** [comment]
Sure, I will take a look. Just to confirm, `re.all` would accept any string, and `re.allchar` would accept any single character, correct?

**Comment by NikolajBjorner** [comment]
right, I retained re.all for the universal set.

**Comment by mtrberzi** [comment]
Opened #1508
