### ISSUE TITLE
Floating Point BitVectors NaN representation

### ISSUE THREAD

**Issue by franck44** [Z3Prover/z3#1477]
Hi,
I am trying some examples in the QF_FP theory and encountered some strange behaviours when using NaN. (I have looked up the issues but could not find anything related to this problem, so I am posting this new issue).

I am running Z3 version 4.6.0 - 64 bit, MacOSX.

1. Converting a NaN with a signbit equals to 1 to a bv 
```
(set-option :produce-models true)
(set-logic QF_FPBV)
(set-info :source "Negative NaN")

(declare-fun nan1 () Float32 )
(declare-fun c1 () (_ BitVec 1) )
(declare-fun c2 () (_ BitVec 8) )
(declare-fun c3 () (_ BitVec 23) )
(assert
  (and
    (= nan1 (fp #b1 #b11111111 #b10000000000000000000001))
    (= nan1 (fp c1 c2 c3))
  )
)
(check-sat)
(get-value (c1 c2 c3))
```
produces
```
sat
((c1 #b0)
 (c2 #xff)
 (c3 #b00000000000000000000001))
```
Both signbit (c1) and significand (c3) have been "normalised" to an internal representation of NaN.
This looks counter-intuitive but I assume there is a good reason to do so?

2. The following code
```
(assert
  (and
    (= nan1 (fp #b0 #b11111111 #b10000000000000000000001))
    (= nan1 (fp #b1 #b11111111 #b10000000000000000000001))
    (= nan1 (fp c1 c2 c3))
  )
)
(check-sat)
(get-value (c1 c2 c3))
``` 
evaluates to
```
sat
((c1 #b0)
 (c2 #xff)
 (c3 #b00000000000000000000001))
```
Why is it 'sat'? 

As I understand it, whenever a number isNaN Z3 converts it to a canonical NaN (c1, c2, c3) representation as above.
The IEEE standard defines NaNs as 's' '1......1' 'xxxxxxxxxxx' with one x not 0, which allows NaN with a signbit set to 1. 

Is there a way to define a NaN with a signbit 1 in Z3?

**Comment by wintersteiger** [comment]
IEEE754 is not the reference, instead it is the [SMT FloatingPoint theory](http://smtlib.cs.uiowa.edu/theories-FloatingPoint.shtml), which has only one NaN and it does not assume a bit-vector encoding is used internally. Z3 does use a translation to bit-vectors, but, again, there is only one NaN, so your `(fp #b0 ...)` all represent the same floating-point number. I.e., 
```
(assert
      (not (=  (fp #b1 #b11111111 #b10000000000000000000001)
               (fp #b0 #b11111111 #b10000000000000000000001)
)))
```
is unsatisfiable. The SMT theory also suggests the following to encode NaNs:
```
 :note
 "There is no function for converting from (_ FloatingPoint eb sb) to the
  corresponding IEEE 754-2008 binary format, as a bit vector (_ BitVec m) with 
  m = eb + sb, because (_ NaN eb sb) has multiple, well-defined representations.
  Instead, an encoding of the kind below is recommended, where f is a term
  of sort (_ FloatingPoint eb sb):

   (declare-fun b () (_ BitVec m))
   (assert (= ((_ to_fp eb sb) b) f))
"
```

(Related warning: Z3 also has a function called `fp.to_ieee_bv`, which is neither SMT nor IEEE compliant as it will always chose the same representation for NaNs, so in this context you do not want to use `fp.to_ieee_bv`.)

**Comment by NikolajBjorner** [comment]
I guess this is not a bug, so close
