### ISSUE TITLE
Bad performance using datatype discriminators 

### ISSUE THREAD

**Issue by danr** [Z3Prover/z3#148]
Here's a small example where using `ite` and a `is-`-discriminator destroys the performance of z3:

    (declare-sort sk_x 0)
    (declare-datatypes ()
      ((list (nil) (cons (head sk_x) (tail list)))))
    (declare-const z list)
    (declare-const w list)
    (declare-fun append (list list) list)
    (assert
      (forall ((x list) (y list))
        (= (append x y)
          (ite (is-cons x) (cons (head x) (append (tail x) y)) y))))
    (assert
      (distinct (append nil (append z w)) (append (append nil z) w)))
    (check-sat)

This does not terminate on 4.3.2, 4.3.1 or the git version. However, defining
append in this way by pattern-matching gives an almost instant `unsat`:

    (declare-sort sk_x 0)
    (declare-datatypes ()
      ((list (nil) (cons (head sk_x) (tail list)))))
    (declare-const z list)
    (declare-const w list)
    (declare-fun append (list list) list)
    (assert (forall ((ys list)) (= (append nil ys) ys)))
    (assert
      (forall ((x sk_x) (xs list) (ys list))
        (= (append (cons x xs) ys) (cons x (append xs ys)))))
    (assert
      (distinct (append nil (append z w)) (append (append nil z) w)))
    (check-sat)

Thanks,
Dan

**Comment by NikolajBjorner** [comment]
not much to do about such sources of non-termination other than noting that patterns benefit from being constructor based.
