### ISSUE TITLE
Strange define-fun behavior with Int/Real

### ISSUE THREAD

**Issue by AdrienChampion** [Z3Prover/z3#1484]
z3 reports an error for the following:

```smt2
(define-fun fun ( (v_0 Real) ) Bool true)
(assert (fun 1));      ^|^^
(check-sat); ^----------|
```

```smt2
(error "line 2 column 14: unknown function/constant fun")
sat
```

Column `14` is the `1` of `(fun 1)`. I just confirmed it on 792fdb915f7098177e6414e25a59373d3c7b9ca7 (latest at time of writing). But [rise4fun/z3](https://rise4fun.com/Z3/uJab) does not produce any error.

The error goes away if I pass a fraction instead:

```smt2
(define-fun fun ( (v_0 Real) ) Bool true)
(assert (fun (/ 1 1)))
(check-sat)
```

It works the other way around:

```smt2
(define-fun fun ( (v_0 Int) ) Bool true)
(assert (fun (/ 1 1)));^|^
(check-sat); ^^^^^^^----|
```

```smt2
(error "line 2 column 20: unknown function/constant fun")
sat
```

Column `20` is the `)` of `(/ 1 1)`. [Rise4fun/z3](https://rise4fun.com/Z3/6BIVU) does not complain.

Is this expected? I mean, the error is off, but are these scripts supposed to be rejected?

**Comment by AdrienChampion** [comment]
Super fast, thanks!

**Comment by mengwong** [comment]
The error is happening again, in 4.8.8 / 4.8.9. The https://github.com/Z3Prover/z3/commit/eab7ae58bec086583f630d8d4e4a5b4b4ac294e1 patch seems to have been undone in https://github.com/Z3Prover/z3/commit/5d3a4ee8050791ba23dacf6efe8ed7843445497b
