### ISSUE TITLE
Bad error message generated for (set-option :%s true) or (set-option :%n true)

### ISSUE THREAD

**Issue by jchl** [Z3Prover/z3#149]
Running z3 on a file containing just the following:

    (set-option :%s true)

produces an error message such as:

    (error "line 1 column 17: unknown parameter ',¿]☺Ï←Q'

Running z3 on a file containing just the following:

    (set-option :%n true)

produces (after a few seconds) the error:

    (error "out of memory")

This is using the latest code from unstable.

**Comment by NikolajBjorner** [comment]
thanks, fixed
