### ISSUE TITLE
infinite loop in proto_model::eval

### ISSUE THREAD

**Issue by kenmcmil** [Z3Prover/z3#1492]
In this example Z3 seems to get into an infinite loop in proto_model::eval, quickly exhausting memory. I would recommend running this in the debug version. Otherwise you have to kill it quickly to avoid thrashing your machine. It builds up a very long 'todo' list in proto_model::eval, which makes me think it might have built a cyclic expression node. If you remove the line '(push)' Z3 finishes quickly with a SAT result. 

repro: see the attached input file (and remove the .txt extension)
 
[infinite_loop.smt2.txt](https://github.com/Z3Prover/z3/files/1733079/infinite_loop.smt2.txt)

**Comment by NikolajBjorner** [comment]
it seems to be as follows: smt_model_finder.cpp extracts macros but does not detect a cyclic dependency between them.

**Comment by kenmcmil** [comment]
That's cute. In the input you have two formulas like this:

cond1 -> forall X. f(X) = ... g(X) ...
cond2 -> forall X. f(X) = g(X)

So if you happen to propositionally assign both forall sub-formulas to true, *and* if the macro finder gets the second equality backward (i.e, g(X) = f(X)) then you have a macro cycle in the pre-model.

Anyway, this is a bug, since Z3 is supposed to be a decision procedure for equality with stratified functions, so I'm re-opening.
 
I guess I could attempt a fix for this, but I'd be a bit afraid to break something. Is macro extraction just an optimization in smt_model_finder, or is it needed for completeness in some cases?

**Comment by NikolajBjorner** [comment]
Can you provide a real example of what was broken with the fix that filters out cyclic models from a step that optimizes model construction.

**Comment by kenmcmil** [comment]
Sorry Nikolaj -- I didn't get from your comment that the problem was fixed. Thanks!

**Comment by NikolajBjorner** [comment]
Comment was part of triage. Fix was 2 days later.
