### ISSUE TITLE
Difference between bv2int and Z3_mk_bv2int

### ISSUE THREAD

**Issue by OrenGitHub** [Z3Prover/z3#1493]
Hi,
Following the bv2int thread (#1481) there seems to be some
difference between the API Z3_mk_bv2int, and calling bv2int from an smt2 script like this:

    (declare-const i Int)
    (declare-const ibv (_ BitVec 5))
    
    (assert (= i (bv2int ibv 1)))
    
    (assert (< i 0))
    
    (check-sat)
    (get-value (i ibv))

And I get that bv2int expects only one parameter:

    (error "line 4 column 26: expecting one argument to bv2int")

Which one is right?
Can I specify signed-ness in bv2int from the above script?
Thanks!

**Comment by NikolajBjorner** [comment]
The signed version is just a shorthand made available over the binary API.

    from z3 import *
    b = BitVec('b', 5)

    print((BV2Int(b, True)).sexpr())
    # (ite (bvslt b #b00000) (- (bv2int b) 32) (bv2int b))
