### ISSUE TITLE
Get string from model bug?

### ISSUE THREAD

**Issue by kren1** [Z3Prover/z3#1498]
I think there might be a bug in the z3 c api for extracting strings. Basically I have a string constraints corresponding to something like:

```
if (strchr(p1,'A')
      && strchr(p1,'B')
      && strchr(p2,'D')
      && strchr(p2,'E')
      && strlen(p1) == 4
      && strlen(p2)  == 4
      && strcmp(p1,p2) == 0
      )
```
where p1 and p2 are abstract buffers. And I want z3 to give me back values for p1 and p2. I'm building the query with C api and then dumping it with `Z3_solver_to_string(builder->ctx, theSolver)` to get smt2 queries: [z3.smt2.txt](https://github.com/Z3Prover/z3/files/1748737/z3.smt2.txt) and with `Z3_open_log` to give you the actual C api interaction: [z3.log.txt](https://github.com/Z3Prover/z3/files/1748736/z3.log.txt).

When I run the `z3 z3.smt2` (the output of `Z3_solver_to_string` + check-sat + get-value), I get:
```
sat
((AB_serial_1_version_0 "EDBA\x00")
 (AB_serial_2_version_0 "EDBA\x00"))
```
 
for the last query. Which is *good*, because both abstract buffer are some permutation of BDEA and are equal.

However when I extract the contents of the two abstract buffers in the program, with something like:
```
Z3_model_eval(builder->ctx, 
              theModel, 
              Z3_mk_const(builder->ctx,
                          Z3_mk_string_symbol(builder->ctx,
                                              "AB_serial_1_version_0"),
                          Z3_mk_string_sort(builder->ctx)),
              Z3_TRUE, 
              &out);
printf("AB_serial_1_version_0 : %s",Z3_get_string(builder->ctx,out))
```
I get
```
AB_serial_1_version_0: BEAD\x00
AB_serial_2_version_0: BAED\x00
```

Which looks suspiciously right, but the strings are *not* equal. Actually the order can change, but it always contains the right letters.

So it seems the bug is either in my use of Z3 C api or in the API itself. Does the  [z3.log.txt](https://github.com/Z3Prover/z3/files/1748736/z3.log.txt)  suffice for you to reproduce this, without me finding a small C program that has this property?

**Comment by OrenGitHub** [comment]
Hi,
Here is a self contained c program that demonstrates the problem @kren1 mentions:

    void string_example()
    {
    	Z3_ast C;
    	Z3_ast M;
    
    	Z3_ast C_bv;
    	Z3_ast M_bv;
    
    	Z3_ast a1;
    	Z3_ast a2;
    	Z3_ast a3;
    	Z3_ast a4;
    	Z3_ast a5;
    	Z3_ast a6;
    	Z3_ast s1;
    	Z3_ast s2;
    	Z3_ast out;
    	Z3_ast x00;
    
    	Z3_ast p1_bv;
    	Z3_ast p2_bv;
    	Z3_ast p1_int;
    	Z3_ast p2_int;
    
    	Z3_ast one_int;
    	Z3_ast zero_int;
    	Z3_ast five_int;
    
    	Z3_ast cond0;
    	Z3_ast cond1;
    	Z3_ast cond2;
    	Z3_ast cond3;
    	Z3_ast cond4;
    	Z3_ast cond5;
    
    	Z3_ast one_bv;
    	Z3_ast zero_bv;
    	Z3_ast five_bv;
    
    	Z3_ast strlen_s1;
    	Z3_ast strlen_s2;
    	Z3_ast strchr_s1_M;
    	Z3_ast strchr_s2_C;
    
    	Z3_ast and_args[2];
    	Z3_ast sub_args[2];
    	Z3_ast add_args[2];
    	Z3_ast minusOne_int;
    
    	Z3_ast s1_0_to_4;
    	Z3_ast strchr_s1_0_to_4_M;
    	Z3_ast strchr_s1_0_to_4_x00;
    
    	Z3_ast s2_0_to_4;
    	Z3_ast strchr_s2_0_to_4_C;
    	Z3_ast strchr_s2_0_to_4_x00;
    
    	Z3_ast s1_to_first_x00;
    	Z3_ast s2_to_first_x00;
    
    	/***************/
    	/* [0] Context */
    	/***************/
        Z3_context ctx = mk_context();
    
    	/**************/
    	/* [1] Solver */
    	/**************/
        Z3_solver solver = mk_solver(ctx);
    
    	/*************/
    	/* [2] Sorts */
    	/*************/
    	Z3_sort int_sort    = Z3_mk_int_sort(ctx);
    	Z3_sort bv_8_sort   = Z3_mk_bv_sort(ctx,8);
    	Z3_sort bv_64_sort  = Z3_mk_bv_sort(ctx,64);
    	Z3_sort string_sort = Z3_mk_string_sort(ctx);
    
    	/********************************************/
    	/* [3] (declare-const one    (_ BitVec 64)) */
    	/*     (declare-const zero   (_ BitVec 64)) */
    	/*     (declare-const five   (_ BitVec 64)) */
    	/*     (assert (=  one #x0000000000000001)) */
    	/*     (assert (= zero #x0000000000000000)) */
    	/*     (assert (= five #x0000000000000005)) */
    	/********************************************/
    	one_bv   = Z3_mk_numeral(ctx,"1",bv_64_sort);
    	zero_bv  = Z3_mk_numeral(ctx,"0",bv_64_sort);
    	five_bv  = Z3_mk_numeral(ctx,"5",bv_64_sort);
    
    	one_int  = Z3_mk_bv2int(ctx,one_bv, Z3_TRUE);
    	zero_int = Z3_mk_bv2int(ctx,zero_bv,Z3_TRUE);
    	five_int = Z3_mk_bv2int(ctx,five_bv,Z3_TRUE);
    
    	M_bv = Z3_mk_numeral(ctx,"77",bv_8_sort);
    	C_bv = Z3_mk_numeral(ctx,"67",bv_8_sort);
    
    	p1_bv = Z3_mk_numeral(ctx,"435093805498",bv_64_sort);
    	p2_bv = Z3_mk_numeral(ctx,"439587345734",bv_64_sort);
    
    	p1_int = Z3_mk_bv2int(ctx,p1_bv,Z3_TRUE);
    	p2_int = Z3_mk_bv2int(ctx,p2_bv,Z3_TRUE);
    
    	sub_args[0] = zero_int;
    	sub_args[1] = one_int;
    
    	minusOne_int = Z3_mk_sub(ctx,2,sub_args);
    
    	/*********************************/
    	/* [4] (declare-const s1 String) */
    	/*     (declare-const s2 String) */
    	/*********************************/
    	s1 = Z3_mk_const(ctx,Z3_mk_string_symbol(ctx,"AB_serial_1_version_0"),string_sort);
    	s2 = Z3_mk_const(ctx,Z3_mk_string_symbol(ctx,"AB_serial_2_version_0"),string_sort);
    
    	/***********************************/
    	/* [5] (assert (= (str.len s1) 5)) */
    	/***********************************/
    	strlen_s1 = Z3_mk_seq_length(ctx,s1);
        cond0 = Z3_mk_eq(ctx,strlen_s1,five_int);
    	Z3_solver_assert(ctx,solver,cond0);
    
    	/***********************************/
    	/* [6] (assert (= (str.len s2) 5)) */
    	/***********************************/
    	strlen_s2 = Z3_mk_seq_length(ctx,s2);
        cond1 = Z3_mk_eq(ctx,strlen_s2,five_int);
    	Z3_solver_assert(ctx,solver,cond1);
    
    	/***********************************************/
    	/* [7] (assert (!= (str.indexof s1 "M" 0) -1)) */
    	/***********************************************/
    	M   = Z3_mk_seq_unit(ctx,M_bv);
    	x00 = Z3_mk_string(ctx,"\\x00");
    	s1_0_to_4 = Z3_mk_seq_extract(ctx,s1,zero_int,five_int);
    	strchr_s1_0_to_4_M   = Z3_mk_seq_index(ctx,s1_0_to_4,M,  zero_int);
    	strchr_s1_0_to_4_x00 = Z3_mk_seq_index(ctx,s1_0_to_4,x00,zero_int);
        a4 = Z3_mk_not(ctx,Z3_mk_eq(ctx,strchr_s1_0_to_4_M,minusOne_int));
    
    	add_args[0]=strchr_s1_0_to_4_M;
    	add_args[1]=p1_int;
    
    	a6 = Z3_mk_add(ctx,2,add_args);
    
    	and_args[0] = a4;
    	and_args[1] = Z3_mk_lt(ctx,strchr_s1_0_to_4_M,strchr_s1_0_to_4_x00);
    	a5 = Z3_mk_and(ctx,2,and_args);
    
    	cond2 = Z3_mk_not(ctx,Z3_mk_eq(ctx,Z3_mk_ite(ctx,a5,a6,zero_int),zero_int));
    	Z3_solver_assert(ctx,solver,cond2);
    
    	/***********************************************/
    	/* [7] (assert (!= (str.indexof s1 "M" 0) -1)) */
    	/***********************************************/
    	C   = Z3_mk_seq_unit(ctx,C_bv);
    	// x00 = Z3_mk_string(ctx,"\\x00");
    	s2_0_to_4 = Z3_mk_seq_extract(ctx,s2,zero_int,five_int);
    	strchr_s2_0_to_4_C   = Z3_mk_seq_index(ctx,s2_0_to_4,C,  zero_int);
    	strchr_s2_0_to_4_x00 = Z3_mk_seq_index(ctx,s2_0_to_4,x00,zero_int);
        a4 = Z3_mk_not(ctx,Z3_mk_eq(ctx,strchr_s2_0_to_4_C,minusOne_int));
    
    	add_args[0]=strchr_s2_0_to_4_C;
    	add_args[1]=p2_int;
    
    	a6 = Z3_mk_add(ctx,2,add_args);
    
    	and_args[0] = a4;
    	and_args[1] = Z3_mk_lt(ctx,strchr_s2_0_to_4_C,strchr_s2_0_to_4_x00);
    	a5 = Z3_mk_and(ctx,2,and_args);
    
    	cond2 = Z3_mk_not(ctx,Z3_mk_eq(ctx,Z3_mk_ite(ctx,a5,a6,zero_int),zero_int));
    	Z3_solver_assert(ctx,solver,cond2);
    
    	/**************************/
    	/* [8] (assert (= s1 s2)) */
    	/**************************/
    	s1_to_first_x00 = Z3_mk_seq_extract(ctx,s1_0_to_4,zero_int,strchr_s1_0_to_4_x00);
    	s2_to_first_x00 = Z3_mk_seq_extract(ctx,s2_0_to_4,zero_int,strchr_s2_0_to_4_x00);
    	cond3 = Z3_mk_eq(ctx,s1_to_first_x00,s2_to_first_x00);
    
    	/*******************/
    	/* [9] (check-sat) */
    	/*******************/
    	if (Z3_solver_check(ctx,solver))
    	{
            printf("\nHere are my two strings:\n");
            printf("======================= \n\n");
            printf("%s\n",Z3_model_to_string(ctx,Z3_solver_get_model(ctx, solver)));
    
    		FILE *fl=fopen("/home/oren/GIT/z3_queries/example_from_test_capi.txt","w+t");
            //printf("\nHere is the query:\n");
            //printf("================= \n\n");
            fprintf(fl,"%s\n",Z3_solver_to_string(ctx, solver));
    		fclose(fl);
    
            //printf("\nHere is just s1:\n");
            //printf("================= \n\n");
    		//Z3_model_eval(ctx,Z3_solver_get_model(ctx,     solver),Z3_mk_const(ctx,Z3_mk_string_symbol(ctx,"s1"),string_sort),1,&out);
            //	printf("%s\n",Z3_get_string(ctx,out));
    	}
    	/**********************************/
    	/* [10] delete solver and context */
    	/**********************************/
    	del_solver(ctx, solver);
    	Z3_del_context(ctx);
    }

When I look at the output of the program I get **different** strings:

    
    Here are my two strings:
    ======================= 
    
    AB_serial_2_version_0 -> "C\x00C�\x00"
    AB_serial_1_version_0 -> "\x04\x10M\r\x00"
    

But when I run the stand alone query example_from_test_capi.txt I get **identical** strings like I should:

    sat
    ((AB_serial_1_version_0 "�\x01MC\x00")
     (AB_serial_2_version_0 "�\x01MC\x00"))

**Comment by NikolajBjorner** [comment]
You seem to miss adding cond3 to the solver. I get equal strings if I add the line

	Z3_solver_assert(ctx,solver,cond3);

**Comment by OrenGitHub** [comment]
Sorry you're right ... when I add cond3 to the solver I am no longer able to see any difference between API and smt2 script. The original query comes from a symoblic execution context (KLEE) and is significantly larger. I've tried creating a minimal counter example but I guess I got it wrong in some point. I'll try to recreate it again. Thanks.

**Comment by OrenGitHub** [comment]
I've **failed to create a self contained example**, though the generated query from **my independent c file** (with Z3_solver_to_string(ctx,solver)) is identical to the query **KLEE emits** (with Z3_solver_to_string(ctx,solver)). If I want to be precise, there is a slight difference, that KLEE further outputs this line (**which is redundant right?**)

    (assert (not false))

My independent c file outputs the **correct** results with API, but KLEE outputs **wrong** results with API calls. Any ideas how we can proceed in debugging this? Thanks ...

**Comment by NikolajBjorner** [comment]
with some luck the z3.log.txt files (if extracted from a faulty behavior) would be the way to go.

**Comment by kren1** [comment]
@NikolajBjorner Thanks for the response! How do you see the last model generated by the z3.log.txt? I tried `z3 -log z3.log.txt` but that doesn't print anything meaningful.

Also I assume the models inside z3 would be correct, as the smt2 queries print the correct models and in the models obtained through the api only the order is wrong. I would guess something goes wrong when extracting the actual c_string out of them when things go wrong. Would z3.log.txt reflect this? As in print the actual values returned from `Z3_get_string`  calls in the replay?

**Comment by NikolajBjorner** [comment]
I instrumented the Z3 code locally with more options for verbose output.
When also instrumenting the get_string method I see that you call it in two different instances and for two different models. The returned strings are different, but for the two models, the values of your two variables are the same, just in one model it is DEBA\x00 and in the other model it is BADE\x00.

**Comment by kren1** [comment]
Ah okay, thanks for looking into this! I wouldn't be able to see the problem otherwise.
