### ISSUE TITLE
Crash with bare variable of type Bool in the tail of a horn rule

### ISSUE THREAD

**Issue by jchl** [Z3Prover/z3#150]
Running z3 on the following file:

    (set-logic HORN)
    (declare-const a Bool)
    (assert (forall ((x Bool)) (=> x a)))
    (check-sat)

results in an assertion failure with the following stack trace:

 	z3.exe!to_app(ast * n) Line 857	C++
 	z3.exe!hnf::imp::is_horn(expr * n) Line 115	C++
 	z3.exe!hnf::imp::operator()(expr * n, app * p, ref_vector<expr,ast_manager> & result, ref_vector<app,ast_manager> & ps) Line 137	C++
 	z3.exe!hnf::operator()(expr * n, app * p, ref_vector<expr,ast_manager> & rs, ref_vector<app,ast_manager> & ps) Line 518	C++
 	z3.exe!datalog::rule_manager::mk_rule_core(expr * fml, app * p, datalog::rule_set & rules, const symbol & name) Line 196	C++
 	z3.exe!datalog::rule_manager::mk_rule(expr * fml, app * p, datalog::rule_set & rules, const symbol & name) Line 173	C++
 	z3.exe!datalog::context::flush_add_rules() Line 466	C++
 	z3.exe!datalog::context::query(expr * query) Line 875	C++
 	z3.exe!horn_tactic::imp::verify(expr * q, const ref<goal> & g, sref_buffer<goal,16> & result, ref<model_converter> & mc, ref<proof_converter> & pc) Line 258	C++
 	z3.exe!horn_tactic::imp::operator()(const ref<goal> & g, sref_buffer<goal,16> & result, ref<model_converter> & mc, ref<proof_converter> & pc, obj_ref<dependency_manager<ast_manager::expr_dependency_config>::dependency,ast_manager> & core) Line 247	C++
 	z3.exe!horn_tactic::operator()(const ref<goal> & in, sref_buffer<goal,16> & result, ref<model_converter> & mc, ref<proof_converter> & pc, obj_ref<dependency_manager<ast_manager::expr_dependency_config>::dependency,ast_manager> & core) Line 381	C++
 	z3.exe!cleanup_tactical::operator()(const ref<goal> & in, sref_buffer<goal,16> & result, ref<model_converter> & mc, ref<proof_converter> & pc, obj_ref<dependency_manager<ast_manager::expr_dependency_config>::dependency,ast_manager> & core) Line 1188	C++
 	z3.exe!exec(tactic & t, const ref<goal> & in, sref_buffer<goal,16> & result, ref<model_converter> & mc, ref<proof_converter> & pc, obj_ref<dependency_manager<ast_manager::expr_dependency_config>::dependency,ast_manager> & core) Line 179	C++
 	z3.exe!check_sat(tactic & t, ref<goal> & g, ref<model> & md, obj_ref<app,ast_manager> & pr, obj_ref<dependency_manager<ast_manager::expr_dependency_config>::dependency,ast_manager> & core, std::basic_string<char,std::char_traits<char>,std::allocator<char> > & reason_unknown) Line 201	C++
 	z3.exe!tactic2solver::check_sat_core(unsigned int num_assumptions, expr * const * assumptions) Line 142	C++
 	z3.exe!solver_na2as::check_sat(unsigned int num_assumptions, expr * const * assumptions) Line 67	C++
 	z3.exe!combined_solver::check_sat(unsigned int num_assumptions, expr * const * assumptions) Line 218	C++
 	z3.exe!cmd_context::check_sat(unsigned int num_assumptions, expr * const * assumptions) Line 1442	C++
 	z3.exe!smt2::parser::parse_check_sat() Line 2018	C++
 	z3.exe!smt2::parser::parse_cmd() Line 2332	C++
 	z3.exe!smt2::parser::operator()() Line 2471	C++
 	z3.exe!parse_smt2_commands(cmd_context & ctx, std::basic_istream<char,std::char_traits<char> > & is, bool interactive, const params_ref & ps) Line 2519	C++
 	z3.exe!read_smtlib2_commands(const char * file_name) Line 128	C++
 	z3.exe!main(int argc, char * * argv) Line 342	C++
 	[External Code]	
 	[Frames below may be incorrect and/or missing, no symbols loaded for kernel32.dll]	

This is in the predabst branch, but I don't believe this is related to any predabst-specific code, and therefore I would expect this bug to be present in the latest unstable code as well.

**Comment by NikolajBjorner** [comment]
fixed
