### ISSUE TITLE
The solver slows down of java version when using multi-thread

### ISSUE THREAD

**Issue by destinyfucker** [Z3Prover/z3#1504]
I am using the java version of z3 for constraint solving.Recently I try to use multi-thread, and the problem occurs: the solving speed slows down when using several contexts in different threads.The codes are like this: 
	private void  start(int num) {
		for (int i = 0; i <num; i++) {
			new MyThread(i).start();
		}
	}
	
	class MyThread extends Thread{
		private int index= 0;
		public MyThread(int index) {
			this.index = index;
		}
		@Override
		public void run() {
			for (int i =index; i < 10000; i = i + 5) {
				Context ctx = new Context();
				Expr mystr = ctx.mkConst("mystr", ctx.mkStringSort());
				SeqExpr suff = ctx.mkString("end" + i);
				SeqExpr contain = ctx.mkString("contain" + i);

				Solver solver = ctx.mkSolver();
				
				solver.add(ctx.mkSuffixOf(suff, (SeqExpr)mystr));
				solver.add(ctx.mkContains((SeqExpr)mystr, contain));
				
				long before = System.currentTimeMillis();
				if (Status.SATISFIABLE == solver.check()) {
		            Model model = solver.getModel();
		            String output = model.evaluate(mystr, false).toString();
				}
				long after = System.currentTimeMillis();
				System.out.println(after-before);
				ctx.close();
			}
		}
	}

When i set 'num' to 5 , the result is : 16 31 31 16 32 16 16 31 31 16 15 15 16 32 32 16 31........
And when i set 'num' to 1, the result is :15 16 0 0 16 0 0 15 16 0 15 16 0 15 16 0 0.......

Is it the right behavior of z3?

The OX is Windows and my PC has a quad-core processor.
Does multi-thread can not speed up java version of z3? Or I missed some settings for it?

**Comment by NikolajBjorner** [comment]
You are like hitting contention issues, esp. On small queries.
