### ISSUE TITLE
Using (check-sat) twice causes inconsistent models

### ISSUE THREAD

**Issue by bj2015** [Z3Prover/z3#1509]
I am not sure whether or not it is allowed to use `(check-sat)` twice in an SMTLIB-run, but when I did, I came across this really strange phenomenon:

The following snippet of SMTLIB
```
(set-option :produce-models true)

(set-logic QF_NRA)

(declare-const d Real)
(declare-const b Real)
(declare-const c Real)
(declare-const a Real)

(check-sat)

(assert (<= a b))
(assert (<= b c))
(assert (>= a 0.0))
(assert (= d (/ 1.0 c)))
(assert (not (<= d (/ 1.0 b))))

(check-sat)

(get-value (a b c d))
```
yields the following output when passed to `z3 -smt2 snippet.smt2`

```
sat
sat
((a 0.0)
 (b 0.0)
 (c (/ 1.0 2.0))
 (d (/ 1.0 2.0)))
```

which is really strange since c = 1/2 and d=1/2 clearly contradicts d = 1 / c, which was asserted in the snippet.
When trying to make the example more minimal I noticed that removing the first (check-sat) resolves this issue. The model reported in that case seems to be correct.

As stated initially, I am not sure whether it is allowed to use `(check-sat)` twice in SMTLIB. However, when doing it can lead to inconsistent models, which seems to be the case, I would strongly suggest to at least issue a warning in this case.

**Comment by bj2015** [comment]
Almost forgot:
I am using Z3 version 4.5.0 - 64 bit on MacOS 10.12.6

**Comment by NikolajBjorner** [comment]
Right, we fixed bugs in model generation for non-linear arithmetic when using the incremental solver (this gets used if you call check-sat the second time or perform push/pop operations. So this does not repro in the latest version of Z3.

**Comment by bj2015** [comment]
You are right. I updated to 4.6.0 and could not reproduce the problem either. Thanks!
