### ISSUE TITLE
z3 fails to do proper type-checking for Horn rules

### ISSUE THREAD

**Issue by jchl** [Z3Prover/z3#151]
When z3 is given the following file:

    (set-logic HORN)
    (declare-fun p (Int) Bool)
    (assert (forall ((x Real)) (p x)))
    (check-sat)

it will produce a result of "sat", even though the type of the application (p x) is incorrect.

If the type of x in the above example is changed from Real to Bool, then the result is an assertion failure (in debug mode):

    #26 := (:var 0 Bool)
    (p #26)

    Expected sort: Int
    Actual sort:   Bool
    Function sort: (declare-fun p (Int) Bool).
    ASSERTION VIOLATION
    File: ..\src\muz\fp\horn_tactic.cpp
    Line: 188
    g->is_well_sorted()

This is in the predabst branch, but this is not using predabst-specific code, so the bug is likely present in the latest unstable branch too.

**Comment by NikolajBjorner** [comment]
The bug is not present in the unstable branch. The unstable branch inserts a type coercion to_int, which is the default behavior for mixed integer/real usage.
