### ISSUE TITLE
4.6.0 hangs while solving a formula that 4.5.0 could solve quickly

### ISSUE THREAD

**Issue by leonardoalt** [Z3Prover/z3#1511]
Hi all,

I've got the formula below, which is solved (SAT) by 4.5.0 in ~0.2s in my machine. When trying to solve the same formula with 4.6.0, it hangs.
Any thoughts?

Cheers!

```
(declare-fun x_4 (Int) Int)
(declare-fun y_6 (Int) Int)
(declare-fun _9 (Int) Int)
(declare-fun expr_12 () Int)
(declare-fun expr_13 () Int)
(declare-fun expr_14 () Bool)
(declare-fun expr_17 () Int)
(declare-fun expr_18 () Int)
(assert (>= (x_4 0)
    (- 57896044618658097711785492504343953926634992332820282019728792003956564819968)))
(assert (<= (x_4 0)
    57896044618658097711785492504343953926634992332820282019728792003956564819967))
(assert (>= (y_6 0)
    (- 57896044618658097711785492504343953926634992332820282019728792003956564819968)))
(assert (<= (y_6 0)
    57896044618658097711785492504343953926634992332820282019728792003956564819967))
(assert (= (_9 0) 0))
(assert (= expr_12 (y_6 0)))
(assert (= expr_13 0))
(assert (= expr_14 (not (= expr_12 expr_13))))
(assert (or (not true) expr_14))
(assert (= expr_17 (x_4 0)))
(assert (= expr_18 (y_6 0)))
(assert (not (= expr_18 0)))
(assert (let ((a!1 (ite (>= expr_18 0)
                (div expr_17 expr_18)
                (- 0 (div expr_17 (- 0 expr_18)))))
      (a!2 (ite (>= expr_18 0)
                (- 0 (div (- 0 expr_17) expr_18))
                (div (- 0 expr_17) (- 0 expr_18)))))
  (and true
       (> (ite (>= expr_17 0) a!1 a!2)
          57896044618658097711785492504343953926634992332820282019728792003956564819967))))
(check-sat)
```

**Comment by NikolajBjorner** [comment]
it uses non-linear arithmetic (integer division). there were bugs in model construction for this in 4.5 and it is possible that the fixes required for this influences the behavior here.

**Comment by NikolajBjorner** [comment]
It seems to struggle with the nested ite expressions. If you run Z3 with the option rewriter.pull_cheap_ite=true, it finishes quickly. The pre-processor changed significantly last August (between 4.5 and 4.6) so this is the most likely cause for the regression. 
So with either version, I would instrument Z3 with this option given that you produce such ite expressions.

**Comment by leonardoalt** [comment]
That's awesome, thanks!
We indeed use `ite`s heavily, so it's good to know about this option.

**Comment by leonardoalt** [comment]
Just one more question: how exactly do I add that option via the c++ api?
I've tried `context.set("rewriter.pull_cheap_ite", true);` and also via `params` without success.

**Comment by NikolajBjorner** [comment]
that would be the correct way, except it should be on the solver object.

**Comment by leonardoalt** [comment]
The option works well when I run the `z3` binary on a standalone `smtlib2` formula, but it hasn't been the same with the C++ API.
I added the line `m_solver.set("rewriter.pull_cheap_ite", true);`, but it still hangs.
I did some debugging related to this option, and I've seen that if `smt/asserted_formulas.cpp:125` is changed from `p.set_bool("pull_cheap_ite", false);` to `p.set_bool("pull_cheap_ite", true);` it works and the formula is solved very quickly.
So I'm not sure if the option isn't propagating, or if this change that I mentioned makes any sense at all, just looking for ideas.

**Comment by NikolajBjorner** [comment]
I am not sure why the option is set to false in the code. It definitely overwrites external options.
You must be running things incrementally, because I can get it to work very well on the following python script:

`from z3 import *

str = """
(declare-fun x_4 (Int) Int)
(declare-fun y_6 (Int) Int)
(declare-fun _9 (Int) Int)
(declare-fun expr_12 () Int)
(declare-fun expr_13 () Int)
(declare-fun expr_14 () Bool)
(declare-fun expr_17 () Int)
(declare-fun expr_18 () Int)
(assert (>= (x_4 0)
    (- 57896044618658097711785492504343953926634992332820282019728792003956564819968)))
(assert (<= (x_4 0)
    57896044618658097711785492504343953926634992332820282019728792003956564819967))
(assert (>= (y_6 0)
    (- 57896044618658097711785492504343953926634992332820282019728792003956564819968)))
(assert (<= (y_6 0)
    57896044618658097711785492504343953926634992332820282019728792003956564819967))
(assert (= (_9 0) 0))
(assert (= expr_12 (y_6 0)))
(assert (= expr_13 0))
(assert (= expr_14 (not (= expr_12 expr_13))))
(assert (or (not true) expr_14))
(assert (= expr_17 (x_4 0)))
(assert (= expr_18 (y_6 0)))
(assert (not (= expr_18 0)))
(assert (let ((a!1 (ite (>= expr_18 0)
                (div expr_17 expr_18)
                (- 0 (div expr_17 (- 0 expr_18)))))
      (a!2 (ite (>= expr_18 0)
                (- 0 (div (- 0 expr_17) expr_18))
                (div (- 0 expr_17) (- 0 expr_18)))))
  (and true
       (> (ite (>= expr_17 0) a!1 a!2)
          57896044618658097711785492504343953926634992332820282019728792003956564819967))))
(check-sat)"""

s = Solver()
s.from_string(str)
s.set("rewriter.pull_cheap_ite", True)
set_option(verbose=10)
print(s.check())`

**Comment by leonardoalt** [comment]
If I load the `.smt2` file via the C++ API it also works for me. The case where it doesn't is when my program adds the constraints in the solver.
Yes! I am running it incrementally. What changes?

**Comment by leonardoalt** [comment]
Indeed, if I add a `(push)` before the first assertion in the `.smt2` file the binary run also hangs.

**Comment by NikolajBjorner** [comment]
right, pull_cheap_ite is disabled in incremental mode from the line you pointed out. The non-incremental mode uses a simplifier pass. I am looking at what should be done. The simplest change is to just delete the offending line that disables pull_cheap_ite, but there is another methods that could be used so I am investigating this one

**Comment by leonardoalt** [comment]
Ok, thank you!

**Comment by NikolajBjorner** [comment]
Could you try if this takes care of the issue? You still have to set the pull-cheap option as it is not enabled by default.

**Comment by leonardoalt** [comment]
It does solve the issue of the `.smt2` file with incremental mode. However I seem to still have a problem enabling the option in c++.
It only works if I enable the option by default in `ast/rewriter/rewriter_params.hpp`.
I'm using `m_solver.set("rewriter.pull_cheap_ite", true);`.

**Comment by NikolajBjorner** [comment]
Until I fix this, then use z3::set_param, which sets the parameter globally. The parameter on the solver isn't picked up.

**Comment by leonardoalt** [comment]
Yes, that works.
Thank you so much for the quick help!

**Comment by NikolajBjorner** [comment]
can we close this then?

**Comment by leonardoalt** [comment]
Closing. Thanks again.

**Comment by NikolajBjorner** [comment]
BTW, I saw the referenced issue is open with a comment of not being able to use 4.6.
Can you use the current snapshot or do you need a tagged release? 
Bugs are fixed on a continuous basis.

**Comment by leonardoalt** [comment]
We can use the current snapshot, it's not a problem.

**Comment by leonardoalt** [comment]
Hi @NikolajBjorner 
If I can take that back: would it be possible to have a tagged release? It would be good to have it working with the latest tagged release.
