### ISSUE TITLE
Is it possible to anticipate (estimate) time needed to solve a string query?

### ISSUE THREAD

**Issue by OrenGitHub** [Z3Prover/z3#1516]
Hi,
This is more of a **theoretical question** rather than an explicit issue:
Is it possible to somehow **estimate the time needed to solve a string query**?
We ran into the following query that did not finish in an hour:

    (declare-const dst    String)
    (declare-const src    String)
    
    (assert (= (str.len dst) 1025))
    (assert (= (str.len src) 1050))
    
    (assert (< (str.len dst) (str.indexof src "\x00" 0)))
    
    (check-sat)
    (get-value (dst src))

so we decided to **profile it** by replacing 1025:1050 with smaller numbers (125:150, 225:250, ...)
It seems that solving times are really hard to anticipate, is that true?

    str.len dst | str.len src | query time (sec)
    ------------+-------------+-----------------
        125     |     150     |           5
        225     |     250     |          19
        325     |     350     |          50
        425     |     450     |         130
        525     |     550     |         160
        625     |     650     |         972
        725     |     750     |        1225
        825     |     850     |           -
        925     |     950     |           -
       1025     |    1050     |           -

**Comment by NikolajBjorner** [comment]
There are several obstacles, theoretical and practical:
Practical:
- str.indexof implementation isn't following a branching strategy that depends on string lengths.
  You have a different bug open that exposes a flaw in the implementation. The right way seems to
  follow a string-length directed branching scheme.
Theoretical:
- maybe for some queries where branching can be predicted based on a recursive decomposition of
  the definitions, yes.
- generally, with combinatorial problems, tough luck.

**Comment by OrenGitHub** [comment]
Thanks @NikolajBjorner , we have also experimented with the following idea of **limiting the search space by restricting the string contents to be either x00 or x01** (hoping it will accelerate running times). However, the following script proves that this is definitely **not** the way to go:

    (declare-const dst            String)
    (declare-const src            String)
    ;(declare-const zero           Regex)
    ;(declare-const one            Regex)
    ;(declare-const zero_or_one    Regex)
    ;(declare-const binary_strings Regex)
    
    (assert (= (str.len dst) 25))
    (assert (= (str.len src) 50))
    
    ;(assert (= zero           (str.to.re "\x00" )))
    ;(assert (= one            (str.to.re "\x01" )))
    ;(assert (= zero_or_one    (re.union zero one)))
    ;(assert (= binary_strings (re.* zero_or_one )))
    
    ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
    ; [0] This doesn't work ... probably got the Regex sort word wrong ... ;
    ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
    ;(assert (str.in.re src binary_strings))
    
    ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
    ; [1] This actually increases running times from 2 sec to 28 sec (!??) ;
    ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
    ;(assert (str.in.re src (re.* (re.union (str.to.re "\x00") (str.to.re "\x01")))))
    
    ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
    ; [2] This further increase running times from 2 sec to 57 sec ;
    ;     though it is semantically equivalent to [1] (?!?)        ;
    ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
    (assert (str.in.re src (re.* (re.range "\x00" "\x01"))))
    
    ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
    ; [3] original query takes 2 sec for the 25:50 pair ;
    ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
    (assert (< (str.len dst) (str.indexof src "\x00" 0)))
    
    (check-sat)
    (get-value (dst src))

Running time went from 2 sec up to 28 sec with union, and 57 sec with range ...
I should probably explain the context (motivation) for this query: it comes from symbolic execution in which we often use the (str.indexof _ "\x00" 0) operation to look for null termination. From our point of view, x00 is a (very) special character.

**Comment by nunoplopes** [comment]
The short answer is no, you can't anticipate how much time a query will take.
