### ISSUE TITLE
possible unsoundness related to bitvectors and integers

### ISSUE THREAD

**Issue by kanigsson** [Z3Prover/z3#1520]
[pixel.adb_21_63_division_check.smt2.txt](https://github.com/Z3Prover/z3/files/1788410/pixel.adb_21_63_division_check.smt2.txt)

Hello,

Z3 answers "unsat" on the attached file, but I don't believe the VC actually is unsat. I reproduced this behavior using latest release 4.6.0 and current master. I tried to extract a proof or model using various options, but either they didn't work, or the VC wasn't "unsat" anymore in that case.

Sorry for the large reproducer, but removing any declaration (even seemingly unnecessary ones) or light rewriting makes z3 timeout instead of answering "unsat". This is also one of the reasons that makes me believe it's an issue in z3 and not an actual contradiction in the file.

Any help is appreciated.

Johannes

**Comment by florianschanda** [comment]
Hi Christoph,

I've made a few tweaks to Johannes' file, but I can't make it any shorter. I've also added a few comments on the things I've tried. This is definitely very strange behaviour.

I've tried with Z3 eb1122c5cb434338e25b87e7d94c7c6d56be02f8.

You might complain about the extra axiomatisation of div and mod that seems to be needed to trigger this, but that is a separate issue :)

```
(set-logic ALL)
(set-info :smt-lib-version 2.5)
(set-info :category industrial)
;; (set-info :status sat) ;probably

(declare-datatypes () ((tuple0 (Tuple0))))

;; Deleting all of this produces SAT quickly
(declare-fun div1 (Int Int) Int)
(declare-fun mod1 (Int Int) Int)
;; Swapping the order of the following two asserts produces timeout. I've
;; tried a few orderings and all seem to cause this. Also deleting any
;; individual assert causes timeout.
(assert (forall ((x Int) (y Int)) (=> (not (= y 0)) (= x (+ (* y (div1 x y)) (mod1 x y))))))
(assert (forall ((x Int) (y Int)) (=> (and (<= 0 x) (< 0 y)) (and (<= 0 (div1 x y)) (<= (div1 x y) x)))))
(assert (forall ((x Int) (y Int)) (=> (not (= y 0)) (and (< (- (abs y)) (mod1 x y)) (< (mod1 x y) (abs y))))))
(assert (forall ((x Int) (y Int)) (=> (and (<= 0 x) (< 0 y)) (<= 0 (div1 x y)))))
(assert (forall ((x Int) (y Int)) (=> (and (<= x 0) (< 0 y)) (<= (div1 x y) 0))))
(assert (forall ((x Int) (y Int)) (=> (and (<= 0 x) (not (= y 0))) (<= 0 (mod1 x y)))))
(assert (forall ((x Int) (y Int)) (=> (and (<= x 0) (not (= y 0))) (<= (mod1 x y) 0))))
(assert (forall ((x Int) (y Int)) (=> (not (= y 0)) (<= (abs (* (div1 x y) y)) (abs x)))))
(assert (forall ((x Int)) (= (div1 x 1) x)))
(assert (forall ((x Int)) (= (mod1 x 1) 0)))
(assert (forall ((x Int) (y Int)) (=> (and (<= 0 x) (< x y)) (= (div1 x y) 0))))
(assert (forall ((x Int) (y Int)) (=> (and (<= 0 x) (< x y)) (= (mod1 x y) x))))
;; This pattern seems to be required to trigger the behaviour (deleting it
;; causes timeout).
(assert (forall ((x Int) (y Int) (z Int)) (! (=> (and (< 0 x) (and (<= 0 y) (<= 0 z))) (= (div1 (+ (* x y) z) x) (+ y (div1 z x)))) :pattern ((div1 (+ (* x y) z) x)))))
(assert (forall ((x Int) (y Int) (z Int)) (=> (and (< 0 x) (and (<= 0 y) (<= 0 z))) (= (mod1 (+ (* x y) z) x) (mod1 z x)))))
(define-fun dynamic_invariant1 ((temp___expr_166 (_ BitVec 64)) (temp___is_init_162 Bool) (temp___skip_constant_163 Bool) (temp___do_toplevel_164 Bool) (temp___do_typ_inv_165 Bool)) Bool true)
(define-fun in_range1 ((x Int)) Bool (and (<= (- 9223372036854775808) x) (<= x 9223372036854775807)))
(define-fun dynamic_invariant2 ((temp___expr_201 Int) (temp___is_init_197 Bool) (temp___skip_constant_198 Bool) (temp___do_toplevel_199 Bool) (temp___do_typ_inv_200 Bool)) Bool (=> (or (= temp___is_init_197 true) (<= (- 9223372036854775808) 9223372036854775807)) (in_range1 temp___expr_201)))
(declare-fun omod ((_ BitVec 64) Int) Int)
(assert (forall ((left (_ BitVec 64))) (forall ((right Int)) (=> (and (dynamic_invariant1 left true true true true) (dynamic_invariant2 right true true true true)) (dynamic_invariant2 (omod left right) true false true true)))))

(declare-fun to_address ((_ BitVec 64)) (_ BitVec 64))

;; Deleting this causes timeout
(declare-const buffer (_ BitVec 64))
(define-fun in_range2 ((x Int)) Bool (and (<= 0 x) (<= x 2147483647)))
(define-fun dynamic_invariant4 ((temp___expr_39 Int) (temp___is_init_35 Bool) (temp___skip_constant_36 Bool) (temp___do_toplevel_37 Bool) (temp___do_typ_inv_38 Bool)) Bool (=> (or (= temp___is_init_35 true) (<= 0 2147483647)) (in_range2 temp___expr_39)))
(declare-fun zero (tuple0) Int)
(declare-fun zero__function_guard (Int tuple0) Bool)
(assert (forall ((us_void_param tuple0)) (let ((result (zero us_void_param))) (=> (zero__function_guard result us_void_param) (dynamic_invariant4 result true false true true)))))
(assert (forall ((us_void_param tuple0)) (=> (zero__function_guard (zero us_void_param) us_void_param) (= (zero us_void_param) 0))))
(assert (= buffer (to_address #x0000000000000000)))

;; Deleting this causes timeout
(declare-const asp Int)

;; Ditto
(declare-const pixel__buffer__assume (_ BitVec 64))
(assert (= pixel__buffer__assume (to_address #x0000000000000000)))

;; Ditto
(assert (and (<= (- 2147483648) asp) (<= asp 2147483647)))

(check-sat)
(exit)
```

**Comment by florianschanda** [comment]
Below is a slightly re-ordered file. I have now completed manual proof that this is SAT (which I have emailed to Christoph.)

I should not that we're not using any command-line flags, and the observed behaviour is this:

$ time z3 issue_1520.smt2
unsat
(error "line 106 column 10: check annotation that says sat")

real    0m0.299s
user    0m0.288s
sys     0m0.008s

```
(set-logic ALL)
(set-info :smt-lib-version 2.5)
(set-info :category industrial)
(set-info :status sat) ;; manual proof, see comments

;;  Overall proof strategy:
;;  - reorder file into independent sections
;;  - for quantifiers, show they always hold
;;  - for variables, give a satisfying assignment

;;  These are axioms for "ComputerDivision" from why3. Functiond div1 and
;;  div2 appear here and are not used anywhere else. See directory
;;  proof_cdiv for a satisfying interpretation and a proof that it is not
;;  inconsistent.

(declare-fun div1 (Int Int) Int)
(declare-fun mod1 (Int Int) Int)
(assert (forall ((x Int) (y Int)) (=> (not (= y 0)) (= x (+ (* y (div1 x y)) (mod1 x y))))))
(assert (forall ((x Int) (y Int)) (=> (and (<= 0 x) (< 0 y)) (and (<= 0 (div1 x y)) (<= (div1 x y) x)))))
(assert (forall ((x Int) (y Int)) (=> (not (= y 0)) (and (< (- (abs y)) (mod1 x y)) (< (mod1 x y) (abs y))))))
(assert (forall ((x Int) (y Int)) (=> (and (<= 0 x) (< 0 y)) (<= 0 (div1 x y)))))
(assert (forall ((x Int) (y Int)) (=> (and (<= x 0) (< 0 y)) (<= (div1 x y) 0))))
(assert (forall ((x Int) (y Int)) (=> (and (<= 0 x) (not (= y 0))) (<= 0 (mod1 x y)))))
(assert (forall ((x Int) (y Int)) (=> (and (<= x 0) (not (= y 0))) (<= (mod1 x y) 0))))
(assert (forall ((x Int) (y Int)) (=> (not (= y 0)) (<= (abs (* (div1 x y) y)) (abs x)))))
(assert (forall ((x Int)) (= (div1 x 1) x)))
(assert (forall ((x Int)) (= (mod1 x 1) 0)))
(assert (forall ((x Int) (y Int)) (=> (and (<= 0 x) (< x y)) (= (div1 x y) 0))))
(assert (forall ((x Int) (y Int)) (=> (and (<= 0 x) (< x y)) (= (mod1 x y) x))))
(assert (forall ((x Int) (y Int) (z Int)) (! (=> (and (< 0 x) (and (<= 0 y) (<= 0 z))) (= (div1 (+ (* x y) z) x) (+ y (div1 z x)))) :pattern ((div1 (+ (* x y) z) x)))))
(assert (forall ((x Int) (y Int) (z Int)) (=> (and (< 0 x) (and (<= 0 y) (<= 0 z))) (= (mod1 (+ (* x y) z) x) (mod1 z x)))))

;;  What follows are 4 entirely independent blobs, each which share no
;;  variables or functions between them.

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;  Section 1: These are entirely self-contained

(declare-fun to_address ((_ BitVec 64)) (_ BitVec 64))
(declare-const buffer (_ BitVec 64))
(assert (= buffer (to_address #x0000000000000000)))

(declare-const pixel__buffer__assume (_ BitVec 64))
(assert (= pixel__buffer__assume (to_address #x0000000000000000)))

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;  Section 2: These are entirely self-contained

(declare-const asp Int)
(assert (and (<= (- 2147483648) asp) (<= asp 2147483647)))

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;  Section 3: These are entirely self-contained

(declare-datatypes () ((tuple0 (Tuple0))))

(define-fun in_range2 ((x Int)) Bool
  (and (<= 0 x) (<= x 2147483647)))

(define-fun dynamic_invariant4 ((temp___expr_39 Int)
                                (temp___is_init_35 Bool)
                                (temp___skip_constant_36 Bool)
                                (temp___do_toplevel_37 Bool)
                                (temp___do_typ_inv_38 Bool))
  Bool
  (=> (or (= temp___is_init_35 true) (<= 0 2147483647)) (in_range2 temp___expr_39)))
(declare-fun zero (tuple0) Int)
(declare-fun zero__function_guard (Int tuple0) Bool)
(assert (forall ((us_void_param tuple0))
                (let ((result (zero us_void_param)))
                  (=> (zero__function_guard result us_void_param)
                      (dynamic_invariant4 result true false true true)))))
(assert (forall ((us_void_param tuple0))
                (=> (zero__function_guard (zero us_void_param) us_void_param)
                    (= (zero us_void_param) 0))))

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;  Section 4: These are entirely self-contained

(define-fun in_range1 ((x Int)) Bool
  (and (<= (- 9223372036854775808) x) (<= x 9223372036854775807)))

(define-fun dynamic_invariant1 ((temp___expr_166 (_ BitVec 64))
                                (temp___is_init_162 Bool)
                                (temp___skip_constant_163 Bool)
                                (temp___do_toplevel_164 Bool)
                                (temp___do_typ_inv_165 Bool))
  Bool
  true)

(define-fun dynamic_invariant2 ((temp___expr_201 Int)
                                (temp___is_init_197 Bool)
                                (temp___skip_constant_198 Bool)
                                (temp___do_toplevel_199 Bool)
                                (temp___do_typ_inv_200 Bool))
  Bool
  (=> (or (= temp___is_init_197 true) (<= (- 9223372036854775808) 9223372036854775807))
      (in_range1 temp___expr_201)))

(declare-fun omod ((_ BitVec 64) Int) Int)
(assert (forall ((left (_ BitVec 64)))
                (forall ((right Int))
                        (=> (and (dynamic_invariant1 left true true true true) (dynamic_invariant2 right true true true true))
                            (dynamic_invariant2 (omod left right) true false true true)))))

(check-sat)
(exit)
```

**Comment by yannickmoy** [comment]
We have a smaller VC that shows the same unsoundness, which occurs unfortunately in a much simpler setting in SPARK, meaning that this issue is more critical for us. Z3 answers unsat on the VC below, while it should not.

;; produced by z3_gnatprove.drv ;;
(set-info :smt-lib-version 2.5)
(set-info :source |VC generated by SPARK 2014|)
(set-info :category industrial)
(set-info :status unknown)
;;; generated by SMT-LIB2 driver
;;; SMT-LIB2 driver: bit-vectors, common part
;;; SMT-LIB2: integer arithmetic
(declare-datatypes () ((tuple0 (Tuple0))))
(declare-sort us_private 0)


(declare-fun div1 (Int Int) Int)

(declare-fun mod1 (Int Int) Int)

;; Div_mod
  (assert
  (forall ((x Int) (y Int))
  (=> (not (= y 0)) (= x (+ (* y (div1 x y)) (mod1 x y))))))

;; Div_bound
  (assert
  (forall ((x Int) (y Int))
  (=> (and (<= 0 x) (< 0 y)) (and (<= 0 (div1 x y)) (<= (div1 x y) x)))))

;; Mod_bound
  (assert
  (forall ((x Int) (y Int))
  (=> (not (= y 0)) (and (< (- (abs y)) (mod1 x y)) (< (mod1 x y) (abs y))))))

;; Div_sign_pos
  (assert
  (forall ((x Int) (y Int)) (=> (and (<= 0 x) (< 0 y)) (<= 0 (div1 x y)))))

;; Div_sign_neg
  (assert
  (forall ((x Int) (y Int)) (=> (and (<= x 0) (< 0 y)) (<= (div1 x y) 0))))

;; Mod_sign_pos
  (assert
  (forall ((x Int) (y Int))
  (=> (and (<= 0 x) (not (= y 0))) (<= 0 (mod1 x y)))))

;; Mod_sign_neg
  (assert
  (forall ((x Int) (y Int))
  (=> (and (<= x 0) (not (= y 0))) (<= (mod1 x y) 0))))

;; Rounds_toward_zero
  (assert
  (forall ((x Int) (y Int))
  (=> (not (= y 0)) (<= (abs (* (div1 x y) y)) (abs x)))))

;; Div_1
  (assert (forall ((x Int)) (= (div1 x 1) x)))

;; Mod_1
  (assert (forall ((x Int)) (= (mod1 x 1) 0)))

;; Div_inf
  (assert
  (forall ((x Int) (y Int)) (=> (and (<= 0 x) (< x y)) (= (div1 x y) 0))))

;; Mod_inf
  (assert
  (forall ((x Int) (y Int)) (=> (and (<= 0 x) (< x y)) (= (mod1 x y) x))))



;; Mod_mult
  (assert
  (forall ((x Int) (y Int) (z Int))
  (! (=> (and (< 0 x) (and (<= 0 y) (<= 0 z)))
     (= (mod1 (+ (* x y) z) x) (mod1 z x))) :pattern ((mod1 (+ (* x y) z) x)) )))
(declare-sort integer 0)

(declare-fun integerqtint (integer) Int)

;; integer'axiom
  (assert
  (forall ((i integer))
  (and (<= (- 2147483648) (integerqtint i)) (<= (integerqtint i) 2147483647))))

(define-fun in_range ((x Int)) Bool (and (<= (- 2147483648) x)
                                    (<= x 2147483647)))


(declare-const j Int)

(declare-const k Int)

;; H
  (assert (=> (<= (- 2147483648) 2147483647) (in_range j)))


(assert
;; WP_parameter_def
 ;; File "e.ads", line 4, characters 0-0
  (not (not (= k 0))))
(check-sat)

**Comment by kanigsson** [comment]
Hello, we found that the current master branch of z3 doesn't have this problem any more, so I am closing this issue.

**Comment by NikolajBjorner** [comment]
I have been looking at it since yesterday and wasn't able to reproduce it on the master branch either, and the other examples time out too.
The 4.6.0 bits also seem to not be able to reproduce it (trying just a few random seeds).
The more systematic test is to try several variants of smt.random_seed=<NN> to take into account differences in pre-processing orders. The even more systematic approach is to perform a wider bisection search for where the changed behavior differs. I don't have a proper setup or cycles for this today/this week and there is a good chance that the findings will be that indeed some bug that got fixed between the version from March and now took care of it. It is still rather useful to know the root cause given that the latest example seems pretty straight-forward and satisfiable. 
Note that Z3 had very major churn during May - early July. 
This should now be going back for some time to the more mundane update cycles for general stability.

**Comment by NikolajBjorner** [comment]
with smt.random_seed=9, the latest example produces unsat

**Comment by dailler** [comment]
Hello,

> I have been looking at it since yesterday and wasn't able to reproduce it on the master branch either, and the other examples time out too.

If this can help, on my machine with a recent version of Z3, the last example given by Yannick answers "unsat" with random_seed 28.
Z3 version 4.8.0 - 64 bit - build hashcode 01b5db63e6b8

`z3 -t:3000 smt.random_seed=28 example.smt2`

**Comment by NikolajBjorner** [comment]
The following is a smaller example exhibiting the bug:

<code>

;; produced by z3_gnatprove.drv ;;
(set-info :smt-lib-version 2.5)
(set-info :source |VC generated by SPARK 2014|)
(set-info :category industrial)
(set-info :status unknown)
;;; generated by SMT-LIB2 driver
;;; SMT-LIB2 driver: bit-vectors, common part
;;; SMT-LIB2: integer arithmetic
(declare-datatypes () ((tuple0 (Tuple0))))
(declare-sort us_private 0)
(declare-fun div1 (Int Int) Int)
(declare-fun mod1 (Int Int) Int)

;; Div_mod
(assert (forall ((x Int) (y Int)) (=> (not (= y 0)) (= x (+ (* y (div1 x y)) (mod1 x y))))))

;; Mod_bound
(assert (forall ((x Int) (y Int)) (=> (not (= y 0)) (and (< (- (abs y)) (mod1 x y)) (< (mod1 x y) (abs y))))))

;; Div_sign_pos
(assert (forall ((x Int) (y Int)) (=> (and (<= 0 x) (< 0 y)) (<= 0 (div1 x y)))))

;; Div_sign_neg
(assert (forall ((x Int) (y Int)) (=> (and (<= x 0) (< 0 y)) (<= (div1 x y) 0))))

;; Rounds_toward_zero
(assert (forall ((x Int) (y Int)) (=> (not (= y 0)) (<= (abs (* (div1 x y) y)) (abs x)))))

;; Div_1
(assert (forall ((x Int)) (= (div1 x 1) x)))

;; Mod_1
(assert (forall ((x Int)) (= (mod1 x 1) 0)))

;; Mod_inf
(assert (forall ((x Int) (y Int)) (=> (and (<= 0 x) (< x y)) (= (mod1 x y) x))))

;; Mod_mult
 (assert
 (forall ((x Int) (y Int) (z Int))
 (! (=> (and (< 0 x) (and (<= 0 y) (<= 0 z)))
 (= (mod1 (+ (* x y) z) x) (mod1 z x))) :pattern ((mod1 (+ (* x y) z) x)) )))


(check-sat)

</code>

**Comment by NikolajBjorner** [comment]
The latest update https://github.com/Z3Prover/z3/commit/6bacf09447c7cb0b65848cca2c85677ce53c6012 
fixes a bug that was triggered by the above example.

**Comment by kanigsson** [comment]
Nikolaj,

sorry for the late answer. Does that mean you consider the issue fixed?

**Comment by NikolajBjorner** [comment]
I can confirm that the cases that produced unsat on these benchmarks were caused by a bug that is now fixed. So yes, I would consider it fixed. If you get a chance to check it would be useful.

**Comment by kanigsson** [comment]
Sorry for the late reply - August was strange.

Yes, from our side also, everything appears to be fixed now.
