### ISSUE TITLE
Use stdbool.h in the C API?

### ISSUE THREAD

**Issue by waywardmonkeys** [Z3Prover/z3#1526]
It would make things a bit better if the C API could use `stdbool.h`. This should be available in pretty much any modern compiler. Visual Studio has had it since VS 2013.

This would let us replace `Z3_bool`, `Z3_TRUE` and `Z3_FALSE` with standard equivalents.

In my case, this would improve the quality of the Rust language bindings that I am developing / maintaining.

If this idea is welcome, I am happy to create a pull request.

**Comment by NikolajBjorner** [comment]
Our build machines are still based on VS2012. The plan was to switch to VS2013 end of last year. @Wintersteiger, what would it take to move on from VS2012 for the build system?

**Comment by waywardmonkeys** [comment]
@NikolajBjorner I don't have access to the build logs for that failure ... so, did it work? Can I do a patch that now actually uses it? :)

**Comment by NikolajBjorner** [comment]
Not yet, quite yet unfortunately.
The VS 2012 build is broken https://cz3.visualstudio.com/Z3/_build/index?definitionId=4
Do you say you don't have access to these logs?
We were planning to upgrade these build machines to at least VS2013. 
I don't see a reason to be stuck in the way past and various improvements, such as stdbool.h 
will be welcome. Unforunately, updating the build machines takes a few hoops. I hope we can take care of this without too much delay.

**Comment by waywardmonkeys** [comment]
I understand and will keep my eye out for signs that I can submit a PR :)

**Comment by NikolajBjorner** [comment]
It is now in.

**Comment by waywardmonkeys** [comment]
Thanks so much for seeing this through. :)
