### ISSUE TITLE
Segmentation fault in Z3

### ISSUE THREAD

**Issue by wdanilo** [Z3Prover/z3#153]
I'm using Haskell to create some Z3 formulas. When I try to run the following code I get segmentation fault (although other examples made by me work great). Does anybody know if that is a bug in Z3? The API used in Haskell is a mirror of the C API names:

```Haskell
import Z3.Monad
import Control.Monad.IO.Class
import Control.Applicative
import Data.Traversable
import Prelude hiding (sequence)

main = do
    out <- evalZ3 $ do
        is  <- mkIntSort
        _3  <- mkInteger 3
        _5  <- mkInteger 5
        _10 <- mkInteger 10
        x   <- mkFreshIntVar "x"
        y   <- mkFreshIntVar "y"
        y2  <- mkBvmul y y

        assert =<< mkAnd =<< mkEq x y2
   
    print "end"
```

Result : segmentation fault. 

It is caused by the line makes x y2.

**Comment by NikolajBjorner** [comment]
Multiplying two bit-vector expressions is a type error. Z3 should return "null" from Z3_mk_bvmul which is called from mkBvmul. Then Z3 sets an error flag, which the caller has to check. The C++, .NET, Java and OCaml wrappers check the error condition. Based on a repro attempt in C++ of your example, it appears that Z3 does indeed set the error flag and it is somehow not checked. Though, this seems odd given the withContextError and related wrappers that Z3.Monad seems to employ consistently.

    void crash() {
        context c;
        expr x(c), y(c), f(c);
        x = c.constant("x", c.int_sort());
        y = c.constant("y", c.int_sort());
        Z3_ast f1 = Z3_mk_bvmul(x.ctx(), x, y);
        c.check_error();              // ---- Z3 throws an exception here.
        f = expr(c, f1);
        std::cout << f << "\n";
        solver s(c);
        s.add(f);
        std::cout << s << "\n";
      }

**Comment by wdanilo** [comment]
Ah, I see. Thank you @NikolajBjorner for explanation. I'll look into the Haskell code to see whats happening inside.

**Comment by NikolajBjorner** [comment]
closing per no repro based on unstable and direct API usage.
