### ISSUE TITLE
PROOF_MODE

### ISSUE THREAD

**Issue by waywardmonkeys** [Z3Prover/z3#1531]
The docs refer to `PROOF_MODE` having values of `1` or `2`.

However, this is the old name for the parameter and it is now `proof` and only boolean, as far as I can tell.

Should the docs be updated to reflect that the parameter is `PROOF` and the value is `true` and not `1`?

What about the case(s) where `PROOF_MODE` was `2`?

**Comment by NikolajBjorner** [comment]
PROOF_MODE is deprecated. There used to be two flavors of proof tracing, a fine grained and a coarse grained mode. The coarse grained mode would summarize certain operations. The "fine" grained would attempt to track proof steps in greater detail. The coarse grained mode has been deprecated, so everything is "fine" grained, which for Z3 means a best-effort attempt. 

I have removed references to PROOF_MODE and updated the documentation.
