### ISSUE TITLE
Does Z3 have any specific rules for selecting a valid model?

### ISSUE THREAD

**Issue by SMTStuck** [Z3Prover/z3#1535]
I have this simple snippet of SMT script:

```
    (declare-const MyBool Bool)
    (declare-const MyInt Int)
    (assert (= MyBool (ite (< MyInt 10) true false )))
    (check-sat)
    (get-model)
```

This evaluates to `MyInt = 0` and `MyBool = true`. Is there a reason Z3 makes this choice, after all `MyInt = 10` and `MyBool = false` is just as valid, as are an infinite other models.

Must I assume that any values of a valid model may be random or are there some set rules that can be relied upon for the generation of the model? For example, Int will always try to take the lowest positive value etc...

I ask as I have a piece of SMT code that is currently testing the equality of an Int against 0, for an ITE result, which appears to always be satisfiable but I don't know if I may rely on this in the long term.

Thanks!

**Comment by NikolajBjorner** [comment]
The values assigned in a model are implementation specific. You can't make any assumptions. You can in some cases use optimization to get values with specific features. 

Your assertion can be simplified to (assert (= MyBool (< MyInt 10)))
