### ISSUE TITLE
str.to.int is this a bug?

### ISSUE THREAD

**Issue by OrenGitHub** [Z3Prover/z3#1538]
Hi,
We're trying to use a simple regular expression constraint together with a simple str.to.int:

    (declare-const src String)
    
    (define-fun digit           () (RegEx String) (re.range "5"  "9"))
    (define-fun decimal_strings () (RegEx String) (re.* digit       ))
    
    (assert (= (str.len src) 4))
    
    ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
    ; [0] src in {5,6,7,8,9}*                        ;
    ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
    (assert (str.in.re src decimal_strings))
    
    ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
    ; [1] src == "5778" ... without this "hint" z3 says query is unsat ;
    ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
    ;(assert (= src "5778"))
    
    ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
    ; [2] str.to.int ( src ) == 5778                     ;
    ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
    (assert (= 5778 (str.to.int src)))
    
    (check-sat)
    (get-value (src))

And this is the result we're getting:

    unsat
    (error "line 24 column 16: model is not available")

But when we **remove the comment in [1]**, everything works as expected:

    sat
    ((src "5778"))

What's going on here? Thanks!

**Comment by OrenGitHub** [comment]
@NikolajBjorner thanks, when I pulled and ran some tests I get that this indeed works, but [issue 1500](https://github.com/Z3Prover/z3/issues/1500) now returns a wrong answer:

    (declare-const s String)
    (declare-const i    Int)
    
    (assert (< i -2))
    
    (assert (= s (int.to.str i)))
    (assert (< 0 (str.len s   )))
    
    (check-sat)
    (get-value (s i))

Now returns:

    unsat
    (error "line 10 column 16: model is not available")

**Comment by NikolajBjorner** [comment]
I added a comment to issue #1500 to explain what is going on.
