### ISSUE TITLE
Make include guards unique

### ISSUE THREAD

**Issue by elfring** [Z3Prover/z3#154]
I find that include guards like "[`AST_H_`](https://github.com/Z3Prover/z3/blob/4bc044c98233ef90b1e2bd0863c654ed1cd71a1f/src/ast/ast.h#L19)" and "[`FORMAT_H_`](https://github.com/Z3Prover/z3/blob/4bc044c98233ef90b1e2bd0863c654ed1cd71a1f/src/ast/format.h#L19)" are too short for the safe reuse of your header files (when they belong to an application programming interface).

**Comment by NikolajBjorner** [comment]
these are internal header files and not visible over the Z3 API, which comprises of files z3_api.h, z3.h, z3_macros.h,...
