### ISSUE TITLE
Z3 python bindings - assert_and_track shows as an implies in sexpr()

### ISSUE THREAD

**Issue by lupodellemontagne** [Z3Prover/z3#1543]
Dear all,
when using the last version of the python bindings. If I set a constraint with assert_and_track the print with solver.sexpr() shows a corresponding implies statement. This is a bit inconsistent with the behaviour that is seen when assumptions are used to check is the model is satisfiable. 

```
import z3

x = z3.BitVec('x', 32)
a = z3.BitVec('a', 32)
solver = z3.Solver()
solver.set(unsat_core=True)
d = z3.Bool('d')
solver.assert_and_track(x != a, d) #comment this line
#solver.add(z3.Implies(x + a,d))   #decomment this line
solver.add(x == a)
print solver.sexpr()  #the pretty print shows the same set of assertions in both cases
print solver.check(d)                 
print solver.check(z3.Not(d))  
```
Probably the pretty print should specify that assert_and_track is not actually creating an implies among the assertions. 

Best Regards,
Giuseppe

**Comment by NikolajBjorner** [comment]
When you use assert_and_track, the tracking literal is automatically added as an assumption when you call solver.check.
So you also get the core from the following code:

<code>
    solver.assert_and_track(x != a, d)
    solver.add(x == a)
    print (solver.sexpr())
    print (solver.check())
   print (solver.unsat_core())
</code>

It doesn't matter if you add 'd' or Not(d) as additional assumptions.

Note also that "x + a" is not a Boolean, so you can't create the formula z3.Implies(x + a, d).
