### ISSUE TITLE
Wrong model given for formula on datatypes

### ISSUE THREAD

**Issue by jad-hamza** [Z3Prover/z3#1547]
```smt
(declare-datatypes () ((X A B)))

(declare-const x X)

(assert (not (is-A x))) 
(assert (not (is-B x)))

(check-sat)
(get-model)
```

This should be unsat but succeeds with:
```
sat
(model 
  (define-fun x () X
    B)
)
```

**Comment by NikolajBjorner** [comment]
We are moving to SMT-LIB2.6 versions of recognizers.
For now, try the following:

     (declare-datatypes () ((X A B)))
     (declare-const x X)
     (assert (not ((_ is A) x))) 
     (assert (not ((_ is B) x)))
    (check-sat)

**Comment by jad-hamza** [comment]
Thanks!
