### ISSUE TITLE
Is (not (str.contains s "#")) expected to be faster than (= -1 (str.indexof s "#" 0))

### ISSUE THREAD

**Issue by OrenGitHub** [Z3Prover/z3#1548]
Hi,
This is **not a bug** but rather a **simple question** about the difference
between an "**str.contains**" query and an "**str.indexof == -1**" query.
When using the following query I get **different running times**
(6 vs. 12 seconds in favor of contains) and **two different models** for s:

    (declare-const s String)
    (declare-const i    Int)
    (declare-const j    Int)
    (declare-const k    Int)
    
    (assert (= 90  (str.len     s      )))
    (assert (= i   (str.indexof s "@" 0)))
    (assert (= j   (str.indexof s "#" 0)))
    (assert (= k   (str.indexof s "$" 0)))
    
    (assert (= (str.substr s 0  4) "TT8G"))
    (assert (= (str.substr s 30 4) "TT8G"))
    
    (assert (= -1 (str.indexof s "\x00" 0)))
    ;(assert (not (str.contains s "\x00")))
    
    (assert (< 0 i))
    (assert (< i j))
    (assert (< j k))
    
    (check-sat)
    (get-value (s i j k))

Result for str.contains:

    sat
    ((s "TT8G\x02 \x09 �\x04\x02\x10\x04\x01�\x02@#\x02\x02@ \x04\x02@\x01\x04 \x11$TT8G  �\x10@\x08\x04\x04@\x02\x10 \x01\x08\x02�\x10\x01\x02\x01�\x10\x01\x01@�\x02\x02\x10 \x10\x10\x04 \x04 \x10\x02\x08�\x04� \x04\x02\x08 \x02\x02\x04@\x01\x04\x02\x02@")
     (i 16)
     (j 17)
     (k 29))

Result for str.indexof == -1:

    sat
    ((s "TT8G\x02\x08�\x01 \x04@\x01  \x10\x08@\x01\x10@\x01\x01@ \x01\x08\x04�\x10@TT8G #\x10\x02\x01\x01\x10�@@\x01���\x04�@\x01�\x04@ \x10�\x10`$\x08\x04\x04\x01\x08 \x08\x04�\x02 \x01 \x08\x01�\x02�� \x01\x10\x08\x01�\x02\x04 \x04")
     (i 10)
     (j 35)
     (k 60))

So I guess **str.contains is not just syntactic sugar**, right?
Are there any scenarios where str.contains **will be slower** than str.indexof == -1?
Thanks!

**Comment by NikolajBjorner** [comment]
In the implementation str.indexof creates clauses that use str.contains, but not the other way around.
In particular, str.indexof has to identify the _first_ occurrence of a substring. 
Positive occurrences of str.contains are easy: they expand into an equality (str.contains x y) expands into (str.concat y1 y y2) = x. Negative occurrences are handled by incremental unfolding. 
str.indexof, on the other hand, is compiled into a set of clauses. The method used for str.indexof with the setting string_solver=seq is currently incorrect as reported in #1397.

**Comment by OrenGitHub** [comment]
@NikolajBjorner thanks, that was informational.
