### ISSUE TITLE
How to solve a system of inequalities with Z3

### ISSUE THREAD

**Issue by Hanifor** [Z3Prover/z3#1549]
I want to calculate the boundaries of all the variables in a system of inequalities.
For example:
`a + b + 3 > 10`
`a - 2b + 1 < 5`
I want to have the boundaries of a and b, rather than minimizing or maximizing other objective.
How can I do that with Z3 in python or Java?
Thank you!

**Comment by NikolajBjorner** [comment]
Not sure what the question is, but there is an option to get "box" prioritization of objectives. 
https://rise4fun.com/Z3/tutorial/optimization
