### ISSUE TITLE
add_git_dir_dependency() doesn't work in subrepositories

### ISSUE THREAD

**Issue by sei-mwd** [Z3Prover/z3#1551]
`add_git_dir_dependency()` was updated as per issue #1227 to handle git worktrees.  Unfortunately, it fails if z3 is being used as subrepository, failing with the following:

    -- Found git worktree
    CMake Error at cmake/git_utils.cmake:37 (message):
      Found git worktree dir but could not find
      "../../.git/modules/repos/z3/commondir"

I suggest that instead of checking if .git is a file and trying to follow it via cmake, you instead use `git rev-parse --git-common-dir` and `git rev-parse --git-dir` instead.   This former invocation will get you the base .git dir, and the latter will get you the directory with the HEAD file.  This should work with all .git repositories: worktrees, subrepos, and normal.

**Comment by NikolajBjorner** [comment]
can you add a pull request?

**Comment by NikolajBjorner** [comment]
Thanks, that is an approach. Let's keep the pull open for now.

**Comment by roastduck** [comment]
It seems that this issue has already been solved by #4850 and then #4959.
