### ISSUE TITLE
str.contains weird behavior

### ISSUE THREAD

**Issue by OrenGitHub** [Z3Prover/z3#1554]
Hi,
Following issues #1548 (closed) and #1397 (open),
We've started re-writing some of our string constraints with str.contains.
When we profiled it, we found simple examples where **adding an or contstraint
slows solving times by 10x to 100x** (instead of intuitively making it faster, right?)
Here is the query we're using:

    (declare-const s String)
    (declare-const i Int)
    
    (assert (< 0 i))
    
    (assert (> (str.len s) 24))
    
    (assert
    (and      (str.contains (str.substr s 0 i) "#")
         (not (str.contains (str.substr s 0 i) "\x00"))))
    
    ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
    ; Intuitively, this should "help" the solver    ;
    ; since more solutions are now feasible ...     ;
    ; However, this slows solving times by 100x ... ;
    ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
    ;(assert
    ;(or (and      (str.contains (str.substr s 0 i) "#")
    ;         (not (str.contains (str.substr s 0 i) "\x00")))
    ;    (and (str.contains s "#") (not (str.contains s "\x00")))))
    
    (check-sat)
    (get-value (s i))

And here is the profiling table for four length constraints:

    str.len(s) | without or | with or
    -----------+------------+----------
        > 16   |    2 sec   |   3 sec
        > 20   |    2 sec   |  10 sec
        > 24   |    5 sec   | 419 sec
        > 64   |   18 sec   |   --

Are we doing something wrong here? Thanks!

**Comment by NikolajBjorner** [comment]
it is much faster now
