### ISSUE TITLE
check-sat is "unknown", why or any solutions?

### ISSUE THREAD

**Issue by zjzh** [Z3Prover/z3#1558]
when i use quantifiers such as "forall",it's "unknown",actually it's sat.
example:    return =this.lastindexof(o)
(declare-const this String)
(declare-const return Int)
(declare-const o String)
(assert (= o "a"))
(assert (= this "baac"))
(assert (and (>= return 0) (< return (str.len this))))
(assert (=  o (str.at this return )))
  (assert(forall ((i Int))
  (=> (and (> i return) (< i (str.len this)))  (not (= (str.at this i) o)))
                                  ))
(check-sat)

**Comment by NikolajBjorner** [comment]
Z3 isn't a decision procedure for such formulae.

**Comment by zjzh** [comment]
Thank you,however ,I'm confused  why my writing isn't a decision procedure,even though i change it into
 forall( ((i Int)) (=> (and (> i 0) (< i 4)) .....),it's still "unknown".
but i think it's have been a decision procedure.so how to use quantifier(such as forall)?

**Comment by zjzh** [comment]
@NikolajBjorner

**Comment by wintersteiger** [comment]
@NikolajBjorner's comment means that Z3 can't decide formulas containing quantifiers and strings, sorry.

**Comment by zjzh** [comment]
@wintersteiger  it's sad,Thank you.
