### ISSUE TITLE
Current version hangs on example that 4.5.0 says "unknown". Expected?

### ISSUE THREAD

**Issue by leonardoalt** [Z3Prover/z3#1561]
Hi there,

I'm checking two different formulas, F1 with only nonlinear:
```
(declare-fun c () Int)
(declare-fun a () Int)
(declare-fun b () Int)
(assert (> a 0))
(assert (= c (* a b)))
(assert (not (= b (div c a))))
(check-sat)
```
and F2 with nonlinear and UF:
```
(declare-fun c (Int) Int)
(declare-fun a (Int) Int)
(declare-fun b (Int) Int)
(assert (> (a 0) 0))
(assert (= (c 0) (* (a 0) (b 0))))
(assert (not (= (b 0) (div (c 0) (a 0)))))
(check-sat)
```
What I see right now is:
- `z3 4.5.0` says `unknown` for F1 and hangs for F2
- latest `z3 master` hangs for both

Any idea what could be going on?
I kinda thought F1 would be solvable.

**Comment by NikolajBjorner** [comment]
Yes, these are at the moment the most likely outcomes when using non-linear division and non-linear multiplication.

**Comment by leonardoalt** [comment]
Alright, thanks!
