### ISSUE TITLE
Simple use of str.contains returns unknown

### ISSUE THREAD

**Issue by juliandolby** [Z3Prover/z3#1563]
Unless I am doing something very wrong, the latest Z3 (as of 4/6/18) is returning unknown for the following smtlib program:

(declare-fun c0 () String)
(define-fun e1 () Bool (str.contains c0 "access_token"))
(define-fun e2 () Bool (not e1))
(assert e2)
(check-sat)

Is that expected?

**Comment by juliandolby** [comment]
this program works though:

(declare-fun c0 () String)
(define-fun e1 () Bool (str.contains c0 "access_token"))
(assert e1)
(check-sat)

**Comment by OrenGitHub** [comment]
@juliandolby you can take a look at #1676 and the response regarding negated string-contains.
It seems to be exactly the case here ...

**Comment by NikolajBjorner** [comment]
handling of negated contains has been improved.
