### ISSUE TITLE
set of steps to install z3, with options other than visual studio 13

### ISSUE THREAD

**Issue by shegde4** [Z3Prover/z3#1568]
I have a memory problem and need to get something done within a deadline and hence the visual studio 13 installation does not happen. Any alternatives to get z3 working in my python environment would be helpful.

Thanks !

**Comment by NikolajBjorner** [comment]
Just download pre-built binaries from github.com/z3prover/bin

**Comment by shegde4** [comment]
I am trying the above solution but the zip I download runs into 750 MB as I type and more. Seems like I am doing something wrong. Also I tried the pip install like so pip install z3-solver, doesn't seem to work. I am using Python2.7
![capture](https://user-images.githubusercontent.com/35979615/38555994-1bc189c8-3c96-11e8-87fa-2b04b2e00c4f.PNG)

**Comment by shegde4** [comment]
I am sorry on the first one, overlooked the fact that I was downloading the entire folder. My bad. But if you could shed some light on the pip install not working which seems to be a solution that worked as suggested on stackoverflow

**Comment by NikolajBjorner** [comment]
Just put your script in a directory that contains libz3, and has the Z3 directory with python files as a subdirectory

**Comment by shegde4** [comment]
Thanks a lot Nikolaj, works fine for my assignment.
