### ISSUE TITLE
Z3Py Problem With Bit-Blasing

### ISSUE THREAD

**Issue by dp880** [Z3Prover/z3#1569]
Hello, I'm using Z3Py to convert SMT expressions into SAT. However, when I run the following code:

from z3 import *
g = Goal()

x = BitVec('x', 3)
g.add(And(x >= 0, x < 2)) 

t = Then('simplify', 'bit-blast')
subgoal = t(g)
assert len(subgoal) == 1
print subgoal[0].sexpr()

I get the following output:
(goal
  (not k!2)
  (not (not (or k!2 (not k!1)))))

If you look closely you'll notice that the only satisfying assignment is when both k!1 and k!2 are 0. However, this should not be the case as there should be two satisfying assignments, x == 0 and x ==1.

**Comment by NikolajBjorner** [comment]
The other thing to note is that there are no constraints on k!0 (the least significant bit).
