### ISSUE TITLE
Memory Leak in C++ API with Incremental Mode

### ISSUE THREAD

**Issue by Betsy-Wang** [Z3Prover/z3#157]
Run the following code (z3_incremental_test.cpp) with Valgrind and got memory leak error.

    #include<iostream>
    #include<z3++.h>

    using namespace z3;

    void incremental_example2() {
       context c;
       expr x = c.int_const("x");
       solver s(c);
       s.add(x > 0);
       std::cout << s.check() << "\n";
       s.push();
       s.add(x < 0);
       std::cout << s.check() << "\n";
       s.pop();
       std::cout << s.check() << "\n";
       std::cout << s << "\n";
    }
    
    int main() {
        try {
           incremental_example2(); std::cout << "\n";
           std::cout << "done\n";
        } catch (exception & ex) {
           std::cout << "unexpected error: " << ex << "\n";
        }
        return 0;
    }

Here is the command I used to run Valgrind:

     valgrind --leak-check=yes ./z3_incremental_test

Here is the report dumped by Valgrind:

     ==60367== LEAK SUMMARY:
     ==60367==    definitely lost: 472 bytes in 1 blocks
     ==60367==    indirectly lost: 8,696 bytes in 3 blocks
     ==60367==      possibly lost: 76,576 bytes in 81 blocks
     ==60367==    still reachable: 104 bytes in 1 blocks
     ==60367==         suppressed: 0 bytes in 0 blocks
     ==60367== Reachable blocks (those to which a pointer was found) are not shown.
     ==60367== To see them, rerun with: --leak-check=full --show-reachable=yes
     ==60367== 
     ==60367== For counts of detected and suppressed errors, rerun with: -v
     ==60367== ERROR SUMMARY: 82 errors from 82 contexts (suppressed: 2 from 2)

**Comment by NikolajBjorner** [comment]
We don't garbage collect symbols. Symbols are used for names in constants/functions/sorts. 
So there will always be some overhead after existing.

**Comment by NikolajBjorner** [comment]
For future reference: Note that the following APIs let clients control how the memory allocated to global data-structures is managed:

           void Z3_API Z3_finalize_memory(void);

The above API function can be used for memory leak detection and also in contexts where the memory overhead of a library has to be controlled.

           void Z3_API Z3_reset_memory(void);

This above API first de-allocates all internal structures. It then re-allocates internal tables (this time they are empty). It can be used for situations where the use of persistent tables leads to memory pressure. 



In particular, the
