### ISSUE TITLE
Unsound results with str.to.int and int.to.str

### ISSUE THREAD

**Issue by levjj** [Z3Prover/z3#1570]
When using `str.to.int` and `int.to.str`, z3 might return "sat" with a model that does not actually satisfy the SMT input.

I tried to create a minimal example that illustrates the issue but I was not able to simplify it further:

```smt
(declare-datatypes () ((A
  A1
  (A2 (num Int)))))

(define-fun A_tostring ((x A)) String
  (ite (is-A1 x) "A1" (int.to.str (num x))))

(declare-fun A_array (Int) A)
(assert (= (A_array 0) (A2 1)))
(assert (= (A_array 1) (A2 2)))

(declare-const a1 A)
(declare-const a2 A)

(assert (is-A1 a1))
(assert (implies (is-A1 a1)
                 (and (= a2 (A2 1))
                      (= (A_array (str.to.int (A_tostring a2))) a2))))

(check-sat) ; should be unsat

(get-value ((is-A1 a1)
            (= a2 (A2 1))
            (= (A_array (str.to.int (A_tostring a2))) a2)))
```

For this SMT input, z3 incorrectly returns "sat". The returned model does not actually satisfy the right side of the implication which z3 can actually confirm when querying the assertion with `get-value`:

```
sat
(((is-A1 a1) true)
 ((= a2 (A2 1)) true)
 ((= (A_array (str.to.int (A_tostring a2))) a2) false))
```

This can be reproduced with both 4.5 and 4.6.

**Comment by NikolajBjorner** [comment]
It is fixed in the newer builds.
