### ISSUE TITLE
With PbEq constraints, sometimes z3 returns unsound model

### ISSUE THREAD

**Issue by Lopsy** [Z3Prover/z3#1571]
In Z3Py, the following code returns a model where the variable d is True and the other variables are False. This model doesn't satisfy the first constraint.

```
S = Solver()
a,b,c,d,e = Bools("a b c d e")
S.add(If(a, PbEq([(b,1),(c,1)], 3), PbEq([(b,1),(c,1)], 1)))
S.add(If(c, PbEq([(a,1),(d,1),(e,1)], 3), PbEq([(a,1),(d,1),(e,1)], 1)))
S.check()
M = S.model()
```

Z3Py agrees that the model it returned is unsound:

```
for constraint in S.assertions():
    print M.eval(constraint), # prints False True
```

I think I can replicate this [on rise4fun](https://rise4fun.com/Z3/20Li). If I understand the SMT2 language correctly, this encodes the same problem as above. The solver returns a model where c, d, and e are True, and a and b are False. This doesn't satisfy the second constraint.

**Comment by LeventErkok** [comment]
An observation: If you add:

`print S.sexpr()`

to the Python program, you can indeed see that Z3 is producing precisely the program original poster created. So, this indeed seems to be an issue with Z3 itself, instead of the Python interface.
