### ISSUE TITLE
libz3.dll not found

### ISSUE THREAD

**Issue by wuyizhang** [Z3Prover/z3#1573]
Hi, 

I downloaded the source code and successfully built it following steps in README on my Win10. But when I run example.py, it says  _libz3.dll not found_. The python scripts is in the same directory as libz3.dll, and I have added the 'build\python' directory the PYTHONPATH environment variable and the 'build' directory  to the PATH environment variable. Any idea on why I encounter this issue would be helpful. 

Thanks.

**Comment by NikolajBjorner** [comment]
Did you build 64bit Z3 and use a 32 bit python installation, or conversely build a 32 bit Z3 and use a 64 bit python installation?

**Comment by wuyizhang** [comment]
@NikolajBjorner Thanks. I found out I was using 32bit python to install 64bit z3. I reinstalled using 64bit python and everything works fine. Thank you.
