### ISSUE TITLE
c++ API, func_decl function

### ISSUE THREAD

**Issue by nnarodytska** [Z3Prover/z3#1574]
Dear All,

I would like to encode a function with a number of parameters using C++ AP. I was going to use 
`
func_decl function(char const * name, sort_vector const& domain, sort const& range);`

However, it looks like this function is not defined in z3++.h (please see lines 2660--2682).
I can use a similar function to obtain the same result, i.e. `func_decl context::function(..,sort_vector const& domain,..)`.
I was wondering if there is a reason why` func_decl function(..,sort_vector const& domain,..)` should not be used (and, perhaps, 
`func_decl context::function(..,sort_vector const& domain,..)` should not be used as well).

Thank you!

nina

**Comment by nnarodytska** [comment]
Hi Nikolaj,

Thank you for the reply! 

Yes,  **func_decl context::function** is defined with ` sort_vector` in 2491.  
But **func_decl function**  is not defined with  `sort_vector`.  I thought there might be a reason for that. 
I will use the  **func_decl context::function**.

Thanks again,

nina

**Comment by NikolajBjorner** [comment]
Perhaps I am not parsing the question correctly. Are you saying that z3++.h should include the following shorthand:

    inline func_decl function(char const& name, sort_vector const& domain, sort const& range) {
        return range.ctx().function(name, domain, range);
    }

**Comment by nnarodytska** [comment]
Hi Nikolaj,

Great, thank you for adding the shorthand!

nina
