### ISSUE TITLE
Why is this unsat?

### ISSUE THREAD

**Issue by LeventErkok** [Z3Prover/z3#1575]
I'm curious why Z3 says `unsat` for this query:

```
(declare-fun s () String)
(assert (forall ((i Int))
            (and (= (str.len s) 3)
                 (=> (and (<= 0 i) (< i 2))
                     (= (str.substr s i 1) (str.substr s (- 2 i) 1))))))
(check-sat)
```

If I understand correctly, this query would be satisfied by all length 3 strings that are palindromic. Is this not the case?

(I was actually expecting `unknown` as I didn't expect quantifiers to be well-supported with strings; but the `unsat` response is confusing to me. When I try it on CVC4, it does indeed say `unknown`, though I'm not sure if that's to be trusted either.)

**Comment by NikolajBjorner** [comment]
looks suspicious.
Also with z3str3 it reports a memory leak. @mtrberzi

**Comment by mtrberzi** [comment]
I will look into the memory leak this week, although I may not be able to do much about quantifiers.

**Comment by NikolajBjorner** [comment]
the good news is that quantifier handling is mainly external to the theory plugins.
