### ISSUE TITLE
Bug with strToNat

### ISSUE THREAD

**Issue by LeventErkok** [Z3Prover/z3#1581]
For this `unsat` benchmark:

```
(set-option :produce-models true)
(set-logic ALL)
(declare-fun s () String)
(assert (not (=> (str.in.re s (re.+ (re.range "0" "9")))
                 (>= (str.to.int s) 0))))

(check-sat)
(get-value (s))
```

Z3 agrees that the model it finds is invalid:

```
$ z3 model_validate=true bug.smt2
sat
(error "line 7 column 10: an invalid model was generated")
((s "6020015140634623"))
```

A call of the form:

```
$ z3 smt.string_solver=z3str3 model_validate=true bug.smt2
```

doesn't seem to terminate.

**Comment by OrenGitHub** [comment]
For what it's worth, here is the hex value of the integer z3 found:

    >>> hex(6020015140634623)
    '0x15632bffffffff'

The 32 LSBs look like some sign extension problem where this number is supposedly negative.
I also re-wrote the query like this:

    (declare-fun s () String)
    (assert (str.in.re s (re.+ (re.range "0" "9"))))
    (assert (< (str.to.int s) 0))
    (check-sat)
    (get-value (s))

And got:

    sat
    ((s "2001454759935"))

Whose hex value is:

    >>> hex(2001454759935)
    '0x1d1ffffffff'

Again, with 32 LSBs all equal to 1 ... hope this helps ...
