### ISSUE TITLE
Eager bit-blasting based tactic for QF_AUFBV

### ISSUE THREAD

**Issue by rainoftime** [Z3Prover/z3#1582]
From `src/tactic/smtlogics/qfbv_tactic.cpp`, I suppose Z3 takes the eager bit-blasting approach to solving a QF_BV constraint except when it is in the "QFBV_EQ" fragment (which will be fed to the DPLL(T)-style `smt_tactic`). 

However, when solving QF_AUFBV constraints (`src/tactic/smtlogics/qfaufbv_tactic.cpp`), Z3 will always call the `smt_tactic` after some preprocessing phases.  Is it possible to implement a bit-blasting based tactic for QF_AUFBV? 

My premilarly solution is to modify the "preamble" part in qfbv_tactic.cpp.  The basic idea is using  `mk_bvarray2uf_tactic` and `mk_ackermannize_bv_tactic` for eliminating array and uninterpreted function symbols. However, my implementation may get an exception in the later SAT solving part when testing some queries from KLEE. 
~~~~
#include"ackermannize_bv_tactic.h"
#include"bvarray2uf_tactic.h"
// omit 

static tactic * mk_eager_qfaufbv_preamble(ast_manager& m, params_ref const& p) {
    params_ref solve_eq_p;
    //.. omit some paramters 
    return
            and_then(
                    mk_simplify_tactic(m),
                    mk_propagate_values_tactic(m),
                    using_params(mk_solve_eqs_tactic(m), solve_eq_p),
                    mk_elim_uncnstr_tactic(m),
                    mk_bv_size_reduction_tactic(m),
                    using_params(mk_simplify_tactic(m), simp2_p),
                    //using_params(mk_simplify_tactic(m), hoist_p),
                    mk_bvarray2uf_tactic(m, p),        // reduce bv array to bv(with uninterpreted function)
                    mk_ackermannize_bv_tactic(m, p), // TODO: do ackermannization here or after max_bv_sharing?
                    mk_max_bv_sharing_tactic(m)
            );
}
~~~~

Do I misuse the two APIs  `mk_bvarray2uf_tactic(m, p)` and `mk_ackermannize_bv_tactic(m, p)`?
Is there any advice on implementing a bit-blasting based tactic for QF_AUFBV? @NikolajBjorner Thank you!

**Comment by NikolajBjorner** [comment]
1. Perhaps the tactics don't ensure the results being SAT. E.g., bvarray2uf does not convert as-array occurrences (but it is unlikely you use them). There could be other cases that slip through. An example that slips through the cracks of these tactics could help identify what is going on.
2. You could protect the sat tactic as follows: cond(mk_is_qfbv_probe(), sat, smt)

**Comment by rainoftime** [comment]
@NikolajBjorner Thank you! I will try.
I observe that on QF_BV instances, the `qfbv_tactic` is usually faster than `smt_tactic`.  Maybe the eager-to SAT approach will also work better for QF_AUFBV.
