### ISSUE TITLE
Defining a recursive function from the C API

### ISSUE THREAD

**Issue by jawline** [Z3Prover/z3#1589]
Sorry if this question has an obvious answer. What is the easiest way to declare the function 

`(define-fun-rec str-repeat ((a String) (b Int)) String (ite (<= b 0) "" (str.++ a (str-repeat a (- b 1)))))`

using the C API? I can't find any mention of declaring a recursive function via the API in the docs but I might have missed it.

Alternatively is there any way I can parse this function as SMT and use it in the C API? (It would simplify a lot of our boilerplate functions)

**Comment by NikolajBjorner** [comment]
The current approach to recursive function definitions is by compiling them to quantifiers.
Then these quantifiers are tagged in a particular way to ensure that MBQI (quantifier reasoning) uses them cautiously. In a nutshell, Z3 assumes that the recursive function definitions are consistent (do don't define f(x) = f(x+1)+1), and checks if candidate models satisfy the recursive equations at a limited set of values.

From python you can use the parser to get recursive functions:

       from z3 import *
       s = Solver()
       s.from_string("(define-fun-rec str-repeat ((a String) (b Int)) String \
              (if (<= b 0) \"\" (str.++ a (str-repeat a (- b 1)))))")
      for f in s.assertions():
           print(f.sexpr())

**Comment by jawline** [comment]
Thank you for the reply :smiley: 

Is the C API function `Z3_solver_from_string` the same as this or does it refer to a different operation?

**Comment by NikolajBjorner** [comment]
In z3.py the function Solver.from_string calls Z3_solver_from_string, yes.

**Comment by jawline** [comment]
Awesome, thanks for the help.

**Comment by jawline** [comment]
Sorry to re-open the issue. The string function works great but I'm having trouble addressing the function that has been declared.

Is there any way I can look up a declaration by name or extract the most recent declaration from the solver?

**Comment by NikolajBjorner** [comment]
There is no direct method for this. You can either create the function declaration using the same name and signature outside and it will be the same (there are no hidden attributes), or you can walk the assertions of the solver to find the appropriate functions based on their names.

**Comment by jawline** [comment]
Great, that worked for me.

Thanks
