### ISSUE TITLE
Z3 4.4.0 segfaults

### ISSUE THREAD

**Issue by UnboxedType** [Z3Prover/z3#159]
Greetings, gentlemen!

First of all thank you for your great effort in doing this stuff!
I would like to submit segfault issue which can be reproduced on Z3 4.4.0 using
this sample:

(set-logic AUFNIRA)
(define-sort _array () (Array Int Int))
(declare-fun equals (_array _array Int) Bool)
(assert (forall ((ar1 _array) (ar2 _array) (i Int) (len Int))
        (=> (and (>= i 0) (< i len)) 
            (= (select ar1 i) (select ar2 i)))))
(declare-fun make_array (Int Int) _array)  
(assert (forall ((ar _array) (i Int) (len Int) (val Int))    
            (=> (and (>= i 0) (< i len)) 
                (=> (= (select ar i) val) 
                    (= ar (make_array len val))))))
(assert (equals (make_array 3 0) (make_array 3 0)))
(check-sat)

**Comment by nunoplopes** [comment]
Doesn't crash with latest unstable branch.

**Comment by UnboxedType** [comment]
I figured out that this issue has to do with absence of 3rd argument to the equals function
in the last assert.
