### ISSUE TITLE
 Define-fun using C++ API

### ISSUE THREAD

**Issue by nnarodytska** [Z3Prover/z3#1598]
Dear All,

I have a  question regarding define-fun similar to @jawline 's but not exactly the same.

I would like to define interpreted functions that use input parameters and other variables
using C++/C API.

For example,

```
(define-fun valid_stack ((a Int) (s Int) ) Bool
(<= (+ a s ) stack )
)
```

1. From stackoverflow discussions it seems that one way to do this is to first declare UF
and then define it using forall.

For example,

```
(declare-fun valid_stack (Int Int) Bool)
(assert
 (forall ((a Int) (s Int)) (<= (+ a s ) stack ))
 )

```
Unfortunately, such rewriting hurts performance a lot on some benchmarks.

2. Another option  is  to use the "from_string" option. However, this option does not seem to work for me as I would need to represent the entire program as a string to use it.This is not very convenient for incremental calls and debugging of counterexamples.

I would very much appreciate an advice on how to define functions using z3 C++/C API without using "forall".

Thank you!

nina

**Comment by NikolajBjorner** [comment]
If your function is just a macro, then the approach over the API is to define an expression builder that returns the body of the function given expressions that represent the arguments. 
For example 
 
expr mk_valid_stack(expr& a, expr& s, expr& stack) {
    return (a + s) <= stack;
}

(I believe we have the appropriate overloads available to write it like this).

Note also that your aximatization of valid_stack is not correct.
You need 

(assert (forall ((a Int) (s Int)) (= (valid_stack a s) (<= (+ a s) stack)))))

Z3 should detect that this is a macro. and compile every occurrence of (valid_stack a s) into the definition.

**Comment by NikolajBjorner** [comment]
does this address the issue?

**Comment by nnarodytska** [comment]
Hi Nikolaj,

> Note also that your aximatization of valid_stack is not correct.

Yes, you are right about my expression with forall. I introduced an error while simplifying a function.

> If your function is just a macro, then the approach over the API is to define an expression builder that returns the body of the function given expressions that represent the arguments.

Than you for the suggestion! I implemented an expression builder. It works much better than the "forall" solution. I am testing performance now compared to loading from an smt2 file. I am closing the issue for now if it is ok.

**Comment by bja2019** [comment]
Hi Nikolaj,
I have similar requirement to define function using c++ API for Z3.  How to define expression builder  using Z3 API. Any reference / documentation would be helpful.

**Comment by NikolajBjorner** [comment]
Not sure what else to say that look at the cpp example in the examples directory.
It builds a bunch of expressions and exercises main API functionality. 
There is also a tptp interface in the examples directory. It is an example of translating from expressions extracted from a parse tree into z3.

**Comment by bja2019** [comment]
Hi Nikolaj, 
Thanks for the reference and will study example - This helps !
