### ISSUE TITLE
Seg fault in Z3 4.4.1: misformed implication proposition

### ISSUE THREAD

**Issue by UnboxedType** [Z3Prover/z3#160]
Hello again!

$ z3 --version
Z3 version 4.4.1

$ z3 -smt2 arrays_func.smt2 
Segmentation fault (core dumped)

$ cat arrays_func.smt2
(set-logic AUFNIRA)
(define-sort _array () (Array Int Int))
(declare-fun set (_array Int Int) _array)
(assert (forall ((ar _array) (i Int) (v Int))
            (=> (= (store ar i v) (set ar i v)))))
(check-sat)

Notice that implication has no 2nd argument. If I put one then no segfault happens.

**Comment by NikolajBjorner** [comment]
Thanks
