### ISSUE TITLE
Slow performance on simple query that uses equalities for assignments

### ISSUE THREAD

**Issue by 4tXJ7f** [Z3Prover/z3#1602]
The following simple query is not solved within a 5 minute timeout on my machine:

```
(set-logic QF_FP)

(declare-const a Float32)
(declare-const b Float32)
(declare-const r0 Float32)
(declare-const r1 Float32)

(assert (= r0 (fp.abs a)))
(assert (= r1 (fp.abs b)))
(assert (not (= (fp.mul RNE r0 r1) (fp.mul RNE (fp.abs a) (fp.abs b)))))
(check-sat)
```

It looks like Z3 is not using the equalities to perform substitutions in this case. Is this expected? Is there any option that can be used to get better performance? Thanks!

**Comment by rainoftime** [comment]
By default, z3 takes the qffp_tactic. It first reduces the floating point constraint to a bit-vector constraint, which is then eagerly bit-blasted (or "flattened") to an SAT constraint.  It is possible that a "simple" floating point constraint might be translated to a complex SAT formula.

There also exist other tactics in Z3 that can solve floating point constraints which might be better.  For your query, the smt_tactic is very fast.
 ~~~~
// Z3 C++ API
   context ctx;
   solver s = tactic(ctx, "smt").mk_solver(); 
 ~~~~
In general, it is hard to tell which tactic will be the best for a given query.

**Comment by ranjitjhala** [comment]
@4tXJ7f it looks like following the suggestion of @rainoftime if we change the last line of your query to

```
(check-sat-using smt)
```

then Z3 instantaneously says `unsat`...

**Comment by NikolajBjorner** [comment]
Perhaps something like:

    (check-sat-using (then solve-eqs qffp))

**Comment by 4tXJ7f** [comment]
Thank you @NikolajBjorner and @rainoftime. We are now using `(par-or (then solve-eqs simplify qffpbv) smt)`, which seems to work fairly well on our problems. `(check-sat-using smt)` helped with the simple example but did not help with a more complicated one and `(check-sat-using (then solve-eqs qffpbv))` alone was slow in some cases as well.
