### ISSUE TITLE
Z3 fails to find libz3java on windows 

### ISSUE THREAD

**Issue by zjzh** [Z3Prover/z3#1603]
when I cmake z3 bindings with JAVA,I want to run  examples/java/JavaExample.java
I add the  com.microsoft.z3-4.7.0.0.jar and  set native library path ,But it failed:
Actually I found past issues #294 refered to it ,But it seems no solutions.
![image](https://user-images.githubusercontent.com/29055749/39396402-1d277870-4b20-11e8-9c08-943533d7a40c.png)
![image](https://user-images.githubusercontent.com/29055749/39396434-a268796c-4b20-11e8-81b5-6c9a4b144f1a.png)

**Comment by NikolajBjorner** [comment]
cmake does not include dotnet/java examples.
