### ISSUE TITLE
str.substr (Substring of String) not present in Python API

### ISSUE THREAD

**Issue by dgboy2000** [Z3Prover/z3#1605]
Documentation suggests there's a function to retrieve a substring from a string:

(str.substr s offset length) | Retrieves substring of s at offset
https://rise4fun.com/z3/tutorialcontent/sequences

I've looked a few times through the installed python API and don't see a way to access such a function. Is this intentional? If not, would a PR with that addition be appreciated? Or am I missing something?

Thanks!

**Comment by dgboy2000** [comment]
Ahh, I missed that. Thanks for the quick response!

That would be helpful to future people in my situation, searching the Sequence and String portions of the 10k line python API. I approve :)

**Comment by NikolajBjorner** [comment]
It is part of bff15e12efbadeb553dcc80bf1b5f5e3bd33536
