### ISSUE TITLE
Timeout with trivial use of "is_int"

### ISSUE THREAD

**Issue by levjj** [Z3Prover/z3#1608]
When using "is_int" with a Real-valued variable, even trivial examples result in a timeout.

```smt
(declare-const x Real)
(assert (is_int x))
(assert (not (is_int (+ x 1))))
(check-sat)
```
Adding 1 to an int should result in an int, so this should result in `unsat` but instead z3 times out.
If this is expected behavior, then it seems "is_int" cannot be used reliably this way.

**Comment by NikolajBjorner** [comment]
good example. The current solver creates a perpetual number of mixed integer cuts. It will take a while to fix this properly.

**Comment by levjj** [comment]
This is not a high priority issue but it would be nice if z3 could be used to prove facts like in the example above. Maybe adding some new theorems or simplification rules for `is_int` would help.

**Comment by NikolajBjorner** [comment]
correction: it does not create any cuts, only branches. 
The current implementation of cuts is incomplete.
 I strengthened the simplifier a bit such that this example is dealt during pre-processing, pending more systematic approaches.

**Comment by levnach** [comment]
Works now.
