### ISSUE TITLE
Incorrect rational passed as integer

### ISSUE THREAD

**Issue by NikolajBjorner** [Z3Prover/z3#161]
http://stackoverflow.com/questions/31389140/error-invalid-rational-value-passed-as-an-integer

**Comment by ShalonNisha** [comment]
Have you fixed the problem? Can you explain me what is going wrong in simple terms? How can I avoid it?

**Comment by NikolajBjorner** [comment]
Yes, I have fixed the problem. 
The background is that Z3 uses a simplex engine that works over rationals. It has some support for bounds propagation for non-linear monomials on top of this. In the process some variables declared as integers have rational values. In the end, the solver is unable to determine sat/unsat. Z3 creates a candidate interpretation, nevertheless and this step did not take into account that the current rational values to integer variables was incorrect.
