### ISSUE TITLE
Expected differences when specifying smt.string_solver=z3str3?

### ISSUE THREAD

**Issue by OrenGitHub** [Z3Prover/z3#1614]
Hi,
What are the expected differences when specifying:

    smt.string_solver=z3str3

I see that the **returned models** are **usually different**. For example, with this query:

    (declare-const s1 String)
    (declare-const s2 String)
    
    (assert (= (str.len s1) 8))
    (assert (= (str.len s2) 5))
    
    (assert (= (str.at  s2  4) "\x00"))
    (assert (= -1 (str.indexof (str.substr s2 0 4) "\x00" 0)))
    
    (check-sat)
    (get-model)

This is what I get when I specify **smt.string_solver=z3str3**:

    sat
    (model 
      (define-fun s2 () String
        "aaaC\x00")
      (define-fun s1 () String
        "aaaaaaa2")
    )

And this is what I get **without it**:

    sat
    (model 
      (define-fun s2 () String
        "\x04\x10\x04\x10\x00")
      (define-fun s1 () String
        "\x00\x00\x00\x00\x00\x00\x00\x00")
    )

I wanted to ask the following questions:

**[1]** Are there any queries for which z3str3 will return a **faster** response? **slower** response?
**[2]** In the future, will these two paradigms be united?

Thanks!

**Comment by NikolajBjorner** [comment]
This is an open-ended question, so providing some answer it and closing:

- the z3str3 and seq solvers are different implementations for string (and sequence) solving. They share some functionality around rewriting and possibly share several approaches for reducing string constraints, but they use different approaches towards simplifying string constraints. So it really depends on which solver figured out the best way to solve constraints. There is latency in fixing issues with either solver, so users that hit blocking issues with one can switch.

- z3str3 produces "nicer" models for strings preferring legible characters. The seq solver makes no such attempt it just uses 8 bit bit-vectors as a basis and is happy with any solution the bit-vector solver provides.  

- there are some features supported in one solver, but not the other: Notably, the seq solver supports sequences over generic types. This is mainly historic as z3str3 grew out of solver specialized to only strings, but also has some consequences on the implementation side. See the item above. 

- the z3str3 solver is in active development, so watch out for updates.

- the seq solver is, from what I am concerned with, in minimal development mode: I try to make sure it is solid, handles useful scenarios, address bugs and blatant performance issues, but would prefer to take improvements from users/researchers who actively need these features. There are many directions to take this, and it depends on use cases to determine what are the most useful ones: regular expressions with variables (allows to encode context free languages), richer transducers, native Unicode, efficiency, decidable fragments, model completeness (exhaust the space of finite length sequences).
