### ISSUE TITLE
Failures when build Z3 with msvc + permissive- on windows

### ISSUE THREAD

**Issue by PhoebeHui** [Z3Prover/z3#1616]
Z3 failed when build with permissive- by msvc on windows, could you help have a look?

Environment: VS2017 latest version + windows server 2016 + Z3 master branch latest revision

Repro:
1. git clone https://github.com/Z3Prover/z3 D:\Z3\src
2. Open a VS 2017 x86 command prompt and browse to d:\Z3
3. set _CL_=/permissive-
4. mkdir build_x86 && pushd build_x86
5. cmake -G "Visual Studio 15 2017" -DCMAKE_SYSTEM_VERSION=10.0.16299.0 ..\src
6. msbuild build_x86\Z3.sln /p:Configuration=Release;Platform=Win32 /t:Rebuild /m /p:BuildInParallel=true

Failures like:
D:\Z3\src\src\util/string_buffer.h(85): error C3861: 'ARRAYSIZE': identifier not found
D:\Z3\src\src\util/string_buffer.h(136): note: see reference to class template instantiation 'string_buffer<INITIAL_SIZE>' being compiled
D:\Z3\src\src\util/string_buffer.h(95): error C3861: 'ARRAYSIZE': identifier not found
D:\Z3\src\src\util/string_buffer.h(105): error C3861: 'ARRAYSIZE': identifier not found

**Comment by PhoebeHui** [comment]
For #1, should be /permissive-, no breaks.
For #2, The macro ARRAYSIZE (probably a macro) is not defined when string_buffer.h is included. we're not sure which header this comes from. So no pull request planed here.

**Comment by PhoebeHui** [comment]
This issue still affect us, is there any reasons to close this issue?

**Comment by NikolajBjorner** [comment]
apart from not using " -DCMAKE_SYSTEM_VERSION=10.0.16299.0 ", my build with the current master goes through with these settings.

**Comment by NikolajBjorner** [comment]
I have now also removed references to ARRAYSIZE in the code.

**Comment by PhoebeHui** [comment]
Thank you NikolajBjorner for fix this issue!

I will verify the changes, I will let you know the results.

**Comment by PhoebeHui** [comment]
I have verified, this issue fixed, thank you NikolajBjorner!
