### ISSUE TITLE
Parse smt file and use already defined symbol of it from API

### ISSUE THREAD

**Issue by SylvainCecchetto** [Z3Prover/z3#1627]
Hi,

Let's say I have a SMT file foo.smt2 like this:
```
(set-logic QF_ABV)
(set-info :smt-lib-version 2.0)
(define-fun res () (_ BitVec 32) (_ bv1 32))
(define-fun edi () (_ BitVec 32) res)
```

I use the C++ API function `parse_file` in order to load my SMT file:
```
context c;
expr a = c.parse_file("foo.smt2");
```

I already know that `edi` is defined in the smt file, so I want to compute something like that:
```
context c;
expr a = c.parse_file("foo.smt2");
expr b = c.bv_const("toto", 32);
solver s(c);
```

But it didn't work... Maybe I miss something?

Thanks for help.

EDIT: My original goal is to build a context object  once and for all from an initial SMT file (because in my SMT file there is only declarations and no assert). Then from this context object I want to check different things. (You can see a pseudo code bellow that explain what I want to do):

```
context c; // The only context object that I want to use to work
function_that_initialize_the_context_with_all_declarations_from_my_smt_file;

// Then now a lot of computation with existing objects from my smt file
solver s(c);
s.add(toto == titi);
s.check;

solver s2(c);
s2.add(abc != def);
s2.check;

[...]
```

**Comment by NikolajBjorner** [comment]
The parse_file returns just assertions that are presented in the file. Declarations are not going to be available in any direct way to the caller. For programmatic use of Z3 over the API you build sorts, declarations and expressions bottom up. To point to a given declaration you would build it by supplying the name, sorts in the domain, and sort of the range.

**Comment by SylvainCecchetto** [comment]
Thank you for your answer.

I just found a workaround in order to use declaration symbols present in my SMT file.

Let's say I have this SMT file (`foo.smt2`) generated from an external tool:
```
(set-logic QF_ABV)
(set-info :smt-lib-version 2.0)
(declare-fun a () (_ BitVec 32))
(declare-fun c () (_ BitVec 32))
(define-fun b () (_ BitVec 32) (bvadd c (_ bv4 32)))
```

Now from my C++ code with the Z3 API I would like to ask `a != b?`. So I do:
```cpp
context c;
solver s(c);
expr foo = c.parse_file("foo.smt2");
s.add(foo);
expr a = c.bv_const("a", 32);
expr b = c.bv_const("b", 32);
s.add(a != b);
check_result r = s.check();
```

But, if I understand, it doesn't work because the `foo` expr is empty because there is no assertion in `foo.smt2`. That's right?

So my workaround is to add "fake" assertion in my SMT file like that:
```
(set-logic QF_ABV)
(set-info :smt-lib-version 2.0)
(declare-fun a () (_ BitVec 32))
(declare-fun c () (_ BitVec 32))
(define-fun b () (_ BitVec 32) (bvadd c (_ bv4 32)))

(declare-fun a_end () (_ BitVec 32))
(assert (= a a_end))

(declare-fun b_end () (_ BitVec 32))
(assert (= b b_end))
```

Now if I do:

```cpp
context c;
solver s(c);
expr foo = c.parse_file("foo.smt2");
s.add(foo);
expr a = c.bv_const("a_end", 32);
expr b = c.bv_const("b_end", 32);
s.add(a != b);
check_result r = s.check();
```

It works!

But I'm not sure if my workaround is good? Maybe there is a better solution? 

What do you think about that?

Thank you for your help!

**Comment by NikolajBjorner** [comment]
> But, if I understand, it doesn't work because the foo expr is empty because there is no assertion in foo.smt2. That's right?
The current version of the API returns an expression that is the conjunction of all assertions. So if there are no assertions, the conjunction is empty and the expression is "true".
I am going to change this API to return a _vector_ of assertions. In this case the vector is empty. So same deal. There is no real difference between the solutions you propose, other than some use extra variables.
