### ISSUE TITLE
[Question] Z3py changing contexts

### ISSUE THREAD

**Issue by JoranHonig** [Z3Prover/z3#1629]
Hi, I am using z3py and would like to do some computations in parallel.
After some research, I found that this would require the use of different Context objects, due to thread safety. 
Manually changing the context of expressions results in the following exception:
``` z3.z3types.Z3Exception: b'invalid dec_ref command' ```

So now I'm wondering if setting the ctx variable for an expression to a new context is the correct approach.

**Comment by NikolajBjorner** [comment]
Expressions and contexts belong together: you cannot mix expressions created from different contexts.
If you want to copy expressions from one context to another, do it in code that does not run in parallel with anything that touches the two contexts, then use the "translate" methods to perform the deep copy operations.

**Comment by JoranHonig** [comment]
Thanks for the answer! Translate seems like the thing I was looking for.
The following dir contains some python examples: examples/python. Would you accept a pr from me with a parallel python example? ( that might be usefull )

**Comment by NikolajBjorner** [comment]
Gladly yes
