### ISSUE TITLE
Modernization of `buffer<T>`

### ISSUE THREAD

**Issue by danielschemmel** [Z3Prover/z3#1632]
As originally discussed in #1630, the current `buffer<T>` implementation can possibly be improved upon.

I would like to submit this analysis for your consideration, so that an eventual pull request matches your expectations.

### Properties of the Current Implementation
- The current implementation restricts its capacity to 2^31, which effectively saves 8 bytes on 64 bit machines
  - The restriction 2^31 follows from how `buffer::expand` works and from `buffer::INITIAL_SIZE` always being a power of 2
  - Saving 8 bytes happens because `buffer::m_pos` and `buffer::m_capacity` should otherwise be `std::size_t`, which requires 4 bytes more on 64 bit targets. For most compilers, padding should not be introduced in either case.
- Relies on the user deciding whether destructors should be explicitly called (`buffer`'s `CallDestructors` template argument).
  - Sometimes the user may decide in a way that is inconsistent with C++ rules (the destructor may not be trivial in the C++ sense, but the use may decide to not call it anyway)
  - Sometimes the user may be wrong not just in the strict sense (cf. [`sbuffer`](https://github.com/Z3Prover/z3/blob/6938c76950f21c0e7bb958376604cb0fc4811784/src/util/buffer.h#L260-L265), [`smt::coeff_expr`](https://github.com/Z3Prover/z3/blob/6938c76950f21c0e7bb958376604cb0fc4811784/src/smt/theory_arith.h#L991), [`smt::theory_arith<Ext>::display_coeff_exprs(std::ostream&, sbuffer<coeff_expr> const&) const`](https://github.com/Z3Prover/z3/blob/6938c76950f21c0e7bb958376604cb0fc4811784/src/smt/theory_arith.h#L1129) considering [`~rational`](https://github.com/Z3Prover/z3/blob/6938c76950f21c0e7bb958376604cb0fc4811784/src/util/rational.h#L67)).
  - Maybe somewhat surprisingly, this optimization can easily be done by the compiler: If `~T()` is trivial, [the loop](https://github.com/Z3Prover/z3/blob/6938c76950f21c0e7bb958376604cb0fc4811784/src/util/buffer.h#L49-L53) becomes an empty loop over a pointer range, which can then be removed, (and so forth)
  - The same problem also exists in the opposite direction, some types which do not need to be destroyed (e.g. `bool` and `char`) exist in both specializations, which at least introduces unnecessary types
- Assumes that all types it is instantiated with are [trivially copyable](http://en.cppreference.com/w/cpp/types/is_trivially_copyable) by moving them with `memcpy` by default.
  - Often quite fast
  - Often OK in practice, as destructors are not called on the old objects => usually works in practice as long as the value of `this` is irrelevant
  - Questionable C++
- Basically ignores alignment
  - On common 32 bit and 64 bit machines, `m_initial_buffer` is still pointer aligned, which mostly works (practically speaking, SSE may not be used on buffers)
  - Can be easily fixed with pretty much zero overhead (`alignas(alignof(T))`)
- Semantically closely related to [`vector`](https://github.com/Z3Prover/z3/blob/6938c76950f21c0e7bb958376604cb0fc4811784/src/util/vector.h#L41-L42), which is basically a `buffer` with `INITIAL_SIZE=0`.

### Target Properties
- Be correct
- Performance (memory and speed) should (at least) not degrade significantly unless required for correctness
- The implementation should become as standards compliant as possible w/o losing performance
- Use template mechanisms to ensure that destructors and move constructors are called where necessary
  - Possibly rely on the optimizer to deal with this
- The type of `m_pos` and `m_capacity` (or their equivalents) should be templatized as in `vector`
  - Possibly add assertions/runtime checks that check for overflow of the capacity (`vector` throws on overflow)
- Ensure that the object has power of two size?
  - Currently, it is 16 bytes larger than its initial buffer, which results in weird sizes, e.g., a 1024 pointer buffer (which is actually used) becomes 8192 + 16 bytes, meaning it spans just over 2 memory pages...
- Use `realloc` for improved performance where possible (`vector` does this)?
- Unify with `vector`?

### List of Instantiations
By forcing that `T` is one of a list of known types and iteratively adding types to this list, I have come up with a hopefully complete list of instantiations. The result [can be seen here](https://github.com/danielschemmel/z3/blob/72c79a10c63334399460f0763c07f7e044344179/src/util/buffer.h#L50-L94).

### Other Notes
Due to its internal structure, accessing the buffer requires chasing a pointer - no matter if it is still the initial buffer or not. If this were to be replaced with a branch over the capacity, the object size could be reduced by 8 bytes on a 64 bit machine. If it is guaranteed that the initial buffer is always large enough, this is inefficient in either case.

**Comment by danielschemmel** [comment]
A (so far) rather conservative implementation can be seen [in the buffer branch of my z3 fork](https://github.com/danielschemmel/z3/tree/buffer). [The new implementation](https://github.com/danielschemmel/z3/blob/buffer/src/util/new_buffer.h) and [the translation to the previous buffer](https://github.com/danielschemmel/z3/blob/buffer/src/util/buffer.h).

**Comment by NikolajBjorner** [comment]
I took a glance at your buffer implementation. It seems pretty competent and as you say, leveraging modern features. I will have to rely on those who are more competent than I to spot whether the appropriate std features are used. We use buffers in places where we assume short-lived objects and vectors most other places. Vectors do have a 64 bit versions when we allow large vectors, but otherwise most code has to assume limited size vectors until a use case tells us otherwise. The distinctions between copy constructor template arguments and those without is quite possibly dated by now as we have (finally) moved to the C++11 world, but our basic infrastructure containers have not taken full advantage of this.

**Comment by danielschemmel** [comment]
Thanks for having a look at the implementation. I have now completed the initial work and implemented the specialization for vector as well ([see this translation to the previous vector class template](https://github.com/danielschemmel/z3/blob/buffer/src/util/vector.h)). At the moment, this is a fairly conservative reimplementation:
- The new class template behaves like `vector` when its `INITIAL_SIZE` is `0` and like `buffer` otherwise
  - The basic algorithms are all kept (both that of `buffer` and of `vector`)
  - Performance should be at least similar to that before - but only by construction, I have not actually benchmarked this...
- There is a shim in place to enable as both `buffer` and `vector`, which requires one change in the rest of the project: There is [a single instance](https://github.com/Z3Prover/z3/blob/c390b72e42222312ca3492756e083a52cfda3c5f/src/util/lp/dense_matrix_instances.cpp#L38) where the class keyword is used in front of `vector`, which needs to be omitted
- No changes are necessary anywhere else
- I did some very basic testing by compiling everything and pushing a few queries into the resulting z3 binary

I believe it would make sense to clean up the interface as well, and would like to make it a bit closer to its counterparts from the standard library. Some parts of that are reasonably simple (e.g. rename the `data` member type to `value_type`), but may still cause a lot of changed lines. What are your feelings on this?

Finally, testing w.r.t. both performance and correctness might be in order. Do you have any suggestions on how to best do so?

**Comment by NikolajBjorner** [comment]
It is possible (but a time sink for me) to run some SMT-LIB regressions on such a pull request, A more targeted approach would be an additional unit test. I don't mind writing one over the weekend it would perform random access to vectors/buffers by push_back functions (we didn't implement emblace as this was introduced after buffers/vectors were written), and also sequential access patterns. 
The main cache issues with the existing vectors is that they record the length inside a dynamically allocated heap object so one gets a cache miss when accessing the length of an initialized vector. A perf test could exercise whether this is measurable.

**Comment by NikolajBjorner** [comment]
This is potentially becoming a bit more than you are bargaining for: 
- If I understand you indicate we could use different allocators. Fair, we mainly want to be able to track application allocation size and an option to fail in a soft way if the barrier is exceeded. It turns out it isn't used much in a critical way (saturation based theorem provers, BDD packages swear to the ability to GC when heap allocation fails or reaches a threshold)..
- I was reflecting yesterday about the origins of vector/buffer instead of std::vector. The decisions were based on 2006 implementations, not on C++11 features. It could very well be that the motivations are no longer valid. 
    - svector avoids copy constructor on expansion. Seems like C++11 has enough features to differentiate these modes (right ?).
    - it hides the custom allocator that keeps track of most of Z3's heap usage (but you could always do this with std anyhow).
   - fiddling with size tracking in the heap, which possibly has a fairly minimal benefit and some penalty when it comes to size access.

**Comment by NikolajBjorner** [comment]
another note: time spent in memory allocation tends to be fairly limited during search. We either use page pools or, if well tuned, there isn't significant heap allocation going on.

**Comment by danielschemmel** [comment]
Playing around with the allocators was mainly my own curiosity (which killed the proverbial cat, I hear), not so much a real suggestion.

Building upon `std::vector` is also totally possible, but will effectively cost 8 bytes, as `sizeof(vector<T>)` turns out to be 24 on x86_64. The std::vector allocator template parameter even allows us to retain the tracking mechanism currently in place. I am however not sure how aggressively `std::vector` utilizes `realloc` and friends (I tuned it quite aggressively, as you can see by the silenced warning ;) ).

Of course std::vector also does not provide the small string optimization of buffer, but that mainly relates to creation not access. (In fact I can even imagine it having weird effects on access due to reducing cache-locality on the heap.) Interestingly, as you noted that memory allocation is limited during search, it may even turn out that buffer is actually counter-productive, as it incurs a slight access penalty...

Size tracking on the heap (as is done in the current Z3 vector) effectively saves 8 bytes (or 50%) on *unused* (not just empty, but capacity == 0) vectors while seemingly slightly reducing performance. It is my guess that the trade-off is not worth it, but I have not really measured impact on memory usage so far.

Oh, and don't worry - I am totally enjoying myself with this :D

**Comment by NikolajBjorner** [comment]
forgot, std::vector does not have c_ptr() (thanks Arie). So can't go there even with vector.

**Comment by danielschemmel** [comment]
std::vector has `.data()` which behaves just like `c_ptr`, but with logical const-ness - is that a problem somewhere?

**Comment by danielschemmel** [comment]
Additionally, `std::vector` guarantess contiguous storage, so `&myvec[0]` has well-defined behavior.

**Comment by NikolajBjorner** [comment]
Depends on compiler and debug mode. Visual studio debug mode includes or included debug asserts that would fire on such uses. Sorry.

**Comment by NikolajBjorner** [comment]
could be. Maintaining what we have with vector and buffer remains the plan for Z3 though. Then I don't have to twist code around working with older compilers and their header files.

**Comment by danielschemmel** [comment]
Makes sense. I think I will clean up the suggested changes a bit and open a pull request in the next few days.
