### ISSUE TITLE
Problem with parse_smtlib2_string

### ISSUE THREAD

**Issue by gpfarina** [Z3Prover/z3#1633]
Hello I m trying to use the above function to parse an smt2 string but I don't understand why it fails. Here a minimal "non" working example:
```
    let ctx=Z3.mk_context  [("model", "true"); ("proof", "false")] ;;
    let str="(assert (> 0 a))" ;;
    let sym=Z3.Symbol.mk_string ctx "a" ;;
    let ssort=Z3.Arithmetic.Integer.mk_sort ctx ;;
    let exprSMT=Z3.SMT.parse_smtlib2_string ctx str [sym] [ssort] [] [] ;;

Exception: Z3.Error("parser error").
Raised by primitive operation at unknown location
Called from file "//toplevel//", line 1, characters 16-71
Called from file "toplevel/toploop.ml", line 180, characters 17-56
```

The following code does not work either for me: 
```
    let ctx=Z3.mk_context  [("model", "true"); ("proof", "false")] ;;
    let str="(assert (> 0 a))" ;;
    let sym=Z3.Symbol.mk_string ctx "a" ;;
    let ssort=Z3.Arithmetic.Integer.mk_sort ctx ;;
    let exprSMT=Z3.SMT.parse_smtlib2_string ctx str [] [] [] [] ;;

Exception: Z3.Error("parser error").
Raised by primitive operation at unknown location
Called from file "//toplevel//", line 1, characters 16-63
Called from file "toplevel/toploop.ml", line 180, characters 17-56

```
Thanks in advance.

GP

**Comment by NikolajBjorner** [comment]
It is easier to declare constants and functions and sorts as part of the string. So try

    let str = "(declare-const a Int) (assert (> 0 a))"
    let exprSMT=Z3.SMT.parse_smtlib2_string ctx str [] [] [] [] ;;

regarding the parse error. Arguments 2 & 3 are lists of sort names and the sorts they bind to. Arguments 4 & 5 are names of constants and functions and their declarations. So you would have to pass in a constant declaration for "a" as part of arguments 4 & 5. The ML API does not specify this, but you would have to rely on the documentation in z3_api.h for the underlying C function to get this information.

**Comment by gpfarina** [comment]
Thanks now i understand better.
