### ISSUE TITLE
Z3 picks control characters in strings - e.g. '\x00'

### ISSUE THREAD

**Issue by ChrisBradshaw1** [Z3Prover/z3#1636]
It appears that Z3 is free to pick any 8-bit character value for characters in a string, and defaults to picking '\0' when it is able to:

>>> a = String("a")
>>> s = Solver()
>>> s.add(Length(a) == 5)
>>> s.check()
sat
>>> s.model()
[a = "\x00\x00\x00\x00\x00"]

This seems incorrect, as a string of 5 NULL characters is just the empty string. 

I have tried adding additional constraints of the form:
Not(Contains(string, StringVal('\\x00')))

This has two issues:
- returns unknown if no restriction is placed on length
>>> s.add(Not(Contains(a, "\\x00")))
>>> s.check()
unknown
- The set of characters that I wish to exclude is large (0-31; 128-255), and this slows down the solution generation for Strings considerably (~5x).

Is it possible to make a change to Z3 itself to prevent it from picking these control/special characters? If this is not considered to be useful more widely I can make the change myself if given a pointer to what changes are needed. 

Thanks,
Chris

**Comment by OrenGitHub** [comment]
> a string of 5 NULL characters is just the empty string

There is a difference between how Z3 represents strings and how C represents strings.
A C string is a sequence of characters **up until the first null termination**.
While a Z3 size 5 string is a sequence of 5 characters.
What you're looking for is indexof:

    (declare-const a String)
    
    (assert (= (str.indexof a "\x00" 0) 5))
    
    (check-sat)
    (get-value (a))

Which gives:

    sat
    ((a "�\x04\x02\x01\x01\x00"))

If you don't like \x00 as default value you can try to specify:

    smt.string_solver=z3str3

Which outputs visible ascii as its default (from what I've seen at least):

    sat
    ((a "aaaa3\x00\x00e"))

**Comment by ChrisBradshaw1** [comment]
Thanks - setting string_solver=z3str3 has the behaviour I am looking for.
