### ISSUE TITLE
timeout message inconsistency

### ISSUE THREAD

**Issue by LeventErkok** [Z3Prover/z3#1638]
I'm curious why the Python and the SMTLib interfaces react differently to timeout commands.

For this script:

```python
from z3 import *
s = Solver()
s.set(timeout=1)
x, y = Ints('x y')
s.add(x**y == x)
result = s.check()
print result
print s.reason_unknown()
```

Z3 nicely says:

```
unknown
timeout
```

I'd consider the following to be the rendering of the same in SMTLib:

```
(set-option :timeout 1)
(declare-fun x () Int)
(declare-fun y () Int)
(assert (= (^ x y) x))
(check-sat)
(get-info :reason-unknown)
```

For this, z3 says:

```
unknown
(:reason-unknown "canceled")
```

The python response is much more accurate; as `canceled` is quite vague.

Would it be possible to have the unknown response be the same in SMTLib ? That is:

```
(:reason-unknown "timeout")
```

**Comment by pastelblue** [comment]
I run this Python script but z3 says: 
<pre>
unknown
canceled
</pre>

**Comment by LeventErkok** [comment]
@pastelblue 

With a very fresh build of Z3 (i.e., out of github master branch HEAD), I see the reported behavior:

```
$ z3 -version
Z3 version 4.8.0 - 64 bit
```

Perhaps you're using an older version?
