### ISSUE TITLE
Breakage around optimization routines

### ISSUE THREAD

**Issue by LeventErkok** [Z3Prover/z3#1644]
@NikolajBjorner 

I'm seeing some test failures with a very fresh Z3 build (https://travis-ci.org/LeventErkok/sbv/jobs/382869021#L3283)

Failures seem to be happening around optimization calls, but I haven't investigated in full yet.

Since you seem to be in the middle of a bunch of changes, I wanted to check if you'd rather I wait till the code-base stabilizes, or would rather hear about these right away. Please advise.

**Comment by NikolajBjorner** [comment]
We have regression tests with every build. For your own regression tests, 
perhaps could you use the serializers to SMT-LIB and a corresponding "gold" output would let us run similar regressions on every CI build.

**Comment by LeventErkok** [comment]
Great! I'll report as I see issues.
