### ISSUE TITLE
Pareto optimization no longer terminates

### ISSUE THREAD

**Issue by LeventErkok** [Z3Prover/z3#1647]
Z3 no longer terminates with the following query:

```
(declare-fun x () Int)
(assert (>= 1 x))
(assert (<= 0 x))
(minimize x)
(maximize (+ x x))
(set-option :opt.priority pareto)
(check-sat)
```

This used to work till yesterday.

**Comment by NikolajBjorner** [comment]
this wasn't a new bug, it reproduces in 4.6 and 4.7.1 and likely in most other versions. x ends up being eliminated before the first optimization calls.

**Comment by LeventErkok** [comment]
Quite right. My bad; I was trying to simplify my failing test, and ran into this; didn't realize it was failing before as well.

I'm still seeing an issue with pareto though, so expect another ticket coming soon.
