### ISSUE TITLE
Another looping pareto

### ISSUE THREAD

**Issue by LeventErkok** [Z3Prover/z3#1652]
(This is still not my failing test case; but I'm running into it as I'm trying to simplify it. It won't terminate. Possibly was looping before as well.)

```
(declare-fun x   () Int)
(declare-fun mx  () Int)
(declare-fun mxx () Int)
(assert (>= 1 x))
(assert (<= 0 x))
(assert (= x mx))
(minimize mx)
(maximize mxx)
(set-option :opt.priority pareto)
(check-sat)
```

**Comment by NikolajBjorner** [comment]
This should not be a new issue: the objective mxx is unbounded and the pareto code doesn't check for unbounded objectives. I am currently inclined to ask callers to ensure that objectives are always bounded before invoking pareto as the query doesn't make much sense for unbounded models.

**Comment by LeventErkok** [comment]
One way to do that would be to call `(get-objectives)` after `(check-sat)`; but that's chicken-and-egg here.

Do you recommend first doing a check-sat call using lexicographic priority, and then switch to pareto if all objectives are bounded?

**Comment by NikolajBjorner** [comment]
It would be the box priority for pareto front bounds, but otherwise yes if your application doesn't guarnatee bounds it can check for them.

    (set-option :opt.priority pareto)
    (check-sat)
    (get-objectives)

    sat
    (objectives
     (mx 0)
     (mxx oo)
    )

**Comment by LeventErkok** [comment]
You meant:

     (set-option :opt.priority box)

I trust. Fair enough.

I'm still having other issues with pareto though in the bounded case; will open another ticket.
