### ISSUE TITLE
Segmentation Fault when using QF_S and regular expressions

### ISSUE THREAD

**Issue by julianthome** [Z3Prover/z3#1662]
Hello,

using `QF_S` in conjunction with regular expressions may lead to segmentation faults. I have attached an [example constraint](https://github.com/Z3Prover/z3/files/2053857/segfault.txt) that triggers a segmentation fault for Z3 4.7.1. When trying to solve the same constraint with Z3 4.6.0, it does not lead to a segmentation fault.

Thanks a lot and kind regards,
  Julian

**Comment by NikolajBjorner** [comment]
theory_str (and theory_seq) don't support regular expressions over variables, such as (str.to.re sv1)
