### ISSUE TITLE
logic conversion ??

### ISSUE THREAD

**Issue by alx441** [Z3Prover/z3#1663]
Hi,
I think it could be a stupid question, but it is not clear for me (Sorry if this is the case) :

If i have a smt2-file with queries in QF_BV theory, how do i proceed to have an equivalent smt2-file with queries in QF_LIA theory ? (For example with Z3Py)

**Comment by NikolajBjorner** [comment]
You can't have an equivalent, but at best an equi-satisfiable formula, by loading the QF_BV file into a set of assertions and then walk them recursively, translating bit-vector variables to integer variables. You will be better off translating each syntax node to an equation or set of equations to ensure that the result is in QF_LIA.

**Comment by alx441** [comment]
Thank you.
