### ISSUE TITLE
Underflow checking of signed multiplication

### ISSUE THREAD

**Issue by LeventErkok** [Z3Prover/z3#1668]
@NikolajBjorner This is not strictly about Z3, but about the following paper:

   https://www.microsoft.com/en-us/research/wp-content/uploads/2016/02/z3prefix.pdf

(I believe some of the code in Z3 regarding overflow-checking is based on this paper, so perhaps it's related in that way.)

On page 12 when it talks about checking underflow for signed multiplication, I think we need to make an explicit check that neither `x` nor `y` equals `0`.

For instance, if `x` is `0`, and `y` is any negative number, then the hypothesis that the signs are different holds (essentially `0` being identified as sign-bit `0`), but the consequent fails since the extended multiplication produces `0`; and thus the check that all the initial `N+1` bits must be `1` fails. So, a straightforward reading of the formula will  incorrectly classify this case as an underflow.

A minor point perhaps, but wanted to double check with you that this is indeed needed. Or is there some other language in the paper that I missed that already covers this case?

**Comment by NikolajBjorner** [comment]
Page 12 seems dated. The implementation multiplies into N+1 bits and checks if MSB of x, y add up to N, is less than N or bigger than N. Only in the case that the sum of MSBs is N, is it required to check the N+1'st bit.

**Comment by LeventErkok** [comment]
@NikolajBjorner Thanks Nikolaj. I'm having hard time following your comment though; is there a piece of code I can look to decipher?

**Comment by NikolajBjorner** [comment]
yes you found it. There are comments. The MSB acts as the sign bit and it is used to calibrate the locations of the most significant bits in a and b as also described in the TR.

**Comment by LeventErkok** [comment]
Thanks. I'll give this a shot and hopefully will be able to reconstruct it.

**Comment by LeventErkok** [comment]
@NikolajBjorner Thanks for all the help! Just a note that I was able to reconstruct the code, and it all worked out.

One minor note, in case you're "fixing" the paper: At the top of page 14, the formula for signed->unsigned underflow casting is actually checking when the underflow happens. Instead of:

    [|(N_s → M_u) x|]_ ≐ x[N − 1] ≃ 1

it should say:

    [|(N_s → M_u) x|]_ ≐ x[N − 1] ≃ 0

**Comment by NikolajBjorner** [comment]
I will take all credit and put all blame on Yannick Moy for the errors :-)
