### ISSUE TITLE
Unknown returned from simple string query

### ISSUE THREAD

**Issue by OrenGitHub** [Z3Prover/z3#1672]
Hi,
I have the following simple string query that **returns unknown**:

    (declare-fun AB_.str2_0_version_0  () String)
    (declare-fun AB_serial_1_version_0 () String)
    (declare-fun AB_serial_1_version_1 () String)
    (declare-fun AB_serial_2_version_0 () String)
    (declare-fun tmp_read_arr_10 () (Array (_ BitVec 32) (_ BitVec 8)))
    (declare-fun tmp_read_arr_21 () (Array (_ BitVec 32) (_ BitVec 8)))
    (declare-fun c0 () String)
    (assert (= AB_.str2_0_version_0 "<br/>\x00"))
    
    (assert (= (str.len AB_serial_1_version_0) 16))
    (assert (= (str.len AB_serial_1_version_1) (str.len AB_serial_1_version_0)))
    (assert (= (str.at AB_serial_1_version_1 15) (seq.unit #x00)))
    (assert (let ((a!1 (+ (str.indexof (str.substr AB_serial_1_version_1 0 (- 16 0))
                               (seq.unit #x00)
                               0)
                  1)))
      (= 10 a!1)))
    
    (assert (= (str.len AB_serial_2_version_0) 10))
    (assert (= (seq.unit (select tmp_read_arr_10 #x00000000))
       (str.at AB_serial_1_version_1 0)))
    (assert (= (seq.unit #x3c) (str.at AB_serial_1_version_1 0)))
    (assert (= #x3c (select tmp_read_arr_21 #x00000000)))
    (assert (let ((a!1 (str.indexof (str.substr AB_serial_1_version_1 0 (- 16 0))
                            (seq.unit #x00)
                            0))
          (a!2 (str.indexof (str.substr AB_.str2_0_version_0 0 (- 6 0))
                            (seq.unit #x00)
                            0)))
    (let ((a!3 (= (str.substr (str.substr AB_serial_1_version_1 0 (- 16 0))
                              0
                              (ite (<= a!1 5) a!1 5))
                  (str.substr (str.substr AB_.str2_0_version_0 0 (- 6 0))
                              0
                              (ite (<= a!2 5) a!2 5)))))
      (= #x00000000 (ite a!3 #x00000000 #x00000001)))))
    
    ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
    ; if I comment out the following line, z3 immediately returns sat  ;
    ; note that c0 is unconstrained and can be almost anything ...     ;
    ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
    (assert (not (str.contains (str.substr AB_serial_1_version_1 0 (- 16 0)) c0)))

    ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
    ; Furthermore, if I reveal the following "hint" that c0 might be "M" ;
    ; then again, z3 returns immediately with a sat answer               ;
    ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
    ;(assert (= c0 "M"))
    
    (check-sat)
    (get-value (AB_serial_1_version_1 c0))

However, the line that confuses him involves an unconstrained string variable c0,
for which almost any value will do.
Is that a "reasonable" behavior?
Thanks!

**Comment by NikolajBjorner** [comment]
Thanks for the example. The solver is unable to handle the not-contains constraint unless it is given strong hints.
