### ISSUE TITLE
fp.max is no longer defined in latest version of z3

### ISSUE THREAD

**Issue by migimunz** [Z3Prover/z3#1674]
Hi,

fp.max no longer seems to be defined, and z3 interprets it as an unspecified uninterpreted function. The following program:

```
(set-logic QF_FP)
(declare-fun a ()(_ FloatingPoint 4 12))
(assert (fp.eq (fp.max a a) (fp.max a a)))
(check-sat)
(get-model)
```
should just produce a model for a. However, the version from master produces the following model:

```
(model 
  (define-fun a () (_ FloatingPoint 4 12)
    (_ +zero 4 12))
  (define-fun fp.max ((x!0 (_ FloatingPoint 4 12)) (x!1 (_ FloatingPoint 4 12))) (_ FloatingPoint
     4
     12)
    (_ +zero 4 12))
)
```

**Comment by migimunz** [comment]
Additionally, here's an example that was unsat on 4.4.1, but is now sat because max is sometimes treated as an uninterpreted function.

```
(set-logic QF_FP)
(declare-fun fp_a ()(_ FloatingPoint 4 12))
(declare-fun fp_b ()(_ FloatingPoint 8 24))
(assert (fp.geq (fp.mul RTN (fp.mul RNE fp_b fp_b) ((_ to_fp 8 24) RNE fp_a)) (fp.add RTP ((_ to_fp 8 24) RNE (fp.sub RTN fp_a ((_ to_fp 4 12) RNE fp_b))) (fp.div RTN fp_b fp_b))))
(assert (not (fp.isNaN (fp.add RTZ (fp.add RTZ (fp #b1 #b1010 #b11101011010) ((_ to_fp 4 12) RNE fp_b)) (fp.sub RTP fp_a fp_a)))))
(assert (fp.lt ((_ to_fp 8 24) RNE (fp.max (fp.sub RTP (fp #b1 #b1010 #b11001010110) ((_ to_fp 4 12) RNE (fp #b1 #b00000000 #b11001001100010101000011))) ((_ to_fp 4 12) RNE (fp.div RTZ fp_b fp_b)))) (fp.add RNE (fp.min ((_ to_fp 8 24) RNE fp_a) fp_b) ((_ to_fp 8 24) RNE (fp.add RTZ fp_a fp_a)))))
(assert (not (fp.eq (fp.sub RTZ (fp.mul RTZ ((_ to_fp 4 12) RNE (fp #b1 #b10001110 #b01111001110100010111110)) fp_a) (fp.mul RTZ ((_ to_fp 4 12) RNE fp_b) fp_a)) (fp.mul RTP ((_ to_fp 4 12) RNE (fp.min ((_ to_fp 8 24) RNE fp_a) (fp #b0 #b00000000 #b10010011000100000101100))) (fp.div RTP ((_ to_fp 4 12) RNE (_ -oo 8 24)) fp_a)))))
(check-sat)
(get-model)
```

Output on current master:
```
(model 
  (define-fun fp_b () (_ FloatingPoint 8 24)
    (fp #b0 #xf8 #b00000000000000000000000))
  (define-fun fp_a () (_ FloatingPoint 4 12)
    (fp #b0 #x8 #b00000000001))
  (define-fun fp.min ((x!0 (_ FloatingPoint 8 24)) (x!1 (_ FloatingPoint 8 24))) (_ FloatingPoint
     8
     24)
    (ite (and (= x!0 (_ +zero 8 24)) (= x!1 (_ -zero 8 24))) (_ -zero 8 24)
      (_ +zero 8 24)))
  (define-fun fp.max ((x!0 (_ FloatingPoint 4 12)) (x!1 (_ FloatingPoint 4 12))) (_ FloatingPoint
     4
     12)
    (_ +zero 4 12))
)
```

**Comment by wintersteiger** [comment]
This is correct, `fp.min`/`fp.max` are not defined for `+zero`/`-zero` inputs. See [SMTLIB](http://smtlib.cs.uiowa.edu/theories-FloatingPoint.shtml) and [semantics paper](http://smtlib.cs.uiowa.edu/papers/BTRW15.pdf).

**Comment by LeventErkok** [comment]
@wintersteiger 

I thought the parameter `hi_fp_unspecified` can be used to control the behavior of this, but a few experiments suggest that is not the case: 

https://github.com/Z3Prover/z3/blob/e8f4dd76c21b52460b6bd95487183aea88749ce0/src/ast/fpa/fpa2bv_rewriter_params.pyg#L4

Is this not the intended use case for this parameter?

**Comment by wintersteiger** [comment]
@LeventErkok No, `hi_fp_unspecified` disables all unspecified FP behavior of all FP functions and essentially replaces them with zeroes. I.e., this is completely unsound and only to be used if you are absolutely sure what you're doing (for instance testing the bit-blaster), not just because you're too lazy to ignore the uninterpreted functions in the model.
