### ISSUE TITLE
Python Interface Does not Support Array Default operator

### ISSUE THREAD

**Issue by npricci** [Z3Prover/z3#168]
There doesn't seem to be a way to use the "default" operator on arrays using the python interface. I.E., it would be nice to do something like this:

(declare-const FPolicy (Array Int Int Int Bool))

(assert (select FPolicy 0 1 30))
(assert (select FPolicy 0 2 20))
(assert (not (default FPolicy)))

Work in the python interface, but there is no way to use the "default" operator.

**Comment by NikolajBjorner** [comment]
added to unstable
