### ISSUE TITLE
No model for (A xor A) == 0

### ISSUE THREAD

**Issue by JonathanSalwan** [Z3Prover/z3#1680]
Hello,

I'm wondering why z3 cannot provide a model for the following constraint:

```smt
(set-logic QF_BV)

(declare-fun A () (_ BitVec 64))

(assert (= (bvxor A A) (_ bv0 64)))

(check-sat)
(get-model)
```

```console
$ z3 --version
Z3 version 4.8.0 - 64 bit

$ z3 -smt2 ./a-xor-a.smt2
sat
(model 
)
```

Is there something that i'm missing or misunderstood?

**Comment by NikolajBjorner** [comment]
Any value of A satisfies the constraint. A disappears during pre-processing so there is no reference to A during solving and model generation. When you use the API to query the value of A you can specify whether to _complete_ the model construction for A. Under model completion, the API for querying values will fix some arbitrary value for A.
