### ISSUE TITLE
error: stray ‘#’ in program on Ubuntu 14.04

### ISSUE THREAD

**Issue by haggaie** [Z3Prover/z3#1682]
Hi,

I tried building z3 on Ubuntu 14.04, and I got the following error:
```
../src/smt/smt_context.cpp:2642:191: error: stray ‘#’ in program
         IF_VERBOSE(2, verbose_stream() << "(smt.simplifying-clause-set"; verbose_stream().flush(););
                                                                                                                                                                                               ^
../src/smt/smt_context.cpp: In member function ‘void smt::context::simplify_clauses()’:
../src/smt/smt_context.cpp:2642:198: error: expected ‘;’ before string constant
         IF_VERBOSE(2, verbose_stream() << "(smt.simplifying-clause-set"; verbose_stream().flush(););
                                                                                                                                                                                                      ^
```

I tried running the C++ preprocessor only and I got the following output:
```c++
        { if (get_verbosity_level() >= 2) { if (is_threaded()) { { 
# 2642 "../src/smt/smt_context.cpp"
#pragma omp critical (verbose_lock)
# 2642 "../src/smt/smt_context.cpp"
 { verbose_stream() << "(smt.simplifying-clause-set"; verbose_stream().flush();; } }; } else { verbose_stream() << "(smt.simplifying-clause-set"; verbose_stream().flush();; } } } ((void) 0);# 2653 "../src/smt/smt_context.cpp"
```

I'm not sure if that's the issue, but it seems like the line number statement for `# 2653` joins the line before and causes the error. 

Is Ubuntu 14.04 supposed to work?

**Comment by NikolajBjorner** [comment]
Not sure to test this on my end, all build machines pass. Try the following in src/util/util.h and let me know if this works.


#ifdef _MSC_VER
#define DO_PRAGMA(x) __pragma(x)
#define PRAGMA_LOCK __pragma(omp critical (verbose_lock))
#else
#define DO_PRAGMA(x) _Pragma(#x)
#define PRAGMA_LOCK _Pragma("omp critical (verbose_lock)")
#endif

#ifdef _NO_OMP_
#define LOCK_CODE(CODE) CODE;
#else
#define LOCK_CODE(CODE)                         \
    {                                           \
        PRAGMA_LOCK   \
            {                                   \
                CODE;                           \
            }                                   \
    }                      
#endif

**Comment by haggaie** [comment]
Thanks. I tried your suggestion but it didn't help. I saw that only this specific line in smt_context.cpp caused the error, and not other instances of `IF_VERBOSE`, so I tried moving it to some other place in the code where it is not immediately followed by a comment. That seemed to solve the issue. I guess there is some kind of C pre-processor bug in this distro.

Here's the change that helped:
```diff
diff --git a/src/smt/smt_context.cpp b/src/smt/smt_context.cpp
index 14a19f824236..e50b8a1ae689 100644
--- a/src/smt/smt_context.cpp
+++ b/src/smt/smt_context.cpp
@@ -2636,11 +2636,10 @@ namespace smt {
         }
 
         TRACE("simplify_clauses_detail", tout << "before:\n"; display_clauses(tout, m_lemmas););
+        IF_VERBOSE(2, verbose_stream() << "(smt.simplifying-clause-set"; verbose_stream().flush(););
         SASSERT(check_clauses(m_lemmas));
         SASSERT(check_clauses(m_aux_clauses));
 
-        IF_VERBOSE(2, verbose_stream() << "(smt.simplifying-clause-set"; verbose_stream().flush(););
-
         // m_simp_counter is used to balance the cost of simplify_clause.
         //
         // After executing simplify_clauses, the counter will contain
```

**Comment by NikolajBjorner** [comment]
Thanks, sorry this is weird. I moved the line in the code per what worked for you.
