### ISSUE TITLE
simple `div` reasoning

### ISSUE THREAD

**Issue by daejunpark** [Z3Prover/z3#1683]
Z3 seems to fail to prove `(x * y) / y == x` when `/` is the integer division `div`, while it succeeds in proving it when `/` is the real division. What am I missing here? Thanks!

Here is a simple example query:
```
(declare-fun x () Int)
(declare-fun y () Int)

(assert (> x 0))
(assert (> y 0))

; (x * y) / y == x 
 (assert (not (= (div (* x y) y) x))) ; timeout
;(assert (not (= (/   (* x y) y) x))) ; unsat

(check-sat)
```

Permalink: https://rise4fun.com/Z3/RlSF

**Comment by NikolajBjorner** [comment]
Z3 is rather weak when it comes to non-linear integer reasoning. If you have a set of use-cases we should target it would help working on fixing this area.

**Comment by NikolajBjorner** [comment]
I have added some preprocessing to catch some of these cases.

**Comment by jad-hamza** [comment]
Hi,

Here is another example which is not going through (returns `unknown` on 4.8.4 and current master 112e13e):

```smt
(declare-const n Int)
(assert (= (div n n) 1))
(check-sat)
(get-model)
```

**Comment by levnach** [comment]
Now it produces unsat for both cases - incorrectly.
