### ISSUE TITLE
Unable to build z3-solver using "pip install z3-solver"

### ISSUE THREAD

**Issue by unboxedtype** [Z3Prover/z3#1688]
Having troubles with installing z3-solver using pip.

`$ python -m virtualenv env`
..
`$ source env/bin/activate`
..
`$ pip install z3-solver`
....
"../src/util/lp/permutation_matrix.h:120:44: error: cannot convert ‘const vector<unsigned int>’ to ‘unsigned int’ in return
unsigned values() const { return m_permutation; }

Problem can be fixed by changing the line at
../z3-solver-4.5.1.0.post2/core/src/util/lp/permutation_matrix.h: 120
to 
`unsigned * values() const { return m_permutation.c_ptr(); }`

**Comment by NikolajBjorner** [comment]
This is already fixed in the current master branch.
