### ISSUE TITLE
z3str3 crashes instead of reporting error

### ISSUE THREAD

**Issue by pjljvandelaar** [Z3Prover/z3#1695]
I am using the latest nightly Z3 version on Windows
`Z3 version 4.8.0 - 64 bit - build hashcode a12af4a619a0`

Using TorXakis and `Z3` I made the attached smt2 file.
[smt2.txt](https://github.com/Z3Prover/z3/files/2122840/smt2.txt)

When I provide this file to `z3str3`, I get the following output
[z3str3.txt](https://github.com/Z3Prover/z3/files/2122851/z3str3.txt)
before `z3str3` crashes.

I understand that calling `get-val` after `check-sat` returned `unknown` should not result in a value.
And indeed most problem solvers return `(error "no model after unknown")` instead of crashing.
Could z3str3 be made to also not crash?

Note: I found this behavior while analyzing different behavior between z3 and z3str3.
See https://github.com/TorXakis/TorXakis/issues/739 for more details.

**Comment by NikolajBjorner** [comment]
get-val / eval should not crash regardless of whether there is valid model or not. Murphy, could you take a look? seems to not be a small repro and take some time to get there.

**Comment by mtrberzi** [comment]
Thanks - taking a look

**Comment by mtrberzi** [comment]
Crash for me is during the search, not during `get-val`. This is an issue I've been aware of related to value testing but which I thought I fixed a while ago. Looks like I will have to reopen that investigation.

**Comment by NikolajBjorner** [comment]
Correct, I also get the crash during search inside theory_str. An expression is nullptr when it shouldn't be.

**Comment by pjljvandelaar** [comment]
Crash also observed with z3 version "4.8.4 - build hashcode b40c2b2926ed"

**Comment by pjljvandelaar** [comment]
Note: 8 crashes of z3str3 are also observed in the benchmarks of #1979.

After a crash, I waited at least five minutes before pressing `Close the program`.

4.8.4 z3 | 4.8.4 z3str3 | improvement     z3str over z3
-- | -- | --
0,0292 | 0,0249 | 0,854492265
0,0200 | 0,0202 | 1,010675765
0,0652 | 0,0622 | 0,953241067
0,0268 | 0,0316 | 1,179754622
0,0215 | 0,0208 | 0,964676652
0,1813 | 0,1956 | 1,078533105
0,0733 | 0,0880 | 1,200625741
0,0194 | 0,0212 | 1,093964709
0,0203 | 0,0206 | 1,013344946
0,0194 | 0,0214 | 1,101336412
0,0192 | 0,0208 | 1,080204175
0,8524 | 0,9499 | 1,114493269
0,0191 | 0,0223 | 1,168348581
0,0195 | 0,0215 | 1,105280706
0,0195 | 0,0206 | 1,055426412
0,0208 | 0,0206 | 0,990614261
0,0195 | 0,0209 | 1,068779415
0,0194 | 0,0201 | 1,036671317
0,4654 | 0,5557 | 1,194089792
22,8322 | 443,2295 | 19,41249411
0,0200 | 0,0282 | 1,409440834
0,0193 | 0,0271 | 1,402322825
0,0192 | 0,0276 | 1,436506902
0,0188 | 0,0258 | 1,370084102
0,0559 | 0,0863 | 1,542948717
0,8505 | 1,4320 | 1,683708987
0,7564 | 1,3956 | 1,845169367
0,9616 | 1,8302 | 1,903263962
0,0195 | 0,0271 | 1,39071778
0,0189 | 0,0255 | 1,346905856
0,0245 | 0,0264 | 1,078232766
0,0207 | 0,0291 | 1,405108326
0,0214 | 0,0399 | 1,86334722
0,0190 | 0,0286 | 1,500157619
0,0334 | 0,0556 | 1,663759667
0,0344 | 0,0623 | 1,812783806
0,2389 | 0,4614 | 1,930814144
0,0266 | 0,0365 | 1,37380527
0,0223 | 0,0338 | 1,515292199
0,0652 | 0,0923 | 1,414947272
0,0456 | 0,0702 | 1,539731157
0,0230 | 0,0416 | 1,803891865
0,0207 | 0,0759 | 3,66842146
0,0224 | 0,0512 | 2,287217031
0,4386 | 0,8164 | 1,861340074
0,0914 | 0,1313 | 1,436655003
2,0819 | 3,9076 | 1,876999261
1,6741 | 2,9272 | 1,748509052
330,7267 | 898,0559 | 2,715402077
0,0295 | 0,0243 | 0,826120604
0,0288 | 0,0223 | 0,773561565
0,0276 | 0,0227 | 0,822146264
0,0318 | 0,0225 | 0,70868507
0,0808 | 0,0609 | 0,753130593
0,0520 | 0,0414 | 0,79665475
0,1293 | 0,0865 | 0,669023582
0,0657 | 0,0487 | 0,741374009
0,1010 | 0,0720 | 0,71338307
0,1248 | 0,0893 | 0,715694821
0,0944 | 0,0587 | 0,621101734
4,9483 | 628,2799 | 126,9682935
30,8470 | 505,3643 | 16,38292399
0,0334 | 0,0311 | 0,929767968
0,0527 | 0,0345 | 0,653614389
0,0341 | 0,0288 | 0,842756976
0,0328 | 0,0248 | 0,756571972
0,0336 | 0,0283 | 0,844481859
0,0461 | 0,0349 | 0,755412381
0,0418 | 0,0395 | 0,944818613
0,1096 | 0,0485 | 0,442865578
57,1186 | 662,6629 | 11,60152935
3,4496 | 361,9148 | 104,9136361
0,0248 | 0,0278 | 1,119349944
0,0224 | 0,0263 | 1,173562864
0,0203 | 0,0261 | 1,285817567
0,0211 | 0,0263 | 1,246223314
0,0217 | 0,0240 | 1,106846086
0,0226 | 0,0256 | 1,13494652
0,0255 | 0,0222 | 0,870607998
0,0641 | 0,0654 | 1,020438182
0,0327 | 0,0348 | 1,063986381
0,0389 | 0,0380 | 0,975830009
0,0345 | 0,0325 | 0,94159937
0,0330 | 0,0283 | 0,859698793
0,0642 | 0,0568 | 0,885365736
0,0618 | 0,0422 | 0,682223566
0,0301 | 0,0277 | 0,918462759
0,0389 | 0,0312 | 0,802630395
0,0381 | 0,0310 | 0,814054074
0,0427 | 0,0323 | 0,757714907
0,0264 | 0,0205 | 0,777009321
0,0272 | 0,0201 | 0,739994634
0,0230 | 0,0207 | 0,900481464
0,0269 | 0,0206 | 0,763824042
0,0247 | 0,0207 | 0,83742544
1,3305 | 0,9398 | 0,706333805
10,3794 | 8,0966 | 0,780065164
1,1009 | 1,1606 | 1,054233974
1,6685 | 1,7438 | 1,045170709
0,0214 | 0,0213 | 0,995484579
0,0200 | 0,0206 | 1,030760545
0,0200 | 0,0209 | 1,041556017
0,0199 | 0,0210 | 1,054388034
2,5948 | 2,5278 | 0,974206556
0,3940 | 0,3863 | 0,980488985
0,6390 | 0,7059 | 1,104677174
0,2512 | 0,2556 | 1,017513936
0,1999 | 0,2015 | 1,008023505
0,8145 | 0,8351 | 1,025373628
0,9897 | 1,0790 | 1,090258664
1,0566 | 1,0952 | 1,036599203
19,0009 | 445,5722 | 23,45001658
26,6410 | 350,4960 | 13,15625965
0,0288 | 0,0281 | 0,973315585
0,0229 | 0,0247 | 1,080055455
0,0254 | 0,0295 | 1,161459771
0,0257 | 0,0253 | 0,985198522
0,0260 | 0,0236 | 0,906902969
0,1563 | 0,1352 | 0,86476161
0,1566 | 0,1251 | 0,798524776
33,1672 | 19,1056 | 0,576038244
0,2024 | 0,1188 | 0,586596859
  |   |  
562,3671 | 4351,7748 | 7,738316935

I am curious whether z3str3 is an improvement overall when the crashes are removed.

**Comment by mtrberzi** [comment]
We're in the process of replacing value testing (which is causing these crashes) with a faster and more stable model construction procedure. I'll evaluate against that and see how it performs.

**Comment by pjljvandelaar** [comment]
I downloaded Z3 today, Z3Str3 does not crash anymore!
However, Z3Str3's performance is terrible. It seems to hang, where as Z3 just solves this file.

**Comment by pjljvandelaar** [comment]
Z3Str3 is also unable to solve:
[slow.smt2.txt](https://github.com/Z3Prover/z3/files/4275749/slow.smt2.txt)
which z3 solves almost immediately!
