### ISSUE TITLE
Not Authorized to download (OSX)

### ISSUE THREAD

**Issue by checkraiser** [Z3Prover/z3#1696]
I clicked on Download for MacOS, successfully signed in and got `Not Authorized to download` error.
How can i download binary for MacOSX ?

**Comment by NikolajBjorner** [comment]
Can you provide more details? What link did you try? Is the error persistent?

**Comment by checkraiser** [comment]
Hi, this is the [link](https://cz3.visualstudio.com/Z3/_build/index?definitionId=2)

**Comment by NikolajBjorner** [comment]
This is not the download link. Go to httos://github.com/z3prover/bin  instead

**Comment by checkraiser** [comment]
@NikolajBjorner Ah, i see. Thanks.
