### ISSUE TITLE
Error querying relations with datalog engine with bitvectors of size 64

### ISSUE THREAD

**Issue by brianburns567** [Z3Prover/z3#1698]
I am not sure if this is just a size constraint or a bug, but I am trying to run a modified example from the Z3 fixed-points tutorial and I am getting the following error:

`(error "query failed: Rule contains infinite sorts in rule <null>:
path(#1,#0) :- 
 edge(#1,#0).
")
unknown
`

Here is the code:

```
define-sort s () (_ BitVec 64))
(declare-rel edge (s s))
(declare-rel path (s s))
(declare-var a s)
(declare-var b s)
(declare-var c s)

(rule (=> (edge a b) (path a b)))
(rule (=> (and (path a b) (path b c)) (path a c)))

(rule (edge #x0000000000000001 #x0000000000000002))
(rule (edge #x0000000000000001 #x0000000000000003))
(rule (edge #x0000000000000002 #x0000000000000004))

(declare-rel q1 ())
(declare-rel q2 ())
(declare-rel q3 (s))
(rule (=> (path #x0000000000000001 #x0000000000000004) q1))
(rule (=> (path #x0000000000000003 #x0000000000000004) q2))
(rule (=> (path #x0000000000000001 b) (q3 b)))

(query q1)
(query q2)
(query q3 :print-answer true)
```

If I change `(_ BitVec 64)` to `_ BitVec 48)` and update the values accordingly (i.e. remove four 0's from each), it works perfectly. I am using Z3 4.8.0 on Debian 8.10.

Note that the only things I changed from the tutorial example are the bitvector size, and their representation (binary -> hex).

**Comment by NikolajBjorner** [comment]
It is a design decision. The bottom up data log engine that uses hash tables can at most hold relations with a few million entries. So using large bit vectors for that engine is not a good match.

**Comment by ikv163** [comment]
I had the same problem, how to solve it?
