### ISSUE TITLE
Bug in either FP conversion or addition

### ISSUE THREAD

**Issue by LeventErkok** [Z3Prover/z3#17]
This is on the unstable branch.

The following benchmark is essentially asking Z3 to compute the addition of the following two numbers:

```
   15749125 / 64
   268632143 / 1024
```

represented as single-precision floating point numbers.

With `roundNearestTiesToEven`, these numbers in decimal are:

```
246080.08
16255.999
```

So, addition should produce 

```
262336.06
```

But it appears Z3 is producing a value that equals

```
2.1885552e-38
```

which is nowhere even close. I'm not sure if the bug is in the conversion of the constants, which I believe you recently modified, or in the actual `fp.add` routine.

Here's the benchmark:

```
; Automatically generated by SBV. Do not edit.
(set-option :produce-models true)
(set-logic QF_FP)
; --- uninterpreted sorts ---
; --- literal constants ---
(define-fun s_2 () Bool false)
(define-fun s_1 () Bool true)
(define-fun s1 () RoundingMode roundNearestTiesToEven)
(define-fun s2 () (_ FloatingPoint  8 24) ((_ to_fp 8 24) roundNearestTiesToEven (/ 15749125 64)))
(define-fun s3 () (_ FloatingPoint  8 24) ((_ to_fp 8 24) roundNearestTiesToEven (/ 16646143 1024)))
; --- skolem constants ---
(declare-fun s0 () (_ FloatingPoint  8 24))
; --- constant tables ---
; --- skolemized tables ---
; --- arrays ---
; --- uninterpreted constants ---
; --- user given axioms ---
; --- formula ---
(assert ; no quantifiers
   (let ((s4 (fp.add s1 s2 s3)))
   (let ((s5 (fp.eq s0 s4)))
   s5)))
(check-sat)
(get-value (s0))
``` 

Z3 responds:

```
sat
((s0 (fp #b0 #x01 #b11011100101000000000100)))
```

which is the internal representation for `2.1885552E-38`

**Comment by LeventErkok** [comment]
I did some extra testing, and it appears the handling of constants is OK, but the issue lies really with `fp.add` itself; and possibly other arithmetic.

**Comment by wintersteiger** [comment]
That was way off indeed. The problem was in my fix for the recent issue with fp.isSubnormal, resulting in uninitialized variables and assertion failures in debug mode, but now there's a fix for the fix.
