### ISSUE TITLE
Z3 Java application SegFaults on Alpine Linux

### ISSUE THREAD

**Issue by mpahrens** [Z3Prover/z3#1702]
Occuring on Alpine-3.8.0_rc8

Steps to reproduce:
- install necessary build tools (gcc,g++,clang,python,libstdc++,build-base,etc, openjdk8)
- grab and unpack a stable release package of z3 (I tried both 4.7.1 and 4.6.0)
- in the z3 directory `python scripts/mk_make.py --java && make && make install` successfully
- from the build directory, `javac -cp ".:com.microsoft.z3.jar" Test.java` the following program:

<pre><code>
import com.microsoft.z3.*;
public class Test {
  public static void main(String[] args){
     Context ctx = new Context();
     BoolExpr b = ctx.mkBoolConst("hello");
     Solver solver = ctx.mkSolver()
     solver.add(b);
     if(Status.SATISFIABLE == solver.check()){
       System.out.println(solver.getModel().toString());
     }
   }
}
</code></pre>
- java -cp ".:com.microsoft.z3.jar" Test

Expected results: Prints out the model where hello => true
Current Results: 
<pre>
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x000066614dc1d14d, pid=13471, tid=0x00006661d0049ae8
#
# JRE version: OpenJDK Runtime Environment (8.0_171-b11) (build 1.8.0_171-b11)
# Java VM: OpenJDK 64-Bit Server VM (25.171-b11 mixed mode linux-amd64 compressed oops)
# Derivative: IcedTea 3.8.0
# Distribution: Custom build (Wed Jun 13 18:00:32 UTC 2018)
# Problematic frame:
# C  [libgomp.so.1+0x814d]  omp_set_nested+0xf
#
# Core dump written. Default location: /root/z3-z3-4.6.0/build/core or core.13471
#
# An error report file with more information is saved as:
# /root/z3-z3-4.6.0/build/hs_err_pid13471.log
#
# If you would like to submit a bug report, please include
# instructions on how to reproduce the bug and visit:
#   http://icedtea.classpath.org/bugzilla
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
Segmentation fault (core dumped)

</pre>

setting the ulimit to be unlimited and allocating more stack memory to java with -Xss# does not alleviate this issue.

Please find attached my trace.
[hs_err_pid13530.log](https://github.com/Z3Prover/z3/files/2133649/hs_err_pid13530.log)

Any thoughts are appreciated it. I understand there is an up to date alpine package in the alpine package manager, but it does not have the libz3java.so library, thus why I am building from source.

Thanks!

**Comment by mpahrens** [comment]
As extra information, the z3 binary that gets built works fine on the equivalent hello world example:
<pre><code>
(declare-const a Int)
(declare-fun f (Int Bool) Int)
(assert (> a 10))
(assert (< (f a true) 100))
(check-sat)
(get-model)
</code></pre>

**Comment by NikolajBjorner** [comment]
Is this specific to Alpine Linux? Our build machines automatically test various OS/compiler configurations, including running our Java examples.

**Comment by mpahrens** [comment]
I have not tested the same build process on another os, but I know the prebuild windows and ubuntu binaries in the releases works fine on this example. 

I was going to try building from source on ubuntu today and see if it my error or something else. 

I just was wondering if anyone else has tried building and running the java interface on alpine and got this result or knows a workaround. My educated guess from looking at the strace is that is is a bug in the alpine version of libstdc++, but then I don't know why the z3 binary I built -- presumably calling the same libz3.so --  isn't having the same error. (unless the error is in libz3java.so calling libgomp.so, etc).

**Comment by NikolajBjorner** [comment]
It is very possible it is outside of Z3, if not a build configuration issue. 
From what I can glean, it is possible to create a Travis CI target for Alpine Linux and in this way systematically test Z3 builds on Alpine. Of course, the other way around, testing Alpine by compiling and running applications, such as Z3 (it wouldn't be the first time Z3 is used as a test :-)).
 I can't help with setting up these builds (as I remain totally incompetent in such things), but will take reasonable pull requests.

**Comment by mpahrens** [comment]
Ok, feel free to close this issue or wait until I make a PR for a Travis CI target for alpine. I think I can do that, but it might take me a little bit

**Comment by mpahrens** [comment]
I was able to get the build to succeed by using the cmake instructions and turning off OpenMP and GMP via the cmake flags. I'll close this ticket as that is a good workaround for now, and will follow up with OpenMP and GMP maintainers (libstdc++?) for alpine.

Thanks!
