### ISSUE TITLE
Fixedpoint engine (for Datalog) returns incorrect results

### ISSUE THREAD

**Issue by XujieSi** [Z3Prover/z3#1703]
The fixedpoint engine returns incorrect results for the following datalog program:

```
Z 16

Input(t:Z, s:Z, c:Z) input
invent_1(t:Z, c:Z) printtuples
Output(t:Z, c:Z, c:Z) printtuples

invent_1(v0, v4) :- Input(v0, v1, v2), Input(v3, v1, v4).
Output(v0, v1, v2) :- invent_1(v0, v1), invent_1(v0, v2).

Input("a","active",1).
```
There should be only one tuple dervied for relation `invent_1` and `Output`.
However, fixedpoint engine derives 16 tuples for `Output`. 

[buggy.datalog.txt](https://github.com/Z3Prover/z3/files/2135281/buggy.datalog.txt)

**Comment by NikolajBjorner** [comment]
This was tricky. A fix should be available with 5762be2a0fc3f96ea472e0fbba2235347be850f1.
