### ISSUE TITLE
Can i set default return  string ?

### ISSUE THREAD

**Issue by popoaichuiniu** [Z3Prover/z3#1704]
for example:
(declare-const x String)
(declare-const y String)
(assert (= x  "ttt"))
(assert (not (= y  "aaa")))
(check-sat)
(get-model)

this input, z3 will return y=!0! or other string  in input code in some situation.
So can i set any default  return string

**Comment by NikolajBjorner** [comment]
Currently not available. Is there a good use case for this? If you feel the urge to add a pull request with a suggested approach, you are welcome.

**Comment by popoaichuiniu** [comment]
because i can't know that it is a certain value or a casual value.

**Comment by LeventErkok** [comment]
@popoaichuiniu 

You can use soft-assertions to deal with this scenario:

```
(declare-const x String)
(declare-const y String)
(assert (= x "ttt"))
(assert (not (= y "aaa")))

(assert-soft (= x "default_x"))
(assert-soft (= y "default_y"))

(check-sat)
(get-value (x y))
```

This prints:

```
sat
((x "ttt")
 (y "default_y"))
```

**Comment by popoaichuiniu** [comment]
@LeventErkok  Thank you very much
