### ISSUE TITLE
Interpolation - unsupported proof rule - not-or-elim

### ISSUE THREAD

**Issue by Heizmann** [Z3Prover/z3#171]
While executing z3 eeef4d2 on the following script,

    (set-option :produce-interpolants true)
    (set-logic AUFLIRA)
    (push 1)
    (declare-fun unseeded_-1 () Bool)
    (declare-fun oldRank0_-1 () Int)
    (declare-fun |old(oldRank0)_-1| () Int)
    (declare-fun |old(unseeded)_-1| () Bool)
    (declare-fun main_~y~2_-1 () Int)
    (declare-fun main_~x~2_-1 () Int)
    (declare-fun main_~x~2_0 () Int)
    (assert (! (and (>= oldRank0_-1 (+ (* 2 main_~x~2_-1) 1)) (>= (+ main_~y~2_-1 (- 1)) 0)) :named ssa_precond))
    (assert (! (not (and (>= (+ main_~y~2_-1 (- 1)) 0) (or unseeded_-1 (and (> oldRank0_-1 (+ (* 2 main_~x~2_0) 1)) (>= oldRank0_-1 0))))) :named ssa_postcond))
    (assert (! (and (>= main_~x~2_-1 0) (= main_~x~2_0 (- main_~x~2_-1 main_~y~2_-1))) :named ssa_0))
    (check-sat)
    (get-interpolant (and ssa_0 ssa_precond ssa_postcond))
    (pop 1)
    (exit)
I obtain the following output.

    unsat
    (0) |- ~[118]  {1,1}
    |------ not-or-elim
    |- ~[115]  {1,1}
    z3: ../src/interp/iz3translate.cpp:2020: iz3proof_itp::node iz3translation_full::translate_main(iz3mgr::ast, bool): Assertion `0 && "translate_main: unsupported proof rule"' failed.
    Aborted

**Comment by kenmcmil** [comment]
fixed in unstable
