### ISSUE TITLE
Null constant of given sort

### ISSUE THREAD

**Issue by ionuttamas** [Z3Prover/z3#1714]
I was wondering if there is a way to declare a "null" constant for string or a custom sort type.

**Comment by ionuttamas** [comment]
I see; but for custom defined datatypes, like:

```
public class Customer 
{
    public int Age {get; set;}
    public string Name {get; set;}
}

(declare-datatypes () ((Customer (Age int) (Name string))))
```
1. then Customer somehow equivalent to set { (Age of int), (Name of string)}?
2. isn't it possible to define null of Customer set then?  Or can I specify somehow a null marker in Customer constructor?

**Comment by NikolajBjorner** [comment]
You can

       (declare-datatypes () ((Customer (Age int) (Name string) (Null))))
   
See http://smtlib.cs.uiowa.edu/papers/smt-lib-reference-v2.6-r2017-07-18.pdf page 61 for more examples.
