### ISSUE TITLE
JavaExample: ArrayExample1 fails with "Argument was not an array constant"

### ISSUE THREAD

**Issue by rHermes** [Z3Prover/z3#1717]
I don't know what could cause this, as I've just started looking around at the Java API.
## Reproduction
```shell
git clone https://github.com/Z3Prover/z3
cd z3
python scripts/mk_make.py --java
cd build
make
make examples
LD_LIBRARY_PATH=. java -cp com.microsoft.z3.jar:. JavaExample
````
## Expected
For all the tests to pass and for a normal exit.

## Actual
The program hits an exception when it hits line 389, which is in ArrayExample1.

The last lines of the output:
```
Status: SATISFIABLE
Model = (define-fun x () Int
  7719)
(define-fun MyArray () (Array Int (_ BitVec 32))
  (lambda ((x!1 Int)) #x0000002a))
(define-fun f ((x!0 Int)) Int
  (- 7596))
Z3 Managed Exception: Argument was not an array constant
Stack trace: 
com.microsoft.z3.Z3Exception: Argument was not an array constant
	at com.microsoft.z3.Model.getFuncInterp(Model.java:95)
	at JavaExample.arrayExample1(JavaExample.java:389)
	at JavaExample.main(JavaExample.java:2292)
```

## Version
Z3 [version 4.8.0 - 64 bit]

**Comment by NikolajBjorner** [comment]
this one was a recent regression. The java example seems not built by any of our environments and other bit-rot materialized. This is fixed now.
