### ISSUE TITLE
Array datasort declaration API in C#

### ISSUE THREAD

**Issue by ionuttamas** [Z3Prover/z3#1720]
Given that I have custom defined data type (let's say Customer) I want to define the following array data type:

`Customers[]`.

Looking at the C# API:

`var customerArraySort = context.MkArraySort(<domain>, <range>);`

1. What does <domain> and <range> mean?
2. Would the following achieve my goal?

`var customerArraySort  = context.MkArraySort(customerSort, context.IntSort);`

**Comment by NikolajBjorner** [comment]
1. "and" means conjunction. When you say "x and y", then you mean that both x and y are true.
2. Perhaps you want the declaration to have context.IntSort in the domain, and customerSort in the range. You are indexing with integers and the contents is a Customers or customerSort.

**Comment by ionuttamas** [comment]
I see: so `domain `is the indexer type (IntSort in this case) and `range` is the element type stored (CustomerSort)
