### ISSUE TITLE
Z3 crashes on simple input (strings)

### ISSUE THREAD

**Issue by migimunz** [Z3Prover/z3#1725]
Hi,

The following input causes the master version of Z3 crash with a segfault:
```
(set-logic QF_S)
(declare-const x String)
(assert (str.contains (str.++ x "T1WT1t") "GWWT1W"))
(check-sat)
```
Not sure if related to #1718 or not.

**Comment by NikolajBjorner** [comment]
@trinhmt could you code review change and address the comment that precedes the code? The comment seems not to match what the code does and I tried to reproduce the spec based on what the code is almost doing.
