### ISSUE TITLE
Inconsistency between Z3 string solver and Z3Str3

### ISSUE THREAD

**Issue by migimunz** [Z3Prover/z3#1726]
Hi,

There's a strange inconsistency where the z3 string solver (correctly) solves an input as `sat`, but the z3str3 solver solves it as `unsat`. Here's a minimal example:
```
(set-logic QF_S)
(declare-const s String)
(assert (= -1 (str.indexof s s 5)))
(check-sat)
```
According to z3str3 documentation, `str.indexof` should simplify to `-1` and produce a sat answer.

**Comment by NikolajBjorner** [comment]
@mtrberzi could you check? A solution is s = "".

Note also that (simplify (str.indexof "" "" 5)) produces -1

**Comment by mtrberzi** [comment]
Thanks - taking a look.

**Comment by mtrberzi** [comment]
Looks like we are getting into a state where a conflict clause has justification `(not (str.contains s s))`. Obviously bogus, this is probably the result of a bad assumption while generating side conditions for the indexof check. Hoping to have this narrowed down quickly.

**Comment by mtrberzi** [comment]
Opened #1728

**Comment by mtrberzi** [comment]
Opened #1796 which should address this in a better way

**Comment by NikolajBjorner** [comment]
Is this fixed with the latest pull?

**Comment by mtrberzi** [comment]
Yes, I've tested the latest pull and both solvers now correctly report SAT with a valid model.
