### ISSUE TITLE
Side effects: can they be removed?

### ISSUE THREAD

**Issue by pjljvandelaar** [Z3Prover/z3#1734]
We use problem solvers to handle constraints our users add in their test models.
On top of that we add randomization since in tests we want to vary the input as much as possible.

We however noticed that some numbers are hardly chosen. Why? 
Before trying to randomize we ask the problem solver: does a solution exists with another value?
Since if another solution does not exists, trying to find a random solution is a waste of time.

Based on our experience I generated the follow smt2 input that show two issues we experienced:
```
(get-info :name)
(get-info :version)
(set-option :produce-models true)
(set-logic ALL)
(set-info :smt-lib-version 2.5)

(define-fun
    f1044$validInt ( (x$$1045 Int) ) Bool
    (and (<= 0 x$$1045) (<= 0 (+ 10 (- x$$1045))))
)
(push 1)
(declare-fun $In$1050$0$1$() Int)
(assert (f1044$validInt $In$1050$0$1$))
(check-sat)
(get-value ($In$1050$0$1$))

(push 1)
(assert (and (not (<= 0 (+ (- 2) (- $In$1050$0$1$)))) (<= 0 (+ 4 (- $In$1050$0$1$)))))
(check-sat)
(get-value ($In$1050$0$1$))
(pop 1)

(push 1)
(assert (not (= 0 $In$1050$0$1$)))
(check-sat)
(pop 1)

(push 1)
(assert (and (not (<= 0 (+ (- 2) (- $In$1050$0$1$)))) (<= 0 (+ 4 (- $In$1050$0$1$)))))
(check-sat)
(get-value ($In$1050$0$1$))
(pop 1)

(push 1)
(assert (and (not (<= 0 (+ (- 2) (- $In$1050$0$1$)))) (<= $In$1050$0$1$ 0)))
(check-sat)
(get-value ($In$1050$0$1$))
(pop 1)
(pop 1)
```

And we get the answers:
```
C:\experiments> z3 .\distributionPushPop.smt2
(:name "Z3")
(:version "4.8.0 - build hashcode a12af4a619a0")
sat
(($In$1050$0$1$ 0))
sat
(($In$1050$0$1$ 0))
sat
sat
(($In$1050$0$1$ 1))
sat
(($In$1050$0$1$ 0))
```

In other words:
```
(push 1)
(assert (not (= 0 $In$1050$0$1$)))
(check-sat)
(pop 1)
```
has a side effect on the later statement (yet since it is popped we had not expected this!)

Although the answer is correct, and no bug is present (see the last test that 0 is indeed also valid),
we wonder whether it is possible to remove this undesired side effect?

For your information: this behavior is also observed in cvc4. However, Yices does exhibit the desired behavior so it seems possible.

Furthermore, we experienced that out commenting the first push (and last pop) results in:
```
 C:\experiments> z3 .\distributionPushPop.smt2
(:name "Z3")
(:version "4.8.0 - build hashcode a12af4a619a0")
sat
(($In$1050$0$1$ 10))
sat
(($In$1050$0$1$ 0))
sat
sat
(($In$1050$0$1$ 1))
sat
(($In$1050$0$1$ 0)) 
```
Also here we had not expected any effect of encapsulating our statements in a push/pop environment.
We are aware that the answer is correct, but we are surprise that seemingly unrelated statements can cause a change in the given answer.
Both Yices and CVC4 do not show this behavior. So our question: can the side effect of inserting statements with a push/pop environment be removed from Z3?

**Comment by NikolajBjorner** [comment]
It will be too brittle to bake in such assumptions either within a solver or outside.
The set of learned clauses, the state of the data-structures that maintain terms, can be expected to be updated unless you adapt a systematic copy-on-write discipline (e.g., use pure data-structures, which haven't been mainstream in SMT since ICS). Is it possible that even CVC4 and Yices will eventually show something different, but the test you used wasn't exercising all state change features?
For Z3 it will not be possible to ensure state purity after a pop. It was not a design goal. 
The ability to maintain underspecified, but deterministic (unless using timeouts)  solver behavior. is on the other hand a goal.

**Comment by pjljvandelaar** [comment]
Thanks for you information. I understand that Z3 is designed with other goals in mind.
