### ISSUE TITLE
Z3 failed with error C4716 when build with MSVC

### ISSUE THREAD

**Issue by shanshan0309** [Z3Prover/z3#1739]
Hi All,

I tried to build Z3 with VS2017 Update 7 on Windows. It failed to build due to the error C4716: <func:#485 "?is_trace_enabled@@YA_NPBD@Z"> 'is_trace_enabled': must return a value. This issue can be reproduced from master revision fd75ecc. Could you please help take a look at this? Thanks!

**Steps to reproduce the behavior:**
1. Open VS2017 x86 Native tools command tool
2. git clone https://github.com/Z3Prover/z3 D:\Z3\src
3. cd D:\Z3
4. mkdir build_x86 && pushd build_x86
5. cmake -G "Visual Studio 15 2017" -DCMAKE_SYSTEM_VERSION=10.0.17134.0 ..\src
6. msbuild build_x86\Z3.sln /p:Configuration=Release;Platform=Win32 /t:Rebuild /m /p:BuildInParallel=true

**Error info:**
The whole log please see attachment.
[Z3_x86_build.log](https://github.com/Z3Prover/z3/files/2175212/Z3_x86_build.log)
d:\z3\src\src\util\trace.h(54) : error C4716: <func:#485 "?is_trace_enabled@@YA_NPBD@Z"> 'is_trace_enabled': must return a value

Thanks,
Shanshan

**Comment by NikolajBjorner** [comment]
Fixed with #1740

**Comment by shanshan0309** [comment]
Thank you @NikolajBjorner. Z3 works well now.
