### ISSUE TITLE
feature request: declarations in  `Z3_solver_to_string`

### ISSUE THREAD

**Issue by cheshire** [Z3Prover/z3#174]
Hi All,

I really like `Z3_optimize_to_string` function, as it drops the entire problem in SMT-lib compatible way, so that it can be directly loaded into the solver.
Recently I have discovered that `Z3_solver_to_string` behaves in a slightly different fashion: unlike `Z3_optimize_to_string` it does not dump the entire problem: namely, it does not print definitions and sorts of the participating variables.

I agree that this information is technically redundant, but to be able to get a full problem with one API call makes a tremendous difference in convenience.
Thus I would be glad if `Z3_solver_to_string` would also output the whole problem, including variables sorts.
It would also make it more consistent.

**Comment by wintersteiger** [comment]
That sounds like a good suggestion to me, we should add that to Z3_goal_to_string as well as Z3_solver_to_string, possibly guarded by an option so as not to upset existing processes. Are there any opinions against this?

**Comment by NikolajBjorner** [comment]
I will add this.

**Comment by wintersteiger** [comment]
Great! Thanks for avoiding a potential collision :-)

**Comment by NikolajBjorner** [comment]
Feature added for solver: https://github.com/Z3Prover/z3/commit/c7649088e72a9b69ee449459d5bb4c3f80f16bc8
