### ISSUE TITLE
Get assertions of Optimize in Java Api

### ISSUE THREAD

**Issue by Koelbl** [Z3Prover/z3#1741]
Hello,
I parse the example below with an object opt of Optimize in Z3 Java API and the example also works with opt.check(). Now I need to traverse the assertions to get the variables names x and y used by assert-soft, but I don't find a possibility to do so. With the Python API, it seems to be done by the function Z3_optimize_get_assertions, but this function is missing in the Java API

Example:
"(declare-const x Bool)
(declare-const y Bool)
(assert (xor x y))
(assert-soft (= x true))
(assert-soft (= y true))"

Thanks for your help.
Bye

**Comment by yujboss** [comment]
Hello,
But this current update only returns hard constraints, how can we get also the soft ones?

**Comment by NikolajBjorner** [comment]
Soft assertions are returned as objectives.
