### ISSUE TITLE
"logic does not support uninterpreted functions"-error when using algebraic datatypes.

### ISSUE THREAD

**Issue by bj2015** [Z3Prover/z3#1745]
I played around with algebraic datatypes and was a bit puzzled when Z3 answered

`(error "line 9 column 30: logic does not support uninterpreted functions")`

to the SMTLIB snippet below as I cannot find any uninterpreted functions in it...

```
(set-option :print-success true)
(set-option :produce-models true)
(set-option :produce-unsat-cores true)

(set-logic QF_NIA)

(declare-datatypes ( (Option  1) ) ((par (X) ( (none) (some (val X)) ))))

(declare-const x (Option Int))
```

I ran it with `z3 -smt2 snippet.smt2` and I am using `Z3 version 4.6.0 - 64 bit` on `MacOS Sierra Version 10.12.6 (16G1212)`.

**Comment by NikolajBjorner** [comment]
The QF_NIA logic is specified here http://smtlib.cs.uiowa.edu/logics-all.shtml#QF_NIA
It does not contain symbols for algebraic datatypes. Z3 disables theories that are not part of the logics specified by the set-logic command. You can just remove the set-logic command.

**Comment by bj2015** [comment]
I see. So algebraic datatypes need uninterpreted functions for some reason, right?
