### ISSUE TITLE
Z3 failed when build with permissive- + MSVC on windows

### ISSUE THREAD

**Issue by QuellaZhang** [Z3Prover/z3#1752]
Build Z3 with permissive- by msvc failed with error C2589, this issue can be reproduced from master revision 30a30e7. Could you please help take a look at this?
 
**Repro:**
 1.Open VS2017 x86 Native tools command tool
 2.git clone https://github.com/Z3Prover/z3 D:\Z3\src
 3.cd D:\Z3
 4.mkdir build_x86 && pushd build_x86
 5.cmake -G "Visual Studio 15 2017" -DCMAKE_SYSTEM_VERSION=10.0.17134.0 ..\src
 6.msbuild build_x86\Z3.sln /p:Configuration=Release;Platform=Win32 /t:Rebuild /m /p:BuildInParallel=true

**Failures:**
d:\z3\src\src\util\mpz.h(156): error C2589: '(': illegal token on right side of '::'
d:\z3\src\src\util\mpz.h(693): note: see reference to class template instantiation 'mpz_manager<SYNCH>' being compiled

**Comment by NikolajBjorner** [comment]
This doesn't repro for me. 
Can you perhaps trace down the root-cause why std::max isn't accepted?

**Comment by NikolajBjorner** [comment]
OK, seems like a clue. Perhaps the right way for Z3 then is to include <climits> instead ,of <limits.h>.

**Comment by NikolajBjorner** [comment]
Can you try the latest update https://github.com/Z3Prover/z3/commit/6bacf09447c7cb0b65848cca2c85677ce53c6012?
I changed some include files from <limits.h> to <climits> which I suspect were the cause. 
calling #undef max does appear to be a good solution (it is a workaround of something else).

**Comment by QuellaZhang** [comment]
Leave a comment @NikolajBjorner

**Comment by QuellaZhang** [comment]
@NikolajBjorner Thank you very much!
I use version 6bacf09 and latest version 124e963 of Z3, this issue can still be repro, the failure is as follows. And I update the repro steps, maybe you can have a try.

**Failure:**
c1xx: warning C4199: two-phase name lookup is not supported for C++/CLI, C++/CX, or OpenMP; use /Zc:twoPhase-
d:\z3\src\src\util\mpz.h(155,18): error C2589: '(': illegal token on right side of '::'
        c = std::max(c, m_init_cell_capacity);
                 ^
d:\z3\src\src\util\mpz.h(692): note: see reference to class template instantiation 'mpz_manager<SYNCH>' being compiled
};

**Comment by QuellaZhang** [comment]
Thank you very much! Z3 works well now. @NikolajBjorner

**Comment by NikolajBjorner** [comment]
Good!
