### ISSUE TITLE
SMTLib compliance: divisible predicate is missing

### ISSUE THREAD

**Issue by LeventErkok** [Z3Prover/z3#1757]
SMTLib Int theory specifies the `divisible` predicate: http://smtlib.cs.uiowa.edu/theories-Ints.shtml

>   All ranked function symbols of the form
>     ((_ divisible n) Int Bool)
>   where n is a positive numeral.

I don't seem to be able to get the following benchmark to be accepted by z3:

```
(set-logic ALL)

(assert ((_ divisible 2) 6))
(check-sat)
```

I tried giving no `set-logic` at all, along with `ALL`,  `LIA`, `QF_LIA`, `QF_NIRA`, but in all cases z3 said:

```
(error "line 3 column 26: invalid use of indexed indentifier, unknown builtin function divisible")
```

I can't believe nobody complained about this before, so I'm wondering if I'm missing something obvious.

Also,  the word `identifier` is misspelt in a couple of places:

   https://github.com/Z3Prover/z3/blob/master/src/cmd_context/cmd_context.cpp#L1066

and:

   https://github.com/Z3Prover/z3/blob/master/src/math/subpaving/subpaving_t.h#L205

**Comment by NikolajBjorner** [comment]
you are the first one to ask for this. I don't recall this operator from previous versions of SMT-LIB. It is redundant because there is already mod. so you write (= (s mod 6) 0).

**Comment by NikolajBjorner** [comment]
Fixed with https://github.com/Z3Prover/z3/commit/6bacf09447c7cb0b65848cca2c85677ce53c6012

**Comment by LeventErkok** [comment]
@NikolajBjorner 

Unfortunately this is still non-compliant due to https://github.com/Z3Prover/z3/commit/42d30e3eddcfff602da327db907fe3dc699c78d5

If I may suggest a solution: If the user explicitly states compliance, then z3 should provide the `divisible` predicate. That is, if the script contains:

    (set-option :smtlib2_compliant true) 

then `divisible` should be available. I'm guessing the broken benchmarks don't set this attribute, and if they do, they should really not define `divisible` anyhow.

I'd be willing to implement this in a pull request to get myself acclimated with the code base if desired.

**Comment by dio4ev** [comment]
Is there any detailed information about what changes to Z3 `(set-option :smtlib2_compliant true)` triggers?
