### ISSUE TITLE
Using Optimizer in Java API

### ISSUE THREAD

**Issue by efeg** [Z3Prover/z3#176]
I am interested in using z3 for pareto optimization via Java API. The constructor of z3/src/api/java/Optimize.java class is not public so I cannot create an object of type Optimize -- i.e. Optimize opt = new Optimize(ctx);

Since there is no tutorial/documentation other than the API documentation within the repository, I cannot confirm if I am missing something. I assumed that the Java API is similar to the Python API as exemplified in the paper http://research.microsoft.com/en-US/people/nbjorner/nuz.pdf in Section 1.3.

**Comment by NikolajBjorner** [comment]
It's a bug. The Context object should contain a method called mkOptimize similar to the .NET version.

**Comment by efeg** [comment]
Thanks a lot for the quick response!
Do you think a quick fix for this would be ready soon? Should I wait or use another API?

**Comment by NikolajBjorner** [comment]
I will fix it now, but you can also add the simple fix to Context.java next to mkFixedpoint method and recompile.
