### ISSUE TITLE
How to use the class optimize of Z3? Are there any documents?

### ISSUE THREAD

**Issue by qtangandy** [Z3Prover/z3#1760]
I'd like to use the C++ api of Z3 to solve an ILP problem, e.g., for two positive integers a and c, a<=50, c<=60, a+2c<=120, I want to maximize 2*a+3*c. How to model this problem in Z3? 

Thanks.

**Comment by NikolajBjorner** [comment]
see the opt example in https://github.com/Z3Prover/z3/blob/master/examples/c%2B%2B/example.cpp
