### ISSUE TITLE
Link http://rise4fun.com/Z3Py/tutorial/advanced in python binding docs broken

### ISSUE THREAD

**Issue by yxliang01** [Z3Prover/z3#1762]
In the documentation of the python binding (e.g. `Exists` function), there are many places referring http://rise4fun.com/Z3Py/tutorial/advanced . However, it's not accessible showing message "Oops,
Something failed on the server." (Looks like HTTP 404).

**Comment by yxliang01** [comment]
@NikolajBjorner I can see that in d74978c , you removed all such links. Are they simply not existent? Or, are they storing elsewhere? Because I feel like these functions should really have more documentation to be understood by new API users.

**Comment by NikolajBjorner** [comment]
The link is gone. We would have to update the documentation in a different way.
