### ISSUE TITLE
Strange behavior maybe related to rationals

### ISSUE THREAD

**Issue by rixed** [Z3Prover/z3#1763]
Looking at the VMs scheduling problems in https://rise4fun.com/Z3/tutorialcontent/optimization#h25
and more specifically at the integer encoded version, I though that this:

```smt
(assert (<= (+ (* 100 x11) (* 50 x21) (* 15 x31)) (* 100 y1)))
(assert (<= (+ (* 100 x12) (* 50 x22) (* 15 x32)) (* 75 y2)))
(assert (<= (+ (* 100 x13) (* 50 x23) (* 15 x33)) (* 200 y3)))
```

could as well have been written:

```smt
(assert (<= (+ (* 100 x11) (* 50 x21) (* 15 x31)) 100))
(assert (<= (+ (* 100 x12) (* 50 x22) (* 15 x32)) 75))
(assert (<= (+ (* 100 x13) (* 50 x23) (* 15 x33)) 200))
```

since `y{1,2,3}` will be either 0 or 1.

The result (on mater branch at 8744c62fca91dddc) is:

```
sat
(model 
  (define-fun y1 () Int
    0)
  (define-fun x13 () Int
    0)
  (define-fun x23 () Int
    0)
  (define-fun x33 () Int
    0)
  (define-fun y3 () Int
    0)
  (define-fun x12 () Int
    0)
  (define-fun y2 () Int
    0)
  (define-fun x32 () Int
    0)
  (define-fun x22 () Int
    0)
  (define-fun x31 () Int
    1)
  (define-fun x21 () Int
    1)
  (define-fun x11 () Int
    1)
)
(objectives
 ((+ y1 y2 y3) 1)
 ((+ (* 10 y1) (* 5 y2) (* 20 y3)) (/ 460.0 33.0))
)
```

Which seems to violates `(assert (and (>= y1 x11) (>= y1 x21) (>= y1 x31)))` but the result of the `((+ (* 10 y1) (* 5 y2) (* 20 y3))` objective seems to suggest there is more to `y{1,2,3}` value than what's in the model.

Is this normal and am I merely (or ignorant not_awake stupid) ?

**Comment by NikolajBjorner** [comment]
Thanks, should be fixed by #1771.

**Comment by rixed** [comment]
It is indeed.

**Comment by NikolajBjorner** [comment]
FWIW, it is a fairly recent regression due to significant overhaul of the ILP solver.
