### ISSUE TITLE
Sementation fault

### ISSUE THREAD

**Issue by Heizmann** [Z3Prover/z3#1768]
When I run Z3 (without additional arguments) on the attached file I get a `Segmentation fault` after the last SMT command in the script (which is `(pop 1)`).

I compiled the latest checkout of the master branch 01b5db63e6b869fb714c0e4fdf5d82b4efeebdd7 with gcc 7.3.0.

[Peterson.smt2.txt](https://github.com/Z3Prover/z3/files/2216559/Peterson.smt2.txt)

**Comment by NikolajBjorner** [comment]
thanks, this will be fixed in next push

**Comment by NikolajBjorner** [comment]
fixed
