### ISSUE TITLE
AUFLIRA and SMTLIB2_COMPLIANT=true

### ISSUE THREAD

**Issue by Heizmann** [Z3Prover/z3#177]
Executing z3 52de96fcfc92bba72ef82f088a2a18f3855da588 with the argument **SMTLIB2_COMPLIANT=true** gives the wrong result on the following SMT script

    (set-logic AUFLIRA)
    (push 1)
    (declare-fun main_a_const_-1079096603 () Real)
    (declare-fun main_q_const_-1079096619 () Real)
    (declare-fun main_b_const_-1079096606 () Real)
    (assert (let ((main_a main_a_const_-1079096603) (main_q main_q_const_-1079096619) (main_b main_b_const_-1079096606)) (not (= (> (+ (* (- 64) main_a) (* 640 main_q) (* (- 128) main_b) 52) 0) (< (+ (* 64.0 main_a) (* 128.0 main_b)) (+ (* 640.0 main_q) 52.0))))))
    (check-sat)
    (pop 1)
    (exit)

Z3 says *sat* although *unsat* is correct. If I drop the argument SMTLIB2_COMPLIANT=true of change the logic (e.g., to QF_LRA) I obtain the correct result.

**Comment by NikolajBjorner** [comment]
thanks, of course you/we could dump -128 and -64 to workaround but I take one would expect unknown based on the warning.

**Comment by wintersteiger** [comment]
Has this been changed/fixed or is it still in discussion?

**Comment by NikolajBjorner** [comment]
This is what Z3 produces:

       (error "line 6 column 259: logic does not support nonlinear arithmetic") 
       sat

what happens is that "(* (- 64) main_a)", for instance, is recognized as non-linear because the SMTLIB definition does not recognize that (- 64) should be read as a constant -64.

The assertion is dropped and Z3 checks satisfiability of an empty set of assertions.
