### ISSUE TITLE
z3 (python) issues misleading error when import libz3.so

### ISSUE THREAD

**Issue by typon** [Z3Prover/z3#1770]
I'm trying to use z3 on my machine using python package (https://pypi.org/project/z3-solver/). 

During the import process, the code checks to see the existence of libz3.so in several locations, and if the call to ctypes.DLL fails, issues an error saying libz3.so not found. Even though the import failed, libz3.so not found may not be the actual reason.

In my case, the actual error is:

```python
import ctypes
ctypes.CDLL('~/libz3.so')                                                                           
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "lib/python2.7/ctypes/__init__.py", line 362, in __init__                                                                  
    self._handle = _dlopen(self._name, mode)
OSError: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by ~/libz3.so)
```
The relevant code doing the import is in z3core.py:

```python
for d in _all_dirs:
  try:
    d = os.path.realpath(d)
    if os.path.isdir(d):
      d = os.path.join(d, 'libz3.%s' % _ext)
      if os.path.isfile(d):
        _lib = ctypes.CDLL(d)
        break
  except:
    # Maybe add  traceback.print_exc()
    pass
```

It might be useful to print a traceback here unless the exception that was raised is specifically about FileNotFound (which actually has a nice error message suggesting which environment variables to modify)

**Comment by NikolajBjorner** [comment]
Could you do a favor an let me know how something along the lines of could help:

     _failures = []
     for d in _all_dirs:
       try:
         d = os.path.realpath(d)
         if os.path.isdir(d):
           d = os.path.join(d, 'libz3.%s' % _ext)
          if os.path.isfile(d):
            _lib = ctypes.CDLL(d)
            break
      except e:
        _failures += [e]
        pass

    if _lib is None:
      # If all else failed, ask the system to find it.
      try:
        _lib = ctypes.CDLL('libz3.%s' % _ext)
      except e:
        _failures += [e]
        pass

    if _lib is None:
      print(_failures)
      …

with reasonable fixes for pretty printing the failures properly?

**Comment by typon** [comment]
That makes a lot of sense. 

I would probably write:

```python
  except Exception as e:
    _failures += [e]
    pass
```
So you don't end up catching stuff like KeyboardInterrupt

**Comment by NikolajBjorner** [comment]
Added with https://github.com/Z3Prover/z3/commit/6bacf09447c7cb0b65848cca2c85677ce53c6012

**Comment by tamas-visy** [comment]
Hi @NikolajBjorner, I've just encountered an issue very similar to typon's.

Looks like this final section of the fix
```
if _lib is None:
  print(_failures)
  …
```
is missing from the merged pull request https://github.com/Z3Prover/z3/commit/6bacf09447c7cb0b65848cca2c85677ce53c6012 and so the error message is still misleading, hiding the real cause in case of failure.
