### ISSUE TITLE
z3Py generates wrong counterexample (BitVectors)

### ISSUE THREAD

**Issue by 0xpr** [Z3Prover/z3#1772]
```
from z3 import *

def min(x, y):
  if simplify(ULT(x, y)):
    return x
  else:
    return y

def max(x, y): 
  if simplify(ULT(x, y)):
    return y
  else:
    return x

def div(n, k): 
  return simplify(UDiv(n, k)) 


def divide(n, k): 
  l = BitVec('l', 32) 
  m_ = BitVec('m_', 64) 
  one = BitVecVal(1, 64) 
  one32 = BitVecVal(1, 32) 
  zero = BitVecVal(0, 32) 
  q = BitVec('q', 32) 
  t = BitVec('t', 64) 
  sh1 = BitVec('sh1', 32) 
  sh2 = BitVec('sh2', 32) 
  s = Solver() 
  s.add(And(ULE(k, (1 << l)), UGT(k, (1 << (l - 1)))))
  if s.check() == sat:
    m = s.model()
    l = m.evaluate(l)
  m_ =  ((one << 32) * ((one << ZeroExt(32, l)) - ZeroExt(32, k)) / ZeroExt(32, k)) + 1 
  sh1 = min(l, one32)
  sh2 = max(l - one32, zero)
  t = LShR((ZeroExt(32, n) * m_), 32) 
  n64 = ZeroExt(32, n)
  sh164 = ZeroExt(32, sh1)
  sh264 = ZeroExt(32, sh2)
  q = Extract(31, 0, LShR((t + (LShR((n64 - t), sh164))), sh264))
  return simplify(q)

n = BitVec('n', 32) 
k = BitVec('k', 32)

prove(Or(k == 0, div(n, k) == divide(n, k)))

print()

# prove that counterexample is wrong
n_ = BitVecVal(2147483647, 32)
k_ = BitVecVal(536870912, 32)
prove(div(n_,k_) == divide(n_,k_))
```

On my PC it generates the counterexample `n = 2147483647` and `k = 536870912` which when I check by applying `div(n, k)` and `divide(n, k)` ― both functions give the same result. 

I was trying to prove that the optimization described in figure 4.1 of [Division by Invariant Integers using Multiplication](https://gmplib.org/~tege/divcnst-pldi94.pdf) is correct.

**Comment by NikolajBjorner** [comment]
The code:

      s = Solver() 
      s.add(And(ULE(k, (1 << l)), UGT(k, (1 << (l - 1)))))
      if s.check() == sat:
        m = s.model()
        l = m.evaluate(l)


produces different values for l depending on whether you pass the symbolic values or the constant values.

**Comment by NikolajBjorner** [comment]
On another note, for min/max you probably want something along the lines of:

   def min(x, y):
       return If(ULT(x,y),x,y)

    def max(x, y): 
       return If(ULT(x,y),y,x)

**Comment by 0xpr** [comment]
Hi, thanks for the response.

> produces different values for l depending on whether you pass the symbolic values or the constant values.

I'm confused ― are you implying this is the desired behavior? Surely a counterexample generated by `prove` should not satisfy the proof condition?

Also, for a bitvector `d` is there any other way to calculate `ceil(log_2 d)`? (where ceil is the ceiling function and log_2 is the base 2 logarithm).
