### ISSUE TITLE
Wrong results in optimization query using Java API

### ISSUE THREAD

**Issue by JustinHuang402490** [Z3Prover/z3#1783]
Hi, I attempted to find the optimal value of the variable considering some constraints. However, I didn't get the expected results. I am not sure whether there are bugs or I have wrong assumptions about optimizations. There are my questions, codes and temporary solutions as follow:

* Questions for the Myfunction_1.java:
**1-1. Does the opt.Add() assert soft constraints into the optimizing solver?**
The reason I ask the question is that I found the variable a violated its constraint because it should be greater than or equal to 0 instead of -22.
**1-2. Is there a bug in opt.MkMinimize()?**
I found that the variable a in the model is right, but the variable a got from the opt.MkMinimize() is wrong.

* Questions for the Myfunction_2.java:
**2. Why can't I get the expected result with the following query?**
The expected result is a=1, b=0, c=7, but the output of Myfunction_2.java is a=10, b=0, c=4. In addition, the variable a violates its constraint due to a<10.

--------------------------------------------------------------------------------------------
* Myfunction_1.java:
```Java
import com.microsoft.z3.*;
import java.util.HashMap;

public class Myfunction_1{
    public static void main(String[] args) {
        HashMap<String, String> m = new HashMap<String,String>();
        Context ctx = new Context(m);

        IntExpr a = ctx.mkIntConst("a");
        IntExpr b = ctx.mkIntConst("b");
        IntExpr c = ctx.mkIntConst("c");
        Optimize opt = ctx.mkOptimize();
      
        /* let a + 2*b + 3*c = 22 */
        BoolExpr formula = ctx.mkEq(
            ctx.mkAdd(
                ctx.mkMul(a,ctx.mkInt(1)), 
                ctx.mkMul(b,ctx.mkInt(2)), 
                ctx.mkMul(c,ctx.mkInt(3))
                ),
            ctx.mkInt(22)
            );
        System.out.println("formula : " + formula);

        /* constraints definition */
        BoolExpr constraint_1 = ctx.mkGe(a, ctx.mkInt(0));  // a >= 0
        BoolExpr constraint_3 = ctx.mkGe(b, ctx.mkInt(0));  // b >= 0
        BoolExpr constraint_5 = ctx.mkGe(c, ctx.mkInt(0));  // c >= 0
       
        /* add constraints into the optimizing solver */
        opt.Add(
            formula,
            constraint_1,
            constraint_3,
            constraint_5
            );    

        /* the optimize goal */
        Optimize.Handle ma = opt.MkMinimize(a);
        
        if(opt.Check() == Status.SATISFIABLE)
        {
            Model model = opt.getModel();
            System.out.println("model : " + model);
          
            Expr mb = model.eval(b,false); 
            Expr mc = model.eval(c,false);
            
            System.out.println("\nma = " + ma);
            System.out.println("uppera = " + ma.getUpper());
            System.out.println("lowera = " + ma.getLower());

            System.out.println("\nmb = " + mb);
            System.out.println("mc = " + mc);  
        }else
        {
            System.out.println("not satisfiable");
        }      
    }
}
```

* The output of Myfunction_1.java:
![image](https://user-images.githubusercontent.com/41780406/43515437-1881bcb0-95b5-11e8-8165-a9038498d1ec.png)

--------------------------------------------------------------------------------------------
* Myfunction_2.java:
```Java
import com.microsoft.z3.*;
import java.util.HashMap;

public class Myfunction_2{
    public static void main(String[] args) {
        HashMap<String, String> m = new HashMap<String,String>();
        Context ctx = new Context(m);

        IntExpr a = ctx.mkIntConst("a");
        IntExpr b = ctx.mkIntConst("b");
        IntExpr c = ctx.mkIntConst("c");
        Optimize opt = ctx.mkOptimize();
      
        // let a + 2*b + 3*c = 22
        BoolExpr formula = ctx.mkEq(
            ctx.mkAdd(
                ctx.mkMul(a,ctx.mkInt(1)), 
                ctx.mkMul(b,ctx.mkInt(2)), 
                ctx.mkMul(c,ctx.mkInt(3))
                ),
            ctx.mkInt(22)
            );
        System.out.println("formula : " + formula);

        /* constraints definition */
        BoolExpr constraint_1 = ctx.mkGe(a, ctx.mkInt(0));  // a >= 0
        BoolExpr constraint_2 = ctx.mkLt(a, ctx.mkInt(10)); // a < 10
        BoolExpr constraint_3 = ctx.mkGe(b, ctx.mkInt(0));  // b >= 0
        BoolExpr constraint_4 = ctx.mkLt(b, ctx.mkInt(10)); // b < 10
        BoolExpr constraint_5 = ctx.mkGe(c, ctx.mkInt(0));  // c >= 0
        BoolExpr constraint_6 = ctx.mkLt(c, ctx.mkInt(10)); // c < 10
        
        /* add constraints into the optimizing solver */           
        opt.Add(
            formula,
            constraint_1,
            constraint_2,
            constraint_3,
            constraint_4,
            constraint_5,
            constraint_6
            );  
        
         /* the optimize goal */
        Optimize.Handle mc = opt.MkMaximize(c);
        
        if(opt.Check() == Status.SATISFIABLE)
        {
            Model model = opt.getModel();
            System.out.println("model : " + model);

            Expr ma = model.eval(a,false); 
            Expr mb = model.eval(b,false); 
  
            System.out.println("\nma = " + ma);
            System.out.println("\nmb = " + mb);   

            System.out.println("\nmc = " + mc);
            System.out.println("upperc = " + mc.getUpper());
            System.out.println("lowerc = " + mc.getLower());
        }else
        {
            System.out.println("not satisfiable");
        }   
    }
}
```

* The output of Myfunction_2.java:
![image](https://user-images.githubusercontent.com/41780406/43523313-8ec22be4-95ce-11e8-87a5-377d7a7e274a.png)

--------------------------------------------------------------------------------------------
* The temporary solution for the Myfunction_1.java:
**<Solution 1>**.  Multiply each coefficient of the formula by 2 (e.g. 2*a + 4*b + 6*c = 44)
After a lot of tests, I found that if the coefficients of the formula are not equal to 1, then the result will be right. 
The output will be:
![image](https://user-images.githubusercontent.com/41780406/43523218-455c1d52-95ce-11e8-9101-c2c8d8f38d9c.png)

--------------------------------------------------------------------------------------------
* The temporary solution for the Myfunction_2.java:
**<Solution 1>**. Same as the above solution, multiply each coefficient of the formula by 2 (e.g. 2*a + 4*b + 6*c = 44)
The output will be:
![image](https://user-images.githubusercontent.com/41780406/43525498-86e340e2-95d4-11e8-8210-a41a52aeeb89.png)

    **<Solution 2>**. Replace the mkLt with mkLe in constraint_2, constraint_4, and constraint_6. For example, replacing ctx.mkLt(a, ctx.mkInt(10)) with ctx.mkLe(a, ctx.mkInt(9)).
The output will be:
![image](https://user-images.githubusercontent.com/41780406/43524369-b0371d40-95d1-11e8-930d-ecfab6a142ad.png)

    It would be kind of tricky because both of solutions don't change the meaning of constraints. However, the right answer can be got from Z3.

* Conclusion
1. We should avoid any coefficient of the formula is equal to 1.
2. If any coefficient of the formula is equal to 1, we should use mkLe instead of mkLt, or the result in the model would be wrong. Moreover, we should get the result in the model and recompute the optimize goal for verifying.
--------------------------------------------------------------------------------------------
My Z3 version is 4.8.0.0. 
In addition, it is possible that there are same bugs in #1326. Note that the coefficients of the formula in #1326 are equal to 1.
If you are interested in this issue, you are welcome to share your ideas. Thanks!

**Comment by NikolajBjorner** [comment]
It could be that your java bindings are referencing a stale dll. 
I was able to reproduce the bug earlier from the python bindings, and with the fix the bug does not manifest itself.

**Comment by JustinHuang402490** [comment]
Thanks for your quick reply! I reinstall the Open JDK (version 1.8.0_171) and Z3 java bindings (version 4.8.0.0) in Ubuntu Linux 16.04.1 today. After compiling and running example codes, I find the output of Myfunction_1.java is correct! However, the output of Myfunction_2.java is still wrong and same as the figure shown above.

**Comment by JustinHuang402490** [comment]
The output of Myfunction_2.java is correct now. Thanks a lot!

**Comment by NikolajBjorner** [comment]
Thanks for the reports. These were two different root causes.
