### ISSUE TITLE
performance regression 4.7.1 -> 4.8

### ISSUE THREAD

**Issue by DvonHolten** [Z3Prover/z3#1785]
Folks,
i know 4.8 is work-in-progress, but i think any hint to open issues is welcome.
Attached are a small problem-file (z38x8-v30.txt) and the results of running it with 4.7 and the last two nightly builds of 4.8.
Statistics are at end of file.

[res-8x8-v30-v480b.txt](https://github.com/Z3Prover/z3/files/2253689/res-8x8-v30-v480b.txt)
[res-8x8-v30-v471.txt](https://github.com/Z3Prover/z3/files/2253690/res-8x8-v30-v471.txt)
[res-8x8-v30-v480a.txt](https://github.com/Z3Prover/z3/files/2253691/res-8x8-v30-v480a.txt)
[z38x8-v30.txt](https://github.com/Z3Prover/z3/files/2253692/z38x8-v30.txt)

**Comment by NikolajBjorner** [comment]
Regression repros are welcome.
For 4.8 behavior on the small example, seems that (check-sat-using smt), 
instead of (check-sat), bypasses some of the preliminary tactics that are inconclusive. 
Running wih -v:10 shows some information about the tactics that are used.

**Comment by DvonHolten** [comment]
this problem is solved by using check-sat-using. This is indeed an insight - one half of the problem is to find the right way to formulate the problem, the other half is to find the right parameter-mix to get the right performance.
