### ISSUE TITLE
Need explanation of "verbose" output

### ISSUE THREAD

**Issue by 0xpr** [Z3Prover/z3#1787]
While running `prove` with `set_option(verbose = 10)`, I get output like this:

```
(sat-restart :conflicts 5207919 :decisions 10011352 :restarts 539196 :clauses 9202/1595 :learned 84627/381 :units 258 :gc-clause 5106822 :memory 54.29 :time 873.12)
```

I couldn't find documentation on what the numbers mean. I presume it is possible to estimate progress by looking at the verbose output? What can I infer from the above code with respect to progress on the proof?

**Comment by NikolajBjorner** [comment]
:conflicts 5207919 - number of conflicts encountered during search
:decisions 10011352 - number of decisions
:restarts 539196 - number of restarts
:clauses 9202/1595 - overall number of clauses / of which 1595 are binary
:learned 84627/381 - overall number of current learned clauses / of which 381 are binary
:units 258 - unit literals
:gc-clause 5106822 - total accumulated number of clauses garbage collected
:memory 54.29 - current memory overhead
:time 873.12 - yes


progress in SAT is fairly relative. The ratio of decisions to conflicts should decrease. 
The rate of decrease can say something. Z3 does not report this, but you can mine this number from the output. 
The rate of new unit literals also indicates progress, but it can depend on benchmark class.

For fun, you could try parallel.enable=true. Depending on your benchmark class and tactic it may be able to exercise the cube&conquer solver that will produce subgoals with progressively more units.
