### ISSUE TITLE
A tactic for compactly solving multiple assertions

### ISSUE THREAD

**Issue by rainoftime** [Z3Prover/z3#1788]
Consider the following common problem in program analysis and verification:  given a satisfiable formula `P` and a set of formulas `Q1, Q2, ..., Qn`, we need to decide if each `P \land Q` is satisfiable respectively. For examples,

- `P` is an inductive invariant, and `Q1, ..., Qn` are properties to verify;
- `P` is the current state in symbolic execution, and `Q1, ..., Qn` are checker-specific (e.g., overflow , null dereference) constraints 

The problem might be similar to MaxSAT or predicate abstraction, but their goals are different. Is it possible to provide a specialized tactic for soving such problem?

First, a trivial approach is to solve each `P \land Qi` on-by-one, possibly using the incremental solving facility.
~~~~
context ctx;
s = solver(ctx);
s.add(P);
for (unsigned i = 1; i <= n; i++) {
  s.push();
  s.add(Qi);
  auto res_i = s.check();
  s.pop();
}
~~~~
However, there may exist much redundant computation.  We always have to call the sovler for `n` times.

A possible approach for compactly solving them is to use over-approximation and model-based refinement:

1. First check an aggregate constraint `P \land (Q1 \lor ... \lor Qn)`, which can be regarded as an over-approximation of each `P \land Qi`.
2. If the aggregate constraint is UNSAT, then all `P \land Qi` are UNSAT, and we can abort the algorithm.
3. Otherwise, get a model `M` of  `P \land (Q1 \lor ... \lor Qn)`, and test if each `P \land Qi` is satisfied by `M`. Remove the satisfied `Qi` from `(Q1 \lor ... \lor Qn)`
4. Restart from the first step.

At step 3, we can also add blocking clauses to blcok `M`.  With this appraoch, we need to call the solver for at most `min(k, n+1)` times, where `k` is the number of satisfiable constraints among `P \land Qi`.  A major drawback is that the quereis sent to solver might be larger that the previous trivial approach.

@NikolajBjorner Would you please give some suggestions about this?

**Comment by NikolajBjorner** [comment]
I would suggest the last approach without the blocking clauses idea.
You simply assert first Q1 or … or Qn, then filter out the ones that are true in M, 
Suppose for example Q1, Q3 are true in M, and n = 5.
in the next round you assert the "Q2 or Q4 or Q5",
repeat the process until the result is unsat.

There is an internal API on the Solver object, used by SPACER, that allows using temporary clauses.
It is called check_sat_cc.
Besides taking a cube (assumptions), the solver object can take a set of temporary clauses.
The advantage of this API is that the set of learned clauses are not going to be affected
by the temporary clauses. It isn't exposed as it is only partially implemented and it would take more than one use case to expose.
