### ISSUE TITLE
Complete Javascript N-API support for Javascript

### ISSUE THREAD

**Issue by sb98052** [Z3Prover/z3#1791]
#1298 led to work-in-progress N-API bindings. Some work has to be done before these become usable:

- [ ] Complete packaging - calling `make; make install` after `mk_make.py --js` should install the JS bindings as an npm package
- [ ] Add unit tests mirroring other language APIs. Right now, there is a barebones sanity check.
- [ ] Integrate build and unit tests with CI
- [ ] Add an idiomatic API on top of the current thin shim

**Comment by NikolajBjorner** [comment]
no progress on this for a year
