### ISSUE TITLE
Parser error for large numbers

### ISSUE THREAD

**Issue by layderv** [Z3Prover/z3#1793]
This code produces a parser error:

```
from z3 import *
f = 3.00146118189147e+16
s = str(f)
RealVal(s)  # z3.z3types.Z3Exception: parser error
RealVal(f)  # z3.z3types.Z3Exception: parser error
```
Same with `-f`.

It behaves differently with floats and ints:
```
RealVal(30014611818914700)       # ok
RealVal(30014611818914700.0)    # z3.z3types.Z3Exception: parser error
RealVal('30014611818914700.0')  # ok
```

**Comment by ytrezq** [comment]
@NikolajBjorner a question in general, does Z3 supports arbitrary sized integers? For example can I solve equation with 512 bits equivalent literals?

**Comment by NikolajBjorner** [comment]
it can represent arbitrary sized integers, whether you mean Int or BitVec.
Whether it can _solve_ equations involving them is a different question and depends on characteristics of the equations and efficiency of supported procedures.
