### ISSUE TITLE
Has anyone tried building z3 with cuda?

### ISSUE THREAD

**Issue by k53sc** [Z3Prover/z3#1795]
Hello Everyone,

This is more of a curiosity question.

NVIDIA Cuda provides GPU-accelerated Libraries for Computing.
Is there any way we can build z3 with Cuda?

I would like to experiment if CPU intensive z3 operations ( mostly solver check calls ) will be more performant if they are run on a machine with supported CUDA supported NVIDIA Graphics card.

Any thoughts on this?

Thanks,
Ayush

**Comment by NikolajBjorner** [comment]
There is at this point no code calling out to GPU features so you would have to create these links on your own before it makes sense to compile with Cuda in the picture. What algorithms in Z3 should use GPU?

**Comment by NikolajBjorner** [comment]
@k53sc. Based on a SAT only integration, which makes sense, you could try the following: from sat/sat_solver.cpp introduce a CUDA mode where you convert the current set of clauses into the solver of @wellcomez and call out into this solver, or alternatively an even deeper integration as investigated in their paper. We will be curious to learn about your experiences.

**Comment by k53sc** [comment]
@NikolajBjorner Thanks, I hope i can share my experiences with you soon.

I think I got what I needed from this issue, closing it.

**Comment by NikolajBjorner** [comment]
cool

**Comment by yxliang01** [comment]
@k53sc Have you tried with some insights that can be shared? It would be interesting to see such work as I expect there would be huge speedup :)

**Comment by yxliang01** [comment]
@NikolajBjorner To the best of your knowledge, has this been done already? Thanks.

**Comment by NikolajBjorner** [comment]
To the best of my knowledge it hasn't. 
There is also a question of what parts make sense to accelerate. Possibly just the SAT solver engine as demonstrated by paper mentioned above.
