### ISSUE TITLE
Z3 CLI: crash on certain assertion checking (Int and Bool mix expression)

### ISSUE THREAD

**Issue by wanderseeme** [Z3Prover/z3#180]
Say I have a file z3crash2.smt2 with content below:

(declare-datatypes () ((Tuple (tuple (first Int) (second Int)))))
(declare-const a Tuple)
(declare-const b Tuple)

(assert (= (first a) (distinct (first b) 0)))
(check-sat)

then I type "z3 z3crash2.smt2" in terminal, I get:

Segmentation fault (core dumped)

I know the expression is now allowed but at least Z3 should report it not crash itself. This will not happen if the variables are not nested in a data type, the content below will not cause crashing:

; this will not crash

(declare-const a Int)
(declare-const b Int)
(assert (= a (distinct b 0)))
(check-sat)

**Comment by wintersteiger** [comment]
The type checker was disabled so the error was found too late. I've (re-)enabled the type checker by default, which fixes the problem for this example, but the problem remains when type_check=false.
