### ISSUE TITLE
ML API: mk_int: check for overflow

### ISSUE THREAD

**Issue by btj** [Z3Prover/z3#1800]
I just discovered a nasty unsoundness https://github.com/verifast/verifast/issues/138 in my tool VeriFast, caused by the fact that `Z3native.mk_int n s`, on platforms where OCaml's `int` type is 63 bits but C's `int` type is 32 bits (which today probably means any platform except Cygwin32; it definitely includes macOS), silently truncates its argument `n`.

The docs for `Z3.mk_int` do (somewhat vaguely) warn about not all integers being supported, but still I would suggest putting a run-time check into `Z3native.mk_int`, something like:
```c
if ((int)Int_val(a1) != Int_val(a1)) { /* throw an OCaml exception */ }
```

Since the Z3native stubs are generated automatically, I guess this should be fixed in `update_api.py`. Furthermore, I guess this issue really applies to each API function that takes an OCaml `int`.

Alternatively, of course, versions of the Z3 C APIs could be implemented and used that take machine words instead of C `int`s.

**Comment by NikolajBjorner** [comment]
would you be able to add a pull request?

**Comment by NikolajBjorner** [comment]
on some inspection, it would be more places. First of all mk_int is used 3 places total so could use a wrapper. There are 64 bit versions of mk_int (called something like mk_int64) that could be used instead for both platforms assuming the parameter layout is not affected.
But there are also the functions that detect whether a numeral is an integer of a certain size. They can't be used if the most significant bit is set. This seems unchecked

**Comment by NikolajBjorner** [comment]
The treatment of "int" is fairly suspicious both for supplying and retrieving integers. 
In most cases these integers will fit in 31 bits and there is no issue. On the other hand, I opted to remove a couple of APIs that would produce incorrect results on 31 bit representations. The functions that produce numeral integers now work for all bit-widths: they fall back to using strings if the numeral does not fit within 31 bits.
