### ISSUE TITLE
Compile .NET API in AnyCPU

### ISSUE THREAD

**Issue by ahelwer** [Z3Prover/z3#1801]
Currently, there are separate amd64 and x86 .NET assemblies. The reason for this is there are separate amd64 and x86 native assemblies, which the .NET assemblies wrap with PInvoke. However, it's possible to compile the .NET API in AnyCPU, then at runtime determine whether the process is running in a 32- or 64-bit environment and load the correct native assembly. Example code:

```
using System;
using System.Runtime.InteropServices;

public static class NativeWrapper
{
    public static int NativeFunction()
    {
        if (Environment.Is64BitProcess)
        {
            return NativeWrapper64.NativeFunction()
        }
        else
        {
            return NativeWrapper32.NativeFunction();
        }
    }

    private static class NativeWrapper64
    {
        [DllImport("libz3.amd64.dll")]
        public static extern int NativeFunction();
    }

    private static class NativeWrapper32
    {
        [DllImport("libz3.x86.dll")]
        public static extern int NativeFunction()
    }
}
```

Compiling the .NET API in AnyCPU would have the following benefits:
- Enable customers to easily reference Z3 in their AnyCPU .NET projects
- Simplify future NuGet package releases (see #653)

These changes would require modifying the Native.cs code generation process to output the above boilerplate (or something similar).

This process can be further extended to write a single cross-platform .NET assembly for Linux and OS X, as the OS is detected at runtime and correct native assembly loaded.

**Comment by NikolajBjorner** [comment]
Perhaps same as #1892

**Comment by NikolajBjorner** [comment]
It works without this indirection and the script that creates nuget packages from the release bundles accross architectures.
