### ISSUE TITLE
z3 failing with simple abstract ring

### ISSUE THREAD

**Issue by matthewfl** [Z3Prover/z3#1802]
I have the following abstract definition of a semiring inside of z3.  If I only have the definition of the ring itself z3 is able to identify that there is a one and zero element.  However when I add any additional statements to the program (even just defining a an additional term equal to zero or one) then it ends up running for seemingly forever.

```
; declare the ring elements
(declare-sort R)

(declare-fun add (R R) R)
(declare-fun mul (R R) R)

(declare-fun one () R)
(declare-fun zero () R)

; the add properties
(assert (forall ((a R)) (= (add a zero) a)))
(assert (forall ((a R) (b R)) (= (add a b) (add b a))))
(assert (forall ((a R) (b R) (c R)) (= (add (add a b) c) (add a (add b c)))))

; the multiply properties
(assert (forall ((a R)) (= (mul a one) a)))
(assert (forall ((a R)) (= (mul a zero) zero)))
(assert (forall ((a R) (b R)) (= (mul a b) (mul b a))))
(assert (forall ((a R) (b R) (c R)) (= (mul (mul a b) c) (mul a (mul b c)))))

; distributive
(assert (forall ((a R) (b R) (c R)) (= (mul a (add b c)) (add (mul a b) (mul a c)))))

; different elements
(assert (distinct zero one))

; Either of the following blocks on their own cause the solver to run seemingly forever
(declare-fun fubar () R)
(assert (= fubar (mul fubar one)))

(assert (= zero (mul zero one)))



(set-option :timeout 100000)
(check-sat)
(get-model)
```

**Comment by NikolajBjorner** [comment]
Z3 isn't tuned for this sort of problems. It tries to find a finite model. Suggestion: try a superposition based theorem prover, Vampire, Waldmeister or E, for these kinds of problems (in this case unit equalities).

**Comment by matthewfl** [comment]
@NikolajBjorner There are finite rings which is what I was looking for in this case.

Eg:
0*0 = 0
0*1 = 0
0*2 = 0
1*1 = 1
1*2 = 2
2*2 = 1 

The above example isn't even getting into any of the more interesting examples.  Without the additional blocks (as I mentioned in the original post) it could find a two element ring.  But even defining another element as equal to the zero element (fubar) then it failed.

**Comment by NikolajBjorner** [comment]
Quantifier instantiation using matching produces a very large number of instances. The way I can solve this example is by adding a domain size restriction and disable ematching.

Thus, add an assertion: 

    (declare-const r1 R)
    (declare-const r2 R)
    (declare-const r3 R)
    (assert (forall ((x R)) (or (= x r1) (= x r2) (= x r3))))

And run z3 with the option smt.ematching=false
