### ISSUE TITLE
Const construct with arrays of bitvectors not supported?

### ISSUE THREAD

**Issue by SeanHeelan** [Z3Prover/z3#1803]
Hi,

Is the `const` construct for creating constant arrays supported in user scripts for arrays of bitvectors? The tutorial at [1] demonstrates the construct for the sort `(Array Int Int)`, but trying to use it for the sort `(Array (_ BitVec 32) (_ BitVec 8))` generates an error. e.g 

```
(set-logic QF_ABV)
(declare-const IN (Array (_ BitVec 32) (_ BitVec 8)))
(assert (= IN ((as const (Array (_ BitVec 32) (_ BitVec 8))) #x00)))
(check-sat)
```
```
$ z3 const.smt2 
(error "line 3 column 65: unknown function/constant const")
sat
```

I'm using a build of z3 from the latest git branch. I would have just assumed it was unsupported for the sort I want except for the fact that in models that z3 produces I have seen it use the construct for arrays of bitvectors. 

Thanks,
Sean

[1] https://rise4fun.com/z3/tutorialcontent/guide

**Comment by NikolajBjorner** [comment]
The issue is that the QF_ABV logic does not include the function "const". 
You can use Z3 without specifying a logic. In this case, the parser's symbol table includes the "const" function. For SMT-LIB2 logics, it will exclude "const" from being a known symbol.

**Comment by SeanHeelan** [comment]
Ah, I see. Thanks.
