### ISSUE TITLE
Make error in MacOS 10.13.6 High Sierra

### ISSUE THREAD

**Issue by YufengXin** [Z3Prover/z3#1804]
Did a "Git pull" today in my MacBook Pro (MacOS 10.13.6 High Sierra) and ran into the following error in the "Make" step, wonder what the problem might be. Thanks.
------------------------
g++  -o z3  shell/lp_frontend.o shell/dimacs_frontend.o shell/z3_log_frontend.o shell/install_tactic.o shell/mem_initializer.o shell/datalog_frontend.o shell/gparams_register_modules.o shell/opt_frontend.o shell/smtlib_frontend.o shell/main.o cmd_context/extra_cmds/extra_cmds.a api/api.a opt/opt.a tactic/portfolio/portfolio.a tactic/fpa/fpa_tactics.a tactic/smtlogics/smtlogic_tactics.a tactic/ufbv/ufbv_tactic.a muz/fp/fp.a muz/bmc/bmc.a muz/ddnf/ddnf.a muz/tab/tab.a muz/clp/clp.a muz/spacer/spacer.a muz/rel/rel.a muz/transforms/transforms.a muz/dataflow/dataflow.a muz/base/muz.a tactic/fd_solver/fd_solver.a sat/sat_solver/sat_solver.a qe/qe.a tactic/sls/sls_tactic.a smt/tactic/smt_tactic.a tactic/bv/bv_tactics.a smt/smt.a smt/proto_model/proto_model.a smt/params/smt_params.a ast/rewriter/bit_blaster/bit_blaster.a ast/pattern/pattern.a ast/fpa/fpa.a parsers/smt2/smt2parser.a cmd_context/cmd_context.a ackermannization/ackermannization.a tactic/aig/aig_tactic.a math/subpaving/tactic/subpaving_tactic.a nlsat/tactic/nlsat_tactic.a tactic/arith/arith_tactics.a sat/tactic/sat_tactic.a solver/solver.a ast/proofs/proofs.a tactic/core/core_tactics.a math/euclid/euclid.a math/grobner/grobner.a parsers/util/parser_util.a ast/substitution/substitution.a tactic/tactic.a model/model.a ast/normal_forms/normal_forms.a ast/macros/macros.a ast/rewriter/rewriter.a ast/ast.a math/subpaving/subpaving.a math/realclosure/realclosure.a math/interval/interval.a math/automata/automata.a math/simplex/simplex.a math/hilbert/hilbert.a util/lp/lp.a nlsat/nlsat.a sat/sat.a math/polynomial/polynomial.a util/util.a -lpthread 
Undefined symbols for architecture x86_64:
  "mpq_manager<true>::rat_lt(mpq const&, mpq const&)", referenced from:
      lp::lp_solver<rational, rational>::row_e_is_obsolete(std::__1::unordered_map<unsigned int, rational, std::__1::hash<unsigned int>, std::__1::equal_to<unsigned int>, std::__1::allocator<std::__1::pair<unsigned int const, rational> > >&, unsigned int) in lp.a(lp_solver_instances.o)
      lp::lp_solver<rational, rational>::row_ge_is_obsolete(std::__1::unordered_map<unsigned int, rational, std::__1::hash<unsigned int>, std::__1::equal_to<unsigned int>, std::__1::allocator<std::__1::pair<unsigned int const, rational> > >&, unsigned int) in lp.a(lp_solver_instances.o)
      lp::lp_solver<rational, rational>::row_le_is_obsolete(std::__1::unordered_map<unsigned int, rational, std::__1::hash<unsigned int>, std::__1::equal_to<unsigned int>, std::__1::allocator<std::__1::pair<unsigned int const, rational> > >&, unsigned int) in lp.a(lp_solver_instances.o)
      lp::lp_solver<rational, rational>::get_minimal_row_value(std::__1::unordered_map<unsigned int, rational, std::__1::hash<unsigned int>, std::__1::equal_to<unsigned int>, std::__1::allocator<std::__1::pair<unsigned int const, rational> > >&, rational&) in lp.a(lp_solver_instances.o)
      lp::lp_solver<rational, rational>::get_maximal_row_value(std::__1::unordered_map<unsigned int, rational, std::__1::hash<unsigned int>, std::__1::equal_to<unsigned int>, std::__1::allocator<std::__1::pair<unsigned int const, rational> > >&, rational&) in lp.a(lp_solver_instances.o)
      lp::lp_solver<rational, rational>::pin_vars_on_row_with_sign(std::__1::unordered_map<unsigned int, rational, std::__1::hash<unsigned int>, std::__1::equal_to<unsigned int>, std::__1::allocator<std::__1::pair<unsigned int const, rational> > >&, rational) in lp.a(lp_solver_instances.o)
      operator>(rational const&, int) in lp.a(lp_solver_instances.o)

**Comment by NikolajBjorner** [comment]
perhaps make clean, then make?

**Comment by YufengXin** [comment]
Strangely, I got:
--------------
make clean
make: *** No rule to make target `clean'.  Stop.
-------------
I didn't use any options, just did this:
-------------
python scripts/mk_make.py --python
-------------
The last line of error msg is:
-------------
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
----------

Thanks.

**Comment by NikolajBjorner** [comment]
Try a clean build (remove previous build directory).

**Comment by YufengXin** [comment]
This worked. Thanks a lot!
