### ISSUE TITLE
Obtain version from C++ API

### ISSUE THREAD

**Issue by sjunges** [Z3Prover/z3#1805]
Dear developers,

to allow support for multiple versions of the z3 C++ API within our model checker, we would love to obtain the z3 version within our CMake project file. 
We found a possibility to extract the z3 version from the Java API. 
 Is there a way to obtain the z3 version from the C++ API?

Right now, we obtain the version from the z3-binary: However, the binary is not necessarily available when the library is, which has lead to some errors.

Best regards,
Sebastian

**Comment by NikolajBjorner** [comment]
Yes, the C++ API includes the C API functions by inclusion. The C API includes the function

    /**
       \brief Return Z3 version number information.

       def_API('Z3_get_version', VOID, (_out(UINT), _out(UINT), _out(UINT), _out(UINT)))
    */
    void Z3_API Z3_get_version(unsigned * major, unsigned * minor, unsigned * build_number, unsigned * revision_number);

You call this directly from C++ code.
