### ISSUE TITLE
Q: what is expected performance on LPs?

### ISSUE THREAD

**Issue by jwaldmann** [Z3Prover/z3#1806]
What is the expected performance of Z3 on systems of linear inequalities
over the reals (that is, QF_LRA, but the constraint is a conjunction of atoms)?

It would "just" need some exact LP solver (e.g., simplex), which I assume is built in, for use by DPLL(T).

My experiments show that Z3 is much slower than GLPK (e.g., for 100 unknowns, 10000 ineqs.)

But that may be apples to oranges since GLPK uses machine numbers, and my problem instances are simple enough so that I can just convert to some nearest rational afterwards (of course I do check the result with exact computation).

**Comment by NikolajBjorner** [comment]
For LP problems the default mode uses bignum arithmetic and is therefore going to be rather slow (spend 90%+ running time in bignum arithmetic). There is a switch between floating point and bignum representations, which might get exercised depending on the form of benchmarks and the state of the implementation in Z3. @levnach could say more.

**Comment by jwaldmann** [comment]
Even small integer coefficients could force huge numbers in a satisfying assignment.
E.g., `x0 = 1, x1 = 2 * x0, x2 = 2 * x1, ...`

**Comment by levnach** [comment]
Currently bignum arithmetic is always used.

**Comment by jwaldmann** [comment]
"Some values in a fairly small set" => use finite domain constraint solvers or do a SAT encoding.

Then why  don't I? I did (minisat/ersatz), but I found that GLPK was better - although still slow for some (large) instances. Then I was referred to http://plato.asu.edu/ftp/lpsimp.html https://prod.sandia.gov/techlib-noauth/access-control.cgi/2013/138847.pdf claiming that GLPK may not be best in class. So I thought, give Z3 a try.

**Comment by DvonHolten** [comment]
yo - i had SAT-models before. And when some thousand 4-bit adder-comparators showed up, i thought, ints would be more natural. i will carefully continue with Z3

**Comment by jwaldmann** [comment]
Right. One final (and off-topic) remark: If it's a small number of small integer (or FD) unknowns, but a large number of constraints - then we should be using BDDs? Because with SAT, after Tseitin transform we just get a large CNF.

**Comment by NikolajBjorner** [comment]
Note that Z3 only uses real bignums if the intermediary numerals exceed ~30 bits representation. Otherwise, it uses a smaller representation. Some overhead remains, such as computing gcds for rational number representations. To really understand what is going on with respect to benchmarks I use a profiler combined with overall statistics of how search behaves.
