### ISSUE TITLE
nmake error 

### ISSUE THREAD

**Issue by Kogmawzy** [Z3Prover/z3#1807]
I am confused when I use nmake by VS 2017 under Windows,it prompts the error like flowing:
fatal error C1083: Cannot open include file: 'iostream': No such file or directory;
And I am sure I have create the build directory , there maybe sth wrong within the build ,but I dont know what it maybe . Looking forward to your answer!

**Comment by NikolajBjorner** [comment]
iostream is found under your VS2017 installation. So the paths may not be set up properly in the shell you use for the build. For 64 bit builds you can run: "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Auxiliary\Build\vcvars64.bat" to set up the proper environment. For 32 bit builds there is a similar command script.

**Comment by Kogmawzy** [comment]
Thanks a lot .For I only add bin to the classpath , so it didnt work. then I did as you said it really worked thax gain！
