### ISSUE TITLE
Model printing conflates sequences and strings

### ISSUE THREAD

**Issue by LeventErkok** [Z3Prover/z3#1808]
This is a bit of nit-picking, but reporting it for consistency. This script:

```
(set-option :produce-models true)
(set-logic ALL)
(declare-fun str   () String)
(declare-fun seq8  () (Seq (_ BitVec  8)))
(declare-fun seq16 () (Seq (_ BitVec 16)))
(assert (= 1 (str.len str)))
(assert (= 1 (seq.len seq8)))
(assert (= 1 (seq.len seq16)))
(check-sat)
(get-value (str seq8 seq16))
```

produces:

```
sat
((str "\x00")
 (seq8 "\x00")
 (seq16 (seq.unit #x0000)))
```

Since `String` and `Seq` are two distinct types, I'd expect the `seq8` value to be printed just like the one for `seq16`; instead of being printed as a `String`.

I realize that z3 equates `String` to `(Seq (_ BitVec 8))` internally, but from the surface they are different types.

**Comment by NikolajBjorner** [comment]
no longer
