### ISSUE TITLE
Can not find libz3java.dll

### ISSUE THREAD

**Issue by Kogmawzy** [Z3Prover/z3#1814]
I just did as the readme said to compile z3,but I only found libz3.dll without no libz3java.dll. I dont know how to get it

**Comment by NikolajBjorner** [comment]
and you did as it says in:

### ``Java``

Use the ``--java`` command line flag with ``mk_make.py`` to enable building these.

**Comment by NikolajBjorner** [comment]
README-CMake.md also has java specific instructions for cmake

**Comment by Kogmawzy** [comment]
Thx a lot . I will have a try

**Comment by Kogmawzy** [comment]
I did as you said like this python scripts/mk_make.py --java. however it prompt ：
Testing C:\Program Files (x86)\Java\jdk1.8.0_171\bin\javac.exe...
Finding jni.h...
Traceback (most recent call last):
  File "scripts/mk_make.py", line 18, in <module>
    mk_bindings(API_files)
  File "E:\programing\testing empirical study\jpf\z3\scripts\mk_util.py", line 2978, in mk_bindings
    check_java()
  File "E:\programing\testing empirical study\jpf\z3\scripts\mk_util.py", line 422, in check_java
    raise MKException("Failed to detect jni.h. Possible solution: set JNI_HOME with the path to JDK.")
mk_exception.MKException: 'Failed to detect jni.h. Possible solution: set JNI_HOME with the path to JDK.'

I am sure my JDK path has been add into my classpath，and I try add JNI_HOME to my classpath it still failed

**Comment by NikolajBjorner** [comment]
Perhaps just download a prebuilt binary instead of trying to build yourself. Seems these are issues that can be resolved by ensuring that the build environment is properly set up, but it requires some experience.

**Comment by EcnuTengfei** [comment]
@Kogmawzy I am installing z3 in my windows system. Now I have the same problem when finding the path of jni.h to JDK.

    Did you solve the problem?

**Comment by EcnuTengfei** [comment]
Ok, I solved the problem. 

I didn't use "Visual Studio Command Prompt" to built z3.

**Comment by NikolajBjorner** [comment]
Right, use the VS prompt for building on Windows so the environment is properly set up.
If the Java utilities happen not to be on the path, then add them.
