### ISSUE TITLE
Optimization bug with sequences

### ISSUE THREAD

**Issue by LeventErkok** [Z3Prover/z3#1820]
For this input:

```
(set-logic ALL)
(declare-fun s () (Seq Int))
(define-fun  l () Int (seq.len s))
(minimize l)
(check-sat)
(get-objectives)
(get-value (l s))
```

z3 says:

```
sat
(objectives
 ((seq.len s) (* (- 1) oo))
)
((l 0)
 (s Seq!val!0))
```

It appears it correctly deduced the minimum value for `l` is indeed `0`, but `get-objectives` returns `-oo` for the same. Also the model value of `s` must be an empty sequence, but instead we get some uninterpreted looking value of `Seq!val!0`.

**Comment by LeventErkok** [comment]
@NikolajBjorner This has gotten a little better: Correct value of `s` is returned; but the objective value is still `-oo`:

```
sat
(objectives
 ((seq.len s) (* (- 1) oo))
)
((l 0)
 (s (as seq.empty (Seq Int))))
```

**Comment by NikolajBjorner** [comment]
yes, I am aware of this. The fact that optimization "gives up" on this case isn't desired, but I currently haven't investigated whether this is fixable.

**Comment by NikolajBjorner** [comment]
produces 0 and empty sequence
