### ISSUE TITLE
Seg fault with sequences+recursion

### ISSUE THREAD

**Issue by LeventErkok** [Z3Prover/z3#1828]
I'm not sure if it's reasonable to expect z3 to actually find a model for this, but it should at least not seg-fault on the following benchmark:

```
(define-fun-rec mlen ((lst (Seq Int))) Int
   (ite (= (seq.len lst) 0)
        0
        (+ 1 (mlen (seq.extract lst 1 (- (seq.len lst) 1))))))

(declare-fun s () (Seq Int))
(assert (= 10 (mlen s)))

(check-sat)
(get-model)
```

**Comment by NikolajBjorner** [comment]
@trinhmt: the root cause was in a utility that interacts with arithmetical theories.
I am adding a self-contained module that we should use / adapt going forward. 
It is called smt_arith_values It can also be used in theory_str, @mtrberzi..

**Comment by mtrberzi** [comment]
Thanks, I will refactor to use this module in theory_str.
