### ISSUE TITLE
possible bug with data types

### ISSUE THREAD

**Issue by kanigsson** [Z3Prover/z3#183]
I think I came across an unsoundness in unstable branch, see this [file](https://gist.github.com/kanigsson/137b4c41d96c97e586c6).

The VC is supposed to be "sat" as far as I can see, and this is what z3 returns on the file as is. But replacing a sort + function definition by a data type definition makes z3 return unsat (see comment at line 51).

I know that a data type is more than just a type with function declarations, but in this VC it shouldn't make a difference.

Is there maybe a bug in z3 with data types?

Thanks for considering this.

**Comment by NikolajBjorner** [comment]
Did you take a look at the model Z3 returns for the sat result?
The model stipulates that rec__ has a single element. 
Could this be related to your axiomatization of get_post_axiom?

**Comment by kanigsson** [comment]
I hadn't looked at the model, thanks! That z3 derives this constraint is probably the issue, but I don't think the get_post_axiom is the culprit. Here is I VC with only one harmless-looking assert, z3 stil derives the same constraint:

(declare-sort integer 0)
(declare-fun in_range (Int) Bool)

(declare-sort enum_t 0)
(declare-datatypes ()
((spl_ty
 (mkspl (rec__b Bool)(rec__e enum_t)(rec__i integer)))))

(declare-sort rec__ 0)
(declare-fun spl (rec__) spl_ty)
(declare-fun get_i (rec__) Int)

(declare-fun r2 () rec__)

(assert (not (= 0 (get_i r2))))

(check-sat)

**Comment by NikolajBjorner** [comment]
yes, it seems like a bug related to MBQI that gets triggered by the example.

**Comment by NikolajBjorner** [comment]
Above fix should address the bug.

**Comment by kanigsson** [comment]
Confirmed, thank you! However, I found another potential problem, will open a new issue.
