### ISSUE TITLE
Compile-time Z3 version number

### ISSUE THREAD

**Issue by matzke1** [Z3Prover/z3#1833]
In order to support a C/C++ project that can be compiled with multiple versions of Z3, the project needs to make choices at compile time based on the Z3 version number ("#if"). Although Z3 has a Z3_get_version function, this is only run-time. Although Z3 creates an src/util/version.h file that has the required C preprocessor macros, it's not installed.

It seems like a simple solution would be "make install" (as well as the other installation methods) to install src/util/version as $Z3_ROOT/include/z3/z3_version.h after adding the proper include-once stuff and copyright notice. (Update: or better yet, just copy the contents of version.h into z3.h.)

**Comment by NikolajBjorner** [comment]
Hopefully this works for you

**Comment by NikolajBjorner** [comment]
can we close this given the updates?

**Comment by matzke1** [comment]
Works. Thank you.
