### ISSUE TITLE
Poor performance on sequence length

### ISSUE THREAD

**Issue by joelburget** [Z3Prover/z3#1835]
On issue #1828, the following script was posted.

```
(define-fun-rec mlen ((lst (Seq Int))) Int
   (ite (= (seq.len lst) 0)
        0
        (+ 1 (mlen (seq.extract lst 1 (- (seq.len lst) 1))))))

(declare-fun s () (Seq Int))
(assert (= 10 (mlen s)))

(check-sat)
(get-model)
```

The segfault has been fixed, but now I observe the following behavior:

* Asserting list length 0 (rather than 10), z3 immediately returns the model `seq.empty`
* At length 1, it immediately returns `seq.unit 2`
* At length 2, it immediately returns `unknown`
* And at longer lengths it hangs

I understand that this is not necessarily z3's focus, so this issue is just to ask whether the maintainers are interested in improving z3's performance on this test.

**Comment by NikolajBjorner** [comment]
It is a relevant question when it comes to procedures that are string (and tree) transducers. 
There are a fair amount of results on this, but not integrated as mainstream accessible from Z3.
It may be something @trinhmt and/or @mtrberzi are pursuing.

**Comment by NikolajBjorner** [comment]
This is now fixed with the introduction native rec-fun reasoning.
