### ISSUE TITLE
crash with many axioms over reals

### ISSUE THREAD

**Issue by kanigsson** [Z3Prover/z3#184]
Hello Z3 team,

please look at this [file](https://gist.github.com/kanigsson/e95317d7ea5780bbd983). With the option "memory_max_alloc_count=400000", I get

    *** Error in `z3': double free or corruption (fasttop): 0x00000000028fb730 ***
    Aborted (core dumped)"

This is on x86_64-linux. I am sory for the size of the file, but removing any axiom seems to make the error disappear. I am only guessing, but the large number of axioms over reals might play a role.

Note that we are working on targeting the z3 support for floats directly at some point. This will make many of the axioms disappear I suppose.

**Comment by wintersteiger** [comment]
Possible duplicate of #175.

**Comment by kanigsson** [comment]
Right, it might be the same issue, however the reproducer also triggers the issue also on 64bit systems.

**Comment by NikolajBjorner** [comment]
From my tests it is a duplicate of #175 and my check-in from 16 days ago should have fixed the issue.

**Comment by kanigsson** [comment]
Hello,

I confirm that the crash is gone, but on my system the behavior is still not very good.
    $ z3 memory_max_alloc_count=385307 float_crash.smt2 
    (error "line 547 column 10: number of configured allocations exceeded")
     [returns very quickly, <1s]
    $ z3 memory_max_alloc_count=385308 test.smt2
     [does not return even after 1 minute]

So at step 385307, some expensive computation which does not consume any steps seems to take place ... Should I create a new issue or do you want to take it from here?

**Comment by NikolajBjorner** [comment]
Thanks, right. The fix introduced a bug and the example also exposes a non-termination bug.
