### ISSUE TITLE
How to properly do an integer to string conversion?

### ISSUE THREAD

**Issue by bj2015** [Z3Prover/z3#1846]
I use Z3's String type and often convert integers to insert them into strings.

However, both built-in functions `str.from-int` and `int.to.str` do not support negative integers. So I built the following user-defined function to remove this restriction:

```
(define-fun intToStr ((i Int)) String (ite (> i 0) (int.to.str i) (str.++ "-" (int.to.str (- 0 i)))))
```

While this seems to work, I noticed that Z3 returns "unknown" even on completely trivial problems like

```
(set-option :produce-unsat-cores true)

(define-fun intToStr ((i Int)) String (ite (> i 0) (int.to.str i) (str.++ "-" (int.to.str (- 0 i)))))

(declare-const t Int)
(declare-const s String)

(assert (! (= t 42) :named a))
(assert (= s (intToStr t)))

(check-sat)
```

Hence my question is:
Am I doing something wrong here? Is there a better way to convert integers into strings? maybe even one that does not cause Z3 headaches?

Would it be possible to simply support negative numbers in int.to.str so that the above routine becomes unneccessary?

**Comment by DvonHolten** [comment]
your example works in rise4fun (version 4.5.1) . do you have another one ?

**Comment by bj2015** [comment]
Sorry, I forgot to mention:
I am using Z3 version 4.7.1 - 64 bit on MacOS Sierra Version 10.12.6

**Comment by NikolajBjorner** [comment]
Z3 used to handle int.to.str and str.to.int for negative integers, but this is incompatible with how the SMTLIB2 proposal for strings prescribes the behavior. Overall the int.to.str and str.to.int are not easy/possible to support well with decision procedures.

**Comment by NikolajBjorner** [comment]
Here is a simpler example that produces unknown:


     (declare-const t Int)
     (declare-const s String)
     (assert (>= t 53))
     (assert (= s (int.to.str t)))
     (check-sat)

**Comment by allanlw** [comment]
For both examples listed in this bug z3str3 (from HEAD) seems to have trouble as well and seems to loop forever (or at least for a long time).
