### ISSUE TITLE
Unsoundness with const arrays

### ISSUE THREAD

**Issue by jhoenicke** [Z3Prover/z3#1847]
The following script should be `unsat` but returns `sat` (with a wrong model):

```
>z3 -in -smt2
(set-option :produce-proofs true)
(set-option :produce-models true)
(set-logic ALL)
(declare-sort U 0)
(declare-fun i () U)
(declare-fun v1 () U)
(declare-fun v2 () U)
(assert (= (store ((as const (Array U U)) v1) i v2) ((as const (Array U U)) v2)))
(assert (not (= v1 v2)))
(check-sat)
sat
```

Showing that this formula is unsat requires some cardinality reasoning:  U has at least two elements because `v1 != v2` so rewriting a `(const v1)` array at one position cannot end up with `(const v2)` array.  If two locations `i,j` would be rewritten to v2, the formula would be sat, but only if `{i,j} = {v1,v2}` and `U = {v1,v2}` (z3 gives a model where all variables are different).

**Comment by NikolajBjorner** [comment]
fixed
