### ISSUE TITLE
Type-checking problems in n-ary equality

### ISSUE THREAD

**Issue by mschwerhoff** [Z3Prover/z3#185]
I observed the following behaviour in Z3 4.4.0 (x64 build on Win 7 x64). Let's assume the preamble

```
(set-option :type_check true)

(declare-const b (Bool))
(declare-const x (Int))
(declare-const y (Int))
```
As expected, `(assert (= x b))` yields a `sort mismatch` error.

Unexpectedly, `(assert (= x b y))` yields no error, and a subsequent `check-sat` even yields `sat`.

Moreover, the sequence
```
(assert (= x y z))
(check-sat)
(assert (= x b y))
(check-sat)
```
makes Z3 crash (`z3.exe has stopped working`).

**Comment by mschwerhoff** [comment]
Might be related to issue #180

**Comment by NikolajBjorner** [comment]
thanks, fixed
