### ISSUE TITLE
segmentation fault - lexicographic optimization

### ISSUE THREAD

**Issue by PatrickTrentin88** [Z3Prover/z3#1851]
**commit:** 35bf63d563b682d794067c66f018a0fb06bf7ce2

**error:** segmentation fault

**offending formula:**

```
(set-option :opt.priority lex)
(set-option :produce-models true)

(declare-fun s1 () Bool)
(declare-fun s2 () Bool)
(declare-fun s3 () Bool)
(declare-fun s4 () Bool)
(declare-fun q1 () Real)
(declare-fun q2 () Real)
(declare-fun q3 () Real)


(assert (<= 1.0 q1))
(assert (<= 0.0 q2))

(assert (<= 3.0 q3))

(assert (< q1 q2))

(assert (< (* 100000000000000000000000000000 q2) q3 ))

(minimize q1)
(minimize q2)
(minimize q3)

(check-sat)
(get-objectives)
(get-model)
(exit)
```

**comments:** the formula works just fine if the last inequality is transformed into an equality.

**Comment by NikolajBjorner** [comment]
so far no repro on either windows or ubuntu

**Comment by PatrickTrentin88** [comment]
This is the system config:

```
Host platform:  Linux
C++ Compiler:   g++
C Compiler  :   gcc
Archive Tool:   ar
Arithmetic:     internal
OpenMP:         True
Prefix:         /usr
64-bit:         True
FP math:        SSE2-GCC
Python pkg dir: /usr/lib/python2.7/dist-packages
Python version: 2.7
```
I just tested it again and I get the same result.
Attached you can find the executable I just compiled.

[z3.zip](https://github.com/Z3Prover/z3/files/2443811/z3.zip)

**Comment by nunoplopes** [comment]
I can't reproduce on CentOS either. Could you try running valgrind or something similar to shed some light about what's going on?

**Comment by NikolajBjorner** [comment]
I have added it to the regressions that are run on every check-in. None of the build scenarios that are used crash on this. So at this point we have no repro of this reported bug. Perhaps check with your compiler tool chain or clean builds.
