### ISSUE TITLE
Segmentation Fault using QF_FP

### ISSUE THREAD

**Issue by kevinclancy** [Z3Prover/z3#186]
When I run Z3 4.4.0 (64-bit build on Ubuntu 14.04) on the following file, I get a segmentation fault. After removing the line containing "(assert (fpeq z3v87 (z3f86 z3v83 z3v85)))", the fault does not occur. 

(set-option :auto-config false)
(set-option :model true)
(set-option :model.partial false)
(set-option :smt.mbqi false)
(set-logic QF_FP)
(define-sort Float () (_ FloatingPoint 8 24))
(define-fun rnte () RoundingMode roundNearestTiesToEven)
(define-fun neg-zero () Float (_ -zero 8 24))
(define-fun zero () Float (_ +zero 8 24))
(define-fun one () Float ((_ to_fp 8 24) rnte 1.0))
(define-fun fpadd ((a Float) (b Float)) Float (fp.add rnte a b))
(define-fun fpsub ((a Float) (b Float)) Float (fp.sub rnte a b))
(define-fun fpneg ((a Float)) Float (fp.sub rnte zero a))
(define-fun fpmul ((a Float) (b Float)) Float (fp.mul rnte a b))
(define-fun fpdiv ((a Float) (b Float)) Float (fp.div rnte a b))
(define-fun fpeq  ((a Float) (b Float)) Bool (fp.eq a b))
(define-fun fplt  ((a Float) (b Float)) Bool (fp.lt a b))
(define-fun fpleq ((a Float) (b Float)) Bool (fp.leq a b))
(define-fun fpgt  ((a Float) (b Float)) Bool (fp.gt a b))
(define-fun fpgeq ((a Float) (b Float)) Bool (fp.geq a b))
(define-fun fpabs ((a Float)) Float (fp.abs a))
(define-fun fpmin ((a Float) (b Float)) Float (fp.min a b))
(define-fun fpmax ((a Float) (b Float)) Float (fp.max a b))
(define-fun fpIsNum ((a Float)) Bool (not (or (fp.isInfinite a) (fp.isNaN a))))
(declare-fun z3v66 () Int)
(declare-fun z3v67 () Int)
(assert (distinct z3v66 z3v67))
(declare-fun z3v68 () Int)
(declare-fun z3f69 (Int) Int)
(declare-fun z3f70 (Int) Bool)
(declare-fun z3v71 () Int)
(declare-fun z3v72 () Int)
(declare-fun z3v73 () Float)
(declare-fun z3v74 () Float)
(declare-fun z3v75 () Float)
(declare-fun z3v76 () Float)
(declare-fun z3v77 () Int)
(declare-fun z3v78 () Int)
(declare-fun z3v79 () Float)
(declare-fun z3v80 () Float)
(declare-fun z3v81 () Int)
(declare-fun z3v82 () Int)
(declare-fun z3v83 () Float)
(declare-fun z3v84 () Float)
(declare-fun z3v85 () Float)
(declare-fun z3f86 (Int Int) Int)
(declare-fun z3v87 () Float)
(declare-fun z3v88 () Float)
(push 1)
(assert (fpeq z3v88 z3v73))
(assert (fpeq z3v87 (z3f86 z3v83 z3v85)))
(assert (= (z3f70 z3v77) (fplt z3v84 z3v75)))
(assert (fpeq z3v83 (fpadd z3v73 z3v76)))
(assert (not (z3f70 z3v82)))
(assert (not (z3f70 z3v82)))
(assert (not (z3f70 z3v82)))
(assert (= z3v82 z3v81))
(assert (= (z3f70 z3v81) (fplt z3v80 z3v79)))
(assert (fpeq z3v79 (fpneg z3v75)))
(assert (not (z3f70 z3v78)))
(assert (not (z3f70 z3v78)))
(assert (not (z3f70 z3v78)))
(assert (= z3v78 z3v77))
(assert (fpgt z3v73 ((_ to_fp 8 24) rnte 1.0)))
(assert (fplt z3v76 ((_ to_fp 8 24) rnte 4000.0)))
(assert (fpgt z3v75 ((_ to_fp 8 24) rnte 0.0)))
(assert (fpeq z3v74 z3v73))
(assert (z3f70 z3v66))
(assert (= (z3f69 z3v72) z3v72))
(assert (= (z3f69 z3v71) z3v71))
(assert (not (z3f70 z3v67)))
(assert (= (z3f69 z3v68) z3v68))
(push 1)
(assert (not (fpgt z3v88 ((_ to_fp 8 24) rnte 1.0))))
(check-sat)

**Comment by NikolajBjorner** [comment]
thanks, added type checking
