### ISSUE TITLE
no sets returned?

### ISSUE THREAD

**Issue by rwst** [Z3Prover/z3#187]
Please pardon, I'm not a logician and new to SMT solvers. If I feed Z3 with
```
(declare-fun x () Real)
(declare-fun a () Real)
(assert (> (* a x) 0))
(assert (> a 0))
(check-sat)
(get-value (x a))
(exit)

z3 -smt2 file
```
result:
```
sat
((x 1.0)
 (a 1.0))
```
which means it finds a solution, but not the set of all solutions which would be something like `((0 < x) (a > 0))`. Do I have to specify something and, if so, why?

**Comment by NikolajBjorner** [comment]
This is not a bug. This is how Z3 is supposed to work. A "model" of a formula is some assignment to the variables and functions that satisfies the formula. Z3 produces one assignment if there is one. See the tutorial on http://rise4fun.com/z3 for additional examples of models.
