### ISSUE TITLE
Error in SMTLIB output from the Python API

### ISSUE THREAD

**Issue by SeanHeelan** [Z3Prover/z3#1870]
Using the latest version of Z3 from the master branch I have created a model using the Python API. When I dump that model using `s.sexpr()`, where `s` is a `z3.Solver` object, there are erroneous `and` tokens in various places in the output. 

For example:

```
(assert (let ((a!1 (= (concat (concat (concat I0_L0_ARG0 I0_L0_ARG1) I0_L0_ARG2)
                      I0_L0_ARG3)
              #x00000004))
      (a!2 (=> (= I0_L0_create_user_user_addr #x01410000)
               (and (= I0_L0_create_user_tmp_hl0 false)
...
                    (= I0_L0_HL_OUT23 true)
                    and
                    (= I0_L0_HV_OUT24 I0_L0_create_user_tmp_hv24)
                    (= I0_L0_HV_OUT25 I0_L0_create_user_tmp_hv25)
                    (= I0_L0_HV_OUT26 I0_L0_create_user_tmp_hv26)
                    (= I0_L0_HV_OUT27 I0_L0_create_user_tmp_hv27)
                    and
                    (= I0_L0_HL_OUT24 I0_L0_create_user_tmp_hl24)
                    (= I0_L0_HL_OUT25 I0_L0_create_user_tmp_hl25)
                    (= I0_L0_HL_OUT26 I0_L0_create_user_tmp_hl26)
                    (= I0_L0_HL_OUT27 I0_L0_create_user_tmp_hl27)
...
```

In the above the second and third `and`s are missing the parentheses that should open and close their expressions. I am guessing these correspond to my nested uses of `z3.And` via the Python API. e.g there are places where I create a model like: `z3.And( ......, z3.And( .....), .....)`, but I haven't been able to create a minimal example.  Perhaps it has something to do with the let bindings or the implication? 

If you can't think of anything that would cause this problem let me know and I'll dig a little deeper into trying to create a minimal test case.

**Comment by SeanHeelan** [comment]
I cleaned up the generated SMTLIB file by removing these `and`s and it seems that the output is not semantically correct. Via the Python API it takes 300 seconds to prove that the problem is satisfiable, but when I run z3 from the command line it takes 4 seconds, but the satisfying assignment is not correct. 

The model can be found [here](https://github.com/Z3Prover/z3/files/2468519/model7.txt).

The correct result is `S0 = 0x0, S1 = 0x22, S2= 0x12, S3 = 0xF3, S4 = 0xF0, S5 = 0x23, S6 = 0x30` but when run on the SMTLIB file I get:

```
((S0 #xf0)
 (S1 #xf0)
 (S2 #xf0)
 (S3 #xf0)
 (S4 #xf2)
 (S5 #xf2)
 (S6 #xf0))
```

**Comment by NikolajBjorner** [comment]
The model when run over the smt2 file is validated: every assertion evaluates to true in that model.
Z3 parses nullary and without parentheses. It is then a constant.

**Comment by SeanHeelan** [comment]
Hi Nikolaj,

Thanks for the clarification. I am not sure how but, the final assertion got clipped out of the .smt2 file.

**Comment by SeanHeelan** [comment]
Hi Nikolaj,

With the correct assertion at the end I have encountered an unrelated quirk. Let me know if you'd rather I create a new issue, but the details are as follows:

In some cases, if I dump the model to a .smt2 file and invoke the z3 binary it can correctly solve problems in a fraction of the time it takes to solve via the `check()` method of a `Solver` object from Python. 

A sample .smt2 file can be found here: [model6.txt](https://github.com/Z3Prover/z3/files/2478624/model6.txt). It is UNSAT, but I get a similar performance difference for SAT results. On the command line it takes 5 seconds and from Python about 80. 

If you want to see the Python performance then you can grab the code from here: [example.zip](https://github.com/Z3Prover/z3/files/2478621/example.zip)

It can be ran with `./userstore -o /tmp/outputdir`. When it creates the 6th model you will see it takes 80 seconds or so to resolve, while the 7th one takes even longer. Those models will be logged into the output directory and, if you append on a (check-sat) call, they can be solved on the command line in a fraction of the time.

**Comment by NikolajBjorner** [comment]
Model6 takes a few seconds. I tried with different random seeds (sat.random_seed=<nn>). It uses the sat solver in both the SMT-LIB format and when I load the problem from a file for a default Solver.
It gets really slow if I disable the sat solver. For example: 

from z3 import *
s = SolverFor("BV")   # really use s = Solver() or s = SolverFor("QF_FD")
fmls = s.from_file("slow.smt2")
set_option(verbose=10)
print s.check()
