### ISSUE TITLE
prove function returns wrong counterexample ?

### ISSUE THREAD

**Issue by oooo0o** [Z3Prover/z3#1872]
```python
>>> import z3
>>> A = z3.BitVec('A', 8)
>>> B = z3.BitVec('B', 8)
>>> C = z3.BitVec('C', 8)
>>> z3.prove((A*B)/C == A*(B/C))
counterexample
[A = 67, B = 86, C = 2]
>>> ((67*86)%256)/2
65
>>> (67*(86/2))%256
65
```

[Test Environment]
Z3-4.7.1-x86-win
Python-2.7.15

I think it seems to return an incorrect counterexample.
What is the problem? am i using it incorrect way??

**Comment by LeventErkok** [comment]
@oooo0o You asked this very question on stackoverflow and already received an answer there: https://stackoverflow.com/a/52763899/936310
