### ISSUE TITLE
Wrong answer on string problem

### ISSUE THREAD

**Issue by 4tXJ7f** [Z3Prover/z3#1875]
The input below returns `sat` on Z3 4.7.1 and the current master 2f9853f. The model returned corresponds to the commented out assertions. When I comment them in, the answer changes to `unsat`. CVC4 agrees with the model being incorrect (it currently cannot solve the problem, at least not within a short timeout).

```
(set-option :produce-models true)
(set-logic SLIA)
(declare-const x String)
(declare-const y String)
(declare-const z String)
(declare-const n Int)
(assert (not (= (str.contains (str.replace x y x) (str.substr z n 1)) (str.contains x (str.substr z n 1)))))
; (assert (= x "\x00"))
; (assert (= y "\x00"))
; (assert (= z "\x00\x00"))
; (assert (= n 0))
(check-sat)
(get-model)
```

**Comment by NikolajBjorner** [comment]
this is now fixed
