### ISSUE TITLE
conda install not working

### ISSUE THREAD

**Issue by cell2749** [Z3Prover/z3#1879]
When running command: 
`conda install libpython m2w64-toolchain -c msys2`
From pystan installation guide: https://pystan.readthedocs.io/en/latest/windows.html#windows
I get following error msg: 

> 
> Solving environment: ...working... failed
> CondaHTTPError: HTTP 404 NOT FOUND for url <https://github.com/Z3Prover/z3/noarch/repodata.json>
> Elapsed: 00:00.139665
> 
> The remote server could not find the noarch directory for the
> requested channel with url: https://github.com/Z3Prover/z3
> 
> As of conda 4.3, a valid channel must contain a `noarch/repodata.json` and
> associated `noarch/repodata.json.bz2` file, even if `noarch/repodata.json` is
> empty. please request that the channel administrator create
> `noarch/repodata.json` and associated `noarch/repodata.json.bz2` files.
> $ mkdir noarch
> $ echo '{}' > noarch/repodata.json
> $ bzip2 -k noarch/repodata.json
> 
> You will need to adjust your conda configuration to proceed.
> Use `conda config --show channels` to view your configuration's current state.
> Further configuration help can be found at <https://conda.io/docs/config.html>.

Running the suggested show channels command reveals:

> $ conda config --show channels
> channels:
>   - https://github.com/Z3Prover/z3
>   - https://github.com/mwaskom/seaborn
>   - https://github.com/plotly/plotly.py
>   - defaults

**Comment by NikolajBjorner** [comment]
Not sure about these instructions. The requested empty file is under:
https://github.com/Z3Prover/z3/blob/master/noarch/repodata.json
Can you add pull request for proper files? or file the issue on pystan or the place that has added the dependency?

**Comment by cell2749** [comment]
Yes I can see the file. Will try to ask conda devs. Issue can be closed.

**Comment by cell2749** [comment]
Fixed by removing every channel except default from condarc
For some reason I had the three extra channels after installing anaconda3 and they were causing issues with every conda install command.
