### ISSUE TITLE
Can't find libz3.so

### ISSUE THREAD

**Issue by jaismin** [Z3Prover/z3#1891]
Hi, I have been trying to use z3py but I get the error that "Could not find libz3.so" I tried making the follwing comments and it says that ~/z3/build/libz3.so is not a file.
![screenshot from 2018-10-19 06-48-19](https://user-images.githubusercontent.com/19632028/47192446-0abe3880-d36b-11e8-88ed-9cd1baa69013.png)
![screenshot from 2018-10-19 06-48-30](https://user-images.githubusercontent.com/19632028/47192479-2b868e00-d36b-11e8-84dd-76ca25783685.png)
It would be great if someone could help!

**Comment by NikolajBjorner** [comment]
Did the readme instructions help?
