### ISSUE TITLE
different results (sat & unknown) for same problem

### ISSUE THREAD

**Issue by pjljvandelaar** [Z3Prover/z3#1895]
A user of our TorXakis test tool reported an issue that can be traced back to Z3 (see https://github.com/TorXakis/TorXakis/issues/795 for more info).

I have tried to isolate the issue on windows.
I found that, surprisingly, Z3 reports for the same problem different results.
For the following file, I get (after quite some time) 
[TorXakis#795-2.smt2.txt](https://github.com/Z3Prover/z3/files/2501230/TorXakis.795-2.smt2.txt)
```
PS C:\temp> z3 .\TorXakis#795-2.smt2
(:name "Z3")
(:version "4.8.1 - build hashcode 016872a5e0f6")
once
unknown
twice
sat
```
However, the problem is the same in those two cases!
So I would have expected either `sat sat` or `unknown unknown` and not this mixture.

Even worse, small changes change the answer (and termination).
The following file
[TorXakis#795-1.smt2.txt](https://github.com/Z3Prover/z3/files/2501258/TorXakis.795-1.smt2.txt)
yields
```
PS C:\temp> z3 .\TorXakis#795-1.smt2
(:name "Z3")
(:version "4.8.1 - build hashcode 016872a5e0f6")
once
sat
twice
```
(I killed it after 15 minutes)

I expect this is caused by a relative recent change, since I have used Z3 on a recursive length function myself in the past without any problems.

**Comment by NikolajBjorner** [comment]
It was now added to the master branch. The new approach to handling recursive functions is turned on by default. To disable it, and get the old behavior, set smt.recfun.native=false. The new behavior should be superior in all cases, though and I will retire the old behavior once we are reasonably clear.
