### ISSUE TITLE
unsoundness issue with datatypes?

### ISSUE THREAD

**Issue by c-cube** [Z3Prover/z3#1897]
On the following problem, Z3 4.7.1 returns "unsat", whereas Z3 4.5.1 and CVC4 1.6 both return "sat" (with, as far as I can tell, a valid model).

```smt2
(set-logic ALL)

(declare-sort sort0 0)
(declare-datatypes ((list 0)) (((nil) (cons (head sort0) (tail list)))))
(declare-fun x () list)
(declare-fun y () list)
(declare-fun append (list list) list)
(declare-fun bool0 () Bool)
(declare-fun bool1 () Bool)
(declare-fun bool2 () Bool)
(assert (not (= (= (append x y) y) (= x nil))))
(assert (=> true bool0))
(assert (=> (and bool0 (not (= x nil)))
    bool1))
(assert
  (let ((a!1 (ite (= x nil) y (cons (head x) (append (tail x) y)))))
  (= (append x y) a!1)))
(assert
  (let ((a!1 (and bool1 (not (= (tail x) nil)))))
  (=> a!1 bool2)))

(assert
  (let ((a!1 (cons (head (tail x)) (append (tail (tail x)) y))))
  (= (append (tail x) y) (ite (= (tail x) nil) y a!1))))

(check-sat)
```

**Comment by NikolajBjorner** [comment]
The new occurs check code in theory data types isn't clear here. It claims an occurs check without premises.

**Comment by NikolajBjorner** [comment]
Occurs check enter uses app and app->get_root. Some equality is lost.

**Comment by c-cube** [comment]
I see. I'll submit a patch asap. Sorry about that :-/

**Comment by c-cube** [comment]
@NikolajBjorner I'm going to submit a patch, will be you be able to run it against all the datatypes problems currently available to you (including this regression test)?

**Comment by NikolajBjorner** [comment]
I have a fix too. Adding it in a couple of hours when online

**Comment by c-cube** [comment]
I'd be interested in comparing our fixes. Regarding the regression test, I only have this one example file for this bug…
