### ISSUE TITLE
Parallel mode example

### ISSUE THREAD

**Issue by palladin** [Z3Prover/z3#1898]
Is there any example about how to use the new (4.8.1) Parallel mode (cube and conquer) with (Python or Dotnet)?

**Comment by DvonHolten** [comment]
*ANY* parallel mode example would be interesting - even in SMTLIB...

**Comment by palladin** [comment]
I'm using the dotnet api and you can set
``
Microsoft.Z3.Global.SetParameter("parallel.enable", "true")
``
but I haven't be able to see multicore cpu utilisation.

**Comment by NikolajBjorner** [comment]
Parallel mode is selective among a subset of the tactics that are used under the hood.
The main mode of operation is for finite domain (bit-vector) benchmarks.
For example:

[36.smt2.txt](https://github.com/Z3Prover/z3/files/2543182/36.smt2.txt)

If you run it you will see output estimating progress.

**Comment by DvonHolten** [comment]
yo - that looks interesting !! where can i find LLVM Alias Analysis proofs 1 to 35??
however, i am not entirely SAT - now i have to decide whether to rewrite my integer/boolean stuff to bitvectors 😢

**Comment by palladin** [comment]
Thanks for the response @NikolajBjorner
The thing I was missing was to explicit set the logic
```
let solver = ctx.MkSolver("QF_UFBV")
``` 
Unfortunately I don't see multicore speedups and the reported progress is
```(tactic.parallel :progress 0% :closed 0 :open 1)```

**Comment by NikolajBjorner** [comment]
Try (check-sat-using psmt) for your non-bit-vector needs.

The lookahead features for SMT is very weak, though. 
And I haven't harnessed performance on any samples.

**Comment by palladin** [comment]
The curious thing is that I don't have non-bit-vector needs.
My example uses only BoolExpr expressions.

**Comment by palladin** [comment]
Here is my example
[test.zip](https://github.com/Z3Prover/z3/files/2543504/test.zip)

**Comment by NikolajBjorner** [comment]
There are a few fishy things, both in input and in Z3.
- Your input: QF_UFBV is not the right logic. Use QF_BV or QF_FD. You have no functions?
- In Z3: I had to tease it to use (check-sat-using pqffd).
Then the stronger inprocessing used in parallel mode just killed the problem or it got lucky.
Will need to check why (check-sat) didn't trigger parallel mode. Probably it went ahead with one of the preprocessing tactics, which isn't using psat (the tactic that ensures that the sat solver is wrapped by the c&c solver)

**Comment by palladin** [comment]
Yes QF_BV is ok... I use only ```ctx.MkBoolConst(...)```
