### ISSUE TITLE
Bitvector Division by Zero is Possibly Overconstrained

### ISSUE THREAD

**Issue by kyledewey** [Z3Prover/z3#190]
On the `unstable` branch at commit 424f34d3d948283b61c92f089cc3b90e76c44324, if I run Z3 with the following command-line:

```console
z3 rewriter.hi_div0=false old_simplify.bv.hi_div0=false test.smt2
```

...where `test.smt2` has the following contents:

```
(declare-const x (_ BitVec 1))
(assert (= x (bvudiv #b0 #b0)))
(assert (= x #b0))
(check-sat)
```

...Z3 reports `unknown`.  My interpretation of the standard is that it should be `sat` in this instance, as the result of bitvector division by zero is unconstrained, which is consistent with the behavior for reals and integers.  For what it's worth, CVC4 reports `sat` for this input.

I realize this may be more of a discussion point than a bug report, based on [some prior discussion](http://sourceforge.net/p/smtcomp/mailman/message/32457410/).  I'm honestly not sure what the correct behavior is here.

**Comment by NikolajBjorner** [comment]
not quite supported. Z3 does not realize that you turned a pure bit-vector problem into a hybrid where division by 0 is under-specified. You can force the hybrid mode solver by setting the logic to (set-logic QF_UFBV)

**Comment by NikolajBjorner** [comment]
I added a filter to prevent this scenario.
