### ISSUE TITLE
"nested" data definitions

### ISSUE THREAD

**Issue by nikivazou** [Z3Prover/z3#1903]
Can I define "nested" data definitions in z3, for example, I want to define a term that contains a predicate that contains a term, as follows: 
```
(declare-datatypes (T) 
  (
    (Pred (predSelector (predValue T)))
    (Term (termPredSelector (termPredValue (Pred Term))))
  )
)
```

But I get the error 

```
unknown sort `Pred`
```
In Haskell language, I want to encode the following data type
```
data Pred l 
  = Pred l

data Term l 
  = TPred (Pred (Term l))
```

**Comment by NikolajBjorner** [comment]
You can declare datatypes according to the SMTLIB 2.6 specification.
This allows for nested datatypes. The spec is on http://smtlib.cs.uiowa.edu/papers/smt-lib-reference-v2.6-r2017-07-18.pdf 
The syntax you use is a non-standard format that was introduced in Z3 long before this spec was introduced. It does not support nested datatypes.

**Comment by LeventErkok** [comment]
Web version of Z3 is rather old (4.4.2 I think). If you try this on an installed version (4.8.0), you actually get:

```
(error "line 1 column 28: sort already defined List")
```
And the fix is easy: Once you rename `List` to `MyList` (or whatever you like), z3 4.8.0 accepts it just fine.

**Comment by NikolajBjorner** [comment]
Right. We keep pre defining List as polymorphic for convenience of the tutorial, but it can't be be redeclared.

**Comment by NikolajBjorner** [comment]
Is there something that should be fixed?

**Comment by nikivazou** [comment]
Nothing to be fixed. Thanks a lot!
