### ISSUE TITLE
Why can a model contain an interpretation for a function without interpreting its domain?

### ISSUE THREAD

**Issue by wilcoxjay** [Z3Prover/z3#1904]
Consider the following SMT2 query:

```
(declare-sort A)

(declare-fun S1 (A) Bool)
(declare-fun S2 (A) Bool)

(assert (forall ((x A)) (= (S1 x) (S2 x))))

(check-sat)
(get-model)
```

to which Z3 responds

```
sat
(model 
  (define-fun S2 ((x!0 A)) Bool
    false)
  (define-fun S1 ((x!0 A)) Bool
    (S2 x!0))
)
```
Notice that the model contains no universe for the sort `A`.

I ran into this problem when using the API, where I would get a model back from Z3, which contained an interpretation for S1. And I would like to try to enumerate all the values for `S1` by looping over the universe of `A`, only to get the error that `A` has no universe in the model.

I can trick Z3 into giving `A` a universe by adding 

```
(declare-fun C () A)
(assert (S1 C))
```

I have a few questions about this:
- Is it a bug in Z3 or the intended behavior?
- What does it mean if Z3 decides not to include a universe for a sort in a model, even when the model interprets functions with that sort in their domain? Does it mean that the formula is true in every possible universe? 
- Is there a standard/documented way to force Z3 to have a universe for a sort? Is the trick I use above standard?

**Comment by LeventErkok** [comment]
You can always use the `model.completion` parameter:

```
$ z3 model.completion=true a.smt2
sat
(model
  ;; universe for A:
  ;;   A!val!0
  ;; -----------
  ;; definitions for universe elements:
  (declare-fun A!val!0 () A)
  ;; cardinality constraint:
  (forall ((x A)) (= x A!val!0))
  ;; -----------
  (define-fun S2 ((x!0 A)) Bool
    false)
  (define-fun S1 ((x!0 A)) Bool
    (S2 x!0))
)
```

**Comment by wilcoxjay** [comment]
Interesting, that seems to work in SMT2LIB, but not via the python API:

```
import z3

z3.set_param('model.completion', True)

s = z3.Solver()

A = z3.DeclareSort('A')
S1 = z3.Function('S1', A, z3.BoolSort())
S2 = z3.Function('S2', A, z3.BoolSort())

x = z3.Const('x', A)
s.add(z3.ForAll(x, S1(x) == S2(x)))

res = s.check()
assert res == z3.sat

m = s.model()

print('sorts:', m.sorts())  # prints sorts: []
print('decls:', m.decls())  # prints decls: [S2, S1]
```

**Comment by NikolajBjorner** [comment]
The example is so simple that A never appears in any constraints during solving. 
Then the model generation doesn't assign a finite domain to A.
The formula is satisfied for every domain (non-empty, finite or infinite).

**Comment by LeventErkok** [comment]
@NikolajBjorner I think it's interesting why the SMTLib version works with the `model.completion` parameter, but the python version doesn't. As far as I can see, they produce precisely the same solver state. Any reason why they behave differently?
