### ISSUE TITLE
ImportError: cannot import name BitVec

### ISSUE THREAD

**Issue by nrrpinto** [Z3Prover/z3#1905]
Hi,
I get an error when trying to import the BitVec from z3:
>Traceback (most recent call last):
>  File "example.py", line 1, in <module>
>    from z3 import BitVec, Solver
>ImportError: cannot import name BitVec

I've installed the z3 library with the:
> pip install z3

Because of the error, i've cloned the github repository and made the 
> python scripts/mk_make.py 
> cd build; make
> make install

But the error persists.

Can someone point me in the right direction, what should I do?
Thanks in advance.

**Comment by NikolajBjorner** [comment]
what does "pip install z3" actually install?
when I look at https://pypi.org/project/z3/#history, 
I see a link to https://github.com/presslabs/z3
This says: "z3 is a ZFS to S3 backup tool. "
While I worked on storage in a previous life, 
I can ensure you that this Z3 does not touch your disk unless it is using the page file.

**Comment by nrrpinto** [comment]
Hi @NikolajBjorner ,

I thought that the "pip install z3" would install this lib into my system. My bad for not checking it in detail.
I install your tool manually, but i could only execute my script in one of the tool folders.
After that I did a "apt-get install python-z3" and now I can execute the my script everywhere all over my OS.

I am sorry for my lack of knowledge, I use Linux systems for only 8 months now, so a lot of this concepts are still somehow "magic" for me, and I don't know exactly how they work.

Thanks for taking your time to help me.

**Comment by NikolajBjorner** [comment]
Good to hear. You mention python-z3. I found references to it online. It was prepared by Michael Tautschnig it seems and is for version 4.4, which is a few years old. I haven't been involved with this package and will only be able to support questions on the current version of Z3. There are no supported python install packages for Z3 (I have no talent or bandwidth for this). It is probably sufficient for introdoctory experiments though.
