### ISSUE TITLE
Incorrect string simplification

### ISSUE THREAD

**Issue by 4tXJ7f** [Z3Prover/z3#1908]
The following input results in `unsat` for the first `(check-sat)` call and `sat` for the second:

```
(declare-const x String)

(push)
(assert (= (str.replace "" x "B") "B"))
(check-sat)
(pop)

(assert (= (str.replace "" "" "B") "B"))
(check-sat)
```

From what I can tell, this seems to be an issue in the rewriter: `(simplify (str.replace "" x "B"))` returns the empty string.

**Comment by NikolajBjorner** [comment]
@mtrberzi: regressions/smt2/string10.smt2 now produces different answers. Can you double check the encoding of semantics for replace in z3str3?

**Comment by mtrberzi** [comment]
Thanks, will check this

**Comment by mtrberzi** [comment]
According to the expected output Z3str3 is returning UNSAT (expected) and theory_seq is returning SAT (unexpected). Is UNSAT still the expected answer here? Semantics of replacing over "" should still produce "" no matter what the target and replacement are. Has this changed?

**Comment by 4tXJ7f** [comment]
The current [draft](http://smtlib.cs.uiowa.edu/theories-UnicodeStrings.shtml) of the SMT-LIB standard for strings says the following:

```
  ; Replace 
  ; (str.replace s t t') is the string obtained by replacing the first occurrence 
  ; of t in s, if any, by t'. Note that if t is empty, the result is to prepend
  ; t' to s; also, if t does not occur in s then the result is s.
  ; Total
  (str.replace String String String String)
```

So replacing over `""` may produce a non-empty string if the string-to-replace is also `""` and the last argument is non-empty.

**Comment by NikolajBjorner** [comment]
@mtrberzi, I also read the draft standard to require a non-empty string in this case.

**Comment by mtrberzi** [comment]
Probably a standards change I overlooked - I'll double-check and correct it for Z3str3.
