### ISSUE TITLE
Z3Exception: Objective function '...' is not supported

### ISSUE THREAD

**Issue by efeg** [Z3Prover/z3#191]
I am working on a lexicographic optimization problem. I have a number of objective functions and constraints that are working fine using Java API. However, for my latest objective function I get a Z3Exception. Related objective function and constraints are explained below. All the variables are `IntExpr`.

Objective function:

    minimize (+ collocation_intensityT1_ collocation_intensityT2_ collocation_intensityT3_)

Related Constraints (note that partition_existence_XX is guaranteed to be either 0 or 1 via other constraints):

    (= collocation_intensityT1_
       (+ (* (+ partition_existence0T1_00 partition_existence0T1_02)
             (+ partition_existence0T1_00 partition_existence0T1_02))
          (* (+ partition_existence1T1_00 partition_existence1T1_02)
             (+ partition_existence1T1_00 partition_existence1T1_02))
          (* (+ partition_existence2T1_00 partition_existence2T1_02)
             (+ partition_existence2T1_00 partition_existence2T1_02))))
    (= collocation_intensityT2_
       (+ (* (+ partition_existence0T2_01 partition_existence0T2_02)
             (+ partition_existence0T2_01 partition_existence0T2_02))
          (* (+ partition_existence1T2_01 partition_existence1T2_02)
             (+ partition_existence1T2_01 partition_existence1T2_02))
          (* (+ partition_existence2T2_01 partition_existence2T2_02)
             (+ partition_existence2T2_01 partition_existence2T2_02))))
    (= collocation_intensityT3_
       (+ (* (+ partition_existence0T3_01 partition_existence0T3_02)
             (+ partition_existence0T3_01 partition_existence0T3_02))
          (* (+ partition_existence1T3_01 partition_existence1T3_02)
             (+ partition_existence1T3_01 partition_existence1T3_02))
          (* (+ partition_existence2T3_01 partition_existence2T3_02)
             (+ partition_existence2T3_01 partition_existence2T3_02))))

When I try to check the model I get Z3Exception. Here is the message I get from the caught exception:

    Objective function '(let ((a!1 (+ 2
                  (* (- 1) partition_existence1T1_00)
                  (* (- 1) partition_existence2T1_00)
                  (* (- 1) partition_existence1T1_02)
                  (* (- 1) partition_existence2T1_02)))
          (a!2 (+ 2
                  (* (- 1) partition_existence1T2_01)
                  (* (- 1) partition_existence2T2_01)
                  (* (- 1) partition_existence1T2_02)
                  (* (- 1) partition_existence2T2_02)))
          (a!3 (+ 2
                  (* (- 1) partition_existence1T3_01)
                  (* (- 1) partition_existence2T3_01)
                  (* (- 1) partition_existence1T3_02)
                  (* (- 1) partition_existence2T3_02))))
      (+ (* (- 1) a!1 a!1)
         (* (- 1)
            (+ partition_existence1T1_00 partition_existence1T1_02)
            (+ partition_existence1T1_00 partition_existence1T1_02))
         (* (- 1)
            (+ partition_existence2T1_00 partition_existence2T1_02)
            (+ partition_existence2T1_00 partition_existence2T1_02))
         (* (- 1) a!2 a!2)
         (* (- 1)
            (+ partition_existence1T2_01 partition_existence1T2_02)
            (+ partition_existence1T2_01 partition_existence1T2_02))
         (* (- 1)
            (+ partition_existence2T2_01 partition_existence2T2_02)
            (+ partition_existence2T2_01 partition_existence2T2_02))
         (* (- 1) a!3 a!3)
         (* (- 1)
            (+ partition_existence1T3_01 partition_existence1T3_02)
            (+ partition_existence1T3_01 partition_existence1T3_02))
         (* (- 1)
            (+ partition_existence2T3_01 partition_existence2T3_02)
            (+ partition_existence2T3_01 partition_existence2T3_02))))' is not supported

I noticed that the exception message does not include variables starting with `partition_existence0T` anywhere. Is this expected or am I doing something wrong?

Thanks

**Comment by NikolajBjorner** [comment]
Are you sure you have the newest unstable branch?
I recently (last week) added purification such that the linear solvers only observe linear objectives and non-linear sub-terms are side-constraints. Prior to that change, I could not optimize non-linear objectives.

The variables 0TX are probably set to either 0 or 1 by equality propagation. Z3 shows the objective function after equality propagation.

**Comment by efeg** [comment]
I think that is probably the reason. I am indeed using the old version -- from August 1st. I will try again with the newest branch. Thanks!
