### ISSUE TITLE
Invalid model using tactic pqffd

### ISSUE THREAD

**Issue by palladin** [Z3Prover/z3#1912]
I found an example that generates an invalid model using 4.8.1 and ```(check-sat-using pqffd)```.
[example.zip](https://github.com/Z3Prover/z3/files/2545743/example.zip)

**Comment by NikolajBjorner** [comment]
I have tried to reproduce this with the latest bits using multiple random seeds, but haven't been able to get invalid models. In another note, with pending updates in the csp branch under github.com/nikolajbjorner/z3.git, this example is destroyed in a few seconds.

**Comment by palladin** [comment]
Thanks! My reproduction is based on https://github.com/Z3Prover/z3/releases/download/z3-4.8.1/z3-4.8.1.016872a5e0f6-x64-win.zip

**Comment by palladin** [comment]
I have tested the example with 4.8.3 and it works! Thanks!
