### ISSUE TITLE
Z3 4.8.2 giving UNSAT for large dimacs formulae

### ISSUE THREAD

**Issue by AniOjha** [Z3Prover/z3#1913]
I have a dimacs problems with around 3000 literals and 8000 clauses which I know is SAT (checked on MiniSAT), but Z3 calls it unsat while it works fine with smaller formulae.

**Comment by AniOjha** [comment]
[1_bmark.txt](https://github.com/Z3Prover/z3/files/2545913/1_bmark.txt)

For instance it doesn't work on this but works on formulae with fewer clauses

**Comment by NikolajBjorner** [comment]
Note: This doesn't reproduce under 4.8.1 release tag.

**Comment by NikolajBjorner** [comment]
Could you update the report with relevant details?
