### ISSUE TITLE
Inconsistent result in Bitvector module of Z3 OCaml and Z3 Python

### ISSUE THREAD

**Issue by SunBeomSo** [Z3Prover/z3#1916]
I would like to check the invalidity of the below formula in bitvector theory:

```
x = (1000000000000000000 + b) / 2 
-> x + (b * 1000000000000000000/x) >= x
```
where ```->``` represents an implication. 

To this end, I wrote two versions of code in OCaml and Python, respectively. However, each of the code produces different results. 

The Z3 OCaml answers the formula is valid (which is incorrect result), while the Z3 Python answers correctly. 

I attach both of the implementations for clarity (I used Z3 4.7.1).

In OCaml:
```
let ctx = Z3.mk_context []

let main() =
  let bits = 64 in
  let x = Z3.BitVector.mk_const_s ctx "x" bits in
  let b = Z3.BitVector.mk_const_s ctx "b" bits in
  let const1 = Z3.BitVector.mk_numeral ctx "1000000000000000000" bits in
  let const2 = Z3.BitVector.mk_numeral ctx "2" bits in
  let pre = Z3.Boolean.mk_eq ctx x (Z3.BitVector.mk_udiv ctx (Z3.BitVector.mk_add ctx const1 b) const2) in
  let con = Z3.BitVector.mk_uge ctx (Z3.BitVector.mk_add ctx x (Z3.BitVector.mk_udiv ctx (Z3.BitVector.mk_mul ctx b const1) x))
                                    x in
  let f = Z3.Boolean.mk_implies ctx pre con in
  let f' = Z3.Boolean.mk_not ctx f in
  let _ = print_endline (Z3.Expr.to_string f) in
  let solver = Z3.Solver.mk_solver ctx None in
  let _ = Z3.Solver.add solver [] in
    (match Z3.Solver.check solver [f'] with
    | UNSATISFIABLE -> (print_endline "unsat"; true)
    | _ -> (print_endline "sat"; false))

let _ = main ()
```
In Python:
```
from z3 import *
import time

def main ():

  bit = 64
  b = BitVec ('b', bit)
  x = BitVec ('x', bit)

  pre = (x == (1000000000000000000 + b)/2)
  con = UGE (x + (b * 1000000000000000000/x), x)

  final = Implies (pre,con)

  print final
  solve (Not (final))

if __name__ == '__main__':
  main ()
```

**Comment by NikolajBjorner** [comment]
If you replace 
    print final
by
    print (final.sexpr())
then you get the output

   (let ((a!1 (bvuge (bvadd x (bvsdiv (bvmul b #x0de0b6b3a7640000) x)) x)))
        (=> (= x (bvsdiv (bvadd #x0de0b6b3a7640000 b) #x0000000000000002)) a!1))

You can observe that the smtlib formatted text uses the identifiers "bvsdiv". This has different semantics than "bvudv", which is created by Z3.BitVector.mk_udiv
