### ISSUE TITLE
How to read the interpretation of a bound variable in 'exists' quantifier assertion.md

### ISSUE THREAD

**Issue by nuppt** [Z3Prover/z3#192]
When I learn the usage of SMT2 by rise4fun.com/z3/tutorial, I was beset by a problem:
`how to eval the interpretation of a bound variable in 'exists' quantifier assertion from a sat model.`

I want to use an example from the tutorial to explain my problem:

In the tutorial, there is a saying: `The command eval evaluates an expression in the last model produced by Z3. It is essentially executing the "function program" produced by Z3.`

So I try to modify the example code following (just change forall  ->  exists), and want to get the value of x in 'exists' quantifier after get-model operation, I find no way to do this. The reason is obvious that the scope of x is only in the body of 'exists' quantifier. But as we all know, Z3 produces an assignment of x in the produced sat model actually, and that is what I want to read.

Can anyone help me?

![2015-08-12 4 20 43](https://cloud.githubusercontent.com/assets/8719521/9219577/76c11036-410e-11e5-83aa-adfd68340d74.png)

![2015-08-12 4 21 15](https://cloud.githubusercontent.com/assets/8719521/9219593/8f45c80e-410e-11e5-831e-502129526bc9.png)

**Comment by wintersteiger** [comment]
The easiest way to do that is by skolemizing the problem up front, i.e., for every existential introduce a new function that depends on all the universal that are in scope. When that is done, the function will have a proper name that you can look up in the model. For an example, see here: http://rise4fun.com/Z3/Eslk9
