### ISSUE TITLE
z3py: setting model completion seems to have no effect

### ISSUE THREAD

**Issue by LeventErkok** [Z3Prover/z3#1920]
This is motivated by an earlier closed issue: https://github.com/Z3Prover/z3/issues/1904 and a more recent stack-overflow question: https://stackoverflow.com/questions/53162290/why-z3py-does-not-provide-all-possible-solutions

It comes down to the following command:

       z3.set_param('model.completion', True)

This seems to have no effect in the produced models; as they are still coming out as partial. For very similar SMT-Lib problems and setting this parameter from the command line, z3 does produce complete models.

A good example is in that closed ticket: https://github.com/Z3Prover/z3/issues/1904#issuecomment-433682289

I'm curious why this setting doesn't seem to have any effect when used from the Python interface, as opposed to the SMTLib level and command-line. For python users, there does not seem to be a work-around, aside from using the `eval` function's `model_completion` parameter; but that seems to be an after-thought and harder to program with. Would be much easier if this parameter setting was respected.

**Comment by NikolajBjorner** [comment]
Some comments:

- the command-line version is going to invoke the sat core, not smt core, and they produce different models.

- model_completion refers to evaluation, not to model representation. So when you evaluate a term under a model it should evaluate to a value term (not an arbitrary expresion), such as true, false, 0, 1, -10, (cons 1 (cons 2 nil)). WIthout model completion, evaluation is not guaranteed to produce a value term. It simplifies the term as much as possible under the current model. If some variable is a don't care (for example under the evaluation -1, -2, -3, -4, it is the case that 5 is a don't care, it can evaluate to itself.

**Comment by LeventErkok** [comment]
@NikolajBjorner 

Thanks for the explanation. The confusion is really arising from the fact that I was expecting the command-line and param-setting to behave in the same way. I do believe this is true in general, but apparently not for model completion; which makes it confusing.

I'm going to put the following down here purely for documentation purposes; feel free to close this ticket if you think there's nothing left to be done regarding this.

Here's the simplest example I can think of:

```
(set-option :produce-models true)
(set-logic QF_BV)
(declare-fun a () Bool)
(declare-fun b () Bool)
(assert a)
(check-sat)
(get-model)
```

With this SMT-Lib benchmark, I get:

```
$ z3 a.smt2
sat
(model
  (define-fun a () Bool
    true)
)
```
And if I turn completion on, I get:
```
$ z3 model.completion=true a.smt2
sat
(model
  (define-fun a () Bool
    true)
  (define-fun b () Bool
    false)
)
```

So, it's just a `get-model` call; there's no evaluation going on at all.

I'd consider the following Python program to be equivalent to this spec:

```
from z3 import *

set_param('model.completion', True)

s = Solver()
a, b = Bools('a b')

s.add(a)
s.check()
print(s.model())
```

But, regardless of the parameter setting (i.e., whether I comment out the `set_param` call or not),  you get the following output:

```
$ python a.py
[a = True]
```

And there doesn't seem to be an easy/equivalent way to trigger the SMTLib behavior from Python.

It is this discrepancy that causes occasional headaches: It bites when you least expect it.

**Comment by NikolajBjorner** [comment]
You are absolutely right.
The command-line has explicit model completion logic for all variables/sorts that are declared. 
The solver objects do not. For starters, they don't know about the constants or functions that are not added to their assertions. The command-line keeps track of declared functions and sorts and performs model completion on everything. 
This is a good example illustrating this situation.
My first instinct was to add a remedy on the solver objects, but they still would not directly know about constants that were declared but not used. Adding this information seems arbitrary. They could traverse the assertions for sorts that are used, but not instantiated (with a finite domain), but I don't see the point: any finte domain or infinite domain would be a model for such un-instantiated sorts because the models are parametric when the simplifications that remove sorts from the solver go into effect.

**Comment by drlagos** [comment]
I've recently been bitten by this as well. Here is a test case where every variable is asserted but model completion fails:

```python
ctx = z3.Context()
solver = z3.Solver(ctx=ctx)
solver.set("model.completion", True)
x = z3.Bool("x", ctx)
y = z3.Bool("y", ctx)
z = z3.Bool("z", ctx)
solver.add(z3.Or([x, y, z]))

while True:
    result = solver.check()
    if result == z3.unsat:
        break
    m = solver.model()
    assert m[x] is not None and m[y] is not None
    solver.add(z3.Or([x != m[x], y != m[y]]))
```

Gives an assertion error.
My solution at the moment is to use evaluate(x, True) instead, not sure of the performance implications of that.

**Comment by andrewvaughanj** [comment]
Have you tried: `model.eval(expression, model_completion=True)`?

**Comment by drlagos** [comment]
Yes that works just fine, I said it in my answer (evaluate is an alias for eval). 
But most examples for z3py use the __getitem__ version, including the [Programming Z3](https://theory.stanford.edu/~nikolaj/programmingz3.html#sec-blocking-evaluations) tutorial.

**Comment by andrewvaughanj** [comment]
Ah, sorry!

As far as I'm aware, the behaviour of `__getitem__` not doing completion has always been that way (or, at least has been that way for ~5 years).

**Comment by NikolajBjorner** [comment]
It is not going to be practical to have model_completion ensure that non-relevant variables/functions are given values in the model. The smt core model construction throws away non-relevant values from the model. The behavior of eval is also different than model access. Use eval. The tutorial example for block_model uses eval.
