### ISSUE TITLE
Integrating third-party SAT solvers

### ISSUE THREAD

**Issue by rainoftime** [Z3Prover/z3#1921]
For tactics based on eager bit-blasting, it might be helpful to integrate third-party SAT solvers as tunable backends.  Would you please give some advices on implementing such facilities?  I notice that the most relevant souce files include `z3/src/sat/tactic{atom2bool, goal2sat, sat_tactic}`

**Comment by NikolajBjorner** [comment]
One approach: use qffd tactic with a very short timeout, e.g., 
sat.conflict.max = 10 or a bound on restarts. Then the resulting goal state is a set of clauses.

The main challenge is to integrate model convertion is relatively opaque. 
A model of the sub-goal produced by qffd and a short "timeout" is not necessarily
going to correspond to a model of the original formula, especially if Z3 gets to perform in-processing.
The method Z3_goal_convert_model advertises that you can supply a goal and 
model and have it converted into a model of the original goal.
Thus, if you find a model m using some independent means for goal g, 
then call this method with g and m to produce a model of the original goal.

Besides "qffd", you can stitch together tactics as you please. The best guide is to look at
how this is done in the source code (the tactic that handles qfbv under src/tactis/smtlogics),
or the rise4fun tutorial on tactics from SMTLIB2. Each SMTLIB2 command corresponds closely
to an API.
