### ISSUE TITLE
get-unsat-assumptions for JavaAPI not found

### ISSUE THREAD

**Issue by sohah** [Z3Prover/z3#1923]
According to the SMTLib doc [here](http://smtlib.cs.uiowa.edu/papers/smt-lib-reference-v2.5-r2015-06-28.pdf) we can check sat using `check-sat-assuming` and then one can determine the unsatisfiable assumptions using `get-unsat-assumptions`. 

Reflecting that on Z3 in JavaAPI, I can see `checkAssuming` API doing the same thing as the`check-sat-assuming` but I can't seem to find anything that is doing something similar to `get-unsat-assumptions`, all I can find is `getUnsatCore` api. 

`get-unsat-assumptions` needs to be supported on the JavaAPI of Z3.

**Comment by NikolajBjorner** [comment]
getUnsatCore returns the unsatisfiable assumptions.
