### ISSUE TITLE
Missing VCOMP140.dll for Z3 version > 4.6.0

### ISSUE THREAD

**Issue by timo92** [Z3Prover/z3#1924]
Running z3 on windows maschines yields an exception regarding a missing dll (VCOMP140.dll). This issue was already encountered and fixed with respect to version 4.5.0 and VCOMP110.dll #788.
I can't reproduce the issue with version 4.5 and 4.6 but the dll is missing for 4.7.1 and 4.8.1.
I also noticed that none of the dll's listed in [VS_RUNTIME_PATS](https://github.com/Z3Prover/z3/blob/master/scripts/mk_win_dist.py#L248) are part of the released zip archives of the affected versions but they can be found in releases of earlier versions.

**Comment by NikolajBjorner** [comment]
I have added these to the zip files for 4.8.1 and updated the scripts so it should work in future releases.
