### ISSUE TITLE
z3 4.8.3 fails at (query q :print-certificate true)

### ISSUE THREAD

**Issue by shiatsumat** [Z3Prover/z3#1926]
I tried z3 4.8.1 and 4.8.3 but both failed at `(query q :print-certificate true)`, while this does work for z3 4.7.1.
Here is an example from https://rise4fun.com/z3/tutorialcontent/fixedpoints executed on z3 4.8.3.
```
$ z3 -in
(declare-rel mc (Int Int))
(declare-var n Int)
(declare-var m Int)
(declare-var p Int)

(rule (=> (> m 100) (mc m (- m 10))))
(rule (=> (and (<= m 100) (mc (+ m 11) p) (mc p n)) (mc m n)))

(declare-rel q1 (Int Int))
(rule (=> (and (mc m n) (< n 91)) (q1 m n)))
(query q1)
unsat
(query q1 :print-certificate true)
unsat
NOT IMPLEMENTED YET!
Segmentation fault: 11
```

**Comment by NikolajBjorner** [comment]
@agurfinkel: proofs and cerificates (both used when there is a proof trail or a model) are not implemented in spacer.

**Comment by shiatsumat** [comment]
Thank you so much. I should have explicitly noted that this happens when I use Spacer.

**Comment by shiatsumat** [comment]
Thank you for the commit!!
https://github.com/Z3Prover/z3/pull/1930
