### ISSUE TITLE
Request for a multiline comment in z3

### ISSUE THREAD

**Issue by shiatsumat** [Z3Prover/z3#1932]
Oftentimes I am inclined to write a multi-line comment but z3 does not accept usual Lisp-like multi-line comments. I wish to have a multi-line comment in z3.
```
$ z3 -in
; this is a single-line comment
(echo "hello")
hello
#| when I try to write a multi-line comment
(error "line 3 column 1: invalid bit-vector literal, expecting 'x' or 'b'")
```

**Comment by NikolajBjorner** [comment]
You can write a string that spans multiple lines:

(echo "line1
line2
")

**Comment by shiatsumat** [comment]
The multiline string feature is great and I sometimes use that workaround, but I was wondering if there was a room for multiline comments in z3.

**Comment by shiatsumat** [comment]
Thank you so much!!
