### ISSUE TITLE
Injectivity function over a custom datatype

### ISSUE THREAD

**Issue by francoisthire** [Z3Prover/z3#1933]
I am using version 4.5.1 of z3 and the answer to the following example is "unknown":

```
(set-option :smt.auto-config false) ; disable automatic self configuration
(set-option :smt.mbqi false) ; disable model-based quantifier instantiation
(declare-datatypes () ((Color red green blue)))
(declare-fun next (Color) Color)
(declare-fun prev (Color) Color)
(assert (forall ((x Color))
                (! (= (prev (next x)) x)
                   :pattern ((next x))
                   )))
(assert (= (next red) green))
(assert (= (next green) blue))
(assert (= (next blue) red))
(assert (= (prev red) blue))
(assert (= (prev blue) green))
(assert (= (prev green) red))
(check-sat)
```

This example declares an enumeration "Color" with three components and then declare an injective function `next` over this enumeration. I use the trick explained in the z3 guide to postulate that `next` is an injective function. But even if I defined this function over all the colors, z3 cannot say that it is satisfiable. 

If I remove the hypothesis that `next` is injective, then `z3` gives the following model:

```
(model 
  (define-fun next ((x!0 Color)) Color
    (ite (= x!0 red) green
    (ite (= x!0 green) blue
    (ite (= x!0 blue) red
      green))))
  (define-fun prev ((x!0 Color)) Color
    (ite (= x!0 red) blue
    (ite (= x!0 blue) green
    (ite (= x!0 green) red
      blue))))
)
```

Which corroborates the fact that there is a model of an injective function for `next`. But I have the impression that `z3` is missing the fact that there are only three cases to define the function `next` which is why it does not find a model with the assumption that `next` is injective.

**Comment by NikolajBjorner** [comment]
quantifier instantiation without mbqi is _not_ a decision procedure for finite domains. You need mbqi to validate that the state reached after instantiation really satisfies all quantifiers.
