### ISSUE TITLE
Z3 optimize pb.compile_equality gives sub-optimal solution

### ISSUE THREAD

**Issue by burgholzer** [Z3Prover/z3#1934]
I am currently using the optimisation engine of Z3 via the C++-API to find an optimal solution for a strictly boolean problem with an arithmetic objective/cost function.

After some experimenting with the options offered by the optimize solver I stumbled upon the _pb.compile_equality_ option which defaults to false. When enabling this option I noticed that my set of benchmarks was solved (considerably) faster. However the produced results where not globally optimal, e.g. `opt.check()` yielded a model with cost/objective value 29, while the same instance with _pb.compile_equality_ set to false yields the correct optimum of 19.

To further clarify the problem: If I add a constraint of the form `objective < currentlyFoundMinimum` after the first `opt.check()` call returned SAT and call `opt.check()` again, this also yields SAT in some instances. Furthermore this then results in a model with the (expected) optimal cost.

Is this behaviour expected or is there something fishy going on?

**Comment by NikolajBjorner** [comment]
fishy, sounds like a bug in the pre-processor

**Comment by burgholzer** [comment]
Would you like me to provide a minimum working example to reproduce the issue?

**Comment by NikolajBjorner** [comment]
please

**Comment by burgholzer** [comment]
I attached the minimum working example. It tests 3 three problem instances. The optimal solutions for each of them have objective value
1. 19,
2. 23,
3. 30

Two kinds of problems occur when computing the solutions to the problems:
1. enabling pb.compile_equality generally produces suboptimal results,
2. the objective function consists of two main components. Exchanging their order influences the result. (even when they yield the same result, the computation time varies heavily)

In my opinion neither of these problems should occur.

The results on my computer can be summarised in the following way:
- Original order of objective function terms with pb.compile_equality: 29 / 29 / 36,
- Original order of objective function terms without pb.compile_equality: 19 / 24 / 30,
- Exchanged order of objective function terms with pb.compile_equality: 29 / 24 / 30,
- Exchanged order of objective function terms without pb.compile_equality: 19 / 23 / 30,

The last combination of options does yield the optimal objective for each problem. However, especially the third problem takes extremely long compared to the other option combinations.

Furthermore, as explained in the original post, successive calls to `opt.check()`, after adding a constraint of the form `objective < currentlyFoundMinimum`, finally yield the optimal solution in all cases. However, this takes very very long and should not at all be necessary.

I have marked the places in the code where to change the options (including descriptions) with comments. 

I hope this helps and am looking forward to your reply.

[mwe.zip](https://github.com/Z3Prover/z3/files/2587206/mwe.zip)

**Comment by NikolajBjorner** [comment]
There is clearly a bug.

**Comment by NikolajBjorner** [comment]
At this point, as far as I can tell it is a bug/regression introduced after 4.7.1, so while I figure out what is wrong, you may be able to use the earlier version for experiments.
