### ISSUE TITLE
Large discrepancy between time to solve formula via API vs command line

### ISSUE THREAD

**Issue by SeanHeelan** [Z3Prover/z3#1936]
I originally mentioned this problem as a comment on #1870 (see [this](https://github.com/Z3Prover/z3/issues/1870#issuecomment-429826942) and [this](https://github.com/Z3Prover/z3/issues/1870#issuecomment-436696995)) but as that issue is now closed I thought I should open a new one for this problem specifically as it is quite bad. 

To summarise, if I create large models (10s of thousands of vars) via the Python API as follows:

```
s = z3.Solver()
x = z3.BitVec('x', 32)
y = z3.BitVec('y', 32)
....
s.add(...)
....
s.check()
```

then the call to `s.check()` takes `N` seconds. However, if instead of `s.check()` I call `s.sexpr()`, log the output to `model.smt2` and invoke `z3 model.smt2` on the command line it takes `M` seconds where `M` can be an order of magnitude, or more, less than `N`. 

To see this download [example.zip](https://github.com/Z3Prover/z3/files/2478621/example.zip). Inside you will find Python code for building models. 

It can be ran with `./userstore.py -o /tmp/outputdir`. When it creates the 6th model you will see it takes 80 seconds or so to resolve, while the 7th one takes even longer. Those models will be logged into the output directory and, if you append on a `(check-sat)` call, they can be solved on the command line in a fraction of the time. 

I have also uploaded that 6th model [here](https://github.com/Z3Prover/z3/files/2478624/model6.txt) so you can simply download that if you want. It takes about 5 seconds to resolve if you run `z3 model6.smt2`. 

I'm using the latest version of z3 from git, on Fedora 29.

**Comment by NikolajBjorner** [comment]
Try:

    num_lines = args.start_line
    while num_lines <= args.max_lines:
        s = z3.SolverFor("QF_FD")
        instance_states = []

The default solver is the general SMT solver. But the engine for "QF_FD" is a more efficient engine specialized for propositional (finite domain) SAT problems.
You can also create one-shot solvers from the "qffd" tactic. This opens up inprocessing techniques that are available only for non-incremental mode (where the solver is used only for a single call).

**Comment by NikolajBjorner** [comment]
The default solver works as follows:
- In the very first call it uses a one-shot solver.
- If there is another call, it switches to incremental mode. If it doesn't know any properties of the formulas you use, it will rely on a general purpose SMT core. 
You can ensure the one-shot mode by creating a new solver every time you make a call.
You can copy assertions from one solver to another: s2.add(s1.assertions()), or use deep copy (s2 = s1.translate(s1.ctx)).

**Comment by SeanHeelan** [comment]
Thanks! Creating a new solver object addresses the issue. 

Out of curiosity, am I hitting some sort of edge case here in that subsequent formulae take far longer in incremental mode than they otherwise would? I am obviously missing the context for this design decision and so I assume that in most situations the behaviour is correct. However, when I asked around about the discrepancy in run times I had encountered a few people complained they had seen similar problems and had no idea what could be causing it. It may be mentioned in the docs somewhere, but if not it would be worth drawing attention to the potential for the problem to occur, and possible resolutions.

**Comment by NikolajBjorner** [comment]
Perhaps http://theory.stanford.edu/~nikolaj/programmingz3.html#sec-incrementality

**Comment by SeanHeelan** [comment]
That's great, thank you
