### ISSUE TITLE
Track relations between bit-vector and Boolean variables after bit-blasting

### ISSUE THREAD

**Issue by rainoftime** [Z3Prover/z3#1946]
In many tactics, if a bit-vector formula `F_bv` is not solved by word-level pre-processing, it will be bit-blasted into an SAT formula `F_bool`, and the internal model converter can track the relations of the two constraints. 

However, is there any high-level and convenient approach to query such information, e.g.,  which Boolean variables correspond to which bit-vector variable?  (This might not be trivial, as some word-level tactics such as `bv_size_reduction` may make thinings complicate)

Consider the following problem. After applying the tactic `tac`, four Boolean variables `k!0, k!1, k!2, k!3` are created in the SAT formula `sat_fml`.
~~~~
from z3 import *
x = BitVec('x', 2)
y = BitVec('y', 2)
bv_fml = x + y == 2
tac = Then(Tactic('simplify'), Tactic('bit-blast'))
sat_fml = tac(bv_fml).as_expr()
s = Solver()
~~~~
One moitvation is to use the "assumption based solving" facility, which may be useful for implementing "optimization module theory" algorithms.  For instance, we would like to maximize the value of `y` subject to `bv_fml`.
-  suppose we know `k!2, k!3` correspond to the first and second bits of variable `y`. 
-  we can solve `s.check(k!3)`  to know if $y$ might be equal to 2 in all models of `bv_fml`.

**Comment by NikolajBjorner** [comment]
not quite at this point. It would require some changes. bit_blaster_model_converter.cpp line 98 creates bit-vector values for variables that are declared in the target model. In a changed implementation, it could take a source model where k!1, k!2, k!3 are not given any values and produce symbolic expressions for these. In this way you could evaluate x, y under a model (the right terminology is model_converter) produced from tac(bv_fml) and obtain these symbolic values.

**Comment by rainoftime** [comment]
I noticed that, in function `sat_tactic::operaor()` of `z3/src/sat/sat_tactic.cpp`,  it seems the data structure `atom2bool_var map(m)` maintains a map between variables after bit-blasting (`k!0, k!1, k2, ...`) to the Boolean variables inside the SAT engine.  

Is it possible to get the mapping between bit-vector variables `x, y` and variables `k!0, k!1, ...` in `sat_tactic` (possibly from `goal2sat`)?  If so, some incremental-SAT based algorithms might be implemented at `sat_tactic` where we iteract with the SAT engine. Thank you!

**Comment by NikolajBjorner** [comment]
This is not the right place: there are no references to bit-vectors when the flow reaches sat_tactic.
The src/tactic/bv/bit_blaster_model_converter.cpp is the place where the bit-vectors are handled.

**Comment by rainoftime** [comment]
Thanks.  I will try `src\sat\sat_sovler\inc_sat_solver.cpp` (by forcing to use it to solve QF_BV problems).
It seems that I can query the relations from the `scoped_ptr<bit_blaster_rewriter> m_bb_rewriter` field of `inc_sat_solver`, since `bit_blaster_model_converter` also relies on `bit_blaster_rewriter`.
