### ISSUE TITLE
very heavy regression: broken detection of unbounded objective

### ISSUE THREAD

**Issue by cheshire** [Z3Prover/z3#195]
Hi All,

I've recently upgraded from 9734407cde074c5bc65029548919f4a94f2d905f to latest 9ad065a538815a6c13b6d890920f44d9418df8d3, and it looks like every optimization involving unbounded objectives is timing out.
Would it be possible to add those to regression test suite?
Even

```
(declare-fun x () Int)

(maximize x)

(check-sat)
```

is timing out.

Cheers,
George

**Comment by cheshire** [comment]
From bisecting, the regression first occurs in d815cf9b7b658a5393d8cc96ae1b6af13adb67cb

**Comment by NikolajBjorner** [comment]
it is fixed with 9ad065a..7c87096
