### ISSUE TITLE
Linux only regression

### ISSUE THREAD

**Issue by LeventErkok** [Z3Prover/z3#1953]
The following benchmark

```
(declare-const a String)
(declare-const b String)
(declare-const c String)
(assert (str.contains a b))
(assert (str.contains a c))
(assert (not (str.contains b c)))
(assert (not (str.contains c b)))
(check-sat)
(get-model)
```
which comes right out of https://rise4fun.com/Z3/tutorial/sequences, is surprisingly answered `sat` on a build on Mac OSX, but is answered `unknown` when run on Linux. This was answered `sat` on both platforms about two weeks ago or so; so far as I can tell. I'm not sure why Linux build is having hard time with it, while the Mac build is just fine.

Both builds are quite fresh from the master. I don't have a Windows box handy to try it.

**Comment by NikolajBjorner** [comment]
z3 is flickle on this example on all platforms. While the behavior ought to be the same across platforms, barring timeout behavior, the answers fluctuate when setting smt.random_seed=<n> for different values of n.

**Comment by NikolajBjorner** [comment]
the solver is now much more stable on this.

**Comment by LeventErkok** [comment]
@NikolajBjorner Thanks! I think this is still in your side branch, right? When should we expect it to get to master?

**Comment by NikolajBjorner** [comment]
it is in master, but it is highly unstable these days. Best to wait until Monday.
