### ISSUE TITLE
int.to.str cannot show unsat

### ISSUE THREAD

**Issue by MontyThibault** [Z3Prover/z3#1957]
This example leads to an infinite hang.

```
(declare-const n Int)

(assert (= (int.to.str n) "asdf"))

(check-sat)
```

**Comment by DvonHolten** [comment]
is it really 'inifinite' ? or just 'very long' ? it seems, it is busy iterating through all the integers - there are quite a few of them - to find a value, which is converted to a string, equal to "asdf". I think, Z3 has no idea about the fact that _no_ converted Int would result in "asdf"

**Comment by NikolajBjorner** [comment]
It is incomplete, and doesn't realize it.

**Comment by NikolajBjorner** [comment]
Note however, that

   z3 1957.smt2 smt.string_solver=z3str3

quickly solves this
