### ISSUE TITLE
Disjunctive of objectives in opt solver

### ISSUE THREAD

**Issue by rainoftime** [Z3Prover/z3#1962]
Consider the following program. The two objectives for optimization are {max(x), max(y)}. Intuitively, the result should be {max(x)=10, max(y)=10}. However, after calling `opt.check()`, I got the result `x: 10 y: 1`.  

It seems that opt will consider the multiple objectives as a "conjunction", and optimize them following some priorities? 

How should we correctly use the opt API  to get the "disjunctive" results of the objectives? (In this case, {max(x)=10, max(y)=10}) Must I create several opt solvers? Thank you.
~~~~
void test_opt() {
    context c;
    optimize opt(c);
    params p(c);
    p.set("priority",c.str_symbol("pareto"));
    opt.set(p);
    expr x = c.int_const("x");
    expr y = c.int_const("y");
    opt.add(10 >= x && x >= 0);
    opt.add(10 >= y && y >= 0);
    opt.add(x + y <= 11);
    optimize::handle h1 = opt.maximize(x);
    optimize::handle h2 = opt.maximize(y);
    if (sat == opt.check()) {
        std::cout << x << ": " << opt.lower(h1) << " " << y << ": " << opt.lower(h2) << "\n";
    }
}
~~~~

**Comment by LeventErkok** [comment]
@rainoftime 

What you're looking for are "independent objectives." Try with:

       p.set("priority",c.str_symbol("box"));

See here: https://rise4fun.com/Z3/tutorialcontent/optimization#h24

**Comment by rainoftime** [comment]
Thank you!
