### ISSUE TITLE
Distributed cube & conquer

### ISSUE THREAD

**Issue by palladin** [Z3Prover/z3#1965]
I'm wondering if there is a way to use the cube & conquer API to serialize and distribute cubes for large scale distributed cube & conquer scenarios.

**Comment by NikolajBjorner** [comment]
Yes, I have a system that does this in Azure with blob store, queues, tables to manage state and communication. The simplest is to serialize solver state to SMT-LIB2 using the methods that save a solver state to a string. The C&C interface offers different ways to integrate cubing: you can generate a single set of several cubes and then solve them. This is mostly how march_cu can be used (see Marijn's GitHub account which provides a C&C solver based on march + lingeling/glucose) from scripts. You can also generate two cubes at a time and split the search space in a way similar to Treengeling. Some distributed systems use cubes as assumptions and can therefore share lemmas. You also have the option to assert cubes and obtain better simplification. The cubing interface is really only geared towards propositional problems (QF_FD), there is basically no support yet for informed cubing for more general SMT domains.

**Comment by palladin** [comment]
I have some experience with the Azure stack and it would be very useful if it is possible to share with the community a C&C Azure sample.
