### ISSUE TITLE
soundness bug with str.to.int

### ISSUE THREAD

**Issue by LeventErkok** [Z3Prover/z3#1966]
This got introduced very recently; used to get `unsat` for it till last week:

```
(set-option :produce-models true)
(set-logic ALL)
(declare-fun s () String)
(define-fun  l  () Int (str.to.int s))
(assert (not (=> (and (>= l 0) (< l 10)) (= (str.len s) 1))))
(check-sat)
(get-model)
```

Essentially, the benchmark is proving that if the converted number is between 0 and 9, then the starting string should have precisely one character. This is now producing `""` as a model for `s`, which is incorrect. Interestingly, z3 does know that it generated an invalid model:

```
$ z3 model_validate=true a.smt2
sat
(error "line 6 column 10: an invalid model was generated")
(model
  (define-fun s () String
    "")
)
```

**Comment by NikolajBjorner** [comment]
fixed
