### ISSUE TITLE
Unicode support and byte order marks

### ISSUE THREAD

**Issue by cpitclaudel** [Z3Prover/z3#197]
Hi,

z3 does not seem to process utf-8 encoded documents properly. I tried the following:

    (echo "Nikolaj Bjørner")

But all I got back was

    Nikolaj BjÃ¸rner

I then tried to add a Byte-Order mark to my file, but this caused z3 to complain:

```
(error "line 1 column 1: unexpected character")
(error "line 1 column 2: unexpected character")
(error "line 1 column 3: unexpected character")
Nikolaj BjÃ¸rner
```

Is this a known problem? Is there a way to at least tell z3 to ignore the BOM?

Thanks!

**Comment by NikolajBjorner** [comment]
Z3 supports the common SMT-LIB2 format. Does it support Unicode in the first place?

**Comment by cpitclaudel** [comment]
This seems to be what the latest standard says:

> SMT-LIB source files consist of Unicode characters in any 8-bit encoding, such as UTF-8, that extends the original 7-bit US-ASCII set.  While not technically Unicode,  the ISO 8859-1 character set is also allowed since it coincides with the first 256 characters of UTF-8.

There is no mention of byte-order marks, so I imagine this means they are not supported.
