### ISSUE TITLE
Questions about Bit-vector optimization engine

### ISSUE THREAD

**Issue by rainoftime** [Z3Prover/z3#1970]
It seems that "optimization module theory" engine for bit-vectors is not implemented in `z3/src/opt/optsmt.cpp` (Thus algorithms like "Symba" do not work). 
Instead, it is based on bit-blasting and the incremental SAT engine in `z3/src/sat/sat_solver/inc_sat_solver.cpp`? 

If so, does Z3 work in the style of **Binary search**? For example, suppose `x` is a bit-vector of length 4 and the goal is to maximize it.  Assume `x` is bit-blasted into 4 Boolean variables `b3, b2, b1, b0`.
1. First check under assumption `b3 = 1`
2. If the first step is sat, then check under assumption `b3 = 1, b2 = 1`; else `b3 = 0, b2 = 1`
3. ...

Or does Z3 reduces to  the problem a **Weighted MaxSAT** problem (by assigning different weights to `b3, b2, b1, b0`)?

In addition, how does Z3 perform multi-objectives optimizations of bit-vectors, especially for **independent objectives**? 
Will it optimize the objective one-by-one (e.g., solve several independent MaxSAT problems) 
Thank you!

**Comment by LeventErkok** [comment]
@rainoftime 

Did you see Nikolaj and Anh-Dung's paper? 

https://pdfs.semanticscholar.org/a938/cdcf32f340fd654aa2e9d372f3eff9fabb62.pdf

**Comment by rainoftime** [comment]
@LeventErkok  I just went through the paper. According to the paper, the bit-vector optimization problem is reduced to weighted MaxSAT solving.

I am still a bit confused about the "independent multi-objectives" problem. Algorithm 5 in the paper addresses the prolem. But Algorithm 5 looks similar to the algorithm(s) implemented in `z3\src\opt\optsmt.cpp`, which is mainly for linear ad integer constraints.

**Comment by NikolajBjorner** [comment]
I do something simple for bitvectors, but they are handled. It is possible to be more efficient if applications see strain on runtime.

**Comment by rainoftime** [comment]
Now I understand the weighted MaxSAT encoding. It seems "eager" for a single objective. But when optimizing the two independent objectives (E.g., { max(x), max(y) } as in the following example ), will Z3 solve two "independent" MaxSAT problems (they only share the hard constraints)?
~~~~
void test_opt() {
    context c;
    params p(c); p.set("priority",c.str_symbol("box"));
    optimize opt(c); opt.set(p);
    expr x = c.bv_const("x", 8);
    expr y = c.bv_const("y", 8);
    opt.add(10 >= x && x >= 0);
    opt.add(10 >= y && y >= 0);
    optimize::handle h1 = opt.maximize(x);
    optimize::handle h2 = opt.maximize(y);
    if (sat == opt.check()) {
        std::cout << x << ": " << opt.lower(h1) << " " << y << ": " << opt.lower(h2) << "\n";
    }
}
~~~~
