### ISSUE TITLE
Invalid model using parallel QF_FD

### ISSUE THREAD

**Issue by palladin** [Z3Prover/z3#1971]
I found an example that generates an invalid model using https://github.com/Z3Prover/z3/releases/download/z3-4.8.3/z3-4.8.3.7f5d66c3c299-x64-win.zip
[example.zip](https://github.com/Z3Prover/z3/files/2620003/example.zip)

**Comment by palladin** [comment]
It is probably a race condition because with the same z3 binaries and example I couldn't reproduce it in a different machine.

**Comment by NikolajBjorner** [comment]
thanks, probably with different sat.random_seed values will do the trick. However, it takes some time to debug these ones (they are related with copying inferences that transform models).

**Comment by palladin** [comment]
Thanks! Based on my experiments, it is relative easy to generate an invalid model but difficult to generate a reliable reproduction sample.

**Comment by NikolajBjorner** [comment]
It was fixed in the above pushes
