### ISSUE TITLE
Z3 version 4.8.3 slower and unable to solve problem that was solved by Z3 version 4.8.1

### ISSUE THREAD

**Issue by pjljvandelaar** [Z3Prover/z3#1979]
We noticed a drop in performance when z3 version 4.8.3 was released.
Note that we don't mind Z3 becoming slower on simple problems when it becomes able to solve complicate problems (or is able to solve them considerable faster).
However, it seemed that more complicate problems took considerably more time.

To make this observation quantitative, we ran a benchmark on the smt2 files that are passed to Z3 when executing all TorXakis examples (for more info on the examples see https://github.com/TorXakis/TorXakis/tree/develop/examps). 
The smt2 files were made using z3 version 4.8.1 and are attached below:
[smtlog.zip](https://github.com/Z3Prover/z3/files/2623623/smtlog.zip)

During this benchmark, we decided to killed z3 version 4.8.3 after 164620 seconds on the smt2 file 
`logSMT.2018-11-21-15-42-14.105276.smt2`, since it seems unable to solve it!
Note that z3 version 4.8.1 solves this smt2 file in just 973 seconds.

For all other benchmarks see the table below:
Factor less than 1 is an improvement.

benchmark | v 4.8.1  | v 4.8.3  | factor
-- | -- | -- | --
logSMT.2018-11-21-15-33-50.8787886.smt2 | 0,0250 | 0,0426 | 1,71
logSMT.2018-11-21-15-33-50.8792904.smt2 | 0,0247 | 0,0231 | 0,94
logSMT.2018-11-21-15-33-50.8827887.smt2 | 0,0764 | 0,0853 | 1,12
logSMT.2018-11-21-15-33-50.8962892.smt2 | 0,0271 | 0,0379 | 1,40
logSMT.2018-11-21-15-33-52.4122794.smt2 | 0,0168 | 0,0249 | 1,49
logSMT.2018-11-21-15-33-52.6807788.smt2 | 0,1652 | 0,1910 | 1,16
logSMT.2018-11-21-15-33-52.995277.smt2 | 0,0748 | 0,0990 | 1,32
logSMT.2018-11-21-15-33-53.7597708.smt2 | 0,0168 | 0,0282 | 1,68
logSMT.2018-11-21-15-33-54.6157668.smt2 | 0,0161 | 0,0222 | 1,38
logSMT.2018-11-21-15-33-56.132756.smt2 | 0,0163 | 0,0231 | 1,42
logSMT.2018-11-21-15-33-57.2392481.smt2 | 0,0168 | 0,0232 | 1,38
logSMT.2018-11-21-15-33-57.4742487.smt2 | 0,8566 | 0,7538 | 0,88
logSMT.2018-11-21-15-33-59.901016.smt2 | 0,0171 | 0,0266 | 1,55
logSMT.2018-11-21-15-34-00.629011.smt2 | 0,0180 | 0,0226 | 1,25
logSMT.2018-11-21-15-34-04.9592091.smt2 | 0,0184 | 0,0220 | 1,20
logSMT.2018-11-21-15-34-05.5417043.smt2 | 0,0180 | 0,0223 | 1,24
logSMT.2018-11-21-15-34-07.2756944.smt2 | 0,0165 | 0,0216 | 1,31
logSMT.2018-11-21-15-34-07.8481929.smt2 | 0,0167 | 0,0214 | 1,29
logSMT.2018-11-21-15-34-08.6726855.smt2 | 0,8502 | 0,4493 | 0,53
logSMT.2018-11-21-15-34-10.0806761.smt2 | 84,1520 | 268,5495 | 3,19
logSMT.2018-11-21-15-34-46.0254771.smt2 | 0,0202 | 0,0270 | 1,34
logSMT.2018-11-21-15-35-45.5038235.smt2 | 0,0172 | 0,0221 | 1,28
logSMT.2018-11-21-15-35-48.0198081.smt2 | 0,0180 | 0,0222 | 1,24
logSMT.2018-11-21-15-35-49.9062961.smt2 | 0,0172 | 0,0225 | 1,30
logSMT.2018-11-21-15-35-51.8152858.smt2 | 0,0584 | 0,0819 | 1,40
logSMT.2018-11-21-15-35-55.5192596.smt2 | 0,9811 | 0,7707 | 0,79
logSMT.2018-11-21-15-36-30.6272754.smt2 | 0,8233 | 0,7074 | 0,86
logSMT.2018-11-21-15-36-42.2092015.smt2 | 1,1349 | 0,9329 | 0,82
logSMT.2018-11-21-15-36-57.9840565.smt2 | 0,0196 | 0,0213 | 1,09
logSMT.2018-11-21-15-36-59.9445442.smt2 | 0,0192 | 0,0221 | 1,15
logSMT.2018-11-21-15-37-01.7280313.smt2 | 0,0189 | 0,0250 | 1,33
logSMT.2018-11-21-15-37-03.6515184.smt2 | 0,0195 | 0,0234 | 1,20
logSMT.2018-11-21-15-37-05.6805065.smt2 | 0,0219 | 0,0228 | 1,04
logSMT.2018-11-21-15-37-16.7811513.smt2 | 0,0189 | 0,0221 | 1,17
logSMT.2018-11-21-15-37-37.8702793.smt2 | 0,0412 | 0,0365 | 0,89
logSMT.2018-11-21-15-37-41.5859871.smt2 | 0,0397 | 0,0396 | 1,00
logSMT.2018-11-21-15-37-45.2387915.smt2 | 0,3066 | 0,2445 | 0,80
logSMT.2018-11-21-15-37-51.6038667.smt2 | 0,0360 | 0,0353 | 0,98
logSMT.2018-11-21-15-37-55.2952476.smt2 | 0,0299 | 0,0281 | 0,94
logSMT.2018-11-21-15-37-58.3670365.smt2 | 0,1041 | 0,0666 | 0,64
logSMT.2018-11-21-15-38-03.3051455.smt2 | 0,0629 | 0,0516 | 0,82
logSMT.2018-11-21-15-38-08.3397822.smt2 | 0,0267 | 0,0288 | 1,08
logSMT.2018-11-21-15-38-11.4577918.smt2 | 0,0232 | 0,0254 | 1,09
logSMT.2018-11-21-15-38-12.5892498.smt2 | 0,0249 | 0,0282 | 1,13
logSMT.2018-11-21-15-38-13.8051496.smt2 | 1,0823 | 0,4580 | 0,42
logSMT.2018-11-21-15-38-21.4079486.smt2 | 0,1269 | 0,0744 | 0,59
logSMT.2018-11-21-15-38-23.2310692.smt2 | 10,9245 | 2,0656 | 0,19
logSMT.2018-11-21-15-38-43.5060369.smt2 | 2,3210 | 1,5987 | 0,69
logSMT.2018-11-21-15-42-14.105276.smt2 | 973,0083 | 164620,9296 | 169,19
logSMT.2018-11-21-16-00-07.0915554.smt2 | 0,0180 | 0,0529 | 2,95
logSMT.2018-11-21-16-00-08.2175651.smt2 | 0,0169 | 0,0236 | 1,39
logSMT.2018-11-21-16-00-09.4110953.smt2 | 0,0170 | 0,0255 | 1,49
logSMT.2018-11-21-16-00-10.5508705.smt2 | 0,0166 | 0,0270 | 1,62
logSMT.2018-11-21-16-00-11.7444.smt2 | 0,0463 | 0,0649 | 1,40
logSMT.2018-11-21-16-00-13.4067085.smt2 | 0,0323 | 0,0450 | 1,39
logSMT.2018-11-21-16-00-14.7503588.smt2 | 0,0731 | 0,0890 | 1,22
logSMT.2018-11-21-16-00-16.7925852.smt2 | 0,0378 | 0,0576 | 1,52
logSMT.2018-11-21-16-00-18.2353535.smt2 | 0,0618 | 0,0782 | 1,27
logSMT.2018-11-21-16-00-19.9885107.smt2 | 0,0793 | 0,0876 | 1,10
logSMT.2018-11-21-16-00-21.8030702.smt2 | 0,0596 | 0,0666 | 1,12
logSMT.2018-11-21-16-00-24.4540276.smt2 | 19,4797 | 113,9103 | 5,85
logSMT.2018-11-21-16-01-01.3769848.smt2 | 34,3561 | 175,5398 | 5,11
logSMT.2018-11-21-16-03-19.1722118.smt2 | 0,0277 | 0,0337 | 1,21
logSMT.2018-11-21-16-03-20.5487019.smt2 | 0,0362 | 0,0511 | 1,41
logSMT.2018-11-21-16-03-21.9532665.smt2 | 0,0248 | 0,0339 | 1,37
logSMT.2018-11-21-16-03-23.2622626.smt2 | 0,0214 | 0,0355 | 1,65
logSMT.2018-11-21-16-03-23.3332623.smt2 | 0,0221 | 0,0294 | 1,33
logSMT.2018-11-21-16-04-35.3276261.smt2 | 0,0328 | 0,0420 | 1,28
logSMT.2018-11-21-16-04-36.8115312.smt2 | 0,0327 | 0,0387 | 1,18
logSMT.2018-11-21-16-04-39.1860184.smt2 | 0,0841 | 0,0732 | 0,87
logSMT.2018-11-21-16-04-43.0369942.smt2 | 436,4655 | 3634,8789 | 8,33
logSMT.2018-11-21-16-16-15.8549852.smt2 | 52,6105 | 669,8952 | 12,73
logSMT.2018-11-21-16-17-16.4802747.smt2 | 0,0178 | 0,0233 | 1,31
logSMT.2018-11-21-16-17-17.6703054.smt2 | 0,0168 | 0,0252 | 1,50
logSMT.2018-11-21-16-17-17.7302499.smt2 | 0,0168 | 0,0244 | 1,45
logSMT.2018-11-21-16-17-37.2777576.smt2 | 0,0200 | 0,0245 | 1,23
logSMT.2018-11-21-16-17-37.369757.smt2 | 0,0172 | 0,0224 | 1,30
logSMT.2018-11-21-16-17-53.181488.smt2 | 0,0174 | 0,0228 | 1,31
logSMT.2018-11-21-16-17-53.2999344.smt2 | 0,0177 | 0,0212 | 1,20
logSMT.2018-11-21-16-18-07.933066.smt2 | 0,0574 | 0,0604 | 1,05
logSMT.2018-11-21-16-18-09.3521934.smt2 | 0,0322 | 0,0346 | 1,07
logSMT.2018-11-21-16-18-09.5016948.smt2 | 0,0350 | 0,0407 | 1,16
logSMT.2018-11-21-16-18-33.3019764.smt2 | 0,0313 | 0,0378 | 1,21
logSMT.2018-11-21-16-18-34.5522905.smt2 | 0,0270 | 0,0330 | 1,22
logSMT.2018-11-21-16-18-35.7943764.smt2 | 0,0516 | 0,0662 | 1,28
logSMT.2018-11-21-16-18-35.8993717.smt2 | 0,0451 | 0,0504 | 1,12
logSMT.2018-11-21-16-18-49.8884182.smt2 | 0,0253 | 0,0347 | 1,37
logSMT.2018-11-21-16-18-51.142361.smt2 | 0,0311 | 0,0317 | 1,02
logSMT.2018-11-21-16-18-52.3940894.smt2 | 0,0322 | 0,0353 | 1,10
logSMT.2018-11-21-16-18-54.365258.smt2 | 0,0318 | 0,0375 | 1,18
logSMT.2018-11-21-16-18-57.7788216.smt2 | 0,0179 | 0,0303 | 1,69
logSMT.2018-11-21-16-19-09.6543324.smt2 | 0,0173 | 0,0225 | 1,30
logSMT.2018-11-21-16-19-21.5543568.smt2 | 0,0173 | 0,0245 | 1,42
logSMT.2018-11-21-16-19-24.474233.smt2 | 0,0170 | 0,0226 | 1,34
logSMT.2018-11-21-16-19-36.4435744.smt2 | 0,0171 | 0,0226 | 1,33
logSMT.2018-11-21-16-20-41.76741.smt2 | 0,8927 | 1,1115 | 1,25
logSMT.2018-11-21-16-20-41.8729082.smt2 | 35,4094 | 9,0861 | 0,26
logSMT.2018-11-21-16-20-41.9384074.smt2 | 2,4260 | 1,2393 | 0,51
logSMT.2018-11-21-16-20-41.9519057.smt2 | 4,0908 | 1,8256 | 0,45
logSMT.2018-11-21-16-21-09.6346365.smt2 | 0,0169 | 0,0250 | 1,48
logSMT.2018-11-21-16-21-11.2816155.smt2 | 0,0171 | 0,0235 | 1,37
logSMT.2018-11-21-16-21-13.2550927.smt2 | 0,0173 | 0,0241 | 1,39
logSMT.2018-11-21-16-21-15.475562.smt2 | 0,0171 | 0,0241 | 1,41
logSMT.2018-11-21-16-21-18.7920202.smt2 | 3,3134 | 3,2396 | 0,98
logSMT.2018-11-21-16-21-33.063929.smt2 | 0,3714 | 0,4735 | 1,27
logSMT.2018-11-21-16-21-51.5235282.smt2 | 0,6187 | 0,7607 | 1,23
logSMT.2018-11-21-16-22-01.9888948.smt2 | 0,2463 | 0,2992 | 1,21
logSMT.2018-11-21-16-22-11.3305285.smt2 | 0,1901 | 0,1918 | 1,01
logSMT.2018-11-21-16-22-19.2309292.smt2 | 0,7842 | 1,0297 | 1,31
logSMT.2018-11-21-16-22-23.7673705.smt2 | 1,0892 | 1,2673 | 1,16
logSMT.2018-11-21-16-22-53.6579925.smt2 | 1,0739 | 1,3107 | 1,22
logSMT.2018-11-21-16-22-57.694136.smt2 | 117,3108 | 624,0372 | 5,32
logSMT.2018-11-21-16-23-51.6692437.smt2 | 207,7492 | 1573,3027 | 7,57
logSMT.2018-11-21-16-24-04.4761551.smt2 | 0,0180 | 0,0227 | 1,27
logSMT.2018-11-21-16-24-09.7845879.smt2 | 0,0169 | 0,0225 | 1,33
logSMT.2018-11-21-16-24-09.8615854.smt2 | 0,0168 | 0,0220 | 1,31
logSMT.2018-11-21-16-25-25.7845773.smt2 | 0,0165 | 0,0225 | 1,36
logSMT.2018-11-21-16-25-25.8735771.smt2 | 0,0165 | 0,0221 | 1,34
logSMT.2018-11-21-16-26-37.9946463.smt2 | 0,1089 | 0,1309 | 1,20
logSMT.2018-11-21-16-26-42.8490846.smt2 | 0,1074 | 0,1228 | 1,14
logSMT.2018-11-21-16-26-47.9205211.smt2 | 17,3395 | 25,3485 | 1,46
logSMT.2018-11-21-16-29-06.2410598.smt2 | 0,0907 | 0,1644 | 1,81
  |   |   |  
total | 2015,4142 | 171740,0019 | 85,21

So the performance differs between 4.8.1 and 4.8.3.
In some cases 4.8.3 is faster, but in most 4.8.1 is faster.
In particular, cases that already took a lot of time in 4.8.1 (above 50 seconds) take more time in 4.8.3.
And even worse, one benchmark has become unsolvable by Z3.

So we would like,
1. That Z3 becomes able to solve `logSMT.2018-11-21-15-42-14.105276.smt2` once more
2. The performance of Z3 will be improved for the more complicated problems

**Comment by GSPP** [comment]
I am experiencing a 3x slowdown moving from 4.4 to 4.8.3. I might open a ticket about it but I'm still investigating. Fyi.

**Comment by NikolajBjorner** [comment]
FYI, I am using the regressions to find perf issues and bugs and adding improvements in various commits.

**Comment by NikolajBjorner** [comment]
I believe you will find performance numbers from the latest builds satisfactory.

**Comment by pjljvandelaar** [comment]
I will check...
Thanks for your effort!

**Comment by pjljvandelaar** [comment]
We rerun the bench mark today with Z3 version 4.8.4 - 64 bit - build hashcode b40c2b2926ed

We got the following values (together with the previous measurements):

4.8.1 | 4.8.3 | 4.8.4 | improvement     4.8.4 over 4.8.1
-- | -- | -- | --
0,0250 | 0,0426 | 0,0292 | 1,167100291
0,0247 | 0,0231 | 0,0200 | 0,811445273
0,0764 | 0,0853 | 0,0652 | 0,853714851
0,0271 | 0,0379 | 0,0268 | 0,98640494
0,0168 | 0,0249 | 0,0215 | 1,285307531
0,1652 | 0,1910 | 0,1813 | 1,097851943
0,0748 | 0,0990 | 0,0733 | 0,979939082
0,0168 | 0,0282 | 0,0194 | 1,15815657
0,0161 | 0,0222 | 0,0203 | 1,260618204
0,0163 | 0,0231 | 0,0194 | 1,191065794
0,0168 | 0,0232 | 0,0192 | 1,145620199
0,8566 | 0,7538 | 0,8524 | 0,995070402
0,0171 | 0,0266 | 0,0191 | 1,116072629
0,0180 | 0,0226 | 0,0195 | 1,082722426
0,0184 | 0,0220 | 0,0195 | 1,061054187
0,0180 | 0,0223 | 0,0208 | 1,152427863
0,0165 | 0,0216 | 0,0195 | 1,183264328
0,0167 | 0,0214 | 0,0194 | 1,165305816
0,8502 | 0,4493 | 0,4654 | 0,547360866
84,1520 | 268,5495 | 22,8322 | 0,271320614
0,0202 | 0,0270 | 0,0200 | 0,98959353
0,0172 | 0,0221 | 0,0193 | 1,122528657
0,0180 | 0,0222 | 0,0192 | 1,068359603
0,0172 | 0,0225 | 0,0188 | 1,090873746
0,0584 | 0,0819 | 0,0559 | 0,958106405
0,9811 | 0,7707 | 0,8505 | 0,866852531
0,8233 | 0,7074 | 0,7564 | 0,918709278
1,1349 | 0,9329 | 0,9616 | 0,847288553
0,0196 | 0,0213 | 0,0195 | 0,996632205
0,0192 | 0,0221 | 0,0189 | 0,983276044
0,0189 | 0,0250 | 0,0245 | 1,29697991
0,0195 | 0,0234 | 0,0207 | 1,06026267
0,0219 | 0,0228 | 0,0214 | 0,978283417
0,0189 | 0,0221 | 0,0190 | 1,005967136
0,0412 | 0,0365 | 0,0334 | 0,811722922
0,0397 | 0,0396 | 0,0344 | 0,865733927
0,3066 | 0,2445 | 0,2389 | 0,779454647
0,0360 | 0,0353 | 0,0266 | 0,738941792
0,0299 | 0,0281 | 0,0223 | 0,745441062
0,1041 | 0,0666 | 0,0652 | 0,626545902
0,0629 | 0,0516 | 0,0456 | 0,724764505
0,0267 | 0,0288 | 0,0230 | 0,862083418
0,0232 | 0,0254 | 0,0207 | 0,890077407
0,0249 | 0,0282 | 0,0224 | 0,897536022
1,0823 | 0,4580 | 0,4386 | 0,405252551
0,1269 | 0,0744 | 0,0914 | 0,720066798
10,9245 | 2,0656 | 2,0819 | 0,190567544
2,3210 | 1,5987 | 1,6741 | 0,721311412
973,0083 | 164620,9296 | 330,7267 | 0,339901191
0,0180 | 0,0529 | 0,0295 | 1,639334958
0,0169 | 0,0236 | 0,0288 | 1,699941519
0,0170 | 0,0255 | 0,0276 | 1,618686083
0,0166 | 0,0270 | 0,0318 | 1,909575204
0,0463 | 0,0649 | 0,0808 | 1,746938511
0,0323 | 0,0450 | 0,0520 | 1,61046744
0,0731 | 0,0890 | 0,1293 | 1,77013206
0,0378 | 0,0576 | 0,0657 | 1,73740387
0,0618 | 0,0782 | 0,1010 | 1,63447444
0,0793 | 0,0876 | 0,1248 | 1,573747752
0,0596 | 0,0666 | 0,0944 | 1,583986527
19,4797 | 113,9103 | 4,9483 | 0,254024918
34,3561 | 175,5398 | 30,8470 | 0,897860183
0,0277 | 0,0337 | 0,0334 | 1,205078829
0,0362 | 0,0511 | 0,0527 | 1,45719796
0,0248 | 0,0339 | 0,0341 | 1,377495873
0,0214 | 0,0355 | 0,0328 | 1,530625379
0,0221 | 0,0294 | 0,0336 | 1,517381553
0,0328 | 0,0420 | 0,0461 | 1,408437034
0,0327 | 0,0387 | 0,0418 | 1,280109729
0,0841 | 0,0732 | 0,1096 | 1,303136324
436,4655 | 3634,8789 | 57,1186 | 0,130866186
52,6105 | 669,8952 | 3,4496 | 0,065569504
0,0178 | 0,0233 | 0,0248 | 1,395152053
0,0168 | 0,0252 | 0,0224 | 1,337908267
0,0168 | 0,0244 | 0,0203 | 1,210032374
0,0200 | 0,0245 | 0,0211 | 1,053901525
0,0172 | 0,0224 | 0,0217 | 1,261302535
0,0174 | 0,0228 | 0,0226 | 1,295489855
0,0177 | 0,0212 | 0,0255 | 1,446193661
0,0574 | 0,0604 | 0,0641 | 1,116330255
0,0322 | 0,0346 | 0,0327 | 1,015632809
0,0350 | 0,0407 | 0,0389 | 1,113691571
0,0313 | 0,0378 | 0,0345 | 1,104497189
0,0270 | 0,0330 | 0,0330 | 1,222396564
0,0516 | 0,0662 | 0,0642 | 1,243578561
0,0451 | 0,0504 | 0,0618 | 1,370742674
0,0253 | 0,0347 | 0,0301 | 1,188469795
0,0311 | 0,0317 | 0,0389 | 1,250520693
0,0322 | 0,0353 | 0,0381 | 1,183484558
0,0318 | 0,0375 | 0,0427 | 1,340927512
0,0179 | 0,0303 | 0,0264 | 1,474856254
0,0173 | 0,0225 | 0,0272 | 1,570976552
0,0173 | 0,0245 | 0,0230 | 1,329652011
0,0170 | 0,0226 | 0,0269 | 1,587718057
0,0171 | 0,0226 | 0,0247 | 1,444013748
0,8927 | 1,1115 | 1,3305 | 1,490376817
35,4094 | 9,0861 | 10,3794 | 0,293125996
2,4260 | 1,2393 | 1,1009 | 0,453793012
4,0908 | 1,8256 | 1,6685 | 0,407858906
0,0169 | 0,0250 | 0,0214 | 1,267174353
0,0171 | 0,0235 | 0,0200 | 1,171452149
0,0173 | 0,0241 | 0,0200 | 1,158718499
0,0171 | 0,0241 | 0,0199 | 1,165110146
3,3134 | 3,2396 | 2,5948 | 0,783123641
0,3714 | 0,4735 | 0,3940 | 1,060714254
0,6187 | 0,7607 | 0,6390 | 1,032787765
0,2463 | 0,2992 | 0,2512 | 1,019857866
0,1901 | 0,1918 | 0,1999 | 1,051288025
0,7842 | 1,0297 | 0,8145 | 1,038550421
1,0892 | 1,2673 | 0,9897 | 0,908665726
1,0739 | 1,3107 | 1,0566 | 0,98383883
117,3108 | 624,0372 | 19,0009 | 0,161970809
207,7492 | 1573,3027 | 26,6410 | 0,128236402
0,0180 | 0,0227 | 0,0288 | 1,605707416
0,0169 | 0,0225 | 0,0229 | 1,353446745
0,0168 | 0,0220 | 0,0254 | 1,50930616
0,0165 | 0,0225 | 0,0257 | 1,553009532
0,0165 | 0,0221 | 0,0260 | 1,580193953
0,1089 | 0,1309 | 0,1563 | 1,435660505
0,1074 | 0,1228 | 0,1566 | 1,459081781
17,3395 | 25,3485 | 33,1672 | 1,912813708
0,0907 | 0,1644 | 0,2024 | 2,23079644
  |   |   |  
2015,4142 | 171740,0019 | 562,3671 | 0,279033006

So your statement
```
I believe you will find performance numbers from the latest builds satisfactory.
```
is conservative in my opinion:

I am **thrilled** by these performance numbers!

Thanks for the great work!

**Comment by GSPP** [comment]
Is there a way to access these builds without compiling and without waiting for an official release? I am eager to test this.

**Comment by pjljvandelaar** [comment]
Yes: look at https://github.com/Z3Prover/bin/tree/master/nightly
