### ISSUE TITLE
maximize hangs for maximizing a real-valued variable

### ISSUE THREAD

**Issue by alanborning** [Z3Prover/z3#198]
For the unstable branch (commit 7a0deed3fe4e83eebd10e9ce86dc19bfff97661), maximize hangs for the following query:

(declare-const y Real)
(assert (<= y 100))
(maximize y)
(check-sat)

It also hangs for  (maximize (+ 0 y)), but works fine for (maximize (+ 1 y)).

**Comment by NikolajBjorner** [comment]
seems I noticed this too last week while overhauling some of the functionality.

**Comment by NikolajBjorner** [comment]
fixed with 9ad065a..7c87096
