### ISSUE TITLE
What's a replacement for the removed BenchmarkToSMTString?

### ISSUE THREAD

**Issue by GSPP** [Z3Prover/z3#1981]
While upgrading from Z3 4.4 .NET I found that the `BenchmarkToSMTString` function has been removed. What's the recommended alternative?

**Comment by NikolajBjorner** [comment]
Create a solver object, add the assertions to the solver, then the ToString() method for the solver object produces the SMT-LIB string.

**Comment by GSPP** [comment]
I tried generating an SMT-LIB string like this:

```
                    var solver = context.MkSimpleSolver();
                    solver.Assert(context.MkEq(context.MkIntConst("x") + context.MkIntConst("y"), context.MkIntConst("z")));
                    solver.Assert(context.MkGt(context.MkIntConst("x"), context.MkInt(0)));
                    var smtlibString = solver.ToString();
```
The output does not look usable:

```
(kernel
  (= (+ x y (* (- 1) z)) 0)
  (not (<= x 0)))
```

And it cannot be parsed back (results in a zero length `BoolExpr` array).

When I use `context.MkSolver("QF_LIA")` I get

```
(solver
  (= (+ x y) z)
  (> x 0))
```

which is also not parseable. How can I generate a true SMT-LIB string? E.g.:

```
(set-info :status unknown)
(set-logic QF_LIA)
(declare-fun targetHashFactor () Int)
...
(assert
(let (($x109 (>= targetHashFactor 0)))
... )
(check-sat)
```

**Comment by GSPP** [comment]
Hello @NikolajBjorner, did you have time to look at this? How can we generate SMT-LIB strings with the latest Z3?

**Comment by wintersteiger** [comment]
@GSPP did this issue ever get resolved?

**Comment by GSPP** [comment]
@wintersteiger no, still looking for a solution. I want to use this functionality to extract a repro case for a problem that got much slower in a recent Z3 release. I can also create a QF_BV benchmark from a sophisticated program synthesis project of mine if you are interested.

**Comment by wintersteiger** [comment]
@NikolajBjorner do we still have a function that dumps a complete benchmark with declarations etc?

@GSPP for reporting problems with API usage, it's usually better to submit an API log instead of an SMT2 file, because SMT2 files do not necessarily show the same behaviour as the corresponding API interaction (see `Microsoft.Z3.Log.Open`).

**Comment by NikolajBjorner** [comment]
The new way to dump benchmarks is to create a Solver object as done above. With the newer versions of Z3 you will not get "kernel" or "solver" keywords. This was the case for older versions. For the older versions there is the BenchmarkToSMTString..

**Comment by GSPP** [comment]
I will look into this.

**Comment by GSPP** [comment]
It works in 4.8.4. I can use `ParseSMTLIB2String` to parse the assertions. For reference here is my test code:

	string smtlibString;
	{
		var solver = context.MkSolver("QF_LIA");
		solver.Assert(context.MkEq(context.MkAdd(context.MkIntConst("x"), context.MkIntConst("y")), context.MkIntConst("z")));
		solver.Assert(context.MkGt(context.MkIntConst("x"), context.MkInt(0)));
		smtlibString = solver.ToString();
	}

	{
		var parseExprs = context.ParseSMTLIB2String(smtlibString);
		var solver = context.MkSimpleSolver();

		solver.Assert(parseExprs);

		Console.WriteLine(solver.Check());
		Console.WriteLine(solver.Model);
	}

Also, the performance problem I was investigating in 4.8.3 is gone. 4.8.4 is much faster than 4.0.0. Awesome.
