### ISSUE TITLE
z3 printing exception to stdout - can't figure out why

### ISSUE THREAD

**Issue by typon** [Z3Prover/z3#1987]
I'm doing a bunch of manipulation of z3 expressions and z3 variable objects using the python API and i get the following lines being printed randomly to stdout:

``
Exception z3.z3types.Z3Exception: Z3Exception() in <object repr() failed> ignored
``

This usually happens when there are a lot of z3 expressions being created. It is fairly reproducible, but sometimes does not happen. This leads me to believe that it has something to do with the python garbage collector and not cleaning up z3 objects correctly. However, i tried to do ``gc.disable()`` before running this code, but it still prints these exceptions. Functionally, nothing is wrong and the code behaves exactly as expected. 

My question is: How do I debug this? How do i figure out the source of these 'exceptions'? Is there a way to turn off all output from z3 using the python API?

Thanks

**Comment by typon** [comment]
The weird thing is that z3 is internally catching the exception and then printing it out stdout. Is there a way to tell z3 to not catch these exceptions? Is there some global flag?

**Comment by NikolajBjorner** [comment]
it shouldn't print to output from internal code. The python wrapper prints in some cases. You can likely find the places in the python bindings where it prints relatively easily.

**Comment by waywardmonkeys** [comment]
I'm pretty sure this is coming from Python, not from Z3 directly. So you'll need to see which `__repr__` method is causing this...

**Comment by NikolajBjorner** [comment]
right, embarrassingly though, it sometimes happens that I leave such code around.

**Comment by waywardmonkeys** [comment]
Well, nothing in Z3 prints a message like that ... and other Python projects have reported similar ones. :)

**Comment by NikolajBjorner** [comment]
OK, relating to the greyed out text, yes.

**Comment by typon** [comment]
The problem was in the `__del__` method of `AstRef`. I monkey patched z3.py to catch the exception and silently ignore it. 

Thanks for your help @waywardmonkeys  and @NikolajBjorner
