### ISSUE TITLE
Odd corrospondance between Z3_get_bool_value and model

### ISSUE THREAD

**Issue by jawline** [Z3Prover/z3#2007]
When solving the following SMT problem (generated via the C API):

`(declare-fun |0 Fill 0| () String)
(declare-fun A () String)
(declare-fun TTTTTT () Bool)
(assert (str.in.re |0 Fill 0|
           (re.inter (re.range "\x00" "\xff")
                     (re.complement (re.range "0" "9")))))
(assert (let ((a!1 (str.in.re A
                      (re.inter (re.range "\x00" "\xff")
                                (re.complement (re.range "0" "9"))))))
  (or (not a!1) (= A |0 Fill 0|))))
(assert (let ((a!1 (str.in.re A
                      (re.inter (re.range "\x00" "\xff")
                                (re.complement (re.range "0" "9"))))))
  (or (not a!1) TTTTTT)))
(assert (str.in.re A
           (re.inter (re.range "\x00" "\xff")
                     (re.complement (re.range "0" "9")))))
`

I get the following model for output, 

`Model: A -> "\xba"
TTTTTT -> true
0 Fill 0 -> "\xba"`

However when I call Z3_get_bool_value on the following AST:

`(str.in.re "\xba"
           (re.inter (re.range "\x00" "\xff")
                     (re.complement (re.range "0" "9"))))`

 after evaluating it with the model I get the result 0 (UNDEF) rather than 1 (Z3_TRUE) as I was expecting.

Do I need to do anything special to evaluate these cases to Bool?

**Comment by NikolajBjorner** [comment]
Good point. 
Evaluation/simplification of regular expressions with complement and intersection isn't available in the way it is currently organized.

**Comment by NikolajBjorner** [comment]
Evaluation and simplification now deal with regular expression membership also when they use intersection and complement. However Z3_get_bool_value is not the proper API. Z3_get_bool_value checks if the expression that is passed as argument is either the constant "true" or the constant "false".

**Comment by jawline** [comment]
Many thanks
