### ISSUE TITLE
Z3 binary crashes on certain input with FloatingPoint sorts

### ISSUE THREAD

**Issue by wanderseeme** [Z3Prover/z3#201]
The input:

    (declare-datatypes () ((Tuple (tuple 
        (location Int) 
        (_b Bool) 
        (_i15 (_ BitVec 15)) 
        (_i32 (_ BitVec 32)) 
        (_i64 (_ BitVec 64)) 
        (_f (_ FloatingPoint 8 24)) 
    ))))
    (declare-const prop0 Tuple)
    (assert (not (not (= (location prop0) 1))))
    (check-sat)

Description:

This input causes "Segmentation fault (core dumped)", but if I remove line "    (_f (_ FloatingPoint 8 24)) ", z3 will work as normal.

Version info:

4.4.0 on Linux x86_64 (Fedora 22)

**Comment by wintersteiger** [comment]
Thanks for the report! This was indeed a bug and it's now been fixed in the unstable branch.
