### ISSUE TITLE
Segfault when translating solver z3py

### ISSUE THREAD

**Issue by norhh** [Z3Prover/z3#2023]
I am currently working on a symbolic execution engine. Currently I am trying to put a solver for each branch to prune states and after pruning I am unreferencing the solver.
- Each branch has a solver
- The solver's reference is directly propagated when no constraint gets added to a branch
- Solver is copied to multiple children when a branch split happens, Solver copy is made in the same context
- Solver is unreferenced to that memory when that state's execution is finished
- Python's garbage collection should handle the unreferencing by counting references and freeing memory based on that
But unfortunately it is causing a segfault after going to some depth, and the python faulttracer is pointing towards z3core.py line 3367 in Z3_solver_translate.
![segfault](https://user-images.githubusercontent.com/15844703/49535727-d4bd1f80-f8ea-11e8-9ec8-baf2567c89f0.png)
Can you guys help me out, Like should I do something more than directly using solver's \_\_copy\_\_()?

**Comment by norhh** [comment]
Also it seems a bit weird that copying twice doesn't cost same memory increment.
![copy_weird](https://user-images.githubusercontent.com/15844703/49537037-e2c06f80-f8ed-11e8-9a9b-7ec1901fb5a1.png)
Is there anything which is being mutually used between the copies?

**Comment by NikolajBjorner** [comment]
Is it possible to reproduce the crash with a log trace? Use open_log("z3.log") before any call into z3.

**Comment by norhh** [comment]
Sure, 
[z3.log](https://github.com/Z3Prover/z3/files/2651556/z3.log)

**Comment by NikolajBjorner** [comment]
The log indicates you are using a version from July. Does this reproduce with the latest Z3?

**Comment by norhh** [comment]
not sure how to get the latest Z3py, I couldn't get it through pip from github.

**Comment by NikolajBjorner** [comment]
https://github.com/Z3Prover/bin/tree/master/nightly

**Comment by norhh** [comment]
@NikolajBjorner , still the same problem , installed 4.8.4 
[z3.log](https://github.com/Z3Prover/z3/files/2654170/z3.log)

**Comment by NikolajBjorner** [comment]
The log doesn't crash

**Comment by norhh** [comment]
thats weird, does it fail with the previous log?

**Comment by norhh** [comment]
@NikolajBjorner , does the log provide crash report for segfault?

**Comment by NikolajBjorner** [comment]
It didn't
