### ISSUE TITLE
Is it possible to get a legit range info when using a SMT constraint with Z3

### ISSUE THREAD

**Issue by ireneGP** [Z3Prover/z3#2028]
So basically I am trying to solve the following SMT constraint with a generic constraint solver like Z3:

````
    >>> from z3 import *
    >>> a = BitVec("a", 32)
    >>> b = BitVec("b", 32)
    >>> c1 = (a + 32) & (b & 0xff)
    >>> c2 = (b & 0xff)
    >>> s = Solver()
    >>> s.add(c1 == c2)
    >>> s.check()
    sat
    >>> s.model()
    [b = 0, a = 4294967199]
````

Note that obviously, the constraint should be `sat` whenever `b` falls within the range of `[0x00000000, 0xffffff00]`. 

Although I don't see this as possible, but just want to confirm, is it feasible for `Z3` to provide the "range" information for a satisfiable constraint? Thanks.

**Comment by DennisYurichev** [comment]
You can switch to optimization problem and use minimize()/maximize().

**Comment by LeventErkok** [comment]
@ireneGP 

You asked about this in stackoverflow and received a response there: https://stackoverflow.com/a/53677251/936310

Long story short: Not if you are looking for a "widest" range such that it is true for all numbers in between. (That would require a quantified optimization problem, which is not supported.)

However, easily solved if all you care about is what the min/max values `b` can take, without guaranteeing that everything in that range will also satisfy your constraint.

Also note that the range of `b` is unrestricted in this specific instance, unlike what you predicted it would be. See the stack-overflow answer for details.

**Comment by DennisYurichev** [comment]
Yes, I fogot, when using minimize/maximize, something may be in between.

**Comment by NikolajBjorner** [comment]
You can extract intervals using minimize/maximize and iterating calls. This is not built into Z3. There is a description of such a procedure here https://www.microsoft.com/en-us/research/wp-content/uploads/2016/02/secguru.pdf
