### ISSUE TITLE
Unexpected result from Context.MkAnd() using v. 4.8.1

### ISSUE THREAD

**Issue by filipliwinski** [Z3Prover/z3#2029]
I use  Z3 .NET API via NuGet package in my NetCore 2.1 app and I encountered a problem with `ctx.MkAnd()` method after updating from version [4.5.0.1](https://www.nuget.org/packages/z3x64win/) to [4.8.1](https://www.nuget.org/packages/Microsoft.Z3.x64/):

Using following parameters:
```
a: true
b: (not (<= n 0))
c: (< (+ a 1) n)
d: (= (mod (+ a 1) 5) 0)
e: (not (= (mod (+ a 1) 7) 0))
```

`ctx.MkAnd(a, b, c, d)` returns:
(and (= (mod (+ a 1) 5) 0) (< (+ a 1) n) (not (<= n 0)) true)
but `ctx.MkAnd(a, b, c, d, e)` returns:
(let ((a!1 (not (= (mod (+ a 1) 7) 0))))\n  (and a!1 (= (mod (+ a 1) 5) 0) (< (+ a 1) n)
expected result:
(and (not (= (mod (+ a 1) 7) 0)) (= (mod (+ a 1) 5) 0) (< (+ a 1) n) (not (<= n 0)) true)

Is there a known reason for this?

**Comment by NikolajBjorner** [comment]
what is the self-contained repro?

For me, I get the following:

    from z3 import *
    n, a = Ints('n a')
    A = True
    B = Not(n <= 0)
    C = (a + 1) < n
    D = (a + 1) % 4 == 0
    E = Not( ((a + 1) % 7) == 0)

    print(And([A,B,C,D]))

It produces

    And(True, Not(n <= 0), a + 1 < n, (a + 1)%4 == 0)

**Comment by filipliwinski** [comment]
`ctx.MkAnd(a, b, c, d, e).ToString()`
Output:
(let ((a!1 (not (= (mod (+ a 1) 7) 0))))\n  (and true (not (<= n 0)) (< (+ a 1) n) (= (mod (+ a 1) 5) 0) a!1))

`ctx.MkAnd(e, d, c, b, a).ToString()`
Output:
(let ((a!1 (not (= (mod (+ a 1) 7) 0))))\n  (and a!1 (= (mod (+ a 1) 5) 0) (< (+ a 1) n) (not (<= n 0)) true))

**Comment by NikolajBjorner** [comment]
Looks right
