### ISSUE TITLE
"value is out of bounds" exception trigger by push

### ISSUE THREAD

**Issue by wysiib** [Z3Prover/z3#203]
The code in https://gist.github.com/wysiib/ef31a34978cbd45ec2eb leads to a "value is out of bounds" exception being thrown if the push is included.
If it is commented out, Z3 returns unknown.

Tested with Z3 4.4.1 on OS X.

If you need further input let me know!

**Comment by NikolajBjorner** [comment]
Thanks, yes a bug in the finite domain theory
