### ISSUE TITLE
enable_trace(tag) is available but enable_all_trace(flag) is not available in z3py

### ISSUE THREAD

**Issue by muqsitazeem148** [Z3Prover/z3#2038]
I want to analyze z3 traces (for example, I want to see how z3 solves two different encodings of a problem first using 'BitVecs' and second using 'Ints' by looking at z3 traces). 

- I am using z3 release version 4.8.3 compiled with --debug and --trace options. 
- Currently, I am using enable_trace(tag) using z3py to analyze the traces which dumps the trace in '.z3-trace'. 
- In z3 source-code, I found out an option enable_all_trace(bool flag) which is available in trace.cpp but not in python API.

Is there a way to enable all types traces at once using z3py?

**Comment by NikolajBjorner** [comment]
there isn't and we never use it internally: it produces an _enourmous_ amount of tracing. You should trace relevant features, such as
- "before_search"
- "after_search"
- "asserted_formulas"
- "bv" (and variants found in theory_bv)
- "resolve_conflict"
- "set_conflict"
- "arith" (and variants found in theory_arith*, theory_lra.cpp)
- "rewriter"
