### ISSUE TITLE
Python (and possibly other APIs?) don't seem to handle string escapes

### ISSUE THREAD

**Issue by LeventErkok** [Z3Prover/z3#2039]
Is `as_string` the correct call to make to convert a z3py `String` object to a Python string?

Consider:

```
from z3 import *

a = "\""
b = StringVal(a)
c = b.as_string()
print a
print c
print a == c
```

I was expecting this would round-trip `a` via a z3py string, and get it back as a Python string in `c`; equivalent to `a`. Alas, this prints:

```
"
""""
False
```

It looks like the `as_string` method isn't handling the conversion correctly. Two problems I can spot:

  * The returned string seems to always have surrounding quotes
  * If there's an intervening quote, it gets double quoted; which isn't the right thing to do in Python. There should simply be a single quote, and the Python printer would appropriately add the escaping as necessary (which is backslash).

I looked through the code and it seems like this could be an issue for other APIs as well (C/Java etc.); though I'm not sure.

But perhaps `as_string()` is just not the right function to call? If that's the case, what's the right API call for converting a Z3Py String to a Python one?

**Comment by LeventErkok** [comment]
I'm not a Python expert, but I was able to work around this using the following function:

```python
def as_python_string(obj):
    if not obj.is_string():
        raise Z3Exception("as_python_string requires a Z3 String object. Received: %s" % obj.as_string())

    s = obj.as_string()

    if len(s) < 2 or s[0] != '"' or s[-1] != '"':
        raise Z3Exception("as_python_string: Unexpected string representation received: %s" % s)

    # drop the surrounding quotes
    contents = s[1:-1]

    # walk thru and remove double quotes:
    while '""' in contents:
        contents = contents.replace('""', '"')

    return contents
```

But I think the following definition:

https://github.com/Z3Prover/z3/blob/b6bf299b8b453d5ff5aef7ee840301385f72dc16/src/api/python/z3/z3.py#L9915-L9917

should be changed to test for string instances and do the above, obviating the need for this extra function.

**Comment by NikolajBjorner** [comment]
right, I have something like this locally:

      def as_string(self): 
        if Z3_is_string(self.ctx_ref(), self.as_ast()):
              return Z3_as_string(self.ctx_ref(), self.as_ast()) 
        return Z3_ast_to_string(self.ctx_ref(), self.as_ast())

**Comment by LeventErkok** [comment]
Just tested it and works out just fine. Thanks!

**Comment by NikolajBjorner** [comment]
well, it broke the doc-test
