### ISSUE TITLE
Hang for a String benchmark

### ISSUE THREAD

**Issue by iwob** [Z3Prover/z3#2045]
For the following script [phone-1.txt](https://github.com/Z3Prover/z3/files/2687297/phone-1.txt) Z3 seems to run indefinitely with increasing memory usage. The expected answet is unsat. With `smt.string_solver=z3str3 ` this is solved instantly.

**Comment by mtrberzi** [comment]
Interesting, I'll look into this when I have some time.

**Comment by mtrberzi** [comment]
I can confirm that this has been fixed in master. Z3str3 solves this correctly in the latest master branch (returns UNSAT immediately); the sequence solver takes a little longer but also solves it correctly. I think this was fixed with some of my previous fixes to `str.contains` and `str.indexof`.
