### ISSUE TITLE
Z3 eats my memory and crashes

### ISSUE THREAD

**Issue by zhangboyang** [Z3Prover/z3#2054]
Hello,

I'm new to Z3. I found this program made Z3 eat up my memory and crash.
Is this a intended behavior or a bug?

Thanks!
[z3crash.txt](https://github.com/Z3Prover/z3/files/2718342/z3crash.txt)

**Comment by NikolajBjorner** [comment]
It uses a lot of non-linear integer arithmetic something that currently doesn't have much support. 
It currently is stuck in bit-blasting tactic to check satisfiability.

**Comment by zhangboyang** [comment]
Thanks for your reply.
