### ISSUE TITLE
Minimizing str.len leads to invalid result with the default string solver

### ISSUE THREAD

**Issue by zimmski** [Z3Prover/z3#2055]
I am using Z3 4.8.4 under 64bit Linux.

The following formula prints a string with `"\x00\x00\x00\x00"`.
```smtlib
(set-option :produce-models true)

(declare-const s_0 String)

(assert (> (str.len s_0) 3))

(check-sat)
(get-model)
```

However, when I put in a "minimize" for "str.len" I get the empty string which is invalid for this formula.

```smtlib
(set-option :produce-models true)

(declare-const s_0 String)

(assert (> (str.len s_0) 3))
(minimize (str.len s_0))

(check-sat)
(get-model)
```

Using `(set-option :smt.string_solver z3str3)` results into "aaaaaa" and "aaam" (minimized) (why not "aaaa"?).

If you are reading this in January: Happy New Year! :fireworks: :champagne:

**Comment by NikolajBjorner** [comment]
fixed
