### ISSUE TITLE
Add API for the Go lang

### ISSUE THREAD

**Issue by alexpantyukhin** [Z3Prover/z3#2059]
Would it be a good idea to make an API for the Go lang? If yes, I would like to help with this.

**Comment by NikolajBjorner** [comment]
It is a good idea provided you or someone else needs it to be productive.

There are  several languages/runtimes where the same question has come up: ECMAScript, Haskell, Kotlin, Rust, WebAssembly. There are also independent distributions of python bindings (z3-solver and something else, but not z3, which is ZFS bindings for S3) that come as pip packages. These are essentially developed in separate forks which helps separate dependencies and breaks. Furthermore, to integrate with the master branch we would have to make sure there is a sustainable build/test path such that at least the TravisCI tests the extensions on every check-in.

**Comment by NikolajBjorner** [comment]
GO or no-GO? Seems not to have GOne further.
