### ISSUE TITLE
Ignored timeout in QF_NIA

### ISSUE THREAD

**Issue by Heizmann** [Z3Prover/z3#206]
Using ef7915858bca5e759ee0a34df2ae976e7e507bef,  z3 -t:1000 does not terminate on the following script.

    (set-option :produce-models true)
    (set-logic QF_NIA)
    (declare-fun init_main_x () Int)
    (declare-fun honda_main_x () Int)
    (declare-fun init_main_y () Int)
    (declare-fun honda_main_y () Int)
    (declare-fun gev_main_x0 () Int)
    (declare-fun gev_main_y0 () Int)
    (declare-fun lambda0 () Int)
    (declare-fun gev_main_x1 () Int)
    (declare-fun gev_main_y1 () Int)
    (declare-fun lambda1 () Int)
    (declare-fun gev_main_x2 () Int)
    (declare-fun gev_main_y2 () Int)
    (declare-fun lambda2 () Int)
    (declare-fun nu0 () Int)
    (declare-fun nu1 () Int)
    (assert (and true (and (>= (+ (* (+ (* gev_main_y0 lambda0) (* gev_main_y1 nu0)) (- 1)) (* (+ (* gev_main_x0 lambda0) (* gev_main_x1 nu0)) (- 5)) (* gev_main_y0 3) (* gev_main_x0 0)) 0) (>= (+ (* (+ (* gev_main_y0 lambda0) (* gev_main_y1 nu0)) 0) (* (+ (* gev_main_x0 lambda0) (* gev_main_x1 nu0)) 0) (* gev_main_y0 0) (* gev_main_x0 1)) 0) (>= (+ (* (+ (* gev_main_y0 lambda0) (* gev_main_y1 nu0)) 1) (* (+ (* gev_main_x0 lambda0) (* gev_main_x1 nu0)) 5) (* gev_main_y0 (- 3)) (* gev_main_x0 0)) 0) (>= (+ (* (+ (* gev_main_y0 lambda0) (* gev_main_y1 nu0)) 0) (* (+ (* gev_main_x0 lambda0) (* gev_main_x1 nu0)) (- 1)) (* gev_main_y0 2) (* gev_main_x0 1)) 0) (>= (+ (* (+ (* gev_main_y0 lambda0) (* gev_main_y1 nu0)) 0) (* (+ (* gev_main_x0 lambda0) (* gev_main_x1 nu0)) 1) (* gev_main_y0 (- 2)) (* gev_main_x0 (- 1))) 0) (>= (+ (* (+ (* gev_main_y1 lambda1) (* gev_main_y2 nu1)) (- 1)) (* (+ (* gev_main_x1 lambda1) (* gev_main_x2 nu1)) (- 5)) (* gev_main_y1 3) (* gev_main_x1 0)) 0) (>= (+ (* (+ (* gev_main_y1 lambda1) (* gev_main_y2 nu1)) 0) (* (+ (* gev_main_x1 lambda1) (* gev_main_x2 nu1)) 0) (* gev_main_y1 0) (* gev_main_x1 1)) 0) (>= (+ (* (+ (* gev_main_y1 lambda1) (* gev_main_y2 nu1)) 1) (* (+ (* gev_main_x1 lambda1) (* gev_main_x2 nu1)) 5) (* gev_main_y1 (- 3)) (* gev_main_x1 0)) 0) (>= (+ (* (+ (* gev_main_y1 lambda1) (* gev_main_y2 nu1)) 0) (* (+ (* gev_main_x1 lambda1) (* gev_main_x2 nu1)) (- 1)) (* gev_main_y1 2) (* gev_main_x1 1)) 0) (>= (+ (* (+ (* gev_main_y1 lambda1) (* gev_main_y2 nu1)) 0) (* (+ (* gev_main_x1 lambda1) (* gev_main_x2 nu1)) 1) (* gev_main_y1 (- 2)) (* gev_main_x1 (- 1))) 0) (>= (+ (* (* gev_main_y2 lambda2) (- 1)) (* (* gev_main_x2 lambda2) (- 5)) (* gev_main_y2 3) (* gev_main_x2 0)) 0) (>= (+ (* (* gev_main_y2 lambda2) 0) (* (* gev_main_x2 lambda2) 0) (* gev_main_y2 0) (* gev_main_x2 1)) 0) (>= (+ (* (* gev_main_y2 lambda2) 1) (* (* gev_main_x2 lambda2) 5) (* gev_main_y2 (- 3)) (* gev_main_x2 0)) 0) (>= (+ (* (* gev_main_y2 lambda2) 0) (* (* gev_main_x2 lambda2) (- 1)) (* gev_main_y2 2) (* gev_main_x2 1)) 0) (>= (+ (* (* gev_main_y2 lambda2) 0) (* (* gev_main_x2 lambda2) 1) (* gev_main_y2 (- 2)) (* gev_main_x2 (- 1))) 0) (>= (+ (* (+ honda_main_y gev_main_y0 gev_main_y1 gev_main_y2) (- 1)) (* (+ honda_main_x gev_main_x0 gev_main_x1 gev_main_x2) (- 5)) (* honda_main_y 3) (* honda_main_x 0) 1) 0) (>= (+ (* (+ honda_main_y gev_main_y0 gev_main_y1 gev_main_y2) 0) (* (+ honda_main_x gev_main_x0 gev_main_x1 gev_main_x2) 0) (* honda_main_y 0) (* honda_main_x 1) 0) 0) (>= (+ (* (+ honda_main_y gev_main_y0 gev_main_y1 gev_main_y2) 1) (* (+ honda_main_x gev_main_x0 gev_main_x1 gev_main_x2) 5) (* honda_main_y (- 3)) (* honda_main_x 0) (- 1)) 0) (>= (+ (* (+ honda_main_y gev_main_y0 gev_main_y1 gev_main_y2) 0) (* (+ honda_main_x gev_main_x0 gev_main_x1 gev_main_x2) (- 1)) (* honda_main_y 2) (* honda_main_x 1) 0) 0) (>= (+ (* (+ honda_main_y gev_main_y0 gev_main_y1 gev_main_y2) 0) (* (+ honda_main_x gev_main_x0 gev_main_x1 gev_main_x2) 1) (* honda_main_y (- 2)) (* honda_main_x (- 1)) 0) 0)) (and (or (= nu0 0) (= nu0 1)) (or (= nu1 0) (= nu1 1)) (>= lambda0 0) (>= lambda1 0) (>= lambda2 0))))
    (check-sat)

**Comment by NikolajBjorner** [comment]
OK, thanks
