### ISSUE TITLE
Modify an element inside   z3::expr_vector  object  

### ISSUE THREAD

**Issue by ezudheen** [Z3Prover/z3#2068]
I am using C++ API for verification of some properties over matrices.  The elements of a matrix are stored inside a z3::expr_vector object. In order to perform row transformation of matrices, I need to update the elements inside the z3::expr_vector object.
I would like to know whether z3::expr_vector::iterator can be used to update the elements inside the z3::expr_vector object. Are there any example programs which modify the elements inside the z3::expr_vector object?

**Comment by NikolajBjorner** [comment]
You can call Z3_ast_vector_set(v.ctx(), v, index, a).
The C++ API doesn't expose a set method directly on the expr_vector object, which it probably should.

**Comment by ezudheen** [comment]
Thanks, Nikolaj. It works fine.
