### ISSUE TITLE
Crash in fairly simple example, involving refcounting?

### ISSUE THREAD

**Issue by waywardmonkeys** [Z3Prover/z3#2069]
When using `Z3_mk_context_rc`, this code crashes:

```c
#include <stdio.h>
#include <z3.h>

int main(int argc, char** argv) {
    Z3_config cfg = Z3_mk_config();
    Z3_context ctx = Z3_mk_context_rc(cfg);

    Z3_sort int_sort = Z3_mk_int_sort(ctx);
    Z3_sort int_set_sort = Z3_mk_set_sort(ctx, int_sort);

    Z3_symbol a_name = Z3_mk_string_symbol(ctx, "a");
    Z3_ast a = Z3_mk_const(ctx, a_name, int_sort);
    Z3_inc_ref(ctx, a);

    Z3_symbol set_name = Z3_mk_string_symbol(ctx, "set");
    Z3_ast set = Z3_mk_const(ctx, set_name, int_set_sort);
    Z3_inc_ref(ctx, set);

    Z3_ast result = Z3_mk_set_add(ctx, set, a);
    Z3_inc_ref(ctx, result);
    printf("%s", Z3_ast_to_string(ctx, result));
}
```

This doesn't crash if you use `Z3_mk_context` and remove the calls to `Z3_inc_ref`.

But more interestingly, it doesn't crash if you change the order of the construction such that `a` is created after `set`:

```c
    Z3_symbol set_name = Z3_mk_string_symbol(ctx, "set");
    Z3_ast set = Z3_mk_const(ctx, set_name, int_set_sort);
    Z3_inc_ref(ctx, set);

    Z3_symbol a_name = Z3_mk_string_symbol(ctx, "a");
    Z3_ast a = Z3_mk_const(ctx, a_name, int_sort);
    Z3_inc_ref(ctx, a);
```

This was reported from the Rust bindings: https://github.com/prove-rs/z3.rs/issues/7

**Comment by waywardmonkeys** [comment]
Ends up that this is missing `Z3_inc_ref` calls on the sorts that are created, and that fixing that will fix the crash. But it is still odd that just reversing the order of construction also seems to fix the crash.

**Comment by NikolajBjorner** [comment]
You also have to increment the reference counts for sorts. 

    
    Z3_sort int_sort = Z3_mk_int_sort(ctx);
    Z3_sort int_set_sort = Z3_mk_set_sort(ctx, int_sort);

is missing

    Z3_sort int_sort = Z3_mk_int_sort(ctx);
    Z3_sort_inc_ref(ctx, int_sort);
    Z3_sort int_set_sort = Z3_mk_set_sort(ctx, int_sort);
    Z3_sort_inc_ref(ctx, int_set_sort);

the inc-ref to int_sort is redundant because int_sort gets used right away and therefore int_set_sort holds a reference count, but the systematic way to use reference counts is to always increment them at the call site.

**Comment by NikolajBjorner** [comment]
It's not odd: if you use the reverse order, then a reference is created for int_set_sort within the "set" ast. 
int_set_sort owns a reference count on int_sort (which is built-in so reference counts to it abound already). 
If you use the original order that crashes, then the temporary reference count to int_set_sort within Z3's API will be released and instead used for "a".

**Comment by waywardmonkeys** [comment]
Thanks. I've published a new version of the Rust bindings that should have this fixed.
