### ISSUE TITLE
Inconsistent results with QF_FP between incremental and non-incremental solver

### ISSUE THREAD

**Issue by tdudziak** [Z3Prover/z3#207]
I ran into some problems with floating point and NaNs. Initially I though I misunderstood how NaNs are handled in the theory of floats but it's probably a bug because the result switches between sat and unsat depending on whether I use the incremental solver or not. It looks as if the incremental solver accidentally uses floating point equality (where `!(NaN == NaN)`).

Input:
```
(set-option :produce-models true)
(set-logic QF_FP)

(declare-const x (_ FloatingPoint 11 53))

(push)
(assert (and (fp.isNaN x) (not (= x (_ NaN 11 53)))))

(check-sat) ; sat (!)
(get-model) ; x is (_ NaN 11 53)
```

Without `(push)`, the result is unsat. I've tested on recent Z3 built from a7a0deed3f.

**Comment by wintersteiger** [comment]
Thanks for the report! Your suspicion was quite right, there were two cases in which the wrong equality was used. This is now fixed in unstable.
