### ISSUE TITLE
z3 runs a lot slower in cygwin with python

### ISSUE THREAD

**Issue by BitsByWill** [Z3Prover/z3#2070]
Hi,

I was solving a CTF reverse engineering problem and needed z3 to solve a part of it.  When I first installed it, I did it with pip on cygwin.  Running my script involving z3 ran for hours without any results.  I also tried it on another computer (both python 2 and 3 were also used) and the same problem occurred.  When I switched to my Debian system (installed z3 with pip too), I ran the exact same script and it was solved in less than a second.
Here's the constraint portion of my script:
```
p.add((s0 + s1) % 36 == 14)
p.add((s2 + s3) % 36 == 24)
p.add((s2 - s0) % 36 == 6)
p.add((s5 + s3 + s1) % 36 == 4)
p.add((s6 + s4 + s2) % 36 == 13)
p.add((s5 + s4 + s3) % 36 == 22)
p.add((s10 + s8 + s6) % 36 == 31)
p.add((s7 + s4 + s1) % 36 == 7)
p.add((s9 + s12 + s15) % 36 == 20)
p.add((s13 + s14 + s15) % 36 == 12)
p.add((s8 + s9 + s10) % 36 == 27)
p.add((s7 + s12 + s13) % 36 == 23)
```
When I took out 3 to 4 of the constraints, z3 on cygwin managed to solve it in a few seconds.  But using all of these constraints caused it to still run after several hours on cygwin.  Any ideas on what is causing this issue?

**Comment by NikolajBjorner** [comment]
This answer is perhaps simple: The linear integer arithmetic solver isn't particularly strong.
There is a clear pattern in your constraints: everything is modulo 36 so the real beef is how each of the variables behave modulo 36. You could reformulate the problem to use bounded integers (and hope that Z3 picks up it is a finite domain problem and translates it to bit-vectors) or formulate the problem using bit-vectors of bit-width 6.

**Comment by NikolajBjorner** [comment]
could then be difference between big-int reasoning (GMP vs. built-in) or simple instability (under different random seeds, set smt.random_seed to different values and see if it performs the same).

**Comment by NikolajBjorner** [comment]
BTW, I tried your example locally on Windows on the latest build with 100 different random seeds. It is always instantaneous. Under Cygwin to dig in, perhaps try to set_param(verbose=10) and see if search itself takes a different path.

**Comment by BitsByWill** [comment]
Alright, I just messed around with the random seeds.  For my cygwin, any seed larger or equal to 25 solves the problem instantaneously.  Any other lower seed value causes it to not get anywhere.  I'm just glad it works now!  Thanks!

**Comment by NikolajBjorner** [comment]
It isn't your bug if Z3 gets stuck on an otherwise very easy problem depending on random seeds.
With the first 3500 seeds, it doesn't reproduce on Windows yet. Understanding the diverging case could help improve the integer linear solver.

**Comment by BitsByWill** [comment]
Oh okay.  Would you like me to post a pastebin showing the messages z3 in verbose mode outputs for the seeds that don't work for me?  If so, is just a small section of the output enough?

**Comment by NikolajBjorner** [comment]
what is more useful is a z3.log obtained by calling z3.Z3_open_log before other calls.
This may generate a reproducible starting point where Z3 loops. 
The best is of course an SMT-LIB2 file with the right random seed that diverges across platforms.
After 10K random seeds on the example, Z3 doesn't diverge on me.

**Comment by BitsByWill** [comment]
I recorded some log files before the solving started to take really long.  Also, as a correction, the problem did get solved with a random seed of 20, but it took like half a minute (much longer than the nearly instantaneous time it took with a seed of 25).  When I didn't change the seeds previously, it was still running after 5 hours.  Here are the log files for random seed 20, 25 and a few seeds that didn't work (by the way, what does the logged text even mean?):
Random seed 1:
https://pastebin.com/m6qXe4A7
Random seed 7:
https://pastebin.com/MtqSKpNU
Random seed 15:
https://pastebin.com/9feGJwC2
Random seed 17:
https://pastebin.com/rprksbTf
Random seed 19:
https://pastebin.com/Zqk18mn4
Random seed 20:
https://pastebin.com/K65DhZqF
Random seed 25:
https://pastebin.com/bbuy1qhr

Let me know if this helps at all.

**Comment by NikolajBjorner** [comment]
the log files indicate you are running version 4.8.0. The newest version is 4.8.4 and in particular it uses a new LIA solver. This is the one that gets exercised. It has special heuristics for finding integral solutions that the old solver doesn't have so I would discount performance brittleness on the older version.

**Comment by BitsByWill** [comment]
Oh okay.  I guess pip did not install the newest version.
