### ISSUE TITLE
String Solver Regex wrong answer and crash

### ISSUE THREAD

**Issue by pjljvandelaar** [Z3Prover/z3#2071]
When running z3 version 4.8.4 on windows as follows on the attached files, one gets
```
PS C:\temp\TorXakis\sys\solve> z3 .\logRegex3+.txt
(:name "Z3")
(:version "4.8.4 - build hashcode b40c2b2926ed")
sat
((i1000$$1000 "dd"))
PS C:\temp\TorXakis\sys\solve> z3 .\logRegex35.txt
(:name "Z3")
(:version "4.8.4 - build hashcode b40c2b2926ed")
sat
((i1000$$1000 "cc"))
PS C:\temp\TorXakis\sys\solve> z3 smt.string_solver=z3str3 .\logRegex3+.txt
(:name "Z3")
(:version "4.8.4 - build hashcode b40c2b2926ed")

CRASH


PS C:\temp\TorXakis\sys\solve> z3 smt.string_solver=z3str3 .\logRegex35.txt
(:name "Z3")
(:version "4.8.4 - build hashcode b40c2b2926ed")
sat
((i1000$$1000 "ccccc"))
PS C:\temp\TorXakis\sys\solve>
```
[logRegex35.txt](https://github.com/Z3Prover/z3/files/2733133/logRegex35.txt)
[logRegex3+.txt](https://github.com/Z3Prover/z3/files/2733134/logRegex3%2B.txt)

The answer of z3 is wrong: it should be at least 3 characters long.
Z3str3 crashes on the first case, but the answer of z3str3 is right on the second case.

Success solving this bug and crash!

Greetings

**Comment by NikolajBjorner** [comment]
try with latest fix

**Comment by pjljvandelaar** [comment]
I Will try  tomorrow.

**Comment by pjljvandelaar** [comment]
The bug is indeed solved in z3 4.8.5 - build hashcode 14f3ff0b6325.

However, the crash with `  z3 smt.string_solver=z3str3  .\logRegex3+.txt` is still present.

So I don't close this issue yet ;-(

**Comment by NikolajBjorner** [comment]
correct

**Comment by pjljvandelaar** [comment]
problem is still present.
we are updating TorXakis and have to execlude z3str as solver due to the following failing smt2 files.
[txs-smt.zip](https://github.com/Z3Prover/z3/files/3574154/txs-smt.zip)
All issues seem to be traced back to
`(re.loop <expr> <int>)`

**Comment by mtrberzi** [comment]
Thanks very much for the bug report. I believe I understand the issue - I didn't implement support for the two-argument version of `re.loop` (which is what appears in the crashing case) because the standard only specifies the three-argument version. I should be able to add this without too much difficulty.

**Comment by mtrberzi** [comment]
Opened #2620
