### ISSUE TITLE
datatype definition crashes with SIGSEGV in z3 version>4.5

### ISSUE THREAD

**Issue by nikivazou** [Z3Prover/z3#2077]
The below definitions 

```
; a.smt2
(declare-datatypes (T0 T1) (
    (Fun (junkFun (jfunArg T0) (jFunRes T1)) 
    (Fun (FunArg T1) (FunRes Int)))
    )
)
(declare-datatypes (T0) ((Term Unit)))

(declare-datatypes (T0) ((Foo (Foo (ffield (Fun (Term T0) T0))))))
```

crash `z3` with 

```
> z3 a.smt2
fish: 'z3 a.smt2' terminated by signal SIGSEGV (Address boundary error)
```

This was not an issue with z3 version 4.5

-- Triggered by @yiyunliu

**Comment by NikolajBjorner** [comment]
@c-cube: this is related to how sizes of datatypes are computed in the new representation. The multiple nested instantiations produce a sort that does not have the same type parameters of the data-type definition. The code that computes sizes does not take these instantiations into account.
