### ISSUE TITLE
libz3java.dll should be z3java.dll

### ISSUE THREAD

**Issue by ffrohn** [Z3Prover/z3#208]
Dear all,

with version 4.4.0, I was not able to use the Z3 java bindings on a Windows machine until I renamed the file libz3java.dll to z3java.dll. The problem could be reproduced on two different machines.

Best
Florian

**Comment by wintersteiger** [comment]
If Z3 can't find z3java.dll, it will try to load libz3java.dll, at least one of them needs to be present. This is done here: https://github.com/Z3Prover/z3/blob/unstable/scripts/update_api.py#L573 but this change hasn't made it into the master branch yet, so you'll have to to upgrade to the unstable branch for now.

The reason for this was that Cygwin looked for libz3java.dll while Windows itself looks for z3java.dll, so if those two were combined (e.g., build in cygwin bash, run in normal bash, or vice versa), you'd get exactly those problems.
