### ISSUE TITLE
Incorrect proof related to div

### ISSUE THREAD

**Issue by boehmes** [Z3Prover/z3#2082]
The following invocation of Z3 (version 4.8.4 and the nightly build z3-4.8.5.6e60926cc383-x86-win) produces an incorrect proof:

`z3.exe smt.random_seed=1 smt.refine_inj_axioms=false -T:20 -smt2 test.smt2`

where test.smt2 contains the following content:

```
(set-option :produce-proofs true)
(declare-datatypes () ((Num$ (one$) (bit0$ (select$ Num$)) (bit1$ (selecta$ Num$)))))
(declare-fun divide$ (Int Int) Int)
(declare-fun modulo$ (Int Int) Int)
(assert (! (not (= (divide$ 0 5) 0)) :named a0))
(assert (! (forall ((?v0 Int) (?v1 Int)) (= (divide$ ?v0 ?v1) (ite (= ?v1 0) 0 (ite (< 0 ?v1) (div ?v0 ?v1) (div (- ?v0) (- ?v1)))))) :named a1))
(assert (! (forall ((?v0 Int) (?v1 Int)) (= (modulo$ ?v0 ?v1) (ite (= ?v1 0) ?v0 (ite (< 0 ?v1) (mod ?v0 ?v1) (- (mod (- ?v0) (- ?v1))))))) :named a2))
(check-sat)
(get-proof)
```

In the produced proof, there is a rewrite step which is roughly as follows:

`div (- 1 * a) (- 1 * b) = (if 0 = - 1 then div 0 0 else div a b)`

This should be wrong, if one takes a=5 and b=2 and Z3 follows the [SMTLIB specification](http://smtlib.cs.uiowa.edu/theories-Ints.shtml) saying:

>Regardless of sign of m, 
>  when n is positive, (div m n) is the floor of the rational number m/n;
>  when n is negative, (div m n) is the ceiling of m/n.

**Comment by NikolajBjorner** [comment]
a good one
