### ISSUE TITLE
(check-sat-using qfnra-nlsat) returns "unknown" and a model

### ISSUE THREAD

**Issue by Maryam81609** [Z3Prover/z3#2083]
For my non-linear optimization problem, `(check-sat-using qfnra-nlsat)` gives a model, but returns "unknown". And the given model is correct.

I know that the model is solvable. Only one of the variables makes the model non-linear, and when I assign a value to that (so that the model is not non-linear anymore, but simple arithmetic with constraints), `(check-sat)` returns "sat". 

All values and variables have the `Real` type.

**Comment by Maryam81609** [comment]
I was using rise4fun, where (get-info :reason-unknown) returns "incomplete". 
However, calling z3 on my machine works well and returns "sat" for the same code. Thanks!

**Comment by NikolajBjorner** [comment]
for some reason the older version of Z3 on rise4fun uses a solver combination that doesn't trust the result when there is non-linear multiplication. It is better to use the up-to-date version of Z3 as a reference point for what bugs have been fixed. I use a mostly stable version of Z3 on rise4fun.
