### ISSUE TITLE
How to create constant (interpreted) from a sort?

### ISSUE THREAD

**Issue by typon** [Z3Prover/z3#2086]
If I have the following z3 code:
```python
Color, (red, green, blue) = EnumSort('Color', ['red', 'green', 'blue'])
...
# At a later time, say I don't have access to the variables "red", "green" or "blue"
# How can I instantiate one of the enum constants (interpreted)?
# To instantiate a variable, i could do:
color = z3.Constant("color", Color)
```

Is there any API that I could use to instantiate "red", for example? I want to be able to construct expressions somewhere else in my code with the enum values, but i only have access to the EnumSort itself. I'm willing to implement some ugly hacks to get this working, if you could point me in the right direction.

**Comment by LeventErkok** [comment]
@typon 

If I may chime in.. These sort of end-user questions are better suited for forums like stack-overflow. See here: https://stackoverflow.com/questions/tagged/z3

Having said that; yes, you can indeed access the constructors and build variables out of them so long as you have access to the sort declaration:

```python
from z3 import *

Color, (red, green, blue) = EnumSort('Color', ['red', 'green', 'blue'])

nElems = Color.num_constructors();

s = Solver()

vs = [Const("v%d" % i, Color) for i in range(nElems)]
for i in range(nElems):
    s.add(vs[i] == Color.constructor(i)())

print s.check()
print s.model()
```

This prints:

```
sat
[v2 = blue, v0 = red, v1 = green]
```

Hope this helps! For any further discussion, it'd be best to utilize stack-overflow z3/z3py tags.

**Comment by NikolajBjorner** [comment]
Thanks @LeventErkok.

**Comment by typon** [comment]
@leventerkok

Sorry about that. Next time I will use stackoverflow.com.

Thanks for your help, that looks like exactly what I need!
