### ISSUE TITLE
z3 optsmt upper bound clarification

### ISSUE THREAD

**Issue by muqsitazeem148** [Z3Prover/z3#2087]
I am using python binding of Z3 (version 4.8.0) under 64bit Linux

I am trying to find out minimum value that a variable 'x' can take, together with a bunch of other constraints, by using minimize(x). I get an output that looks like this:

(optimize:check-sat)
(optimize:sat)
(optsmt upper bound: 859)
(optsmt upper bound: 209)
(optsmt upper bound: 60)

I want to know the meaning the values 859, 209, 60. Does this mean that there exists solutions with x=859, 209 and 60; which satifies all the constraints? And it's still trying to find out a value of x lesser than 60?

If yes, is there a way to extract the entire model that it has for x = 60, while it continues to look for lesser values of x?

**Comment by NikolajBjorner** [comment]
If you cancel Z3, then it will return the best model found so far. So if you cancel (interrupt) after it reports 209, it should return a model with bound 209.

**Comment by NikolajBjorner** [comment]
I have added a configuration parameter that you can use to dump the models.
Usage: 
     z3 <file> opt.dump_models=true
