### ISSUE TITLE
z3str3 str.indexof BUG (with offset)

### ISSUE THREAD

**Issue by SaneBow** [Z3Prover/z3#2092]
Minimized example:

```
(set-option :smt.string_solver z3str3)

(declare-fun s () String)
(assert (= (str.indexof "01234" "3" 2) 3))
(assert (= (str.indexof s "_" 2) 1))

(check-sat)
(get-model)
```

Output:

```
sat
(model
  (define-fun s () String
    "_ex___aw")
)
```

When the string is a constant, the result index is correct (counted from the beginning of the string). However, when the string is a symbolic variable, the meaning of `str.indexof` becomes the index after the offset. The correct value of `(str.indexof s "_" 2)` for `_ex__aw` should be 3, which can be checked with `(assert (= (str.indexof "_ex___aw" "_" 2) 3))`.

If we set the solver option to "seq", it gives the correct result (unsat).

**Comment by mtrberzi** [comment]
Thanks for the report. I'm having some trouble reproducing this in the latest version of Z3. I've checked a few different runs with Z3str3 of your instance and gotten models similar to the following:

```
sat
(model 
  (define-fun s () String
    "__r__aaaD")
)
```

which seems to be valid. Are you able to reproduce this on the latest commit?

**Comment by SaneBow** [comment]
I have just pulled and built the latest commit f00697cf95b8b025c4769217554243a14e1a581b and it is still the same result for me. `z3 --version` shows `Z3 version 4.8.5 - 64 bit`. I ran the test simply with `z3 z3str3_bug.smt`. I can even produce the same result both on my Macbook and PC.

**Comment by SaneBow** [comment]
@mtrberzi I think even your test output is incorrect. By definition of `indexof(str, sub, start)`, the returned index should never be smaller than `start` as it's the index of the original string (`str`). Shouldn't the correct result be `unsat`?

**Comment by mtrberzi** [comment]
Thanks, I did check this again and it does seem to produce the wrong answer. I think the test output I was looking at was for a different case, sorry for the confusion. I think `unsat` is correct here, I'll take a look at Z3str3 to see what might be happening.
