### ISSUE TITLE
contains() is inefficient with vector classes

### ISSUE THREAD

**Issue by volodya31415** [Z3Prover/z3#2098]
I have been running small test cases with z3 and discovered a few inefficiencies. In particular, one of the test cases spends 97% of cpu time in contains method of variable m_del_bin, called from big::in_del (line 169 of sat_big.cpp). 

Since m_del_bin is plain vector class and not a hash table it is unsurprising that contains() is very expensive. I can see that some of the other contains() calls use hash-table variables, but this one does not.

I attached a file with test case that was run (extension .smt.txt) and a text file with perf output.

[signal_test3.smt.txt](https://github.com/Z3Prover/z3/files/2787195/signal_test3.smt.txt)
[signal_test3.perf.txt](https://github.com/Z3Prover/z3/files/2787196/signal_test3.perf.txt)

**Comment by NikolajBjorner** [comment]
It was likely calling the routine in sat_big a large number of times. This was exposed by #2101 and has been fixed with a throttle.

**Comment by NikolajBjorner** [comment]
this would be fixed with the second push in this thread

**Comment by volodya31415** [comment]
Right, that inefficiency is gone, I see a trace with a bunch of different functions. Thank you !
