### ISSUE TITLE
Test tst_udoc_relation throws and exception on ARM, PowerPC

### ISSUE THREAD

**Issue by tautschnig** [Z3Prover/z3#210]
Hi,

The Debian auto-builds of Z3 presently fail on both ARM and PowerPC architectures while running tst_udoc_relation (this is the unstable branch up to 6a50f10b8b). A full build log can be found here:

https://buildd.debian.org/status/fetch.php?pkg=z3&arch=armel&ver=4.4.0-3&stamp=1440859344

The stack trace upon throwing the exception is:

(gdb) bt
\#0  0xb6ebaeac in __cxa_throw () from /usr/lib/arm-linux-gnueabi/libstdc++.so.6
\#1  0x00283a18 in datalog::check_relation_plugin::check_equiv (this=0x9f0bd1f8, this@entry=0xa8e4bd2c, objective=0xbeffe000 "t\303 \237\f\350\377\276\025", fml1=0xb064fcc4, fml2=0xa8e4bd2c) at ../src/muz/rel/check_relation.cpp:438
\#2  0x002882fc in datalog::check_relation_plugin::verify_filter_by_negation (this=0xa8e4bd2c, dst0=0xbeffe378, dst=..., neg=..., cols1=..., cols2=...) at ../src/muz/rel/check_relation.cpp:752
\#3  0x00079194 in udoc_tester::apply_filter_neg (this=0xbeffe808, dst=..., neg=..., cols1=..., cols2=...) at ../src/test/udoc_relation.cpp:866
\#4  0x000793a8 in udoc_tester::test_filter_neg2 (this=this@entry=0xbeffe808) at ../src/test/udoc_relation.cpp:729
\#5  0x0007c620 in udoc_tester::test1 (this=this@entry=0xbeffe808) at ../src/test/udoc_relation.cpp:165
\#6  0x00075cec in tst_udoc_relation () at ../src/test/udoc_relation.cpp:926
\#7  0x000186c0 in main (argc=2, argv=0xbefff754) at ../src/test/main.cpp:146

One aspect that is specific to these architectures is that char is unsigned by default, which is also warned about by the compiler on the following instances:

../src/qe/qe_lite.cpp: In member function 'fm::constraint* fm::fm::resolve(const fm::constraint&, const fm::constraint&, fm::var)':
../src/qe/qe_lite.cpp:2067:17: warning: case label value is less than minimum value for type

../src/parsers/smt2/smt2scanner.cpp: In member function 'smt2::scanner::token smt2::scanner::scan()':
../src/parsers/smt2/smt2scanner.cpp:335:13: warning: case label value is less than minimum value for type

../src/tactic/arith/fm_tactic.cpp: In member function 'fm_tactic::constraint* fm_tactic::imp::resolve(const fm_tactic::constraint&, const fm_tactic::constraint&, fm_tactic::var)':
../src/tactic/arith/fm_tactic.cpp:1398:17: warning: case label value is less than minimum value for type

At least the above instances should use "signed char", but please let me know what further info I might be able to provide in order to properly diagnose the problem.

Best,
Michael

**Comment by NikolajBjorner** [comment]
Does this do the trick?

**Comment by tautschnig** [comment]
Thanks a lot for those fixes, but it does not seem to affect the outcome of that test yet I'm afraid! Any suggestions to help debugging this issue are welcome.

Best,
Michael

**Comment by NikolajBjorner** [comment]
The test prints some diagnostics. I updated the unstable branch so that it gets printed by default (the old behavior required to run with verbosity set to >= 3). 
We can get additional information by running the unit test under debug mode as follows:

             test-z3.exe udoc_relation /tr:doc /v:3

This will display both the non-equivalent versions computed by the TBVs, it will also create a .z3-trace file with additional tracing information. The trace mode is only enabled with the debug build.

The TBV module plays some bit-tricks that in the end may not be portable.

**Comment by nunoplopes** [comment]
That's probably that. ARM and PPC and big-endian, and we read the raw number representation. To make it portable we would need some byte swaps.

**Comment by NikolajBjorner** [comment]
but where? :-)
E.g., this kind of code:

       // 10101010 = 2 + 8 + 32 + 128
       memset(bv.m_data, 2 + 8 + 32 + 128, m.num_bytes());

**Comment by tautschnig** [comment]
Thanks a lot for the further info - I did run the proposed command and got the following output:
<pre>
dst:{xxx}
neg:{0x1}
true
(and true (not (and (= (:var 0) #b1) (= (:var 2) #b0))))
(and (= (:var 0) #b1) (= (:var 2) #b0))
(let ((a!1 (not (exists ((x!1 (_ BitVec 1))
                         (x!2 (_ BitVec 1))
                         (x!3 (_ BitVec 1)))
                  (and (= x!3 #b1)
                       (= x!1 #b0)
                       (= k!0 x!3)
                       (= k!1 x!2)
                       (= k!2 x!1))))))
  (and true a!1))
(and true (not (and (= k!0 #b1) (= k!2 #b0))))
(smt.searching)
ASSERTION VIOLATION
File: ../src/smt/smt_context.cpp
Line: 210
get_assignment(not_l) == l_false
(C)ontinue, (A)bort, (S)top, (T)hrow exception, Invoke (G)DB
T
assertion violation
dangling: 0x1e02104
dangling: 0x1e0235c
dangling: 0x1e023a4
PASS
(test udoc_relation :time 0.04 :before-memory 0.00 :after-memory 0.05)
</pre>

with (possibly redundant) info in .z3-trace:

<pre>
-------- [doc] check_equiv ../src/muz/rel/check_relation.cpp:422 ---------
(and true (not (and (= k!0 #b1) (= k!2 #b0))))
(let ((a!1 (not (exists ((x!1 (_ BitVec 1))
                         (x!2 (_ BitVec 1))
                         (x!3 (_ BitVec 1)))
                  (and (= x!3 #b1)
                       (= x!1 #b0)
                       (= k!0 x!3)
                       (= k!1 x!2)
                       (= k!2 x!1))))))
  (and true a!1))
------------------------------------------------
-------- [doc] ~tbv_manager ../src/muz/rel/tbv.cpp:39 ---------
dangling: 0x1e02104
------------------------------------------------
-------- [doc] ~tbv_manager ../src/muz/rel/tbv.cpp:39 ---------
dangling: 0x1e0235c
------------------------------------------------
-------- [doc] ~tbv_manager ../src/muz/rel/tbv.cpp:39 ---------
dangling: 0x1e023a4
------------------------------------------------
</pre>

Best,
Michael

**Comment by nunoplopes** [comment]
I've commited a (tentative) fix for the crash in the SMT solver.  Michael: could you please rerun the experiment to check if the problem goes away?  Thanks!
(sorry, I don't have handy access to this kind of machines)

**Comment by tautschnig** [comment]
Thanks a lot for the further patch - this undoubtedly changes things, but doesn't seem to fully fix all problems. Here is the updated output, after applying the signedness-patches:
<pre>
dst:{xxx}
neg:{0x1}
true
(and true (not (and (= (:var 0) #b1) (= (:var 2) #b0))))
(and (= (:var 0) #b1) (= (:var 2) #b0))
(let ((a!1 (not (exists ((x!1 (_ BitVec 1))
                         (x!2 (_ BitVec 1))
                         (x!3 (_ BitVec 1)))
                  (and (= x!3 #b1)
                       (= x!1 #b0)
                       (= k!0 x!3)
                       (= k!1 x!2)
                       (= k!2 x!1))))))
  (and true a!1))
(and true (not (and (= k!0 #b1) (= k!2 #b0))))
(smt.searching)
ASSERTION VIOLATION
File: ../src/smt/smt_enode.h
Line: 340
m_lbl_hash >= 0 && static_cast<unsigned>(m_lbl_hash) < approx_set_traits<unsigned long long>::capacity
(C)ontinue, (A)bort, (S)top, (T)hrow exception, Invoke (G)DB
T
assertion violation
dangling: 0x2778104
dangling: 0x277835c
dangling: 0x27783a4
PASS
(test udoc_relation :time 0.04 :before-memory 0.00 :after-memory 0.05)
</pre>
I am happy to give further patches a try, this is very easy for me.

Best,
Michael

**Comment by NikolajBjorner** [comment]
This is possibly going to require more signed char annotations and apparently the compiler didn't catch what seems to be the source of this one. I checked in a possible fix, but I suspect it will only address the exposed malignment of signed and unsigned character semantics partially.

**Comment by tautschnig** [comment]
Thanks a lot for further diving into this, I do believe the original problem (the test udoc_relation) is fixed now.

Yet I now get a further failure in a later test, as follows:

<pre>
(gdb) bt
#0  0xb6ebaea8 in __cxa_throw () from /usr/lib/arm-linux-gnueabi/libstdc++.so.6
#1  0x00ababa4 in th_rewriter_cfg::max_steps_exceeded (this=0x9a6d8f84, this=0x9a6d8f84, num_steps=1)
    at ../src/ast/rewriter/th_rewriter.cpp:104
#2  rewriter_tpl<th_rewriter_cfg>::check_max_steps (this=0x9a6d8edc) at ../src/ast/rewriter/rewriter.h:258
#3  rewriter_tpl<th_rewriter_cfg>::resume_core<false> (this=0x9a6d8edc, result=..., result_pr=...)
    at ../src/ast/rewriter/rewriter_def.h:586
#4  0x00abdce4 in rewriter_tpl<th_rewriter_cfg>::main_loop<false> (result_pr=..., result=..., t=<optimized out>,
    this=<optimized out>) at ../src/ast/rewriter/rewriter_def.h:568
#5  rewriter_tpl<th_rewriter_cfg>::operator() (this=<optimized out>, t=<optimized out>, result=..., result_pr=...)
    at ../src/ast/rewriter/rewriter_def.h:633
#6  0x00ab4ef4 in rewriter_tpl<th_rewriter_cfg>::operator() (result=..., t=<optimized out>, this=<optimized out>)
    at ../src/ast/rewriter/rewriter.h:348
#7  th_rewriter::operator() (this=this@entry=0x9d8a4624, term=...) at ../src/ast/rewriter/th_rewriter.cpp:753
#8  0x0045b690 in qe::quant_elim_plugin::normalize (this=0x9d8a4604, result=..., pos=..., neg=...)
    at ../src/qe/qe.cpp:1804
#9  0x00460cc0 in qe::quant_elim_plugin::check (this=0x9d8a4604, num_vars=num_vars@entry=1, vars=0x0,
    vars@entry=0xbefff23c, assumption=0x0, fml=..., get_first=false, get_first@entry=28, free_vars=...,
    defs=0xbeffec04, defs@entry=0xb6ffef10 <__stack_chk_guard>) at ../src/qe/qe.cpp:1437
#10 0x00461388 in qe::quant_elim_new::eliminate_block (this=0xa9a6791c, num_vars=1, vars=0xbefff23c, fml=...,
    free_vars=..., get_first=false, defs=0xbeffec04) at ../src/qe/qe.cpp:2174
#11 0x00451860 in qe::expr_quant_elim::solve_for_vars (this=this@entry=0xbeffec84, num_vars=num_vars@entry=1,
    vars=vars@entry=0xbefff23c, _fml=_fml@entry=0x9a25a2ac, defs=...) at ../src/qe/qe.cpp:2408
#12 0x000fac48 in test_quant_solver (m=..., sz=sz@entry=1, xs=0xbefff23c, xs@entry=0xbefff234, fml=0x6572616c,
    validate=validate@entry=true) at ../src/test/quant_solve.cpp:91
#13 0x000fc0d0 in test_quant_solver (m=..., x=0xbefff5c0, x@entry=0x9ba50754, str=<optimized out>, validate=true)
    at ../src/test/quant_solve.cpp:156
#14 0x000fc51c in test_quant_solve1 () at ../src/test/quant_solve.cpp:184
#15 0x000fcb70 in tst_quant_solve () at ../src/test/quant_solve.cpp:254
#16 0x0001f0a4 in main (argc=2, argv=0xbefff754) at ../src/test/main.cpp:218
(gdb) cont
Continuing.
terminate called after throwing an instance of 'rewriter_exception'

Program received signal SIGABRT, Aborted.
0xb6c23aa4 in raise () from /lib/arm-linux-gnueabi/libc.so.6
</pre>

What I find very worrying about this is that it is not reproducible when running quant_solve by itself, but instead there must be an interaction with the test "datalog_parser", as I deduce from the following experiment. I changed the code in src/test/main.cpp to the following:

<pre>
#if 0
...
#endif
    TST(datalog_parser);
    //TST_ARGV(datalog_parser_file);
    //TST(dl_query);
    TST(quant_solve);
</pre>

This yields the following output:

<pre>
$ build/test-z3 -a
Expecting colon in declaration (first occurence of a predicate must be a declaration) at line 2 '' found ','

Parser did not succeed on string

H :- C1(X,a,b), C2(Y,a,X) .
Expecting colon in declaration (first occurence of a predicate must be a declaration) at line 3 '' found ','

Parser did not succeed on string
N 128

H :- C1(X,a,b), C2(Y,a,X) .
out of memory
Parser did not succeed on string
N 128
I 128

C1(x : N, y : N, z : I)
C2(x : N, y : N, z : N)
H :- C1(X,a,b), C2(Y,a,X) .
Expecting colon in declaration (first occurence of a predicate must be a declaration) at line 2 '' found ','

Parser did not succeed on string

H :- C1(X,a,b), nC2(Y,a,X) .
Expecting colon in declaration (first occurence of a predicate must be a declaration) at line 2 '' found ','

Parser did not succeed on string

H :- C1(X,a,b),nC2(Y,a,X).
Expecting colon in declaration (first occurence of a predicate must be a declaration) at line 2 '' found ','

Parser did not succeed on string

H :- C1(X,a,b),\
C2(Y,a,X).
Expecting colon in declaration (first occurence of a predicate must be a declaration) at line 2 '' found ','

Parser did not succeed on string

H :- C1(X,a\,\b), C2(Y,a,X) .
PASS
(test datalog_parser :time 247.17 :before-memory 0.02 :after-memory 2048.05)
Expecting colon in declaration (first occurence of a predicate must be a declaration) at line 2 '' found ','

Parser did not succeed on string

H :- C1(X,a,b), C2(Y,a,X) .
Expecting colon in declaration (first occurence of a predicate must be a declaration) at line 3 '' found ','

Parser did not succeed on string
N 128

H :- C1(X,a,b), C2(Y,a,X) .
out of memory
Parser did not succeed on string
N 128
I 128

C1(x : N, y : N, z : I)
C2(x : N, y : N, z : N)
H :- C1(X,a,b), C2(Y,a,X) .
Expecting colon in declaration (first occurence of a predicate must be a declaration) at line 2 '' found ','

Parser did not succeed on string

H :- C1(X,a,b), nC2(Y,a,X) .
Expecting colon in declaration (first occurence of a predicate must be a declaration) at line 2 '' found ','

Parser did not succeed on string

H :- C1(X,a,b),nC2(Y,a,X).
Expecting colon in declaration (first occurence of a predicate must be a declaration) at line 2 '' found ','

Parser did not succeed on string

H :- C1(X,a,b),\
C2(Y,a,X).
Expecting colon in declaration (first occurence of a predicate must be a declaration) at line 2 '' found ','

Parser did not succeed on string

H :- C1(X,a\,\b), C2(Y,a,X) .
PASS
(test datalog_parser :time 247.12 :before-memory 2048.05 :after-memory 4096.05)
terminate called after throwing an instance of 'rewriter_exception'
Aborted
</pre>

Best,
Michael

**Comment by NikolajBjorner** [comment]
The quant_solve unit test exits the process (because I was using it to debug a memory leak).
It now does not exit the process, so the behavior has changed. 
The error messages from datalog_parser unit test are expected: the unit test throws malformed input to the parser.

**Comment by tautschnig** [comment]
Hi Nikolaj,
So with your latest patch quant_solve (when run in isolation) nicely ends with

<pre>
...
validating: (not (=> true true))
PASS
(test quant_solve :time 0.78 :before-memory 0.02 :after-memory 1.11)
</pre>

Yet when run after datalog_parser, the rewriter_exception remains. Disabling datalog_parser (but running all the rest I get pretty far:

<pre>
...
(smt.preprocessing :time 0.01 :before-memory 1977.56 :after-memory 1977.56)
PASS
(test qe_arith :time 0.06 :before-memory 1976.64 :after-memory 1976.66)
terminate called after throwing an instance of 'out_of_memory_error'
Aborted
</pre>

So this is expr_substitution running out of memory, which it also does when run in isolation.

Am I right to summarise that the proposed patches solve the problems in udoc_relation, and just happen to uncover a few others, notably one in datalog_parser? (I don't know whether expr_substitution ever worked, on any platform, as previously you would terminate the test runs after quant_solve.)

Best,
Michael

**Comment by NikolajBjorner** [comment]
1. The crashes exposed by running the udoc_relation test seem based on signed / unsigned char semantics. I have fixed the ones we could identify so far. The udoc_relation test exercises a lot of code, so it identified a number of places where to fix signed/unsigned throughout the code base.

2. You seem to run the unit tests all in a row (test-z3.exe -a). This option is actually ill suited because some unit tests allocate a lot of memory. For example, the "vector" unit tests check specifically for memory overflow and end up allocating 1/2 GB. 

3. The "expr_substitution" unit wasn't terminating. I now commented out the portion that diverges. This would be the cause of the exception you logged. The unit test should of course terminate. It is independent of ARM.

**Comment by tautschnig** [comment]
Ad 2: I wasn't aware the the unit tests didn't clean up after themselves. Certainly I could run all the tests individually, but with -a being available that just seemed like the most straight forward thing to do.
Ad 3: Thanks a lot for this fix; tst_sat_user_scope happens to be another non-terminating test (https://github.com/Z3Prover/z3/blob/unstable/src/test/sat_user_scope.cpp#L90), and the fuzzing in theory_pb takes forever, yet eventually crashed for me (segmentation fault on an i386, but I haven't investigated this yet) - so probably that's useful.

**Comment by NikolajBjorner** [comment]
It is a good point to fix these unit tests so that they smoothly, so yes I am looking into the other failures.
When it comes to testing Z3 on ARM, I would suggest to use the regression test suite from the z3test repository. It is also available from GitHub under z3prover. We run these regressions on every check-in and they cover a fair amount of end-to-end functionality.

**Comment by tautschnig** [comment]
Oh, thanks a lot, I wasn't quite aware. Is there any chance the stuff in z3test could get a license and copyright information so that I can legitimately use (and maybe even distribute) them?

**Comment by NikolajBjorner** [comment]
Sure. But before distributing them, I hope you can use this to test ARM..

I now added copyright to several files in z3test (1110 files got changed when adding copyright notices).
This could potentially destabilize the regression test itself, but this will be fixed when I get the reports from our build. File a separate bug if you rely on files not covered in z3test (ClusterExperiment isn't tagged because it contains a bunch of files with some character set selection).

**Comment by tautschnig** [comment]
Thanks a lot for all the help. The results on z3test don't look too promising at the moment, though:
Looking at regressions/smt2-debug/poly6.produced.out:
<pre>
unsupported
; poly/isolate-roots
unsupported
; poly/isolate-roots
unsupported
; poly/isolate-roots
unsupported
; poly/isolate-roots
unsupported
; poly/isolate-roots
unsupported
; poly/isolate-roots
unsupported
; poly/isolate-roots
unsupported
; poly/isolate-roots
unsupported
; poly/isolate-roots
unsupported
; poly/isolate-roots
(error "line 47 column 0: unexpected character")
(error "line 47 column 1: unexpected character")
(error "line 47 column 2: unexpected character")
(error "line 47 column 3: unexpected character")
(error "line 47 column 4: unexpected character")
(error "line 47 column 5: unexpected character")
(error "line 47 column 6: unexpected character")
...
(error "line 47 column 1362856: unexpected character")
(error "line 47 column 1362857: unexpected character")
(error "line 47 column 1362858: unexpected character")
</pre>

**Comment by NikolajBjorner** [comment]
Are you using the "release" build? The polynomial commands are disabled when the _EXTERNAL_RELEASE flag is set. Our scripts are supposed to take care of building and running the correct binary.

**Comment by NikolajBjorner** [comment]
Can we close this bug?
Seems the ARM port got past the endianness issues.
