### ISSUE TITLE
String solver hangs forever on query with str.len and forall

### ISSUE THREAD

**Issue by GennadyGS** [Z3Prover/z3#2100]
I am trying to define custom function 'upper' (see code fragment below).
According to limitations, described [here](https://stackoverflow.com/questions/36506650/how-to-add-touppercase-function-in-z3?answertab=active#tab-top), I was trying to define at least the most basic axiom about function (returns string with the same length).
However, once I am trying to verify asserted rule with request, closely matching the axiom, Z3 hangs forever, while expected result is 'sat'. In comparison, it correctly returns 'unsat' if change '=' to '>' or '<' in last assertion. By the way, I am not interested in concrete model, just satisfiability.
Reproduced with 4.8.4 for Windows-x86 and https://rise4fun.com as well.

```
(declare-fun upper (String) String)
(declare-fun v1 () String)
(declare-fun v2 () String)
(assert (forall ((x String) (y String))
  (=> (= (upper x) y) (= (str.len x) (str.len y)))))
(assert (= (upper v1) v2))
(assert (= (str.len v1) (str.len v2)))
```

**Comment by NikolajBjorner** [comment]
z3 is unable to synthesize a model here. upper could be identity function, but the way quantifier-instantiation and model search works, it wouldn't be able to detect this.

**Comment by GennadyGS** [comment]
Thanks for your answer.
> z3 is unable to synthesize a model here.
I would like to clarify, is there way to check satisfiability for such case without synthesizing model?
