### ISSUE TITLE
Solver doesn't raise timeout in the specified time

### ISSUE THREAD

**Issue by norhh** [Z3Prover/z3#2101]
Tried the python wrapper of the solver on the latest z3 master branch, for a timeout of 30s on the solver and it doesn't timeout.
[constraints_fail.txt](https://github.com/Z3Prover/z3/files/2793655/constraints_fail.txt) , each constraint in the file is separated by 3 new lines

**Comment by norhh** [comment]
is it optimize.set_param()?

**Comment by NikolajBjorner** [comment]
ok, good

**Comment by NikolajBjorner** [comment]
this is fixed

**Comment by norhh** [comment]
Yes, I checked it out(I wonder why it wasn't closed), @NikolajBjorner thanks for the fix.
