### ISSUE TITLE
Maybe remove commit revision from releases

### ISSUE THREAD

**Issue by zimmski** [Z3Prover/z3#2106]
The commit revision in the release files makes it more difficult to update to a specific version using a script. Instead of defining a specific version (e.g. 4.8.4 or 4.8.3) one has to lookup what commit revision the tag has.

As an example 4.8.4 is
https://github.com/Z3Prover/z3/releases/download/z3-4.8.4/z3-4.8.4.d6df51951f4c-x64-ubuntu-16.04.zip
and 4.8.3 is
https://github.com/Z3Prover/z3/releases/download/z3-4.8.3/z3-4.8.3.7f5d66c3c299-x64-ubuntu-16.04.zip

It is easy to get the "latest" release using GitHub's API (just query https://api.github.com/repos/Z3Prover/z3/releases/latest. With the same API one has to lookup the correct version and then the correct URL. I will implement this now in our installation script but I was just curious if it wouldn't be simplier to ask if the commit revision could be removed and why it is there in the first place?

**Comment by NikolajBjorner** [comment]
OK, will get rid of this in next.
