### ISSUE TITLE
z3str3: Incorrect model

### ISSUE THREAD

**Issue by 4tXJ7f** [Z3Prover/z3#2108]
The following input returns an incorrect model on master 1297eeb817c7b0340f187bee35888c3f51bce569 with `smt.string_solver=z3str3 dump_models=true`:

```
(set-logic QF_S)
(declare-fun x () String)
(assert (not (= (str.replace (str.++ "B" x) x "B") (str.++ "B" "B"))))
; (assert (= x "aT"))
(check-sat)
```

The model returned is `(define-fun x () String "aT")`. When asserting the model by uncommenting the line above, z3str3 reports `unsat`. Z3 master 1297eeb817c7b0340f187bee35888c3f51bce569 and CVC4 both agree that the answer to the original query should be `unsat`.

**Comment by NikolajBjorner** [comment]
@mtrberzi

**Comment by NikolajBjorner** [comment]
The updated behavior of z3str3 seems to be divergence

**Comment by NikolajBjorner** [comment]
z3 2108.smt2 model_validate=true smt.string_solver=z3str3 smt.random_seed=10 /st
sat
(error "line 5 column 11: an invalid model was generated")

**Comment by mtrberzi** [comment]
Z3str3 now times out (I suspect it will have some trouble finding UNSAT here).
