### ISSUE TITLE
z3str3: "NOT IMPLEMENTED YET!" on input with supported operators

### ISSUE THREAD

**Issue by 4tXJ7f** [Z3Prover/z3#2111]
When running master 1297eeb817c7b0340f187bee35888c3f51bce569 with `smt.string_solver=z3str3` on the following input:
```
(set-logic QF_S)
(declare-fun z () Int)
(assert (not (= (str.prefixof "A" (int.to.str z)) false)))
(check-sat)
```

Then I get the following error:
```
NOT IMPLEMENTED YET!
*** stack smashing detected ***: ../z3/build/z3 terminated
Aborted
```

However, `str.prefixof` and `int.to.str` seem to be supported by `smt.string_solver=z3str3` on other inputs. Is this expected?

**Comment by mtrberzi** [comment]
I have an idea of what might be going on here. It seems that when string operators are nested in that way, the solver doesn't treat them as things to be solved for. For the first example I substituted a fresh variable for the `int.to.str` term and the crash doesn't happen. The operators are supported, the part that isn't implemented is a refinement check that looks for this term to be equal to something.

I have a potential solution in the works for this and I will take another look at these cases when it is stable. The idea here is to perform this substitution as part of the rewriting step before solving, essentially to put string equations into something like a "normal form".

**Comment by NikolajBjorner** [comment]
@mtrberzi this is still throwing NOT_IMPLEMENTED_YET

**Comment by mtrberzi** [comment]
Known issue with `int.to.str`, we are investigating how to handle this.

**Comment by mtrberzi** [comment]
Fix in progress for this one.

**Comment by mtrberzi** [comment]
Opened #4313
