### ISSUE TITLE
Incorrect unsat: Equality of casted float to bit-vector

### ISSUE THREAD

**Issue by maiermic** [Z3Prover/z3#2113]
Casting 2<sup>31</sup> (2147483648) from float to a 32 bit-vector should be equal to the 32 bit-vector of 2<sup>31</sup>. The following is satisfiable

```lisp
(set-option :produce-models true)
(set-logic QF_FPBV)

(assert
  (= ((_ fp.to_sbv 32) roundTowardZero (fp #b0 #b10000011110 #x0000000000000))
     #x80000000))
(check-sat)
```
The negated formula should be unsatisfiable, but it is satisfiable

```lisp
(set-option :produce-models true)
(set-logic QF_FPBV)

(assert
  (not
    (= ((_ fp.to_sbv 32) roundTowardZero (fp #b0 #b10000011110 #x0000000000000))
       #x80000000)))
(check-sat)
```

Tested with the releases
- [z3-4.6.0-x64-ubuntu-16.04](https://github.com/Z3Prover/z3/releases/download/z3-4.6.0/z3-4.6.0-x64-ubuntu-16.04.zip)
- [z3-4.7.1-x64-ubuntu-16.04](https://github.com/Z3Prover/z3/releases/download/z3-4.7.1/z3-4.7.1-x64-ubuntu-16.04.zip)
- [z3-4.8.4.d6df51951f4c-x64-ubuntu-16.04](https://github.com/Z3Prover/z3/releases/download/z3-4.8.4/z3-4.8.4.d6df51951f4c-x64-ubuntu-16.04.zip)

**Comment by LeventErkok** [comment]
@maiermic 

I think z3 is doing the right thing here. Note that you're using the function `(_ fp.to_sbv 32)`, which tries to convert the float to a *signed* 32-bit value. The range of signed 32-bit values is `-2^31` to `2^31-1`. So, your number is out-of-range. And if you look at the SMTLib floating-point spec, it clearly states that these functions are underspecified when the values converted are out-of-bounds for the target type; so in a sense z3 is free to pick whatever value it wants. See here: http://smtlib.cs.uiowa.edu/theories-FloatingPoint.shtml

If you instead use `(_ fp.to_ubv 32)`, you get:

```
$ cat a.smt2
(set-option :produce-models true)
(set-logic QF_FPBV)

(assert
  (= ((_ fp.to_ubv 32) roundTowardZero (fp #b0 #b10000011110 #x0000000000000))
     #x80000000))
(check-sat)
$ z3 a.smt2
sat
```

And for the negated assertion:

```
$ cat a.smt2
(set-option :produce-models true)
(set-logic QF_FPBV)

(assert (not
  (= ((_ fp.to_ubv 32) roundTowardZero (fp #b0 #b10000011110 #x0000000000000))
     #x80000000)))
(check-sat)
$ z3 a.smt2
unsat
```
which behaves just as you would expect.

**Comment by maiermic** [comment]
Thanks, you are totally right :+1:
