### ISSUE TITLE
Incomplete model for strings?

### ISSUE THREAD

**Issue by alebugariu** [Z3Prover/z3#2115]
I have some formulas for which both string solvers (seq and z3str3) correctly return sat. But when I ask for the model, only the string variables are assigned, the integer ones have no value. For the example below, both solvers assign values to all the strings, but not to tmp_int1. Does this mean that tmp_int1 can have any value? Or some default value (e.g., 0)?
````
(set-info :status sat)
(declare-fun tmp_str2 () String)
(declare-fun tmp_str3 () String)
(declare-fun tmp_int1 () Int)
(declare-fun tmp_str0 () String)
(declare-fun s () String)
(declare-fun suffix () String)
(assert
 (let ((?x44 (str.len tmp_str2)))
 (let ((?x17 (str.to.int tmp_str3)))
 (let ((?x2320 (str.at tmp_str0 tmp_int1)))
 (= s (str.substr ?x2320 ?x17 ?x44))))))
(assert
 (let ((?x146 (str.len s)))
 (= ?x146 0)))
(assert
 (let ((?x44 (str.len tmp_str2)))
 (= ?x44 0)))
(assert
 (let ((?x6 (str.len tmp_str0)))
 (= ?x6 5)))
(assert
 (let ((?x152 (str.len tmp_str3)))
 (= ?x152 1)))
(assert
 (let ((?x407 (str.len suffix)))
 (= ?x407 18)))
(assert
 (let (($x234 (str.suffixof suffix s)))
 (not $x234)))
(check-sat)
(get-model)
````
Thank you very much.

**Comment by LeventErkok** [comment]
@alebugariu By default `get-model` only returns "what matters." You can use an explicit call to `get-value` to grab values of all variables you care about. Add the following to your script after `check-sat`:

```
(get-value (tmp_str2 tmp_str3 tmp_int1 tmp_str0 s suffix))
```

and z3 prints:

```
((tmp_str2 "")
 (tmp_str3 "\x00")
 (tmp_int1 0)
 (tmp_str0 "\x00\x00\x00\x00\x00")
 (s "")
 (suffix "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"))
```

This suggests value of `tmp_int1` really doesn't matter for this benchmark. (Though I did not explicitly check to make sure that is indeed the case!)

**Comment by alebugariu** [comment]
Ok, thank you very much for the explanations.
