### ISSUE TITLE
Z3 failed with error C2668 when build with permissive- + MSVC on windows

### ISSUE THREAD

**Issue by QuellaZhang** [Z3Prover/z3#2117]
Build Z3 with permissive- by msvc failed with error C2668, this issue can be reproduced from master revision 8566d88. Could you please help take a look at this?

**Repro:**

1. open VS2017 x86 Native tools command tool
2. git clone https://github.com/Z3Prover/z3 D:\Z3\src
3. cd D:\Z3
4. set CL=/permissive-
5. mkdir build_x86 && pushd build_x86
6. cmake -G "Visual Studio 15 2017" -DCMAKE_SYSTEM_VERSION=10.0.17134.0 ..\src
7. msbuild build_x86\Z3.sln /p:Configuration=Release;Platform=Win32 /t:Rebuild /m /p:BuildInParallel=true

**Failures:**
D:\Z3\src\src\test\matcher.cpp(87): error C2668: 'ast_manager::mk_app': ambiguous call to overloaded function
D:\Z3\src\src\ast\ast.h(1844): note: could be 'app *ast_manager::mk_app(func_decl *,expr *)'
D:\Z3\src\src\ast\ast.h(1756): note: or       'app *ast_manager::mk_app(family_id,decl_kind,unsigned int,const parameter *,unsigned int,expr *const *,sort *)'
D:\Z3\src\src\test\matcher.cpp(87): note: while trying to match the argument list '(func_decl_ref, expr_ref)'

**Our workaround:**
diff --git a/src/test/matcher.cpp b/src/test/matcher.cpp
index cd220a9..68f37cc 100644
--- a/src/test/matcher.cpp
+++ b/src/test/matcher.cpp
@@ -84,7 +84,7 @@ void tst1() {
     app_ref b(           m.mk_const(symbol("b"), s), m);
     expr_ref x(          m.mk_var(0, s), m);
     expr_ref y(          m.mk_var(1, s), m);
-    app_ref gx(          m.mk_app(g, x), m);
+    app_ref gx(          m.mk_app(g.get(), x.get()), m);
     app_ref fgx_x(       m.mk_app(f, gx.get(), x.get()), m);
     app_ref ha(          m.mk_app(h, a.get()), m);
     app_ref gha(         m.mk_app(g, ha.get()), m);

**Comment by NikolajBjorner** [comment]
I believe this is now fixed
