### ISSUE TITLE
Assertion Violation Involving Incremental Bitvector Division by Zero

### ISSUE THREAD

**Issue by kyledewey** [Z3Prover/z3#212]
I'm on `unstable` at commit 09980a496c7b1fbd74c241589011d0cf522dd03c, with a debug + tracing build.  If I run Z3 with the following command line:

```console
z3 rewriter.hi_div0=false old_simplify.bv.hi_div0=false --smt2 test.smt2
```

...where `test.smt2` has the following contents:

```
(set-option :produce-models true)
(set-logic QF_BV)
(declare-fun x0 () (_ BitVec 1))
(check-sat)
(assert (= #b1 (bvudiv #b0 x0)))
(assert (= #b0 (bvudiv x0 #b0)))
(check-sat)
(get-model)
```

...then Z3 crashes on the `get-model` command with the following output:

```
sat
sat
ASSERTION VIOLATION
File: ../src/sat/sat_solver/inc_sat_solver.cpp
Line: 412
m.is_true(tmp)
(C)ontinue, (A)bort, (S)top, (T)hrow exception, Invoke (G)DB
```

The second call to `check-sat` should result in `unsat`, as any alternative would violate the fact that `bvudiv` is a pure function.  As such, I'm assuming that an invalid model is getting generated internally, and then the fact that it's invalid is later discovered in the `get-model` usage.

While the first use of `check-sat` is basically a no-op in this case, without it Z3 correctly returns that the rest is `unsat`.

**Comment by NikolajBjorner** [comment]
I recently enabled an engine for QF_BV that uses the more scalable sat solver, but it requires the default semantics for the bit-vector operations. It now detects the global configuration flag that turns off the default semantics.
