### ISSUE TITLE
Unable to use match binder

### ISSUE THREAD

**Issue by vrama628** [Z3Prover/z3#2120]
I'm trying to use the match binder in inputs to Z3 but it's not working. For example, when I try the following program:
```
(declare-datatype Dyn ((a) (b)))
(define-fun foo ((x Dyn)) Int (
  match x (
    (a 1)
    (b 2)
  )
))
(assert (= (foo a) 1))
(check-sat)
```
Z3 gives me the error "line 4 column 7: variable symbol expected" even though this syntax is correct according to page 27 of the [SMT-LIB Standard](http://smtlib.cs.uiowa.edu/papers/smt-lib-reference-v2.6-r2017-07-18.pdf).

**Comment by avery-laird** [comment]
Is it possible to use the match syntax in any of the APIs? eg python or c++

**Comment by NikolajBjorner** [comment]
There isn't. Match syntax is compiled into if-then-else expressions at the level of the parser.
