### ISSUE TITLE
Sets: Ext function in the Python API: Purpose and implementation issue

### ISSUE THREAD

**Issue by LeventErkok** [Z3Prover/z3#2123]
I'm looking into how sets are implemented, and having issues with the `Ext` function in the Python api:

https://github.com/Z3Prover/z3/blob/master/src/api/python/z3/z3.py#L4492-L4497

It's definition is:

```python
def Ext(a, b):
    """Return extensionality index for arrays.
    """
    if __debug__:
        _z3_assert(is_array(a) and is_array(b))
    return _to_expr_ref(Z3_mk_array_ext(ctx.ref(), a.as_ast(), b.as_ast()));
```

My first question is exactly what the purpose of this function is and how end-users are supposed to utilize it?

Furthermore, If I try to use it from my script like this:

```python
from z3 import *

a = Const('a', SetSort(IntSort()))
s = Solver()
print (Ext(a, a)).sexpr()
```

I get:

```
Traceback (most recent call last):
  File "b.py", line 5, in <module>
    print (Ext(a, a)).sexpr()
  File "/usr/local/lib/python2.7/site-packages/z3/z3.py", line 4496, in Ext
    _z3_assert(is_array(a) and is_array(b))
TypeError: _z3_assert() takes exactly 2 arguments (1 given)
```

That seems an easy fix, just add a string to the `_z3_assert` call. But even when I do that, I get:

```
Traceback (most recent call last):
  File "a.py", line 42, in <module>
    print (Ext(a, a)).sexpr()
  File "/usr/local/lib/python2.7/site-packages/z3/z3.py", line 4498, in Ext
    return _to_expr_ref(Z3_mk_array_ext(ctx.ref(), a.as_ast(), b.as_ast()));
TypeError: _to_expr_ref() takes exactly 2 arguments (1 given)
```

So looks like that function needs some fixing; but my question is more about exactly what it's role is: How are end-users supposed to use this function? Or is it completely internal. I couldn't locate any further info on this.

**Comment by NikolajBjorner** [comment]
It is essentially internal. It is exposed so that users can rebuild terms that Z3 introduces.  
I should fix these API calls too, but I don't think you want/need to use it.

Ext is a Skolem function. It is used to enforce the axiom:

         a = b or a[Ext(a,b)] != b[Ext(a,b)]

Thus, two arrays are equal or there is some index where they differ. The index is identified using Ext.
Quantifier solving and Interpolation (past, present/SPACER and future) features may produce this term so it cannot be kept hidden.

**Comment by LeventErkok** [comment]
Thank you!
