### ISSUE TITLE
Self-referential model for uninterpreted function

### ISSUE THREAD

**Issue by LeventErkok** [Z3Prover/z3#2127]
For this benchmark:
```
(declare-fun q (Int) Int)
(check-sat)
(get-value (q))
```

z3 says:
```
sat
((q (_ as-array q)))
```

`q` is self-referential here; something that shouldn't really happen. (Though perfectly reasonable!)

**Comment by NikolajBjorner** [comment]
So model completion in get-value is not applied to functions. It is applied to constants (if I declare x to an Int, then x is evaluated to 0).

**Comment by LeventErkok** [comment]
I see. This indeed comes up in practical scenarios for me, but it is not hard for me to work around. I suspect it wouldn't be hard for you to work around either, by generating an arbitrary value of the return type, but perhaps there's other complexity involved. I'm more concerned about "gotcha" scenarios where upstream tools don't anticipate this possibility.

I'll implement the workaround for myself; and please feel free to close this ticket if there isn't enough ROI for you to do so.

Thanks!
