### ISSUE TITLE
Some QF_NIA script where Z3 does not terminate

### ISSUE THREAD

**Issue by Heizmann** [Z3Prover/z3#213]
Z3 ef7915858bca5e759ee0a34df2ae976e7e507bef does not terminate on the following script
http://www.informatik.uni-freiburg.de/~heizmann/UltimateAutomizer_NutzTransformation02.c.smt2

The script does not seem too difficult, other solvers provide a result within seconds.

At a first glance, it seems that this script contains only linear arithmetic. However, according to SMT-LIB it does not, e.g., because of the following term.
    (mod (mod x 4294967296) (mod 13 4294967296))

**Comment by NikolajBjorner** [comment]
It is still linear because the second modulus simplifies to a constant. Z3 gets stuck in a sequence of cuts and branches. When run with smt.random_seed=5 it converges on one version of your file, so there is some amount of instability of whether z3 finds the right cuts.

**Comment by Heizmann** [comment]
> It is still linear 

But if I change the logic from AUFNIRA to AUFLIRA, I get the following error message.

    (error "line 804 column 410: logic does not support nonlinear arithmetic")

**Comment by NikolajBjorner** [comment]
.... it is still linear after pre-processing. The SMT-LIB2 format does not consider pre-processing.

**Comment by wintersteiger** [comment]
Is this issue resolved and can we close it? It looks to me like a performance problem for which there is no general fix, sometimes the solver will be lucky, and sometimes it won't?

**Comment by NikolajBjorner** [comment]
I would leave the issue open because it seems to point to a performance bug relative to what should be easy.

**Comment by levnach** [comment]
Works both in "master" and "debug" branches.
