### ISSUE TITLE
z3-opt for bit-vector with box parameter

### ISSUE THREAD

**Issue by rainoftime** [Z3Prover/z3#2137]
z3 reduces bit-vector optimization to weighted MaxSAT solving.
Suppose the priotity is "box". For the following problem, will z3 solve two MaxSAT problems in sequence? 
From `z3\src\opt\opt_context.cpp`, I observe that in function `context::execute_box()`,  each objective is solved in an iteration of a loop.  What statuses will be shared when optimizing different objectives?  Thank you!
~~~~
context c; optimize opt(c);
expr x = c.bv_const("x", 8);
expr y = c.bv_const("y", 8);
expr fml = uge(x, 2) && ule(y, 26);
opt.maximize(x);  opt.maximize(y);
~~~~

**Comment by NikolajBjorner** [comment]
There is no tuning for box objectives when it comes to maxsat objectives (Pseudo-Boolean objectives), not even partial bounds from feasible solutions.
Seems like something one could ponder about: suppose you did a core-based solver, then a core using both x and y variables doesn't necessarily translate to a core of either. 
Note that for bit-vector objectives I now use a specialized optimization engine that walks each bit in order of magnitude and try to satisfy it.

**Comment by rainoftime** [comment]
Do you mean that there is a new bit-level, binary-search style engine? 
For instance, `x` is a bit vector of length 4 which is translated to 4 Boolean variables `b3 b2 b1 b0`.
First, we test if the translated SAT formula can be satisfiable if `b3` is true, then we test `b2` ...

**Comment by NikolajBjorner** [comment]
conceptually, https://github.com/Z3Prover/z3/blob/master/src/opt/maxlex.cpp
