### ISSUE TITLE
Error "undefined symbol: Z3_solver_from_string" on calling solver.from_string()

### ISSUE THREAD

**Issue by aashish12345678910** [Z3Prover/z3#2138]
In the following code, on invoking from_string() I am getting the error "undefined symbol: Z3_solver_from_string". But this should work as concluded in Issue #1928.

z3::context c;
z3::solver s(c);

const char* pred = "(declare-const x Int)(assert (> x 10))";
s.from_string(pred);
cout<<s.check();

Any help would be appreciated

**Comment by NikolajBjorner** [comment]
Perhaps check if the version of libz3.dll on your path is up-to-date.

**Comment by aashish12345678910** [comment]
Yes, the libz3.so file I have is corresponding to the latest version of Z3 (4.8.4).

**Comment by NikolajBjorner** [comment]
sometimes users have old versions of libz3.so in different locations and these get loaded instead of the newest. What version does it produce using Z3_get_version?
