### ISSUE TITLE
Are symbolic rotate amounts supported?

### ISSUE THREAD

**Issue by LeventErkok** [Z3Prover/z3#2142]
SMTLib does not allow symbolic rotation amounts. But I'm noticing that z3 does seem to support some variants of it:

```
(set-option :produce-models true)
(set-logic QF_BV)

(define-fun i () (_ BitVec 8) #x04)
(declare-fun vi () (_ BitVec 8))
(assert (= i vi))

(define-fun x () (_ BitVec 8) #x42)
(declare-fun vx () (_ BitVec 8))
(assert (= x vx))

(define-fun r () (_ BitVec 8) ((_ rotate_left vi) vx))

(check-sat)
(get-value (r))
```

z3 accepts this, but responds with an incorrect result:

```
sat
((r #x42))
```

The correct answer should be `#x24`, not `#42`.

I've also noticed that z3 doesn't always like symbolic rotate amounts. For this benchmark:

```
(set-option :produce-models true)
(set-logic QF_BV)

(define-fun vi () (_ BitVec 8) #x04)
(define-fun vx () (_ BitVec 8) #x42)

(define-fun r () (_ BitVec 8) ((_ rotate_left vi) vx))
```

z3 says:

```
(error "line 7 column 46: invalid function declaration reference, named expressions (aka macros) cannot be referenced vi")
```

I'm curious if this was intentional and there simply are bugs with it; or, perhaps you never intended to support symbolic rotate amounts in the first place and some benchmarks go through somehow.

**Comment by NikolajBjorner** [comment]
sorry, symbolic parameters are not supported.
You will need a big mux: e.g., 

    if shift = 0 then ((_ shift_left 0) x) else 
    if shift = 1 then ((_ shift_left 1) x) else ..
    …
