### ISSUE TITLE
Assertion Violation Involving Floating Point Multiplication

### ISSUE THREAD

**Issue by kyledewey** [Z3Prover/z3#215]
On the `unstable` branch at commit 44105b7aeb8ec6e85dfba23321eaa6838695d1f3, if I run Z3 with no command-line options on the following input:

```
(set-logic QF_FP)
(simplify (fp.mul RNE (fp #b1 #b110 #b1) (fp #b0 #b100 #b0)))
```

...then Z3 crashes with the following output:

```
ASSERTION VIOLATION
File: ../src/util/mpf.cpp
Line: 1736
TINY || (m_mpz_manager.ge(o.significand, p_sig))
```

**Comment by wintersteiger** [comment]
Single-bit significands and exponents are not supported (and they don't make sense in theory). I'll fix the error message, but that will mean that you'll just get a different message. The minimum safe size is 3 significand and 3 exponent bits.

**Comment by kyledewey** [comment]
To clarify, is the 3 bit restriction part of the standard, or specific to Z3?  From the [standard for the theory of floating point](http://smtlib.cs.uiowa.edu/theories-FloatingPoint.shtml), it states:

```
:values "For all m,n > 1, the values of sort (_ FloatingPoint m n) are 
  - (_ +oo m n)  
  - (_ -oo m n)
  - (_ NaN m n)
  - all terms of the form (fp c1 c2 c3) where
    - c1 is the binary #b0 or #b1
    - c2 is a binary of size m other than #b1...1 (all 1s)
    - c3 is a binary of size n-1
```

Based on my understanding, this means that `(fp #b0 #b100 #b0)` should be a legal value, where `m` is 3 and `n` is `2`.  Is this incorrect?

**Comment by wintersteiger** [comment]
Yes, that is correct, this is a Z3 limitation, mainly because it's untested and it's not been needed so far. Most operators would still work, but there may be a few cases for which input normalization is impossible, as far as I remember.

**Comment by wintersteiger** [comment]
This is now fixed, so I'm closing the issue. The minimum numbers of bits it won't complain about is now ebits=2, sbits=2, but I may have missed a couple corner cases for which some operators could produce wrong results. If that is so, please open a new issue.
