### ISSUE TITLE
Unreduced boolean value in model

### ISSUE THREAD

**Issue by LeventErkok** [Z3Prover/z3#2151]
For this benchmark:

```
(set-logic ALL)
(declare-fun s0 () (Array Int Bool))
(declare-fun s1 () (Array Int Bool))
(declare-fun s2 () (Array Int Bool))
(define-fun s3 () (Array Int Bool) (union s1 s2))

(define-fun s4 () Bool (or (subset s0 s1) (not (subset s0 s3))))
(assert (not s4))

(check-sat)
(get-value (s4))
```

z3 says:

```
sat
((s4 (let ((a!1 (lambda ((x!1 Int)) (= x!1 0)))
      (a!2 ((_ map (not (Bool) Bool)) (lambda ((x!1 Int)) (not (= x!1 0))))))
(let ((a!3 (= ((_ map (and (Bool Bool) Bool))
                a!1
                ((_ map (not (Bool) Bool))
                  ((_ map (or (Bool Bool) Bool))
                    (_ as-array k!1)
                    (_ as-array k!5))))
              ((as const (Array Int Bool)) false))))
  (or (= ((_ map (and (Bool Bool) Bool)) a!1 a!2)
         ((as const (Array Int Bool)) false))
      (not a!3))))))
```

But `s4` is a simple boolean, I was expecting to see `true` or `false`. Looks like it doesn't get reduced in the final model.

I noticed that if I comment out:

```
; (assert (not s4))
```

then I get:

```
sat
((s4 true))
```

So, looks like maybe there's a missing case in the model evaluator with arrays?

**Comment by NikolajBjorner** [comment]
sat
((s4 false)
 ((subset s0 s1) (= (lambda ((x!1 Int)) (= x!1 0)) ((as const (Array Int Bool)) false))))

**Comment by NikolajBjorner** [comment]
this is about as much rewriting I would support.
s4 is false, (subset s0 s1) rewrites to (forall ((x Int)) (not (= x 0))), which is equivalent to false, but the rewriter is not going to produce canonical values (and isn't designed to be).

**Comment by LeventErkok** [comment]
Thanks Nikolaj! The output is much better behaved now; much appreciated.
