### ISSUE TITLE
Empty answer on fixpoint engine (regression)

### ISSUE THREAD

**Issue by algobardo** [Z3Prover/z3#2155]
HI, I'm having trouble getting answers to queries.

The following example from the tutorial returns ``sat and``
```
(declare-rel mc (Int Int))
(declare-var n Int)
(declare-var m Int)
(declare-var p Int)

(rule (=> (> m 100) (mc m (- m 10))))
(rule (=> (and (<= m 100) (mc (+ m 11) p) (mc p n)) (mc m n)))

(declare-rel q3 (Int Int))
(rule (=> (and (mc m n) (< n 92)) (q3 m n)))

(query q3 :print-answer true)
```

If I replace the query by the following
```
(query (exists ((x Int) (y Int)) (q3 x y)) :print-answer true)
```
then the following is returned
```
(error "line 12 column 17: unknown sort 'x'")
```

**Comment by algobardo** [comment]
@levnach have you tried to reproduce?

**Comment by NikolajBjorner** [comment]
@levnach is not the right contact. @agurfinkel is more appropriate.
The SPACER engine now handles the fixedpoint queries. The format of the "answer" trace depends on the engine. In this case it produces an empty trace.

Regarding the error you report: The argument to "query" should be the name of a predicate, not a formula.

**Comment by algobardo** [comment]
@agurfinkel Shouldn't a substitution from bound variables to expressions be returned, in place of the empty answer?
