### ISSUE TITLE
CDCL SAT engine without simplifications

### ISSUE THREAD

**Issue by rainoftime** [Z3Prover/z3#2156]
Boolean simplifications (pre-processing and in-processing) can considerably improve the performance of CDCL solvers.  However,  their additional runtime may exceed the runtime saved. 

We observe that for some easy QF_BV queries, disabling Boolean simplifications may accelerate the solving time dramatically.  Perhaps an important reason is that the theory-level simplifications have already greatly simplified the constraints.  It is hard to provide theoretical guarantees, though. 

Is it possible to devise some "simple" metrics for automatically turning on/off Boolean simplifications?   Approaches like Satzilla seem too complex.

**Comment by NikolajBjorner** [comment]
In fact inprocessing isn't well tuned. It needs to back off more aggressively. It is something I am trying to improve. Besides outright performance bugs that were reported and fixed some months ago, the current bottleneck appears to be asymmetric branch simplification, which is triggered quite a bit.

**Comment by rainoftime** [comment]
That could be an important reason inside Z3. Maybe I can first generate SAT instances with Z3, and feed them to other SAT solvers. Then we are able to examine the effects of Boolean simplifications in those solvers.
