### ISSUE TITLE
bug in arith_solver=6 optimize

### ISSUE THREAD

**Issue by NikolajBjorner** [Z3Prover/z3#2157]
This one returns unbounded.
@levnach It seems to be a bug in arith_solver=6. It is bounded if I revert to the old solver.

(declare-fun z5 () Int)
(declare-fun z4 () Int)
(declare-fun z6 () Int)
(declare-fun f (Int Int) Int)
(declare-fun z2 () Int)
(declare-fun x2 () Int)
(declare-fun x1 () Int)
(declare-fun z1 () Int)
;(assert (= z6 (+ z4 z5)))
;(assert (= z5 (f x2 z2)))
;(assert (= z4 (f x1 z2)))
;(assert (= (f z1 z2) (+ (f x1 z2) (f x2 z2))))
(assert (= z1 (+ x1 x2)))
(assert (< x1 z4))
(assert (= z4 (f x1 z2)))
(assert (< (f x1 z2) z1))
(assert (< z1 z6))
(assert (= z6 (f z1 z2)))
(assert (< (f z1 z2) z2))
(assert (< z2 z5))
(assert (= z5 (f x2 z2)))
(assert (< (f x2 z2) x2))
(minimize (- x2 x1))
(check-sat)
(get-objectives)

**Comment by levnach** [comment]
@NikolajBjorner, how to revert to the old solver here?

**Comment by NikolajBjorner** [comment]
The old solver can be forced by changing the code in src/smt_setup.cpp:

    void setup::setup_lra_arith() {
        m_context.register_plugin(alloc(smt::theory_lra, m_manager, m_params));
    }

to

    void setup::setup_lra_arith() {
        m_context.register_plugin(alloc(smt::theory_mi_arith, m_manager, m_params));
    }

Perhaps there is a more flexible way with configuration but I currently don't see one.

**Comment by levnach** [comment]
I tried replacing the applications of function f, there are three of those, by new integers a, b, c as below.
(declare-fun z5 () Int)
(declare-fun z4 () Int)
(declare-fun z6 () Int)
(declare-fun z2 () Int)
(declare-fun x2 () Int)
(declare-fun x1 () Int)
(declare-fun z1 () Int)
(declare-fun a () Int)
(declare-fun b () Int)
(declare-fun c () Int)
(assert (= z1 (+ x1 x2)))
(assert (< x1 z4))
(assert (= z4 b))
(assert (< b z1))
(assert (< z1 z6))
(assert (= z6 c))
(assert (< c z2))
(assert (< z2 z5))
(assert (= z5 a))
(assert (< a x2))
(check-sat)
(minimize (- x2 x1))
(check-sat)
(get-objectives)


Then the answer was correct.
 (objectives
 ((- x2 x1) 6)
)
It seems the  bug is lurking it the code handling non interpreted functions.

**Comment by NikolajBjorner** [comment]
fixed
