### ISSUE TITLE
Z3 fails to terminate on a simple expression (possibly regression).

### ISSUE THREAD

**Issue by vrthra** [Z3Prover/z3#2161]
I am trying to evaluate this expression on 4.8.4 release
```
(declare-const arg_1 Int)
(assert
  (and
     (not (= 0 (mod arg_1 10)))
     (= 0 (mod (+ 1 arg_1) 10))))
(check-sat)
```

I get the following repeating messages when running, and does not terminate.

```
$ z3 -v:3 expr.z3
(smt.searching)
(smt.simplifying-clause-set :num-deleted-clauses 1)
final-check OPTIMAL
final-check OPTIMAL
... does not terminate...
```
However, I verified that it does terminate on an earlier version which is available online.
https://rise4fun.com/Z3/AsMn

**Comment by levnach** [comment]
I have not found the reason for the problem. Not sure it is relevant but I noticed that starting from the second call to "lar_solver::find_feasible_solution()" the solution has not integral values, however  "int_solver::check()" is not called.
