### ISSUE TITLE
z3 does not solve a string expression (possibly regression)

### ISSUE THREAD

**Issue by vrthra** [Z3Prover/z3#2162]
Using  `z3 4.8.0`  this expression returns `unknown`

```
(declare-const my_str String)
(assert (>= (str.indexof my_str " a " 0) 0))
(check-sat)
```
However, removing the space from front or back of `" a "` makes it `sat`. It also works in an earlier version of z3 https://rise4fun.com/Z3/nhtF4

**Comment by NikolajBjorner** [comment]
works with 4.8.4
