### ISSUE TITLE
Interpolation Problem Real-Int

### ISSUE THREAD

**Issue by Heizmann** [Z3Prover/z3#217]
Executing Z3 ef7915858bca5e759ee0a34df2ae976e7e507bef with the command

    z3 SMTLIB2_COMPLIANT\=true -t\:12000
on [this SMT script](http://www.informatik.uni-freiburg.de/~heizmann/20150912-Z3InterpolationProblem-avg.c.smt2.zip), I obtain the following error message.

    (error "line 74616 column 3676: Sort mismatch at argument #2 for function (declare-fun * (Real Real) Real) supplied sort is Int")

However, there is no *Real* in the script at all.

**Comment by NikolajBjorner** [comment]
can you update the link?

**Comment by Heizmann** [comment]
I just did. (Sorry for the dead link)
Furthermore, I updated the arguments of my Z3 call. (Problem can be reproduced without smt.mbqi=false)

**Comment by Heizmann** [comment]
It seems that the problem only occurs if I use the argument ``SMTLIB2_COMPLIANT\=true``.

**Comment by NikolajBjorner** [comment]
got it

**Comment by NikolajBjorner** [comment]
yes, it is the issue: the interpolants created mixed integer/real constraints. This is not expressible in SMT-LIB2's AUFLIRA theory. Is the compliant configuration required for your tool?

**Comment by NikolajBjorner** [comment]
fixed

**Comment by Heizmann** [comment]
> Is the compliant configuration required for your tool?
Once, we required it. I cannot remember the reason any more. In the last hours I run a few benchmarks without the compliant configuration and I have not noticed any problems.

**Comment by NikolajBjorner** [comment]
Right, but with the new fix you can use both compliant and non-compliant mode. Interpolation overwrites the portion that disables coercions in compliant mode.
