### ISSUE TITLE
How to decrease the complexity of the formula when the formula contains forall and existence

### ISSUE THREAD

**Issue by northcity0406** [Z3Prover/z3#2172]
Those days, I am doing a project with z3's Python API. However, there are some problems, when a formula contains Forall and Existence, the complexity is so high that it takes a long time to work it out. How can I decrease the complexity of this formula?

**Comment by NikolajBjorner** [comment]
Not sure what to say that would be informative here. Obviously, if the formula is unsatisfiable, you can replace the formula by false.
