### ISSUE TITLE
Answer stability?

### ISSUE THREAD

**Issue by pietrobraione** [Z3Prover/z3#2175]
Hello; I have encountered a situation where running Z3 twice on the same problem produces two different answers: On its first run it answers "unknown" to the final check-sat, on its second run and (apparently) all subsequent ones it answers "unsat". I would therefore ask if it is expected that Z3 might behave in a not perfectly deterministic way, e.g., because it "improves" its behavior with time by somehow learning from its previous runs. Unfortunately I am not able to submit a reproducible test at the moment. Also, I am not yet sure that this behavior holds on version (I am working with a symbolic executor that integrates Z3 4.7.1 and it would need some work to integrate 4.8.4). If you confirm to me that this might be an unexpected behavior, and that nothing similar was fixed from 4.7.1 to 4.8.4, I will further investigate the issue and report my results here.

**Comment by NikolajBjorner** [comment]
It isn't quite unexpected, but always a source of issues:

1. If you issue the same query multiple times under push/pop internal state changes and this can have an effect on search. "unknown" is a symptom of theories with incomplete support (non-linear integers, strings).
2. Some tactics are run for a short duration to attempt solving goals using non-default strategies. These may succeed before their timeout. In other runs they may time out before they get a chance to succeed. For example, non-linear integer arithmetic is converted to finite domain SAT for finding small integer assignments.
