### ISSUE TITLE
version 4.8.4 build shared library if you also ask it disable omp

### ISSUE THREAD

**Issue by linux40** [Z3Prover/z3#2177]
Commands:
```
./configure --staticlib --noomp
cd build
make -j 16
```

**Comment by NikolajBjorner** [comment]
yes, and?

**Comment by linux40** [comment]
But i specify `--staticlib`. If i run `./configure --staticlib`, the reasult of building is the static library of z3.

**Comment by wintersteiger** [comment]
If I remember correctly, `--staticlib` _adds_ the static library (`.a`) to the build, it does not disable the shared library.

**Comment by linux40** [comment]
Sorry for my mistake and my poor presentation. I want to say there is no static library when i specify `--staticlib` and `--noomp` together, but it is my mistake.
