### ISSUE TITLE
Problem implementing `Select` on `Lambda` via substitution

### ISSUE THREAD

**Issue by Pet3ris** [Z3Prover/z3#2179]
I'm trying to make a substitution over the body of a Lambda expression, but it doesn't seem to substitute at all.

The ultimate goal was to run a `Select` expression over `Lambda` (which is not directly allowed unless you create an intermediate variable of `Array` sort and assign the lambda to that).

This is what I'm trying in Python:

```python
def test_select_over_lambdas_can_be_implemented():
    solver = Solver()
    read = BitVec('read', 8)
    fake_array = Lambda([read], read)
    print(fake_array)  # Lambda(read, read)
    print(fake_array.body())  # Var(0)
    new_select = substitute(
        fake_array.body(),
        [
            (Const("Var(0)", fake_array.var_sort(0)), BitVecVal(1, 8))
        ])
    print(new_select)  # Var(0) / substitution failed
    solver.add(new_select == 1)
    assert str(solver.check()) == "sat"  # Fails with answer "unknown"
```

I also tried to replace the `read` variable, and this didn't work either.

Any other recommended way to implement `Select` over `Lambda`?

**Comment by NikolajBjorner** [comment]
You want to use bound variables and not Const expressions:

     new_select = substitute(
         fake_array.body(),
         [
             (Var(0, read.sort()), BitVecVal(1, 8))
         ])

Not sure what your overall goal was with "implementing Select over Lambda". 
I guess it is clear that you can create lambda expressions and apply them to arguments using "Select".
