### ISSUE TITLE
Incorrect floating point model when `blast_mul=false`

### ISSUE THREAD

**Issue by grantpassmore** [Z3Prover/z3#2182]
I believe the floating point solver doesn't like being told not to blast multipliers :-).
A simple repro:

```
(declare-fun x () (_ FloatingPoint 11 53))

(assert (fp.eq (fp.add roundNearestTiesToEven
                       x
                       (fp #b0 #b01111111111 #x0000000000000))
               (fp #b0 #b10000000000 #x0000000000000)))

;; This gives a valid model
(check-sat)
(get-model)

;; This does, too
(check-sat-using qffp)
(get-model)

;; But this gives an invalid model
(check-sat-using (with qffp :blast_mul false))
(get-model)
```

**Comment by wintersteiger** [comment]
@NikolajBjorner: is the idea of `:blast_mul false` to bit-blast `bvmul` terms lazily in the SMT solver or does treat `bvmul` as uninterpreted?

**Comment by wintersteiger** [comment]
It seems to treat `bvmul` as uninterpreted with `blast_mul` off:

```
(declare-fun x () (_ BitVec 8))
(declare-fun y () (_ BitVec 8))
(declare-fun r () (_ BitVec 8))

(assert (= r (bvmul x y)))

(assert (= x #x03))
(assert (= y #x07))

(assert (not (= r #x15)))
(check-sat-using (then bit-blast sat)) ;; unsat

(assert (not (= r #x00)))
;; add more (not (= ... here
(check-sat-using (with (then simplify bit-blast smt) :blast_mul false))
(get-model)
```

@NikolajBjorner is that intended and should we fix the parameter description, or is this unintended?

**Comment by NikolajBjorner** [comment]
theory_bv calls the internalizer for bvmul, so it should correspond to delaying bit-blasting until the smt core is invoked.

**Comment by wintersteiger** [comment]
That's what I thought, but it's apparently not what's happening. I'll have to do some digging to figure out why.

**Comment by wintersteiger** [comment]
So, on my BV-only problem, from what I can see in the debugger, the BV theory is enabled, those `bvmul` terms do exist, and they are (presumably correctly) internalized by `internalize_assertions` in `setup_and_check`. Yet, it behaves like they are uninterpreted. @NikolajBjorner any ideas what could be going wrong here?

**Comment by NikolajBjorner** [comment]
The possible fix takes care of the reported issue.
