### ISSUE TITLE
z3_version.h header is generated differently depending on build system

### ISSUE THREAD

**Issue by ddcc** [Z3Prover/z3#2184]
LLVM is currently implementing a SMT API based off of Z3, and as part of this we need to identify the version of the local z3 install, if it's present. Unfortunately, it seems that the `Z3_FULL_VERSION` macro definition is [generated differently depending on whether the Python or CMake-based build system is being used](https://reviews.llvm.org/D54978#1431430), which breaks a proposed regex-based version parser. @delcypher has [identified the root cause for this, and has proposed a fix](https://reviews.llvm.org/D54978#1431935).

**Comment by NikolajBjorner** [comment]
If you pass in --githash options then the version "tweak" gets populated. It should be 0 by default as well, but it is almost for sure that I am not getting the real point yet.

**Comment by NikolajBjorner** [comment]
For some context: if the tools are downloading releases from GitHub, then indeed the latest release has a Git hash in the last argument. Another user raised the issue that this breaks with how previous releases didn't include the hash. So I will make sure this doesn't happen in the future.

For releases, the only significant digits are the first three. The last one is informative.
So version 4.8.4 is different from 4.8.3, but 4.8.4.0 build based on the release tag is the same as 4.8.4.dddd for the releases. Build tags change between releases.

**Comment by NikolajBjorner** [comment]
Could I perhaps get some additional input on what would be a workable solution for your build?

**Comment by ddcc** [comment]
I think the only other discrepancy we noticed is that the python-based build system does not include the git hash, but the CMake-based one does (if it detects a git repository): https://reviews.llvm.org/D54978#1433229

It looks like we plan to parse `Z3_MAJOR_VERSION`, `Z3_MINOR_VERSION`, and `Z3_BUILD_NUMBER` instead of `Z3_FULL_VERSION`, so as long as the format of those remains stable, everything should be fine.

**Comment by NikolajBjorner** [comment]
Good, yes just use Z3_MAJOR_VERSION, Z3_MINOR_VERSION, and Z3_BUILD_NUMBER. 
The python build system also has the ability to include git hashes, but then it depends which flags
you use when building. It makes it brittle for consumers of builds based on different flags.
I guess we can close?

**Comment by ddcc** [comment]
Sure, just wanted to point out the differences in default behavior between the two build systems, in case it wasn't intentional.
