### ISSUE TITLE
[z3py] Model decls does not contain all declared constants

### ISSUE THREAD

**Issue by HammySession** [Z3Prover/z3#2185]
**Spec1_ex.z3**
```
(declare-datatypes () (( permission deny permit   )))
(declare-datatypes () (( node HopThroughLaptop cr-rtr lnx-rtr-1 lnx-rtr-2 lnx-rtr-3 nullhost tp-rtr   )))
(declare-datatypes () (( acl_name cs-acl-01 null_acl tp-acl-01   )))
(declare-fun acl_action ( Int node acl_name (_ BitVec 32) Int Int (_ BitVec 32) Int Int Int )  permission)
(assert (! ( = (acl_action 1 tp-rtr tp-acl-01  #b00000000000000000000000000000000 0 0  #b00000101000001010000010100000001 0 22 0) deny) :named dummy_name73))
```

**Spec2_ex.z3**
```
(assert (! ( = (acl_action 2 tp-rtr tp-acl-01  #b00000000000000000000000000000000 0 0  #b00000110000001100000011000000001 0 22 0) permit) :named dummy_name77))
```
**Code**
```python
import z3
ctx = z3.Context()
s = z3.Solver(ctx=ctx)
abc = z3.parse_smt2_file('spec1_ex.z3',ctx=ctx)
s.add(abc)
s.check()
dce = z3.parse_smt2_file('spec2_ex.z3',decls={x.name():x for x in s.model().decls()}, ctx=ctx)
```
**Results**
```
Z3Exception: (error "line 1 column 30: unknown constant tp-rtr")
```

The model only contains [acl_action = [else -> deny]] . I'm guessing the model is simplified from the original smt2 file as the solver still contains the full model with constants by calling to_smt2.

**Comment by NikolajBjorner** [comment]
tp-rtr is an enumeration sort. It doesn't belong to the model and isn't included. 
I updated the parser to traverse sorts in function declarations that are passed.
Even that isn't enough for your script as is.

The following change does work with the update:


<code>

     def get_sorts(sorts, ts):
        for t in ts:
            sorts[t.sort().name()] = t.sort()
            for i in range(t.decl().arity()):
                s = t.decl().domain(i)
                sorts[s.name()] = s
            get_sorts(sorts, t.children())

    sorts = {}
    get_sorts(sorts, abc)
    s.add(abc)
    s.check()
    dce = z3.parse_smt2_file('spec2_ex.smt2',decls={x.name():x for x in s.model().decls()}, sorts=sorts, ctx=ctx)
</code>

**Comment by HammySession** [comment]
Thanks for the help worked like a charm, beats my string manipulation based workaround any day of the week.

**Comment by NikolajBjorner** [comment]
Just one note. The traversal code sample I gave doesn't scale to terms with shared subexpressions. 
There are some examples online of how to deal with this. They are of the form:

from z3 import *

    def subterms_rec(seen, t):
        if t in seen:
            return
        yield t
        seen |= { t }
        for ch in t.children():
            for s in subterms_rec(seen, ch):
                yield s

    def subterms(t):
         seen = set([])
         return subterms_rec(seen, t)

You get retrieve sorts from the subterms.
