### ISSUE TITLE
Additional call of check-sat makes UNSAT formula satisfiable.

### ISSUE THREAD

**Issue by larissa95** [Z3Prover/z3#2190]
I have a formula in z3. When I am calling check-sat on certain assumptions I get UNSAT. When I am adding another check-sat call before (of a literal which should be true anyways) both check-sats return SAT. I attached the example here: [example.txt](https://github.com/Z3Prover/z3/files/2980137/example.txt)
If you solve it with z3 you will get:
sat
sat
if you remove the first check-sat ((check-sat x_blablabla) in line 903)
you will get unsat.

**Comment by NikolajBjorner** [comment]
I guess you are using a release, such as 4.8.4. I had to fix several bugs in the pseudo-Boolean SMT-mode solver thanks to bug reports by Mark Dunlop. I seem unable to reproduce the reported behavior with the current master.

**Comment by larissa95** [comment]
You can also reproduce it with the online z3 solver:
https://rise4fun.com/Z3/
