### ISSUE TITLE
FP unsoundness involving roundToIntegral

### ISSUE THREAD

**Issue by ajreynol** [Z3Prover/z3#2191]
Z3 4.8.4 answers "unsat" on the following:
```
(set-logic QF_FP)
(declare-fun x () (_ FloatingPoint 3 5))
;(define-fun x () (_ FloatingPoint 3 5) (fp #b0 #b011 #b0100))
(declare-fun y () (_ FloatingPoint 3 5))
;(define-fun y () (_ FloatingPoint 3 5) (fp #b0 #b000 #b0101))
(assert (not (= (fp.roundToIntegral RNE x) x)))
(assert (= (fp.roundToIntegral RNE y) x))
(check-sat)
```
It answers "sat" after replacing the declare-fun with define-fun for x.

**Comment by wintersteiger** [comment]
Thanks for the report! The latest master produces `unsat` for both versions (which may or may not be correct), please upgrade. Still smells fishy to me though, I'll take another look.

**Comment by wintersteiger** [comment]
Actually, that should be fine, or am I missing some special case with infinities or similar?

**Comment by ajreynol** [comment]
I'm getting master z3 commit `5c67c9d907ca196c7efb1e757ced48707a1e9b35` answers "sat" with the define-fun x uncommented:
```
(set-logic QF_FP)
(define-fun x () (_ FloatingPoint 3 5) (fp #b0 #b011 #b0100))
(declare-fun y () (_ FloatingPoint 3 5))
(assert (not (= (fp.roundToIntegral RNE x) x)))
(assert (= (fp.roundToIntegral RNE y) x))
(check-sat)
```
My impression is that the input is sat although I'm not 100% sure. Regardless, if its sat with the define-fun, and unsat with the declare-fun, then something is wrong.
Let me know if you need more information about the z3 I'm using. I'm surprised you are getting unsat for both versions?

**Comment by NikolajBjorner** [comment]
I also get discrepancies. The following reports "sat".

(set-logic QF_FP)
;(declare-fun x () (_ FloatingPoint 3 5))
(define-fun x () (_ FloatingPoint 3 5) (fp #b0 #b011 #b0100))
(declare-fun y () (_ FloatingPoint 3 5))
;(define-fun y () (_ FloatingPoint 3 5) (fp #b0 #b000 #b0101))
(assert (not (= (fp.roundToIntegral RNE x) x)))
(assert (= (fp.roundToIntegral RNE y) x))
(check-sat)

Then this one, which is less constrained, 

(set-logic QF_FP)
(declare-fun x () (_ FloatingPoint 3 5))
;(define-fun x () (_ FloatingPoint 3 5) (fp #b0 #b011 #b0100))
(declare-fun y () (_ FloatingPoint 3 5))
;(define-fun y () (_ FloatingPoint 3 5) (fp #b0 #b000 #b0101))
(assert (not (= (fp.roundToIntegral RNE x) x)))
(assert (= (fp.roundToIntegral RNE y) x))
(check-sat)

reports unsat.

**Comment by wintersteiger** [comment]
Ah, got it! I uncommented both `define-funs` instead of just one of them.

**Comment by wintersteiger** [comment]
Thanks again for the report, this is now fixed!

The original problem is indeed unsatisfiable as rounding twice can't produce something that's different from rounding once.
