### ISSUE TITLE
How can I fix it?

### ISSUE THREAD

**Issue by Timingan** [Z3Prover/z3#2194]
mk_exception.MKException: 'C++ compiler was not found. Try to set the environment variable CXX with the C++ compiler available in your system.'

**Comment by NikolajBjorner** [comment]
The script that fails is

      https://github.com/Z3Prover/z3/blob/master/scripts/mk_util.py#L533

it traverses c++ compilers defined in environment variables or supplied directly as command-line arguments to the build script. See the README.md instructions on

      https://github.com/z3prover/z3

(scroll down a bit on the page) for examples of passing C++ compilers from the command-line.
Typically you expect to compile Z3 from a command-line that has the installed compilers on the PATH. 
For example, under Windows use a Visual Studio Development prompt or console where CLANG or GCC is installed. Similar for Linux/MacOS, ensure that one of the mainstream compilers is installed (sudo apt-get install clang, etc).
