### ISSUE TITLE
Remove unnecessary null pointer checks

### ISSUE THREAD

**Issue by elfring** [Z3Prover/z3#2195]
[An extra null pointer check is not needed in functions](https://isocpp.org/wiki/faq/freestore-mgmt#delete-handles-null "Do I need to check for null before delete p?") like the following.
- [lar_core_solver::pop](https://github.com/Z3Prover/z3/blob/3c7e7a7ffd73a31e560b58747aece09666c51949/src/util/lp/lar_core_solver.h#L230 "lar_core_solver::pop function")
- [lp_dual_simplex](https://github.com/Z3Prover/z3/blob/5e0da456a96731d9516efea67fa545feb689d728/src/util/lp/lp_dual_simplex.h#L36 "Destructor for lp_dual_simplex")
- [lp_solver](https://github.com/Z3Prover/z3/blob/eae4fd6afd29bddcfea4e7fa05a7a87788528883/src/util/lp/lp_solver_def.h#L88 "Destructor for lp_solver")

**Comment by NikolajBjorner** [comment]
Thanks, cleaner code is always good. Seems more like a code-review though.

**Comment by levnach** [comment]
Thanks, done!

**Comment by elfring** [comment]
A few update candidates were left over.
- [Destructor for mps_reader class](https://github.com/Z3Prover/z3/blob/5df29daa35bb6b116ab22fe888b228dea4d1e31e/src/util/lp/mps_reader.h#L751)
- [lar_core_solver::pop()](https://github.com/Z3Prover/z3/blob/6e5d0b759401d5f20da9d73ed8e59536bbcff765/src/util/lp/lar_core_solver.h#L230)

**Comment by levnach** [comment]
lar_core_solver::pop() is fine in my opinion. I fixed Destructor for mps_reader class

**Comment by NikolajBjorner** [comment]
It's basically about getting rid of noise

    ---> remove    if (m_r_solver.m_factorization != nullptr) {

            delete m_r_solver.m_factorization;

            m_r_solver.m_factorization = nullptr;

      --> remove        }

        m_r_x.resize(m_r_A.column_count());

        m_r_solver.m_costs.resize(m_r_A.column_count());

        m_r_solver.m_d.resize(m_r_A.column_count());

        if(!settings().use_tableau())

            pop_markowitz_counts(k);

        m_d_A.pop(k);

   ---> remove        if (m_d_solver.m_factorization != nullptr) {

            delete m_d_solver.m_factorization;

            m_d_solver.m_factorization = nullptr;

   ---> remove        }

**Comment by elfring** [comment]
I (and @NikolajBjorner) find two source code places still questionable in the implementation of the function “lar_core_solver::pop”.

**Comment by levnach** [comment]
Fixed everywhere.

**Comment by elfring** [comment]
Thanks for [another small source code improvement](https://github.com/Z3Prover/z3/commit/e59d60fbbe44876f878233d6487ed4f28d46af68 "Remove unnecessary null pointer checks").
