### ISSUE TITLE
Strange behavior with str.to.int and numeric comparisons

### ISSUE THREAD

**Issue by copumpkin** [Z3Prover/z3#2197]
This might be related to #2060 but even ignoring the hang on that case, it's not doing what I expect:

```
(declare-const a String)
(assert (<= (str.to.int a) 5))
(check-sat)
(get-model)
```

On rise4fun that assigns "0" to `a`, but on 4.8.1 and 4.8.4 (macOS if that matters) I'm getting an empty string out of my model. I'm not entirely sure what the comment on it saying "(ground rewriting only)" so perhaps this is expected to behave strangely?

**Comment by copumpkin** [comment]
Actually, this may be a dupe of https://github.com/Z3Prover/z3/issues/1966.

**Comment by NikolajBjorner** [comment]
both versions of Z3 report legal answers. str.to.int of strings that are not non-negative numbers map to -1, and -1 <= 5. So is 0 <= 5.

**Comment by copumpkin** [comment]
@NikolajBjorner thanks, I see. Is there an easy way to constrain the behavior to what we as humans would consider a valid number?

**Comment by NikolajBjorner** [comment]
You could add a regular expression that constrains possible values of a.
To give the idea:
   
         (assert (str.in.re a (re.+ (re.range "0" "9"))))

(this still allows 000 and 001 as strings, which is can be addressed by writing a longer and correct regular expression)

**Comment by copumpkin** [comment]
Oh, that makes sense, thanks! Wasn’t sure how well the solvers would play with one another but I’ll give it a try
