### ISSUE TITLE
Solver reports resource limits reached

### ISSUE THREAD

**Issue by roastduck** [Z3Prover/z3#2198]
After scaling my application to multi-thread (even only 2 threads), the solver returns `unknown` from time to time, with the reason `smt tactic failed to show goal to be sat/unsat (resource limits reached)`, but the actual memory consumption is always low.

I found all options related to resource limits in global settings and solver settings are infinite by default, and I didn't set any of them. Are there any options elsewhere, or are there any hard-coded limits? How can I reset those limit, or does the message I get just result from other errors?

Each threads in my application accesses different contexts, so I think it's thread safe.

I'm running version 4.8.4 using Python binding.

**Comment by NikolajBjorner** [comment]
It could be because the smt core solver overwrites the real reason, such as memory pressure. 
I found one place where this could have happened.

**Comment by roastduck** [comment]
After upgrading my Z3 from 4.8.4 to master, the problem disappears, i.e. it reports no error. The actual bug might already been fixed somewhere earlier in the master branch. I think this thread can be closed, because things cannot be reproduced again :)

**Comment by NikolajBjorner** [comment]
Probably yes, I try to forget whatever details were updated so we have to look at commit logs to examine further.
