### ISSUE TITLE
Possible Bug in fp.sqrt

### ISSUE THREAD

**Issue by kyledewey** [Z3Prover/z3#220]
On the `unstable` branch, at commit 52df2224e94de0842281899449a58966698450f5, consider the following input:

```
(set-option :produce-models true)
(set-logic QF_FP)
(declare-fun x0 () Float32)

; Floating point representation of -2
(assert (= (fp.sqrt RNE (fp #b1 #b10000000 #b00000000000000000000000)) x0))

(check-sat)
(get-model)
```

Z3 states that this is `sat`, with a model that `x0` is `(_ -zero 8 24)`.  According to the IEEE standard, the square root of `-2` should be a quiet `NaN`, though this only suggests `NaN` is the correct result.  Looking at [the expected SMT-LIB semantics](http://www.philipp.ruemmer.org/publications/smt-fpa.pdf), I'm actually not sure what's supposed to happen here.  From the standard, assuming `E^-` is 0 (I'm not 100% sure it is here; this is unclear to me) then the second case shouldn't apply, as in this case the exponent is not zero.  The third case would be applicable, except that it bears the constraint that the mantissa must be greater than 0, and in this case the mantissa is zero.  As such, it looks to me like no cases apply, though I could very well be wrong.  Given that everything should be total, if no cases apply, then this is a bug in the standard itself (or I'm confused, which, again, is quite possible).

In any event, on a "similar" input of `2.5`, Z3 returns `NaN`, which seems to be due to the third case of the standard applying (`m` is greater than 0 in this situation).  For what it's worth, on an input of 2, MathSAT5 reports `NaN`.  If this isn't an issue in either the standard or Z3, I'll go ahead and report it to the MathSAT5 team.

**Comment by wintersteiger** [comment]
Thanks for the report. Indeed, this does look fishy, I'll take a look. Note that the document you're citing is not "expected" anymore. The final theory differs in a number of details, see [theory definition](http://smtlib.cs.uiowa.edu/theories-FloatingPoint.shtml) and [semantics paper](http://smt-lib.org/papers/BTRW15.pdf).

**Comment by wintersteiger** [comment]
Yep, that was an obvious bug. This is fixed in unstable now, so I'm closing the issue.

**Comment by kyledewey** [comment]
Whoops; thanks for pointing that out.  I had grabbed the wrong link from the theory definition.  I see the final theory does cover this case.
