### ISSUE TITLE
Z3py AST string representation loses re.loop parameters

### ISSUE THREAD

**Issue by copumpkin** [Z3Prover/z3#2200]
I think this might have something to do with the strange syntax for `re.loop` in the documentation, as `((_ re.loop lo hi) r)`. I'm not quite sure why it's phrased that way, but regardless of that, here's what I get in Z3py:

```
>>> from z3 import *
>>> Loop(Re('a'), 5)
re.loop(str.to.re("a"))
>>> Loop(Re('a'), 5, 6)
re.loop(str.to.re("a"))
```

Note that the AST string representation lost the 5 and 6 parameters.

**Comment by NikolajBjorner** [comment]
The python pretty printer is now updated with features that facilitate reflecting the values back to a format that looks like the python input.
