### ISSUE TITLE
Error "Overflow encountered when expanding old_vector"

### ISSUE THREAD

**Issue by mschwerhoff** [Z3Prover/z3#2201]
Using Z3 4.8.5 604c9d38dca3, attached file (for whose ugliness I sincerely apologise), causes Z3 to report "Overflow encountered when expanding old_vector". Looks related to #1251. 

I hope you can reproduce the issue, despite all the `:timeout`s in the file.

[logfile-01.zip](https://github.com/Z3Prover/z3/files/3000549/logfile-01.zip)

**Comment by NikolajBjorner** [comment]
There is a high variance of behavior under the timeouts so even basic fuzzing timeouts around the range that are indicated in the file seems not to be able to hit the issue.
I have added a new feature 

        (get-info :rlimit)

It prints the current value of the rlimit counter.

Presumably incrementing the current rlimit by a delta prior to check-sat calls would be able to steer a repro to the same code path. The delta would be the difference between the rlimit printed before check-sat and after check-sat.

**Comment by NikolajBjorner** [comment]
FYI, using additional fuzzing I am able to reproduce some assertion violations in debug mode.
This points to some actionable bugs. Let me try to address these.

**Comment by mschwerhoff** [comment]
I'll happily let you try to address them ;-) Thank you!

Please let me know if you need further information — e.g. I can also run a debug built locally.

**Comment by NikolajBjorner** [comment]
Could you try with the newest version of master branch?

**Comment by NikolajBjorner** [comment]
It is not possible to use timeouts to produce reliable repros, but rlimits are more reasonable.
I have been using scripts of the form seen below to fuzz based on limits.
The input to the script is a trace from your file but suppressing "success" and adding some annotations 
to each check-sat call, for example

(echo "L15")
(get-info :rlimit)
(check-sat)
(get-info :rlimit)

The crashing output is then saved in crash.txt

I am sure you can write nicer scripts, but this is to give an idea of producing input that is easier to work with than the timeouts.


import re
import random
import os
import sys

with open("logfile-01.smt2") as f:
    bench = f.readlines()

with open("limits.txt") as f:
    crash = f.readlines()

lim = re.compile(":rlimit (\d+)\)")
start = False
before = 0
after  = 0
lims = {}
for line in crash:
    if line.startswith("L"):
        level = line[:-1]
        start = True
        continue
    m = lim.search(line)
    if m:
        n = int(m.group(1))
        if start:
            before = n
            start = False
        else:
            after = n
            lims[level] = after - before

is_echo = re.compile("echo \"L(\d+)\"")
is_to = re.compile("\(set-option :timeout ")
is_lim = re.compile("\(get-info :rlimit")

start = True
def update_line(line):
    global start
    m = is_echo.search(line)
    if m:
        level = "L" + m.group(1)
        if level not in lims:
            return line
        delta = lims[level]
        rand = random.random()
        delta = int(delta/2 + 3*rand*delta)
        start = True
        return line + ("\n(set-option :rlimit %d)\n" % delta)
    m = is_to.search(line)
    if m:
        return ";" + line
    m = is_lim.search(line)
    if m:
        if start:
            start = False
            return line
        else:
            return line + "(set-option :rlimit 1000000)\n"
    return line

num = 0
while True:
    num += 1
    start = True
    lines = [update_line(line) for line in bench]
    file = "limit%d.smt2" % num
    with open(file, 'w') as f:
        for line in lines:
            f.write(line)
    print(file)
    sys.stdout.flush()
    os.system("D:/z3/build/z3.exe %s" % file)


\\nikolaj-z420\D$\z3\build\fuzzrlimit.py


import re
import random
import os
import sys

with open("logfile-01.smt2") as f:
    bench = f.readlines()

timeout = re.compile(":timeout (\d+)\)")

def fuzz_timeout(line):
    m = timeout.search(line)
    if m:
        to = int(m.group(1))
        rand = random.random()
        tr = int(to/2 + 3*rand*to);
#        print(line)
        line = line.replace(m.group(1), "%d" % tr)
#        print(line)
    return line

num = 0
while True:
    file = "bench%d.smt2" % num
    num += 1
    lines = [fuzz_timeout(line) for line in bench]
    with open(file, 'w') as f:
        for line in lines:
            f.write(line)
    print(file)
    sys.stdout.flush()
    os.system("D:/z3/build/z3.exe %s" % file)

**Comment by mschwerhoff** [comment]
> 
> 
> Could you try with the newest version of master branch?

I just tried `nightly/z3-4.8.5.deb48bffe138-x64-win.zip` and cannot reproduce the error any more. Thank you! If you don't mind, please keep the issue open for a bit longer, I'd like to run a few additional experiments, just to check.

I'll also give your Python script a try, thanks.

**Comment by mschwerhoff** [comment]
FYI: I _think_ I might have observed the error again: while running my whole test suite, Z3 crashed at some point, but I couldn't yet reproduce the crash by separately running the failing test. I'll keep digging.

**Comment by mschwerhoff** [comment]
I haven't observed this problem in a while, so I'll close the issue.

**Comment by fpoli** [comment]
In case it's useful to others, I encountered this bug when using Z3 version 4.8.5. Using a more recent version of Z3 was enough to avoid the "Overflow encountered when expanding old_vector" error.
