### ISSUE TITLE
horn tactic print_certificate

### ISSUE THREAD

**Issue by fread2281** [Z3Prover/z3#2202]
The horn tactic has a print_certificate option inherited from query's options. It would be really nice if it worked. That is, `(check-sat-using (using-params horn :print_certificate true))` should print a certificate on unsat like `(query q3 :print-certificate true)` does on sat.

**Comment by NikolajBjorner** [comment]
try it

**Comment by fread2281** [comment]
Thanks! btw, does the horn tactic or the fixedpoint API work incrementally at all?

**Comment by NikolajBjorner** [comment]
The fixedpoint API isn't incremental. There is an incremental Datalog engine by Leonid Ryzhyk
https://github.com/ryzhyk/differential-datalog
