### ISSUE TITLE
Z3py isn't interruptible with ctrl-c

### ISSUE THREAD

**Issue by copumpkin** [Z3Prover/z3#2203]
If you set up any long-running Z3 execution from Z3py and give up and want to stop it, you won't be able to ctrl-c out of your Python program, and you have to kill it from outside.

Apparently this is a fairly common problem with native Python extensions and the solution as I understand it (from [here](https://stackoverflow.com/a/33652496/104136)) is to periodically call `PyErr_CheckSignals()` from the native code. I don't know how feasible it is to inject that into the Z3 Python API but it would definitely make things more pleasant.

**Comment by NikolajBjorner** [comment]
yes, major pain, but a simple default configuration change does the job.

**Comment by copumpkin** [comment]
Oh, I hadn't seen that configuration option, thanks!

**Comment by NikolajBjorner** [comment]
and I had forgotten about it, and ended up killing python the hard way most of the time. no longer.
