### ISSUE TITLE
Parallel.enable for QF_BV in 4.8

### ISSUE THREAD

**Issue by maxzinkus** [Z3Prover/z3#2207]
I'm running Z3 via Python, and noticing that with
 ```
solver = SolverFor("QF_BV")
solver.set_param("parallel.enable", True)
solver.set_param("parallel.threads.max", 32)
```
When I run the program, I noticed that only one new thread spins up through the duration of execution. How do I ensure that multiple threads are used, or what might cause this issue?

Potentially related issues: #1898 #1890

**Comment by wintersteiger** [comment]
This is a relatively new feature. What version of Z3 are you running and what input are you running it on? (E.g., if a simplifier solves the problem, it may never need the parallel solver.)

**Comment by maxzinkus** [comment]
I'm on 4.8.0 as reported by `z3 --version`. I'm running it on a complex system of assertions created via python which include bitshifts, xors, and various other bitwise operations (some with bitvec constants, other with bitvecs as both operands).

**Comment by NikolajBjorner** [comment]
Try newer versions as the availability of parallel features got fixes after 4.8.0.
Try also to set the parallel parameters as _global_ parameters (not on the solver object).
For example, this works for me:

from z3 import *
solver = SolverFor("QF_BV")
set_option("parallel.enable", True)
set_option("parallel.threads.max", 5)
solver.from_file("D:\\QF_BV\\2017-BuchwaldFried\\synthesis.dump.ia32_RorMem_base_index_scale_disp2--Add32.Add32.Add32.Add32.load32.Or32.Or32.store32.am_shl32.0001.smt2")
print(solver.check())

**Comment by maxzinkus** [comment]
The change to `set_option` doesn't seem to fix it. Also, I was mistaken: `z3.get_version_string()` reports 4.8.5

**Comment by maxzinkus** [comment]
I moved the `set_options` to before I instantiate the solvers and `tactic.parallel` is logging something. Does that mean threads will be used?

**Comment by NikolajBjorner** [comment]
Threads should be used after some initial rounds of solving. Depending on the problem size it can take some minutes. By default it doubles the number of threads every time it makes a cubing decision.

**Comment by maxzinkus** [comment]
Excellent, thanks!
