### ISSUE TITLE
How to speedup Z3 for an optimization process?

### ISSUE THREAD

**Issue by Timingan** [Z3Prover/z3#2208]
Hello,
Thanks for your effort and excellent work on Z3 solver. This is my first time to use SMT solver. I am trying to solve an optimization problem with Z3, while, I have run it on a CPU server for nearly 50 hours with no result printed. I sincerely ask for your help.
My task is to place some chess pieces on a board. The chess piece needs some time to finish specific position movement on the board after it has been put on the board. And one piece to put at a time. One position for one piece. I have about 200 pieces and the size of board is around 160*160. I want to get the minimum time. 

The process is as follows:
put piece[i] on the board -> wait for its movement -> put piece[j] on the board -> wait......

I write it in SMT2 language, declare some 'Int' variables(about 1,000 variables, presenting 'the position of chess piece and recording the critical moment for pieces'), and add some IMPLY, OR, AND logic constraints and boundaries(about 6w lines) on them. 
Examples:
<img width="720" alt="屏幕快照 2019-03-28 下午9 25 58" src="https://user-images.githubusercontent.com/35556592/55161279-19bdd800-51a0-11e9-9355-eed1fa499e6e.png">
<img width="495" alt="屏幕快照 2019-03-28 下午9 22 01" src="https://user-images.githubusercontent.com/35556592/55161208-f98e1900-519f-11e9-8461-16077f786912.png">
<img width="290" alt="屏幕快照 2019-03-28 下午9 24 13" src="https://user-images.githubusercontent.com/35556592/55161180-e9763980-519f-11e9-8345-61c9b3de93a3.png">
The lines above appears most in the code.

I have some questions about Z3 and sincerely hope for your answer.
a. 
I am wondering what is the strategy for Z3 to solve an optimization problem like this. For such optimization problem, will Z3 return a global optimal solution.
b.
What is the largest number of timeout( __ ms)?
c.
Are there some tactics for this kind of constraints and optimization problem? I have tried parallel, split-clause, solver-eq. 
d.
Will it help if I declare the variables as BitVector? And what are the tactics for BV?

**Comment by NikolajBjorner** [comment]
a: for optimization, Z3 produces only the optimal answer. You can interrupt and get intermediary answers, if any was found. You can also specify parameters to have intermediary models printed out. Use z3 -pm:opt to see the parameters.
b: timeouts is specified in milliseconds. it is bounded by 2^32-1
c. Optimization doesn't support tactics
d. Bitvectors tend to work better on benchmarks that don't use + in essential ways.
