### ISSUE TITLE
Z3 model_to_string inconsistent with model_eval

### ISSUE THREAD

**Issue by tjknoth** [Z3Prover/z3#2209]
I'm curious about the semantics of `model_eval` -- I have an app that involves sending large disjunctions to z3, none of which share any variables, and I'm attempting to determine which clauses are satisfied by looking at which variables are actually present in the resulting model. 
When I print out the models, I see results for only a few variables. I was assuming that these corresponded to the variables that are assigned in the model. However, when I query the model with `model_eval` (and with model completion turned off), I get valid assignments for many variables that were not printed out. 

Basically, it seems like `model_to_string` and `model_eval` are giving me different partial models, is this the intended behavior? The result from `model_to_string` is always a subset of what I get from `model_eval` (again, without model completion). Is there a way to get only the partial model from `model_to_string`? 

I should add that if I manually evaluate each clause of the disjunction with the model to see which clauses are actually satisfied, only the clauses with the variables that are shown by `model_to_string` are satisfied.

I'm interacting with the z3 API (version 4.7.1) through the Haskell bindings. I'm working on getting a minimal example together.

**Comment by NikolajBjorner** [comment]
model_eval takes an optional argument - whether to complete a model assignment. That is, it will assign values to variables that are not assigned already in a model. They are don't cares when it comes to a model, but depending on how you want to use model_eval it could be useful to have values.
The more robust way to distinguish the don't cares may be to extract an unsat core over the current assignment of atoms for the negation of your formula. In other words, suppose M is a propositional model (set of literals) that satisfies phi, then not phi & M is unsat, If you add not phi to a solver, then call check(M), the result should be unsat and you can use the unsat core over M to find an assignment that matters.

Notice that you can also iterate over a model and retrieve 
the assignments for constants (and functions). Then you wouldn't have to rely on model_eval.

**Comment by tjknoth** [comment]
I assume you're referring to the model completion argument? I've been turning that off, and the results from `model_eval` are incomplete as I would expect, but still include assignments that seem unnecessary and don't show up when I print the model. 

The unsat core idea might help, thanks! I'll try just iterating through the model as well.
