### ISSUE TITLE
Z3 version 4.4.1 gives semingly incorrect model

### ISSUE THREAD

**Issue by sdasgup3** [Z3Prover/z3#2212]
With the following Z3 query:
```
(declare-const A (_ BitVec 64))
(declare-const B (_ BitVec 64))
(push)  
(assert

(>= (+ (bv2int A) (bv2int B)) (^ 2 32))
)  
(check-sat)
(get-model)
(pop)
```  
With Z3 version 4.4.1, I am getting a model like
```
sat
(model 
  (define-fun A () (_ BitVec 64)
    #x0000000000000000)
  (define-fun B () (_ BitVec 64)
    #x0000000000000000)
)
```
With version Z3 version 4.5.1 I am getting correct interpretation. 
Is this fixed as per  https://github.com/Z3Prover/z3/issues/250 ? Or there is something I am doing wrong.

**Comment by NikolajBjorner** [comment]
There is no support for (very) old versions of Z3. Use newer versions where the models are correct.
