### ISSUE TITLE
Opam install isn't static

### ISSUE THREAD

**Issue by giltho** [Z3Prover/z3#2213]
Hello,

I'm having an issue with the OCaml API of z3 installed through OPAM.
It installs correctly, and I can build my libraries and programs, but as soon as I try to execute my binary that depends on z3, it fails with :
```
dyld: Library not loaded: libz3.dylib
  Referenced from: /Path/to/project/./binary.native
  Reason: image not found
```

I'm not an expert in the domain of static/dynamic linking etc., I searched a bit, and I noticed that the [z3 `opam` file](https://github.com/ocaml/opam-repository/blob/master/packages/z3/z3.4.8.4/opam) gives the `--staticlib` flag to `mk_make`, which "build Z3 static library". 

Is this working as it should be ?

Thanks

**Comment by c-cube** [comment]
Note that the opam package isn't maintained by the Z3 maintainers. It works for me by exporting the opam path in `LD_LIBRARY_PATH` on linux (there's a similar thing to do on mac OS I think). I'm not sure if we could just package the z3 _static_ library as part of an OCaml module; it'd be nice, but probably not easy.

**Comment by giltho** [comment]
Yes I just saw, the maintainer field on the file sorry.
So it's not possible :/ It means I have to ship the z3 dylib file with my executable on installation ?
I need to find an elegant way of doing that :/

**Comment by c-cube** [comment]
I have absolutely no idea how to do this cleanly, sorry. Also note that on my machine, libz3.so weights 30MB, it might be problematic to ship it inside every binary.

**Comment by giltho** [comment]
For now, adding the right folder to `LD_LIBRARY_PATH` works in macOS, but it means I have to reexport the variable everytime I change my opam switch, if I have several ocaml version working in parallel :/

I guess the best way is just to ship the z3 dylib with our tool. I just need to find how that can be done.

Thank you for you answer ! (And for answering so fast !)
