### ISSUE TITLE
Does Z3 support union type in Datatype

### ISSUE THREAD

**Issue by VictorCoder123** [Z3Prover/z3#2215]
Hi All,

I was wondering if Z3 supports the union of of multiple sorts to create a user-defined new sort? I haven't find a way to write the following expression. 

```python
A = Datatype('A')
A.declare('cons', ('item', UserDefinedUnionSort))
UserDefinedUnionSort = StringSort() + IntSort()

cons(IntVal(1))
cons(StringVal('hello'))
```

**Comment by NikolajBjorner** [comment]
Maybe

from z3 import *

u = Datatype('IntOrString')
u.declare('IntV', ('int', IntSort()))
u.declare('StringV', ('string', StringSort()))
IntOrString = u.create()
StringV = IntOrString.StringV
IntV = IntOrString.IntV

print(IntV(1))
print(StringV(StringVal("abc")))
print(IntV(1).sort())
print(IntV(1) == StringV(StringVal("abc")))
s = String('s')
print(simplify(IntV(1) == StringV(s)))

**Comment by VictorCoder123** [comment]
Thanks a lot and hope z3 will support it in the future.

**Comment by NikolajBjorner** [comment]
Do you mean, you would like the Python API to expose shorthands for creating Product and Sum types?

**Comment by VictorCoder123** [comment]
Yes, what I mean is union type or sum type, which express choice between multiple data structures. I only have used Python API to write some expressions and didn't find any API that can handle Sum type. Is Sum type supported in SMT2? I haven't checked it yet but would appreciate if Python API provides the shorthands as well.

**Comment by VictorCoder123** [comment]
To be more specific, I attach the following code in Python. Node has a reference to MetaNode and I want to create a union type AllNode ::= MetaNode + Node. The Dilemma is that if I put MetaNode and Node in separate datatypes like below, I don't know how to create a union type without ugly wrappers. If I put MetaNode and Node as constructors under the same datatype, I don't know how to reference MetaNode in Node.

```python
MetaNodeDef = Datatype('MetaNode')
MetaNodeDef.declare('MetaNode', ('name', StringSort()))
MetaNodeDef = MetaNodeDef.create()
MetaNode = MetaNodeDef.MetaNode

NodeRef = Datatype('Node')
NodeRef.declare('Node', ('name', StringSort()), ('type', MetaNodeDef))
NodeRef = NodeRef.create()
Node = NodeRef.Node

# AllNode ::= MetaNode + Node
AllNodeDef = Datatype('AllNode')
AllNodeDef.declare('MetaNodeWrap', ('node', MetaNodeDef))
AllNodeDef.declare('NodeWrap', ('node', NodeRef))
AllNodeDef = AllNodeDef.create()
MetaNodeWrap = AllNodeDef.MetaNodeWrap
NodeWrap = AllNodeDef.NodeWrap
```

**Comment by NikolajBjorner** [comment]
So,

<code>

    def TupleSort(name, sorts, ctx = None):
    """Create a named tuple sort base on a set of underlying sorts
    Example:
        >>> pair, mk_pair, (first, second) = TupleSort("pair", [IntSort(), StringSort()])
    """    
    tuple = Datatype(name, ctx)
    projects = [ ('project%d' % i, sorts[i]) for i in range(len(sorts)) ]
    tuple.declare(name, *projects)
    tuple = tuple.create()
    return tuple, tuple.constructor(0), [tuple.accessor(0, i) for i in range(len(sorts))]

    def DisjointSum(name, sorts, ctx=None):
    """Create a named tagged union sort base on a set of underlying sorts
    Example:
        >>> sum, ((inject0, extract0), (inject1, extract1)) = DisjointSum("+", [IntSort(), StringSort()])
    """
    sum = Datatype(name, ctx)
    for i in range(len(sorts)):
        sum.declare("inject%d" % i, ("project%d" % i, sorts[i]))
    sum = sum.create()
    return sum, [(sum.constructor(i), sum.accessor(i, 0)) for i in range(len(sorts))]

**Comment by VictorCoder123** [comment]
Thanks for your help! 

I think the instances of `TupleSort` requires instantiation of all children sorts like t = `tuple(IntVal(1), StringVal('hello')` at the same time so it does not represent Sum type. While instances of `DisjointSum` is what I'm looking for but still need constructor `injectx` to hold the value of children sorts like `v = inject0(IntVal(1)) v2 = inject1(StringVal('hello'))` and I don't think it's very different from `AllNode` datatype in my last example code.

```python
ADef = Datatype('A')
ADef.declare('A', ('num', IntOrStringSort()))
ADef = ADef.create()
A = ADef.A
```
Is there any way we can write `a = A(StringVal('hello'))` instead of `a = A(inject0(StringVal('hello')))`

**Comment by NikolajBjorner** [comment]
There isn't. This is similar to algebraic datatypes in ML languages.
