### ISSUE TITLE
z3 minimize versus soft-constraints clarification

### ISSUE THREAD

**Issue by muqsitazeem148** [Z3Prover/z3#2216]
I am using python binding of Z3 (version 4.8.4) under 64bit Linux.

Suppose, I have a bunch of soft constraints as follows:

s.add_soft(c1)
s.add_soft(c2)
s.add_soft(c3)

then Z3 will try to satisfy as many as possible from constraints c1, c2 and c3.

Also I want to minimize value of m, i.e.

s.minimize(m)

minimize will try to find the minimum value of m.

Suppose the value of m is dependent on c1,c2 and c3 in some way, what will z3 do? Will it first minimize m and then try to satisfy the soft-constraints c1, c2 and c3? Or will it first try to satisfy all the soft constraints and then minimize? Or will it be non-deterministic?

**Comment by NikolajBjorner** [comment]
It should be in the order of declaration to 's'.
If you first add soft constraints, then s.minimize(m), then it will first find the optimal value for the soft constraints, and then minimize m. On the other hand, if you declare s.minimize(m), before adding soft constraints, it will find the optimal value for m before the soft constraints. 

Example:

from z3 import *

x, y, z = Ints('x y z')

s = Optimize()
s.add(x > y)
s.add(y > z)
s.add(z > 0)
s.add_soft(x > y +1)
h = s.minimize(x)
print(s.check())
print(s.model())
print(h.value())


s = Optimize()
s.add(x > y)
s.add(y > z)
s.add(z > 0)
h = s.minimize(x)
s.add_soft(x > y +1)
print(s.check())
print(s.model())
print(h.value())

The output is:

sat
[y = 2, z = 1, x = 4]
4
sat
[z = 1, y = 2, x = 3]
3
