### ISSUE TITLE
Segfault when using `declare-datatypes` (Z3 version 4.8.0 - 64 bit)

### ISSUE THREAD

**Issue by traiansf** [Z3Prover/z3#2217]
We're trying to use `declare-datatypes`  to help us reason about constructors and case-splits.
However, we're noticing an exceptional behavior for a seemingly benign example: 
```
(declare-datatypes ((|HB_S| 0 ) (|HB_T| 0 ) ) (((|HB_C|) (|HB_D| (|HB_D1| |HB_T| ) ) ) ((|HB_E|) ) ) )
(declare-fun x () |HB_S| )
(assert (distinct x |HB_C| ))
(check-sat)
sat
(assert (distinct x (|HB_D| |HB_E| ) ))
(check-sat)
Segmentation fault (core dumped)
```

Do you know what might happen here?
Interestingly enough, if we declare the datatypes separately, the behavior is as expected:
```
(declare-datatypes ( (|HB_T| 0 ) ) (((|HB_E|) ) ) )
(declare-datatypes ((|HB_S| 0 )) (((|HB_C|) (|HB_D| (|HB_D1| |HB_T| ) ) )))
(declare-fun x () |HB_S| )
(assert (distinct x |HB_C| ))
(check-sat)
sat
(assert (distinct x (|HB_D| |HB_E| ) ))
(check-sat)
unsat
```

**Comment by NikolajBjorner** [comment]
It should be fixed at this point

**Comment by traiansf** [comment]
Thanks! Is it in any release, or should we build from the master branch?

**Comment by NikolajBjorner** [comment]
The nightly builds seem stale, except the windows builds. So you would need to build your own bits from the current master branch for now if you use MacOs, Ubuntu.

**Comment by wintersteiger** [comment]
(Nightly builds are fixed)
