### ISSUE TITLE
Check returns sat, but error in model

### ISSUE THREAD

**Issue by SimonPetocz** [Z3Prover/z3#2219]
I'm having an issue when using functions with two different argument types. 
In the following, two_arg should be able to be [else -> 0], and check() returns sat, but model() causes an error:
"Sort mismatch at argument #1 for function (declare-fun = (Bool Bool) Bool) supplied sort is Int"

Code:
```
two_arg = Function("two_arg", BoolSort(), IntSort(), IntSort())
x = Const('x', BoolSort())
y = Const('y', IntSort())
s.add(ForAll(x, ForAll(y, Implies((two_arg(x,y) == 3), Or(x, y == 3)))))
s.add((two_arg(True, 3) == 0))
print(s.check())
print(s.model())
```

**Comment by NikolajBjorner** [comment]
I am unable to reproduce the issue. 
Do you have a self-contained example that crashes, and what version of Z3 are you using?

**Comment by SimonPetocz** [comment]
Thanks for the response. When I make a standalone file and run it from command line it works fine, so it must be an issue with my IDE configuration.
