### ISSUE TITLE
z3py: Inflexible use of __debug__

### ISSUE THREAD

**Issue by stklik** [Z3Prover/z3#2225]
I observed that a lot of code uses `if __debug__:` calls that allow a switch between optimized mode and "safe mode" where various checks are performed.

Unfortunately, this solution is very inflexible, as the only way to use the optimized mode is via `python -O`. I am using z3 in combination with Jupyter, where I have not found a way to enter `__debug__`-mode.

Before opening a long discussion, I want to first ask whether there is a particular reason for using `__debug__` directly? Wouldn't it be better to add a form of placeholder variable in between whose value can be modified?
This could be implemented by e.g. changing all `if __debug__:` to `if DEBUG_MODE:` and defining  `DEBUG_MODE = __debug__` in a central place (e.g. in `__init__.py`).

This way, it would be even possible to manually switch on DEBUG_MODE at runtime (during execution) and gain some performance for particular tasks.

**Comment by NikolajBjorner** [comment]
sounds good. Many questions in computer science can be solved by a level of indirection.

**Comment by NikolajBjorner** [comment]
see commit

**Comment by stklik** [comment]
Perfect. Thanks for the quick action.
