### ISSUE TITLE
Uninterpreted function error in Datatype accessor

### ISSUE THREAD

**Issue by VictorCoder123** [Z3Prover/z3#2226]
I wrote the following code with union types and tried to call accessor function but z3 always gives me an error that the accessor function is uninterpreted. My understanding to z3 is still limited and don't know if the fixpoint executor needs to add some configurations to make it right. Thanks!

```python
    fp = Fixedpoint()

    MetaNodeDef = Datatype('MetaNode')
    MetaNodeDef.declare('MetaNode', ('name', StringSort()))
    MetaNodeDef = MetaNodeDef.create()
    MetaNode = MetaNodeDef.MetaNode

    NodeDef = Datatype('Node')
    NodeDef.declare('Node', ('name', StringSort()), ('type', MetaNodeDef))
    NodeDef = NodeDef.create()
    Node = NodeDef.Node

    # AllNode ::= MetaNode + Node
    AllNodeDef = Datatype('AllNode')
    AllNodeDef.declare('MetaNodeWrap', ('node', MetaNodeDef))
    AllNodeDef.declare('NodeWrap', ('node', NodeDef))
    AllNodeDef = AllNodeDef.create()
    MetaNodeWrap = AllNodeDef.MetaNodeWrap
    NodeWrap = AllNodeDef.NodeWrap

    allnode_example_1 = MetaNodeWrap(MetaNode(StringVal('test')))
    print simplify(AllNodeDef.accessor(0, 0)(allnode_example_1))
    print fp.query(AllNodeDef.accessor(0, 0)(allnode_example_1) == MetaNode(StringVal('test')))
```

**Comment by NikolajBjorner** [comment]
Accessor functions are partially specified. For example head(cons(x,l)) = x, but head(nil) does not have a fixed meaning so it is uninterpreted when applied to nil. 
The fp engines don't support uninterpreted fuctions.
The Horn clause solvers don't handle strings either. 
So better avoid the fixedpoint engine for these kinds of queries.

**Comment by VictorCoder123** [comment]
I see what you mean but somehow adding simplify() works and resolve the issue. `fp.query(simplify(AllNodeDef.accessor(0, 0)(allnode_example_1)) == MetaNode(StringVal('test')))`
