### ISSUE TITLE
R language API bindings

### ISSUE THREAD

**Issue by alexkyllo** [Z3Prover/z3#2230]
I haven't been able to find any R packages for SMT solving. Are you aware of anyone already working on Z3 bindings for R? Would you be willing to potentially accept a PR to add R bindings?

**Comment by NikolajBjorner** [comment]
sounds good. Would be important to ensure that the build system builds them and runs unit tests.

**Comment by alexkyllo** [comment]
After reading through the python API codebase and observing that the build system is also mostly python scripts, I think it's probably best to follow a similar approach for R--also using a python script (similar to [setup.py](https://github.com/Z3Prover/z3/blob/master/src/api/python/setup.py)) to copy the needed C++ source files into the R package's src subdirectory, and then write the R bindings to them using [Rcpp](https://github.com/RcppCore/Rcpp), plus maybe a bit of custom codegen for the enums etc. 

Then, just like the Python package, the C++ sources don't need to be duplicated in the Z3 repository but they would be included in the archive submitted to the package repository ([CRAN](https://cran.r-project.org/)), so that the R package can be built from source without depending on an existing libz3.dll/.so install.

As for unit tests, I think they should be written in R using the standard test framework for R packages, but they can also be kicked off from make or a python script, just as long as you have an R interpreter installed.

Any thoughts?

**Comment by NikolajBjorner** [comment]
Rcpp is probably the way to go. The other approach, using the C API, seems much more tedious. 

For the build scripts:

- The setup.py script was created by Andrey Dutcher as part of the z3-solver pip package. So for a CRAN setting, seems relevant.
- Other scripts used to create stubs during build are in the scripts directory. The update_api.py script is used to create dynamic stubs. If you have a way to build it on top of the C++ API to Z3 (in src/api/c++/z3++.h), it could avoid customization there. The C++ API changes very slowly and mostly by additions. 

One obstacle in redistribution is whether to rely on rebuilding from sources: users will invariably run into build issues and there is a support question around this. If releasing binaries, a pain point is to ensure that dependencies are taken care of, but this could be a one-time issue. Z3 has only a few: currently omp, and for VS builds the redistributable dlls. 

If it is possible to update the travis CI to unit test from R, that is install a suitable R in the docker containers and run the tests it would be perhaps the best and most seamless approach. Even installing
ocaml, java, .net, and python to build and test everything is not very practical when starting from a fresh platform.

**Comment by alexkyllo** [comment]
Thanks for the response!

>One obstacle in redistribution is whether to rely on rebuilding from sources: users will invariably run into build issues and there is a support question around this. If releasing binaries...

CRAN only allows submission of source packages; they are not allowed to include binary code of any kind. So I think the two options are either to include all the sources needed to build libz3 in the R package submitted to CRAN, or to link to a shared libz3 library, in which case the user will have to install libz3 first, before installing the R package. 

TravisCI does have support for R, so it should be possible to get Travis to build it and run tests.

**Comment by NikolajBjorner** [comment]
closing as no traction, there are now Julia bindings.
