### ISSUE TITLE
segment fault while solve Implies

### ISSUE THREAD

**Issue by LH-413x** [Z3Prover/z3#2235]
from z3 import *

x,y=Bools('x y')
solve(Implies(And(x,y),Or(x,y)))

Process:               Python [7594]
Path:                  /usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/Resources/Python.app/Contents/MacOS/Python
Identifier:            Python
Version:               3.7.3 (3.7.3)
Code Type:             X86-64 (Native)
Parent Process:        pycharm [1198]
Responsible:           Python [7594]
User ID:               501

Date/Time:             2019-04-14 01:04:59.473 +0800
OS Version:            Mac OS X 10.14.4 (18E226)
Report Version:        12
Bridge OS Version:     3.4 (16P4507)
Anonymous UUID:        DF88302B-5C65-BCB2-A1EF-295FC0F983C5

Sleep/Wake UUID:       E00A27D9-32C5-4771-8F56-06F93B0A719E

Time Awake Since Boot: 62000 seconds
Time Since Wake:       1900 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_INSTRUCTION (SIGILL)
Exception Codes:       0x0000000000000001, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Signal:    Illegal instruction: 4
Termination Reason:    Namespace SIGNAL, Code 0x4
Terminating Process:   exc handler [7594]

Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   libz3.dylib                   	0x000000010b76cba4 sat2goal::mc::operator()(ref<model>&) + 724
1   libz3.dylib                   	0x000000010af7b4de inc_sat_solver::get_model_core(ref<model>&) + 334
2   libz3.dylib                   	0x000000010af6e84d enum2bv_solver::get_model_core(ref<model>&) + 29
3   libz3.dylib                   	0x000000010af70281 pb2bv_solver::get_model_core(ref<model>&) + 33
4   libz3.dylib                   	0x000000010af6a3c0 bounded_int2bv_solver::get_model_core(ref<model>&) + 32
5   libz3.dylib                   	0x000000010b77eab6 solver2tactic::operator()(ref<goal> const&, sref_buffer<goal, 16u>&) + 390
6   libz3.dylib                   	0x000000010b82f6b0 and_then_tactical::operator()(ref<goal> const&, sref_buffer<goal, 16u>&) + 1232
7   libz3.dylib                   	0x000000010b832f10 exec(tactic&, ref<goal> const&, sref_buffer<goal, 16u>&) + 48
8   libz3.dylib                   	0x000000010b83324b check_sat(tactic&, ref<goal>&, ref<model>&, labels_vec&, obj_ref<app, ast_manager>&, obj_ref<dependency_manager<ast_manager::expr_dependency_config>::dependency, ast_manager>&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&) + 267
9   libz3.dylib                   	0x000000010b7767af (anonymous namespace)::tactic2solver::check_sat_core(unsigned int, expr* const*) + 655
10  libz3.dylib                   	0x000000010b7755c9 solver_na2as::check_sat(unsigned int, expr* const*) + 169
11  libz3.dylib                   	0x000000010b778280 combined_solver::check_sat(unsigned int, expr* const*) + 1008
12  libz3.dylib                   	0x000000010af263e2 _solver_check(_Z3_context*, _Z3_solver*, unsigned int, _Z3_ast* const*) + 258
13  libz3.dylib                   	0x000000010af265c1 Z3_solver_check_assumptions + 97
14  _ctypes.cpython-37m-darwin.so 	0x0000000109f1c377 ffi_call_unix64 + 79
15  _ctypes.cpython-37m-darwin.so 	0x0000000109f1cb3d ffi_call + 713
16  _ctypes.cpython-37m-darwin.so 	0x0000000109f183f2 _ctypes_callproc + 647
17  _ctypes.cpython-37m-darwin.so 	0x0000000109f12e25 PyCFuncPtr_call + 500
18  org.python.python             	0x00000001098fbaf4 _PyObject_FastCallKeywords + 358
19  org.python.python             	0x0000000109990e20 call_function + 746
20  org.python.python             	0x0000000109989b9a _PyEval_EvalFrameDefault + 6439
21  org.python.python             	0x00000001099916d3 _PyEval_EvalCodeWithName + 1867
22  org.python.python             	0x00000001098fbc53 _PyFunction_FastCallKeywords + 225
23  org.python.python             	0x0000000109990e27 call_function + 753
24  org.python.python             	0x0000000109989c35 _PyEval_EvalFrameDefault + 6594
25  org.python.python             	0x00000001099916d3 _PyEval_EvalCodeWithName + 1867
26  org.python.python             	0x00000001098fbc53 _PyFunction_FastCallKeywords + 225
27  org.python.python             	0x0000000109990e27 call_function + 753
28  org.python.python             	0x0000000109989b81 _PyEval_EvalFrameDefault + 6414
29  org.python.python             	0x00000001099916d3 _PyEval_EvalCodeWithName + 1867
30  org.python.python             	0x00000001098fbc53 _PyFunction_FastCallKeywords + 225
31  org.python.python             	0x0000000109990e27 call_function + 753
32  org.python.python             	0x0000000109989c35 _PyEval_EvalFrameDefault + 6594
33  org.python.python             	0x00000001099916d3 _PyEval_EvalCodeWithName + 1867
34  org.python.python             	0x00000001099881d0 PyEval_EvalCode + 51
35  org.python.python             	0x00000001099b679b run_mod + 54
36  org.python.python             	0x00000001099b57c5 PyRun_FileExFlags + 163
37  org.python.python             	0x00000001099b4e6b PyRun_SimpleFileExFlags + 263
38  org.python.python             	0x00000001099cd9b0 pymain_main + 5367
39  org.python.python             	0x00000001099ce088 _Py_UnixMain + 56
40  libdyld.dylib                 	0x00007fff7850f3d5 start + 1

Thread 0 crashed with X86 Thread State (64-bit):
  rax: 0x00007fffaac578b0  rbx: 0x00007ffee631fee0  rcx: 0x39f98cf27ea7009e  rdx: 0x0000000000000000
  rdi: 0x00007fffab50c028  rsi: 0x00000000000120a8  rbp: 0x00007ffee631fd20  rsp: 0x00007ffee631fcd0
   r8: 0x00000000000130a8   r9: 0x00007fffab50c048  r10: 0x0000000000000000  r11: 0x00007fffab50c040
  r12: 0x00007f85631ec1b8  r13: 0x00007f8561165008  r14: 0x0000000000000000  r15: 0x00007f85631ee8c8
  rip: 0x000000010b76cba4  rfl: 0x0000000000010202  cr2: 0x000000010aee6270
  
Logical CPU:     6
Error Code:      0x00000000
Trap Number:     6

Binary Images:
       0x1098de000 -        0x1098dffff +org.python.python (3.7.3 - 3.7.3) <B968F9D7-7B2D-38ED-B412-D123E08C3E78> /usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/Resources/Python.app/Contents/MacOS/Python
       0x1098e2000 -        0x109a65fff +org.python.python (3.7.3, [c] 2001-2019 Python Software Foundation. - 3.7.3) <84264F8D-1243-3F6F-AECD-81001338665C> /usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/Python
       0x109f10000 -        0x109f1ffff +_ctypes.cpython-37m-darwin.so (0) <D276A7E4-A817-337E-AE82-198934D03AD9> /usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/lib-dynload/_ctypes.cpython-37m-darwin.so
       0x109f2a000 -        0x109f2dfff +_struct.cpython-37m-darwin.so (0) <00562B1E-7813-30E5-A48D-613782E211E0> /usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/lib-dynload/_struct.cpython-37m-darwin.so
       0x109f35000 -        0x109f38fff +zlib.cpython-37m-darwin.so (0) <06AC34F5-76F2-3CBE-A0D4-AA8499C77CCE> /usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/lib-dynload/zlib.cpython-37m-darwin.so
       0x109fa6000 -        0x109fa7fff +_heapq.cpython-37m-darwin.so (0) <A5297284-1D5D-3D4B-96B2-335DAE0A48F8> /usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/lib-dynload/_heapq.cpython-37m-darwin.so
       0x109fab000 -        0x109facfff +_bz2.cpython-37m-darwin.so (0) <ADC48339-0FCB-3C21-9077-58779C911962> /usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/lib-dynload/_bz2.cpython-37m-darwin.so
       0x109fb0000 -        0x109fb3ff7 +_lzma.cpython-37m-darwin.so (0) <A1086826-C244-33B0-AD7E-387B5EAC525F> /usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/lib-dynload/_lzma.cpython-37m-darwin.so
       0x109fb8000 -        0x109fb9fff +grp.cpython-37m-darwin.so (0) <8DDDA372-84F1-38E5-A7EA-41538F7BB0EC> /usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/lib-dynload/grp.cpython-37m-darwin.so
       0x109fbc000 -        0x109fbdfff +_posixsubprocess.cpython-37m-darwin.so (0) <41961A25-00CC-33D3-8FD3-CF6A1553B0E7> /usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/lib-dynload/_posixsubprocess.cpython-37m-darwin.so
       0x10a082000 -        0x10a09dff3 +liblzma.5.dylib (0) <D5E25B2B-6DFB-3233-850B-65F488A14688> /usr/local/opt/xz/lib/liblzma.5.dylib
       0x10a0a3000 -        0x10a0a6ff7 +binascii.cpython-37m-darwin.so (0) <3D6B54D2-32BD-3793-8EB9-24C731D33CE0> /usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/lib-dynload/binascii.cpython-37m-darwin.so
       0x10a0ea000 -        0x10a0edfff +select.cpython-37m-darwin.so (0) <DF16ED7C-95EE-3995-BE70-21C46BC67798> /usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/lib-dynload/select.cpython-37m-darwin.so
       0x10a0f2000 -        0x10a0f6ffb +math.cpython-37m-darwin.so (0) <AD4BEECA-77E1-3ECB-A0C9-8C9D6849F4E2> /usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/lib-dynload/math.cpython-37m-darwin.so
       0x10a13c000 -        0x10a147ff3 +_datetime.cpython-37m-darwin.so (0) <DCCE3472-6269-3868-A81E-1D04BE56523F> /usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/lib-dynload/_datetime.cpython-37m-darwin.so
       0x10a14f000 -        0x10a16effb +pyexpat.cpython-37m-darwin.so (0) <4F167C7B-8CFB-3CF4-B007-3DD3A27FB68A> /usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/lib-dynload/pyexpat.cpython-37m-darwin.so
       0x10a1ba000 -        0x10a1bdfff +_hashlib.cpython-37m-darwin.so (0) <CEEDA174-D324-3C9F-A641-6883C26D230B> /usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/lib-dynload/_hashlib.cpython-37m-darwin.so
       0x10a1c1000 -        0x10a200ff7 +libssl.1.0.0.dylib (0) <0F81118F-C6DD-3452-85EB-D1860B45848F> /usr/local/opt/openssl/lib/libssl.1.0.0.dylib
       0x10a21f000 -        0x10a224ffb +_blake2.cpython-37m-darwin.so (0) <4858ABFA-F4AF-32FD-8F67-24F5EA5E5EDD> /usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/lib-dynload/_blake2.cpython-37m-darwin.so
       0x10a228000 -        0x10a238fff +_sha3.cpython-37m-darwin.so (0) <67867CF0-9EBE-33A5-AC9F-F0B1233D72EB> /usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/lib-dynload/_sha3.cpython-37m-darwin.so
       0x10a23d000 -        0x10a23dfff +_bisect.cpython-37m-darwin.so (0) <71551D1B-9A62-39B1-9E07-E8C2D2B122AA> /usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/lib-dynload/_bisect.cpython-37m-darwin.so
       0x10a240000 -        0x10a241ffb +_random.cpython-37m-darwin.so (0) <3EE21A2B-6164-3348-A3AC-9BE83DC846C0> /usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/lib-dynload/_random.cpython-37m-darwin.so
       0x10a284000 -        0x10a28cffb +_socket.cpython-37m-darwin.so (0) <0B427FFA-31A7-307B-8248-13D4ABFCD988> /usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/lib-dynload/_socket.cpython-37m-darwin.so
       0x10a297000 -        0x10a297fff +_opcode.cpython-37m-darwin.so (0) <8F956798-EE54-301E-9D96-448CC2296FD1> /usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/lib-dynload/_opcode.cpython-37m-darwin.so
       0x10a382000 -        0x10a4d5e87 +libcrypto.1.0.0.dylib (0) <96B06B4B-AF12-3701-BB9C-5FA206454D03> /usr/local/opt/openssl/lib/libcrypto.1.0.0.dylib
       0x10a94e000 -        0x10a97bff7 +_decimal.cpython-37m-darwin.so (0) <9797AF9F-922E-331A-80D6-145A362CFC40> /usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/lib-dynload/_decimal.cpython-37m-darwin.so
       0x10ae8e000 -        0x10be18ffb +libz3.dylib (0) <AB8AF963-B412-31A0-AF0F-876F98CCCF64> /Users/USER/*/libz3.dylib
       0x11895a000 -        0x1189c46ef  dyld (655.1.1) <F217F7F8-A795-3109-B77F-B1E2277F3E3B> /usr/lib/dyld
    0x7fff4c061000 -     0x7fff4c4a4fff  com.apple.CoreFoundation (6.9 - 1570.16) <F3DFF269-6705-35AD-9F01-66D77DD1B518> /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
    0x7fff74e94000 -     0x7fff74e95ffb  libDiagnosticMessagesClient.dylib (107) <B5675E8C-2F34-3E0A-B7E8-6F2373589038> /usr/lib/libDiagnosticMessagesClient.dylib
    0x7fff752d3000 -     0x7fff752d4ffb  libSystem.B.dylib (1252.250.1) <72841192-B0C9-36A0-8E55-ED651EADEF08> /usr/lib/libSystem.B.dylib
    0x7fff75508000 -     0x7fff75515fff  libbz2.1.0.dylib (38.200.3) <62019AC3-20C9-3DDC-9C83-189C1F258073> /usr/lib/libbz2.1.0.dylib
    0x7fff75516000 -     0x7fff75569ff7  libc++.1.dylib (400.9.4) <446DAE5E-4E97-3E4B-B2A3-AC0A74C0E453> /usr/lib/libc++.1.dylib
    0x7fff7556a000 -     0x7fff7557fff7  libc++abi.dylib (400.17) <A2D1FDAD-E10F-3E53-958F-CB6BC8485767> /usr/lib/libc++abi.dylib
    0x7fff7618c000 -     0x7fff763ecff3  libicucore.A.dylib (62123.0.1) <3936C798-1978-3C6C-9050-3BBD57CDA53E> /usr/lib/libicucore.A.dylib
    0x7fff76ccd000 -     0x7fff77452fdf  libobjc.A.dylib (756.2) <4F86FC7C-496B-3E68-8A74-1EA2BA22FBCC> /usr/lib/libobjc.A.dylib
    0x7fff77ba3000 -     0x7fff77bb5ff7  libz.1.dylib (70.200.4) <FDF169F3-F992-3E8E-B3F7-D4134FEBAE41> /usr/lib/libz.1.dylib
    0x7fff78392000 -     0x7fff78396ff3  libcache.dylib (81) <9A8C27B0-49C9-337F-8BE2-37171ED2D8EE> /usr/lib/system/libcache.dylib
    0x7fff78397000 -     0x7fff783a1ff3  libcommonCrypto.dylib (60118.250.2) <17C4F395-9FF0-331F-8167-5E85AA3588E9> /usr/lib/system/libcommonCrypto.dylib
    0x7fff783a2000 -     0x7fff783a9ff7  libcompiler_rt.dylib (63.4) <8CB2B2B6-2C55-3733-9842-0E037AE3F46A> /usr/lib/system/libcompiler_rt.dylib
    0x7fff783aa000 -     0x7fff783b3ff7  libcopyfile.dylib (146.250.1) <24905E41-9E2F-3DD1-A255-5A17F9FCDAD7> /usr/lib/system/libcopyfile.dylib
    0x7fff783b4000 -     0x7fff78438fc7  libcorecrypto.dylib (602.250.23) <3A6CBD41-AFFE-3E06-B1EC-3E95BC79BAC5> /usr/lib/system/libcorecrypto.dylib
    0x7fff784bf000 -     0x7fff784f8ff7  libdispatch.dylib (1008.250.7) <50235FCE-B399-3319-90DC-88F530D4FC5C> /usr/lib/system/libdispatch.dylib
    0x7fff784f9000 -     0x7fff78525ff7  libdyld.dylib (655.1.1) <54C6B494-4A3D-3EEC-B083-636A76AAD649> /usr/lib/system/libdyld.dylib
    0x7fff78526000 -     0x7fff78526ffb  libkeymgr.dylib (30) <BEA04E04-FCF1-3A70-810F-08D0FF54CA36> /usr/lib/system/libkeymgr.dylib
    0x7fff78534000 -     0x7fff78534ff7  liblaunch.dylib (1336.251.2) <30E6424E-4640-3DBA-9B64-D5F725263C6E> /usr/lib/system/liblaunch.dylib
    0x7fff78535000 -     0x7fff7853afff  libmacho.dylib (927.0.2) <D8515A20-ED7B-3B13-9ADA-4BD7E19E38C4> /usr/lib/system/libmacho.dylib
    0x7fff7853b000 -     0x7fff7853dffb  libquarantine.dylib (86.220.1) <8A9BF971-DB7D-311A-B131-6C5025E82F8F> /usr/lib/system/libquarantine.dylib
    0x7fff7853e000 -     0x7fff7853fff7  libremovefile.dylib (45.200.2) <950036B7-B91E-3B5D-853C-8C551E5B6A32> /usr/lib/system/libremovefile.dylib
    0x7fff78540000 -     0x7fff78557ff3  libsystem_asl.dylib (356.200.4) <16F632AD-FADA-3DE9-85E8-EBC7D619A1DA> /usr/lib/system/libsystem_asl.dylib
    0x7fff78558000 -     0x7fff78558ff7  libsystem_blocks.dylib (73) <0CD6861B-EC5F-3345-9C24-B21EEB85E44F> /usr/lib/system/libsystem_blocks.dylib
    0x7fff78559000 -     0x7fff785e0fff  libsystem_c.dylib (1272.250.1) <F3AA9047-EEDD-3D80-8CC1-023FB312EC8B> /usr/lib/system/libsystem_c.dylib
    0x7fff785e1000 -     0x7fff785e4ffb  libsystem_configuration.dylib (963.250.1) <02C7A973-014A-31D7-B7D2-247D384CB0D2> /usr/lib/system/libsystem_configuration.dylib
    0x7fff785e5000 -     0x7fff785e8ff7  libsystem_coreservices.dylib (66) <4CF1C89B-FA6C-3DF3-B1F8-79F549849534> /usr/lib/system/libsystem_coreservices.dylib
    0x7fff785e9000 -     0x7fff785effff  libsystem_darwin.dylib (1272.250.1) <6983A268-20F4-3F98-A3F5-D63848933B02> /usr/lib/system/libsystem_darwin.dylib
    0x7fff785f0000 -     0x7fff785f6ff7  libsystem_dnssd.dylib (878.250.4) <9FC5724C-DD03-3E14-A6E1-2DD009D79E0A> /usr/lib/system/libsystem_dnssd.dylib
    0x7fff785f7000 -     0x7fff78642ffb  libsystem_info.dylib (517.200.9) <F617D3CF-5A4A-36D0-8CBB-4A7C7CDB67AF> /usr/lib/system/libsystem_info.dylib
    0x7fff78643000 -     0x7fff7866bff7  libsystem_kernel.dylib (4903.251.3) <84EF0290-6CB5-36E5-A273-692A7E437B36> /usr/lib/system/libsystem_kernel.dylib
    0x7fff7866c000 -     0x7fff786b7ff7  libsystem_m.dylib (3158.200.7) <33105665-CCC3-36D5-82C9-9B21730CB3DF> /usr/lib/system/libsystem_m.dylib
    0x7fff786b8000 -     0x7fff786dcfff  libsystem_malloc.dylib (166.251.2) <90DA09E3-1276-3FCF-8F5F-C9AA61AB9B6D> /usr/lib/system/libsystem_malloc.dylib
    0x7fff786dd000 -     0x7fff786e7ff7  libsystem_networkextension.dylib (767.250.2) <4575D797-B793-3D18-9E93-8696CF0B133B> /usr/lib/system/libsystem_networkextension.dylib
    0x7fff786e8000 -     0x7fff786effff  libsystem_notify.dylib (172.200.21) <679E9132-1A46-326E-9A11-D3FF9C86041C> /usr/lib/system/libsystem_notify.dylib
    0x7fff786f0000 -     0x7fff786f9fef  libsystem_platform.dylib (177.250.1) <3CC59141-5365-3848-94C3-D65E6FCA1E74> /usr/lib/system/libsystem_platform.dylib
    0x7fff786fa000 -     0x7fff78704ff7  libsystem_pthread.dylib (330.250.2) <4344198A-A1A3-3C52-97B4-F168D56E9789> /usr/lib/system/libsystem_pthread.dylib
    0x7fff78705000 -     0x7fff78708ff7  libsystem_sandbox.dylib (851.250.12) <66E91015-F62A-3365-BB81-AA88707E8F12> /usr/lib/system/libsystem_sandbox.dylib
    0x7fff78709000 -     0x7fff7870bff3  libsystem_secinit.dylib (30.220.1) <F054DCB0-68CE-35E7-8B8C-D648C42124EC> /usr/lib/system/libsystem_secinit.dylib
    0x7fff7870c000 -     0x7fff78713ff3  libsystem_symptoms.dylib (820.257.1) <C8517F35-E9DA-3649-B07D-2B38349C6730> /usr/lib/system/libsystem_symptoms.dylib
    0x7fff78714000 -     0x7fff78729fff  libsystem_trace.dylib (906.250.5) <AE77ACC7-488F-3AE1-BB0C-1ACFC7E1CE77> /usr/lib/system/libsystem_trace.dylib
    0x7fff7872b000 -     0x7fff78730ffb  libunwind.dylib (35.4) <8F0BC197-B97C-3DDC-92B0-6A7D3CB72FD8> /usr/lib/system/libunwind.dylib
    0x7fff78731000 -     0x7fff78760ff7  libxpc.dylib (1336.251.2) <49138829-09C8-355C-B558-97E070B84EC5> /usr/lib/system/libxpc.dylib

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 40964
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=263.2M resident=0K(0%) swapped_out_or_unallocated=263.2M(100%)
Writable regions: Total=75.1M written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=75.1M(100%)
 
                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
Kernel Alloc Once                    8K        1 
MALLOC                            49.4M       19 
MALLOC guard page                   16K        4 
MALLOC_LARGE (reserved)            128K        1         reserved VM address space (unallocated)
STACK GUARD                          4K        1 
Stack                             16.0M        1 
VM_ALLOCATE                       9476K       18 
__DATA                            4784K       74 
__LINKEDIT                       225.4M       29 
__TEXT                            37.8M       70 
__UNICODE                          564K        1 
shared memory                       12K        3 
===========                     =======  ======= 
TOTAL                            343.3M      222 
TOTAL, minus reserved VM space   343.1M      222 

Model: MacBookPro15,1, BootROM 220.250.366.0.0 (iBridge: 16.16.4507.0.0,0), 6 processors, Intel Core i7, 2.2 GHz, 16 GB, SMC 
Graphics: kHW_IntelUHDGraphics630Item, Intel UHD Graphics 630, spdisplays_builtin
Graphics: kHW_AMDRadeonPro555XItem, Radeon Pro 555X, spdisplays_pcie_device, 4 GB
Memory Module: BANK 0/ChannelA-DIMM0, 8 GB, DDR4, 2400 MHz, Micron, 8ATF1G64HZ-2G6E1
Memory Module: BANK 2/ChannelB-DIMM0, 8 GB, DDR4, 2400 MHz, Micron, 8ATF1G64HZ-2G6E1
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0x7BF), wl0: Feb 21 2019 21:04:15 version 9.137.3.0.32.6.29 FWID 01-d837a364
Bluetooth: Version 6.0.11f4, 3 services, 27 devices, 1 incoming serial ports
Network Service: Wi-Fi, AirPort, en0
USB Device: USB 3.1 Bus
USB Device: iBridge Bus
USB Device: iBridge DFR brightness
USB Device: iBridge Display
USB Device: Apple Internal Keyboard / Trackpad
USB Device: Headset
USB Device: iBridge ALS
USB Device: iBridge FaceTime HD Camera (Built-in)
USB Device: iBridge
Thunderbolt Bus: MacBook Pro, Apple Inc., 34.6
Thunderbolt Bus: MacBook Pro, Apple Inc., 34.6

**Comment by NikolajBjorner** [comment]
typically this is because the path to the z3lib dll is pointing to a stale version.
It does not crash in the current master.
