### ISSUE TITLE
Recursive predicate occurs nested in the body of a rule

### ISSUE THREAD

**Issue by VictorCoder123** [Z3Prover/z3#2236]
I was using Pseudo Boolean constraints to express a constraint that at most one sub-constraint should be satisfied and an exception was thrown out saying recursive predicate occurs nested in the body of a rule, but I didn't see any recursive type definition in my example and I'm also wondering how to express in fixed point executor the cardinality constraint that check the number of instances of a datatype like `count({n | n = Node(str, metanode)}) < 2`. Thanks!

```python
MetaNodeDef = Datatype('MetaNode')
MetaNodeDef.declare('MetaNode', ('name', StringSort()))
MetaNodeDef = MetaNodeDef.create()
MetaNode = MetaNodeDef.MetaNode

NodeDef = Datatype('Node')
NodeDef.declare('Node', ('name', StringSort()), ('type', MetaNodeDef))
NodeDef = NodeDef.create()
Node = NodeDef.Node

NodePred = Function('NodePred', NodeDef, BoolSort())

fp = FixedPoint()
fp.fact(NodePred(Node('n1', mn1)))
fp.query(PbLe([(NodePred(Node(s1, symbmn1)), 1), (NodePred(Node(s2, symbmn2)), 1)], 1))
```

**Comment by NikolajBjorner** [comment]
The format for Horn clauses is fairly restricted, to, well, Horn clauses. 
So the predicate "NodePred" can only occur under and/or connectives. 
For this example, use the standard solver instead:

    s = Solver()
    s.add(NodePred(Node('n1', mn1)))
    s.add(Not(PbLe([(NodePred(Node(s1, symbmn1)), 1), (NodePred(Node(s2, symbmn2)), 1)], 1)))
    print(s.check())
