### ISSUE TITLE
Segmentation Fault (maybe because of quantified RoundingMode)

### ISSUE THREAD

**Issue by Heizmann** [Z3Prover/z3#2239]
Input: [double_req_bl_0240a_true-unreach-call.c-simplified.smt2.txt](https://github.com/Z3Prover/z3/files/3080170/double_req_bl_0240a_true-unreach-call.c-simplified.smt2.txt)
Command: z3 without additional arguments
Z3 version `b4ba44ce9d39b784a07d9b6a878193af03946219` (Sat Apr 13)

Unfortunately, this SMT script is not an exception. The new version of Ultimate Automizer supports the `fesetround` function and loves to produce formulas with quantified RoundingMode variables.

**Comment by NikolajBjorner** [comment]
It is model creation for rounding mode sorts. The current model construction only considers floating point numbers and not elements of the rounding mode sort.

**Comment by wintersteiger** [comment]
Interesting, all of this should be implemented, I'll take a look.

**Comment by wintersteiger** [comment]
Blatant omission on my part! Should be fixed now.
