### ISSUE TITLE
From `unsat` to `unknown` after adding trivial unrelated assertion?

### ISSUE THREAD

**Issue by mtzguido** [Z3Prover/z3#2240]
I am not completely sure this is a bug, but it looks very odd to me.

I am asking z3 to prove a simple assertion about the reals (`r*r = 0` implies `r = 0`), which works by itself, but when adding a seemingly unrelated assertion, z3 returns `unknown`.

The most minimal example I could construct is the following:
```smt2
(declare-fun F (Real) Int)

(assert (forall ((u0 Real)) (= 10 (F u0))))

(assert (not (forall ((r Real))
                 (implies 
                  (= (* r r) 0.0) 
                  (= r 0.0)
                 ))))
(check-sat)
(get-info :reason-unknown)
```

This returns
```
unknown
(:reason-unknown "smt tactic failed to show goal to be sat/unsat (incomplete (theory arithmetic))")
```

But removing the assertion about `F` makes it succeed with `unsat`. Also, tweaking the assertion sometimes makes it succeed. For instance writing `(= (F u0) (F u0))` instead of `(= 10 (F u0))`.

My z3 version is `Z3 version 4.5.1 - 64 bit - build hashcode 1f29cebd4df6`. And it also seems to happen with version 4.8.5 (commit eae4fd6afd29bddcfea4e7fa05a7a87788528883).

Is there something I'm missing or is this a bug?

**Comment by NikolajBjorner** [comment]
Thanks for pointing to this scenario.

Not really a bug: if the formula is purely over nonlinear reals it uses a decision procedure as a tactic. This decision procedure doesn't work with formulas that mix uninterpreted predicates/functions so it is disabled if the formula contains these.

**Comment by mtzguido** [comment]
Thanks Nikolaj! So what can one do in cases like this?

This came up from an F* query, using the relatively recent `FStar.Real` library that encodes to Z3's reals. In the actual query there are tons of axioms like this.
