### ISSUE TITLE
finding contraints that are difficult for solver

### ISSUE THREAD

**Issue by muqsitazeem148** [Z3Prover/z3#2243]
I have a SAT instance which is taking too long. There are many constraints in problem, and I was wondering if it is possible analyse which constraints are the ones where the solver takes more time.

Once I know the time-taking constraints, I can perhaps try a better encoding of them so that the solver come back faster.

I am using python API of z3 release version 4.8.3 compiled with --debug and --trace options.
Currently, I am using enable_trace(tag) using z3py to analyze the traces which dumps the trace in '.z3-trace'.

It produces an enormous amount of log, and I am unable to make a lot of sense of it. I was wondering if the logs can, in any way, point me to the constraints that are difficult for the solver.

**Comment by NikolajBjorner** [comment]
> I was wondering if it is possible analyse which constraints are the ones where the solver takes more time

Not sure what to say here. The time a solver spends depends not additively on constraints. There can be dependencies between constraints such that the overhead of solving a conjunction of constraints grows dramattically after adding some constraint. 

Debug mode slows down the solver so don't use that.

You could try something form outside akin to delta debugging: add a subset of constraints and determine if there is a phase change.
