### ISSUE TITLE
Segmentation Fault with Z3_mk_enumeration_sort

### ISSUE THREAD

**Issue by jrakow** [Z3Prover/z3#2245]
The following code crashes the current master:
```c
#include <stdio.h>
#include <z3.h>
#include <z3_version.h>

int main() {
	printf("%s\n", Z3_FULL_VERSION);

	Z3_context ctx = Z3_mk_context(Z3_mk_config());
	Z3_solver solver = Z3_mk_solver(ctx);
	Z3_symbol sort_name = Z3_mk_string_symbol(ctx, "instruction_sort");
	Z3_symbol instructions[] = {
		Z3_mk_string_symbol(ctx, "PUSH"),
		Z3_mk_string_symbol(ctx, "ADD"),
	};
	Z3_func_decl instruction_consts[] = { 0, 0 };
	Z3_func_decl instruction_testers[] = { 0, 0 };

	Z3_sort instruction_sort = Z3_mk_enumeration_sort(
		ctx,
		sort_name,
		2,
		instructions,
		instruction_consts,
		instruction_testers
	);

	printf("%s\n", Z3_solver_to_string(ctx, solver));
}
```
The output is
```
Z3 4.8.5.1 aafb16e master 
Segmentation fault (core dumped)
```
I compiled the snippet with
```
gcc repro.c -l z3 -Wall -Wextra
```
The GCC version string is `gcc (SUSE Linux) 7.3.1 20180323 [gcc-7-branch revision 258812]`.
I am on openSUSE Leap 15.0.

**Comment by NikolajBjorner** [comment]
Use the C++ API not the C API because it is error prone: your code isn't incrementing the reference count on the solver object.

**Comment by jrakow** [comment]
Thank you for the explanation.
When do I have to increment the ref count? Is that documented somewhere?

**Comment by NikolajBjorner** [comment]
In z3_api.h, 

A web version is here:
http://z3prover.github.io/api/html/group__capi.html#ga6339c11a9dc478400444cebd82847c2a
