### ISSUE TITLE
TryFor throws an exception when it timeout 

### ISSUE THREAD

**Issue by Ahmed-anwar** [Z3Prover/z3#2246]
```python
from z3 import *

file = "term-XbWQfu.smt2"
f = parse_smt2_file(file)
goals = Goal()
goals.add(f)

t = Tactic('sat')
g = t(goals)
print('First Tactic Passed')

tactic = TryFor(Then(Tactic('sat'), Tactic('sat')), 1)
t2 = Then(tactic, Tactic('sat'))
g2 = t2(goals)
print('Second Tactic Passed')
```

This example applies the first tactic but throws an exception while trying to apply the second tactic. Is this the intended behavior? My intuition was that a timeout while applying a tactic would have the same effect as 'skip'.
I attached the used smt2 file which is from the QF_NIA/Leipzig SMT-LIB benchmark.
[code_smt2.zip](https://github.com/Z3Prover/z3/files/3111034/code_smt2.zip)

I am working with python 3.7.0 and Z3 4.8.5

**Comment by NikolajBjorner** [comment]
Then(t1, t2) only executes if t1 succeeds. A timeout for t1 amounts to a failure so t2 does not get invoked and therefore the entire tactic fails.

**Comment by Ahmed-anwar** [comment]
@NikolajBjorner  thank you for your answer. To implement the same behavior  (skipping if a tactic timeout) I wrapped it by an OrElse(t, Tactic(skip)). I just want to confirm with you that this is what is actually happening in the same example:

```python
from z3 import *

file = "term-XbWQfu.smt2"
f = parse_smt2_file(file)
goals = Goal()
goals.add(f)

t = Tactic('sat')
g = t(goals)
print('First Tactic Passed\n')

# tactic = TryFor(Then(Tactic('sat'), Tactic('sat')), 1)
tactic = OrElse(TryFor(Then(Tactic('sat'), Tactic('sat')), 1), Tactic('skip'))
t2 = Then(tactic, Tactic('sat'))
g2 = t2(goals)
print('Second Tactic Passed')
```

**Comment by NikolajBjorner** [comment]
Right, the OrElse handles a failure (timeout/unknown) by the first tactic by running instead the second.
