### ISSUE TITLE
Z3py: 'pop operation is not supported' with Fixedpoint

### ISSUE THREAD

**Issue by LordGordonQ** [Z3Prover/z3#2249]
Hello,

I'm playing with Fixedpoint and I tried to use `push\pop` methods,  but with no success.

### Environment

* Z3 `4.8.4`
* Python `3.7.3`
* macOS `10.14.4`

### Code to replicate

```python
from z3 import *
s = Fixedpoint()
s.set(engine="datalog")

a = Bool('a')
b = Bool('b')

s.register_relation(a.decl())
s.register_relation(b.decl())

s.rule(b, a)

s.push()
s.fact(a)
s.pop()
```

### Unexpected behaviour

The trace of the error is:
```
---------------------------------------------------------------------------
Z3Exception                               Traceback (most recent call last)
<ipython-input-22-4ae0e0c38113> in <module>
     12 s.push()
     13 s.fact(a)
---> 14 s.pop()

/usr/local/lib/python3.7/site-packages/z3/z3.py in pop(self)
   7000     def pop(self):
   7001         """restore to previously created backtracking point"""
-> 7002         Z3_fixedpoint_pop(self.ctx.ref(), self.fixedpoint)
   7003 
   7004     def update_rule(self, head, body, name):

/usr/local/lib/python3.7/site-packages/z3/z3core.py in Z3_fixedpoint_pop(a0, a1, _elems)
   4000 def Z3_fixedpoint_pop(a0, a1, _elems=Elementaries(_lib.Z3_fixedpoint_pop)):
   4001   _elems.f(a0, a1)
-> 4002   _elems.Check(a0)
   4003 
   4004 def Z3_mk_optimize(a0, _elems=Elementaries(_lib.Z3_mk_optimize)):

/usr/local/lib/python3.7/site-packages/z3/z3core.py in Check(self, ctx)
   1344     err = self.get_error_code(ctx)
   1345     if err != self.OK:
-> 1346         raise self.Exception(self.get_error_message(ctx, err))
   1347 
   1348 def Z3_set_error_handler(ctx, hndlr, _elems=Elementaries(_lib.Z3_set_error_handler)):

Z3Exception: b'pop operation is not supported'
```
 
### Expected behaviour

`pop` call should revert to the previous backtracking point created with `push`. The behaviour is inconsistent as `push` allows to create a backtracking point.  Also, the API documentation seems those operation are supported: 
https://z3prover.github.io/api/html/classz3py_1_1_fixedpoint.html#a2765ae24bbf034397818f83ca80b836c

If I call `pop` without a previous `push`, I have the correct error: `there are no backtracking points to pop to`.

**Comment by agurfinkel** [comment]
push and pop on fixedpoint are not currently supported

**Comment by LordGordonQ** [comment]
> push and pop on fixedpoint are not currently supported

I see. Should the same error `Z3Exception: b'push operation is not supported'` be raised when calling the first `push` with Fixedpoint?

**Comment by NikolajBjorner** [comment]
I will be removing these from the API.

**Comment by NikolajBjorner** [comment]
I removed push/pop now.
