### ISSUE TITLE
QF_BV model contains bitblasted/intermediate CNF variables

### ISSUE THREAD

**Issue by maxzinkus** [Z3Prover/z3#2250]
Using a `SolverFor('QF_BV')` we're running into an issue where occasionally when we `check` and get `sat` we attempt to extract a value for a `BitVec` using `model` and get `0` (which isn't possible in what the constraints should allow).

Printing out the model, normally the bitvecs we've added constraints on show up, along with `long` values which represent valid instances from the solution space.

However, occasionally the model contains heaps of what look like CNF variables and values for them, e.g. `k!2984 : True`, and asking this model for one of our bitvecs gives back `0`.

In order to flesh this out further:
```
>>> s = SolverFor("QF_BV")
>>> p = BitVec('p', 128)
...snip: adding constraints...
>>> s.check() == sat
True
>>> m = s.model()
>>> m[p]
0
>>> m[p].as_long()
0
>>> s.add(p == 0)
>>> s.check() == sat
False
```
and
```
>>> s = SolverFor("QF_BV")
>>> p = BitVec('p', 128)
...snip: adding constraints...
>>> s.check() == sat
True
>>> m = s.model()
>>> m[p]
0
>>> m[p].as_long()
0
>>> s.add(p != 0)
>>> s.check() == sat
True
>>> m = s.model()
>>> m[p]
<some large integer value which seems correct>
```

**Comment by maxzinkus** [comment]
How can I aid debugging this?

Is there any way this could be caused by instantiating solvers in many different python processes via the `multiprocessing` package?

**Comment by NikolajBjorner** [comment]
1. Some self-contained repro steps would be helpful. Maybe the conversion of p == 0, when p is a 128 bit value isn't what meets the eye.
2. You definitely don't want to solvers that use the same default context in different threads. The way to use solvers from different threads is to use independent context objects. Functions, such as SolverFor, BitVec, take an optional context argument. You want the threads to own their own context.

**Comment by maxzinkus** [comment]
I’ll try to provide a cnf and some steps. Note that these are separate processes, and explocit context object creation and passing doesn’t seem to resolve the issue.

Will update soon, thanks!

**Comment by maxzinkus** [comment]
Unfortunately the issue is happening nondeterministically. This is what the problematic model looks like:

```
[k!1408 = True,
 k!1409 = False,
 k!1410 = False,
 k!1411 = False,
 k!1412 = False,
 k!1413 = False,
 k!1414 = False,
 k!1415 = False,
 k!1416 = True,
 k!1417 = False,
 k!1418 = True,
 k!1419 = True,
 k!1420 = True,
 k!1421 = False,
 k!1422 = False,
 k!1423 = False,
 k!1424 = True,
 k!1425 = False,
 k!1426 = True,
 k!1427 = True,
 k!1428 = False,
 k!1429 = True,
 k!1430 = True,
 k!1431 = True,
 ...]
```
As opposed to a normal one (`p`, `m1_1`, ... are the names we gave our bitvectors):
```
[m2_2 = 228733977504339017458713940499083367169,
 p = 43864523860902303339260486753410163459,
 m1_2 = 81799956163601860118722388322993840385,
 m1_4 = 158990754301321798419472954575326552321,
 m2_1 = 301310571174447745862030356419651635969,
 m1_0 = 175799209739612188504683518175255535873,
 m2_0 = 331102559439136631432531871817953289985,
 m1_1 = 149465447456120739404831403038664688130,
 m1_3 = 4292187207281697759489,
 m2_3 = 195813445956683982961554897977700026625,
 m2_4 = 319098124867226054774358560444634170629]
```

**Comment by maxzinkus** [comment]
`bad.cnf.txt` is the one wherein the z3 model created a strange model, and `bad.out.txt` is the result of processing this CNF using `z3` on the command line. `good.cnf.txt` is the same solver dumped to CNF after `p != 0` was added, and `good.out.txt` similar.

[bad.cnf.txt](https://github.com/Z3Prover/z3/files/3135478/bad.cnf.txt)
[bad.out.txt](https://github.com/Z3Prover/z3/files/3135479/bad.out.txt)
[good.cnf.txt](https://github.com/Z3Prover/z3/files/3135480/good.cnf.txt)
[good.out.txt](https://github.com/Z3Prover/z3/files/3135481/good.out.txt)

**Comment by maxzinkus** [comment]
Any thoughts on what might be causing what looks like a model full of intermediate bitblasted variables?

**Comment by NikolajBjorner** [comment]
The cnf files aren't helpful to identify the issue with private variables being exposed.
The private variables should have been removed by layers that track where they were introduced while processing bit-vector inputs.

**Comment by NikolajBjorner** [comment]
labeling as no-repro as the attached files don't produce the issue
