### ISSUE TITLE
Linker errors on OSX

### ISSUE THREAD

**Issue by kmicinski** [Z3Prover/z3#2254]
When building on OSX, I get a ton of linker errors along the lines of...

```
ld: warning: ld: warning: ld: warning: ignoring file opt/opt.a, file was built for archive which is not the architecture being linked (x86_64): opt/opt.ald: warning: ignoring file api/api.a, file was built for archive which is not the architecture being linked (x86_64): api/api.a
```

and then the build crashes.

This happens across multiple accounts on my Mac, leading me to believe that clang or command-line tools must be set up wrong. However, the build instructions don't really seem helpful at articulating how I can debug this.

To set up Z3 I did:

```
CXX=clang++ CC=clang python scripts/mk_make.py
```

So I would have thought I would be covered by the correct linking flags.

Any hints as to how to set this up?

**Comment by agurfinkel** [comment]
Try using cmake build system. It works well for me on OSX

In the source directory,
```
mkdir build ; cd build ; cmake ../ -GNinja ; ninja
```

Use `cmake -L ../` to see available build options.

**Comment by kmicinski** [comment]
Unfortunately this is unacceptable, since it doesn't build the ML bindings for Z3.

**Comment by kmicinski** [comment]
(I can confirm, though, that the cmake build properly terminates on my OSX now! Just not the custom mk_make.py)

**Comment by kmicinski** [comment]
(I can confirm that it does build with cmake :-) )

**Comment by NikolajBjorner** [comment]
Are these completely clean builds? (consider for example what happened for https://github.com/MoarVM/MoarVM/issues/334) 
Suppose you built using gcc before, then old versions of archives may be sticking around. I am not familiar with this error and have built using clang on MacOS routinely.

**Comment by kmicinski** [comment]
I agree with you. It does appear that that's the case. And yet they are clean builds. I will note that a clean cmake build does work. I suspect the problem is that there is something a bit wonky in my system setup that's not correctly being picked up my mk_make.py.

**Comment by NikolajBjorner** [comment]
Maybe mk_make.py uses environment variables that contain links to other builds?

**Comment by kmicinski** [comment]
this was a fresh git pull on a machine that had never had z3 built (z3
builds correctly with an older version on another OSX machine). Same thing
when I create a new user account on the same machine.

**Comment by NikolajBjorner** [comment]
so that should rule out the "dirty" build scenario.
The other factor that seemed sticking out is the x64 dependencies, 
but the MacOS build doesn't have any specific configuration for architectures.
We do build on MacOS during every check-in, but without the clang options.
I have built using clang on our own Mac, which uses an up-to-date MacOS.

The mk_make script creates a makefile, the makefile is the "ground" truth regarding clang. 
If you are able to use the makefile to identify what is the configuration issue with respect to your environment it could help.

**Comment by agurfinkel** [comment]
perhaps some more information on the error might help us diagnose what is going on. What does `mk_make.py` prints when it identifies the system. Perhaps it identifies the compiler as 32 bit? Also check the produced archives (e.g., `file NAME.a`), to see what architecture they are compiled for. Is that 32 vs 64 bit issue or something else...

**Comment by kmicinski** [comment]
I remember looking and checking to see that the build was configured for x86_64, rather than a 32-bit build. However, I will look into this more systematically and come back with something concrete for you all, pointing out the configuration options from `mk_make.py` and after digging through the generated makefile for a while.

**Comment by kmicinski** [comment]
Hi everyone.

Sorry for taking so long to follow up on this. The problem ended up being that `binutils`--when installed via Mac OSX's Homebrew system--breaks current OCaml builds. This means that you (essentially) have to either reinstall Homebrew (and all your packages) from scratch, or `brew unlink binutils` (which can potentially damage other apps, I believe, so you may need to relink).

More information can be found in these two github issues:
https://github.com/ocaml/opam-repository/issues/13008
https://github.com/ocaml/opam/issues/3650

**Comment by NikolajBjorner** [comment]
thanks for sharing the information. Sorry for this situation.

**Comment by kmicinski** [comment]
Not your fault. I appreciate all of the discussion! I eventually got to the point where my native and ocaml builds were consistently failing for obscure and hard-to-diagnose reasons. Thanks!
