### ISSUE TITLE
Can't install on Win10 or MacOS

### ISSUE THREAD

**Issue by MarynaLongnickel** [Z3Prover/z3#2255]
Trying to install on Win 10, i get `MSBUILD : error MSB1003: Specify a project or solution file. The current working directory does not contain a project or solution file.`
Running `python mk_make.py` (-x or no -x) ... returns `Python bindings directory 'src\\api\\python' does not exist`
Trying on MacOS, i get `No rule to make target 'install-z3py`

**Comment by NikolajBjorner** [comment]
I have been trying to reproduce these scenarios, but I am not able to really understand what commands you have tried to reach these error messages. 
A few comments:

- Don't run mk_make.py in the python sub-directory. Run it in the directory below. That is, run it in the directory that contains "src" and "scripts". So run "python scripts/mk_make.py". This may explain the error message.
- There is no "install" directive for the python build under Windows. There is an install directive for the cmake build system. If you install cmake on your machine (and Ninja) I can recommend this for building Z3. It creates a script to also install binaries in directories that you can specify. See the README-cmake.txt file for details.
- For Linux (I only have a linux shell locally to play with here), the python build works with the install directive just fine.

**Comment by MarynaLongnickel** [comment]
I'm pretty much just trying `pip install z3-solver`, even tried it jupyter notebook on docker, but still keep getting:
```
    ld: symbol(s) not found for architecture x86_64
    clang-4.0: error: linker command failed with exit code 1 (use -v to see invocation)
    make: *** [z3] Error 1
    error: Unable to build Z3.
```

**Comment by NikolajBjorner** [comment]
The pip installer is by angr, https://pypi.org/project/z3-solver/
They suggest to file issues on https://github.com/angr/angr-z3
I know it would be better to have an official pip package, but I lack bandwidth and competence to create a package.

**Comment by NikolajBjorner** [comment]
The z3-solver pip package was just updated. I hope it helps.
