### ISSUE TITLE
Segfault when mixing arrays and recursive datatypes

### ISSUE THREAD

**Issue by Calvin-L** [Z3Prover/z3#2256]
I am running Z3 4.8.4 on MacOS:

```
$ z3 --version
Z3 version 4.8.4 - 64 bit
```

This tiny input causes a segfault:

```
(define-sort Set (T) (Array T Bool))

(declare-datatypes ((Value 0)) (
  ((VBool (bool-value Bool))
   (VSet (set-value (Set Value))))))

(declare-const set  Value)
(declare-const elem Value)
(assert (is-VSet set))
(assert (select (set-value set) elem))

(check-sat)
(get-model)
```

```
$ z3 input.smt2 
Segmentation fault: 11
```

**Comment by NikolajBjorner** [comment]
This kind of datatype declaration should have been rejected. It isn't in the class of datatypes handled by the decision procedure as "Value" appears in the contra-variant position of the array type.

**Comment by Calvin-L** [comment]
Ah, I see. Thanks for clarifying!

Since this input is invalid, an error message at typechecking time would be much more useful.

**Comment by shiatsumat** [comment]
Even if the recursion is covariant, segfault occurs. https://github.com/Z3Prover/z3/issues/2297
```
$ ./z3 -in
(declare-datatype Box (par (T) ((box (unbox T)))))
; ok (declare-datatype Lst (par (T) ((nil) (cons (hd (Box T)) (tl (Lst T))))))
(declare-datatype Lst (par (T) ((nil) (cons (hd T) (tl (Box (Lst T)))))))
Segmentation fault: 11
```
