### ISSUE TITLE
Logo Design for Z3

### ISSUE THREAD

**Issue by zuurw** [Z3Prover/z3#2259]
Hi, how are you? I'd like to collaborate on your open source project and propose free logo/icon design for this project. If it's something you're interested in, please, let me know!
Best Regards
Zuur

**Comment by NikolajBjorner** [comment]
It's a valid point that the Z3 "logo" is barely a logo. Dejan Jovanovich at some point replaced our screen-capture from a power-point slide by SVG text, sources of which I am not in a position to locate. Maybe Jasmin Blanchette has a drawing somewhere that would be fun, or he is waiting for higher-order refinement-type Z3 so he can suggest a "horz3" logo (horse, in case my use of 3 for "e" was ambiguous). 
I should really have invoked the vast marketing department in my compancy (it is a software company in the operating systems and productivity space) a long time ago to come up with something less amateurish.
