### ISSUE TITLE
z3 C++ API function push and check_error

### ISSUE THREAD

**Issue by gspeiliu** [Z3Prover/z3#226]
I am using the C++ API. I want to set a backtrack point in my code, so I used the function of push. My code segment is as follow:
/*****************code start***************/
std::cerr << z3_solver << std::endl; // z3_solver is a solver of the C++ API object. This statement print out            
                                                        //   all the constraints that I want to use z3 to solver.
z3_solver.push();	//backtrack 1. I want to use the statement to make a backtrack point. But I got an 
                                // error.
/***************code end****************/

The error is like this:
terminate called after throwing an instance of 'z3::exception'
The error stack's last statement is : z3::context::check_error() const + 122.
I know that this error happened in the function push after calling function of check_error, I want to know the function of check_error how to get an exception. Thank you.

**Comment by wintersteiger** [comment]
`check_error()` will thrown an exception of type z3::exception when something goes wrong. To get an idea of what has gone wrong, could you try catching that exception and then print the exception message (via `z3::exception::msg()`)?

**Comment by gspeiliu** [comment]
Thanks you, the exception show us "out of memory", that's means the z3 solver can solve finite constraints, my constraints is more to the solver's ability?

**Comment by wintersteiger** [comment]
Yes, an out of memory exception means Z3 has exhausted all available memory, so it gives up and throws an exception.

**Comment by wintersteiger** [comment]
Closing as resolved.
