### ISSUE TITLE
Goal not in unsat core

### ISSUE THREAD

**Issue by GerhardSchellhorn** [Z3Prover/z3#2261]
Sorry for forgetting to add the goal in the last issue. The crash is gone but the problem, that the two axioms + the goal give an unsat-core which does not include the goal still persists.
Here is the file again, this time with the goal:

(set-option :smt.auto-config false) ; disable automatic self configuration
(set-option :smt.mbqi false) ; disable model-based quantifier instantiation
(set-option :smt.ematching true) ; enable ematching
(set-option :smt.macro-finder true)
(set-option :smt.pull_nested_quantifiers false)

;; setting auto-config to true (and removing the rest of the options above)
;; gives the same result

(set-option :unsat_core true)
(set-option :timeout 50)

;;;sorts
(declare-sort elem)

;;;lists
(define-sort list () (Seq elem))

;;;operations
;; membership test
(declare-fun inset (elem list) Bool)

;;;axioms

;; a in x <-> seq.contains(seq.unit(a),x)
(assert (!
  (forall ((a elem) (x list))
           (!
                     (= ; <->
           (inset a x)
           (seq.contains (seq.unit a) x)
        )
           :pattern (inset a x)
           ))
     :named elem-def))

;; x = seq.empty <-> not exists a. a in x
(assert (! (forall ((x list))
                            (= ; <->
           (= x (as seq.empty (Seq elem)))           
           (not (exists ((a elem)) (inset a x)))

        )) :named list--some-element))

;; a in cons(b, x) <-> a = b or a in x
(assert (! (not (forall ((a elem) (b elem) (x list))
        (= ; <->
           (inset a (seq.++ (seq.unit b) x))
           (or (= a b) (inset a x))
        ))) :named goal))

(check-sat)
;(get-unsat-core)

**Comment by NikolajBjorner** [comment]
Note the semantics of "contains", is provided informally on https://rise4fun.com/Z3/tutorial/sequences, an in formaleze in SMT-LIB string proposals:
     
                 (seq.contains s sub) | Does s contain the sub-sequence sub?

Thus, when you write 

            (seq.contains (seq.unit a) x)

It means that (seq.unit a) contains x, not the other way around.

If you flip the order, the unsat core is as expected to contain both elem-def and goal, but not list--some-element.

**Comment by GerhardSchellhorn** [comment]
Ah, I see, apologies for being too dumb to notice this.
