### ISSUE TITLE
Eval of array extensionality term doesn't get reduced to true or false

### ISSUE THREAD

**Issue by dbueno** [Z3Prover/z3#2267]
I am using the C++ API of Z3 4.6.0 to write a model checker. Profiling shows that my inner loop spends 50% or more of its time inside z3::model::eval(e). For a given model, I call eval() many times, but never for the same expression twice.

The code for model::eval() constructs a model_evaluator and rewrites e in a loop. The model_evaluator seems to cache intermediate rewrites. Unfortunately, when model.eval() returns, the cache is thrown away.

What's the simplest way to speed up multiple eval()s?

I figured that the way would be to define a new type in the C++ API, z3::model_evaluator, that would use the existing evaluation engine under the hood. I started doing this by following the Z3 pattern -- defining a C-land datatype, Z3_model_evaluator, working my way toward defining a new class for model evaluators.

This approach seems doable but has a lot of boilerplate that's going to take some time.

Is there a simpler way I can drive down the cost of calling eval() many times? Or perhaps an alternative to eval()?

[BTW, I'm using Z3 4.6.0 because the latest release doesn't evaluate array extensionality terms completely. I can reproduce this easily in my benchmarks, but so far have had a hard time reproducing it with a simple testcase.]

**Comment by dbueno** [comment]
I had an idea to just embed an evaluator into each model, rather than exposing it. The diff is here: https://github.com/Z3Prover/z3/compare/z3-4.6.0...dbueno:model-evaluator-4.6.0

**Comment by NikolajBjorner** [comment]
For newer versions of Z3, the model evaluator is cached inside the model object. 
Thus, if you have to stay with 4.6 for now, then another way to do this is to create a pointer to a model evaluator inside the model object, and allocate it on demand.

However, I can't maintain down-level versions of Z3. Better to resolve the extensionality problem.

**Comment by dbueno** [comment]
I was able to reproduce. I would expect the eval to give me true or false, but it gives a term with lambdas. This is with Z3 4.8.5 commit 16af728fbe0cb3fd7583d921fea9b545f42591b8.

SMT2 File: https://gist.github.com/dbueno/3c5094ed91f80c4dd11a681b56719332

**Comment by NikolajBjorner** [comment]
this is different from extensionality. I am trying to address both issues in the latest push.

**Comment by dbueno** [comment]
This resolves my issue, thank you!
