### ISSUE TITLE
Does Z3 support evaluating quantified formulae in a model?

### ISSUE THREAD

**Issue by wilcoxjay** [Z3Prover/z3#2269]
Empirically, it appears that Z3 does not fully support evaluating quantified formulae in models:

```
(declare-sort S)
(declare-fun R (S) Bool)
(declare-const x S)

(assert (R x))

(check-sat)
(get-model)                      ; prints a model with only one element in sort S
(eval (forall ((z S)) true))     ; prints true
(eval (forall ((z S)) (= z x)))  ; prints symbolic expression
```

I would either expect both `eval` commands to print `true`, or for both of them to print a quantified symbolic answer. 

What is the correct way to think about eval? Is it supposed to handle quantifiers or not? If yes, what is going on above? If not, how hard would it be to add support? If the answer is somewhere between yes and no, how can I predict when eval will succeed in returning a non-symbolic answer for a formula?

As an indication that such evaluation should be possible in principle, here is a Python implementation that evaluates the specific quantifier on the last line above by iterating through the domain of `S` in the model:

```
#!/usr/bin/env python3
import z3

S = z3.DeclareSort('S')
R = z3.Function('R', S, z3.BoolSort())
x = z3.Const('x', S)

s = z3.Solver()

s.add(R(x))

s.check()
m = s.model()

print(m)

z = z3.Const('z', S)
print(m.eval(z3.ForAll(z, z3.BoolVal(True))))  # prints True despite quantifier
print(m.eval(z3.ForAll(z, z == x)))            # prints symbolic expression

# Manually evaluating the above expression.
print(all(m.eval(c == x) for c in m.get_universe(S)))
```

**Comment by NikolajBjorner** [comment]
The "eval" function substitutes values for uninterepreted constants in expressions, it then performs basic simplification to perform constant folding. It does not attempt to evaluate quantifiers even though these would be closed. Loops over finite domains is only possible for quantifiers with small domains, and the simplifier doesn't consider this option either.

**Comment by wilcoxjay** [comment]
Okay, thanks!
