### ISSUE TITLE
solver internals: implication axioms not being asserted to the solver

### ISSUE THREAD

**Issue by mtrberzi** [Z3Prover/z3#227]
(background: I am a software engineering Master's student at the University of Waterloo under the (co-)supervision of Vijay Ganesh. In collaboration with Yunhui Zheng (IBM Research) we are developing a new version of the Z3str2 string solver. The previous implementation of Z3str2 was built against a now-obsolete version of Z3 and relies on some hacks because it had to be built totally outside the main codebase. This version of the string solver is being developed as a first-class theory plugin within the latest version of Z3.

So far my efforts in porting this code have been successful, although I am far from being done with the initial implementation. I am working on my code in the 'develop' branch at [my fork of Z3](https://github.com/mtrberzi/z3). I plan to create a pull request once the basic solver is ready and has been tested carefully.)

While developing the string theory plugin, I ran into an interesting bug related to asserting theory axioms. I found that implications that are asserted with `get_context().mk_th_axiom()` are totally ignored by the core solver. This is best shown with a short example. I want to assert the implication `(Concat X Y) == "" -> X == ""`. (In other words, if the concatenation of X and Y is equal to the empty string, then X must also be equal to the empty string.) Here's the code that I'm using to generate the axiom:

```
expr_ref premise(ctx.mk_eq_atom(concat, emptystr), m);
expr_ref conclusion(ctx.mk_eq_atom(x, emptystr), m);
expr_ref axiom(m.mk_implies(premise, conclusion), m);
```

Then I assert `axiom` with the following, which I believe is borrowed from theory_fpa:

```
void theory_str::assert_axiom(expr * e) {
    if (get_manager().is_true(e)) return;
    context & ctx = get_context();
    if (!ctx.b_internalized(e)) {
        ctx.internalize(e, true);
    }
    literal lit(ctx.get_literal(e));
    ctx.mark_as_relevant(lit);
    ctx.mk_th_axiom(get_id(), 1, &lit);
}
```

When I later display the entire set of assignments (in `final_check_eh`), I can see the axiom I've asserted among them. However, I also noticed that the solver can enter a state where it believes the truth of A, A->B, and not(B) simultaneously. In this case I can add the assertions `(= (Concat X Y) "")` and `(not (= X ""))` to the initial instance, see that the axiom `(=> (= (Concat X Y) "") (= X ""))` is correctly generated, and then see that the solver simultaneously believes that all three of these facts are true.

I can modify the premise and conclusion to be anything I want and the solver will still accept it regardless of what other facts it believes. I can even assert the implication (=> true false) as an axiom in this fashion and the solver will still return SAT.

The fix I am using right now is to instead use the following representation for my axiom:

`expr_ref axiom(m.mk_or(m.mk_not(premise), conclusion), m);`

which is equisatisfiable with `(=> premise conclusion)`. This gives the expected result.

**Comment by wintersteiger** [comment]
Would you have a small test input that reliably reproduces the problem and a commit hash for the version of your code that triggers it? 

(Just for reference: theory_fpa::assert_cnstr is a copy of theory_dl::assert_cnstr, and theory_fpa currently handles uninterpreted functions very crudely, don't copy too much of those parts :-))

**Comment by mtrberzi** [comment]
Sorry for the late response on this -- grant proposal deadlines, etc. 

The commit with hash `5fe129b` in mtrberzi/z3, on the `develop` branch, definitely has this bug. I've put this in its own branch, `implication-bug` in the same repository, for quick access.

I've pushed, in the latest commit to `implication-bug`, a file `test.smt` that contains a test case revealing this bug. Model generation is not working in this branch, so an assertion will fail after final check, but compile with tracing enabled and run with `-tr:t_str -tr:t_str_detail` to see the strange output I saw.

In detail, in `final_check_eh` I dump all assignments, and notice the solver has entered a state where it thinks all of the following are true:

```
-------- [t_str_detail] final_check_eh ../src/smt/theory_str.cpp:632 ---------
dumping all assignments:
(= (Concat X Y) "")
(=> (= (Concat X Y) "") (= (Length "") (Length (Concat X Y))))
(=> (= (Concat X Y) "") (and (= X "") (= Y "")))
(>= (Length (Concat X Y)) 0)
(= (= (Concat X Y) "") (= (Length (Concat X Y)) 0))
(>= (Length X) 0)
(= (= X "") (= (Length X) 0))
(>= (Length Y) 0)
(= (= Y "") (= (Length Y) 0))
(= (Length "") 0)
(= (Length (Concat X Y)) 0)
(<= (Length (Concat X Y)) 0)
(= (Length "") (Length (Concat X Y)))
(not (= (Length X) 0))
(not (<= (Length X) 0))
(not (= X ""))
(not (and (= X "") (= Y "")))
(not (= Y ""))
(not (= (Length Y) 0))
(not (<= (Length Y) 0))
------------------------------------------------
```

Of note, the following excerpt:
```
(= (Concat X Y) "")
(=> (= (Concat X Y) "") (and (= X "") (= Y "")))
(not (= X ""))
(not (and (= X "") (= Y "")))
(not (= Y ""))
```

The assertion `(=> (= (Concat X Y) "") (and (= X "") (= Y "")))` is an axiom, which is added in `smt/theory_str.cpp:382`.

**Comment by NikolajBjorner** [comment]
Seems as if you should follow how axioms are added elsewhere in the Z3 code and not follow the untested code in dl and fp. Normally you internalize atomic formulas into literals, a clause is a disjunction of literals. So in this case you should pass a vector for signed atoms to a procedure that internalizes them and creates corresponding literals. Then when you call mk_th_axiom pass the list of literals.

**Comment by NikolajBjorner** [comment]
I have updated theory_dl to use mk_th_axiom appropriately. Other code should also do it. The smt_internalizer assumes that expressions have been normalized, and does not handle implication expressions.
