### ISSUE TITLE
Accelerate model finding in SAT solver

### ISSUE THREAD

**Issue by rainoftime** [Z3Prover/z3#2272]
It seems that some heuristics in CDCL solver can perform better on satisfiable instances. Suppose we have a set of SAT instances (e.g., bit-blasted from bit-vector constraints), and most of them tend to be satisfiable.  Is there any suggestion for configuring the SAT engine to improve its empirical performance? (E.g., the restarting strategy, branching heuristics,  and in-processing algorithms). 

Thank you!

**Comment by NikolajBjorner** [comment]
Generally a question that is attracting attention.
You can try to disable/delay restarts. 
Enabling several threads tends to help on satisfiable instances.
The csp branch includes some other improvements that are good for at least some satisfiable instances, such as chronological backtracking.
