### ISSUE TITLE
How can I get a small model from theory_arith?

### ISSUE THREAD

**Issue by diepbp** [Z3Prover/z3#2279]
I am trying to write a custom string theory for z3. My current problem is that the satisfying model returned by theory_arith is large, e.g. satisfying lengths of string variables, which are non-negative int variables, are unnecessarily large (around 10k). Therefore satisfying values of string variables are unnecessarily long. Constructing long strings will take much time in my implementation, so I prefer to get small satisfying values from theory_arith.

Are there any available flags that guide theory_arith prioritize searching for a smaller model, or any mechanism in z3 allow me to acquire that aim?

Thanks,
Diep

**Comment by NikolajBjorner** [comment]
The arithmetic theory only produces large numbers if it is tricked into a satisfying state where large values are required. The theory_recfun and theory_seq use a technique of interative deepenening for creating progressively weaker bounds. This is a general technique that can be useful for establishing small finite models if they exist. So my suggestion is to bound string lengths and progressively increase (e.g., double) the lengths if there are no small models (and the cores depend on the small bounds).
