### ISSUE TITLE
Fixedpoint C++ API: what's the correct way of declaring vars?

### ISSUE THREAD

**Issue by leonardoalt** [Z3Prover/z3#2282]
I declared consts, and following https://github.com/Z3Prover/z3/issues/1832 tried:
```
expr rule_fb1 = forall(x_0, y_0, a_0, implies(fentry(), b1(x_0, y_0, a_0)));
s.add_rule(rule_fb1, rule_fb1.decl().name());
```
but then I get the runtime error
```
chc: /usr/include/z3++.h:891: z3::expr::operator Z3_app() const: Assertion `is_app()' failed.
Aborted (core dumped)
```
Should I not use `add_rule` in that case? Or what would be the correct way?

**Comment by agurfinkel** [comment]
I think the problem is that `rule_fb1` is a quantified expression and not an app. Hence `.decl()` fails on it. Use `str_symbol()` to create a name for the rule instead.

**Comment by leonardoalt** [comment]
Indeed, my bad.
It works now, thanks @agurfinkel !
