### ISSUE TITLE
How do I execute the .cpp file? 

### ISSUE THREAD

**Issue by HarishUth** [Z3Prover/z3#2284]
I did all the required downloads and cloning to install z3 into my PC. What are the commands to execute the cpp file?
![Screenshot from 2019-05-16 13-31-11](https://user-images.githubusercontent.com/45685124/57836733-fba74800-77de-11e9-858e-933645f92d0e.png)

I created a new CPP file in the z3 directory.
can you please tell me the commands that compile and execute the file on LINUX?

**Comment by NikolajBjorner** [comment]
Based on the question seems you don't have experience with building cpp files for other projects either.
Therefore, one option is read the README-cmake.txt and build the cpp_examples. Then build your own examples using similar methods.
