### ISSUE TITLE
[Feature Request] Improving API Z3_mk_string and Z3_get_string.

### ISSUE THREAD

**Issue by carstimon** [Z3Prover/z3#2286]
The API for Z3_mk_string and Z3_get_string performs escaping of characters.  So, if my program that uses Z3 passes it the string representing two backslashes, the object returned represents only one backslash.  Similarly, it's surprising that getting the C string value from a string term with length one can give me a C string with length two.  Users have to reimplement the escaping in reverse to use the API correctly, unless they happen to want "escaped" strings directly.

Can we add an argument or another function to get the strings represented directly, instead of escaped?
Also, it would be convenient to have versions with (char *, length) or, in the C++ api, returning std::string, so we could have null bytes.

**Comment by NikolajBjorner** [comment]
Yes, but per smtlib proposal it or a different function will have to also support unicode.

**Comment by NikolajBjorner** [comment]
Do the added functions work for your use?

**Comment by carstimon** [comment]
Thanks Nikolaj, this looks great!

From my point of view, this does support unicode- the unicode string can be passed as a plain byte array.  The only thing is that then length and regex character sets are with respect to byte length :)

**Comment by pointhi** [comment]
I would need this for java as well, but do not see any API reference for it yet.

**Comment by NikolajBjorner** [comment]
Could you suggest what the API function should be?
The existing one for creating strings is:

    /**
     * Create a string constant.
     */
    public SeqExpr mkString(String s) 
    {
        return (SeqExpr) Expr.create(this, Native.mkString(nCtx(), s));
    }

**Comment by pointhi** [comment]
I talk about getting the value back from the model. I have some tests which try to write some strings into z3 and extract them from the model again. It fails miserably with unicode, but even with control characters:

```java
    @Test
    public void newlineTest() {
        Context ctx = new Context();

        String input = "\n";
        Assert.assertEquals(input, ctx.mkString(input).getString());

        ctx.close();
    }
```

```
stringTest: FAILED
stringTest(***.z3.tests.SmokeTest)
org.junit.ComparisonFailure: expected:<[
]> but was:<[\n]>
```

even more problematic, ```\n``` and ```\\n``` returns the same value:

```
    @Test
    public void shouldNotWorkTest() {
        Context ctx = new Context();

        Assert.assertEquals("\\n", ctx.mkString("\n").getString());
        Assert.assertEquals("\\n", ctx.mkString("\\n").getString());

        ctx.close();
    }
```

Unless, I use the API in a wrong way, this means Strings are not properly defined using the java interface. Actually, z3 should never try to escape strings, and simply return the internal representation. Otherwise every user needs to write a parser for escaped string constants.
