### ISSUE TITLE
Z3 string theory inconsistency

### ISSUE THREAD

**Issue by agacek** [Z3Prover/z3#2288]
Build: `z3-4.8.5.e0c3b4a77d3c-x64-osx-10.11.6` using the default `seq` string solver.

Z3 returns an invalid model on this file: https://gist.github.com/agacek/ed139c5e71ee2a5ad2949a51e5ace306

In particular the variable `p0.0.resource` is reported as `false` even though it's asserted equal to an expression which evaluates to `true`.

**Comment by NikolajBjorner** [comment]
I am not getting a repro yet

**Comment by varming** [comment]
I got a repro on OSX with both the product and debug build of https://github.com/Z3Prover/z3/commit/f989e4eb389ccc2fd86dca8acd8ea76f4ced946e

**Comment by NikolajBjorner** [comment]
Can you say something more about how you see the discrepancy?

Here is what I get when asserting p0.0.resource to false:


(assert (not p0.0.resource))
 
(check-sat)
(eval (= "arn" resource_prefix))
(eval (= "aws" resource_partition))
(eval (= "s3" resource_service))
(eval (= "" resource_region))
(eval (= "" resource_account))
(eval (str.prefixof "mybucket/" resource_resource))
(eval resource_resource)


I get:

sat
true
true
true
true
true
false
"mybucket"

And "mybucket/" is not a prefix of "mybucket".

**Comment by agacek** [comment]
Right, asserting `(not p0.0.resource)` makes it go away. Instead, when I use the original final and query:

```
(check-sat)
(eval (= "arn" resource_prefix))
(eval (= "aws" resource_partition))
(eval (= "s3" resource_service))
(eval (= "" resource_region))
(eval (= "" resource_account))
(eval (str.prefixof "mybucket/" resource_resource))
(eval resource_resource)
(eval p0.0.resource)
```

I get

```
sat
true
true
true
true
true
true
"mybucket/Bananas/Cherries.pdf"
false
```

Which is a contradiction to the assertion:

```
(assert (= p0.0.resource (and (= "arn" resource_prefix) (= "aws" resource_partition) (= "s3" resource_service) (= "" resource_region) (= "" resource_account) (str.prefixof "mybucket/" resource_resource))))
```

Note, I'm not able to reproduce this with the very latest version of z3, but I am in the version from 5 days ago and ones before that.

**Comment by NikolajBjorner** [comment]
closing as related bug was fixed and this doesn't reproduce
