### ISSUE TITLE
Inconsistent answer on floating-point input

### ISSUE THREAD

**Issue by 4tXJ7f** [Z3Prover/z3#2289]
The following issue came up while comparing CVC4 and Z3 on the current set of SMT-LIB benchmarks (https://github.com/CVC4/CVC4/pull/3007#issuecomment-493640402) and finding that they answer differently on five benchmarks. @martin-cs did some debugging and narrowed the issue down to the following.

On the following input, Z3 (https://github.com/Z3Prover/z3/commit/bd46c52f959e01ac7c65bbf634994c6e9649f927) answers `unsat`:
```
(define-sort FP () (_ FloatingPoint 3 5))
(declare-const x FP)                     
(assert (fp.leq (fp #b0 #b001 #x0) (fp.rem x (fp #b0 #b010 #x0))))
; (assert (= x (fp #b0 #b101 #b0001)))
(check-sat)    
```
but when commenting in the second assertion (i.e. setting `x` to `(fp #b0 #b101 #b0001)`, CVC4's model), Z3 answers `sat`.

**Comment by wintersteiger** [comment]
Did you minimize the number of FP bits for this testcase, i.e. does it also fail on larger floats or only on these tiny ones?

**Comment by martin-cs** [comment]
On Mon, 2019-05-20 at 05:47 -0700, Christoph M. Wintersteiger wrote:
> Did you minimize the number of FP bits for this testcase,

Not intentionally; this was the precision at which we observed the
problem.

>  i.e. does it also fail on larger floats or only on these tiny ones? 

I don't know if it fails for larger formats.  Given the testing we have
done for float32 and float64 I think it only affects some formats.

**Comment by wintersteiger** [comment]
Thanks for the report, this was indeed a proper bug in the encoding of `fp.rem` that would have manifested itself on normal size floats too. I think it's now fixed for good, but I noticed there are some new SMT benchmarks that I haven't tried before, so I'll run some checks to make sure I didn't break any new ones.

**Comment by martin-cs** [comment]
Great; thank you!  If you find an instance of the same bug in Float32
or Float64 it would be great to know which values so we can improve our
testing procedure.
