### ISSUE TITLE
sort mismatch in the theory of array

### ISSUE THREAD

**Issue by SunBeomSo** [Z3Prover/z3#2290]
Hi, my question is about the sort mismatch problem when using the theory of array in Z3. Please see the below code in Python:
```
from z3 import *

def main ():

  four = 4
  eight = 8

  arr1 = Array('array', BitVecSort(four), BitVecSort(four))
  arr2 = Array ('array', BitVecSort (eight), BitVecSort (four))

  formula1 = arr1[0] == arr2[0]
  solve (formula1) # fine

  formula2 = arr1 == arr2
  solve (formula2) # sort mismatch error

if __name__ == '__main__':
  main ()
```

When I queried ```formula2```, Z3 raises a sort mismatch error. **However, I do not understand why Z3 does not raise an error when I queried ```formula1```.**

Although the expressions ```arr1[0]``` and ```arr2[0]``` have the same types, I think internally there should be a problem because it means the Z3 variable named ```array``` has  two different types at the same time which cannot happen in general, as shown in the declarations of  ```arr1``` and ```arr2```.

Is this a normal situation? I am quite confused.

Thank you in advance.

**Comment by zimmski** [comment]
This seems OK to me. The sort(type) of `arr1[0]` and `arr2[0]` are the same, a BitVector of size 4. However, the sort of `arr1` and `arr2` are different. `arr1` has an index sort of a BitVector of size 4 and `arr2` has size 8. So the types for `formula2` are not exactly the same. Hence, the mismatch.

**Comment by NikolajBjorner** [comment]
the comment above explains what is going on.
