### ISSUE TITLE
Tag new release

### ISSUE THREAD

**Issue by zimmski** [Z3Prover/z3#2291]
There are a lot of good changes between the last tagged release and what we have in master. For us the changes substantially reduce the time we spend in the solver (going from s/min/h to ms for some formulas). Are there any plans on tagging a new release?

I know that there is usually a mix of bugfix/non-bugfix changes in the master branch. So tagging a regular bugfix release does not make sense if Z3 is following the semantic versioning schema. However, since there are some closed issues that asked for new tags and blockers (e.g. segfaults) are usually fixed right away, would it maybe be possible to do some kind of regular tagging?

**Comment by NikolajBjorner** [comment]
I will prepare next week.

**Comment by zimmski** [comment]
Thank you!
