### ISSUE TITLE
Tseitin Conversion extremely slow

### ISSUE THREAD

**Issue by maxzinkus** [Z3Prover/z3#2293]
The tactic composed of `simplify, bit-blast, tseitin-cnf` can take a very long time on complex QF_BV constraint systems despite its asymptotic efficiency - up to hours on solvers with few albeit complex statements added. Can tseitin conversion be parallelized?

https://github.com/Z3Prover/z3/blob/master/src/tactic/core/tseitin_cnf_tactic.cpp

**Comment by NikolajBjorner** [comment]
If the conversion is super-linear in the formula DAG it means there is a performance bug. Parallelization isn't the way to go. It would be better to simply fix the perf bug if it is possible to identify it.
Tseitin just adds definitions for nodes in a DAG representation of a formula so needs not be expensive. There could be mistakes that makes it expensive.

**Comment by maxzinkus** [comment]
Thanks for the prompt response. Is there a way I can log the formula DAG size so I can sample the tactic at various DAG sizes in terms of size vs time?

**Comment by NikolajBjorner** [comment]
We don't compute DAG sizes. It can of course be computed by walking it bottom-up.

**Comment by NikolajBjorner** [comment]
This report isn't actionable. If you have a repro please post and re-open.
