### ISSUE TITLE
Performance issues in internal_symbol_table::get_str(char const*)

### ISSUE THREAD

**Issue by qingkaishi** [Z3Prover/z3#2299]
We have a tool which uses Z3 in multiple threads. Each thread has its own z3 context. We observe that the critical sections (Line 39 in the code below) in the function ``internal_symbol_table::get_str(char const*)`` causes a lot of overhead due to lock contentions.

https://github.com/Z3Prover/z3/blob/112e13eeea705ca40b73ea3b82eb39a3bea6d398/src/util/symbol.cpp#L37-L61

Is it possible to get rid of the global symbol table and use a thread-local one instead? Or could you explain a bit about the functionality of the global symbol table and provide some suggestions to avoid such runtime overhead?

**Comment by NikolajBjorner** [comment]
Thread local string interning wouldn't work if the application passes state between worker threads.
The allocate and memcpy calls are likely to create contention (and even page faults) so a more nimble version of this code would release locks when performing this operations, but then have to deal with races, or even more suave use a lock free table. Either option isn't simple, but you are invited to give it a stab and a pull request if you want.

**Comment by qingkaishi** [comment]
Thanks very much. I definitely learn something from your reply. I will try to handle the issue.

**Comment by NikolajBjorner** [comment]
Could you try whether the newly added pool of tables help your application?

**Comment by qingkaishi** [comment]
I think it will help because we tried to fix this issue in a very similar manner.
