### ISSUE TITLE
Broken loop

### ISSUE THREAD

**Issue by wintersteiger** [Z3Prover/z3#230]
From #24: This loop is executed only a single time. Always. Is this correct?
https://github.com/Z3Prover/z3/blob/d01c3491a67d4a06ea1f6e57d385f04914529317/src/util/prime_generator.cpp#L70

Looks fishy to me, that break statement should probably be removed altogether.

**Comment by NikolajBjorner** [comment]
looks like a missing else { break; } statement. Unit test passes.
