### ISSUE TITLE
How do I evaluate float values in z3?

### ISSUE THREAD

**Issue by HarishUth** [Z3Prover/z3#2302]
This is the problem statement I got. 

 Encode the following menu choices into Z3 and determine what a customer could buy using exactly
$15.05
• Mixed fruit $2.15
• French Fries $2.75
• Side Salad $3.35
• Hot Wings $3.55
• Mozzarella Sticks $4:20
• Sampler Plate $5:80

The following is the code I attempted to write but had some warnings and the output is worng. 
#include<z3++.h>
using namespace z3;

int main()
{
	context c;
	expr money = c.int_const("money");
	expr fruit = c.int_const("fruit");
	expr salad = c.int_const("salad");
	expr wings = c.int_const("wings");
	expr cheeze = c.int_const("cheeze");
	expr plate = c.int_const("plate");
	expr fries = c.int_const("fries");
	
	solver s(c);
	
	s.add(((fruit*c.real_val(2.15))+(salad*c.real_val(3.35))+(wings*c.real_val(3.55))+(cheeze*c.real_val(4.20))+(fries*c.real_val(2.75))+(plate*c.real_val(5.80)))==15.05);
	std::cout<<s.check();
	std::cout<<s.get_model();
}

OUTPUT:
#include<z3++.h>
using namespace z3;

int main()
{
	context c;
	expr money = c.int_const("money");
	expr fruit = c.int_const("fruit");
	expr salad = c.int_const("salad");
	expr wings = c.int_const("wings");
	expr cheeze = c.int_const("cheeze");
	expr plate = c.int_const("plate");
	expr fries = c.int_const("fries");
	
	solver s(c);
	
	s.add(((fruit*c.real_val(2.15))+(salad*c.real_val(3.35))+(wings*c.real_val(3.55))+(cheeze*c.real_val(4.20))+(fries*c.real_val(2.75))+(plate*c.real_val(5.80)))==15.05);
	std::cout<<s.check();
	std::cout<<s.get_model();

 
}
OUTPUT:
sat(define-fun plate () Int
  0)
(define-fun wings () Int
  0)
(define-fun fries () Int
  6)
(define-fun fruit () Int
  0)
(define-fun salad () Int
  1)
(define-fun cheeze () Int
  0)

WARNINGS I GOT:
/usr/include/z3++.h:3016:17: note: candidate: z3::expr z3::context::real_val(uint64_t)
     inline expr context::real_val(uint64_t n) { Z3_ast r = Z3_mk_unsigned_int64(m_ctx, n, real_sort()); check_error(); return expr(*this, r); }

Sir, I wrote the same code without the decimal places and the solution was correct. But it was not able to evaluate the problem with decimal places. 

-Harish

**Comment by NikolajBjorner** [comment]
The API doesn't have a conversion from float/double to rational numbers. You can pass in a string representation of a decimal number to real_val.
