### ISSUE TITLE
Print UNSAT core inside Z3

### ISSUE THREAD

**Issue by guluchen** [Z3Prover/z3#2304]
I try to print the unsat sat core using the get_unsat_core_size() and get_unsat_core_expr() functions in smt.kernel in the check_sat(expr* e) function below, where int_expr_solver is a subclass of expr_solver and m_kernel is an instance of smt.kernel:

    lbool int_expr_solver::check_sat(expr* e) {
        m_kernel.push();
        m_kernel.assert_expr(e);
        lbool r = m_kernel.check();

        if(r==lbool::l_false){
            std::cout<< "UNSAT core:\n";
            for(unsigned i=0;i<m_kernel.get_unsat_core_size();i++){
                std::cout<<mk_pp(m_kernel.get_unsat_core_expr(i),m)<<std::endl;
            }
        }

        m_kernel.pop(1);
        return r;
    }

But I always get empty unsat core. Should I set some parameter so that the unsat core can be properly stored? 

An additional question:
When I print log, I usually use the macro STRACE or TRACE in the following style:
            STRACE("str", tout << __LINE__ << " leave " << __FUNCTION__ << std::endl;);
But it always go to a log file .z3_trace.

Sometimes I would like to have the some of the STRACE output directly go to the screen. Is there any recommend way of doing this inside Z3?

**Comment by guluchen** [comment]
I have added the global parameter unsat_core=true, but still get empty unsat_core

**Comment by NikolajBjorner** [comment]
Unsat cores are only relative to assumptions passed as extra arguments to check. 
This is based on the way that cores are extracted. If you call m_kernel.check([x, y, z]) 
after asserting mk_implies(x, y), mk_implies(z, mk_not(y)), you could get a core [z,y] or [x,z].
But if you assert x, then assert y, and assert z, together with mk_implies(x,y) and mk_implies(z, mk_not(y))
and call m_kernel.check(), then no core is extracted.

The constant "tout" is defined in util/trace.cpp. It is fixed to a file that always is opened. We don't have a facility to tee this. Perhaps a hack, such as redefining tout to a macro:
#define tout trace_out()
and then have redirections of trace_out() using different settings is a way to go. Or maybe there is a more proper approach.

**Comment by guluchen** [comment]
I see. Thanks Nikolaj.
