### ISSUE TITLE
z3 api file information. 

### ISSUE THREAD

**Issue by HarishUth** [Z3Prover/z3#2308]
Sir, can you please tell me which file in the z3 folder describes information about the parameters , operators, operands of an expression? 
ex: implies() , get_model()
I want to go through the library but not able to find  it.

**Comment by NikolajBjorner** [comment]
there is an include folder in the release for external APIs. 
Some web resources:

https://github.com/Z3Prover/z3/blob/master/src/api/c%2B%2B/z3%2B%2B.h

https://github.com/Z3Prover/z3/blob/master/src/api/z3_api.h

http://lmgtfy.com/?q=Z3+API+documentation

**Comment by HarishUth** [comment]
Sir the First Link is about the z3++.h library. In that folder there is another header file that has been included called the z3.h
I basically want to find out where all the c++ bindings are defined.? 

-Harish

**Comment by NikolajBjorner** [comment]
You can find the relevant header files in the releases from

https://github.com/Z3Prover/z3/releases/tag/z3-4.8.4

Should you want to navigate Z3 sources, then you would find the included file here:

https://github.com/Z3Prover/z3/blob/master/src/api/z3.h

Again, it is easy to find such files with simple utilities, such as "grep" or "findstr" or some modern utility, and applying such methods isn't specific to Z3. The question indicates that you haven't looked around much or you are new to navigating code. The initial question also isn't clearly posed. It assumes some context that I will somehow have to guess. More clearly formulated issues are easier to address in a constructive manner.

**Comment by HarishUth** [comment]
Yes sir, I am new to Ubuntu and z3. Sorry for not clearly asking the question. But thank you so much for helping , your answers and support has been of great help for me to understand z3 in depth.

**Comment by HarishUth** [comment]
Sir, I basically need to convert the z3 expression into another format. When I pass the z3 expression into my convert() function it must convert the expression into the form I require. 
For doing that I need to go through the expression format which is in usually in a file.
Is there a file that would tell if my expression has operators and and operands and if my operator itself is another expression?
