### ISSUE TITLE
cmake import targets are lacking a Z3ConfigVersion.cmake file

### ISSUE THREAD

**Issue by ekpyron** [Z3Prover/z3#2318]
Following https://cmake.org/cmake/help/latest/command/find_package.html?#version-selection, the command ``find_package(Z3 4.8.0 CONFIG)`` only works, if Z3 provides a ``Z3ConfigVersion.cmake`` file that performs version checking - however, currently an installation of Z3 is lacking this file (even though it does define Z3_VERSION* in Z3Config.cmake), preventing the use of cmake's version requirements.

**Comment by NikolajBjorner** [comment]
pull requests are appreciated. I am not warmed up to what is actionable regarding cmake

**Comment by ekpyron** [comment]
I can gather from your CMakeLists that you need to stay compatible with cmake 2.8.12, right?

**Comment by NikolajBjorner** [comment]
Indefinite down-level compatibility is not a design goal. I am not familiar with cmake versions so will rely on advise what makes sense.

**Comment by NikolajBjorner** [comment]
Seems the minimum is 3.4:
https://github.com/Z3Prover/z3/blob/master/CMakeLists.txt#L2

**Comment by ekpyron** [comment]
Ok, missed that - then there's quite a few workarounds that can be removed:
https://github.com/Z3Prover/z3/blob/master/CMakeLists.txt#L30
https://github.com/Z3Prover/z3/blob/master/CMakeLists.txt#L201
https://github.com/Z3Prover/z3/blob/master/CMakeLists.txt#L553

I hope I'll get around to put a pull request together this weekend.

**Comment by NikolajBjorner** [comment]
Also, < 3 references removed in: cb6d3d245809fa0ba827f4adfc704e5cde761a26

**Comment by NikolajBjorner** [comment]
2.8 seems to be from about 2013. I cannot think of a rational reason to support a version so old.
