### ISSUE TITLE
Non-deterministic behaviour with 4.8.5

### ISSUE THREAD

**Issue by StephenFosterQRA** [Z3Prover/z3#2319]
When running the latest release of z3 on the attached file, I've been seeing the following non-deterministic behaviour: roughly two-thirds/three-quarters of the time, z3 will return unsat in about 13s (timing is pretty consistent). The rest of the time, it hangs indefinitely (generally I waited 3-5 minutes while testing this; I never saw it complete analysis after it had gotten past ~13s).

My operating system is Ubuntu 16.04, and I'm running the pre-built binary for version 4.8.5 (naturally the Ubuntu 16.04 binary).

Some relevant information: with version 4.4.2 (commit 8fa29f6), analysis of this file completes consistently in ~13s. With version 4.8.4 (commit d6df519), analysis never completes (again, generally I tested for 3-5 minutes).

This issue _could_ be related to a previous issue I reported (https://github.com/Z3Prover/z3/issues/2242), which involved a regression between 4.4.2 and 4.8.4 on a somewhat similar smt file (both are based on the same discrete-time system). Note that for both issues, the files in question require the pull_cheap_ite flag to be set in order for analysis to ever complete. However, I never saw any non-deterministic behaviour with that earlier issue, so the similarity could just be a red herring.

Upping the verbosity didn't provide much insight - at least at a verbosity level of 10, it looked like the same thing was happening every time, but it was just getting stuck at a random place in certain runs.

Let me know if you need any more information from me - I'd be happy to run any tests that might be useful on my machine.

Here's the file in question:

[non-deterministic-bug-smt2.txt](https://github.com/Z3Prover/z3/files/3253591/non-deterministic-bug-smt2.txt)

**Comment by petercommand** [comment]
I am also experiencing non-deterministic behavior with 4.8.5. Not sure if it's related to this issue or not
This is the file that I used: https://gist.github.com/petercommand/4aa67575117b0a6bcbff708d1afd8f87

**Comment by NikolajBjorner** [comment]
The original file exercises nlsat tactic only. It uses only reals. 
Your file is non-linear, but over integers.
Your formula is of a specific form (which is not handled well by z3): it is a set of modular equations.
They can be solved by realizing that all variables are bounded and can be solved with modular equations. The same formula over bit-vectors would be solved by pre-processing.

**Comment by NikolajBjorner** [comment]
added rewriting for modular equations

**Comment by petercommand** [comment]
> The original file exercises nlsat tactic only. It uses only reals.
> Your file is non-linear, but over integers.
> Your formula is of a specific form (which is not handled well by z3): it is a set of modular equations.
> They can be solved by realizing that all variables are bounded and can be solved with modular equations. The same formula over bit-vectors would be solved by pre-processing.

Hi, I followed your advice and tried bitvec with z3 rev 84025d5. It didn't work for me though.
This is the file that I used: https://gist.github.com/petercommand/415f8e5a41a29927c7aa3828e57ee28d
Perhaps I did something wrong here?

**Comment by NikolajBjorner** [comment]
Indeed, the rewriting on bit-vectors would only work when the modulus is the one that is implicit by the bit-vector length. At any rate, the integer case is now picked up to some extent by pre-processing.
