### ISSUE TITLE
omp_set_nested deprecated above OpenMP-5.0

### ISSUE THREAD

**Issue by steakhal** [Z3Prover/z3#2322]
`omp_set_nested` function is **deprecated** at and above OpenMP-5.0.
We should use `omp_set_max_active_levels`, according to the [OpenMP Technical Report 7: v5.0](https://www.openmp.org/wp-content/uploads/openmp-TR7.pdf) at page 341, section 3.2.10.

[src/util/cooperate.cpp#L31](https://github.com/Z3Prover/z3/blob/7d20fbb28094f27e399d4d8cbc47bcee93f572f0/src/util/cooperate.cpp#L31)

**Comment by NikolajBjorner** [comment]
OMP will be completely deprecated from Z3 by end of week, anyway.
