### ISSUE TITLE
Why "(assert (str.in.re "A" (re.complement (str.to.re "A"))))" returns true?

### ISSUE THREAD

**Issue by gogo9th** [Z3Prover/z3#2326]
(re.complement (str.to.re "A")) is the set of characters: {"", "B", "BB, "BB...", ... "C", "CC", ...}, which doesn't include "A". 

Therefore, (assert (str.in.re "A" (re.complement (str.to.re "A")))) should return false. But if I run it from [Online Z3](https://rise4fun.com/z3/tutorial), it returns true. Why is it so?

Also, I wonder how to express a complement of a regular expression in Javascript. For example, we have a regex class ([hello]|[world])+ in Javascript. How can we express its complement?

**Comment by NikolajBjorner** [comment]
this is fixed in current master
