### ISSUE TITLE
How to express re.complement in Javascript's regular expression?

### ISSUE THREAD

**Issue by gogo9th** [Z3Prover/z3#2327]
I wonder how to express a complement of a regular expression in Javascript. For example, we have a regex class ([hello]|[world])+ in Javascript. How can we express its complement?

**Comment by NikolajBjorner** [comment]
this is not an issue regarding Z3

**Comment by gogo9th** [comment]
Sorry about that...
I think I found a solution, so I will just post here:

"...": By this I denote any regular expression
(?!...): should not match "..." & rewind the input string upon match/mismatch
(?=...): should match "..." & rewind the input string upon match/mismatch
(?:...): Do not consider this parenthesis as a capture group

Match the input string only if it doesn't match "...":
^(?:(?!...).)*$

For example, with regex = ^(?:(?!(ab)+).)*$, input "acdfg" matches "acdfg", whereas input "acabf" doesn't match anything (because it matches (ab)+ ).
