### ISSUE TITLE
conversion of an expression to a string?

### ISSUE THREAD

**Issue by HarishUth** [Z3Prover/z3#2328]
I am trying to create a map that corresponds to my expression variables and expression constants with an random integer value.
This is the expression: ((x || !z) && (y || !z)) where x y and z are bool_const expressions.

I have created a recursive function where it is able to traverse through every element in the expression. But in the mapping function I've to give an INTEGER and a STRING as inputs.

map<int,string> symbols; 
void walk(expr e)
{     

    if(e.is_const())
    {   
        std::cout <<"ARGUMENT: " << e<< endl;
        int ran_num = (rand() % 10) + 1;
        symbols.insert(pair<int,string>(ran_num,e.to_string)); 
    }
    else
    {
        cout <<"APP: " << e.decl().name() << endl;
        for(int i = 0; i < e.num_args(); i++)
        {    int ran_num = (rand() % 10) + 1;
             symbols.insert(pair<int,string>(ran_num,e.decl().name())); 
             walk(e.arg(i));
        }
    }
}
Here the problem is occurring with

symbols.insert(pair<int,string>(ran_num,e.to_string)
where e.to_string is not able to interpret as string

and

symbols.insert(pair<int,string>(ran_num,e.decl().name()))
is also not able to interpret the e.decl().name() part as STRING.

How do I convert them to string in order to satisfy my mapping function?

**Comment by NikolajBjorner** [comment]
consider e.to_string() instead of e.to_string
