### ISSUE TITLE
Does 4.4.1 include all floating-point changes?

### ISSUE THREAD

**Issue by LeventErkok** [Z3Prover/z3#233]
Not an issue, but a question. Congrats on the official 4.4.1 release. Does it contain all the FP theory changes you implemented in the unstable branch over the last couple of months? Couldn't tell from the release-notes; so just double checking.

**Comment by wintersteiger** [comment]
Yes, that contains all those changes, except for the fp.min/fp.max zero cases (issue #68 ), those are still in progress.
