### ISSUE TITLE
[Question] In ocaml z3, Why z3 says 'sat' this problem

### ISSUE THREAD

**Issue by hongjisung** [Z3Prover/z3#2331]
Why does z3 consider 'sat' below problem?
(declare-datatypes () ((LList nil (cons (head Int) (tail LList)) )) )
(define-fun f ((x LList)) Int (+ 1 (head x)))
(assert (= (f (cons 4 nil)) 5) )
(assert (= (f (cons 0 nil)) 1) )
(assert (= (f nil) 0) )
(check-sat)

In case (= (f nil) 0), why is the body of f, (+ 1 (head x)) satisfiable?

![스크린샷, 2019-06-08 14-37-07](https://user-images.githubusercontent.com/31429770/59142673-9c62df00-89fc-11e9-8a17-f7e7515e21c5.png)
![스크린샷, 2019-06-08 14-49-05](https://user-images.githubusercontent.com/31429770/59142674-9c62df00-89fc-11e9-8dbd-7a8fdaef5ce0.png)

**Comment by NikolajBjorner** [comment]
The solver is free to decide the interpretation of "head" on "nil". In this case it finds some itnerpretation that satisfies the equation. (such as (f nil) = -1).
