### ISSUE TITLE
New Feature: many valued logic

### ISSUE THREAD

**Issue by aestriplex** [Z3Prover/z3#2333]
Dear all,

There is a calculus for propositional Lukasiewicz infinite-valued logic ([this one](https://link.springer.com/article/10.1007/s11225-009-9185-2)) that, given as input a formula, returns a system of linear inequalities. Since Z3 can already solve such systems, my question is the following:

could it worth the effort if I start to work on this new feature to incorporate the possibility of working with many valued logic?

**Comment by NikolajBjorner** [comment]
Z3 isn't generally suitable for encoding logical calculi. It is a low-level solver with classical first-order semantics. Logical frameworks supported by interactive theorem provers are more suitable.
