### ISSUE TITLE
Z3 nightly aborts when run without inputs

### ISSUE THREAD

**Issue by shiatsumat** [Z3Prover/z3#2336]
First of all, thank you for Z3 nightly build. It is really helpful for me.

Let me report a small bug.
The latest Z3 nightly aborts when run without inputs (e.g. `z3`, `z3 --version`, `z3 --help`).
For example, `z3 --version` will output this.
```
$ z3 --version
Z3 version 4.8.6 - 64 bit
libc++abi.dylib: terminating with uncaught exception of type std::__1::system_error: mutex lock failed: Invalid argument
fish: 'z3 --version' terminated by signal SIGABRT (Abort)
```

**Comment by NikolajBjorner** [comment]
This is on a mac, right?

**Comment by shiatsumat** [comment]
Yes, exactly.

**Comment by NikolajBjorner** [comment]
@nunoplopes fixed this earlier today
