### ISSUE TITLE
Conversion of a symbol to an expression 

### ISSUE THREAD

**Issue by Harish-uthravalli** [Z3Prover/z3#2337]
expr e = (x || !z) && (y || !z);
expr op = e.decl().name();
if( symbol.is_var())

I basically need to compare if the given operator/operand is a variable or not. But .decl().name() is giving me a symbol as return type and is_var() evaluates only an expression. Is there a function that can convert a symbol to an expression. or any function that can compare those 2 variables. ?

**Comment by wintersteiger** [comment]
This kind of "variables" in Z3 are applications of constant, uninterpreted functions (as opposed to bound variables), so you're likely looking for `if (e.is_const() && e.decl().decl_kind() == Z3_OP_UNINTERPRETED)`.

**Comment by Harish-uthravalli** [comment]
So can I do this? 
symbol op = exp.decl().name();
if(exp.is_const() && exp.decl().decl_kind()==Z3_OP_UNINTERPRETED)

**Comment by wintersteiger** [comment]
Yes, does that not work? I don't know what meaning the symbol name has to you, but Z3 doesn't need it to determine whether it's an uninterpreted constant.

**Comment by Harish-uthravalli** [comment]
okay sir.
