### ISSUE TITLE
Not able to resolve the error. 

### ISSUE THREAD

**Issue by Harish-uthravalli** [Z3Prover/z3#2340]
I am basically trying to create a programs that give me the operands of an operator from an expression. 

#include<iostream>
#include<map>
#include<iterator>
#include"z3++.h"
using namespace z3;
using namespace std;
map<expr,int> mapping;

int fun(z3::expr exp)
{   static int number=1;
    int id[50];
    if(mapping.find(exp)!= mapping.end())
    {
        std::cout<<"this is IF statement";
        return mapping[exp];
    }    
    else 
    {
        mapping.insert(pair<expr,int>(exp,++number));
        symbol op = exp.decl().name();
        if(exp.is_const() && (exp.decl().decl_kind()==Z3_OP_UNINTERPRETED))
           return(number);
        else
        {
          for(int i =0;i<exp.num_args();i++)
          {
              id[i] = fun(exp.arg(i));
          }
        }
        std::cout<<"for operator :"<<op.str();
        std::cout<<"values of id are: "<<id[0]<<" "<<id[1];       
   }  
}
int main()
{   map<expr,int>::iterator itr;
    context c;
    expr x = c.bool_const("x");
    expr y = c.bool_const("y");
    expr z = c.bool_const("z");
    expr e = (x || !z) && (y || !z);       
    
    fun(e);
    cout << "\tKEY\tELEMENT\n"; 
    for (itr = mapping.begin(); itr != mapping.end(); ++itr) { 
        cout << '\t' << itr->first 
             << '\t' << itr->second << '\n';
}

}

This is the error I am getting. 

a.out: /usr/include/z3++.h:1488: z3::expr z3::operator<(const z3::expr&, const z3::expr&): Assertion `false' failed.
Aborted (core dumped)
Not able to understand where the problem is.

**Comment by NikolajBjorner** [comment]
The C++ API overloads operator < to create a less-than expression. It is only defined on integers, reals, bit-vectors and floating point expressions. 
This clashes with the std::map<> class that by default assumes an operator "<" on the domain of the map that is supposed to compare the domain elements in a linear order. 
You can override the default comparison in map<> using a comparison on expression identifiers. Every z3 expression has a unique unsigned identifier. The identifier is retrieved using the id() function. For example if you have 'e' as an expr then e.id() is an unsigned.
