### ISSUE TITLE
installation on linux 

### ISSUE THREAD

**Issue by Aishaaldosery** [Z3Prover/z3#2342]
I installed z3 on the wrong directory, which causes the error that (python can't find it):

    from z3 import *
ModuleNotFoundError: No module named 'z3'

and then I tried to uninstall z3 by using:

sudo make uninstall

but unfortunately, I got another error and could fix it:

 make: *** No rule to make target 'uninstall'.  Stop.

could you please help me to uninstall z3 and all dependency?

**Comment by Aishaaldosery** [comment]
I tried this command:

sudo apt-get remove --auto-remove z3

and I got

Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package 'z3' is not installed, so not removed
0 upgraded, 0 newly installed, 0 to remove and 515 not upgraded.

**Comment by NikolajBjorner** [comment]
I suggest you use "pip install z3-solver" to install z3 in your environment.
