### ISSUE TITLE
Difference between declare-fun, define-fun, define-fun-rec

### ISSUE THREAD

**Issue by arohner** [Z3Prover/z3#2343]
I believe this is similar to #2139, but not exactly the same.

I'm trying to write a static type checker for clojure in Z3

```
(define-fun parent? ((x Type) (y Type)) Bool
  (or (= x clojure.core/any?)
      (= x java.lang.Object)
      (= x y)
      (and (= x clojure.core/number?) (= y clojure.core/integer?))
      (and (= x clojure.core/integer?) (= y clojure.core/int?))
      (and (= x clojure.core/int?) (= y clojure.core/pos-int?))
      ...))

(define-fun subtype? ((x Type) (y Type)) Bool
  (or (= x y)
      (parent? x y)
      (exists ((a Type))
              (and (parent? x a) (parent? a y)))
      (exists ((a Type) (b Type))
              (and (parent? x a) (parent? a b) (parent? b y)))
      (exists ((a Type) (b Type) (c Type))
              (and (parent? x a) (parent? a b) (parent? b c) (parent? c y)))))
```

This code works, and is fast, returning answers in ~10ms. 

If I change `subtype?`'s definition to `declare-fun` + `(assert (forall ((x Type) (y Type)) (= (subtype? x y) <body>)`, the check-sat times out after one minute. The problem seems to be related to the `exists` calls. If I comment out the exists checks, the function returns the expected results quickly.

If I change `subtype?`'s definition to `define-fun-rec` without changing the body, I get the same timeout. 

Both of these are problems for me because they prevent forward declarations of the functions. I'd like to be able to use (subtype?) in some of the parent? checks. 

It's also very confusing that `define-fun` and `declare-fun` behave differently. The SMTLIB spec says that declare-fun + forall should result in the same behavior.

**Comment by NikolajBjorner** [comment]
The version with Forall x y . subtype(x,y) <=> Exists .... introduces quantifier alternation. The formula is no longer in a decidable fragment and Z3 does in this case not realize that you introduced a conservative definition.

**Comment by wintersteiger** [comment]
I haven't tried whether it works on your example, but the macro-finder tactic recognizes function definitions of the form `(assert (forall (...) (= (f  ...) ...)` and inlines them, so later stages of the solver won't see a quantifier alternation anymore.

**Comment by arohner** [comment]
Using 4.8.5, Is there any way to express this using `declare-fun` or `define-fun-rec`?

**Comment by wintersteiger** [comment]
No, it's a tactic, e.g. instead of using `(check-sat)` you can use `(check-sat-using (then macro-finder smt))`.
