### ISSUE TITLE
OCaml bindings undefined symbol

### ISSUE THREAD

**Issue by dlindsaye** [Z3Prover/z3#2346]
I've installed Z3 (4.8.5) from source and with opam on Ubuntu with OCaml 4.07.1 and either way I get a load error:

Cannot load required shared library dllz3ml.
Reason: /home/lindsay/.opam/default/lib/stublibs/dllz3ml.so: /home/lindsay/.opam/default/lib/stublibs/dllz3ml.so: undefined symbol: Z3_rcf_del.

Suggestions appreciated.

**Comment by NikolajBjorner** [comment]
The opam distribution is maintained independently so I can't speak for what is the issue with using it. 
You could build z3 from sources, following the instructions in README.md

**Comment by dlindsaye** [comment]
Thanks Nikolaj. Had the same problem when building from sources. Will find a way to sort it out.

**Comment by namasikanam** [comment]
Same problem. How did you sort it out?
