### ISSUE TITLE
free(): invalid pointer in CLion for C++ with Z3 on OS X and UBUNTU

### ISSUE THREAD

**Issue by affernan** [Z3Prover/z3#2348]
Hello.

I know that an error: free(): invalid pointer, is well know in C++ and there in (https://github.com/Z3Prover/z3/issues/1157), but I have a doubt with a compile C++ program with Z3 on OSX and Ubuntu.

1. Previosly, I was installed Z3 on OSX v10.13.6 and UBUNTU v18.04

2. Install CLion Jetbrains, create new project and import `z3++.h `library, all ok.

3. I linked the library `-lz3` as said in **(1)** https://stackoverflow.com/questions/17514923/need-help-in-using-z3-api-in-a-c-program and **(2)** https://stackoverflow.com/questions/50365936/how-to-link-library-in-clion

4. I tested the C++ example from **(1)** for each OS system, and I get that:
OS X: all fine, ouput : `(+ x 1)`
..and
UBUNTU : I get the output : `free(): invalid pointer`

if I did the same installation steps in both operating systems, then I did the linked of the library, because I get an error in ubuntu? How can i fix it?

regards,
Alex

**Comment by NikolajBjorner** [comment]
Our builds on OSX and Ubuntu 16.04 check the examples. I can't speak for Ubuntu 18.04 and tool chains on top if this.
