### ISSUE TITLE
On Linux install into /usr/local

### ISSUE THREAD

**Issue by neilnelson** [Z3Prover/z3#2349]
Software installed from the distribution, such as using apt on Ubuntu, goes into /usr. Software compiled and installed by the user goes into /usr/local.

**Comment by NikolajBjorner** [comment]
The ubuntu packages appear to be without any support. 
https://packages.ubuntu.com/search?keywords=z3 lists very old versions of Z3.
I suggest you use a nightly build or build yourself.

**Comment by neilnelson** [comment]
Just did this about two hours ago.

Get Z3 at

https://github.com/Z3Prover/z3

Use the following line. Otherwise the install goes to standard 
distribution directories immediately under /usr.

python scripts/mk_make.py --prefix=/usr/local

You will need to make a soft link so llvm will find the so.

ln -s /usr/local/lib/libz3.so /usr/lib/x86_64-linux-gnu/libz3.so
