### ISSUE TITLE
Segmentation fault via the Python API

### ISSUE THREAD

**Issue by andrewvaughanj** [Z3Prover/z3#2350]
Hi,

I am experiencing a segmentation violation when using Z3 via its Python API. Where possible, I have endeavoured to create a "minimal" instance that triggers this issue, but it has been quite elusive to make it totally minimal.

To diagnose this, I have done the following:

* Add a call to `z3.Z3_open_log("z3.log")` before working with the solver at all (again, under this "minimal" example)

* Using a non-debug build of Z3, confirm that re-running `z3.log` leads to a SIGSEGV

* Create a build of Z3 with `--debug` to validate that, even under a debug build, the issue appears

This was done with a fresh build of both `z3` and `libz3.so` at [88d51d3](https://github.com/Z3Prover/z3/commit/88d51d3).

To capture some information for this, I created Z3 log files using both a debug (i.e., with `--debug`) and release build. Interestingly, running the log file generated with the debug build _under the release build_ **does not crash**. However, all other permutations do crash (i.e., running the release and debug log under the debug build always crashes, and running the release log under the release build also crashes).

Importantly, no matter which build I use, I get a SIGSEGV when running utilising the API under Python.

Here are the two log files:

- https://gist.github.com/andrewvaughanj/2319d338ce3c126a82d05dfff3b10aa1

- https://gist.github.com/andrewvaughanj/f6ab83fa5b9752863b8da397100f7e35

Some "system specifics":

- `uname -a` == `Linux avjcentos1 3.10.0-957.5.1.el7.x86_64 #1 SMP Fri Feb 1 14:54:57 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`

- `cat /etc/redhat-release` == `CentOS Linux release 7.6.1810 (Core)`

- `gcc --version` == `gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-36)`

- `python --version` == `Python 2.7.14`

Is there anything more that I can provide to help further demonstrate this issue?

Cheers,

Andrew

**Comment by andrewvaughanj** [comment]
Slightly misleadingly, I had left some random seed and timeout code in this example -- I've removed these and the issue still exists. If traces without this in there are helpful, I am more than happy to provide them!

**Comment by NikolajBjorner** [comment]
Thanks, this produces a repro. Still going to be slightly tricky to narrow in as the bug is related to reference counting. The reference count on "true" goes down to 0 by the time of the last call. The log seems to have adequate information, such as calls to evaluate after the second call.

**Comment by andrewvaughanj** [comment]
@NikolajBjorner Thanks for looking! Please let me know if there's anything I can do to provide any further information.

**Comment by NikolajBjorner** [comment]
I am observing that the constant "True" has its reference count decremented twice per increment from the API. The only reference count access to expressions should be in 

https://github.com/Z3Prover/z3/blob/master/src/api/python/z3/z3.py#L301
and 
https://github.com/Z3Prover/z3/blob/master/src/api/python/z3/z3.py#L305

WIthout running the python code I am unable to say how the double free happens.
Could you instrument z3.py on your end to trap the calls to Z3_inc_ref and Z3_dec_ref when 
the ast is "true"? 
For example

    def __del__(self):
        if self.ctx.ref() is not None:
           Z3_dec_ref(self.ctx.ref(), self.as_ast())

becomes

    def __del__(self):
        global count_ref
        if self.ctx.ref() is not None:
           if is_true(self):
              print("dec-ref: ", self)
              assert(count_ref > 0)
              count_ref -= 1
           Z3_dec_ref(self.ctx.ref(), self.as_ast())

**Comment by andrewvaughanj** [comment]
Okay, I added that, and now:

```
('dec-ref: ', True)
Exception NameError: "global name 'count_ref' is not defined" in <bound method BoolRef.__del__ of True> ignored
```

Where should `count_ref` be declared? Should I also have an increment somewhere?

**Comment by andrewvaughanj** [comment]
Here was my guess:

```
count_ref=0

class AstRef(Z3PPObject):
    """AST are Direct Acyclic Graphs (DAGs) used to represent sorts, declarations and expressions."""
    def __init__(self, ast, ctx=None):
        global count_ref
        self.ast  = ast
        self.ctx  = _get_ctx(ctx)
        if self.ctx.ref() is not None:
           if is_true(self):
              print("dec-ref: ", self)
              count_ref += 1
        Z3_inc_ref(self.ctx.ref(), self.as_ast())
```

**Comment by andrewvaughanj** [comment]
Interesting ... so our code does something like this:

```
def some_function():
    value = None

    try:
        value = some_call_that_builds_an_expression_and_does_model_eval()
    except Exception as e:
        # error handling
        pass

    return value

# EOF
```

and, then, with the above tracing in, we get:

```
  File "test.py", line 123, in some_function
    return value
  File "z3/z3.py", line 317, in __del__
    traceback.print_stack()
```

so the `assert(count_ref > 0)` gets triggered on the return statement (fine); I changed it to be:

```
              if count_ref <= 0:
                  import traceback
                  traceback.print_stack()
```

Digging a little deeper, it seems that `some_call_that_builds_an_expression_and_does_model_eval` experiences `maximum recursion depth exceeded`.

I guess that when that happens in Python, the exception handlers do not run some code that Z3 expects to have run to ensure that reference counting has occurred properly.

I'm happy to say that our code is extremely stupid that it has this error, and that our code _silently gobbles this up and continues_ (!), but I wonder how good it is for Z3 to then bring the whole house down?

**Comment by andrewvaughanj** [comment]
Another interesting point, is that I do only see one instance of `('inc-ref: ', True)`, but two instances of `('dec-ref: ', True)`.

**Comment by NikolajBjorner** [comment]
This is the whole point: the python runtime somehow calls a destructor twice.
We can work around this as follows:

    def __del__(self):
        if self.ctx.ref() is not None:
           Z3_dec_ref(self.ctx.ref(), self.as_ast())
          self.ctx.ctx = None

could you try this?

**Comment by andrewvaughanj** [comment]
Yep, it seems that adding `self.ast = None` does fix this!!!

The original `ctx.ctx` thing gave another error.

**Comment by NikolajBjorner** [comment]
changing ctx.ctx was my mistake
