### ISSUE TITLE
Verifying very simple non-linear integer inequalities

### ISSUE THREAD

**Issue by abadams** [Z3Prover/z3#2351]
Consider the following integer inequality: `x * c0 + c1 <= y * c0`
Assuming positive c0, you can just divide both sides by c0, rounding up on the left and rounding down on the right, to get the equivalent inequality: `x + ceil(c1/c0) <= y`

I'm trying to use Z3 to verify facts of this flavor. Other examples that rely on the same trick are
`(min(x * c0, c1) <= y * c0) == (min(x, ceil(c1/c0)) <= y)`
and the more general:
`(x * c0 + c1 <= y * c2) == (x * (c0/c3) + ceil(c1/c3)) <= y * (c2/c3))` 
where `c3 = gcd(c0, c2)`

It seems that z3 can handle this sort of thing for bounded c0, via enumeration I guess (runtime scales linearly with the upper bound I use), but returns unknown if c0 has no upper bound. Is there some trick to encoding this so that I can verify facts of this flavor? Here's what I have:

```
; Attempt to prove that (x * c0 + c1 <= y * c0) == (x + ceil(c1/c0) <= y), for positive c0

(declare-const x Int)
(declare-const y Int)
(declare-const c0 Int)
(declare-const c1 Int)
(declare-const c2 Int)
(declare-const lhs Bool)
(declare-const rhs Bool)

(assert (= lhs (<= (+ (* x c0) c1) (* y c0))))
(assert (= rhs (<= (+ x c2) y)))

; c0 positive
(assert (< 0 c0))

; c2 = ceil(c1/c0)
(assert (= c2 (+ (div (- c1 1) c0) 1)))

(assert (not (= lhs rhs)))

(check-sat)
(get-model)
```

@shoaibkamil @jn80842

**Comment by abadams** [comment]
Simplifying further, this still doesn't work if you just try to verify that `(x * c0 < y * c0) == (x < y)` for positive c0

```

(declare-const x Int)
(declare-const y Int)
(declare-const c0 Int)
(declare-const c1 Int)
(declare-const lhs Bool)
(declare-const rhs Bool)

(assert (= lhs (< (* x c0) (* y c0))))
(assert (= rhs (< x y)))

; c0 positive
(assert (< 0 c0))

(assert (not (= lhs rhs)))

(check-sat)
(get-model)

```

**Comment by levnach** [comment]
Returns an "unsat" in debug branch at 330ee6261c11d9150b375e9f3dc9442bd924e094, as expected, I believe.

**Comment by abadams** [comment]
This still returns unknown at current master for me. I see the lines from that commit in my source tree (though c_idx has been changed to v: https://github.com/Z3Prover/z3/commit/330ee6261c11d9150b375e9f3dc9442bd924e094#diff-33ea7955435d4781c53c8081101aaaf0R261)

**Comment by levnach** [comment]
It should work if you run z3 you_file smt.arith.solver=6.

**Comment by abadams** [comment]
Confirmed! Thanks.

**Comment by TaihuLight** [comment]
‘’‘
; Attempt to prove that (x * c0 + c1 <= y * c2) == (x * (c0/c3) + ceil(c1/c3)) <= y * (c2/c3) for positive c0，where c3 = gcd(c0, c2).

(set-option :produce-models true)
(set-option :smt.arith.solver=6)

(declare-const x Int)
(declare-const y Int)
(declare-const c0 Int)
(declare-const c1 Int)
(declare-const c2 Int)
(declare-const lhs Bool)
(declare-const rhs Bool)

(assert (= lhs (<= (+ (* x c0) c1) (* y c0))))
(assert (= rhs (<= (+ (* x (/ c0 c3)) (div c1 c3)) (* y (/ c2 c3))))

; c0 positive
(assert (< 0 c0))

; definition of function gcd() for using Euclidean algorithm to find gcd(f,g)
(define-fun gcd ((a Int) (b Int) ) Int
(
forall ((y Int)) ((= m (mod x y)) (ite (== m 0) (return y) ((= x y) (= y m))))
)
)

; c3 = gcd(c0, c2)
(declare-fun gcd (Int Int) Int)
(assert (= c3 (gcd c0 c2))

(assert (not (= lhs rhs)))

(check-sat)
(get-model)
’‘’
