### ISSUE TITLE
Trouble installing and using Z3py on Windows

### ISSUE THREAD

**Issue by 0xTowel** [Z3Prover/z3#2352]
I'm using Python 3.7.3, 64bit on Windows 10, and am having trouble getting the Python support to work.

I followed the steps [here](https://github.com/Z3Prover/z3/wiki/Using-Z3Py-on-Windows), using pre-built binaries for nightly `z3-4.8.6-x64-win.zip` and `z3-4.8.5-x64-win.zip`, and tried the instructions to build from source using `nmake` as well.

Regardless of the method, I cannot access Z3 from the Python bindings, and it fails with the following error:

```
>>> import z3
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\z3\bin\python\z3\__init__.py", line 1, in <module>
    from .z3 import *
  File "C:\z3\bin\python\z3\z3.py", line 45, in <module>
    from . import z3core
  File "C:\z3\bin\python\z3\z3core.py", line 154, in <module>
    _lib.Z3_mk_array_sort_n.restype = Sort
  File "C:\Program Files\Python37\lib\ctypes\__init__.py", line 369, in __getattr__
    func = self.__getitem__(name)
  File "C:\Program Files\Python37\lib\ctypes\__init__.py", line 374, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: function 'Z3_mk_array_sort_n' not found
```

I've set:

 * `PATH` to include `C:\z3\bin`
 * `PYTHONPATH` to `C:\z3\bin\python`

And am using the x64 releases with the following version of Python:

`Python 3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 22:22:05) [MSC v.1916 64 bit (AMD64)] on win32`

Would anyone be able to point me in the right direction?

**Comment by NikolajBjorner** [comment]
maybe an older version of libz3.dll is elsewhere on your PATH

**Comment by 0xTowel** [comment]
Thank you @NikolajBjorner , that was indeed the issue! Running `which libz3.dll` found the offending copy. Resolved.
