### ISSUE TITLE
Incorrect model produced for Horn clauses

### ISSUE THREAD

**Issue by jrmcclurg** [Z3Prover/z3#2357]
This is potentially related to my previous issue #2353. If I uncomment either of the below assertions, Z3 gives me the model `λ(x,y).false` for `source`, which seems incorrect.

```
(set-logic HORN)
(declare-fun source (Int Real) Bool)

(assert (forall ((x Int)) (=> (= x 1) (source x 20.0))))
(assert (forall ((x Int)) (=> (= x 2) (source x 0.0))))

; Uncommenting either of the following (incorrectly) results in the model "λ(x,y).false" for source:
;(assert (forall ((x Int) (sr1 Real) (sr2 Real)) (=> (and (not (= sr1 sr2)) (source x sr1) (source x sr2)) false)))
;(assert (forall ((x Int) (sr1 Real) (sr2 Real)) (=> (and (source x sr1) (source x sr2)) (= sr1 sr2))))

(check-sat)
(get-model)
(exit)
```
If I uncomment *both* of the assertions, I get the (also incorrect) model `λ(x,y).((y <= 20) ^ (y >= 20))` for `source`.

If I disable the Horn solver by commenting out the first line, I get the same model regardless of which of the two assertions I uncomment, as expected.

**Comment by NikolajBjorner** [comment]
@agurfinkel: debug mode produces: 

z3 2357.smt2

Failed to verify: lemma->get_pob()->pt().check_inductive(lemma->level(), cube, uses_level, lemma->weakness())

**Comment by NikolajBjorner** [comment]
seems fixed
