### ISSUE TITLE
Z3 C++ APIs are not supported if Z3 is dynamically loaded by LoadLibrary on Windows

### ISSUE THREAD

**Issue by mcfi** [Z3Prover/z3#2361]
We would like to use z3 in our project. Our code policy prohibits checking-in external static libs, so we can’t check-in libz3.lib and link with it, but instead have to use the LoadLibrary API to dynamically load libz3.dll. However, this prevents us from using the C++ APIs because all of the C APIs in z3++.h are statically called, so libz3.lib is still required to be specified at build time, which cannot be checked in.

For a simple example, if I include z3++.h, and instantiate a config object in C++, the constructor of config will call Z3_mk_config, without calling GetPorcessAddress first to get the address of the function from libz3.dll. Though it is possible to use pure C APIs in our project, they are not as convenient and readable as the C++ APIs.

**Comment by NikolajBjorner** [comment]
@nunoplopes - do you have advice how to best approach this? 
The Windows build uses .def files to specify the exports.

**Comment by NikolajBjorner** [comment]
as far as I understand there is no requirement to support dynamic GetProcessAddress indirections
