### ISSUE TITLE
How to print the output of 'bit-blast' method in c++?

### ISSUE THREAD

**Issue by Harish-uthravalli** [Z3Prover/z3#2363]
I have created a function that converts PL formulas to qdimacs. I want to convert even some bit_vector formulas to pl and then QDIMACS.I have this method called 'bit-blast' and an example such as :
[https://github.com/Z3Prover/z3/blob/master/examples/c%2B%2B/example.cpp](url) line 568. 
But is there a way where I can store the output of 'bit-blast' in a expression and print it? 
Is there an example program that demonstrates my problem or can you please show me how its done? 
I basically need to see how the bit_vector is broken into statements so that I can fit it into my function.

Thank you.

**Comment by wintersteiger** [comment]
See [tactic_example2](https://github.com/Z3Prover/z3/blob/master/examples/c%2B%2B/example.cpp#L547). The tactic `t` is applied to goal `g` resulting in (multiple) subgoals `r`. In your case, "split-clause" is of course "bit-blast".

**Comment by Harish-uthravalli** [comment]
Yes. But what if I had to work on bit_vectors? 
if I have am expression such as 
x= y+z; 
Can I use 'split-clause' in such examples?

**Comment by wintersteiger** [comment]
Is `bit_vector` the name of one of your classes/modules/functions or are you referring to SMT bit-vectors? You can use "split-clause" if that's a tactic you want to run. It works for any tactic.

**Comment by Harish-uthravalli** [comment]
Yes, I am talking about bv_count type we use in z3 solver with c++. 
#include<z3++.h>  
using namespace std;
using namespace z3;

int main()
{   context c;
    expr x = c.bv_const("x",16);
    expr y = c.bv_const("y",16);  
    expr y = c.bv_const("y",16);  
}

I am sorry if my question does not make any sense.
if I take an example as 
g(c)
g.add(x = y + z )
and I want to use a function ( split-clause or bit-blast I dont know which one will give me my output.) which would give me output in the form of propositional logic.

**Comment by wintersteiger** [comment]
Did you try something like this?

```
tactic t(c, "bit-blast");
apply_result r = t(g);
for (unsigned i = 0; i < r.size(); i++)
    std::cout << r[i] << "\n";
```

**Comment by Harish-uthravalli** [comment]
Yes. I guess 'bit-blast is what I want. 
But why is my program not able to compile this. 

#include<z3++.h>  
using namespace std;
using namespace z3;

int main()
{   
    std::cout << "tactic example 2\n";
    context c;
    expr x = c.real_const("x");
    expr y = c.real_const("y");
    expr z = c.real_const("z");

    goal g(c);
    g.add(x = y + z);
    tactic t(c, "bit-blast");
    apply_result r = t(g);
    for (unsigned i = 0; i < r.size(); i++) {
        std::cout << "subgoal " << i << "\n" << r[i] << "\n";
    }
}


Its saying 
terminate called after throwing an instance of 'z3::exception'
Aborted (core dumped)

**Comment by wintersteiger** [comment]
I don't know. Did you try catching the exception and printing the exception message?

**Comment by Harish-uthravalli** [comment]
How do I print the output of "bit-blasst" on an expression like 
x = y + z where "x" , "y" and "z" are bv_const types. ?
