### ISSUE TITLE
Python Complex Example has a typo

### ISSUE THREAD

**Issue by gmCAD** [Z3Prover/z3#2365]
Line 49 in the complex.py example should be changed from __mul__ to __rmul__

` 

    def __mul__(self, other):
        other = _to_complex(other)
        return ComplexExpr(self.r*other.r - self.i*other.i, self.r*other.i + self.i*other.r)

    def __mul__(self, other):
        other = _to_complex(other)
        return ComplexExpr(other.r*self.r - other.i*self.i, other.i*self.r + other.r*self.i)

`

The second __mul__ should be __rmul__

**Comment by NikolajBjorner** [comment]
because?

**Comment by NikolajBjorner** [comment]
thanks
