### ISSUE TITLE
How to use 'bit-blast' to produce boolean expressions in Propositional form?

### ISSUE THREAD

**Issue by Harish-uthravalli** [Z3Prover/z3#2367]
I have created a function that produces a qdimacs file from a z3 input exrpression.I am trying to create another function that converts bit-vector formulas such as  X = Y + Z to qdimacs. 
I cam across this method called "Bit-blast" that converts such expressions to propositional logic form. 
My expression variables are of type 'bv_const'. 
This is something I have tried. 
#include<z3++.h>  
#include<iostream>
using namespace std;
using namespace z3;

int main()
{   context c;
    tactic t = tactic(c, "bit-blast");
    expr x = c.bv_const("x", 16);
    expr y = c.bv_const("y", 16);
    expr z = c.bv_const("z", 16);

    solver s(t.mk_solver());
    s.add(x = y + z);
}  
Here I need to output the result of bit-blast of my expression " X = Y + Z". 
How do I display the output of "bit-blast"? Are there any reading materials that can help me gain some more knowledge on this topic apart from z3 namespace?

Thank you.

**Comment by NikolajBjorner** [comment]
Suggestion: Check out the tutorial on using tactics on rise4fun.com.
Also https://notebooks.azure.com/nbjorner/projects/z3examples/html/strategies.ipynb

**Comment by Harish-uthravalli** [comment]
But how do I obtain the result of bit-blast and print it?
