### ISSUE TITLE
Timeout not enforced - solver.check()

### ISSUE THREAD

**Issue by Ahmed-anwar** [Z3Prover/z3#2371]
I am facing a problem when setting the global timeout parameter, after a certain threshold value for the timeout (depending on the machine) it is not enforced anymore and the solver seems like it is running forever. On my local machine any value above 6000 triggers this behavior and on our server the behavior starts at around 20000.

I have attached a script that recreates the problem with a test file from the SMT-LIB benchmarks QF_NIA/Leipzig.
[timeout.zip](https://github.com/Z3Prover/z3/files/3350061/timeout.zip)

**Comment by NikolajBjorner** [comment]
the attached formula is solved very quickly in the current master branch.
One way to debug further: save solver state using 

            print(solver.sexpr() + "(check-sat)\n")
            exit()

Then run z3 with smt.random_seed=<n>, where you can set 'n' in case behavior of Z3 is unstable.
Then either identify the place in the code where Z3 doesn't check the cancel flag by dumping a call stack from a debugger or attach the text file.

**Comment by Ahmed-anwar** [comment]
@NikolajBjorner Thank you for your fast reply. I have pulled the master branch again and the issue is resolved.
