### ISSUE TITLE
Could not build ocaml example

### ISSUE THREAD

**Issue by Gueckmooh** [Z3Prover/z3#2373]
Hello, I'm trying to use the z3 api for ocaml program, however neither the opam version nor the git version of the library succeeds to be linked to the ocaml code.
Actually typing `make examples` fails too and gives the following message:

`ocamlc -custom -o ml_example.byte -I api/ml -cclib "-L. -lz3" nums.cma z3ml.cma ../examples/ml/ml_example.ml`

`/usr/bin/ld: ./libz3-static.a(cmd_context.o): undefined reference to symbol '_ZTVN10__cxxabiv121__vmi_class_type_infoE@@CXXABI_1.3'`
`/usr/bin/ld: /usr/lib/libstdc++.so.6: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status`
`File "../examples/ml/ml_example.ml", line 1:`
`Error: Error while building custom runtime system`
`make: *** [Makefile:4504: ml_example.byte] Error 2`

How can I solve this problem ? Thanks in advance.

(ocamlc version 4.05.0, opam version 2.0.4, gcc/g++ version 9.1.0)

**Comment by wintersteiger** [comment]
Not sure why it happens, but it sounds like the static library is missing a reference to the dynamic system library. Can you try adding ` -lstdc++` after `-lz3`?

**Comment by Gueckmooh** [comment]
I tried and it worked, thank's a lot !
