### ISSUE TITLE
ImportError: No module named pkg_resources

### ISSUE THREAD

**Issue by jeffmoore2** [Z3Prover/z3#2374]
**Traceback (most recent call last):
  File "example.py", line 29, in <module>
    from z3 import *
  File "/cygdrive/c/Users/moore.DRYAD/z3/build/python/z3/__init__.py", line 1, in <module>
    from .z3 import *
  File "/cygdrive/c/Users/moore.DRYAD/z3/build/python/z3/z3.py", line 45, in <module>
    from . import z3core
  File "/cygdrive/c/Users/moore.DRYAD/z3/build/python/z3/z3core.py", line 5, in <module>
    import pkg_resources**

Above is the error I am receiving but, I have install z3 and created paths for PYTHONPATH and Path. I am using a Windows 10 OS.

**Comment by NikolajBjorner** [comment]
Did you try "pip install pkg_resources" or "pip3 install pkg_resources" ?

**Comment by jeffmoore2** [comment]
> Did you try "pip install pkg_resources" or "pip3 install pkg_resources" ?
No, I have not. Which directory would I run this command in?

**Comment by jeffmoore2** [comment]
@NikolajBjorner  No, I have not. Which directory would I run this command in?

**Comment by jeffmoore2** [comment]
@NikolajBjorner attempted to install the packages and received this message. 
$ ~/../moore.DRYAD/AppData/Local/Programs/Python/Python37-32/Scripts/pip.exe install pgk_resources
Collecting pgk_resources
  ERROR: Could not find a version that satisfies the requirement pgk_resources (from versions: none)
ERROR: No matching distribution found for pgk_resources

**Comment by NikolajBjorner** [comment]
pkg_resources may work better than pgk_resources

**Comment by Dania-Abuhijleh** [comment]
> Did you try "pip install pkg_resources" or "pip3 install pkg_resources" ?

ERROR: Could not find a version that satisfies the requirement pkg_resources
ERROR: No matching distribution found for pkg_resources

what do i do? (my z3 and python are both x64 and my PYTHONPATH and PATH are correct)

**Comment by andrewvaughanj** [comment]
Try `pip install setuptools`
