### ISSUE TITLE
Unable to verify checksum for libz3.dll

### ISSUE THREAD

**Issue by mcfi** [Z3Prover/z3#2380]
libz3.dll are not compiled with linker flag /RELEASE passed, so when libz3.dll is loaded in windbg, the following warning shows up, which complains about "Unable to verify checksum for libz3.dll"

![image](https://user-images.githubusercontent.com/6384579/60628678-64ef1480-9da7-11e9-8bba-c4a00a22d735.png)

Could we pass linker flag /RELEASE when building z3 on windows? See here for more details: https://docs.microsoft.com/en-us/cpp/build/reference/release-set-the-checksum?view=vs-2019

**Comment by mcfi** [comment]
This issue will be solved by #2383

**Comment by NikolajBjorner** [comment]
I think we merged appropriate updates
