### ISSUE TITLE
Linker error on debug build: export ordinal too large

### ISSUE THREAD

**Issue by mschlaipfer** [Z3Prover/z3#2385]
Trying to do a debug build on Windows using GCC on cygwin results in the following error message:

`/usr/lib/gcc/x86_64-pc-cygwin/7.4.0/../../../../x86_64-pc-cygwin/bin/ld: Error: export ordinal too large: 92123`

Release build works fine.

**Comment by mschlaipfer** [comment]
This seems to be a Cygwin or version issue. I've managed to build with the same approach just fine on my Linux machine.

**Comment by NikolajBjorner** [comment]
Not sure what to do about this.
