### ISSUE TITLE
check-sat switches from unknown to unsat when enabling trace=true and PROOF=true

### ISSUE THREAD

**Issue by mschlaipfer** [Z3Prover/z3#2386]
The second `(check-sat)` command in the following file [1] sometimes (depending on random seed) produces unknown when simply calling z3 on it without additional options. Once adding `trace=true PROOF=true` for generating Axiom Profiler-compatible log files, the outcome changes to unsat and seems to remain stable at unsat.

Is this something we just have to live with due to incompleteness or is there some explanation?

[1] https://gist.github.com/mschlaipfer/ca1cc3ddfb12a25a14fc0a1bf882ff39#file-fun-with-slices-noatlayer-smt2

I'm using z3 version 4.8.6

**Comment by NikolajBjorner** [comment]
It depends on the value of smt.random_seed, and as it uses e-matching isn't complete.
(get-info :reason-unknown) returns:
(:reason-unknown "(incomplete quantifiers)")
