### ISSUE TITLE
z3_fpa.h document missing in website

### ISSUE THREAD

**Issue by cgcgbcbc** [Z3Prover/z3#239]
The document for this file is not generated in http://research.microsoft.com/en-us/um/redmond/projects/z3/group__capi.html

**Comment by wintersteiger** [comment]
The FPA API has been generated correctly, but your link is outdated; the current documentation is hosted on [GitHub](http://z3prover.github.io/api/html/group__capi.html).

I'm now in the process of removing the old website to avoid any confusion.

**Comment by wintersteiger** [comment]
Old website has been removed to avoid any confusion, so I'm closing this issue.
