### ISSUE TITLE
Unkown result on QF_NIA formula

### ISSUE THREAD

**Issue by wintered** [Z3Prover/z3#2392]
```
(declare-fun a () Int) 
(declare-fun b () Int)   
(declare-fun c () Int) 
(declare-fun d () Int)  
(declare-fun e () Int) 
(declare-fun f () Int) 
(declare-fun j () Int) 
(declare-fun g () Int)  
(declare-fun h () Int) 
(declare-fun i () Int)  
(assert
  (and
    (and (<= d 0) (<= 0 d))
    (<= 0 e) 
    (<= 0 f) 
    (<= 0 i) 
    (<= 0 j) 
    (> 1 e) 
    (< f 2) 
    (<= 0 (/ b g))
    (<= 0  (+ c (/ a h ))) 
  )
)
(check-sat)
```
z3 reports `unknown` for this satisfiable formula. Changing ` (and (<= d 0) (<= 0 d))` to `(= d 0)`
gives `sat` with 

```
(model 
  (define-fun f () Int
    0)
  (define-fun b () Int
    1236)
  (define-fun g () Int
    1)
  (define-fun a () Int
    (- 1))
  (define-fun h () Int
    0)
  (define-fun e () Int
    0)
  (define-fun c () Int
    0)
  (define-fun j () Int
    0)
  (define-fun i () Int
    0)
  (define-fun d () Int
    0)
)
```
The model satisfies the constraints.

OS: Ubuntu 18.04
Revision: ee94f8f5ce89651dd5e659f3e876b535f41ad73c

**Comment by NikolajBjorner** [comment]
are these formulas created by a fuzzer or an application? What is the use-case for the divisions?

**Comment by wintered** [comment]
Yes, the formula was constructed by a fuzzer for testing SMT solvers.  We hope to help make modern SMT solvers, like Z3, more reliable and robust.  We very much appreciate your prompt responses and fixes to the bug reports!

**Comment by NikolajBjorner** [comment]
Z3 is inherently incomplete on QF_NIRA. Some additional preprocessing could take of this example, but given that it is created from a fuzzer it isn't interesting.
