### ISSUE TITLE
CMake: Z3Config.cmake not found

### ISSUE THREAD

**Issue by roxaaams** [Z3Prover/z3#2394]
Hello all,

I have built the latest version Z3 using make and GCC without any problems in the Ubuntu system.

However, I got the following message error when trying to build a small C project that uses the Z3 api:

"CMake Error at CMakeLists.txt:9 (find_package): By not providing "FindZ3.cmake" in CMAKE_MODULE_PATH this project has asked CMake to find a package configuration file provided by "Z3", but CMake did not find one.

Could not find a package configuration file provided by "Z3" with any of the following names:

Z3Config.cmake
z3-config.cmake

Add the installation prefix of "Z3" to CMAKE_PREFIX_PATH or set "Z3_DIR" to a directory containing one of the above files. If "Z3" provides a separate development package or SDK, be sure it has been installed."

The CMakeLists.txt file looks like this:

cmake_minimum_required(VERSION 3.14)
project(Z3APITest C CXX)

set(CMAKE_C_STANDARD_REQUIRED ON)
set(CMAKE_C_STANDARD 11)
set(CMAKE_C_EXTENSIONS OFF)

find_package(Z3 REQUIRED CONGIF /home/roscai/Documents//Tools/Z3/cmake)
message(STATUS "Z3_FOUND: ${Z3_FOUND}")
message(STATUS "Found Z3 ${Z3_VERSION_STRING}")
message(STATUS "Z3_DIR: ${Z3_DIR}")

add_executable(Z3APITest EXCLUDE_FROM ALL main.c)

option(FORCE_CXX_LINKER "Force linker with C++ linker" OFF)
if (FORCE_CXX_LINKER)
    # This is a hack for avoiding UBSan linking errors
    message(STATUS "Forcing use of C++ linker")
    set_target_properties(c_example
            PROPERTIES
            LINKER_LANGUAGE CXX
            )
endif()

include_directories("${Z3_C_INCLUDE_DIR}")
include_directories("${Z3_INCLUDE_DIR}")

target_link_libraries(c_example PRIVATE ${Z3_LIBRARIES})
target_include_directories(c_example PRIVATE ${Z3_C_INCLUDE_DIRS})

I appreciate any idea how to solve this matter.

Thank you!

**Comment by NikolajBjorner** [comment]
I don't have much context on CMake to give good advise. 
Here is a suggestion: create a subfolder in z3/examples for your example and copy what is done for c++ CMake files to your own example.

In the worst case, just replace the file "example.cpp" by your own code and you should be unblocked.

**Comment by NikolajBjorner** [comment]
I hope this helped, can you confirm?

**Comment by roxaaams** [comment]
@NikolajBjorner, yes, it helped! Thanks!
