### ISSUE TITLE
it seems that unexpected result with square root check-sat

### ISSUE THREAD

**Issue by gastrodia** [Z3Prover/z3#2398]
(declare-fun a () Real)
(declare-fun b () Real)
(assert (= (^ (+ (^ a 2.0) (^ b 2.0)) (/ 1 2)) 5))
(check-sat)

it return unkown

**Comment by NikolajBjorner** [comment]
fractional or negative powers are not included in the reduction to polynomial arithmetic so Z3 will not be a decision procedure for it.

**Comment by gastrodia** [comment]
thanks @NikolajBjorner ,so I think i can declare c ,set a^2 + b^2 = c^2 and return c in my application
