### ISSUE TITLE
operations on bound variables are not allowed?

### ISSUE THREAD

**Issue by SunBeomSo** [Z3Prover/z3#2401]
In quantified formulas, are operations on bound variables **not** allowed?

For example, please see the OCaml code below, where Z3 raised an exception when bitvector extension operation is performed on a bound variable.

As shown in the comments, the first quantified formula can be generated, but Z3 raises an ```invalid argument``` error for the second quantified formula, i.e., the message ```passed``` is printed but ```passed2``` is not printed.

Is it an intended behavior in Z3?

```
let ctx = Z3.mk_context []

let main () =
  let bit_sort_2 = Z3.BitVector.mk_sort ctx 2 in
  let bit_sort_120 = Z3.BitVector.mk_sort ctx 120 in
  let var = Z3.Expr.mk_const_s ctx "xxx" bit_sort_2 in
  let var = Z3.BitVector.mk_zero_ext ctx 118 var in
  let var2 = Z3.Expr.mk_const_s ctx "yyy" bit_sort_120 in
  let _ = (* works fine *)
    Z3.Quantifier.expr_of_quantifier (Z3.Quantifier.mk_forall_const ctx [var2] (Z3.Boolean.mk_true ctx) None [] [] None None) in
  let _ = print_endline "passed" in (* will be printed *)
  let _ = (* raises an exception *)
    Z3.Quantifier.expr_of_quantifier (Z3.Quantifier.mk_forall_const ctx [var] (Z3.Boolean.mk_true ctx) None [] [] None None) in
  let _ = print_endline "passed2" in (* will NOT be printed *)
  () 

let _ = main ()
```

**Comment by NikolajBjorner** [comment]
var is defined as an interpreted expression. You can only quantify over uninterpreted constants that get abstracted into bound variables. It doesn't make sense to abstract other sub-expressions as they have meaning, such as being a zero extension of a bit-vector.
The argument [var] is therefore invalid.
