### ISSUE TITLE
Sat formula reports unsat

### ISSUE THREAD

**Issue by Ahmed-anwar** [Z3Prover/z3#2402]
I was using the file aproveSMT3216048788972107323.smt2 from the SMT-LIB benchmarks with the Z3 python API and after applying the tactic "nla2bv" with the parameter nla2bv_max_bv_size set to 3 the solver reported an unsat status.

I have attached a python script to show the issue along with the file. 

[bug.zip](https://github.com/Z3Prover/z3/files/3397902/bug.zip)

**Comment by NikolajBjorner** [comment]
The nla2bv tactic performs an under-approximation. Thus, if it produces sat the goal is really sat, but if it returns unsat it may still be sat. 
You can access this information from the "prec" method defined on Goal.
So you have to extract the subgoal from tactic(goals, **params) to access this information, especially if you find yourself using various tactics whose semantics you are unsure about.
Or you can just know that nla2bv is an under-approximation from the get-go.
