### ISSUE TITLE
z3 assertion violation in theory_arith_nl

### ISSUE THREAD

**Issue by liqing9399** [Z3Prover/z3#2404]
ASSERTION VIOLATION

**Comment by liqing9399** [comment]
This problem occurs when I call the solver.check() multiple times, how can I solve it?

ASSERTION VIOLATION
File: /home/litao/test_z3/z3/src/smt/theory_arith_nl.h
Line: 1553
n != nm

**Comment by NikolajBjorner** [comment]
Share a self-contained repro.

**Comment by liqing9399** [comment]
Did not reproduce
