### ISSUE TITLE
Incremental Solving

### ISSUE THREAD

**Issue by YuanbinCN** [Z3Prover/z3#2407]
Hi,
I would like to use z3py to solve a synthesis problem in embedded systems. There are lots of variables to be determined, so the scalability issue is an important factor in my tool. One way to handle it is the usage of incremental design.  The code looks like:

x, y = Reals('x y')
s = Solver()
s.push()
s.add(x>10)
s.check()
s.model()
s.pop()
s.add(y > x)
s.check()
s.model()

The solver is divided into two steps and I got two results from these two steps: [x = 11] and [y = 1, x = 0].
Actually what I want to do in the second step is to fix the value of x solved in the first step and then solve value of y only in this step. Although this question looks like the issue https://github.com/Z3Prover/z3/issues/2220, I am not able to find the solution.
Any suggestions are welcome. Thanks.

**Comment by NikolajBjorner** [comment]
from z3 import *
x, y = Reals('x y')
s = Solver()
s.push()
s.add(x>10)
s.check()
m = s.model()
print(m)
s.pop()
s.add(y > x)
s.add(m[x] == x)
s.check()
print(s.model())

**Comment by YuanbinCN** [comment]
@NikolajBjorner Any automated way to add model m into the model with new assertions. I have many variables in each incremental step, so I need the automated way to do it.
Thanks for any suggestion.

**Comment by NikolajBjorner** [comment]
The model objects provide iterators in case this helps

**Comment by YuanbinCN** [comment]
@NikolajBjorner I want to copy all the old states into the new assertions. Bit do not assign variables one by one. I try to use s.import_model_converter(m). But it always return "AttributeError: Solver instance has no attribute 'import_model_converter'
". It looks strange.
