### ISSUE TITLE
WARNING: unhandled theory N3smt17theory_diff_logicINS_7rdl_extEEE

### ISSUE THREAD

**Issue by prakashmurali** [Z3Prover/z3#2410]
I am running on Z3 on this problem https://github.com/prakashmurali/random/blob/master/z3_warning. I am using the optimization API from Python. While running check(), z3 goes into a loop of printing "WARNING: unhandled theory N3smt17theory_diff_logicINS_7rdl_extEEE". 
The solver runs to completion and returns sat. On smaller instances of my problem (which are also sat), this warning doesn't appear. I would like to understand what is triggering this warning. Do you know what I should look at to fix this?

I can supply more instances if that helps. Thanks!

**Comment by NikolajBjorner** [comment]
should be fixed now

**Comment by prakashmurali** [comment]
Thanks a lot for the quick response!
