### ISSUE TITLE
regarding evaluations in a current model

### ISSUE THREAD

**Issue by SunBeomSo** [Z3Prover/z3#2411]
While playing with a toy program, I got a model
```
(define-fun x__6@I_2 () (_ BitVec 256)
  #x0000000000000000000000000000000000000000000000000000000000000001)
(define-fun y__8@I_2 () (_ BitVec 256)
  #xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff)
(define-fun u__4@E_1 () (Array (_ BitVec 256) (_ BitVec 256))
  ((as const (Array (_ BitVec 256) (_ BitVec 256)))
  #x0000000000000000000000000000000000000000000000000000000000000000))
(define-fun u__4@X_2 () (Array (_ BitVec 256) (_ BitVec 256))
  (store ((as const (Array (_ BitVec 256) (_ BitVec 256)))
         #x0000000000000000000000000000000000000000000000000000000000000000)
       #x0000000000000000000000000000000000000000000000000000000000000000
       #x0000000000000000000000000000000000000000000000000000000000000001))
(define-fun u__4@E_2 () (Array (_ BitVec 256) (_ BitVec 256))
  ((as const (Array (_ BitVec 256) (_ BitVec 256)))
  #x0000000000000000000000000000000000000000000000000000000000000000))
(define-fun u__4@X_1 () (Array (_ BitVec 256) (_ BitVec 256))
  ((as const (Array (_ BitVec 256) (_ BitVec 256)))
  #x0000000000000000000000000000000000000000000000000000000000000000))
(define-fun @LOC_2 () (_ BitVec 4)
  #x2)
(define-fun @LOC_1 () (_ BitVec 4)
  #x1)
```

Then, I attempted to evaluate ```(select b__10 ((_ int2bv 256) 0))``` in the above model. As you can see, there is no corresponding assignment for ```b__10``` in the model. However, Z3 answered the evaluated result is  ```#b00```.

Could you explain how is it possible?

**Comment by NikolajBjorner** [comment]
The background should be as follows: Some variables are don't cares with respect to satisfiable assignments. Then Z3 is free to not list them in a model. Evaluation with respect to a model has two modes: either it evaluates expressions to ground values or it evaluates to the most simplified expression with respect to the don't cares. The first mode is default. So it comes up with an interpretation for unbound variables on the fly and updates the model accordingly. I believe this is what you are noticing.
