### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by prakashmurali** [Z3Prover/z3#2412]
Z3 seg faults on this problem https://github.com/prakashmurali/random/blob/master/z3_seg_fault

I am using Z3py for an instance of interval scheduling. The issue seems to be related to if-then-else. When I encode my overlapping intervals (s1, f1) (s2, f2) using 
intervals_overlap = And(s2 <= f1, s1 <= f2), the code works. But when I want more fine-grained overlap checks, using If(f1-s2 < f2-s1, f1-s2, f2-s1)) > some-constant, then the seg fault appears. Please look into it. I can supply more instances if that helps. 

I am running the master version.

Thanks!

**Comment by NikolajBjorner** [comment]
ASSERTION VIOLATION
File: D:\z3\src\util/lp/lar_core_solver_def.h
Line: 269
m_r_solver.non_basic_columns_are_set_correctly()

**Comment by levnach** [comment]
It seems to be solved by the pull request [](https://github.com/Z3Prover/z3/pull/2459)
