### ISSUE TITLE
Self referential array value in model

### ISSUE THREAD

**Issue by LeventErkok** [Z3Prover/z3#2420]
Unfortuantely github doesn't allow me to re-open old closed issues. This is essentially a duplicate of http://github.com/Z3Prover/z3/issues/2127

For this benchmark:

```
(declare-fun q (Int) Int)
(check-sat)
(get-value (q))
```

z3 gives:

```
sat
((q (_ as-array q)))
```

While this is consistent, it's hard for up-stream tools to deal with it. When http://github.com/Z3Prover/z3/issues/2127 was first reported, you actually fixed it, so this was no longer the case; but looks like the behavior came back.

Was this intentional?

**Comment by NikolajBjorner** [comment]
Now it is
      ((q ((as const Array) 0)))
