### ISSUE TITLE
Z3 gives unknown on QF_NIRA formula

### ISSUE THREAD

**Issue by muchang** [Z3Prover/z3#2421]
Hi,
For this QF_NIRA formula:
```
(declare-fun a () Int)
(declare-fun b () Int)
(assert (= b (/ a b) 2))
(check-sat)
```
Z3 reports `unknown` on this formula, while the latest release Z3-4.8.5 can give `sat` result.

OS: Ubuntu 18.04
Revision: aff4b3022ad9a4c65364c82c2da3bcbd62052189

**Comment by NikolajBjorner** [comment]
it is not a bug, handling of /, especially over Int is super partial
