### ISSUE TITLE
Does exception msg "canceled" mostly mean timeout?

### ISSUE THREAD

**Issue by leonardoalt** [Z3Prover/z3#2425]
On my side of the API I want my tool to report errors when there's an exception from Z3, except if it's due timeout. Can I assume that if the msg contains "canceled" the timeout (or other resource) was the reason?

**Comment by NikolajBjorner** [comment]
canceled covers timeout, resource limit and user-interrupts.

**Comment by leonardoalt** [comment]
Ok, sounds good. Thanks!
