### ISSUE TITLE
minimize with bit-vectors not working on arm64

### ISSUE THREAD

**Issue by waskyo** [Z3Prover/z3#2427]
Hi, on arm64, this formula:

```smt2
(declare-fun transfer_size () (_ BitVec 64))
(assert (bvsgt transfer_size #x0000000000000028))
(minimize transfer_size)
(check-sat)
(get-model)
```

gives me this erroneous result:

```smt2
sat
(model 
  (define-fun transfer_size () (_ BitVec 64)
    #x0000000000000000)
)
```

on x86_64 it works fine though:

```smt2
sat
(model 
  (define-fun transfer_size () (_ BitVec 64)
    #x0000000000000029)
)
```

I used this python program to generate it:

```python
#!/usr/bin/env python

import z3

buffer_size = z3.BitVecVal(40, 64)
transfer_size = z3.BitVec('transfer_size', 64)

solver = z3.Optimize()
solver.add(transfer_size > buffer_size)
solver.minimize(transfer_size)
solver.check()
print("%s" % solver.model())
```

Both python and z3 binary give me the bad answers.

Some other notes:
- If I use `z3.Solver`instead of `z3.Optimize` it works fine.
- If I remove the `minimize` call in the python program I also get a bad answer:
`[transfer_size = 40]`. I don't know how to reproduce this with the command line tool. 
- I tried this on debian 9, ubuntu 16.04 and ubuntu 18.04, all with the same result.
- I tried it with both the released 4.8.5 (compiled from source) and master (as of aff4b3022ad9a4c65364c82c2da3bcbd62052189)

Happy to help debug if you don't have easy access to an arm machine.

**Comment by NikolajBjorner** [comment]
It is easiest to debug from the binary. The likely issues are around endianess assumptions and how numbers within 64 bit representation are handled. We don't have amd64 build machines and as such is not something I can offer timely support for. Given that the example is so small, it should be easy enough to debug by running builds that have tracing enabled (debug builds work for this). Then trace or -tr:opt -tr:sat to start with and observe the difference in behavior between the builds.

**Comment by DvonHolten** [comment]
he talks about arm64 - not amd64. maybe something with compiler...

**Comment by NikolajBjorner** [comment]
Yes, thanks. I also meant arm, but mistakingly wrote amd. amd64 is well tested, arm is not.

**Comment by waskyo** [comment]
I did a debug build on the arm64 machine and before I could get to compare behaviors this is what I got:

```
ASSERTION VIOLATION
File: ../src/sat/sat_solver.cpp
Line: 903
!l.sign() || value(v) == l_false
(C)ontinue, (A)bort, (S)top, (T)hrow exception, Invoke (G)DB
```

I get no other output from -tr:opt or -tr:sat. I'll debug more later this afternoon, but figured I'd post this now in case that points you in some useful direction

**Comment by NikolajBjorner** [comment]
This points to abuse of char. The sat_solver uses vectors of char to store values that get casted.
In this case m_assignment is defined as char_vector instead of svector<lbool>. The lbool type is an enumeration with values -1, 0, 1. Likely fixes are to change char_vector to svector<lbool>

**Comment by NikolajBjorner** [comment]
I updated the vectors in sat_solver to avoid char.

**Comment by waskyo** [comment]
That did the trick, thank you!

**Comment by NikolajBjorner** [comment]
it is unlikely the only portability bug. Are you able to run z3test regressions and test-z3 -a?

**Comment by waskyo** [comment]
For sure. I ran both with a debug build, would a release build be useful too?

For the regressions I did:

```
cd z3
git clone https://github.com/z3prover/z3test
python z3test/scripts/test_benchmarks.py build/z3 z3test/regressions/smt2
```

Output is here: [regressions.txt](https://github.com/Z3Prover/z3/files/3429317/regressions.txt)

For test-z3 I did:

```
cd build
make -j8 test-z3
./test-z3 -a
```

Output is here: [test-z3.txt](https://github.com/Z3Prover/z3/files/3429376/test-z3.txt)

Let me know if I missed a step or you'd like me to run anything else. FWIW, this was all on a debian 9 machine.

**Comment by NikolajBjorner** [comment]
looks fine: debug assertions should trigger if there is anything clearly wrong. Thanks.
