### ISSUE TITLE
time difference in soft and hard constraints

### ISSUE THREAD

**Issue by muqsitazeem148** [Z3Prover/z3#2429]
Suppose, I have a bunch of constraints as follows:

s.add(c1)
s.add(c2)
...
s.add(cn)

z3 took 2 seconds to find that it's SAT.

Now, I add the same set of constraints but soft:

s.add_soft(c1)
s.add_soft(c2)
...
s.add_soft(cn)

then z3 will try to satisfy as many as possible from constraints c1, c2,..., cn.

It took ~150 seconds to find the satisfiability of the constraints with penalty zero.

What is the reason behind this huge timing difference?

**Comment by rainoftime** [comment]
In the first case, you are trying to solve a constraint satisfiability problem, e.g., SAT problem (if `c_i` are Boolean formulas)
~~~~
s.add(c1)...
~~~~
In the second case, you are trying to solve a mathematical optimization (or "maximum satisfiability") problem, e.g., MaxSAT problem (if `c_i` are Boolean formulas)
~~~~
s.add_soft(c1),..
~~~~

Empirically, the later problem is harder than the first one. 
In the implementation, to solve a single MaxSAT problem, Z3 may solve a large number of SAT instances.
