### ISSUE TITLE
 Missing Bulk mode for adding Expressions to Z3 via Java-Wrapper

### ISSUE THREAD

**Issue by dbinkele** [Z3Prover/z3#2435]
Looking a the class Solver.java in package com.microsoft.z3 one can see that the method ' public void add(BoolExpr... constraints)' simply cycles over the constraints and for each calls Z3 via the Native-Interface. This poses performance issues.

This issue is well known for mathematical Solvers like Gurobi or Cplex. They offer either a bulk versions of such methods on the Native-Interface or provide buffering for the whole model in the Java-Wrapper. Upon a call to a 'update'-method the model is transferred to the native Code.

Offering a real bulk-version of the add-method (and also other methods for creating a model) where all constraints of the parameters are transferred to Z3-native-code in one go, would make Z3 more amenable to be used via Language-Wrappers.

**Comment by NikolajBjorner** [comment]
The code you are looking at calls native directly. Adding a bulk mode native version would end up performing essentially the same loop modulo setup overhead of Java calling C. Have you observed a measurable performance hit with this approach?
