### ISSUE TITLE
Evaluating expressions in different Z3 contexts

### ISSUE THREAD

**Issue by SunBeomSo** [Z3Prover/z3#2436]
**[Question in one sentence]**
When evaluating expressions w.r.t a given model, does Z3 care the Z3 context at the time the model was obtained?

The concrete situation that I encountered is as follows.

1. Set the Z3 timeout as 1 seconds (I used OCaml api):
Z3.mk_context [("timeout", string_of_int 1000)]

2. Assume I got a model ```M``` in the above Z3 context.  Further assume that the model includes an assignment ```[a |-> 10]```.

3. Now set the Z3 timeout as 10 seconds:
Z3.mk_context [("timeout", string_of_int 10000)]

4. Finally, suppose I evaluate ```a``` with respect to the model ```M```, obtained in step 2; the result is ```0```. However, I think the result should be ```10``` according to my assumption in step 2 (the ```M``` includes an assignment ```[a |-> 10]```).

Is it an intended behavior? I know the Z3 context in step 4 is different from that of step 2, but do not understand why it matters. Making consistent Z3 context (e.g., remove step 3) resolved this issue, but I am curious about this situation.

**Comment by NikolajBjorner** [comment]
Answer in one sentence: yes it cares
You should maintain complete separation of expressions, models, solvers that are created in different contexts. Lower levels of Z3 doesn't check that you mix expressions from different contexts.

**Comment by SunBeomSo** [comment]
Thanks. I close the issue.
