### ISSUE TITLE
Z3 hangs (doesn't timeout)

### ISSUE THREAD

**Issue by GUIpsp** [Z3Prover/z3#2437]
Hello,

I'm currently using z3 on a rather large application, and in some cases z3 doesn't timeout even when the timeout is set (and continues pegging the CPU).

I'm using the Java z3 bindings.

I was unable to find a standalone repro, but here's the toString() of the solver anyways:

[toString.txt](https://github.com/Z3Prover/z3/files/3431969/toString.txt)

I was also able to generate a flamegraph of traces collected while it's hung. Here's a screenshot:

![Flamegraph](https://user-images.githubusercontent.com/386686/61882262-09203300-aef0-11e9-9939-ff8c10dc0362.png)

Please let me know if there's any way I can provide more info.

Thanks

**Comment by NikolajBjorner** [comment]
seems it is spending all time in big-num arithmetic. Conflict resolution is not a state where Z3 can safely time out and resume. I don't want to change this code as we should rely on a new solver going forward.

**Comment by NikolajBjorner** [comment]
solver behavior has changed, it returns unknown quickly
