### ISSUE TITLE
Documentation of command language is hard to find

### ISSUE THREAD

**Issue by simsong** [Z3Prover/z3#2440]
I am looking for documentation of the command language used by Z3 for input files. I'm unable to find it. It would be useful if the README file had a link to the documentation, rather than just to all of the papers. Where is the documentation?

**Comment by NikolajBjorner** [comment]
* The SMTLIB format is documented on http://smtlib.cs.uiowa.edu/. It is so well established by SMT solvers that we may have omitted links to it.

**Comment by NikolajBjorner** [comment]
Link added in "background" page

**Comment by NikolajBjorner** [comment]
Also updated readme http://smtlib.cs.uiowa.edu/language.shtml

**Comment by simsong** [comment]
Thanks. So Z3 implements this entire SMTLIB language with 100% adherence to the standard as presented on this unrelated website?

**Comment by NikolajBjorner** [comment]
That is basically what users expect.
