### ISSUE TITLE
Z3 rise4fun does not know seq.nth

### ISSUE THREAD

**Issue by OrenGitHub** [Z3Prover/z3#2444]
Hi,

It seems z3 rise4fun does not know `seq.nth`.
Here is a [permalink](https://rise4fun.com/Z3/TJt9).
It says: `unknown function/constant seq.nth`
This example works fine with master.

**Comment by NikolajBjorner** [comment]
rise4fun is using an older version of Z3. It will be updated sometime in the future, but not too soon.
