### ISSUE TITLE
Disproving transitivity of subtraction succeeds and fails with theoretically equivalent examples

### ISSUE THREAD

**Issue by mikesol** [Z3Prover/z3#2446]
From [this SO post](https://stackoverflow.com/questions/57260272/proving-transitivity-in-z3-fails-with-arrays).

I am trying to work with arrays in `z3` and I am having trouble proving transitivity for arrays.  I am able to do it for functions, though.  The first function fails whereas the second succeeds.  Is there a subtle difference between functions and arrays that I'm not seeing here?

```python
from z3 import *

def test_not_transitive():
  binop = ArraySort(IntSort(), ArraySort(IntSort(), IntSort()))
  a, b = Consts('a b', binop)
  w, x, y, z = Ints('w x y z')
  s = Solver()
  s.add(a == Lambda(x, Lambda(y, x - y)))
  s.add(b == Lambda(w, Lambda(z, a[z][w])))
  s.push()
  s.add(a != b)
  assert s.check() == sat
  s.pop()
  s.push()
  s.add(a == b)
  assert s.check() == unsat # this fails and yields sat, don't know why

def test_not_transitive2():
  a = Function('a', IntSort(), IntSort(), IntSort())
  b = Function('b', IntSort(), IntSort(), IntSort())
  w, x, y, z = Ints('w x y z')
  s = Solver()
  s.add(ForAll([x,y], a(x,y) == x - y))
  s.add(ForAll([w,z], b(w,z) == a(z, w)))
  s.push()
  s.add(a != b)
  assert s.check() == sat
  s.pop()
  s.push()
  s.add(a == b)
  assert s.check() == unsat # this succeeds
```

**Comment by NikolajBjorner** [comment]
test2 succeeds for a reason you are not expecting. Z3 does not overload equality between function declarations. Therefore, a != b is "True" and a == b is "False" because the pointers are different.
I have removed some asserts from pre-lambda days. Then the second checksat returns unsat (comment out the first check-sat to get an answer).
