### ISSUE TITLE
SIGSEGV  with `--staticbin`

### ISSUE THREAD

**Issue by SaswatPadhi** [Z3Prover/z3#2457]
A statically linked z3 binary compiled from the master branch fails to run and terminates with a segmentation fault (SIGSEGV signal).

Steps to reproduce: (tested on Debian 10)
1. `git checkout master`
2. `python scripts/mk_make.py --staticbin`
3. `cd build && make`
4. `./z3 -v`

Without the `--staticbin` flag, the compiled z3 binary runs as expected.

**Comment by NikolajBjorner** [comment]
Perhaps related to recent use of lpthread. 
https://stackoverflow.com/questions/35116327/when-g-static-link-pthread-cause-segmentation-fault-why

**Comment by fpoli** [comment]
Is there any workaround to statically compile z3?

**Comment by fpoli** [comment]
The `python scripts/mk_make.py --staticbin` command generates a `build/config.mk` containing `LINK_EXTRA_FLAGS= -lpthread`. If I manually modify this to `LINK_EXTRA_FLAGS= -pthread -Wl,--whole-archive -lpthread -Wl,--no-whole-archive` (as suggested in the SO question) then the compiled z3 runs fine. However, I'm not sure how to generate this modified configuration using the `mx_make.py` script.

**Comment by SaswatPadhi** [comment]
I pulled the latest changes and rebuilt z3 on my Debian machine -- works as expected with both `--staticbin` and `--staticlib`.

Thanks @NikolajBjorner  and @fpoli.

**Comment by SaswatPadhi** [comment]
Actually, I just noticed that although the build was successful, the `z3` binary still fails on my Debian machine with `SIGSEGV` ...

@fpoli: Does `z3` run as expected on your Ubuntu machine?

Sorry for the confusion!

**Comment by fpoli** [comment]
@SaswatPadhi on various Ubuntu 16.04 computers that I tried yes, it runs as expected. Before, `z3 --version` was enough to cause a segmentation fault.

Have you checked if your `build/config.mk` actually contains `LINK_EXTRA_FLAGS= -Wl,--whole-archive -lpthread -Wl,--no-whole-archive`?

**Comment by SaswatPadhi** [comment]
Hello,

Sorry for the delay in getting back -- I had a deadline.

I pulled the latest changes and checked again that `build/config.mk` contains `LINK_EXTRA_FLAGS= -Wl,--whole-archive -lpthread -Wl,--no-whole-archive`. Here is my `config.mk` file:

```make
PREFIX=/usr
CC=gcc
CXX=g++
CXXFLAGS= -D_MP_INTERNAL -DNDEBUG -D_EXTERNAL_RELEASE -D_USE_THREAD_LOCAL  -std=c++11 -fvisibility=hidden -c -mfpmath=sse -msse -msse2 -O3 -D_LINUX_ -fPIC
CFLAGS= -D_MP_INTERNAL -DNDEBUG -D_EXTERNAL_RELEASE -D_USE_THREAD_LOCAL   -fvisibility=hidden -c -mfpmath=sse -msse -msse2 -O3 -D_LINUX_ -fPIC
EXAMP_DEBUG_FLAG=
CXX_OUT_FLAG=-o 
C_OUT_FLAG=-o 
OBJ_EXT=.o
LIB_EXT=.a
AR=ar
AR_FLAGS=rcs
AR_OUTFLAG=
EXE_EXT=
LINK=g++
LINK_FLAGS=
LINK_OUT_FLAG=-o 
LINK_EXTRA_FLAGS=-Wl,--whole-archive -lpthread -Wl,--no-whole-archive 
SO_EXT=.so
SLINK=g++
SLINK_FLAGS=-shared
SLINK_EXTRA_FLAGS=-lpthread  -Wl,-soname,libz3.so
SLINK_OUT_FLAG=-o 
OS_DEFINES=-D_LINUX_
```

But I still get:
```bash
$ ./z3 --version
"./z3 --version" terminated by signal SIGSEGV (Address boundary error)
```

**Comment by NikolajBjorner** [comment]
Could you if possible dig deeper? e.g., modify the SLINK_EXTRA_FLAGS

**Comment by SaswatPadhi** [comment]
I tried to modify the `SLINK_EXTRA_FLAGS` as well, as below

```
SLINK_EXTRA_FLAGS=-Wl,--whole-archive -lpthread -Wl,--no-whole-archive -Wl,-soname,libz3.so
```

but it did not help.

Also, this issue is reproducible on **Ubuntu 19.04** as well.

**Comment by fpoli** [comment]
I can reproduce the issue by using an Ubuntu 19.04 Docker image

**Comment by fpoli** [comment]
[This SO question](https://stackoverflow.com/questions/58848694/gcc-whole-archive-recipe-for-static-linking-to-pthread-stopped-working-in-rec) seems to explain the difference between Ubuntu 16.04 and 19.04, but no solution is provided.

On Ubuntu 16.04, indeed, the output of `nm z3 | grep pthread_mutex_lock` contains `T pthread_mutex_lock`, while on 19.04 it contains `W pthread_mutex_lock`.

**Comment by fpoli** [comment]
@SaswatPadhi Can you try on Debian with `LINK_EXTRA_FLAGS=-Wl,--whole-archive -lpthread -lrt -Wl,--no-whole-archive`? That should work.

**Comment by SaswatPadhi** [comment]
Awesome! I confirm that z3 compiles and runs as expected on both Debian 10.2 and Ubuntu 19.04.

Thanks @fpoli, @NikolajBjorner.
