### ISSUE TITLE
(check-sat) vs (check-sat-using default), and :auto_config false

### ISSUE THREAD

**Issue by mschwerhoff** [Z3Prover/z3#2467]
I've read Stackoverflow threads [37443308](https://stackoverflow.com/questions/37443308) and [28603229](https://stackoverflow.com/questions/28603229), and understood the following: `(check-sat-using default)` is as close as it gets to `(check-sat)`, but isn't exactly the same because in the latter case, Z3's heuristics might suggest a sequence of tactics that differs from the `default` one.

Running a very recent nightly of Z3 with `-v:10` seems to confirm that: for [this example](https://github.com/Z3Prover/z3/files/3467291/logfile.smt2.txt), which *succeeds* (unsat) with `(check-sat)` but *fails* with `(check-sat-using default)`, I get the following output:

    (check-sat)                 | (check-sat-using default)
    ----------------------------|------------------------------
    (smt.propagate-values)      | (smt.propagate-values)
    (smt.nnf-cnf)               | (smt.nnf-cnf)
    (smt.reduce-asserted)       | (smt.reduce-asserted)
    (smt.refine-injectivity)    | (smt.refine-injectivity)
    (smt.pattern-inference)     | (smt.pattern-inference)
    (smt.maximizing-bv-sharing) | (smt.maximizing-bv-sharing)
    (smt.reduce-asserted)       | (smt.reduce-asserted)
    (smt.simplifier-done)       | (smt.simplifier-done)
                                | (smt.tactic start)
    (smt.propagate-values)      | (smt.propagate-values)
    (smt.nnf-cnf)               | (smt.nnf-cnf)
    (smt.reduce-asserted)       | (smt.reduce-asserted)
    (smt.refine-injectivity)    | (smt.refine-injectivity)
    (smt.pattern-inference)     | (smt.pattern-inference)
    (smt.maximizing-bv-sharing) | (smt.maximizing-bv-sharing)
    (smt.reduce-asserted)       | (smt.reduce-asserted)
    (smt.simplifier-done)       | (smt.simplifier-done)
    (smt.searching)             | (smt.searching)
                                | (smt.giveup quantifiers)

(I've removed additional output which I obtained for `check-sat-using`, but which looked irrelevant to me).

What I would ultimately like to do is to parallelise Z3, e.g. 

    (check-sat-using
      (par-or
        (using-params default :random_seed 0)
        (using-params default :random_seed 77)))

However, various tests from our test suite (the [Viper verification infrastructure](http://viper.ethz.ch/)) then fail, and also with just `(check-sat-using default)`.

**Questions:**

☐ Z3 option `:auto_config` is set to `false`. Given that, will Z3 always apply the same tactics upon `(check-sat)`, or can this still vary from example to example?

☐ Is there any other Z3-internal way I can `par-or` multiple "default" provers with different random seeds?

Thank you,
Malte

**Comment by NikolajBjorner** [comment]
The solver used by check-sat uses information from the assertions to spawn a solver. So it depends on the input what tactic is used. It also has a mode where it handles incremental uses of Z3. The default tactic is used by the check-sat solver, not the other way. The check-sat call uses the value of set-logic to specialize solvers.

**Comment by NikolajBjorner** [comment]
The default tactic includes pre-processing simplification. 
For your formula, this results in removing the helpful trigger for your pattern. 
Notice that the pattern refers to an expression that is not inside of the formula, 
it talks about at2 .. i xs and not at1 ... xs i. 
To get the incremental smt behavior the 'smt' tactic is a better match.
