### ISSUE TITLE
A very very strange behaviour for a simple problem

### ISSUE THREAD

**Issue by cgcgbcbc** [Z3Prover/z3#247]
```
(declare-fun a() Real)
(declare-fun b() Bool)
(declare-fun c() Int)

(assert (distinct a 0.0))

(assert (= b (distinct (* a a) 0.0)))

(assert (= b false))

;(assert (= c 0))

(check-sat)
```

This is unsat, but if uncomment the last assert, it will be unknown, although `c=0` has nothing to do with the above assertions.

**Comment by cgcgbcbc** [comment]
I found that using `(check-sat-using (then simplify bit-blast qfnra))` will solve this problem according to http://stackoverflow.com/questions/12929633/mixing-reals-and-bit-vectors
But how can I use this in API :( ?

**Comment by wintersteiger** [comment]
`(then ... )` is a tactic that can be constructed via the API as well. To learn about tactics, check out the [strategies tutorial](http://rise4fun.com/Z3/tutorial/strategies). For the Python API, as an example, check out the [`AndThen(...)`](http://z3prover.github.io/api/html/namespacez3py.html#abfb617bc5ba78abc4a0e3247f7994d67) tactic constructor. Built-in tactics are simply referred to by their names as a string (See `Tactic(...)` constructor), and you can get a list of built-in tactics by calling [tactics()](http://z3prover.github.io/api/html/namespacez3py.html#a85e8ba1129781ae18aa1a59cf0c51577). Once constructed, a tactic can be applied to a goal (see [`apply(...)`](http://z3prover.github.io/api/html/z3py_8py_source.html#l06696)) or it can be turned into a solver (see [`Tactic.solver()`](http://z3prover.github.io/api/html/classz3py_1_1_tactic.html#a0a7dab8f4093ebd6f6377d99f67e9569)).
