### ISSUE TITLE
ocaml-num is deprecated - switch to Zarith is recommended

### ISSUE THREAD

**Issue by XVilka** [Z3Prover/z3#2471]
Previously Num was a part of OCaml compiler. Recently it was extracted out of it, and deprecated if favor of Zarith:

> This is a legacy library. It used to be part of the core OCaml distribution (in otherlibs/num) but is now distributed separately. New applications that need arbitrary-precision arithmetic should use the Zarith library (https://github.com/ocaml/Zarith) instead of the Num library, and older applications that already use Num are encouraged to switch to Zarith. Zarith delivers much better performance than Num and has a nicer API.

from the https://github.com/ocaml/num/

**Comment by NikolajBjorner** [comment]
Note that it adds dependency on GMP and Num is used for interfacing and does not use expensive operations on the ocaml side.

**Comment by NikolajBjorner** [comment]
What do other OCaml users think of swapping Num by Z? @protz, @c-cube, @grantpassmore.

**Comment by c-cube** [comment]
I like Zarith a lot more than `num`, it's also faster (small integers are actual OCaml integers, and GMP is fast). However I'd understand if the dependency on GMP was a drawback for the core maintainers.

**Comment by NikolajBjorner** [comment]
it is mainly about what users want/need.

**Comment by c-cube** [comment]
Then I think I'd be in favor of moving to Zarith. We convert numbers to Zarith anyway at Imandra.

**Comment by msprotz** [comment]
Sorry for the delay Nikolaj. Yes, Zarith is the right choice. Num is going to disappear possibly very soon.

**Comment by NikolajBjorner** [comment]
done
