### ISSUE TITLE
C++ API More Examples(Seq, Array etc.)

### ISSUE THREAD

**Issue by alpaylan** [Z3Prover/z3#2474]
When I was looking at the c++ api example file, I noticed the lack of various structures that exist in the tutorial rise4fun. I think adding more examples is necessary for giving a better experience to beginners.

**Comment by NikolajBjorner** [comment]
you are certainly invited to add pull requests. 
I mainly use the python API for examples and with jupyter notebooks available provides an easy way to run them. 

https://notebooks.azure.com/nbjorner/projects/z3examples
