### ISSUE TITLE
Finding soft constraints which were dropped to satisfy the formula using python Z3 API.

### ISSUE THREAD

**Issue by pankajkalita** [Z3Prover/z3#2480]
```
from z3 import *
s = Optimize()
x = Int('x')
y = Int('y')
z = Int('z')
s.add_soft(x > 0,  id= 1)
s.add_soft(x <= -1, id= 2)
s.add_soft(Or((x > 0),(y < 1)) ,  id= 3)
s.add_soft(y > 2, id= 4)
s.add_soft(y > 3, id= 5)
s.add_soft(y <= -1, id= 6)
s.add(z == x + y)
print(s.check())
print(s.objectives())
```

In the above python code using Z3, I am trying to get the constraints which are being dropped to  make the formula SAT (trying to get MAXSAT). 
If I use `(get-objectives)` in smt-lib2 format for this example I can get which constraints are being dropped.
So how to do the same using python API for Z3.

**Comment by NikolajBjorner** [comment]
There are a few ways to obtain the values of objectives.
When you create an optimization objective over the API it returns a "handle".
The handle can be queried for the value after optimization. The model can also be used.

from z3 import *
s = Optimize()
x = Int('x')
y = Int('y')
z = Int('z')
h1 = s.add_soft(x > 0,  id= 1)
h2 = s.add_soft(x <= -1, id= 2)
h3 = s.add_soft(Or((x > 0),(y < 1)) ,  id= 3)
s.add_soft(y > 2, id= 4)
s.add_soft(y > 3, id= 5)
s.add_soft(y <= -1, id= 6)
s.add(z == x + y)
print(s.check())
print(s.objectives())
print(s.model())
mdl = s.model()
print([mdl.eval(f) for f in s.objectives()])
print(h1.value())
print(h2.value())
print(h3.value())
