### ISSUE TITLE
z3 minimize clarification

### ISSUE THREAD

**Issue by muqsitazeem148** [Z3Prover/z3#2484]
I am working on a constraint satisfaction problem in which there's an objective that I am trying to minimize, along with finding a solution. I have encoded the constraints in z3py. The constraint file looks like this:

declare-fun totalCount () Int

; problem-related constraints

; assert (<= totalCount 5700)
minimize totalCount
check-sat

The solution that I get from z3 (version 4.8.5) for these constraints has the value of totalCount as 5995. When I uncomment the line before the minimize constraint (above), asking z3 to find a solution with totalCount <= 5700, it returns a solution with 5603. I get the same solution, irrespective of whether I keep the minimize constraint or not. I get similar behavior with z3 version 4.8.0 as well.
I have omitted the problem-related constraints, and I can send it if you want.

Am I using the minimize constraint correctly? There are no push or pop statements in my constraint file. Am I missing something?

**Comment by rixed** [comment]
Lookup smt.core.minimize in https://github.com/Z3Prover/z3/issues/1761

**Comment by NikolajBjorner** [comment]
not sure what discrepancy is supposed to be here.

**Comment by muqsitazeem148** [comment]
Thanks for the response. To give a concrete example, I am attaching two files to clearly explain my problem.

Following are the links of two files:
(1) https://rise4fun.com/Z3/TLslX
(2) https://rise4fun.com/Z3/87SQ

Consider a couple of lines before check-sat.

minimize totalCount
;assert(< totalCount 33000)

In (1) the assert is commented, but in (2) it is uncommented.

I am using z3 version 4.8.0.
The value of totalCount in (1) is 33220 and in (2) totalCount is 30084.

According to me, If both set of constraints return a solution, it should be same. Otherwise, If the totalCount=33220 is actually minimum, I should get UNSAT for (2).
