### ISSUE TITLE
set solver tactic for interpolant api?

### ISSUE THREAD

**Issue by cgcgbcbc** [Z3Prover/z3#249]
I'm facing a problem which must be solved with `qfnra`, and then I need to compute interpolant for this unsat problem, how can I pas this option to this problem.

**Comment by wintersteiger** [comment]
I'm fairly sure that there is no support for that in the interpolation modules and that there are no options for that yet either. It may be possible to construct some class of interpolant via normal, non-interpolation queries, but I'll let the experts answer those questions.

**Comment by kenmcmil** [comment]
Unfortunately, interpolation for non-linear arithmetic isn't supported. Only AUFLIA.
