### ISSUE TITLE
Expected date for the new release

### ISSUE THREAD

**Issue by leonardoalt** [Z3Prover/z3#2491]
First of all, it's great that since last year there are often new releases.

On that subject, is there an expected date for 4.8.6?
I'm interested in the official 4.8.6 release because we link against the latest and I have some examples that use Spacer which hang with 4.8.5 but are solved quickly by latest master.

Thanks!

**Comment by NikolajBjorner** [comment]
there are several bugs (GitHub issues) that would be good to fix before calling it a release

**Comment by leonardoalt** [comment]
Ok, thanks!
