### ISSUE TITLE
BitVec ASHR modeled with LSHR not recognized

### ISSUE THREAD

**Issue by alpaylan** [Z3Prover/z3#2497]
(bvor (bvand R_2 #x80000000) (bvlshr (bvand R_2 #x7fffffff) #x00000003))
(bvashr R_2 #x00000003)

These 2 statements fail to be recognized as equivalent, but to me it seems they should have been equivalent.

**Comment by wintersteiger** [comment]
```
...$ cat gh2497.smt2
(declare-const R_2 (_ BitVec 32))
(assert (not (= (bvor (bvand R_2 #x80000000) (bvlshr (bvand R_2 #x7fffffff) #x00000003))
             (bvashr R_2 #x00000003))))
(check-sat)
(get-model)
...$ z3 gh2497.smt2
sat
(model
  (define-fun R_2 () (_ BitVec 32)
    #x80000000)
)
```

You're shifting by `#x00000003` but adding back only one of the shifted bits via `#x80000000` and ` #x7fffffff`.

**Comment by alpaylan** [comment]
> You're shifting by `#x00000003` but adding back only one of the shifted bits via `#x80000000` and ` #x7fffffff`.
I don't fully understand what you mean by that.
Doesn't (bvand R_2 #x80000000) capture the sign and (bvand R_2 #x7fffffff) capture the rest, then the rest is logically right shifted 3 bits and the result is then bitwise OR'ed with the sign bit. Isn't this basically what asr does? 
Where do I add only one of those bits?

**Comment by NikolajBjorner** [comment]
Consider the following

(define-const R_2 (_ BitVec 32) #x80000000)

(simplify (bvand R_2 #x7fffffff))
(simplify (bvor (bvand R_2 #x80000000) (bvlshr (bvand R_2 #x7fffffff) #x00000003)))
(simplify (bvashr R_2 #x00000003))

We get the results:

#x00000000
#x80000000
#xf0000000

Thus, bvand R_2 and #x7fff.... is 0 and the entire expression is #x80.... OTOH, bvashr keeps the sign bits 3 positions down the line so the result is #xf0000....
