### ISSUE TITLE
Formula returns UNSAT with regular Z3 Solver, segfaults when using parallel c&c

### ISSUE THREAD

**Issue by becgabri** [Z3Prover/z3#2498]
I think something may be incorrect with how state is being shared when z3 has parallelization enabled. I have a formula that is correctly deduced to be unsatisfiable when not using the parallel cube and conquer, but if I do it then z3 segfaults. I've included a smt2 file corresponding to the state of the solver before the check is run and I was able to repro by setting z3.set_params('parallel.enable', True) at the beginning of the python script [even though it takes a decently long time before the solver is able to answer satisfiability/seg fault]. I also have some of the stack trace that comes up in gdb. Any help would be appreciated

[potential_bug.tar.gz](https://github.com/Z3Prover/z3/files/3506931/potential_bug.tar.gz)

**Comment by NikolajBjorner** [comment]
wasn't able to repro it yet

**Comment by becgabri** [comment]
Sorry, I know it's a large file. I'll try and see if I can get something smaller that still segfaults. If I can't find one within the next day, I'll close the issue.

**Comment by becgabri** [comment]
Closing this issue for now. I'll reopen if I can make the seg fault time more reasonable.
