### ISSUE TITLE
Use of InterpolationContext in Java causes JVM SIGSEGV

### ISSUE THREAD

**Issue by j58** [Z3Prover/z3#25]
I was trying to use the Java interpolation API from z3-unstable  to construct some simple examples. Unfortunately using an InterpolationContext crashes the JVM.  Here is the offending code:

 System.out.print("Z3 Major Version: ");
 System.out.println(Version.getMajor());
 System.out.print("Z3 Full Version: ");
 System.out.println(Version.getString());

HashMap<String, String> cfg = new HashMap<String, String>();
InterpolationContext ictx = new InterpolationContext(cfg);
System.out.println("SimpleInterpExample1");
IntExpr x = ictx.mkIntConst("x"); //Causes SIGSEGV in JVM

Here is the JVM  output:

Z3 Major Version: 4
Z3 Full Version: 4.4.0.0
SimpleInterpExample1

 A fatal error has been detected by the Java Runtime Environment:

  SIGSEGV (0xb) at pc=0x00007f712b0098c2, pid=19251, tid=140124041512704

 JRE version: Java(TM) SE Runtime Environment (8.0_31-b13) (build 1.8.0_31-b13)
 Java VM: Java HotSpot(TM) 64-Bit Server VM (25.31-b07 mixed mode linux-amd64 compressed oops)
 Problematic frame:
 C  [libc.so.6+0x7e8c2]# [ timer expired, abort... ]

The rest of the Java Z3 API seems to work fine in the unstable branch: All the examples in JavaExample.java work.

Any ideas on what the issue could be?

**Comment by wintersteiger** [comment]
Thanks for reporting this issue! mk_interpolation_context erroneously deleted the Z3_config object passed to it. This is now fixed in unstable.
