### ISSUE TITLE
Multiple inspection results are inconsistent

### ISSUE THREAD

**Issue by liqing9399** [Z3Prover/z3#2500]
When I first check, the result was unsat
When I check with another solver, the result is sat.why this ?
code show as below：

void myUnsat() {
z3::context c;
z3::solver s(c);
expr a = c.int_const("a");
expr b = c.int_const("b");
 params p (c);
p.set("unsat_core", true);
s.set(p);
s.add(a>b, "x1");
s.add(a < 5, "x2");
s.add(b > 8, "x3");
std::cout << s.check() << std:endl;
std::cout << s.unsat_core() << std::endl;

auto ass = s.assertion();
z3:::solver s2(c);
s2.set(p);
for (int i =0; i< ass.size(); i++) {
  s2.add(ass[i]);
}
std::cout << s2.check() << std::endl;
}

**Comment by liqing9399** [comment]
![unsat](https://user-images.githubusercontent.com/39342865/63156338-1344d580-c047-11e9-9024-3476c651b171.jpg)

**Comment by liqing9399** [comment]
![code](https://user-images.githubusercontent.com/39342865/63156516-67e85080-c047-11e9-96d8-418162ba141c.jpg)

**Comment by linkret** [comment]
Maybe you're not allowed to just feed assumptions from one solver to another one. As you can see, s.add(expr, name) is called upon the solver s, so maybe the resulting assumption also has some ties to the solver s? This could be bugging it out, when you try to "copy-paste" the assumption into a new solver.

**Comment by andrewvaughanj** [comment]
This isn't an answer, but in your second instance, your assertion `a > b` has been rewritten to `x1 => (a > b)` and then `x1` comes out as `false` in your second model (where `false => anything` is "trivially" `true`).

**Comment by NikolajBjorner** [comment]
try to display the assertions. You will see that they include the assumption literals x1, x2, x3.
These literals are not going to be tracked as assumptions in the new solver. You can do

from z3 import *
a, b = Ints('a b')
s = Solver()
s.set("unsat_core",True)
s.assert_and_track(a>b, "x1")
s.assert_and_track(a<5, "x2")
s.assert_and_track(b > 8, "x3")
print(s.check())
print(s.unsat_core())
print(s.assertions())


prints

unsat
[x1, x2, x3]
[Implies(x1, a > b), Implies(x2, a < 5), Implies(x3, b > 8)]

you could do 

s2 = Solver()
s2.add(s.assertions())
print(s2.check([x for x in Bools('x1 x2 x3')]))

**Comment by liqing9399** [comment]
Why are the same assertions for different solvers, the same assertions, the results will be different？
When I gradually added the assertion, I finally needed a model, how to remove the unsatisfied conditions? I am now using a temporary solver C to add the assertions in solver A and the assertions in solver B（new assertion）. When solver C has a model, I add the assertion in solver B to solver A. Use this strategy to continue adding new assertions.  Is this method feasible or a better way?
