### ISSUE TITLE
Spacer solves query via C++ API but hangs via Z3 binary

### ISSUE THREAD

**Issue by leonardoalt** [Z3Prover/z3#2503]
I have an example generated via the C++ API that is solved in 0.3s. Results: https://pastebin.com/f2S6ctRG.
When I dump the generated rules and query (in https://pastebin.com/vAXh22JR) and try to solve with the Z3 binary it hangs.
Any idea what could be happening here?
I checked that the library and binary were created from the same code/version of Z3.

**Comment by leonardoalt** [comment]
Version 4.8.5 solves it via the binary and latest master hangs. Need to do some binary search to figure which commit is causing it.

**Comment by agurfinkel** [comment]
For me, spacer diverges in both master and 4.8.5. Looking at what is happening, it is unrolling some loops. It is possible that under some configuration a different interpolant is found that leads to a quick solution. Unfortunately, this is hard to debug without having at least one configuration that solves it. 

What are the options are you using in the binary? Having stats (-st) would be useful as well.

**Comment by leonardoalt** [comment]
I'm actually not using any extra parameters via the API.
Here's the result of `solver.statistics()`:
```

**Comment by leonardoalt** [comment]
What is also interesting is that I'm sure I had this example working before (2 weeks ago maybe).

**Comment by leonardoalt** [comment]
In conversations with @agurfinkel we figured Spacer doesn't like `mod`. I still don't really know why API vs Z3 binary give different results, but closing this for now.
