### ISSUE TITLE
how to sum up array of Boolexpr using z3 in java?

### ISSUE THREAD

**Issue by michaela-egger** [Z3Prover/z3#2505]
I would need a function in z3 to sum up a list of BoolExpr, is there by now a possibility to use something like mkPbeq in java?(so pseudo-boolean operations in z3 for java)

I tried to do it myself like this, but I found no possibility to go through the list x inside the mkAdd
`solver.add(ctx.mkEq(ctx.mkAdd((x[k].isTrue() ? ctx.mkInt(1) : ctx.mkInt(0)) , ctx.mkInt(1)));`

(i think in python it can be done like And(x[i]) for i in range (0, length))

**Comment by nickgian** [comment]
You can use PB operations through the Java API (line 2243 in Context.java),
    `public BoolExpr mkPBEq(int[] coeffs, BoolExpr[] args, int k)`

But it sounds like you want to use a loop in java to go through that list. (unless you know the constant k and you want to constraint the sum to that)

```
   ArithExpr acc = mkInt(0);
   for (i =0; i < x.size(); i++) {
      acc = mkAdd(mkIte(x[i],mkInt(1),mkInt(0)),acc);
   }
   ....
```

**Comment by michaela-egger** [comment]
Thank you it works with the loop you proposed:)

But wouldn't it be possible to do the same with PB functions, since i want to sum up bools and compare that to a number?

**Comment by NikolajBjorner** [comment]
You should first build arrays with the contents you want to pass into mkpbeq or mkadd, then call these functions. So, first allocate BoolExpr[] args, and int[] coeff of appropriate sizes, then fill in values, then pass args and coeff to mkpbeq (or in case of mkAdd you have ArithExpr[] array).
