### ISSUE TITLE
z3 minimize clarification (repost)

### ISSUE THREAD

**Issue by muqsitazeem148** [Z3Prover/z3#2508]
I am not sure whether the comments over a closed issue will be answered, therefore reposting the issue. 

Thanks for the response. As a concrete example, I am attaching two files to clearly explain my problem.

Following are the links of two files:
(1) https://rise4fun.com/Z3/TLslX
(2) https://rise4fun.com/Z3/87SQ

Consider a couple of lines before check-sat.

minimize totalCount
;assert(< totalCount 33000)

In (1) the assert is commented, but in (2) it is uncommented.

I am using z3 version 4.8.0.
The value of totalCount in (1) is 33220 and in (2) totalCount is 30084.

According to me, If both set of constraints return a solution, it should be same. Otherwise, If the totalCount=33220 is actually minimum, I should get UNSAT for (2).

_Originally posted by @muqsitazeem148 in https://github.com/Z3Prover/z3/issues/2484#issuecomment-522549881_

**Comment by NikolajBjorner** [comment]
this would be a bug in 4.8. There have been several fixes since. I consistently get the right answer with current master.
