### ISSUE TITLE
Inconsistent result between 4.5.1 (online tutorial) and 4.8.4 / 4.8.5

### ISSUE THREAD

**Issue by andrewkatis** [Z3Prover/z3#2510]
Hello,

I am trying to run the attached formula with Z3, but I noticed that there is an inconsistency between the results from the online version (get-info returns 4.5.1) and the two latest releases (4.8.4, 4.8.5). The former gives SAT, while the latter gives UNKNOWN. Would it be possible to know which one to trust?

[inconsistent.zip](https://github.com/Z3Prover/z3/files/3526982/inconsistent.zip)

**Comment by NikolajBjorner** [comment]
The current master returns SAT. Unknown just means that the solver gave up, so it is a functionality regression. Quantified formulas are generally not decidable and the solver is generally not complete.
