### ISSUE TITLE
Build Error on RHEL 7.4 ar: tactic/bv/bv_tactics.a: File format not recognized

### ISSUE THREAD

**Issue by neerajbadal** [Z3Prover/z3#2512]
Hi,

While building the z3 library I am encountering the ar: tactic/bv/bv_tactics.a: File format not recognized error. Currently I'm stuck and want some  help to build it.

**Comment by NikolajBjorner** [comment]
try a clean build.

**Comment by neerajbadal** [comment]
Thanks, it worked. May be it might be the accidental cancellation while build for the first time was causing the problem.
