### ISSUE TITLE
Datalog engine for multiple demand queries

### ISSUE THREAD

**Issue by rainoftime** [Z3Prover/z3#2515]
Suppose have defined the `edge` and `path` relations and a set of facts.
We then make two on-demand queries about if there is a path between two vertices.
~~~~
from z3 import *
fp = Fixedpoint(); fp.set(engine='Datalog')
s = BitVecSort(3)
edge = Function('edge', s, s, BoolSort())
path = Function('path', s, s, BoolSort())
a,b,c = Consts('a b c', s)
fp.register_relation(path, edge); fp.declare_var(a,b,c)
# define the relations
fp.rule(path(a,b), edge(a,b))  
fp.rule(path(a,c),[edge(a,b), path(b,c)])

# the vertices: v0, ..., v4
# facts about the edges omitted

# "demand queries"
fp.query(path(v0,v4))  #query 1
fp.query(path(v1,v4))  #query 2
~~~~
Some algorithms such as the magic sets transformation can make Datalog query answering demand-driven. However, what if we have multiple demand queries?
 
- If we issue the two queries to the solver in sequential (as in the above code), will the intermediate states for answering the first query be "reused" for the second query?
- Can we send the tow queries to the solver by calling it once, so that the solver can schedule the search strategies for the two queries?

Note that we need the results of query 1 and query 2, respectively, instead of their disjunction or conjunction.

Thank you!

**Comment by NikolajBjorner** [comment]
You can create multiple relations besides path and edge, one for every query. 
The code for Fixedpoint query in z3.py has two cases depending on whether you pass in a Boolean expression or a list of predicate declarations.
For example, you can create 

```
q1 = Function('q1', BoolSort())
fp.register_relation(q1,q2)
```

Then 
```
fp.rule(path(v0,v4),q1())
fp.rule(path(v1,v4),q2())
```

then

```
fp.query(q1,q2)
```
