### ISSUE TITLE
Incorrect model with quantified BV

### ISSUE THREAD

**Issue by cdonovick** [Z3Prover/z3#2520]
in z3 4.8.6 (built from master, commit 271cd2ac6b8bffe6bd69edd432d7b73b3aa3631e), on debian. 
The follow test case generates an incorrect model.
```
(set-logic BV)
(declare-fun y () (_ BitVec 1))
(declare-fun c () (_ BitVec 2))
(assert
 (forall ((x (_ BitVec 1)))
  (=>
   (and
        (= x ((_ extract 0 0) c))
        (= y ((_ extract 1 1) c))
   )
   (= (bvor ((_ extract 0 0) c) ((_ extract 1 1) c)) #b1)
  )
 )
)
(check-sat)
(get-value (y))
```
Clearly the model for `y` should be `#b1` but `#b0` is produced. 
If I remove the "indirection" through `c` i.e.
```
(set-logic BV)
(declare-fun y () (_ BitVec 1))
(assert
 (forall ((x (_ BitVec 1)))
   (= (bvor x y) #b1)
  )
 )
)
(check-sat)
(get-value (y))
```
The model is correct

**Comment by wintersteiger** [comment]
Has this been resolved or was the issue closed accidentally?
