### ISSUE TITLE
Spacer times out when example uses const array

### ISSUE THREAD

**Issue by leonardoalt** [Z3Prover/z3#2524]
Consider the following 2 benchmarks:
1- https://gist.github.com/leonardoalt/511b6480514a2a26d943ae423d5b1e8d
2- https://gist.github.com/leonardoalt/645f717ec93ad5b180d52b7d2200aadf

The only difference between them is that 2) has an extra constraint that initializes an array with all 0s (line 30). 1) is solved instantly where 2) hangs.

Is there a parameter, maybe related to quantifiers, that I can use here to try and solve 2) as well?

**Comment by leonardoalt** [comment]
That's great, thanks!
What exactly does `ground_pobs` mean? I see all the `fp.spacer` options via `z3 -p`, but can I see the description of each option anywhere?

**Comment by agurfinkel** [comment]
https://github.com/Z3Prover/z3/blob/master/src/muz/base/fp_params.pyg

Spacer repeatedly computes predecessors, a.k.a, Proof OBligations (POBs) using existential quantifier elimination. Some theories (i.e., arrays) are not closed under qelim, which means that pobs might contain existentially quantified symbols. `ground_pobs=true` means that these existential symbols are ground by replacing them by constants. `ground_pobs=false` means that they are left quantified, which might lead to quantified lemmas, which leads to a lot of other differences later in the solving process. With `ground_pobs=false` you get a much more powerful solver, but also a lot less predictable one (think quantifiers).

**Comment by leonardoalt** [comment]
Ok, thanks again!
