### ISSUE TITLE
Update Z3 package for chocolatey 

### ISSUE THREAD

**Issue by hermanventer** [Z3Prover/z3#2526]
I have a Rust project that uses Z3 and I want to add Windows to the test matrix on Travis.

Nuget does not work for Rust projects, as far as I can tell. The guidance on the Travis website is that the supported package manager is chocolatey. There is a Z3 package for that https://chocolatey.org/packages/z3. Unfortunately it is very old and not being maintained.

Would it be possible to update and support this package? Alternatively, is there some other nice way to install Z3 on a Windows system without having to build it?

**Comment by NikolajBjorner** [comment]
You can download binary zip files from the releases. The releases tab.
Should you need additional files in the nuget packages it would be nice to get a pull request on the script that populates them (https://github.com/Z3Prover/z3/tree/master/scripts/mk_nuget_release.py)

**Comment by hermanventer** [comment]
My memory came back to me. It turns out that all I needed to know is that I need to copy libz3.dll to the same directory as the one containing the executable built by Rust.

I was scratching my head about where to put it so that it can be found and thought that a package manager will save me from having to figure this out. :-)

Never mind then, although it does seem suboptimal to have so many packaged distributions of Z3 lying around in a Zombie state, waiting to pounce on the unwary.
