### ISSUE TITLE
Z3 and Multiple Contexts in one process?

### ISSUE THREAD

**Issue by evmaus** [Z3Prover/z3#2535]
Hey:

We're running into a pretty consistent set of crashes on a slightly older version of Z3 (from the April/May-timeframe) in small_object_allocator::allocate.

Our use case that's crashing is having multiple Z3 contexts in the same process--we want slightly more throughput than a single Z3 context gives us.  After digging into it a bit more, it seems like that might not be supported by Z3's memory manager on Linux--the memory:: classes all seem to be static or rely on static state.

Is the memory management expected to be threadsafe and shared across contexts, or is what we're trying to do completely unsupported, or am I totally reading the code wrong?  Is there a way to instantiate multiple Z3 contexts within the same process and have them play nicely together?

Thanks,
Everett

**Comment by NikolajBjorner** [comment]
we can use multi-threading by isolating the use of each context to its own thread. 
The race condition is either internal to Z3 or because you are transferring data-structures between threads when it is not intended to.

**Comment by evmaus** [comment]
So we are creating a separate context per thread--I've got a repro within our own codebase where we will very consistently segfault in small_object_allocator with a single context per thread.

Would a repro case be helpful here?  I can spend some time trying to get a minimal one extracted from our codebase if it would help you all diagnose the issue.  :)

**Comment by NikolajBjorner** [comment]
It isn't viable for me to debug external code, especially multi-threaded. 
The small object allocator is going to be used from some place that is not protected by locks, a debug stack should say something about this and could point to what is not being protected.
Note that you cannot pass expressions between contexts.

**Comment by evmaus** [comment]
So I more meant a minimal repro case--like a few hundred lines in a single file.  But I'm happy to provide whatever is most helpful for you.

We seem to get a whole slew of different stacks.  They all seem to have the last two frames in common:

```
0xbace3f5 | small_object_allocator::allocate |  
0xbabda3a | mpz_manager::big_set |  
```

Here are a few:

```
0xbace3f5 | small_object_allocator::allocate |  
-- | -- | --
0xbabda3a | mpz_manager::big_set |  
0xbacb652 | rational::power_of_two |  
0xaf52d30 | bv_decl_plugin::mk_bv_sort |  
0xaf527e6 | bv_decl_plugin::set_manager |  
0xaf2cddd | ast_manager::register_plugin |  
0xaf93ab6 | reg_decl_plugins |  
0xaef712d | api::context::context |  
0xaef91ce | Z3_mk_context_rc |  
0xaecdf99 | z3::context::context
```

```
0xbace3f5 | small_object_allocator::allocate |  
-- | -- | --
0xbabda3a | mpz_manager::big_set |  
0xbacb652 | rational::power_of_two |  
0xaf5597d | bv_decl_plugin::mk_num_decl |  
0xaf2dc2b | ast_manager::mk_app |  
0xaf5983d | bv_util::mk_numeral |  
0xaef86ba | api::context::mk_numeral_core |  
0xaf115ea | Z3_mk_unsigned_int64 |  
0xaed2952 | z3::context::bv_val
```

There are a few others, too, but I think the last few stack frames were the same. (I haven't re-found one in our logs with push/pop, but I recall that triggering one of them).

**Comment by evmaus** [comment]
Oh, also, we definitely aren't passing expressions between contexts (or contexts between threads)--we have a wrapping class that doesn't leak any SMT internals outside of it (and which has an internal context/solver/etc.) that I created one of per thread.

**Comment by evmaus** [comment]
Hey:

So a coworker of our team's pointed out that this may actually just be that we're on an older version; it looks like in the past few months there was an update to how mpz_manager handles locking around allocation. (https://github.com/Z3Prover/z3/commit/9262908ebb7bdb4875a4316fdb607754ad9e72be#diff-b0849c8a6d47a4c47a4c0a370b91ce49L524)

I'll make sure we're still running into the crash on the latest version of Z3 and then reopen this if we're still hitting this stack trace.

Sorry about the bother,
Everett

**Comment by NikolajBjorner** [comment]
that particular commit is when I removed dependencies on OMP in favor of C++11 locks. The locking behavior should be the same so it would unlikely be attributed to that change. For race conditions it is often sufficient to capture stack traces of the threads involved. The apple does not fall far from the tree.
