### ISSUE TITLE
Regression: infinity detection strikes again

### ISSUE THREAD

**Issue by cheshire** [Z3Prover/z3#254]
Hi @NikolajBjorner,

Thank you for your fix!
Unfortunately, the issue is still there.

For the optimization problem below the expected bound is `2`, yet latest Z3 answers `infinity` (which is at least inconsistent, since adding a constraint `objective > 2` makes the problem `unsat`)
```
(declare-fun |BOUND_[7]_[ - main::x]| () Int)
(declare-fun |[5]_main::x@2| () Int)
(declare-fun |BOUND_[9]_[main::x]| () Int)
(declare-fun |[4]_main::x@2| () Int)
(declare-fun |BOUND_[18]_[main::x]| () Int)
(declare-fun |BOUND_[18]_[ - main::x]| () Int)
(declare-fun |BOUND_[8]_[ - main::x]| () Int)
(declare-fun |BOUND_[8]_[main::x]| () Int)
(declare-fun |[6]_main::x@3| () Int)
(declare-fun |BOUND_[7]_[main::x]| () Int)
(assert (<= (* (- 1) |[5]_main::x@2|) |BOUND_[7]_[ - main::x]|))
(assert (= |[4]_main::x@2| |BOUND_[9]_[main::x]|))
(assert (= |BOUND_[18]_[main::x]| 2))
(assert (= |BOUND_[18]_[ - main::x]| (- 2)))
(assert (= (* (- 1) |[5]_main::x@2|) |BOUND_[8]_[ - main::x]|))
(assert (= |[6]_main::x@3| |BOUND_[8]_[main::x]|))
(assert (= |BOUND_[7]_[ - main::x]| 0))
(assert (<= |[4]_main::x@2| |BOUND_[8]_[main::x]|))
(assert (= |BOUND_[7]_[main::x]| 0))
(assert (<= |[6]_main::x@3| |BOUND_[18]_[main::x]|))
(assert (>= |BOUND_[9]_[main::x]| 2))

(maximize |BOUND_[9]_[main::x]|)

(set-option :opt.optsmt_engine basic)
(set-option :opt.priority box)
(check-sat)
```

**Comment by cheshire** [comment]
I could try to generate all test inputs w/ expected outputs at once and commit them to the regression tests repository.

**Comment by NikolajBjorner** [comment]
Yes, I need to take regression tests so far run on offline and integrate them in our builds to avoid these kinds of regressions. If you have a collection of tests to share it would be great to test with them, except that copyright conditions have to follow the contribution guidelines (https://github.com/Z3Prover/z3/wiki/Contribution-Guidelines) 
if we are to include them in a repository.

**Comment by cheshire** [comment]
hi,

yes, I'll look into creating such a dataset; it does require some work though.
The query above still gives an answer of "infty" on the latest Z3 after your commit.

**Comment by cheshire** [comment]
Cool, everything seems working now! I'll generate the whole benchmarking set, maybe after the SV-COMP deadline though.
