### ISSUE TITLE
Why does not  z3 result show the length of an array?

### ISSUE THREAD

**Issue by tintinlam007** [Z3Prover/z3#2542]
the input is:
(declare-const x1(Array Int String)) 
(declare-const x2 Int) 
(declare-const y String) 
(assert (= (select x1 x2) y)) 
(declare-const x3 Int) 
(assert (= x3 1)) 
(assert (= x2 x3)) 
(check-sat)
(get-model)

the result is:
sat
(model
  (define-fun x2 () Int
    1)
  (define-fun x3 () Int
    1)
  (define-fun x1 () (Array Int String)
    ((as const (Array Int String)) ""))
  (define-fun y () String
    "")
)

why z3 do not show the length of x1? x1 is an array, and it is length is 1.
the right result should be:
sat
(model
  (define-fun x2 () Int
    1)
  (define-fun x3 () Int
    1)
  (define-fun x1 () (Array Int String)
    (store ((as const (Array Int String)) "") 0 "")
  (define-fun y () String
    "")
)

**Comment by NikolajBjorner** [comment]
arrays in SMTLIB do not have associated lengths. 
Furthermore, the "select" function is totally defined.
In other words it is defined on all index values of the sort used for the indices.
So the "length" of an array is not defined in a way you understand from programming languages.
You can model arrays from programming languages using two variables. The array and the length of the array. The length may be associated with which indices you expect to access and update an array at. In logic you specify that indices you access an array at are within the bounds and you can check these conditions separately. Checking such conditions is orthogonal to updating the applicative store structure that the array theory encodes.
