### ISSUE TITLE
Why z3 does not show the size of array

### ISSUE THREAD

**Issue by tintinlam007** [Z3Prover/z3#2543]
z3 input:
(declare-const x1(Array Int String)) 
(declare-const x2 Int) 
(declare-const y String) 
(assert (= (select x1 x2) y)) 
(declare-const x3 Int) 
(assert (= x3 1)) 
(assert (= x2 x3)) 
(check-sat)
(get-model)

z3 result:
sat
(model
  (define-fun x2 () Int
    1)
  (define-fun x3 () Int
    1)
  (define-fun x1 () (Array Int String)
    ((as const (Array Int String)) ""))
  (define-fun y () String
    "")
)

the array x1 should have size of 1, but z3 doet not show

**Comment by NikolajBjorner** [comment]
The SMTLIB2 standard describes the theory of arrays. It does not say anything about sizes.
