### ISSUE TITLE
Z3_get_string memory management

### ISSUE THREAD

**Issue by komalb007** [Z3Prover/z3#2555]
Hi,

I am using **Z3_get_string** to get Z3_string from Z3_ast in my code.

_Z3_ast currentAssert = assertValue;
Z3_string solution = Z3_get_string( context, currentAssert );_

I see that Z3_string is basically const char *.
Z3_get_string is returning me Z3_string which is char * ,so I am seeing memory leak in my code for _solution_ variable.

Is there way I can handle this leak?

Thanks,

**Comment by NikolajBjorner** [comment]
The lifetime of the strings returned by Z3 is only until the next string is returned.
Thus, if you call:

    Z3_string s1 = Z3_get_string(context, assert1);
    Z3_string s2 = Z3_get_string(context, assert2);

Then s1 is no longer a valid reference. The caller (your code) is reponsible for storing s1 somewhere it can be accessed should it be needed after the second call.

Internally, Z3 uses a single buffer to store the returned strings. The buffer is owned by the context object so the life-time of the buffer follows the lifetime of the context. The buffer is freed when the context is deleted.
