### ISSUE TITLE
Spacer solves via binary but answers `unknown` via API

### ISSUE THREAD

**Issue by leonardoalt** [Z3Prover/z3#2559]
Query dumped just before solving:
https://gist.github.com/leonardoalt/a010814a99def265bf3a9cdade562b6f

Z3 proves it `unsat` in 0.4s via the command line with:
`z3 -st fp.spacer.q3.use_qgen=true fp.spacer.mbqi=false fp.spacer.ground_pobs=false rewriter.pull_cheap_ite=true unknown.smt2`

whereas it returns `unknown` in 0.5s via the C++ API, using the same options.

Stats unsat: https://gist.github.com/leonardoalt/b91ca438c47609cd83f7a899ed67c6e3
Stats unknown: https://gist.github.com/leonardoalt/79c4a8ce5a8bbc72bc31cf835c912e05

Any idea what the difference could be?

Version: latest master

**Comment by agurfinkel** [comment]
Seems like randomness might be at play. I get `unknown` from command line using 
```
fp.spacer.random_seed=102
```
And solved for many other random seeds. Try a different random seed from the API.
It would help if you can post the log from `-v:1` in case of divergence. Then I can tell whether it diverges in the similar way for you as it does for me on command line.

**Comment by leonardoalt** [comment]
Oh I see.
Here are the logs:
unsat.log https://gist.github.com/leonardoalt/dae13c96ba06851e6b74c614c01b5aee
unknown.log https://gist.github.com/leonardoalt/decf2bf2f187d0848234de48bf6029c4

It eventually did work via the API as well.
I also observed the following:
- Most seeds led to unsat via the binary, whereas most seeds led to unknown via the api
- The same seed led to unsat via the binary and unknown via de api
- A single seed led to both unsat and unknown via the api in different runs

**Comment by leonardoalt** [comment]
@agurfinkel any hints on how to handle this besides the random seed? I'm running into more and more examples that the binary solves for almost all seeds and API fails for almost all seeds. In this case changing the seed isn't helping me much, since it takes a while to get a seed that works via the API.

**Comment by leonardoalt** [comment]
I just tried to replicate this with Spacer trace but couldn't anymore, so I'll close it for now.
