### ISSUE TITLE
z3 crashes on MBT test case

### ISSUE THREAD

**Issue by pjljvandelaar** [Z3Prover/z3#2560]
We are developing a new version of TorXakis, a model based testing tool.
And of course, we should practice what we preach, so we are testing TorXakis using MBT.
One of the MBT tools we use is QuickCheck, and with this tool we generate valid data types and then ask for all constructors, an instance of that data type made with that constructor.
In this test, on windows, we observed a crash by Z3 (the official release 4.8.5) on the attached smt2 input:
[crash.smt2.txt](https://github.com/Z3Prover/z3/files/3620195/crash.smt2.txt)

We tried to minimize the crash file. Although all problems are independent (see our usage of push and pop) removing earlier problems also removed the crash. This might be a hint that the problem is related to incremental problem solving.

**Comment by pjljvandelaar** [comment]
Just downloaded the latest nightly build on windows.
That version also crashes on the attached smt2 file.

**Comment by NikolajBjorner** [comment]
A first analysis suggests that Z3 attempts to generate what appears to be an enormous witness term. I doubt this is a new issue.

**Comment by pjljvandelaar** [comment]
What do you mean with new issue?
* Is this a duplicate of another / earlier reported issue?

or

* Is this problem already long present in z3, just not detected earlier?

**Comment by NikolajBjorner** [comment]
Second case.

fixed by 02e71c7d23627fc19b2a91b3d537daa1bad65673
