### ISSUE TITLE
Potentially incorrect result when using floating point theory

### ISSUE THREAD

**Issue by andrewvaughanj** [Z3Prover/z3#2564]
Hi,

Some quick preamble on the specifics of our environment:

* Python version: 2.7.5

* OS: CentOS 7.6 (kernel: 3.10.0-957.27.2.el7.x86_64)

* `z3 --version`: Z3 version 4.8.6 - 64 bit

* `z3.get_full_version()`: Z3 4.8.6.11304 master z3-4.8.4-1032-g77ef40a

On to our problem ...

We have extracted a cut-down reproducer from a real-world example where we feel that Z3 is providing "bad" answers when using the floating point theory.

Our real-world problem encodes something like:

```
x = FP("x", Float32())
y = FP("y", Float32())
s.add((x * y) <= 12)
```

However, for some instances, Z3 gives the following values for `x` and `y`:

* `x` == 2361856

* `y` == 5.08075027028e-06

If we check these values using Python (or C), then these values _do not_ give a result that is less than 12.

Here is our end-to-end reproducer:

```
from z3 import *
from numpy import float32
from decimal import *
import re


def calculate_with_numpy(float1_as_str, float2_as_str):
    """
    Convert both numbers from str to float32 and then caclulate their product
    """
    float1 = float32(float1_as_str)
    float2 = float32(float2_as_str)
    return float1 * float2


def calculate_with_z3(float1_as_str, float2_as_str):
    """
    Use z3 to calculate the product of our two numbers (as str) and obtain the
    result
    """
    z3_float1 = FPVal(float1_as_str, Float32())
    z3_float2 = FPVal(float2_as_str, Float32())

    # Helper assertion from our original problem
    twelve = FPVal("12.0000", Float32())

    # Symbolic value for the result
    result = FP("result", Float32())

    # Construct our solver
    s = Solver()

    # Multiplication of our two floats should equal the result
    s.add((z3_float1 * z3_float2) == result)

    # Our result should be less than 12
    s.add(result < twelve)

    # Z3 should give SAT
    assert s.check() == z3.sat

    # Obtain the model
    m = s.model()

    # Value for result
    value_for_result = m[result]

    # "Easy" way to extract the value from Z3
    matcher = r"FPVal\(\(/ (\d*) (\d*)\), FPSort\(8, 24\)\)"
    as_str = value_for_result.as_string()
    parts = re.match(matcher, as_str)
    assert parts

    # Build-up an arbitary precision decimal for our result
    denominator = Decimal(parts.groups()[0])
    numerator = Decimal(parts.groups()[1])

    # Calculate the result
    calculated_result = denominator / numerator

    # Many ways to skin a cat (should avoid eval though)
    assert calculated_result == float(eval(str(value_for_result)))

    return calculated_result


def main():
    float1_as_str = "5.08075027028e-06"
    float2_as_str = "2361856"

    numpy_value = calculate_with_numpy(float1_as_str, float2_as_str)
    z3_value = calculate_with_z3(float1_as_str, float2_as_str)

    print("Numpy returned: {:f}".format(numpy_value))
    print("Z3 returned: {:f}".format(z3_value))


if __name__ == "__main__":
    main()

# EOF
```

Which produces the following output:

```
Numpy returned: 12.000001
Z3 returned: 11.99999904632568359375
```

That is, it seems that when using "real" 32-bit floats (via numpy) that we get a value that is greater than 12. However, z3 believes that the product is less than 12, which is why it does not report UNSAT.

Is this a bug, or have I misunderstood the floating point semantics that Z3 (or the SMTLIB theory) defines (i.e., maybe they are idealised floats and some instances they should not correspond to real-world floats)?

**Comment by andrewvaughanj** [comment]
After sitting on this for the evening, I had the brain-wave of "I wonder if this is related to the rounding mode?".

So I changed the code slightly, such that I explicitly used `fpMul` with a rounding-mode, rather than using `__mul__` with the default mode.

The "interesting" part of code now looks like this:

```
    rms = [RTZ, RTN, RTP, RNE, RNA]
    for rm in rms:
        print(rm)
        try:
            z3_value = calculate_with_z3(float1_as_str, float2_as_str, rm())
            print("Z3 ({:s}) returned: {:f}".format(str(rm), z3_value))
        except:
            print("Z3 ({:s}) returned: UNSAT".format(str(rm)))
```

and then the output is like this:

```
Z3 (<function RTZ at 0x7f9834642938>) returned: 11.99999904632568359375
<function RTN at 0x7f9834642848>
Z3 (<function RTN at 0x7f9834642848>) returned: 11.99999904632568359375
<function RTP at 0x7f9834642758>
Z3 (<function RTP at 0x7f9834642758>) returned: UNSAT
<function RNE at 0x7f9834642578>
Z3 (<function RNE at 0x7f9834642578>) returned: 11.99999904632568359375
<function RNA at 0x7f9834642668>
Z3 (<function RNA at 0x7f9834642668>) returned: 11.99999904632568359375
```

That is, all of the rounding modes *except* `Z3_OP_FPA_RM_TOWARD_POSITIVE` return the same value, and `Z3_OP_FPA_RM_TOWARD_POSITIVE` actually says UNSAT (which, I believe, is correct, if I am comparing against Python/C).

Is the correct answer here that we need to be using `Z3_OP_FPA_RM_TOWARD_POSITIVE` to allow us to match what Python might do if using `float32` from `numpy`?

Can anyone comment on how the Z3 rounding modes correspond to what would be in `fenv.h`? I guess part of the answer is obvious:

* `Z3_OP_FPA_RM_TOWARD_ZERO` == `FE_TOWARDZERO`
* `Z3_OP_FPA_RM_TOWARD_NEGATIVE` == `FE_DOWNWARD`
* `Z3_OP_FPA_RM_TOWARD_POSITIVE` == `FE_UPWARD`

 but what about `Z3_OP_FPA_RM_NEAREST_TIES_TO_EVEN` and `Z3_OP_FPA_RM_NEAREST_TIES_TO_AWAY`, and how they compare to `FE_TONEAREST`?

**Comment by wintersteiger** [comment]
It's incredibly unlikely that there is this sort of bug in the current implementation of the adder. Please make absolutely sure that you compare exactly identical configurations. Obviously, the rounding mode has an impact, so make sure that you know exactly which one is used. 

I have no idea what the default configuration for numpy is, but I think it's unlikely that it's default semantics match the SMT FP semantics. 

The rounding modes are obvious as you say; `Z3_OP_FPA_RM_NEAREST_TIES_TO_EVEN` == `FE_TONEAREST` and `Z3_OP_FPA_RM_NEAREST_TIES_TO_AWAY` is not in the IEEE 754 standard, but the SMT theory supports it anyways.

**Comment by andrewvaughanj** [comment]
I'm happy for this to be closed. After experimenting with rounding modes, it seems that `RTP` appears to match `numpy` (for all the cases we care about), so that solves that issue!

Thank you, @wintersteiger!

**Comment by wintersteiger** [comment]
Fantastic, thanks for reporting back!
