### ISSUE TITLE
declare-datatypes needs declare-const for some reason

### ISSUE THREAD

**Issue by johndoe888** [Z3Prover/z3#2569]
When executing 
```
(declare-datatypes () ((D D1 D2)))
(declare-datatypes (T1) ((X (mk-x (p T1)))))
(declare-datatypes (T1) ((Y (mk-y (q (X T1))))))
(declare-datatypes (T1) ((Z (mk-z (r T1)))))
(define-sort S () (Z (Y D)))
;;(declare-const any (X D))
(declare-const a S)
(assert (= (p(q(r a))) D1))
(check-sat)
(exit)
```
z3 yields
```
(error "line 15 column 21: unknown function/constant p")
sat
```
but uncommenting the commented line to
```
(declare-datatypes () ((D D1 D2)))
(declare-datatypes (T1) ((X (mk-x (p T1)))))
(declare-datatypes (T1) ((Y (mk-y (q (X T1))))))
(declare-datatypes (T1) ((Z (mk-z (r T1)))))
(define-sort S () (Z (Y D)))
(declare-const any (X D))
(declare-const a S)
(assert (= (p(q(r a))) D1))
(check-sat)
(exit)
```
returns 
```
sat
```
and the error is gone.

How does an unrelated const declaration help z3 to find what it is looking for?

Z3 version 4.8.6, commit 63840806d as of 2019-09-10 on Debian Stretch.

**Comment by NikolajBjorner** [comment]
Per the SMTLIB2 standard you can use the (as ...) construct to disambiguate types without the const declaration. Otherwise Z3 relies on looking up type resolution for symbols in a table of pre-existing type instantiations.
