### ISSUE TITLE
Z3 binary could not solve certain assertions with qfnra

### ISSUE THREAD

**Issue by wanderseeme** [Z3Prover/z3#257]
The code is:

```
(declare-const _lv_n_1_1 Int)
(declare-const _lv_n_19_b Bool)

(assert (= _lv_n_19_b (distinct (- (* _lv_n_1_1 _lv_n_1_1) 2) 0)))
(assert (not _lv_n_19_b))

;(check-sat-using (then qfnra))
(check-sat)
```

If use `(check-sat)`, you will get `unsat`; but if you use `(check-sat-using (then qfnra))`, you will get `unknown`.

Version info:
Z3 4.4.2 at commit ad58226f43a44c6795f92657699ad1c4742aa8d1

**Comment by NikolajBjorner** [comment]
This is not a bug. The tactic qfnra does not understand how to handle integers. It only knows the quantifier-free theory of reals. The default strategy invoked by check-sat uses a general purpose solver, which is not tuned for non-linear reals, but happens to do just the necessary bounds propagations to understand that there is no integer square root of 2.
