### ISSUE TITLE
**UNUSED** value in z3str3 model

### ISSUE THREAD

**Issue by jmrtz** [Z3Prover/z3#2571]
```
(declare-fun a () (Array String String))
(declare-fun c1 () String)
(declare-fun m1 () String)
(declare-fun cmd1 () String) 

(assert (= c1 (select a "cmd")))
(assert (= m1 (select a "m")))
(assert (= m1 "test"))
(assert (= cmd1 c1))
(assert (str.contains cmd1 "qwertzu"))
(check-sat)
(get-model)
```
When I solve the script above with z3str3 and the latest version of z3, I get multiple "\*\*UNUSED\*\*" values in the model:
```
(:version "4.8.6")
sat
(model 
  (define-fun a () (Array String String)
    (store ((as const (Array String String)) "**UNUSED**3") "m" "test"))
  (define-fun cmd1 () String
    "**UNUSED**3")
  (define-fun m1 () String
    "test")
  (define-fun c1 () String
    "**UNUSED**3")
)
```
Z3 version 4.6.0 outputs correct values:
```
(:version "4.6.0")
sat
(model 
  (define-fun cmd1 () String
    "aaaaaaaaaaaaaaaaaaaaaaCqwertzuaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaav")
  (define-fun a () (Array String String)
    (_ as-array k!0))
  (define-fun m1 () String
    "test")
  (define-fun c1 () String
    "aaaaaaaaaaaaaaaaaaaaaaCqwertzuaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaav")
  (define-fun k!0 ((x!0 String)) String
    (ite (= x!0 "m") "test"
    (ite (= x!0 "cmd")
      "aaaaaaaaaaaaaaaaaaaaaaCqwertzuaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaav"
      "test")))
)
```
It seems to be a problem with the Array access

**Comment by pjljvandelaar** [comment]
Is z3str3 still actively supported? I see the numbers of issues related to z3str3 increasing but not being solved...

**Comment by NikolajBjorner** [comment]
@mtrberzi

**Comment by mtrberzi** [comment]
It is supported. I am working through a backlog of issues including ones reported by personal correspondence. Apologies for any delay in getting these resolved.

**Comment by mtrberzi** [comment]
I have a potential fix for this issue as well as possibly others. I need to test it very carefully because it changes a big assumption that I've made about what counts as a "string variable". I should be able to post a PR in a day or two if all goes well.

**Comment by mtrberzi** [comment]
Opened #2594
