### ISSUE TITLE
accepted by QF_ALIA, rejected by QF_AUFLIA

### ISSUE THREAD

**Issue by Smattr** [Z3Prover/z3#2574]
I distilled a problem I was working on to the following:

```smt
(set-logic QF_ALIA)
(declare-datatype C ((red) (blue)))
(assert (not (= red red)))
(check-sat)
```

Z3 correctly tells me this is unsat. However if I switch the logic to `QF_AUFLIA` it complains:

```
(error "line 3 column 25: logic does not support theory datatype")
sat
```

This surprised me as I thought [everything accepted by `QF_ALIA` was accepted by `QF_AUFLIA`](http://smtlib.cs.uiowa.edu/logics.shtml). Is this behaviour expected?

This is with Z3 4.8.5.

**Comment by Smattr** [comment]
I subsequently realised what I believe is the root cause: [`set_logic` does not appear to know `QF_ALIA`](https://github.com/Z3Prover/z3/blob/0b84c6088604da58885a4cda2ad9faf94fc157bd/src/cmd_context/check_logic.cpp#L70-L205) so it gets treated as an unknown logic, assumed to support everything during the preliminary check. Is this intentional?

**Comment by NikolajBjorner** [comment]
Correct. Z3 only recognizes a few logics. It uses default tactics for the remaining. The alphabet soup of logic annotations has grown over time. Not setting any logic is indeed sometimes better than setting a logic.

**Comment by Smattr** [comment]
Thanks for the explanation, Nikolaj. It seems a bit strange that [other parts of Z3 are aware of `QF_ALIA`](https://github.com/Z3Prover/z3/blob/63840806d84c4205952fe97a572b4cbf398ad273/src/solver/smt_logics.cpp#L51) but I can certainly work around this by setting no logic.
