### ISSUE TITLE
Z3 binary could not solve certain assertions with real

### ISSUE THREAD

**Issue by wanderseeme** [Z3Prover/z3#258]
Quite similar SMT snippet, but if use `Real` instead of `Int`, the result becomes `unknown`

```
(define-fun Int_Real ((n Int)) Real (to_real n))

(declare-const _lv_n_1_1 Int)
(declare-const _lv_n_19_b Bool)

(assert (= _lv_n_19_b (distinct (- (Int_Real (* _lv_n_1_1 _lv_n_1_1)) 2.) 0.0)))
(assert (not _lv_n_19_b))

(check-sat)
;result is unknown
```

Version info:
Z3 4.4.2 at commit ad58226f43a44c6795f92657699ad1c4742aa8d1

**Comment by NikolajBjorner** [comment]
Z3 can solve it if you eliminate the "to_real" coercions:
z3 toreal.smt2 rewriter.elim_to_real=true

**Comment by NikolajBjorner** [comment]
Pull request for fixes has been merged now
