### ISSUE TITLE
java API, closing context, segfault

### ISSUE THREAD

**Issue by proteusGIT** [Z3Prover/z3#2582]
I am iteratively computing all models for a condition with free variables.
For this purpose, I am adding the negations of found models to the solver.
At the end, when the solver returns the status unsatisfiable, I am closing the context from which the solver is derived.
This results in a segfault.

Interestingly, the java API example class states that the context should always be closed manually but this is not done there as well.

Should I do something to the solver first?
When I call solver.reset() and then context.close() I do not get a segfault.
Maybe this should be done automatically.

**Comment by NikolajBjorner** [comment]
The context is the last object to close. Objects created using a context should be closed before.
These objects have backpointers to the context (the contexts manages expressions and other shared state).
