### ISSUE TITLE
java API, simplifying quantified condition

### ISSUE THREAD

**Issue by proteusGIT** [Z3Prover/z3#2583]
Is there a sequence of safe tactics that can simplify `exists a. ((a=0) && p)` to `{0/a}p`?
If there is no such tactic, I will check models of the subcondition realizing that a must be 0 and then perform the substitution.

**Comment by NikolajBjorner** [comment]
It is called "qe-light"

(declare-fun p (Int) Bool)
(assert (exists ((x Int)) (and (= x 0) (p x))))
(apply qe-light)
