### ISSUE TITLE
bizarre fp solving performance/regression

### ISSUE THREAD

**Issue by rhelmot** [Z3Prover/z3#2584]
This showed up for me initially because some testcases started timing out after the automatic upgrade to 4.8.6 (:tada:) but from investigation it looks a lot weirder. This is about the following script, with the parameter controlling how one of the constraints is added:

```python
import z3
from functools import reduce
import time
import sys

if len(sys.argv) != 2 or sys.argv[1] not in '1234':
    print("usage")
    sys.exit(1)

sort = z3.FPSort(11, 53)

solver = z3.Solver()
sumbits = [z3.FP(chr(0x41 + i), sort) for i in range(19)]
thesum = reduce(lambda x, y: z3.fpAdd(z3.RNE(), x, y), sumbits)

if sys.argv[1] == '1':
    solver.add(thesum == z3.FPVal(27.7, sort))
if sys.argv[1] == '2':
    solver.add(z3.fpEQ(thesum, z3.FPVal(27.7, sort)))

for elem in sumbits:
    solver.add(elem > z3.FPVal(1.0, sort))

if sys.argv[1] == '3':
    solver.add(thesum == z3.FPVal(27.7, sort))
if sys.argv[1] == '4':
    solver.add(z3.fpEQ(thesum, z3.FPVal(27.7, sort)))

tstart = time.time()
print(solver.check())
print(time.time() - tstart)
```

z3 4.8.5:

```
$ python manysum_testcase.py 1
sat
5.543213605880737
$ python manysum_testcase.py 2
sat
101.17556762695312
$ python manysum_testcase.py 3
sat
45.65452170372009
$ python manysum_testcase.py 4
sat
4.905688285827637
```

z3 4.8.6:

```
$ python manysum_testcase.py 1
sat
10.441969633102417
$ python manysum_testcase.py 2
sat
83.53299117088318
$ python manysum_testcase.py 3
sat
213.03837394714355
$ python manysum_testcase.py 4
sat
394.18676829338074
```

These tests were done on linux, with cpython 3.6.5 and the z3 binaries from pypi. These times are pretty stable (within 5%) between runs. I also tried messing with various random seed options and nothing seemed to change.

There are two very concerning things here:

- Whether you add the constraint on the sum before or after the constraints on the individual pieces affects solving time gigantically (and also whether you use fpEq or ==, is there supposed to be a difference?)
- Performance regression between versions on case 4 (and somewhat on case 3)

what on EARTH is going on :cold_sweat:

**Comment by wintersteiger** [comment]
This is more or less expected. All FP constraints are translated into SAT and if there is any change to the heuristics of the SAT solver (intended or not), runtime performance will change, sometimes drastically.

There is a significant difference between `=` and `fp.eq`: the latter has different semantics and it is a proper (interpreted) function. Whenever it returns true, we cannot assume that `=` also is true (for instance -0 != +0 but fp.eq(-0, +0) is true), so all simplifications that rely on `=` do not apply in the case of `fp.eq`.

**Comment by rhelmot** [comment]
Is there any way to structure this problem so it can be solved efficiently regardless of heuristics?

**Comment by wintersteiger** [comment]
It's essentially a long sum of numbers that's constrained on the input and the output, I don't think there's a way to solve this without the SAT or SMT solver. Perhaps the SMT solver would behave a little slower but more predictable (as long as the problem doesn't change), you can try it with something like `solver = z3.Tactic("smt").solver()` instead of the plain solver.

Just on the off-chance that you're using floats because you assume things would be quicker than with ints or reals: floats are usually harder on the solver.
