### ISSUE TITLE
to_smt2

### ISSUE THREAD

**Issue by KihongHeo** [Z3Prover/z3#2589]
Hi,  I have a question about the to_smt2 function.
Is there any change for the dumped smt2 file to have a different result?
Here is a part of my code
```cpp
z3::check_result Result = Solver.check();
if (Result == z3::unsat) {
    std::ofstream Smt2("formula.smt2");
    Smt2 << Solver.to_smt2() << std::endl;
    Smt2.close();
}
```
When I directly invoke z3 with the dumped file, the result is SAT.

**Comment by NikolajBjorner** [comment]
Possibly Solver.check() produces unsat and then the resulting formulas extracted for to_smt2 should have been the same as "false". At least I haven't tested this scenario as it doesn't appear to make sense. Mainly I have tested the scenarios where the solver returns sat or unknown and the solver is on finite domain constraints.

**Comment by KihongHeo** [comment]
It seems that answer literal causes the problem. z3 assigns False to answer literal so that the whole formula becomes SAT. Here is a minimal example:
```cpp
#include "z3++.h"
#include <fstream>

int main(int argc, char **argv) {
  z3::context C;
  z3::sort BV = C.bv_sort(32);
  z3::solver Solver(C);
  z3::params Params(C);
  Params.set("unsat_core", true);
  Params.set("core.minimize", true);
  z3::expr X = C.bv_const("X", 32);
  z3::expr Zero = C.bv_val(0, 32);
  Solver.add(X == Zero, "Assert1");
  Solver.add(X != Zero, "Assert2");
  z3::check_result Result = Solver.check();
  std::cout << Result << std::endl;
  if (Result == z3::unsat) {
    std::ofstream Smt2("formula.smt2");
    Smt2 << Solver.to_smt2() << std::endl;
    Smt2.close();
  }
  return 0;
}
```

It prints out "unsat" but `z3 formula.smt2` produces sat. Please let me know if I am wrongly using the APIs.

**Comment by NikolajBjorner** [comment]
the smt2 file does not assert the tracking literals. it adds tracking literals to clauses that are tracked, but you have to pass in the tracking literals to the check-sat call or check-with-assumptions to get the same semantics as through the API.

**Comment by obicons** [comment]
> the smt2 file does not assert the tracking literals

Why not?

I’m a new user to Z3. I encountered this behavior this morning, and I found it rather surprising. It seems strange that an API called `assert_and_track` fails to produce assertions in the result contained by `to_stm2`.
