### ISSUE TITLE
Different satisfiability for commutative !=

### ISSUE THREAD

**Issue by 0152la** [Z3Prover/z3#2604]
In the attached test case, we create two equivalent-by-construction expressions, `r_0` and `r_5`. We expect that the formulas `r_0 != r_5` and `r_5 != r_0` are unsatisfiable. However, the actual results differ for the two instantiated `solver`s. Furthermore on rise4fun, the satisfiability is `unknown` in both cases. Inspecting the SMT2 formulas for both expressions seems to show them as equivalent. The inconsistency was observed with a build from commit d70b63c8acf816e57adce30242c0c8a81be515f0.

[inconsistent_sat.zip](https://github.com/Z3Prover/z3/files/3676116/inconsistent_sat.zip)

**Comment by NikolajBjorner** [comment]
z3 is not a decision procedure for non-linear integer arithmetic. the solver may give up or figure out whether it is sat/unsat depending on search state.

**Comment by 0152la** [comment]
The fact that Z3 is not a decision procedure for this theory explains the `unknown` we see in `rise4fun` - thanks.

However, am I correct that when Z3 does specifically report `sat` for a formula in this theory, that result is supposed to be trustworthy (same for `unsat`)? I.e., if it does return a conclusive result due to heuristics and based on the search state, we should trust the given result.

If so, with respect to the reported example above, Z3 reports that `r_0 != r_5` is `unsat`, while `r_5 != r_0` is `sat`. We believe that the two formulas are equivalent, by nature of commutativity of `!=`, which should in turn not affect the satisfiability reported by Z3.
