### ISSUE TITLE
How to find `libz3.so` and `libz3.so.4` ?

### ISSUE THREAD

**Issue by btrb** [Z3Prover/z3#2605]
Hello, please forgive if this is more like a question.

I have cloned the repo, and successfully installed using:
```
CXX=clang++ CC=clang python scripts/mk_make.py
cd build
make
make install
```

Now I have:
```
$ z3 --version
Z3 version 4.8.7 - 64 bit
```

But I'm facing problems with another build, when I find:
```
-- Could NOT find Z3: Found unsuitable version "0.0.0", but required is at least "4.7.1" (found Z3_LIBRARIES-NOTFOUND)
```

It seems that it's looking for the files `libz3.so` and `libz3.so.4`, expecting it to be in `/usr/lib/x86_64-linux-gnu`.

If only I could find those files, then I guess they could be moved/copied/linked to the expected dir, and everything should be fine. 

**Therefore, my question is, how can I find the files and `libz3.so` and `libz3.so.4`?**

Thank you for your time. 
Any replies would be much appreciated.

**Comment by NikolajBjorner** [comment]
Could you try the cmake build system instead? it requires to install cmake, but has been tested under more scenarios for installation.

**Comment by btrb** [comment]
ok thank you, let me try that.

**Comment by NikolajBjorner** [comment]
I take the answer to the original question
> Therefore, my question is, how can I find the files and libz3.so and libz3.so.4?
is to consider looking in the generated Makefile to where the "install" option places its files.
