### ISSUE TITLE
support 64bit symbols

### ISSUE THREAD

**Issue by wdcui** [Z3Prover/z3#2606]
Z3 currently only supports a symbol based on int (32-bit).  Given that concolic executions track expressions for memory, it would be nice to have a 64-bit symbol.  This way the caller can use the memory address directly as the symbol.

**Comment by NikolajBjorner** [comment]
the representation we use for symbols does not allow changing the representation to 64 bits. Users will have to maintain a hash-table to map their 64 bit values to smaller unsigned values. Z3 doesn't scale to problems with 2^31 variables anyway so it isn't going to change practical uses.
