### ISSUE TITLE
Difference between sat and psat

### ISSUE THREAD

**Issue by nickgian** [Z3Prover/z3#2607]
I expected the two to have similar behavior but psat can solve some cases in which sat returns unknown.
For instance the query:

```
(declare-const w (_ BitVec 3))
(declare-const z (_ BitVec 3))
(assert (ite (= w z) true false))
```
returns unknown when checked with sat, which is what I expected anyway:
```
(check-sat-using sat)
```
but sat when checked with psat (the set-option is required for this to work)
```
(set-option :parallel.enable true)
(check-sat-using psat)
```

If I use bit-blasting then it works with sat too (no surprise there).

But I have a larger example, where I add a pseudoboolean constraint and then bit-blasting no longer solves the issue with sat. It still works fine with psat.
Is that the intended behavior? If yes, is smtfd my best alternative to sat?

**Comment by NikolajBjorner** [comment]
Perhaps you should use qffd or qffdp instead of sat and satp. These tactics perform bit-blasting for you. the sat tactic doesn't. It assumes you have performed bit-blasting with other suitable tactics or that the formula is essentially a set of clauses. The smtfd tactic is early work in progress.

**Comment by nickgian** [comment]
Thank you for your reply and the pointer to qffd.
I understand that although it seems as if psat performs some type of bit-blasting or has some other reasoning mechanism to take care of bitvectors. 

Any ideas on why
```check-sat-using (then bit-blast sat)``` returns unknown while
```check-sat-using (then bit-blast psat)``` 
solves the query when pseudobooleans come into play?

**Comment by NikolajBjorner** [comment]
Psat tactic uses the incremental version of the sat solver that applies bit blasting transformations on its own.

- Nikolaj

________________________________
