### ISSUE TITLE
Z3_get_numeral_decimal_string not work

### ISSUE THREAD

**Issue by cgcgbcbc** [Z3Prover/z3#262]
```
#include <z3++.h>
#include <z3.h>

#include <iostream>
#include <string>

using namespace std;

int main() {
    z3::context ctx;
    z3::symbol xs(ctx, Z3_mk_string_symbol(ctx, "x"));
    z3::sort f32(ctx, Z3_mk_fpa_sort_32(ctx));
    z3::expr x(ctx, Z3_mk_const(ctx, xs, f32));
    z3::expr c(ctx, Z3_mk_fpa_numeral_float(ctx, 20.0f, f32));
    z3::solver s(ctx);
    s.add(x == c);
    cout << s.check() << endl << s.get_model() << endl;
    z3::model model = s.get_model();
    z3::expr value = model.get_const_interp(x.decl());
    cout << value << endl;
    cout << Z3_get_numeral_string(ctx, value) << endl;
    cout << Z3_get_numeral_decimal_string(ctx, value, 16) << endl;
}
```
the last cout just output an empty line

**Comment by wintersteiger** [comment]
This is a problem with the order of evaluation of operator<<. This line of code

    cout << s.check() << endl << s.get_model() << endl;

calls `s.get_model()` _before_ calling `s.check()`. If we change it to

    cout << s.check() << endl;
    cout << s.get_model() << endl;

Then everything works as expected. It's confusing that this didn't throw a proper error/exception though; I'll look into adding that.

**Comment by wintersteiger** [comment]
Z3 does in fact throw an exception; it just wasn't caught anywhere. If we wrap the example in

    try {
    ...
    } 
    catch (z3::exception & ex) {
        cout << "Exception: " << ex.msg() << endl;
    }

Then you will get the exception message (invalid usage).

**Comment by cgcgbcbc** [comment]
Does this mean that floating point can't be directly transformed to a c float or approximate decimal string by api? I found that in the python api, if I call `as_string()` on a float point value, it fails as well because it will throw `NameError: global name 'Z3_fpa_get_numeral_string' is not defined` :
```python
from z3 import *
x = FP('x', FPSort(8,24))
v = FPVal(20.0, FPSort(8,24))
s = Solver()
s.add(x==v)
s.check()
xv = s.model()[x]
xv.as_string()
```

**Comment by wintersteiger** [comment]
No, this means that you can't call `s.check` and `s.get_model()` in the order you tried to call them. You have to call `s.check()` first, and only if that check is satisfiable you're allowed to call `s.get_model()`, everything else is "invalid usage" as the exception message says. This line of code:

    cout << s.check() << endl << s.get_model() << endl;

will call `s.get_model()` first (for some compilers; the C++ standard says the order is "undefined").

**Comment by wintersteiger** [comment]
Converting FP numerals is a completely orthogonal issue, I'll have to look into that separately.
