### ISSUE TITLE
z3str3 crashes

### ISSUE THREAD

**Issue by pjljvandelaar** [Z3Prover/z3#2622]
With [z3-4.8.7-x64-win](https://github.com/Z3Prover/z3/releases/download/Nightly/z3-4.8.7-x64-win.zip) [a.k.a. the latest nightly build](https://github.com/Z3Prover/z3/commit/6e994f92794f72abdda28dcd7e9bebb7d6f0543e)
Z3 crashes with the parameter `smt.string_solver=z3str3` on all attached files:
[smt2.zip](https://github.com/Z3Prover/z3/files/3707197/smt2.zip)

Could you please into these problems?

**Comment by mtrberzi** [comment]
Thanks for the report. At least on the first instance I tried, it looks like an assertion violation (which results in an artificial "crash" in release mode). So I have somewhere to start taking a look.

**Comment by mtrberzi** [comment]
Opened #2627. Verified that the solver no longer crashes on any of the attached files (a few of them do timeout at 30 seconds) with this patch.
