### ISSUE TITLE
Tactic/solver for EPR (Bernays–Schönfinkel class)?

### ISSUE THREAD

**Issue by rainoftime** [Z3Prover/z3#2625]
Is there a tactic/solver dedicated to the EPR class (Effectively Propositional Logic)?
Or, we only need to encode a problem as EPR and create a solver (e.g, using the `smt` tactic?)
If my problem instance is EPR, how can I turn Z3 for improving the empirical performance? Thank you!

**Comment by NikolajBjorner** [comment]
when presented with a quantified formula, Z3 uses by default the SMT solver with model-based quantifier instantiation (mbqi). MBQI is a decision procedure for EPR.
