### ISSUE TITLE
Confused that result of Z3-opt interface contains Epsilon, 

### ISSUE THREAD

**Issue by gingeredder** [Z3Prover/z3#263]
I have downloaded the Z3 bin file  today from 
https://github.com/Z3Prover/bin/blob/master/nightly/z3-4.4.2.89fb5a44fba8-x64-ubuntu-14.04.zip

When I set the following smt-code as input.
 
(declare-fun k () Int)
(assert (< (to_real k) 2))
(maximize k)
(check-sat)

It gives the result like this:
k |-> (+ (to_real 2) (* (to_real (- 1)) epsilon))
sat

But in the http://rise4fun.com/Z3Opt, I get the result  like this:
k |-> 1
sat

Could you tell me that how to get the "precise" result like in the http://rise4fun.com/Z3Opt.
Many thanks

**Comment by NikolajBjorner** [comment]
Thanks, this looks like a regression.

**Comment by gingeredder** [comment]
Yes, But the k has a type of Integer, how could I  get the result k -> 1?
Thanks

**Comment by NikolajBjorner** [comment]
correct, the result should be k -> 1, fixed.

**Comment by gingeredder** [comment]
Thanks. Got it.
