### ISSUE TITLE
feat: z3py should be able to output non-prettied compact string for objects

### ISSUE THREAD

**Issue by yxliang01** [Z3Prover/z3#2633]
As far as I see, the `__str__` method calls `obj_to_string`(defined in https://github.com/Z3Prover/z3/blob/5bdcc737ec477a9267ac2e1104126b8525a40d52/src/api/python/z3/z3printer.py#L1236 ) which always pretty the output. However, sometimes, it's better to have compact string representation, rather than the prettied one. So, this is to suggest having the feature that `obj_to_string` can optionally create compact string. For my use case, removing the newlines should be good enough.

Thanks

**Comment by NikolajBjorner** [comment]
You can configure the python pretty printer in some ways. You can also call the "sexpr()" method and get the smtlib2 version of the representation. This is what is supported.

**Comment by yxliang01** [comment]
No... SMTLIB2 format is not the compact string representation I was talking about... However, I don't quite see how I can configure it? z3printer.py doesn't expose these options?

**Comment by NikolajBjorner** [comment]
The file z3printer.py contains the PP class.

https://github.com/Z3Prover/z3/blob/5a1003f6ed10fc65a1cbcd2554f183714c413c7c/src/api/python/z3/z3printer.py#L453

It contains the options, with defaults:
        self.max_lines  = 200
        self.max_width  = 60
        self.bounded    = False
        self.max_indent = 40

The function set_pp_option can be used to modify these values.

**Comment by momvart** [comment]
Is there a way to achieve similar thing through the native `Z3_ast_to_string` API? Currently I'm dumping hundreds of megabytes of SMTLIB expressions which I believe can be reduced significantly with the erasure of whitespaces.

**Comment by NikolajBjorner** [comment]
For SMTLIb output you have some format options:

https://github.com/Z3Prover/z3/blob/68a7d1e1b1cbca5796e0cbf647d6a940b08b4cde/src/api/z3_api.h#L1353

They control the formatting. The default pretty printer has overhead for indentation. The faster ones produce well-formed output but are less readable.

**Comment by momvart** [comment]
Actually, let me add that I want to parse the ASTs later; in fact, I'm implementing a serialization/deserialization flow.

The low level mode is indentation free, but I don't know any API for reading them back. And `Z3_PRINT_SMTLIB2_COMPLIANT` is still statically (?) indented.
