### ISSUE TITLE
Tab instead of spaces in z3.py and multiple defines of FloatSingle

### ISSUE THREAD

**Issue by nils2000** [Z3Prover/z3#264]
Hi, 
no compilation with python3 because of:
*** Sorry: TabError: inconsistent use of tabs and spaces in indentation (z3.py, line 3924)
while fixing that my editor (spyder, great editor btw) marked multiple definitions of FloatSingle

from line 7759 on:
def FloatSingle(ctx=None):
    """Floating-point 64-bit (double) sort."""
    ctx = _get_ctx(ctx)
    return FPSortRef(Z3_mk_fpa_sort_double(ctx.ref()), ctx)

def Float128(ctx=None):
    """Floating-point 128-bit (quadruple) sort."""
    ctx = _get_ctx(ctx)
    return FPSortRef(Z3_mk_fpa_sort_128(ctx.ref()), ctx)

def FloatSingle(ctx=None):
    """Floating-point 128-bit (quadruple) sort."""
    ctx = _get_ctx(ctx)
    return FPSortRef(Z3_mk_fpa_sort_quadruple(ctx.ref()), ctx)

is that correct ?

**Comment by wintersteiger** [comment]
Thanks for the report! The indendation problem had already been fixed, but those function names were still wrong. This is now fixed in master.
