### ISSUE TITLE
Spacer falls into SIGSEGV when "get-proof" is passed

### ISSUE THREAD

**Issue by shiatsumat** [Z3Prover/z3#2643]
On z3 4.8.6 I encounter the following issue.
```
$ z3 -in
(declare-rel ? ())
(query ?)
unsat
(get-proof)
fish: 'z3 -in' terminated by signal SIGSEGV (Address boundary error)
```

**Comment by NikolajBjorner** [comment]
Fort the "rel" and "query" extension syntax you want something along the lines of:

(set-option :fp.engine spacer)
(declare-rel ? ())
(query ? :print-certificate true)
