### ISSUE TITLE
'Out of memory' or 'Killed' being systematically output

### ISSUE THREAD

**Issue by fabiopakk** [Z3Prover/z3#2649]
Z3 is failing to run with the attached SMT query, causing either 'Out of memory' or 'Killed' messages to be output on Linux or '(error: Out of memory)' to be output on Windows. In both cases memory usage increases but not to a point where the system's memory is entirely consumed.

This behavior occurs with different frequencies depending on which computer you run, however with the following seeds, it is 100% reproducible, regardless of operating system or computer configuration:

z3 -st sat.random_seed=3877 nlsat.seed=80 smt.random_seed=15862 sls.random_seed=575 query.smt.2

[query.smt.2.txt](https://github.com/Z3Prover/z3/files/3754552/query.smt.2.txt)

Thank you,

Fábio Pakk Selmi-Dei

**Comment by fabiopakk** [comment]
In the latest commit 0acbdff, the issue is reproducible with the following seeds:
z3 -st sat.random_seed=9302 nlsat.seed=7181 smt.random_seed=14597 sls.random_seed=2278 query.smt.2

**Comment by NikolajBjorner** [comment]
Killing that configuration after about a minute shows considerable memory consumption based on a large number of quantifier instantiations. The axiomatization seems to cause z3 to perform considerable quantifier instantiation.

unknown
(:added-eqs            2090789
 :arith-add-rows       1330190
 :arith-assert-diseq   27797
 :arith-assert-lower   362320
 :arith-assert-upper   378468
 :arith-bound-prop     194371
 :arith-conflicts      698
 :arith-eq-adapter     248742
 :arith-fixed-eqs      214916
 :arith-gcd-tests      1133
 :arith-offset-eqs     282388
 :arith-patches        5
 :arith-patches_succ   5
 :arith-pivots         246233
 :binary-propagations  7
 :conflicts            1909
 :decisions            40410
 :del-clause           1569157
 :dyn-ack              3
 :final-checks         37
 :interface-eqs        15
 :max-generation       100
 **:max-memory           2664.54**
 :memory               2398.85
 :minimized-lits       20429
 :mk-bool-var          1950810
 :mk-clause            1569158
 :num-allocs           196447299843.00
 :num-checks           1
 :propagations         1162350
 **:quant-instantiations 733415**
 :restarts             5
 :rlimit-count         164193498
 :time                 55.28
 :total-time           57.33)
