### ISSUE TITLE
How to translate the Expr(Const number) in Z3 to be an object in MPQ/MPFR

### ISSUE THREAD

**Issue by gingeredder** [Z3Prover/z3#265]
When I use the Z3-opt(Ocaml version) to solve some planning problem, and I get a result from Z3 like this:

(+ (/ 31.0 10.0) (* (to_real (- 1)) epsilon))

And this result is of type of Z3.Expr. I want to know how to translate this result(of Z3.Expr) to anther common data-type object(for example, MPQ/MPFR).Does the Z3-opt(Ocaml version) provide the ocaml interface to this?
The result like (+ (/ 31.0 10.0) (* (to_real (- 1)) epsilon)) is to complex. 
I could not use this in my project. How could I get the rational number it represents?

Many thanks.

**Comment by gingeredder** [comment]
I have tried several interfaces in the file https://github.com/Z3Prover/z3/blob/master/src/api/ml/z3.mli.
But it seems to fail to work.
The expr of string (+ (/ 31.0 10.0) (* (to_real (- 1)) epsilon)) could be translated to a float-point number like 3.099999999...5. Also it could be truncated to be rational number(like MPQ). But how could I handle this with the ocaml interface provided by Z3-opt?
Thanks.

**Comment by NikolajBjorner** [comment]
Admittedly a workaround for not returning something from an extension field.

You can for example

(1) Expr.substitute_one epsilon by a small number of your choice, 
(2) call Expr.simplify to reduce the expression to a constant, 
(3) extract Expr.numeral_to_string.

The term "epsilon" is of type Real, so you can create it directly from ocaml as opposed to walk the expression returned from Z3-opt to find it. E.g., 
let epsilon = mk_const_s ctx "epsilon" (Real.mk_sort ctx)

For unbounded objectives Z3-opt also creates a term called "oo" (to indicate that optimal solutions can be arbitrarily large positive or arbitrarily large negative).

**Comment by gingeredder** [comment]
Hi Bjorner ,
Thanks for your reply.
I have substituted the epsilon with 0.01(for example) in the expression. Then the expression could translated like (+ (/ 31.0 10.0) (* (to_real (- 1)) |0.01|))
Now I want to reduce this expression to a constant with the interface Expr.simplify. The parameter need a "Params.params option". What parameter should I choose to get the constant the expression represents?

**Comment by NikolajBjorner** [comment]
just pass None.

**Comment by gingeredder** [comment]
When I pass None. I just get the Expr of string "(+ (/ 31.0 10.0) (* (- 1.0) |0.01|))".  How could I get the result as a constant?

**Comment by NikolajBjorner** [comment]
Use
   (** Create a real numeral.
		@return A Term with the given value and sort Real *)
    val mk_numeral_s : context -> string -> Expr.expr

not mk_const

**Comment by gingeredder** [comment]
Thanks. Got it!
