### ISSUE TITLE
z3 crash 

### ISSUE THREAD

**Issue by kanigsson** [Z3Prover/z3#2656]
[Uploading z3_crash.smt2.txt…]()

Hello Z3 team,

On the attached VC, z3 4.8.6 crashes as follows:

  $ z3 z3_crash.smt2
  Failed to verify: m_util.is_numeral(rhs, _k)
  Bus error (core dumped)

Sorry for the large reproducer, but as soon as I start removing stuff, the bug disappears.

**Comment by kanigsson** [comment]
[z3_crash.smt2.txt](https://github.com/Z3Prover/z3/files/3770120/z3_crash.smt2.txt)

Looks like there was an issue to upload the file, trying again

**Comment by NikolajBjorner** [comment]
yes it crashes in the release, the crash is already fixed in current master.

**Comment by kanigsson** [comment]
Cool thanks! Sorry for the noise then.
