### ISSUE TITLE
Checking if a pair of real numbers has the minimum difference in an array of reals

### ISSUE THREAD

**Issue by sg61189** [Z3Prover/z3#2670]
Hello, I was trying to check if a pair of real numbers has the minimum difference in an array of reals. I have added the array indices as the constraints to the solver for checking if the reals at these indices have the minimum difference.  When I was trying to use ForAll() in the minimum checking constraint, the solver was not giving the correct results. 

But, when I was using the clause: s.add(a>=lb,a<ub,b>=lb,b<ub,Implies(a==x,b!=y), Implies(b==x,a!=y),d1==CH[a]-CH[b],d2==CH[x]-CH[y],Abs(d1) > Abs(d2))  instead of 
s.add(ForAll([a, b],And(a>=lb,a<ub,b>=lb,b<ub,Implies(a==x,b!=y), Implies(b==x,a!=y),d1==CH[a]-CH[b],d2==CH[x]-CH[y],Abs(d1) < Abs(d2)) )) and checking for the minimum difference on UNSAT decision of the solver, I was getting the correct results. 

I tried a lot to understand why the clause on ForAll quantifier is unable to give the correct answer but failed. Please help me in addressing this issue.  The code is given below.
----------------------------------
from z3 import *

def Abs(x):
    return If(x >= 0,x,-x)
    
s=Solver()

x, y, lb, ub, a, b=Ints('x y lb ub a b')
d1, d2=Reals('d1 d2')

CH = Array('ch',RealSort(),RealSort())

#check if the difference between CH[x] and CH[y] is the minimum  or not

s.add(CH[0]==0.6,CH[1]==0.2,CH[2]==0.4,CH[3]==0.8)  # CH has 4 elements
s.add(x==3,y==1,lb==0,ub==3)  # Minimum case for x=3 and y=1, lb and ub are lower and upper bounds rsp. of the array having elements
s.add(ForAll([a, b],And(a>=lb,a<ub,b>=lb,b<ub,Implies(a==x,b!=y), Implies(b==x,a!=y),d1==CH[a]-CH[b],d2==CH[x]-CH[y],Abs(d1) < Abs(d2)) ))

if(s.check()==sat):
	print "Min"
	print s.model()
else:
	print "Not Min"

#s.add(a>=lb,a<ub,b>=lb,b<ub,Implies(a==x,b!=y), Implies(b==x,a!=y),d1==CH[a]-CH[b],d2==CH[x]-CH[y],Abs(d1) > Abs(d2))  # UNSAT on this condition is working

---------------------------------------

More interestingly, for the testing purpose, if I just run the following code which is expected to give an SAT answer, it is  giving UNSAT.

from z3 import *

def Abs(x):
    return If(x >= 0,x,-x)

s=Solver()
x, y, lb, ub, a, b=Ints('x y lb ub a b')
d1, d2=Reals('d1 d2')

CH = Array('ch',RealSort(),RealSort())

s.add(CH[0]==0.6,CH[1]==0.2,CH[2]==0.4,CH[3]==0.8)  # CH has 4 elements
s.add(x==3,y==1,lb==0,ub==3)  # Minimum case for x=3 and y=1, lb and ub are lower and upper bounds rsp. of the array having elements

#s.add(ForAll([a, b],And(a>=lb,a<ub,b>=lb,b<ub,Implies(a==x,b!=y), Implies(b==x,a!=y),d1==CH[a]-CH[b],d2==CH[x]-CH[y],Abs(d1) < Abs(d2)) ))

s.add(ForAll([a,b],And(a>=lb,a<ub,b>=lb,b<ub,d1==CH[a]-CH[b],d1<10) ))

if(s.check()==sat):
	print "Min"
	print s.model()
else:
	print "Not Min"

What I guess from it, it the problem with the underlying logic of the ForAll() structure, which I am not able to find out. Could anyone help me to figure it out?

Thanks in advance.

**Comment by wintersteiger** [comment]
`ForAll([a, b],And(a>=lb, ...` means that your require `a >= b` be true for all integers, which it isn't, so the formula is indeed unsatisfiable. You probably want to state something like `ForAll([a, b],Implies(a>=lb, c))` which means that `c` only has to be true when `a` is larger than `lb`.

**Comment by sg61189** [comment]
Thank you. I have got the point.
