### ISSUE TITLE
Python serializing expressions

### ISSUE THREAD

**Issue by JoranHonig** [Z3Prover/z3#2674]
I've not been able to find any documentation around this subject.

Between two runs of a program I'd like to re-use smt expressions.  
To do that I believe I need some way to serialize and deserialize z3 expressions.
I've found a way to do this using solvers, but it is not very pretty:

```python3
from z3 import Int, Solver, parse_smt2_string
x = Int('x')


def serialize(expression):
    solver = Solver()
    solver.add(expression == expression)
    return solver.sexpr()


def deserialise(expression):
    parsed_conditions = parse_smt2_string(expression)
    return parsed_conditions[0].children()[0]

print(serialize(x))
print(deserialise(serialize(x)))
```

So my question is: 
Is there a better way to do this right now? / Will there be a better way in the future?

**Comment by NikolajBjorner** [comment]
For formulas you use
 
   def deserialize(formula):
         s = Solver()
         s.from_string(formula)
         return s.assertions()    # returns vector of formulas

It is not a common ask to serialize expressions.
It can be wrapped in ways you suggest and given that Z3 relies on SMTLIB2 conventions for its main text-based interface interactions a method on Expr for converting between strings and expressions would end up using the same approach you are taking.
