### ISSUE TITLE
Why is the default value of `smt.str.use_binary_search` false?

### ISSUE THREAD

**Issue by embg** [Z3Prover/z3#2681]
The solve time for the following formula on my machine, using z3 version 4.8.0, is more than 2 minutes:
```
(set-option :smt.string_solver z3str3)
(declare-const s String)
(declare-const len Int)
(assert (= (str.indexof s "\00") len))
(assert (>= len 0))
(assert (not (= (bvand ((_ int2bv 12) len) #xF00) #x000)))
(check-sat)
(get-model)
```
However, if I add `(set-option :smt.str.use_binary_search true)` to the top, the solve time drops to under 2 seconds. Are there any drawbacks to using this option? Or should I always enable it when I use `z3str3`?

**Comment by NikolajBjorner** [comment]
@mtrberzi

**Comment by mtrberzi** [comment]
There is a known issue with the binary search where temporary variables created during the search will sometimes cause the solver to crash. For this reason it is not the default. If you would like to use it and you do encounter crashes, please do send bug reports. However I am planning to replace both this search strategy and the default one with something more robust in the near future, so it may become obsolete.
