### ISSUE TITLE
An issue about  expr_vector

### ISSUE THREAD

**Issue by laibunizi1022** [Z3Prover/z3#2684]
Hi! I‘m a new to Z3,I saw the Sudoku program example written in C++.  In this sample program, I found that a two-dimensional array was stored in a one-dimensional  expr_vector.   But now, I need to constrain a four-dimensional array, What should I do?   Thank you  for your attention!

**Comment by NikolajBjorner** [comment]
std::vector<std::vector<std::vector<expr_vector*>>>

**Comment by laibunizi1022** [comment]
In python, We can limit each element by traversing the two-dimensional array (X[i][j])as following:
"  
X = [ [ Int("x_%s_%s" % (i+1, j+1)) for j in range(9) ]
      for i in range(9) ]
cells_c  = [ And(1 <= X[i][j], X[i][j] <= 9)
             for i in range(9) for j in range(9) ]
"
But in C++,The sample program uses the following method“
for (unsigned i = 0; i < 9; ++i)
        for (unsigned j = 0; j < 9; ++j) {
            s.add(x[i*9+j] >=1 && x[i*9+j]  <=  9);
        } “
I want to know if C++ can traverse array in the same way?  For instance,How can I use "X[i][j][k]" to constrain the elements of each position of a 3D array?

**Comment by laibunizi1022** [comment]
In python, We can limit each element by traversing the two-dimensional array (X[i][j])as following:
"
X = [ [ Int("x_%s_%s" % (i+1, j+1)) for j in range(9) ]
for i in range(9) ]
cells_c = [ And(1 <= X[i][j], X[i][j] <= 9)
for i in range(9) for j in range(9) ]
"
But in C++,The sample program uses the following method“
for (unsigned i = 0; i < 9; ++i)
for (unsigned j = 0; j < 9; ++j) {
s.add(x[i*9+j] >=1 && x[i*9+j] <= 9);
} “
I want to know if C++ can traverse array in the same way? For instance,How can I use "X[i][j][k]" to constrain the elements of each position of a 3D array?

**Comment by laibunizi1022** [comment]
I am looking forward your early reply,thank you very much!
