### ISSUE TITLE
Profiling rule usage in SPACER

### ISSUE THREAD

**Issue by NikolajBjorner** [Z3Prover/z3#2685]
Overall question: what is the profiling strategy for SPACER?
Specific question: can we profile rule usage, e.g., number of times a rule is used in create_children.

**Comment by agurfinkel** [comment]
I have counter and times at key places. These are printed with `-st`. I use profiler (vtune) for anything lower level. 

Rules are tagged in the encoding. `create_children` knows what rule it is using to create predecessors. This can be logged.

Mapping rules in Spacer to original rules is non-trivial. I don't see how to summarize the result.

Perhaps we can add a rule name that indicates that a rule should be counted. Statistics can be computed for all marked rules. This will work as long as rule names are propagated during pre-processing. Although, if you are profiling, you might want to run pre-processing first and run spacer without pre-processing on the result.

**Comment by NikolajBjorner** [comment]
Rules are "accounted objects". There is an "instructions" count in the cost field. spacer_context would need to handle rules as mutable (currently rules are const objects).
Then increment instructions on every expansion. 
The finite table datalog engine has a mode where it prints verbose statistics. 
Something like that can be a way to go, though I would say if it is doable over statistics(), then it is much easier to discover. 
I take pretty printing a rule or the head predicate name followed by a rule digest, suffices as a key when inserting such information into statistics.
