### ISSUE TITLE
capi: unknown parameter 'model.partial'

### ISSUE THREAD

**Issue by aep** [Z3Prover/z3#2687]
https://github.com/Z3Prover/z3/blob/ecba7b3cde4c1125ac1db63b7b7d63b299051b4a/src/api/z3_api.h#L5094

mentiones that Z3_model_eval can fail if the model is incomplete, if MODEL_PARTIAL has been set.

i want it to fail, instead of returning an arbitrary interpretation, but this is the only mention of  MODEL_PARTIAL in the entire source code, so its unclear how to set that behavior. 

in smt2 we can 
```
(set-option :model.partial true)
```
which has  the expected result, but this does not work in C

```C
Z3_set_param_value(cfg, "model.partial", "true") 
```

prints

```
WARNING: unknown parameter 'model.partial'
Legal parameters are:
  auto_config (bool) (default: true)
  debug_ref_count (bool) (default: false)
  dot_proof_file (string) (default: proof.dot)
  dump_models (bool) (default: false)
  model (bool) (default: true)
  model_compress (bool) (default: true)
  model_validate (bool) (default: false)
  proof (bool) (default: false)
  rlimit (unsigned int) (default: 0)
  smtlib2_compliant (bool) (default: false)
  stats (bool) (default: false)
  timeout (unsigned int) (default: 4294967295)
  trace (bool) (default: false)
  trace_file_name (string) (default: z3.log)
  type_check (bool) (default: true)
  unsat_core (bool) (default: false)
  well_sorted_check (bool) (default: false)
```

on the other hand, this does not error, but also has no effect:

```
Z3_global_param_set("model.partial", "true") 
```

the entire model still has specified values, even for functions that are completely unconstrained

**Comment by NikolajBjorner** [comment]
Z3_set_param_value is used only for the parameters that are printed in the error values. Use Z3_global_param_set. 
A repro would help.
Here is one scenario:

from z3 import *

set_param("model.partial", True)
x = Int('x')
f = Function('f', IntSort(), IntSort())
s = Solver()
s.add(x == f(x))
s.check()
print(s.model())

I get the following result:
C:\z3\build\python>p.py
[x = 0, f = [0 -> 0, else -> #unspecified]]

**Comment by aep** [comment]
> A repro would help.

yeah. python is a pretty difficult language tho. i'll try to extract an smt from the c code

but Z3_global_param_set is correct, and this is an unrelated problem?

working around it by extracting the value, then adding an assert for the opposite value and seeing if the solve fails for now :/

**Comment by aep** [comment]
get-value doesn't seem to do the right thing in smt2 either

```
(set-option :model.partial true)
(declare-fun x (Int) Int)
(check-sat)
(get-value (x 0))
```

outputs:

```
sat
((x (_ as-array x))
 (0 0))
```

i'm beginning to think this is intended behavior and whatever an 'incomplete' model is doesn't match my idea of it. i was expecting to be able to obtain the difference between an exact value and a range.

i.e in
```
i = 2 * 2;
j = 2 * a;
```
j and i can both be 2 to make the model sat, but i'd like to know that i can not be any other value

**Comment by NikolajBjorner** [comment]
Right, there are no guarantees that z3 returns a "most general" or parametric model.
