### ISSUE TITLE
z3py API checks extensively for errors

### ISSUE THREAD

**Issue by sjunges** [Z3Prover/z3#2689]
Dear developers,

In some recent test code, I heavily interact with z3 via the Python bindings. 
When profiling, I discovered that every call induces a Elementaries.Check call, which makes up more than 10% of the run time, even before further optimisations. 

Is there an option to reduce the number of these checks? Do you foresee such a feature could be added? Am I doing something wrong?

Best,
Sebastian Junges

**Comment by NikolajBjorner** [comment]
have you tried setting

z3.Z3_DEBUG = False

**Comment by sjunges** [comment]
Hi,

many thanks for your swift response. 

* z3.Z3_DEBUG is set to false after importing z3. 
* I use the lower-level z3 API to avoid coerce etc.
* I run python with -O
* I think that there might be still some z3-object to int/string etc extraction as I am using the models created by z3. So the overhead might be due to the Check() from there.

It is not super easy to provide a minimal working example, but I could cook something up if that would be helpful. 
Generally, it would be cool if these error checks could be disabled in something like z3.PERFORMANCE or even z3.UNSAFE. Of course, 10% is not critical, but if I start to optimise other calls, this might become even more significant.

**Comment by NikolajBjorner** [comment]
Even without error checking, Python is super slow compared to C#, C++, OCaml, and even Java.
Python is great for prototyping, but not for production.

**Comment by sjunges** [comment]
fair enough :-)
