### ISSUE TITLE
How to use std::<std::vector<std::vector<expr_vector*>>> in C++?

### ISSUE THREAD

**Issue by laibunizi1022** [Z3Prover/z3#2691]
Hi , I am so sorry to ask this question again, because this problem has been bothering me for a long time.  In python, We can limit each element by traversing the two-dimensional array (X[i][j])as following:
"
X = [ [ Int("x_%s_%s" % (i+1, j+1)) for j in range(9) ]
for i in range(9) ]
cells_c = [ And(1 <= X[i][j], X[i][j] <= 9)
for i in range(9) for j in range(9) ]
"
But in C++,The sample program uses the following method“
for (unsigned i = 0; i < 9; ++i)
for (unsigned j = 0; j < 9; ++j) {
s.add(x[i9+j] >=1 && x[i9+j] <= 9);
} “

But now，I am designing a schedule for a TTE，I need to process arrays above 3D！I want to know if C++ can traverse array in the same way? For instance,How can I use "X[i][j][k]" to constrain the elements of each position of a 3D array?

**Comment by laibunizi1022** [comment]
Thank you for your sincere help!

**Comment by NikolajBjorner** [comment]
perhaps use stackoverflow for programming questions.
Creating nested vectors is not specific to Z3.

**Comment by laibunizi1022** [comment]
Thank you for  your  help!   Do you mean that the method of creating nested vectors in Z3 is not desirable?  Do I have to limit a three-dimensional array by the following method?
“for (int i = 0; i < msg_cnt; ++i)
		for (int j = 0; j < row_cnt; ++j)
			for (int  k = 0; k < col_cnt; ++k){
				s.add(X[i*row_cnt*col_cnt + j*row_cnt + k] >= 0 && 
                                        X[i*row_cnt*col_cnt + j*row_cnt + k] <= 1)”

**Comment by laibunizi1022** [comment]
Thank you for your help!  I  know creating nested vectors is not specific to Z3. As I mentioned above，I want to know if I can  traverse a three-dimensional array using X[i][j][k] like python?
Do you mean that it is not advisable to create nested vectors ?

**Comment by laibunizi1022** [comment]
And  could you please  rewrite the Sudoku program by creating a nested vector in "example.cpp"?

**Comment by laibunizi1022** [comment]
？
