### ISSUE TITLE
Unexpected result on simple constraints

### ISSUE THREAD

**Issue by gtwgtwgtw** [Z3Prover/z3#2694]
(declare-const x Int)
(declare-const y Int)
(declare-const a3 Real)
(assert (= 3 (* a3 a3)))
(assert (= 2 (/ x y)))
(check-sat)

Z3 outputs 'unknown'
And it outputs 'sat' after deleting any one of assert

**Comment by NikolajBjorner** [comment]
z3 isn't a decision procedure for mixed integer / real non-linear constraints.
