### ISSUE TITLE
Info on new Z3 releases 

### ISSUE THREAD

**Issue by pjljvandelaar** [Z3Prover/z3#2695]
I can subscribe to be informed about new Z3 releases using `watch releases`.
I can however nowhere find when new releases are planned.
I would like this info, since I am maintaining a [tool](https://github.com/TorXakis/TorXakis) that uses problem solvers.
Based on this information, I could better decide 
* whether upgrading to the latest officially released Z3 version is worthwhile,
* and when to release our tool.

Can this information be provided? For example, as time line on the wiki?

See for example our [tools' planned releases page](https://github.com/TorXakis/TorXakis/wiki/Planned-Releases)

**Comment by NikolajBjorner** [comment]
I mainly make decisions on release based on user requests, not some pre-determined plan.
Secondarily, I create a new release when enough features and bug fixes have accumulated.
A main reason for a new release will be updating our NuGet package story with symbols.

**Comment by NikolajBjorner** [comment]
I am now using RELEASE_NOTES for comments on plans.
