### ISSUE TITLE
Getting different results using "parseSMTLIB2String" vs. rise4fun online tool

### ISSUE THREAD

**Issue by echo-xiangchen** [Z3Prover/z3#2696]
Hello, I'm an undergraduate student using z3 to develop my 4th-year project, and I'm trying a simple test case with the encoding:

`(declare-const s Bool)`
`(assert (exists ((p Bool))(or (not s) p)))`
`(check-sat)`
`(get-model)`

The rise4fun online tool gives me the result:
`sat`
`(model `
  `(define-fun s () Bool`
    `false)`
`)`

However, when I try this same string using "parseSMTLIB2String" method in Java, it gives me the following result:
`sat`
`(define-fun s () Bool`
  `true)`

         
Below is my simple Java class for testing the encoding:
`public class TestZ3 { `                
       `public static void main(String[] args){ `
        	         `HashMap<String, String> cfg = new HashMap<String, String>();`
        	          `cfg.put("model", "true");`
        	`Context ctx = new Context();`
        	`BoolExpr[] formula = ctx.parseSMTLIB2String("(declare-const s Bool)"`
        			`+ "(assert (exists ((p Bool))(or (not s) p)))", null, null, null, null);`
        	`Solver s = ctx.mkSolver();`
        	`s.add(formula);`
        	`Status result = s.check();`
        	`if (result == Status.SATISFIABLE){  `
        		`System.out.println("sat");`
        		`Model m = s.getModel();`
        		`System.out.println(m.toString());`
            `}  `
           ` else if(result == Status.UNSATISFIABLE)  {`
                `System.out.println("unsat"); ` 
`}`
           ` else {`  
               `System.out.println("unknow");` 
    `} ` 
`}`
`}`

I also test it in Python using the same encoding, it gives me the same result as my Java output.
I'm wondering why I got different results using "parseSMTLIB2String" vs. rise4fun online tool.
I'm using Eclipse on Mac OS to develop the program.
Thank you so much!

**Comment by NikolajBjorner** [comment]
Not sure, I get

      [s = True]

for 

      from z3 import *
      fmls = parse_smt2_string("(declare-const s Bool) (assert (exists ((p Bool))(or (not s) p)))")
      s = Solver()
      s.add(fmls)
      s.check()
      print(s.model())
