### ISSUE TITLE
Different results (unsat and no termination) for the same problem with different Z3 versions

### ISSUE THREAD

**Issue by ylya** [Z3Prover/z3#2697]
For the same problem older Z3 version terminates with unsat, newer version does not terminate:

b0aaa4c6d7a739eb5e8e56a73e0486df46483222 unsat 
a2b18a37ec2a8c2a031956ae8b4bddf4340719e8 no termination

[safemath-sub.txt](https://github.com/Z3Prover/z3/files/3835668/safemath-sub.txt)

**Comment by agurfinkel** [comment]
This example seem to depend on the underlying smt solver magically finding the right interpolant. Unfortunately, this is currently not very stable. We are working on better treating such cases, but public release of the new approach is not yet available (nor is tested with arrays).

However, it seems that enabling quantifiers works great here. The option is `fp.spacer.ground_pobs=false` makes it work once again on the current master.

**Comment by ylya** [comment]
Thank you very much for the explanation and the option suggestion!
