### ISSUE TITLE
Getting Different Results when using https://rise4fun.com/Z3

### ISSUE THREAD

**Issue by mjblackhorse** [Z3Prover/z3#2698]
For the following problem 

(set-option :smt.string_solver auto)
(declare-datatypes () ((Object Null NotNull)))
(define-sort Char () (_ BitVec 8))
(declare-fun containsKey (Object String) Bool)
(declare-fun containsKey (String String) Bool)
(declare-fun containsKey (Int String) Bool)
(declare-fun containsKey (Real String) Bool)
(declare-fun containsKey (Bool String) Bool)
(declare-fun containsKey ((Array Int Int) String) Bool)
(declare-fun containsKey ((Array String Int) String) Bool)
(declare-fun containsKey ((Array Real Int) String) Bool)
(declare-fun containsKey ((Array Bool Int) String) Bool)
(declare-fun containsKey ((Array Object Int) String) Bool)
(define-fun ToInt ((x Int)) (_ BitVec 8) ((_ int2bv 8) x))
(declare-fun getAction (Object) String)
(declare-fun fromIntent (Object) Object)
(declare-fun fromIntent (String) Object)
(declare-fun fromIntent (Int) Object)
(declare-fun fromIntent (Real) Object)
(declare-fun fromIntent (Bool) Object)
(declare-fun fromIntent ((Array Int Int)) Object)
(declare-fun fromIntent ((Array Real Int)) Object)
(declare-fun fromIntent ((Array String Int)) Object)
(declare-fun fromIntent ((Array Object Int)) Object)
(declare-fun fromIntent ((Array Bool Int)) Object)
(declare-datatypes () ((ParamRef (mk-paramref (index Int) (type String) (method String)))))
(declare-fun hasParamRef (Object String ParamRef) Int)
(declare-fun hasParamRef (String String ParamRef) Int)
(declare-fun hasParamRef (Int String ParamRef) Int)
(declare-fun hasParamRef (Real String ParamRef) Int)
(declare-fun hasParamRef (Bool String ParamRef) Int)
(declare-fun hasParamRef ((Array String Int) String ParamRef) Int)
(declare-fun hasParamRef ((Array Object Int) String ParamRef) Int)
(declare-fun hasParamRef ((Array Int Int) String ParamRef) Int)
(declare-fun hasParamRef ((Array Real Int) String ParamRef) Int)
(declare-fun hasParamRef ((Array Bool Int) String ParamRef) Int)
(declare-fun isNull (String) Bool)
(declare-fun isNull (Object) Bool)
(declare-fun oEquals (String Object) Bool)
(declare-fun oEquals (Object String) Bool)
(declare-const cats (Array Int String))
(declare-const keys (Array Int String))
(declare-const $r2_android.content.Intent_Service1_Entry_dummyMainClass Object )
(declare-const $r1_cn.edu.nju.moon.array.Service1_Service1_Entry_dummyMainClass Object )
(declare-const $r0_java.lang.String-Arr_Service1_Entry_dummyMainClass (Array String Int) )
(declare-const pr0_java.lang.String-Arr_Service1_Entry_dummyMainClass ParamRef )
(declare-const $i0_int_onStart_cn.edu.nju.moon.array.Service1_7 Int )
(declare-const $r2_int-Arr_onStart_cn.edu.nju.moon.array.Service1_2 (Array Int Int) )
(declare-const $r1_android.content.Intent_onStart_cn.edu.nju.moon.array.Service1 Object )
(declare-const pr0_android.content.Intent_onStart_cn.edu.nju.moon.array.Service1 ParamRef )
(declare-const $i0_int_onStart_cn.edu.nju.moon.array.Service1 Int )
(declare-const pr1_int_onStart_cn.edu.nju.moon.array.Service1 ParamRef )
(declare-const $r0_cn.edu.nju.moon.array.Service1_onStart_cn.edu.nju.moon.array.Service1 Object )
(assert ( = (index pr0_java.lang.String-Arr_Service1_Entry_dummyMainClass) 0))
(assert ( = (type pr0_java.lang.String-Arr_Service1_Entry_dummyMainClass) "java.lang.String[]"))
(assert ( = (method pr0_java.lang.String-Arr_Service1_Entry_dummyMainClass) "dummyMainClass.Service1_Entry"))
(assert (= (hasParamRef $r0_java.lang.String-Arr_Service1_Entry_dummyMainClass "dummyMainClass.Service1_Entry" pr0_java.lang.String-Arr_Service1_Entry_dummyMainClass) 0))
(assert (= $i0_int_onStart_cn.edu.nju.moon.array.Service1_7 1))
(assert (>= $i0_int_onStart_cn.edu.nju.moon.array.Service1_7 -2147483648))
(assert (<= $i0_int_onStart_cn.edu.nju.moon.array.Service1_7 2147483647))
(assert (= $i0_int_onStart_cn.edu.nju.moon.array.Service1_7 (select $r2_int-Arr_onStart_cn.edu.nju.moon.array.Service1_2 0)))
(assert (= (containsKey $r2_int-Arr_onStart_cn.edu.nju.moon.array.Service1_2 "IntArray") true))
(assert (= (fromIntent $r2_int-Arr_onStart_cn.edu.nju.moon.array.Service1_2) $r1_android.content.Intent_onStart_cn.edu.nju.moon.array.Service1))
(assert ( = (index pr0_android.content.Intent_onStart_cn.edu.nju.moon.array.Service1) 0))
(assert ( = (type pr0_android.content.Intent_onStart_cn.edu.nju.moon.array.Service1) "android.content.Intent"))
(assert ( = (method pr0_android.content.Intent_onStart_cn.edu.nju.moon.array.Service1) "cn.edu.nju.moon.array.Service1.onStart"))
(assert (= (hasParamRef $r1_android.content.Intent_onStart_cn.edu.nju.moon.array.Service1 "cn.edu.nju.moon.array.Service1.onStart" pr0_android.content.Intent_onStart_cn.edu.nju.moon.array.Service1) 0))
(assert (>= $i0_int_onStart_cn.edu.nju.moon.array.Service1 -2147483648))
(assert (<= $i0_int_onStart_cn.edu.nju.moon.array.Service1 2147483647))
(assert ( = (index pr1_int_onStart_cn.edu.nju.moon.array.Service1) 1))
(assert ( = (type pr1_int_onStart_cn.edu.nju.moon.array.Service1) "int"))
(assert ( = (method pr1_int_onStart_cn.edu.nju.moon.array.Service1) "cn.edu.nju.moon.array.Service1.onStart"))
(assert (= (hasParamRef $i0_int_onStart_cn.edu.nju.moon.array.Service1 "cn.edu.nju.moon.array.Service1.onStart" pr1_int_onStart_cn.edu.nju.moon.array.Service1) 1))
(assert (= $r2_android.content.Intent_Service1_Entry_dummyMainClass $r1_android.content.Intent_onStart_cn.edu.nju.moon.array.Service1))
(assert (= 0 $i0_int_onStart_cn.edu.nju.moon.array.Service1))
(check-sat-using (then qe smt))
(get-model)

I tried to solve via https://rise4fun.com/Z3, and I got the following result:

sat
(model 
  (define-fun pr0_android.content.Intent_onStart_cn.edu.nju.moon.array.Service1 () ParamRef
    (mk-paramref 0
             "android.content.Intent"
             "cn.edu.nju.moon.array.Service1.onStart"))
  (define-fun $r1_android.content.Intent_onStart_cn.edu.nju.moon.array.Service1 () Object
    NotNull)
  (define-fun $r0_java.lang.String-Arr_Service1_Entry_dummyMainClass () (Array String Int)
    (_ as-array k!0))
  (define-fun pr0_java.lang.String-Arr_Service1_Entry_dummyMainClass () ParamRef
    (mk-paramref 0 "java.lang.String[]" "dummyMainClass.Service1_Entry"))
  (define-fun $i0_int_onStart_cn.edu.nju.moon.array.Service1_7 () Int
    1)
  (define-fun pr1_int_onStart_cn.edu.nju.moon.array.Service1 () ParamRef
    (mk-paramref 1 "int" "cn.edu.nju.moon.array.Service1.onStart"))
  (define-fun $r2_int-Arr_onStart_cn.edu.nju.moon.array.Service1_2 () (Array Int Int)
    (_ as-array k!1))
  (define-fun $r2_android.content.Intent_Service1_Entry_dummyMainClass () Object
    NotNull)
  (define-fun $i0_int_onStart_cn.edu.nju.moon.array.Service1 () Int
    0)
  (define-fun hasParamRef ((x!0 (Array String Int)) (x!1 String) (x!2 ParamRef)) Int
    (ite (and (= x!0 (_ as-array k!0))
              (= x!1 "dummyMainClass.Service1_Entry")
              (= x!2
                 (mk-paramref 0
                              "java.lang.String[]"
                              "dummyMainClass.Service1_Entry")))
      0
      0))
  (define-fun hasParamRef ((x!0 Object) (x!1 String) (x!2 ParamRef)) Int
    (ite (and (= x!0 NotNull)
              (= x!1 "cn.edu.nju.moon.array.Service1.onStart")
              (= x!2
                 (mk-paramref 0
                              "android.content.Intent"
                              "cn.edu.nju.moon.array.Service1.onStart")))
      0
      0))
  (define-fun containsKey ((x!0 (Array Int Int)) (x!1 String)) Bool
    (ite (and (= x!0 (_ as-array k!1)) (= x!1 "IntArray")) true
      true))
  (define-fun k!1 ((x!0 Int)) Int
    (ite (= x!0 0) 1
      1))
  (define-fun k!0 ((x!0 String)) Int
    22)
  (define-fun hasParamRef ((x!0 Int) (x!1 String) (x!2 ParamRef)) Int
    (ite (and (= x!0 0)
              (= x!1 "cn.edu.nju.moon.array.Service1.onStart")
              (= x!2
                 (mk-paramref 1 "int" "cn.edu.nju.moon.array.Service1.onStart")))
      1
      1))
  (define-fun fromIntent ((x!0 (Array Int Int))) Object
    (ite (= x!0 (_ as-array k!1)) NotNull
      NotNull))
)

I also tried to solve it directly via installed Z3 tool, but the obtained result was different from the above:

sat
(model 
  (define-fun $i0_int_onStart_cn.edu.nju.moon.array.Service1 () Int
    0)
  (define-fun $r1_android.content.Intent_onStart_cn.edu.nju.moon.array.Service1 () Object
    Null)
  (define-fun $r0_java.lang.String-Arr_Service1_Entry_dummyMainClass () (Array String Int)
    ((as const (Array String Int)) 0))
  (define-fun $r2_android.content.Intent_Service1_Entry_dummyMainClass () Object
    Null)
  (define-fun pr0_java.lang.String-Arr_Service1_Entry_dummyMainClass () ParamRef
    (mk-paramref 0 "java.lang.String[]" "dummyMainClass.Service1_Entry"))
  (define-fun pr1_int_onStart_cn.edu.nju.moon.array.Service1 () ParamRef
    (mk-paramref 1 "int" "cn.edu.nju.moon.array.Service1.onStart"))
  (define-fun $i0_int_onStart_cn.edu.nju.moon.array.Service1_7 () Int
    1)
  (define-fun $r2_int-Arr_onStart_cn.edu.nju.moon.array.Service1_2 () (Array Int Int)
    ((as const (Array Int Int)) 1))
  (define-fun pr0_android.content.Intent_onStart_cn.edu.nju.moon.array.Service1 () ParamRef
    (mk-paramref 0
             "android.content.Intent"
             "cn.edu.nju.moon.array.Service1.onStart"))
  (define-fun cats () (Array Int String)
    ((as const (Array Int String)) ""))
  (define-fun keys () (Array Int String)
    ((as const (Array Int String)) ""))
  (define-fun $r0_cn.edu.nju.moon.array.Service1_onStart_cn.edu.nju.moon.array.Service1 () Object
    Null)
  (define-fun $r1_cn.edu.nju.moon.array.Service1_Service1_Entry_dummyMainClass () Object
    Null)
  (define-fun containsKey ((x!0 (Array Int Int)) (x!1 String)) Bool
    true)
  (define-fun hasParamRef ((x!0 Object) (x!1 String) (x!2 ParamRef)) Int
    0)
  (define-fun hasParamRef ((x!0 Int) (x!1 String) (x!2 ParamRef)) Int
    1)
  (define-fun hasParamRef ((x!0 (Array String Int)) (x!1 String) (x!2 ParamRef)) Int
    0)
  (define-fun fromIntent ((x!0 (Array Int Int))) Object
    Null)
  (define-fun getAction ((x!0 Object)) String
    "")
  (define-fun fromIntent ((x!0 Object)) Object
    Null)
  (define-fun hasParamRef ((x!0 Bool) (x!1 String) (x!2 ParamRef)) Int
    0)
  (define-fun oEquals ((x!0 Object) (x!1 String)) Bool
    false)
  (define-fun containsKey ((x!0 Object) (x!1 String)) Bool
    false)
  (define-fun isNull ((x!0 String)) Bool
    false)
)

I expect the result obtain via https://rise4fun.com/Z3, how could I get it with the install Z3?

**Comment by NikolajBjorner** [comment]
formulas don't necessarily have unique models. The models generated by Z3 change when the algorithms inside of z3 are updated. To control busy-work, the version on rise4fun.com is not updated with every release.
