### ISSUE TITLE
Assigning values to variables 

### ISSUE THREAD

**Issue by Tephilla** [Z3Prover/z3#2701]
I wish to declare a variable(t) : constant (true). 

 solverInstance.add(t==true) adds a constraint to the solverInstance. Is there a method to assign a value to a variable

**Comment by NikolajBjorner** [comment]
The use of terminology _assignment_ doesn't align well with first-order formalism conventions. Similar to pure functional programs, logical formulas don't have side-effects, so you can't assign a variable to a value one place and then reassign it. 
When you write a program that creates formulas, you can use variables as place holders for terms and formulas. You can assign these placeholders different values, but that is outside of the logical formalisms.

**Comment by Tephilla** [comment]
Thank you for your comment. It was helpful.
