### ISSUE TITLE
Specifying Linear Temporal Logic formulae

### ISSUE THREAD

**Issue by Tephilla** [Z3Prover/z3#2702]
Using Z3 CPP API, an expression of type **expr** can be constructed for propositional formulae. 
Does Z3 support Linear Temporal Logic formulae? And how does one go about representing a LTL formula?

**Comment by NikolajBjorner** [comment]
Z3's logic formalism is simply-typed first-order logic with some built-in theories, such as arithmetic. It does not provide connectives from other formalisms. While reification can be applied to LTL, but Z3 does not have any particular support to solve formulas from the unary fragment.

**Comment by Tephilla** [comment]
Do you see future support for temporal operators in Z3, in the pipeline?

**Comment by NikolajBjorner** [comment]
No: the scope of z3 is classical logic and the main service is around algorithmic support for theories.
