### ISSUE TITLE
Simplification Question

### ISSUE THREAD

**Issue by gmCAD** [Z3Prover/z3#2703]
Why do the following two lines of similar python code produce different answers?

```python

#If statement with BitVec Output

a = BitVec('a', 2)

simplify(
    If(a==2, BitVecVal(1,1), BitVecVal(0,1)), 
    bit2bool=True
)

>> If(a == 2, 1, 0)

#If statement with Boolean Output

simplify(If(a==2, True, False))

>> a == 2
```
Is there a simplification option(s) that will allow the BitVec Equation to produce the same simplification result as the Boolean Output as shown below?  

```python 

#Ideal Z3 output

a = BitVec('a', 2)
simplify(If(a==2, BitVecVal(1,1), BitVecVal(0,1)), bit2bool=True)

>> a == 2
```

I'm using version 4.8.5.0

**Comment by NikolajBjorner** [comment]
The sort Bool is different from the sort BitVec(1).
The simplifier also preserves types, so the full expression has sort BitVec(1) and not Bool.
The sort of a == 2 is Bool, but the sort of BitVecVal(1,1) is BitVec(1).

**Comment by gmCAD** [comment]
Will Z3 try and convert BitVec(1) types into Bools if the simplifier bit2bool option is enabled?

**Comment by NikolajBjorner** [comment]
bit2bool is used internally during pre-processing formulas. It does not change the type top-level expressions. If you have a formula that uses bit-vectors, these may be rewritten.
