### ISSUE TITLE
.NET Enhancement: Api rework and Documentation

### ISSUE THREAD

**Issue by Marti2203** [Z3Prover/z3#2705]
Hello. I began playing around today with the .Net API and I saw some minor inconveniences which I did not like a lot. Would it be possible for me to make some tweaks to the API and get them accepted in a pull request or should I make my own fork? 
Another thing I have in mind is making some documentation as it was really hard to understand how to properly do maximization and why it works like that. I would be happy to have a discussion about the part with the optimization as I am really interested in the API and the possibilities it has.

**Comment by Marti2203** [comment]
I know it may be too vague for the API rework, but I am really interested to see if I can make the functions more generic and the system more type safe as currently it is just a lot of abstractness and documentation really would help out.

**Comment by NikolajBjorner** [comment]
sure, improvements is a constant feedback process based on experiences.
I often update the API as a result of working through applications.
As you can see from GitHub pull requests, reasonable improvements are welcome.

**Comment by Marti2203** [comment]
Okay, wonderful!
