### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by bkragl** [Z3Prover/z3#2707]
Most recent Z3 segfaults on the following input (generated from Boogie):
[smt2.log](https://github.com/Z3Prover/z3/files/3855117/smt2.log)

I get the following results on Ubuntu 16.04:
**4.8.5** (and earlier): `unsat`
**4.8.6**: `Segmentation fault` (without option `smt.ARITH.RANDOM_INITIAL_VALUE true`: `unsat`)
**4.8.7 (nightly)**: `Segmentation fault` (without option `smt.CASE_SPLIT 3`: `unsat`)

**Comment by NikolajBjorner** [comment]
it contains an impressive number of special options. 
One has been changed. From now on use:

```
(set-option :model.compact false)
```

I don't get the seg faults (yet) locally

**Comment by NikolajBjorner** [comment]
also, if I disable all options you set. Z3 is much faster

**Comment by bkragl** [comment]
Yeah, these are the options Boogie passes to Z3 by default.

Let me know if you need any other info for reproducing the segfaults, but I just use the binaries for Ubuntu (now I also ran it on Ubuntu 18.04 with the same result).
