### ISSUE TITLE
CMake: Don't build lp_test, shell, and test-z3

### ISSUE THREAD

**Issue by asmaloney** [Z3Prover/z3#2708]
I want to include z3 as a cmake submodule in another cmake-based project.

There doesn't seem to be a flag for turning off building of `lp_test`, `shell`, or `test-z3`.

Am I missing something? If not, would you accept a PR for this?

**Comment by NikolajBjorner** [comment]
yes, would accept if PR is reasonable

**Comment by asmaloney** [comment]
Thank you for putting in these changes.

One more suggestion: `Z3_ENABLE_EXAMPLE_TARGETS` should probably be turned off by default when using Z3 as a library submodule as well.
