### ISSUE TITLE
CMake: When adding options, prefix with "Z3_"

### ISSUE THREAD

**Issue by asmaloney** [Z3Prover/z3#2709]
If you use  library like this as a submodule in another project, it is very useful to have its options prefixed by the project name. Otherwise you end up with options sprinkled throughout the cmake interface and it's not obvious which project they are for.

e.g. `API_LOG_SYNC`, `BUILD_DOTNET_BINDINGS`, `ENABLE_TRACING_FOR_NON_DEBUG`, `INCLUDE_GIT_DESCRIBE`, etc..

This gets worse as you include more external libraries in your project. You can also end up with option name collisions.

As a bonus when adding a prefix, the graphical interface to cmake will group options together under the first "word" (up to the first "_"). So if they are all prefixed by "Z3_" they get grouped and it's much easier to manage.

**Comment by NikolajBjorner** [comment]
could you add pull request?

**Comment by NikolajBjorner** [comment]
suggestion seems to make sense, but implementing it will almost for sure break things.
Pointing out problems as part of this issue will be appreciated

**Comment by asmaloney** [comment]
These changes are great Nikolaj - thank you!
