### ISSUE TITLE
Changing rlimits yields (non-monotonic) fluctuations between unsat and unknown 

### ISSUE THREAD

**Issue by mschwerhoff** [Z3Prover/z3#2711]
Running x64 builds of Z3 4.8.6 [1] and 4.8.7.nightly [2] on Windows 10 x64, I observed fluctuations between `unsat` and `unknown` when changing the `rlimit` option. For example, for SMT file [logfile-01.smt2.txt](https://github.com/Z3Prover/z3/files/3855554/logfile-01.smt2.txt), where trying different `rlimit`s in lines 1893ff (search for comment `[PLACE A]`) affects the result of the final `check-sat` in line 1990 (search for comment `[PLACE B]`).

What surprises me a lot is the non-monotonic result for the `check-sat`:

    (set-option :rlimit 100000)   ;; UNKNOWN
    ; (set-option :rlimit 1000)   ;; UNSAT
    ; (set-option :rlimit 500)    ;; UNSAT
    ; (set-option :rlimit 50)     ;; UNKNOWN
    ; (set-option :rlimit 0)      ;; UNSAT (makes sense)

Using `get-info` to obtain the `rlimit-count`, I observe the following output between setting the `rlimit` and the *final* `check-sat` (there are several `push`-`pop`s and additional `check-sat`s in between):

    100K             | 1K               | 50               | 0
    -----------------|------------------|------------------|-----------------
    (:rlimit 101357) | (:rlimit 101357) | (:rlimit 101357) | (:rlimit 101357)
    (:rlimit 109677) | (:rlimit 102357) | (:rlimit 101407) | (:rlimit 109677)
    (:rlimit 118029) | (:rlimit 103357) | (:rlimit 101457) | (:rlimit 118029)
    (:rlimit 122794) | (:rlimit 104357) | (:rlimit 101507) | (:rlimit 126298)
    (:rlimit 122794) | (:rlimit 105377) | (:rlimit 101577) | (:rlimit 134592)
    (:rlimit 122794) | (:rlimit 105377) | (:rlimit 101577) | (:rlimit 142856)
    unknown          | unsat            | unknown          | unsat
    (:rlimit 122794) | (:rlimit 105435) | (:rlimit 101627) | (:rlimit 142944)

It seems that with an `rlimit` of 100K, all resources are spent prior to the final `check-sat`, for which then no work is done any more. In contrast, for 1K, some resources appear to be left over for the final `check-sat`.

I'm trying to replace `timeout`s with `rlimit`s, but `timeout`s appear to behave monotonic (more time --> higher chance of `UNSAT`), and I was hoping that `rlimit`s behave monotonic as well.

[1]  https://github.com/Z3Prover/z3/tree/z3-4.8.6
[2] https://github.com/Z3Prover/z3/commit/09523a4bca456aa1d7c4b510abff234586e9f8df

**Comment by NikolajBjorner** [comment]
The solver uses the same mechanism to check for timeout and rlimit. 
Thus, timeout is just a non-deterministic version of rlimit. 
The state that a previous call to a solver leaves influences search in the next call. For example, the expressions that are created during search will influence an ordering used for prioritizing search (for example, the order of case splits). So it is not realistic to expect monotonic behavior at a fine grained level.

**Comment by mschwerhoff** [comment]
Thank you for the explanation. I'm still puzzled about the following, though: in the `100K` column, the fact that the rlimit-count before and after is equal seems to suggest that no work is done for the final check-sat; this does not seem to be the case for the other columns. Is that also a consequence of differing solver states?

**Comment by NikolajBjorner** [comment]
rlimit is counted in ad-hoc places. It could be that "a very small amount of work" is performed, but rlimit isn't increased.
