### ISSUE TITLE
z3str3 assertion violation 

### ISSUE THREAD

**Issue by muchang** [Z3Prover/z3#2714]
Hi,
For this formula,
```
(declare-fun a () Bool)
(push)
(assert a)
(check-sat)
(assert false)
(push)
(check-sat)
```
z3 smt.string_solver=z3str3 will throw out an assertion violation:
```
ASSERTION VIOLATION
File: ../src/smt/smt_conflict_resolution.cpp
Line: 367
idx > 0
(C)ontinue, (A)bort, (S)top, (T)hrow exception, Invoke (G)DB
```

OS:Ubuntu18.04
Revision: d95b549

**Comment by muchang** [comment]
Close due to the duplicate.

**Comment by mtrberzi** [comment]
So, this may be of interest: The actual output of the solver is that it first prints `sat`, and then the assertion violation occurs. It also does not occur if `smt.string_solver=seq` is set, which is strange to me because nowhere in this formula does a string term occur.

**Comment by mtrberzi** [comment]
If I comment out the body of `context::add_theory_assumptions()` it solves correctly. @NikolajBjorner do you have any suggestions on why theory assumptions may be breaking this assertion?
