### ISSUE TITLE
Bool to String

### ISSUE THREAD

**Issue by bdrodes** [Z3Prover/z3#2716]
Is there any support to convert a bool to/from a string? 

I'm representing an array that can store arbitrary types for indices and values but using StringSort for both the domain and range. When converting an int to a str or vise versa, there is built in support, but I don't see anything analogous for converting strings to/from bool. 

If this were just an individual variable I was thinking I could do something like:
```
x = Bool('x')
...
s.add(If(x, String('x') == StringVal('True'), String('x') == StringVal('False')
```
This is a bit wonky though having two variables with the same name, but different types. Also, the issue with an array is I don't have a handle for an arbitrary index, especially if the index is symbolic. So I'm not sure how to name the new variable I create. I suppose I can make up something at random, but ideally I would ideally like to get back is a String I can compare against immediately (e.g, BoolToStr(x) == String('z')), which I don't think I can do in such an approach.

Any suggestions?

**Comment by NikolajBjorner** [comment]
How about:

```
BoolToStr(x) = If(x,"True","False")
StrToBool(s) = x == "True"
```

**Comment by bdrodes** [comment]
Ah. I think I was under the false impression that I had to provide a boolean expression for the if and else bodies, but re-reading the docs, I see I just didn't look closely enough. Ooops. Thanks.
