### ISSUE TITLE
Removing Constraints From Arrays

### ISSUE THREAD

**Issue by bdrodes** [Z3Prover/z3#2725]
When updating an array element, my current approach is to create a new array and set all indices to the old array using a ForAll expression. 
```
ForAll(tmp, Implies(tmp != index, new_array[tmp] == old_array[tmp]))
```
I'm seeing this approach slow down gradually as more elements are updated. Is it possible to remove prior constraints on an index instead? 

Something like:
```
ArrayUpdate(myArray, index, value)
```
Where all existing constraints on myArray[index] are blown away and the new value is used instead?

**Comment by NikolajBjorner** [comment]
The function 'Store' seems to be what you are describing.

```
    Store(myArray, index, value)
```

Generally, you can create lambda expressions.
Thus, something along the lines:

```
   def myStore(a,i,v):
         j = FreshConst(i.sort(), name='j') 
         return Lambda([j], If(i == j, v, a[i]))
```

**Comment by bdrodes** [comment]
Thanks again. Playing with that more I think it's getting me what I want and more efficiently!
