### ISSUE TITLE
z3 Segmentation fault

### ISSUE THREAD

**Issue by muchang** [Z3Prover/z3#2726]
Hi,
For this formula,
```
(declare-fun a () String)
(assert (= (str.len a) 20000))
(check-sat)
```
z3 will throw out a segmentation fault.

OS: Ubuntu 18.04
Revision: a0dcad0

**Comment by mtrberzi** [comment]
I cannot reproduce this issue on the latest version of Z3. Do you have a stack trace available?

**Comment by mtrberzi** [comment]
This is a bug of the sequence solver and not Z3str3.

**Comment by NikolajBjorner** [comment]
It runs out of stack space. There are possibly many other places that can force Z3 to run out of stack space and not all these scenarios are worth fixing.
