### ISSUE TITLE
Question about the branching heuristic in the SAT engine

### ISSUE THREAD

**Issue by rainoftime** [Z3Prover/z3#2734]
In the main loop of the CDCL search, the solver starts each round by selecting a literal, which is decided by the branching heuristic. 

Suppose a formula has four clauses `C1, C2, C3, C4`, such that `C1, C2` do not share any variables with `C3, C4`.  
Can the branching heuristic select multiple literals once? For instance, at some round, we select one literal from `C1, C2` and one literal from `C3, C4`. 
Or does Z3 already support some similar strategies?
Thank you!

**Comment by NikolajBjorner** [comment]
The CDCL engine selects a single literal at a time. The phase caching heuristic used by SAT solvers since it was introduced in RSAT is aimed to retain assignments that are independent of a conflict. So that when a conflict comes from C1, C2, backjumping does not affect the assignments that were found to work for C3, C4.

**Comment by rainoftime** [comment]
Thanks!
Suppose that we already know that `{ C1, C2 }` and `{ C3, C4 }` are two disjoint clauses sets, i.e., they do not share Boolean variables. 
May it be better to "force" the CDCL engine to solve the two independent sub-problems one-by-one?

If we solve the whole problem `{ C1, C2, C3, C4 }` altogether, the branching heuristic may be "worse".
For instance, assume that in the branching heuristic, the initial score for a literal `l`
is the number of clauses in which `l` appears. Then, the score of the two sub-problems may not be fair.

**Comment by NikolajBjorner** [comment]
There are possibly other reasons for applying slicing (as pre-processing): The overhead of watch-lists and other data-structures is reduced with the smaller problems.
