### ISSUE TITLE
Forward declaration of `fma` in C++ API does not match implementation

### ISSUE THREAD

**Issue by ahumenberger** [Z3Prover/z3#2735]
https://github.com/Z3Prover/z3/blob/84025d5c116b5da480f1e658e08029ef5b613886/src/api/c%2B%2B/z3%2B%2B.h#L1147

vs

https://github.com/Z3Prover/z3/blob/84025d5c116b5da480f1e658e08029ef5b613886/src/api/c%2B%2B/z3%2B%2B.h#L1631

**Comment by wintersteiger** [comment]
Thanks for the report, `fma` definitely needs a rounding mode!
