### ISSUE TITLE
Assertions in C++ API

### ISSUE THREAD

**Issue by ahumenberger** [Z3Prover/z3#2740]
I'm writing a Julia package which wraps the C++ API of Z3. The assertions in the API let Julia crash which is kind of annoying especially in the REPL mode of Julia, exceptions on the other hand could be caught and turned into Julia exceptions. 
I was thinking about defining a macro `Z3_ASSERT` and decide at compile time whether assertions or exceptions are used.

This would also require rethinking `context::enable_exceptions` in order to provide consistency. Can this be decided at compile time?

Finally, the default now is that assertions are used, and exceptions within `context::check_error()`. Can this be changed to exceptions being the default everywhere?

Provided that we agree on something, I can create a pull request.

**Comment by NikolajBjorner** [comment]
You can disable assert by setting NDEBUG. This should be set in release builds. Isn't this sufficient?

**Comment by ahumenberger** [comment]
Oh, I missed that. Sorry!
