### ISSUE TITLE
Soundnes bug in z3str3, formula with str.indexof, str.contains

### ISSUE THREAD

**Issue by wintered** [Z3Prover/z3#2742]
Hi,

here is another soundness bug in z3str3. On the following satisfiable formula z3str reports `unsat` while z3 reports `sat` on it.

```

(set-logic QF_S)
(declare-fun x () String)
(declare-fun y () String)
(assert (= (str.indexof x y 1) (str.len x)))
(assert (str.contains x y))
```
OS: Ubuntu 18.04
Revision: ba03d99

**Comment by mtrberzi** [comment]
@NikolajBjorner please tag `string` `z3str3`

**Comment by NikolajBjorner** [comment]
consolidated into #2736
