### ISSUE TITLE
Z3 hangs and Z3str3 segfaults on QF_SLIA formula

### ISSUE THREAD

**Issue by muchang** [Z3Prover/z3#2744]
Hi,
For this formula:
```
(declare-fun s () String)
(declare-fun x () Int)
(assert (>= x 66))
(assert (>= (str.indexof s "goodbye" x) 155))
(check-sat)
```
z3 hangs on it while z3str3 throws out an segmentation fault:
```
[528] % timeout -s 9 60 z3 small.smt2
Killed
[529] % z3 smt.string_solver=z3str3 small.smt2
Segmentation fault
```

OS: Ubuntu 18.04:
Revision: 07dcb0a

**Comment by mtrberzi** [comment]
Z3str3 no longer crashes on this as of the latest commit; however it does time out, this may be a known issue due to the relatively long lengths of the strings involved.
