### ISSUE TITLE
Adding :named to one formula changes result of query from "unsat" to "unknown"

### ISSUE THREAD

**Issue by aterga** [Z3Prover/z3#2747]
Dear Z3 developers, 

I am experiencing unstable behavior of Z3 (version 4.8.7 - 64 bit) while adding a ```:named``` annotation to a single formula (the particular formula name seems irrelevant): 

```SMT2
; results in "unsat", as expected
(assert (__dummy__ 
    (|Seq#Length| (|Seq#Build| (|Seq#Empty| intType) fresh_Int_0 (int_2_U 42) -1))))
```

```SMT2
; results in "unknown"
(assert (! (__dummy__ 
    (|Seq#Length| (|Seq#Build| (|Seq#Empty| intType) fresh_Int_0 (int_2_U 42) -1))) 
:named Repro)) 
```

[a1-1_named.smt2.txt](https://github.com/Z3Prover/z3/files/3901579/a1-1_named.smt2.txt)
[a1-1_noname.smt2.txt](https://github.com/Z3Prover/z3/files/3901580/a1-1_noname.smt2.txt)

The example contains only 7 assertions, 6 of which are universally quantified; 2 user-defined, non-parametric sorts, and 8 used-defined functions over these. The only theory used is the linear integer theory. 

Might this be an instance of #930? Although in my case, providing the random seed via command line options (```smt.random_seed=4 sat.random_seed=4```) doesn't seem to affect the experiments. 

Also, #930 seems to be related to the undecidable array theory which is not used in my example. 

I would highly appreciate any insights on how to stabilize the behavior of Z3 in such cases. 

---
Best regards, 
Arshavir Ter-Gabrielyan
ETH Zurich
ter-gabrielyan@inf.ethz.ch

**Comment by NikolajBjorner** [comment]
The example uses a ton of options a few of which seem to be only useful for debugging and one of these is brittle for quantifiers. The smt.core.validate options is for debugging. It isn't something a user should play with. In this case, quantifier instantiation relies on the terms in the dummy assumption to find the right instances. When the dummy assumption isn't used directly in the core, but only indirectly through the terms useful for quantifier instantiation it isn't part of the core. Then the SMT solver is free to assign the atom "Repro" to false, and therefore the terms in dummy become irrelevant and not visible to quantifier instantiation.

When you set smt.core.validate to true, Z3 will create a separate solver with the original assertions and also assert the literals from the core. It seeks to validate that the core is unsat. 
In your case, the solver gives up and, as this is a debugging feature, it throws. 

        (:reason-unknown "Core could not be validated")

(Use (get-info :reason-unknown) to have this printed to the console)
I could surely suppress "unknown" from the validator producing "unknown" at the user level, but really I don't see why you should use this option in the first place.

I figured this out by turning the set-options on/off by commenting some out selectively.

**Comment by NikolajBjorner** [comment]
Added warning message in a257ec0cc112979c4b1189e6030accdd3e0cb55f

**Comment by aterga** [comment]
Thanks, Nikolaj, for explaining what's going on here! 

FYI: the original version of this example was taken from a very old version of [Dafny](https://github.com/dafny-lang/dafny) that I've been experimenting with.
