### ISSUE TITLE
Segmentation fault in z3str3

### ISSUE THREAD

**Issue by numairmansur** [Z3Prover/z3#2757]
Hi,
On the following 'sat' fromula, z3str3 throws a segmentation fault.
While z3 reports  "sat".

[strings5.smt2.zip](https://github.com/Z3Prover/z3/files/3906330/strings5.smt2.zip)

`Z3 version 4.8.7 - 64 bit`

On z3 version 4.8.6, z3str3 returns "sat" and does not throw a seg fault.

**Comment by mtrberzi** [comment]
I can't reproduce the segfault on the latest commit; Z3str3 times out but does not crash.

**Comment by numairmansur** [comment]
Yes, I get the segmentation fault with the pre built binaries of the latest release (4.8.7).
You are right that with the latest commit it is not throwing the seg fault but timing out.
Feel free to close if you think this is not an issue.
