### ISSUE TITLE
(continuously updating) List of benchmarks on which z3str3 return an incorrect result

### ISSUE THREAD

**Issue by numairmansur** [Z3Prover/z3#2758]
Hi,
For the following list of benchmarks, z3str3 return incorrect result:

All the files listed below are **sat**. 
z3str3 returns **unsat** for all of them.
CVC4 returns **sat** for all of them.
Z3 (without z3str3) retrurns **sat** for all of them. For some it hangs. Those files are marked with _(z3 hangs)_.

- [1.smt2](https://github.com/Z3Prover/z3/files/3906997/1.smt2.zip) 
- [2.smt2](https://github.com/Z3Prover/z3/files/3906998/2.smt2.zip)
- [3.smt2](https://github.com/Z3Prover/z3/files/3906999/3.smt2.zip)
- [4.smt2](https://github.com/Z3Prover/z3/files/3907000/4.smt2.zip)
- [5.smt2](https://github.com/Z3Prover/z3/files/3907001/5.smt2.zip)
- [6.smt2](https://github.com/Z3Prover/z3/files/3907002/6.smt2.zip)
- [7.smt2](https://github.com/Z3Prover/z3/files/3907003/7.smt2.zip)
- [8.smt2](https://github.com/Z3Prover/z3/files/3907242/8.smt2.zip)
- [9.smt2](https://github.com/Z3Prover/z3/files/3907243/9.smt2.zip)  _(z3 hangs)_
- [10.smt2](https://github.com/Z3Prover/z3/files/3907244/10.smt2.zip)
- [11.smt2](https://github.com/Z3Prover/z3/files/3907245/11.smt2.zip)  _(z3 hangs)_ 
- [12.smt2](https://github.com/Z3Prover/z3/files/3907246/12.smt2.zip)  _(z3 hangs)_
- [13.smt2](https://github.com/Z3Prover/z3/files/3907247/13.smt2.zip)
- [14.smt2](https://github.com/Z3Prover/z3/files/3907339/14.smt2.zip)
- [15.smt2](https://github.com/Z3Prover/z3/files/3907340/15.smt2.zip)
- [16.smt2](https://github.com/Z3Prover/z3/files/3907341/16.smt2.zip)  _(z3 hangs)_
- [17.smt2](https://github.com/Z3Prover/z3/files/3907342/17.smt2.zip)  _(z3 hangs)_
- [18.smt2](https://github.com/Z3Prover/z3/files/3907628/18.smt2.zip)
- [19.smt2](https://github.com/Z3Prover/z3/files/3907629/19.smt2.zip)
- [20.smt2](https://github.com/Z3Prover/z3/files/3907630/20.smt2.zip)
- [21.smt2](https://github.com/Z3Prover/z3/files/3907631/21.smt2.zip)
- [22.smt2](https://github.com/Z3Prover/z3/files/3907632/22.smt2.zip)
- [23.smt2](https://github.com/Z3Prover/z3/files/3907633/23.smt2.zip)
- [24.smt2](https://github.com/Z3Prover/z3/files/3907634/24.smt2.zip)
- [25.smt2](https://github.com/Z3Prover/z3/files/3907635/25.smt2.zip)
- [26.smt2](https://github.com/Z3Prover/z3/files/3907636/26.smt2.zip)
- [27.smt2](https://github.com/Z3Prover/z3/files/3907637/27.smt2.zip)
- [28.smt2](https://github.com/Z3Prover/z3/files/3907638/28.smt2.zip)
- [29.smt2](https://github.com/Z3Prover/z3/files/3907639/29.smt2.zip)
- [30.smt2](https://github.com/Z3Prover/z3/files/3907640/30.smt2.zip)
- [31.smt2](https://github.com/Z3Prover/z3/files/3907641/31.smt2.zip)
- [33.smt2](https://github.com/Z3Prover/z3/files/3907642/33.smt2.zip)
- [34.smt2](https://github.com/Z3Prover/z3/files/3907643/34.smt2.zip)
- [35.smt2](https://github.com/Z3Prover/z3/files/3907644/35.smt2.zip)
- [36.smt2](https://github.com/Z3Prover/z3/files/3907645/36.smt2.zip)
- [37.smt2](https://github.com/Z3Prover/z3/files/3907646/37.smt2.zip)
- [38.smt2](https://github.com/Z3Prover/z3/files/3907647/38.smt2.zip)
- [39.smt2](https://github.com/Z3Prover/z3/files/3907648/39.smt2.zip)
- [40.smt2](https://github.com/Z3Prover/z3/files/3907649/40.smt2.zip)
- [41.smt2](https://github.com/Z3Prover/z3/files/3907650/41.smt2.zip)
- [42.smt2](https://github.com/Z3Prover/z3/files/3907651/42.smt2.zip)
- [43.smt2](https://github.com/Z3Prover/z3/files/3907652/43.smt2.zip)

I am using the z3 nightly build
`Z3 version 4.8.8 - 64 bit`

**Comment by NikolajBjorner** [comment]
[strings4.smt2.zip](https://github.com/Z3Prover/z3/files/3906229/strings4.smt2.zip)

**Comment by NikolajBjorner** [comment]
[strings3.smt2.zip](https://github.com/Z3Prover/z3/files/3906118/strings3.smt2.zip)

**Comment by NikolajBjorner** [comment]
[strings.smt2.zip](https://github.com/Z3Prover/z3/files/3905765/strings.smt2.zip)

**Comment by numairmansur** [comment]
Some more examples on the latest nightly build:

[44.smt2](https://github.com/Z3Prover/z3/files/3908593/44.smt2.zip)
[45.smt2](https://github.com/Z3Prover/z3/files/3908594/45.smt2.zip)
[46.smt2](https://github.com/Z3Prover/z3/files/3908595/46.smt2.zip)
[47.smt2](https://github.com/Z3Prover/z3/files/3908596/47.smt2.zip)
[48.smt2](https://github.com/Z3Prover/z3/files/3908597/48.smt2.zip)
[49.smt2](https://github.com/Z3Prover/z3/files/3908598/49.smt2.zip)
[50.smt2](https://github.com/Z3Prover/z3/files/3908599/50.smt2.zip)
[51.smt2](https://github.com/Z3Prover/z3/files/3908600/51.smt2.zip)
[52.smt2](https://github.com/Z3Prover/z3/files/3908601/52.smt2.zip)
[53.smt2](https://github.com/Z3Prover/z3/files/3908602/53.smt2.zip)
[54.smt2](https://github.com/Z3Prover/z3/files/3908603/54.smt2.zip)
[55.smt2](https://github.com/Z3Prover/z3/files/3908604/55.smt2.zip)
[56.smt2](https://github.com/Z3Prover/z3/files/3908605/56.smt2.zip)
[57.smt2](https://github.com/Z3Prover/z3/files/3908606/57.smt2.zip)
[58.smt2](https://github.com/Z3Prover/z3/files/3908607/58.smt2.zip)
[59.smt2](https://github.com/Z3Prover/z3/files/3908608/59.smt2.zip)
[60.smt2](https://github.com/Z3Prover/z3/files/3908609/60.smt2.zip)
[61.smt2](https://github.com/Z3Prover/z3/files/3908610/61.smt2.zip)
[62.smt2](https://github.com/Z3Prover/z3/files/3908611/62.smt2.zip)
[63.smt2](https://github.com/Z3Prover/z3/files/3908612/63.smt2.zip)

**Comment by mtrberzi** [comment]
Taking a look at these cases. Some are now resolved (z3str3 returns sat), others are actually segfaults and a few are timing out. Is there a way we would prefer to track progress on these (maybe editing the list in the comment)?

**Comment by numairmansur** [comment]
I can rearrange them.
What timeout are you using ?

**Comment by mtrberzi** [comment]
20 seconds. I'll post the full list tomorrow (I will need to update the segfaults list as well as I tested those on the latest build).

**Comment by mtrberzi** [comment]
Actually, what timeout did you use? I could re-test the "timeout" cases if you used a longer interval.

**Comment by numairmansur** [comment]
The timeout I used was 120 seconds

**Comment by mtrberzi** [comment]
I re-ran the timeout cases for 120 seconds. Here are the latest results for commit `0b486d26daea05f918643a9d277f12027f0bc2f6` (release build):

Cases which are still UNSAT:
- 28
- 58
- 62

Cases which timeout:

- 2
- 17
- 18
- 23
- 25
- 26
- 27
- 29
- 39
- 41
- 42
- 43
- 44
- 55
- 63
- strings3

Cases which segfault:

- 9
- 10
- 47
- 57

And all 42 other cases return SAT.

**Comment by numairmansur** [comment]
@mtrberzi  Here are some more examples :
[15.smt2](https://github.com/Z3Prover/z3/files/4089958/15.smt2.zip)
[13.smt2](https://github.com/Z3Prover/z3/files/4089959/13.smt2.zip)
[12.smt2](https://github.com/Z3Prover/z3/files/4089960/12.smt2.zip)
[11.smt2](https://github.com/Z3Prover/z3/files/4089961/11.smt2.zip)
[10.smt2](https://github.com/Z3Prover/z3/files/4089962/10.smt2.zip)
[9.smt2](https://github.com/Z3Prover/z3/files/4089963/9.smt2.zip)
[8.smt2](https://github.com/Z3Prover/z3/files/4089964/8.smt2.zip)
[7.smt2](https://github.com/Z3Prover/z3/files/4089965/7.smt2.zip)
[6.smt2](https://github.com/Z3Prover/z3/files/4089966/6.smt2.zip)
[3.smt2](https://github.com/Z3Prover/z3/files/4089967/3.smt2.zip)
[2.smt2](https://github.com/Z3Prover/z3/files/4089968/2.smt2.zip)
[1.smt2](https://github.com/Z3Prover/z3/files/4089969/1.smt2.zip)

All the formulas at each level in the assertion stack are satisfiable. But z3str3 gives unsat at some level. For example for the file 1.smt2, z3str3 gives:
sat
sat
unsat

while z3-seq gives:
sat
sat
sat
 
OS:
NAME="Ubuntu"
VERSION="16.04.5 LTS (Xenial Xerus)"

$ git log -1
commit 321bad2c84c9bb0c58f44d5797bdf993b47b09d4
Author: Christoph M. Wintersteiger <cwinter@microsoft.com>
Date:   Mon Jan 20 17:06:35 2020 +0000
    Fix for implicit consts in FPA models. Fixes #2865.

**Comment by mtrberzi** [comment]
OK, thanks for the new cases. Is that commit the one you tested on?

I'm actually in the middle of replacing the length and value testing algorithm with an improved procedure that should deal with many of these correctness issues. I tracked down several wrong-answer cases to bad behaviour in the legacy algorithm and the best way is to implement this new technique (which should also be more efficient in many cases). I'll let you know when it's ready to be tested, I would really appreciate the cross-check from your tool.

**Comment by numairmansur** [comment]
That sounds good. Just let me know when it's ready :)

**Comment by mtrberzi** [comment]
OK, all of these cases now return SAT, or time out. I'll close this issue for now, and look at addressing the slow cases after some of the bigger old issues are resolved. Please do keep reporting any wrong answer cases or crashes you find, I appreciate it.
