### ISSUE TITLE
(continuously updating) List of benchmarks on which z3str3 throws a segmentation fault

### ISSUE THREAD

**Issue by numairmansur** [Z3Prover/z3#2759]
Hi,
For the following list of **sat** benchmarks, z3str3 throws a segmentation fault:
z3(without z3str3) hangs on most but returns **sat** on some.

- [seg_fault1.smt2](https://github.com/Z3Prover/z3/files/3907274/seg_fault1.smt2.zip) _(z3 hangs)_
- [seg_fault2.smt2](https://github.com/Z3Prover/z3/files/3907275/seg_fault2.smt2.zip) _(z3 hangs)_
- [seg_fault3.smt2](https://github.com/Z3Prover/z3/files/3907276/seg_fault3.smt2.zip) _(z3 returns **sat**)_
- [seg_fault4.smt2](https://github.com/Z3Prover/z3/files/3907277/seg_fault4.smt2.zip) _(z3 hangs)_
- [seg_fault5.smt2](https://github.com/Z3Prover/z3/files/3907288/seg_fault5.smt2.zip) _(z3 returns **sat**)_
- [seg_fault6.smt2](https://github.com/Z3Prover/z3/files/3907289/seg_fault6.smt2.zip) _(z3 hangs)_
- [seg_fault7.smt2](https://github.com/Z3Prover/z3/files/3907311/seg_fault7.smt2.zip) _(z3 returns **sat**)_
- [seg_fault8.smt2](https://github.com/Z3Prover/z3/files/3907312/seg_fault8.smt2.zip) _(z3 hangs)_
- [seg_fault9.smt2](https://github.com/Z3Prover/z3/files/3907455/seg_fault9.smt2.zip) _(z3 returns **sat**)_
- [seg_fault10.smt2](https://github.com/Z3Prover/z3/files/3907456/seg_fault10.smt2.zip) _(z3 returns **sat**)_
- [seg_fault11.smt2](https://github.com/Z3Prover/z3/files/3907457/seg_fault11.smt2.zip) _(z3 returns **sat**)_
- [seg_fault12.smt2](https://github.com/Z3Prover/z3/files/3907458/seg_fault12.smt2.zip) _(z3 returns **sat**)_

I am using the z3 nightly build
`Z3 version 4.8.8 - 64 bit`

**Comment by NikolajBjorner** [comment]
Thanks for using the format of updating the issue. There are currently very
many unfixed bugs in z3str3. Separate issues on these bugs have been overloading the issue list.

**Comment by mtrberzi** [comment]
For this set the following cases time out (120 seconds):
- seg_fault2
- seg_fault7

seg_fault11 still crashes

The remaining 9 cases all complete successfully.

**Comment by mtrberzi** [comment]
seg_fault11 no longer crashes, but times out. All other cases in this issue successfully return SAT with Z3str3. I'm closing this issue since the reported crashes have been fixed and I'll consider looking at why seg_fault11 is slow.
