### ISSUE TITLE
assertion violation ../src/opt/opt_context.cpp, line: 1667

### ISSUE THREAD

**Issue by wintered** [Z3Prover/z3#2760]
Hi, 

on the following formula, z3 throws an assertion violation:

```
(declare-fun a () Real)
(declare-fun b () Real)
(declare-fun c () Real)
(assert (< 0 b a c))
(minimize a)
(minimize b)
(minimize c)
```
```
ASSERTION VIOLATION
File: ../src/opt/opt_context.cpp
Line: 1667
r1 == r2
(C)ontinue, (A)bort, (S)top, (T)hrow exception, Invoke (G)DB
```
OS: Ubuntu 18.04
Revision: cdf3c48

**Comment by NikolajBjorner** [comment]
This is not a bug: the debug assert is used to catch unsound behavior when minima or maxima are uniquely defined. When you have strict lower bounds the optima are not well defined. Normal use of Z3 is to either produce constraints where optima are unique or don't use the debug mode.
