### ISSUE TITLE
Non-termination when use Z3-opt(OCaml version) to solve a sample SMT2 file

### ISSUE THREAD

**Issue by gingeredder** [Z3Prover/z3#277]
In my project, I need to solve such a planning problem using Z3-opt(Ocaml version). The sample file(test.smt2) is as follows:

(declare-fun tmp0 () Int)
(declare-fun c1 () Int)
(declare-fun p0 () Int)
(declare-fun tmp1 () Int)
(declare-fun c0 () Int)
(assert (let ((a!1 (and 
                (= (to_real (- p0 c0)) 0.0)
                (= (to_real tmp1) 1.0)))
      (a!2 (not (= (to_real (- p0 c0)) 0.0)))
      (a!4 (and (= (to_real (- p0 c1)) 0.0)
                (= (to_real tmp0) 1.0)
                ))
      (a!5 (not (= (to_real (- p0 c1)) 0.0))))
(let ((a!3 (or a!1 (and a!2 (= (to_real tmp1) 0.0))))
      (a!6 (or a!4 (and a!5 (= (to_real tmp0) 0.0)))))
  (and a!3
       (= (to_real c1) (+ (to_real c0) 1.0))
       a!6))))
(maximize c1)
(check-sat)

When I run the Z3 on it using the command "./z3 test.smt2" in my computer, It seems that it doesn't return any result. It  just hangs on and doesn't terminate for at least 5 mins. The Z3 source file is downloaded from "https://github.com/Z3Prover/z3". Also I have tried the binary file of Z3. The Z3 binary file is download from "https://github.com/Z3Prover/bin/blob/master/nightly/z3-4.4.2.89fb5a44fba8-x64-ubuntu-14.04.zip". 
What's interesting, when I give  the SMT-input to the rise4fun in "http://rise4fun.com/Z3Opt", it could give the correct result quickly. 
Could you tell me how to solve this problem? Thank you!

**Comment by gingeredder** [comment]
I have tried to delete some constraints from above sample file, then it could be solved. But that above constraint could be solved I think. Thanks.

**Comment by gingeredder** [comment]
Could you tell how to get the Z3-source file could act as "http://rise4fun.com/Z3Opt" ?
Because I think the version of "http://rise4fun.com/Z3Opt" is not the same as the homepage "https://github.com/Z3Prover/bin/blob/master/nightly/".

**Comment by wintersteiger** [comment]
That's correct, the version on rise4fun is out of date and should be removed altogether. All optimization features have since been built into Z3 proper, so the separate webpage is not needed at all anymore. 

Further, the version of Z3 on rise4fun is also out of date (4.4.0). We don't have direct access to that web-server, so it may take some time until a new version gets pushed.

**Comment by NikolajBjorner** [comment]
rise4fun/z3opt uses an old binary, different from the binary used on rise4fun/z3.
The non-termination is possibly a regression. You can remove the coercions "to_real" and just use integers in your problem. This makes it much easier for Z3 (and makes the current code converge).
The code corresponding to rise4fun/z3opt is on GitHub under the now deprecated "opt" branch.

**Comment by NikolajBjorner** [comment]
The update above makes this particular example go through.

**Comment by gingeredder** [comment]
Thanks for your work and reply.
