### ISSUE TITLE
How to obtain a pure Tseitin-CNF transformation without modifying the number of solutions of the formula?

### ISSUE THREAD

**Issue by danieljmg** [Z3Prover/z3#2775]
Dear Nikolaj,
Z3 is a superb tool. Thank you for your work.

Currently I am referring to Z3py.

I am using the Tactics 'simplify', 'bit-blasting', 'tseitin-cnf' to obtain the 3CNF formular previouly declared as Bit-Vectors plus their formulas.

However, when checking the number of solutions (with a model counting approach), more than often is not consistent, increasing them.

I think it is due to some simplifications/optimizations during the process, that creates artificial solutions (I have some trivial examples in case of).

Is there anyway I can obtain the 3CNF without modifying the number of solutions? For example, deactivating the simplification/optimisation functionality making use of some parameters?

Any help would be appreciated.

Best regards,

**Comment by NikolajBjorner** [comment]
The simplify tactic is equivalence preserving, so it does not change the number of models.
On the other hand, no such guarantees are provided for bit-blasting and especially not 
tseitin-cnf. They were not implemented with model count preservation in mind. 
I wouldn't be able to tell you where it breaks model counts, but as no such thing is enforced by design it could be a matter of chasing several details. 
For example, pure literal elimination and other transformations could happen in different places and also does not preserve models.

**Comment by danieljmg** [comment]
Thank you Nikolaj, in case I want to dig deep in it, do you have any suggestion in where to start to look at? 
Best regards,

**Comment by NikolajBjorner** [comment]
1. Run z3 in verbose mode -v:10 (verbose=10) to get a birds eye.
2. Use a build with debug tracing enabled.
3. Find the files where the exercised tactics are implemented
4. Enable tracing on the tags defined in those files, especially the tags that have to do with printing the goal after a transformation.
5. For a non-count preserving transformation, dig further into the steps that perform the steps of interest.

**Comment by danieljmg** [comment]
Hello Nikolaj and thank you once again,
I am trying to set-off several parameters from the tseitin_cnf_tactic class (or from tactic in general). But the furthest I have gotten is to retrieve the list of params (i.e., "tactic.param_descrs()"). Any other attempt has been unsuccessful. Could you kindly provide me a hint?
Regards.

**Comment by danieljmg** [comment]
> 
> 
>     1. Run z3 in verbose mode -v:10 (verbose=10) to get a birds eye.
> 
>     2. Use a build with debug tracing enabled.
> 
>     3. Find the files where the exercised tactics are implemented
> 
>     4. Enable tracing on the tags defined in those files, especially the tags that have to do with printing the goal after a transformation.
> 
>     5. For a non-count preserving transformation, dig further into the steps that perform the steps of interest.

I have succesfully built it with --debug --trace --python -x options.
However, set_option(trace = True) results in "OSError: exception: access violation reading".

I have noticed as well "enable_trace(msg)", **but I have no idea of the specific tag names or how to locate them in the code**. I am interested in checking/edit the Tseitin_cnf transformation, as Bit-Blasting keeps model count (for the record).

In the issue "#2038" there are a few examples, but I still get empty trace.log file.

Thank you,
