### ISSUE TITLE
Z3 strange NaN behaviour

### ISSUE THREAD

**Issue by wanderseeme** [Z3Prover/z3#278]
Just a quick think and found this bug (in my eyes):
```
(declare-const a (_ FloatingPoint 8 24))
(assert (not (distinct a a)))
(assert (= a (_ NaN 8 24)))
(check-sat)
(get-model)
```
The result is (which should not be like this):
```
sat
(model 
  (define-fun a () (_ FloatingPoint 8 24)
    (_ NaN 8 24))
)
```
Version info:
Z3 4.4.2 at commit ad58226f43a44c6795f92657699ad1c4742aa8d1

**Comment by cgcgbcbc** [comment]
More test:
```
(echo "(NaN=NaN)")
(push)
(assert (fp.eq (_ NaN 8 24) (_ NaN 8 24)))
(pop)
(check-sat)

(echo "!(NaN=NaN)")
(push)
(assert (not (fp.eq (_ NaN 8 24) (_ NaN 8 24))))
(pop)
(check-sat)

(echo "(NaN!=NaN)")
(push)
(assert (distinct (_ NaN 8 24) (_ NaN 8 24)))
(pop)
(check-sat)

(echo "(!NaN!=NaN)")
(push)
(assert (not (distinct (_ NaN 8 24) (_ NaN 8 24))))
(pop)
(check-sat)
```
got result:
```
(NaN=NaN)
sat
!(NaN=NaN)
sat
(NaN!=NaN)
sat
(!NaN!=NaN)
sat
```

**Comment by wintersteiger** [comment]
All these examples look fine to me. 

For `(assert (not (distinct a a))) ` note that "distinct" means `(not (= ...))` and not `(not (fp.eq ...))`. So, `(not (distinct a a))` means `(= a a)`, which is indeed satisfiable, even if we substitute the (unique) SMT NaN. 

For all other examples, note the location of all `(pop)` commands: they pop the constraint that was just added, so all `(check-sat)` commands check an empty set of assertions, which is indeed satisfiable. If we move the pops one line down, the results are respecively unsat, sat, unsat, sat.

**Comment by cgcgbcbc** [comment]
aha, sorry for my foolish examples

**Comment by wanderseeme** [comment]
Thanks for your response! Seems I finally understand the difference between `=` and `fp.eq` for a FloatingPoint! :-)

**Comment by wintersteiger** [comment]
Indeed, those two need to be separated! 

The normal `=` means "structural equality", i.e., the two things have the same (e.g., bit-vector) representations, but they could be non-equal floating point-numbers. This is the case for NaN, i.e., we have (= NaN NaN) but not (fp.eq NaN NaN). 

Another important thing to remember is that in SMT there is only one NaN, while in real implementations there may be many, i.e., 

    (not (= (_ NaN 8 24) (_ NaN 8 24)))

is unsatisfiable, while in real programs there may be two NaNs that have different (bit-vector) representations.

**Comment by wanderseeme** [comment]
Yeah that's exactly what I'm going to say, and thank you again for the reminding :-D
