### ISSUE TITLE
Solver state changes on return (due to Python GC ?)

### ISSUE THREAD

**Issue by bohlender** [Z3Prover/z3#2784]
Working with the lastest release (v4.8.7) via the Python bindings I experience changes to the state of a solver object when returning from a call on both Windows and Linux. The following is a reduced example to illustrate the issue:
```python
from z3 import *

def is_and(gate):
    return And(Not(gate(False, False)), Not(gate(False, True)), Not(gate(True, False)), gate(True, True))

def gen_goal():
    constraints = [is_and(gate) for gate in f]
    quantified = ForAll(Bools("x0 x1"), And(constraints))
    s.add(quantified)
    print("At call exit:\n=============\n{}".format(s.to_smt2()))

s = Solver()
f = [Function("f{:d}".format(i), [BoolSort()] * 3) for i in range(2)]
gen_goal()
print("After call:\n===========\n{}".format(s.to_smt2()))
```
Printing the SMTLIB representation prior to the return of `gen_goal` everything looks as expected, but printing it right after the call yields a slightly different representation:
![diff](https://user-images.githubusercontent.com/1607520/70128856-efe97900-167d-11ea-8ee9-900760e66a0a.PNG)
In this reduced example the difference is abysmal (and the formulas happen to be semantically equivalent) but there should be no difference at all. In my original code the difference amounts to the solver instance turning from `sat` within the call to `unknown` right after it -- and we're talking about a decidable fragment.

Unless I'm overlooking something, this seems to be a garbage collection issue. Inlining `gen_goal` yields consistent representations. I know that there have been issues with PyPy in the past but I'm using the regular Python v3.8 here. Can you confirm/reproduce this issue?

**Comment by NikolajBjorner** [comment]
For the example, it is just the pretty printer that ends up making different decisions on how it lays out the expression. 
In general, the solver state should return simplified assertions after a check-sat. This is intended so that one can run a solver with some timeout or other resource bound and then post-process the result, such as cubing. I can't say why your case produces unknown, other than it doesn't seem to be intended behavior. (get-info :reason-unknown), or s.reason_unknown(), from python, could shed light on what is going on.

**Comment by bohlender** [comment]
Thanks for the quick reply!
> In general, the solver state should return simplified assertions after a check-sat. This is intended so that one can run a solver with some timeout or other resource bound and then post-process the result, such as cubing.

This is very reasonable and I understand this, however, I do **invoke `check()` only once**. What I cannot explain is why it matters whether I invoke `check_sat` from within `gen_goal` or right after it returns. It seems like returning from `gen_goal` affects the solver object somehow.

To stress the issue I (unfortunately) had to provide a bigger excerpt. Running the following script with different values for `CHECK_BEFORE_RET` will either check satisfiability within `gen_goal` or right afterwards:
```python
import time
from itertools import *
from z3 import *

s = Solver() # Made global to illustrate the weirdness
CHECK_BEFORE_RET = True

def main():
    print("Using {}".format(z3.get_full_version()))
    sum = lambda inputs: Xor(Xor(inputs[0], inputs[1]), inputs[2])
    carry = lambda inputs: Or(And(inputs[0], inputs[1]), And(Xor(inputs[0], inputs[1]), inputs[2]))
    outputs = [sum, carry]
    gen_goal(3, outputs, 9)
    if not CHECK_BEFORE_RET:
        check_sat() # Checking here yields UNKNOWN (30s, 1500MB RAM)

def gen_goal(num_inputs, outputs, num_inner_gates):
    x = [Bool("x{:d}".format(gate_idx)) for gate_idx in range(num_inputs + num_inner_gates)]
    f = [Function("f{:d}".format(gate_idx), [BoolSort()]*3) for gate_idx in range(num_inputs, len(x))]

    goal = Goal()
    constraints = chain(output_constraints(num_inputs, x, outputs), gate_constraints(num_inputs, x, f), f_constraints(f))
    simplified = And([simplify(assrt) for assrt in constraints])
    quantified = ForAll(x[:num_inputs], Exists(x[num_inputs:], simplified) if num_inner_gates > 0 else simplified)
    goal.add(quantified)
    s.add(quantified)
    if CHECK_BEFORE_RET:
        check_sat() # Checking here yields SAT (17s, 10MB RAM)

def check_sat():
    start = time.perf_counter()
    status = s.check()
    print("{} ({:f}s)".format(status, time.perf_counter() - start))
    if status == unknown:
        print(s.reason_unknown())
    print(s.statistics())

def output_constraints(num_inputs, x, outputs):
    asserts = []
    for output_idx in range(len(outputs)):
        conn_vars = []
        for gate_idx in range(len(x)):
            conn_var = Bool("g_{:d}_{:d}".format(output_idx, gate_idx))
            conn_vars.append(conn_var)
            asserts.append(Implies(conn_var, outputs[output_idx](x[:num_inputs]) == x[gate_idx]))
        asserts.append(Or(conn_vars))
    return asserts

def gate_constraints(num_inputs, x, f):
    asserts = []
    for gate_idx in range(num_inputs, len(x)):
        conn_vars = []
        for in1_idx, in2_idx in combinations(range(gate_idx), 2):
            conn_var = Bool("c_{:d}_{:d}_{:d}".format(gate_idx, in1_idx, in2_idx))
            conn_vars.append(conn_var)
            asserts.append(Implies(conn_var, x[gate_idx] == f[gate_idx - num_inputs](x[in1_idx], x[in2_idx])))
        asserts.append(Or(conn_vars))
    return asserts

def f_constraints(f):
    asserts = []
    is_and = lambda fate: And(Not(gate(False, False)), Not(gate(False, True)), Not(gate(True, False)), gate(True, True))
    is_or = lambda gate: And(Not(gate(False, False)), gate(False, True), gate(True, False), gate(True, True))
    is_not = lambda gate: And(gate(False, False), gate(False, True) != gate(True, False), Not(gate(True, True)))

    for gate in f:
        gate_filters = [is_and(gate), is_or(gate), is_not(gate)]
        asserts.append(Or(gate_filters))
    if len(f) > 0:
        asserts.append(AtMost([is_not(gate) for gate in f] + [2]))
    return asserts

if __name__ == '__main__':
    main()

```

Running with `CHECK_BEFORE_RET = True` will work as expected and output:
```
Using Z3 4.8.7.0
sat (16.439051s)
(:added-eqs            4468270
 :binary-propagations  290238
 :conflicts            68807
 :decisions            189806
 :del-clause           402078
 :dyn-ack              24
 :final-checks         2
 :max-generation       2
 :max-memory           10.04
 :memory               5.71
 :minimized-lits       1456926
 :mk-bool-var          208776
 :mk-clause            443328
 :num-allocs           62657884
 :num-checks           1
 :pb-conflicts         268
 :pb-predicates        10
 :pb-propagations      70293
 :pb-resolves          268
 :propagations         20162932
 :quant-instantiations 43257
 :restarts             3
 :rlimit-count         42048173)
```

Running with `CHECK_BEFORE_RET = False` will behave differently though:
```
Using Z3 4.8.7.0
unknown (27.344311s)
out of memory
(:added-eqs            229976
 :binary-propagations  1575
 :conflicts            543
 :decisions            6387
 :del-clause           2886166
 :final-checks         1
 :max-generation       10
 :max-memory           1588.55
 :memory               613.58
 :minimized-lits       4900
 :mk-bool-var          5962460
 :mk-clause            12301610
 :num-allocs           64102893331.00
 :num-checks           1
 :pb-predicates        10
 :pb-propagations      175
 :propagations         765068
 :quant-instantiations 9071
 :restarts             2
 :rlimit-count         34437675)
```
> `s.reason_unknown()`, from python, could shed light on what is going on.

As shown above the solver runs out of memory.

I'm not sure how helpful this big example is with tracking down where the issue is, but do you agree that the impact of just invoking `check()` at a different location is very unexpected and hints at something being off?

**Comment by NikolajBjorner** [comment]
ok, i missunderstood the question. This seems gc related. 
Could you update script to make it runnable? Eg., "chain" -> ? "fate" -> "gate".
Another approach is to dump logs:
Approach 1: use Z3_open_log("z3.log") before s = Solver()
Approach 2: before s.check_sat() print s.sexpr() to a file.

**Comment by bohlender** [comment]
> ok, i missunderstood the question. This seems gc related.
> Could you update script to make it runnable? Eg., "chain" -> ? "fate" -> "gate".

I fixed the typo (`fate` to `gate`) but I'm not sure what you mean by making the script _runnable_. [`chain`](https://docs.python.org/3.8/library/itertools.html#itertools.chain) is not a typo but a standard function and (having Z3 installed) the script is runnable via `python3`:
[![asciicast](https://asciinema.org/a/zvAag2oQ3g2bPkShJ9RGDRUEn.svg)](https://asciinema.org/a/zvAag2oQ3g2bPkShJ9RGDRUEn)
I would gladly update the script to make it runnable, but I'm unsure why the current one does not qualify as _runnable_ for you.

However, toying around with your suggestions I learned the following:
- Invoking `s.sexpr()` immediately before `s.check()` yields identical S-expressions -- no matter whether `CHECK_BEFORE_RET` is `True` or `False`. Only the pretty printed `s.to_smt2()` string differs slightly (not semantically) as shown in my
- Replacing the chaining of iterables by a concatenation, i.e. using
`constraints = output_constraints(..) + gate_constraints(..) + f_constraints(f)`
instead of
`constraints = chain(output_constraints(..), gate_constraints(..), f_constraints(f))`,
is a _spurious_ fix to the issue (invocations do not deviate significantly). The weird discrepancies comes back for different arguments though, i.e. for `gen_goal(3, outputs, 10)`.

>  Approach 1: use Z3_open_log("z3.log") before s = Solver()

I've logged the runs with `s.check()` within and after `gen_goal` for both my introductory example and the bigger one. They differ slightly towards the end but I'm not sure how that helps:
[ex1_check_after_call.log](https://github.com/Z3Prover/z3/files/3926874/ex1_check_after_call.log)
[ex1_check_in_call.log](https://github.com/Z3Prover/z3/files/3926876/ex1_check_in_call.log)
[ex2_check_after_call.log](https://github.com/Z3Prover/z3/files/3926877/ex2_check_after_call.log)
[ex2_check_in_call.log](https://github.com/Z3Prover/z3/files/3926878/ex2_check_in_call.log)

**Comment by NikolajBjorner** [comment]
This worked for the repro, thanks.

The GC probably removes expressions from "constraints" after call return as their reference counts are decreased at this point. This creates different order of expression identifiers. 
The big difference seems to be the quantifier parttern that gets inferred. In the fast example, z3 infers the pattern 

       :pattern ((f3 x0 x1) (f3 x0 x2))))

In the slow version it infers

      :pattern ((f11 x1 x2) (f11 x0 x2))))

It is very likely to make a big difference in solving. For example, I find instances where f3 is applied directly to bound variables, but f11 is applied to nested terms (created from existential skolem functions). 

There is probably something to learn from pattern inference heuristics. If you have a way to infer a good pattern during generation time of the constraints it could help. The conditions for what makes a good pattern for your domain would require some investigation.

**Comment by bohlender** [comment]
> The GC probably removes expressions from "constraints" after call return as their reference counts are decreased at this point. This creates different order of expression identifiers.
> The big difference seems to be the quantifier parttern that gets inferred.

Thanks, this makes so much sense. With this in mind, the observed behaviour is not that unexpected and I can continue using the Python bindings without doubting the correctness of the solver state after returning from `gen_goal`.

> If you have a way to infer a good pattern during generation time of the constraints it could help. The conditions for what makes a good pattern for your domain would require some investigation.

Regarding the problem itself, I do actually reduce the characterisation to propositional logic later on. The resulting SAT instances turn out to be significantly simpler. However, for educational purposes (and blogging), I found it more reasonable to approach the characterisation from first-order logic but stumbled upon the discussed (to me unexpected) behaviour along the way.

Now that the observed behaviour turned out to be just a side effect of garbage collection -- which fortunately enough does not affect correctness -- I think the issue can be closed. Feel free to reopen it if you see need for it. Thanks again!
