### ISSUE TITLE
Z3 smt.arith.solver=1 incorrect answer on QF_UFLRA formula with = and distinct operators

### ISSUE THREAD

**Issue by muchang** [Z3Prover/z3#2787]
Hi,
For this formula,
```
(declare-fun x () Real)
(declare-fun y () Real)
(declare-fun f (Real) Real)
(declare-fun g (Real) Real)
(assert (= x (f x) y))
(assert (distinct (g x) (g y)))
(check-sat)
(get-model)
```
`Z3 smt.arith.solver=1` incorrectly reports `sat` and gives an incorrect model:
```
(model 
  (define-fun x () Real
    0.0)
  (define-fun y () Real
    0.0)
  (define-fun f ((x!0 Real)) Real
    0.0)
  (define-fun g ((x!0 Real)) Real
    (- 1.0))
)
```

OS: Ubuntu 18.04
Revision: e5ca451

**Comment by NikolajBjorner** [comment]
This is almost a "won't fix": the basic arithmetic solvers have no support for theory combinations and I don't want to add it. They are too specialized to be useful for general theories. 
I am therefore having this solver return unknown in the final check whenever there is something else than arithmetic/boolean op. 
Overall, most bugs in smt.arith.solver=1 haven't been too interesting, even some were the result of fixing some other bug report. Their relevance to use scenarios of Z3 that other users would care about is unclear to me.
