### ISSUE TITLE
link z3 exec against libz3 ?

### ISSUE THREAD

**Issue by jelmd** [Z3Prover/z3#279]
Just wondering, why the z3 executable gets not linked against libz3.so? AFAICS z3 uses exactly the same modules as the libz3.so + shell/*.o , which produces another 240+ MB monster. Any reason why?

**Comment by wintersteiger** [comment]
It's not necessary for z3.exe to be linked dynamically and it avoids potential problems for users, or in situations where multiple libz3.dll/.so/.dylib are in the path. On OSX, both objects are around 40MB, and on Windows they are around 20MB, both in debug mode. On which system do you get a 240MB file?

**Comment by jelmd** [comment]
Hmmm, well, the multiple libs "problem" is usually resolved via libname and/or LD_LIBRARY_PATH on *x systems, so not really a problem. IMHO z3 is just duped code, and thus we have the same problems as with static libs (incl. the resource/huge package thing). Also initially I assumed, that z3 is a "real world" example, how libz3 can be used ...

I build it on Solaris 11.3. More information can be found via http://iws.cs.uni-magdeburg.de/~elkner/tmp/z3/ - should provide all the tiny details ...

**Comment by wintersteiger** [comment]
No, it's not a "real world example", but the other examples in the examples folder are.

Yeah, Solaris is definitely not "supported" at this time. What's the default compiler on Solaris and was that in debug mode?

**Comment by jelmd** [comment]
OK.

On Solaris there is not really a "default" compiler. If GNU C/C++ compiler is installed, most "auto" stuff will pick it up before trying others like cc or CC, however, I prefer Sun/Oracle Studio compilers and thus try to use them first, and with debug info aka '-g' enabled, yes.

**Comment by delcypher** [comment]
I just took a look at this. 

The first problem I hit is that appears that some of the components of the ``z3`` executable call into code that's in ``libz3.so`` that is exported (due to ``-fvisiblity=hidden``) and so linking fails. After removing that flag I still had more link errors so I gave up.

**Comment by ohhmm** [comment]
@jelmd , but its not compilable in Solaris

**Comment by jelmd** [comment]
???

**Comment by ohhmm** [comment]
Solaris is not supported, right?

**Comment by NikolajBjorner** [comment]
I will not be able to do anything support-wise for Solaris. 
If you have updates to cmake scripts and OS dependent code you can add pull requests.
