### ISSUE TITLE
why could array have nagetive index?

### ISSUE THREAD

**Issue by tintinlam007** [Z3Prover/z3#2790]
(declare-const A (Array Int String ))
(declare-const B Int )
(declare-const C String)
(assert (= B -1))
(assert (= (select A B ) C))
(check-sat)
(get-model)

the model:
sat
(model
  (define-fun A () (Array Int String)
    ((as const (Array Int String)) ""))
  (define-fun C () String
    "")
  (define-fun B () Int
    (- 1))
)

why not z3 throw error？what does B = -1 mean?

**Comment by NikolajBjorner** [comment]
All functions in Z3, which is based on classical first-order logic, are total. 
Furthermore Z3 does not have a type of Natural numbers, only Integers. 
The "select" function is defined on all possible type correct inputs, including -1.
Z3 produces a model where A is an array that maps all integers to the empty string.
