### ISSUE TITLE
ASSERTION VIOLATION File: ../src/smt/smt_enode.h, Line: 217

### ISSUE THREAD

**Issue by wintered** [Z3Prover/z3#2797]
Hi, 

for the following formula Z3 gives an assertion violation.

```
(assert
 (exists ((?g Real))
  (forall ((?a Real))
   (forall ((?c Real))
    (forall ((?d Real))
     (forall ((?b Real))
      (or
       (not (= (* ?a ?b) 0))
       (<= (+ (/ (+ 94 ?b (* 20 ?d)) (* 41 ?c)) (* 3 ?g)) 0))))))))
(check-sat)
```

```
ASSERTION VIOLATION
File: ../src/smt/smt_enode.h
Line: 217
idx < get_num_args()
(C)ontinue, (A)bort, (S)top, (T)hrow exception, Invoke (G)DB
```
OS: Ubuntu 18.04
Revision: ec39d84

**Comment by NikolajBjorner** [comment]
as added bonus you and other fuzzers are invited to submit bug fixes to lower the overhead of fixing these corner cases. There are good bugs, but there are also corner cases that I don't know whether they benefit users. But you are welcome to submit fixes too.
