### ISSUE TITLE
the new API of Z3_parse_smtlib2_file

### ISSUE THREAD

**Issue by oferst** [Z3Prover/z3#2798]
That function now returns Z3_ast_vector rather than Z3_ast, which breaks our former code. 
How should we parse an smt file and turn it into an expr ? 
Our line used to be 
to_expr(get_ctx(), Z3_parse_smtlib2_file(get_ctx(), fileName.c_str(), 0, 0, 0, 0, 0, 0));

Ofer

**Comment by NikolajBjorner** [comment]
You can use take the conjunction of the elements using Z3_mk_and
