### ISSUE TITLE
OSX wheels missing from Pypi

### ISSUE THREAD

**Issue by mtreinish** [Z3Prover/z3#2800]
Precompiled wheels are built and uploaded for windows and linux but not osx. This requires users on osx to compile z3 as part of the installation process when using pip which is not ideal. It'd be good to also publish wheels for osx as part of the release process.

It looks like this issue was previously raised in https://github.com/Z3Prover/z3/issues/1038 and they were pointed to the hosted artifacts on the github release page. But this isn't really a solution for a multi-platform python package that wants to depend on z3. It basically means requiring any python user on osx to have a compiler installed and build z3 from source whenever installing.

**Comment by NikolajBjorner** [comment]
There was without doubt a good reason why MacOS wasn't supported for the pip packaging.
The pip package is created using Azure Pipelines, so the scripts for creating the packages are available for anybody to update (but I publish the packages at this point).

The scripts/nightly.yaml contains a rehearsal script and scripts/release.yml is a similar script that I invoke when updating Z3. It directly pushes the pip package to pypi. @rhelmot created these scripts and also created the original pip packages that used to be managed independently. I don't think there was ever a pip package. If you (or other MacOS expert users) have courage in your copious spare time to try out updates to these build scripts you are certainly invited to add a pull request with the result.  As some of the requirements for creating pypi packages are opaque to me, I can't promise to support this extension but would appreciate community help around this.

**Comment by rhelmot** [comment]
The real reason I never distributed wheels for macos back when the whole release process was manual is that I don't have access to a mac machine to test them on. The mac ecosystem is fragmented enough and has mysterious enough requirements to it that I couldn't put myself on the hook to be tagged into issues by Nikolaj when people have problems. `python setup.py bdist_wheel` should work on macos so far as I know, but I have no idea what's going to happen when those wheels are released into the wild.

**Comment by NikolajBjorner** [comment]
Could you try to install locally https://github.com/Z3Prover/z3/releases/download/Nightly/z3_solver-4.8.8.0-py2.py3-none-macosx_10_14_x86_64.whl?

**Comment by NikolajBjorner** [comment]
Did you have a change to check if the pypi binding works?

**Comment by mtreinish** [comment]
Yeah, it looks like it works. At least according to: https://github.com/Qiskit/qiskit-terra/pull/3648#issuecomment-569752802 (I don't actually own a mac otherwise I'd test it locally too)

**Comment by NikolajBjorner** [comment]
https://files.pythonhosted.org/packages/40/9f/6ba0bb38709cf16dc13e877ef6ea8a59147478e4f036a0d60475b7997b3d/z3_solver-4.8.8.0-py2.py3-none-macosx_10_14_x86_64.whl
