### ISSUE TITLE
make error: ModuleNotFoundError: No module named 'distutils.sysconfig'

### ISSUE THREAD

**Issue by Tephilla** [Z3Prover/z3#2801]
While compiling z3 , on executing make,  ModuleNotFoundError: No module named 'distutils.sysconfig' was observed. Logs are attached. 
System Specifications:
*Debian GNU/Linux 10 (buster)
*Python 3.7
*cmake version 3.13.4
*GNU Make 4.2.1

[makeErrorLog.txt](https://github.com/Z3Prover/z3/files/3961991/makeErrorLog.txt)

**Comment by NikolajBjorner** [comment]
https://lmgtfy.com/?q=distutils.sysconfig+not+found&pp=1

**Comment by NikolajBjorner** [comment]
In more detail: this would have to be because your python installation doesn't have a particular package. The typical way is to install python packages using pip. I don't have particular information about distutils.sysconfig, but I think the information should be somewhere on forums already.
