### ISSUE TITLE
Dealing with Quantifiers

### ISSUE THREAD

**Issue by xoro4me** [Z3Prover/z3#2804]
I am trying to run the code below which tries to find if there exists some value of t1 and t2 such that for all values of x1, x2, y1, y2 and z, the implication holds.

```
from z3 import *
s = SolverFor("LIA")
x1, y1, x2, y2, t1 , t2, z = Ints('x1 y1 x2 y2 t1 t2 z')
s.add(ForAll([x1,x2,y1,y2,z], Implies(True , Exists([t1,t2], Not(And ( (t1>=2), (t1<=7),(t2>=5),(t2<=9), (x1>=0), (x2>=0), (x1>=x2),(y1==x1+t1),(y2==x2+t2),(z>=0),(y1<=z),(z<=y2) )) ))))

print(s.check())
print(s.model())
```
which gives a result as below:
```

sat
[ ]
```

The solution is not providing any values for t1 and t2. There exists a valuation of t1==7 and t2==5 for which the implication holds. 

Can someone explain why it is happening? Shouldn't we get valuations of t1 and t2 as the solution of SAT?

**Comment by nunoplopes** [comment]
dup of https://github.com/Z3Prover/z3/issues/2807
