### ISSUE TITLE
Values of Existential Quantifiers in Z3

### ISSUE THREAD

**Issue by xoro4me** [Z3Prover/z3#2807]
Say, I write a simple code with quantifiers as below:

```
from z3 import *
s = SolverFor("LIA")
x1, y1 = Ints('x1 y1')
s.add(ForAll(x1, Implies(x1>=0, Exists(y1, (y1>x1)))))

```
print(s.check())
print(s.model())

The result is :

```
sat
[ ]
```

Shouldn't this output a value of y1 for which it is satisfiable?

**Comment by nunoplopes** [comment]
The model only includes variables that not explicitly quantified, ie, they have to be bound by the top-level exists quantifier.
