### ISSUE TITLE
Is there any way to prove complement?

### ISSUE THREAD

**Issue by tintinlam007** [Z3Prover/z3#2816]
I want to transfer a 32-bit integer to binary(complement), when given a complement, get the corresponding integer。Because positive integer and negetive integer has different way to transfer to complement, so the smt2 should be:

(declare-const A Int)
(define-fun PosInt2Bin0 ((B Int)) (_ BitVec 32) (ite (= (mod B 2) 1) #x00000001 #x00000000 ))
(define-fun PosInt2Bin1 ((B Int)) (_ BitVec 32) (ite (= (mod (div B 2) 2) 1) #x00000002 #x00000000))
(define-fun PosInt2Bin2 ((B Int)) (_ BitVec 32) (ite (= (mod (div B 4) 2) 1) #x00000004 #x00000000))
(define-fun PosInt2Bin3 ((B Int)) (_ BitVec 32) (ite (= (mod (div B 8) 2) 1) #x00000008 #x00000000))
(define-fun PosInt2Bin4 ((B Int)) (_ BitVec 32) (ite (= (mod (div B 16) 2) 1) #x00000010 #x00000000))
(define-fun PosInt2Bin5 ((B Int)) (_ BitVec 32) (ite (= (mod (div B 32) 2) 1) #x00000020 #x00000000))
(define-fun PosInt2Bin6 ((B Int)) (_ BitVec 32) (ite (= (mod (div B 64) 2) 1) #x00000040 #x00000000))
(define-fun PosInt2Bin7 ((B Int)) (_ BitVec 32) (ite (= (mod (div B 128) 2) 1) #x00000080 #x00000000))
(define-fun PosInt2Bin8 ((B Int)) (_ BitVec 32) (ite (= (mod (div B 256) 2) 1) #x00000100 #x00000000))
(define-fun PosInt2Bin9 ((B Int)) (_ BitVec 32) (ite (= (mod (div B 512) 2) 1) #x00000200 #x00000000))
(define-fun PosInt2Bin10 ((B Int)) (_ BitVec 32) (ite (= (mod (div B 1024) 2) 1) #x00000400 #x00000000))
(define-fun PosInt2Bin11 ((B Int)) (_ BitVec 32) (ite (= (mod (div B 2048) 2) 1) #x00000800 #x00000000))
(define-fun PosInt2Bin12 ((B Int)) (_ BitVec 32) (ite (= (mod (div B 4096) 2) 1) #x00001000 #x00000000))
(define-fun PosInt2Bin13 ((B Int)) (_ BitVec 32) (ite (= (mod (div B 8192) 2) 1) #x00002000 #x00000000))
(define-fun PosInt2Bin14 ((B Int)) (_ BitVec 32) (ite (= (mod (div B 16384) 2) 1) #x00004000 #x00000000))
(define-fun PosInt2Bin15 ((B Int)) (_ BitVec 32) (ite (= (mod (div B 32768) 2) 1) #x00008000 #x00000000))
(define-fun PosInt2Bin16 ((B Int)) (_ BitVec 32) (ite (= (mod (div B 65536) 2) 1) #x00010000 #x00000000))
(define-fun PosInt2Bin17 ((B Int)) (_ BitVec 32) (ite (= (mod (div B 131072) 2) 1) #x00020000 #x00000000))
(define-fun PosInt2Bin18 ((B Int)) (_ BitVec 32) (ite (= (mod (div B 262144) 2) 1) #x00040000 #x00000000))
(define-fun PosInt2Bin19 ((B Int)) (_ BitVec 32) (ite (= (mod (div B 524288) 2) 1) #x00080000 #x00000000))
(define-fun PosInt2Bin20 ((B Int)) (_ BitVec 32) (ite (= (mod (div B 1048576) 2) 1) #x00100000 #x00000000))
(define-fun PosInt2Bin21 ((B Int)) (_ BitVec 32) (ite (= (mod (div B 2097152) 2) 1) #x00200000 #x00000000))
(define-fun PosInt2Bin22 ((B Int)) (_ BitVec 32) (ite (= (mod (div B 4194304) 2) 1) #x00400000 #x00000000))
(define-fun PosInt2Bin23 ((B Int)) (_ BitVec 32) (ite (= (mod (div B 8388608) 2) 1) #x00800000 #x00000000))
(define-fun PosInt2Bin24 ((B Int)) (_ BitVec 32) (ite (= (mod (div B 16777216) 2) 1) #x01000000 #x00000000))
(define-fun PosInt2Bin25 ((B Int)) (_ BitVec 32) (ite (= (mod (div B 33554432) 2) 1) #x02000000 #x00000000))
(define-fun PosInt2Bin26 ((B Int)) (_ BitVec 32) (ite (= (mod (div B 67108864) 2) 1) #x04000000 #x00000000))
(define-fun PosInt2Bin27 ((B Int)) (_ BitVec 32) (ite (= (mod (div B 134217728) 2) 1) #x08000000 #x00000000))
(define-fun PosInt2Bin28 ((B Int)) (_ BitVec 32) (ite (= (mod (div B 268435456) 2) 1) #x10000000 #x00000000))
(define-fun PosInt2Bin29 ((B Int)) (_ BitVec 32) (ite (= (mod (div B 536870912) 2) 1) #x20000000 #x00000000))
(define-fun PosInt2Bin30 ((B Int)) (_ BitVec 32) (ite (= (mod (div B 1073741824) 2) 1) #x40000000 #x00000000))
(define-fun PosInt2Bin31 ((B Int)) (_ BitVec 32) (ite (= (mod (div B 2147483648) 2) 1) #x80000000 #x00000000))
(define-fun PosInt2Bin ((B Int)) (_ BitVec 32) (bvadd (PosInt2Bin0 B) (PosInt2Bin1 B) (PosInt2Bin2 B) (PosInt2Bin3 B) (PosInt2Bin4 B) (PosInt2Bin5 B) (PosInt2Bin6 B) (PosInt2Bin7 B) (PosInt2Bin8 B) (PosInt2Bin9 B) (PosInt2Bin10 B) (PosInt2Bin11 B) (PosInt2Bin12 B) (PosInt2Bin13 B) (PosInt2Bin14 B) (PosInt2Bin15 B) (PosInt2Bin16 B) (PosInt2Bin17 B) (PosInt2Bin18 B) (PosInt2Bin19 B) (PosInt2Bin20 B) (PosInt2Bin21 B) (PosInt2Bin22 B) (PosInt2Bin23 B) (PosInt2Bin24 B) (PosInt2Bin25 B) (PosInt2Bin26 B) (PosInt2Bin27 B) (PosInt2Bin28 B) (PosInt2Bin29 B) (PosInt2Bin30 B) (PosInt2Bin31 B)))
(define-fun NegInt2Bin ((B Int)) (_ BitVec 32) (bvadd (bvnot (PosInt2Bin (abs B))) #x00000001))
(define-fun Int2Bin ((B Int)) (_ BitVec 32) (ite (= B -2147483648) #x80000000 (ite (>= B 0) (PosInt2Bin B) (NegInt2Bin B))))
(assert (= (Int2Bin A) #xFFFFFFFF))
(check-sat)
(get-model)

The answer is A = -1, But z3 consumes a huge time to solve it. It seems that z3 just do an enumeration amoung integer.

Is there any other solution to this problem? Thank you!

**Comment by NikolajBjorner** [comment]
Preferrably do all your reasoning within bit-vectors.
There are some built-in functions for converting between bit-vectors and integers, but they are similarly inefficient for the same reasons.
While bit-vectors are not signed, there are signed operations, such as signed < and signed division. Thus, you can distinguish between signed and unsigned semantics at the bit-vector level.
There is no signed + or signed * because they produce the same bit-vectors whether they are treated as signed or unsigned.
