### ISSUE TITLE
Is it possible to define two dimensional array variable in Z3py

### ISSUE THREAD

**Issue by sg61189** [Z3Prover/z3#2817]
Hello,

I want to define a two-dimensional boolean array in Z3py so that I can access the array indices using other integer variables, e.g., A[x][3], where x is an integer variable whose value is decided by the SMT-solver in runtime.

If I define the two-dimensional array as follows: A = [ [ Bool("a_%s_%s" % (i, j)) for j in range(5) ] for i in range(5) ] then, I get "TypeError: object cannot be interpreted as an index" on adding the constraint like (A[x][3]==True).

I checked that for a z3 array defined as A = Array('A',IntSort(),IntSort()), I can access the array indices using other integer variable (e.g., A[x]). Now, I want the same for two-dimensional array.

Please help me in this regard. Thanks in advance.

**Comment by NikolajBjorner** [comment]
When you create 

      [ [ Bool("a_%s_%s" % (i, j)) for j in range(5) ] for i in range(5) ] 

it corresponds to a Python object, a nested sequence of sequences.
Z3 objects for arrays are not the same as Python sequences. 
You create nested Z3 arrays from Python as follows:

from z3 import *

```
A = Array('A', IntSort(), ArraySort(IntSort(), IntSort()))
x, y = Ints('x y')
print(A[x][y])
```

**Comment by sg61189** [comment]
Thank you so much.
