### ISSUE TITLE
Soundness bug in QF_FP

### ISSUE THREAD

**Issue by numairmansur** [Z3Prover/z3#2827]
Hi,
On the latest nightly build, z3 returns an unsound result.
The attached formula is satisfiable but z3 returns "unsat".

[qf_FP.smt2.zip](https://github.com/Z3Prover/z3/files/4001364/qf_FP.smt2.zip)

$ /z3-nightly/bin/z3 qf_FP.smt2
unsat

While CVC4 return "sat".

OS:
NAME="Ubuntu"
VERSION="16.04.5 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.5 LTS"
VERSION_ID="16.04"

**Comment by numairmansur** [comment]
This seems fixed in the latest release @NikolajBjorner

**Comment by wintersteiger** [comment]
This one is very flaky, it's likely that there still is a bug, but it's not triggered with random_seed=0 anymore. I suspect that one of the recent fixes to the BV theory may have changed the behaviour and possibly fixed it, but I haven't confirmed that yet.

**Comment by wintersteiger** [comment]
Closing as fixed (most likely after additional checks). Please file a new report if something similar comes up.
