### ISSUE TITLE
Soundness bug in QF_LIA

### ISSUE THREAD

**Issue by numairmansur** [Z3Prover/z3#2829]
Hi, 
On the latest nightly build, z3 gives wrong answer on the following file:

[qf_lia.smt2.zip](https://github.com/Z3Prover/z3/files/4001441/qf_lia.smt2.zip)

All the formulas at every level in the assertion stack are satisfiable.

$ /z3-nightly/bin/z3 qf_lia.smt2
sat
sat
sat
sat
unsat
sat
sat

CVC4 return:

sat
sat
sat
sat
sat
sat
sat

OS:
NAME="Ubuntu"
VERSION="16.04.5 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.5 LTS"
VERSION_ID="16.04"

**Comment by NikolajBjorner** [comment]
@levnach 
C:\z3\build>z3 qf_lia.smt2\qf_lia.smt2
sat
sat
sat
ASSERTION VIOLATION
File: ..\src\util\lp\lar_solver.cpp
Line: 370
ax_is_correct()

**Comment by levnach** [comment]
The issue does not reproduce anymore.

**Comment by NikolajBjorner** [comment]
can you backport the fix to master branch?

**Comment by levnach** [comment]
It does not repro.

**Comment by NikolajBjorner** [comment]
The assertion repros beautifully for me

**Comment by levnach** [comment]
It does not reproduce on Ubuntu, but it does reproduce on Windows...

**Comment by levnach** [comment]
fixed by removing a wrong assert statement
