### ISSUE TITLE
BitVec unexpectedly slow when finding counterexamples 

### ISSUE THREAD

**Issue by aep** [Z3Prover/z3#2833]
i'm using z3 for symbolic execution in SSA form in a compiler. All is working well, except when using it to provide counter examples. It is extremely slow. 

Here's a reduced example with annotations (the real prove is much larger) that takes 2.8 seconds on my core i5. I suspect this is because it is trying really hard to find a solution, when really all i wanted was prove that there is no solution. Or more precisely: prove that there is no counter example.

yices2 solves the same in 200ms, this is probably because it's less "complete"? 

is there a better way to do this than using negating the assertion and using check-sat == unsat as prove?

```smt
(declare-fun A  () (_ BitVec 64))
(declare-fun B  () (_ BitVec 64))
(declare-fun C  () (_ BitVec 64))
(declare-fun D  () (_ BitVec 64))
(declare-fun E  () (_ BitVec 64))

; we know A < B
(assert (bvult A B ))

; if  (C + A  > B - 1) { C =  B - 1 - A }
(assert (= D (ite

    (bvugt
        (bvadd C A)
        (bvsub B (_ bv1 64))
    )

    (bvsub
        (bvsub B (_ bv1 64))
        A
    )

    C
)))

; E = A + C
(assert (= E (bvadd A D)))

; all good here, we made no contradicting statements
(check-sat)

; FINALLY
; find all counter examples in which E < B is not true
(assert (not (bvult E B)))

; unsat = no counter examples
(check-sat)
```

**Comment by NikolajBjorner** [comment]
It is a bit faster if you use QF_BV for everything, but still takes the SAT solver 24K conflicts.
Your uses of functions that use an Int as argument is really just a way to create different variables.
Z3 doesn't figure out that they can be treated as variables, mainly because it has to be able to handle your constraints in an incremental way, so how can it predict that you will not use the functions with non-constant arguments. 

```
(set-logic QF_BV)
(declare-fun a0 () (_ BitVec 64))
(declare-fun a1 () (_ BitVec 64))
(declare-fun b0 () (_ BitVec 64))
(declare-fun c0 () (_ BitVec 64))
(declare-fun c1 () (_ BitVec 64))


; we know A < B
(assert (bvult a0 b0))

; expression C + A  > B - 1
(declare-fun S15_infix_expression () Bool)
(assert (=  S15_infix_expression (
    bvugt
        (bvadd c0 a0)
        (bvsub b0 (_ bv1 64))
)))

; expression B - 1 -A
(declare-fun S19_infix_expression () (_ BitVec 64));
(assert (=  S19_infix_expression  (bvsub  (bvsub b0 (_ bv1 64))    a0)))

; if  (C + A  > B - 1) { C =  B - 1 - A }
(assert (= c1 (ite ( and S15_infix_expression)  S19_infix_expression c0)))

; A = A + C
(assert (= a1 (bvadd a0 c1)))


; all good here, we made no contradicting statements
(check-sat)


; FINALLY
; find all counter examples in which return < t is not true
(assert (not (bvult a1 b0)))

; unsat = no counter examples
(check-sat)
```

**Comment by aep** [comment]
I did indeed rewrite the example to const variables too. good to know this has performance impact as well, thanks for the info.

what really helps QF_BV.  it's **significantly**  faster.
is there any documentation for what the drawbacks are of set-logic?

with QF_BV its twice as slow as boolector and yices2,
with QF_UFBV its ~5-8 times slower.

no idea what the difference between the two is, but i'll stick to QF_BV until i see problems.

**Comment by NikolajBjorner** [comment]
If you stay with QF_BV formulas then setting QF_BV logic is better than not setting it.
The dedicated QF_BV solver is much better.
There are still simple things that can be done to improve performance.
On your example, if I do the following two small changes:

1. Remove line https://github.com/Z3Prover/z3/blob/1fff7bb51da144635228ff114589efd50e3fcf92/src/sat/sat_solver/inc_sat_solver.cpp#L560
2. Change https://github.com/Z3Prover/z3/blob/1fff7bb51da144635228ff114589efd50e3fcf92/src/sat/sat_solver.cpp#L37 to set ENABLE_TERNARY to false

Perf is twice as fast. Trying out such options systematically on larger benchmarks would show whether there is an overall gain. Probably there is.

Nikolaj

**Comment by aep** [comment]
indeed with the test case i also get twice the speed.
unfortunately both your suggestions have negligible impact in real life.

the zz compiler self test suite contains about half a million lines of smt2
it has uninterpreted functions, so i need QF_UFBV (that might be the reason it has no impact?)

|change|time|
|----------|-----|
|original| 112.5s |
| QF_UFBV |   59.959 |
| remove mk_simplify_tactic | 59.588 |
| ENABLE_TERNARY false | 58.062 |


i attached one of the worst performing real cases
[::string::append_bytes.smt2.txt](https://github.com/Z3Prover/z3/files/4013234/string.append_bytes.smt2.txt)

**Comment by aep** [comment]
no longer using the C api, so repros are better now. are you interested in me continuing to provide slow cases?
