### ISSUE TITLE
Soundness bug in QF_UFLIA

### ISSUE THREAD

**Issue by numairmansur** [Z3Prover/z3#2835]
Hi, 
On the latest revision, z3 gives wrong answer on the following file:

[qf_uflia.smt2.zip](https://github.com/Z3Prover/z3/files/4012497/qf_uflia.smt2.zip)

$ z3 qf_uflia.smt2
sat
sat
unsat

CVC4 return:
sat
sat
sat

OS:
NAME="Ubuntu"
VERSION="16.04.5 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.5 LTS"
VERSION_ID="16.04"

$ git log -1
commit 1fff7bb51da144635228ff114589efd50e3fcf92
Author: Lev Nachmanson <levnach@hotmail.com>
Date:   Mon Dec 30 17:58:56 2019 -0800
    use u_map in lar_term    
    Signed-off-by: Lev Nachmanson <levnach@hotmail.com>

**Comment by NikolajBjorner** [comment]
C:\z3\build>z3 ufl\qf_uflia.smt2
sat
sat
ASSERTION VIOLATION
File: ..\src\util\lp\lar_solver.cpp
Line: 860
(m_settings.random_next() % 100) != 0 || m_status != lp_status::OPTIMAL || all_constraints_hold()

**Comment by NikolajBjorner** [comment]
@levnach

**Comment by levnach** [comment]
It seem fixed now.
