### ISSUE TITLE
any API like is_numeral for String

### ISSUE THREAD

**Issue by komalb007** [Z3Prover/z3#2837]
Hi,

I have a requirement where I need to know z3::expr type.

Expression created in following way :
`z3::expr stringExp= ctx.string_val( "mystring" );`

Now I need to know _stringExp_ is created by _string_val_ and not by _int_val_ or bool_const or int_const etc.
For example there is `expression.is_numeral()` to know expression is numeral similar way to know string.

Thanks,
Komal

**Comment by NikolajBjorner** [comment]
the function was missing from the C++ API.
