### ISSUE TITLE
Unable to validate Z3 floating point values using machine execution

### ISSUE THREAD

**Issue by andrewvaughanj** [Z3Prover/z3#2844]
Given some values found by Z3 (from its models), I have attempted to "cross-check" them using (what I believe to be) is exactly the same "logic", but implemented in C.

Here is an example of one kind of SMT instance:

```
(declare-fun bits2 () (_ FloatingPoint 8 24))
(declare-fun bits1 () (_ FloatingPoint 8 24))
(declare-fun FLOAT_TEMP_1 () (_ BitVec 32))
(declare-fun FLOAT_TEMP_2 () (_ BitVec 32))
(assert (= ((_ to_fp 8 24) roundTowardPositive FLOAT_TEMP_1) bits1))
(assert (= ((_ to_fp 8 24) roundTowardPositive FLOAT_TEMP_2) bits2))
(assert (= FLOAT_TEMP_1 (bvnot FLOAT_TEMP_2)))
(push)
(assert (= ((_ to_fp 8 24) roundTowardPositive -303136) bits1))
(assert (= ((_ to_fp 8 24) roundTowardPositive 303135) bits2))
(check-sat)
(get-model)
(pop)
(push)
(assert (= ((_ to_fp 8 24) roundTowardPositive 1067188352) bits1))
(assert (= ((_ to_fp 8 24) roundTowardPositive -1067188288) bits2))
(check-sat)
(get-model)
(pop)
```

What's important here is that Z3 considers:

* `-303136` and `303135`
* ` 1067188352` and `-1067188288`

to be pairs of "good" inputs (that is, they are both SAT). I should say: I found these values by playing with Z3 and its random seed; I have no interest in these particular pairs of values.

Here is a simple example of a cross-checker that attempts to check the values generated by Z3:

```
#include <stdio.h>
#define _GNU_SOURCE
#include <fenv.h>

void test(float bits1, float bits2)
{
  int FLOAT_TEMP_1;
  int FLOAT_TEMP_2;
  FLOAT_TEMP_1 = (int)bits1;
  FLOAT_TEMP_2 = (int)bits2;

  if (FLOAT_TEMP_1 == ~FLOAT_TEMP_2)
  {
    printf("true\n");
  }
  else
  {
    printf("false\n");
  }
}

int main(void)
{
  fesetround(FE_UPWARD);

  // correct values
  test(-303136, 303135);

  // incorrect value
  test(1067188352, -1067188288);
}

// EOF
```

Interestingly, for the first set of values, the cross-checker reports "true", while for the second it reports "false".

Given that Z3 was trying to ensure that `FLOAT_TEMP_1 == ~FLOAT_TEMP_2` was indeed true, I had expected both values to print "true".

**My issue**: is this a bug in Z3 or does my "cross-checker" not actually implement the same "logic" as what's in the SMT instance?

The only thing that makes me wonder if something is wrong with my approach is that you cannot convert a float to a BV using SMT, only a BV into a float.

That is, the SMT2 does this:

```
(assert (= ((_ to_fp 8 24) roundTowardPositive FLOAT_TEMP_1) bits1))
```

while the C does this:

```
FLOAT_TEMP_1 = (int)bits1;
```

The subtle difference here is that the SMT2 is rounding an int to a float, while the C is rounding a float to an int -- maybe this means that my rounding modes are the wrong way around? However, changing the cross-checker to use `FE_DOWNWARD` doesn't help!

Tested with:

```
~/working/z3/build/z3 -version
Z3 version 4.8.8 - 64 bit
```

```
git rev-parse --short HEAD
5555421
```

**Comment by andrewvaughanj** [comment]
I think the conversion from floats to ints is wrong, and it should be using something akin to `fpSignedToFP`.

**Comment by wintersteiger** [comment]
Reproducing those conversions in C is quite tricky! Also check your compiler flags to strictly produce IEEE compliant code; the default for most compilers is not strict. Casts like `(int)bits1` do not necessarily call the right conversion functions - look for intrinsics that are clearly documented. 

The reason for the missing float -> BV conversion is that NaN has multiple representations (in SMT and in reality). Z3 has `to_ieee_bv` which fixes it to the "normal" one, but that's non-standard and you have to know what you're doing to use it correctly.

**Comment by andrewvaughanj** [comment]
Hi @wintersteiger!

Thanks for reply (even to the closed case!).

I had a poke around, and it seems that a cast like `(int)bits1` should (really) be truncating the value. Would you agree that implementing something like this in SMTLIB2 would be something like:

```
(assert (= ((_ fp.to_sbv 32) roundTowardNegative bits1) FLOAT_TEMP_1))
```

That is, the assignment "rounds down" the value to the near whole number?

Cheers,

Andrew

**Comment by wintersteiger** [comment]
I think `roundTowardZero` would get you closer, but I think technically, that cast is undefined behaviour, at least when the float is NaN/+-Inf. So no, an arbitrary compiler in the wild with default compiler flags will probably show some difference in behaviour over the whole range.

See, for instance, [Convert double to int?](https://stackoverflow.com/questions/18587452/convert-double-to-int) and [C convert floating point to int](https://stackoverflow.com/questions/24723180/c-convert-floating-point-to-int), and I'm sure there are lots similar questions elsewhere. You can also inspect the assembly your compiler generates and check whether it uses the FIST/FISTP/FISTTP instructions or some custom "fast" code (there are lots of different ones for various compilers).
