### ISSUE TITLE
Symbolic String Split

### ISSUE THREAD

**Issue by bdrodes** [Z3Prover/z3#2848]
Given a symbolic z3 string, is there any easy way to symbolically split it into substrings, with a concrete and/or symbolic delimiter? 

For example, consider modeling and reasoning over the python string `split()` method in z3. I would like to have a z3 expression to capture this kind of constraint:
```
mystring.split(",")[0] != 'bad_string'
```
The split index, delimiter, and use of the referenced token may vary in my use case, so while I'm personally interested how it may be possible to hand jam the above example given it its specificity and I have full knowledge of what I want a priori, I need a more general solution generating a symbolic array of strings that can be accessed arbitrarily. 

Any directions on how to proceed inside the z3 python wrapper? 

Thanks

**Comment by NikolajBjorner** [comment]
The function str.indexof can be used for your example. 
(str.indexof a b) or (str.indexof a b offset) 
returns the index of the first occurrence in a of b after offset (set to 0 if omitted).
Then you can say 
(or (= -1 (str.indexof a b)) (not (= "bad_string" (str.substr a (str.indexof a b) (str.len "bad_string")))

**Comment by bdrodes** [comment]
Ignoring the particular example, is there a way to get back a Z3 array that is a string split of a symbolic string with a symbolic delimiter? The rationale here is I'm trying to build up Z3 expression automatically. It is easier to directly convert split into a Z3 array, rather than looking at the use of the split within an expression to use the kind of solution you suggested. 

Thanks again

**Comment by NikolajBjorner** [comment]
not directly. 
Indirectly by defining a recursive function that does the transduction into sequences of strings.
Unlikely to be really good for reasoning, at least if considering that there are ways to reason about transducers on strings and the string-split function is a mild generalization of a string2string transducer.
