### ISSUE TITLE
No Joy on Trivial Inequality

### ISSUE THREAD

**Issue by JokeRoss** [Z3Prover/z3#2849]
The following prints "unknown", in spite of being easily satisfiable.
`# -*- coding: utf-8 -*-
# This is z3-4.8.6-x64-win

from z3 import *

a,b,c = Reals('a b c')
i = Int('i')
    
s = Solver()    
set_param("smt.random_seed", 1)
   
s.add(-a-b+c < 0.0)
s.add(+a-b-c < 0.0)
s.add(+a+b+c+i*c < 0.0)
# Satisfied by a=-1, b=+1, c=-1, i=0

print(s.check())
`
The problem goes away (i.e., z3 returns a satisfactory model) if any of the following changes are made:
- Delete "+i*c"
- Change the declaration of 'i' from Int to Real
- Change the '*' to '+'
- Change the 'i' to 'c'

**Comment by levnach** [comment]
It works now.
