### ISSUE TITLE
Z3 doesn't properly convert float value to maximum subnormal

### ISSUE THREAD

**Issue by ritave** [Z3Prover/z3#2851]
Minimal Python reproduction:
```python
import z3
s = z3.Float32()

# Should be represented as: 0x007fffff
#   with error: 1.069244107548702944484928735E-46
a = z3.FPVal(1.1754942e-38, s)

# Decimal: 1.1754942106924411e-38
# Should be represented as: 0x007fffff
#   with error: -2.451297055515071265117294757E-55
b = z3.FPVal(float.fromhex("0x1.fffffcp-127"), s)

# a.significand_as_bv() == 8388606
# b.significand_as_bv() == 8388607
assert z3.simplify(a == b)
```

**Comment by wintersteiger** [comment]
Python disagrees, those are not the same numbers:

```
print((1.1754942e-38).hex())
print(float.fromhex("0x1.fffffcp-127").hex())
```

says

```
0x1.fffffbb1dd6a1p-127
0x1.fffffc0000000p-127
```

Note that in Python, floats are double precision, i.e. 64 bit, so there will be some rounding involved when converting to 32 bit (Z3's Float32). I think numpy provides single precision floats, but I don't know whether they are IEEE-754 compliant.

**Comment by ritave** [comment]
@wintersteiger 
I'm sorry I didn't provide enough clarity, let me elaborate.

What you've written is all correct - these are doubles and are indeed different.
But they should be rounded down to the same 32bit representation, which I verified by an example below and by using online tools such as https://www.h-schmidt.net/FloatConverter/IEEE754.html

```python
import struct

def float_to_hex(f):
    # Converts into little endian byte stream of float representation
    # and then into little endian integer, which then is printed as hex string
    return hex(struct.unpack('<I', struct.pack('<f', f))[0])

# Both of which are equal to '0x7fffff'
assert float_to_hex(1.1754942e-38) == float_to_hex(float.fromhex("0x1.fffffcp-127"))
```
The algorithm of the Python's float packing can be found here:
https://github.com/python/cpython/blob/cb8b946ac10386e6cab1376945f64f683b5b16d3/Objects/floatobject.c#L2176

What I'm trying to convey is that Z3's conversion into smaller precision differs from the canonical one.

This error is caused by wrong rounding method, which in case of Z3 is round down, which can be seen, for example, here:
https://github.com/Z3Prover/z3/blob/423e084cda3c58b931bee7034e68b58516512106/src/api/api_numeral.cpp#L85

Instead of the canonical round ties to even as per https://ieeexplore.ieee.org/document/8766229 (Section 4.3.1).

**Comment by ritave** [comment]
Ps. You can sidestep the issue by using the following workaround
```python
z3.simplify(
            z3.fpFPToFP(z3.RoundNearestTiesToEven(),
                        z3.FPVal(float(v), z3.Float64()),
                        sort))
```

**Comment by wintersteiger** [comment]
Oh right, the Python API converts to strings before it converts to Z3-floats and the SMT standard doesn't specify that conversion. IEEE-754 requires NearestTiesToEven though, as you say; as specified in section 5.12. Fixed, thanks for the report!
