### ISSUE TITLE
c++ example is broken, make file is incorrect

### ISSUE THREAD

**Issue by arstero** [Z3Prover/z3#2855]
I have synced the latest code and build(make, sudo make install, then make example).

g++ -D_MP_INTERNAL -DNDEBUG -D_EXTERNAL_RELEASE -D_USE_THREAD_LOCAL  -std=c++11 -fvisibility=hidden -c -mfpmath=sse -msse -msse2 -O3 -D_LINUX_ -fPIC -D_LINUX_  -o example.o  -I../src/api -I../src/api/c++ ../examples/c++/example.cpp
g++ -o example example.o -lstdc++ -lz3

/usr/bin/ld: example.o: in function `main':
example.cpp:(.text.startup+0x5b1): undefined reference to `Z3_mk_lstring'
/usr/bin/ld: example.cpp:(.text.startup+0x600): undefined reference to `Z3_get_lstring'
collect2: error: ld returned 1 exit status

Please fix this.

Thanks,
arstero

**Comment by NikolajBjorner** [comment]
seems you have an old version of libz3 laying around.
