### ISSUE TITLE
Error in bitvector reasoning with QF_BV

### ISSUE THREAD

**Issue by skloibi** [Z3Prover/z3#2856]
Hi, I ran into a problem when dealing with bitvector arithmetics in logic `QF_BV` - the following snippet produces unexpected output:
```smt
(set-option :produce-models true)
(set-logic QF_BV)
(declare-fun a () (_ BitVec 32))
(assert (bvslt a (_ bv32768 32)))
(assert (bvslt (_ bv4294934527 32) a))
(check-sat)
(push 1)
(assert (bvslt a (_ bv11 32)))
(push 1)
(pop 1)
(pop 1)
(assert (not (bvslt a (_ bv11 32))))
(check-sat)
(assert (= a (_ bv123 32)))
(check-sat)
(get-value (a)) ; should be #x0000007b (123), but is #x00000079 (121)
```

As stated, this should ideally return `#x0000007b` (and does so on CVC4), but returns `#x00000079`. Interestingly, removal of the sat-checks or the redundant push / pop sequences fixes this problem, hence this test case seems a little bit convoluted.

The full output is:
```
sat
sat
sat
((a #x00000079))
``` 

I tested this on Z3 v4.8.8 built from source on Fedora 30.

**Comment by NikolajBjorner** [comment]
it isn't reproducing, windows 64 / ubuntu 16.
If you are able to reproduce under debug mode and trace selectively on -tr:rewriter -tr:rewrite -tr:before_search -tr:after_search -tr:bv and similar, it should be possible to localize the issue, which is perhaps an overflow bug.

**Comment by skloibi** [comment]
Thanks for the update. I also tried it on ee62f83131c3ead740729aac99ea48de797fdb06 and it seems to be resolved by now, i.e. now the result is `#x0000007b` as expected!
