### ISSUE TITLE
Translate constructor for optimize

### ISSUE THREAD

**Issue by marcelwa** [Z3Prover/z3#2859]
Hi,

I was wondering if technical obstacles are preventing the optimize class from having a translate constructor as the solver class does.

I'm using Z3 in a complex asynchronous approach in C++. I have multiple solver and optimize objects that are used by different threads. Each having its own context because of thread safety of course. It's super convenient to translate solvers from one context to another for incremental solving on different threads. I really want to do the same with optimize, too.

Any chance this can be made possible?

Thanks for your time and effort!

**Comment by NikolajBjorner** [comment]
This is a good point. Currently, the workaround is to extract the assertions and objectives separately, and create a new context based on these. A maximize objective is translated to a minimize objective where the objective function is multiplied by -1. An internal implementation would probably do precisely this, as there is no real incrementality available for optimization context at the moment.

So something like this:

```
optimize translate(optimize& src, context& dst) {
      optimize result(dst);
      for (auto& e : src.assertions()) result.add(expr(Z3_translate(e, e.ctx(), dst), dst));
      for (auto& e : src.objectives()) result.minimize(expr(Z3_translate(e, e.ctx(), dst), dst));
      return result;
}
```   

BTW, it also suggests that the C++ API doesn't have the translate functions on expressions and expr_vectors exposed at the moment. So it should be useful to have these for common consumption. If you or others find such small things that can be added to the API a pull request is certainly invited and it could help everyone.

**Comment by marcelwa** [comment]
Thank you a lot for the quick reply. Just to make sure I understood you correctly, please allow me to ask a follow-up question regarding your line

> as there is no real incrementality available for optimization context at the moment.

Do you mean that even if its `context` is not translated, `optimize` does not make use of learned clauses when confronted with a series of `add`, `check`, `add`, `check` requests? And, vice versa, does the regular `solver` still make use of learned clauses when its `context` was translated?

> BTW, it also suggests that the C++ API doesn't have the translate functions on expressions and expr_vectors exposed at the moment.

Indeed, `translate` is only available as a member function of `solver` and `model` at the moment.

**Comment by NikolajBjorner** [comment]
In mainstream use cases, you can interrupt the regular solver, clone it and start from where it left in the clone. I use this for enabling parallel solving. This is not a supported scenario when it comes to optimization.

**Comment by marcelwa** [comment]
I was just about to send a pull request implementing the respective constructor, but you were quicker^^ Thank you.

If you could refer to my question regarding incremental solving (not necessarily assuming multi-threading) real quick, then this issue can be closed as far as I'm concerned.

> Do you mean that even if its context is not translated, optimize does not make use of learned clauses when confronted with a series of add, check, add, check requests? And, vice versa, does the regular solver still make use of learned clauses when its context was translated?

**Comment by NikolajBjorner** [comment]
- optimize never uses learned clauses between calls.
- solver uses learned clauses in many use cases (not all, because when it invokes a tactic, the state is going to be insulated) where a solver is used incrementally and/or interrupted.

**Comment by NikolajBjorner** [comment]
There was also a bug inside of the optimize implementation so it was useful to catch this.

**Comment by marcelwa** [comment]
I'm glad you could isolate a bug. That's always nice. Plus, I could gain some new insights with your help. Only one thing isn't completely clear to me yet: are learned clauses copied to the solver created by the translate constructor? What I mean can be illustrated by the following snippet.

```c++
z3::context ctx1, ctx2;
z3::solver s1(ctx1);

s1.add(...);
s1.check();
// ...

// translate constructor
z3::solver s2(ctx2, s1, z3::solver::translate);
```

Does `s2` "inherit" learned clauses from `s1`? My apologies for keeping you busy.

**Comment by NikolajBjorner** [comment]
For clauses from QF_FD solver, which uses the SAT solver core, it copies learned clauses with a low glue level. For general SMT formulas it only copies the current non-redundant clauses. This still includes simplified clauses, such as learned units. I didn't enable copying learned clauses for the SMT core because I was unable to produce a test where this had a benefit. The SMT core does not use glue levels, but just activity scores. They could be used as a heuristic there but really establishing a benefit from copying learned clauses requires a good use case and evaluation. It will be better to create variants of this functionality based on an application. So if you have one, you could try toggling the options in the smt_context code and provide feedback on what works. 
https://github.com/Z3Prover/z3/blob/dc5d8819cd5bc8377f142c94ebd34818c03f3e1c/src/smt/smt_context.cpp#L200

**Comment by marcelwa** [comment]
That's exactly what I needed to know. Thanks a lot for your time and the helpful comment. As far as I'm concerned, this issue can be closed now.

**Comment by NikolajBjorner** [comment]
ok
