### ISSUE TITLE
ForAll

### ISSUE THREAD

**Issue by dah-fari7009** [Z3Prover/z3#2866]
Good evening,

I was wondering if there were a way to apply a forall to uninterpreted functions. mkForAll expects an array of Expr, from which FuncDecl does not inherit. I am trying to express that I want my formula to stand for any valuations that a function might take 
(ex: mkForAll( func(int,int,int) int, .....)

**Comment by NikolajBjorner** [comment]
You can't quantify over functions in Z3. You can quantify over uninterpreted constants that become representatives for bound variables. You can quantify over constants that range over arrays and there is limited instantiation support for finding lambda solutions.

**Comment by dah-fari7009** [comment]
Hi again,
This time I am trying to make a forall on the expr I obtain from an application 
forall (f a) where f is a function, but I obtain an exception:
com.microsoft.z3.Z3Exception: invalid argument
