### ISSUE TITLE
Sensitive performance/timeout in QF_UFLIA

### ISSUE THREAD

**Issue by wilcoxjay** [Z3Prover/z3#2875]
I am running into a performance/timeout problem with examples like [this](http://jamesrwilcox.com/qfuflia-timeout.smt2). (Minimized as best I could.)

The formula is satisfiable, but Z3 has trouble seeing this quickly. Removing any single assertion from that file causes Z3 to find it satisfiable immediately. In most cases, the returned model will *also* satisfy the deleted assertion, meaning that the original file is also satisfiable.

On Z3's 4.8.7 and 4.8.6 releases, this example seems to take for ever (> 1 minute at least), but removing any single assertion causes immediate SAT. 

On yesterday's nightly (09523a4), the unmodified is much faster, taking about 3 seconds to find a model. However, even then, removing any single assertion seems to cause it to be instantaneous instead of taking 3 seconds.

Strangely, on rise4fun (which reports using version 4.5.1) returns SAT quickly as well. So perhaps this is a problem that was introduced sometime after 4.5.1 and has been partially fixed some time since 4.8.7?

Is it fair to call this a performance bug? Is there anything I can do to work around it?

/cc @shellygr

**Comment by NikolajBjorner** [comment]
This seems to work well: smt.arith.solver=2 smt.auto_config=false /st
@levnach: possibly perf regression for the new lia solver

**Comment by levnach** [comment]
I ran z3 http://jamesrwilcox.com/qfuflia-timeout.smt2.
I narrowed it down: it worked fast at:
 ad309e53a ("fix #2766", 2019-12-01)
then it became slow at 
7b0327dba ("fix #2767", 2019-12-02)
All revisions in between these two commits crash on this benchmark.

**Comment by wilcoxjay** [comment]
When I minimized example above, I only used the new arithmetic solver. But I went back to the original example and it also times out under the old solver. So [here](http://jamesrwilcox.com/qfuflia-timeout-2.smt2) is another minimized version of the example that times out after 1 minute under the following 8 configurations:

```
z3-4.8.7 
z3-4.8.7 smt.arith.solver=2 smt.auto_config=false
z3-4.8.7 smt.arith.solver=2 smt.auto_config=false tactic.solve_eqs.max_occs=4
z3-4.8.7 tactic.solve_eqs.context_solve=true tactic.solve_eqs.max_occs=4
z3-nightly 
z3-nightly smt.arith.solver=2 smt.auto_config=false
z3-nightly smt.arith.solver=2 smt.auto_config=false tactic.solve_eqs.max_occs=4
z3-nightly tactic.solve_eqs.context_solve=true tactic.solve_eqs.max_occs=4
```

where `z3-nightly` refers to the release from commit `eb3fc4f47e` from a few days ago. 

Unfortunately the minimized file is quite large, but I hope it helps.

**Comment by NikolajBjorner** [comment]
OK, thanks

**Comment by NikolajBjorner** [comment]
Wve been working hard on profiling these examples and added several improvements in various places. The solver now handles them most of the time, that is for most values of random seeds. Setting smt.phase_selection=7 seems to help further, and generally I am moving to make this the default phase selection heuristic as it can help dramatically in some other cases that have shown up.

Another way to improve answer robustness and at the same time utilize all your spare cores is also now available through the option smt.threads=<number of threads of your desire>. It is super fresh and given that the solver now handles these examples most of the time it doesn't compete well against the common case on these examples. For other instances, there is a good chance it should be helpful so consider playing with this option.
