### ISSUE TITLE
uninterpreted functions 

### ISSUE THREAD

**Issue by dah-fari7009** [Z3Prover/z3#2882]
Good morning,

I am trying to check the satisfiability of a given formula. Let's say I have a formula that contains multiple real uninterpreted functions and for example the multiplication of two of them (UF_1() * UF_2 ()). I currently obtain UNKNOWN as a result and wanted to know if these type of cases can be handled by z3 ? Is it a known problem or is there a specific tactic that I should use ?

Thank you :)

**Comment by NikolajBjorner** [comment]
it isn't complete for non-linear arithmetic
