### ISSUE TITLE
z3 doesn't like the `produce-interpolants` command

### ISSUE THREAD

**Issue by LeventErkok** [Z3Prover/z3#2885]
Looks like interpolants are back with this commit: https://github.com/Z3Prover/z3/commit/9179deb7463c707719e2461850a78be41cad69dd

Which is really nice. It seems to work fine in my limited testing so far.

But looks like z3 doesn't understand/support the command:

```
(set-option :produce-interpolants true)
```

was this intentional? I believe the old version not only did support this command, it actually was required for interpolants to be produced.

This isn't a must, but just checking the change was intentional.

**Comment by NikolajBjorner** [comment]
It is not quite ready for prime time. It is going through a very first round of testing and I am finding crashes and bugs. We are currently working on documenting the theory, making sure this is right, and then refining the implementation, which is probably going to take several iterations. For sure, if you have test cases it is good to assemble these for development. MathSAT & SMTInterpol publish relatively few and they are useful. 
There is no _standard_ format for posing interpolation problems. MathSAT uses annotated formulas and sequence interpolants, SMTInterpol uses named formulas. I believe both ways are requiring unnecessary linguistic support. SMTLIB2 already has define-fun which can be used for creating names for large formulas. In addition, there are no additional settings required. The interpolation command is separate from the state of current assertions. The conventions used for previous support of interpolation are not relevant as the implementation is completely different. So you can ignore whatever set-info was used before. The main target at present is EUFLIA (and EUFLRA). Arrays are possible, but will not be added until this functionality feels solid.
