### ISSUE TITLE
assert

### ISSUE THREAD

**Issue by dah-fari7009** [Z3Prover/z3#2886]
Good evening,

Is there a way to add an assert to a formula in the JAVA API, if one is working directly on BoolExpr and not use the smt2-lib parser ? 

I mean something like context.mkAssert(context.mkEq(ret,5))

**Comment by NikolajBjorner** [comment]
I believe JavaExample.java has several examples that would be instances of your question.

**Comment by dah-fari7009** [comment]
Hi,
The instances in JavaExample all provide assert as a string and use the smt2-lib parser. My expression is already a BoolExpr and not a string

**Comment by NikolajBjorner** [comment]
Not true at all. See "prove" function.

- Nikolaj

________________________________

**Comment by dah-fari7009** [comment]
Oh, I understand. Thank you very much
