### ISSUE TITLE
Soundness bug QF_FP, fp.roundToIntegral

### ISSUE THREAD

**Issue by wintered** [Z3Prover/z3#2894]
Hi,
on the following formula z3 returns `sat` although the formula is unsat.
```
(declare-fun x () (_ FloatingPoint 3 24))
(declare-fun rm () RoundingMode)
(assert (distinct (fp.roundToIntegral rm (fp.roundToIntegral rm x)) (fp.roundToIntegral rm x)))
(check-sat)
```
OS: Ubuntu 19.04
Revision: eea7805

**Comment by wintersteiger** [comment]
Thanks for the report, this is now fixed! Three exponent bits are a corner-case in many operations, it's quite possible that there are more similar bugs, so feel free to report anything that looks suspicious.
