### ISSUE TITLE
installing Z3 4.8.7 on Ubuntu 14.04

### ISSUE THREAD

**Issue by SunBeomSo** [Z3Prover/z3#2897]
I have installed Z3 4.8.7  from source code on Ubuntu 14.04, with OCaml binding. As a result, ``z3 --version`` successfully outputs the message ``Z3 version 4.8.7 - 64 bit``.

However, when I tried the OCaml code snippet
```
let _ = print_endline Z3.Version.to_string in ...
```
outputs ``4.5.1.0``. At that time, my OCaml version was ``4.06.1``.

So I also have "newly" installed OCaml 4.09.0 and reinstalled Z3 from source code with OCaml 4.09.0 binding, but I still encountered the same problem.

Could you provide me any guidance for me?

**Comment by SunBeomSo** [comment]
I also checked Z3 4.8.7 has been installed via ``#use topfind;;`` and ``#list`` commands in OCaml interpreter.

**Comment by NikolajBjorner** [comment]
could be you have an old z3 library laying around in your path.

**Comment by SunBeomSo** [comment]
@NikolajBjorner 

``opam install z3`` finally worked for me. But I still wonder why this command works but my building from source code did not work (because I usually prefer building from source code).

> could be you have an old z3 library laying around in your path.

Regarding ``old z3 library``, do you mean Z3 related files under ``lib`` directory?

**Comment by NikolajBjorner** [comment]
on your question: yes, that is what I am referring to. Installation locations can be several places, including if you have a pip install.

**Comment by SunBeomSo** [comment]
@NikolajBjorner Thanks,  I will investigate it later.
