### ISSUE TITLE
How to make size of BitVec compatible

### ISSUE THREAD

**Issue by tintinlam007** [Z3Prover/z3#2900]
(declare-const A (_ BitVec 8))
(declare-const B (_ BitVec 4))
(assert (= A #x01))
(assert (= A B))
(check-sat)
(get-model)

z3 has got error because size of BitVec incompatible. How to transformat BitVec size? thank you~

**Comment by wintersteiger** [comment]
Use the `zero_extend` or `sign_extend` operator as defined in smt-lib here: http://smtlib.cs.uiowa.edu/Logics/QF_BV.smt2
