### ISSUE TITLE
AUFNIRA soundness bug

### ISSUE THREAD

**Issue by Heizmann** [Z3Prover/z3#291]
Using f78c769b3b650464650631e655fc2e9d7d4cbdfe the result of the last check-sat command in [this script](http://www.informatik.uni-freiburg.de/~heizmann/20141104-z3bug-invert_string_true-unreach-call.i.smt2.zip) is *unsat*, however *sat* would be the correct result.

The bug is not reproducible any more if you change the logic to something simpler or if you remove all "useless" SMT commands. I first detected the problem with z3 version that is at least one month old, so the bug was probably not introduced recently.

**Comment by wintersteiger** [comment]
That's a 16.5MB file; there is no way for us to tell whether it should really be sat or unsat in any useful amount of time. Do you have further evidence, or can you minimize the script, e.g., by removing unnecessary push/pop scopes?

**Comment by Heizmann** [comment]
All push/pop scopes but the last one are "unnecessary". However, if I remove them, the bug is not reproducible any more. Hence, my wild guess is that Z3 does not clear the assertion stack properly for some pop.

Another comment. The script does not contain any quantifier. If you switch the logic to QF_UFNIRA the result is *sat*.

**Comment by Heizmann** [comment]
Let my try to make it more clear. The script has to following form

    a bunch of variable declarations
    (echo "Finished declaration local variables")

    thousands of push/pop blocks such that we never assert something on the empty assertion stack

    (push 1)
    (assert (and (<= c_ULTIMATE.start_main_~max~5 5) (<= 5 c_ULTIMATE.start_main_~max~5) (not (< (mod c_ULTIMATE.start_main_~i~5 4294967296) (mod c_ULTIMATE.start_main_~max~5 4294967296)))))
    (assert (not (or (<= 4294967300 c_ULTIMATE.start_main_~i~5) (<= c_ULTIMATE.start_main_~i~5 4))))
    (check-sat)
    (pop 1)

**Comment by wintersteiger** [comment]
I see, that will take some time to figure out then. Do you have an easy way of doing a binary search-like removal of scopes? E.g., remove half of the scopes and check whether the bug is still triggered?

**Comment by Heizmann** [comment]
Unfortunately, no. My hope was that you have some delta debugging script that you apply if you receive bug reports like this.

**Comment by NikolajBjorner** [comment]
BTW, one way to turn down the noise is to use random seeds.
commenting out all the echo and previous check-sats retains the bug:

z3 invert_string_true-unreach-call.i.smt2 smt.random_seed=1
sat

z3 invert_string_true-unreach-call.i.smt2 smt.random_seed=3
unsat

**Comment by wintersteiger** [comment]
Further reduced to just a few lines: https://gist.github.com/wintersteiger/c280c3f2aa9fca76aa56

**Comment by NikolajBjorner** [comment]
fix is now a pull request.

**Comment by wintersteiger** [comment]
Awesome, thanks for going through all of that! This is quite a significant change, so I can't tell from the diff whether it will work in all cases. I think we should just merge it and then see whether the nightly runs throw any new problems.

**Comment by NikolajBjorner** [comment]
Thanks for weighing in. It is indeed a bit of a change so not without risk of regressions. I just merged the change.

Nikolaj

**Comment by wintersteiger** [comment]
Great! I'm currently fixing the other issues with the nightly runs. I'm hoping we'll get much cleaner results tomorrow.

**Comment by NikolajBjorner** [comment]
Merged
