### ISSUE TITLE
ast_manager LEAKED: 6

### ISSUE THREAD

**Issue by wintered** [Z3Prover/z3#2911]
Consider the following formula. 
```
(declare-fun a () Real)
(assert (> 0 0 (= a 0)))
(check-sat)
```
Z3 gives the following output.
```
sat
ast_manager LEAKED: 6
Leaked: (> 0::Int 0::Int)
id: 27
```
OS:Ubuntu 18.04
Revision: 41a4dcf

**Comment by NikolajBjorner** [comment]
This is not really interesting: the input is not well-typed and it reports a type error. The leak is debug diagnostics. WIll not address this.
