### ISSUE TITLE
API inconsistency when using the API "incorrectly"

### ISSUE THREAD

**Issue by andrewvaughanj** [Z3Prover/z3#2915]
This is very much an example of "garbage in, garbage out" or "play stupid games, win stupid prizes", but I have code that looks like this:

```
from z3 import *
import itertools


def test(use_abv, use_fpeq):

    if use_abv:
        s = SolverFor("QF_ABV")
    else:
        s = Solver()

    y = Const("y", Float32())

    ten = FPVal(10, Float32())

    if use_fpeq:
        s.add(fpEQ(y, ten))
    else:
        s.add(y == ten)

    assert s.check() == sat
    m = s.model()
    val_for_y = m[y]

    return (hasattr(val_for_y, "isNaN"), isinstance(val_for_y, FPNumRef))


def main():

    to_try = itertools.product([False, True], [False, True])
    for use_abv, use_fpeq in to_try:
        has_is_nan, is_fpnumref = test(use_abv, use_fpeq)
        print(
            "use_abv={use_abv}, use_fpeq={use_fpeq}, has_is_nan={has_is_nan}, is_fpnumref={is_fpnumref}".format(
                use_abv=use_abv,
                use_fpeq=use_fpeq,
                has_is_nan=has_is_nan,
                is_fpnumref=is_fpnumref,
            )
        )


if __name__ == "__main__":
    main()

# EOF
```

Which prints the following:

```
use_abv=False, use_fpeq=False, has_is_nan=True, is_fpnumref=True
use_abv=False, use_fpeq=True, has_is_nan=True, is_fpnumref=True
use_abv=True, use_fpeq=False, has_is_nan=True, is_fpnumref=True
use_abv=True, use_fpeq=True, has_is_nan=False, is_fpnumref=False
```

That is, in the case where we use `QF_ABV` (incorrectly) and use `fpEQ`, we get back an `FPRef` object, rather than a `FPNumRef` object.

I fully understand that when I use `QF_ABV` with `fpEQ`, that things become uninterpreted and Z3 can do what it likes:

```
[fp.numeral = FloatingPoint!val!1,
 y = FloatingPoint!val!0,
 fpEQ = [else -> True]]
```

However, what I don't understand is why the API returns objects of different _types_ when the API gets misused like this.

I don't really need a solution for this (personally); I'm raising the issue:

1. in case that this this is a genuine "bug";

2. to try and better understand why Z3 does what it does;

Thanks!

Tested on Z3 version: `d2fc88d`

**Comment by NikolajBjorner** [comment]
If I print the value and sorts as well, I see the following:

```
use_abv=False, use_fpeq=False, has_is_nan=True, is_fpnumref=True val=1.25*(2**3), sort=FPSort(8, 24)
use_abv=False, use_fpeq=True, has_is_nan=True, is_fpnumref=True val=1.25*(2**3), sort=FPSort(8, 24)
use_abv=True, use_fpeq=False, has_is_nan=True, is_fpnumref=True val=1.25*(2**3), sort=FPSort(8, 24)
use_abv=True, use_fpeq=True, has_is_nan=False, is_fpnumref=False val=FloatingPoint!val!0, sort=FPSort(8, 24)
```

So it seems the type of the z3 values are the same, but in the "abuse" case, the values are different. 
Z3's python wrapper creates an FPNum object when the underlying z3 value is a numeral. 
This is the case where is_fpnumref is True.

**Comment by andrewvaughanj** [comment]
I guess what I don't (really) understand is that after doing `m[x]`, I would have expected Z3 to give a "value" (i.e., a numeral value) to `x`.

However, when ABV is used "incorrectly", the value is left as an uninterpreted value, which isn't actually a "number", so you can't ask (e.g.,) `is_NaN`.

Does this "make sense"? This isn't a sarcastic question; I'm genuinely interested in understanding the behaviour of Z3 here.

**Comment by NikolajBjorner** [comment]
I think it goes along the following lines:
The solver associates so-called "value factories" for the theories that are attached. It looks like QF_ABV doesn't attach a floating point theory because the advertised theories are arrays and bit-vectors. So by default it invents fake values. You see these fake values in the model. 
The __get_item__ method in ModelRef, which you are using directly queries for values in the model, and these values are in most cases atomic (cannot be simplified or evaluated further).
The main way I tend to evaluate under a model is using "eval", or "evaluate". These methods have options to force evaluation to produce ground values (and not some unevaluated expression). But for your example it shouldn't make a difference.

Not for a second did I read your question as sarcastic. Sorry if my answer is late. It is a legitimate question. Perhaps I misunderstood the notion of "type" or "sort" in the question, because the notion of value evaluation is orthogonal to the object wrappers used by the Python API.

**Comment by andrewvaughanj** [comment]
My "sarcastic" comment was probably the wrong word -- it was more like "I know I keep asking 'why', but I am genuinely very curious to know, sorry if it seems we're stuck in a loop".

I also probably didn't use "sort" and "type" with their correct meanings: I know all of those values are the same sort (`FPSort(8, 24)`), but it was the fact that the API can return both `FPRef` and `FPNumRef` ("types") that confused me.

Normally I would use `m.eval(y, model_completion=True)` but, as you say, this doesn't actually make any difference to this example, as you get the same result irrespective of using `eval` (with `model_completion=True`) or `__getitem__`.

For an example like this, where everything is "uninterpreted", is it not reasonable for me (as a user) to expect Z3 to return a "concrete" value after requesting (via `eval`) the value of a term? If the current logic doesn't support obtaining a concrete value, then maybe it would be "kinder" to raise an exception, than give something back that isn't actually a value.

For example, when I've had Z3 make stuff "uninterpreted" past (e.g., when doing something like `fpFPToBV` with out-of-range values for the target BV width) then the operation still has "concrete" values, they're just not the values one might consider to make sense. That is, you still get something like is duck-typed like a real value, but you don't get that here.

As I mentioned, this actually isn't a problem I'm facing in any real instances; this was a bug in some code I wrote, which just had a very unexpected behaviour.

**Comment by NikolajBjorner** [comment]
I think the background is clarified by now: If Z3 is told to only consider the logic QF_ABV, then symbols from other logics are not interpreted. They can still have _values_ in models, so these values come from some abstract domain and don't tie back to floating point numbers. The cliché way to characterize this approach is that it is _by design_, and in this case I am not sure it makes sense to change this design. It is inherent that solvers for theories are added only according to the logic specified.
