### ISSUE TITLE
Incorrect result on NRA formula without free variable

### ISSUE THREAD

**Issue by muchang** [Z3Prover/z3#2917]
Hi,
For this formula,
```
(assert (forall ((a Real)) (exists ((b Real)) (and (= (/ 0 b) 0) (= a (/ 0 0))))))
(check-sat)
```
z3 gives an incorrect answer `sat` while cvc4 gives `unsat`.

OS: Ubuntu 18.04
Revision: 3ec7146

**Comment by NikolajBjorner** [comment]
this doesn't repro any longer
