### ISSUE TITLE
smtfd incorrect result on formula with  = and distinct 

### ISSUE THREAD

**Issue by muchang** [Z3Prover/z3#2923]
Hi,
For this formula,
```
(assert (= 0 1))
(assert (distinct 0 2))
(check-sat-using smtfd)
```
z3 gives an incorrect `sat` on this `unsat` formula. 

OS: Ubuntu 18.04
Revision: 805ac74

**Comment by NikolajBjorner** [comment]
dont' use smtfd on non-finite domains. It isn't filtering in formulas not in scope at the moment.
