### ISSUE TITLE
Variable redeclaration

### ISSUE THREAD

**Issue by wintersteiger** [Z3Prover/z3#293]
A bug reported by shoon42 on [stackoverflow.com](http://stackoverflow.com/questions/33507204/z3s-java-apis-handle-quantifier-variable-wrongly):

    (declare-fun i () Int)
    (declare-fun @I () Int)
    (declare-fun r2 () (Array Int Int))
    (assert (= i 4))
    (assert (forall ((@I Int))
    (! (=> (and (>= @I 0) (< @I i)) (= (select r2 @I) 0))
        :weight 10
        :skolemid test
        :qid test)))
    (check-sat)
    (get-model)

`@I` is declared globally existential, but later locally universal without a warning or an error.

**Comment by NikolajBjorner** [comment]
There is no bug. Lexical scoping rules apply. Bound variables supersede outer scopes.

**Comment by wintersteiger** [comment]
Indeed, that is what the standard says! In that case there's no issue here, thus closing.
