### ISSUE TITLE
smtfd incorrect answer on BV 

### ISSUE THREAD

**Issue by muchang** [Z3Prover/z3#2932]
Hi,
For this formula,
```
(assert (exists ((a (_ BitVec 1)))
  (forall ((b (_ BitVec 1)))
    (forall ((c (_ BitVec 1)))
      (forall ((d (_ BitVec 1))) false)))))
(check-sat-using smtfd)
```
z3 incorrectly gives `sat` on this `unsat` formula.

OS: Ubuntu 18.04
Revision: a05dec9

**Comment by NikolajBjorner** [comment]
please stop filing bugs on SMTFD: it performs worse than default on average and is therefore not a supported feature.
