### ISSUE TITLE
Assertion violation at ../src/util/hash.h Line: 78

### ISSUE THREAD

**Issue by muchang** [Z3Prover/z3#2935]
Hi,
For this formula,
```
(define-sort a () (FloatingPoint))
(check-sat)
```
z3 throws out an assertion violation:
```
ASSERTION VIOLATION
File: ../src/util/hash.h
Line: 78
n > 0
(C)ontinue, (A)bort, (S)top, (T)hrow exception, Invoke (G)DB
```

OS: Ubuntu 18.04
Revision: a05dec9

**Comment by NikolajBjorner** [comment]
why is this a useful bug?
The assertion is triggered in debug mode on malformed input.
There are no issues in release mode.
