### ISSUE TITLE
Wrong model on QF_NIA formula, functions, let

### ISSUE THREAD

**Issue by wintered** [Z3Prover/z3#2938]
Consider the following formula.
```
(declare-fun f (Int Int Int) Int)
(declare-fun g (Int Int Int) Int)
(declare-fun a () Int)
(assert (let ((b (f a a a))) (let ((c (f b a a))) (< (g b b 2) (- c)))))
(check-sat)
```
Z3 gives a wrong model on it.
```
(model 
  (define-fun a () Int
    0)
  (define-fun g ((x!0 Int) (x!1 Int) (x!2 Int)) Int
    0)
  (define-fun f ((x!0 Int) (x!1 Int) (x!2 Int)) Int
    0)
)
```
OS: Ubuntu 18.04
Revision: 1d05723

**Comment by NikolajBjorner** [comment]
@levnach This is a regression from a very recent push

**Comment by levnach** [comment]
It does not reproduce for me. I get 
================================
lev@lev-Surface-Laptop-2:~/dev/z3/build/debug$ ./z3 ~/Dropbox/smts/bug.smt2
(error "line 1 column 11: model is not available")
sat
================================
The same behavior occurs on earlier versions, as well. For example, on version 7df8d1763 ("move in assumptions to loop", 2020-02-01). I have not investigated when this bug has been introduced.

**Comment by NikolajBjorner** [comment]
the error "model is not available" seems not right: the problem is sat, and model generation is always on by default.

**Comment by NikolajBjorner** [comment]
seems fixed
