### ISSUE TITLE
z3str3 invalid model on int.to.str and str.++

### ISSUE THREAD

**Issue by muchang** [Z3Prover/z3#2954]
Hi,
For this formula,
```
(declare-fun a () String)
(declare-fun b () Int)
(assert (= (int.to.str b) (str.++ a "0")))
(check-sat)
(get-model)
```
`z3 smt.string_solver=z3str3` gives an incorrect model:
```
(model 
  (define-fun b () Int
    0)
  (define-fun a () String
    "\x00")
)
```
If I feed this model to the formula, `z3 smt.string_solver=z3str3` gives `unsat`.

OS: Ubuntu 18.04
Revision: 140926e

**Comment by mtrberzi** [comment]
Opened #3097
