### ISSUE TITLE
dom-simplify incorrect answer on QF_BV formula

### ISSUE THREAD

**Issue by muchang** [Z3Prover/z3#2965]
Hi,
For this formula,
```
(declare-fun d () (_ BitVec 4))
(assert
  (let ((a!6 (ite (and (= d #x0) true)
                  true
                  (and (= d #x0) true))))
  (and a!6 a!6)))
(check-sat-using dom-simplify)
```
z3 gives an incorrect answer `unsat` on this `sat` formula. 
` (check-sat-using default)` gives `sat`

OS: Ubuntu 18.04
Revision: 524434c

**Comment by nunoplopes** [comment]
This seems is a serious issue with the expression cache in `simplify_rec`. It is caching that `(and (= d #x0) true)` is false because in the ite false branch it becomes false.
The expression cache needs to be popped like the assertions.
