### ISSUE TITLE
qe-sat Assertion violation at ../src/qe/qe_sat_tactic.cpp Line: 634

### ISSUE THREAD

**Issue by muchang** [Z3Prover/z3#2966]
Hi,
For this formula,
```
(declare-fun a () Real)
(declare-fun b () Real)
(assert (forall ((c Real)) (= (>= 0.0 b) (= (<= c 0.0) (> a b)))))
(assert (forall ((d Real)) (< (/ (* (- a b) b) 0.0) a)))
(check-sat-using qe-sat)
```
z3 throws out an assertion violation:
```
Failed to verify: l_true == m_solvers[idx+1]->check()
ASSERTION VIOLATION
File: ../src/qe/qe_sat_tactic.cpp
Line: 634
UNREACHABLE CODE WAS REACHED.
(C)ontinue, (A)bort, (S)top, (T)hrow exception, Invoke (G)DB
```

OS: Ubuntu 18.04
Revision: 524434c

**Comment by NikolajBjorner** [comment]
I am trying really hard to imagine a reasonable user having the urge to eliminate a quantified formula which contains abusive division by 0.

**Comment by zhendongsu** [comment]
Thanks for fixing this bug (and a lot of the other bugs that we filed), Nikolaj!   The original unreduced test doesn't have such obvious divisions by 0.

**Comment by NikolajBjorner** [comment]
The case that seems to have been error prone is dealing correctly with semantics of underspecified operators, division, mod, remainder, power. They are bugs, but go under the radar as the use of these operators where the solver has to deal with underspecified behavior seems to have been pretty rare.
