### ISSUE TITLE
Build problem

### ISSUE THREAD

**Issue by Heizmann** [Z3Prover/z3#297]
I am trying to build 5ea2c2215367157080d432615db8467fcea1ff31 and get the following error message.

	src/smt/arith_eq_solver.cpp
	src/smt/theory_arith.cpp
	In file included from ../src/smt/theory_arith_def.h:27:0,
					from ../src/smt/theory_arith.cpp:20:
	../src/smt/theory_arith_int.h: In member function ‘void smt::theory_arith<Ext>::branch_infeasible_int_var(smt::theory_var)’:
	../src/smt/theory_arith_int.h:213:35: error: call of overloaded ‘mark_as_relevant(expr_ref&)’ is ambiguous
			ctx.mark_as_relevant(bound);
									^
	../src/smt/theory_arith_int.h:213:35: note: candidates are:
	In file included from ../src/smt/theory_arith_core.h:22:0,
					from ../src/smt/theory_arith_def.h:23,
					from ../src/smt/theory_arith.cpp:20:
	../src/smt/smt_context.h:1110:14: note: void smt::context::mark_as_relevant(expr*)
			void mark_as_relevant(expr * n) { m_relevancy_propagator->mark_as_relevant(n); m_relevancy_propagator->propagate(); }
				^
	../src/smt/smt_context.h:1114:14: note: void smt::context::mark_as_relevant(smt::bool_var)
			void mark_as_relevant(bool_var v) { mark_as_relevant(bool_var2expr(v)); }
				^
	Makefile:2221: recipe for target 'smt/theory_arith.o' failed
	make: *** [smt/theory_arith.o] Error 1

If needed, I can provide more information about my system.

**Comment by NikolajBjorner** [comment]
It will take me until tomorrow to fix. It should be easy temporary patch if this is urgent for you: Add explicit types to call site.

**Comment by Heizmann** [comment]
Thanks for the fix, but now there is a new compilation problem.

	src/smt/theory_utvpi.cpp
	In file included from ../src/util/util.h:23:0,
					from ../src/util/mpz.h:24,
					from ../src/util/mpq.h:22,
					from ../src/util/rational.h:22,
					from ../src/smt/theory_diff_logic.h:25,
					from ../src/smt/theory_utvpi.h:25,
					from ../src/smt/theory_utvpi.cpp:17:
	../src/smt/theory_diff_logic.h: In member function ‘virtual smt::theory* smt::theory_diff_logic<Ext>::mk_fresh(smt::context*)’:
	../src/smt/theory_diff_logic.h:246:95: error: invalid use of incomplete type ‘class smt::context’
			virtual theory * mk_fresh(context * new_ctx) { return alloc(theory_diff_logic, new_ctx->get_manager(), m_params); }
																								^
	../src/util/memory_manager.h:94:58: note: in definition of macro ‘alloc’
	#define alloc(T,...) new (memory::allocate(sizeof(T))) T(__VA_ARGS__)
															^
	In file included from ../src/smt/smt_enode.h:23:0,
					from ../src/smt/smt_theory.h:22,
					from ../src/smt/theory_diff_logic.h:30,
					from ../src/smt/theory_utvpi.h:25,
					from ../src/smt/theory_utvpi.cpp:17:
	../src/smt/smt_types.h:49:11: error: forward declaration of ‘class smt::context’
		class context;
			^
	In file included from ../src/util/util.h:23:0,
					from ../src/util/mpz.h:24,
					from ../src/util/mpq.h:22,
					from ../src/util/rational.h:22,
					from ../src/smt/theory_diff_logic.h:25,
					from ../src/smt/theory_utvpi.h:25,
					from ../src/smt/theory_utvpi.cpp:17:
	../src/smt/theory_utvpi.h: In member function ‘virtual smt::theory* smt::theory_utvpi<Ext>::mk_fresh(smt::context*)’:
	../src/smt/theory_utvpi.h:186:90: error: invalid use of incomplete type ‘class smt::context’
			virtual theory * mk_fresh(context * new_ctx) { return alloc(theory_utvpi, new_ctx->get_manager()); }
																							^
	../src/util/memory_manager.h:94:58: note: in definition of macro ‘alloc’
	#define alloc(T,...) new (memory::allocate(sizeof(T))) T(__VA_ARGS__)
															^
	In file included from ../src/smt/smt_enode.h:23:0,
					from ../src/smt/smt_theory.h:22,
					from ../src/smt/theory_diff_logic.h:30,
					from ../src/smt/theory_utvpi.h:25,
					from ../src/smt/theory_utvpi.cpp:17:
	../src/smt/smt_types.h:49:11: error: forward declaration of ‘class smt::context’
		class context;
			^
	Makefile:2138: recipe for target 'smt/theory_utvpi.o' failed
	make: *** [smt/theory_utvpi.o] Error 1

**Comment by NikolajBjorner** [comment]
Not sure how you would get this error and I would not, but the latest check-in moves the calls that can (potentially) not resolve the type into an environment where they can.

**Comment by Heizmann** [comment]
Using 8d1fa3ae50428a5b947cfa71fe0f512c0afc256d I was able to compile it. Thanks.
