### ISSUE TITLE
Floating Point conversion bug at small numbers 

### ISSUE THREAD

**Issue by hkr-droid** [Z3Prover/z3#2970]
Running on commit `e2514a2` as `z3 -smt2 -file <one of the below>` I seem to be running into a small inconsistency with how conversion between floating points is treated.  Consider the following:

`(set-logic QF_FP)`  
`(simplify (fp.geq ((_ to_fp 2 2) RNE (fp #b1 #b1100 #b0101)) (_ -oo 2 2)))`  

which results in `false`.  Pulling out just the to_fp conversion in the following way:

`(set-logic QF_FP)`  
`(simplify ((_ to_fp 2 2) RNE (fp #b1 #b1100 #b0101)))`  

we get `(fp #b1 #b10 #b1)`.  And if we substitute that for the to_fp conversion in the original formula as:

`(set-logic QF_FP)`  
`(simplify (fp.geq (fp #b1 #b10 #b1) (_ -oo 2 2)))`  

we generate `true`.

**Comment by wintersteiger** [comment]
Just in case you tried it: does this also happen with normal-sized floats?

**Comment by hkr-droid** [comment]
To address that, I tried the above sequence with the following initial formula:

`(simplify (fp.geq ((_ to_fp 8 9) RNE (fp #b1 #b10010111010 #b10110100010)) (_ -oo 8 9)))`  

This returns `false`, simplifying just the fp bitvector returns `(fp #b1 #x3a #xa2)` and substituting that for the to_fp returns `true`.  

I'm not sure if that's sufficiently normal-sized; if you have an idea for another diagnostic, I am happy to try it.

**Comment by wintersteiger** [comment]
Thanks for the report, there was indeed a bug in the simplifier; `(_ to_fp ...)` was wrong. By "normal-sized" I meant single/double size, which didn't trigger this bug.
