### ISSUE TITLE
qe_rec incorrect answer on UFLIA formula

### ISSUE THREAD

**Issue by muchang** [Z3Prover/z3#2974]
Hi,
For this formula,
```
(declare-fun a (Int) Bool)
(assert (exists ((b Int)) (and (> b 0) (a b))))
(check-sat)
(check-sat-using (then qe_rec smt))
```
`check-sat` reports `sat` while `(check-sat-using (then qe_rec smt))` reports `unsat`

OS: Ubuntu 18.04
Revision: ba4cc27

**Comment by NikolajBjorner** [comment]
qe tactics were tested on domains that admit QE. UF doesn't, so this exercises a potential use-case that wasn't tested for. It is reasonable to ask for parameter validation or similar, but priority wise it is lower.
