### ISSUE TITLE
Old C++ standards are not supported by Z3

### ISSUE THREAD

**Issue by SweetVishnya** [Z3Prover/z3#2984]
@NikolajBjorner, it would be nice if you could avoid using C++11 in `z3++.h` header. Our tool uses old C++03 and we are not able to build with fresh z3 from now on.

https://github.com/Z3Prover/z3/blob/f161bdaf8faf92b23a07d9a3c89f94b448791f0b/src/api/c%2B%2B/z3%2B%2B.h#L2787

**Comment by NikolajBjorner** [comment]
Could you add a pull request that makes the header file down compatible?

**Comment by SweetVishnya** [comment]
Yes, I'll try it this week.
