### ISSUE TITLE
Unexpected slow performance

### ISSUE THREAD

**Issue by pjljvandelaar** [Z3Prover/z3#2985]
We test TorXakis in such a way that the problem solvers that TorXakis uses under the hood just get simple fill-in exercises.

So far that seemed to work fine.
Yet today we generate a test scenario that Z3 can't handle even in hours.

Could you please look into the performance of Z3 on this file:
[logSMT.2020-02-12-12-09-58.1564602.smt2.txt](https://github.com/Z3Prover/z3/files/4193308/logSMT.2020-02-12-12-09-58.1564602.smt2.txt)

Once again:
* Other problem solvers have no problems with this file.
* On many, many similarly generated test cases Z3 also has no problems at all and just takes seconds to solve those.

**Comment by NikolajBjorner** [comment]
it is the use of if-then-else and recursive function declarations. The pre-processor unfolds them to a flat case statement. It can be exponential in the size of the encoding. If you are not using recursive functions then just use define-fun. @c-cube, fyi.

**Comment by pjljvandelaar** [comment]
I have analysed this issue further.
On windows, with the attached file
[z3.echo.smt2.txt](https://github.com/Z3Prover/z3/files/4244181/z3.echo.smt2.txt)
one gets
```
PS C:\TorXakis\TorXakis.RefactorAll> z3 .\sys\txs-smt\z3.echo.smt2
sat
check-sat 1
pop 1
sat
check-sat 2
```
where the echo message `pop 1` was output at 10:27, 
the echo message `check-sat 2` was output at 10:32.
Yet at 11:45 I still didn't have the echo message `pop 2`.

So I really believe,  there is something wrong in z3.
Imho the pop instructions takes far too long (infinite loop maybe?), 
even when related to time taken by the actions pushed on the stack.

I hope you can look into this issue once more.
I will also try to find an even simplere example where pop doesn't behave as to be expected.

**Comment by NikolajBjorner** [comment]
Commit 15f5444b8c6574b7bc97bd253fa35bf819527833 seeks to address the overheads reported.

**Comment by pjljvandelaar** [comment]
I just downloaded the latest version and the problem is gone.
It is really fast!
