### ISSUE TITLE
cmake build on Windows fails because "/D WIN32" is missing

### ISSUE THREAD

**Issue by chsticksel** [Z3Prover/z3#2986]
I tried building Z3 on Windows with CMake, and it stopped with the error `"/D WIN32" is missing`.

I traced that to msvc_legacy_quirks.cmake Line 61, where there is a check whether `CMAKE_CXX_FLAGS` contains the pattern `"/D[ ]*WIN32"`.

My `CMAKE_CXX_FLAGS` has a mix of `-D` and `/D` flags, and does include `-DWIN32`.

I can work around that by changing the pattern to `[/-]D[ ]*WIN32`, and to `[/-]D[ ]*_WINDOWS` three lines below. Is that safe to do, and would you be interested in changing that, too?

**Comment by NikolajBjorner** [comment]
sure, pull request appreciated matching for '-' along with '/' seems legit
