### ISSUE TITLE
New unsoundness bug in z3str3 after recent pushes

### ISSUE THREAD

**Issue by numairmansur** [Z3Prover/z3#2994]
Hi @mtrberzi 
I have an example where z3str3 gives an unsound result. The following file is satisfiable but z3str3 gives unsat. 
 
[9.smt2](https://github.com/Z3Prover/z3/files/4198409/9.smt2.zip)

I think this bug was introduced after the recent changes in z3str3. It does not exist in commit 321bad2c84c9bb0c58f44d5797bdf993b47b09d4 .

The bug was found on the following commit:

commit 0146259ea402a8bf3996f1ca0d2d37ed69fddd35
Author: Murphy Berzish <murphy.berzish@gmail.com>
Date:   Wed Feb 12 13:46:27 2020 -0500

**Comment by mtrberzi** [comment]
This was an interesting one. The bug ended up being exposed as a result of the commit you identified, but had been around for a while previous to that commit. Thanks for the report!

Opened #2997
