### ISSUE TITLE
Bit-blast tactic returns an incomplete formula

### ISSUE THREAD

**Issue by danieljmg** [Z3Prover/z3#2995]
Hello,
As the tseitin-cnf tactic does not preserve model equivalence I am trying to implement my own CNF transformation of the 'bit-blasted' formula.
The problem is that, after running (simplify, bit-blasting) tactic, and dumping the formula to a file or printing it, I am obtaining several incomplete clauses like 'Or(..., ...)))'.
How can I obtain the complete 'bit-blasted' formula?
Regards,

**Comment by wintersteiger** [comment]
Are you saying that the output literally contains three dots? Would sound like a Python issue to me, but I'm not sure whether you're using Python at all.

**Comment by danieljmg** [comment]
Yes, I am using python 3.8 under Windows 10 x64.
The code to dump the formula is plain simple:
`    p = ParamsRef()
    t = WithParams(Then('simplify', 'bit-blast'), p)
    subgoal = t(constraints)
    assert len(subgoal) == 1

    auxbb = open("pbb.txt","w+")
    for pbb in subgoal[0]:
        auxbb.write(str(pbb))
        auxbb.write(" and\n")
    auxbb.close()`

I have been looking for a python issue of this kind but could not find anything at all. It happens for large models.

**Comment by danieljmg** [comment]
The only similar issue that I've found is for numpy specifically: [](https://stackoverflow.com/questions/15364114/python-prints-in-very-large-output)
I think that the length of the text is constrained somehow within Z3py.

**Comment by danieljmg** [comment]
I have found something related, params:
`max_lines=10000000000, max_width=1000000`
Modify the output allowing larger text-width and more lines, however it still shows dots.

**Comment by danieljmg** [comment]
It is solved. The file z3printer.py contains the PP (Pretty Printer) class.
This parameter increase the ellipsis limit.
`set_option(max_depth = 10000000000)`
Closing it.
