### ISSUE TITLE
Installation prefix in a virtual environment is inconsistent between Linux and macOS

### ISSUE THREAD

**Issue by rosekunkel** [Z3Prover/z3#2998]
Curently, the installation prefix is set to `sys.prefix` by default: https://github.com/Z3Prover/z3/blob/0146259ea402a8bf3996f1ca0d2d37ed69fddd35/scripts/mk_util.py#L105.
When running `python scripts/mk_make.py` with an active virtual environment, this means that the prefix is set to `/path/to/venv/`. However, on macOS, the prefix is explicitly reset to /usr/local: https://github.com/Z3Prover/z3/blob/0146259ea402a8bf3996f1ca0d2d37ed69fddd35/scripts/mk_util.py#L592-L594
The effect of this is that if you build the python bindings on macOS while inside a virtual environment without explicitly setting the prefix on the command line, the python bindings won't work correctly. To fix this, you need to do something like this:
```sh
python mk_make.py --python --prefix=$(python -c 'import sys; sys.stdout.write(sys.prefix)')
```

**Comment by NikolajBjorner** [comment]
Should we just remove that line?

**Comment by rosekunkel** [comment]
I think so, but I don't have a mac available to test that.

**Comment by NikolajBjorner** [comment]
If you add a pull request, it will be tested in 3 different Mac builds
