### ISSUE TITLE
Can you merge the new ML API from the unstable branch into the master branch?

### ISSUE THREAD

**Issue by UnixJunkie** [Z3Prover/z3#30]

**Comment by Drup** [comment]
While we are at it, making the opt branch up to date with the unstable one would be very useful for me.

**Comment by wintersteiger** [comment]
Yes all of this will happen over the next few months as we prepare the next master release. After that (at the latest) we will switch to the different model of updating the master branch more often, until then we will collect everything in the unstable branch before we release, so bear with us for a little bit as we transition.

**Comment by wintersteiger** [comment]
Closing this issue, everything's on track, but we don't have an exact data for the next master release yet.
