### ISSUE TITLE
A constraint should be unsat, but z3 reports sat

### ISSUE THREAD

**Issue by qingkaishi** [Z3Prover/z3#301]
;
(set-info :status unknown)
(declare-fun a () (_ BitVec 3))
(declare-fun b () (_ BitVec 3))

(assert
(=
a
((_ int2bv 3) (ite (bvslt b (_ bv0 3)) (- (bv2int b) 8) (bv2int b)))
)
)

(assert
(distinct b a))

(check-sat)
(get-model)

The model z3 (version 4.4.0) provides for the above constraints is:

sat
(model 
  (define-fun b () (_ BitVec 3)
    #b001)
  (define-fun a () (_ BitVec 3)
    #b000)
)

But it does not satisfy the first assertion.

Please help~

**Comment by LeventErkok** [comment]
@qingkaishi This is most likely due to `int2bv` being uninterpreted. See here for details: http://stackoverflow.com/questions/27914582/z3-questions-about-z3-int2bv

**Comment by NikolajBjorner** [comment]
Yes, that's correct. Although it seems we never need this default behavior.

**Comment by NikolajBjorner** [comment]
I am changing the default behavior to avoid this and other pitfalls.
