### ISSUE TITLE
Forall/Exists working differently for similar models

### ISSUE THREAD

**Issue by damascenodiego** [Z3Prover/z3#3013]
**Version:** Z3 [version 4.8.7 - 64 bit]

I have a set of inequalities that I am trying to find a (trivial) solution. 

When I use the **Exists** operator, everything works great, as you can see in this [script](https://rise4fun.com/Z3/WUMsl). 

However, when I replace it by **Forall**, there is no solution, as I show in this [link](https://rise4fun.com/Z3/2iZS).

In this specific case, both scripts should be **sat** and return the same solution, right?

ps.: These are simplified versions of a script where I _explicitly defined all the inequalities for all Integer values from a specific range_  rather than _using the ForAll operator and a constraint defining the same interval_.

**Comment by NikolajBjorner** [comment]
For reference, here is the input using forall:

```

(declare-fun f_p1 () Int)
(declare-fun f_p2 () Int)
(declare-fun f_p3 () Int)
(declare-fun p1_f () Int)
(declare-fun p2_f () Int)
(declare-fun p3_f () Int)
(declare-fun l11 () Int)
(assert (= f_p1 1))
(assert (= f_p2 0))
(assert (= f_p3 0))
(assert (= p1_f 0))
(assert (= p2_f 0))
(assert (= p3_f 1))
(assert (= l11 1))
(assert (forall ((l11 Int))
  (let ((a!1 (< (+ 0 (* l11 (- f_p1 p1_f))) 0))
        (a!2 (< (+ 0 (* l11 (- f_p2 p2_f))) 0))
        (a!3 (< (+ 1 (* l11 (- f_p3 p3_f))) 1)))
    (or a!1 a!2 a!3))))

(check-sat)
(get-model)
```

The semantics is that there should be f_p1, p1_f, f_p2, p2_f, f_p3, p3_f such that for all l11, the disjunction of inequalities holds. However, for every possible value of f_p1, ... p3_f there is some value for l11 that violates each inequality (by setting l11 to 0). Therefore, the solution with ForAll is unsat.

**Comment by damascenodiego** [comment]
Thanks for the information @NikolajBjorner 
We've fixed our script by setting constraints within each clause in the OR operator.

Thanks
