### ISSUE TITLE
fix-dl-var incorrect answer on QF_SLIA formula with str.to.int int.to.str

### ISSUE THREAD

**Issue by muchang** [Z3Prover/z3#3023]
Hi,
For this formula:
```
(declare-fun a () Int)
(assert (distinct a (str.to.int (int.to.str a))))
(check-sat-using fix-dl-var)
```
Z3  incorrectly gives unsat, while this formula should be sat.

OS: Ubuntu 18.04
Commit: aaf2c3b

**Comment by NikolajBjorner** [comment]
It is also direct abuse to force using anything difference logic when invoking sequences/strings because the string theory uses full LIA not just DL fragment. Default mode would not apply such a mix.
