### ISSUE TITLE
trunk/src/ackermannization/lackr_model_constructor.cpp:323:9: style: Statements following return, break, continue, goto or throw will never be executed. [unreachableCode]

### ISSUE THREAD

**Issue by dcb314** [Z3Prover/z3#3024]
Source code is

        TRACE("model_constructor",
              tout << "eval(\n" << mk_ismt2_pp(term.get(), m, 2) << "\n->"
              << mk_ismt2_pp(result.get(), m, 2) << ")\n"; );
        return;
        if (fid == m_b_rw.get_fid()) {
            decl_kind k = fd->get_decl_kind();
            if (k == OP_EQ) {

**Comment by NikolajBjorner** [comment]
These occurrences are intended so will not be fixed even though it looks odd. I don't comment out the unreachable code.
