### ISSUE TITLE
Assertion violation at ../src/ast/ast.cpp Line: 1923

### ISSUE THREAD

**Issue by muchang** [Z3Prover/z3#3025]
Hi,
For this formula:
```
(declare-sort E 0)
(declare-fun s () (Set E))
(declare-fun t () (Set E))
(declare-fun u () (Set E))
(assert (< (card (union s t)) 4))
(assert (>= (card (union s u)) 1))
(assert (< (card (union t u)) 3))
(assert (< (card s) 4))
(check-sat)

```
Z3  throws out an assertion violation:
```
ASSERTION VIOLATION
File: ../src/ast/ast.cpp
Line: 1923
m_ast_table.contains(n)
(C)ontinue, (A)bort, (S)top, (T)hrow exception, Invoke (G)DB

```

OS: Ubuntu 18.04
Commit: 19ba294

**Comment by zhendongsu** [comment]
Hi Nikolaj, I'm curious as to why this one was closed as a duplicate.  The assertion violation still triggers for me with the latest trunk on Ubuntu, and I don't see another open issue with the same crash message.  Thank you.

**Comment by NikolajBjorner** [comment]
There is already another open bug for same cause.

- Nikolaj

________________________________

**Comment by NikolajBjorner** [comment]
C:\zzz\build>z3 2909.smt2
ASSERTION VIOLATION
File: ..\src\ast\ast.cpp
Line: 1923
m_ast_table.contains(n)

#2909

**Comment by zhendongsu** [comment]
Nikolaj, okay, I see; thanks.  I didn't notice #2909 as it had a different assertion failure from this one.
