### ISSUE TITLE
New unsoundness issue in z3str3

### ISSUE THREAD

**Issue by numairmansur** [Z3Prover/z3#3031]
Hi @mtrberzi,

In the latest commit  (41ab578593b5f3acf8d62b0fc3a3c7fa745ee67d) i get the following incorrect result on the following file:

[66.zip](https://github.com/Z3Prover/z3/files/4215232/66.zip)

```
$ ./z3-nightly/bin/z3 smt.string_solver=z3str3 66.smt2 
sat
sat
sat
sat
unsat
```

Everything should be sat. 

Interestingly, in commit 321bad2c84c9bb0c58f44d5797bdf993b47b09d4, i still get a wrong answer but a different one:

```
$ ./z3-321b/bin/z3 smt.string_solver=z3str3 66.smt2 
sat
sat
unsat
unsat
unsat

```

**Comment by mtrberzi** [comment]
This is fixed as of the latest commit (5 SAT responses and all models are valid).
