### ISSUE TITLE
Soundness bug in LIA with dom-simplify tactic

### ISSUE THREAD

**Issue by numairmansur** [Z3Prover/z3#3052]
Hi,
On the following satisfiable file, I get `unsat` when using `(check-sat-using dom-simplify)`

[1838.zip](https://github.com/Z3Prover/z3/files/4226623/1838.zip)

commit: 00e43b6b88d6a1a111df7ebd762d11ba42eab4ab

**Comment by nunoplopes** [comment]
wow, it's almost as I recognize the tool that generated this file.. :)

**Comment by nunoplopes** [comment]
Reduced test case:
```
(declare-fun A () Bool)
(declare-fun B () Bool)

(assert (not B))
(assert (not (and (not A) B)))
(assert A)

(check-sat-using (then dom-simplify smt))
(check-sat)
```

**Comment by nunoplopes** [comment]
@numairmansur : out of curiosity, where does this file come from?

**Comment by numairmansur** [comment]
This is just a randomly generated file. Not really from an application.

**Comment by nunoplopes** [comment]
> This is just a randomly generated file. Not really from an application.

What? Your random generator could have done my PhD thesis??  Damn, you should have told me sooner :)
(the variable names are extremely similar to the ones my tool generated)
