### ISSUE TITLE
z3 producing unsound model?

### ISSUE THREAD

**Issue by pramodsu** [Z3Prover/z3#3053]
Please see the attached test case
[debug.zip](https://github.com/Z3Prover/z3/files/4229121/debug.zip) in which Z3 seems to producing a model that violates the assertion between lines 192-210. In fact, running the eval command on the exact same expression as the assertion results in false.

**Comment by NikolajBjorner** [comment]
this is most likely fixed compared to the version you are using and current master

**Comment by pramodsu** [comment]
Yes, it is indeed fixed. Thank you.
