### ISSUE TITLE
qe2 z3str3 assertion violation at ../src/qe/qsat.cpp Line: 633

### ISSUE THREAD

**Issue by muchang** [Z3Prover/z3#3056]
Hi,
For this formula:
```
(declare-fun s () String)
(assert (< (str.to.int s) 2))
(check-sat-using (then qe2 smt))
```
Z3  throws out an assertion violation:
```
ASSERTION VIOLATION
File: ../src/qe/qsat.cpp
Line: 633
validate_defs("check_sat")
(C)ontinue, (A)bort, (S)top, (T)hrow exception, Invoke (G)DB
```

OS: Ubuntu 18.04
Commit: 3bb05b5

**Comment by NikolajBjorner** [comment]
This is a bit esoteric: string theories don't admit quantifier elimination so using qe strategies is not really in scope, second z3str3's behavior is best analyzed in isolation. Closing as there are too many other busy-work bugs being filed.
