### ISSUE TITLE
Floating point precision and tolerance in Z3

### ISSUE THREAD

**Issue by bja2019** [Z3Prover/z3#3066]
Hi, 
What precision is used in Z3 to represent the floating numbers ( real ) and tolerance used to compare between two floating numbers ( real ) in Z3 ?  
I have example ( attached  ) and my expectation is that , the example need to produce satisfiability as sat.
[Z3FloatTester.cpp.txt](https://github.com/Z3Prover/z3/files/4236008/Z3FloatTester.cpp.txt)

Also, is there any way to set the precision/tolerance to Z3 for float numbers representation and its comparison ?

My Z3 version : 4.8.4

**Comment by NikolajBjorner** [comment]
When you use a "real" number z3 uses arbitrary precision, so there is no approximation. 
You should check your example on the lastest version of z3 and for easier repros create an SMT2 file from the constraints by printing the solver to a string (or std::cout).

**Comment by NikolajBjorner** [comment]
Based on your program and what it prints (and the assumptions that are not printed):

```
 (declare-fun Size () Real)
(declare-fun SizeBool () Bool)
(declare-fun Model () String)
(declare-fun modelBool () Bool)
(declare-fun myImplicationBool () Bool)
(declare-fun exprToEvaluateBool () Bool)
(assert (= SizeBool
   (or (= Size (/ 10800000000000001.0 1000000000000000.0))
       (= Size (/ 20699999999999999.0 1000000000000000.0)))))
(assert (= modelBool (or (= Model "small") (= Model "big"))))
(assert (= myImplicationBool (=> (= Model "small") (= Size (/ 54.0 5.0)))))
(assert (= exprToEvaluateBool (= Model "small")))
(assert SizeBool)
(assert modelBool)
(assert myImplicationBool)
;(assert exprToEvaluateBool)
(check-sat)
(get-model)
```

Adding exprToEvaluateBool makes the constraints unsat because none of the two possible
values for Size can be 54/5.
