### ISSUE TITLE
Soundness bug in z3str3

### ISSUE THREAD

**Issue by numairmansur** [Z3Prover/z3#3067]
Hi @mtrberzi 
On the latest commit (1aea0d2c8bb177ca9b2c9e04a2a13850f54e36dc), I get the following wrong result on the following satisfiable file: 

[65.zip](https://github.com/Z3Prover/z3/files/4236043/65.zip)

```
sat
sat
unsat
```

I didn't exactly check on which commit was this bug introduced but I think it was introduced recently.

**Comment by numairmansur** [comment]
On commit 321bad2c84c9bb0c58f44d5797bdf993b47b09d4, i correctly get 

```
sat
sat
sat
```

**Comment by mtrberzi** [comment]
You're right that this was introduced recently, setting `smt.str.fixed_length_models=false` prevents the bug so that should narrow it down.

**Comment by mtrberzi** [comment]
This also suddenly starts working if I take out the first `(push 3)` command.

**Comment by mtrberzi** [comment]
Something very strange is going on as calling `(check-sat)` twice in a row with nothing in between produces a `sat` followed by an `unsat`.

**Comment by mtrberzi** [comment]
I'm ultimately not sure which internal data structure was causing the problem, but cleaning them all up between runs is probably not a bad idea, and that fixed this completely. Opened #3818.

**Comment by numairmansur** [comment]
awesome. Thanks !
