### ISSUE TITLE
CHC query with list raises error "uninterpreted 'tail' in <null> [..]"

### ISSUE THREAD

**Issue by bohlender** [Z3Prover/z3#3070]
Both the [latest stable release](https://github.com/Z3Prover/z3/tree/z3-4.8.7) and [today's nightly build](https://github.com/Z3Prover/z3/commit/09523a4bca456aa1d7c4b510abff234586e9f8df) raise an error on the [following instance](https://github.com/Z3Prover/z3/files/4237365/issue3070.txt) except if `fp.engine` is set to `bmc`:
```Lisp
;(set-option :fp.engine bmc) ; raises error if engine is not bmc

(declare-var l (List Int))
(declare-var l! (List Int))
(declare-rel state ((List Int)))

; Initial list: [42, [17, nil]]
(rule (=>
    (= l (insert 42 (insert 17 nil)))
    (state l)
))

; Remove head from list
(rule (=>
    (and
        (state l)
        (not (= l nil))
        (= l! (tail l))
    )
    (state l!)
))

; Any state reachable?
(declare-rel q ())
(rule (=> (state l) q))
(query q)
```
The raised error is:
```Lisp
(error "query failed: Uninterpreted 'tail' in <null>:
state(#0) :- 
 state(#1),
 (not (= (:var 1) nil)),
 (= (:var 0) (tail (:var 1))).
")
unknown
```
I am aware of the fact that `head` and `tail` are partially specified and uninterpreted when applied to `nil` (as in  #2226) but I think this shouldn't be an issue since I'm asserting `(not (= l nil))`.

I am not sure whether this really is a bug or maybe the fixedpoint engine does not support reasoning about lists. However, a similar issue (#2310) seems to have been encountered and fixed already.

**Comment by NikolajBjorner** [comment]
First of all, reasoning about ADTs (lists) is minimal in the Horn clause solver.
Second, the input cannot use accessors that are under-specified on some cases.
For example, tail does not have a fixed interpretation on _nil_. The Horn clause solver isn't prepared for constraints that have _loose_ interpretations. 
Instead of
```
   (= l! (tail l))
```
you can
```
   (= l (cons x! l!))
```
where x! is a fresh variable.

**Comment by NikolajBjorner** [comment]
Here is the full example
```
(set-option :fp.engine bmc)
(declare-var l (List Int))
(declare-var l! (List Int))
(declare-var x! Int)
(declare-rel state ((List Int)))

; Initial list: [42, [17, nil]]
(rule (=>
    (= l (insert 42 (insert 17 nil)))
    (state l)
))

; Remove head from list
(rule (=>
    (and
        (state l)
        (not (= l nil))
        (= (insert x! l!) l)
    )
    (state l!)
))

; Any state reachable?
(declare-rel q ())
(rule (=> (state l) q))
(query q)
```
