### ISSUE TITLE
Build with CMake None build type fails

### ISSUE THREAD

**Issue by nmeum** [Z3Prover/z3#3071]
The Z3 CMake build system includes a check to ensure that the given build type is valid. This checks is performed using a list of available build types:

https://github.com/Z3Prover/z3/blob/17fb07875df5278c64c0ff0e92f7d000fbdfe922/CMakeLists.txt#L133

However, the list is missing the `None` build type which results in builds failing if `cmake(1)` was invoked with `-DCMAKE_BUILD_TYPE=None`. I don't really see why this check is needed in the first place as a similar check is performed by CMake itself [\[1\]](https://github.com/Kitware/CMake/blob/07cfb18f9d29cfc0588ede928846a03ec5599c48/Modules/CMakeInitializeConfigs.cmake#L23), so maybe consider removing this check all together?

**Comment by NikolajBjorner** [comment]
These build types are tested, others are not, so I don't see why it makes sense to open the door for non-tested build modes.

**Comment by nmeum** [comment]
The `None` build type is a common choice for distros as it is the only one which picks up the `CFLAGS`, `CXXFLAGS`, … environment variables instead of overwriting them. We use it at Alpine Linux, while adjusting the Alpine Linux Z3 package I noticed that this build type is not supported.
