### ISSUE TITLE
Z3 Java timeout perhaps not working properly

### ISSUE THREAD

**Issue by Rhovan-cloud** [Z3Prover/z3#3073]
In [1] I made a minimal working example in the web application. In essence I have a current_position which starts at 0 and can only be incremented by 1 each timestep, but at a given time t = t1 it needs to reach a certain value, e.g. 20 or 50.
Unfortunately there is a timeout when I change the the value to e.g. 30 or  higher (for current_position(t) = 20 Z3 still finds a soluion). I implemented the same example in Java, hoping that I could increase the timeout so that Z3 can solve the problem. However, after about 1 minute the solver always returns with model unknown (which, I assume, is due to a timeout). 
I tried omitting (minimize t1), using the tactics qe, qe-light or qe-sat but I get the same result after approx. 1 minute. Is there any way I can get results even for values like 50, or 100?

[1] https://rise4fun.com/Z3/plTzIR

**Comment by NikolajBjorner** [comment]
Optimization hasn't been tuned for quantified formulas, so I don't expect it to work well. It is not a supported scenario at the moment.
