### ISSUE TITLE
Z3 gives an error on a valid formula

### ISSUE THREAD

**Issue by muchang** [Z3Prover/z3#3074]
Hi,
For this formula,
```
(define-fun a ((x Int)) Int 0)
(assert (let ((b a)) true))
(check-sat)
```
Z3 gives an error `(error "line 2 column 17: unknown constant a")`, while cvc4 accpets this formula and gives sat.

OS: Ubuntu 18.04
Commit: c71da17

**Comment by NikolajBjorner** [comment]
This isn't legal SMTLIB2.
