### ISSUE TITLE
Confused when using the Z3-opt to solve multiple objects, when setting the option "set-option :opt.priority box", 

### ISSUE THREAD

**Issue by gingeredder** [Z3Prover/z3#308]
When I use the Z3-opt(ocaml version) to parse the following input SMT2 file:
(declare-const x Int)
(assert (and (>= x 0) (<= x 5)))
(maximize x)
(minimize x)
(set-option :opt.priority box)
(check-sat)
(get-model)

The result is shown like:
x |-> [7:1]
x |-> [7:1]
sat
(model 
  (define-fun x () Int
    0)
)

While I changed the file like this
(declare-const x Real)
(assert (and (>= x 0) (<= x 5)))
(maximize x)
(minimize x)

(set-option :opt.priority box)
(check-sat)
(get-model)

The result is like:
x |-> 5
x |-> 0
sat
(model 
  (define-fun b!2 () Bool
    true)
  (define-fun x () Real
    5.0)
)

My question is that : 
1, What does the first result "x |-> [7:1]" mean?
2, Why does the Z3-opt give two different results for these two files?(The difference between these two files is the type of variable "x" (Int vs. Real))

**Comment by NikolajBjorner** [comment]
it wasn't catching that multiple objectives could be the same term and also correspond to maxsat.

**Comment by gingeredder** [comment]
Thanks for your work.
By Jiahong Jiang
