### ISSUE TITLE
StringVal(s).as_string() does not round-trip in Python API

### ISSUE THREAD

**Issue by pschanely** [Z3Prover/z3#3080]
Should `StringVal(s).as_string()` produce the same value as `s`?
If so, it looks like we don't have our escaping quite correct yet:
```
>>> from z3 import *
>>> s='hi\x00bye'
>>> len(s)
6
>>> StringVal(s).as_string()
'hi\\x00bye'
>>> len(StringVal(s).as_string())
9
```
(python is at 3.8.0 and z3 is at HEAD ~2020-2-22)

#2286 and #2039  appear to be related but have both been resolved.

**Comment by NikolajBjorner** [comment]
The python bindings should most likely be using Z3_get_lstring instead of Z3_get_string here
https://github.com/Z3Prover/z3/blob/b68efe44afe486a00640e84ec9b78d0a73e30997/src/api/python/z3/z3.py#L10038

The caveat is that Z3_get_lstring isn't quite ready for prime time: it returns a Z3_string object, which is marshalled by Python (and other APIs) to a string (and not a char* buffer). The directives are present in the "z3/scripts/mk_genfile_common.py" build script. Help updating this part would be highly appreciated.

**Comment by pschanely** [comment]
Those pointers really help - thanks! I understand at least some of what's going on and will spend a few minutes poking at it.

**Comment by pschanely** [comment]
Okay! I've made some progress. With some work, I can get python to bind to Z3_get_lstring. My current patch looks like this:
```
diff --git a/scripts/update_api.py b/scripts/update_api.py
index 94cabf72b..316732d7d 100755
--- a/scripts/update_api.py
+++ b/scripts/update_api.py
@@ -317,6 +317,8 @@ Unwrapped = [ 'Z3_del_context', 'Z3_get_error_code' ]
 
 def mk_py_wrappers():
     core_py.write("""
+_lib.Z3_get_lstring.restype = ctypes.POINTER(ctypes.c_char)
+
 class Elementaries:
   def __init__(self, f):
     self.f = f
diff --git a/src/api/python/z3/z3.py b/src/api/python/z3/z3.py
index 64b9b834f..3d12dbace 100644
--- a/src/api/python/z3/z3.py
+++ b/src/api/python/z3/z3.py
@@ -10018,7 +10018,10 @@ class SeqRef(ExprRef):
     def as_string(self):
         """Return a string representation of sequence expression."""
         if self.is_string_value():
-           return Z3_get_string(self.ctx_ref(), self.as_ast())
+            string_length = ctypes.c_uint()
+            chars = Z3_get_lstring_bytes(self.ctx_ref(), self.as_ast(), byref(string_length))
+            return string_at(chars, size=string_length.value).decode('ascii')
         return Z3_ast_to_string(self.ctx_ref(), self.as_ast())
 
     def __le__(self, other):
```
Note the horrible thing I do in `update_api.py` where I overwrite the restype manually just for this one function.

Anyway, with this patch, I can get things to work on the v4.8.6 tag, but not at head:
```
# at v4.8.6
>>> len(StringVal('hi\x00bye').as_string())
6

# at HEAD
>>> len(StringVal('hi\x00bye').as_string())
2
>>> simplify(Length(StringVal('hi\x00bye'))) # (internally, StringVal is storing the right stuff)
6
```

It seem as though, in both versions, Z3_get_lstring ends up calling `seq_util::str::is_string` which initializes a `zstring` from only a char* (a symbol's "bare_str()"). Perhaps something has changed in semi-recent history with our expectations about how that char* escapes characters? Anyway, at this point, I am in deep enough that a few hints from someone who knows more would be pretty valuable. :)

**Comment by NikolajBjorner** [comment]
Thanks, appreciated.
The internal code wasn't doing the right thing.
I have updated the API declarations to have it return the right type. 
Some caveats getting there: Apparently c_char_p does not work, but POINTER(c_char) works (which is what your version had).

**Comment by pschanely** [comment]
Thank you; I've confirmed that this works for me! Glad that I could be at least a little helpful in the process.

This will mean a lot for [CrossHair](https://github.com/pschanely/CrossHair), and I am especially excited about the potential for unicode support I noticed in the [planned features](https://github.com/Z3Prover/z3/blob/master/RELEASE_NOTES)!
