### ISSUE TITLE
rise4fun uses a very old version of Z3 with broken optmisation

### ISSUE THREAD

**Issue by tari3x** [Z3Prover/z3#3084]
Not sure if this is the right place to report rise4fun issues. This output of rise4fun seems very broken and is not consistent with version 4.8.5 (which seems correct).

```
(declare-const x1 Real)
(declare-const y2 Real)
(declare-const x2 Real)
(assert (>= y2 0))
(assert (<= y2 1))
(assert (>= x1 -0.0940283))
(assert (>= x2 (* 0.1 (- y2))))
(minimize x1)
(check-sat)
(get-model)
(get-objectives)
```

The output I get is 

```
sat
(model 
  (define-fun x2 () Real
    0.0)
  (define-fun x1 () Real
    0.0)
  (define-fun y2 () Real
    0.0)
)
(objectives
 (x1 (* (- 1) oo))
)
```

Changing -0.0940283 in the model to -0.094028 changes the output to be correct.

I wonder if this is related to 
https://github.com/Z3Prover/z3/issues/1326
https://github.com/Z3Prover/z3/issues/1645

**Comment by NikolajBjorner** [comment]
I will not be updating the rise4fun version soon. It will at some point be updated, but it is not something that is a priority. It uses a version of Z3 which is stable with respect to many common features. For optimization and other non-basic features download the latest releases or nightly builds.
