### ISSUE TITLE
Oddly complicated model out of Z3 with seemingly innocent string constraints in it

### ISSUE THREAD

**Issue by copumpkin** [Z3Prover/z3#3085]
I've run this program on both master as of yesterday, and 4.8.7:

```
(declare-const |arnvar| String)
(declare-const |arnvar_exists| Bool)
(declare-const resource String)

; If you take this bit out of the two assertions below, you get a nice segfault on automata
;   (re.++ (str.to.re "us-") (re.* re.allchar))

(declare-const condition0 Bool)
(assert
  (= condition0
    (and |arnvar_exists|
      (str.in.re |arnvar|
        (re.++
          (str.to.re "arn:aws:")
          (re.inter (re.* (re.union (re.range "a" "z") (re.range "0" "9") (str.to.re "-"))) (str.to.re "lambda"))
          (str.to.re ":")
          (re.inter (re.union (str.to.re "") (str.to.re "us-west-2")) (re.++ (str.to.re "us-") (re.* re.allchar)))
          (str.to.re ":")
          (re.inter (re.union (str.to.re "") (re.loop (re.range "0" "9") 12 12) (str.to.re "aws") (str.to.re "cloudfront")) (str.to.re "012345678901"))
          (str.to.re ":")
          (re.++ (str.to.re "function") (re.* re.allchar)))))))

(declare-const useless Bool) ; This looks useless but the weird behavior stops if you take it out
(declare-const condition1 Bool)
(assert
  (= condition1
    (and |arnvar_exists|
      (str.in.re |arnvar|
        (re.++
          (str.to.re "arn:aws:")
          (re.inter (re.* (re.union (re.range "a" "z") (re.range "0" "9") (str.to.re "-"))) (str.to.re "lambda"))
          (str.to.re ":")
          (re.inter (re.union (str.to.re "") (str.to.re "us-west-2")) (re.++ (str.to.re "us-") (re.* re.allchar)))
          (str.to.re ":")
          (re.inter (re.union (str.to.re "") (re.loop (re.range "0" "9") 12 12) (str.to.re "aws") (str.to.re "cloudfront")) (str.to.re "012345678901"))
          (str.to.re ":function"))))))

(assert condition0)
(assert (not (and condition1 useless)))

(check-sat)
(get-model)
```

I run with `/z3 -in -smt2 -T:24 smt.string_solver=seq < ~/z3bug-reduced.smtlib ` and get the following output:

```
sat
(model 
  (define-fun arnvar () String
    "arn:aws:lambda:us-west-2:012345678901:function")
  (define-fun useless () Bool
    false)
  (define-fun condition0 () Bool
    true)
  (define-fun condition1 () Bool
    (let ((a!1 (re.inter (re.* (re.union (re.range "a" "z")
                                     (re.range "0" "9")
                                     (str.to.re "-")))
                     (str.to.re "lambda")))
      (a!2 (re.inter (re.union (str.to.re "")
                               ((_ re.loop 12 12) (re.range "0" "9"))
                               (str.to.re "aws")
                               (str.to.re "cloudfront"))
                     (str.to.re "012345678901"))))
(let ((a!3 (re.++ (str.to.re "arn:aws:")
                  a!1
                  (str.to.re ":")
                  (re.inter (re.union (str.to.re "") (str.to.re "us-west-2"))
                            (re.++ (str.to.re "us-") re.all))
                  (str.to.re ":")
                  a!2
                  (str.to.re ":function"))))
  (str.in.re "arn:aws:lambda:us-west-2:012345678901:function" a!3))))
  (define-fun arnvar_exists () Bool
    true)
  (define-fun resource () String
    "")
)
```

Note that there's nothing terribly _wrong_ with the output (other than `condition1`'s truth being hard to determine), as the problem is indeed satisfiable and the assignments are reasonable, but the fresh variables and `str.in.re` assertion at the top level is surprising to me, given that there are no unknowns and I'd expect that to all get simplified away.

For additional solver datapoints, `cvc4 --lang smt2.5 --output-lang z3str -m --strings-exp --tlimit=24000 --no-re-elim` has no issue with this problem, but z3 with `smt.string_solver=z3str3` segfaults with no output. The last z3 I tried with, 4.8.5, didn't exhibit the same behavior on this program.

**Comment by NikolajBjorner** [comment]
Notice that a!1 and a!2 and a!3 are not fresh variables, they are let bound definitions.
The model generator, in this case, does not perform constant folding of the definition for condition1. 
You can evaluate an RE membership by simplifying the expression (call eval or evaluate from SMTLIB2).

**Comment by copumpkin** [comment]
Ah interesting, so would you say this is deliberate? I've just never seen anything like it, and it didn't happen in previous versions, so I thought it might be a regression

**Comment by copumpkin** [comment]
Oddly enough, even asking for `(eval condition1)` against that program doesn't seem to reduce it. Is there a way to get it into a normal form?

**Comment by copumpkin** [comment]
I've tried a few (random, to me) strategies like `(apply propagate-values)` and such, but nothing I've tried has been able to get those let-bound variables substituted into the regexp to allow the `str.in.re` to reduce to a flat boolean. Is there something I'm missing here or do I need to write my own evaluator for these expressions?

**Comment by varming** [comment]
@NikolajBjorner what is the reasoning behind the non-normalized model? As mentioned above, `(eval condition1)` does not reduce to a boolean value:

```
(eval condition1)    
(let ((a!1 (re.inter (re.* (re.union (re.range "a" "z")
                                     (re.range "0" "9")
                                     (str.to.re "-")))
                     (str.to.re "lambda")))
      (a!2 (re.inter (re.union (str.to.re "")
                               ((_ re.loop 12 12) (re.range "0" "9"))
                               (str.to.re "aws")
                               (str.to.re "cloudfront"))
                     (str.to.re "012345678901"))))
(let ((a!3 (re.++ (str.to.re "arn:aws:")
                  a!1
                  (str.to.re ":")
                  (re.inter (re.union (str.to.re "") (str.to.re "us-west-2"))
                            (re.++ (str.to.re "us-") re.all))
                  (str.to.re ":")
                  a!2
                  (str.to.re ":function"))))
  (str.in.re "arn:aws:lambda:us-west-2:012345678901:function" a!3)))

```

How would I figure out if condition1 is true or false in this model?

**Comment by NikolajBjorner** [comment]
The term contains intersection. Z3 does not fully evaluate these even if membership terms are all ground values. Seq_rewriter would be the place to enhance. Will revisit this functionality around june, july timeframe. 

The pre-processor detects that condition1 can be substituted for the regex membership constraint, so it eliminates condition1 and instead uses the membership constraint.
The poor woman/man's approach to bypass the pre-processor is to push a "(push)" before the check-sat.

Currently, Z3's simplifier first generates a symbolic automaton and then checks membership.
Instead it can just check membership one character at a time based on the regex. 
This is similar to regex packages. Your backend is of course also free to use a regex package to simplify the expression further, and then Z3 is also open source.

**Comment by NikolajBjorner** [comment]
the simplifier now reduces these cases
