### ISSUE TITLE
Debug branch: incorrect answer on QF_LIRA formula

### ISSUE THREAD

**Issue by muchang** [Z3Prover/z3#3098]
Hi,
For this formula,
```
(declare-fun a () Real)
(assert (= (to_int a) 3))
(assert (= (to_int (/ 1 a)) 0))
(check-sat)
```
z3 debug branch gives unsat while z3 master branch gives sat.

OS: Ubuntu 18.04
Commit: caa118c

**Comment by NikolajBjorner** [comment]
maybe fixed, but takes forever now

**Comment by levnach** [comment]
Closed to improve the tracking.
