### ISSUE TITLE
Z3 sequence solver reports UNSAT on SAT instance

### ISSUE THREAD

**Issue by mtrberzi** [Z3Prover/z3#3100]
We found a case during testing of Z3str3 that exposes a bug in the sequence solver where it returns an incorrect answer:

```
(set-logic QF_S)
(declare-fun E () String)
(assert (= (str.++  E "aa" E "ab" E)  (str.++  "a" E E "aabaa") ))
(check-sat)
(get-model)
```

On the latest commit (e8f7a082897a5a32f4b4c000521624fff006193c) running with `smt.string_solver=seq` returns `unsat`. However, running with `smt.string_solver=z3str3` produces a SAT answer:

```
sat
(model 
  (define-fun E () String
    "aa")
)
```

This model can be double-checked by inspection.

**Comment by NikolajBjorner** [comment]
@trinhmt - the code that collects indices for ternary branch case seems incorrect
