### ISSUE TITLE
Incorrect model on QF_S formula 2

### ISSUE THREAD

**Issue by muchang** [Z3Prover/z3#3105]
Hi,
For this formula:
```
(declare-fun a () String)
(declare-fun b () String)
(declare-fun c () String)
(assert (distinct (str.substr a 3 (str.len b)) ""))
(assert (distinct
         (ite (= (str.len (str.substr (str.replace a b "") 0 (- (str.len c)))) 1) 0 2)
         (ite (= (str.at (str.replace a b "") 2) "") 1 2)))
(check-sat)
(get-model)
```
Z3  gives an invalid model:
```
(model 
  (define-fun b () String
    "\x00")
  (define-fun a () String
    "\x00\x00\x00\x00\x00")
  (define-fun c () String
    "\x00")
)
```
if I feed this model to the formula, Z3 reports unsat.

OS: Ubuntu 18.04
Commit: ad6062c

**Comment by NikolajBjorner** [comment]
this is not in z3str3, it is in seq. z3str3 works well on this

**Comment by NikolajBjorner** [comment]
@muchang could you append this to one of the other bugs that use strings / substr / replace.
They are almost for sure duplicates. So unless there is evidence there is too much noise to have separate issues.

**Comment by muchang** [comment]
Sure, just appended.
