### ISSUE TITLE
segfault with fixpoints

### ISSUE THREAD

**Issue by seanmcl** [Z3Prover/z3#311]
The following program segfaults:

    (define-sort Bv32 () (_ BitVec 32))
    (declare-datatypes () ((LIP Lip1 Lip2)))
    (declare-datatypes () ((NID I1 I3)))
    (declare-datatypes () ((SID S1_1 S2_1 S2_2 S3_1)))
    (declare-datatypes () ((VID V1 V2 V3)))

    (declare-var In NID)
    (declare-var In1 NID)
    (declare-var In2 NID)
    (declare-var LIP LIP)
    (declare-var LIP1 LIP)
    (declare-var LIP2 LIP)
    (declare-var LIP3 LIP)
    (declare-var Pi Bv32)
    (declare-var S SID)
    (declare-var Vp VID)
    (declare-var Vp1 VID)
    (declare-var Vp2 VID)
    (declare-var _Bool-30 Bool)
    (declare-var _Bv32-31 Bv32)
    (declare-var _Bv32-32 Bv32)

    (declare-rel lIP (LIP VID Bv32))
    (declare-rel nI (NID SID  ))
    (declare-rel nIHLI (NID LIP))
    (declare-rel nIHV (NID VID))
    (declare-rel nIO (NID))
    (declare-rel rNI (NID NID))
    (declare-rel rP (LIP LIP))
    (declare-rel s (SID VID))
    (declare-rel sHV (SID VID))
    (declare-rel sO (SID))
    (declare-rel v (VID))
    (declare-rel vO (VID))

    (rule (nI I1 S1_1 ))
    (rule (nI I3 S3_1 ))
    (rule (s S1_1 V1 ))
    (rule (s S2_2 V2 ))
    (rule (s S3_1 V3 ))
    (rule (v V1))
    (rule (v V3))
    (rule (lIP Lip1 V1 #x0A000001))
    (rule (lIP Lip2 V3 #x0A020001))

    (rule (=> (nIHV In Vp) (lIP LIP Vp Pi)))
    (rule (=> (and (nIHV In Vp) (lIP LIP Vp Pi)) (nIHLI In LIP)))
    (rule (=> (and (nI In S) (nIO In) (sHV S Vp)) (nIHV In Vp)))
    (rule (=> (nI In S) (nIO In)))
    (rule (=> (and (nIHLI In1 LIP1) (nIHLI In2 LIP2) (rP LIP1 LIP2)) (rNI In1 In2)))
    (rule (=> (rP LIP2 LIP1) (rP LIP1 LIP2)))
    (rule (=> (and (lIP LIP1 Vp _Bv32-31) (lIP LIP2 Vp _Bv32-32)) (rP LIP1 LIP2)))
    (rule (=> (and (s S Vp) (sO S) (vO Vp)) (sHV S Vp)))
    (rule (=> (and (s S Vp) (vO Vp)) (sO S)))
    (rule (=> (v Vp) (vO Vp)))

    (query (rNI I1 I3) :print-certificate true)
        
Running z3 on OSX gives

    $ z3 /tmp/db.smt2
    sat
    [1]    45526 segmentation fault  z3 /tmp/db.smt2

**Comment by NikolajBjorner** [comment]
thanks

**Comment by seanmcl** [comment]
Thanks for the quick fix!
