### ISSUE TITLE
`Rule contains infinite sorts` error

### ISSUE THREAD

**Issue by leonardoalt** [Z3Prover/z3#3113]
```
(declare-rel f ((Array Int Int)))
(declare-var a (Array Int Int))
(rule (f a))
(query f)
```
I expected this to be fine, but it yields:
```
(error "query failed: Rule contains infinite sorts in rule <null>:
f(#0).
")
unknown
```

If I change it to
```
(declare-rel f ((Array Int Int) Int))
(declare-var a (Array Int Int))
(rule (f a 2))
(query f)
```
it's fine and says `sat`.

Am I missing something from the syntax?

**Comment by NikolajBjorner** [comment]
I think this is addressed since the build you use:
the auto-detector for which engine to use doesn't realize that arrays of integers are not finite domain.
The current head is happy with the sample. You can work around this by specifying fp.engine=spacer

**Comment by leonardoalt** [comment]
Ok, sounds good. Thanks!
