### ISSUE TITLE
Debug branch: Incorrect answer on LIRA formula

### ISSUE THREAD

**Issue by muchang** [Z3Prover/z3#3128]
Hi,
For this formula:
```
(assert (exists ((a Int) (b Int)) (and (> b 1) (> a (/ 1 b)))))
(check-sat)
```
Z3 debug branch  incorrectly gives unsat, while this formula should be sat.
If we change (> b 1) to (> b 0), Z3 debug branch correctly answers sat,

OS: Ubuntu 18.04
Commit: 9f16fee

**Comment by NikolajBjorner** [comment]
Note: Not really LIA. it uses real division.

**Comment by muchang** [comment]
Thanks, Nikolaj. I just updated the title.

**Comment by levnach** [comment]
It works now.
