### ISSUE TITLE
Debug branch, emonics: Assertion violation at ../src/math/lp/emonics.cpp Line: 241

### ISSUE THREAD

**Issue by muchang** [Z3Prover/z3#3136]
Hi,
For this formula:
```
(declare-fun a () Real)
(declare-fun b () Real)
(declare-fun c () Real)
(declare-fun d () Real)
(declare-fun e () Real)
(declare-fun f () Real)
(declare-fun g () Real)
(declare-fun h () Real)
(declare-fun i () Real)
(declare-fun l () Real)
(declare-fun m () Real)
(assert
 (not (exists ((j Real))
       (or (and (distinct (+ 9 e) 2.0)
            (< (* f (/ 0 (* 2.0 (+ 6 b )))) 0)
            (distinct c 2.0) (< 0 l))
        (<= 0.0 (/ b (- j)) a g)
        (= 0.0 i)))))
(assert
 (not (exists ((k Real))
   (and (< 0.0 (/ 0 d m)) (< 0.0 h)))))
(check-sat)
```
Z3 debug branch  throws out an assertion violation:
```
ASSERTION VIOLATION
File: ../src/math/lp/emonics.cpp
Line: 241
c == it->second
(C)ontinue, (A)bort, (S)top, (T)hrow exception, Invoke (G)DB
```

OS: Ubuntu 18.04
Commit: 097e6e4

**Comment by levnach** [comment]
I cannot reproduce it, but I am seeing 
~/dev/z3/build/debug/z3  /home/lev/Dropbox/smts/3136.smt2  smt.random_seed=2
ASSERTION VIOLATION
File: ../../src/math/lp/emonics.cpp
Line: 291
m_ve.is_root(w)
(C)ontinue, (A)bort, (S)top, (T)hrow exception, Invoke (G)DB
https://github.com/NikolajBjorner, why do we assume that each variable in emonics::add() is a root variable? The original variables are copied to mon_eq::m_vs, but the corresponding root variables are pushed to monic::m_rvars . I tried to remove this assert but it opened a can of worms.

**Comment by zhendongsu** [comment]
I can still reproduce the originally reported assertion violation on the latest debug branch: 

```
[560] % z3debug bug3136.smt2 
ASSERTION VIOLATION
File: ../src/math/lp/emonics.cpp
Line: 241
c == it->second
(C)ontinue, (A)bort, (S)top, (T)hrow exception, Invoke (G)DB
a
[561] % 
```

**Comment by NikolajBjorner** [comment]
same issue as #3186

**Comment by NikolajBjorner** [comment]
emons was rewritten, this bug is stale
