### ISSUE TITLE
segfaults with java api

### ISSUE THREAD

**Issue by seanmcl** [Z3Prover/z3#314]
I'm getting frequent core dumps from the Java API.  It's been difficult to track down the issue, and I'm still trying to isolate a small example.  Stepping through the code in a debugger usually segfaults the JVM with this line

C  [libz3.dylib+0xa04a71]  operator<<(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, mk_ismt2_pp const&)+0x21
#

I realize this is a lame bug report, and mk_ismt2_pp is just a fancy pretty printer, but I wanted to just throw this out there in case anyone else has had this issue.  I'll reply in the thread as/if I track down a small example.

**Comment by seanmcl** [comment]
This is too vague.  I'll open another when I have a cogent argument.

**Comment by NikolajBjorner** [comment]
Probably the expression is null and the code around the print statement does not take this into account.

**Comment by seanmcl** [comment]
Are you saying this is user error or z3 bug?  I assume I'd get a NullPointerException from Java if I had a null Java Expr, and I don't see a classifier for null, e.g. 'isNull' or whatever in Expr.java.

**Comment by NikolajBjorner** [comment]
You should retrieve the stack trace from Z3 downwards. Then also get the value of expression that is passed to mk_ismt2_pp. I bet it is 0. Z3 should not crash ungracefully. If supplied with incorrect arguments it should throw an exception. E.g., some argument validation is expected.
