### ISSUE TITLE
sequence solver produces invalid model

### ISSUE THREAD

**Issue by mtrberzi** [Z3Prover/z3#3147]
On the latest commit (6cbcd13224728ea7a6ec6bf01d1766d6845fc5c8) the sequence solver answers the following instance with an invalid model:

```
(declare-fun s () String)

(assert (and (and (and (and (and (and (and (and (and (and (and (not (not (= (ite (= (str.at s 2) (str.at s (- (- (- (str.len s) 1) 1) 1))) 1 0) 0))) (not (= (ite (>= (- (- (- (str.len s) 1) 1) 1) 2) 1 0) 0))) (not (= (ite (>= (- (- (- (str.len s) 1) 1) 1) 0) 1 0) 0))) (not (= (ite (> (str.len s) 2) 1 0) 0))) (not (= (ite (= (str.at s 1) (str.at s (- (- (str.len s) 1) 1))) 1 0) 0))) (not (= (ite (>= (- (- (str.len s) 1) 1) 1) 1 0) 0))) (not (= (ite (>= (- (- (str.len s) 1) 1) 0) 1 0) 0))) (not (= (ite (> (str.len s) 1) 1 0) 0))) (not (= (ite (= (str.at s 0) (str.at s (- (str.len s) 1))) 1 0) 0))) (not (= (ite (>= (- (str.len s) 1) 0) 1 0) 0))) (not (= (ite (>= (- (str.len s) 1) 0) 1 0) 0))) (not (= (ite (> (str.len s) 0) 1 0) 0))))

(check-sat)
(get-model)
```

output:
```
exclude (str.at s 2) = (str.at s (+ (- 3) (str.len s))) = "\x00"
sat
(error "line 6 column 10: an invalid model was generated")
(model 
  (define-fun s () String
    "\x00\x00\x00\x00\x00\x00")
)
```

Not sure what is producing the "exclude" line with the constraint. This is running on the release build with `smt.string_solver=seq model_validate=true`. 

CVC4 answers SAT with a valid model for this case; Z3str3 returns UNKNOWN.

I have about 47 cases where the sequence solver is returning invalid models on the latest commit. Instead of opening 47 issues, I'll check them again once this is fixed and report any outstanding bugs.

**Comment by zhendongsu** [comment]
Perhaps it is related to, if not the same as, the several open invalid model issues for the sequence solver?   See https://github.com/Z3Prover/z3/issues/3062.
