### ISSUE TITLE
The maximum number of multiple objects for Z3-opt

### ISSUE THREAD

**Issue by gingeredder** [Z3Prover/z3#315]
Thanks for your reply in #312 .
The new problem comes when using Z3-opt(OCaml version) in my workspace.
I found that if there are too many objects( about 120 object expression), the Z3-opt seems not to terminate for a very long time(at least half an hour).
1, So I want to know what is the upper bound of number of objects for Z3-opt?
2, Why does the Z3-opt seem not to terminate for the input SMT-formula with multiple objects(in my experiment, the number is about 120)?
By Jiahong Jiang

**Comment by gingeredder** [comment]
Maybe the constraint expression is also too big and complicated. But I don't know how to evaluate the size of constraint expression.

**Comment by NikolajBjorner** [comment]
There is no actionable information in this report. The usual scale limitations apply for constraint solving.
