### ISSUE TITLE
Z3 cannot be dynamically linked by coq

### ISSUE THREAD

**Issue by douglastt** [Z3Prover/z3#3159]
I am current writing a coq plugin project, which uses z3 as an external decision procedure for proving some arithmetic properties. However, `z3ml.cmxs` cannot be dynamically loaded by coq.

while I wrote the following two lines in a coq source file, and tried to compile it,
```coq
Declare ML Module "zarith".
Declare ML Module "z3ml".
``` 
I got 
```
error loading shared library: /home/xxx/.opam/ocaml-base-compiler.4.05.0/lib/z3/z3ml.cmxs: undefined symbol: _ZTVN10__cxxabiv117__class_type_infoE
```
The coqc told me that the error line was `Declare ML Module "z3ml".`.
It seems that `z3ml.cmxs` does not link with `libstdc++.so` in the correct way.

**Comment by NikolajBjorner** [comment]
I can't support third party interaction scenarios.
Z3 now builds directly with every check-in (tested on ubuntu18.4) thanks to Simon, and there is configuration for opam distributions. Both build z3 by linking it statically with the resulting ocaml bindings. Whether that relates in any way to your scenario is unknown to me. You will have to consult with how ocaml works.
