### ISSUE TITLE
Bug in the Hilbert Basis computation

### ISSUE THREAD

**Issue by AndiDraghici** [Z3Prover/z3#3160]
On the x3-x5 = 0; 3x1+5x2-3x4 = 0, I get an incomplete basis. The basis returned is [[0,0,1,0,1] , [1,0,0,1,0]]. However, this is not complete since I can not construct the solution x1 = 0, x2 = 3, x3 = 0, x4 = 5, x5 = 0.

**Comment by NikolajBjorner** [comment]
You will have to find the bug on your own. 
This feature isn't used by external functionality that matters so I cannot debug it.
