### ISSUE TITLE
Debug branch: Soundness bug QF_NRA

### ISSUE THREAD

**Issue by wintered** [Z3Prover/z3#3164]
Hi,
For this formula:
```
(declare-fun a () Real)
(assert (= (* 40 a a) 30))
(push)
(check-sat)
```
Z3  incorrectly gives unsat, while this formula should be sat.

OS: Ubuntu 18.04
Commit: 6b0e599

**Comment by rainoftime** [comment]
In my PC (Ubuntu 16.04), z3 commit 6b0e599 gives sat.

**Comment by levnach** [comment]
It works in master branch, but does not finish in debug branch.
