### ISSUE TITLE
Proposal for finite sorts in smt2 fixedpoint syntax extensions

### ISSUE THREAD

**Issue by seanmcl** [Z3Prover/z3#317]
I propose to have the Z3 fixedpoint engine support finite sorts (enums) in the SMT-LIB2 syntax, in addition to the bddbddb syntax.  Currently, we need to encode enums as bitvector constants.  This makes reading and writing the files unintuitive, and makes interpreting the answers involve an extra step for the user, where they must maintain their own mapping of enum name to bitvector constant.

According to the [tutorial](http://rise4fun.com/Z3/tutorialcontent/fixedpoints), the fixedpoint extensions to SMT-LIB2 include declare-{var,rule}, rule, query, and set-predicate-representation.  The simple

    (declare-datatypes T () (CONSTRUCTOR*))

doesn't work.  The declare-datatypes declaration is rather complicated, involving multiple types, constructors with different arities, and type parameters.  Moreover, it doesn't seem obvious how to tell when the user wants to use it as a finite type in a datalog program.  Thus, I think it would be prudent to have a completely separate concept for datalog finite types.  

How about this?

    (declare-finite-sort T (CONSTRUCTOR*))

I figure this would translate to the `datalog::context::symbol_sort_domain`.

**Comment by NikolajBjorner** [comment]
Datatype declarations will very likely change with SMT-LIB3. See smtlib website for formats.
