### ISSUE TITLE
Bug in AST printer from Java API

### ISSUE THREAD

**Issue by seanmcl** [Z3Prover/z3#319]
The pretty printer seems to be printing function arguments backwards.  The following program creates 
the expression `(exists (X Y Z) (f X Y Z))`, but prints as `(exists (X Y Z) (f Z Y X))`.  Calling getBody gives the correct order:  `(f (:var 0) (:var 1) (:var 2))`, and getBoundVariableNames gives X Y Z in the correct order.  So no real harm done.  Just very confusing.

    import com.microsoft.z3._

    class Z3PrinterBug  {
        val ctx = new Context
    
        val query = {
          val s: Sort = ctx.getBoolSort
          val f = ctx.mkFuncDecl("f", Array(s, s, s), s)
          val q = ctx.mkExists(Array(s, s, s), Array(
            ctx.mkSymbol("X"),
            ctx.mkSymbol("Y"),
            ctx.mkSymbol("Z")),
            ctx.mkApp(f,
              ctx.mkBound(0, s),
              ctx.mkBound(1, s),
              ctx.mkBound(2, s)), 0, null, null, null, null)
          val str = q.toString
        }
      }

**Comment by wintersteiger** [comment]
This is not a bug, these arguments are supposed to be reversed, or in other words, the de-Bruijn index of the last variable is 0. See e.g., the comments in the C-API for [mk_bound](http://z3prover.github.io/api/html/group__capi.html#gaa80db40fee2eb0124922726e1db97b43) and [mk_forall](http://z3prover.github.io/api/html/group__capi.html#gaf6c853afacbef8aedd78098d6c8c8b97). 

I'll make sure those comments get copied over to the other APIs.

**Comment by seanmcl** [comment]
Thanks.
