### ISSUE TITLE
Adding a rule reduces the cover of a predicate

### ISSUE THREAD

**Issue by seanmcl** [Z3Prover/z3#320]
In this program, the query returns a bunch of results for the query when the final rule is commented out, but when the rule is there, the query returns a single result.   Note that the final rule doesn't even mention the predicate in question.

    (define-sort Bv8 () (_ BitVec 8))
    (define-sort Bv32 () (_ BitVec 32))
    (declare-rel a (Bv8 Bv8 Bv32))

    (rule (a #x00 #x00 #x0A000001))
    (rule (a #x01 #x00 #x0A000002))
    (rule (a #x02 #x01 #x0A000101))
    (rule (a #x03 #x01 #x0A000102))
    (rule (a #x04 #x01 #x0A010001))
    (rule (a #x05 #x01 #x0A010002))
    (rule (a #x06 #x01 #x0A010101))
    (rule (a #x07 #x01 #x0A010102))
    (rule (a #x08 #x02 #x0A020001))

    (declare-rel b (Bv8  Bv8 Bv8 Bv8 Bool))
    (declare-rel d (Bv8))
    (declare-rel e (Bv8))

    (rule (forall ((A Bv8) (B Bv8) (C Bv8) (D Bool))
                  (=> (and
                       (b A B C #x00 D)
                       (d C))
                      (e A))))

    (query (exists ((X Bv8) (Y Bv8) (Z Bv32)) (a X Y Z)) :print-answer true)
        

Without last rule:

    $ z3 z3/bug-example/bug.smt2
    sat
    (or (and (= X!1 #x00) (= X!2 #x00) (= X!3 #x0a000001))
        (and (= X!1 #x01) (= X!2 #x00) (= X!3 #x0a000002))
        (and (= X!1 #x02) (= X!2 #x01) (= X!3 #x0a000101))
        (and (= X!1 #x03) (= X!2 #x01) (= X!3 #x0a000102))
        (and (= X!1 #x04) (= X!2 #x01) (= X!3 #x0a010001))
        (and (= X!1 #x05) (= X!2 #x01) (= X!3 #x0a010002))
        (and (= X!1 #x06) (= X!2 #x01) (= X!3 #x0a010101))
        (and (= X!1 #x07) (= X!2 #x01) (= X!3 #x0a010102))
        (and (= X!1 #x08) (= X!2 #x02) (= X!3 #x0a020001)))

With the rule:

    $ z3 z3/bug-example/bug.smt2
    sat
    (a #x08 #x02 #x0a020001)

**Comment by seanmcl** [comment]
This behavior goes away when I add

    (set-option :fixedpoint.engine datalog)

I originally concocted this example from the same behavior in the Java API.

**Comment by NikolajBjorner** [comment]
Only datalog engine gives all answers. Other supply single answers

**Comment by seanmcl** [comment]
How can I force the API to use the datalog engine?  I assume 'query' since it's datalog only, would use the correct engine.

**Comment by NikolajBjorner** [comment]
Set parameter option

**Comment by seanmcl** [comment]
I see, there are different engines even within the datalog module.  Thanks.
