### ISSUE TITLE
Assertion violation for QF_FP formula at model_evaluator.cpp:118

### ISSUE THREAD

**Issue by rainoftime** [Z3Prover/z3#3200]
Hi,
For this formula:
[modelevaluator118.txt](https://github.com/Z3Prover/z3/files/4301749/modelevaluator118.txt)

Z3 throws out an assertion violation:
~~~~
ASSERTION VIOLATION
File: ../src/model/model_evaluator.cpp
Line: 118
fi->get_arity() == num
(C)ontinue, (A)bort, (S)top, (T)hrow exception, Invoke (G)DB
~~~~

OS: Ubuntu 16.04
Commit: 7d976e4

**Comment by NikolajBjorner** [comment]
QF_FP does not handle reals, seems not valuable to fix
