### ISSUE TITLE
Debug branch: Incorrect answer on UFLIA formua

### ISSUE THREAD

**Issue by muchang** [Z3Prover/z3#3212]
Hi,
For this formula:
```
(declare-fun a () Int)
(declare-fun b () Int)
(declare-fun c (Int) Bool)
(assert (> b 0))
(assert (= (+ a b) 1))
(push)
(assert (c (div (- 1) (+ b 1))))
(check-sat)
```
Z3 debug branch  incorrectly gives unsat, while this formula should be sat.

OS: Ubuntu 18.04
Commit: f088932

**Comment by levnach** [comment]
Fixed in https://github.com/Z3Prover/z3/commit/34a1cd1e358ec075bda1c9bb4a49819b2b9094a4
