### ISSUE TITLE
Different results Linux vs OSX with rlimit

### ISSUE THREAD

**Issue by leonardoalt** [Z3Prover/z3#3217]
I have an example via the C++ API that returns due to `rlimit` on Linux but solves on OSX. Unfortunately I can't provide an smtlib2 file because if run via the `z3` binary both work fine.
Here are at least the statistics after solving:

OSX: https://gist.github.com/leonardoalt/73b24baa1240dcfb393b3152053a6c3e
Linux: https://gist.github.com/leonardoalt/9eccebcaf70900f0bea6d27befdb2c76

Any idea what could be the reason?

**Comment by agurfinkel** [comment]
It is hard to tell from the stats. The most probable reason is some non-deterministic action is resolved differently in two systems causing the solver to take a different direction.

I'm preparing a PR for logging (and visualizing) a run of spacer. This should help us debug this even when the issue only happens through the API.

**Comment by leonardoalt** [comment]
Ok, thanks. Can you let me know when the PR is pushed? Then I can take a look. Also feel free to close the issue for now.

**Comment by NikolajBjorner** [comment]
the data provided isn't sufficient to figure out what the core issue is.
It could also be a matter of setup (the first stats for osx does not mention rlimit count and the total rlimit counts are different). 
I didn't find the usual sources of non-determinism in spacer (using unordered collections for traversal). They could still be lurking (for example, sorting lists with a key that identifies some elements that are treated differently).
