### ISSUE TITLE
unexpected behavior of the `/` operator

### ISSUE THREAD

**Issue by nikivazou** [Z3Prover/z3#323]
If you run the following file 

http://goto.ucsd.edu/~nvazou/TreesDiv.hs.smt2

with z3-4.4.0 (as I downloaded from [here](https://z3.codeplex.com/releases/view/101918)) it returns an unexpected (buggy) sat, while z3-3 returns only unsats. 

Specifically, the buggy result of z3-4.4.0 is 

```
unsat
unsat
unsat
unsat
unsat
unsat
unsat
unsat
unsat
unsat
unsat
unsat
unsat
unsat
unsat
unsat
unsat
unsat
unsat
unsat
unsat
unsat
unsat
unsat
unsat
unsat
unsat
unsat
unsat
unsat
unsat
unsat
unsat
unsat
unsat
unsat
unsat
unsat
unsat
unsat
unsat
unsat
unsat
unsat
unsat
unsat
unsat
unsat
unsat
unsat
unsat
unsat
unsat
unsat
unsat
unsat
unsat
unsat
unsat
unsat
unsat
unsat
unsat
unsat
unsat
unsat
unsat
unsat
sat
unsat
unsat
unsat
unsat
unsat
unsat
unsat
unsat
unsat
unsat
unsat
unsat
unsat
unsat
unsat
```

Thanks, 
Niki

PS: Sorry for the unreadable file, it is automatically generated by liquidHaskell

**Comment by NikolajBjorner** [comment]
I can't reproduce it with the current master branch, so I hope the bug was fixed.

**Comment by nikivazou** [comment]
Sorry Nikolaj, can you try it again. 
I simplified the file in the link I sent you.
 
z3-3 says `sat` and `sat` is what we expect. 
z3-4 says `unsat`, which is unexpected.

**Comment by sorawee** [comment]
Minimal program that demonstrates the bug:

```
(declare-fun TreeSize (Int) Int)
(declare-fun NodeCreator (Int) Int)
(declare-fun size_subtree () Int)
(declare-fun subtree () Int)
(declare-fun size_excluding_root () Int)

(assert (= size_excluding_root (- (TreeSize (NodeCreator subtree)) 10)))
(assert (= (TreeSize (NodeCreator subtree)) (+ 1 (* 2 (TreeSize subtree)))))
(assert (= size_subtree (/ size_excluding_root 2)))

(assert (not (= (TreeSize subtree) size_subtree)))
(check-sat)
```

**Comment by NikolajBjorner** [comment]
Why should this be sat (other than that Z3 previously had a bug).
The first equation says that there are two integers x, y such that y = x - 4.5 (after simplifying (2*x - 10 + 1)/2 = (2*x - 9)/2). 
If you want integer division semantics use the "div" function.

**Comment by NikolajBjorner** [comment]
Do you agree or disagree that this is not a bug?

**Comment by sorawee** [comment]
I see now, but I don't know what LiquidHaskell team will think about it ( @nikivazou , @ranjitjhala ).

**Comment by sorawee** [comment]
Shouldn't this be a type error, though? Virtually, there's no good to use `/` with `Int` at all. Shouldn't `/` only accept Reals as arguments?

**Comment by NikolajBjorner** [comment]
Z3 adds coercions by default. You can disable coercions as follows:

<pre>
(declare-fun y () Int)
(declare-fun x () Int)
(set-option :int-real-coercions false)
(assert (= y (/ (- (+ 1 (* 2 x)) 10) 2)))
(assert (not (= x y)))
(check-sat)
</pre>

Z3 produces a type error.

**Comment by ranjitjhala** [comment]
Thanks @NikolajBjorner -- due to the coercions (which I didn't know about) and the glitch in the old version of z3, I was under the impression that / was in fact integer division (at least when applied to ints). Will update to use 'div'. 

Thanks @sorawee for helping get to the bottom of this!
