### ISSUE TITLE
optimisation causes segfault

### ISSUE THREAD

**Issue by nils2000** [Z3Prover/z3#324]
Hello,

first attached file causes a segfault. When the line:
(minimize k)
is replaced with
(assert (< k 5))
a solution is found (second file)....

I would be happy to supply any additional information ....
(tested with recent versions of z3 on (arch)linux and mac)

[test_functional.smt.notworking.txt](https://github.com/Z3Prover/z3/files/37285/test_functional.smt.notworking.txt)
[test_functional.smt.working.txt](https://github.com/Z3Prover/z3/files/37286/test_functional.smt.working.txt)

**Comment by NikolajBjorner** [comment]
One of the transformation tactics ignored quantifiers.
