### ISSUE TITLE
Presence of lblpos makes query unknown

### ISSUE THREAD

**Issue by fpoli** [Z3Prover/z3#3240]
On the following query Z3 4.8.5 answers "unknown" because "smt tactic failed to show goal to be sat/unsat (incomplete (theory arithmetic))".

```
(set-option :random-seed 42)

(declare-fun x () Real)
(assert (not
  (=> (! true :lblpos +123) (=> (> x 0.0) (> (* x x) 0.0)))
))
(check-sat)
(get-info :reason-unknown)
```

However, if I remove the `lblpos` Z3 answers "unsat", as expected.
```
(set-option :random-seed 42)

(declare-fun x () Real)
(assert (not
  (=> (! true) (=> (> x 0.0) (> (* x x) 0.0)))
))
(check-sat)
(get-info :reason-unknown)
```

Any hints regarding why the `lblpos` makes the tactic incomplete?

Thanks

**Comment by fpoli** [comment]
This might be explained by https://github.com/Z3Prover/z3/issues/2240

**Comment by NikolajBjorner** [comment]
nlsat_solver doesn't support labels and the smt core, which supports labels, is incomplete for nla
