### ISSUE TITLE
Getting labels after optimization

### ISSUE THREAD

**Issue by wuestholz** [Z3Prover/z3#325]
I would like to extend Boogie to support some of the optimization features in Z3 (e.g., to minimize values in counterexamples). However, I ran into a minor issue. It seems that after invoking `(minimize ...)` the labels are always empty. Is there some specific reason for this?

In the example below, I get `(labels)`. However, I get `(labels +125 +39 @145)` if I comment out the line with `(minimize x@0)`.

```
(set-option :print-success false)
(set-info :smt-lib-version 2.0)
(set-option :produce-models true)
(set-option :AUTO_CONFIG false)
(set-option :pp.bv_literals false)
(set-option :MODEL.V2 true)
(set-option :smt.PHASE_SELECTION 0)
(set-option :smt.RESTART_STRATEGY 0)
(set-option :smt.RESTART_FACTOR |1.5|)
(set-option :smt.ARITH.RANDOM_INITIAL_VALUE true)
(set-option :smt.CASE_SPLIT 3)
(set-option :smt.DELAY_UNITS true)
(set-option :NNF.SK_HACK true)
(set-option :smt.MBQI false)
(set-option :smt.QI.EAGER_THRESHOLD 100)
(set-option :TYPE_CHECK true)
(set-option :smt.BV.REFLECT true)
(set-option :TIMEOUT 0)
; done setting options


(declare-fun tickleBool (Bool) Bool)
(assert (and (tickleBool true) (tickleBool false)))
(declare-fun minim (Int) Bool)
(declare-fun %lbl%+39 () Bool)
(declare-fun x@0 () Int)
(declare-fun %lbl%@145 () Bool)
(declare-fun MayFail (Int) Bool)
(declare-fun %lbl%+125 () Bool)
(push 1)
(set-info :boogie-vc-id test0)
(assert (not
(let ((anon0_correct  (=> (! (and %lbl%+39 true) :lblpos +39) (=> (and (< 42 x@0) (minim x@0)) (! (or %lbl%@145 (MayFail x@0)) :lblneg @145)))))
(let ((PreconditionGeneratedEntry_correct  (=> (! (and %lbl%+125 true) :lblpos +125) anon0_correct)))
PreconditionGeneratedEntry_correct))
))
(minimize x@0)
(check-sat)
(get-model)
```

Independently, I was wondering if it is possible to suppress the output that shows the assignment for the minimized expressions (here `x@0 |-> 43`) before showing the result of `(check-sat)`.

**Comment by NikolajBjorner** [comment]
Thanks for the requests. The optimization core doesn't expose the labels features (at this point) which may be somewhat specific to one of our (main) kernels.
Regarding output format, yes this should be somewhat streamlined (and put in LISP format). Perhaps for starters you suggest to change order of reporting.

**Comment by NikolajBjorner** [comment]
labels are now available and order of output changed.

**Comment by wuestholz** [comment]
Great! Thank you for the quick fix! I just gave it a try and that makes things much easier. However, I noticed that in some cases some labels seem to be missing. Any idea why this could be the case?

For instance, in the following example I get `(labels +56)`, but `(labels +56 +43 +47 @87)` if I comment out the line `(maximize x@0)`.

```
(set-option :print-success false)
(set-info :smt-lib-version 2.0)
(set-option :produce-models true)
(set-option :AUTO_CONFIG false)
(set-option :pp.bv_literals false)
(set-option :MODEL.V2 true)
(set-option :smt.PHASE_SELECTION 0)
(set-option :smt.RESTART_STRATEGY 0)
(set-option :smt.RESTART_FACTOR |1.5|)
(set-option :smt.ARITH.RANDOM_INITIAL_VALUE true)
(set-option :smt.CASE_SPLIT 3)
(set-option :smt.DELAY_UNITS true)
(set-option :NNF.SK_HACK true)
(set-option :smt.MBQI false)
(set-option :smt.QI.EAGER_THRESHOLD 100)
(set-option :TYPE_CHECK true)
(set-option :smt.BV.REFLECT true)
(set-option :TIMEOUT 0)
; done setting options


(declare-fun tickleBool (Bool) Bool)
(assert (and (tickleBool true) (tickleBool false)))
(declare-fun %lbl%+47 () Bool)
(declare-fun x@0 () Int)
(declare-fun %lbl%@87 () Bool)
(declare-fun may_fail (Int) Bool)
(declare-fun %lbl%+45 () Bool)
(declare-fun %lbl%+43 () Bool)
(declare-fun %lbl%+56 () Bool)
(push 1)
(set-info :boogie-vc-id test0)
(assert (not
(let ((anon2_correct  (=> (! (and %lbl%+47 true) :lblpos +47) (! (or %lbl%@87 (may_fail x@0)) :lblneg @87))))
(let ((anon3_Else_correct  (=> (! (and %lbl%+45 true) :lblpos +45) (=> (= x@0 1) anon2_correct))))
(let ((anon3_Then_correct  (=> (! (and %lbl%+43 true) :lblpos +43) (=> (= x@0 2) anon2_correct))))
(let ((anon0_correct  (=> (! (and %lbl%+56 true) :lblpos +56) (and anon3_Then_correct anon3_Else_correct))))
anon0_correct))))
))
(maximize x@0)
(check-sat)
(labels)
(get-model)
```

Note that in both cases the counterexample (which includes the lbl functions) is the same and consistent with `(labels +56 +43 +47 @87)`:

```
%lbl%+56 -> true
%lbl%+43 -> true
x@0 -> 2
%lbl%@87 -> false
%lbl%+47 -> true
tickleBool -> {
  true -> true
  false -> true
  else -> true
}
may_fail -> {
  2 -> false
  else -> false
}
```

**Comment by wuestholz** [comment]
Great! Thank you very much! That did the trick.

I noticed that the list may now contain duplicates, which was not the case before. I'm currently filtering them myself, but I thought I'd mention it in case you want to guarantee no duplicates.

**Comment by NikolajBjorner** [comment]
If you have a chance, then upload a repro. I now removed one source of potential duplicates.

**Comment by wuestholz** [comment]
Thank you! This took care of all the duplicates in my test cases. I'll let you know if I run into duplicates again.
