### ISSUE TITLE
solver.enforce_model_conversion smt.phase_selection soundness bug on QF_LRA formula

### ISSUE THREAD

**Issue by muchang** [Z3Prover/z3#3250]
Hi,
For this formula:
```
(set-option :solver.enforce_model_conversion true)
(set-option :smt.phase_selection 1)
(declare-fun a () Real)
(declare-fun b () Real)
(assert (not (= b 0)))
(check-sat)
(assert (> (/ 1 a) 0))
(assert (< b (- 1)))
(check-sat)
```
Z3  gives an incorrect answer:
```
[748] % z3 small.smt2
sat
unsat
[749] % z3debug small.smt2
sat
sat
[750] % cat small.smt2
(set-option :solver.enforce_model_conversion true)
(set-option :smt.phase_selection 1)
(declare-fun a () Real)
(declare-fun b () Real)
(assert (not (= b 0)))
(check-sat)
(assert (> (/ 1 a) 0))
(assert (< b (- 1)))
(check-sat)
```
Z3 debug branch is correct.

OS: Ubuntu 18.04
Commit: d9c09dc

**Comment by NikolajBjorner** [comment]
again, enforce_model_conversion is not for incremental mode.

**Comment by zhendongsu** [comment]
Nikolaj, it would be nice to know what sort of things shouldn't be used when or together.   In particular, besides that enforce_model_conversion is not for the incremental mode, any others?   Thanks for any information.

**Comment by NikolajBjorner** [comment]
It would, but there is very limited bandwidth to supply such information. 
I will have to resort to the options that are documented in tutorials/user guides (programmingz3).
This option isn't even advertised so those who find it are basically trying all knobs and for those cases I have to first triage whether the issues cover a potential user relevant scenario and once one guideline is established I deal with the issues accordingly.

**Comment by zhendongsu** [comment]
Okay, thanks for the quick response, Nikolaj.  In that case, we will try our best to remember not reporting this similar issue again --- we, in fact, did try as we expected that the master and debug branches would agree in such scenarios.
