### ISSUE TITLE
problem doing quantifier elimination

### ISSUE THREAD

**Issue by zganjei** [Z3Prover/z3#3251]
I have a small formula for which I need to do quantifier elimination. Z3 takes a lot of time to do that (and on other bigger variants of the formula it doesn't return) and the result is weired. The python code is as follows.

``
from  z3 import *

for i in range(0,10) :
      n,X_0_, X_1_= Ints('n X_0_ X_1_')
      R_0_0, R__0, R_1_0, R__1,R_0_1,R_1_1,a0,a1= Ints('R_0_0 R__0 R_1_0 R__1 R_0_1 R_1_1 a0 a1')
      all=[
           [n >= 3],
           X_0_ + X_1_ ==n,
	   5*R_0_1 <= 5*X_0_ + n,
           5*R_1_0 <= 5*X_1_ + n,
           40*R_0_1 > 19*n,
           40*R_1_0 > 19*n]
      expr = And(*all)
      expr = Exists([R_1_0, R_0_1],expr)
      tactic = Then(Tactic('simplify'),Tactic('qe2'),Tactic('solve-eqs'))     
      expr=tactic(expr).as_expr()
``
I would expect the output to be something like 40*X_0_>11*n and 40*X_1_>11*n. But it is the following.

And(n >= 3,
    11*n + -40*X_0_ <= -1,
    11*n + -40*X_1_ <= -1,
    Or(11*n + -40*X_0_ <= -9, (-1*n + -5*X_0_)%5 == 0),
    Or((-1*n + -5*X_1_)%5 == 0, 11*n + -40*X_1_ <= -9),
    Or(11*n + -40*X_1_ <= -25,
       (1 + -1*n + -5*X_0_)%5 == 0,
       (-1*n + -5*X_0_)%5 == 0,
       11*n + -40*X_1_ <= -17),
    Or(11*n + -40*X_1_ <= -25,
       (3 + -1*n + -5*X_0_)%5 == 0,
       (2 + -1*n + -5*X_1_)%5 == 0,
       (1 + -1*n + -5*X_0_)%5 == 0,
       (-1*n + -5*X_0_)%5 == 0,
       Not(11*n + -40*X_1_ <= -17),
       (-1*n + -5*X_1_)%5 == 0,
       (1 + -1*n + -5*X_1_)%5 == 0),
    Or((3 + -1*n + -5*X_0_)%5 == 0,
       (2 + -1*n + -5*X_1_)%5 == 0,
       11*n + -40*X_0_ <= -25,
       (1 + -1*n + -5*X_0_)%5 == 0,
       (-1*n + -5*X_0_)%5 == 0,
       (-1*n + -5*X_1_)%5 == 0,
       (1 + -1*n + -5*X_1_)%5 == 0),
    Or(11*n + -40*X_0_ <= -25,
       (1 + -1*n + -5*X_0_)%5 == 0,
       (-1*n + -5*X_0_)%5 == 0,
       (-1*n + -5*X_1_)%5 == 0,
       (1 + -1*n + -5*X_1_)%5 == 0,
       Not((3 + -1*n + -5*X_1_)%5 == 0)),
    Or(11*n + -40*X_1_ <= -25,
       (1 + -1*n + -5*X_0_)%5 == 0,
       (-1*n + -5*X_0_)%5 == 0,
       Not(11*n + -40*X_1_ <= -17),
       (-1*n + -5*X_1_)%5 == 0,
       (1 + -1*n + -5*X_1_)%5 == 0,
       Not((3 + -1*n + -5*X_1_)%5 == 0)),
    Or(Not(11*n + -40*X_0_ <= -25),
       (3 + -1*n + -5*X_0_)%5 == 0,
       (2 + -1*n + -5*X_1_)%5 == 0,
       (1 + -1*n + -5*X_0_)%5 == 0,
       (-1*n + -5*X_0_)%5 == 0,
       Not(11*n + -40*X_1_ <= -17),
       (-1*n + -5*X_1_)%5 == 0,
       55*n + -200*X_1_ <= -161,
       55*n + -200*X_0_ <= -161,
       Not(11*n + -40*X_1_ <= -25)),
    Or((3 + -1*n + -5*X_0_)%5 == 0,
       (2 + -1*n + -5*X_1_)%5 == 0,
       (1 + -1*n + -5*X_0_)%5 == 0,
       (-1*n + -5*X_0_)%5 == 0,
       (-1*n + -5*X_1_)%5 == 0,
       (1 + -1*n + -5*X_1_)%5 == 0,
       55*n + -200*X_0_ <= -161),
    Or(11*n + -40*X_0_ <= -25,
       (1 + -1*n + -5*X_0_)%5 == 0,
       (-1*n + -5*X_0_)%5 == 0,
       (-1*n + -5*X_1_)%5 == 0,
       11*n + -40*X_0_ <= -17,
       (1 + -1*n + -5*X_1_)%5 == 0,
       Not((2 + -1*n + -5*X_1_)%5 == 0),
       Not((2 + -1*n + -5*X_0_)%5 == 0)),
    Or((3 + -1*n + -5*X_0_)%5 == 0,
       (2 + -1*n + -5*X_1_)%5 == 0,
       (1 + -1*n + -5*X_0_)%5 == 0,
       (-1*n + -5*X_0_)%5 == 0,
       (-1*n + -5*X_1_)%5 == 0,
       (1 + -1*n + -5*X_1_)%5 == 0,
       55*n + -200*X_1_ <= -161))

Am I doing something wrong?

**Comment by NikolajBjorner** [comment]
There seems to be room for improvement regarding qe2. 
The qe2 tactic can sometimes beat qe, but not always. In this case qe produces a smaller solution.
The solve-eqs tactic may eliminate variables from the formula. The contract is that the model produced by the goal that is returned can be used to reconstruct a model for the original goal, but this is likely not what you want for quantifier elimination where you want a handle on the formula.
Therefore solve-eqs is unlikely to be good for your uses.
