### ISSUE TITLE
Z3 loops and ignores soft time-out

### ISSUE THREAD

**Issue by RustanLeino** [Z3Prover/z3#326]
In the attached file, the variables `s#0` and `t#0` are set up in the same way. Trying to prove something about `s#0` immediately returns with a result, whereas changing the file to try to prove the same thing for `t#0` causes Z3 (version 4.4.1 or 4.4.0) to immerse itself in its toil to the extent that it even ignores the soft timeout.

To repro:
* See the end of the attached input file.  Choose either the marked `s#0` line or the marked `t#0` line.  Then run z3.exe version 4.4.1 or 4.4.0 on the input file.
[dd.smt2](https://github.com/Z3Prover/z3/files/37424/dd.smt2.txt)

Notes:
* I am, of course, aware of that minute changes in the input can cause dramatic changes in Z3's behavior. However, the fact that the soft timeout gets ignored here smells to me like some bug.
* I have distilled this file from a larger one with more axioms, where the `s#0` line resulted in a Valid (that is, unsat) query. In that case, using the `t#0` line caused Z3 never to come back at all.  With the attached file, Z3 does terminate on the `t#0` line, but after about 25 seconds, even with `-t:3000`.  I'd be happy to furnish this larger input file, if you want it.

**Comment by NikolajBjorner** [comment]
Is it furnished the IKEA way?

**Comment by RustanLeino** [comment]
Frugally?  Or should I have named `s#0` and `t#0` something like `Bananskal` and `Gristjärn`?

**Comment by NikolajBjorner** [comment]
how about rüstán?

**Comment by NikolajBjorner** [comment]
your new axiom profiler should be useful for shedding light on the massive amount of quantifier instantiations that swarm in.

**Comment by wintersteiger** [comment]
Looks to me like at least the soft timeout issue is covered. Can we close this issue or are there more sub-issues?

**Comment by NikolajBjorner** [comment]
R.u.stan?

**Comment by wintersteiger** [comment]
I suppose this issue is fixed after Rustans failure to soft-timeout? :-)
