### ISSUE TITLE
Different behaviors in Mac and Ubuntu

### ISSUE THREAD

**Issue by qingkaishi** [Z3Prover/z3#327]
I create two threads and each thread works in its own z3::context. However, it works well in Linux, but has data races in Mac OS causing segmentation fault. The Mac OS is 10.11 OS X Capitan. And the z3 (4.4.0 or 4.4.1) is built using clang. Please help. Many thanks!

The example is as below:

```c++
void* f1(void* a) {
    // this is a z3 built-in example (see in examples/c++/example.cpp)
    expr_vector_example();

    return NULL;
}

void* f2(void* a) {
    // this is a z3 built-in example (see in examples/c++/example.cpp)
    expr_vector_example();

    return NULL;
}

void multi_thread_example() {
   pthread_t t1, t2;
   pthread_create(&t1, NULL, f1, NULL);
   pthread_create(&t2, NULL, f2, NULL);

   pthread_join(t1, NULL);
   pthread_join(t2, NULL);

}
```

**Comment by wintersteiger** [comment]
Parallel construction of context objects is not supported at this time either. This works in some of the higher level APIs (whcih sequentialize it), but it doesn't work via the C API. I recommend construction of all Context's required and putting them in an array, then each thread can get their Context from that array. If you try that it would be great if you could report back whether you see any other problems!

**Comment by NikolajBjorner** [comment]
Alternatively call Z3_memory_reset_memory() in the main thread. This ensures that global shared state is fully initialized before each thread creates contexts.

**Comment by qingkaishi** [comment]
@wintersteiger  @NikolajBjorner  I have tried your methods, but neither of them work in my mac. It still crashes in mac.

One typical crash information is "malloc: *** error for object 0x10326a000: pointer being freed was not allocated"

**Comment by NikolajBjorner** [comment]
I wonder maybe the OMP libraries are not being used in your mac installation. When you configure the build environment, Z3 should print:

Testing OpenMP...
64-bit:         "True or False"
OpenMP:         True

If you see OpenMP         False, then it would not use the necessary locks.
The script mk_make.py tests for whether OpenMP is available. i
