### ISSUE TITLE
Debug branch: Soundness bug with nonlinear integer arithmetic and uninterpreted function

### ISSUE THREAD

**Issue by wintered** [Z3Prover/z3#3270]
Hi, on this formula 

```
(declare-const a Int)
(declare-fun b (Int) Int) 
(assert (and  (= (* a a) (b a) 1) (= (b 1)  (b (- 1)) 0))) 
(check-sat) 
```
OS: Ubuntu 18.04
Commit: a02d3e9

**Comment by levnach** [comment]
It returns "unsat" in "debug" branch now, which seems correct.

**Comment by levnach** [comment]
@NikolajBjorner . If you enable monomial_bounds then running on this sample gives an assert
ASSERTION VIOLATION
File: ../../src/math/lp/nla_core.cpp
Line: 1045
!c.ineq_holds(ineq)

With the stack:
#1  0x0000555555e03472 in nla::new_lemma::operator|= (this=0x7fffffffbc20, ineq=...) at ../../src/math/lp/nla_core.cpp:1045
#2  0x0000555555ddf40f in nla::monomial_bounds::propagate_value (this=0x555557794758, range=..., v=4, p=2) at ../../src/math/lp/monomial_bounds.cpp:109
#3  0x0000555555de0272 in nla::monomial_bounds::propagate_down (this=0x555557794758, m=..., mi=..., v=4, power=2, product=...) at ../../src/math/lp/monomial_bounds.cpp:208
#4  0x0000555555de001d in nla::monomial_bounds::propagate (this=0x555557794758, m=...) at ../../src/math/lp/monomial_bounds.cpp:195
#5  0x0000555555dde73a in nla::monomial_bounds::operator() (this=0x555557794758) at ../../src/math/lp/monomial_bounds.cpp:24
