### ISSUE TITLE
Assertion failure: duality engine with two `(not (exists …))`

### ISSUE THREAD

**Issue by cocreature** [Z3Prover/z3#328]
Hi,
I have some very simple code
```smt
(set-logic HORN)
(declare-fun INV (Int) Bool)
(assert (forall ((D Bool)) (not D)))
(assert (forall ((A Int)) (not (INV A))))
(check-sat)
(get-model)
```
that produces an assertion failure
```
[0]node 1: query!0
[1]node 2: @Fail!2
[2]node 3: INV
ASSERTION VIOLATION
File: ../src/smt/smt_internalizer.cpp
Line: 329
is_app(n)
```
It seems to be related to using two having two clauses of the form `(not (exists …))` or in this case formulated as foralls (changing it to the exists form still produces the error).

If I instead use
```smt
(set-logic HORN)
(declare-fun INV (Int) Bool)
(assert (forall ((D Bool) (A Int)) (and (not D) (not (INV A)))))
(check-sat)
(get-model)
```
it works just fine.

I am using z3 built from the master branch.

**Comment by kenmcmil** [comment]
Looks like datalog::context::get_raw_rule_formulas is returning formulas with a free variable that look like this:

(=> (and (:var 0)) query!0)
(=> (and (INV (:var 0))) query!0)

These clauses seem to have been created to merge the two negative clauses in the source, but the quantifier has been forgotten.

**Comment by cocreature** [comment]
Thanks!
