### ISSUE TITLE
smt.arith.solver assertion violation at ../src/ast/ast.cpp Line: 1931

### ISSUE THREAD

**Issue by legendtang** [Z3Prover/z3#3293]
Hi,
For this formula:
[ast3.txt](https://github.com/Z3Prover/z3/files/4332716/ast3.txt)
Z3 throws out an assertion violation:
```
sat
sat
ASSERTION VIOLATION
File: ../src/ast/ast.cpp
Line: 431
UNREACHABLE CODE WAS REACHED.
(C)ontinue, (A)bort, (S)top, (T)hrow exception, Invoke (G)
```
the options is:
```
(set-option :smt.arith.solver 6)
```
Commit: 6f2b5696d560cdf83016708342d30b069ffbc6c7

**Comment by NikolajBjorner** [comment]
we are grateful for bug reports against arith.solver = 6 in the Debug branch, but not yet master branch. This one seems to have already been addressed in the debug branch.
