### ISSUE TITLE
z3 can't solve constraints int const in function power

### ISSUE THREAD

**Issue by chineshboy** [Z3Prover/z3#330]
z3 version: 4.4.0

try the following constraint

; 
(set-info :status unknown)
(declare-fun b () Int)
(assert
(= (^ b 4) 16))
(check-sat)

the result is 'unknown'
the same with this one:

; 
(set-info :status unknown)
(declare-fun b () Int)
(assert
(= (^ 4 b) 16))
(check-sat)

but another one would give the right result:

; 
(set-info :status unknown)
(declare-fun b () Int)
(assert
(= (^ 2 4) b))
(check-sat)

**Comment by NikolajBjorner** [comment]
This is not a bug. Z3 isn't a decision procedure for non-linear integer arithmetic
