### ISSUE TITLE
Debug branch: Soundness bug 

### ISSUE THREAD

**Issue by wintered** [Z3Prover/z3#3300]
Hi,
on the following formula Z3 reports `unsat` while Z3 master branch reports `sat`
```
(declare-fun a () Real)
(declare-fun b () Real)
(assert (or (distinct b 2.0) (not (= (/ (- b) (* 2.0 b)) 0.0))))
(assert (< (* a b) 0.0))
(push)
(check-sat)
```
OS: Ubuntu 18.04
Commit: 63aae5d

**Comment by rainoftime** [comment]
Seems caused by an issue about incremental solving in the master branch https://github.com/Z3Prover/z3/issues/3285
https://github.com/Z3Prover/z3/issues/3244

**Comment by levnach** [comment]
Does not finish now at commit 9181e6644c6157b556b634b615243408d3ff78a8
