### ISSUE TITLE
Debug branch: soundness issue for QF_BV instance 

### ISSUE THREAD

**Issue by rainoftime** [Z3Prover/z3#3307]
Hi, for the following instance,
~~~~
(set-logic QF_BV)
(set-option :model_validate true)
(declare-const v12 Bool)
(declare-const v15 Bool)
(assert (or v12 v15))
(check-sat)
(check-sat)
~~~~
z3 debug branch gives an incorrect model.

When removing the first line `(set-logic QF_BV)`, z3 can work correctly.

Commit: 3ac9dbd7d6d

**Comment by NikolajBjorner** [comment]
duplicate of master branch.
Debug branch is only for integrating arith.solver=6 fully
