### ISSUE TITLE
`Z3_mk_fpa_to_fp_float()` makes unsat constraints  be sat

### ISSUE THREAD

**Issue by martin2011** [Z3Prover/z3#331]
I want to solve the two following constraints about  ` a` with `double_sort` :
```
(1)  a > 1.0;

(2)   (float) (a) <= 1.0f
```
There is a type  conversion in the second constraint, that first convert `double` to  `float` and then add a condition with ` fa <= 1.0f`,   `fa` is the floating type of `a`.
this is definitely `unsat` by rewriting  semantically as `a>1  && a<=1` 
However, I get a `sat`  output with implementation by the following code:
```
	context ctx;
    solver s(ctx);
	Z3_sort float_sort,double_sort;
	float_sort=Z3_mk_fpa_sort_32(ctx);
	double_sort=Z3_mk_fpa_sort_64(ctx);

 /*  create float 1.0f and double 1.0l*/
	expr fone=to_expr(ctx,Z3_mk_fpa_numeral_float(ctx,1.0f,float_sort));
	expr done=to_expr(ctx,Z3_mk_fpa_numeral_float(ctx,1.0l,double_sort));

/* create double_sort Z3_ast  "a" */
	expr da=to_expr(ctx,Z3_mk_const(ctx,Z3_mk_string_symbol(ctx,"a"),double_sort));

/*add   da > 1.0l*/
	expr dagt1=to_expr(ctx,Z3_mk_fpa_gt(ctx,da,done));	
	s.add(dagt1);

/* convert  "da"   to "fa"  */
	expr roundtonearest_even=to_expr(ctx,Z3_mk_fpa_round_nearest_ties_to_even(ctx));
	expr datofa=to_expr(ctx,Z3_mk_fpa_to_fp_float(ctx,roundtonearest_even,da,float_sort));

/* add fa  <= 1.0f*/
	expr fagtone=to_expr(ctx,Z3_mk_fpa_leq(ctx,datofa,fone));
	s.add(fagtone);
```

The output is `sat` with
 `(define-fun a () (_ FloatingPoint 11 53)   (fp #b0 #b11111111110 #x000100280f182))`

I try to output the added constraint  after the last line in the listed code, and the output is:
```
(fp.gt a (fp #b0 #b01111111111 #x0000000000000))
(fp.leq ((_ to_fp 8 24) roundNearestTiesToEven a)
        (fp #b0 #x7f #b00000000000000000000000))

```
which should indicate the constraint is added successfully. 
Then I test `double a` `a>1.0  && a< =1.0` without conversation, the result is unsat and  `float a` `a>1.0f && a<=1.0f` is also unsat.  As a result,  I conclude this unexpected result is introduced by the function `Z3_mk_fpa_to_fp_float()` ( or I missed something).

**Comment by wintersteiger** [comment]
Thanks for the report! There was indeed a bug in the float to float conversion which is now fixed. 

Note however that your original test case is not unsatisfiable; here is the whole test case in SMT2:

    (set-logic QF_FP)
    (declare-fun da () (_ FloatingPoint 11 53))
    (declare-fun fa () (_ FloatingPoint 8 24))

    (define-fun done () (_ FloatingPoint 11 53) (fp #b0 #b01111111111 #x0000000000000))
    (define-fun fone () (_ FloatingPoint 8 24) (fp #b0 #x7f #b00000000000000000000000))

    (assert (fp.gt da done))
    (assert (= fa ((_ to_fp 8 24) RNE da))) ;; <-- Change RNE to RTP to make it unsat.
    (assert (fp.leq fa ((_ to_fp 8 24) RNE 1.0)))

    (check-sat)

The large number `da` is assigned "1.0 + a little bit" and when it is cast down to single precision, rounding takes place and removes the "little bit", so exactly 1.0 is still a valid solution - except if we round towards positive.

**Comment by martin2011** [comment]
yes, RTP is right.
But, Is it unrealistic to use RNE in theory or  is it  on the way?

**Comment by wintersteiger** [comment]
RNE is fully implemented and working soundly. Both, in theory as well as in practice, this problem is satisfiable!

**Comment by martin2011** [comment]
I get it ,thanks.
