### ISSUE TITLE
Debug branch: inconsistency with master branch for QF_NIA instance

### ISSUE THREAD

**Issue by rainoftime** [Z3Prover/z3#3317]
Hi, for the following formula,
~~~~
(set-logic QF_NIA)
(set-option :model_validate true)
(declare-const i2 Int)
(assert (distinct i2 (abs (* 52 i2 i2 70))))
(assert (> 82 (mod 442 (* 52 i2 i2 70))))
(check-sat)
~~~~
z3 debug branch (Commit https://github.com/Z3Prover/z3/commit/3ac9dbd7d6d7fca29d32657e7cabe79def3259c1)  returns `sat` and gives an invalide mode,
but master branch  (Commit 894702d60) gives `unsat`

**Comment by levnach** [comment]
Works correctly now
