### ISSUE TITLE
"unknow function" when array-ext are fed back

### ISSUE THREAD

**Issue by 0-14N** [Z3Prover/z3#333]
Hi,

I got interpolants from z3 with function "array-ext", however, when I fed them back to z3, it returns "unknown function/constant array-ext" and sat. I am testing on the latest codes.

The following is the smt file:

(declare-datatypes () ((ArrayTest3 (ArrayTest3_nil))))
(declare-fun |0!!this!0| () ArrayTest3)
(declare-fun |0!r0!0| () ArrayTest3)
(declare-fun |0!!parameter0!0| () (Array Int Int))
(declare-fun |0!r1!0| () (Array Int Int))
(declare-fun |0!i3!0| () Int)
(declare-fun |0!$i0!0| () Int)
(declare-fun length_of_int ((Array Int Int)) Int)
(declare-fun |0!$i1!0| () Int)
(declare-fun |0!$i2!0| () Int)
(declare-fun |0!r1!1| () (Array Int Int))
(declare-fun |0!i3!1| () Int)
(declare-fun |0!$i0!1| () Int)
(declare-fun |0!$i1!1| () Int)
(declare-fun |0!$i2!1| () Int)
(declare-fun |0!r1!2| () (Array Int Int))
(declare-fun |0!i3!2| () Int)
(declare-fun |0!$i0!2| () Int)

(declare-fun |0!!this!!0| () ArrayTest3)
(declare-fun |0!r0!!0| () ArrayTest3)
(declare-fun |0!!parameter0!!0| () (Array Int Int))
(declare-fun |0!r1!!0| () (Array Int Int))
(declare-fun |0!$i0!!0| () Int)
(declare-fun |0!i3!!0| () Int)
(declare-fun |0!$i1!!0| () Int)
(declare-fun |0!$i2!!0| () Int)
(declare-fun |0!r1!!1| () (Array Int Int))
(declare-fun |0!i3!!1| () Int)
(declare-fun |0!$i1!!1| () Int)
(declare-fun |0!$i2!!1| () Int)
(declare-fun |0!r1!!2| () (Array Int Int))
(declare-fun |0!i3!!2| () Int)

(compute-interpolant (let ((a!1 (not (and (= (length_of_int |0!r1!2|) (length_of_int |0!r1!!2|))
                     (= |0!r1!2| |0!r1!!2|))))
      (a!2 (and (interp (and (interp true) (= |0!r0!0| |0!!this!0|)))
                (= |0!r1!0| |0!!parameter0!0|)))
      (a!18 (and (interp (and (interp true) (= |0!r0!!0| |0!!this!!0|)))
                 (= |0!r1!!0| |0!!parameter0!!0|))))
(let ((a!3 (and (interp (and (interp a!2) (= |0!i3!0| 0)))
                (= |0!$i0!0| (length_of_int |0!r1!0|))
                (>= |0!$i0!0| 0)))
      (a!19 (interp (and (interp a!18)
                         (= |0!$i0!!0| (length_of_int |0!r1!!0|))
                         (>= |0!$i0!!0| 0)))))
(let ((a!4 (interp (and (interp a!3) (not (>= |0!i3!0| |0!$i0!0|)))))
      (a!20 (interp (and a!19 (= |0!i3!!0| (- |0!$i0!!0| 1))))))
(let ((a!5 (interp (and a!4 (= |0!$i1!0| (select |0!r1!0| |0!i3!0|)))))
      (a!21 (interp (and a!20 (not (< |0!i3!!0| 0))))))
(let ((a!6 (interp (and a!5 (= |0!$i2!0| (+ |0!$i1!0| 1)))))
      (a!22 (interp (and a!21 (= |0!$i1!!0| (select |0!r1!!0| |0!i3!!0|))))))
(let ((a!7 (interp (and a!6 (= |0!r1!1| (store |0!r1!0| |0!i3!0| |0!$i2!0|)))))
      (a!23 (interp (and a!22 (= |0!$i2!!0| (+ |0!$i1!!0| 1))))))
(let ((a!8 (interp (and a!7 (= |0!i3!1| (+ |0!i3!0| 1)))))
      (a!24 (interp (and a!23
                         (= |0!r1!!1| (store |0!r1!!0| |0!i3!!0| |0!$i2!!0|))))))
(let ((a!9 (interp (and a!8 (= |0!i3!1| (+ |0!i3!0| 1)))))
      (a!25 (interp (and a!24 (= |0!i3!!1| (+ |0!i3!!0| (- 1)))))))
(let ((a!10 (interp (and a!9
                         (= |0!$i0!1| (length_of_int |0!r1!1|))
                         (>= |0!$i0!1| 0))))
      (a!26 (interp (and a!25 (= |0!i3!!1| (+ |0!i3!!0| (- 1)))))))
(let ((a!11 (interp (and a!10 (not (>= |0!i3!1| |0!$i0!1|)))))
      (a!27 (interp (and a!26 (not (< |0!i3!!1| 0))))))
(let ((a!12 (interp (and a!11 (= |0!$i1!1| (select |0!r1!1| |0!i3!1|)))))
      (a!28 (interp (and a!27 (= |0!$i1!!1| (select |0!r1!!1| |0!i3!!1|))))))
(let ((a!13 (interp (and a!12 (= |0!$i2!1| (+ |0!$i1!1| 1)))))
      (a!29 (interp (and a!28 (= |0!$i2!!1| (+ |0!$i1!!1| 1))))))
(let ((a!14 (interp (and a!13 (= |0!r1!2| (store |0!r1!1| |0!i3!1| |0!$i2!1|)))))
      (a!30 (interp (and a!29
                         (= |0!r1!!2| (store |0!r1!!1| |0!i3!!1| |0!$i2!!1|))))))
(let ((a!15 (interp (and a!14 (= |0!i3!2| (+ |0!i3!1| 1)))))
      (a!31 (interp (and a!30 (= |0!i3!!2| (+ |0!i3!!1| (- 1)))))))
(let ((a!16 (interp (and a!15 (= |0!i3!2| (+ |0!i3!1| 1)))))
      (a!32 (interp (and a!31 (= |0!i3!!2| (+ |0!i3!!1| (- 1)))))))
(let ((a!17 (interp (and a!16
                         (= |0!$i0!2| (length_of_int |0!r1!2|))
                         (>= |0!$i0!2| 0)))))
  (and (= |0!!this!0| |0!!this!!0|)
       (= (length_of_int |0!!parameter0!0|) (length_of_int |0!!parameter0!!0|))
       (= |0!!parameter0!0| |0!!parameter0!!0|)
       a!1
       (interp (and a!17 (>= |0!i3!2| |0!$i0!2|)))
       (interp (and a!32 (< |0!i3!!2| 0)))))))))))))))))))))

However, when I use Java API to feed the interpolant with "array-ext" to z3, it just return UNKNOW.
Thanks.

**Comment by NikolajBjorner** [comment]
Are you building the term using the Java API, or are you parsing the file from Java?
To build the term array-ext, you should use the following function

    /**
     * Create Extentionality index. Two arrays are equal if and only if they are equal on the index returned by MkArrayExt.
     **/
    public Expr mkArrayExt(ArrayExpr arg1, ArrayExpr arg2)
    {
    checkContextMatch(arg1);
    checkContextMatch(arg2);
    return Expr.create(this, Native.mkArrayExt(nCtx(), arg1.getNativeObject(), arg2.getNativeObject()));
    }

**Comment by kenmcmil** [comment]
Can you say what satisfiability problem you are trying to solve using the interpolant formulas? I notice the interpolants Z3 produces for these formulas are quantified (in fact have quantifiers over an array variable). So it could be that, using the Java API, Z3 is saying "unknown"  because of the quantifiers (generally, this is what Z3 says what it can't prove unsat but can't produce a model either).

**Comment by NikolajBjorner** [comment]
I am going to have to close this issue due to lack of repro. Z3 does now take array extensionality terms as part of the array vocabulary and handles decision problems for them.
