### ISSUE TITLE
Assertion violataion at lar_solver.cpp:429

### ISSUE THREAD

**Issue by rainoftime** [Z3Prover/z3#3333]
Hi, for the following instance,

[lar429.txt](https://github.com/Z3Prover/z3/files/4334326/lar429.txt)

z3 master branch (Commit 894702d)
throws an assertion violation
~~~~
File: ../src/math/lp/lar_solver.cpp
Line: 429
jset.m_index.size()==0
~~~~
The issue occurs when a timeout is triggered

**Comment by NikolajBjorner** [comment]
we defer issues around lar_solver to the debug branch
