### ISSUE TITLE
Nondeterminstic assertion violation at sat_integrity_checker.cpp:51

### ISSUE THREAD

**Issue by rainoftime** [Z3Prover/z3#3341]
Hi, for the following instance,
[sat51.txt](https://github.com/Z3Prover/z3/files/4335526/sat51.txt)

z3 master branch (Commit 6ad261e24ce)
throws an assertion violation when timeout

~~~~
File: ../src/sat/sat_integrity_checker.cpp
Line: 51
!c.was_removed() 
(C)ontinue, (A)bort, (S)top, (T)hrow exception, Invoke (G)DB
~~~~

The "timeout" should be "longer enough"

**Comment by NikolajBjorner** [comment]
sure, cancellation causes clauses to be in a non-standard state. The integrity checker is invoked by the destructor of sat in debug mode. Very low priority.
