### ISSUE TITLE
Assertion violation at /src/math/lp/cross_nested.h:289 with QF_NIA instance

### ISSUE THREAD

**Issue by 5hadowblad3** [Z3Prover/z3#3345]
Hi,
For this formula:
[z3-cross_nested289.smt2.zip](https://github.com/Z3Prover/z3/files/4335755/z3-cross_nested289.smt2.zip)

It is similar to issue #3249, but the condition to trigger the issue seems totally different.

Z3 throws out an assertion violation

ASSERTION VIOLATION
File: ../src/math/lp/cross_nested.h
Line: 289
nex_creator::equal(m_e, m_e_clone)
(C)ontinue, (A)bort, (S)top, (T)hrow exception, Invoke (G)DB

OS: Ubuntu 16.04
Commit: 6f2b5696d560cdf

**Comment by NikolajBjorner** [comment]
seems stale
