### ISSUE TITLE
nlsat.reorder rewriter.arith_ineq_lhs Invalid model on QF_NRA formula 

### ISSUE THREAD

**Issue by muchang** [Z3Prover/z3#3367]
Hi,
For this formula:
```
(declare-fun a () Real) 
(declare-fun b () Real) 
(declare-fun c () Real) 
(declare-fun d () Real) 
(declare-fun e () Real) 
(assert (< (+ (/ (* c c) (* 2.0 e))) d)) 
(assert (= a (+ b c))) 
(check-sat)  
```
Z3  gives an invalid model:
```
$ z3/build/z3 small.smt2 
sat
(error "line 11 column 10: an invalid model was generated")
$ cat small.smt2 
(set-option :model_validate true)
(set-option :nlsat.reorder false) 
(set-option :rewriter.arith_ineq_lhs true) 
(declare-fun a () Real) 
(declare-fun b () Real) 
(declare-fun c () Real) 
(declare-fun d () Real) 
(declare-fun e () Real) 
(assert (< (+ (/ (* c c) (* 2.0 e))) d)) 
(assert (= a (+ b c))) 
(check-sat)
```

OS: Ubuntu 18.04
Commit: 6ad261e

**Comment by NikolajBjorner** [comment]
dup, false positive, 2 levels of indirection from real issue

**Comment by rainoftime** [comment]
@muchang Previously, I had a similar issue https://github.com/Z3Prover/z3/issues/3303
The reason given by Nikolaj is 
> not really, the model_validate fails because the root objects don't simplify.
So the model validator provides a false positive. This is two degrees of separation from a real bug (change of parameters + model validation).

**Comment by NikolajBjorner** [comment]
sorry, too many bug reports floating in, I can't comment in depth on each

**Comment by muchang** [comment]
Thank @rainoftime and @NikolajBjorner for the explanations! 
As the title of #3303 is called soundness bug rather than the invalid model, I did not check it out. 
Nikolaj's previous comment is fairly okay, thanks!
