### ISSUE TITLE
Double->Float conversion broken

### ISSUE THREAD

**Issue by LeventErkok** [Z3Prover/z3#337]
This used to work until a very recent builds. I suspect the fix to http://github.com/Z3Prover/z3/issues/331 might have introduced it.

This benchmark converts to smallest possible double denormal (5.0e-324) to a single-precision value:

```
(set-option :produce-models true)
(set-logic QF_FP)
(define-fun s2 () (_ FloatingPoint 11 53) ((_ to_fp 11 53) roundNearestTiesToEven (/ 1 202402253307310618352495346718917307049556649764142118356901358027430339567995346891960383701437124495187077864316811911389808737385793476867013399940738509921517424276566361364466907742093216341239767678472745068562007483424692698618103355649159556340810056512358769552333414615230502532186327508646006263307707741093494784)))
(declare-fun s0 () (_ FloatingPoint 11 53))
(declare-fun s1 () (_ FloatingPoint  8 24))
(assert
   (let ((s3 (fp.eq s0 s2)))
   (let ((s5 ((_ to_fp 8 24) roundNearestTiesToEven s0)))
   (let ((s6 (fp.eq s1 s5)))
   (let ((s7 (and s3 s6)))
   s7)))))
(check-sat)
(eval s1)
```

The result should be `+0`, but Z3 says `+oo`:

```
sat
(_ +oo 8 24)
```

A similar issue exists when converting `-5.0e-324` as well.

**Comment by wintersteiger** [comment]
Thanks for the report. Yes, that's was definitely the fix for #331, I ignored those corner cases so far; they might need some more though, so might take a while until they're fixed.
