### ISSUE TITLE
Error in z3printer.py with python3

### ISSUE THREAD

**Issue by JoBaehr** [Z3Prover/z3#339]
When using z3 (v 4.4.2) with python3 (v 3.4.3, 64 bit, ubuntu v14.04),  there seems to be an error in the z3printer. 
Using the given example:

     from z3 import *
     x = Real('x')
     y = Real('y')
     s = Solver()
     s.add(x + y > 5, x > 1, y > 1)
     print(s.check())
     print(s.model())

Throws the following error:

      File "test.py", line 10, in <module>
         print(s.model())
      File "/usr/local/lib/python3.4/dist-packages/z3.py", line 5355, in __repr__
         return obj_to_string(self)
      File "/usr/local/lib/python3.4/dist-packages/z3printer.py", line 1165, in obj_to_string
         if enc != None: return r.decode(enc)
      AttributeError: 'str' object has no attribute 'decode'

It works fine for python 2. Also works fine when using sexpr().

**Comment by wintersteiger** [comment]
I fixed that piece of code yesterday (in 5e37cf9bbfbefc4aac24127ba7a7d8a1cc192f44), so before going further please upgrade to the latest master branch.

**Comment by JoBaehr** [comment]
Thanks, just updated, works fine now.
