### ISSUE TITLE
Debug branch: multi-threading z3 assertion violation at nla_core.cpp:433

### ISSUE THREAD

**Issue by rainoftime** [Z3Prover/z3#3408]
Hi, for the following instance,
[nla_core433.txt](https://github.com/Z3Prover/z3/files/4353196/nla_core433.txt)

Z3 debug branch  (Commit 9b58b77) throws out an assertion violation:
~~~~
File: ../src/math/lp/nla_core.cpp
Line: 433
!ineq_holds(ineq(cmp, t, rs))
File: ../src/math/lp/nla_core.cpp
Line: 433
!ineq_holds(ineq(cmp, t, rs))
~~~~

The parameter are 
~~~~
(set-option :smt.phase_selection 0)
(set-option :smt.threads 2)
;....

(check-sat-using (then simplify propagate-values dom-simplify ctx-solver-simplify))
~~~~

Related issue: https://github.com/Z3Prover/z3/issues/3318

**Comment by NikolajBjorner** [comment]
probably sign related, and in particular in nla_order_lemmas.cpp, where vars() are accessed directly without considering the sign of the monomial.

    const rational mult_val = val(ac.vars()[0]) * val(ac.vars()[1]);

**Comment by NikolajBjorner** [comment]
this stopped reproducing
