### ISSUE TITLE
push changing behavior of tautology

### ISSUE THREAD

**Issue by catalin-hritcu** [Z3Prover/z3#341]
We've been debugging some strange behavior in F* and minimized it to something really small:
```
(set-option :smt.mbqi false)
(push)
(assert (not (exists ((@x2 Int)) (= 42 @x2) )))
(check-sat)
```
Without the `(push)` in the second line z3 4.4.1 returns `unsat` on this, but with the `(push)` it returns `unknown`. This change of behavior seems really strange to us, is there any good reason for it?

**Comment by wintersteiger** [comment]
Because no logic is specified, Z3 assumes the worst case and disables many simplifiers that could perhaps be unsound in an incremental context. Adding `(set-logic AUFLIA)` or enabling MBQI will solve this particular problem, but that's not a long-term solution. We'll probably be able to fix this by setting some option, but I haven't found the right one yet.

**Comment by NikolajBjorner** [comment]
You could enable quantifier elimination in incremental mode to deal with such formulas.

**Comment by catalin-hritcu** [comment]
@wintersteiger  Thank you for explaining, it makes sense. This example is mostly an artifact of a (now fixed) bug in an F* library and of the minimization process. So I guess at this point it suffices for us to know when minimizing that files without any push are treated differently than files with pushes. The files F* produces always have pushes, so outside minimization this shouldn't matter.

@NikolajBjorner  Just curious, what would be the command to "enable quantifier elimination in incremental mode"?

Also, some of the guys in Cambridge (Nuno and Andrey via Antoine) suggest (beyond using `set-logic`) to specify the tactic of `check-sat`. Interestingly, in this case `(check-sat-using smt)` works even with the push, but `(check-sat)` doesn't.

**Comment by NikolajBjorner** [comment]
quantifier elimination in incremental mode is as a matter of fact deprecated. 
So you can only really solve these examples in non-incremental mode.
