### ISSUE TITLE
Debug branch: :smt.phase_selection Soundness bug for LIA formula 

### ISSUE THREAD

**Issue by muchang** [Z3Prover/z3#3415]
Hi,
For this formula:
```
(set-option :smt.phase_selection 5)                                        
(assert (forall ((a Int)) 
(exists ((b Int)) 
(forall ((c Int)) 
(or (distinct (* 13 a) c) (forall ((bb Int)) (xor (distinct (* 192 bb) c) (<= 4 b)))))))) (check-sat)     
```
Z3 debug branch  gives an incorrect answer:
```
$ z3debug/build/z3 small.smt2
sat
$ cat small.smt2 
(set-option :smt.phase_selection 5)                                        
(assert (forall ((a Int)) 
(exists ((b Int)) 
(forall ((c Int)) 
(or (distinct (* 13 a) c) (forall ((bb Int)) (xor (distinct (* 192 bb) c) (<= 4 b)))))))) (check-sat)            
$ CVC4/build/bin/cvc4 -q small_without_opts.smt2 
unsat
$ cat small_without_opts.smt2
(assert (forall ((a Int)) 
(exists ((b Int)) 
(forall ((c Int)) 
(or (distinct (* 13 a) c) (forall ((bb Int)) (xor (distinct (* 192 bb) c) (<= 4 b)))))))) (check-sat)
```

OS: Ubuntu 18.04
Commit: 9b58b77

**Comment by NikolajBjorner** [comment]
The cut generation seems suspicious.
The cut lemmas should be valid, and therefore include relevant bounds on variables.
It is not the case for the theory lemmas that are produced from cuts.

-------- [arith] smt::theory_lra::imp::check_lia ..\src\smt\theory_lra.cpp:2056 ---------
new cut:
(declare-fun a!0 () Int)
(declare-fun bb!2 () Int)
(assert (not (<= (+ (* 192 bb!2) (* (- 13) a!0)) (- 13))))
(check-sat)

The lemmas produced by the arithmetic solver should all be unsat:

z3 3415.smt2 /v:1 /st smt.arith.dump_lemmas=true

Several lemmas are not, such as lemm_49.smt2, which is shown in the log above.

**Comment by levnach** [comment]
Fixed by porting gomory.cpp from master branch 7c3d9bec48319e7bb81140fc96420a1c7413a291
