### ISSUE TITLE
Memory leak with skolem functions

### ISSUE THREAD

**Issue by nunoplopes** [Z3Prover/z3#342]
Z3 leaks memory with the attached file [FN7SXZ.txt](https://github.com/Z3Prover/z3/files/45190/FN7SXZ.txt):
```
$ z3.exe -t:100 FN7SXZ.smt2
unknown
ast_manager LEAKED: 8
Leaked: decl z3.sk.15 :: bv[32]
Leaked: decl z3.sk.15 :: bv[32]
z3.sk.15
Leaked: Bool
Leaked: decl z3.sk.15 :: bv[32]
(= z3.sk.15 bv[2:32])
Leaked: Leaked: Leaked: bv[2:32]
Leaked: bv
```

I couldn't figure out why the leak happens.  The equality expression is created in model_checker::add_blocking_clause(), but doesn't seem to leak there.

**Comment by wintersteiger** [comment]
Since you're using -t:100, is this leak only reported when the timeout is reached, or can you see it without the timeout as well?

**Comment by nunoplopes** [comment]
Found the damn bug: it would sometimes create a new equality but not use it, and therefore the equality would stay around with ref_count = 0.
