### ISSUE TITLE
Assertion violation at old_vector.h:375 for QF_NRA opt formula

### ISSUE THREAD

**Issue by rainoftime** [Z3Prover/z3#3421]
Previously, a similar issue was fixed https://github.com/Z3Prover/z3/issues/3401

Hi, for the following instance,
[old_vector375.txt](https://github.com/Z3Prover/z3/files/4357483/old_vector375.txt)

z3 master branch (Commit https://github.com/Z3Prover/z3/commit/5cbcd9a88ad5f5f259be8066c854c9bddd4327db) throws an assertion violation
~~~~
File: ../src/util/old_vector.h
Line: 375
idx < size()
~~~~

**Comment by NikolajBjorner** [comment]
could you just paste in the instance under "triple quotes":

```
instance
```
