### ISSUE TITLE
Debug Branch: Soundness Bug with unsat_core=true smt.phase_selection=5

### ISSUE THREAD

**Issue by wintered** [Z3Prover/z3#3446]
```
[954] % z3debug unsat_core=true smt.phase_selection=5 small.smt2
unsat
[955] % z3 small.smt2
sat
[956] % z3debug small.smt2
sat
[957] % 
[957] % cat small.smt2
(declare-fun a () Int)
(declare-fun b () Int)
(declare-fun c () Int)
(declare-fun d () Int)
(declare-fun e () Int)
(assert (= 0 (- c)))
(assert (> (- 1 a (- b)) (* 205 d e)))
(assert (= (* 98 a) (* 133 (+ 215 b))))
(assert (and (>= (* a b) 1) (<= (* e d) 7)))
(check-sat)
[958] % 
```
OS: Ubuntu 18.04
Commit: ceb2849

**Comment by NikolajBjorner** [comment]
z3 3446.smt2 unsat_core=true smt.phase_selection=5 smt.random_seed=1
sat
z3 3446.smt2 unsat_core=true smt.phase_selection=5 smt.random_seed=2
sat
z3 3446.smt2 unsat_core=true smt.phase_selection=5 smt.random_seed=3
sat
z3 3446.smt2 unsat_core=true smt.phase_selection=5 smt.random_seed=4
sat
z3 3446.smt2 unsat_core=true smt.phase_selection=5 smt.random_seed=5
sat
z3 3446.smt2 unsat_core=true smt.phase_selection=5 smt.random_seed=6
sat
z3 3446.smt2 unsat_core=true smt.phase_selection=5 smt.random_seed=7
sat
z3 3446.smt2 unsat_core=true smt.phase_selection=5 smt.random_seed=8
sat
z3 3446.smt2 unsat_core=true smt.phase_selection=5 smt.random_seed=9
sat
z3 3446.smt2 unsat_core=true smt.phase_selection=5 smt.random_seed=10
sat
z3 3446.smt2 unsat_core=true smt.phase_selection=5 smt.random_seed=11
sat
z3 3446.smt2 unsat_core=true smt.phase_selection=5 smt.random_seed=12
sat
z3 3446.smt2 unsat_core=true smt.phase_selection=5 smt.random_seed=13
sat
z3 3446.smt2 unsat_core=true smt.phase_selection=5 smt.random_seed=14
sat
z3 3446.smt2 unsat_core=true smt.phase_selection=5 smt.random_seed=15
sat
z3 3446.smt2 unsat_core=true smt.phase_selection=5 smt.random_seed=16
sat
z3 3446.smt2 unsat_core=true smt.phase_selection=5 smt.random_seed=17
sat
z3 3446.smt2 unsat_core=true smt.phase_selection=5 smt.random_seed=18
sat
z3 3446.smt2 unsat_core=true smt.phase_selection=5 smt.random_seed=19

etc
