### ISSUE TITLE
Assertion violations in math/lp/lp_primal_core_solver_def.h:1299 and util/old_vector.h:370

### ISSUE THREAD

**Issue by wintered** [Z3Prover/z3#3471]
Consider the formula [bug.smt2](https://github.com/Z3Prover/z3/files/4366377/bug.txt) that causes two different assertion violations when feed to Z3. There were recently closed issue these two assertion violations (cf. #3344, #3304, #2930 and #2955). 
 
```
% z3-8717c7d smt.threads=2 bug.smt2
ASSERTION VIOLATION
File: ../src/math/lp/lp_primal_core_solver_def.h
Line: 1299
!this->use_tableau()
(C)ontinue, (A)bort, (S)top, (T)hrow exception, Invoke (G)DB
ASSERTION VIOLATION
File: ../src/util/old_vector.h
Line: 370
idx < size()
(C)ontinue, (A)bort, (S)top, (T)hrow exception, Invoke (G)DB
```

OS: Ubuntu 18.04
Commit: 8717c7d

**Comment by NikolajBjorner** [comment]
doesn't seem to reproduce. Threads might provide some entropy, but smt.random_seed=NNN has been shown to be a good deterministic substitute in the past.
