### ISSUE TITLE
Assertion violation at util/old_vector.h: 370

### ISSUE THREAD

**Issue by wintered** [Z3Prover/z3#3499]
```
[1114] % z3 small.smt2
ASSERTION VIOLATION
File: ../src/util/old_vector.h
Line: 370
idx < size()
(C)ontinue, (A)bort, (S)top, (T)hrow exception, Invoke (G)DB
a
[1115] % 
[1115] % cat small.smt2
(define-sort FPN () (_ FloatingPoint 11 2))
(declare-fun a () FPN)
(declare-fun b () FPN)
(declare-fun c () FPN)
(assert (= (fp.add roundTowardNegative a b) c))
(check-sat)
[1116] % 
```
OS: Ubuntu 18.04
Commit: 8717c7d

**Comment by NikolajBjorner** [comment]
@wintersteiger could you review fix?

**Comment by wintersteiger** [comment]
Thanks for the fix! That's an OK solution, but the exception message is a bit misleading. We do support non-standard sizes (as SMT-LIB requires), but within "reasonable" limits. Huge exponents (including in intermediate values) are not supported (we use a 64-bit int to keep them) and there are lower limits on the numbers of bits. 

This particular case is unusual in that the number of exponent bits is larger than the number of significant bits, which isn't well tested, and in that the number of significant bits is exactly 2, which is a weird corner-case for which I may have to add an explicit exception.
