### ISSUE TITLE
Compiling a to a statically linked binary

### ISSUE THREAD

**Issue by heyLu** [Z3Prover/z3#35]
With a tiny change to the build system it's possible to compile to a statically linked binary.  The issue is that `-lrt` needs to appear before `-lpthread` in the linker options on linux. Here's a fix that allows that:

```
diff --git a/scripts/mk_util.py b/scripts/mk_util.py
index 4641a7b..3ece506 100644
--- a/scripts/mk_util.py
+++ b/scripts/mk_util.py
@@ -1613,7 +1613,7 @@ def mk_config():
         config.write('LINK=%s\n' % CXX)
         config.write('LINK_FLAGS=\n')
         config.write('LINK_OUT_FLAG=-o \n')
-        config.write('LINK_EXTRA_FLAGS=-lpthread %s\n' % LDFLAGS)
+        config.write('LINK_EXTRA_FLAGS=%s -lpthread\n' % LDFLAGS)
         config.write('SO_EXT=%s\n' % SO_EXT)
         config.write('SLINK=%s\n' % CXX)
         config.write('SLINK_FLAGS=%s\n' % SLIBFLAGS)
```

With the change applied, the following steps allow building the statically linked binary:

- `LDFLAGS="-static-libstdc++ -static-libgcc -static" CXXFLAGS="-static-libstdc++ -static-libgcc -static" python2 scripts/mk_make.py`
- `cd build; make -j4` as usual

The motivation for linking statically is to make it easy to pass around the binary and to be able to use it in small docker images, such as [wunderseltsam/constraint-solvers](https://registry.hub.docker.com/u/wunderseltsam/constraint-solvers/).

I'd be happy to submit a pull-request against `master` or `unstable` if the change is useful.

**Comment by wintersteiger** [comment]
We've had the --staticlib flag to mk_make.py for some time, does that not work anymore?

Also, is there any documentation on -lrt necessarily having to be included before -lposix? Otherwise we should run some tests on all platforms to see what else breaks.

**Comment by heyLu** [comment]
I didn't know that --staticlib existed, so I tried the above first. --staticlib still works. However, I wanted a statically linked binary, not just the library. It is something of an edgecase, but it's useful, especially for using it in docker containers and other systems that you don't want to compile on. (While it is possible to distribute the dynamically linked binary, it's not as simple, because you have to include quite a few libraries, including libstdc++.)

I haven't found anything official, just a post [on the GHC mailing list](https://mail.haskell.org/pipermail/ghc-devs/2013-January/000146.html) where someone had the same problem. It seems only to occur when statically linking and I'm guessing it's also glibc specific, because libpthread and librt both are part of the glibc package on my system.

**Comment by wintersteiger** [comment]
To me this issue seems too system specific to include it in the main distribution; those flags and libraries are different on all platforms (i.e., Windows, OSX, and BSD all have different options and libraries). I think this is something best left to the end user, because only they know exactly what platform they need to run the binaries on. If we add new flags to the build scripts, then we have to support all those platforms, which is considerable effort with very little benefit. Thus I'm closing this issue, but if you would like to work this out so that it works on all the platforms, then please do submit a PR!
