### ISSUE TITLE
SMT-LIB2 Log Empty File

### ISSUE THREAD

**Issue by baierd** [Z3Prover/z3#3513]
Setting the `smtlib2_log` param in a solver (in the Java-wrapper) does not write anything to the set file.
I tried writing to the file beforehand and setting the file as `Log`, which worked for the Z3 specific log.
I tested on Ubuntu 18.04 and Arch.
Is there an option i am missing to activate smtlib2 logging or is it a bug?

**Comment by NikolajBjorner** [comment]
seems not to have been picked up consistently.
The following two ways work now:

```
from z3 import *
# Approach 1: as global
#set_param("solver.smtlib2_log", "l1.smt2")
s = Solver()
# Approach 2: on the solver object
#s.set("smtlib2_log", "l2.smt2")

x = Int('x')
s.add(True)
s.add(False)
s.add(x*x < 1)
print(s.check())


```
