### ISSUE TITLE
native support for strings and regexes

### ISSUE THREAD

**Issue by PierreVDL** [Z3Prover/z3#353]
Many problems also include strings: 
e.g. for a password to be valid it should satisfy some constraints.
and the string output of a system must match a particular regular expression.

I would like Z3 to solve string problems as well.
Furthermore, I would like that the string operations are standardized 
(such that I can start multiple smt-lib compatible problem solvers and take the first one with an answer).
So, please also look at activities of other problem solver, such as CVC4: http://cvc4.cs.nyu.edu/wiki/Strings

Note that Z3 already has an add on to support strings: z3str2 (see https://sites.google.com/site/z3strsolver/)
However, this addon can only be build on linux platforms.

**Comment by wintersteiger** [comment]
We are not in charge of the SMT standard. A new theory of strings is being developed but hasn't been finished. Another (internal) module for strings exists, but is not fit for integration yet. We know of the situation, but it will take considerable time until we will be able to tackle this. Of course, external contributions are always welcome!

**Comment by NikolajBjorner** [comment]
There is now basic support for main string/regex and sequence operations using compatible syntax.
