### ISSUE TITLE
arith.solver changes the result of a satisfiability check

### ISSUE THREAD

**Issue by rainoftime** [Z3Prover/z3#3539]
Hi, for the following formula
~~~~
(set-logic ALL)
(declare-const v0 Bool)
(declare-const v2 Bool)
(declare-const v3 Bool)
(declare-const v6 Bool)
(declare-const r5 Real)
(declare-const r7 Real)
(check-sat)
(declare-const bv_17-0 (_ BitVec 17))
(assert (xor (> 817.0 817.0 r5 r7) (> 86223.1 817.0 r7 r5) (= bv_17-0 bv_17-0 bv_17-0) (> 817.0 817.0 r5 r7) (distinct v2 (distinct v6 v0) v3  (> 86223.1 817.0 r7 r5))))
(assert (not (exists ((q1 (_ BitVec 12)) (q2 Int) (q3 Real) (q4 Bool)) (xor (distinct (to_int 86223.1) 468) (distinct q1 #x136 q1) (not q4) (<= (abs (/ r7 r7)) 0.47 q3 0.6710657415 r5)))))
(check-sat)
~~~~
The final `(check-sat)` returns "unknown". 

After adding `(get-info :reason-unknown)`, z3 (commit 907d3106) gives the information "(:reason-unknown "(incomplete (theory arithmetic))")".

Then I tried two modifications:
- By removing the first (check-sat), z3 can solve successfully.
- By adding the option `(set-option :smt.arith.solver 6)`.  z3 can also solve successfully.

@NikolajBjorner Maybe z3 should automatically select `smt.arith.solver 6` for some incremental and non-linear instances?

**Comment by NikolajBjorner** [comment]
We want to use arith.solver=6 as the default solver. This is the plan.
Thanks to the heavy testing of the debug branch by you and others it is definitely more stable.
It still isn't at parity across the board so changing the defaults will break a lot of user scenarios.
