### ISSUE TITLE
AUFLIA Soundness Bug

### ISSUE THREAD

**Issue by Heizmann** [Z3Prover/z3#354]
Using 3f02beb8203bb4bf68e39a168254fc97e8f75338 I obtain *sat* on the following script
http://xayn.heizmann.name/owncloud/index.php/s/NHaQgwshl8g4cid
However, I expect the result *unsat* because I our tool asserted a ``distinct`` of two similar terms.
I checked the result also with CVC4 and Princess. Both return the result *unsat*.

**Comment by Heizmann** [comment]
I found a simpler script that probably triggers the same bug (I incorrectly obtain *sat*).
http://xayn.heizmann.name/owncloud/index.php/s/5xlXBaYA2LMCGbM

**Comment by NikolajBjorner** [comment]
Tough to track down. It boils down to the array theory not propagating select over ite expressions in a complete way. When I check in this fix, this example will diverge using the default configuration parameters. You can use "auto_config=false, smt.mbqi=false" to disable mbqi. Then the example is shown unsat almost instantaneously.

**Comment by NikolajBjorner** [comment]
Pull request for fixes has been merged now

**Comment by Heizmann** [comment]
Thanks. 
Unfortunately, I cannot remember which verification problem processed by our tool (Ultimate Automizer) revealed the bug. But I run several testsuites of our tool using the current Z3 version and it seems that the problem is gone.
The questions whether to use MBQI or not is indeed interesting for us. We have several benchmarks that we can only solve with MBQI and several that can be only solved without MBQI. At this years' SV-COMP our compromise was to use MBQI, but to set the timeout to 2s (-t:2000).
However, I never evaluated carefully if this was the best choice
