### ISSUE TITLE
OCaml bindings for mk_fpa_max mk_fpa_min acting weird.

### ISSUE THREAD

**Issue by johndoe888** [Z3Prover/z3#358]
I use the following code to get the minimum of two numbers (in this case the same number twice).

```
let _ =
  try
    let ctx = Z3.mk_context [] in
    let ft = Z3.FloatingPoint.mk_sort_32 ctx in 
    let t1 = Z3.FloatingPoint.mk_numeral_f ctx 0.5 ft in
    let t2 = Z3.FloatingPoint.mk_min ctx t1 t1 in
    let t3 = Z3.FloatingPoint.mk_eq ctx t1 t2 in 
    let solver = Z3.Solver.mk_simple_solver ctx in
    let result = Z3.Solver.check solver [t3] in
    let s = 
      match result with
      | Z3.Solver.SATISFIABLE -> "sat"
      | Z3.Solver.UNSATISFIABLE -> "unsat"
      | Z3.Solver.UNKNOWN -> "unknown"
    in
    Printf.printf "Test Z3: The check yields: %s\n" s
  with
  | Z3native.Exception exn -> Printf.printf "Test Z3: Z3native.Exception: %s\n" exn
  | _ -> Printf.printf "Test Z3: failed\n"
```
Unfortunately Z3 reports unknown for this code. This can't be right, can it?

Another weird message pops up using the same code to get the max of two (identical) numbers:
```
let _ =
  try
    let ctx = Z3.mk_context [] in
    let ft = Z3.FloatingPoint.mk_sort_32 ctx in 
    let t1 = Z3.FloatingPoint.mk_numeral_f ctx 0.5 ft in
    let t2 = Z3.FloatingPoint.mk_max ctx t1 t1 in
    let t3 = Z3.FloatingPoint.mk_eq ctx t1 t2 in 
    let solver = Z3.Solver.mk_simple_solver ctx in
    let result = Z3.Solver.check solver [t3] in
    let s = 
      match result with
      | Z3.Solver.SATISFIABLE -> "sat"
      | Z3.Solver.UNSATISFIABLE -> "unsat"
      | Z3.Solver.UNKNOWN -> "unknown"
    in
    Printf.printf "Test Z3: The check yields: %s\n" s
  with
  | Z3native.Exception exn -> Printf.printf "Test Z3: Z3native.Exception: %s\n" exn
  | _ -> Printf.printf "Test Z3: failed\n"
```
Now Z3 throws an Exception "Z3native.Exception: invalid argument".
          
I have no clue why min and max behave differently in the first place. 
Next thing is why unknown or an Exception pops up. 
All other tests I ran seemed to be fine 
(I have written tests for almost all the floating point operations).

I am running Debian (Linux version 3.16.0-4-amd64) and Z3 4.4.2 
(downloaded and compiled today without problems). 
I also tried with Z3 4.4.0 and got the same output.

Any suggestions that might help to solve this are appreciated.

**Comment by wintersteiger** [comment]
min and max are unspecified if the inputs are +zero and -zero (or vice versa) which complicates things considerably (and min/max are the only core functions that to that, some of the other conversions to other theories do too).

**Comment by johndoe888** [comment]
Thank you for the comments. I have seen a discussion w.r.t. +/- zero and min/max in the issues here. 

In the case posted above there are no zeroes involved (at least from my point of view). 
Comparing two different numbers (like 1/2 and 1/4) does not change the outcome considerably. 

Even if there is a problem with unspecified inputs, I still do not understand why the 
"invalid argument" exception is thrown.

Is this reproducable at other installations?

**Comment by wintersteiger** [comment]
Probably because some kind of bug. Currently working on the broken build scripts for ocaml so I can build your program...

**Comment by wintersteiger** [comment]
There is a problem with the first input program and Z3 reports the correct error message `WARNING: an assumption must be a propositional variable or the negation of one`, which is because of this line:

    let result = Z3.Solver.check solver [t3] in

The argument `[t3]` here are _not_ the assertions that the solver will check. This argument is supposed to contain only _assumptions_, which must be Boolean literals only (for incremental and unsat-core use). Assertions need to be added to the solver via Z3.Solver.add before calling check, for instance like this:

    ...
    Z3.Solver.add solver [t3];
    let result = Z3.Solver.check solver [] in
    ...

The result is then `sat` as expected.

**Comment by wintersteiger** [comment]
The second problem was due to a bug in `Z3_mk_fpa_max` which is now fixed.

**Comment by johndoe888** [comment]
Just ran a test of your bugfix. Works fine. Thanks a lot.

**Comment by wintersteiger** [comment]
Great, thanks for letting us know!
