### ISSUE TITLE
Linux build tries to compile the dotnet api

### ISSUE THREAD

**Issue by LeventErkok** [Z3Prover/z3#359]
Trying to build Z3 on linux, I end up getting errors:

```
../src/api/dotnet/AST.cs(118,49): error CS1644: Feature `generics' is not supported in Mono mcs1 compiler. Consider using the `gmcs' compiler instead                                                  
```

I suppose the dotnet stuff should just not be attempted unless we're on Windows?

I'm compiling like this:

```
git pull
/bin/rm -rf build
python scripts/mk_make.py
cd build
make
make install
```

**Comment by wintersteiger** [comment]
This is a recent addition. By default the .NET bindings are produced on Windows and when mono compiler is found. Could you tell us which variety of mcs you are using?

**Comment by NikolajBjorner** [comment]
This is a regression from integrating #340, which enables Mono on non-Windows platforms.
You should be able to work around for the time being by adding --nodotnet (or -n) 
option to the build script.

**Comment by LeventErkok** [comment]
Ah, good point. I was using mcs 2.6.4. I had 4.0.2.0 lying around as well; so switching to it fixed the problem. I understand even 4.0.2.0 isn't the latest either, but it manages to compile as well.

**Comment by wintersteiger** [comment]
Great, thanks for updating us!
