### ISSUE TITLE
Invalid model for incremental QF_BV instance

### ISSUE THREAD

**Issue by rainoftime** [Z3Prover/z3#3590]
Hi, for the followin formula,
~~~~
(set-logic QF_BV)
(set-option :model_validate true)
(set-option :parallel.enable true)
(declare-const v1 Bool)
(declare-const v4 Bool)
(assert (=> v4 v1))
(check-sat)
(check-sat)
~~~~

z3 (commit 9be7bda69a) gives an invalid model for the second check command.

**Comment by rainoftime** [comment]
Another instance
~~~~
(set-logic QF_BV)
(set-option :model_validate true)
(set-option :parallel.enable true)
(declare-const v0 Bool)
(declare-const v4 Bool)
(assert (or v0 v4))
(check-sat)
(check-sat)
~~~~

**Comment by zhendongsu** [comment]
Should be a dup of https://github.com/Z3Prover/z3/issues/3576

**Comment by rainoftime** [comment]
@zhendongsu  Since the theory type is different, I am not sure if the root cause the same.
If I see more formulas of different theories encounter this problem (under the same parameter), I will append to that issue. Is this OK?

**Comment by zhendongsu** [comment]
The different theories seem irrelevant for the option (set-option :parallel.enable true), but Nikolaj will for sure let us know.

**Comment by NikolajBjorner** [comment]
It is a duplicate. Would be great to have less noise.
There were many different kind of duplicates the past two days.
