### ISSUE TITLE
Incorrect objective values with real optimization

### ISSUE THREAD

**Issue by LeventErkok** [Z3Prover/z3#3595]
For this benchmark:

```
(set-option :produce-models true)
(set-logic ALL)
(declare-fun x () Real)
(assert (and (> x (/ 16.0 5.0)) (< x (/ 127.0 10.0))))
(minimize x)
(maximize x)
(set-option :opt.priority box)
(check-sat)
(get-objectives)
```

z3 used to produce (about a month ago):

```
sat
(objectives
 (x (+ (/ 16.0 5.0) epsilon))
 (x (+ (/ 127.0 10.0) (* (- 1.0) epsilon)))
)
```

which is correct. But it now produces:

```
sat
(objectives
 (x (/ 21.0 5.0))
 (x (/ 21.0 5.0))
)
```

Looks like perhaps the objectives aren't quite correctly updated? (`x` in the objectives see to be a satisfying element, but not actual objective values.)

**Comment by NikolajBjorner** [comment]
there is no optimal value for this. Producing epsilons is a best effort basis.

**Comment by LeventErkok** [comment]
Thanks @NikolajBjorner 

I guess I'm quite confused then what `:opt.priority box` means. My understanding was it would essentially do optimization independently for `maximize`/`minimize` command. So, the above would be equivalent to making two separate calls, issuing one of `max`/`min` each time. Is that not the case?

I'm using this sort of `maximize`/`minimize` in the same benchmark with `box` priority to essentially get upper-lower bounds on variables. This used to work really well so far. Should I instead be making two separate calls?

**Comment by vst** [comment]
> My understanding was it would essentially do optimization independently for each `maximize`/`minimize` command in the file.

I am struggling with the same. @LeventErkok Do you have any insight into this now?

---

PS: I am an [sbv]-groupie :vulcan_salute:. So, I assumed that `mapM`ing `SBV.optimize` over individual objectives is the same as a single `SBV.optimize` call with `SBV.Independent` style and all objectives at once. I never compared produced values, but I noticed that my assumption was wrong when I realized the latter hangs for some (tough) problems.

Then, I found the [Independent Objectives] example on the official z3 guide. Results change both when:

1. Removing an objective, and
2. Re-ordering objectives.

[SBV]: https://hackage.haskell.org/package/sbv
[Independent Objectives]: https://microsoft.github.io/z3guide/docs/optimization/combiningobjectives/#independent-objectives
