### ISSUE TITLE
Push changes sat to unsat

### ISSUE THREAD

**Issue by agacek** [Z3Prover/z3#360]
I'm using Z3 version 4.4.1 on Windows. This file below has a single query which should be SAT. However, Z3 reports it as UNSAT. If you comment out the push statement on line 140, Z3 then correctly reports SAT.

  https://gist.github.com/agacek/d034f1211a68fa4f2524

**Comment by NikolajBjorner** [comment]
Thanks, but I can't reproduce it on the current version:
C:\z3\debug>z3 -version
Z3 version 4.4.2

**Comment by agacek** [comment]
Thanks for the quick response. Is there an easier way to get version 4.4.2 on Windows besides building it?

**Comment by NikolajBjorner** [comment]
Try https://github.com/Z3Prover/bin/tree/master/nightly

**Comment by agacek** [comment]
Thanks! I never knew out about that repository. It will be very useful going forward. I can confirm that the bug doesn't happen in the latest nightly.
