### ISSUE TITLE
Soundness bug with smt.clause_proof=true

### ISSUE THREAD

**Issue by wintered** [Z3Prover/z3#3629]
Hi,
the following trace shows a soundness bug in Z3 if smt.clause_proof=true option is used.
Is the use of the smt.clause_proof=true option expected in this context?
```
[639] % cvc4 --quiet small.smt2
unsat
[640] % z3 smt.clause_proof=true small.smt2
sat
[641] % z3 small.smt2
unknown
[642] % 
[642] % cat small.smt2
(assert (= (sin 1.0) 0.0))
(check-sat)
[643] %
```

OS: Ubuntu 18.04
Commit: 7ada20c

**Comment by NikolajBjorner** [comment]
duplicate
