### ISSUE TITLE
mk_unix_dist.py is kind of pointless

### ISSUE THREAD

**Issue by delcypher** [Z3Prover/z3#365]
The proper way to build a distributable tarball is to do something like

```
$ python scripts/mk_make.py <flags to enable bindings>
$ cd build
$ make
$ mkdir staged
$ make DESTDIR=`readlink -f staged` install
$ tar -C staged -czvf z3.tar.gz .
```

The newly added ``DESTDIR`` support makes a lot of the existing python code ``mk_unix_dist()`` a bit pointless because now creating a distributable is basically the same as doing a staged install but then tarballing the result.

**Comment by wintersteiger** [comment]
So? Fell free to propose an update to the script. Our automatic builds call mk_unix_dist, but as you say, it may not be as complicated as it used to be.

Note that mk_unix_dist also enables githash versioning in the binaries and zip files and it automatically checks for 32/64 bit systems. So all in all, that file wouldn't get much shorter I think.

**Comment by wintersteiger** [comment]
Closing this for now. It may make sense to revisit this question when we switch to a new build system/infrastructure.
