### ISSUE TITLE
Fractional powers and even roots yield negative numbers

### ISSUE THREAD

**Issue by dgenin** [Z3Prover/z3#366]
Running Z3 on the following sequence of propositions

`(declare-const x Real)`
`(assert (= 1 (^ x (/ 1 2))))`
`(check-sat-using qfnra-nlsat)`
`(get-model)`
`(eval (= 1 (^ x (/ 1 2))))`

produces

`sat`
`(model`
`    (define-fun x () Real`
`        (- 1.0)) `
`)`
`Z3(5, 25): ERROR: even root of negative number is not real`

Note that the final line simply evaluates the equation from line 2 on the proposed solution for x, so Z3 seems to contradict itself.

**Comment by NikolajBjorner** [comment]
This was fixed a few hours ago in the master branch.
