### ISSUE TITLE
qe, qe2, and qe_rec incomplete for QBF solving

### ISSUE THREAD

**Issue by rainoftime** [Z3Prover/z3#3674]
Hi, for the following formula
~~~~
(declare-const v3 Bool)
(assert (not (forall ((q10 Bool) (q11 Bool) (q12 Bool)) v3)))
(check-sat-using (then simplify qe_rec))
~~~~
The final (check-sat-using ...) returns "unknown".

After adding (get-info :reason-unknown), z3 b686bb61 returns `(:reason-unknown "incomplete")`

**Comment by rainoftime** [comment]
qe, qe2 also do not work

**Comment by rainoftime** [comment]
`(check-sat)`  works.
But by adding -v:15 or -v:100, I did not see information like "mbqi".

**Comment by NikolajBjorner** [comment]
the purpose of the "qe" tactics is to _eliminate_ quantifiers and produce an equivalent quantifier-free formula. They are not decision procedures. The check-sat-using ends up with a goal that isn't "true" or "false", but which is "v3". It takes a sat solver or something else to determine whether the trivial assertion v3 is satisfiable. 

It is more appropriate to _apply_ these tactics wen used as end-solvers.


```
C:\zzz\build>type 3674.smt2
(declare-const v3 Bool)
(assert (not (forall ((q10 Bool) (q11 Bool) (q12 Bool)) v3)))
(apply (then simplify qe_rec))
C:\zzz\build>z3 3674.smt2
(goals
(goal
  (not v3)
  :precision precise :depth 2)
)
```
