### ISSUE TITLE
Error in make install

### ISSUE THREAD

**Issue by rasoolmaghareh** [Z3Prover/z3#368]
Hi,

On Ubunutu 14.04 when running the following instructions on the latest version of Z3 from (https://github.com/Z3Prover/z3):

python scripts/mk_make.py
cd build
make
sudo make install

I receive this error:

make: *** No rule to make target api/ml/z3ml.cmxa', needed byinstall'. Stop.

Can you please let me know what the issue is?

**Comment by wintersteiger** [comment]
This has been fixed yesterday, please upgrade to the latest version from the master branch. If you configure (mk_make.py) without the --ml flag then there should not be any 'cmxa' in the Makefile.
