### ISSUE TITLE
Java API: expr.isInt() seems not to work as expr.isBool() or expr.isBV()

### ISSUE THREAD

**Issue by gapag** [Z3Prover/z3#370]
Hi!
Z3, 4.4.2. 
Java API.

I suspect this might be an error:
```java
System.out.println(ctx.mkIntConst("ico").isInt()); 
System.out.println(ctx.mkInt(4).isInt()); 
```
print respectively
```java
false
true
```
which seems not to respect the corresponding [C++ specification] (http://z3prover.github.io/api/html/classz3_1_1expr.html#ad5f0c356738a1efd67332e7c31aff42c); I am therefore inspecting the return value of getSort() to check if the expression is of Int sort, but I wonder if this was intentional.

Compare with analogous expressions for bitvector or boolean sort:
```java
System.out.println(ctx.mkBoolConst("bco").isBool());
System.out.println(ctx.mkBool(true).isBool());
System.out.println(ctx.mkBVConst("bvco",9).isBV());
System.out.println(ctx.mkBV(19,9).isBV());
```
print all `true`.

**Comment by wintersteiger** [comment]
Thanks for the bug report! That was indeed a bug in the multiple APIs but it should be fixed now.
