### ISSUE TITLE
Segmentation fault during Z3.FloatingPoint.get_*bits

### ISSUE THREAD

**Issue by johndoe888** [Z3Prover/z3#372]
There is a bug in Z3.FloatingPoint.get_ebits and Z3.FloatingPoint.get_sbits I stumbled
upon during a debugging session. Please see following code:

```
let _ =
    let ctx = Z3.mk_context [] in
    let term = Z3.Boolean.mk_true ctx in
    let result = Z3.FloatingPoint.get_ebits ctx (Z3.Expr.get_sort term) in
    Printf.printf "Test Z3: get_ebits: %d.\n" result
```
This will exit with "Segmentation fault".

I know, the usage of get_ebits is wrong. But maybe there is some better way to tell the user
that a Boolean has no ebits or sbits.

**Comment by wintersteiger** [comment]
Thanks for your report! The argument validation wasn't very good in the FPA API, but I have now added a bunch of checks so we'll get nicer exceptions/errors without segfaulting. I haven't had much time for tests yet, so I'll leave this issue open for now.

**Comment by wintersteiger** [comment]
This should be fixed now, so I'm closing the issue.
