### ISSUE TITLE
Non-deterministic assertion violation at ../src/math/lp/lar_solver.cpp:409

### ISSUE THREAD

**Issue by rainoftime** [Z3Prover/z3#3725]
Hi, for the following formula

[407.txt](https://github.com/Z3Prover/z3/files/4430789/407.txt)

z3 f447292 throws an assertion violation deterministically 
~~~~
ASSERTION VIOLATION
File: ../src/math/lp/lar_solver.cpp
Line: 407
is_zero(m_mpq_lar_core_solver.m_r_solver.m_costs[j])
(C)ontinue, (A)bort, (S)top, (T)hrow exception, Invoke (G)DB
ASSERTION VIOLATION
~~~~

In my PC (2.3 GHz), the timeout should be around 10 seconds.

**Comment by levnach** [comment]
Sorry, @rainoftime , what was the platform you were running it? I cannot reproduce it.

**Comment by rainoftime** [comment]
@levnach Ubuntu 16.04
BTW, I cannot compile z3 0fc8ebc8ccf on  Ubuntu 16.04

The error is 
~~~~
/src/ast/rewriter/poly_rewriter_def.h:744:34: error: expected primary-expression
TRACE("le_bug", tout << mk_pp(lhs, m()) << " " << mk_pp(rhs, m()) << "\n";)
....
~~~
Could you have a check? Thank you!

**Comment by levnach** [comment]
Sorry, just this comment this comment Trace out for the time being

Sent from a phone
________________________________

**Comment by NikolajBjorner** [comment]
@levnach was not involved in breaking the clang build

**Comment by levnach** [comment]
Does not reproduce for random seeds in the range 1-2000 on Ubuntu, 18.04

**Comment by rainoftime** [comment]
@levnach I still encounter the problem in z3 ae5a713e815e
