### ISSUE TITLE
Invalid model for QF_LIA formula (parallel)

### ISSUE THREAD

**Issue by rainoftime** [Z3Prover/z3#3737]
Hi,
For the following formula,
~~~~
(set-logic QF_FD)
(set-option :model_validate true)
(set-option :parallel.enable true)
(declare-const v0 Bool)
(declare-const v1 Bool)
(declare-const v2 Bool)
(declare-const v3 Bool)
(declare-const v5 Bool)
(declare-const v6 Bool)
(declare-const i3 Int)
(declare-const i4 Int)
(declare-const v7 Bool)
(declare-const i5 Int)
(declare-const i6 Int)
(declare-const v8 Bool)
(declare-const v10 Bool)
(assert (or (> 56 i3) v2 v1 v5 v3 v1 v8))
(assert (or (< 56 (- i4)) v5 (< i3 56)))
(assert (or (=> v1 (=> v2 v7)) v0 v5))
(assert v10)
(assert (= i5 i6))
(assert v8)
(assert (or v7 v1 v3))
(assert (or (< 56 (- i4)) v2 v5))
(assert v6)
(assert (or v3 (< 56 (- i4)) v1))
(assert (or v0 v0 (and v2 v5 v2)))
(check-sat)
~~~~

z3 f447292 gives an invalid model.

I guess that we cannot set the option QF_FD for int/real formula.
But when disabling `parallell`, z3 can return "unknown".
Maybe z3 should perform more formula type checking in the parallel mode?

**Comment by zhendongsu** [comment]
This and https://github.com/Z3Prover/z3/issues/3736 must have been the same issue (or the same non-issue) as https://github.com/Z3Prover/z3/issues/3733.  Perhaps there is no need to create new ones to avoid unnecessary traffic?

**Comment by rainoftime** [comment]
I will append the two test cases from https://github.com/Z3Prover/z3/issues/3736 and https://github.com/Z3Prover/z3/issues/3737 to https://github.com/Z3Prover/z3/issues/3733

Besides, I guess that 
this issue https://github.com/Z3Prover/z3/issues/3732 might also be the same with https://github.com/Z3Prover/z3/issues/3733.
