### ISSUE TITLE
make error:  no matching function for call to ‘smt::theory_seq::eq::eq

### ISSUE THREAD

**Issue by liuyuer** [Z3Prover/z3#376]
src/smt/theory_seq.cpp
../src/smt/theory_seq.cpp: In member function ‘bool smt::theory_seq::simplify_eq(expr*, expr*, smt::theory_seq::enode_pair_dependency*)’:
../src/smt/theory_seq.cpp:421:86: error: no matching function for call to ‘smt::theory_seq::eq::eq(expr_ref, expr_ref, smt::theory_seq::enode_pair_dependency*&)’
         m_eqs.push_back(eq(expr_ref(lhs[i].get(), m), expr_ref(rhs[i].get(), m), deps));
                                                                                      ^
../src/smt/theory_seq.cpp:421:86: note: candidates are:
In file included from ../src/smt/theory_seq.cpp:23:0:
../src/smt/theory_seq.h:103:13: note: smt::theory_seq::eq::eq(const smt::theory_seq::eq&)
             eq(eq const& other): m_lhs(other.m_lhs), m_rhs(other.m_rhs), m_dep(other.m_dep) {}
             ^
../src/smt/theory_seq.h:103:13: note:   candidate expects 1 argument, 3 provided
../src/smt/theory_seq.h:101:13: note: smt::theory_seq::eq::eq(expr_ref&, expr_ref&, smt::theory_seq::enode_pair_dependency*)
             eq(expr_ref& l, expr_ref& r, enode_pair_dependency* d):
             ^
../src/smt/theory_seq.h:101:13: note:   no known conversion for argument 1 from ‘expr_ref {aka obj_ref<expr, ast_manager>}’ to ‘expr_ref& {aka obj_ref<expr, ast_manager>&}’
../src/smt/theory_seq.cpp: In member function ‘expr_ref smt::theory_seq::expand(expr*, smt::theory_seq::enode_pair_dependency*&)’:
../src/smt/theory_seq.cpp:741:46: error: no matching function for call to ‘smt::theory_seq::solution_map::add_cache(expr*&, smt::theory_seq::expr_dep)’
     m_rep.add_cache(e, expr_dep(result, deps));
                                              ^
../src/smt/theory_seq.cpp:741:46: note: candidate is:
In file included from ../src/smt/theory_seq.cpp:23:0:
../src/smt/theory_seq.h:69:19: note: void smt::theory_seq::solution_map::add_cache(expr*, smt::theory_seq::expr_dep&)
             void  add_cache(expr* v, expr_dep& r) { m_cache.insert(v, r); }
                   ^
../src/smt/theory_seq.h:69:19: note:   no known conversion for argument 2 from ‘smt::theory_seq::expr_dep {aka std::pair<expr*, dependency_manager<scoped_dependency_manager<std::pair<smt::enode*, smt::enode*> >::config>::dependency*>}’ to ‘smt::theory_seq::expr_dep& {aka std::pair<expr*, dependency_manager<scoped_dependency_manager<std::pair<smt::enode*, smt::enode*> >::config>::dependency*>&}’
make: *** [smt/theory_seq.o] Error 1

**Comment by NikolajBjorner** [comment]
our build scripts have been sleeping.

**Comment by liuyuer** [comment]
Code never sleep. Thank you man! Enjoy your good dream!
