### ISSUE TITLE
[Python 3] `__hash__` is not inherited if `__eq__` is implemented

### ISSUE THREAD

**Issue by ice-phoenix** [Z3Prover/z3#377]
This makes most of the Z3 types unhashable and breaks `visitor.py` example.

Also, see the corresponding paragraph from the Python 3 reference:

> If a class that overrides `__eq__()` needs to retain the implementation of `__hash__()` from a parent class, the interpreter must be told this explicitly by setting `__hash__ = <ParentClass>.__hash__`.

**Comment by wintersteiger** [comment]
Sounds good. Do you happen to have a small test file so I can make sure it actually works after fixing it?

**Comment by wintersteiger** [comment]
As far as I can see, this is only true for Python 3.x, but not for 2.x, is that right, or do we need to do something lese for 2.x?

**Comment by wintersteiger** [comment]
This should now be fixed. Can you take another look to see whether it works for you too?
