### ISSUE TITLE
z3py fails to parse the 2015 SMT-COMP  benchmark "add_01_1_1_reduced.smt2"

### ISSUE THREAD

**Issue by zell08v** [Z3Prover/z3#382]
z3py fails to parse the 2015 SMT-COMP  benchmark "add_01_1_1_reduced.smt2" proposed by Alberto Griggio.

Command in python:  import z3; z3.parse_smt2_file("add_01_1_1_reduced.smt2")
Error message: <repr(<z3.BoolRef at 0x10bd7d320>) failed: z3types.Z3Exception: invalid argument>

File Content: (can also be downloaded from StarExec):
 
(set-logic QF_FP)
(set-info :smt-lib-version 2.0)
(set-info :category "crafted")
(set-info :source |Alberto Griggio <griggio@fbk.eu>. These benchmarks were used for the evaluation in the following paper: L. Haller, A. Griggio, M. Brain, D. Kroening: Deciding floating-point logic with systematic abstraction. FMCAD 2012. Real-numbered literals have been automatically translated by MathSAT|)
(set-info :status unknown)
;; MathSAT API call trace
;; generated on 05/20/15 17:24:51

(declare-fun |c::main::1::b!0@1#1| () (_ FloatingPoint 8 24))
(declare-fun |c::main::1::a!0@1#1| () (_ FloatingPoint 8 24))
(declare-fun |c::main::1::c!0@1#1| () (_ FloatingPoint 8 24))
(declare-fun |goto_symex::&92;guard#1| () Bool)
(define-fun _t_3 () RoundingMode RNE)
(define-fun _t_9 () (_ FloatingPoint 8 24) |c::main::1::a!0@1#1|)
(define-fun _t_10 () (_ FloatingPoint 11 53) ((_ to_fp 11 53) _t_3 _t_9))
(define-fun _t_12 () (_ FloatingPoint 11 53) (fp #b0 #b10000001000 #b1111010000000000000000000000000000000000000000000000))
(define-fun _t_13 () Bool (fp.lt _t_10 _t_12))
(define-fun _t_14 () (_ FloatingPoint 8 24) |c::main::1::b!0@1#1|)
(define-fun _t_15 () (_ FloatingPoint 8 24) |c::main::1::c!0@1#1|)
(define-fun _t_16 () (_ FloatingPoint 8 24) (fp.add _t_3 _t_14 _t_15))
(define-fun _t_17 () (_ FloatingPoint 8 24) (fp.add _t_3 _t_9 _t_16))
(define-fun _t_18 () (_ FloatingPoint 8 24) (fp.neg _t_17))
(define-fun _t_19 () (_ FloatingPoint 8 24) (fp.add _t_3 _t_9 _t_14))
(define-fun _t_20 () (_ FloatingPoint 8 24) (fp.add _t_3 _t_15 _t_19))
(define-fun _t_21 () (_ FloatingPoint 8 24) (fp.add _t_3 _t_18 _t_20))
(define-fun _t_23 () (_ FloatingPoint 8 24) (fp #b0 #b01111111 #b00000000000000000000000))
(define-fun _t_24 () Bool (fp.leq _t_21 _t_23))
(define-fun _t_26 () (_ FloatingPoint 11 53) (fp #b1 #b10000001000 #b1111010000000000000000000000000000000000000000000000))
(define-fun _t_27 () Bool (fp.lt _t_26 _t_10))
(define-fun _t_28 () Bool (and _t_13 _t_27))
(define-fun _t_29 () (_ FloatingPoint 11 53) ((_ to_fp 11 53) _t_3 _t_14))
(define-fun _t_30 () Bool (fp.lt _t_29 _t_12))
(define-fun _t_31 () Bool (and _t_28 _t_30))
(define-fun _t_32 () Bool (fp.lt _t_26 _t_29))
(define-fun _t_33 () Bool (and _t_31 _t_32))
(define-fun _t_34 () (_ FloatingPoint 11 53) ((_ to_fp 11 53) _t_3 _t_15))
(define-fun _t_35 () Bool (fp.lt _t_34 _t_12))
(define-fun _t_36 () Bool (and _t_33 _t_35))
(define-fun _t_37 () Bool (fp.lt _t_26 _t_34))
(define-fun _t_38 () Bool (and _t_36 _t_37))
(define-fun _t_39 () Bool (fp.leq _t_14 _t_9))
(define-fun _t_40 () Bool (and _t_38 _t_39))
(define-fun _t_41 () Bool (fp.leq _t_15 _t_14))
(define-fun _t_42 () Bool (and _t_40 _t_41))
(define-fun _t_43 () (_ FloatingPoint 8 24) (fp.neg _t_14))
(define-fun _t_44 () (_ FloatingPoint 8 24) (fp.add _t_3 _t_9 _t_43))
(define-fun _t_46 () (_ FloatingPoint 8 24) (fp #b0 #b01111011 #b10011001100110011001101))
(define-fun _t_47 () Bool (fp.leq _t_44 _t_46))
(define-fun _t_48 () Bool (and _t_42 _t_47))
(define-fun _t_49 () (_ FloatingPoint 8 24) (fp.neg _t_15))
(define-fun _t_50 () (_ FloatingPoint 8 24) (fp.add _t_3 _t_9 _t_49))
(define-fun _t_51 () Bool (fp.leq _t_50 _t_46))
(define-fun _t_52 () Bool (and _t_48 _t_51))
(define-fun _t_53 () (_ FloatingPoint 8 24) (fp.add _t_3 _t_14 _t_49))
(define-fun _t_54 () Bool (fp.leq _t_53 _t_46))
(define-fun _t_55 () Bool (and _t_52 _t_54))
(define-fun _t_56 () (_ FloatingPoint 11 53) ((_ to_fp 11 53) _t_3 _t_20))
(define-fun _t_57 () (_ FloatingPoint 11 53) (_ +oo 11 53))
(define-fun _t_58 () Bool (fp.lt _t_56 _t_57))
(define-fun _t_59 () (_ FloatingPoint 11 53) (_ -oo 11 53))
(define-fun _t_60 () Bool (fp.lt _t_59 _t_56))
(define-fun _t_61 () Bool (and _t_58 _t_60))
(define-fun _t_62 () Bool (and _t_55 _t_61))
(define-fun _t_63 () (_ FloatingPoint 11 53) ((_ to_fp 11 53) _t_3 _t_17))
(define-fun _t_64 () Bool (fp.lt _t_63 _t_57))
(define-fun _t_65 () Bool (fp.lt _t_59 _t_63))
(define-fun _t_66 () Bool (and _t_64 _t_65))
(define-fun _t_67 () Bool (and _t_62 _t_66))
(define-fun _t_68 () Bool (not _t_24))
(define-fun _t_69 () Bool (and _t_67 _t_68))
(assert _t_69)
(check-sat)

**Comment by wintersteiger** [comment]
As far as I can tell there is no file called "add_01_1_1_reduced.smt2" in SMTLIB, neither in the latest nor in the previous release. There is a file called "add_01_1_1.smt2" which has similar but different content. 

The file content pasted above is not legal SMT2 because of two reasons: 
 - `( FloatingPoint...` should be `(_ FloatingPoint...`
 - some occurrences of symbols are prefixed by `_` and some of them aren't, e.g., `_t_10` vs `t_10`

After fixes those two, the file parses fine for me.

**Comment by zell08v** [comment]
Sorry for some typos introduced when pasting the smt-lib file. But the issue still holds.  The file that triggers the issue can be found as 

/QF_FP/griggio/fmcad12/2042842/add_01_1_1.smt2 

located in Clark Barrett's site:   http://www.cs.nyu.edu/~barrett/smtlib/QF_FP_Hierarchy.zip 

The following is from my ipython console:

In [46]: z3.parse_smt2_file("add_01_1_1.smt2")
Out[46]: <repr(<z3.BoolRef at 0x10a0aae60>) failed: z3types.Z3Exception: invalid argument>

**Comment by wintersteiger** [comment]
Sorry, but I can't reproduce this error, in all settings everything works just fine for me (Python 2.7, 3.5, IPython 1.20 on top of Python 2.7, 3.5). Can you tell me more about your system?

**Comment by zell08v** [comment]
Probably you are right because when I use Z3 command line the issue disappears. So it only happens in my current z3 version (Z3 version 4.4.2) when using z3py.  I will compile the master branch and let you know if the issue persists. Thanks for your help.

**Comment by zell08v** [comment]
As a follow-up, just let you know that I have re-compiled Z3 with the **latest master branch**, but still get the same error (with z3.parse_smt2_file("add_01_1_1.smt2") ). My system is Mac OS 10.10, with  z3 4.4.2, python 2.7.9, ipython 2.3.0, clang version 3.7.0 (trunk 234707).   

In addition, I have reproduced the error with someone else's Macbook.   But I do not know about  its detailed settings. 

Maybe a bug in z3py (not necessarily in Z3, though).

**Comment by wintersteiger** [comment]
I'm finally able to reproduce this problem. It happens only in the interactive Python shell, not in the usual modes of operation.

**Comment by zell08v** [comment]
Yes, as mentioned earlier,  the issue happens to me when I use z3 to parse the  smt2 file within a python script or from ipython. The issue does not occur when  I use z3 directly from command line, such as `z3 --smt2 <filename>`.

**Comment by wintersteiger** [comment]
The bug is not triggered when running `python file.py`, it is only triggered when running `python` and then pasting the file contents into it. This automatically prints the result of all commands, while `python file.py` only prints when explicitly asked to. So here's an input that triggers the bug in both situations: 

    import z3;
    f = z3.parse_smt2_file("add_01_1_1.smt2")
    print(f)

I just commited a fix that should take care of this problem. If more issues come up feel free to repoen this issue or to submit a new one.

**Comment by zell08v** [comment]
Thanks. It parses well now. But I am unsure whether a new issue in the Z3py binding is introduced with this fix.

In my ipython console, 
z3.solve(z3.parse_smt2_file("add_01_1000_1.smt2")) gives 'no solution',

But I get 'unsat' when using "z3 --smt2 add_01_1000_1.smt2" from Terminal (Mac Os).

**Comment by wintersteiger** [comment]
This is not a bug. The function parse_smt2_file only parses the file, it does not execute any SMT2 commands (like `(check-sat)`). The output is an expression that contains all the assertions in the benchmark file and nothing else (also no logic definition, no options, etc).

**Comment by zell08v** [comment]
Thanks. Did you miss the *z3.solve* part in my previous question? Because if you use 

z3.solve(z3.parse_smt2_file(\<filename\>)) 

for some .smt2 files, z3py does give an answer. But if you use the same command for some other .smt2 files, z3py just reports *no solution*. 

To reproduce this issue, see my screenshot:
<img width="649" alt="89af75ac-46cc-496c-99ca-2cc93258f3de" src="https://cloud.githubusercontent.com/assets/3586263/12071792/7c564776-b073-11e5-837d-5e97256cf443.png">

That said, the issue is only in z3py, not in Z3.  In the screenshot above, the file *e1.c.smt2* is another Griggio's benchmark of 2015-SMT2-Comp.

**Comment by zell08v** [comment]
If you can reproduce this new "issue" (excuse me if I am wrong), let me know and I can then send you  two very tiny .smt2 files for you to trigger on/off the issue, which may ease your fixing it.

**Comment by wintersteiger** [comment]
Yes, I missed that part. See the definition of `solve` e.g. [here](https://github.com/Z3Prover/z3/blob/master/src/api/python/z3.py#L7473). In case of unsatisfiable `*args` it does `print("no solution")`, i.e. "no solution" means the same as "unsatisfiable".

Side remark: Solving SMT2 files via this method will not exhibit the same performance characteristics as running `z3 file.smt2` because options are discarded and the default tactic selection may be different. For QF_FP problems you may want to change `s = Solver()` to `s = SolverFor("QF_FP")` so that it's at least clear that the default tactic for QF_FP should be used. 

The best way to share files (with us and everybody else) is to upload them into a [gist](https://gist.github.com/) and there are a multitude of similar services.

**Comment by zell08v** [comment]
Sorry, I did not know "no solution" actually means the same as "unsat". Thanks for the hint.
