### ISSUE TITLE
horn Assertion violation at ../src/ast/proofs/proof_checker.cpp Line: 539

### ISSUE THREAD

**Issue by muchang** [Z3Prover/z3#3839]
Hi,
For this formula:
```
(assert
 (forall ((a Int))
 (forall ((b Int))
  (exists ((c Int))
  (xor and (= (div 82 a) c) (<= 129 b)
   (exists ((bb Int)) (xor (= (* 32 bb) c) (< 107 b))))))))
(check-sat-using horn)
```
Z3  throws out an assertion violation:
```
ASSERTION VIOLATION
File: ../src/ast/proofs/proof_checker.cpp
Line: 539
UNREACHABLE CODE WAS REACHED.
(C)ontinue, (A)bort, (S)top, (T)hrow exception, Invoke (G)DB
```

OS: Ubuntu 18.04
Commit: cb13641

**Comment by agurfinkel** [comment]
`proof_checker` is a best effort implementation used solely for debugging. Before filing an issue, please check that the proof that is being checked is in-fact incorrect. The proof checker often outputs a lemma in an smt format. If the lemma is valid (unsat) then the proof is correct but the checker is incomplete.

Please reopen this issue if this is infact a bug in the proof.
