### ISSUE TITLE
spacer returns solutions with bit2bool symbol, causing problems down the line

### ISSUE THREAD

**Issue by dbueno** [Z3Prover/z3#3847]
Spacer sometimes returns solutions that contain calls to bit2bool. I believe it shouldn't, since that is an internal Z3 symbol. I think it should return the corresponding bv extract instead.

I am using Z3 4.8.8 from master branch, git commit 121a6de32c3c78a7d3c5986390f5bccf8406730c. I'm on mac os mojave 10.14.6.

reproduce with [spacer_returns_bit2bool.smt2.txt](https://github.com/Z3Prover/z3/files/4445733/spacer_returns_bit2bool.smt2.txt):
```
$ z3 -v:1 fp.engine=spacer fp.print_answer=true fp.xform.inline_eager=false fp.xform.inline_linear=false spacer_returns_bit2bool.smt2
[... other output elided ...]
(define-fun p-3 ((x!0 Bool) (x!1 Bool) (x!2 (_ BitVec 32))) Bool
  (and (not ((_ bit2bool 0) x!2)) ((_ bit2bool 1) x!2)))
```

bit2bool causes problems if fed to a Z3 solver created with the "solve-eqs" tactic. In my case, I composed the "simplify" & "solve-eqs" & "smt" tactics. Such a solver returns incorrect results if fed a bit2bool, but the results are correct if the "solve-eqs" tactic is removed. The results are also correct if every bit2bool is rewritten to the corresponding extract & ite.

**Comment by agurfinkel** [comment]
I will let @NikolajBjorner make a decision here. The current behavior is by design.
Spacer extracts cores by processing the internal proofs. The core is not restricted to smt2-lib -- this might be important for internal workings of the solver. `print_answer` is a debug option that dumps the model. There is no assumption that the model is in smt-lib format either. 

The expansion of `bit2bool` into something else can be done by the client, if it is so desired. 

Perhaps `(get-model)` should be required to output a model in smt-lib format. But I'm not up on the standards enough to make a call here.

**Comment by dbueno** [comment]
In my actual use case, I'm using spacer programmatically by calling fixedpoint::get_answer(). It sounds like I should remove the bit2bool myself and that there might be other things that creep in there down the line. Thanks!

**Comment by agurfinkel** [comment]
That's also not smt-lib interface, but an interface that exposes a lot of internal structures. I would rather not put post-processing on this interface but have access to the internal structures as they are.

**Comment by dbueno** [comment]
Right now I'm taking the get_answer() output and creating formulas which are eventually passed to Z3 in other queries (routed through Z3's public interface). I don't require smt-lib; I mainly program to the Z3 public API.

I use a z3::fixedpoint, set up a query, and then parse the get_answer(). (The problem is CHC-satisfiable by construction; I'm getting interpolants for an unsatisfiable BMC query.) Is there a different way I should be doing this?

**Comment by agurfinkel** [comment]
You can be using smt-lib interface. Might be slightly nicer. Here is an example in python: https://spacerexamples-ariegurfinkel.notebooks.azure.com/j/notebooks/Dagstuhl2019.ipynb

It will still have the same `bit2bool` issue though.

Can you create a repro for the problem that `bit2bool` causes for you elsewhere. Perhaps I can fix that code to work correctly with `bit2bool` or to re-interpreted it as needed.

**Comment by NikolajBjorner** [comment]
Note that with commit, the bit2bool should be gone now from the models.
