### ISSUE TITLE
Horn tactic invalid model (datalog.generate_explanations)

### ISSUE THREAD

**Issue by rainoftime** [Z3Prover/z3#3853]
Hi, for the following formula
~~~~
(set-logic QF_UFLRA)
(set-option :model_validate true)
(set-option :fp.datalog.generate_explanations true)
(declare-const v8 Bool)
(assert v8)
(check-sat-using (then simplify horn))
~~~~

z3 commit 35f184a issues a warning
~~~~
(error "line 6 column 37: an invalid model was generated")
~~~~

**Comment by NikolajBjorner** [comment]
these options are not intended for the HORN tactic. I am shutting down uses where these parameters are set. There is quite likely a very long list of parameters that are unsuitable for the HORN tactic and at some point I will have to punt on bug reports like these.
