### ISSUE TITLE
Z3py fails to parse z3.FPVal(4011467167377.5, z3.Float64()) 

### ISSUE THREAD

**Issue by zell08v** [Z3Prover/z3#386]
If I type 

*import z3; z3.FPVal(4011467167377.5, z3.Float64())*

 in an ipython console, it gives me *Z3Exception: parser error*

But if I use 

*import z3; z3.FPVal(4011467167377, z3.Float64())*

it passes well. Not sure whether it is a bug in Z3py? The screenshot is attached. I am using Z3 4.4.2.

<img width="554" alt="c1c9f711-cf6c-4a2d-a8ef-3f7ec8faf047" src="https://cloud.githubusercontent.com/assets/3586263/11988058/8353d10a-a99e-11e5-9764-8578451c3455.png">

**Comment by wintersteiger** [comment]
This was indeed a bug in the Python bindings, but it should now be fixed.
