### ISSUE TITLE
Model validator reports error on valid model of QF_NIA formula

### ISSUE THREAD

**Issue by muchang** [Z3Prover/z3#3862]
Hi,
For this formula:
```
(declare-fun a () Int)
(declare-fun b () Int)
(assert (= b 11))
(assert (= (div 1 b (+ 1 (div 1 b a))) 0))
(check-sat)
```
Z3  model_validate=true throws out an invalid model error on a valid model:
```
[81] % ./z3/build/z3 model_validate=true test.smt2 
sat
(error "line 5 column 10: an invalid model was generated")
(model 
  (define-fun a () Int
    0)
  (define-fun b () Int
    11)
  (define-fun div0 ((x!0 Int) (x!1 Int)) Int
    (- 1))
  (define-fun mod0 ((x!0 Int) (x!1 Int)) Int
    (- 1))
)
[82] % cat test.smt2 
(declare-fun a () Int)
(declare-fun b () Int)
(assert (= b 11))
(assert (= (div 1 b (+ 1 (div 1 b a))) 0))
(check-sat)
(get-model)

```

OS: Ubuntu 18.04
Commit: 5c9fd90

**Comment by NikolajBjorner** [comment]
C:\zzz\build>z3 3862.smt2 model_validate=true
sat
(error "line 5 column 10: an invalid model was generated")

C:\zzz\build>z3 3862.smt2 model_validate=true smt.arith.solver=2
sat

**Comment by levnach** [comment]
When running with -v:11 I see.
sat
model check failed on:  (let ((a!1 (div (div 1 b) (+ 1 (div (div 1 b) a)))))
  (= a!1 0))
expected value: true.
I am not sure how to proceed from here.

**Comment by NikolajBjorner** [comment]
this bug is a duplicate a a few other recent bugs. It is a regression introduced yesterday and fixed today.
