### ISSUE TITLE
Horn formula failed to verify with rewriter.flat=false

### ISSUE THREAD

**Issue by wintered** [Z3Prover/z3#3866]
```
[735] % z3 small.smt2
sat
[736] % z3 rewriter.flat=false small.smt2
Failed to verify: lemma->get_pob()->pt().check_inductive(lemma->level(), cube, uses_level, lemma->weakness())
[737] % 
[737] % cat small.smt2
(set-logic HORN)
(assert (exists ((a Int) (b Int) (c Int)) (and (= (* 2 a) b) (or (= (* 1) c) (= 0 b)))))
(check-sat)
[738] %
```
OS: Ubuntu 18.04
Commit: 5c9fd90

**Comment by agurfinkel** [comment]
spacer assume that `rewriter.flat=true`. Spacer sets rewriter options that it needs, but it assumes that the rest of the options are in their default setting. This is useful for debugging and advanced users that want to try something outside of supported parameters. 

Please do not change default rewriter parameters when using HORN logic.
