### ISSUE TITLE
Performance regression in current `master` caused since yesterday

### ISSUE THREAD

**Issue by kostis** [Z3Prover/z3#3868]
One of the changes committed to `master` since yesterday. after commit d2ec661ec63446bea4e6c9801b3b3b2522e51ff4, causes a performance regression to the following smt test case:
```smt
; z3 -smt2 -in
(set-option :produce-models true)
(declare-datatypes () ((Term (int (iv Int)) (real (rv Real)) (list (lv TList)) (tuple (tv TList)) (atom (av IList)) (str (sv SList)) (fun (fv Int))) (TList (tn) (tc (th Term) (tt TList))) (IList (in) (ic (ih Int) (it IList))) (SList (sn) (sc (sh Bool) (st SList))) (FList (fn) (fc (fx TList) (fy Term) (ft FList)))))
(declare-fun fa (Int) Int)
(declare-fun fm (Int) FList)
(declare-const |0.1634192954.3601334368.9690| Term)
(declare-const |0.1634192954.3601334368.9691| Term)
(assert (is-int |0.1634192954.3601334368.9690|))
(assert (is-int |0.1634192954.3601334368.9691|))
(declare-const |0.1634192954.3601334368.9818| Term)
(define-fun-rec int-or-rec ((n Int) (n1 Int) (n2 Int)) Bool (or (= n1 n (- 1)) (= n2 n (- 1)) (= n1 n2 n 0) (and (= (or (not (= (mod n1 2) 0)) (not (= (mod n2 2) 0))) (not (= (mod n 2) 0))) (int-or-rec (div n 2) (div n1 2) (div n2 2)))))
(define-fun int-or ((n Int) (n1 Int) (n2 Int)) Bool (and (=> (< n1 0) (and (<= n1 n) (< n 0))) (=> (< n2 0) (and (<= n2 n) (< n 0))) (=> (and (>= n1 0) (>= n2 0)) (<= 0 n (+ n1 n2))) (=> (>= n 0) (and (<= 0 n1 n) (<= 0 n2 n))) (int-or-rec n n1 n2)))
(assert (int-or (iv |0.1634192954.3601334368.9818|) (iv |0.1634192954.3601334368.9690|) (iv |0.1634192954.3601334368.9691|)))
(assert (= (int 132167806349873198573065468706546708964) |0.1634192954.3601334368.9818|))
(check-sat)
```

The above test returns `sat` almost immediately with previous z3s (or with the z3 of the above commit) but requires a timeout of 5 secs or more (on my machine) with the changes that have been pushed to `master` since yesterday.

I thought I should report this soon enough to minimize the effort in finding the culprit.

EDIT: The above test case is not minimized, but cut-and-pasted here exactly as generated by the [CutEr](https://github.com/cuter-testing/cuter) tool. Apologies if this turns out to be due to a sub-optimal test case, but this generation has been working for us for years now.

**Comment by NikolajBjorner** [comment]
Thanks for the heads up. The culprit would be the change from arith.solver=2 as default to arith.solver=6. It takes 10x more time with arith.solver=6. We were anticipating performance regressions with this change and would like to catch them with bug reports like these. 
We will probably make a release with reverting to solver=2, but the idea is to use the new solver.

@levnach

**Comment by kostis** [comment]
@NikolajBjorner Thanks for the quick reaction!

I can confirm that this is the change that causes the regression.
