### ISSUE TITLE
Assertion violation at src/smt/theory_seq.cpp:4678 (Seq)

### ISSUE THREAD

**Issue by rainoftime** [Z3Prover/z3#3883]
Hi, for the following formula
~~~~
(set-option :smt.seq.validate true)
(declare-const Str10 String)
(assert (str.< Str10 ""))
(check-sat)
~~~~

z3 2673807a7f1 throws an assertion violation
~~~~
File: ../src/smt/theory_seq.cpp
Line: 4678
UNREACHABLE CODE WAS REACHED.
~~~~

**Comment by NikolajBjorner** [comment]
seq.validate is for debugging, so this kind of assertion stop isn't interesting.
The validation mechanism is (unfortunately) very partial. It hit a case where the validator does not have a way to check the lemma. I added a more graceful way to bail out here, but generally don't bother fuzzing this parameter setting. It is similar to nlsat.check_lemmas, which is also used for debugging.
