### ISSUE TITLE
HORN Failed to verify on LIA formula with smt.ematching=false

### ISSUE THREAD

**Issue by muchang** [Z3Prover/z3#3894]
Hi,
For this formula:
```
(set-logic HORN)
(assert
 (exists ((a Int))
 (forall ((n Int))
  (exists ((b Int))
  (xor (and true) (distinct a b) (<= (- 1) n)
   (exists ((bb Int))
   (or (distinct (* (- 11) bb) b) (> 0 n))))))))
(check-sat)
```
Z3  throws out a Failed to verify:
```
[642] % z3 small.smt2
sat
[643] % z3 smt.ematching=false small.smt2
Failed to verify: lemma->get_pob()->pt().check_inductive(lemma->level(), cube, uses_level, lemma->weakness())
[644] % 
[644] % cat small.smt2
(set-logic HORN)
(assert
 (exists ((a Int))
 (forall ((n Int))
  (exists ((b Int))
  (xor (and true) (distinct a b) (<= (- 1) n)
   (exists ((bb Int))
   (or (distinct (* (- 11) bb) b) (> 0 n))))))))
(check-sat)
[645] %
```

OS: Ubuntu 18.04
Commit: 2673807

**Comment by agurfinkel** [comment]
incomplete solver. expected result. non-issue.

**Comment by muchang** [comment]
Without `smt.ematching=false`. If we change `bb` to `c`, the "Failed to verify" also appears:
```
[684] % z3 t1.smt2 
sat
[685] % z3 t2.smt2 
Failed to verify: lemma->get_pob()->pt().check_inductive(lemma->level(), cube, uses_level, lemma->weakness())
[686] % diff t1.smt2 t2.smt2 
7,8c7,8
<   (exists ((bb Int))
<    (or (distinct (* (- 11) bb) b) (> 0 n))))))))
---
>   (exists ((c Int))
>    (or (distinct (* (- 11) c) b) (> 0 n))))))))
[687] % cat t1.smt2 
(set-logic HORN)
(assert
 (exists ((a Int))
 (forall ((n Int))
  (exists ((b Int))
  (xor (and true) (distinct a b) (<= (- 1) n)
   (exists ((bb Int))
   (or (distinct (* (- 11) bb) b) (> 0 n))))))))
(check-sat)
[688] % cat t2.smt2 
(set-logic HORN)
(assert
 (exists ((a Int))
 (forall ((n Int))
  (exists ((b Int))
  (xor (and true) (distinct a b) (<= (- 1) n)
   (exists ((c Int))
   (or (distinct (* (- 11) c) b) (> 0 n))))))))
(check-sat)
[689] %
```
Here, `t1` is the original formula, `t2` is the changed formula. 
It seems the variable name affects the triggering of the "Failed to verify".

**Comment by agurfinkel** [comment]
incomplete solver. lots of things affect incompleteness.

**Comment by zhendongsu** [comment]
> incomplete solver. lots of things affect incompleteness.

That's a very developer-centric view --- the user would certainly disagree very strongly :)

**Comment by agurfinkel** [comment]
Sorry, the comment is terse because it appears again and again.

HORN logic requires that the logic of constraints has a complete decidable decision procedure. If this is not the case, the HORN solver might return `unknown` if an underlying constraint solver returns `unknown`. This works as expected in release mode. When faced with an undecidable problem, HORN solver might return `unknown` or run for a long time (there is a time limit, so it will always return `unknown` eventually. 

In debug mode, extra checks are made to see that the solver is complete. These help debug instances that are outside of supported logics. In this specific example, you are mixing universal and existential quantifiers. This is not supported in the sense that assertions might be triggered in debug mode. They do, as expected.

A user might disagree that returning unknown on an undecidable problem is what they want. Unfortunately, I cannot fix spacer to decide undecidable problems.

**Comment by zhendongsu** [comment]
> A user might disagree that returning unknown on an undecidable problem is what they want. Unfortunately, I cannot fix spacer to decide undecidable problems.

Arie, sure, nobody is asking for that :)   But, if changing the name of a variable, say from bb to c as illustrated by @muchang's example in his comment above (i.e., https://github.com/Z3Prover/z3/issues/3894#issuecomment-611500179), it would be highly confusing to the user that the returned answer changes from sat to unknown.  Analogously, if GCC or Clang/LLVM refuses to compile a valid C program when the program's identifier names change, it wouldn't be expected and desirable.

**Comment by agurfinkel** [comment]
The comparison to clang/gcc is not appropriate. They solve a decidable problem using a deterministic algorithm. This is not true for incomplete solvers. Incomplete solvers depend on heuristics. Various identifiers, like internal names of variables, are used to drive these heuristics. Changing variable names, order of parameters, order of assertions -- are all known to affect performance (for exponential algorithms like CDCL, and completeness for partial algorithms like SMT). The users are well aware of this. Unfortunately, this is the nature of the problem. Fortunately, the users of these tools know this quite well and have strategies to deal with it.

Note that, on the other hand, I am very interested in reducing all non-deterministic behavior. That is, two runs with exactly the same input must have the same running time and same result. However, any change in the input, even a single character change, might have significant influence on the final result.

**Comment by agurfinkel** [comment]
These are very interesting issues. But I feel that my responses might not be well thought out -- I'm answering this between other tasks that I am doing. The issue-comments might also not be the most convenient medium for this discussion. 

If my comments appear too harsh or too negative, I apologize, this is not my intention. I would be very happy to continue this discussion (what is and what is not appropriate to expect from a tool like spacer and what issues are of great interest) in some other forum where I can better understand your argument and better communicate mine.

**Comment by zhendongsu** [comment]
> The comparison to clang/gcc is not appropriate. 

Just to add a quick follow-up and stop now: please note that there were actual bugs in GCC/Clang that were sensitive to identifier naming, which did get fixed --- in fact, I reported some of them :) 

I would think that minimizing such, especially not-so-subtle, flaky/nondeterministic behaviors would be quite desirable for both compilers like GCC/Clang and solvers like spacer/Z3. 

>  I would be very happy to continue this discussion (what is and what is not appropriate to expect from a tool like spacer and what issues are of great interest) in some other forum where I can better understand your argument and better communicate mine.

Yes, I'd be happy to discuss further on this.  The fact that you focus on spacer and that we view Z3 (or any SMT solver for that matter) as a whole (of which spacer is a part) may have contributed some confusion to this discussion.
