### ISSUE TITLE
Different solutions with multiple check-sat !

### ISSUE THREAD

**Issue by bja2019** [Z3Prover/z3#3901]
(set-option :produce-unsat-cores true)
(set-option :produce-models true)
(declare-const length Real)
(declare-const lengthVerdict1 Bool)
(declare-const lengthVerdict2 Bool)
(declare-const lengthVerdict_Negated Bool)

; length < ( 15 + tol1) & length > ( 3 - tol2) 
(assert (= lengthVerdict1
   (and (< length
           (+ 15.0 (/ 1 10000000000000 )))
        (> length
           (- 3.0 (/ 1 10000000000000))))))

; abs( length - 5.0) < tol
(assert (let ((a!1 (< (ite (>= (- length 5.0) 0.0)
                   (- length 5.0)
                   (- (- length 5.0)))
              (/ 1 10000000000000))))
  (= lengthVerdict2 a!1)))

(assert lengthVerdict1)
(assert lengthVerdict2)

(echo "First Check")
(check-sat)
(get-model) ; Gives solution length = 5.0 - O.K.

(echo "Check the length solution is unique")
(push)
(assert (let ((a!1 (and (>= length
                    (- 5.0
                       (/ 1 10000000000000)))
                (<= length
                    (+ 5.0
                       (/ 1 10000000000000))))))
  (= lengthVerdict_Negated (not a!1))))

(assert lengthVerdict_Negated)

(check-sat)  ; will result unsat - ok - its unique
(pop) ; remove negative asserts 

(echo "Second Check" )
(check-sat)  
(get-model)

================================================================
Following is the output for the above script
First Check
sat
(model
  (define-fun lengthVerdict1 () Bool
    true)
  (define-fun lengthVerdict2 () Bool
    true)
  (define-fun length () Real
    5.0)
)
Check the length solution is unique
unsat
Second Check
sat
(model
  (define-fun lengthVerdict1 () Bool
    true)
  (define-fun lengthVerdict2 () Bool
    true)
  (define-fun length () Real
    (/ 99999999999999.0 20000000000000.0))
)

The first check-sat gives a solution for the length as  (define-fun length () Real  5.0)
The second one is  (define-fun length () Real
    (/ 99999999999999.0 20000000000000.0))

Though ( / 99999999999999.0 20000000000000.0 ) is almost equal to 5.0, but the solution from the  first check is different from the second solution. 
Is it possible to get the same result with every check-sat in the above scenario ?

**Comment by NikolajBjorner** [comment]
This is not generally possible because the solver does not restore an identical state during backtracking. It relies on many adaptive data-structures to tune search according to what was learned so backtracking to an identical state is not an objective. 

The bounds used in your constraints are also strict. So the LP solver has to find real values close to the bounds. This is another source of where the state changes: there is no LP optimal value that can be returned as rationals so it finds some approximation.
