### ISSUE TITLE
Assertion violation for CHC(LRA) at spacer_context.cpp:1680 (fp.xform.fix_unbound_vars)

### ISSUE THREAD

**Issue by rainoftime** [Z3Prover/z3#3907]
Hi, for the following formula
~~~~
(set-logic HORN)
(set-option :fp.xform.fix_unbound_vars true)
(declare-fun inv-real3 (Real Real Real Real) Bool)
(assert (forall ((q52 Real) (q53 Real) (q54 Real) (q55 Real) (q56 Real) (q57 Real) (q58 Real) (q59 Real) (q60 Real) (q61 Real) (q62 Real) (q63 Real) (q64 Real) (q65 Real) (q66 Real) (q67 Bool)) (inv-real3 55536653727.0 4051.0 0.0 0.0)))
(assert (forall ((q226 Real) (q227 Real) (q228 Real) (q229 Real) (q230 Real) (q231 Bool)) true))
(assert (forall ((q455 Real) (q456 Real) (q457 Real) (q458 Real) (q459 Real) (q460 Real) (q461 Real) (q462 Real) (q463 Real) (q464 Real) (q465 Real) (q466 Real) (q467 Real) (q468 Bool)) (=> (inv-real3 0.0 0.0 0.0 0.0) q468)))
(check-sat)
~~~~

z3 ae5a713e8 throws an assertion violation 
~~~~
ASSERTION VIOLATION
File: ../src/muz/spacer/spacer_context.cpp
Line: 1680
ut_size == 0 || is_ground(trans)
(C)ontinue, (A)bort, (S)top, (T)hrow exception, Invoke (G)DB
~~~~

Related: https://github.com/Z3Prover/z3/issues/3781

**Comment by hgvk94** [comment]
This is a valid assertion failure. I don't see how z3 should fix unbounded variables in the head of a CHC. You can use nullary predicates instead.

**Comment by rainoftime** [comment]
@hgvk94  Thanks for the explanation. Do yous "fix_unbound_vars" is incompatible for the formula, or in general for CHC(LRA) formulas? Thank you!

**Comment by hgvk94** [comment]
incompatible with this particular formula

**Comment by agurfinkel** [comment]
Do not generate `fix_unbound_vars=true` for input that hits `spacer`. The transformation adds an existential quantifier and that assertions checks that there are no such quantifiers. 

We can work around this by returning `unknown` when this transformation is enabled and spacer is used. I am working on this work around.

**Comment by rainoftime** [comment]
I see.
The fp module automatically selects `spacer` engine (instead of `bmc` and `datalog`). But the transformation by `fix-unboude-var` breaks some assumption/specification of spacer.

**Comment by agurfinkel** [comment]
I would say that you are using an option that only works in conjunction of some engines, but you do not select a compatible engine. In debug mode, spacer protects from you by a debug assertion. 

I will hide the assertion and will look for other ways to leave debug information for myself. Please don't report more failures with this option until I'm done with this issue.
