### ISSUE TITLE
Z3-opt for Integer

### ISSUE THREAD

**Issue by gingeredder** [Z3Prover/z3#391]
As far as I was concerned, the Z3-opt is for the LRA theory. Obviously, it could be used to solve the Integer Linear Programming.
But the performance based on rational number may be no better than based on pure integer?
Does the Z3-opt have the branch for pure integer without rational number?(namely, specific for Integer Linear Programming)

**Comment by cheshire** [comment]
I am not a Z3 developer, but Z3 supports integer programming very well, I mostly use it myself for optimizations modulo LIA.
There is no specific branch for integers.

**Comment by NikolajBjorner** [comment]
LIA support is included, performance depends on efficiency of underlying solver. For integer difference logic (IDL) one can try also underlying solvers for this fragment though mostly the default configuration seems better. Pseudo booleans are also handled, eg if you use integers bound between 0 and 1.
