### ISSUE TITLE
How to check the solving space is convex or non-convex for constraint space?

### ISSUE THREAD

**Issue by gingeredder** [Z3Prover/z3#392]
Given a constraint space based on SMT-LIB2, like (x > 2 /\ y > 3) \/ (x < 5 /\ z < 6) /\ (x > z \/ z + y > 0).
How could I check the solving space is convex or not?
Does the Z3 provide the interface to cover this problem?

**Comment by NikolajBjorner** [comment]
There is no direct interface to tell you if lunar arithmetic formulas are convex.
