### ISSUE TITLE
Add an API for creating match expressions

### ISSUE THREAD

**Issue by atodekangae** [Z3Prover/z3#3920]
The `match` expression, introduced in SMT-LIB 2.6, is supported in the SMT parser ([`parsers/smt2/smt2parser.cpp`](https://github.com/Z3Prover/z3/blob/master/src/parsers/smt2/smt2parser.cpp)), but is not available via API. Considering that it's just a syntactic sugar ([it compiles down to if-then-else](https://github.com/Z3Prover/z3/blob/337c07a44c6a143165fc6a8c3f3c1bd7781bf45d/src/parsers/smt2/smt2parser.cpp#L1399)), the absence of it is rather a minor problem, but it would be convenient if Python API had `z3.Match` like `z3.If`.

**Comment by NikolajBjorner** [comment]
I don't see how to prioritize such a feature as it doesn't enable something new.
