### ISSUE TITLE
Need a clarification regarding :smt.arith.sovler=6 option usage !

### ISSUE THREAD

**Issue by bja2019** [Z3Prover/z3#3921]
For a following use case, where it is trying to calculate the area from a length and a width within a double precision epsilon.

(declare-fun EQ_eq (Real Real) Bool)
(declare-fun EQ_ne (Real Real) Bool)
(declare-fun EQ_lt (Real Real) Bool)
(declare-fun EQ_le (Real Real) Bool)
(declare-fun EQ_gt (Real Real) Bool)
(declare-fun EQ_ge (Real Real) Bool)

(declare-fun Length () Real)
(declare-fun LengthAnyVerdict () Bool)
(declare-fun Area () Real)
(declare-fun AreaAnyVerdict () Bool)
(declare-fun Width () Real)
(declare-fun WidthAnyVerdict () Bool)
(declare-fun AreaVerdict () Bool)
(declare-fun LengthVerdict () Bool)
(declare-fun WidthVerdict () Bool)
(declare-fun AreaVerdict_Negated () Bool)

(assert (forall ((x Real) (y Real))
  (let ((a!1 (< (ite (>= (- x y) 0.0) (- x y) (- (- x y)))
                (/ 1.0 100000000000000.0))))
    (= (EQ_eq x y) a!1))))
(assert (forall ((x Real) (y Real))
  (let ((a!1 (> (ite (>= (- x y) 0.0) (- x y) (- (- x y)))
                (/ 1.0 100000000000000.0))))
    (= (EQ_ne x y) a!1))))
(assert (forall ((x Real) (y Real))
  (= (EQ_lt x y) (< x (- y (/ 1.0 100000000000000.0))))))
(assert (forall ((x Real) (y Real))
  (= (EQ_le x y) (< x (+ y (/ 1.0 100000000000000.0))))))
(assert (forall ((x Real) (y Real))
  (= (EQ_gt x y) (> x (+ y (/ 1.0 100000000000000.0))))))
(assert (forall ((x Real) (y Real))
  (= (EQ_ge x y) (> x (- y (/ 1.0 100000000000000.0))))))
  
(assert (= LengthAnyVerdict (distinct Length 0.0)))
(assert (= AreaAnyVerdict (distinct Area 0.0)))
(assert (= WidthAnyVerdict (distinct Width 0.0)))

; Area = Length * Width
(assert (= AreaVerdict (and (= Area (* Length Width)))))

; Length = 5.5
(assert (let ((a!1 (< (ite (>= (- Length (/ 11.0 2.0)) 0.0)
                   (- Length (/ 11.0 2.0))
                   (- (- Length (/ 11.0 2.0))))
              (/ 1097344334114041.0 125000000000000000000000000000.0))))
  (= LengthVerdict a!1)))

; Width = 4.2
(assert (let ((a!1 (< (ite (>= (- Width (/ 21.0 5.0)) 0.0)
                   (- Width (/ 21.0 5.0))
                   (- (- Width (/ 21.0 5.0))))
              (/ 2266853164828717.0 250000000000000000000000000000.0))))
  (= WidthVerdict a!1)))

; check area = 23.1 is unique
(assert (let ((a!1 (and (>= Area
                    (- (/ 231.0 10.0)
                       (* 2.0
                          (/ 9487076962623177.0
                             100000000000000000000000000000.0))))
                (<= Area
                    (+ (/ 231.0 10.0)
                       (* 2.0
                          (/ 9487076962623177.0
                             100000000000000000000000000000.0)))))))
  (= AreaVerdict_Negated (not a!1))))

(assert AreaAnyVerdict)
(assert LengthAnyVerdict)
(assert WidthAnyVerdict)
(assert AreaVerdict)
(assert LengthVerdict)
(assert WidthVerdict)
(assert AreaVerdict_Negated)
(check-sat)
(get-model)
;*************************************

I tried with smt.arith.solver=2 (default), result is 'unknowm'. Then with option smt.arith.solver=6 ( lrasolver ), result is 'unsat' - which is expected in the above scenario. 
I want use the option smt.arith.solver=6, however I have below queries with option usage.

1. What is the performance impact of the option (smt.arith.solver=6) compared to the option (:smt.arith.solver=2)? What if z3 does performs some extra work even for a regular use case? ( i.e., script involving no non-linear equation ).

2. Is this option applicable to real only? OR it is applicable for int as well?

3. Is possible to set this option only where required ? 
   i.e., when I encounter the check-sat giving verdict as 'unknowm', then I want to try with the option (:smt.arith.solver=6) by setting it temporarily and unset the option when not required.

Thank you for your time and support in advance!

**Comment by NikolajBjorner** [comment]
> What is the performance impact of the option (smt.arith.solver=6) compared to the option (:smt.arith.solver=2)? What if z3 does performs some extra work even for a regular use case? ( i.e., script involving no non-linear equation ).

We are trying to make sure arith.solver=6 can replace arith.solver=2. 
arith.solver=6 is a reimplementation and adds some extra features.
We continue to investigate regressions where arith.solver=6 is worse than 2 as 
they are reported or we find them through benchmarking. 
For standard benchmarks solver=6 is a winner.

> Is this option applicable to real only? OR it is applicable for int as well?

The same solver is used for real-only. It just doesn't call any code that performs integer reasoning.

> Is possible to set this option only where required ?
i.e., when I encounter the check-sat giving verdict as 'unknowm', then I want to try with the option (:smt.arith.solver=6) by setting it temporarily and unset the option when not required.

No, you can't switch backend engines on the same objects. You can however create two different optimization objects from the API and configure them separately. From SMTLIB2 you can call (reset) to reset the entire state, re-assert formulas and then set the desired option.
