### ISSUE TITLE
Invalid model for QF_S formula with str.at str.substr str.len

### ISSUE THREAD

**Issue by muchang** [Z3Prover/z3#3926]
Hi,
For this case, Z3 gives an invalid model for the formula:
```
[90] % ./z3debug model_validate=true small.smt2
sat
(error "line 4 column 10: an invalid model was generated")
(model 
  (define-fun a () String
    "\x00\x00\f")
)
[91] % cat small.smt2 
(declare-fun a () String)
(assert (= (str.at (str.substr (str.substr a 1 (- (str.len a) 1)) 1 
        (- (str.len (str.substr a 1 (- (str.len a) ))) 1)) 0) "\f"))
(check-sat)  
(get-model)      
[92] % 
```

Ubuntu 18.04
Commit: db9d6d1

**Comment by NikolajBjorner** [comment]
This was a bug in a rewrite rule.

The example also exposed some opportunities for better rewrites.
Could you use the existing fuzzers + mutators to identify missed rewrites?

The idea is to mine the benchmarks you use for fuzzing and extract subterms and mutants with fewer nodes. Then call 

```
 (declare-const ...)
 (check-sat (not (= original_term new_term)))
 (simplify (= original_term new_term))
```

If the first output is "unsat", but the second is not "true", then there is some chance the simplifier can be improved. It should make sense to focus narrowly on small terms with at most 8-10 nodes.

**Comment by muchang** [comment]
Okay, Nikolaj, I will try to fuzz in the way you suggested.

**Comment by NikolajBjorner** [comment]
cool.

The missing rewrite was:

```
   (str.substr x y z) -> ""   if z cannot be > 0
 ```

It could be mined from the sample

```
   (str.substr a 1 (- (str.len a) )
```

For a given sample it makes sense to look for simplifications to the empty string or a subterm.
This limits the search space significantly and plays well into having some data to play with.

**Comment by zhendongsu** [comment]
Nikolaj, this is interesting, and we will be looking into this.  Is there a convenient way to get at the existing rewrites Z3 uses?

**Comment by NikolajBjorner** [comment]
>  Is there a convenient way to get at the existing rewrites Z3 uses?

Not sure how to parse the question. All rewrites are implemented in seq_rewriter.cpp.
The implementation is pretty low level and in cases ad-hoc. 
This is perhaps not too different from compiler optimizations.
There is no nice domain language or so that would be well presentable (@nunoplopes). 
These rewrite rules are available when using the "simplify" tactic.
So you can see the effect on any given term by running "simplify" as described above.

**Comment by zhendongsu** [comment]
> All rewrites are implemented in seq_rewriter.cpp.

Thanks, Nikolaj; we'll check out this file.
