### ISSUE TITLE
declare-datatypes rejects instantiated recursive fields 

### ISSUE THREAD

**Issue by nikivazou** [Z3Prover/z3#3930]
E.g., the below definition of `DD` ignores the `DDx` and `DDy` constructors: 

```
(declare-datatypes ((DD 1)) (
    (par (T) (
        (DDA (DDx T) (DDy T)) 
        (DDB (DDz (DD Int)))
;        (DDB (DDz (DD T))) ; this instead of the DD Int makes the assertion unsat
        ))))

(declare-fun dd () (DD Int))
(declare-fun yy () Int)
(declare-fun xx () Int)

(assert (and 
(= xx yy) 
(= (DDy dd) yy) 
(= (DDx dd) xx) 
))
(assert (not (= xx yy)))
(check-sat)
; SMT says (error "line 14 column 10: unknown function/constant DDy")
; SMT says sat
```

**Comment by NikolajBjorner** [comment]
dealing with these parametric datatypes is a bit tricky.
I pushed an update that allows to parse the example without errors.
The way it achieves this is to initialize a symbol table for the convenience of the user.
The hard way a user can ensure that the terms with instantiations of algebraic datatypes gets parsed is by adding explicit type annotations using the (as ...) construct. The SMTLIB2 standard describes the syntax for this construct. It is quite difficult to use manually though.

**Comment by nikivazou** [comment]
Thanks @NikolajBjorner! 

FYI, before the fix `as` could not help. The below query gave the same Z3 response. 

```
(assert (and 
(= xx yy) 
(= (DDy (as dd (DD Int)) yy)) 
(= (DDx (as dd (DD Int)) xx)) 
))
(assert (not (= xx yy)))
(check-sat)
```

**Comment by NikolajBjorner** [comment]
Something like: 
```
(= ((as DDy (DD Int)) dd) yy)
```
