### ISSUE TITLE
Segfault in AST manager

### ISSUE THREAD

**Issue by seanmcl** [Z3Prover/z3#395]
I don't have any idea what's wrong here, but it is crashing frequently in the AST manager.  

I have core dumps if needed.

```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00000001a82e4c4d, pid=12964, tid=16015
#
[thread 19575 also had an error]# JRE version: Java(TM) SE Runtime Environment (8.0_66-b17) (build 1.8.0_66-b17)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.66-b17 mixed mode bsd-amd64 compressed oops)
# Problematic frame:
# 
C  [libz3.dylib+0x9e6c4d]  _ZN11ast_manager15coercion_neededEP9func_decljPKP4expr+0xd
```

**Comment by nunoplopes** [comment]
We need more information.
Crashes in the AST manager are often due to missing increfs on the ASTs (ASTs are referenced counted).  I don't know the Z3 Java API, but probably these increfs are done automatically by the wrapping classes.

**Comment by seanmcl** [comment]
What's the best way to get you the information you need?  The Api log? Core file?

**Comment by nunoplopes** [comment]
Sometimes a gdb trace is sufficient. If not, an API log should work.

**Comment by seanmcl** [comment]
I found it difficult to reproduce in a debugger.  It seems the linearization of my queries eliminates the segfault.  I'm creating a Datalog program and then making (stateless) Fixedpoint.query's against it from multiple akka actors/threads.  Are Z3 Context/Fixedpoint objects thread-safe?   I see 'synchronized' in the Context code, so I assume it should be.  

There are no comments about thread-safety in the Fixedpoint java file.

**Comment by NikolajBjorner** [comment]
Use different contexts per thread.

**Comment by seanmcl** [comment]
Nikolai, are you saying

1. Contexts are not thread safe

Or 

2. Contexts should be thread safe but whatever bug I'm hitting can be avoided by using a context per thread
?


It's really expensive for me to build a context, and I'd prefer to try to debug this myself if the answer is 2. Akka actors don't correspond directly to Java threads so this route would take some effort as well.  Possibly more than just looking for race conditions. 

Thanks.

**Comment by NikolajBjorner** [comment]
What I mean: You cannot perform any operation on the same context from two different threads.
You have to use separate contexts for each thread if you use multiple threads. 
We provide translation routines for converting expressions created in one context to another.

**Comment by seanmcl** [comment]
Got it.  Thanks.  I was thrown by the 'synchronized' in Context.java, but it is clear now that that is just for the constructors talking to the native library.
