### ISSUE TITLE
Performance regression for QF_NRA instance (arith.solver 2, 6)

### ISSUE THREAD

**Issue by rainoftime** [Z3Prover/z3#3952]
Hi, for the following formula 
~~~~
(set-logic QF_NRA)
(declare-const v5 Bool)
(declare-const r1 Real)
(declare-const v17 Bool)
(declare-const r2 Real)
(push 1)
(assert (or v17 (> r2 (- r1) (/ r1 0.0) (* r1 (- r1) r1 20.0) 0.0) v5))
(check-sat)
~~~~

If seting `(set-option :smt.arith.solver 2)`, z3 can solve quictkly.
~~~~
sat
real    0m0.382s
user    0m0.076s
sys     0m0.032s
~~~~
However, if seting `(set-option :smt.arith.solver 6)`, z3 does not finished in several minutes.

Commit: 0f697830

**Comment by rainoftime** [comment]
Since the default arith.solver will be changed from 2 to 6, I thought I should report this.

**Comment by levnach** [comment]
Works in ccda9d56d7e1b91d9561e88c913b0c7c50d32a6d
