### ISSUE TITLE
unsat-core?

### ISSUE THREAD

**Issue by ClemFandango2** [Z3Prover/z3#3964]
Do I understand unsat core correctly?
Am I right unsat core for this example should be one of assert's?
But I'm getting empty unsat core.

    (set-option :produce-unsat-cores true)
    
    (declare-fun x  () (_ BitVec 64))
    (assert (= x #x0000000000000000))
    (assert (= x #x1111111111111111))
    
    (check-sat)
    (get-unsat-core)

Output:

    unsat
    ()

**Comment by NikolajBjorner** [comment]
There are a couple of options. You can name assertions that you want to track for the core.
This also means that you can omit assertions from the core when they are not interesting.
You can also use tracking literals and check-sat-assuming.

```
(set-option :produce-unsat-cores true)

(declare-fun x  () (_ BitVec 64))
(assert (! (= x #x0000000000000000) :named f1))
(assert (! (= x #x1111111111111111) :named f2))

(check-sat)
(get-unsat-core)

(reset)

(set-option :produce-unsat-cores true)

(declare-fun x  () (_ BitVec 64))
(declare-const f1 Bool)
(declare-const f2 Bool)
(assert (=> f1 (= x #x0000000000000000)))
(assert (=> f2 (= x #x1111111111111111)))

(check-sat-assuming (f1 f2))
(get-unsat-core)
```
