### ISSUE TITLE
Segfault using z3-4.8.7-x64-osx-10.14.6

### ISSUE THREAD

**Issue by bkragl** [Z3Prover/z3#3974]
Running the OS X release of Z3 4.8.7 on the file [smt2.log](https://github.com/Z3Prover/z3/files/4480589/smt2.log) results in a segfault (after reporting `unsat` 39 times).

However, both the Ubuntu and Windows release terminate fine (reporting `unsat` 43 times).

**Comment by NikolajBjorner** [comment]
Sorry, this is a somewhat old version of z3. It didn't reproduce.
