### ISSUE TITLE
Invalid model for QF_NRA formula (unsat_core, smt.phase_selection 5, smt.arith.solver 6)

### ISSUE THREAD

**Issue by rainoftime** [Z3Prover/z3#3982]
Hi, for the following formula, z3 (commit dde0c51) gives an invalid model
[qfnra.txt](https://github.com/Z3Prover/z3/files/4484795/qfnra.txt)

Options 
~~~~
(set-logic QF_NRA)
(set-option :model_validate true)
(set-option :unsat_core true)
(set-option :smt.phase_selection 5)
(set-option :smt.arith.solver 6)
...
~~~~

**Comment by zhendongsu** [comment]
Looks like the same again --- see Nikolaj's comment for https://github.com/Z3Prover/z3/issues/3902

**Comment by NikolajBjorner** [comment]
this is #3979
