### ISSUE TITLE
Multiplication and `Real`

### ISSUE THREAD

**Issue by ranjitjhala** [Z3Prover/z3#399]
Hi,

the below file causes `z3` (v. 4.4.1)  to hang (as far as I can tell). I'm guessing its because
we're using `Int` values `n` on a function declared for `Real` ? (It works fine if I change the 
sort of `Z3_OP_MUL` to `(x Int) (y Int) Int`. However, note that it also works fine with:

1. version `4.3.2` 
2. if I perturb the formulas a bit (i.e. we've been using this same formulation without trouble on other similar queries.

Just thought I'd point out!

Thanks!

Ranjit.

```
(set-option :auto-config false)
(set-option :model true)
(set-option :model.partial false)
(set-option :smt.mbqi false)

(define-fun Z3_OP_MUL ((x Real) (y Real)) Real (* x y))
(declare-fun ys () Int)
(declare-fun len (Int) Int)
(declare-fun xs () Int)
(declare-fun n () Int)
(declare-fun v () Int)
(declare-fun lq () Int)
(push 1)
(assert (and (= v lq)
             (>= (len xs) 0)
             (= n (len ys))
             (= (len lq) (len ys))
             ))
(push 1)
(assert (not (= (len v) (Z3_OP_MUL n n))))
(check-sat)
; SMT Says: Sat
(pop 1)
```

**Comment by NikolajBjorner** [comment]
When I create and merge the pull from NikolajBjorner/z3, Z3 should solve this and more other cases with mixed integer reals.

**Comment by NikolajBjorner** [comment]
Pull request for fixes has been merged now

**Comment by ranjitjhala** [comment]
Thanks!
