### ISSUE TITLE
Self-referential array values

### ISSUE THREAD

**Issue by LeventErkok** [Z3Prover/z3#4024]
This keeps up coming back. Unfortunately github doesn't let me re-open old issues. Here's the original: https://github.com/Z3Prover/z3/issues/2128

For this benchmark:

```
(set-option :produce-models true)
(set-logic ALL)

(declare-fun col (Int) Int)

(assert (forall ((x Int)) (=> (= x 0) (= (col x) (col (+ x 1))))))
(assert (distinct (col 0) 0))

(check-sat)
(get-value (col))
```

z3 is now saying:

```
sat
((col (_ as-array col)))
```

which is arguably true but not useful at all. A while ago (maybe a few weeks?) it used to say:

```
sat
((col (lambda ((x!1 Int))
  (let ((a!1 (ite (and (not (= x!1 (- 1))) (not (= x!1 1))) 1 3)))
    (ite (and (not (= x!1 (- 1))) (= x!1 1)) 1 a!1)))))
```

which is really much more useful for upstream tools.

**Comment by NikolajBjorner** [comment]
There were some changes to enable SPACER work properly with array models.
Though, there could be a way to have also this desired behavior. The push provides you with the appropriate evaluation.

**Comment by agurfinkel** [comment]
@NikolajBjorner do you remember what was the SPACER issue? 

There was an issue in cex generation (`sat_answer`), but I worked around it by explicitly compressing a model in that code.

**Comment by LeventErkok** [comment]
Thanks @NikolajBjorner 

I can confirm your push fixes the problem. Feel free to close this ticket.
