### ISSUE TITLE
Julia bindings

### ISSUE THREAD

**Issue by XVilka** [Z3Prover/z3#4035]
![](https://julialang.org/assets/infra/logo.svg)
[Julia language](https://julialang.org) becomes more and more popular as a Python alternative in the scientific computational and symbolic software. Along with the proper parallelism out of the box it's way better fit for something like bindings for the SMT solver. I found [zenna/Z3.jl](https://github.com/zenna/Z3.jl) but it seems abandoned. It would be amazing to have Julia bindings out of the box and as a first-class citizen.

**Comment by NikolajBjorner** [comment]
Did you consider https://github.com/Z3Prover/z3/tree/master/src/api/julia?

**Comment by XVilka** [comment]
Haha, I am blind it seems. Thanks! Then it was never mentioned in README or documentation. Would be nice to do that then.

**Comment by NikolajBjorner** [comment]
added to readme.md

**Comment by XVilka** [comment]
There was a typo in README, please see https://github.com/Z3Prover/z3/pull/4068

**Comment by XVilka** [comment]
Also created an issue in that project, for them to update the project description/README https://github.com/zenna/Z3.jl/issues/10
