### ISSUE TITLE
Compile z3 static version with -fPIC

### ISSUE THREAD

**Issue by illera88** [Z3Prover/z3#4038]
Hi,

I'm getting the following error when using the static version of libz3 in a shared library I'm building:

```
/usr/bin/ld: /usr/local/share/vcpkg/installed/x64-linux/lib/libz3.a(memory_manager.cpp.o): relocation R_X86_64_TPOFF32 against hidden symbol `g_memory_thread_alloc_size' can not be used when making a shared object
/usr/bin/ld: /usr/local/share/vcpkg/installed/x64-linux/lib/libz3.a(api_ast.cpp.o): relocation R_X86_64_PC32 against symbol `_ZTVSt9basic_iosIcSt11char_traitsIcEE@@GLIBCXX_3.4' can not be used when making a shared object; recompile with -fPIC
```

It seems that the static version of libz3 is not being compiled using `-fPIC` producing this problem. Is there any reason why `-fPIC` is not set when building libz3 statically?

I built libz3 using `vcpkg` (it uses the default z3 build parameters).

Cheers

**Comment by NikolajBjorner** [comment]
Merged.
New release: good point. Just went over a major revision so time to tone down the churn and stabilize for a release.
