### ISSUE TITLE
Build scripts fail on Linux for non-standard --prefix

### ISSUE THREAD

**Issue by martin-neuhaeusser** [Z3Prover/z3#404]
The mk_make build script fails (on current master) if a non-standard installation directory is specified with the --prefix command line option:

```
python ./scripts/mk_make.py --ml --prefix=/home/marneu/local
opt = --ml, arg = 
opt = --prefix, arg = /home/marneu/local
New component: 'util'
New component: 'polynomial'
New component: 'sat'
New component: 'nlsat'
New component: 'hilbert'
New component: 'simplex'
New component: 'automata'
New component: 'interval'
New component: 'realclosure'
New component: 'subpaving'
New component: 'ast'
New component: 'rewriter'
New component: 'normal_forms'
New component: 'model'
New component: 'tactic'
New component: 'substitution'
New component: 'parser_util'
New component: 'grobner'
New component: 'euclid'
New component: 'core_tactics'
New component: 'sat_tactic'
New component: 'arith_tactics'
New component: 'nlsat_tactic'
New component: 'subpaving_tactic'
New component: 'aig_tactic'
New component: 'solver'
New component: 'interp'
New component: 'cmd_context'
New component: 'extra_cmds'
New component: 'smt2parser'
New component: 'proof_checker'
New component: 'simplifier'
New component: 'fpa'
New component: 'macros'
New component: 'pattern'
New component: 'bit_blaster'
New component: 'smt_params'
New component: 'proto_model'
New component: 'smt'
New component: 'bv_tactics'
New component: 'fuzzing'
New component: 'smt_tactic'
New component: 'sls_tactic'
New component: 'qe'
New component: 'duality'
New component: 'muz'
New component: 'dataflow'
New component: 'transforms'
New component: 'rel'
New component: 'pdr'
New component: 'clp'
New component: 'tab'
New component: 'bmc'
New component: 'ddnf'
New component: 'duality_intf'
New component: 'fp'
New component: 'nlsat_smt_tactic'
New component: 'smtlogic_tactics'
New component: 'fpa_tactics'
New component: 'ufbv_tactic'
New component: 'sat_solver'
New component: 'portfolio'
New component: 'smtparser'
New component: 'opt'
New component: 'api'
New component: 'shell'
New component: 'test'
New component: 'api_dll'
New component: 'dotnet'
New component: 'java'
New component: 'ml'
New component: 'cpp'
Python bindings directory was detected.
Traceback (most recent call last):
  File "./scripts/mk_make.py", line 14, in <module>
    API_files = init_project_def()
  File "/home/marneu/solver/z3/scripts/mk_project.py", line 95, in init_project_def
    add_python_install(_libz3Component)
  File "/home/marneu/solver/z3/scripts/mk_util.py", line 2056, in add_python_install
    reg_component(name, PythonInstallComponent(name, libz3Component))
  File "/home/marneu/solver/z3/scripts/mk_util.py", line 1360, in __init__
    assert PYTHON_PACKAGE_DIR.startswith(PREFIX)
AssertionError
```

The configuration succeeds, if the `--prefix` option is not used.
The `--ml` option does not seem to be related to the problem; it occurs with and without `--ml`

**Comment by wintersteiger** [comment]
Yes, at the moment the Python package directory is required to be within the prefix. We already had to weaken that requirement on OSX, where Python usually lives in /Library. Do you have an actual requirement for Python being installed outside of the prefix or did you expect the Python API to be installed in your prefix?

**Comment by wintersteiger** [comment]
@delcypher, could you take a look at this? I think the best way to handle this is to simply disable the installation of the python bindings if the user didn't explicitly request them to be included (like we do for all the other APIs). Users would then also expect the errors/warnings regarding the installation directories that they chose.

**Comment by martin-neuhaeusser** [comment]
We actually do not use the Python API at all. 
We use the `--prefix` option to make Z3 install itself in a user specified (and otherwise empty) directory.
Of course, there are no Python libraries installed in that location.

**Comment by delcypher** [comment]
> @delcypher, could you take a look at this? I think the best way to handle this is to simply disable the installation of the python bindings if the user didn't explicitly request them to be included (like we do for all the other APIs). Users would then also expect the errors/warnings regarding the installation directories that they chose.

I agree with this. I'd also like to do the same for the .NET bindings. I think treating all bindings equally is the right approach.

I'm currently travelling so I won't be able to take a proper look for a day or so but when I'm back I'll have a go at fixing this.

**Comment by delcypher** [comment]
@martin-neuhaeusser 

As a temporary work around you can try building like this

```
python ./scripts/mk_make.py --ml
make
make install DESTDIR=/home/marneu/local
```

Please note I've not tested this as I don't use the Ocaml bindings. If it doesn't work then you run the install please open up a separate issue as that means the install process for the Ocaml bindings is not respecting the ``DESTDIR`` makefile variable.

**Comment by wintersteiger** [comment]
The OCaml API is installed through ocamlfind, which will use it's own mechanisms to put the files into places that it thinks are good. It has an option called `-destdir`, but I have no idea whether that could be used to make it support `$(DESTDIR)`.

**Comment by wintersteiger** [comment]
The .NET bindings should be optional on all platforms now, I made that change a couple weeks ago or so.

**Comment by martin-neuhaeusser** [comment]
I think it is best to let ocamlfind install the OCaml specific bindings.
Usually, the OCaml libraries and interfaces are located at a different place (e.g. ~/opam/4.02.3/lib/Z3) than the other bindings or the so/dll. I guess that $(DESTDIR) usually points to the latter place (e.g. /usr/local), right?

**Comment by wintersteiger** [comment]
No, $(PREFIX) points to /usr/local, and in addtion $(DESTDIR) is where the $(PREFIX) starts from, so that things can be installed into file systems that don't start at root. So, $(DESTDIR)/$(PREFIX) is where files are copied to and I'm not sure ocamlfind can do that.

**Comment by martin-neuhaeusser** [comment]
Ok, I see.
However, the place where the OCaml specific files are installed is usually different to the place where other bindings need to reside. I.e. one probably does not want other bindings to be installed at the same location.

@delcypher 
I tried to supply the DESTDIR parameter to `make install` and this works out nicely.
ocamlfind is used to determine the correct place for the bindings, and succeeds.

**Comment by wintersteiger** [comment]
DESTDIR is used for staged install, i.e., when you want to set up a completely new system onto, say, a fresh disc that is mounted into /mnt/newdisc. In that case we want libz3.so to go into /mnt/newdisc/usr/local/lib, i.e., DESTDIR=/mnt/newdisc and PREFIX=/usr/local
