### ISSUE TITLE
Spacer hangs when unused (unconstrained) var is added

### ISSUE THREAD

**Issue by leonardoalt** [Z3Prover/z3#4054]
Given these two queries:
1. https://gist.github.com/leonardoalt/0cee9cb2e86082b9c7f2fa1c7c88a0be
2. https://gist.github.com/leonardoalt/aa46fc20d937b8d85258a08e10f1cd32

The second one is basically the first one plus an `Array` variable that is just passed around the rules but unconstrained.
The first one is solved in 0.4s, whereas the second one hangs.

Any idea why that happens?

**Comment by agurfinkel** [comment]
what options are you using?

**Comment by leonardoalt** [comment]
This happens without any extra options. I just tried with the options that I also use in the C++ api:
`fp.spacer.q3.use_qgen=true fp.spacer.mbqi=false fp.spacer.ground_pobs=false`
the behavior is the same

**Comment by agurfinkel** [comment]
`fp.spacer.weak_abs=false` seems to help.

The default setting for option is tuned based on my use. It seems not idea for your case. 
`weak_abs` option limits array reasoning. This speeds things up when an instance has many unimportant array terms.

**Comment by leonardoalt** [comment]
Oh nice, thanks!
I think it's time for me to code something that tunes the parameters and redoes queries ;)

**Comment by agurfinkel** [comment]
I think a combination of `fp.spacer.weak_abs=true` and constant arrays is the root cause. I'll continue debugging, but for now, set the `weak_abs` option to `false` and let me know if you run into any performance issues.

**Comment by leonardoalt** [comment]
`fp.spacer.weak_abs=false` worked for me as well for this case. I'll try it on other examples as well and will let you know. Thanks again.

**Comment by leonardoalt** [comment]
@agurfinkel would you say that
`fp.spacer.weak_abs=false` goes well together with (`fp.spacer.q3.use_qgen=true`, `fp.spacer.mbqi=false`)?
Just trying to have some different strategies, but hopefully not more than 2 or 3 for now.

**Comment by agurfinkel** [comment]
We are working on this now. Conceptually `weak_abs=false` goes well with `ground_pobs=false` and the rest of `quic3`. In practice, it only works for safe system and will prevent generating cexs. We are working on addressing it. Looks easy on paper, so I am expecting an update in the next few days.

**Comment by leonardoalt** [comment]
Nice, thanks!

**Comment by agurfinkel** [comment]
@leonardoalt finally got this into master. Would be interested to know how well this works for you. Set `weak_abs=true` and `ground_pobs=false` plus the rest of your options.

**Comment by leonardoalt** [comment]
@agurfinkel did this actually make the release 4.8.8? My test that triggered this issue actually doesn't have that issue anymore with `weak_abs=true` on 4.8.8

**Comment by agurfinkel** [comment]
No, unfortunately we just got it done. The issue that it fixes is that without it the combination of `weak_abs=true` and `ground_pobs=false` would never produce a counterexample. It would stuck with unknown. Now counterexamples should be produced. This also affects lots of other places where a conjecture is made and a partial counterexample must be produced in order to make progress.
