### ISSUE TITLE
Floor and Ceiling  Function  implementation in Z3

### ISSUE THREAD

**Issue by VerifierIntegerAssignment** [Z3Prover/z3#4066]
I have tried to implement Floor and Ceiling  Function as defined in the following link

https://math.stackexchange.com/questions/3619044/floor-or-ceiling-function-encoding-in-first-order-logic/3619320#3619320

But Z3 query returning counterexample. 

Floor Function

_X=Real('_X')
_Y=Int('_Y')
_W=Int('_W')
_n=Int('_n')
_Floor=Function('_Floor',RealSort(),IntSort())
..
_s.add(_X>=0)
_s.add(_Y>=0)
_s.add(Implies(_Floor(_X)==_Y,And(Or(_Y==_X,_Y<_X),ForAll(_W,Implies(And(_W>=0,_W<_X),And(_W ==_Y,_W<_Y))))))
_s.add(Implies(And(Or(_Y==_X,_Y<_X),ForAll(_W,Implies(And(_W>=0,_W<_X),And(_W==_Y,_W<_Y))),_Floor(_X)==_Y))
_s.add(Not(_Floor(0.5)==0))

Expected Result - Unsat

Actual Result - Sat

Ceiling Function

_X=Real('_X')
_Y=Int('_Y')
_W=Int('_W')
_Ceiling=Function('_Ceiling',RealSort(),IntSort())
..
..
_s.add(_X>=0)
_s.add(_Y>=0)
_s.add(Implies(_Ceiling(_X)==_Y,And(Or(_Y==_X,_Y<_X),ForAll(_W,Implies(And(_W>=0,_W<_X),And(_W ==_Y,_Y<_W))))))
_s.add(Implies(And(Or(_Y==_X,_Y<_X),ForAll(_W,Implies(And(_W>=0,_W<_X),And(_W==_Y,_Y<_W)))),_Ceiling(_X)==_Y))
_s.add(Not(_Ceilng(0.5)==1))

Expected Result - Unsat

Actual Result - Sat

**Comment by rainoftime** [comment]
A smt-lib2 version of the second test.
~~~~
(declare-fun _X () Real)
(declare-fun _Y () Int)
(declare-fun _Celling (Real) Int)
(assert
 (>= _X 0.0))
(assert
 (>= _Y 0))
(assert
 (let (($x57 (forall ((_W Int) )(=> (and (>= _W 0) (< (to_real _W) _X)) (and (= _W _Y) (< _Y _W))))
 ))
 (=> (= (_Celling _X) _Y) (and (or (= (to_real _Y) _X) (< (to_real _Y) _X)) $x57))))
(assert
 (let (($x57 (forall ((_W Int) )(=> (and (>= _W 0) (< (to_real _W) _X)) (and (= _W _Y) (< _Y _W))))
 ))
 (=> (and (or (= (to_real _Y) _X) (< (to_real _Y) _X)) $x57) (= (_Celling _X) _Y))))
(assert
 (not (= (_Celling (/ 1.0 2.0)) 1)))
(check-sat)
~~~
I feed the case to CVC4, which also gives "sat"

**Comment by NikolajBjorner** [comment]
you are missing some universal quantifiers over _X and _Y.
