### ISSUE TITLE
Appending to arrays

### ISSUE THREAD

**Issue by bdrodes** [Z3Prover/z3#4074]
I'm working in the python API. 

I'm investigating (1) concatenating two arrays, and (2) appending values to the end of an array where I don't know the last index of the array. I realize where string domains are used, what it means to append two arrays or to add to 'the end' of an array may not be clearly defined, but I was wondering if you have any recommendations or common idioms to achieve either of these goals (especially with String domains).

I'm currently only familiar with either setting constraints directly on index array elements (something like `a[x] == y')  and using 'Store', both cases assume I have some means to identify an index. 

Thanks.

**Comment by NikolajBjorner** [comment]
Arrays are typically used for modeling total applicative maps. The maps are total on their domain, so they map all values from the domain (say Int or Real) to some value in the range type (e.g,, Bool).
When you write 
 
           (select a i)

where a is an array and i is an index type, then the resulting term is some value in the range.

So the notion of _appending_ two arrays isn't quite a fit for a model where you append arrays.
You can perhaps get away with some lambda overlay encoding as you would do in a functional language, e.g,,

    (lambda ((x Int)) (if (> x 0) (select a x) (select b (+ 10 x)))

but it is somewhat deeper water regarding solving capabilities.

Elements of type (Seq T) where T is some sort (e.g, (Seq Int), a sequence of integers), are finite lists.
They come with an append operation (seq.++). Reasoning about sequences is incomplete, and best effort (and currently I am churning on the solver so the nightly builds are totally unstable, so use a release unless you have too much energy and time to waste). They could be a more useful match for what you want. 
Both sequences and arrays are treated as extensional objects. That is, we are also interested in knowing equalities between arrays and between sequences. For some applications extensionality is overkill. Then instead just use a function. Concatenation of two functions is defined similar to the lambda, but this time it is just inlined where the concatenation is used.
For example given functions

     (declare-fun f (Int) Int)
     (declare-fun g (Int) Int)

and we want a function h that behaves like f on integers 0 to 9, and like g on 10 to 19, we let

     (define-fun h ((x Int)) Int (if (< x 10) (f x) (g x))))

and the constraints use f, g, h. If you can get away with just using such functions for your use it is by far the most effective for reasoning.

**Comment by bdrodes** [comment]
Seems like some good leads. I'll go and explore these a bit. Thanks!
