### ISSUE TITLE
Consider using something other than __builtin_unreachable for the UNREACHABLE macro

### ISSUE THREAD

**Issue by copumpkin** [Z3Prover/z3#4093]
On macOS, compiling and running the following program (with clang):

```
#include <stdio.h>

int main() {
  printf("ohai!\n");
  __builtin_unreachable();
}
```

gives me this output:

```
$ ./test
ohai!
Illegal instruction: 4
```

and the same thing on Linux with `gcc` 4.4.6:

```
$ ./test
ohai!
zsh: segmentation fault  ./test
```

Since both `UNREACHABLE` and `NOT_IMPLEMENTED_YET` macros use it, it leads to less-than-ideal UX when hitting an unexpected `NOT_IMPLEMENTED_YET` case. Much more pleasant would be a call to `abort` with a message suggesting to file a bug on the tracker (maybe with macro source locations), not just because it can link to the tracker, but also because I think the user _perception_ difference between a segfault and an error message saying "sorry we haven't implemented this yet" is quite significant. I do realize that this isn't true in debug builds, but most users aren't running debug builds and will likely see what appears to be a segfault.

If folks don't object, I'd be happy to put together a PR with the change, but I wanted to solicit feedback first in case I was missing something.

**Comment by NikolajBjorner** [comment]
yes, this is very reasonable. 
Currently we get undefined behavior.
It makes debugging tougher. A pull request would be great, as long as the call to abort compiles on all platforms (I guess it does as the call has been a part of the C standard library since forever)
