### ISSUE TITLE
What are the prerequisites to build z3?

### ISSUE THREAD

**Issue by UnixJunkie** [Z3Prover/z3#41]
I know of: python (is it a specific version we need?), a c++ compiler, make.
Are there any others I should know about?
Any library for example?
I am trying to create an opam (a source-based installer for OCaml programs) package for z3 so I should know.
Thanks a  lot,
F.

**Comment by wintersteiger** [comment]
In terms of libraries, openmp required for parallelism, but we can compile it without that. The other APIs required of course corresponding tool chains. -lpthread and -lrt are also required on most platforms. Might be worth taking a look at z3/build/config.mk in case I missed something.

**Comment by wintersteiger** [comment]
Closing as resolved, feel free to re-open if more questions come up.
