### ISSUE TITLE
Public continuous integration testing

### ISSUE THREAD

**Issue by delcypher** [Z3Prover/z3#410]
I'd like propose that publicly visible continuous integration (CI) testing is added by using [TravisCI](https://travis-ci.org/). This **does not** replace the internal testing already done. Instead its purpose is to provide early feedback by checking Z3 (and its bindings) will compile and can be installed.

The neat things about TravisCI is that it can be set up to build every pull request in addition to the current `master` branch. This is very handy because you can quickly see if outside contributions break the build. It will also send e-mails to the authors of commits that break the build.

TravisCI runs on Ubuntu Linux so this CI would only be for this platform. It is a free service for open source projects.

If this idea was accepted I would like to test the following configurations
- CXX=clang-3.7 Release build
- CXX=gcc-4.8 Release build
- CXX=clang-3.7 Debug build
- CXX=gcc-4.8 Debug build

We could test more configurations (e.g. different python versions) but the more configurations we add the longer it will take to complete the builds.

Each configuration would build Z3 and all the language bindings and check that install works correctly. Lightweight testing code be done on the Z3 binary in the future if desired.

I have quite a bit of experience setting up TravisCI so I'm happy to do the work here but I won't start unless I get the go-ahead from @NikolajBjorner and @wintersteiger because it would be a waste of my time to implement something that will never be accepted.

**Comment by wintersteiger** [comment]
Our own internal CI is publically visible, see *.log [here](https://github.com/Z3Prover/bin/tree/master/nightly). I have also set up TravisCI in *.yml in the build-ng branch on my own fork [here](https://github.com/wintersteiger/z3/tree/build-ng). Last time I checked, TravisCI also had a time limit on builds (1 hr?) and I remember thinking that running [bigtest.py](https://github.com/Z3Prover/z3test/blob/master/scripts/bigtest.py) would possibly exceed that, however, for now we only run [smalltest.py](https://github.com/Z3Prover/z3test/blob/master/scripts/smalltest.py) on all non-Windows platforms, which I hope still finishes within that limit.

The problem I haven't gone further with this was that TravisCI only supports one flavour of Linux, and it only partially supports OSX (e.g., no Java yet). I'm currently looking for a solution that offers at least more than one of our configurations. I'm also looking into Windows builds at visualstudio.com, haven't gotten anything working yet. 

I think this kind of contribution is very welcome as long as it is properly set up and maintained.

**Comment by delcypher** [comment]
> Our own internal CI is publically visible, see *.log here

Sorry I didn't know that.

> Last time I checked, TravisCI also had a time limit on builds (1 hr?) and I remember thinking that running bigtest.py would possibly exceed that, however, for now we only run smalltest.py on all non-Windows platforms, which I hope still finishes within that limit.

I believe the time limit has not changed. I wasn't aiming at exhaustive testing. I was thinking more of just checking that the build still compiles and installs. Your internal testing would pick up worse problems eventually.

> The problem I haven't gone further with this was that TravisCI only supports one flavour of Linux, and it only partially supports OSX (e.g., no Java yet). I'm currently looking for a solution that offers at least more than one of our configurations. I'm also looking into Windows builds at visualstudio.com, haven't gotten anything working yet.

One possible option is [buildbot](http://buildbot.net/). It's a bit of a pain to set up but because it's written in Python it can work on multiple platforms reasonably well. It would be self hosted though so you'd need to provide your own build slaves.

Not sure about Jenkins/Hudson. I've not really used them.

**Comment by wintersteiger** [comment]
Thanks for the point to buildbot, I wasn't aware of that one yet. Definitely worth a closer look!

**Comment by wintersteiger** [comment]
Just in case, I'm currently working on setting up build hosts via visualstudio.com and Azure, which gives us full control over the build hosts. (This is usuall a paid service, but that should be fine for us.)

**Comment by NikolajBjorner** [comment]
Is this closable?

**Comment by delcypher** [comment]
@NikolajBjorner Yes. Let's close this.
