### ISSUE TITLE
(rewriter.flat=false smt.threads=2) Invalid model on QF_S formula 

### ISSUE THREAD

**Issue by muchang** [Z3Prover/z3#4124]
Hi,
For this case, Z3  gives an invalid model:
```
[925] % z3release rewriter.flat=false smt.threads=2 model_validate=true small.smt2
sat
(error "line 10 column 10: an invalid model was generated")
[926] % 
[926] % cat small.smt2
(declare-fun a () String)
(declare-fun b () String)
(declare-fun c () String)
(assert
 (xor (= (str.substr (str.++ a "abc" b) 5 (+ 1)) (str.++ a "a"))
 (distinct (str.substr (str.++ a "abc" b) (+ (str.len a) 1) (+ (str.len b) 3))
  (str.++ "bc" b))
 (distinct (str.substr (str.++ a b) 0 (+ (str.len c)))
  (str.substr (str.++ a b) 0 (+ (str.len a) (str.len b))))))
(check-sat)
[927] %
```

OS: Ubuntu 18.04
Commit: a0de244

**Comment by NikolajBjorner** [comment]
C:\z3\build>z3 4124.smt2 smt.random_seed=0 /v:2
(smt.searching)
sat

C:\z3\build>z3 4124.smt2 smt.random_seed=1 /v:2
(smt.searching)
(smt.seq :increase-depth 2)
(smt.searching)
sat

C:\z3\build>z3 4124.smt2 smt.random_seed=2 /v:2
(smt.searching)
sat

C:\z3\build>z3 4124.smt2 smt.random_seed=3 /v:2
(smt.searching)
sat

C:\z3\build>z3 4124.smt2 smt.random_seed=4 /v:2
(smt.searching)
sat

C:\z3\build>z3 4124.smt2 smt.random_seed=5 /v:2
(smt.searching)
(smt.thread 0)
(smt.thread 1)
(smt.searching)
(smt.searching)
sat

C:\z3\build>z3 4124.smt2 smt.random_seed=7 /v:2
(smt.searching)
sat

C:\z3\build>z3 4124.smt2 smt.random_seed=6 /v:2
(smt.searching)
sat

**Comment by NikolajBjorner** [comment]
likely fixed together with duplicate root cause.
