### ISSUE TITLE
Default setting of smt.arith.solver=6 causes Z3str3 to give incorrect UNSAT answers

### ISSUE THREAD

**Issue by mtrberzi** [Z3Prover/z3#4130]
As of commit 6d12540ceb8de7da344b0266e6a07824913adc5e, which set `smt.arith.solver=6` by default, Z3str3 returns incorrect UNSAT answers on some cases where it should return UNKNOWN. One such case is the following:

```
(set-logic QF_S)
(set-info :status sat)
(declare-fun B () String)
(declare-fun E () String)
(declare-fun F () String)
(declare-fun A () String)
(declare-fun C () String)
(declare-fun D () String)
(assert (= (str.++  E F "a" C "aa" C B C)  (str.++  D D) ))
(assert (= (str.++  E E F B "a")  (str.++  D F "aa" C C "aa" C) ))
(assert (= (str.++  B C "aaaaa" C C "aa" E)  (str.++  F F C C C "aa" C "aa" C C "aaaa") ))
(assert (= (str.++  B B B C)  (str.++  D D) ))
(assert (= (str.++  B B E C C "a")  (str.++  D D) ))
(check-sat)
(get-model)
```

This case is satisfiable (checked with Z3's sequence solver and CVC4), but Z3str3 currently returns UNSAT on it. It should be returning UNKNOWN, but something is happening that prevents the `smt::context` from tracking assumptions, so the necessary routine (`theory_str::validate_unsat_core()`) never gets called because unsat core construction returns early. If I manually choose `smt.arith.solver=2`, Z3str3 returns UNKNOWN as expected.

**Comment by NikolajBjorner** [comment]
this does not reproduce any longer
