### ISSUE TITLE
Invalid model for QF_LIA formula (opt, rewriter.flat false)

### ISSUE THREAD

**Issue by rainoftime** [Z3Prover/z3#4137]
Hi, for the following formula, z3 (commit 38e0968) gives an invalid model
~~~~
(set-logic QF_LIA)
(declare-fun _substvar_1111_ () Bool)
(set-option :model_validate true)
(set-option :rewriter.flat false)
(declare-const v2 Bool)
(declare-const i0 Int)
(declare-const i5 Int)
(declare-const i8 Int)
(declare-const i12 Int)
(declare-const i13 Int)
(assert (or (distinct i5 0) v2 v2))
(assert (> (- 0 91 (- i12) i13 773) 0))
(assert (or _substvar_1111_ (>= 0 (mod (- i12) 91))))
(minimize (+ i0 0 i5))
(minimize (+ i0 0 0))
(maximize (- i0 0 i13))
(maximize (- i0 i5 i8))
(check-sat)
~~~~

**Comment by NikolajBjorner** [comment]
C:\z3\build>z3 4137.smt2
sat

C:\z3\build>z3 4137.smt2 smt.random_seed=1
sat

C:\z3\build>z3 4137.smt2 smt.random_seed=2
sat

C:\z3\build>z3 4137.smt2 smt.random_seed=3
sat

C:\z3\build>z3 4137.smt2 smt.random_seed=4
sat

C:\z3\build>z3 4137.smt2 smt.random_seed=5
sat

C:\z3\build>z3 4137.smt2 smt.random_seed=6
sat

C:\z3\build>z3 4137.smt2 smt.random_seed=7
sat
