### ISSUE TITLE
API Readme

### ISSUE THREAD

**Issue by wintersteiger** [Z3Prover/z3#415]
@delcypher, @NikolajBjorner: I think we should move the API part of README.md somewhere else, perhaps just into a different file or simply into the wiki, which is build just for that kind of purpose. I think this should really next to the API documentation, e.g., in [here](https://github.com/Z3Prover/z3/wiki/Documentation) or in separate READMEs in src/api.

**Comment by delcypher** [comment]
@wintersteiger Sounds good to me. I would be happy with either approach. I feel that having this information within the Z3 repository itself (rather than the wiki) is potentially a better choice because it is easier to keep changes to how the APIs are built in sync with the documentation.

**Comment by wintersteiger** [comment]
Good point about the API documentation, that should perhaps also move closer to each API. At the moment all of them (except ml) are built by running doxygen on *.c/cpp/cs/java in src/api, but really we should have separated configurations, e.g., we might want to use javadoc instead of doxygen for the Java API. 

For that matter, the scripts for generating the native layers should also move into their respective directories, but that's a bigger operation. 

(Aside: the wiki is also a git repository that can be found [here](https://github.com/Z3Prover/z3prover.github.io))

**Comment by NikolajBjorner** [comment]
not sure why this is open after 3 years
