### ISSUE TITLE
java API without let-expression?

### ISSUE THREAD

**Issue by dbinkele** [Z3Prover/z3#4151]
I am using the java-API of 4.8.7. I need to model code blocks like this one:
{
int i =1
return i + 2
}

This could be done by a let-expression in SMT-Lib. It seems this is not accessible via Java.

**Comment by NikolajBjorner** [comment]
Let-expressions is syntax for giving a name to a share sub-expression.
When you use a programmatic API, you just create expressions. You can reuse the same expression in many other expressions. This amounts to a let at the syntax level. 
For example, you can create

```
        IntExpr i = ctx.mkInt(1);
        IntExpr t = ctx.mkAdd(i, ctx.mkAdd(i, 2));
```

(details of whether the API actually has the right functions to allow you to write this directly is ignored here).
The sub-expression 'i' is used twice in this expression.

**Comment by dbinkele** [comment]
Thanks for clarification.
