### ISSUE TITLE
Bad string comparison in Java Statistics class

### ISSUE THREAD

**Issue by cmur2** [Z3Prover/z3#416]
In https://github.com/Z3Prover/z3/blob/master/src/api/java/Statistics.java#L190 is a bad string compare done with == instead of equals() which causes it to fail sometimes. I assume that it's not intended? Would you accept PRs in the future?

Side question: why are there duplicate keys in the Statistics entries? Like "mk bool var" in "[conflicts: 1, mk bool var: 3, arith conflicts: 1, assert lower: 1, assert upper: 1, mk bool var: 1, mk bool var: 1, num allocs: 7733213, rlimit count: 46, max memory: 8.66, memory: 8.5]".

**Comment by cheshire** [comment]
The string comparison is fixed in https://github.com/Z3Prover/z3/pull/401, but that is pending extensive testing....

**Comment by wintersteiger** [comment]
Sure, we accept PRs with bugfixes, see [contribution guidelines](https://github.com/Z3Prover/z3/wiki/Contribution-Guidelines). Isn't #401 your PR? Are you asking whether it makes sense to submit a PR specifically for this fix only, instead of testing #401?

**Comment by wintersteiger** [comment]
Ah! No, I mixed up usernames.

**Comment by cmur2** [comment]
Ah, ok I overlooked that there is a PR that fixes this already - I needed it now so I patched my local installation myself. I consider PRs in general more useful than issues like mine; but I'm hesitating signing a CLA for micro-changes like this hence the question.

Any comments to my side question?

**Comment by wintersteiger** [comment]
There is an exception to the CLA rule for trivial, small changes which would definitely apply for this one here. But, in any case it's always good to check first. 

No comments on the side question yet.

**Comment by NikolajBjorner** [comment]
Is there a repro for side-question on multiple repeated keys in statistics? 
I am unable to produce this scenario in a trivial way.

**Comment by cheshire** [comment]
I think after my pull was merged this was fixed.

**Comment by NikolajBjorner** [comment]
Thanks, then I would close this ticket.
