### ISSUE TITLE
Solving equation with division and equality for nullable custom data types returns UNKNOWN or wrong results

### ISSUE THREAD

**Issue by GennadyGS** [Z3Prover/z3#4179]
Solving equation A = B/C returns correct result (which is great):

```
(declare-fun C () Real)
(declare-fun B () Real)
(declare-fun A () Real)
(assert (= A (/ B C)))

SATISFIABLE
((define-fun A () Real  0.0)
(define-fun B () Real  0.0)
(define-fun C () Real  (- 1.0)))
```

However if I try to solve equivalent equation with values of nullable custom type I get different wrong results: 

For example this equation returns result, corresponding to division by 0:
```
(declare-datatypes ((Special_Real_Null 0)) (((Value (value Real)) (Null))))
(declare-fun C () Special_Real_Null)
(declare-fun B () Special_Real_Null)
(declare-fun A () Special_Real_Null)
(assert 
    (let 
        ((a!1 
	    (ite
                (and 
                    ((_ is (Value (Real) Special_Real_Null)) B)
                    ((_ is (Value (Real) Special_Real_Null)) C))
                (Value (/ (value B) (value C)))
                Null)))
    (and 
        ((_ is (Value (Real) Special_Real_Null)) A)
	(= A a!1))))

SATISFIABLE
((define-fun A () Special_Real_Null (Value 38.0))
(define-fun B () Special_Real_Null (Value (- 1.0)))
(define-fun C () Special_Real_Null (Value 0.0)))
```

If I add some more conditions, Z3 returns UNKNOWN:

```
(declare-datatypes ((Special_Real_Null 0)) (((Value (value Real)) (Null))))
(declare-fun C () Special_Real_Null)
(declare-fun B () Special_Real_Null)
(declare-fun A () Special_Real_Null)
(assert 
    (let 
        ((a!1 
	    (ite
                (and 
                    ((_ is (Value (Real) Special_Real_Null)) B)
                    ((_ is (Value (Real) Special_Real_Null)) C))
                (Value (/ (value B) (value C)))
                Null)))
    (and 
        ((_ is (Value (Real) Special_Real_Null)) A)
        ((_ is (Value (Real) Special_Real_Null)) B)
        ((_ is (Value (Real) Special_Real_Null)) C)
	(= A a!1))))

UNKNOWN
```

Expected behavior: results should be the correct values, satisfying the equation, in the similar way as it works for pure real values from first example.

**Comment by NikolajBjorner** [comment]
division by 0 is _under-specified_. The solver is free to assign any meaning to x / 0, including it could set -1 / 0 = 38.
Since reasoning with / is non-linear, z3 is generally incomplete and may give up.

**Comment by GennadyGS** [comment]
Thank you for explanation, it is OK. 
However, just in case, notice that nullable types work fine for me in much more difficult cases. It seems that something wrong here namely in combination with division when free variable is in divider. 
If I only fix value of divider with additional assertion it works fine.
