### ISSUE TITLE
(error "line 1541 column 10: canceled") response to check-sat

### ISSUE THREAD

**Issue by Heizmann** [Z3Prover/z3#419]
I use 99d2ab4e8e51e39791922d6a8c750879d0657c88 an call z3 with the argument -t:1000.
On [20160117-Z3_ErrorTimeout.smt2.txt](https://github.com/Z3Prover/z3/files/93753/20160117-Z3_ErrorTimeout.smt2.txt) the last response that I obtain is 

    (error "line 1541 column 10: canceled")
however, I expect the response

    unknown
If I use 3f02beb8203bb4bf68e39a168254fc97e8f75338 or a higher timeout, I obtain the expected response.

**Comment by NikolajBjorner** [comment]
The return behavior currently depends where the timeout gets detected. I will try to fix this.

**Comment by Heizmann** [comment]
Thanks. Your fix solved our problem.
