### ISSUE TITLE
Assertion violation at smt_context_inv.cpp:312 (Conseq, smt.threads 6)

### ISSUE THREAD

**Issue by rainoftime** [Z3Prover/z3#4202]
Related and fixed: https://github.com/Z3Prover/z3/issues/4194

----

Hi, for the following formula,
[312.txt](https://github.com/Z3Prover/z3/files/4572581/312.txt)

z3 (commit 39fb44fe0) throws an assertion violation
~~~~
Failed to verify: found
ASSERTION VIOLATION
File: ../src/smt/smt_context_inv.cpp
Line: 312
UNREACHABLE CODE WAS REACHED.
(C)ontinue, (A)bort, (S)top, (T)hrow exception, Invoke (G)DB
~~~~

**Comment by NikolajBjorner** [comment]
likely duplicate with #4210
