### ISSUE TITLE
Assertion violation at smt_consequences.cpp:650 (Conseq, smt.threads 2)

### ISSUE THREAD

**Issue by rainoftime** [Z3Prover/z3#4204]
Related https://github.com/Z3Prover/z3/issues/4196

---

Hi, for the following formula,
[650.txt](https://github.com/Z3Prover/z3/files/4572627/650.txt)

z3 (commit 39fb44f) throws an assertion violation
~~~~
 ASSERTION VIOLATION
 File: ../src/smt/smt_consequences.cpp
 Line: 650
 is_sat != l_false
 (C)ontinue, (A)bort, (S)top, (T)hrow exception, Invoke (G)DB
~~~~

**Comment by NikolajBjorner** [comment]
likely duplicate with #4210
