### ISSUE TITLE
OCaml bindings cannot use Quantifier.mk_lambda_const and Quantifier.mk_lambda

### ISSUE THREAD

**Issue by zhaoyonghe** [Z3Prover/z3#4209]
Hi, 
I got this error when I try to use **Quantifier.mk_lambda_const**. The error message is as follows:

**Error: Unbound value Quantifier.mk_lambda_const**

My z3 library version is 4.7.1. This is the first time that I find I cannot use a specific function.

**Comment by zhaoyonghe** [comment]
Actually I cannot find this function in z3.mli that I installed by opam. But it exists in https://github.com/Z3Prover/z3/blob/master/src/api/ml/z3.mli#L740

**Comment by NikolajBjorner** [comment]
The opam installation is quite possibly for some older version that does not have this feature.
You will have to build z3 yourself for newer features.
Build steps are illustrated here:
https://github.com/Z3Prover/z3/blob/7b1aee48dda022f85b8cc5898be8f5c51f3375c5/azure-pipelines.yml#L44
