### ISSUE TITLE
Do Z3 contains API support get all satisfied solutions API

### ISSUE THREAD

**Issue by YanjieGao** [Z3Prover/z3#4212]
I try https://github.com/Z3Prover/z3/blob/a34c5a9450ed6b5d562c846e7c173ea7187fcfbc/examples/python/all_interval_series.py#L65 this method to get all models (solutions). But this has side effect that more solutions more constraints which lead to performance decrease.

Hope to ask weather Z3 support other API to get all satisfied models (solutions)

**Comment by rainoftime** [comment]
Currently, there are no such APIs inside z3.
There exist several programs for ALL-SAT problem (return all solutions of a SAT instance)
E.g., http://www.sd.is.uec.ac.jp/toda/code/allsat.html

**Comment by YanjieGao** [comment]
Thanks a lot!
