### ISSUE TITLE
rise4fun seems to be running extremely slowly

### ISSUE THREAD

**Issue by copumpkin** [Z3Prover/z3#4214]
I'm not sure if this is the right venue to raise this but even loading the rise4fun homepage outside of the Z3 subdirectory is taking several minutes. It's slow enough that https://downforeveryoneorjustme.com/rise4fun.com thinks it's down.

Oddly, the pages do eventually load.

**Comment by NikolajBjorner** [comment]
it is a recurring issue

**Comment by nunoplopes** [comment]
@pelikhan the slowdown in rise4fun.com has been happening for at least a month now. Is there anything we can do?
