### ISSUE TITLE
QF_FP code causes a hang or performance issue

### ISSUE THREAD

**Issue by kevinclancy** [Z3Prover/z3#422]
The last check-sat took an hour on my computer before I terminated the process.
My z3 executable was built from commit 993a0434b442c92e4e84103490722c5428be5ecd.

[Interval.txt](https://github.com/Z3Prover/z3/files/102736/Interval.txt)

**Comment by wintersteiger** [comment]
Thanks for the report. I had this running in the background and Z3 doesn't hang, it just runs into a hard instance and takes around 3 hrs to solve it. Do you have a reason to suspect that this problem should be easy?

**Comment by kevinclancy** [comment]
I thought that the problem would be easy because the most complicated operation being performed is the multiplication of one ground variable by another. Previously, I've only seen performance this bad in instances involving cubic polynomials and/or division. There is a lot of extraneous stuff in that file, however, so I might try to cull away the irrelevant stuff at some point.
