### ISSUE TITLE
Performance issues of smt.arith.solve 2 and 6 on simple UFLRA formula

### ISSUE THREAD

**Issue by rainoftime** [Z3Prover/z3#4221]
Hi, for the following formula
~~~~
(set-logic UFLRA)
(assert (forall ((q5 Real) (q6 Real)) (not (distinct 0.0 q6))))
(check-sat)
~~~~

CVC4 can solve very quickly
~~~~
unsat
real    0m0.288s
user    0m0.080s
sys     0m0.004s
~~~~

But Z3 (commit f2449df, both smt.arith.sovler=2 and 6) cannot finish in several minutes

**Comment by NikolajBjorner** [comment]
It's a limitation of MBQI. Other tactics handle such formulas (in particular when not specifying UFLRA as the logic).
