### ISSUE TITLE
Refutation verification

### ISSUE THREAD

**Issue by leonardoalt** [Z3Prover/z3#4226]
I was wondering if there's any piece of code, in this code base or externally, that implements a verifier for SMT refutations. Otherwise I might try to implement one, but wanted to ask first.

**Comment by rainoftime** [comment]
Do you mean a proof checker?
For purely SAT problems, there is a commonly used standard  DRAT (also supported by z3).
For SMT problems, it seems that different SMT solvers have different formats.

**Comment by leonardoalt** [comment]
Yea, there's no similar common format for SMT. For now I'm interested in checking the ones z3 gives.

**Comment by leonardoalt** [comment]
Just found z3's internal `proof_checker`. It has a method
`bool proof_checker::check(proof* p, expr_ref_vector& side_conditions)`.
What exactly does it fill `side_conditions` with?

**Comment by agurfinkel** [comment]
As far as I know, proofs in Z3 are a bit unstable and incomplete. `proof_checker` is there for debugging. It is a best effort implementation. For some proof steps, it generates side-conditions that have to be validated by a separate SMT call to certify the proof.

**Comment by leonardoalt** [comment]
Ok, thanks @agurfinkel !
