### ISSUE TITLE
Proof via C++ API

### ISSUE THREAD

**Issue by leonardoalt** [Z3Prover/z3#4228]
I'm trying to get the proof for an `unsat` SMT query via the C++ API by setting the option `z3::set_param("proof", true);`, but I get an exception `there is no current proof`. I'm sure the query is `unsat`, since I only call `m_solver.proof()` when `case z3::check_result::unsat`.
Should I use a different option?

**Comment by agurfinkel** [comment]
Make sure you set `proof` mode before creating any Z3 expressions.

**Comment by leonardoalt** [comment]
More than that actually, it needs to be set even before the `context` and the `solver` are instantiated.
For example, the following code from `examples/c++/example.cpp`:
```
void demorgan() { 
    std::cout << "de-Morgan example\n";
      
    context c;

    z3::set_param("proof", true);
    expr x = c.bool_const("x");
    expr y = c.bool_const("y");
    expr conjecture = (!(x && y)) == (!x || !y);
      
    solver s(c);
    // adding the negation of the conjecture as a constraint.
    s.add(!conjecture);
    std::cout << s << "\n";
    std::cout << s.to_smt2() << "\n";
    switch (s.check()) { 
    case unsat:
        std::cout << "de-Morgan is valid\n";
        std::cout << s.proof() << std::endl;
        break;
    case sat:     std::cout << "de-Morgan is not valid\n"; break;
    case unknown: std::cout << "unknown\n"; break;
    } 
}
```
Returns `unexpected error: there is no current proof`
