### ISSUE TITLE
Addition on `Real` has different behavior across versions

### ISSUE THREAD

**Issue by ranjitjhala** [Z3Prover/z3#423]
Hi @NikolajBjorner, 

I found the following query produces different results -- `sat` and `unsat` -- on 
Z3 versions 4.3.2 and 4.4.1.

```
(set-option :auto-config false)
(set-option :model true)
(set-option :model.partial false)
(set-option :smt.mbqi false)

(declare-fun x () Real)
(declare-fun y () Real)
(push 1)
(assert (and (= x 0.200000) (= y (+ 0.900000 x))))
(push 1)
(assert (not (= y 1.00000)))
(check-sat)
(pop 1)
(pop 1)
(exit)
```

Is there a separate `+` operator for `Real` that I should be using in 4.4.1 (and upwards)? Or is something
else the matter? 

Thanks!

Ranjit.

**Comment by NikolajBjorner** [comment]
It is sat: the model is y = 1.1 and x = 0.2. So you are hitting a bug in 4.3.2. Extra brownie points if you can find it, but I am not sure if it makes any sense to patch an old version.

**Comment by ranjitjhala** [comment]
Hi Nikolaj, I agree that it is sat, the problem is that the new version returns UNSAT while the old version returns SAT... So I'm wondering if the bug is in the new version? But let me triple check once I get to my laptop...

**Comment by NikolajBjorner** [comment]
My local version returns sat.

**Comment by ranjitjhala** [comment]
So z3-4.4.1 (which is the latest release) is producing odd results. 

I should build from source? (i.e. by "local version" you mean master?)

<img width="460" alt="screen shot 2016-01-26 at 12 50 27 pm" src="https://cloud.githubusercontent.com/assets/1650232/12594541/78fbe95c-c42b-11e5-9d1b-d81699576204.png">

**Comment by gridaphobe** [comment]
I also get `unsat` on z3-4.4.1, but `sat` on z3-4.4.0, so the bug appears very recent. (@ranjitjhala and I are both on Mac OS btw)

**Comment by NikolajBjorner** [comment]
Still, the current master branch does not have this bug.

     z3 ranjit.smt2
     sat
    (model
      (define-fun y () Real
       (/ 11.0 10.0))
      (define-fun x () Real
        (/ 1.0 5.0))
   )

    z3 --version
    Z3 version 4.4.2

(and unfortunately we do have to fix various bugs between versions)

**Comment by gridaphobe** [comment]
Ah I see, master works for me as well. Thanks!

**Comment by ranjitjhala** [comment]
No worries Nikolaj -- I was worried this was a Mac thing, glad it's a non issue, will just upgrade to master! Thanks!

**Comment by NikolajBjorner** [comment]
Yes master, Master.
