### ISSUE TITLE
make optimize from tactics

### ISSUE THREAD

**Issue by emilienkofman** [Z3Prover/z3#426]
I use the Python API and I can see that the Tactic class has a solver method in order to create a Solver object from a tactic, but there is no way to create an Optimize object from a Tactic. Is there a reason why Tactics would not be applied to Optimize solvers or it's just something that could be added to z3? 

In the latter how could I try to add this Tactic.optimize method? I gave a look into z3_api.h and found the corresponding Z3_mk_solver_from_tactic, but there is no such thing like Z3_mk_optimize*.
I have to say I understand the Python quite well but I'm not sure about the z3-python bindings.

**Comment by NikolajBjorner** [comment]
The solvers used for optimization are highly constrained and it isn't possible to use arbitrary tactics and still pose optimization queries. I am therefore not exposing ways to adapt optimization with tactics.
