### ISSUE TITLE
get the objective value of soft constrained optimization problem

### ISSUE THREAD

**Issue by tbcdebug** [Z3Prover/z3#4261]
I am trying to use someone else's optimization script in C++ based on z3. I think they used soft constraints to describe the objective. For example, the `optimize` object is named `opt`, and they will have `opt.add(not(y[(k-1)*n+piCnt]), cost(augmentedPi));`, where `not(y[(k-1)*n+piCnt])` is some condition and `cost(augmentedPi)` is the weight. 

I would like to get the final objective value after `opt.check()`. So, I tried printing out `opt.objectives()`, and all of the soft constraints described above were displayed. However, what I want is the final objective value, which is the sum of weights of the unsatisfied soft constraints. The `model` of `opt` also does not seem to contain this value.

**Comment by andrewvaughanj** [comment]
Do you mean the value of the symbolic constants (== “variables”) inside of the “soft” constraints?

You should just be able to get the overall model after your check (as long as it returns SAT) and then evaluate the variables (or complete expressions) you want against this model.

You’ll need to do your own “book keeping” though, in terms of storing the expressions you want to evaluate later on.

**Comment by tbcdebug** [comment]
No, I want the sum of all soft constraints, i.e., the objective of the optimization problem. So, some `y[(k-1)*n+piCnt]` is 0, then no cost is added; if it is 1, then, the cost is added. I want the final cost.

**Comment by andrewvaughanj** [comment]
Yeah, so build up that expression using the Z3 API and then “eval” it — the expression doesn’t have to have been added to be able to eval it.

**Comment by tbcdebug** [comment]
So I think there are two theoretically equivalent problem: 1) build up the objective expression and `minimize`, and 2) `add` all soft constraints. With 1), I get an explicit objective that I can refer to in the solved `model`, I assume that in 2), there should also be something that z3 automatically creates standing for the objective? Otherwise, how does the solver even compare two possible models?

**Comment by andrewvaughanj** [comment]
For the soft constraints, Z3 is just going to skip those that it can’t make true.

Z3 has no idea about their cost or anything like that; they’re just 0-1 terms. If you need more information about the overall things that Z3 has decided, you can get that by eval’ing against the model.

You can also use named assertions to keep track of your 0-1 terms.

**Comment by tbcdebug** [comment]
OK. Is there any good reference on how Z3 handles soft constraints?

**Comment by NikolajBjorner** [comment]
It should be the case that opt.objectives() is a big if-then-else expression that adds up all the soft constraints. This expression can be evaluated using the model that is produced as a side-effect from the check() call.

```
   auto r = opt.check();
   if (r == sat) {
        auto m = opt.get_model();
        for (auto o : opt.objectives())
             std::cout << m.eval(o) << "\n";
    }
```

**Comment by tbcdebug** [comment]
I think this solves it. Thanks so much!
