### ISSUE TITLE
Soundness bug in z3str3

### ISSUE THREAD

**Issue by wolffdy** [Z3Prover/z3#4271]
Hi, I found the following formula gives a wrong answer when using the z3str3 solver:
```
% z3 bug.smt2
sat
% z3 smt.string_solver=z3str3 bug.smt2
unsat
ast_manager LEAKED: 3
Leaked: true
id: 1
% cat bug.smt2
(set-info :smt-lib-version 2.5)
(declare-const a Bool)
(declare-fun b () String)
(assert (=  (< (str.len b) 4)a (or    (str.in.re b (re.++ re.allchar re.allchar (re.* re.allchar) re.allchar)) (str.in.re b (re.++ re.allchar re.allchar re.allchar)))))
(assert (and (=  a true)))
(check-sat)
```
Verified on master, commit: [9c97252](https://github.com/Z3Prover/z3/commit/9c972521c4e94ad8c529eb484e4f6deac68b5109)
OS: 4.19.119-1-MANJARO
[bug.smt2.gz](https://github.com/Z3Prover/z3/files/4609036/bug.smt2.gz)

**Comment by wolffdy** [comment]
slightly cleaned up:
```
(declare-fun s () String)
(assert (< (str.len s) 4))
(assert
 (or (str.in.re s (re.++ re.allchar re.allchar (re.* re.allchar) re.allchar))
 (str.in.re s (re.++ re.allchar re.allchar re.allchar))))
(check-sat)
```

**Comment by mtrberzi** [comment]
Taking a look. You might have found an interesting bug with this one.

**Comment by mtrberzi** [comment]
Nice catch, I was able to make some major improvements to the regex algorithm and model construction with this one. Thanks for the report!

Opened #4358 as a draft for further testing and review.
