### ISSUE TITLE
muZ Query Parsing Error

### ISSUE THREAD

**Issue by markus-kusano** [Z3Prover/z3#428]
Seems to be some kind of parsing issue when using the `query` command and the datalog engine.

The example fixedpoint program from the tutorial (http://rise4fun.com/Z3/tutorialcontent/fixedpoints)

```
(set-option :fixedpoint.engine datalog)
(define-sort s () (_ BitVec 3))
(declare-rel edge (s s))
(declare-rel path (s s))
(declare-var a s)
(declare-var b s)
(declare-var c s)

(rule (=> (edge a b) (path a b)))
(rule (=> (and (path a b) (path b c)) (path a c)))

(rule (edge #b001 #b010))
(rule (edge #b001 #b011))
(rule (edge #b010 #b100))

(query (path #b001 #b100))
(query (path #b011 #b100))
(query (path #b001 b)
  :print-answer true)
```

Results in the following output:

```
(error "line 16 column 13: Invalid function name. Expecting sort list startig with '(' to disambiguate function name")
(error "line 17 column 13: Invalid function name. Expecting sort list startig with '(' to disambiguate function name")
(error "line 18 column 13: Invalid function name. Expecting sort list startig with '(' to disambiguate function name")
```

**Comment by NikolajBjorner** [comment]
I have simplified the format in the master branch, but not updated the online tutorial (nor the executable of the online tutorial).
Queries now take a declaration of a predicate only. They don't take compound expressions.
You should state the first query as follows:

        (declare-rel q1 ())
        (rule (=> path #b001 #b100) q1)
        (query q1)

That is, introduce an auxiliary relation and a suitable rule for the relation.
