### ISSUE TITLE
Invalid model for String formula (z3str3, qflra)

### ISSUE THREAD

**Issue by rainoftime** [Z3Prover/z3#4281]
Hi, for the following formula, z3 (commit a14c2a305) gives an invalid model
~~~~
(set-option :model_validate true)
(set-option :smt.string_solver z3str3)
(declare-const Str10 String)
(assert (= false false (str.< "" Str10) false false false))
(check-sat-using qflra)
~~~~

**Comment by zhendongsu** [comment]
Per Nikolaj's comment on https://github.com/Z3Prover/z3/issues/3771, it seems that he doesn't want new bugs for z3str3 to be filed at the moment.  Perhaps Nikolaj and Murphy could confirm.

@NikolajBjorner @mtrberzi

**Comment by rainoftime** [comment]
https://github.com/Z3Prover/z3/issues/4271
https://github.com/Z3Prover/z3/issues/4275

**Comment by zhendongsu** [comment]
#4275 was reported as a soundness bug for z3 default, but it also triggered z3str3 to crash as a by-product, so that information was included.

**Comment by mtrberzi** [comment]
Z3str3 currently doesn't support `str.<` and `str.<=` but I am working on adding support for these operators.
