### ISSUE TITLE
Invalid model for QF_NRA formula (opt, smt.phase_selection 5)

### ISSUE THREAD

**Issue by rainoftime** [Z3Prover/z3#4289]
Hi, for the following formula, z3 (commit a14c2a3) gives an invalid model
~~~~
(set-logic QF_NRA)
(declare-fun _substvar_364_ () Real)
(set-option :model_validate true)
(set-option :smt.phase_selection 5)
(declare-const v0 Bool)
(declare-const r3 Real)
(declare-const r10 Real)
(declare-const r14 Real)
(declare-const r20 Real)
(assert-soft (or v0 (distinct r3 29.0 (/ r10 (- 0.44916))) (>= r3 0.0 0.0 0.44916 r3)))
(assert (<= 55133007.0 (* _substvar_364_ r20 919736.0 29.0) (/ 683.0 (* 32597220.0 r14 39423833.0 5.0 r3)) 93663575965.0))
(check-sat)
~~~~

**Comment by rainoftime** [comment]
no option
~~~~
(set-logic QF_NRA)
(declare-fun _substvar_97_ () Bool)
(declare-fun _substvar_108_ () Real)
(set-option :model_validate true)
(declare-const r1 Real)
(declare-const v27 Bool)
(push 1)
(assert (or _substvar_97_ v27 (< r1 _substvar_108_ 0.0 (- (+ 10220578070.0 0.17387101 (/ r1 (+ 0.0 822554802.0 (/ 588034462.2 r1))) r1 0.0)))))
(check-sat)
~~~~

**Comment by NikolajBjorner** [comment]
there are too many duplicates being filed as separate bugs.

**Comment by levnach** [comment]
Works fine in f2d3160181fbbac57f7a5d28a54e5a2f53e22b32
./z3 ~/Dropbox/smts/4289.smt2 model_validate=true smt.arith.nl.nra=false
sat
cat ~/Dropbox/smts/4289.smt2 
(set-logic QF_NRA)
(declare-fun _substvar_364_ () Real)
(set-option :model_validate true)
(set-option :smt.phase_selection 5)
(declare-const v0 Bool)
(declare-const r3 Real)
(declare-const r10 Real)
(declare-const r14 Real)
(declare-const r20 Real)
(assert-soft (or v0 (distinct r3 29.0 (/ r10 (- 0.44916))) (>= r3 0.0 0.0 0.44916 r3)))
(assert (<= 55133007.0 (* _substvar_364_ r20 919736.0 29.0) (/ 683.0 (* 32597220.0 r14 39423833.0 5.0 r3)) 93663575965.0))
(check-sat)
