### ISSUE TITLE
Segmentation fault, probably problem with LIRA

### ISSUE THREAD

**Issue by Heizmann** [Z3Prover/z3#429]
Using 9b979b6e1e4c196c870b8bf03febae9fa00fce9d I obtain a segmentation fault on the attached script.
If I change the logic from AUFLIRA to AUFLIA, I cannot reproduce the problem any more.

I am using some 64bit Linux.

The script had originally 74MiB but was minimized by Jürgen Christ's SMT delta debugger.

[gcd1-alloca_true-termination.c.i-ProcessedByDeltaDebugger.smt2.txt](https://github.com/Z3Prover/z3/files/116700/gcd1-alloca_true-termination.c.i-ProcessedByDeltaDebugger.smt2.txt)

**Comment by NikolajBjorner** [comment]
thanks, the bug is most likely due to arith_eq_adapter (and the restrictions that the arithmetic internalizer poses on non-repeated tersm).
