### ISSUE TITLE
Segmentation fault using z3 fixedpoints in unstable

### ISSUE THREAD

**Issue by j58** [Z3Prover/z3#43]
Z3 Version: 4.4.0
OS: Ubuntu 14.04 AMD64
git-commit: dd0d0a907554cd81ca12759b5476d4b7417670bc

If the following is given to Z3 on stdin it will result in a segfault:

(declare-rel T (Int Real Int Real))
(declare-rel REACH (Int Real))
(declare-var x Int)
(declare-var c Real)
(declare-var nx Int)
(declare-var nc Real)
(declare-var delay Real)
(rule (! (=> (and (= x 0) (> c 2.0)) (T x c 1 c)) :named stepint))
(rule (! (=> (and (REACH x c) (T x c nx nc)) (REACH nx nc)) :named tstep))
(rule (! (=> (and (= c 0.0) (= x 0)) (REACH x c)) :named initialstates))
(rule (! (let ((a!1 (and (>= delay 0.0) (= nc (+ c delay)) (or (not (= x 0)) (< nc 5.0)))))
  (=> a!1 (T x c x nc))) :named TICK))

(query (and (REACH x c) (= x 1) (= c 3.0))
  :print-certificate true)

This same input works correctly (i.e., produces the expected result) if run on rise4fun.

Thanks.

P.S., If you have the time I have a related question on stackoverflow concerning z3's output on fixedpoint problems:

http://stackoverflow.com/questions/29704976/z3-fixedpoints-what-is-the-meaning-of-formula-false-in-model

**Comment by NikolajBjorner** [comment]
answered on stackoverflow: use opt branch
