### ISSUE TITLE
Significant difference in the solving time between December and the current version

### ISSUE THREAD

**Issue by mrphrazer** [Z3Prover/z3#430]
Hi,

I observed a significant slowdown in the current version of z3, regarding the attached smt2 file. Git commit `c2ab9b72dc7a30f9e8f2078d44d29f38771c9cfa` (Dec 18) takes 0.1 seconds to solve the attached formula, while the latest git commit `9b979b6e1e4c196c870b8bf03febae9fa00fce9d` takes over 8 minutes on the same machine (tested several times with random seeds). 

[x.smt2.txt](https://github.com/Z3Prover/z3/files/117328/x.smt2.txt)

**Comment by wintersteiger** [comment]
This can happen; we can't always guarantee that the performance of Z3 on one particular file increases monotonically. If you have a reason to believe that this benchmark should be easy then we can take a closer look at it, but without that it's probably not worth the time chasing this up. 

For a start, can you perhaps enable verbose output (-v:10 or set the global verbosity option) in both versions, so we can see whether a fundamentally different tactic is being executed, or whether it's the same tactics but with slightly different heuristics/statistics.

**Comment by mrphrazer** [comment]
Thanks for the quick reply. Well, this formula should not be that hard. It contains a few array reads and little writes, but, primary, bit vector arithmetic and a few conditional branches.  z3 was on that problem class very efficient all the time. 

I attached the output of the new version since it is too long: [current_version.txt](https://github.com/Z3Prover/z3/files/117382/current_version.txt)

The output of the older version is here:
```
(simplifier :num-exprs 12485 :num-asts 36417 :time 0.04 :before-memory 2.60 :after-memory 4.79)
(propagate-values :num-exprs 10822 :num-asts 26605 :time 0.03 :before-memory 4.25 :after-memory 4.38)
(solve_eqs :num-exprs 1313 :num-asts 22865 :time 0.02 :before-memory 4.28 :after-memory 4.56)
(:num-elim-vars 2088)
(elim-uncnstr-vars :num-exprs 1057 :num-asts 23509 :time 0.00 :before-memory 4.46 :after-memory 4.46)
(:num-elim-apps 230)
(bv-size-reduction :num-exprs 1057 :num-asts 23509 :time 0.00 :before-memory 4.46 :after-memory 4.46)
(simplifier :num-exprs 1086 :num-asts 23570 :time 0.00 :before-memory 4.46 :after-memory 4.46)
(max-bv-sharing :num-exprs 1086 :num-asts 23522 :time 0.00 :before-memory 4.46 :after-memory 4.46)
(smt.simplifier-done)
(smt.searching)
(smt.simplifying-clause-set :num-deleted-clauses 1301)
sat
```

**Comment by wintersteiger** [comment]
That looks like the new version does essentially the same as the old version, but right from the start they are solving a different problem, e.g., the first `num-exprs' is higher in the new version, thus the result of the simplifier is not the same anymore. By the end of the preprocessing (just before smt.searching) the new problem has about twice the number of expressions.

Some changes relating to those parts were added end of December, for instance [this](https://github.com/Z3Prover/z3/commit/8e26c977824a0246617eb55a0d2f252f6a13624c) and subsequent bugfixes, which could have consequences for the performance on your problems, but overall/on average they didn't have a negative effect on our benchmarks.

**Comment by mrphrazer** [comment]
@wintersteiger Thanks for your explanation. May I tweak certain parameters to get a similar efficiency?

**Comment by NikolajBjorner** [comment]
The change that makes the difference is: 8e26c977824a0246617eb55a0d2f252f6a13624c
More specifically, when adding the changes from bv_rewriter.cpp and bv_rewriter.h we get different behavior.
