### ISSUE TITLE
(AUFNIRA) Invalid model bug on QF_NRA formula 

### ISSUE THREAD

**Issue by muchang** [Z3Prover/z3#4303]
Hi,
For this case, Z3  gives an invalid model:
```
[662] % z3release model_validate=true small.smt2
sat
(error "line 7 column 10: an invalid model was generated")
[663] % 
[663] % cat small.smt2
(set-logic AUFNIRA)
(declare-fun a () Real)
(declare-fun b () Real)
(assert (= (- b a) 1))
(assert (= 2 (/ 1 a b)))
(assert (< b 0))
(check-sat)
[664] %
```

OS: Ubuntu 18.04
Commit: a14c2a3

**Comment by NikolajBjorner** [comment]
this is related to the new code enabled in a14c2a30516003cd1a60f8b7deca029033d11c78

**Comment by NikolajBjorner** [comment]
Hi,
For this case, Z3  gives an invalid model:
```
[597] % z3-4.8.8 model_validate=true small.smt2
sat
[598] % z3release model_validate=true small.smt2
sat
(error "line 7 column 10: an invalid model was generated")
[599] % 
[599] % cat small.smt2
(declare-fun a () Real)
(declare-fun b () Real)
(declare-fun c () Real)
(declare-fun d () Real)
(assert (distinct b (+ d (div c a))))
(assert (= a (/ c (- b d)) b))
(check-sat)
[600] %
```

OS: Ubuntu 18.04
Commit: a14c2a3

**Comment by levnach** [comment]
It seems working correctly now in f2d3160181fbbac57f7a5d28a54e5a2f53e22b32

./z3 ~/Dropbox/smts/4303.smt2 model_validate=true smt.arith.nl.nra=true
sat
sat
./z3 ~/Dropbox/smts/4303.smt2 model_validate=true smt.arith.nl.nra=false
unknown
unknown
cat ~/Dropbox/smts/4303.smt2 
(set-logic AUFNIRA)
(declare-fun a () Real)
(declare-fun b () Real)
(assert (= (- b a) 1))
(assert (= 2 (/ 1 a b)))
(assert (< b 0))
(check-sat)
(reset)
(declare-fun a () Real)
(declare-fun b () Real)
(declare-fun c () Real)
(declare-fun d () Real)
(assert (distinct b (+ d (div c a))))
(assert (= a (/ c (- b d)) b))
(check-sat)
