### ISSUE TITLE
Weird behaviour of "+" operation over BitVectors

### ISSUE THREAD

**Issue by dennis714** [Z3Prover/z3#432]
Not sure if I hit a bug in Z3 or Z3Py (4.4.2) or I just miss something.
Here is a working example.
I coded Sudoku problem as an example.
How would I detect if all 9 numbers in row are unique?
Yes, there is "Distinct", but before I got to know about it, I made this equation:

`1<<cell1 | 1<<cell2 ... | 1<<cell9 == 0b1111111110 (binary)`

So if 9 input cells has 9 unique numbers, the result of this expression should be
0b1111111110 (all cells has numbers in rage of 1..9, hence the last zero bit).

So far so good, I've encoded this and it works very well: http://pastebin.com/arFLmbeb
Now what is weird is that if I replace OR operation with PLUS...

`1<<cell1 + 1<<cell2 ... + 1<<cell9 == 0b1111111110 (binary)`

... it doesn't works, although, mathematically, everything should work: http://pastebin.com/AtAwk3tx

Do I miss something? Should I use some specific tactic?

Thanks in advance!

**Comment by NikolajBjorner** [comment]
The precedence of + is higher than <<, which is higher than |. 
See https://docs.python.org/2/reference/expressions.html
So add parentheses around 1<<cell_i expressions and your script will give the same results.
You already have parentheses around the first two groups of shift expressions, but the last one would require parentheses before you get an answer (the constraints are unsat if you change | to + without the parentheses).

**Comment by dennis714** [comment]
Thanks!
