### ISSUE TITLE
timeout unknown parameter

### ISSUE THREAD

**Issue by dah-fari7009** [Z3Prover/z3#4327]
Good morning,

I am current using z3 with Java on Windows. Whenever I try to set up a timeout (with Params.add("timeout",100) for e.g), I get the exception :
`com.microsoft.z3.Z3Exception: unknown parameter 'timeout'`

I am not sure whether this is due to the version of com.microsoft.jar that I am using or specific to Windows. The project I am working on requires Java 8, so my attempts to try with com.microsoft.jar built with a later version of Java failed.

Is there any chance you encountered this issue before, and know how I could get the timeout parameter while still using Java 8 ?

Thanks :))
![timeout](https://user-images.githubusercontent.com/35702512/82023291-e9a2f400-9642-11ea-8487-63b522268ef4.PNG)

**Comment by NikolajBjorner** [comment]
This is on a solver object?

**Comment by dah-fari7009** [comment]
Hi,
Yes it is.
`Params p = context.mkParams();
					p.add("timeout",timeout);
					solver.setParameters(p);`

**Comment by NikolajBjorner** [comment]
I was able to reproduce this on SimpleSolver objects and fixed the place where timeouts weren't being registered for simple solvers. I hope this takes care of your scenario. The problem does not reproduce for default solvers or the solvers I created using SolverFor().

**Comment by dah-fari7009** [comment]
Thank you very much ! I am using a default solver (with mkSolver). As I have some dependencies issues on my machine when I try to build z3, I will be able to check whether the fix solved my problem after the next release :)
