### ISSUE TITLE
MaxSMT of Z3 gives incorrect result

### ISSUE THREAD

**Issue by XujieSi** [Z3Prover/z3#433]
I just tried the MaxSMT feature (assert-soft) of Z3 at http://rise4fun.com/z3opt/tutorial/ , however, Z3 gives incorrect result for the following example:
;======== Example  Begin ===========
(declare-fun y () Int)
(declare-fun x () Int)

(assert (<= x y))

(assert-soft (= 0 0) :weight 1 :id group1)

(assert-soft (= y 5) :weight 11 :id group1)

(assert-soft (= x 8) :weight 7 :id group1)

(check-sat)
(get-model)
;=======  Example  End =======

Based on my understanding, our goal is to maximize the weighted sum of satisfied assert-softs, and make sure all assertions are satisfied at the same time. The expected model should be: y = 5 and x can be any integer no larger than 5. But the actual result of Z3 is as follows:

======== Z3 Output  Begin =======
group1 |-> 1
sat
(model 
  (define-fun y () Int
    8)
  (define-fun x () Int
    8)
)
======== Z3 Output  End =======

I would like to learn if I misunderstand the assert-soft in Z3, or there might be a potential bug.

**Comment by NikolajBjorner** [comment]
This is the same issue as #425, that was recently reported. A fix is checked into the master branch.
The binaries running on rise4fun have not been updated (and only get updated infrequently).
