### ISSUE TITLE
Does Z3_solver returned by ``Z3_mk_simple_solver()`` and ``Z3_mk_solver_from_tactic()`` require reference counting?

### ISSUE THREAD

**Issue by delcypher** [Z3Prover/z3#434]
In the C API documentation

-  ``Z3_mk_solver()``
-  ``Z3_mk_solver_for_logic()``

have both have the comment

```
/*

...
       \remark User must use #Z3_solver_inc_ref and #Z3_solver_dec_ref to manage solver objects.
       Even if the context was created using #Z3_mk_context instead of #Z3_mk_context_rc.
...
*/
```

however ``Z3_mk_simple_solver()`` and ``Z3_mk_solver_from_tactic()`` do not have this comment. Is this just an omission or do ``Z3_solver`` objects returned from these two calls **not need reference counting calls**?

**Comment by NikolajBjorner** [comment]
Yes, all "objects" (solver, ast_vector, fixedpoint, optimize) have to be reference counted. see also the implementations of the C#/Java APIs that manage reference counts on such objects (e.g., Context.cs or Context.java).
