### ISSUE TITLE
Unsat core returns constraints it shouldn't return

### ISSUE THREAD

**Issue by grottroll** [Z3Prover/z3#435]
Consider the following script:
`(set-option :produce-unsat-cores true)
(define-sort A () (Array (_ BitVec 16) (_ BitVec 8)))

(declare-fun x () (_ BitVec 8))
(declare-fun y () (_ BitVec 8))
(declare-fun z () (_ BitVec 8))
(declare-fun i () (_ BitVec 16))

(declare-fun a () A)

(assert (!(distinct (bvand #x01 (bvsub z x)) #x00) :named p1))
(assert (! (= x (select a i)):named p2))
(assert (! (= y (select a i)):named p3))
(assert (! (= z (select a i)):named p4))

(check-sat)
(get-unsat-core)
`

It returns p1 p2 p3 p4, while the true core is p1 p2 p4

**Comment by NikolajBjorner** [comment]
Z3 isn't guaranteed to return the minimal core.
You can instrument the "sat" core to minimize cores (sat.minimize_core=true), but this will not have any effect on your example.
