### ISSUE TITLE
Assertion violation on String formula at theory_str.cpp:998 (z3str3, unsat_core)

### ISSUE THREAD

**Issue by rainoftime** [Z3Prover/z3#4365]
Hi, for the following formula,
~~~~
(set-option :unsat_core true)
(set-option :smt.string_solver z3str3)
(declare-const v0 Bool)
(declare-const v1 Bool)
(declare-const v3 Bool)
(declare-const v4 Bool)
(declare-const v5 Bool)
(declare-const v6 Bool)
(declare-const v7 Bool)
(declare-const i0 Int)
(declare-const i2 Int)
(declare-const i4 Int)
(declare-const i6 Int)
(declare-const Str3 String)
(declare-const Str5 String)
(declare-const Str6 String)
(declare-const Str8 String)
(declare-const Str14 String)
(declare-const Str15 String)
(declare-const Str18 String)
(check-sat)
(push 1)
(assert (>= (str.len (str.++ Str3 Str15)) 40))
(push 1)
(assert (! (>= 62 i4) :named IP_9))
(check-sat-assuming (true (! (= v1 (>= 62 i4) (> 0 40) (xor v7 true true (str.suffixof Str15 Str14) true (distinct "" Str3 "ugyymg") (>= 62 i4) (or (= "" "" (str.++ Str15 "" "nmbpwv") Str18 Str15) (=> true v4) (and v7 v1 v3 v6 v3 v1) (= true true (= (str.++ Str15 (str.++ "" Str18 "milicw" (int.to.str 0) "") "nmbpwv") Str14 "" "" "") true v4 true) v6 (= 62 0) v6 v4) true true true) (>= 62 i4) (xor v7 (not v7) true (str.suffixof Str15 Str14) true (distinct "" Str3 "ugyymg") (>= 62 i4) true true true (= (> 0 40) false true v1 true (= v6 (not v7) v3 (and v7 v1 v3 v6 v3 v1) v6)))) :named IP_10)))
(check-sat-assuming (true true))
~~~~

z3 (commit 1c760b0, no ASAN) throws an assertion violation 
~~~~
ASSERTION VIOLATION
File: ../src/smt/theory_str.cpp
Line: 998
u.str.is_concat(a_cat)
(C)ontinue, (A)bort, (S)top, (T)hrow exception, Invoke (G)DB
~~~~

**Comment by NikolajBjorner** [comment]
@mtrberzi - I took a closer look at this one. Not for any particular reason. theory_str was trying to pop an empty list.
The root cause was due to misalignment between using scope push/pop for maintaining a vector and resetting it independently.
It was relatively easy to diagnose. I wonder how many similar bugs there are around and what the plan is to address them.

**Comment by mtrberzi** [comment]
Thanks for looking into this. There are definitely several outstanding "legacy code" smells from Z3str2 and I should be able to hunt for more of these and hopefully address them right away. The other immediate goal is to address some of the unsoundness issues by leveraging `seq_axioms` more heavily in `theory_str` axiom setup. I did this a while ago for `str.substr` and it immediately closed a lot of open issues. I think there are still some terms e.g. `str.indexof` where there are issues that would really benefit from this.
