### ISSUE TITLE
No answer for formula with rounding mode

### ISSUE THREAD

**Issue by alebugariu** [Z3Prover/z3#4380]
For the following formula, Z3 (version 4.8.8) cannot provide an answer (even with a timeout of 30 min):
```
(declare-sort U 0)
(declare-fun rmode_2_U (RoundingMode) U)
(declare-fun U_2_rmode (U) RoundingMode)
(declare-fun r () RoundingMode)

(assert (not (= (U_2_rmode (rmode_2_U r)) r)))
(check-sat)
```

Are there any options/tactics required for this formula? I haven't used any.
Thanks a lot for your help.

**Comment by wintersteiger** [comment]
In general I can't recommend mixing floats with uninterpreted sorts, but for this particular problem it helps to declare the logic, e.g. via `(set-logic QF_FP)`. The net effect is that Z3 will translate `RoundingMode`s to bit-vectors before starting the solver, which is much more efficient than the "lazy" theory that it employs on-the-fly during solving. You get the same effect by using the `fpa2bv` tactic explicitly, e.g. `(check-sat-using (then fpa2bv smt))`.
