### ISSUE TITLE
Z3 single-threaded build should not require pthread

### ISSUE THREAD

**Issue by SweetVishnya** [Z3Prover/z3#4383]
Hi!

We are using Z3 inside a DynamoRIO client. DynamoRIO does not support clients linking pthread.

So, I placed all pthread usage under `ifdef` in #4382 . But I don't know how to completely get rid of pthread usage. The main problem is a `scoped_timer` which uses threads. In Linux this can be done by [alarm](http://man7.org/linux/man-pages/man2/alarm.2.html). But I don't know a way how to handle it in Windows. Also, I didn't remove mutexes for event handlers in `api_solver.cpp`.

**Comment by NikolajBjorner** [comment]
So it is a compile time requirement to exclude pthread dependency.

**Comment by SweetVishnya** [comment]
Yes, but I still have no idea what to do with `scoped_timer`.

**Comment by SweetVishnya** [comment]
Now it seems a lot more complicated to me. I may need Z3 not to link with pthread and run DynamoRIO threads to solve multiple queries at the same time.

**Comment by SweetVishnya** [comment]
So, I need a thread-safe Z3 that does not use pthread. Sounds strange.

**Comment by NikolajBjorner** [comment]
Before we used pthread we used omp, but got rid of omp because >= C++11 supports threads.
OMP would be a different kind of dependency and creates its own issues.

**Comment by NikolajBjorner** [comment]
> Yes, but I still have no idea what to do with `scoped_timer`.

in old days programmers with big beards and and attire comprising of lumber shirts and suspenders used obscure functions like "setitimer", SIGALRM or something along these lines.

**Comment by SweetVishnya** [comment]
I got some magic experience. I build thread-safe Z3. I do not link my DynamoRIO client explicitly with pthread. So, I leave symbols undefined. And it works somehow (even on old Ubuntu 10.04). Maybe it is using dymamorio's pthread. One thing I am trying to avoid is that old GLIBC does not have `clock_gettime`. It solves by installing newer libc there. But I think, it is a bit hacky. I will try to solve this problem later.

**Comment by NikolajBjorner** [comment]
At some point one has to settle with reasonable dependencies. 
Xavier Leroy first added pthreads to Linux in the mid 90s (it was since rewritten). 
I have seen some users compile for Solaris too, but not Iris, HPUX, Aix, or help me VAX :-)

**Comment by NikolajBjorner** [comment]
more seriously, it sounds like you have workarounds, but they are fragile. I believe the more sustainable approach is to have a clean cut no-pthread build mode from z3. It is best developed by contribution because you have the requirements, so this is why I would rather let you drive the updates, but with a reasonable set of updates it can be supported from the z3 repository and hopefully avoid kludges or a fragile state down the line.

**Comment by SweetVishnya** [comment]
The thing is that we will need a thread-safe Z3 at some point to invert multiple branches on one path at once. Maybe we can implement some abstraction for threading in Z3 (or just locally patch it), so we can use safe dynamorios thread functions inside Z3. I am still thinking in background for a clean neat solution. My first step was to create a workaround to make it work.

**Comment by NikolajBjorner** [comment]
So let's settle on requirements when you have them. Seems SINGLE_THREAD is _not_ for you.
You want locks to work. It can be done without pthread dependencies.
My current understanding is as follows:

default mode:
  + atomic operations
  + mutex
  + threads

single thread:
  + atomic operations
  - mutex
  - threads

you:
  + atomic operations
  + mutex
  - internal functions using threads.

**Comment by SweetVishnya** [comment]
Yeah, I will definitely need some time to understand and settle on my requirements. As far as I see it now, I will need a build without parallel solving techniques. Maybe we will need a separate define to disable parallel solvers and tactics. But also I need a thread-safe build, so I can spawn my own threads and solve in them. It seems that I should replace threads/mutexes in z3 with DynamoRIO's threads/mutexes.

YES atomic operations
YES DynamoRIO mutexes
YES DynamoRIO threads
NO parallel solving/tactics

**Comment by SweetVishnya** [comment]
We moved all Z3 code to a separate Symbolic Executor process which gets registers and memory through shared memory from DynamoRIO client (Concrete Executor). So, our DynamoRIO client has no pthread dependencies now. And in Symbolic Executor process we can do whatever we want (including thread-safe parallel solving) and do not have a pthread restriction.
