### ISSUE TITLE
bad model using qf_fp

### ISSUE THREAD

**Issue by kevinclancy** [Z3Prover/z3#439]
First off, this problem uses a 3-bit exponent and an 8-bit significand. It could probably be argued that this is an unreasonably small format, but if that is the case, then perhaps z3 should produce an error message when such a small format is used. Bumping the exponent size up to 4 fixes the problem.

I found this using z3 built from CL 993a0434b442c92e4e84103490722c5428be5ecd

I have six floating-point variables a,b,c, d, ac, and bd. They have been given the following constraints:
a /= +oo
b /= -oo
c /= +oo
d /= -oo

a <= b
c <= d

ac = a+c rounded down
bd = b+d rounded up

Furthermore, I have the assertion (not (<= ac bd))
This should not be satisfiable, since ac <= a + c <= b + d <= bd, but z3 produces a model.

[smt_test.smt2.zip](https://github.com/Z3Prover/z3/files/120556/smt_test.smt2.zip)

**Comment by wintersteiger** [comment]
Yes, the problem does not exist with larger exponent ranges. We support exponents down to 2 bits, so this is a bug.

**Comment by wintersteiger** [comment]
Thanks for the report, this should be fixed now. Turns out it was also buggy for large sbits/small ebits combinations, specifically when the number of sbits is exponentially larger than the number of ebits (here 8 sbits vs 2^ebits = 8 exponent values, triggered this corner case).
