### ISSUE TITLE
Include Z3Config.cmake with the binary release

### ISSUE THREAD

**Issue by artemdinaburg** [Z3Prover/z3#4398]
Hi,

Would it be possible to include Z3Config.cmake and other associated CMake files with the binary release(s)? This would make it easier to include Z3 with third-party projects.

Specifically, LLVM is using Z3, but their [custom FindZ3.cmake](https://github.com/llvm-mirror/llvm/blob/master/cmake/modules/FindZ3.cmake) is broken -- it will not correctly detect a statically compiled Z3 library (it links it as C, and is missing `-lpthread`).

The correct solution is to use Z3's native cmake config; but usage of that is blocked pending the CMake config being included in a binary release, per [this Phabricator comment](https://reviews.llvm.org/D50818#inline-450425).

I can try to make a PR to include the config; is the correct place to modify scripts/mk_unix_dist.py ?

**Comment by NikolajBjorner** [comment]
Pull requests are welcome. They shouldn't break reasonable functionality. 
Non-maintainable PRs don't get in (and they have to build). You also have to agree to a release agreement that the code be used in Z3's MIT licensed project.

scripts/mk_unix_dist.py is _not_ the place related to cmake builds. The script calls our old python build scripts that predate the use of cmake. I take you can work backwards from the LLVM requirements and push what is pushable into z3 so it has common benefits.

**Comment by artemdinaburg** [comment]
Could you point me to the scripts/tooling that builds the binary releases published to github?

**Comment by NikolajBjorner** [comment]
https://github.com/Z3Prover/z3/blob/master/scripts/nightly.yaml
https://github.com/Z3Prover/z3/blob/master/scripts/release.yml

**Comment by XVilka** [comment]
Should be partially fixed by https://github.com/Z3Prover/z3/commit/7e84a4806975c321991935a3ae129edac7c545be I think? Since CMake can use pkg-config for finding the library.

**Comment by NikolajBjorner** [comment]
> I can try to make a PR to include the config;

Pull request not received, but @XVilka says it is at least partially addressed.
