### ISSUE TITLE
(z3str3) Soundness bug on QF_S formula with str.to_code, str.from_code

### ISSUE THREAD

**Issue by muchang** [Z3Prover/z3#4409]
Hi,
For this case, Z3  gives an incorrect answer:
```
[643] % z3 small.smt2
unknown
[644] % cvc4 -q small.smt2
unsat
[645] % z3 smt.string_solver=z3str3 small.smt2
sat
[646] % 
[646] % cat small.smt2
(declare-const a String)
(assert (distinct (str.to_code (str.from_code (str.to_code a))) (str.to_code a)))
(check-sat)
[647] %
```

OS: Ubuntu 18.04
Commit: f2d3160

**Comment by mtrberzi** [comment]
This has returned `unknown` in Z3str3 for a while, but now that we properly support Unicode I think I can take another look at this and get support for `str.from_code / str.to_code`.
