### ISSUE TITLE
(ctx-solver-simplify) Soundness bug on QF_S formula with regex 

### ISSUE THREAD

**Issue by muchang** [Z3Prover/z3#4421]
Hi,
For this case, Z3  gives an incorrect answer:
```
[622] % z3release small.smt2
sat
unsat
[623] % 
[623] % cat small.smt2
(set-logic QF_S)
(declare-fun a () String)
(declare-fun b () String)
(declare-fun c () String)
(assert (str.in_re (str.++ b "z" a) (re.union (str.to_re "z") (str.to_re "a"))))
(assert (str.in_re (str.++ b "z" a) (re.inter (str.to_re "z") (str.to_re "b") (str.to_re "a"))))
(assert (str.in_re (str.++ b "z" a) (re.++ (re.comp (re.union (str.to_re "z") (str.to_re "b") (re.inter (str.to_re "a") (str.to_re "z")))) (str.to_re "a"))))
(assert (str.in_re (str.++ b "z" a) (re.inter (re.opt (re.union (str.to_re "z") (str.to_re "a") (re.inter (re.+ (str.to_re "a")) (str.to_re "")))) (str.to_re "a"))))
(assert (str.in_re a (re.* (re.range "a" "u"))))
(assert (str.in_re b (re.opt (re.range "a" "u"))))
(check-sat-using ctx-solver-simplify)
(check-sat)
[624] %
```

OS: Ubuntu 18.04
Commit: 7e84a48

**Comment by NikolajBjorner** [comment]
there are some duplicates of this already

**Comment by zhendongsu** [comment]
Nikolaj, which one/ones that you had in mind?   We checked quite carefully and didn't see any similar ones, thus reported it.  Thank you.

**Comment by NikolajBjorner** [comment]
#4339

**Comment by zhendongsu** [comment]
Nikolaj, but `ctx-solver-simplify` incorrectly reports `sat` here, while for #4339, it incorrectly reports `unsat`; also `re.comp` seems critical for this test.  Perhaps you have other means to help triage these?   Thanks again.

**Comment by NikolajBjorner** [comment]
ctx-solver-simplify replaces sub-expressions by true/false. The end result depends on nestings of negations, so they can be sat or unsat depending on context, not on overall unsoundness.

**Comment by zhendongsu** [comment]
Thanks, Nikolaj, but I still don't see what you used to conclude that the two are the same issue; I trust your judgment and am curious to know what was the underlying cause for the unsoundness.

**Comment by NikolajBjorner** [comment]
I think it goes without saying that the repros are very similar: they both exercise regexes and ctx-solver simplifier. We have to keep these bugs focused. There is too much small stuff being filed right now.

**Comment by zhendongsu** [comment]
> I think it goes without saying that the repros are very similar: they both exercise regexes and ctx-solver simplifier. We have to keep these bugs focused. 

Sounds good, Nikolaj; thanks. 

> There is too much small stuff being filed right now.

Yes, I agree --- most of the recent stuff with `rlimit` seems to be minor and causes quite some traffic/noise.  We also added some of that for curiosity :) 
@muchang @wintered
@rainoftime
