### ISSUE TITLE
The Z3_param_descrs type could do with more documentation and examples

### ISSUE THREAD

**Issue by delcypher** [Z3Prover/z3#443]
This a minor issue but I thought I'd mention that in the C API

* The ``Z3_param_descrs`` type is not one of the documented types
* There isn't an example of using ``Z3_param_descrs`` in ``examples/c/test_capi.c``. It looks like (based on looking at the Doxygen generated documentation) generally you set the parameters on Z3 objects (e.g. ``Z3_solver`` with ``Z3_solver_set_params()``) with a ``Z3_params`` object but when you want to query what parameters a Z3 object is using (e.g. with ``Z3_solver_get_param_descrs()``) you get back a ``Z3_param_descrs`` rather than a ``Z3_params`` object. Is there a reason that clients don't back a ``Z3_params`` object when requesting the parameters that a Z3 object is using? An illustrative example (that also uses ``Z3_params_validate()``, I'm not quite sure what it's for) would probably help here.

**Comment by NikolajBjorner** [comment]
params_validate checks that a parameter is included in the supported parameters of an object (simplify, tactic, solver). The main value of parameter descriptions is to retrieve documentation from the z3 executable. You can get these descriptions by running z3.exe /pm:<module name> from the console.
Though, I have added C++ API support and C++ example (sorry, no C example, you and others should be able to figure out what the use patterns are for pure C by looking at the C++ wrapper).
