### ISSUE TITLE
Z3Prover JavaAPI "toString()" in  class "Expr"  returns wrong name.

### ISSUE THREAD

**Issue by MaxDing** [Z3Prover/z3#4442]
The `toString` returns wrong name of the `Expr` object. For example:

```java
BoolExpr t1 = ctx.mkBoolConst("a b");
System.out.println(t1.toString());  // print |a b|
BoolExpr t2 = ctx.mkBoolConst("中");
System.out.println(t2.toString());  // print |中|
```

I found that if I new `Expr` object with a string `s` which is not ASCII string or contains space,  then `toString` will return the `|s|`. I think its an unexpected behavior because `z3py` works right in this case. Is it an encoding problem in JavaAPI?

**Comment by NikolajBjorner** [comment]
Python has its own pretty printer. The default pretty printer used from Java has to add enclosing || for strings that are not in the range of characters specified by SMTLIB2 to be re-parsable. Furthermore Z3 restricts its parsing to essentially ascii.
