### ISSUE TITLE
Solver parameter "timeout" doesn't behave correctly when setting timeout of zero

### ISSUE THREAD

**Issue by delcypher** [Z3Prover/z3#445]
The documentation for the solver parameter "timeout" says

```
timeout (unsigned int) timeout (in milliseconds) (0 means no timeout) (default: 0)
```

However if I try and set a timeout of zero when I try to use the solver it returns ``Z3_L_UNDEF`` with the reason ( given by ``Z3_solver_get_reason_unknown()``) ``cancelled``.

Here's a simple demonstration. In ``fpa_example()`` in ``examples/c/test_capi.c`` add the following code just after creating the solver ``s``.

```
  // Set "no timeout" for some reason this causes
  // the solver to get "canceled"... what!?
  Z3_params solverParams = Z3_mk_params(ctx);
  Z3_params_inc_ref(ctx, solverParams);
  Z3_symbol timeoutParamStrSymbol = Z3_mk_string_symbol(ctx, "timeout");
  // "timeout (unsigned int) timeout (in milliseconds) (0 means no timeout) (default: 0)"
  Z3_params_set_uint(ctx,
                     solverParams,
                     timeoutParamStrSymbol,
                     0); // no timeout
  Z3_solver_set_params(ctx, s, solverParams);
  Z3_params_dec_ref(ctx, solverParams);
```

With this code added when running the example you see

```
FPA-example
c4: (and (= x_plus_y (fp.add rm x y))
     (= x_plus_y (fp #b0 #b10000000100 #x5000000000000))
     (not (= rm roundTowardZero))
     (not (fp.isZero y))
     (not (fp.isNaN y))
     (not (fp.isInfinite y)))
Error: canceled
```

As you can see the solver fails with reason ``canceled``.

When I set a non-zero timeout the solver seems to behave correctly. Although sometimes I get ``timeout`` and sometimes I get ``unknown`` back from ``Z3_solver_get_reason_unknown()`` which is a little annoying.

Any idea what is going on here? Is this a bug or am I using the API incorrectly?

**Comment by NikolajBjorner** [comment]
It's a documentation/default bug.

**Comment by delcypher** [comment]
@NikolajBjorner Thanks for the clarification.
