### ISSUE TITLE
Question: Sort 'Set' already declared - why?

### ISSUE THREAD

**Issue by mschwerhoff** [Z3Prover/z3#4460]
Using Z3 4.8.7, the declaration `(declare-sort Set)` yields a `sort already defined` error. Does this mean that Z3 has a theory of sets built in? If so, how can I use it?

The background of my question is that we currently use our own set axiomatisation, adopted from Dafny's. Maybe it could be dropped in favour of Z3's built-in one.

**Comment by NikolajBjorner** [comment]
In z3 (Set A) is treated as a shorthand for (Array A Bool).
It has the advantage that we can just use array operations.
operations union, intersection, setminus, complement, subset are available.
Union is shorthand for ((_ map and) X Y) etc.
There is no "member" but you can use "select" directly.
A potential drawback is that it automatically enforces extensionality, 
which isn't always a user requirement. 
It is also not a theory of "finite" sets - legal models include 
the array that maps all integers to true, e.g., the set of all integers.

**Comment by mschwerhoff** [comment]
Thank you for the explanation, Nikolaj!
