### ISSUE TITLE
Question about fp.neg

### ISSUE THREAD

**Issue by mikhailramalho** [Z3Prover/z3#4466]
Hi all,

In `fp.neg` the negation of NaN is ignored:

https://github.com/Z3Prover/z3/blob/master/src/ast/fpa/fpa2bv_converter.cpp#L700

I could not find any mention of this behavior in the SMT standard, only for `fp.is_pos` and `fp.is_neg`. I also tested it with MathSAT and SymFPU, and they seem to always flip the sign bit.

Is this the intended behavior?

Thanks.

**Comment by LeventErkok** [comment]
I think this is intentional. From section VIIIB of http://smtlib.cs.uiowa.edu/papers/BTRW15.pdf:
> IEEE-754 gives four “specification levels” (extended real, floating-point data, representations and bit-strings) with maps between them. The formalization in this paper is based on the second level of specification. Thus there is only one NaN, as quiet and signalling NaN are introduced at level three. Also, NaN is not regarded to have a sign or a payload as these concepts are introduced at level four. As a consequence, functionality that uses these properties of NaN, such as copy sign, sign of and the total order predicate, has been omitted.

In particular, there is only one `NaN`, so it is not meaningful to ask if `NaN` is positive or negative. In fact, that very same paper states:

> These definitions imply f = NaN ⇔ ¬(isNegε,σ(f) ∨ isPosε,σ(f)).

as a footnote in page 8; that is, a good way to detect a `NaN` is to check if the number is neither negative nor positive.

**Comment by mikhailramalho** [comment]
> I think this is intentional. From section VIIIB of http://smtlib.cs.uiowa.edu/papers/BTRW15.pdf:
> 
> > IEEE-754 gives four “specification levels” (extended real, floating-point data, representations and bit-strings) with maps between them. The formalization in this paper is based on the second level of specification. Thus there is only one NaN, as quiet and signalling NaN are introduced at level three. Also, NaN is not regarded to have a sign or a payload as these concepts are introduced at level four. As a consequence, functionality that uses these properties of NaN, such as copy sign, sign of and the total order predicate, has been omitted.
> 

I see. Is there any plan to support `-NaN`s in Z3?

> In particular, there is only one `NaN`, so it is not meaningful to ask if `NaN` is positive or negative. In fact, that very same paper states:
> 
> > These definitions imply f = NaN ⇔ ¬(isNegε,σ(f) ∨ isPosε,σ(f)).
> 
> as a footnote in page 8; that is, a good way to detect a `NaN` is to check if the number is neither negative nor positive.

Yeah, the SMT standard implies that for `fp.isNegative` and `fp.isPositive`:
```
  o (fp.isNegative (_ FloatingPoint eb sb) Bool)

    [[fp.isNegative]](x) = true iff x is [[-zero]] or [[fp.lt]](x, [[-zero]]) holds.

  o (fp.isPositive (_ FloatingPoint eb sb) Bool)

    [[fp.isPositive]](x) = true iff x is [[+zero]] or [[fp.lt]]([[+zero]], x) holds.
```
but I couldn't find anything for `fp.neg`.

**Comment by martin-cs** [comment]
I believe `(= (fp.neg NaN) NaN)` to be a theorem.  The semantics of `fp.neg` are defined by taking the value in the extended reals, negating it and then rounding back to the floats.  Although it takes a little unpicking of the definitions, the value of (floating-point) NaN is (extended real) NaN, which negates to itself.

**Comment by wintersteiger** [comment]
I agree with the others, -NaN == NaN and there is only one NaN in SMT. The implementation is correct, but hard to read, so I cleaned it up a bit so that this case is obvious now. 

Also:

```
(declare-const x (_ FloatingPoint 11 53))
(declare-const y (_ FloatingPoint 11 53))
(assert (fp.isNaN x))
(assert (= y (fp.neg x)))
(assert (not (= y (_ NaN 11 53))))
(check-sat)
```

correctly says `unsat`.
