### ISSUE TITLE
Problem understanding z3 behaviour with floats 

### ISSUE THREAD

**Issue by cfumex** [Z3Prover/z3#447]
Hello,

I am experimenting with z3 float support. Currently z3 is behaving
erratically, proving some hard VCs and not proving simpler ones. I
have isolated a representative problem to try to understand it with
you.

On this example pasted below, I had to kill z3 (git version) after
~550s. However if I remove the (apparently unrelated) first assertion,
line 9, on "to_bv", z3 returns unsat in less than 2 seconds. Now if I 
add the assertion commented out, line 16, z3 returns unsat in ~90s.

Is this expected ?
Is there any way to anticipate / prevent this behaviour (are the
assertions stated in a bad way, or maybe the trigger's patterns are ...) ?

Thank you,
Clément Fumex
___________________________________________________________

(set-info :source |VC generated by SPARK 2014|)
(set-info :smt-lib-version 2.0)
(set-info :category industrial)
(set-info :status unknown)

(declare-fun to_bv (Float32) (_ BitVec 32))

;; \/ x1 : bv32. is_finite (of_bv x1) -> to_bv (of_bv x1) = x1
(assert
 (forall ((x1 (_ BitVec 32)))
 (! (=>
     (not (or (fp.isInfinite ((_ to_fp 8 24) x1)) (fp.isNaN ((_ to_fp 8 24) x1))))
     (= (to_bv ((_ to_fp 8 24) x1)) x1))
    :pattern ((to_bv ((_ to_fp 8 24) x1))) )))

;; (assert
;;   (forall ((x1 Float32))
;;   (! (=> (not (or (fp.isInfinite x1) (fp.isNaN x1)))
;;          (= ((_ to_fp 8 24) (to_bv x1)) x1)) :pattern (((_ to_fp 8 24) (to_bv x1))) )))

(define-fun l2 () Float32 ((_ to_fp 8 24) #x3F800000)) ; 1.0
(define-fun l3 () Float32 ((_ to_fp 8 24) #x3E800000)) ; 0.25
(define-fun l4 () Float32 ((_ to_fp 8 24) #x454CCCCD)) ; 2 ** 16 / 20 ~= 3276.8
(define-fun l5 () Float32 ((_ to_fp 8 24) #x41200000)) ; 10.0
(define-fun l6 () Float32 ((_ to_fp 8 24) #x41A00000)) ; 20.0

(declare-fun x () (_ BitVec 16))
(declare-fun y () Float32)
(declare-fun res4 () Float32)
(declare-fun res5 () Float32)

(assert (and (fp.leq l3 y) (fp.leq y l2)))                        ; 0.25 <= y <= 1.0
(assert (= res4 (fp.div RNE ((_ to_fp_unsigned 8 24) RNE x) l4))) ; res4 = (float)x / l4
(assert (=> (fp.geq res4 l5) (= res5 (fp.sub RNE res4 l6))))      ; res4 >= 10.0 -> res5 = res4 - 20.0
(assert (=> (not (fp.geq res4 l5)) (= res5 res4)))                ; res4 <  10.0 -> res5 = res4

(assert                                                           ; res5 / y is not finite
 (or (fp.isInfinite (fp.div RNE res5 y))
     (fp.isNaN (fp.div RNE res5 y))))
(check-sat)

**Comment by wintersteiger** [comment]
This looks like a pretty hard problem containing quantifiers and division. Internally all floating-point operations are translated into bit-vector operations, so in this case we end up with a QBF problem, which is often hard, but sometimes we can get lucky. On average, I would expect this type of problem not to be solved efficiently. 

The apparently "unrelated" first assertion contains the only quantifier. If that is removed, Z3 will use a completely different solver that doesn't support quantifiers (a pure SAT solver) and I would expect that, on average, to perform much better. 

Just to clarify: If there is a quantifier in the problem that the simplifier can't get rid of, Z3 will always chose the slow (SMT) solver instead of the SAT solver. It doesn't matter whether anything is "unrelated" or "easy", if a quantiifer is in the problem, Z3 will switch.

**Comment by cfumex** [comment]
Thanks for the very quick answer ! 
This definitely explains things. 

To go a little further: this example was reduced from several VCs where we have a lot of assertions with quantifier in the context which don't seem to be directly related to the current goal (defining functions that are not used etc ...). We tried to remove some of them expecting something like the less of those axioms in the context the quicker z3 would be. However we found out that, while removing /adding such axioms has a lot of impact, we are not able to anticipate this impact at all. This is somewhat illustrated in the VC pasted above where if I uncomment the second assertion with a quantifier z3 returns unsat in 80s instead of nothing in 550s with just the first assertion. 
Is there anything to do about that ? (besides getting rid of all of the axioms with quantifier)

**Comment by wintersteiger** [comment]
There's no magic way to make it consistently fast or predictable, but you should of course remove anything you don't need. If you have actual function definitions in there (i.e., forall x . f(x) = ...) then you can try the macro-finder tactic, which will remove them and replace all calls with their definition, possibly at the cost of memory explosion. Finding the right triggers helps of course, and so does disabling MBQI (set smt.mbqi=false) if you're only looking for unsat results.

**Comment by cfumex** [comment]
It does help in some cases, thanks again for your answers, I'll close the issue.
