### ISSUE TITLE
Assertion Violation: Unreachable Code in fpa2bv_converter.cpp

### ISSUE THREAD

**Issue by wolffdy** [Z3Prover/z3#4470]
Hi, I found the following formula throws an assertion violation for hitting unreachable code:

[bug.smt2.gz](https://github.com/Z3Prover/z3/files/4691789/bug.smt2.gz)

This seems to affect many other formulas that utilize floating point operations, and I'd be happy to provide additional examples that reproduce the issue if they are needed.

```
%  z3 bug.smt2 
ASSERTION VIOLATION
File: ../src/ast/fpa/fpa2bv_converter.cpp
Line: 2433
UNREACHABLE CODE WAS REACHED.
(C)ontinue, (A)bort, (S)top, (T)hrow exception, Invoke (G)DB


% cat bug.smt2
(declare-const a Int)
(declare-const b Real)
(declare-const c (_ FloatingPoint 11 53))
(assert (= c ((_ to_fp 11 53) roundTowardZero b a)))
(check-sat-using smt)
```

Verified on master, commit: 94ffd63
OS: Ubuntu 18.04

**Comment by wintersteiger** [comment]
I added the missing conversion, but this is highly non-linear, so the solver returns unknown now. I don't expect that to change any time soon, so if at all possible, reformulate your problem to use only floats. Real and int numerals should be fine, but not any other int/real expressions.
