### ISSUE TITLE
Possible syntactic bug in inferred pattern

### ISSUE THREAD

**Issue by aterga** [Z3Prover/z3#4473]
Dear Z3 developers, 

I'm writing a simple tool that rewrites SMT files by adding the missing pattern annotations, using the pattern inference capability of Z3. To get the inferred patterns, I run ```z3 -v:10 input.smt2``` and then parse the output using an off-the-shelve SMT-LIB-2 parser. This mostly works well, but for one input file I get triggering terms that don't seem to comply with the SMT-LIB standard. 

Concretely, here is the relevant part of the output of ```z3 -v:10 pat-infer-session.smt2```:

```smt2
(smt.inferred-patterns :qid quant-with-auto-pattern_0
  (let ((a!1 (ApplyTT (ApplyTT (ApplyTT (ApplyTT FStar.Algebra.Monoid.__proj__Monoid__item__mult@tok
                                                 (:var 5))
                                        (:var 2))
                               (ApplyTT (:var 4) (:var 1)))
                      (ApplyTT (:var 4) (:var 0)))))
    (a!1))
  (let ((a!1 (ApplyTT (ApplyTT (ApplyTT (ApplyTT FStar.Algebra.Monoid.__proj__Monoid__item__mult@tok
                                                 (:var 6))
                                        (:var 3))
                               (:var 1))
                      (:var 0))))
    (a!1))
)
```

It seems that the terms should have been printed as 
```(let ((a!1 ...))   a!1  )``` rather than 
```(let ((a!1 ...))    (a!1)   )```. Would you agree? 

Here is the complete example: 
[pat-infer-session.smt2.txt](https://github.com/Z3Prover/z3/files/4696972/pat-infer-session.smt2.txt)

As a side remark, the ```let``` expressions in the listing above are produced by Z3 and are not present in the original formula. Arguably, ```let``` expressions are not the best way to represent the pattern terms. Is there a way to tell Z3 not to use ```let```s in the printer?

**Comment by NikolajBjorner** [comment]
A pattern is a list of expressions. So the parenthesis is used when printing this list. 
Here it uses mk_ismt2_pp

**Comment by aterga** [comment]
Thanks for the quick response. Indeed, the two let-expressions correspond to two multi-patterns, each of which consists of a single term in this case. 

Thanks also for pointing me towards the pretty printer function. Turns out, one can control the format of the pretty printers via options. In particular, the following option solved my problem (no let expressions are introduced by Z3 anymore): 
```
(set-option :pp.max_depth 4294967295)
```
