### ISSUE TITLE
Simple Exists-Expression sends z3 4.8.8 to Infinity, but z3 4.8.6 returns.

### ISSUE THREAD

**Issue by dbinkele** [Z3Prover/z3#4475]
I have the following as input: 

`(assert 
  (exists ((idx Int))
                     (not (= (seq.nth (seq.unit "a") idx)
                                   "a")) ))
(check-sat)`

Running 4.8.8 or 4.8.7 on this snippet never returns, where as 4.6.6 returns and reports SAT.
Replacing all "a" with, say, 1, resolves the problem.

Also feeding
`(check-sat 
  (exists ((idx Int))
                     (not (= (seq.nth (seq.unit "a") idx)
                                   "a"))
                     ))`
returns in short time.

Is this probably a bug?!
Help appreciated.....

**Comment by zhendongsu** [comment]
On Ubuntu 18.04, z3-4.8.7 does seem to hang, but I see that both z3-4.8.8 and the release build of the latest commit (https://github.com/Z3Prover/z3/commit/0911a06d81cd94bbb763b32306ec7ba0a465ecab) return instantaneously: 
```
[516] % time z3-4.8.8 t.smt2 
sat

real	0m0.129s
user	0m0.019s
sys	0m0.000s
[517] % time z3release t.smt2
sat

real	0m0.019s
user	0m0.009s
sys	0m0.006s
[518] % timeout -s 9 10 z3-4.8.7 t.smt2
Killed
[519] % 
```

**Comment by dbinkele** [comment]
probably I need to mention that I am running this on macOs.

**Comment by andrewvaughanj** [comment]
Works for me (fresh build of HEAD as of 5 minutes ago):

```
cassidy:build avj$ uname -a
Darwin cassidy 19.4.0 Darwin Kernel Version 19.4.0: Wed Mar  4 22:28:40 PST 2020; root:xnu-6153.101.6~15/RELEASE_X86_64 x86_64 i386 MacBookPro14,3 Darwin
cassidy:build avj$ git rev-parse --short HEAD
0911a06d8
cassidy:build avj$ cat ../test.smt2
(assert (exists ((idx Int)) (not (= (seq.nth (seq.unit "a") idx) "a")) )) (check-sat)
cassidy:build avj$ time ./z3 ../test.smt2
sat

real	0m0.032s
user	0m0.023s
sys	0m0.005s
```

**Comment by dbinkele** [comment]
I have been simplifying my original code with respect to 4.8.7....not considering 4.8.8.

But this slightly more complicated snippet also does not come back on 4.8.8:

`(assert (not (exists ((idx Int))
                     (not (= (seq.nth (seq.++ (seq.unit "a") (seq.unit "ab"))idx)
                                   "a")))))
(check-sat)`

**Comment by andrewvaughanj** [comment]
I can confirm that this doesn't seem to terminate quickly on a build of `HEAD` on macOS.

**Comment by NikolajBjorner** [comment]
There is a big difference between satisfiability of existentially vs universally quantified formulas.
Asserting (not (exists (....)) corresponds to asserting (forall (.. (not ...))).
It is easy to make solving universally quantified formulas diverge.
The model-based quantifier instantiation methods that are on by default try to find a (essentially finite) model of functions, and in this case  it is not successull in finitely instantiating the quantifier.
You can try the parameters smt.mbqi=false smt.auto_config=false for the universally quantified formula, it finishes, but inconclusively.
