### ISSUE TITLE
Invalid model produced in QF_BV/Sage2

### ISSUE THREAD

**Issue by jhoenicke** [Z3Prover/z3#4479]
During the smt-comp we found that z3-4.8.8 (that we ran as non-competing) produced a faulty model.  The model evaluates the formula to false.
https://www.starexec.org/starexec/secure/details/pair.jsp?id=484410563

I attached the scrambled benchmark and the faulty model.
[bench.484410563.smt2.txt](https://github.com/Z3Prover/z3/files/4707404/bench.484410563.smt2.txt)
[model.z3.484410563.txt](https://github.com/Z3Prover/z3/files/4707405/model.z3.484410563.txt)

z3 was run with `z3 -smt2 bench.484410563.smt 2>/dev/null`

**Comment by NikolajBjorner** [comment]
fixed, no longer repros
