### ISSUE TITLE
Can't generate real values if (push) and (pop) are used but does generate them without it

### ISSUE THREAD

**Issue by jawline** [Z3Prover/z3#448]
When working with the SMT query

`(push)
(declare-fun QR () Real)
(assert (> QR 2.0))
(assert (< QR 3.0))
(check-sat)
(get-model)
(get-info :all-statistics)
(pop)`

I get the output 
`Blake-Laptop-2:Z3JS pbai002$ ./z3/build/z3 ./z3/build/tttt 
unsat
(error "line 9 column 10: model is not available")`

However when I use the source without the pops I get the satisfiable 2.5 for QR. Is this desired behaviour for Z3 and, if so, how do I get real values when using push/pop or should I just use a simple solver and reset it?.

I can recreate this using the C API and when built with Emscripten. 
Built using LLVM on Mac OS X building tagged version z3-4.4.1

**Comment by wintersteiger** [comment]
This problem is reported as satisfiable for me. Could you try to upgrade to the latest master branch of Z3 so that we don't chase bugs that were already fixed? It should report version 4.4.2.

**Comment by jawline** [comment]
Ah - Looks like it doesn't occur on master branch so has probably been fixed. Would you recommend sticking to master for a project which relies on Z3 or to tags? I am currently migrating a project over from a much older version of Z3 to take advantage of LLVM support and trying to reincorporate string solving, but want to minimise risk of introducing new bugs so initially shied away from master. (Not sure what strategy you guys use to mark stable releases).

Thanks for the help

**Comment by wintersteiger** [comment]
Our releases/tags are added infrequently and they just mark points in time at which we invested extra effort on testing and/or they contain new features that are not considered just experimental anymore. If you need the latest bugfixes, keep using master. It does break sometimes, but more often than not in a very obvious way, e.g., build problems.

**Comment by jawline** [comment]
Ah ok, will move onto master. Thanks for the help
