### ISSUE TITLE
(z3str3) Assertion Violation in theory_str_mc.cpp with replacing empty Strings

### ISSUE THREAD

**Issue by wolffdy** [Z3Prover/z3#4486]
Hi, I found the following formula throws an assertion violation with the z3str3 solver on the release and debug builds:

[bug.smt2.gz](https://github.com/Z3Prover/z3/files/4711567/bug.smt2.gz)

```
%  z3 smt.string_solver=z3str3 bug.smt2 
ASSERTION VIOLATION
File: ../src/smt/theory_str_mc.cpp
Line: 728
Failed to verify: pos_exists

% cat bug.smt2
(declare-fun a () String)
(declare-fun b () String)
(declare-fun c () Int)
(assert (= (str.replace "" (str.at "" c) "") (str.replace a b "")))
(check-sat)
```

Verified on master, commit: c967b4a
OS: Ubuntu 18.04

**Comment by mtrberzi** [comment]
Seems like the problem might be with `str.at`, but I can resolve this for you.

**Comment by mtrberzi** [comment]
Opened #4490.
