### ISSUE TITLE
Call external function for uninterpreted function and Operator overloading 

### ISSUE THREAD

**Issue by bja2019** [Z3Prover/z3#4489]
I have two queries 
1) Define a uninterpreted function by calling some external function using Z3 API.

For example, given variable x and y,  perform some calculation using definition of uninterpreted function which is defined externally.
In Z3, when we solve constraints, during that time, is it possible to call some external function ?
Something similar in C++ where we can pass the function pointer and it is called during the solve for some custom function  or operators like = >= etc.

2) Override the operator like =  <= etc for arithmetic operation
I want to define custom comparator for Z3 Expression for operator like equal, less than or equal for real numbers 

For Example, 
(declare-fun A () Real)
(declare-fun B () Real)
(declare-fun C () Real)

(assert (= A 7.9))  ; Can we override the operator = , so that I can define my own equality operator using Z3 API.
(assert (= B 11.3)
(assert (= C  ( callExternalFunction A B )) ; Call external function so that value for C is calculated dynamically during solve.

One of the way I thought using quantifier, but that just works like a macro, not a function.

Any suggestions/examples would be helpful.

**Comment by NikolajBjorner** [comment]
It isn't possible to register a callback with a function over the API.
In the theorem proving community it is known as "procedural attachment". It was introduced in the SNARK theorem prover by Mark Stickel and used by Richard Waldinger. Z3 does not have this feature. In a way it supported procedural attachment when it exposed an API for defining user theories. 

You can integrate procedural attachments in an external way by using a so-called lazy loop around the SMT solver: You get back a model. Then you check if the model with your function (call it "f") applied to values from the model satisfies the properties you want. If it does not, you add the instance of "f" that is violated as a constraint (equality) and solve again with this added constraint.

**Comment by bja2019** [comment]
Thank you for the details. The lazy loop approach would look simplistic view , but I think it would not be. If you have some test example to that would be helpful otherwise it's OK.

**Comment by NikolajBjorner** [comment]
Here is a simplistic example

```
from z3 import *

s = Solver()
f = Function("f", IntSort(), IntSort())
x, y, z = Ints('x y z')

def eval_f(x):
    return x + 1

s.add(f(x) == y)
while True:
    is_sat = s.check()
    if is_sat == sat:
        m = s.model()
        xv = m.eval(x).as_long()
        yv = m.eval(y).as_long()
        if eval_f(xv) == yv:
            print("found solution")
            break
        print("add ", f(xv), " == ", eval_f(xv))
        s.add(f(xv) == eval_f(xv))
```

**Comment by bja2019** [comment]
The test example helps to understand. Thanks for the support
