### ISSUE TITLE
How do I put z3 as a library in my project?

### ISSUE THREAD

**Issue by Flians** [Z3Prover/z3#4500]

**Comment by andrewvaughanj** [comment]
(for reference: [https://github.com/Boolector/boolector/issues/125](https://github.com/Boolector/boolector/issues/125))

**Comment by nunoplopes** [comment]
see the examples here: https://github.com/Z3Prover/z3/tree/master/examples

**Comment by Flians** [comment]
Hi,
I used the z3 in my project. But it's wrong when I built this project.


`
Undefined symbols for architecture x86_64:
  "_btor2parser_delete", referenced from:
      _delete_btor2_parser in libboolector.a(btorbtor2.c.o)
  "_btor2parser_error", referenced from:
      _parse_btor2_parser in libboolector.a(btorbtor2.c.o)
  "_btor2parser_iter_init", referenced from:
      _parse_btor2_parser in libboolector.a(btorbtor2.c.o)
  "_btor2parser_iter_next", referenced from:
      _parse_btor2_parser in libboolector.a(btorbtor2.c.o)
  "_btor2parser_new", referenced from:
      _new_btor2_parser in libboolector.a(btorbtor2.c.o)
  "_btor2parser_read_lines", referenced from:
      _parse_btor2_parser in libboolector.a(btorbtor2.c.o)
  "_lgladd", referenced from:
      _btor_process_skeleton in libboolector.a(btorskel.c.o)
      _add in libboolector.a(btorlgl.c.o)
  "_lglassume", referenced from:
      _assume in libboolector.a(btorlgl.c.o)
  "_lglbnr", referenced from:
      _btor_process_skeleton in libboolector.a(btorskel.c.o)
      _init in libboolector.a(btorlgl.c.o)
  "_lglclone", referenced from:
      _sat in libboolector.a(btorlgl.c.o)
  "_lglderef", referenced from:
      _deref in libboolector.a(btorlgl.c.o)
  "_lglfailed", referenced from:
      _failed in libboolector.a(btorlgl.c.o)
  "_lglfixate", referenced from:
      _sat in libboolector.a(btorlgl.c.o)
  "_lglfixed", referenced from:
      _btor_process_skeleton in libboolector.a(btorskel.c.o)
      _fixed in libboolector.a(btorlgl.c.o)
  "_lglfreeze", referenced from:
      _inc_max_var in libboolector.a(btorlgl.c.o)
  "_lglincvar", referenced from:
      _inc_max_var in libboolector.a(btorlgl.c.o)
  "_lglinit", referenced from:
      _btor_process_skeleton in libboolector.a(btorskel.c.o)
  "_lglmclone", referenced from:
      _clone in libboolector.a(btorlgl.c.o)
  "_lglmelt", referenced from:
      _melt in libboolector.a(btorlgl.c.o)
  "_lglmeltall", referenced from:
      _sat in libboolector.a(btorlgl.c.o)
  "_lglminit", referenced from:
      _init in libboolector.a(btorlgl.c.o)
  "_lglrelease", referenced from:
      _btor_process_skeleton in libboolector.a(btorskel.c.o)
      _reset in libboolector.a(btorlgl.c.o)
      _sat in libboolector.a(btorlgl.c.o)
  "_lglrepr", referenced from:
      _repr in libboolector.a(btorlgl.c.o)
  "_lglsat", referenced from:
      _sat in libboolector.a(btorlgl.c.o)
  "_lglseterm", referenced from:
      _sat in libboolector.a(btorlgl.c.o)
      _setterm in libboolector.a(btorlgl.c.o)
  "_lglsetopt", referenced from:
      _btor_process_skeleton in libboolector.a(btorskel.c.o)
      _enable_verbosity in libboolector.a(btorlgl.c.o)
      _sat in libboolector.a(btorlgl.c.o)
  "_lglsetout", referenced from:
      _sat in libboolector.a(btorlgl.c.o)
      _set_output in libboolector.a(btorlgl.c.o)
  "_lglsetprefix", referenced from:
      _btor_process_skeleton in libboolector.a(btorskel.c.o)
      _sat in libboolector.a(btorlgl.c.o)
      _set_prefix in libboolector.a(btorlgl.c.o)
  "_lglsimp", referenced from:
      _btor_process_skeleton in libboolector.a(btorskel.c.o)
  "_lglstats", referenced from:
      _btor_process_skeleton in libboolector.a(btorskel.c.o)
      _sat in libboolector.a(btorlgl.c.o)
      _stats in libboolector.a(btorlgl.c.o)
  "_lglunclone", referenced from:
      _sat in libboolector.a(btorlgl.c.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
`

**Comment by andrewvaughanj** [comment]
That's a Boolector failure though, and this is the Z3 repo ... you probably want to post that in your other thread: https://github.com/Boolector/boolector/issues/125
