### ISSUE TITLE
BitVec dummy variable prevents to find a trivial solution.

### ISSUE THREAD

**Issue by necto** [Z3Prover/z3#451]
Hello, I am playing with z3 `forall` predicates, and found the following weird behaviour:
To this query:

``` lisp
(assert (forall ((x Int)) (exists ((y Int) (z Int))
                                  (and (= y x) (= 0 z)))))
(check-sat)
```

Z3 responds instantly: `sat`, while to this one (I replaced type of `z` from `Int` to `BitVec32`:

``` lisp
(assert (forall ((x Int)) (exists ((y Int) (z (_ BitVec 32)))
                                  (and (= y x) (= #x00000000 z)))))
(check-sat)
```

It takes an unbearably long time to complete. I tested it both on my laptop (ubuntu 14.04/dual-core i7 2GHz with 8Gb RAM) and a computing mainframe (ubuntu 14.04/48-core Xeon E5 2.7 GHz with 774 Gb RAM).

This query seems trivial to me, and certainly should not depend on the type of `z`. Is there a way to hint Z3 to early discover such substitutions (`x = y` and `z = 0`) and simplify the formulas, before starting bruteforce?

I use the today build of Z3 in the master branch. `z3 -h` prints version `4.4.2`.

**Comment by NikolajBjorner** [comment]
There is a much better quantifier satisfiability routine in the works, but it is not ready for broad consumption. For now, you can interpose the qe-light procedure which solves trivial equations.
    
            (assert (forall ((x Int)) (exists ((y Int) (z (_ BitVec 32)))
                                              (and (= y x) (= #x00000000 z)))))
               (check-sat-using (and-then qe-light qe-sat))

**Comment by necto** [comment]
Thank you, @NikolajBjorner, this hint works.
Unfortunately, it does not produce a model `(get-model)` and it jams on a slightly more complicated query, like:
```lisp
(assert (forall ((x Int))
        (=> (< 0 x) (exists ((w Int) (y (_ BitVec 32)) (z (_ BitVec 32)))
                     (and (= w x) (bvsle y z))))))
(check-sat-using (and-then qe-light qe-sat))
```
Do you have any estimation, when the better quantifier satisfiability routing will be published?

**Comment by NikolajBjorner** [comment]
Use "qsat", described in https://easychair.org/publications/paper/jmM

(assert (forall ((x Int))
                (=> (< 0 x) (exists ((w Int) (y (_ BitVec 32)) (z (_ BitVec 32)))
                                    (and (= w x) (bvsle y z))))))
(check-sat-using (and-then qe-light qsat))
(rese)

(assert (forall ((x Int)) (exists ((y Int) (z (_ BitVec 32)))
                                  (and (= y x) (= #x00000000 z)))))
(check-sat-using qsat)
