### ISSUE TITLE
Saving Z3 partial results for reuse during type inference.

### ISSUE THREAD

**Issue by wdanilo** [Z3Prover/z3#4512]
Hi! I want to use z3 as a backend for type inference for a programming language. I'm researching possible technologies and I'm wondering if the following use case would be possible in z3. I have different modules (files) and each module defines types and functions, not always explicitly typed, often very polymorphic (similar to Haskell, but the type inference bases on completely different assumptions here). I want to be able to incrementally type check the files. So if the user changes one of 100 files, z3 would use "pre-computed" values for the rest of the 99 files in order to get the results faster. My question is if it would be possible to design such a system in z3 where I would not need to run it "from scratch" for all files / libraries but I could just "precompile" libraries and ask z3 to incrementally update them (I can provide z3 with exact information which rules changed). I would be very thankful for any hints and guides here!

**Comment by NikolajBjorner** [comment]
Have you considered passing pre-computed solutions as _assumptions_?
In this way, the assumptions would narrow a search space, but you can remove and add assumptions at will without having to recompile the main constraints from scratch.

http://theory.stanford.edu/~nikolaj/programmingz3.html#sec-assumptions

**Comment by wdanilo** [comment]
@NikolajBjorner thank you so much for a fast reply! I haven't considered it yet, I will definitely try it. I'm asking these questions pretty early in the research process, as I'm not knowledgable in this domain enough yet to swiftly validate your idea against all corner cases which may appear during the implementation. I just don't want to spend months before realizing that actually some complex cases will not be possible - the question was about the one case that I'm most afraid of. 

Nikolaj, I understand this is a very broad follow-up question, but in case the answer is short and would not take too much time of yours, I would be very thankful for a short reply. If you would implement a type inference engine (a lot of constraints, and polymorphism), which should work fast and should support many modules and libraries, would passing pre-computed solutions as assumptions be the way you choose? Do you see any alternatives or immediate cases where this will lead to serious performance problems?
