### ISSUE TITLE
Bug in Array equality

### ISSUE THREAD

**Issue by acw1251** [Z3Prover/z3#4515]
I seem to be running into a bug related to equality of arrays. I was able to reduce the issue I was having down to the following:

```python
import z3
s = z3.Solver()
s.add( z3.Store(z3.K(z3.BoolSort(), True), False, False) == z3.K(z3.BoolSort(), False) )
print(s.check())
```

I'm expecting the array on the left to be `[True -> True, False -> False]` so it shouldn't be equal to `K(Bool, False)`, but the check statement is returning `sat`.

**Comment by NikolajBjorner** [comment]
the commits should be addressing the issue.

**Comment by acw1251** [comment]
Thanks! I tried out the small example I posted above and the much larger example in which I first saw the bug, and it is now working correctly in both cases.
