### ISSUE TITLE
Documentation request: inc_ref and memory consumption

### ISSUE THREAD

**Issue by cheshire** [Z3Prover/z3#452]
Hi,

I experience Z3 memory consumption profile which is somewhat counter-intuitive.
In my application, using C Z3 bindings, I have the following code:

```java
    while (true) {
      bfmgr.or(
          bfmgr.makeVariable("a"),
          bfmgr.and(
              bfmgr.makeVariable("b"),
              bfmgr.makeVariable("c")
          )
      );
    }
```

In an endless loop a Z3 AST object is created and never deallocated. Each call to `bfmgr` creates a new AST, which calls `inc_ref` in a constructor and _never_ deallocates the object.
Thus there are at least five new ASTs created in each loop iteration, and each time each AST reference counter is increased.

It would be reasonable to expect a growing memory consumption, as we allocate 5 objects in each loop iteration and never de-allocate it. Instead, for at least 5 minutes, the memory usage is completely flat, modulo the Java wrapping objects, which are then collected by GC, bringing the usage back to zero:

![constant_memory](https://cloud.githubusercontent.com/assets/348959/13051372/321147b6-d3f9-11e5-94fd-ba4280f709ea.png)

It seems like there is a caching algorithm in place, which does a `get-or-create` lookup instead of outright creating an AST.
Indeed, modifying the code to create a different AST each time introduces a long-awaited memory leak:

```java
    int i = 0;
    while (true) {
      ifmgr.equal(
          ifmgr.makeVariable("x"),
          ifmgr.makeNumber(i++)
      );
    }
```

I had a (rather brief) look at `ast.cpp`, but I haven't found the get-or-create behavior.

Would it be possible to add a few notes about it to the documentation? It seems that calling `dec_ref` is not necessary if the same formula is re-created repeatedly through the application (which is often the case in formal verification tools).

**Comment by wintersteiger** [comment]
Yes, Z3 uses hash consing. If you create the same object twice, you will receive the same pointer twice. Where would you have expected this to be mentioned?

**Comment by cheshire** [comment]
@wintersteiger In a docstring for `Z3_mk_context_rc`. It mentions `inc_ref` and `dec_ref` usage, mentioning hash consing would be very helpful.
