### ISSUE TITLE
(UF, FOL) Getting a name of object or...?

### ISSUE THREAD

**Issue by ClemFandango2** [Z3Prover/z3#4520]
(I know it's a bit impolite to post URLs to another websites, but it's too long...)

This is MWE - code like these are abound in Prolog textbooks.
You describe persons and relationships between them, and then you ask Prolog to find a husband of X or a wife...
https://pastebin.com/vwRUHbT2
So far so good, but I want to get a name of a person.
But I'm getting:

    [tst1 = Object!val!2,
      Jacqueline_Kennedy_Onassis = Object!val!1,
     John_Fitzgerald_Kennedy = Object!val!0,
     tst2 = Object!val!3,
    ...

How to fix it?

**Comment by NikolajBjorner** [comment]
It solves the formulas, but the closed world assumption from Prolog isn't retained in first-order semantics. The first order semantics is that every interpretation that satisfies your formulas is legal. This includes an interpretation that sets x and y to values different from JFK and JKO.
It finds a finite model with 4 elements. 
You could use algebraic datatypes (enumeration sorts) for the domain. Then the domain would be bounded by your enumeration sort. You can also bound the domain using a quantifier: Forall(x, Or(x == JFK, x == JKO)).

**Comment by ClemFandango2** [comment]
Thanks for your reply!
