### ISSUE TITLE
Problem with qprofdiff when a "qid" contains colon

### ISSUE THREAD

**Issue by rospoly** [Z3Prover/z3#4521]
It looks like there is a bug in the tool contrib/**qprofdiff** in master. The bug manifests when the **qid** of a quantifier contains the char '**:**' (colon). 

I upload two small profile logs (tmp.log and tmp2.log) to generate the problem. Just run `qprofdiff tmp.log tmp2.log` to generate the issue.
[tmp2.log](https://github.com/Z3Prover/z3/files/4783300/tmp2.log)
[tmp.log](https://github.com/Z3Prover/z3/files/4783303/tmp.log)

Just to give a bit of context, the colon character is present in all the **qid**s when the verification condition comes from the boogie program verifier.

I am running Ubuntu 16.04 LTS and Z3 version 4.8.9 - 64 bit.

**Comment by wintersteiger** [comment]
Thanks for the report and sorry this has taken so long! It's fixed now.
