### ISSUE TITLE
Incremental solving mechanism

### ISSUE THREAD

**Issue by uncttao** [Z3Prover/z3#4523]
Hi all, I just have a simple question regarding the internals of incremental solving/solving over assumptions.

Say my initial formula is X and my assumptions are Delta_1, Delta_2,... Is solving X and then incremental solving over Delta_1, Delta_2,... usually faster than solving (X + Delta_1), (X +Delta_2), ... each in one go? If so, what is the algorithm/mechanism that enables this speedup? Could I get a reference/paper that elaborates this procedure? Thanks!

**Comment by nevilad** [comment]
According to this paper https://www.cin.ufpe.br/~damorim/publications/liu-etal-hvc2014.pdf, incremental solving is faster.
There is also this post https://stackoverflow.com/questions/16422018/how-incremental-solving-works-in-z3, which says that on different tasks different incremental strategies behave different.

**Comment by NikolajBjorner** [comment]
As a rule of thumb: small and relatively easy problems that are solved quickly are best for incremental solving. Harder problems where solving time dominates setup time are much more likely to be solved better using non-incremental solving.
