### ISSUE TITLE
Potential Regression with QE-LIGHT

### ISSUE THREAD

**Issue by kfriedberger** [Z3Prover/z3#4530]
We experienced a regression in our application, which is build on top of Z3, and we traced it back to the commit c9c9efe.
The result of the following query differs before and after this commit:
<pre>
(set-option :produce-proofs true)
(declare-const x Int)
(declare-const y Int)
(assert (exists ((y Int)) (! (and (= y 4) (= x (+ y 3))) :weight 0)))
(apply qe-light)
</pre>
Before this commit, the quantifier elimination simplifies the formula towards `(= x 7)`.
After this commit, the simplification depends on a disabled proof production, and does nothing if proofs are enabled.
Is this intended behaviour or a regression?

**Comment by NikolajBjorner** [comment]
I reverted that change. It exposes some other bugs that were reported by fuzzing. These other bugs are open now.

**Comment by kfriedberger** [comment]
It works with latest revision. Thanks.
