### ISSUE TITLE
Wrong version number when an old version is present

### ISSUE THREAD

**Issue by itmm** [Z3Prover/z3#4531]
if Z3 is build while an old version of Z3 is already installed, Z3_get_version returns the version of the already installed version, not of the version that is build. Perhaps the header of already installed version is included instead of the current one?

**Comment by NikolajBjorner** [comment]
I think you want to remove old installations of Z3 before proceeding. A typical error situation is that there is a stale libz3.so or z3lib.dll laying around on your PATH and it gets used instead of the new version.

**Comment by itmm** [comment]
Hi Nicolaj,

thank you for your reply. I am very confident that I used the right library (specified with -L compiler switch). But the function returns a different version than the macros. So while compiling the Z3_get_version function a different header is used. So the compiled version in the right library returns the wrong version. I call this an error (not in the code, but in the build mechanism).

I agree, that the problem won‘t occur, if I deinstall the old version. But I want to build the head version of the llvm. Only for this I need a new version. The rest of my system should work with the packaged version.

I believe that somewhere in the build mechanism the local path must be set before the default one. But I do not understand the build mechanism. It is too complicated for myself. So sadly I cannot provide a patch.

**Comment by NikolajBjorner** [comment]
It is related to your include path and pertains to your environment. 
Note also that the cmake build system puts the version header file in a directory that is controlled by the build system. In this way, stale compiler-generated files in your source tree will not be touched.
The python build system generates files and puts them in the source tree, which could lead to issues, though I wonder if this has anything to do with what you are observing.
