### ISSUE TITLE
Question about several SMT-LIB attributes Z3 accepts

### ISSUE THREAD

**Issue by mschwerhoff** [Z3Prover/z3#4536]
I found several SMT-LIB attributes in [src/parsers/smt2/smt2parser.cpp](https://github.com/Z3Prover/z3/blob/master/src/parsers/smt2/smt2parser.cpp), some of which I believe to know what they are intended for:

* `:named`: named terms can be included in unsat cores
* `:weight`: heaver quantifiers make Z3 reach its quantifier instantiation depth threshold more quickly
* `:qid`: identify quantifiers, e.g. when obtaining instantiation statistics
* `:pattern`: syntactic hints for when to instantiate a quantifier in e-matching
* `:no-pattern`: prevent Z3 from using certain terms when inferring patterns

But I have no idea about (and couldn't find any documentation for) the following attributes: `:skolemid`, `:ex-act`, `:lblneg`, `:lblpos`.

Could you please briefly explain what these are intended for?

**Comment by NikolajBjorner** [comment]
:ex-act seems like dead code, to be removed
:skolemid - specific to VCC/Boogie use. 
:lblneg, :lblpos associated with Boogie labels to track source of counter-example.

**Comment by mschwerhoff** [comment]
I've turned this into a Stackoverflow question: https://stackoverflow.com/questions/62512506

**Comment by keyboardDrummer** [comment]
@NikolajBjorner Could you elaborate on what `:skolemid` does?

**Comment by NikolajBjorner** [comment]
It is used during normal form conversion where quantifiers are Skolemized. Fresh Skolem functions are given a name that contains the Skolem identifiers (as a suffix) so it is easy to identify what quantifier originated the fresh function. It was introduced for the axiom profiler many years ago.
