### ISSUE TITLE
Suggesting new "comment" SMT-LIB attribute

### ISSUE THREAD

**Issue by mschwerhoff** [Z3Prover/z3#4537]
Our tool ([Viper](https://viper.ethz.ch)) generates SMT-LIB code from user-provided files, including quantifiers. Sometimes patterns are missing, and to ~make these cases grepable~ identify these cases post mortem, I would like to emit a marker attribute. For example:

```
(forall ((i Int)) (!
  (implies  (and (foo i) (bar i)))
  :comment "pattern missing"))
```

However, such a general-purpose attribute does not seem to be supported, and I would thus like to suggest adding one to Z3.

Currently possible workarounds:

* Just use any non-supported attribute (e.g. `:comment`) and either disable warnings, or ignore them. Since e.g. invalid patterns are also reported as warnings, this workaround might be potentially dangerous,

* `:pattern "pattern missing"` does not raise warnings. Misusing `:pattern` this way feels rather hacky, though.

* Use a regular SMT-LIB comment `; pattern missing`. A potential disadvantage is that comments are typically lost when parsing the generated SMT code, which could be a post mortem step.

**Edits:**
* 2020-06-20 20:59 to account for @andrewvaughanj suggestion

**Comment by andrewvaughanj** [comment]
Why not a regular SMTLIB2 comment (`;`) on the line before, the line after or the end of line?

**Comment by mschwerhoff** [comment]
@andrewvaughanj Ah yes, that nicely matched my specs :-) I strengthened them and added your suggestion as a workaround.

**Comment by andrewvaughanj** [comment]
As far as I’m aware, Z3’s SMT front-end has no way to dump back the parsed instance (the API does via parse/dump though).

Will you just be using these instances with Z3?

**Comment by mschwerhoff** [comment]
Practically: yes. For years, we wanted to give other SMT solvers a try, but never actually did.

**Comment by andrewvaughanj** [comment]
So:

- If you're going to *exclusively* use Z3, and you want the ability to load (e.g., using `from_file`) and then dump it out (e.g., using `sexpr`), then I guess Z3 adding an extension that allows you to provide comments against expressions would work for you

- If you're ever interested in re-using your SMTLIB2 files with different solvers/parsers, then you should either ask to get this added to the SMTLIB2 syntax (see, [SMT-LIB - Google Groups](https://groups.google.com/forum/#!forum/smt-lib)) or use the comment idea (to ensure that your files are compatible with the standard SMTLIB2 syntax)

Imagine you want to add these comments using the Z3 API, dump the `.smt2` and then load it with something like [PySMT](https://github.com/pysmt/pysmt) -- to make this work, you'll need to add this new syntax to PySMT too. I'm just really struggling to see the approach where you need these comments being preserved _after_ you parse them with another solver (I agree they're useful when doing a `grep` against the `.smt2` that `viper` generates, but then the comments would work for you there).

**Comment by NikolajBjorner** [comment]
Going back to the requirements, the way i understand it, it is possible to express the query of interest using a regular expression with exclusion patterns already.
In this case I would not add a feature that then adds liability to lower the barrier of using regular expressions.

**Comment by mschwerhoff** [comment]
(I've realised that it might not have been strategic to focus on a specific attribute.)

@andrewvaughanj:
* The SMT-LIB standard defines syntax for arbitrary attributes, so `:comment` would be covered. Appealing to the SMT-LIB standards committee would only be necessary if `:comment` were to be a mandatory attribute, i.e. one that tools *must* support in order to be SMT-LIB compliant, but that's not what I'm aiming for.
* Correspondingly, PySMT's parser accepts any attribute, including `:comment`, and allows, e.g. to query the resulting AST for such comments, [as demonstrated by this snippet](https://gist.github.com/mschwerhoff/d802b2073e75d4a5f23cebbfafb7d0d2). I conjecture that other SMT tools — maybe not solvers, but for parsing, transforming, analysing, etc. — decided to treat attributes similarly general.
* Viper currently interacts with Z3 via stdio, i.e. passing SMT-LIB strings to Z3. The interaction is also recorded to disc, for post mortem operations, e.g. analyses. It is therefore not necessary that Z3 does anything special with non-standard attributes, but not raising a warning would be great.

@NikolajBjorner While greping for a comment (e.g. `; pattern missing`) or regex-searching for quantifiers with missing `:pattern` might be possible, such hacks (compared to proper parser support) are typically hard to get right and fragile.

**Final arguments**; if you're not convinced, I'll rest my case:
1. if Z3 were to parse arbitrary attributes (in line with the SMT-LIB standard), and *optionally* raise a warning for those it doesn't recognise, 
2. then this would allow SMT code generators to freely annotated their code, e.g. for a later analysis via PySMT.

I'm not really familiar with Z3's sources, but I would hope that a corresponding implementation would not require substantial changes.

**Comment by NikolajBjorner** [comment]
I don't understand the design rationales here. 
If adding attributes to quantifiers, then those are carried along. 
There are already a few such attributes, :qid, :skid that are used for tracking.
There are also :pattern, :nopattern, :weight.
Each such attribute is passed along when expressions are created and simplified internally.
Adding other attributes at will begs the question of how they might be handled during processing.
Instead of adding more attributes internally, if they are used for text file annotation, then use text file comments.
SMTLIB is a sequence of commands, adding a comment along those commands is a reasonable part for a tool that provides a way to print assertions and other SMTLIB commands.
Not seeing why this feature should be further supported I would am going to close this.
