### ISSUE TITLE
Difference between version 4.8.7 and 4.8.8

### ISSUE THREAD

**Issue by jad-hamza** [Z3Prover/z3#4539]
```smt
(declare-datatypes () ((AA (A (A1 Int) (A2 (_ BitVec 32)) (A3 (_ BitVec 32))))))
(declare-datatypes () ((BB (B (B1 Int) (B2 (_ BitVec 32))))))

(declare-fun unused () Bool)
(declare-fun b1 () Bool)
(declare-fun b2 () Bool)
(declare-fun bv1 () (_ BitVec 32))
(declare-fun bv2 () (_ BitVec 32))
(declare-fun a2 () AA)
(declare-fun a1 () AA)
(declare-fun f ((_ BitVec 32)) AA)

(assert (=> b1 b2))
(assert b1)
(assert (= b2 (and (bvsgt bv1 #b00000000000000000000000000000000) (bvsge bv2 #b00000000000000000000000000000000) (= bv1 bv2) (bvsle bv2 bv1))))

(assert (= a2 (f (bvadd bv2 #b00000000000000000000000000000001))))
(assert (= bv2 (A2 a2)))
(assert (not (= (A3 a2) bv2)))

(check-sat unused)

(assert (= (f (bvadd bv2 #b00000000000000000000000000000001)) (A (A1 a1) bv2 bv2)))

(check-sat)
```

On this file Z3 4.8.7 returns `sat` and `unsat`, while 4.8.8 returns `sat` and then times out (stopped after a minute). If I comment out `(check-sat unused)`, then both versions return `sat` and `unsat`.
The `unsat` result for the second `check-sat` seems correct, because `(assert (not (= (A3 a2) bv2)))` is equivalent to `(assert (not (= bv2 bv2)))`.

**Comment by NikolajBjorner** [comment]
I can reproduce it: somehow congruence reasoning (adding useful Ackerman axioms) isn't kicking in to help.

**Comment by jad-hamza** [comment]
Thanks for looking into it!
On current master (40159a3a96b3a50622e00424a345538466dcdf2f), this now returns `sat` and `sat`.

**Comment by jad-hamza** [comment]
It's back to timeout for the second assertion on commit 6c9bdc949e90bdfb4605aa7f88a637d121ac710b.

**Comment by NikolajBjorner** [comment]
This is to be addressed by the new core sat.euf=true, but no optimizations for Ackerman lemmas will be done to the old core.
