### ISSUE TITLE
Build z3 as a Static runtime library 

### ISSUE THREAD

**Issue by illera88** [Z3Prover/z3#454]
Can z3 be build as a static Runtime library?

I have tried to change /MD to /MT in the config.mk but it seems it does't work.

Cheers

**Comment by wintersteiger** [comment]
Yes, it can. The mk_make.py script has the --staticlib option for this purpose. There have been some issues with that for a while, but for me it usually works to configure with that option, then build everything, then delete libz3.dll/.lib and then to run nmake again. I've added a new issue #456 for this so we don't forget to fix this.

**Comment by illera88** [comment]
I've tried what you said but it doesn't create the lib :(

`python scripts\mk_make.py -x -v --optimize --staticlib`

That's the command I used

**Comment by wintersteiger** [comment]
Yes, build it and you will get libz3.dll and libz3.lib. Delete libz3.lib and recompile, which should create a static libz3.lib (much bigger than the first one).

**Comment by illera88** [comment]
Yes! It works that way! Thanks

**Comment by illera88** [comment]
Is it normal that the library with the --optimize flag is 1GB? 

What are those optimizations. Are they useful for performance?

Thanks

**Comment by nunoplopes** [comment]
--optimize enables link-time optimizations (https://msdn.microsoft.com/en-us/library/0zza0de8.aspx)
Whether it helps or no, depends a lot on the type of benchmarks.

It shouldn't bloat much the binary, no.  The bloat might be because of --staticlib?

**Comment by wintersteiger** [comment]
This has since been fixed, on Windows the build now produces libz3-static.lib instead of clashing on libz3.lib. Under some conditions the library files are indeed huge, but I haven't figured out why, where, and when yet.
