### ISSUE TITLE
In Z3 solver , is there a way to represent numbers in fixed point notation with arithmetic operations support

### ISSUE THREAD

**Issue by bja2019** [Z3Prover/z3#4540]
I have asked following question @ https://stackoverflow.com/questions/62558757/in-z3-solver-is-there-a-way-to-represent-numbers-in-fixed-point-notation-with 
It is suggested to post here and repeating question here.

In Z3 solver, I want to represent numbers using fixed point notation and perform arithmetic operations with rounding.
Example: Let's say, X, Y and Z represent fixed point numbers type,
         X[4,3]  Total 4 digits number with 3 digits after the decimal.
         Y[4,2]   
         Z[4,1]
         Assign fixed point numbers to X, Y
         X = 1.234  ( here there are total 4 digits & decimal digits are 3 )
         Y = 45.67
         Perform the Fixed point numbers Arithmetic operation
         Z = X * Y (The result 56.35678 needs to be rounded and assign to Z i.e., 56.36)

I understand that, the Z3 supports floating point theory for numbers but not for fixed point theory for numbers with arithmetic operations ! Is there any plan to support fixed point theory for numbers? if not, is there any way to achieve this using any existing theory in Z3 solver with an example ?

Thank you for your help in advance!

**Comment by andrewvaughanj** [comment]
Interesting you asked this, at IJCAR in a few weeks there is a presentation of this work:

- [An SMT Theory of Fixed-Point Arithmetic](https://soarlab.org/publications/2020_ijcar_bhlnr/)

which provides an API via PySMT for dealing with fixed point numbers:

- [SOAR Lab - PySMT - Fixed Points](https://github.com/soarlab/pysmt/tree/fixed-points)

This API proves the ability to fixed-point SMT instances which can then be discharged to an SMT solver (e.g., Z3); [for example](https://github.com/soarlab/pysmt/blob/fixed-points/test_fxp.py):

```
x = Symbol("x", UFXPType(10,5))

y = Symbol("y", UFXPType(10,5))
z = Symbol("z", UFXPType(10,5))

o = Symbol('o', FXP_OM)

r = Symbol('r', FXP_RM)

#z = Equals(x, y)

#z = x == y

#z = UFXPLt(x, y)

zz = UFXPAdd(o, x, y)
zzz = UFXPSub(WP, x, zz)
zzzz = UFXPMul(o, r, x, y)
zzzzz = UFXPDiv(o, r, x, y)

kk = UFXPMul(o, r, x, y)

k = BV(1, 2)
conv =  get_fp_bv_converter()
model = get_model(conv.convert(Equals(zz, kk)))
```

**Comment by bja2019** [comment]
This is really good information and will try PySMT for my few use cases. Thanks for providing the details.
