### ISSUE TITLE
Possible incompleteness in finite almost uninterpreted formula

### ISSUE THREAD

**Issue by wilcoxjay** [Z3Prover/z3#4543]
I have the following query 

```
(set-option :smt.mbqi true)

(declare-sort A 0)
(declare-sort B 0)
(declare-fun f (A Int) B)
(declare-const a A)
(declare-const b B)
(assert (not (= (f a 1) b)))
(assert (forall
         ((x A) (y B))
         (= (f x 0) y)))
(check-sat)  ; unknown
(get-info :reason-unknown)  ; incomplete quantifiers

;; below are two manual ways to get unsat to go through

(push)
  ; manually instantiate the above axiom on x = a, y = b
  (assert (= (f a 0) b))

  (check-sat)  ; unsat
(pop)

(push)
  ; manually add the consequence of the above axiom that there is only one B
  (assert (exists ((the_B B)) (forall ((y B)) (= the_B y))))
  (check-sat)  ; unsat
(pop)
```

I am not 100% sure that I understand the definition of FAU, but I think this formula is FAU? In any case, the formula is unsat, but Z3 gives up quickly and returns unknown without further assistance.

If it turns out that MBQI is not intended to be a decision procedure for any fragment containing this formula, please feel free to close this issue.

Thanks!

/cc: @thomasbernardi

**Comment by NikolajBjorner** [comment]
The bound variable 'y' (of sort B, which is not an integer) is _unprotected_. 
It is used as right side of an equality and not in scope of a function. 
Of course would be useful to catch things like this using paramodulation 
on un-restricted variables.

**Comment by wilcoxjay** [comment]
Ah, ok, thanks! Maybe we can discuss the paramodulation approach to this next time we meet :)

This query actually came from a buggy prototype version of our tool, so it's not a high priority for us.
