### ISSUE TITLE
Optimize and (set-logic ...)

### ISSUE THREAD

**Issue by gledr** [Z3Prover/z3#4544]
Running: Z3 version 4.8.8 - 64 bit

I have a question regarding the (set-logic ...) command as used with the SMT2 input format and Z3's Optimizer.
My question is based on some experiments where I  guess that the (set-logic ...) is somehow processed by the optimizer.

When using the z3::solver I can set the logic directly in the CTOR. When running z3::optimize I could not find any possibility using the C++ API to do this. I've Googled my question for quite some time with no result. 

I am trying to place boxes inside an area where I have clauses in order to place the boxed and where I try to minimize the needed area. I have exported the clauses as SMT2 (see attached) and played a bit around with the possible logics. I figured out that the runtime dropped from around 60s to 5s on my machine by setting (set-logic UFNIA). 

Therefore I wanted to add this to the C++ API based code as well and couldn't find any possibilities for z3::optimize.
I found one discussion online where people were talking about that z3::optimize is using a complex mix of different SMT Logics and therefore its "complicated". 

Since there was this pretty interesting "speed up" when using Z3s binary and the exported SMT2 code as attached by explicitly adding the (set-logic UFNIA) it would be very interesting what configurations are getting set by the command-line version of Z3.

Thank you very much for your help.

[boxes.log](https://github.com/Z3Prover/z3/files/4838631/boxes.log)

**Comment by NikolajBjorner** [comment]
The logic option in solvers is used in two respects:
- to set up a number of pre-processing and tactic options that attempt solving the formula in specialized ways.
- to prepare the general purpose end-game solver with parameters that have been measured to work best.
The pre-processing and specialized tactics are not available when solving for optimization objectives. 
The end-game solver, which is also used by the optimization engine, can be configured selectively using parameters in the "smt" namespace. You can list the parameters by running 

```
      z3   -pm:smt
```

For the release 4.8.8 we may have enabled the new arithmetic solver for non-linear arithmetic for the UFNIA logic.
The ways to force the new solver is by setting:
```
 smt.auto_config=false
 smt.arith.solver=6
```

There is a caveat for precisely the scenario you are exploring: You have set the "symba" engine. This one uses an arithmetic solver that works with non-standard numerals. It uses numerals of the form a*epsilon + b + c*infinity, where typically a = c = 0, but if c = 1 then the number is greater than any a*epsilon + b + c*0.
This is only supported in the legacy arithmetic solver. You would have to not set the symba option to exercise the new arithmetic solver.

**Comment by gledr** [comment]
Thank you very much for your answer :)
