### ISSUE TITLE
Expressions not simplifying

### ISSUE THREAD

**Issue by Shaheenthebean** [Z3Prover/z3#4546]
I've been experimenting with the Python wrapper, and came across this expression: 
```
Or(x <= 0,
  
And(Not(x <= 0), Not(y == 0)),
   
And(Not(x <= 0), y == 0))
```
which, upon inspection, should just be True, but running simplify on it doesn't change anything. Is there any setting I should be using to force it to simplify?

**Comment by NikolajBjorner** [comment]
The default simplifier does not consider context. 
There are tactics that perform various transformations that can also be used to simplify formulas.
In your case there is

```
from z3 import *
x, y = Ints('x y')
fml = Or(x <= 0, And(Not(x <= 0), Not(y == 0)), And(Not(x <= 0), y == 0))
print(simplify(fml))
tac = Tactic("ctx-solver-simplify")
r = simplify(Or([g.as_expr() for g in tac(fml)]))
print(r)

```
