### ISSUE TITLE
Parameterized type declarations cannot be instantiated without a constant of that type

### ISSUE THREAD

**Issue by evelynhaslinger** [Z3Prover/z3#4548]
When passing the following formula to z3 version 4.8.8 - 64 bit:
```
(declare-datatypes (TypeValue)
	(
		(@MyType
			(@MyTypeNil)
			(
				@MyTypeNoneNil
				(length TypeValue)
			)
		)
	)
)

;(declare-const map_7 (@MyType (_ BitVec 8)))
(assert (=
         (length (@MyTypeNoneNil #x01)) #x01
        )
)
(check-sat)
(get-model)
```
The following error is reported:
`error "line 15 column 37: unknown function/constant @MyTypeNoneNil")`

This error does not occur in case a constant of @MyType is delcared, i.e. the following formula does not lead to the aforementioned error:
```
(declare-datatypes (TypeValue)
	(
		(@MyType
			(@MyTypeNil)
			(
				@MyTypeNoneNil
				(length TypeValue)
			)
		)
	)
)

(declare-const map_7 (@MyType (_ BitVec 8)))
(assert (=
         (length (@MyTypeNoneNil #x01)) #x01
        )
)
(check-sat)
(get-model)
```

**Comment by NikolajBjorner** [comment]
SMTLIB2 has syntax for type annotating constants. It uses the (_ as ...) construct. 
Some parametric type instantiations get resolved by the parser, but not all. 
Use the (_ as ..) construct to ensure types are resolved (with the caveat that (_ as ...) 
is not very user friendly or intuitive.

**Comment by NikolajBjorner** [comment]
So in this case you can parse:

```
(declare-datatypes (TypeValue)
	(
		(@MyType
			(@MyTypeNil)
			(
				@MyTypeNoneNil
				(length TypeValue)
			)
		)
	)
)

;(declare-const map_7 (@MyType (_ BitVec 8)))
(assert (=
         (length ((as @MyTypeNoneNil (@MyType (_ BitVec 8))) #x01)) #x01
        )
)
(check-sat)
(get-model)
```

**Comment by evelynhaslinger** [comment]
Thanks for the quick answer and for clearing things up. 
Works like a charm :-)
