### ISSUE TITLE
Overflow encountered when expanding vector

### ISSUE THREAD

**Issue by nikswamy** [Z3Prover/z3#455]
I'm using Z3 version 4.4.1 on windows 10.

It reports:

```
(error "line 35378 column 10: Overflow encountered when expanding vector")
```

I've never seen that before. Is it an expected output? What does it mean?

**Comment by NikolajBjorner** [comment]
you are likely running out of memory.

**Comment by nikswamy** [comment]
Fyi, this was happening because I had an exponential matching loop. And z3 4.4.1 was not respecting my 5s timeout. I guess the timeout issue is supposed to be fixed in the master branch
