### ISSUE TITLE
Z3 DRAT parameter assumed and rejected

### ISSUE THREAD

**Issue by a1880** [Z3Prover/z3#4552]
Z3 4.8.8 64 bit, Windows (pre-compiled binary from GitHub) has a problem when used as SAT solver.

Input file mini.cnf.txt

```
p cnf 3 4
1 -3 0
2 -3 0
-1 -2 3 0
3 0
```

Command:

`z3 -dimacs mini.cnf.txt`

Output:

`ERROR: DRAT checking only works for pure CNF`

With parameter `sat.threads=2` I am getting the expected output:

```
sat
1 2 3
```
Somehow, Z3 assumes that a DRAT check is requested.
This check is only performed for single-threaded mode.

**Comment by NikolajBjorner** [comment]
workaround for now:

z3 mini.cnf sat.cardinality.solver=false
