### ISSUE TITLE
timeout is not working properly in z3py

### ISSUE THREAD

**Issue by sg61189** [Z3Prover/z3#4555]
Hello, 

I have used the following code fragment to set the timeout. But, on running the code I am getting the expected timeout results. The code is not stopping as per the time set in the command. Please suggest how to tackle it. 

from z3 import *

s=Solver()
set_option(timeout=180000)  

x_0_0 = Bool('x_0_0')
x_1_0 = Bool('x_1_0')
...

**Comment by NikolajBjorner** [comment]
Without any details it is impossible to figure out what is going on.
You can use mixed-mode debugging of python scripts from Visual Studio and possibly other environments
It may tell you what code fragment is being exercised that doesn't check cancellation.

One source of cancellation agnostic code is during an external context push that causes propagation. 
If this is super expensive it could stall cancellation. It is generally not safe to stall the propagation originating from an external push.
