### ISSUE TITLE
Another MBQI incompleteness question

### ISSUE THREAD

**Issue by wilcoxjay** [Z3Prover/z3#4557]
Sorry for the similar issue to #4543, but this time I think the formula is really EPR. (Unless there is something special about equality in EPR that I don't know about.)

Here is the query: 

```
(set-option :smt.mbqi true)
(declare-sort A 0)
(declare-sort B 0)
(declare-fun f (A) B)
(declare-const a0 A)
(declare-const a1 A)
(declare-const a2 A)
(declare-const b B)
(assert (= (f a1) (f a2)))  ; comment this line out to see unsat
(assert (not (= (f a0) b)))
(assert (forall ((x_0 A) (y_0 B)) (= (f x_0) y_0)))
(check-sat)
(get-info :reason-unknown)
```

z3 reports unknown in about 1 second. The formula is unsat. In fact, just commenting out the marked line causes z3 to realize it's unsat immediately.

I know `y_0` is unprotected, but does that matter in an EPR formula? It still seems like this should be in the decidable fragment to me.

Thanks!

/cc:@thomasbernardi

**Comment by andrewvaughanj** [comment]
Doesn't EPR disallow functions of arity greater than zero (i.e., it doesn't really allow functions at all)?

- https://en.wikipedia.org/wiki/Bernays–Schönfinkel_class

- http://fmv.jku.at/bv2epr/bv2epr.cade2013.pdf

I would guess your use of `f` (which has arity 1) infringes on this.

That being said, I don't know the cause of this issue, but I really don't think that instance is EPR (if it matters).

**Comment by wilcoxjay** [comment]
Right, I was speaking informally. I really meant "EPR with the usual extension to stratified function vocabularies".

See for example https://www.cs.tau.ac.il/~rabinoa/pub/lpar07a.pdf.

**Comment by NikolajBjorner** [comment]
I believe this takes care of the issue you produced.

**Comment by wilcoxjay** [comment]
yep, this works for me, thanks!
