### ISSUE TITLE
How to sum an expression vector?

### ISSUE THREAD

**Issue by Harut2k** [Z3Prover/z3#4566]
Hello, so I have a vector of expressions which are just variables. I want to add a rule that the sum of these variables must be equal to some k.

For example, if I have an expression vector v =  {x, y, z}, is it possible to do something similar to sum(v) == k? Or is my only option to write in manually that x + y + z = k?

I looked into the z3 header file and the only functions that seemed similar to what I needed were Pble, and the sum function, but I couldn't get either of them to work. Any help would be appreciated. 

Thank you!

**Comment by NikolajBjorner** [comment]
Is this the python or C++ API? 
Python has "Sum", C++ API has "sum" that are convenient ways to take the sum of vectors of arguments.

```
xs = Ints('x%d' % i for i in range(10))
k = 3
s = Solver()
s.add(Sum(xs) == k)
```

and in C++ something to the tune of:

```
expr_vector xs(ctx);
for (int i = 0; i < 10; ++i) xs.push_back(ctx.int_const({'x', '0'+i, 0 }));
int k = 3
s = solver(ctx)
s.add(sum(xs) == k)
```

**Comment by Harut2k** [comment]
> Is this the python or C++ API?
> Python has "Sum", C++ API has "sum" that are convenient ways to take the sum of vectors of arguments.
> 
> ```
> xs = Ints('x%d' % i for i in range(10))
> k = 3
> s = Solver()
> s.add(Sum(xs) == k)
> ```
> 
> and in C++ something to the tune of:
> 
> ```
> expr_vector xs(ctx);
> for (int i = 0; i < 10; ++i) xs.push_back(ctx.int_const({'x', '0'+i, 0 }));
> int k = 3
> s = solver(ctx)
> s.add(sum(xs) == k)
> ```

Thank you so much! It was in C++. My issue was that I was using a literal vector of expr, instead of the built-in expr_vector.


Thank you again

**Comment by NikolajBjorner** [comment]
OK, so suppose you have a vector of Boolean variables, you can use pbge, atmost etc

Their declarations are:

```
        friend expr pble(expr_vector const& es, int const * coeffs, int bound);
        friend expr pbge(expr_vector const& es, int const * coeffs, int bound);
        friend expr pbeq(expr_vector const& es, int const * coeffs, int bound);
        friend expr atmost(expr_vector const& es, unsigned bound);
        friend expr atleast(expr_vector const& es, unsigned bound);
```

atmost and atleast are special cases of pble and pbge, respectively.
You have to pass coefficients in a separate array. When all coefficients are +1, then use atmost/atleast.
