### ISSUE TITLE
Equivalence check

### ISSUE THREAD

**Issue by Flians** [Z3Prover/z3#4567]
For some boolean variables:
```
Z3_ast A;
Z3_ast B;
Z3_ast C;
```
I wanna check whether they are all true.
I tried the following two ways, but their results were different.
```
Z3_ast D = Z3_mk_and(A, B, C);
Z3_solver_assert(ctx, solver, Z3_mk_not(ctx, D));
Z3_solver_check(ctx, solver);
```
```
Z3_solver_assert(ctx, solver, Z3_mk_not(ctx, A));
Z3_solver_assert(ctx, solver, Z3_mk_not(ctx, B));
Z3_solver_assert(ctx, solver, Z3_mk_not(ctx, C));
Z3_solver_check(ctx, solver);
```
Could you please tell me how to solve this problem?
Thank you.

**Comment by nunoplopes** [comment]
The first approach you tried corresponds to `not (A /\ B /\ C)`. The second to `not a /\ not B /\ not C`.  They have very different meanings.
If you want to check if all the 3 variables are always true (i.e., that neither of them can ever be false), then use the first approach and check that you get UNSAT.
