### ISSUE TITLE
Cbmc compatibility

### ISSUE THREAD

**Issue by arey0pushpa** [Z3Prover/z3#457]
I'm using a basic cbmc program

int main() 
{ 
int a[10]; 
__CPROVER_assert(__CPROVER_forall 
{unsigned int i; 
(i >= 0 && i < 10) ==> a[i] < 0}, 
"Assert_Forall"); 
__CPROVER_assert(__CPROVER_forall 
{unsigned int i; 
__CPROVER_exists 
{unsigned int j; 
(i>=0 && i<10 && j>=0 && j<10) ==> a[i] > a[j]}}, 
"Assert_Forall_Exists"); 
return 0; 
}

$ cbmc --z3 quant5.c

CBMC version 5.3 64-bit x86_64 linux
Parsing quant5.c
Converting
Type-checking quant5
Generating GOTO Program
Adding CPROVER library
Function Pointer Removal
Partial Inlining
Generic Property Instrumentation
Starting Bounded Model Checking
size of program expression: 34 steps
simple slicing removed 5 assignments
Generated 2 VCC(s), 2 remaining after simplification
Passing problem to SMT2 QF_AUFBV using Z3
converting SSA
Running SMT2 QF_AUFBV using Z3
SMT2 solver returned error message:
"line 65 column 16: invalid get-value term, term must be ground and must not contain quantifiers"
Runtime decision procedure: 0.025s
decision procedure failed

Is that due to inner exists ??

__CPROVER_exists 
{unsigned int j; 
(i>=0 && i<10 && j>=0 && j<10) ==> a[i] > a[j]}

Code in Z3  was 

check_lparen_next("invalid get-value command, '(' expected");
            while (!curr_is_rparen()) {
                parse_expr();
                if (!is_ground(expr_stack().back()))
                    throw cmd_exception("invalid get-value term, term must be ground and must not contain quantifiers");
                m_cached_strings.push_back(m_scanner.cached_str(cache_it, m_cache_end));
                cache_it = m_cache_end;
            }

**Comment by NikolajBjorner** [comment]
It seems that your tool, CBMC, creates a text-pipe that sends SMT-LIB2 instructions to Z3. 
You can pose queries to Z3 using formulas that use quantifiers and if the formulas are satisfiable, you can use the satisfying model to evaluate ground expressions. Evaluating quantified expressions under a model is still as hard as checking satisfiability, so a simple evaluation engine would not work. 
So Z3 chooses not to support evaluating quantified formulas. 
There is probably something that the CBMC pipe can do differently to handle cases like these.
For example, if it wants to know the truth value of a quantified formula F, it can create a definition
(assert (= q F)) using a predicate symbol q and then work using q. A model for constraints that include F would evaluate F to the same truth value as q.

Could you follow up with CBMC on how to resolve this issue? It isn't really a Z3 bug, and we will not be supporting evaluation of quantified formulas.

**Comment by arey0pushpa** [comment]
Thanks. In touch with cbmc ppl. Was Helpful

**Comment by arey0pushpa** [comment]
cbmc underline is considering to handle that on their own. Thanks

**Comment by NikolajBjorner** [comment]
[OK](http://www.iemoji.com/view/emoji/26/people/face-with-tears-of-joy)
