### ISSUE TITLE
optimization with uninterpreted functions

### ISSUE THREAD

**Issue by LeventErkok** [Z3Prover/z3#4570]
This is more of a curiosity than an actual problem. I totally expected z3 to complain the following wasn't supported:

```python
from z3 import *

x = Int('x')
f = Function('f', IntSort(), IntSort())

o = Optimize()
o.maximize(f(x))
print(o.sexpr())
print(o.check())
print(o.model())
```

I was surprised to get the following output:

```
(declare-fun f (Int) Int)
(declare-fun x () Int)
(maximize (f x))
(check-sat)

sat
[x = 1, f = [else -> 0]]
```

Is this expected? If so, what would be the right way to interpret the output? Perhaps it might help to detect and reject optimization requests in the presence of uninterpreted functions like this?

**Comment by NikolajBjorner** [comment]
In your example, the objective is unbounded so it ends up with some dummy interpretation for f. 
But uninterpreted functions are fine and in fact something that a user can take advantage of. The alternative to compiling away uninterpreted functions is to introduce Ackerman axioms up front. Instead the usual EUF decision procedures handle uninterpreted functions without necessarily creating superfluous constraints.

**Comment by LeventErkok** [comment]
Thanks..

I'm not quite sure how to make that useful though. Typically the constraints I'd put on an uninterpreted function would be quantified. But the optimizer definitely doesn't deal with quantification:

```python
from z3 import *

x = Int('x')
f = Function('f', IntSort(), IntSort())

o = Optimize()
o.add(ForAll([x], f(x) == If(x < 10, x, 20)))
o.maximize(f(x))
print(o.check())
```

This prints a warning and loops forever:

```
WARNING: optimization with quantified constraints is not supported
^Cunknown
```

So, I'm not quite sure how to take advantage of uninterpreted functions in an optimization context.

I'll close this ticket as it's not a real issue, but I'd appreciate any comments/references if you have them handy.

**Comment by NikolajBjorner** [comment]
Quantifiers are different, They are not supported mainly because 
1. the optimization solver fixes some settings that are great for quantifier-free optimization, but bad for quantifiers.
2. the optimization calls may use both sat and unsat sub-calls. With quantifiers the typical scenario is unknown or unsat. 

You can define recursive functions or even simpler your own python macro for the example above.
