### ISSUE TITLE
Meaning of 'compose', 'indent', and 'choice' in z3 log

### ISSUE THREAD

**Issue by murali24adithya** [Z3Prover/z3#4571]
I'm trying to understand the meaning of the log that is generated by running z3 with options trace=true and proof=true. I have attached an example boogie file, the smt file that it generates and a partial log.

There is the quantifier <i>#</i>105 is being instantiated with the term in <i>#</i>186 on line 944
I believe that the intended meaning of <i>#</i>186 is the number 2, which is attached to it on line 616
However, <i>#</i>186 is rewritten between line 616 and line 944 on line 871.

I see this occurring in other instances as well, with the overwritten value typically being a [mk-app] line with 'compose', 'indent', or 'choice' being the function applied. How do I interpret this log?

[factorial_bpl.txt](https://github.com/Z3Prover/z3/files/4891947/factorial_bpl.txt)
[factorial_smt.txt](https://github.com/Z3Prover/z3/files/4891948/factorial_smt.txt)
[factorial.log](https://github.com/Z3Prover/z3/files/4892021/factorial.log)

**Comment by NikolajBjorner** [comment]
The log prints every expression that gets created.
If there is a call to pretty-print an expression, then the pretty printer uses expressions to create a format. The format uses 'compose', 'indent', 'choice'. These expressions are not going to be used in the proof. 
Somewhere the axiom profiler uses the pretty printer and causes this to happen.

**Comment by murali24adithya** [comment]
If I can somehow ignore these pretty-printing instructions, is it the case that all the term ids are in the same namespace, regardles of whether they are assigned to using the [mk-app], [mk-quant], or [attach-meaning] tags?

**Comment by NikolajBjorner** [comment]
It is most likely due to a regression in the axiom tracing. It uses a function to display a justification. That function was changed to display pretty-printed expressions. It isn't really something the profiler should consume. So I added a function to trace justifications without pretty printed expressions. Your log no longer contains these formatting directives.
