### ISSUE TITLE
Segfault in z3

### ISSUE THREAD

**Issue by abakst** [Z3Prover/z3#4572]
Hello, 

The following file causes a segfault: https://gist.github.com/abakst/7a46062e67a581824843393b3f771787:

```
$ z3 -smt2 bad.smt
[1]    84907 segmentation fault  z3 -smt2 bad.smt
```

Note that if the topmost expression is uncommented (`(set-option :produce-proofs true)`) then the segfault is disabled. (I added this because I stumbled on issue #588 when searching for this one). 

```
$ uname -mrsv
Darwin 19.4.0 Darwin Kernel Version 19.4.0: Wed Mar  4 22:28:40 PST 2020; root:xnu-6153.101.6~15/RELEASE_X86_64 x86_64
```
```
$ z3 --version
Z3 version 4.8.8 - 64 bit
```

**Comment by NikolajBjorner** [comment]
Very weird we haven't hit this bug before. A reference to a pointer becomes stale during a loop. The up-to-date version of the pointer has to be retrieved.

**Comment by abakst** [comment]
Thanks!
