### ISSUE TITLE
(smt.relevancy=1) slow to find trivial solution when using "or" over "ite" in recursive function

### ISSUE THREAD

**Issue by krobelus** [Z3Prover/z3#4573]
Hi, we @symflower have been using `smt.relevancy=1`, originally due to #1978 which seems to be fixed in current z3, which solves the reproducer just fine without `smt.relevancy=1`.

We have found an interesting formula where changing an expression like `(ite x true y)` to `(or x y)` causes z3 4.8.8 with `smt.relevancy=1` to take much longer than in the default configuration. Both configurations find the same trivial model.

Should there be a difference between `ite` and other Boolean operators, in particular when used in recursive functions like here?

```sh
$ time z3 ite.smt
sat
__________________________
Executed in   42.49 millis

$ time z3 ite.smt smt.relevancy=1
sat
________________________
Executed in    7.85 secs
```

```smt
(define-sort IndexType () (_ BitVec 7))
(define-const zero	IndexType #b0000000)
(define-const one	IndexType #b0000001)

(declare-datatypes () (
	(Inner
			InnerNil
			(Inner (inner (Array Bool Bool))))))
(declare-datatypes () (
	(Vector
			VectorNil
			(Vector (array (Array IndexType Inner)) (length IndexType)))))

(define-fun-rec all-elements-are-nil ((v Vector) (i IndexType)) Bool
	(
	or (= i zero)		; When using the next line instead, the issue disappears.
	; ite (= i zero) true
		(and
			(=
				(select (array v) (bvsub i one))
				(as InnerNil Inner))
			(all-elements-are-nil v (bvsub i one)))))

(declare-const v Vector)
(assert (all-elements-are-nil v (ite (= v (as VectorNil Vector)) zero (length v))))

(check-sat)
```

**Comment by NikolajBjorner** [comment]
The ite structure of terms within a recursive function definition is used to guide expansion of recursive functions.
So if you have a base case for a recursive function under an "if"(whether the then or else branch), the solver seeks to satisfy that branch before descending into recursively unfolding the function definition.
There is no evaluation specific treatment of "or" or other logical connectives. So if you disable relevancy (from 2) _and_ obscure the base/inductive case distinction for recursive functions, 
then the solver will want to establish a truth value to all atomic formulas within the recursive definition.

**Comment by krobelus** [comment]
Knowing that, the behavior seems entirely reasonable. Thanks for clarifying!

Also I found a small typo in an error message - search for `disumbiguate`.
