### ISSUE TITLE
The difference between the static library and the shared library

### ISSUE THREAD

**Issue by Flians** [Z3Prover/z3#4574]
I meet the problem that I prove the following expression using Z3. 
```
Z3_config cfg;
cfg = Z3_mk_config();
Z3_set_param_value(cfg, "model", "true");
Z3_set_param_value(cfg, "proof", "true");
Z3_set_param_value(cfg, "timeout", to_string(timeout).c_str());
logic = Z3_mk_context(cfg);
Z3_set_error_handler(logic, error_handler);
Z3_del_config(cfg);

bv_sort = Z3_mk_bv_sort(logic, 2);
Z3_solver z3_sol = Z3_mk_solver_for_logic(logic, Z3_mk_string_symbol(logic, "QF_BV"));
Z3_solver_inc_ref(logic, z3_sol);

Z3_ast result = Z3_mk_and(logic, args_size, args);
Z3_solver_assert(logic, z3_sol, Z3_mk_not(logic, result));
Z3_lbool result = Z3_solver_check(logic, z3_sol);
```
When my program uses the shared library, it works normally.
When my program uses the static library, it was interrupted at Z3_solver_check and there was no output.

I dont know what happend. And I must use the static library. 
Can you help me?

**Comment by andrewvaughanj** [comment]
What do you mean by:

> the process of Z3_solver_check is broken

?

**Comment by Flians** [comment]
@andrewvaughanj 
The program was interrupted at Z3_solver_check and there was no output.

**Comment by andrewvaughanj** [comment]
What do you mean "interrupted"? Do you mean a segfault? Are you building a single-threaded `libz3.a` (without the need for `pthread`)?

**Comment by Flians** [comment]
Yes, a segfault. 
Both single-threaded and multi-threaded libraries have failed.

**Comment by andrewvaughanj** [comment]
Can you provide any additional details? Like a backtrace from `gdb`?

**Comment by Flians** [comment]
# static library
target_link_libraries (${PROJECT_NAME} PRIVATE Threads::Threads ${CMAKE_SOURCE_DIR}/lib/linux/libz3.a croaring)
 # shared library
target_link_libraries (${PROJECT_NAME} -lz3 croaring)

**Comment by andrewvaughanj** [comment]
Sorry, but without being able to reproduce this with a [MWE](https://en.wikipedia.org/wiki/Minimal_working_example), I'm not sure I am going to be able to help much.

All I will say is that Z3 is an open-source project, and you're probably doing something outside of the normal flow (statically linking) -- there a chance you might need to fix this yourself. The fact that shared linking works, and we know that statically linking `glibc` can cause issues, makes me think you might be on your own ...

Why do you need static linking?

**Comment by Flians** [comment]
yeah, I wanna print the smt from you. But 2 hours passed, there is still no output.
`printf("term: %s\n", Z3_ast_to_string(logic, result));`

I must copy the executable file to others.

**Comment by SweetVishnya** [comment]
Is it written anywhere in docs that Z3 requires pthread? Maybe it should be placed in README.

**Comment by nunoplopes** [comment]
Ok, it seems there's nothing left to do here.
Please feel free to send a PR if you think there's something in cmake/configure that could be improved.
