### ISSUE TITLE
Sub-optimal optimization result for some duplicate target weights

### ISSUE THREAD

**Issue by Jakob-Bach** [Z3Prover/z3#4575]
Consider the following example, which has a linear objective function combined with an at-most constraint:

```python
import z3

utilities = [0.4, 0.37, 0.51, 0.09, 0.44, 0.7, 0.38, 0.26, 0.7]
optimizer = z3.Optimize()
variables = [z3.Bool('x' + str(i)) for i in range(len(utilities))]
objective = z3.Sum([u * var for (u, var) in zip(utilities, variables)])
objective_value = optimizer.maximize(objective)
optimizer.add(z3.AtMost(*variables, 1))
optimizer.check()
print('Objective value: ' + str(objective_value.value()))
print('Model:')
print(optimizer.model())
print('Optimizer:')
print(optimizer)
```

Output:

```
Objective value: 51/100
Model:
[x0 = False,
 x1 = False,
 x2 = True,
 x3 = False,
 x4 = False,
 x5 = False,
 x6 = False,
 x8 = False,
 x7 = False]
Optimizer:
(declare-fun x8 () Bool)
(declare-fun x7 () Bool)
(declare-fun x6 () Bool)
(declare-fun x5 () Bool)
(declare-fun x4 () Bool)
(declare-fun x3 () Bool)
(declare-fun x2 () Bool)
(declare-fun x1 () Bool)
(declare-fun x0 () Bool)
(assert ((_ at-most 1) x0 x1 x2 x3 x4 x5 x6 x7 x8))
(maximize (+ (ite x0 (/ 2.0 5.0) (to_real 0))
   (ite x1 (/ 37.0 100.0) (to_real 0))
   (ite x2 (/ 51.0 100.0) (to_real 0))
   (ite x3 (/ 9.0 100.0) (to_real 0))
   (ite x4 (/ 11.0 25.0) (to_real 0))
   (ite x5 (/ 7.0 10.0) (to_real 0))
   (ite x6 (/ 19.0 50.0) (to_real 0))
   (ite x7 (/ 13.0 50.0) (to_real 0))
   (ite x8 (/ 7.0 10.0) (to_real 0))))
(check-sat)
```

At least on my system (Windows, Python package  `z3-solver`, version 4.8.8.0 from `pip`), the program wants to set x2 to true, yielding an objective value of 0.51 instead of 0.7 (if x5 or x8 were selected). The issue does not seem to occur if the highest weight in the objective function is unique (here, x5 and x8 have the same weight, which is the highest, x2 only has the 2nd highest). The issue might not occur with fewer variables, but might still occur with more variables (haven't tested that exhaustively). Also, adding the same objective twice:

```
objective_value = optimizer.maximize(objective)
objective_value = optimizer.maximize(objective)
```

seems to resolve the issue (at least for that particular example), for whatever reason.

**Comment by NikolajBjorner** [comment]
good find. Somehow this was undetected bug in an optimization that seeks to reduce problems when there is a useful correction set.
