### ISSUE TITLE
Microsoft.Z3.xml missing in release package

### ISSUE THREAD

**Issue by Progress1** [Z3Prover/z3#4578]
In past (e.g. 4.7.1) you include file **Microsoft.Z3.xml** file inside your release package. Now in current releases is this file missing. This file is important because it shows in Visual Studio help on commands.

**Comment by NikolajBjorner** [comment]
The .net bindings are now built using "dotnet build". These don't emit xml information, at least not by default.
The Microsoft.Z3.X64.nuget package that gets published on NuGet.org should be the go-to source for integrating z3 in a .net project.

**Comment by wintersteiger** [comment]
@NikolajBjorner That .xml contains the function-level documentation so that Visual Studio (and similar) can show it in tooltips, etc. Whatever is now used to build the packages, should also produce that file. I think this has the right instructions for .NET core: https://docs.microsoft.com/en-us/dotnet/csharp/codedoc

**Comment by NikolajBjorner** [comment]
Thanks for the pointer. It works. The next nightly will have xml included.

**Comment by tompazourek** [comment]
@NikolajBjorner I'm just checking the latest nightly ([commit 0aac7e54a91de423088f0f321b9eef1bbac87118 v4.8.10](https://github.com/Z3Prover/z3/releases/tag/Nightly)) and the xml documentation file is still missing. Same goes for the stable v4.8.9.

![image](https://user-images.githubusercontent.com/370699/104286810-db4cf680-54b5-11eb-9115-8a0031c8a0b2.png)

This means that the VS IntelliSense is lacking as a result of that.

Could we please re-open this? It seems it's still an issue...

I'd also offer some help with this, but I checked the source code and don't see any issue there. What's strange to me is that the [csproj in the source](https://github.com/Z3Prover/z3/blob/master/src/api/dotnet/Microsoft.Z3.csproj.in#L52) uses TFMs `netstandard2.0` and `net45` while the final NuGet actually has `netstandard1.4`. So maybe I'm just not looking at the right code...

**Comment by NikolajBjorner** [comment]
There exists some way to figure out how to include the right files.
Last time I fiddled with nuget, before Christmas, it took me 4 days to get code signing to build correctly. Some more savvy person could do it much faster. I pushed what could be a fix or something close to it, and running nightly to see if it gets to the right place.

**Comment by tompazourek** [comment]
@NikolajBjorner What about the TFM inconsistency? Isn't it an issue that you build it for `netstandard2.0` in the csproj and then pack it via nuspec as `netstandard1.4`? I might be missing some part of the build process though...

**Comment by NikolajBjorner** [comment]
The nuget package for the nightly and release build is created by a different script. The script is here:
https://github.com/Z3Prover/z3/blob/8abb644378ebaf1a9699e1b2fdd32075bcfcea4e/scripts/mk_util.py#L1662

The nightly build now includes the xml file in the nupkg bundle.

**Comment by tompazourek** [comment]
@NikolajBjorner Thank you very much for the quick XML doc fix, the nightly build seems ok, and this issue can be closed now. Any idea when we might expect a next stable release?

The issue regarding the TFM I'm raising is that you build the code telling the compiler to build for `netstandard2.0`, then you take the built DLLs, and pack them into a NuGet claiming they are intended for `netstandard1.4`. Do you see the problem I'm trying to point out?

**Comment by NikolajBjorner** [comment]
But the script we use for the build is in z3/scripts/mk_util.py. The file https://github.com/Z3Prover/z3/blob/master/src/api/dotnet/Microsoft.Z3.csproj.in#L52
is not used for the release

**Comment by NikolajBjorner** [comment]
I plan to make an inaugural release by middle of next week.

**Comment by tompazourek** [comment]
@NikolajBjorner I see, thank you for the clarification. Looking forward to the release, lot of great improvements in this one 🙂

**Comment by NikolajBjorner** [comment]
this was fixed
