### ISSUE TITLE
How do I make sure that my theory is linear?

### ISSUE THREAD

**Issue by tari3x** [Z3Prover/z3#4580]
I made changes to a linear optimization problem and the solver now doesn't finish in time. It could be that i made the problem too large, or it could be that I made it non-linear by mistake. Is there a way for me to tell the difference?

Are there other ways to gain insight into what is taking a long time, or should I mostly treat it as a black box?

**Comment by NikolajBjorner** [comment]
You can print _statistics_ that gives a bird's eye view of what subroutines were invoked during solving. For non-linear problems, the solver invokes Horner rules, Grobner style solving, nlsat, and incremental linearization. The statistics would list such activities.
It could very well be that the solver spends time in completely unexpected activities. The statistics is a starting point. Another indicator is to run the solver with verbose=10 and it will give some hints at what it is doing.

**Comment by tari3x** [comment]
Thanks! For reference of others, I think I need (get-info :all-statistics). Will give it a go.
