### ISSUE TITLE
Q: is it possible to force the use of floating point numbers as opposed to rationals?

### ISSUE THREAD

**Issue by tari3x** [Z3Prover/z3#4581]
This is kinda related to https://github.com/Z3Prover/z3/issues/1806

I have a linear problem running for a long time and pstack shows me that it spends time in mpq_manager<true>::rat_mul. Is there any way to tell it to not bother with rationals and to use native floats instead?

**Comment by NikolajBjorner** [comment]
We have been experimenting with floats on and off. It is often very unstable and our basic 
fall-back path to infinite precision would have to be taken too often. The use of floats is not not available and would require significant updates to resurrect.

**Comment by tari3x** [comment]
Thanks! Fwiw, either this or something else is affecting the performance really badly. I tried it with GLPK, and it solves in about 5 seconds problems that Z3 wasn't able to solve in 3 hours, and the output on small problems is the same.
