### ISSUE TITLE
directly obtain values under a certain model, not aliased variables

### ISSUE THREAD

**Issue by SunBeomSo** [Z3Prover/z3#4583]
Using the function ``Z3.Model.evaluate`` (in Z3 OCaml api),
I tried to obtain a value of ``amount__567@E@T460``  under a certain model, and further tried to convert that value into a string using the function ``Z3.BitVector.numeral_to_string``.

However, I encountered an error message ``Z3.Error("invalid argument")``.
Having inspected the obtained model, I guess that the error happend because the function ``Z3.Model.evaluate`` does not directly return ``#x0000000000000000000000000000000000000000000000000000000000000001`` but return ``amount__567@T460``, which makes the use of  ``Z3.BitVector.numeral_to_string`` invalid.

```
(define-fun amount__567@T460 () (_ BitVec 256)
  #x0000000000000000000000000000000000000000000000000000000000000001)
...
 // COMMENT:  HOW TO MAKE IT DIRECTLY RETURN #x0000000000000000000000000000000000000000000000000000000000000001 ?
(define-fun amount__567@E@T460 () (_ BitVec 256)
  amount__567@T460)
...
```

Are there any API functions that directly return values of certain variables? I used Z3 4.8.8.

**Comment by NikolajBjorner** [comment]
You should pass the argument 'true' (model completion) to evaluate so that it produces values to variables even though the model does not produce values for them.  The is_numeral function tests whether expressions are of the right form for BitVector.numeral_to_string.

**Comment by SunBeomSo** [comment]
Thanks for the answer!
