### ISSUE TITLE
Seg fault with both Z3 binary / Python wrapper upon using non-linear solver

### ISSUE THREAD

**Issue by dorcoh** [Z3Prover/z3#4586]
Hi, I'm getting segmentation fault upon attempting to solve the following [formula](https://gist.github.com/dorcoh/c2a82b7896ed2ac10ee98b7f839a6b13) which is in NRA theory. It has one free variable and two variables which are under \forall quantifier clause. Other than that there are about 50+ constraints.

My attempts to solve this formula included versions `4.5.1` (both Python wrapper, z3 binary), `4.8.7` and `4.8.8` through z3 binaries (64 bit version), all of them return with segmentation faults (exit codes 137, 138, 139). Additionally, in all of the runs we observe high amounts of memory consumption (~35Gb), it seems like the memory consumption grows and then reaches some limit at the end of the process. To note, this behavior does not happen (with these versions) when using smaller formulas but similar in their structure to the attached formula. (OS details: `Red Hat Enterprise Linux Server release 6.7 (Santiago)`, Linux kernel: `2.6.32-696.3.2.el6.x86_64`) 

We also tested this formula on another machine, with older z3 binaries / python wrapper (`4.4.1`) and so far we cannot observe an unusual memory usage (it is stable and does not grow gradually in contrast to previously mentioned attempts). (OS details: `Ubuntu 16.04.6 LTS` , Linux kernel: `4.15.0-107-generic`). On this machine I have also tried version `4.8.3 64 bit` and it seems to have the suspected memory leak as well.

Let me please know if any other details are needed if you'd like to try and re-produce this behavior, thanks!

**Comment by andrewvaughanj** [comment]
When the modern ones "segfault", is it possible that it is being killed by Linux's "out of memory" killer? Is there anything in `dmesg`? How much RAM do you have (both physical and swap)?

**Comment by dorcoh** [comment]
Yes, it is indeed a possibility that the process is getting killed automatically. At the first machine which is actually a cluster I don't have access to these, though I'm getting a summary with statistics and it shows the process exits with approximately the same amount of ram/vram consumption. About actual physical RAM, it has about 100GB, swap is around 10% of the physical. This behavior also occurred to me with other similar instances that consumed 80GB (of both ram and vram). 

However, this behavior does not occur at all on `4.4.1`, where the memory is stable. Are you aware of any major differences between versions that could causes this behavior?

**Comment by andrewvaughanj** [comment]
Interesting, so I guess your question is (really): "why is there such a huge difference in memory usage between 4.4.1 and later versions?" (vs. the segfault, which could be a red herring if it is the OOM rather than Z3 itself).

Unfortunately, I'm now out of my depth so can't really help ... sorry!

**Comment by dorcoh** [comment]
Exactly, I would like to know where this gap comes from (if we could somehow solve it for later versions that would be great). In any case, you helped to rephrase my question, then many thanks :) 

Hope that other contributors could also add their insights about it.

**Comment by andrewvaughanj** [comment]
Roughly, how quick does it take to "die" on later versions / how quick does it take to solve on 4.4.1?

I'm just wondering if we can easily narrow it down to when the memory "got worse".

**Comment by dorcoh** [comment]
It takes about 20-40 minutes for the solver to die (or get killed). While on the other, less strong machine (with z3 4.4.1), the solver doesn't terminate even after 24 hours. This formula is relatively hard, but otherwise I cannot reproduce this behavior. If that's critical to have a small sized formula in order to mitigate this issue, then I will put more effort to try and produce such formula.

**Comment by andrewvaughanj** [comment]
Oh! That's really interesting: so, given enough time, *maybe* 4.4.1 would also OOM? Maybe (hopefully 😂) Z3 has gotten better since 4.4.1 so it gets "memory hungry" quicker than in did in 4.4.1.

Maybe your massive file is enough for one of the developers of Z3 to understand what's going on; if you're able to make a smaller example that shows it, then that's probably even more helpful!

**Comment by dorcoh** [comment]
I don’t think the 4.4.1 will OOM since I tracked its memory consumption. It
stays low and constant, and doesn’t grow through time.

I will try to produce a simple formula. Thanks!

**Comment by andrewvaughanj** [comment]
Yeah, I *really* not sure you can say that ... imagine that there a few stages in solving SMT: for the purposes of this example, call them Phase 1 and Phase 2, and Phase 2 is the "memory hungry" one -- it is possible that 4.4.1 is stuck in Phase 1, while newer versions have had improvements to Phase 1, so they move to Phase 2 quicker and eat all the RAM.

I'm not saying that's the case, I'm just saying you cannot say it _isn't_ the case.

**Comment by dorcoh** [comment]
I agree. And yet I hope other contributors could shed more light about it.

**Comment by NikolajBjorner** [comment]
The current behavior of the preprocessor for this class of formulas is to lift non-Boolean if-then-else expression to Boolean top level for expressions inside of a quantifier. Since there are 50 or so if-then-else expression it leads to a non-practical blow-up.
One possible mitigation at this point is to use the built-in ((_ at-least 50) e1 .... , e51)) operator for Boolean versions of the (ite e_i 1 0) expressions.
