### ISSUE TITLE
Root isolation as C/C++ API

### ISSUE THREAD

**Issue by rainoftime** [Z3Prover/z3#4587]
Hi, is there any suggestion for using the root isolation functionality via the C/C++/Python API?
For example, assume an equation `P(x)` has three roots −1, 0.5, and 3. The algorithm may give [−2, -0.3] [0, 1] [2, 6]
Thanks!

**Comment by NikolajBjorner** [comment]
The API exposes methods to access values of algebraic numbers. Algebraic numbers correspond to roots to polynomials. They cannot, generally, be written as rational numbers. The functions algebraic_number_lower and algebraic_number_upper and variants of them allow to retrieve a rational number that represent lower/upper bounds up to a number of decimal places of precision.
So if you have a polynomial P(x) := x*x-x-1, z3 will produce an irrational solution for x (the golden ratio).
The python interface exposes "approx" to access an upper bound for the numeral.

```
from z3 import *

x = Real('x')
p = x*x - x - 1
s = Solver()
s.add(p == 0)
print(s.check())
print(s.model())
print(s.model().eval(x).approx(100))
```

**Comment by rainoftime** [comment]
Thanks! I will try
