### ISSUE TITLE
Unavailableness of using list sort on tuple

### ISSUE THREAD

**Issue by jormal** [Z3Prover/z3#4589]
Hi there. I'm user of Z3 OCaml binding.

I was stuck on `Z3.Tuple.get_mk_decl` because of list sort.

``` OCaml
let ctx = ref (Z3.mk_context []) in

... (* Symbol declarations *)

let int_sort = Z3.Arithmetic.Integer.mk_sort !ctx in
let int_list_sort = Z3.Z3List.mk_sort !ctx int_list_symbol int_sort in
let tuple_sort = Z3.Tuple.mk_sort !ctx tuple_symbol [tuple_fst_symbol; tuple_snd_symbol] [int_sort; int_list_sort] in

let tuple_const_func = Z3.Tuple.get_mk_decl tuple_sort in (* Fatal error: exception Z3.Error("invalid argument") *)
```

On above code, `Z3.Tuple.get_mk_decl` doesn't get `tuple_sort` as argument, because `tuple_sort` has `int_list_sort` on second element.
On the other case, int sort and array sort can make proper constructor function declaration.

Due to hardness to find documents of it, I came here and ask this. Please answer to me. 😭

**Comment by NikolajBjorner** [comment]
this is a bug in a check that is invoked by Tuple.get_mk_decl. It should have worked as you expected and it has now been fixed.

**Comment by jormal** [comment]
@NikolajBjorner Thanks! :)
