### ISSUE TITLE
Problem installing Z3 in ubuntu 16.04

### ISSUE THREAD

**Issue by mahdiehhjz** [Z3Prover/z3#4592]
I downloaded Z3 from https://github.com/Z3Prover/z3 on Ubuntu 16.04, but the compiled file microsoft.z3.dll is installed in the project directory instead of the mono or GAC folder, and the programs do not recognize it (microsoft.z3.dll is placed in z3-master/build/ instead of /usr/lib/mono/xbuild-frameworks/.NETFramework/v4.5.2/).

These are the instructions I used to install Z3:

Install the package repository of the mono project as described at their download page, and then:
sudo apt-get install mono-devel
sudo apt-get install nuget

Download the current stable release from Z3 releases, and then:

CSC=/usr/bin/csc GACUTIL=/usr/bin/gacutil python scripts/mk_make.py --dotnet
cd build
make
sudo make install

Please advise me how to install the file microsoft.z3.dll elsewhere or how to move the installed file microsoft.z3.dll.

**Comment by NikolajBjorner** [comment]
The mentions of GAC/CSC seems stale. It now builds a nuget package, also present in the nighly builds and published on nuget.org. You should use the nuget utilities to install. I have removed stale mentions of CSC and GAC in the readme.
