### ISSUE TITLE
Problem satisfying constraints in QF-ALIA

### ISSUE THREAD

**Issue by assaft** [Z3Prover/z3#460]
Hello,
I hope that this is the right place to report this issue.
I'm trying to check the satisfiability of temporal constraints in Z3 and it seems like there's some problem when the constraints are defined using arrays. Other provers, such as CVC4 and Yices, work fine, so I thought that this issue could be of interest here.
The full story was posted [here](http://stackoverflow.com/questions/35592724/representing-temporal-constraints-in-smt-lib) and sample code for reproducing the problem is attached.
I hope this help,
Assaf

[TemporalTest.zip](https://github.com/Z3Prover/z3/files/150786/TemporalTest.zip)

**Comment by wintersteiger** [comment]
It's known that Z3 behaves worse than other SMT solvers when arrays are involved. By "others work fine" do you mean they produce the correct result within a short amount of time, or do you mean that they don't throw the errors and exceptions that Z3 throws?

**Comment by assaft** [comment]
Thanks for the info. By "others work fine" I mean that they (CVC4 and Yices) manage to satisfy the constraints and create a model. It takes them about 5 seconds to do so. Z3 does not throw errors and exceptions in my example, it just keeps running and I stopped it after 40 minutes.

By the way, may I ask a clarification question here? I'm trying to understand - does the fact that the input is in a decidable logic (QF-ALIA) mean that Z3's behavior should count as a bug? I understand that being in a decidable logic means that there are effective methods for determining whether arbitrary formulas are theorems, and based on that I conclude that a resolution (sat/unsat) should be given in a reasonable time. However, when looking at SMT Comp 2015 results, it seems that all provers fail to prove some theorems in decidable logics. So I'm not sure what to make out of this.

**Comment by wintersteiger** [comment]
Indeed, "decidable" does not mean "efficient". There will always be problems that are too hard to solve for some solvers and sometimes using a different random seed can change hours into seconds. This is unavoidable just by the nature of the problems given. For instance, using huge bit-vectors will make most solvers run out of memory very quickly, regardless of whether the whole problem is decidable, hard, or easy.
