### ISSUE TITLE
Changing variable name turns `sat` into `unknown`

### ISSUE THREAD

**Issue by LeventErkok** [Z3Prover/z3#4600]
This was originally reported https://stackoverflow.com/questions/63159430/z3-variable-name-causing-unknown-satisfiability

The following benchmark is answered `sat` by z3:

```
(declare-fun length ((Array Int Int)) Int)

(declare-const lindx2 (Array Int Int))
(declare-const indx1 (Array Int Int))
(declare-const orig_findx1 (Array Int Int))

(assert (and
  (forall ((i Int) (j Int))
    (let ((a!1 (and (<= 0 i)
                    (<= i (- (length indx1) 1))
                    (<= 0 j)
                    (<= j (- (length orig_findx1) 1))
                    (= i j))))
      (=> a!1 (= (select indx1 i) (select orig_findx1 j)))))
  (= (length lindx2) 11)
  (forall ((i Int)) (=> (and (<= 3 i) (<= i 25)) (= (select indx1 i) (- 1))))))

(check-sat)
```

What it does is really irrelevant. I'm also not sure if `sat` is the correct answer. (In particular, CVC4 produces `unknown` on it.) Since there are a lot of quantifiers involved, I'd have expected `z3` to produce `unknown` as well, but maybe `z3` has a better handle on this problem for some reason.

What's interesting is that if you simply rename the variable `indx1` to `findx1`, i.e., run the following:

```
(declare-fun length ((Array Int Int)) Int)

(declare-const lindx2 (Array Int Int))
(declare-const findx1 (Array Int Int))
(declare-const orig_findx1 (Array Int Int))

(assert (and
  (forall ((i Int) (j Int))
    (let ((a!1 (and (<= 0 i)
                    (<= i (- (length findx1) 1))
                    (<= 0 j)
                    (<= j (- (length orig_findx1) 1))
                    (= i j))))
      (=> a!1 (= (select findx1 i) (select orig_findx1 j)))))
  (= (length lindx2) 11)
  (forall ((i Int)) (=> (and (<= 3 i) (<= i 25)) (= (select findx1 i) (- 1))))))

(check-sat)
```

then z3 says `unknown`. While this isn't unsound, I found it extremely surprising that merely changing the variable name changes `sat` to `unknown`.

To be absolutely clear, here's the word `diff` between these two benchmarks:

```
$ wdiff -3 1.smt2 2.smt2

======================================================================
 [-indx1-] {+findx1+}
======================================================================
 [-indx1)-] {+findx1)+}
======================================================================
 [-indx1-] {+findx1+}
======================================================================
 [-indx1-] {+findx1+}
======================================================================
```

As seen, it's merely replacing 4 instances of the word `indx1` with `findx1`.

I played around a bit, and it seems that if you use any name but `indx1` you get `unknown`. If you use `indx1` then you get `sat`.

Really curious why this would be the case!

**Comment by NikolajBjorner** [comment]
Note also:

C:\z3\build>z3 unk.smt2
sat

C:\z3\build>z3 unk.smt2 smt.random_seed=1
unknown

C:\z3\build>z3 unk.smt2 smt.random_seed=2
sat

C:\z3\build>z3 unk.smt2 smt.random_seed=3
sat

C:\z3\build>z3 unk.smt2 smt.random_seed=4
unknown

C:\z3\build>z3 unk.smt2 smt.random_seed=5
unknown

C:\z3\build>z3 unk.smt2 smt.random_seed=6
sat

**Comment by LeventErkok** [comment]
I remember seeing performance differences before. But I believe this is the first time I’m seeing `sat` becoming `unknown`. That really surprised me, but I guess that’s the behavior. 

Feel free to close this ticket. I’ll leave it open as I can’t tell if there’s anything to be done for it.

**Comment by NikolajBjorner** [comment]
It is MBQI that ends up failing to determine satisfiability. It is tied to array models. MBQI is more stable when you replace arrays by uninterpreted functions.
