### ISSUE TITLE
Vastly different solving behaviors of 4.8.8 due to function naming

### ISSUE THREAD

**Issue by robby-phd** [Z3Prover/z3#4604]
Attached is a zip file containing two examples that differ only on an uninterpreted function's name (`|top.f|` vs `|f|`), one where z3 solved it instantaneously and the other seems to go on forever.  

Interestingly, on Windows and macOS, the first one is solved; and on Linux, the second one is solved instead.

[examples.zip](https://github.com/Z3Prover/z3/files/5004346/examples.zip)

**Comment by robby-phd** [comment]
Perhaps this is a duplicate of #4600 (?).

**Comment by NikolajBjorner** [comment]
This is generally inevitable. The query has non-linear arithmetic which is particularly difficult to control.
