### ISSUE TITLE
Get the unsat core w.r.t. a pre-conditon

### ISSUE THREAD

**Issue by rainoftime** [Z3Prover/z3#4608]
Given a pre-condition `F` and a set of constraints `S = {Q1, ..., Qn}`,  the goal is to find a subset of `S` (of size k) such that 
`F and (Q1 and ... and Q_k)` is unsatisfiable. Does z3 provide such API? Thanks!

In other words, we need to find the unsat core of `{F, Q1, ..., Qn}` such that the core  must contain `F`.

**Comment by rainoftime** [comment]
Maybe I can use named assertions/literals? (1) Add `F` to the solver without giving it a name, (2) add `S` to the solver, with each `Qi` given a name; (3) check for satisfiability and obtain the unsat core

**Comment by NikolajBjorner** [comment]
You want to make sure that {F, Q1,..., Q_k} is unsat but {Q1,... ,Q_k} is sat.
If you ask for a core of {F, Q1, .., Q_k} it could be that it does not include F at all so you can't simply rely on unsat cores.
However, core-based maxsat algorithms that are based on core relaxation can help. Suppose you have a core Q1, Q2, Q3.
You can replace these by R1 := Q1 + Q2 + Q3 >= 1, and R2 := Q1 + Q2 + Q3 >= 2, or with another encoding by R1 := Q1 or Q2, R2 := Q3 or (Q1 and Q2). The new weaker system does not have the core Q1, Q2, Q3, 
but suppose you have a core that uses R2. You then know that the core that uses F has either Q1, Q2 or Q1, Q3 or Q2, Q3.
Generally a post-processing to narrow down subset that must include F can be done by removing elements from a summation one by one, so in a linear number of extra queries. There are some more clever tricks used in works that enumerate unsat cores and correction sets, but this should be a start.

**Comment by rainoftime** [comment]
Thanks!
