### ISSUE TITLE
How to run ddnf in z3

### ISSUE THREAD

**Issue by 916267142** [Z3Prover/z3#4609]
Our team found that "ddnf" was integrated into Z3. We would like to further apply the ddnf, but we didn't find the tutotial how to run it. It was integrated into Z3 as a module. We used "make test" to generate z3-test file then run it. The question is how to run this module such as SMT instead of test module.

**Comment by NikolajBjorner** [comment]
It is not a supported part of Z3. The code is there, but the only way to run it is from a unit test. It is not used otherwise. 
I suggest you simply reimplement it or something along the lines.

**Comment by 916267142** [comment]
Thanks a lot.  According to DDNF's paper, the HSA data set is used. The initial data of the HSA has been downloaded, but we find cannot direct applied into ddnf. Has the data used by DDNF modified the Stanford data? If so, is the modified data open source?
