### ISSUE TITLE
Bugs in Z3.Datatype of OCaml Bindings

### ISSUE THREAD

**Issue by jormal** [Z3Prover/z3#4615]
1. Though `mk_constructor` has a parameter `recognizer:Symbol.symbol`, recognizer of datatype doesn't have any name.
``` OCaml
# let empty_const = Z3.Datatype.mk_constructor !ctx (Z3.Symbol.mk_string !ctx "Empty") (Z3.Symbol.mk_string !ctx "is_empty") [] [] [] in
  let node_const = Z3.Datatype.mk_constructor !ctx (Z3.Symbol.mk_string !ctx "Node") (Z3.Symbol.mk_string !ctx "is_node") [(Z3.Symbol.mk_string !ctx "left"); (Z3.Symbol.mk_string !ctx "data"); (Z3.Symbol.mk_string !ctx "right")] [None; Some data_sort; None] [0; 2; 0] in
  let tree_sort = Z3.Datatype.mk_sort !ctx (Z3.Symbol.mk_string !ctx "Tree") [empty_const; node_const] in
  let recognizers = Z3.Datatype.get_recognizers tree_sort in
  let is_empty_func = List.nth recognizers 0 in
  print_endline (Z3.FuncDecl.to_string is_empty_func);;
(declare-fun is (Tree) Bool) (* not is_empty but is *)
```

2. I don't know why [document](https://z3prover.github.io/api/html/ml/Z3.Datatype.html) said `mk_sorts` is "Create mutually recursive datatypes." I think **mutually recursive** has this property.
``` OCaml
# let empty_const = Z3.Datatype.mk_constructor !ctx (create_symbol "Empty") (create_symbol "is_empty") [] [] [] in
  let node_const = Z3.Datatype.mk_constructor !ctx (create_symbol "Node") (create_symbol "is_node") [(create_symbol "left"); (create_symbol "data"); (create_symbol "right")] [None; Some data_sort; None] [0; 2; 0] in
  let nil_const = Z3.Datatype.mk_constructor !ctx (create_symbol "Nil") (create_symbol "is_nil") [] [] [] in
  let cons_const = Z3.Datatype.mk_constructor !ctx (create_symbol "Cons") (create_symbol "is_cons") [(create_symbol "head"); (create_symbol "tail")] [Some data_sort; None] [1; 0] in
  let what = Z3.Datatype.mk_sorts !ctx [(Z3.Symbol.mk_string !ctx "Tree"); (Z3.Symbol.mk_string !ctx "List")] [[empty_const; node_const]; [nil_const; cons_const]] in
  let tree_sort = List.nth what 0 in
  let list_sort = List.nth what 1 in
  let empty_func = List.nth (Z3.Datatype.get_constructors tree_sort) 0 in
  let node_func = List.nth (Z3.Datatype.get_constructors tree_sort) 1 in
  let nil_func = List.nth (Z3.Datatype.get_constructors list_sort) 0 in
  let cons_func = List.nth (Z3.Datatype.get_constructors list_sort) 1 in
  let empty = Z3.FuncDecl.apply empty_func [] in
  let nil = Z3.FuncDecl.apply nil_func [] in
  let tree = Z3.FuncDecl.apply node_func [nil; data; empty] in
  print_endline (Z3.Expr.to_string tree);;
Fatal error: exception Z3.Error("Sort mismatch at argument #1 for function (declare-fun Node (Tree Int Tree) Tree) supplied sort is List")
```
What is actual meaning of **mutually recursive**?

3. Functions of get function declaration in `Z3.Datatype.Constructor` throw invalid argument errors. What is correct input of them?
``` OCaml
# let pair_const = Z3.Datatype.mk_constructor !ctx (create_symbol "Pair") (create_symbol "is_pair") [(create_symbol "fst"); (create_symbol "snd")] [Some data_sort; Some data_sort] [1; 2] in
  let pair_func = Z3.Datatype.Constructor.get_constructor_decl pair_const in
  print_endline (Z3.FuncDecl.to_string pair_func);;
Fatal error: exception Z3.Error("invalid argument")
```

**Comment by NikolajBjorner** [comment]
regarding 1: at some point SMTLIB2 standard introduced recognizers as operators. They don't have their own names, but use the name of the constructor as argument. In SMTLIB2 it is: (_ is <constructor-name>). The internal representation of Z3 then took this earnest by introducing the "is" function that takes a constructor as parameter. The pretty printer doesn't show the constructor. It is a limitation of the pretty printer. But the recognizer is this functional. The names of recognizers that are added as parameters to the function that creates the constructor do produce their own functions but these are not the functions returned by the "get_recognizers" call.

Regarding 2, 3. Seem like bugs. 
Since I have a hard time setting up ocaml, could you do the following:
For a self-contained bug open a log.
Before any other calls into Z3 APIs do the following:

val _ Z3.Log._open "z3.log"

Then when there is a failure rerun the z3 executable on the log. 
The same failure should reproduce.
Since I recently added some functions to the API, it would help me if you reproduce the logs based on nightly builds.
If that is not possible, I can work with what you have, but it could lead to some back-and-forth.

**Comment by jormal** [comment]
@NikolajBjorner Thanks for answering me.
Sorry for absence of log file on last question. I immediately make logs for these bugs (2, 3).

I made Gist for their logs. Please check it.
[mk_sorts.log](https://gist.github.com/jormal/5d8c2e64154cecf6cb66847f08f5fab2)
[get_constructor_decl.log](https://gist.github.com/jormal/c3056e381cd000bf9523056fadaed04b)

That logs are made by same code of last question. And additionally, `Z3.Datatype.Constructor.get_tester_decl` and `Z3.Datatype.Constructor.get_accessor_decl` have made same error like 3.

**Comment by NikolajBjorner** [comment]
The logs suggest you have compiled version 4.7.1 recently. The current working version is 4.8.9 and the current release is 4.8.8.

**Comment by jormal** [comment]
I'm in an impossible position to change version right now.... So, I will close this issue and test it later when I can update Z3 to latest version.

**Comment by arbipher** [comment]
@NikolajBjorner 
I got a similar bug on z3 4.8.9 under OCaml 4.11.1, and I figured out how to avoid this bug (though I don't know the reason yet).

This bug can occur either in top-level or a compiled OCaml project.
```ocaml
#require "z3";;
open Z3;;
let ctx = mk_context [] in
let iS = Arithmetic.Integer.mk_sort ctx in
let iC = Datatype.mk_constructor_s ctx "Int" (Symbol.mk_string ctx "is-Int") [Symbol.mk_string ctx "i"] [Some iS] [1] in
(* let iS = Datatype.mk_sort_s ctx "IntOrBool" [iC] in *)
let iD = Datatype.Constructor.get_constructor_decl iC in
()
```

if you call `Datatype.Constructor.get_constructor_decl` on a constructor `iC` before making a sort for this `iC`, this `Z3.Error("invalid argument")` will occur.
if you uncomment the `let iS `, the code will work.
From the code, I guess a `decl` depends on its created `sort` in implementation, while in OCaml we have to ensure it by ourselves.

I also made the log following your instructions in the previous reply
[the log gist](https://gist.github.com/arbipher/9900c859798ce08ebf3c6c4a607fa0c1)
the result for the log is
```shell
z3 z3.log                                                                                        19:07:08
[z3 exception]: expecting object at position 1 but got uint64
[z3 exception]: invalid argument reference
[z3 exception]: invalid argument reference
[z3 exception]: invalid argument reference
[z3 exception]: invalid argument reference
[z3 exception]: invalid argument reference
[z3 exception]: invalid argument reference
[z3 exception]: invalid argument reference
[z3 exception]: invalid argument reference
[REPLAYER ERROR HANDLER]: invalid argument
[z3 exception]: invalid argument reference
[z3 exception]: invalid argument reference
max. heap size:     0.392277 Mbytes
time:               0.000923
```

**Comment by arbipher** [comment]
```
let iC = Datatype.mk_constructor_s ctx "Int" (Symbol.mk_string ctx "is-Int") [Symbol.mk_string ctx "i"] [Some iS] [1]
```
I don't know the meaning of the last `1` but I tried 0, 1, 100 and any integer will trigger this bug.

I asked this question on #4264 . I am expecting some developer can explain it when you have time for this issue.
