### ISSUE TITLE
No handling for boolean xor in c++ API

### ISSUE THREAD

**Issue by jakkdu** [Z3Prover/z3#4618]
Hi, all.
First of all, thank you for your great project, z3.
I am currently using z3 with c++ api and realized that z3++ has no support for boolean xor.

Here is my simple code, which is tested in the latest commit `7ae706844d0bd1b47351bb1d90e8d87265f4494a`.
```c++
#include <z3++.h>
using namespace z3;

int main() {
  context c;
  expr a = c.bool_val(false);
  expr b = c.bool_val(true);
  std::cout << (a ^ b) << "\n";
}
```

```bash
$ ./bool-xor
null
```

This is because current [`z3::expr::operator^`](https://github.com/Z3Prover/z3/blob/master/src/api/c%2B%2B/z3%2B%2B.h#L1679) is built with assumption that given z3::expr is bitvector.
I think we need to consider other cases including boolean (e.g., by adding assertion).

More seriously, there is no way to handle boolean xor with c++ api.
To. do that, we need to use c api.
I think it is better to add c++ api to handle boolean xor.

Largely, I think there are two ways to handle this.
First, we can make `operator^` as polymorphic, so that it can handle boolean cases similar to other operator.
Second, we can introduce dedicated api for boolean xor, e.g., z3::xor.
This is consistent to Python API, which has a dedicated function `Xor` for boolean xor. 
I don't know which one is more preferable to z3's API design philosophy.

Best,
Insu Yun.

**Comment by NikolajBjorner** [comment]
The ^ operator is now overloaded to also Booleans. Some other bit-wise operators are also overloaded now to make it more lenient on users of the C++ API.
