### ISSUE TITLE
Soundness issue in NRA with rewriter.flat=false

### ISSUE THREAD

**Issue by wolffdy** [Z3Prover/z3#4622]
Hi! I found a formula that triggers a soundness bug in Z3 with the rewriter.flat=false option:

```
% z3 bug.smt2
sat
% z3 rewriter.flat=false bug.smt2
unsat
% cat bug.smt2
(set-logic NRA)
(declare-fun a () Real)
(declare-fun b () Real)
(declare-fun c () Real)
(declare-fun d () Real)
(declare-fun e () Real)
(assert (not (exists ((f Real)) (let ((?h (+ (* (- b) f) c)) (?i (* (- 11) b)) (?j (+ (* (- b) e) c)) (?k 0)) (=> (= (<= 3 f e) (>= ?h 10 ?h d)) (>= c a (/ c ?i)) (> b 0.0) (or (< a 0) (> a (/ (* ?j ?j) ?i))))))))
(check-sat)
```
I plugged the model emitted by Z3 without any additional arguments (along with the formula itself) into CVC4 and it reports SAT as well, so it appears that this formula should, indeed, be SAT. 

This does look similar to some of the comments in https://github.com/Z3Prover/z3/issues/4532, but it looked to me like those were mostly resolved aside from performance regressions (?) so I created a new issue.

Verified on master, commit: 1f48eab
OS: Debian GNU/Linux 10 (buster) x86_64

**Comment by NikolajBjorner** [comment]
This shares a root cause with an old issue #2650
