### ISSUE TITLE
Bug: if (C){...} else if (C) {} pattern is found. The second one cannot be reached.

### ISSUE THREAD

**Issue by ustchcs-bugfinder** [Z3Prover/z3#4625]
https://github.com/Z3Prover/z3/blob/7fc4653e4783db45c862979154ccf383d267ef47/src/smt/theory_str_regex.cpp#L842

``` cpp
        } else if (u.re.is_range(re)) {
            return true;
        } else if (u.re.is_full_char(re)) {
            return true;
        } else if (u.re.is_full_seq(re)) {
            return true;
        } else if (u.re.is_complement(re)) { // line 842
            // TODO can we do better?
            return false;
        } else if (u.re.is_intersection(re)) {
            return false;
        } else if (u.re.is_complement(re)) {    // Same as the condition on line 842
            return false;
        } 
```
Reported by: USTCHCS Analysis Toolsuite Bugfinder
(bugfinder-2.3:  The use of if (C) {…} else if (C) {…} pattern should not be used.)

**Comment by mtrberzi** [comment]
Opened #4629 

@ustchcs-bugfinder may we have some more information about your tool please and how to contact the authors?

**Comment by ustchcs-bugfinder** [comment]
> Opened #4629
> 
> @ustchcs-bugfinder may we have some more information about your tool please and how to contact the authors?

Hi, mtrberzi.  We are a startup company with a team from Software Safety Lab. University of Science and Technology of China. So our tool is quite "new". But we are glad you are interested in the result our tool reported.

Last week, we did an analysis on LLVM/Clang code. Here is a [bug list ](https://bugs.llvm.org/buglist.cgi?f1=reporter&o1=equals&v1=%25user%25&list_id=194878) we reported.
