### ISSUE TITLE
Inconsistent preprocessor defines between the Makefile and Visual Studio builds

### ISSUE THREAD

**Issue by delcypher** [Z3Prover/z3#463]
Looking at the Python build system the following defines look suspicious to me

For Debug builds:

```
/D _DEBUG
```

It looks like Visual Studio gets this define but gcc does not get this define

For Release

```
/D NDEBUG
/D _EXTERNAL_RELEASE
/D _LIB
/D _UNICODE
/D UNICODE
```

Visual Studio gets these defines but gcc does not get any of these defines.

Is this intentional?

I discovered this whilst implementing #461 and I wasn't sure how to resolve this.

**Comment by NikolajBjorner** [comment]
The flag Z3DEBUG controls Z3 code debug behavior. AFAIK, this is the same across platforms, also according to mk_util.py. 
The _EXTERNAL_RELEASE would be nice to deprecate (one option less). It is currently used to hide auxiliary features that have only specialized use.

**Comment by delcypher** [comment]
@NikolajBjorner 
> The flag Z3DEBUG controls Z3 code debug behavior. AFAIK, this is the same across platforms

Yes ``Z3DEBUG`` is applied consistently across platforms but that is not the define I was talking about. The main one I was concerned about was ``_DEBUG`` which is not consistently applied.

**Comment by NikolajBjorner** [comment]
The _DEBUG option should not be used in Z3. It is a bug the places it is used and I will fix this.
The reason to use_DEBUG is https://msdn.microsoft.com/en-us/library/0b98s6w8.aspx. Maybe it is redundant when adding the other options

**Comment by NikolajBjorner** [comment]
fix 6cf76f2113b5ea8442156c3e4097f378f82446a5 replaces references to _DEBUG by Z3DEBUG

**Comment by delcypher** [comment]
@NikolajBjorner 
Thanks. Some comments about that commit (6cf76f2)

* There seem to be some unrelated changes in ``src/math/automata/symbolic_automata_def.h``
* Now that you have removed the call to ``memory::deallocate(__FILE__, __LINE__, this);`` doesn't that make the declaration dead code?

**Comment by wintersteiger** [comment]
That may have been a mistake: @NikolajBjorner did you intend to remove the call to the debug-deallocate with __FILE__, __LINE__?

**Comment by NikolajBjorner** [comment]
yes, it was used for debugging at some point in the past.
keep the declaration around if need be at some point later (dead today != dead tomorrow).

**Comment by wintersteiger** [comment]
This looks fixed to me, can we close this issue?

**Comment by delcypher** [comment]
@wintersteiger The issue with not applying ``_DEBUG`` consistently has been fixed but it looks like my concern about the other defines, i.e. 

```
/D NDEBUG
/D _EXTERNAL_RELEASE
/D _LIB
/D _UNICODE
/D UNICODE
```

are still there.

**Comment by wintersteiger** [comment]
This is now fixed, I added NDEBUG and _EXTERNAL_RELEASE for non-Windows platforms as well. _LIB, UNICODE, and _UNICODE are among the default defines for unicode-enabled Windows libraries, so those are only needed elsewhere. -D UNICODE also exists on other platforms, but I think we don't build anything unicode-enabled there, so shouldn't be needed.
