### ISSUE TITLE
Performance regression on int2bv of str.len

### ISSUE THREAD

**Issue by krobelus** [Z3Prover/z3#4635]
Hi, thanks for the recent fix!

After upgrading from 4.8.8 to the nightly build I found that one of our instances would time out - reduced example below.
We might be able to work around that by using `bv2int` instead but IIRC we had other issues with that, I'll investigate.

Bisects to 8758baf24e07641e051a277ba5092c3ae2dd7455.
Comparing performance (of a debug build) before and after that commit:

0.150s before
1.140s after

```smt
(declare-const str String)
(declare-const i (_ BitVec 11))
(assert (bvslt i ((_ int2bv 11) (str.len str))))
(check-sat)
```

With a slightly larger bitwidth:

0.2s before
20s  after

```smt
(declare-const str String)
(declare-const i (_ BitVec 16))
(assert (bvslt i ((_ int2bv 16) (str.len str))))
(check-sat)
```

**Comment by NikolajBjorner** [comment]
Is this really with z3str3?

**Comment by krobelus** [comment]
It's not with z3str3, sorry. I can reproduce with z3's default mode, without any arguments.

**Comment by NikolajBjorner** [comment]
This has been fixed.

**Comment by krobelus** [comment]
Just for the curious: this regressed in 4.8.10 but is fixed again in latest master by 8fde6c207dfa696b0d170f8bc55cb64209436d27 which makes `unicode=true` the default.

**Comment by NikolajBjorner** [comment]
I don't have the commit id from the fix to this. The move to unicode had two components: change the semantics of characters, change the underlying decision procedure for characters. The underlying decision procedure for characters had some influence on regressions. As these have been fixed there is also no need to maintain the old encoding of ascii characters to 8-bit bit vectors. Even ascii encodings use the new decision procedure for characters.

**Comment by zimmski** [comment]
@NikolajBjorner Talked to @krobelus about this. We are currently in the process of switching to Z 4.8.11 and i think this issue needs to be reopened or i found another problem. There seems to be some strangeness regarding "str.len".

When you take the above formula (i changed the name "str" to "x" to make it more readable at least for me) and add a constraint on "str.len" to it, even a simple one, the formula takes a lot longer. The following formula takes 0m17.038s

```
(set-option :produce-models true)
(declare-const x String)
(declare-const i (_ BitVec 16))
(assert (>= (str.len x) 0)) ; <-------- remove this and the formula is down to 0m0.077s
(assert (bvslt i ((_ int2bv 16) (str.len x))))
(check-sat)
(get-model)
```

**Comment by NikolajBjorner** [comment]
It's blind search with this combination. You get different runtimes depending on smt.random_seed=<NNN>
both with and without redundant assertion.

**Comment by zimmski** [comment]
You mean combining BitVector with String theory over int2bv? Can you give me some hints to what i need to read/research to better understand how and why this is implemented that way?

What i find odd, i did run the above formula for an hour in a loop, did not hit a ffast case once. When i use smt.random_seed=1 it finishes in 0m0.500s on this machine. I guess that is randomness at its finest ;-)

**Comment by NikolajBjorner** [comment]
The string solver just tries tries different string values even though the length is the only thing important here.
A much better solver for this exact benchmark and others similar is to convert strings into bounded finite size vectors and search for models over these vectors. This is how some string solvers work, but they are more often outperformed by the general solver.

**Comment by krobelus** [comment]
Okay so it looks like the current implementations of the two theories of strings and bitvectors don't interoperate well. We failed to notice the problem earlier because z3 4.8.8 worked well enough for our test cases on with the default random seed.

I wonder if there are use cases where the current implementation of strings+bitvectors works well enough in practice.

**Comment by krobelus** [comment]
If not - would it make sense to print a warning when there is a combination like `(int2b (str.len x))` that leads to blind search?
That could help the next user.
