### ISSUE TITLE
Ambiguous functions in C++ API

### ISSUE THREAD

**Issue by mhbackes** [Z3Prover/z3#4637]
Something I noticed is that there are some pitfalls in the Z3 C++ API if you are trying to use unsat cores with the `z3::optimize`.

The problem is that [`z3::solver::add(z3::expr const &e, char const *name)`](https://z3prover.github.io/api/html/classz3_1_1solver.html#a3a2b8a57bb513ac9dd3468717d8eda08) adds an assertion to the solver and tracks it with the `name`, while [`z3::optimize::add(z3::expr const &e, char const *weight)`](https://z3prover.github.io/api/html/classz3_1_1optimize.html#a3d132b5f9c469c564ad81ecc94e3718f) (which has the same signature) does something completely different. It adds a soft constraint with weight `weight` converted to a number.

My suggestion is, if possible, to separate `z3::optimize` functions into [`add()`](https://z3prover.github.io/api/html/classz3py_1_1_optimize.html#a5e8e9fe9712130721a0e3f9b2fc950e9) and [`add_soft()`](https://z3prover.github.io/api/html/classz3py_1_1_optimize.html#a081f3314ee984f879c8e9b543126fbb6) or [`assert_and_track()`](https://z3prover.github.io/api/html/classz3py_1_1_optimize.html#ad1255f8f9ba8926bb04e1e2ab38c8c15), just like it was done in the python API.

Anyway, thanks for the awesome job you guys did with this solver!

**Comment by NikolajBjorner** [comment]
valid point, add_soft in opt

**Comment by mhbackes** [comment]
Nice.

But would it make sense if a function `void add(expr const & e, char const * p)` was also added to `optimize`, which does exactly the same as their equivalent in `solver` (it calls `assert_and_track()`), so that both `solver` and `optimize` interfaces are consistent?

**Comment by mhbackes** [comment]
Great, thank you!
