### ISSUE TITLE
Help to use

### ISSUE THREAD

**Issue by zsdevX** [Z3Prover/z3#4639]
I have symbol 'x's and after transforming it will generate the result: '3723147309'.
 I run the  code(something wrong), the model() get a wrong result :
```
sat
00000000000000000000000000000001
```
somebody will you please tell me，what's wrong with the code?

```
from z3 import *

x=[ BitVec("x%d"%i, 1) for i in range(32) ]
r=4
magic=32805
p=magic+(1<<r*8)

hlen=lambda x:len(hex(x)[2:].strip('L'))

def HL(num):
    off=0
    i=31
    while True:
        if ((num>>i)&0x1) == 0x1:
            break
        i-=1
        if i == -1:
            break
    off=i+1 
    l = off/4
    if off%4 != 0:
        l+=1
    return l

def M(m):
    r=0
    for i in range(len(m)):
        r += m[i]<<(len(m) - 1-i)
    return r 

def Do(x):
    res=0
    lens=hlen(p)
    m = M(x) 
    for i in x:
        res *=2
        res ^= If(i==1, m, 0)
        lres=HL(res)
        if lens==lres:
            res ^= p
    return res        

s=Solver()    
for i in range(len(x)):
    s.add(Or(x[i] ==0, x[i] ==1))

s.add(Do(x) == 3723147309)

print(s.check())
r=s.model()
for i in range(len(x)):
    print(r[x[i]], end="")
```

**Comment by andrewvaughanj** [comment]
You're treating the symbolic values as "concrete" during encoding your problem.

For example, you're mixing:

```
res ^= If(i==1, m, 0)
```

(which is the correct way to do it!)

with things like:

```
      if lens==lres:
            res ^= p
```

(which is very much *not* the way to do it!)

As I highlighted on your other issue (#4576), you need to be working with all of these terms symbolically -- your implementation of `HL` works on the Z3 datatype of `BitVec`, but doesn't actually encode your problem into SMT.

See here:

- https://stackoverflow.com/questions/46905254/how-to-solve-this-using-z3

for a concrete way to encode these kind of problems.
