### ISSUE TITLE
unknown function/constant

### ISSUE THREAD

**Issue by dah-fari7009** [Z3Prover/z3#4644]
Hi,
When I try running z3 from the terminal (Ubuntu), on the following example, I get as a result:
(error "line 7 column 917: unknown function/constant sqrt")
(error "line 8 column 925: unknown function/constant sqrt")
sat

However, the sqrt function is defined, and when I run the same example with the online solver at https://rise4fun.com/z3, I get the correct result which is "unsat"

Do you have any idea what could be causing this behavior ?

[InewVImpToSolve.txt](https://github.com/Z3Prover/z3/files/5087681/InewVImpToSolve.txt)

**Comment by NikolajBjorner** [comment]
the current builds seem to not have the problem you mention. Tested on ubuntu and windows.
