### ISSUE TITLE
Bug: stack variable address escaping ？

### ISSUE THREAD

**Issue by ustchcs-bugfinder** [Z3Prover/z3#4645]
https://github.com/Z3Prover/z3/blob/c13e3ce693e9a57a16d747b1fec40fd46d20b8d9/src/shell/dimacs_frontend.cpp#L232

https://github.com/Z3Prover/z3/blob/c13e3ce693e9a57a16d747b1fec40fd46d20b8d9/src/shell/dimacs_frontend.cpp#L255

```cpp
unsigned read_dimacs(char const * file_name) {
    g_start_time = clock();
    register_on_timeout_proc(on_timeout);
    signal(SIGINT, on_ctrl_c);
    params_ref p = gparams::get_module("sat");
    params_ref par = gparams::get_module("parallel");
    p.set_bool("produce_models", true);
    p.set_bool("cardinality.solver", false);
    sat_params sp(p);
    reslimit limit;
    sat::solver solver(p, limit);     //local variable
    g_solver = &solver;              // assign local address to global variable, but without reset g_solver to nullptr before return
```

Reported by: USTCHCS Analysis Toolsuite Bugfinder
(bugfinder-11.2: Pointer or reference of local variables should not be returned or assigned to out-paramters, global variables.)

**Comment by NikolajBjorner** [comment]
this is in main(), the process exits. won't fix.
