### ISSUE TITLE
Bug: avoid doing equality comparisons between floating expressions.

### ISSUE THREAD

**Issue by ustchcs-bugfinder** [Z3Prover/z3#4646]
https://github.com/Z3Prover/z3/blob/c13e3ce693e9a57a16d747b1fec40fd46d20b8d9/src/smt/qi_queue.cpp#L159
https://github.com/Z3Prover/z3/blob/c13e3ce693e9a57a16d747b1fec40fd46d20b8d9/src/smt/qi_queue.cpp#L383
https://github.com/Z3Prover/z3/blob/c13e3ce693e9a57a16d747b1fec40fd46d20b8d9/src/smt/qi_queue.cpp#L393
https://github.com/Z3Prover/z3/blob/c13e3ce693e9a57a16d747b1fec40fd46d20b8d9/src/smt/qi_queue.cpp#L409

https://github.com/Z3Prover/z3/blob/c13e3ce693e9a57a16d747b1fec40fd46d20b8d9/src/solver/solver_pool.cpp#L167
https://github.com/Z3Prover/z3/blob/c13e3ce693e9a57a16d747b1fec40fd46d20b8d9/src/solver/solver_pool.cpp#L207

Reported by: USTCHCS Analysis Toolsuite Bugfinder
(bugfinder-5.15: Avoid doing equality comparisons between floating expressions.)

**Comment by NikolajBjorner** [comment]
this is a won't fix.
