### ISSUE TITLE
Different (valid) results depending on usage of bitvectors vs integers with "str.len" and "smt.arith.solver=6" on 4.8.8 and never-finishes on nightly build

### ISSUE THREAD

**Issue by zimmski** [Z3Prover/z3#4649]
Sorry for the long title, i thought it makes it clearer that this is both inconsistent and a regression.

The following formula:
```smtlib
(declare-const x String)
(assert (bvsge ((_ int2bv 64) (str.len x)) #x0000000000000000))
(check-sat)
(get-model)
```

Gives the following output on 4.8.8 with the defaults:
```
sat
(model 
  (define-fun x () String
    "")
)
```

But with `smt.arith.solver=6`:
```
sat
(model 
  (define-fun x () String
    "\x00")
)
```

I thought that is interesting and was wondering what the current nightly does with it: it does not finish.  `smt.arith.solver=6` does not help.

**Comment by NikolajBjorner** [comment]
it finishes quickly now in both settings.
