### ISSUE TITLE
Z3py generates x <= y instead of x < y for floating-point sorts

### ISSUE THREAD

**Issue by 4tXJ7f** [Z3Prover/z3#465]
```
>>> get_version_string()
'4.4.1'
>>> x = FP('x', Float32())
>>> y = FP('y', Float32())
>>> (x < y).sexpr()
'(fp.leq x y)'
```

**Comment by NikolajBjorner** [comment]
The bug you report is fixed in current master branch. There was a benign documentation bug, however.

**Comment by 4tXJ7f** [comment]
Thanks a lot for the info. I fixed some additional, similar documentation bugs in #466 .
