### ISSUE TITLE
 get none when check == sat

### ISSUE THREAD

**Issue by zlchanger** [Z3Prover/z3#4652]
Why do I get none when check() == sat? How to avoid this problem
`a, b, c = Bools('a b c')
 f = AtLeast(a, b, c, 0)
    s = Solver()
    s.add(f)
    while s.check() == sat:
        print(s.model()[a], s.model()[b], s.model()[c])
        print(s.check())`

results:
None None None
sat
None None None
sat
....

**Comment by andrewvaughanj** [comment]
Try turning on `model_completion`:

```
from z3 import *

a, b, c = Bools("a b c")
f = AtLeast(a, b, c, 0)
s = Solver()
s.add(f)
assert s.check() == sat
m = s.model()
print(m.eval(a, model_completion=True))
print(m.eval(b, model_completion=True))
print(m.eval(c, model_completion=True))
```

Also, your `while` loop doesn't make much sense: you're not changing the assertions in the solver, so continually calling `check()` and `model()` without changing it won't give you any different results.

If you want to enumerate solutions, you need to create a "blocking clause" (which is the negation of the current model) and assert that back:

```
from z3 import *

a, b, c = Bools("a b c")
bools = [a, b, c]
f = AtLeast(a, b, c, 0)
s = Solver()
s.add(f)
while s.check() == sat:
    m = s.model()
    results = [(a_bool, m.eval(a_bool, model_completion=True)) for a_bool in bools]
    print(results)
    blocking_clause = Or([a_bool != val for (a_bool, val) in results])
    s.add(blocking_clause)
```

**Comment by zlchanger** [comment]
thank you
