### ISSUE TITLE
Unknown with: "Reason: Overflow encountered when expanding vector"

### ISSUE THREAD

**Issue by LeventErkok** [Z3Prover/z3#4661]
The following benchmark quickly produces `sat` with z3 compiled on August 11th 2020. But with z3 compiled on August 24th, it runs a long time and eventually produces `unknown` with reason `"Overflow encountered when expanding vector"`.

I'm not sure at which point between Aug 11-Aug 24th introduced this issue, but hopefully it should help you narrow the root cause.

```
(set-option :produce-models true)
(set-logic ALL)
(declare-datatypes ((E 0)) (((A) (B) (C))))
(define-fun E_constrIndex ((x E)) Int
   (ite (= x A) 0 (ite (= x B) 1 2)))
(declare-fun s0 () E)
(assert (forall ((s1 E))
            (let ((s2 (>= (E_constrIndex s0) (E_constrIndex s1))))
            s2)))
(check-sat)
```

**Comment by NikolajBjorner** [comment]
this is fixed
