### ISSUE TITLE
Checking satisfiability when quantifying over non-recursive datatype works, but later trivial (check-sat) doesn't

### ISSUE THREAD

**Issue by Fofeu** [Z3Prover/z3#4664]
Hello,

I have defined a datatype which is a variant of either a pair of Ints or a special value representing "bad values".
This last variant serves mostly to lift partial function to total ones.
```
(declare-datatype Ck
                  ((ck (period Int)
                       (offset Int))
                   (badck)))
```

I want to verify a property over all possible values of that variant. If I directly quantify over all values of that datatype, calling `(check-sat)` terminates (with the right value). However, any later call to `(check-sat)`, even trivial ones, never terminate.

```
(assert (forall ((input-i Ck) (var-x Ck) (v Ck))
                (=>
                 (and
                  (realck input-i)
                  (realck v)
                  (realck var-x)
                  (ck-conf-input-i input-i)
                  (= var-x (pck-up input-i 2))
                  (= v var-x))
                 (precon-pck-up v 5))))
(check-sat)

(push 1)
(declare-const test-i Ck)
(declare-const test-j Ck)
(assert (realck test-i))
(assert (realck test-j))
(check-sat) ;; Never terminates
(pop 1)

```

On the other hand, if I quantify over Integers and construct the values manually, z3 behaves normally and later calls to `(check-sat)` behave as expected. The value `badck` is nether checked in the second case, but `realck` should return `false` for this value anyway.

```
(assert (forall ((input-i-n Int)
                 (input-i-p Int)
                 (var-x-n Int)
                 (var-x-p Int)
                 (v-n Int)
                 (v-p Int))
                (let ( (input-i (ck input-i-n input-i-p))
                       (var-x (ck var-x-n var-x-p))
                       (v (ck v-n v-p))
                       )
                  (=>
                   (and
                    (realck input-i)
                    (realck var-x)
                    (realck v)
                    (ck-conf-input-i input-i)
                    (= var-x (pck-up input-i 2))
                    (= v var-x)
                    )
                   (precon-pck-up v 5)))))

(check-sat)

(push 1)
(declare-const test-i Ck)
(declare-const test-j Ck)
(assert (realck test-i))
(assert (realck test-j))
(check-sat) ;; Terminates
(pop 1)
```
I attached the complete source code. 

Is this an expected behavior ?

[z3-issue.txt](https://github.com/Z3Prover/z3/files/5131187/z3-issue.txt)

**Comment by NikolajBjorner** [comment]
Try the axiom profiler to diagnose runtime behavior. Generally, for formulas mixing uninterpreted functions (including data-type accessor functions), arithmetic, and quantifiers there are no guarantees about convergence.
