### ISSUE TITLE
Recursive datatype T containing (Array Int T) vs List

### ISSUE THREAD

**Issue by leonardoalt** [Z3Prover/z3#4669]
After reading https://stackoverflow.com/questions/9343479/a-datatype-contains-a-set-in-z3, I understand that a recursive datatype `T` containing a Set with domain `T` has fundamental issues. Similarly, an array with domain `T` probably has the same issues. But wouldn't an `(Array Int T)` be ok inside `T`? What's the difference between that and a list?

**Comment by NikolajBjorner** [comment]
The post you refer to is very old. While you can now declare recursive datatypes with arrays using the recursive type in co-variant positions, meaning of a recursive datatype as well-founded is altered: occurs check is not applied to co-variant positions in arrays.  

For differences between (List T), (Seq T), (Array Int T):
- List is an inductive data-type. So a list cannot be contained in itself. 
- The array "store" function has no direct counter-parts in List/Seq.
- Seq supports "random" access at non-negative index, but updates would have to be encoded using concatenations. 
- The quantifier-free array fragment with store/select is decidable, the solver guarantees nothing for an encoding of arrays with sequences.
