### ISSUE TITLE
Question about the schedule of releasing 4.8.9

### ISSUE THREAD

**Issue by jormal** [Z3Prover/z3#4672]
Hi. I'm a user of Z3 OCaml binding.

I had been looking forward to the way of using the recursive function on Z3.
And, I found the issue and commit about #4563.

I wish to use this on my project, so I ask the schedule of releasing version 4.8.9.
Is there anybody who could respond to me?

**Comment by NikolajBjorner** [comment]
I could put an update out in a couple of weeks. There is apparently a regression in consequence finding that uses the SAT solver core (@rainoftime exposed bugs in the version that uses the SMT core). The SAT core based consequence finder is just for finite domain problems (e.g., bit-vectors) and therefore Jack's fuzzing that exercised feature interaction didn't exercise this.

**Comment by jormal** [comment]
> I could put an update out in a couple of weeks. There is apparently a regression in consequence finding that uses the SAT solver core (@rainoftime exposed bugs in the version that uses the SMT core). The SAT core based consequence finder is just for finite domain problems (e.g., bit-vectors) and therefore Jack's fuzzing that exercised feature interaction didn't exercise this.

Thx for answering to me. I'll wait for it.
