### ISSUE TITLE
Generating random solutions with uniform distribution

### ISSUE THREAD

**Issue by leafwaltz** [Z3Prover/z3#4675]
Now i just have code like this:
`z3::context c;
c.set("auto_config", false);
c.set("smt.phase_selection", 5);
c.set("smt.random_seed", 123456);

//two bit vectors
z3::expr x = c.bv_const("x", 48);
z3::expr y = c.bv_const("y", 48);

z3::solver s(c);

//add constraints
s.add(x == 0b1101);
s.add(y < x);

//s.push(); //there is a SO answer said to use this function, the solutions 
                 //is limited randomized but not with uniform distribution

assert (s.check() == z3::sat);
std::cout << s.get_model() << std::endl;`

I want to get random solutions of 'y' value with uniform distribution, but the solutions tend to be a fixed sequence, so is there any way to help me? I will be very grateful to you if you can provide me a cpp example.

**Comment by NikolajBjorner** [comment]
Maybe try throwing in some random parity constraints as suggested for approximate model counting.
Here is a poor-man's version. 

```
from z3 import *
from random import *

x, y = BitVecs('x y', 48)

s = Solver()
s.add(x == 13)
s.add(y < x)

bits = [Extract(i,i,x) == 1 for i in range(48)] + [Extract(i,i,y) == 1 for i in range(48)]

rand = random()
while True:
    s.push()
    rounds = 3
    for x in range(rounds):
        trials = 10
        fml = BoolVal(randrange(0,2))
        for i in range(trials):
            fml = Xor(fml, bits[randrange(0,len(bits))])
        s.add(fml)
    if s.check() == sat:
        print(s.model())
    s.pop()
```

**Comment by leafwaltz** [comment]
> Maybe try throwing in some random parity constraints as suggested for approximate model counting.
> Here is a poor-man's version.
> 
> ```
> from z3 import *
> from random import *
> 
> x, y = BitVecs('x y', 48)
> 
> s = Solver()
> s.add(x == 13)
> s.add(y < x)
> 
> bits = [Extract(i,i,x) == 1 for i in range(48)] + [Extract(i,i,y) == 1 for i in range(48)]
> 
> rand = random()
> while True:
>     s.push()
>     rounds = 3
>     for x in range(rounds):
>         trials = 10
>         fml = BoolVal(randrange(0,2))
>         for i in range(trials):
>             fml = Xor(fml, bits[randrange(0,len(bits))])
>         s.add(fml)
>     if s.check() == sat:
>         print(s.model())
>     s.pop()
> ```

Well, I'm sorry but I tried your code and resized the bitvecs to 4 bits, but it seems like I got wrong solution, here is my version:
`import z3
from random import *

x = z3.BitVec('x', 4)
y = z3.BitVec('y', 4)

s = z3.Solver()
s.add(x == 13)
s.add(y < x)

bits = [z3.Extract(i,i,x) == 1 for i in range(4)] + [z3.Extract(i,i,y) == 1 for i in range(4)]

counter = {}

rand = random()
for i in range(1000):
    s.push()
    rounds = 3
    for x in range(rounds):
        trials = 2
        fml = z3.BoolVal(randrange(0,2))
        for i in range(trials):
            fml = z3.Xor(fml, bits[randrange(0,len(bits))])
        s.add(fml)
    if s.check() == z3.sat:
        val = bin(int(str(s.model().eval(y))))

        if val in counter.keys():
            counter[val] += 1
        else:
            counter[val] = 1
    s.pop()

print(counter)`

and I got output: `{'0b1001': 82, '0b1000': 89, '0b1011': 40, '0b1010': 63, '0b1100': 67}`

did I make something wrong?

**Comment by NikolajBjorner** [comment]
comparison is signed. If you print the bit-vectors of both x and y and take their two's complement values you will see the results are right (13 in base 4 is not 13).

**Comment by leafwaltz** [comment]
> comparison is signed. If you print the bit-vectors of both x and y and take their two's complement values you will see the results are right (13 in base 4 is not 13).

emmm... since I am a rookie of z3, could you please show me an example how to do this? I want to know which api should I use to take the bit-vectors' complement values, thanks a lot. I tried in python but it seems like the 'eval()' function returns an integer not a bit-vector , not same as it does in cpp api.

**Comment by wintersteiger** [comment]
What @NikolajBjorner meant to say is that 13 is not a signed 4-bit number; the bit-pattern is `1101`, which (in [2's complement](https://en.wikipedia.org/wiki/Two%27s_complement)) is -3. The comparison operator has the semantics for signed bit-vectors.

**Comment by leafwaltz** [comment]
> What @NikolajBjorner meant to say is that 13 is not a signed 4-bit number; the bit-pattern is `1101`, which (in [2's complement](https://en.wikipedia.org/wiki/Two%27s_complement)) is -3. The comparison operator has the semantics for signed bit-vectors.



> comparison is signed. If you print the bit-vectors of both x and y and take their two's complement values you will see the results are right (13 in base 4 is not 13).

Well now I understand what you mean, thanks a lot all of you!
