### ISSUE TITLE
sometimes execution returns error, sometimes not

### ISSUE THREAD

**Issue by lburdy** [Z3Prover/z3#4677]
When executing z3 multiple times on the same file, sometimes some errors are returned sometimes not.
For example, on the attached file ([00418.smt.zip](https://github.com/Z3Prover/z3/files/5181633/00418.smt.zip)), (error "line 1407 column 8: canceled") can appear during some executions but not always.
I also join 2 outputs obtained on 2 executions of the command:
z3 -smt2 -t:10 00418.smt
[outputs.zip](https://github.com/Z3Prover/z3/files/5181640/outputs.zip)

**Comment by NikolajBjorner** [comment]
It returns the error message when cancellation happens during a push. It is then not safe to continue. Your automation would have to recover from this by abandoning the part that depends on the push.
