### ISSUE TITLE
corrupted double-linked list

### ISSUE THREAD

**Issue by kanigsson** [Z3Prover/z3#4680]
Hello Z3 team,

On the attached file [double-linked.smt2.txt](https://github.com/Z3Prover/z3/files/5185723/double-linked.smt2.txt), I get an error/crash from z3 after reporting "timeout":

```
z3 -T:1 double-linked.smt2.txt 
timeout
*** Error in `z3': corrupted double-linked list: 0x000000000366c510 ***
Aborted (core dumped)
```

**Comment by NikolajBjorner** [comment]
The error message "corrupted double-linked list" does not originate from Z3. It is in one of the libraries you use.
Furthermore, the -T option is a "hard" timeout. It invokes asynchronously a procedure that optionally displays statistics (your scenario does not use this) and then calls "exit(0)". It therefore appears more likely to me that we are dealing with an external issue.

**Comment by wintersteiger** [comment]
That message is from glibc which reports that one of its internal lists is corrupted, i.e. some kind of heap corruption going on.

**Comment by kanigsson** [comment]
OK, thanks, this can be closed then I guess.
