### ISSUE TITLE
Unexpected incompleteness in use of sequences in presence of quantifiers

### ISSUE THREAD

**Issue by shazqadeer** [Z3Prover/z3#4686]
[intseq.txt](https://github.com/Z3Prover/z3/files/5211766/intseq.txt)
The attached file contains two VCs, each using theory of sequences and a quantified fact.  Both VCs are expected to be proved valid.  Z3 is able to prove only the first VC valid.  The  issue appears to be that terms involving seq.nth are either not being used as triggers or being used in a very restricted way.

**Comment by shazqadeer** [comment]
Here is a cleaned up version of the second VC from the file I attached:

(set-option :smt.mbqi false)
(declare-fun s () (Seq Int))
(declare-fun x () Int)
(declare-fun y () Int)
(assert (and (<= 0 x) (<= x y) (< y (seq.len s))))
(assert (forall ((i Int) (j Int)) (=> (and (<= 0 i) (<= i j) (< j (seq.len s))) (<= (seq.nth s i) (seq.nth s j)))))
(assert (not (<= (seq.nth s x) (seq.nth s y))))
(check-sat)

Z3 seems to hang on this one (I let it run for about a minute and watched memory consumption go up to 150MB).

**Comment by NikolajBjorner** [comment]
a few things to notice:

- seq.nth is rewritten to (if index-is-in-range-of-sequence seq.nth_i seq.nth_u). 
 This breaks any pattern matching on seq.nth. Replacing seq.nth by mynth deals succeeds quickly to prove unsat. Pattern matching on some other interpreted functions also doesn't work well: for example <= is fragile for similar reasons. 
I therefore can't say it is fair to say it is "unexpected". 

- mbqi is only disabled if you also set smt.auto_config = false.

- you would be able to glean more of what goes on by running with statistics and -v:10. You would then see the rewritten expressions and, without the setting of smt.auto_config to false, you would also see that mbqi is still being used.

**Comment by shazqadeer** [comment]
I didn't know about the rewriting of seq.nth.  Now the behavior makes sense to me.  I interpret your comment about "mynth" as a suggestion to define my own wrapper "mynth" around seq.nth and use terms over "mynth" throughout.  Did I get that right?

**Comment by NikolajBjorner** [comment]
I didn't intend you to decipher any guidance. It is up to you how you want to use features.
But it is correct that using a bridge function restores ematching.
For example, 

```
(set-option :smt.mbqi false)
(declare-fun mynth ((Seq Int) Int) Int)
(declare-fun s () (Seq Int))
(declare-fun x () Int)
(declare-fun y () Int)
(assert (forall ((s (Seq Int)) (i Int)) (= (mynth s i) (seq.nth s i))))
(assert (and (<= 0 x) (<= x y) (< y (seq.len s))))
(assert (forall ((i Int) (j Int)) (=> (and (<= 0 i) (<= i j) (< j (seq.len s))) (<= (mynth s i) (mynth s j)))))
(assert (not (<= (mynth s x) (mynth s y))))
(check-sat)
```

**Comment by shazqadeer** [comment]
Thanks for your comments.  I am making slow progress in understanding whether I can make the SMT sequence theory work for my need which essentially amounts to finite extensional arrays.  Unlike the classical array theory in which arrays are unbounded, I need finite arrays with length function.  For my application, a common reasoning pattern would be that two finite arrays with same length and same elements must be proven to be equal.  For example, one array could have been obtained from another by updating a position but for some reason in the background of the verification condition the updated value is the same as the original value,  and so the array should not have changed. 

Currently, it appears that there is a mismatch between what I need and what works out of the box.  The following VC captures the conundrum.  If I supply the VC as is, MBQI kicks in and Z3 does not return.  If I disable MBQI, I get unknown immediately.

(declare-fun s1 () (Seq Int))
(declare-fun s2 () (Seq Int))
(assert (= (seq.len s1) (seq.len s2)))
(assert (forall ((i Int)) (=> (and (<= 0 i) (< i (seq.len s1))) (= (seq.nth s1 i) (seq.nth s2 i)))))
(assert (not (= s1 s2)))
(check-sat)

**Comment by shazqadeer** [comment]
On a different not, @bkragl and I are puzzled by your comment:
 > mbqi is only disabled if you also set smt.auto_config = false.

When Boogie generates the SMT query, it injects the following option settings by default:
 
(set-option :print-success false)
(set-info :smt-lib-version 2.6)
(set-option :smt.mbqi false)
(set-option :model.compact false)
(set-option :model.v2 true)
(set-option :pp.bv_literals false)

As you can see, smt.auto_config is not being set here.  Only smt.mbqi is set.  We verified that there is a difference in Boogie behavior when smt.mbqi is not set to false in the generated SMT queries.  20 regressions which verify normally with smt.mbqi set to false time out if that option is not set.  So we were wondering if (set-option :smt.mbqi false) is having an effect because of some other option that we are setting.

**Comment by shazqadeer** [comment]
@ajreynol, @barrettcw:  FYI, this thread might be interesting to you.
