### ISSUE TITLE
Combination framework for multiple theories in z3

### ISSUE THREAD

**Issue by skmuduli92** [Z3Prover/z3#4687]
How does z3 combines decision procedures of multiple theories? Does it uses the nelson-oppen framework or it has its own technique? If you could also point me to the locations where it is implemented, that would be great.

Thanks :) ...

**Comment by NikolajBjorner** [comment]
The main engine used by mainstream queries uses a Neslon-Oppen / CDCL(T) integration.
It is here: https://github.com/Z3Prover/z3/tree/master/src/smt

There are some other engines, notably nlsat, that solves non-linear reals. It does not combine other theories.

I am currently re-engineering the main core to a, hopefully, more efficient and arguably much cleaner, integration here: 
https://github.com/Z3Prover/z3/tree/master/src/sat/smt. While this new core is not ready for uses, I would say the more modular structure allows to easier disentangle the modules. It is still a substantial amount of code.
