### ISSUE TITLE
Excluding specific uninterpreted constants from the solution

### ISSUE THREAD

**Issue by fruffy** [Z3Prover/z3#4688]
I was wondering, is there a way to express such a thing as a "don't care" constant in Z3? I would like to exclude certain uninterpreted constants from the solution. They cannot not be a part of it. 
 
Context:  I am currently working on a translation validation project where we need to check inequality between a program before and after modification. These programs may have undefined behavior which should not factor into the equality. We represent programs as data types and we compare each member of the data type. For example we are given an equality like this 

```
mk_program_output(normal_var_1, normal_var_2) !=                                                                                    
mk_program_output(normal_var_1, normal_var_3)  
```
in `z3py`, which should yield a `sat` result because `normal_var_2` can be different from `normal_var_3`.

This inequality check is very efficient. However, there is a catch. The data types may have an "undefined" variable that acts as a "joker" in some sense:
```
mk_program_output(normal_var_1, undefined) !=                                                                                    
mk_program_output(normal_var_1, normal_var_3)  
```
This equation should be `unsat` because `undefined` can **not** be used as part of the solution.

These equality checks have very specific semantics, which lead to a couple of edge cases. I collected some of these cases in a  Python script that illustrates my case.

The current method I use works well enough. I rewrite the left-hand program of the equation and replace all the "tainted" members with a fresh constant. Then I use a `ForAll()` check to make sure that the rewritten uninterpreted constants are excluded from the solution. However, for bigger programs this becomes very slow (particularly the `ForAll` check). Is there any way I could avoid this quantifier and do better with utilities Z3 provides? Ultimately, I want Z3 to only give a solution if the assignment does not use any of the "forbidden" constants. 

[undef_script.py.txt](https://github.com/Z3Prover/z3/files/5217427/undef_script.py.txt)

**Comment by rainoftime** [comment]
If `taints` contain only Boolean variables, e.g., {`x, y`},  then it may help to eliminate quantifiers by expansion, i.e., replace `x, y` with `(x = 0 or x = 1)`, `(y = 0, y = 1)`

**Comment by andrewvaughanj** [comment]
My similar suggestion was going to be just assert that your terms are _not_ your `undefined` value (so rather than `(x = 0 or x = 1)`, write `x != undef`).

**Comment by rainoftime** [comment]
I ported the simple efsmt ("exists-forall" problem) solving algorithm in https://github.com/pysmt/pysmt/blob/master/examples/efsmt.py

~~~~
def efsmt(y, phi, maxloops = None):
    """Solves exists x. forall y. phi(x, y)"""
    vars = get_vars(phi)
    x = [item for item in vars if item not in y]
    esolver = Solver()
    fsolver = Solver()
    if True:
        esolver.add(BoolVal(True))
        loops = 0
        while maxloops is None or loops <= maxloops:
            loops += 1
            eres = esolver.check()
            if eres == unsat: return unsat
            else:
                emodel = esolver.model()
                tau = [emodel.eval(var, True) for var in x]
                for i in range(len(x)):
                    sub_phi = simplify(substitute(phi, (x[i], tau[i])))
                fsolver.add(Not(sub_phi))
                if fsolver.check() == sat:
                    fmodel = fsolver.model()
                    sigma = [fmodel.eval(v, True) for v in y]
                    for j in range(len(y)):
                        sub_phi = simplify(substitute(phi, (y[j], sigma[j])))
                    esolver.add(sub_phi)
                else:
                    return sat # tau is the model?
        return unknown

def test():
    x, y = Reals("x y")
    f_sat = Implies(And(y > 0, y < 10), (y - 2*x < 7))
    print(efsmt([y], f_sat, 100))
~~~~

**Comment by fruffy** [comment]
Great suggestions, thank you. I wrote something based on this (updated script attached).

```Python
for idx, m_before in enumerate(prog_before_children):
    taints = set()
    print("Preprocessing...")
    m_before, _ = substitute_taint(m_before, taints)
    m_after = prog_after_children[idx]
    tv_equiv = m_before != m_after
    for taint in taints:
        if m_before.sort() == taint.sort():
            tv_equiv = z3.And(tv_equiv, m_before != taint)
    # check equivalence of the modified clause
    print("Equation after preprocessing:")
    print(tv_equiv)
    ret = s.check(tv_equiv)
    if ret != z3.unsat:
        print("Yes. Violation holds even when "
              "ignoring undefined behavior!")
        print("Proposed solution: %s" % s.model())
        return ret
print("No. This violation was caused by undefined behavior.")
```

However, there is one case I still have trouble with:

```
mk_program_output(If(undefined, normal_var_1, normal_var_2),
                  normal_var_2) !=
mk_program_output(If(cond, normal_var_1, normal_var_2),
                  normal_var_2)
```
Here `undefined` is in the condition and the result should still be `unsat` because the branches are equal. On the other hand this
```
mk_program_output(If(undefined, normal_var_1, normal_var_2),
                  normal_var_2) !=
mk_program_output(If(cond, normal_var_1 + 1, normal_var_2),
                  normal_var_2)
```
should be `sat` because there is a difference in a branch.
`cond` may be an arbitrarily complex expression so I cannot easily match `undefined` with `cond`  and I also not use expansion I believe. 


[undef_script.py.txt](https://github.com/Z3Prover/z3/files/5217993/undef_script.py.txt)

**Comment by fruffy** [comment]
Thank you @rainoftime  will take a look at this.

**Comment by rainoftime** [comment]
Depending on the type of your queries (e.g., BV, ABV, NRA), maybe another direction is to tunning the tactics for solving the queries.

Of course, it is in general better to only encode quantifier-free queries.

**Comment by rainoftime** [comment]
@fruffy  I updated the code snippet above. （the previous one has flaws）

**Comment by NikolajBjorner** [comment]
I wonder if you could lift all relevant functions, such as

```
def my_propgram_output_lifted(x,y):
     return If(Or(x == undef, y == undef), undef, my_program_output(x,y))
```

and then phrase the problem using the lifted version?

**Comment by fruffy** [comment]
Thanks for the fix @rainoftime. Will let you know once I integrated it with my scripts. 

@NikolajBjorner 
Interesting! I am unsure how I could implement this right now. What would the inequality in https://github.com/Z3Prover/z3/issues/4688#issuecomment-691988649 look like with this model?

**Comment by rainoftime** [comment]
You may also attach some SMT queries (if possible) for which Z3 becomes slow.

**Comment by fruffy** [comment]
Unfortunately, this is difficult because the Z3 expressions I work with are auto-generated. Maybe I can find a way to generate a reproducible slow query. They are normally just very large.
