### ISSUE TITLE
z3 can't solve. Sorts Bool and Int are incompatible

### ISSUE THREAD

**Issue by ckmahshooq** [Z3Prover/z3#4696]
(declare-const dPL Bool)
(declare-const mz Bool)
(declare-const bd Bool)
(declare-const mzL Bool)
(assert 
  (ite dPL (=> dPL (=> (or mz mzL) bd)) 0)
)
(check-sat)
(get-model)

**Comment by bohlender** [comment]
The error is fine: Both "branches" of the `ite`-expression must evaluate to the same type.

In your example `(=> dPL (=> (or mz mzL) bd))` is a Boolean but `0` is an integer. In case you used `0` to represent `false`, changing `0` to `false` will indeed fix the error.
