### ISSUE TITLE
Assertion Violation with Z3 4.8.9 on macOS Catalina for model extraction

### ISSUE THREAD

**Issue by leuschel** [Z3Prover/z3#4699]
I have just received this assertion violation on MacOS Catalina with Z3 4.8.9:
```
:z3-version
Z3 version is 4.8.9.0
:z3 x=2
ASSERTION VIOLATION
File: ../src/api/api_ast.cpp
Line: 906
UNREACHABLE CODE WAS REACHED.
Z3 4.8.9.0
Please file an issue with this message and more detail about how you encountered it at https://github.com/Z3Prover/z3/issues/new
```

We use the Z3 API from C++. I was investigating the issue that with version 4.8.8 and 4.8.9 the model extraction sometimes no longer worked on Mac. E.g., for a constraint like z=2 (in our source language), get_model().eval(x) would return the name of the identifier ("z") rather than a value (2), which our tool interpreted as no constraint being attached to z. The issue was not present under Linux and version 4.8.7 on Mac also still worked. When now testing this on macOS Catalina rather than Mojave this assertion violation appeared, which I suspect could be linked to our problem with get_model().eval.

```
static context* c;
static solver* smtt;
...
    static unordered_map<SP_integer, expr> *id_table;
...
           expr x = id_table->at(spexpr);
            expr model = smtt->get_model().eval(x);
            return SP_atom_from_string(out.str().c_str());
```

Here are  few more diagnostics of our tool (ProB, where there is an optional Z3 backend to solve constraints in the B language) where you can see the SMTLib being sent to Z3:
```
z3: called mk_var(integer,x,2)
z3: called mk_int_const(2,3)
z3: called mk_op(equal,2,3,4)
Sending to z3: x = 2
; Z3 Solver Store (SMT2 format):
; 
(set-info :status unknown)
(declare-fun x () Int)
(assert
(= x 2))
(check-sat)

; Context
0x7ffdc2601e40
z3: called query(4,2500,sat)
ASSERTION VIOLATION
File: ../src/api/api_ast.cpp
Line: 906
UNREACHABLE CODE WAS REACHED.
Z3 4.8.9.0
```

**Comment by NikolajBjorner** [comment]
The location of the crash is where it queries the print-mode. 
Check for stale libraries of z3 that link with your code.

x should evaluate to 2, yes. But generally, you have to set model-completion to true to ensure that you get integer values for every variable. If a variable is a don't care, z3 may choose to not assign it any value in the model object. The requirement is that the formula evaluates to true under the returned model, not that every sub-formula in the constraint evaluates to a value.
For example, for the formula (or (= x 2) (= y 4)) it is legal to produce a model y = 4, but not mention x.

**Comment by leuschel** [comment]
Thanks, I will investigate libraries on the Catalina system for the crash.
Concerning the model issue: if I set model-completion to true (on macOS Mojave) I get the solution x=0 for the constraint x=2. I will try to create a minimal C++ example to reproduce the issue. The issue with the model value also seems to be there on Linux (Ubuntu) in version 4.8.9 of Z3.

**Comment by leuschel** [comment]
On macOS Catalina the crash is linked during an illegal call to Z3_set_ast_print_mode with a value of 3 for the mode argument.
Our code looks like this:
```
        c = new context();
        smtt = new solver(*c);
```
The call to new context() seems to call Z3_set_error_handler and then Z3_set_ast_print_mode with the illegal value of 3.
This order of calls seems to correspond what I found at lines 163 in src/api/c++/z3++.h
```
        void set_context(Z3_context ctx) {
            m_ctx = ctx;
            m_enable_exceptions = true;
            m_rounding_mode = RNA;
            Z3_set_error_handler(m_ctx, 0);
            Z3_set_ast_print_mode(m_ctx, Z3_PRINT_SMTLIB2_COMPLIANT);
        }
```
(However, I do not know how the mixed C++/C interaction in Z3 works and whether this code of set_context in the header file is really executed at runtime. Anyway, instead of calling Z3_set_ast_print_mode with value 2 (Z3_PRINT_SMTLIB2_COMPLIANT) a value of 3 is passed (which then later causes the crash when extracting the model). I still have no idea what causes this. I have done clean builds, ensure that I don't have out-dated header files,...

**Comment by leuschel** [comment]
Ah, the crash has been solved :-) It was due to an old header file in /usr/local/include where the enum Z3_ast_print_mode had one more value. The issue with the model extraction, however, is not resolved yet (just the crash).

**Comment by NikolajBjorner** [comment]
Sorry, I should have been more explicit with describing this common error and saved you some time.

It is very common that users have header files and libraries that are out of sync and it can be tricky to debug 
because the way header files and libraries are picked up depends on path variables.

You are not the first and will not be the last posing such an issue.

**Comment by leuschel** [comment]
In response to the Catalina crash, we know also store a Z3 header version when compiling our Z3-bridge. (It could be a good idea to explicitly put a version number #define in z3++.h.)

Concerning the model evaluation issue, where the constraint x=2 leaves x unassigned, I have managed via bisecting to find out the commit in the Z3 sources which cause the problem in our library. Do you have any idea what could be going on and what we could do to further debug or solve the issue?
```
2d59b81353a54b481935975ab38cfafcbd7108da is the first bad commit
commit 2d59b81353a54b481935975ab38cfafcbd7108da
Author: Nikolaj Bjorner <nbjorner@microsoft.com>
Date:   Wed Feb 5 12:33:42 2020 -0800

    delay evaluation of model, throttle propagation, introduce LUT results into cutset
    
    Signed-off-by: Nikolaj Bjorner <nbjorner@microsoft.com>

 src/math/lp/lar_solver.h       |  2 ++
 src/sat/sat_aig_cuts.cpp       | 12 +++++++
 src/sat/sat_aig_cuts.h         |  1 +
 src/sat/sat_aig_simplifier.cpp |  3 +-
 src/smt/smt_consequences.cpp   |  2 +-
 src/smt/smt_context.cpp        | 75 +++++++++++++++++++++++-------------------
 src/smt/smt_context.h          | 29 +++-------------
 src/smt/smt_kernel.cpp         |  4 +--
 src/smt/smt_kernel.h           |  2 +-
 src/smt/smt_parallel.cpp       |  2 +-
 src/smt/smt_quantifier.cpp     |  6 ++++
 src/smt/smt_quantifier.h       |  1 +
 src/smt/theory_lra.cpp         | 46 +++++++++++++++++---------
 src/util/mpz.cpp               |  9 ++---
 14 files changed, 111 insertions(+), 83 deletions(-)
```

**Comment by leuschel** [comment]
I have added m_context->display(std::cout) in model_generator::mk_values(); This is the output e.g. for the constraint x>2 & x<4  (where the issue also appears and x is unbound). The output seems similar to the constraint x=2 or even when adding additional variables like x>2 & x<5 & z=3:
```
Logical context:
scope-lvl: 0
base-lvl:  0
search-lvl:  0
inconsistent(): 0
m_asserted_formulas.inconsistent(): 0
#1 := true
#2 := false
expression -> bool_var:
(#1 -> true) 
expression -> enode:
(#1 -> e!0) (#2 -> e!1) 
recfun{}
decl2enodes:
hot bool vars:
```
This is what we believe to send to Z3
```
; Z3 Solver Store (SMT2 format):
; 
(set-info :status unknown)
(declare-fun x () Int)
(assert
 (let (($x9 (< x 4)))
 (let (($x7 (> x 2)))
 (and $x7 $x9))))
(check-sat)
```

**Comment by NikolajBjorner** [comment]
The root cause is going to be around pre-processing. There will be a pre-processing step that eliminates the variable that is equated to a constant. The model should include this equation, but apparently doesn't.
Since you are relying on the binary API, the better way to debug this is by using z3's low level logging facility.
The call Z3_open_log (and there are variants in Java/C#) should be used before any other Z3 uses. Then it saves all commands sent to Z3 in a log. The log can be replayed (give it the extension ".log" and z3 will automatically understand that it is a log).
The crash should reproduce on the text file and you can attach the text file to the bug report. In this way it will be possible to understand what is going on.

**Comment by leuschel** [comment]
Here is the log for solving the constraint x>2 & x<4 with version 4.8.9 of Z3

[z3_prob.log](https://github.com/Z3Prover/z3/files/5288333/z3_prob.log)

Here is the replay with Z3, I am not sure what I should be looking for though:
```
$ z3 z3_prob.log -v:100
(smt.collecting-features)
(smt.preprocessing :time 0.00 :before-memory 2.67 :after-memory 2.67)
(smt.simplifying :time 0.00 :before-memory 2.67 :after-memory 2.67)
(combined-solver "using solver 2 (without a timeout)")
(smt.propagate-values)
(smt.nnf-cnf)
(smt.reduce-asserted)
(smt.maximizing-bv-sharing)
(smt.reduce-asserted)
(smt.flatten-clauses)
(smt.simplifier-done)
(smt.preprocessing :time 0.00 :before-memory 2.67 :after-memory 2.67)
(smt.searching)
(smt.final-check "arithmetic")
final-check OPTIMAL
(smt.final-check "array")
(smt.final-check "bit-vector")
(smt.final-check "datatype")
(smt.final-check "recfun")
(smt.final-check "datalog")
(smt.final-check "seq")
(smt.final-check "fpa")
(smt.final-check "unknown")
(smt.stats :restarts     :decisions   :clauses/bin :simplify   :memory)
(smt.stats        :conflicts    :propagations :lemmas  :deletions   )
(smt.stats    0      0      0      0     0/0     0    0    0    2.68)
(smt.stats :time 0.00 :before-memory 2.67 :after-memory 2.68)
max. heap size:     2.70615 Mbytes
time:               0.021618
```

**Comment by leuschel** [comment]
For the constraint x=2 I get the following:
[z3_prob.log](https://github.com/Z3Prover/z3/files/5288347/z3_prob.log)

```
$ z3 z3_prob.log -v:100
(smt.collecting-features)
(smt.preprocessing :time 0.00 :before-memory 2.67 :after-memory 2.67)
(smt.simplifying :time 0.00 :before-memory 2.67 :after-memory 2.67)
(combined-solver "using solver 2 (without a timeout)")
(smt.propagate-values)
(smt.nnf-cnf)
(smt.reduce-asserted)
(smt.maximizing-bv-sharing)
(smt.reduce-asserted)
(smt.flatten-clauses)
(smt.simplifier-done)
(smt.preprocessing :time 0.00 :before-memory 2.67 :after-memory 2.68)
(smt.searching)
merge z 2
(smt.final-check "arithmetic")
final-check UNKNOWN
(smt.final-check "array")
(smt.final-check "bit-vector")
(smt.final-check "datatype")
(smt.final-check "recfun")
(smt.final-check "datalog")
(smt.final-check "seq")
(smt.final-check "fpa")
(smt.final-check "unknown")
(smt.stats :restarts     :decisions   :clauses/bin :simplify   :memory)
(smt.stats        :conflicts    :propagations :lemmas  :deletions   )
(smt.stats    0      0      0      0     0/0     0    0    0    2.68)
(smt.stats :time 0.00 :before-memory 2.68 :after-memory 2.68)
max. heap size:     2.70587 Mbytes
time:               0.011211
```

**Comment by NikolajBjorner** [comment]
Based on the log, you are doing a _pop_ before retrieving the model.
The solver will then not be able to access the state of the satisfiability check.
This is for sure changed behavior, but I would argue it is legal behavior and applications can take it into account. 
Z3 used to compute models after every check and keep them around until new constraints were added, 
but I find it hard to argue that the state after a pop should be considered on par with the state before. 
Model building requires access to all decisions that were made during search so it is not possible to build a model
after a pop.
Furthermore, building models if none were asked for can have significant cost.

**Comment by leuschel** [comment]
Thanks for the feedback! That should hopefully help us fix the issue.

**Comment by Nosferican** [comment]
#4728 Is probably related but it occurs in a Linux cluster. It occurs every so often calls but the same model works fine when restarting the session.
