### ISSUE TITLE
Emitting \u instead of \x and others in string constants

### ISSUE THREAD

**Issue by mtrberzi** [Z3Prover/z3#4708]
I am wondering whether it would be the appropriate time to move toward output compatibility with SMT-LIB 2.6 with respect to string constants. Specifically, whether we should be emitting `\u{##}` escape sequences for non-alphanumeric characters (even ASCII ones) even when Unicode is not being used. The reason I bring this up is because currently, validating Z3's models against another solver, such as CVC4, with very strict SMT-LIB standards compliance is a bit difficult, since the string constants need to be parsed and reinterpreted. Currently, we emit `\x##`, `\n`, and others, which are no longer part of SMT-LIB 2.6. This should be very easy to implement, and could even be under a feature flag for backwards compatibility if we don't want to make it the default (or until the Unicode support is fully added). I would like to add support for this but wanted to mention that I was planning to do so since it would affect the output of both theory_str and theory_seq.

**Comment by rainoftime** [comment]
An interstring instance
~~~~
(set-logic QF_S)
(assert (= "\x4a" "\x4A"))
(check-sat)
~~~~
ostrich and z3 yield sat,
but cvc4 gives unsat.


CVC4 follows the standard literally, and
only accepts the escape sequences "" and \u..., whereas Ostrich and Z3
also support \x... (as common in JavaScript, etc.), and therefore
interpret \x4a and \x4A as the same character.

**Comment by NikolajBjorner** [comment]
It now only emits \u{XYZ}. Other escape emits are deprecated
