### ISSUE TITLE
define-fun - Spacer - C++ API

### ISSUE THREAD

**Issue by leonardoalt** [Z3Prover/z3#4711]
Hi there,
Is there a simple way to add interpreted functions to z3's context, similar to the way those can be added via `define-fun`, via the C++ API? Or is the way to universally quantify the arguments and assert equality of the function?

**Comment by andrewvaughanj** [comment]
See:

- https://github.com/Z3Prover/z3/issues/1598

- https://github.com/Z3Prover/z3/issues/4561

tl;dr: the API doesn't expose `define-fun` because the expected use-case is just to use programatic "expression builders", which generated the expanded definition "in place", without the need for the function definition.

**Comment by leonardoalt** [comment]
Ah right, thanks @andrewvaughanj .

My use case is to define functions that use `forall`, which Spacer doesn't accept inside rules. For example:
- If I use `forall` inside a CHC rule, Spacer will throw.
- If instead I use `forall` inside a `define-fun`, Spacer accepts it and it works fine: https://gist.github.com/leonardoalt/3510bf35157d28d9f5a4d168417cb8a4

However, if I use an expression builder which generates the expanded definition in place, I guess Spacer won't accept that either?

**Comment by leonardoalt** [comment]
Ok I have some more data about what I actually want. I'll open a new issue pointing appropriately at it.
Thanks again @andrewvaughanj

**Comment by andrewvaughanj** [comment]
Hmm, so if you're saying that Spacer works with a `forall` inside of a `define-fun`, but *not* if you "inline" it directly, then I agree you're in a tough spot.

@NikolajBjorner's [comment](https://github.com/Z3Prover/z3/issues/1598#issuecomment-384896485) on that first issue suggests that Z3 should detect that certain `define-fun`s using `forall` should be detected as macros. Maybe your definitions aren't being picked-up as macros like they should be?

**Comment by leonardoalt** [comment]
Yea I actually see different behaviors, so it's hard for me to guess/tell what's happening.
