### ISSUE TITLE
Spacer - `forall` inside rule

### ISSUE THREAD

**Issue by leonardoalt** [Z3Prover/z3#4712]
I'm using CHCs, and a new function I'm trying to develop requires `forall`.
First, here's a summary from the behavior I see currently:

The command line is always
`z3 a.smt2 fp.engine=spacer fp.xform.slice=false fp.xform.inline_linear=false fp.xform.inline_eager=false`

1. https://gist.github.com/leonardoalt/b0e7247ed71e5459b0e3f784bad30d83
This uses `forall` inside a rule. Spacer accepts it and it works for the case where `Error` is unreachable (unsat). Making it reachable (by changing the last constraint), yields:
```
sat
(error "line 50 column 36: spacer: could not validate a proof step")
```

2. If I try the above via the C++ API, I see (and it throws):
`spacer: quantifier in a recursive rule:`

3. https://gist.github.com/leonardoalt/3510bf35157d28d9f5a4d168417cb8a4
This achieves the same as the first item, but using `define-fun` instead of a rule. Here both the `sat` and `unsat` cases work perfectly.

I'm trying to achieve 3 which works perfectly well, but I can't exactly replicate that via the C++ API. I have a sort of expression builder that inlines the function body, but then I end up at 2. I'd be happy already with 1, but there seem to be differences between running via smtlib2 vs C++ API preventing that.

Any hints are very appreciated!

**Comment by agurfinkel** [comment]
Spacer does not support universal quantifiers in rule bodies. 

Old behavior was to ignore the quantifiers and run. This sometimes works. However, this causes problems with fuzzing. 

New behavior is to reject features that are not 100% supported. 

You found a loophole around one such protection. I can look at closing it so that quantifiers in rules are always rejected.

**Comment by leonardoalt** [comment]
Thanks @agurfinkel for the quick response. Ok, I'll stop using quantifiers in rules and go another path.
Please feel free to close the issue.
