### ISSUE TITLE
New error 'push canceled' after upgrading from 4.8.7 to 4.8.9

### ISSUE THREAD

**Issue by maurobringolf** [Z3Prover/z3#4713]
After upgrading to 4.8.9 from 4.8.7, we started getting errors saying `push canceled`. The SMT-LIB files for which this occurs have the following structure ([one concrete example](https://gist.githubusercontent.com/maurobringolf/3608335209004945cb7d1778fcb111bb/raw/f9f796273923fea47c9cabe5a1c83b03af9bcc45/error.smt2)):

```smt2
 ...
; ~100'000 lines of preamble
 ...
(set-option :timeout 100)
(check-sat) ; first check-sat in the file
; unknown
(declare-fun f () T) ; probably irrelevant
(push)
; (error "line x column y: push canceled")
```
## Details

The check-sat result `unknown` is expected and occurs with both versions. There is more code after this error occurs which all works fine with 4.8.7. The *preamble* consists solely of sort and symbol declarations plus many `(assert (forall ...))` (axioms). It describes a heap encoding `h[r : Reference, f : Field]`, but unrolls the (finite) field parameter such that all heap functions and axioms are duplicated per field, e.g.
```smt2
; symbols
(declare-fun lookup_f1 (Heap Ref) T1)
(declare-fun lookup_f2 (Heap Ref) T3)
(declare-fun lookup_f3 (Heap Ref) T3)
...
; axioms
(assert (forall (x Ref) someAxiom_f1(x)))
(assert (forall (x Ref) someAxiom_f2(x)))
(assert (forall (x Ref) someAxiom_f3(x)))
```
and similarly all axioms involving these field-parametrised symbols are also duplicated. The number of symbols is linear in the number of fields, the number of axioms is quadratic. The error only occurs with enough fields to create a preamble of ~70'000 or more lines.

## Manual unrolling of finite parametrization vs. encoding via finite sort

If the sheer size of the preamble is the problem, then we could alternatively encode fields as a finite sort and push the symbol/axiom parametrisation down to Z3 as explicit quantifiers over fields:
```smt2
; symbols
(declare-fun lookup (Field Heap Ref) T1)
; axioms
(assert (forall ((f Field) (x Ref)) someAxiom(f, x)))
```
This would drastically shorten the *preamble* but we are not sure whether this helps since it corresponds to the same logical axioms. Is one of these two encodings generally easier to handle for Z3?

**Comment by NikolajBjorner** [comment]
Both check-sat and push rely on unit propagation. Apparently unit propagation times out. 
It is not safe to use a state where push times out. I can't take unit propagation out of the current core of z3. 
A next version of the core should address this and simply postpone internalization and unit propagations in a lazy way.

At this point you can change the timeout to a very large number before push to make sure it doesn't time out and then you can change the timeout again before the next check-sat.

**Comment by maurobringolf** [comment]
Thank you for the quick reply.
