### ISSUE TITLE
error C2666:'z3::ast_vector_tpl<T>::operator[]': 2 overloads have similar conversions

### ISSUE THREAD

**Issue by laibunizi1022** [Z3Prover/z3#4716]
Hi,

When I used z3 with c++ in Visual Studio 2013, everything worked fine, but the same code in VS 2005 had the following errors:
       "error C2666:'z3::ast_vector_tpl<T>::operator[]': 2 overloads have similar conversions"

Could you please tell me how to solve this problem?

**Comment by NikolajBjorner** [comment]
VS 2005 is not supported.
