### ISSUE TITLE
Array of uninterpreted sorts in QF_AUFBV

### ISSUE THREAD

**Issue by nafur** [Z3Prover/z3#4717]
For `QF_AUFBV`, z3 does not allow arrays with indices and elements of uninterpreted sorts:
```
(set-logic QF_AUFBV)
(declare-sort S1)
(declare-sort S2)
(declare-fun uf4 () (Array S1 S2))
$ z3 test.smt2 
(error "line 4 column 33: logic supports only arrays from bitvectors to bitvectors")
```
For the more restrictive logic `QF_AUF` however, this is apparently supported:
```
(set-logic QF_AUF)
(declare-sort S1)
(declare-sort S2)
(declare-fun uf4 () (Array S1 S2))
$ z3 test.smt2 
unsupported
; ignoring unsupported logic QF_AUF line: 1 position: 1
```

**Comment by NikolajBjorner** [comment]
First time I hear of QF_AUF. The alphabet soup of logics is fine for the most basic combinations, but otherwise it is just overboard and you should avoid setting a logic.
