### ISSUE TITLE
Documentation on the puling of a release branch of z3

### ISSUE THREAD

**Issue by smijolovic** [Z3Prover/z3#4718]
Been trying like mad to pull a specific branch vs pulling master from git for stability purposes.

git clone --branch fails every time. I tried v4.7.9, 4.7.9, z3-4.7.9, z3-z3-4.7.9....no luck.

**Comment by andrewvaughanj** [comment]
You should be able to clone a specific _tag_ like this:

```
git clone git@github.com:Z3Prover/z3.git -b z3-4.8.9
```

where `z3-4.8.9` is one of the tags from here:

- https://github.com/Z3Prover/z3/tags

**Comment by smijolovic** [comment]
This one did the trick...thank you!
git clone https://github.com/Z3Prover/z3.git -b z3-4.8.9

**Comment by smijolovic** [comment]
Closing.
