### ISSUE TITLE
automatically added bounds seemingly ignored

### ISSUE THREAD

**Issue by Adorf** [Z3Prover/z3#472]
When I let Z3 solve the following small problem, I get sat, despite the fact that bounds +-2 were added via add-bounds. It looks as if the bounds were ignored.

Input:
=====

;;;
;;; add-bounds.smt2
;;;
;;; execute with z3 -smt2 add-bounds.smt2 >add-bounds.txt
;;;

;; define a simple CSP with 2 variables
(declare-const x Real)
(declare-const y Real)

(assert (or (< x 0) (< 0 x)))
(assert (or (< y 0) (< 0 y)))
(assert (and (= y (* 3 x)) (= y (+ x 6))))

(check-sat)
(get-model)

(apply add-bounds)

(check-sat)
(get-model)

Output:
======
sat
(model 
  (define-fun y () Real
    9.0)
  (define-fun x () Real
    3.0)
)
(goals
(goal
  (or (< x (to_real 0)) (< (to_real 0) x))
  (or (< y (to_real 0)) (< (to_real 0) y))
  (= y (* (to_real 3) x))
  (= y (+ x (to_real 6)))
  (<= x 2.0)
  (>= x (- 2.0))
  (<= y 2.0)
  (>= y (- 2.0))
  :precision under :depth 1)
)
sat
(model 
  (define-fun y () Real
    9.0)
  (define-fun x () Real
    3.0)
)

**Comment by wintersteiger** [comment]
The "apply" command doesn't change the assertions in the solver, its output is a _set_ of goals in text format, i.e., in general there won't be a single subgoal that could replace the existing set of assertions in the solver. You can still do what you want to do by using the "check-sat-using" command, e.g.,

    (check-sat-using (then add-bounds smt))

which produces

    (tactic-exception "under-approximated goal found to be unsat")
    unknown

**Comment by Adorf** [comment]
Thank you very much. Obviously I misunderstood the effect of the apply.command.
