### ISSUE TITLE
Intriguing behavior from `bvsmul_noovfl`

### ISSUE THREAD

**Issue by alex-ozdemir** [Z3Prover/z3#4726]
Z3 version 4.8.9 states that the following is unsatisfiable:
```
(assert (bvsmul_noovfl #b1001 #b1111))
(check-sat) ; unsat
```
which surprised me. I expected that #b1001 would be interpreted as the number "-7", #b1111 would be interpreted as the number "-1", and their product, "7" would be representable in 4 two's-complement bits as #b0111.

From my limited experimentation, it seems that `bvsmul_noovfl`'s current behavior is equivalent to interpreting the inputs as *unsigned* integers, and asking whether their product fits in the appropriate number of *signed* bits.

Is this intentional, or a bug?

**Comment by alex-ozdemir** [comment]
@mlfbrown

**Comment by NikolajBjorner** [comment]
We use the following definitions:

   - Z3_OP_BSMUL_NO_OVFL: a predicate to check that bit-wise signed multiplication does not overflow.
     Signed multiplication overflows if the operands have the same sign and the result of multiplication
     does not fit within the available bits. \sa Z3_mk_bvmul_no_overflow.

   - Z3_OP_BUMUL_NO_OVFL: check that bit-wise unsigned multiplication does not overflow.
     Unsigned multiplication overflows if the result does not fit within the available bits.
     \sa Z3_mk_bvmul_no_overflow.

   - Z3_OP_BSMUL_NO_UDFL: check that bit-wise signed multiplication does not underflow.
     Signed multiplication underflows if the operands have opposite signs and the result of multiplication
     does not fit within the available bits. Z3_mk_bvmul_no_underflow.


So in your example, the two inputs have the same sign and the output has a different sign.

**Comment by alex-ozdemir** [comment]
Thanks, Nikolaj.

**Comment by LeventErkok** [comment]
@NikolajBjorner 

I'm still a bit confused about this output. So, the result is `-1 * -7 = 7` and it *does* fit in 4 bits just fine. That'd mean `bvsmul_noovfl` predicate should be satisfied since there is no overflow. (Since there is no overflow.) So, the benchmark should be `sat`.

I feel like there's some double-negation going on here, rather puzzling.
