### ISSUE TITLE
MaxSMT Complexity?

### ISSUE THREAD

**Issue by MartinKoelbl** [Z3Prover/z3#4732]
Hello,
This is probably the wrong place but I don't know where to ask.
I try to find a paper or book about the complexity of MaxSMT without quantifiers. More specifically with linear real arithmetic.
Can you give me a hint?
Many thanks!

**Comment by NikolajBjorner** [comment]
While QF_LRA (quantifier-free linear real arithmetic) is in P, you still have clauses in SMT so the complexity is the same as it is for propositional MaxSAT. Garey and Johnson cover also the optimization query complexities. 
For MaxSAT you need a certificate of the satisfying solution and a certificate that there are no other solutions that are better. So you can reduce SAT to checking whether the optimal solution satisfies all clauses and UNSAT to a certificate that there are no solutions satisfying all clauses. Perhaps some special cases when clauses have convex forms (Horn SAT) or 2-SAT with LRA are easier.

**Comment by MartinKoelbl** [comment]
Many thanks for your answer! It was very helpful.
