### ISSUE TITLE
Spacer throws "mbp evaluation was only partial"

### ISSUE THREAD

**Issue by leonardoalt** [Z3Prover/z3#4734]
z3 4.8.9
Input: https://gist.github.com/leonardoalt/48af9d241b22db1358858ae081511ef8
Options: `z3 mbp.smt2 rewriter.pull_cheap_ite=true rlimit=1000000 fp.spacer.q3.use_qgen=true fp.spacer.mbqi=false fp.spacer.ground_pobs=false fp.xform.slice=false fp.xform.inline_linear=false fp.xform.inline_eager=false`

Via the C++ API Spacer throws an exception `mbp evaluation was only partial` (via cli returns `unknown` also with that message).
Is this expected? I would try to improve my queries in that case.

**Comment by hgvk94** [comment]
The issue is with nested arrays. Spacer does not fully support terms of sort `(Array bytes_tuple Int)` where `byte_tuple` itself is a tuple of `(Array Int Int)` and `Int`. Avoiding nested arrays would be a useful simplification to try.

**Comment by leonardoalt** [comment]
Ok, thanks @hgvk94 !
