### ISSUE TITLE
Segfault using Sequences via Java API

### ISSUE THREAD

**Issue by cmur2** [Z3Prover/z3#474]
Hi, using the (admitttedly) unstable support for sequences in Z3 I managed to create a problem that leads to Z3 reproducebly segfaulting when invoked via the Java API (on Linux). This is the problem:

```
(declare-fun name2 () String)
(declare-fun name1 () String)
(declare-fun name3 () String)
(assert (= name1 (str.++ name2 "x")))
(assert (not (= name1 (str.++ name3 "x"))))
```

The segfault trace from Java looks like this:

```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007fb9e73a7e61, pid=25074, tid=140436945458944
#
# JRE version: Java(TM) SE Runtime Environment (8.0-b132) (build 1.8.0-b132)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.0-b70 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# C  [libz3.so+0x5dbe61]  smt::clause** std::__copy_move_backward<false, true, std::random_access_iterator_tag>::__copy_move_b<smt::clause*>(smt::clause* const*, smt::clause* const*, smt::clause**)+0x1e2d1
#
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /home/cn/dev/ma/code/z3test/hs_err_pid25074.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.sun.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
```

The version of Z3 I use is self-compiled from master branch from mid January. Should I update my Z3 first, do you need more information?

**Comment by NikolajBjorner** [comment]
Would you mind updating to the latest? There has been a lot of churn in this code (and I haven't advertised the sequence features loudly so far given the high degree of churn. January is ages ago). To reproduce bugs outside of Java, use the logging infrastructure: you call Z3_open_log, from Java it is Log.open("crash.log"). Then an executable built from the same version should be able to reproduce crashes.

**Comment by cmur2** [comment]
Ah, a recent git version seems to have cleared the problem, thanks! Do you know when will sequence support be part of an official release (or is it already)?

**Comment by NikolajBjorner** [comment]
It is getting there. There are endless options for tuning (negative occurrences of prefix and suffix can be tuned similarly to negative containment is), but functionality wise I am mainly missing handling of regular expression complementation from my work list. That would take some time and is not the first feature request I have seen elsewhere. I should have the online documentation available in the coming days.

**Comment by NikolajBjorner** [comment]
The online documentation I mentioned is now on: http://rise4fun.com/Z3/tutorial/sequences
