### ISSUE TITLE
When I set timeout (with python API), and solv.check() throws an exception

### ISSUE THREAD

**Issue by udaymallappa** [Z3Prover/z3#4742]
I am using python API for z3 solver. The Z3 solver is used as part of some hierarchical code.
When I set timeout, and use solv.check() to validate if the solution is "sat" "unsat" or "unknown", I get an exception ("z3.z3types.Z3Exception: b'maximization suspended')  and my code breaks out. Any way to supress the exception ?

**Comment by nunoplopes** [comment]
Can you give a small example, pls? Timeouts work in general, so we need a short repro. thanks!

**Comment by nunoplopes** [comment]
Ok, please reopen once you have a small repro for us. Thanks!
