### ISSUE TITLE
Reason for missing monoid operations?

### ISSUE THREAD

**Issue by chadbrewbaker** [Z3Prover/z3#475]
Is there any reason why Sum() and Product() was implemented but not Max() or Min()?

They are all monoids. OP_MAX seems like it would be easy to add at the low level.

Use case is I wanted to easily encode graph coloring. Minimize the Max() over the list of vertex colors encoded as non-negative Integers.

**Comment by NikolajBjorner** [comment]
The reason is that you have the "if" operator for these kinds of things.

SMT-LIB:
  (define-fun max ((x Int) (y Int)) Int (if (> x y) x y))))

Python: 
    def max(x,y):
         return If(x > y, x, y)

**Comment by chadbrewbaker** [comment]
Yes, that works for two elements.  How do you get the max over a list of z3 variables? I need a list operation like Sum().

**Comment by NikolajBjorner** [comment]
Sum is over a python list, so write a program that walks over a python list and builds the appropriate term.

**Comment by chadbrewbaker** [comment]
Ok I will look into it again. At first glance the implementation looked like it needed a low level binary operator from z3's C library.

If it works I might make a pull request for generic reductions where you pass in the binary operator.

**Comment by NikolajBjorner** [comment]
Your input and willingness to contribute is very much appreciated. 
Note however that every small feature we add requires additional work down the line. 
For example, the a question might be why the other APIs don't have such a feature.
So sometimes I just abstain from adding features based on an estimate of benefit to many vs. increased entropy.

**Comment by chadbrewbaker** [comment]
In most hardcore number crunching libraries like MPI, reductions are a very common abstraction. Reduce(op, list).

Perhaps z3.contrib.Reduce(op,list). That keeps Python only enhancements from polluting the root z3 namespace. Also would need to add proper tests.

Anyway, I will take a second look to see if it is feasible to do general reductions over lists with user defined binary ops.

**Comment by NikolajBjorner** [comment]
sure:
       from z3 import *
       def zmin(x,y):
             return If(x > y, y, x)

        xyz = Ints('x y z')

       print reduce(zmin, xyz)
