### ISSUE TITLE
z3::sort equality operator

### ISSUE THREAD

**Issue by 3y3p4tch** [Z3Prover/z3#4750]
I am using libz3 and libz3-dev version 4.8.7, and I couldn't find `sort::operator==` so I tried looking at the code, and found this disturbing comment in [z3++.h](https://github.com/Z3Prover/z3/blob/3d37060fa97d25337334b1a0c1afeb3001ccb13c/src/api/c%2B%2B/z3%2B%2B.h#L512)

Lines 511-514 are:
```c++
        /**
           \brief Return true if this sort and \c s are equal.
        */
        sort & operator=(sort const & s) { return static_cast<sort&>(ast::operator=(s)); }
```

I believe that the assignment operator was mistaken to be equality operator. It'd be nice if the comment was corrected.

Also, how can I perform equality check on `sort`? I couldn't find anything on this.

Thanks

**Comment by wintersteiger** [comment]
I think only the comment is wrong. The `sort` object is an `ast` object and `ast::operator=` just overwrites the pointer to the underlying pointer to `ast`. You can check equality by comparing the underlying `Z3_ast` pointers (Z3 uses hash consing, so pointer comparison is works). There are no `operator==`'s it seems though.

**Comment by 3y3p4tch** [comment]
Is it safe to compare pointers? Comparing them seems like an implementation dependent thing, and I am not that sure whether it'll be good in the long run since I am working on a big project.
It'd ease my soul if `operator==` could be provided by z3 implementation itself :P

Also, I found the `sort::id` function, which claims to give me a unique identifier for a sort and I am a bit curious: is it somehow related to the underlying `Z3_ast` pointer?

**Comment by wintersteiger** [comment]
It's safe to compare the _underlying_ AST pointers, which is what `Z3_is_eq_ast` does in

     inline bool eq(ast const & a, ast const & b) { return Z3_is_eq_ast(a.ctx(), a, b) != 0; }

I think this `eq` should work for sorts too. Everything is related to the underlying C API :-) The C++ API is really just a wrapper around the C API which takes care of reference counting for the user, everything else is passed down to C functions.

**Comment by 3y3p4tch** [comment]
Thanks for your insights. I'll close the issue, hoping that the comment will be corrected. :)
