### ISSUE TITLE
Got "unknown" output for provably unsat system

### ISSUE THREAD

**Issue by SlavKing98** [Z3Prover/z3#4752]
I'm not asserting that this is a bug, it is posible that I have misunderstood something. But given the following system:

```
(declare-sort T)
(assert (exists ((x T) (y T)) (not (= x y))))
(assert (forall ((f (Array T (Array T Bool))) (x T))
  (=>
    (forall ((y T) (z T))
      (= (f y z) (not (= y z)))
    )
    (f x x)
  )
))
(check-sat)
```

Z3 outputs "unknown" instead of "unsat". Why exactly is Z3 unable to prove that it is unsatisfiable?

**Comment by rainoftime** [comment]
The first line `(declare-sort T)` seems to be out of the SMTLIB2 standard.
After changing it to `(declare-sort T 0)`, both z3 and cvc4 can return `sat` instantly.

**Comment by SlavKing98** [comment]
> After changing it to `(declare-sort T 0)`, both z3 and cvc4 can return `sat` instantly.

What version are you using? In my version 4.8.9 it still prints `unknown` even with `(declare-sort T 0)`. Also, how can it possibly be `sat`? Unless I'm missing something, the system is unsat. I'm really interested to see what `(get-model)` prints for you.

**Comment by rainoftime** [comment]
My mistake. z3 still yields `unknonw`

**Comment by NikolajBjorner** [comment]
This is outside the scope of current handling of second-order constructs. The formula is somewhat easy to solve if recognizing that the antecedent introduces a definition for f (e.g, it is easy to solve using second-order destructive equality resolution, but z3 doesn't implement this or other mechanisms that are relevant for such formulas).
