### ISSUE TITLE
Z3 does not recognise the QF_UFDT logic

### ISSUE THREAD

**Issue by tic-toc** [Z3Prover/z3#4754]
Hello,

The Z3 solver in version 4.8.9 ignores the command `(set-logic QF_UFDT)` from the following formula, written in the SMT-LIB 2.6 language:
```
(set-logic QF_UFDT)
(declare-datatype Places ((p0) (p1) (p2) (p3) (p4)))
(declare-datatype Units ((u0) (u1) (u2) (u3)))
(declare-fun u (Places) Units)
(assert (or (= (u p0) u0)))
(assert (or (= (u p1) u0) (= (u p1) u1)))
(assert (or (= (u p2) u0) (= (u p2) u1) (= (u p2) u2)))
(assert (distinct (u p1) (u p2)))
(assert (distinct (u p1) (u p3)))
(assert (distinct (u p1) (u p4)))
(assert (distinct (u p2) (u p3)))
(assert (distinct (u p3) (u p4)))
(assert (distinct (u p2) (u p4)))
(check-sat)
```

Before solving the formula, Z3 prints the following warning message:

> unsupported
> ; ignoring unsupported logic QF_UFDT line: 1 position: 1

The CVC4 solver does not have this behaviour. As excepted, it does not reject the command `(set-logic QF_UFDT)` from the formula.

Additionally, if `(set-logic QF_UFDT)` is replaced by `(set-logic QF_DT)`, Z3 accepts the formula, although the QF_DT logic does not support uninterpreted functions. In this situation, CVC4 rejects the formula.

**Comment by andrewvaughanj** [comment]
Not an official answer, but https://github.com/Z3Prover/z3/issues/4717#issuecomment-700882328 might be relevant

**Comment by andrewvaughanj** [comment]
Also, it seems that `QF_DT` implicitly enables `UF` in Z3:

https://github.com/Z3Prover/z3/blob/master/src/solver/smt_logics.cpp#L151

**Comment by tic-toc** [comment]
> Not an official answer, but [#4717 (comment)](https://github.com/Z3Prover/z3/issues/4717#issuecomment-700882328) might be relevant

The wiki of the CVC4 solver mentions explicitly the `QF_UFDT` and the  `QF_DT` logics:
http://cvc4.cs.stanford.edu/wiki/Datatypes

The official SMT-LIB repository also mentions the `UFDT` logic:
https://clc-gitlab.cs.uiowa.edu:2443/SMT-LIB-benchmarks/UFDT

> Also, it seems that `QF_DT` implicitly enables `UF` in Z3:
> 
> https://github.com/Z3Prover/z3/blob/master/src/solver/smt_logics.cpp#L151

The `datatypes` theory is independent from the `uninterpreted functions` theory. Also, on the official SMT-LIB repository, none of the `QF_DT` benchmarks use uninterpreted functions:
https://clc-gitlab.cs.uiowa.edu:2443/SMT-LIB-benchmarks/QF_DT

**Comment by tic-toc** [comment]
If the user sets the command  `(set-logic QF_DT)`, Z3 can select a wider logic, such as  `QF_UFDT`, and this is not an issue.

The issue I am pointing out here is Z3 does not accept the command `(set-logic QF_UFDT)`, although it supports this logic. It can be easily corrected by adding the `QF_UFDT` logic (and also `UFDT` which has the same problem) in the file you mentioned.
This improves the interoperability between CVC4 and Z3.

**Comment by NikolajBjorner** [comment]
I have updated z3 to be more compliant for QF_DT, QF_UFDT. 
Logics are great for SMTLIB benchmark collections, 
though it is not aging as well as the rest of SMTLIB2 and 
I think not well scoped for end-users who should ideally just write 
their formulas without having to figure out if they belong to one category or the other.
It is bound to be somewhat open-ended and have a long tail end of 
not very useful differentiations of logics.
