### ISSUE TITLE
'nmake' is not recognized as an internal or external command [installation problem]

### ISSUE THREAD

**Issue by htethtetoo20** [Z3Prover/z3#4756]
I am starting using Z3 SMT prover and I installed the Z3 on visual studio command prompt.Successfully generated make file but
when I run

cd build
nmake

the following command is found.How can I fix that??Please kindly help me.

'nmake' is not recognized as an internal or external command,
operable program or batch file.

**Comment by wintersteiger** [comment]
What version of Visual Studio are you using? nmake comes with VS 2019, but I guess it could be missing if the C++ component isn't installed.

**Comment by htethtetoo20** [comment]
@wintersteiger  Thank for your reply.I am using 2019 version of visual studio.

**Comment by wintersteiger** [comment]
Then something's wrong with your installation or you're using the wrong command prompt. On my machine, nmake is here: `C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.27.29110\bin\Hostx64\x64\nmake.exe` (which is in the PATH in VS command prompts).

**Comment by NikolajBjorner** [comment]
This is not a z3 bug. There are many articles online that discuss how to trouble-shoot this. They can be found by searching "'nmake' is not recognized as an internal or external command, operable program or batch file."

**Comment by v3ritas1989** [comment]
very funny @NikolajBjorner sadly this is one of the top search results for this terminology! Presumable cause of your stupid comment

**Comment by MAfarrag** [comment]
I had the same issue and found the nmake in the following directory
`C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.41.34120\bin\Hostx64\x64`
inside the MSVC directory i found two versions installed and the only added the latest version to my PATH environment variable

**Comment by jimhatesyou** [comment]
> I had the same issue and found the nmake in the following directory `C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.41.34120\bin\Hostx64\x64` inside the MSVC directory i found two versions installed and the only added the latest version to my PATH environment variable

I have MVS 2022 and i do not have this directory at all i don't even have a 2022 folder within the MVS folder

**Comment by MrLantus** [comment]
> > I had the same issue and found the nmake in the following directory `C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.41.34120\bin\Hostx64\x64` inside the MSVC directory i found two versions installed and the only added the latest version to my PATH environment variable
> 
> I have MVS 2022 and i do not have this directory at all i don't even have a 2022 folder within the MVS folder

same

**Comment by MrLantus** [comment]
ok for me its at C:\Program Files (x86)\Microsoft Visual Studio 8\SDK\v2.0\Bin and C:\Program Files (x86)\Microsoft Visual Studio 8\VC\bin
