### ISSUE TITLE
[Z3py] Splitting fpToFP into multiple functions

### ISSUE THREAD

**Issue by 4tXJ7f** [Z3Prover/z3#476]
I find that the `fpToFP` function in Z3py is impossible to use without looking at the implementation---the docstring does not talk about the different use cases and every use case expects different argument types. I'd like to propose to split it into different functions or to make the conversions member functions of the different sorts. Tangentially related, I'd also like to propose to rename `fpToFPUnsigned` (the only to-floating-point-conversion that is in a separate function now) to `unsignedToFP` or `fpFromUnsigned` because the original name is confusing (at least to me ;) ).
I'd be happy to submit a patch for this but I thought that it'd be a good idea to hear some opinions first.

Thanks a lot.

**Comment by wintersteiger** [comment]
The function names are from the SMT-LIB standard for FP and they are the same in the API, the SMT input, etc, and I'd like to keep that consistency. We can add additional ones though just to provide names for each case.

**Comment by 4tXJ7f** [comment]
Sorry for the late reply. Thanks a lot for your explanation, that makes sense. I extended the docstring of `fpToFP` in #486 .

**Comment by wintersteiger** [comment]
Thanks again for the suggestion, I've now added separate functions with names and signatures that are easier to find/remember (https://github.com/Z3Prover/z3/commit/a94aff23e60fe985fc099d388918ad6f5fba25ff).
