### ISSUE TITLE
Docs do not explain whether a config/context/solver can be moved to a different thread

### ISSUE THREAD

**Issue by Trolldemorted** [Z3Prover/z3#4762]
To my best knowledge, none of the docs mention to what degree z3 objects can be used by different threads. The only (unsatisfying) piece of information I found on stackoverflow was a crystal clear ["it depends with a tendency to no"](https://stackoverflow.com/questions/25542200/multi-threaded-z3), but it is more than 6 years old, so I don't think it it is necessarily still up-to-date (sorry @wintersteiger).

The most important question for me is whether one can safely create and interact with z3 objects in thread A, execute a suitable memory barrier, and then use those objects only in thread B. Your rust bindings currently [forbid this by marking the types as !Send](https://docs.rs/z3/0.6.0/z3/struct.Solver.html#impl-Send), which would be appropriate only if one must not transfer the objects from one thread to another.

This uncertainty is forcing projects which use a worker threadpool to[ manually keep track of everything done with z3 objects, send that track record to the next worker, and create new z3 objects there for every unit of work](https://github.com/rems-project/isla/blob/master/isla-lib/src/smt.rs#L308).

Is z3 still using anything thread-specific (thread local storage,  odd platform APIs) that would make moving objects into other threads unsafe?

**Comment by wintersteiger** [comment]
I'm not up to date with the latest changes, but I suspect nothing fundamental has changed, i.e. strictly one context per thread. Z3 objects (like ASTs) are linked to a specific context and their content must be available inside the respective context when operations on them are performed. You can switch context + all its expressions to a different thread, as long as only one thread operates on them at any given time, but you can't use expressions in combination with a different context than the one you created the expression in. For that reason, there is `Z3_translate` which translate expressions between contexts; it essentially re-creates a given expression in a different context, i.e. it's small but non-zero cost.

**Comment by Trolldemorted** [comment]
Thanks for the quick response!

>strictly one context per thread

One context per thread or one thread per context? Is one thread not allowed to have more than one context?

>You can switch context + all its expressions to a different thread, as long as only one thread operates on them at any given time

This is great news, let's hope we can express that nicely in rust semantics.

>For that reason, there is Z3_translate which translate expressions between contexts; it essentially re-creates a given expression in a different context, i.e. it's small but non-zero cost.

Is it really small? I assumed it would clone everything in the source context into the destination context, so the cost would depend on the size of the corresponding AST.

**Comment by wintersteiger** [comment]
Yeah, thread per context, of course you can have more than one context per thread. 

`Z3_translate` does exactly what you would expect it to do, so if you build huge expressions it will take lots of time. Most expressions are relatively small though and there is structural sharing, so it won't visit branches more than once.

**Comment by NikolajBjorner** [comment]
The overhead of Z3_translate is essentially linear in the size of expressions accumulated in a context. 
It performs a single pass over all assertions and rebuilds them.

**Comment by Trolldemorted** [comment]
Could you include the thread safety remarks in your C API documentation?
