### ISSUE TITLE
proof regression from 4.8.8

### ISSUE THREAD

**Issue by kanigsson** [Z3Prover/z3#4764]
[mul_lemmas.adb_159_14_postcondition3___00.smt2.txt](https://github.com/Z3Prover/z3/files/5455925/mul_lemmas.adb_159_14_postcondition3___00.smt2.txt)

Thanks again for your help on issue #4746. Here is another VC that isn't proved by 4.8.9 nor current master (07680408a69) but was proved immediately by 4.8.8. The option `smt.q.lift_ite=2` you mentioned in #4746 doesn't seem to help. Could you take a look?

**Comment by NikolajBjorner** [comment]
It is a regression in non-linear solving in the legacy arithmetic solver. I patched the regression, but it was introduced based on debugging a different bug. The new arithmetic solver handles this easily. So consider running z3 also with smt.arith.solver=6 as well.

**Comment by kanigsson** [comment]
Great! I confirm that latest master proves this using `smt.arith.solver=6`.
