### ISSUE TITLE
Support for monotonic theories such as Graphs like Monosat.

### ISSUE THREAD

**Issue by jeremysalwen** [Z3Prover/z3#4766]
https://github.com/sambayless/monosat implements a specialized solver for monotonic theories with support for a variety of graph predicates and geometric predicates, and boasts of dramatically improved performance on these problems.

In [this stack overlow question](https://stackoverflow.com/questions/46508907/smt-solver-with-custom-theories), Nicolaj mentioned that custom theories could be implemented on top of Z3's internal API.  However, I am curious if it would be feasible to implement graph reachability as a Z3 theory in this way.  The Monosat implementation provides a python API similar to Z3, but has special sorts for graphs.  Would it be necessary to add additional sorts to the frontend of Z3 like this, or would it be possible to encode graphs in a reasonable way using existing Z3 sorts and have the theory on the backend just speed up search?

**Comment by NikolajBjorner** [comment]
Section 7 in http://theory.stanford.edu/~nikolaj/z3navigate.html describes a newer facility for supporting user propagators.
Z3 used to expose user theory solvers where users would declare functions and sorts, but this feature didn't support model generation so was eventually retired. However, there are good uses for ad-hoc propagators. The user propagator plugin facility is an attempt to resurrect support for propagators. The idea is to track truth assignments to Boolean atoms or assignments to bit-vectors and perform propagations or flag conflicts in response. 
So your monotone theory, say whether it is graph reachability, can pick up truth assignments that enable edges and weights in a graph and check consistency criteria in response.

**Comment by jeremysalwen** [comment]
Very cool! Is this only supported through the Python API? Are there concerns about performance?

**Comment by NikolajBjorner** [comment]
It is available from C API and exposed over Python and C++. I have not added stubs to dotnet or Java or OCaml, but they would follow a pattern suggested by the Python/C++ wrappers and you are invited to add such stubs for your favorite language. 
Perf: totally depends on use case.
