### ISSUE TITLE
Error for named assertions in incremental mode with version 4.8.9

### ISSUE THREAD

**Issue by alebugariu** [Z3Prover/z3#4767]
For the following example:
```
(declare-fun f (Int) Int)
(declare-fun g (Int) Int)
(declare-fun a () Int)
  (push)
  (declare-fun t () Int)  
  (assert (! (not (= (g (f t)) t)) :named A0))
  (assert (and (or  (= t a)))) 
    (push)
    (check-sat)
    (get-value (a t))
    (pop)
  (pop) 
  (push)  
    (push)  
      (push) 
      (declare-fun t () Int)
      (assert (! (not (= (g (f t)) t)) :named A0))
      (pop)
    (pop)
```
Z3 version 4.8.9 raises an exception: (error "line 17 column 48: invalid named expression, declaration already defined with this name A0"). A0 is previously defined in a different scope. This example works fine with an earlier version (4.8.6).

Thank you for your time.

**Comment by NikolajBjorner** [comment]
Thanks, this is a bug in the release. I have verified that it has already been fixed.

**Comment by NikolajBjorner** [comment]
The nightly builds would contain the fix.
