### ISSUE TITLE
Z3 hangs or crashes with "double free or corruption (!prev)" when running in multiple threads with Python API

### ISSUE THREAD

**Issue by jankopanski** [Z3Prover/z3#4768]
Hi, I am using z3 solver in multiple threads. Each thread creates its own context and runs a solver created from QF_LIA tactic with a timeout of 1000 ms.
The result depends on the z3 version. In version 4.8.9 (installed from pip) it crashes with
```
double free or corruption (!prev)
Aborted (core dumped)
```
I also built z3 4.8.10 from the latest master, and in this case, the code execution hangs and is irresponsive to interrupts (ctrl^C). Build configure command:
```
python scripts/mk_make.py --python --debug --log-sync
```

The structure of my code looks as follows:
```
z3.open_log('z3_log')
...
def check_combination_satisfiability(job_indices):
    ...
    ctx = z3.Context()
    x = [[z3.Int('x_{}_{}'.format(i, j), ctx) for j in range(self.platform.num_burst_buffers)] for i in range(num_jobs)]
    s = z3.Tactic('qflia', ctx=ctx).solver()
    s.set(timeout=1000)
    # N, B, available_burst_buffer are integer arrays
    for i in range(num_jobs):
        for j in range(self.platform.num_burst_buffers):
            s.add(x[i][j] >= 0)
            s.add(x[i][j] <= N[i])
    for i in range(num_jobs):
        s.add(sum(x[i][j] for j in range(self.platform.num_burst_buffers)) == N[i])
    for j in range(self.platform.num_burst_buffers):
        s.add(sum(B[i] * x[i][j] for i in range(num_jobs)) <= available_burst_buffer[j])
    if s.check() == z3.sat:
        m = s.model()
        ...
...
# main loop
for _ in range(window_size):
    ...
    with ThreadPoolExecutor(max_workers=24) as executor:
        results = executor.map(check_combination_satisfiability, open_combinations)
...
```
Despite multithreaded execution, the issue is rather deterministic and for a given z3 version always appears at the same point of execution. For 4.8.9 it appears under heavy utilisation - when many threads running z3 are created.
The full code is available at https://github.com/jankopanski/Burst-Buffer-Scheduling/blob/daee4efb6491e0aef3730e8ac0825c4cbb0257b4/burstbuffer/alloc_only.py#L840
I generated logs for both versions. Both available at 
https://github.com/jankopanski/Burst-Buffer-Scheduling/tree/master/z3_logs

Would you have some ideas on how to fix it?
Best,
Jan

**Comment by NikolajBjorner** [comment]
Seems the bugs are only seen in multi-threaded mode.

Logs don't work from multi-threaded uses so it isn't possible to use logs to create repros for this.
I cloned the repro, but running your script seems to require a number of dependencies (as outlined in README.md) so isn't straight forward (just cloning and typing python alloc_only.py from the shell will not work).

**Comment by jankopanski** [comment]
README is unfortunately outdated at the moment. Basically, docker and virtualenv are the only important dependencies. Please find all steps to reproduce the bug below.
```
git clone https://github.com/jankopanski/Burst-Buffer-Scheduling.git
cd Burst-Buffer-Scheduling
# First create python virtualenv with pypy, z3 4.8.9 and other dependencies. 
./setup_simulator_env.sh
# Run docker with a simulator process. It will download a docker image. Only Linux and macOS supported.
./run_batsim_docker.sh -w workloads/KTH-SP2-1996-2.1-cln-io-aware.json -e output/out --enable-dynamic-jobs --enable-profile-reuse
# Open a second terminal window and run a scheduler process with python. It should download pybatsim submodule with the first run.
cd Burst-Buffer-Scheduling
source sim/bin/activate
./run_pybatsim_git.sh burstbuffer/schedIOAware.py z3_logs/z3_bug_options.json
```
I was running it on a 24 core machine and it was always crashing after about 4 minutes and completion of 459 steps (tqdm). The key parameter is "window_size" in z3_logs/z3_bug_options.json. If the bug is not observed, you may try increasing the window_size.

**Comment by NikolajBjorner** [comment]
It is going to be difficult to make progress on this using such repro steps. One thing that is useful is to be able to attach a debugger and I am not sure how to do this under the environment suggested by the steps (under a docker, etc). 
For separation of front-end and backend behavior one thing to try is to separate the steps of the script into first generating text files, and have a second pass pick up the text files and solve them. Z3 allows to save benchmarks in SMTLIB2 text files. 
A script that uses just text files can be run or reimplemented.
Multi-threading has been reasonably well debugged within Z3. A remaining problem could be that the python API has an unsafety issue. I reviewed the code that you rely on and didn't find such an issue so I am still unsure where to point blame.
