### ISSUE TITLE
get-value with HORN is inconsistent with get-model

### ISSUE THREAD

**Issue by Technius** [Z3Prover/z3#4774]
Using Z3 4.8.9, I'm trying to infer a property with the horn clause solver:
```
(set-logic HORN)

(declare-fun my_prop (Int Int) Bool)
; (define-fun my_prop ((x Int) (y Int)) Bool
;   (<= x y))

(assert (forall ((x Int))
  (=> true (my_prop 0 1))))

(assert (forall ((x Int) (y Int) (z Int))
  (=> (and (my_prop x y) (= z (+ y 1))) (my_prop x z))))

(assert (forall ((x Int) (y Int))
  (=> (and (my_prop x y) (> x y)) false)))

(check-sat)
(get-model)
(get-value (my_prop))
```
but I get different results from `get-model` and `get-value`:
```
sat
(model 
  (define-fun my_prop ((x!0 Int) (x!1 Int)) Bool
    (not (>= (+ x!0 (* (- 1) x!1)) 0)))
)
((my_prop (lambda ((x!1 Int) (x!2 Int)) (not (>= (+ x!2 (* (- 1) x!1)) 0)))))
```
The `my_prop` returned by `get-model` is correct, but the `my_prop` returned by `get-value` has the two arguments swapped in the body.

I was planning on using `get-model` anyways but was surprised to see a difference here; am I doing something wrong or is this a bug?

**Comment by agurfinkel** [comment]
You are the first user of get-value with HORN. This looks like a bug.

**Comment by NikolajBjorner** [comment]
Not sure about this: it doesn't repro. I have likely fixed it recently.
