### ISSUE TITLE
Creating a sort alias in z3py

### ISSUE THREAD

**Issue by murali24adithya** [Z3Prover/z3#4777]
I'm trying to create an integer sort object with an extra tag (a string) on it, which is interpreted as its 'alias'. My application has variables and functions whose signature includes both the aliased integers and 'regular' integers. I would like the solver itself to treat the two sorts both the same: i.e., look for satisfying assignments for expressions of both types from integer domain, but I would like for the Python API to somehow be able to distinguish the two. The following stub shows what I would like:

```
>>> tagged_sort = TaggedIntegerSort() # want to implement TaggedIntegerSort()
>>> a = Int('a')
>>> b = Const('b', tagged_sort)
>>> a == b  # can be combined with integers in assertions
a == b
>>> a == b + 1 # can be operated upon just like integers
a == b + 1
>>> f = Function('f', IntSort(), tagged_sort)
>>> is_tagged_integer_sort(a.sort()) # want to implement is_tagged_integer_sort
False
>>> is_tagged_integer_sort(b.sort())
True
>>> is_tagged_integer_sort(f.range())
True
>>> is_tagged_integer_sort(f.domain(0))
False
```

I have tried to look at the API itself and the various classes, but it looks like all the calls in the stub above eventually go to the automatically generated 'z3core' module, which somehow wrangles the given ast objects so I'm not able to tag the objects at the python API level. For example, this doesn't work:

```
>>> tagged_sort = IntSort()
>>> tagged_sort.__tag__ = 'hello'
>>> a = Const('a', tagged_sort)
>>> hasattr(a.sort(),  '__tag__')
False
```
because the actual SortRef object is not the one passed to Const, it's the ast field. But this doesn't work either:

```
>>> tagged_sort = IntSort()
>>> tagged_sort.ast.__tag__ = 'hello'
>>> a = Const('a', tagged_sort)
>>> hasattr(a.sort().ast,  '__tag__')
False
```
because the Const function calls Z3_mk_const which is in the automatically generated 'z3core' module and that function doesn't preserve the ast object.

How do I achieve what I want?

**Comment by NikolajBjorner** [comment]
I don't think this is supported in a way that you describe. 
Z3 just uses simple sorts and there is only one version of the sort Int.
The python wrapper uses python classes to encapsulate expressions and sorts, so you can create your own sub-classes there, of course. But these sub-classes are not retained in the built-in methods that retrieve sorts from expressions, such as a.sort().

**Comment by murali24adithya** [comment]
Thank you. In general, is it a bad idea to toy with the Context object inside an AstRef? Because it appears that context objects are persistent where the ast object are not, and I could easily subclass Context and add more data fields/functions to it, and then I would essentially have 'annotations' over the AstRef objects accessible from a mutable context that is preserved under function application, expression declaration/construction/deconstruction, etc. Is that something that I can do without messing with the solver's algorithm and performance?
