### ISSUE TITLE
unknown result in underlying C api, but shows correct results somehow without Z3_ast_kind checks in z3::to_expr

### ISSUE THREAD

**Issue by 3y3p4tch** [Z3Prover/z3#4779]
I am trying to convert a floating-point to it's corresponding IEEE754 bit-vector representation (using version 4.8.8, C++ API)
I am trying to run the following example:
```c++
z3::context c;
int32_t fpa_data[2] = {0x000000003fc99999, 0x000000009999999a}; // IEEE representation for 0.2
// concatenate 32-bits to form 64-bit bitvector
z3::expr ieee_bv_repr = z3::shl(c.bv_val(fpa_data[0], 64), 32) + c.bv_val(fpa_data[1], 64);
// get the 64-bit floating point from its IEEE representation
z3::expr temp = z3::to_expr(c, Z3_mk_fpa_to_fp_bv(c, ieee_bv_repr, c.fpa_sort<64>());
// convert the floating point back to its IEEE representation
z3::to_expr(c, Z3_mk_fpa_to_ieee_bv(c, temp));
```

The last line throws assertion error in `z3::to_expr`. On investigating further, I noticed that `Z3_mk_fpa_to_ieee_bv` returned `Z3_UNKNOWN_AST` and hence `z3::to_expr` wasn't able to convert it properly, but when I replaced the last line with `z3::expr(c, Z3_mk_fpa_to_ieee_bv(c, temp))` it worked fine. It had the right `Z3_ast_kind` and representation.

I am unable to understand what is happening...

**Comment by wintersteiger** [comment]
Thanks for the report, there was indeed a problem in `Z3_mk_fpa_to_ieee_bv`; fixed in 372bb4b25afeb3d727060a7063470e4a11b78983.
