### ISSUE TITLE
tactics/tacticals: competitive SMT-solvers working on subgoals?

### ISSUE THREAD

**Issue by Adorf** [Z3Prover/z3#478]
Is there a way to use tactics and tacticals to split a goal into subgoals (e.g. via split-clause), and then let a bunch of SMT-solvers try to solve the subgoals competitively in parallel?

The functionality should be:
- If a solver finds _sat_, the process stops, and _sat_ is returned.
- If all solvers find _unsat_, _unsat_ is returned.
- Otherwise _unknown_ is returned.

The desired functionality is similar to that of the tactical _par-or_, where some tactics operate in parallel, and the first that succeeds wins the game.

**Comment by wintersteiger** [comment]
Yes, that's what the par-then tactic does, for example:

    (declare-const x Bool)
    (declare-const y Bool)
    (assert (or (= x y) (xor x y)))
    (check-sat-using (par-then split-clause smt))
    (get-model)

**Comment by Adorf** [comment]
In the documentation at http://rise4fun.com/Z3/tutorial/strategies I read

(par-then t s) applies t to the input goal and s to every subgoal produced by t in parallel.

I thought that the only difference to

(then t s) 

was that par-then would apply the tactc s concurrently. I did not see a hint that it would stop the operation at some point, or would have the (sat, unsat, unknown) functionality that I described.

Is the documentation just incomplete, or ist it my understanding how strategies work on a sequence of subgoals?

**Comment by wintersteiger** [comment]
Yes, the documentation doesn't list all those details (which is true for all tactics, not just this one). When in doubt, I just look it up in the code, e.g., [here](https://github.com/Z3Prover/z3/blob/master/src/tactic/tactical.cpp#L762) is where the first solver that finds SAT cancels all others, and [here](https://github.com/Z3Prover/z3/blob/master/src/tactic/tactical.cpp#L853) is where it checks whether all subgoals are unsat.

**Comment by Adorf** [comment]
Thank you very much for taking your time. And I think it is great that a statement as simple as

`(check-sat-using (par-then split-clause smt))`

starts a race between the various SMT-solvers.

However, my hypothetical statement

`(check-sat-using (par-then partition smt))`

posted in the issue https://github.com/Z3Prover/z3/issues/469 is wrong then. It would not necessarily solve all components. Instead

`(check-sat-using (then partition smt))`

would have to be used. However that statement would unfortunately not benefit from concurrency.

**Comment by levnach** [comment]
It produced (
   (define-fun y () Bool
-    true)
+    false)
   (define-fun x () Bool
     false)
The repro is flaky.

**Comment by NikolajBjorner** [comment]
This is available via Z3's parallel tacticals: use `par-or` to race tactics (first to succeed wins) and `par-then` to apply a tactic to subgoals in parallel, e.g. `(par-then split-clause smt)`. Closing as answered; please reopen if a specific combinator is missing.
