### ISSUE TITLE
Passing binskim

### ISSUE THREAD

**Issue by FilippoPolo** [Z3Prover/z3#4783]
Hi all,

We are using Z3 through the nuget package, as part of a tool that gets validated by binskim. BinSkim is a tool (produced by Microsoft) that makes sure binaries have been built with all available security features.

Currently, Z3 fails binskim validation, mostly due to not including the PDB for libz3.dll.

Could you start adding the PDB to the nuget release, and make the library pass binskim?

**Comment by NikolajBjorner** [comment]
I believe it would bloat the overall size of the package.

**Comment by FilippoPolo** [comment]
Probably, and I'll understand if the decision is not to include it. Unfortunately, in that case, the only way to automatically verify that the code has been built securely would be to fork and build ourselves.

**Comment by NikolajBjorner** [comment]
Note that the DLL is also ESRP signed, so it seems to be a question about process and policies and not about capabilities.

**Comment by NikolajBjorner** [comment]
For reference, the script that assembles the nuget package is
https://github.com/Z3Prover/z3/blob/master/scripts/mk_nuget_task.py

**Comment by FilippoPolo** [comment]
Thanks. Yes, it's definitely an issue of policies. I'll try to figure out a way around.

**Comment by NikolajBjorner** [comment]
Note that pdb files are published on github with the releases. 
For example, https://github.com/Z3Prover/z3/releases/download/z3-4.8.9/z3-4.8.9-x64-win.zip, 
contains the pdb files that are used for the nuget distribution. 
It is therefore possible to get symbols for releases even though it requires two different downloads.

**Comment by FilippoPolo** [comment]
That may help, thanks.

**Comment by FilippoPolo** [comment]
After resolving the PDB issue, there's still a problem. It appears that libz3 is built without the /guard:cf flag, which mitigates against a class of attacks.

Any chance of toggling this switch on?

**Comment by NikolajBjorner** [comment]
Good catch. This flag was supposed to be turned on in the distribution builds but the scripts were wrong. I am fixing this.

Regarding debug symbols: the right process seems to publish nuget packages with debug symbols separately.
https://docs.microsoft.com/en-us/nuget/create-packages/symbol-packages-snupkg

@ahelwer: would you be able to guide us through how to update the scripts by any chance :-).

**Comment by FilippoPolo** [comment]
Toggling the flag would help us significantly, thanks!

I've just tried using the .DLL from the nuget package with the .PDB from the release zip - this is a solution that could let us keep using the nuget package (which is way more convenient than using the release zip).

Unfortunately, binskim doesn't seem to be able to match the two files. If I use both the .DLL and .PDB from the release zip, it works. Looking at the DLL files with a binary editor, they appear to be slightly different. I think it's just a timestamp, but it seems to be enough to make binskim distrust the PDB.

I guess the release zip and the nuget package are built separately? Could the scripts be tweaked to make it build once, and use the same DLL file for both?

**Comment by ahelwer** [comment]
@FilippoPolo the DLL/PDB mismatch you're talking about is for the latest release, 4.8.9?

**Comment by FilippoPolo** [comment]
Yes. Here is what I did (right now):

I downloaded https://github.com/Z3Prover/z3/releases/download/z3-4.8.9/z3-4.8.9-x64-win.zip
I downloaded https://www.nuget.org/api/v2/package/Microsoft.Z3.x64/4.8.9
I unzipped both, extracting \runtimes\win-x64\native\libz3.dll from the nuget package, and \bin\libz3.dll from the release zip.
I compared them with winmerge, and there are differences.

**Comment by ahelwer** [comment]
It looks like these two DLLs were produced in separate builds (presumably on the same build inputs). It would be nice to have reproducible builds so this doesn't matter, but the timestamp nature of codesigning makes that sort of impossible (but maybe binskim ignores signatures?)

![image](https://user-images.githubusercontent.com/718765/98716919-57ae4680-235a-11eb-8246-23ed1b41ec80.png)

@NikolajBjorner do you perhaps run the release pipeline twice, only publishing a nuget package once you've validated the github binary uploads? Uploading a symbols package seems like the way to go, anyway.

**Comment by NikolajBjorner** [comment]
I had to repeat the release steps (but for the same tag) a couple of times due to issues with the ESRP steps during last release.
Publishing directly to nuget never worked so this step is manual.

**Comment by ahelwer** [comment]
@NikolajBjorner Email me re: the ESRP & nuget upload issues! Might be able to fix them. Will take a look at publishing a symbols package.

**Comment by FilippoPolo** [comment]
I'm still gathering as much information as possible on this, and I stumbled into:

https://docs.microsoft.com/en-us/nuget/create-packages/symbol-packages-snupkg

I assume this is the symbols package feature you refer to? In theory, that (and setting /guard:cf) should be enough to solve the issue. We'd just point binskim to the nuget symbols server.

**Comment by NikolajBjorner** [comment]
guard:cf should be there in next release. It remains to figure out how to create a snupkg package (see also https://github.com/Z3Prover/z3/issues/4783#issuecomment-724260531) in the build process.

**Comment by ahelwer** [comment]
I believe I will have a few hours to look into the snupkg issue on Sunday.

**Comment by NikolajBjorner** [comment]
I have updated Nightly releases with nupkg and snupkg images.
@FilippoPolo, before preparing the next release, could you check if these packages are in the format that would be adequate for your needs?

**Comment by NikolajBjorner** [comment]
4.8.10 was released some days ago.
I can't publish snupkg to nuget.org, but it can be downloaded from the Release link. The binaries are compiled with appropriate flags.
