### ISSUE TITLE
nightly/release builds for ManyLinux

### ISSUE THREAD

**Issue by NikolajBjorner** [Z3Prover/z3#4784]
The nightly/release builds for ManyLinux started failing after Nov 3.
The VM doesn't load GLIBC.
As these builds are likely not accessible to everyone, I am adding the relevant output here.

```
==============================================================================
Task         : Command line
Description  : Run a command line script using Bash on Linux and macOS and cmd.exe on Windows
Version      : 2.177.3
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/command-line
==============================================================================
/__a/externals/node10/bin/node: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.10' not found (required by /__a/externals/node10/bin/node)
/__a/externals/node10/bin/node: /usr/lib64/libstdc++.so.6: version `CXXABI_1.3.3' not found (required by /__a/externals/node10/bin/node)
/__a/externals/node10/bin/node: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.9' not found (required by /__a/externals/node10/bin/node)
/__a/externals/node10/bin/node: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.11' not found (required by /__a/externals/node10/bin/node)
/__a/externals/node10/bin/node: /lib64/libc.so.6: version `GLIBC_2.9' not found (required by /__a/externals/node10/bin/node)
/__a/externals/node10/bin/node: /lib64/libc.so.6: version `GLIBC_2.6' not found (required by /__a/externals/node10/bin/node)
/__a/externals/node10/bin/node: /lib64/libc.so.6: version `GLIBC_2.7' not found (required by /__a/externals/node10/bin/node)
##[error]Exit code 1 returned from process: file name '/usr/bin/docker', arguments 'exec -i -u 1001 77200a74b555552dffe0926156221f5cf0c033a7de52d7f295646a7784e9a7ad /__a/externals/node/bin/node /__w/_temp/containerHandlerInvoker.js'.
Finishing: CmdLine
```

Help/hints would be appreciated.

**Comment by agurfinkel** [comment]
looks like machine base version was updated but old version of nodejs is being used. This is the usual cause for incompatible glibc error. 

I don't know where you use nodejs in the build process. Maybe this is for machine setup before build begins...

**Comment by NikolajBjorner** [comment]
Some context:

The script that fails is

- job: Manylinux
  displayName: "Manylinux build"
  pool:
    vmImage: "ubuntu-16.04"
  container: "rhelmot/manylinux1_x86_64:latest"
  variables:
    python: "/opt/python/cp35-cp35m/bin/python"
  steps:
  - script: $(python) scripts/mk_unix_dist.py --nodotnet --nojava
  - script: git clone https://github.com/z3prover/z3test z3test
  - script: $(python) z3test/scripts/test_benchmarks.py build-dist/z3 z3test/regressions/smt2
  - script: cp dist/*.zip $(Build.ArtifactStagingDirectory)/
  - task: PublishPipelineArtifact@0
    inputs:
      artifactName: 'Manylinux'
      targetPath: $(Build.ArtifactStagingDirectory)

It uses a container. 

The build step that checks out the container and that checks out z3 sources succeeds. It fails when running the first python script (before it gets there). So it is reasonable to assume the container is somehow not cooperating with the environment.

So you suggest the container needs to be updated?

**Comment by agurfinkel** [comment]
If I read the error report correctly, the problem is this line:

```
##[error]Exit code 1 returned from process: file name '/usr/bin/docker', arguments 'exec -i -u 1001 77200a74b555552dffe0926156221f5cf0c033a7de52d7f295646a7784e9a7ad /__a/externals/node/bin/node /__w/_temp/containerHandlerInvoker.js'.
```

This seems like a script that is part of azure pipelines container setup.

If there is a way to update the container. It is definitely worth a try

**Comment by NikolajBjorner** [comment]
@rhelmot - does this sound correct?

**Comment by agurfinkel** [comment]
on an unrelated note, docker hub introduced pull rate limit on Nov 2nd. Do not see how this can be related, but the dates kind of match.

**Comment by NikolajBjorner** [comment]
Last successful nightly was Nov 3 at 7:00 PM.
Then votes were counted...

**Comment by rhelmot** [comment]
my best guess is that the way azure works was changed, and it now tries to inject an agent (node) so it can process the CI commands. The way to upgrade the container would be to switch from manylinux1 to manylinux2010 or manylinux2014. The only reason it's pulling from my namespace is that I couldn't figure out how to get azure to pull from hosts other than dockerhub, so if we find that one of those images is sufficient it'll either need to be rehosted or we will need to work around that limitation.

**Comment by agurfinkel** [comment]
@NikolajBjorner try changing `vmImage` to `ubuntu-latest`.

If I understand this correctly, the build is done under docker in `rhelmot/...`, but to run docker in azure, docker must run in a linux vm. You are using `ubuntu-16.04` which might have become too old...

At least this is consistent with the settings I have for SeaHorn, where I use `ubuntu-latest` for the vm to run docker that runs the version of container I need inside.

**Comment by NikolajBjorner** [comment]
didn't work

**Comment by NikolajBjorner** [comment]
trying now with quay.io/pypa/manylinux2010_x86_64:latest for the docker

**Comment by NikolajBjorner** [comment]
this seems to get further!
