### ISSUE TITLE
Unexpected "unsat" for probable same z3 clause

### ISSUE THREAD

**Issue by shengfeng** [Z3Prover/z3#4788]
But given the following z3 clause:

```
(declare-fun f (Int) Int)
(assert (forall ((v Int))
  (= (ite (= v 0) 0 (ite (= v 11) 11 12)) (f v))))
(check-sat)
```

I got `sat` in `z3 -smt2 -in`, then I introduce a variable `_var_ret` and the clause becomes:

```
(declare-fun _var_ret () Int)
(declare-fun f (Int) Int)
(assert (forall ((v Int))
  (and (= _var_ret (ite (= v 0) 0 (ite (= v 11) 11 12)))
       (= (f v) _var_ret))))
(check-sat)
```

The result is `unsat`. I think these two clauses are equal, but why exactly Z3 can get `unsat`?

**Comment by wintersteiger** [comment]
`_var_ret ` is implicitly quantified existentially and outermost, i.e. your problem becomes `Exists _var_ret. Forall v. ...` and indeed, there is no single return value that works for all `v`, thus the result is unsat.
