### ISSUE TITLE
tactics: new concurrent tactic that operates on all subgoals

### ISSUE THREAD

**Issue by Adorf** [Z3Prover/z3#479]
It would be nice if there were a new tactic that would operate on all subgoals concurrently.

Suppose s is a splitting tactic, and t is a non-splitting tactic

`(then s t)`

applies t to all subgoals produced by s, but `then` unfortunately does not operate concurrently.

`(par-then s t)`

works concurrently, but the process is interrupted, when the first application of t to one of the subgoals produced by s succeeds.

A hypothetical new tactic `par-do` as in

`(par-do s t)`

would concurrently apply t to each subgoal produced by s, but would not terminate prematurely. The semantics would be borrowed from `then`, and the efficiency would be borrowed from `par-then`.

What do you think?

PS: this issue is related to https://github.com/Z3Prover/z3/issues/469 and to https://github.com/Z3Prover/z3/issues/478

**Comment by NikolajBjorner** [comment]
I think this is an excellent point: the existing tactic combinatory do not let you program with continuations of par-or. To do it for real, continuations should be fully distributive.

**Comment by wintersteiger** [comment]
Yes, that's definitely a good idea, I should have time to add par-do next week, or if @Adorf would like to give it a go himself I can help out. 

@NikolajBjorner: I have no idea what it means for continuations to be distributive. Do you imply that other tactics/combinators should also be added or updated?

**Comment by NikolajBjorner** [comment]
Yes, I imply that the signature used internally isn't suitable for concurrency like this. 
Recall that the signature of tactics is of the form "goal x transforms -> goal list x transforms".
The "and-then" tactic composes two tactics with such signatures and returns a tactic with 
the same signature "goal x transforms -> goal list x transforms".
Suppose you want to compose with a third tactic, it would wait until all subgoals are returned from the and-then tactic, then it would be able to operate. You could create an ad-hoc par-then that would work on a list of tactics, but it would not be able to consume subgoals created by a or-else tactic or similar. 
I claim it would require a more substantial design to understand what should work.
It is basically a matter of using a suitable (continuation) monad where the nasty business 
includes dealing properly with tactic failures and protection and contention on shared state.

**Comment by NikolajBjorner** [comment]
lack of traction
