### ISSUE TITLE
Could you make OCaml API support the string comparison?

### ISSUE THREAD

**Issue by jormal** [Z3Prover/z3#4801]
Hi there. I'm a user of Z3 OCaml binding.

I saw this code [`mk_str_lt`](https://github.com/Z3Prover/z3/blob/master/src/api/api_seq.cpp#L213) in the Seq part of API.
But, there is no function like `mk_str_lt`, and `mk_str_le` in Seq module of OCaml API.
(Furthermore, even `mk_str_gt`, and `mk_str_ge` is not exists in API.)

Could you make the next patch with supporting it?
I want to make a lexicographic comparison of two string expressions in Z3.

**Comment by NikolajBjorner** [comment]
Could you add a pull request for this feature?
So far, I have been unable to set to VxT flag on my desktop BIOS mode, required for testing OCaml mode and it is dragging on to get to a stage where I can test this feature locally.

**Comment by jormal** [comment]
@NikolajBjorner
Ok,, I will do it soon.

**Comment by NikolajBjorner** [comment]
Even pasteurized milk expires after 70 days

**Comment by jormal** [comment]
I'm sorry :(
