### ISSUE TITLE
Invalid smt2 syntax for get-model response?

### ISSUE THREAD

**Issue by rixed** [Z3Prover/z3#4807]
According to [SMT2LIB v2.6](http://smtlib.cs.uiowa.edu/papers/smt-lib-reference-v2.6-r2017-07-18.pdf) the response to a `(get-model)` command should be a list of function definitions.
An example from smt2 lib website illustrates this: http://smtlib.cs.uiowa.edu/examples.shtml

Yet, Z3 (and CVC4) prefixes that list with a `model` symbol:

Expected:
```smt2
(set-option :produce-models true)
(check-sat)
sat
(get-model)
()
```

Observed:
```smt2
(set-option :produce-models true)
(check-sat)
sat
(get-model)
(model      ; <--- ?
)
```

Am I missing something obvious?

**Comment by andrewvaughanj** [comment]
You've hit on a (slightly) contentious issue:

- https://groups.google.com/g/smt-lib/c/5xpcIxdQ8-A

Basically, the SMT-LIB standard never said "include `model`", but one tool did it (["one of those very popular SMT solvers"](https://groups.google.com/g/smt-lib/c/5xpcIxdQ8-A/m/lGGxtApUAgAJ)) and then the rest emulated that non-standard-adhering behaviour.

I think, right now, the world SMT solvers is slightly in-flux; while the /de jure/ behaviour should be to adhere to the standard, the /de facto/ behaviour (as you've observed with Z3 and CVC4) is to include `model`.

It is hard to just remove `model`, as the behaviour is so entrenched in tools that depend on other SMT solvers -- think about all the things, which parse the output of an SMT solver, that would break if, suddenly, `model` wasn't there.

I guess we should see what happens at the 2021 [SMT-COMP](https://smt-comp.github.io/2020/index.html) and if the use of `model` counts as a "failure". That may force solvers to match that standard.

**Comment by rixed** [comment]
Oh I see. Thank you very much for the explanation and the references. I couldn't find this when googling for the issue.

I guess I will merely allow and ignore this additional keyword, like probably every other SMT parser writers have done.
It makes little sense to keep this "bug" open, so let me close it.

Have a nice day!

**Comment by NikolajBjorner** [comment]
The current master uses the (new) advised syntax, which does not use "model", just parentheses.

**Comment by andrewvaughanj** [comment]
Ah, my bad, I was (slightly) out of date ... this was fixed on October 21st: https://github.com/Z3Prover/z3/commit/72d407a49f146d45ca591a0652cf60876f83240c#diff-c8b89aa84b89b05c55ff968b64b98fcaa91cb6d66d0c90ce1a5bc05d90c0b1eeR1663
