### ISSUE TITLE
`is_irrational_algebraic_numeral` et al. may receive null arguments

### ISSUE THREAD

**Issue by zv** [Z3Prover/z3#481]
Here is a simple demonstration of what could trigger this bug
```
(set-option :numeral-as-real true)
(declare-const x Real)

(simplify (acos (/ 2)))
```

I would fix this but I am not sure if the issue should be tackled at the `simplify_cmd` level or if the arithmetic utility functions should be changed to return an errno. Much of the simplification code receives malformed input happily, so fixing this somewhat minor bug could be a fairly large undertaking unless z3 just panics when processing empty literals (which would probably be best anyway)

**Comment by NikolajBjorner** [comment]
Thanks, the fix is going to be in arith_rewriter.cpp because division is declared as left-associative which allows one operand.

       case OP_DIV: if (num_args == 1) { result = args[0]; st = BR_DONE; break; } 
            SASSERT(num_args == 2); st = mk_div_core(args[0], args[1], result); break;
        case OP_IDIV: if (num_args == 1) { result = args[0]; st = BR_DONE; break; }
            SASSERT(num_args == 2); st = mk_idiv_core(args[0], args[1], result); break;

**Comment by zv** [comment]
I'll write a PR now.

**Comment by zv** [comment]
What is the best way for me to include a test for single and double operand division in the form of a SMT2 file?
