### ISSUE TITLE
Adding abs makes sat formula unknown

### ISSUE THREAD

**Issue by 0152la** [Z3Prover/z3#4815]
Using z3 built from commit 291502f8e490d6119f78decfb5bc43dad97b8630, the following formula

```
(set-info :status unknown)
(assert
 (let ((?x6 (^ 65 65)))
 (let ((?x8 (+ ?x6 1.0)))
 (< ?x6 ?x8))))
(check-sat)
```
is found to be SAT, as expected. However, adding an abs check on `x8` (which is expected to be positive) leads to the formula becoming UNKNOWN:

```
(set-info :status unknown)
(assert
 (let ((?x6 (^ 65 65)))
 (let ((?x8 (+ ?x6 1.0)))
 (let ((?x34 (ite (>= ?x8 0.0) ?x8 (- ?x8))))
 (< ?x6 ?x34)))))
(check-sat)
```

Lowering either operators to the ^ operand yields the expected SAT again, and CVC4 also yields SAT on both formulas. Is the difference due to the huge number computed by the ^ operation? If so, is there some practical limit to how large mathematical integers can be?

**Comment by NikolajBjorner** [comment]
Z3 just doesn't expand very large exponents during simplification. It cuts off rewriter.max_degree, which is set to 64 default.
You can set the maximal degree and get sat.

```
(set-option :rewriter.max_degree 100)
(assert
 (let ((?x6 (^ 65 65)))
 (let ((?x8 (+ ?x6 1.0)))
 (let ((?x34 (ite (>= ?x8 0.0) ?x8 (- ?x8))))
 (< ?x6 ?x34)))))
(check-sat)
```
