### ISSUE TITLE
Assertion Violation with SetSort() and SetAdd()

### ISSUE THREAD

**Issue by Faganj-y11** [Z3Prover/z3#4816]
I have reached an assertion violation that stated to file an issue here. I believe this is more coming from my own misunderstanding of defining a set with the Python bindings. The error itself is below:
```
ASSERTION VIOLATION
File: ..\..\src\ast\ast.cpp
Line: 432
UNREACHABLE CODE WAS REACHED.
Z3 4.8.9.0
Please file an issue with this message and more detail about how you encountered it at https://github.com/Z3Prover/z3/issues/new
```
If this is my own error could someone please explain how mathematical sets can be declared in Z3, more specifically a set of all odd or all even integers. The full code context is below:
```Python
from z3 import *

s = Solver()

X1 = SetSort(IntSort())
a = Int('a')
b = Int('b')
AB = SetSort(IntSort())
SetAdd(AB, a) # Where error was raised
SetAdd(AB, b)

# X1 is a set of all odd or all even integers
s.add(And(a % 2 == 0, b % 2 == 1, Xor(ForAll([a, b], SetIntersect(AB, X1) == a), ForAll([a, b], SetIntersect(AB, X1) == b))))
```

**Comment by NikolajBjorner** [comment]
AB, X1 are sorts, not expressions.
The script should start with:

```

X1 = Const('X1',SetSort(IntSort()))
a = Int('a')
b = Int('b')
AB = Const('AB', SetSort(IntSort()))
SetAdd(AB, a) # Where error was raised
SetAdd(AB, b)
```

The assertion is not type correct. It compares an integer with a set (array to Bool).

Nikolaj
