### ISSUE TITLE
Defining recursive functions with Java

### ISSUE THREAD

**Issue by VTCAKAVSMoACE** [Z3Prover/z3#4820]
I have found the following API entries for recursive function definition:
 - https://z3prover.github.io/api/html/group__capi.html#gac7351e4edbea27df243af5e80d615c10
 - https://z3prover.github.io/api/html/z3py_8py_source.html#l00824

Unfortunately, I need to define recursive functions in Java, not Python or C++. Can this be done with the Java API? I don't seem to be able to find a definition for it.

**Comment by NikolajBjorner** [comment]
This is pushed to master

**Comment by VTCAKAVSMoACE** [comment]
Looks like this was a rather simple edit. There are a few more features that I've noticed are missing (most of them being related to Fixedpoint). I don't see a CONTRIBUTING.md -- would you prefer I attempt to write these changes myself and submit them for review in PR, or just let you know what's missing?

**Comment by NikolajBjorner** [comment]
PRs are very welcome. There is a description here:

https://github.com/Z3Prover/z3/wiki

The main thing to notice is that edits that are flagged as somewhat more than trivial, for some metric I don't have insight to, require signing an agreement. The purpose is to ensure that the terms of the MIT license are maintained through contributions. 
About 170 contributors are fine with this, sometimes users working in companies or organizations cannot sign such, in this case a mode describing the desired functionality in a clear an actionable way is one mode of getting changes in and improving usability for everybody.

**Comment by VTCAKAVSMoACE** [comment]
Luckily, personal research is rarely so restrictive. I'll see what I can come up with.
