### ISSUE TITLE
poly/factor works with debug build but is not supported by the release build

### ISSUE THREAD

**Issue by muchang** [Z3Prover/z3#4823]
The following trace shows that poly/factor works with debug build but is not supported by the release build. Is it intend?
```
[546] % z3debug small.smt2
(factors
0)
[547] % z3release small.smt2
unsupported
; poly/factor line: 1 position: 15
[548] % 
[548] % cat small.smt2
(poly/factor 0)
[549] %
```
Commit: f58618a

**Comment by NikolajBjorner** [comment]
Right, this is intended. It is a debug command added quite some time ago to aid debugging and developing polynomial factorization. It does not correspond to a user-supported feature.
