### ISSUE TITLE
Does the order of variables in equality affect E-matching?

### ISSUE THREAD

**Issue by alebugariu** [Z3Prover/z3#4831]
The following 2 examples only different in one line:
[repro_unknown.txt](https://github.com/Z3Prover/z3/files/5610419/repro_unknown.txt)
[repro_unsat.txt](https://github.com/Z3Prover/z3/files/5610420/repro_unsat.txt)

In repro_unknown we have:
```(assert (! (= themsg themsg__entry__loop__1) :named A62))```
while in repro_unsat we have:
```(assert (! (= themsg__entry__loop__1 themsg) :named A62))```

It seems that the order in which the variables are written in an equality changes E-matching response from 'unknown' to 'unsat' (with Z3 4.8.8). I think this is not related to randomness, as changing the random seeds for both files leads to the same results (at least for the combinations of random seeds that I've tried). Is this behavior intended? If so, are there any rules we could follow in generating the formulas, such that we can get better results from E-matching?

Thank you very much for your time and help.

**Comment by NikolajBjorner** [comment]
This is due to a bug related to eliminating variables. The themsg variable is used in a pattern. During elimination, themsg is replaced by themsg__entry__loop_1, but the occurrence of themsg in the patterns don't. 
The formula is proved after fixing this bug. It is somewhat intrusive fix, so
