### ISSUE TITLE
Solution soundness issue on real formula

### ISSUE THREAD

**Issue by rainoftime** [Z3Prover/z3#4838]
Hi, for the following formula,
z3 3bca1fbcd82 yields `sat`,
but cvc4 gives `unsat`.
~~~~
(declare-fun r0 () Real)
(declare-fun r1 () Real)
(assert (<= r0 0.0))
(assert (= r1 (^ r0 0.0)))
(assert (distinct r1 1.0))
(check-sat)
~~~~

**Comment by zhendongsu** [comment]
Z3 seems to treat (^ 0.0 0.0) as uninterpreted, similar to (/ 0.0 0.0). 

Also see https://github.com/CVC4/CVC4/issues/3592.
