### ISSUE TITLE
pyz3 Crashing on python exit

### ISSUE THREAD

**Issue by Owlz** [Z3Prover/z3#485]
Hey,

I'm working on using z3 for a symbolic execution engine. Internally, I store the variables in a class dict structure. I noticed in my program that the app seems to be working as expected, however when I exit python, it always crashes with the following error:

```bash
*** Error in `/home/user/.virtualenvs/z3/bin/python3': corrupted double-linked list: 0x0000000001d9c940 ***
Aborted (core dumped)
```

After a little digging, I discovered the following if/set line appears to be reliably causing the problem:

```python
        if varName not in self.localVars:
            self.localVars[varName] = {
                'var': z3.Int(varName),
                'expr': []
            }
```

This is inside the python class I mentioned previously. varName == a string (say 'x'), self.localVars is a structure for the class as follows:

```python
    localVars = {
        'x': {
            'var': x, # This is the actual z3.Int/z3.Array, etc object
            'expr': [
                'localVars['x']['var'] > 1',    # Actual expressions to go into solver
                'localVars['x']['var'] * 5 > 7'
            ]
        }
    }
```

As I mentioned, the code works while running, but it appears that the exit procedure might be clearing up the links to the z3 variables before the variables are free'd themselves? In any case, not sure what to do about this.

**Comment by Owlz** [comment]
Follow-on question. Is there any way to pickle/copy a z3 object? For instance, I try to do deepcopy and get a pickle error since z3 is using ctype pointers.

**Comment by NikolajBjorner** [comment]
Sorry, this report is not possible to act on. A reliable, small repro would be required.
Regarding pickling, there isn't such a feature so you would have to store the formulas in your own format.

**Comment by wintersteiger** [comment]
As @NikolajBjorner said, we'd need a bit more information to act on this. I'm closing this issue for now, but if the problem still exists, please submit a new one. BTW, there were some reference-counting and memory management bugfixes recently, so you may want to update to the latest master of Z3.

**Comment by Owlz** [comment]
Yeah, this one has been a bugger. Used to hit it all the time, now that I changed my code around I'm hitting it periodically. I'll update this when I find another example of it happening.

Thanks
