### ISSUE TITLE
assert in z3 for while

### ISSUE THREAD

**Issue by Shabnam-t** [Z3Prover/z3#4851]
hello
i made simple code to check pre,post condition such as:
y = int(input("Enter an integer: "))
x = int(input("Enter another integer: "))
z=y-x
while z>0:
    y=y-1
    z=z-1

    print(y,z,x)
but, I formulated it as 
s = z3.Solver()
s.assert_exprs(z==x-y,z>0) 
s.assert_exprs (y==y-1,z==z-1, y>=x)
s.check()
z3 ruterns unsat, could someone help me?

**Comment by NikolajBjorner** [comment]
Some starting points:

* https://en.wikipedia.org/wiki/Hoare_logic 
* https://en.wikipedia.org/wiki/Predicate_transformer_semantics

Introductory courses on theoretical computer science typically will contain sections on these topics.

There are many references and textbooks that describe assigning meanings to programs.
There are also many, many, many tools that give you the ability to write programs with assertions and the tools extract suitable formulas. If I start mentioning a subset I would offend the subset not mentioned, but take for instance a look at some of the tools showcased on https://rise4fun.com (Dafny, Boogie, VCC, F*, etc).

**Comment by Shabnam-t** [comment]
Thanks
