### ISSUE TITLE
opt hangs on trivial instance

### ISSUE THREAD

**Issue by rainoftime** [Z3Prover/z3#4872]
Hi, for the following formula,
z3 9f6a0a868af38f
~~~~
 (declare-fun r1 () Real)
 (declare-fun r5 () Real)
 (declare-fun r9 () Real)
 (minimize (* 0.5055 r5 r1 254863777.0 r9))
 (check-sat)
~~~~
Intuitively, since there are no constraints for `r1, r5, r9`, the minimum value of 
`(* 0.5055 r5 r1 254863777.0 r9)` should be `-oo`?
~~~~
./z3 xx.smt2 timeout=60000
(error "line 5 column 11: maximization suspended")
~~~~

**Comment by NikolajBjorner** [comment]
This is non-linear. There is no particular support for non-linear optimization at this point.
What use case does your application seek to address? I am avoiding spending bandwidth on this unless there is some good use case.
