### ISSUE TITLE
Solution soundness bug in FP logic

### ISSUE THREAD

**Issue by muchang** [Z3Prover/z3#4880]
For this formula, z3 gives an incorrect sat, while the model validator cannot detect. 
```
[503] % cvc4 -q small.smt2
unsat
[504] % z3release model_validate=true small.smt2
sat
[505] % cat small.smt2
(assert (forall ((a Float32)) (not (fp.isNegative (fp.min a (_ +zero 8 24))))))
(check-sat)
[506] %
```
Commit: 621e992

**Comment by NikolajBjorner** [comment]
MBQI doesn't integrate with model updates in https://github.com/Z3Prover/z3/blob/173257b4a0511da4e4a9ba0c2f0edf3d72071628/src/ast/fpa/bv2fpa_converter.cpp#L408

There, a definition for fp.min is added to the model, it gets used to specialize the formula passed into MBQI.

z3 4880.smt2 /v:1 smt.relevancy=0 /tr:quantifier /tr:model_checker /tr:smt_model_checker /tr:model /tr:bv2fpa

**Comment by rainoftime** [comment]
~~~~
(assert (forall ((Y (_ FloatingPoint 8 24))) (or (distinct (_ bv1 8) ((_ fp.to_sbv 8) roundNearestTiesToEven Y)) (fp.eq Y (fp (_ bv0 1) (_ bv0 8) (_ bv0 23))))))
(check-sat)
~~~~

**Comment by wintersteiger** [comment]
I'm not sure CVC is right here, surely `min(a, 0)` is allowed to be negative for some `a`. The min is also unspecified when both arguments are zero, that's what those specials are for.

@rainoftime: the formula you just added has nothing to do with `fp.min`, nor does it come with a bug description. What's wrong with that one?

**Comment by NikolajBjorner** [comment]
Regarding the assertion:

```
(assert (forall ((a Float32)) (not (fp.isNegative (fp.min a (_ +zero 8 24))))))
```
It is unsat, right?
Z3 reports sat.

**Comment by zhendongsu** [comment]
Yes, it should be unsat since if a = `(_ -oo 8 24)` for example, `(not (fp.isNegative (fp.min a (_ +zero 8 24))))` evaluates to false.

**Comment by NikolajBjorner** [comment]
yes, thanks a lot for the example.

**Comment by rainoftime** [comment]
@wintersteiger 

It is another formula that may trigger  "Solution soundness bug in FP logic"

**Comment by NikolajBjorner** [comment]
maybe to_ieee and to_real also need interpreted versions for MBQI to be sound. 
But above cases are now handled (second diverges, but that is separate from being unsound).

**Comment by wintersteiger** [comment]
I've added the remaining ones in #6077. Although, to be honest, I would much prefer to teach MBQI to handle partially unspecified functions, I just don't have the time right now.
