### ISSUE TITLE
Constructor of record is not found

### ISSUE THREAD

**Issue by kevin-dp** [Z3Prover/z3#4882]
```
(declare-datatypes (T) ((Wrapper (wrap (get T)))))
(assert (= (wrap 1) (wrap 1)))
(check-sat)
```

Returns the following error:

> (error "line 2 column 18: unknown function/constant wrap")

While this works:
```
(declare-datatypes (T) ((Wrapper (wrap (get T)))))
(declare-const w (Wrapper Int))
(assert (= (wrap 1) (wrap 1)))
(check-sat)
```

And this also works:
```
(declare-datatypes () ((Wrapper (wrap (get Int)))))
(assert (= (wrap 1) (wrap 1)))
(check-sat)
```

But this doesn't:
```
(declare-datatypes () ((Wrapper (wrap (get Int)))))
(declare-const w (Wrapper Bool))
(assert (= (wrap 1) (wrap 1)))
(check-sat)
```

From the observed behavior, I guess that internally, the constructor of the parametric type `Wrapper` is defined the first time the parametric type is concretized (i.e. applied to some type arguments, e.g. when declaring `(declare-const w (Wrapper Int))` in the second example).

Is this intentional?

**Comment by kevin-dp** [comment]
I observed the above behavior in version 4.8.7 - 64 bit

**Comment by NikolajBjorner** [comment]
Right, the symbol table is populated with instances of Wrapper based on function declarations.
This is for convenience. To ensure that you can parse expressions without relying on this facility use type annotation.
SMTLIB2 has a construct called "as", which allows to type disambiguate the signature or range of a function.
For example, the snippet below parses

```
(declare-datatypes (T) ((Wrapper (wrap (get T)))))
(assert (= ((as wrap (Wrapper Int)) 1) (wrap 1)))
(check-sat)
```
