### ISSUE TITLE
Segmentation fault when calliing Z3_optimize_set_params

### ISSUE THREAD

**Issue by jklmnn** [Z3Prover/z3#4885]
I tried to set an timeout for an optimizer via the C API:
```C
Z3_config config = Z3_mk_config();
Z3_context context = Z3_mk_context(config);
Z3_params opt_params = Z3_mk_params(context);
Z3_params_set_uint(context, opt_params, Z3_mk_string_symbol(context, "timeout"), 1000);
Z3_optimize opt = Z3_mk_optimize(context);
Z3_optimize_set_params(context, opt, opt_params);
```
However the call to `Z3_optimize_set_params` results in a segmentation fault.

**Comment by NikolajBjorner** [comment]
when using the C API, you will need to increment/decrement reference counts on objects as they are created. Use the xxxx_inc_ref and xxx_dec_ref APIs.
For manual programming just use C++.
