### ISSUE TITLE
Z3 crashes with a segmentation fault when configured for QF_BV and operating on QF_FP

### ISSUE THREAD

**Issue by martin-neuhaeusser** [Z3Prover/z3#489]
The following Z3 log (produced with the master branch of Z3Prover/z3, commit-id 4cd1efc5) 
reproduces the segmentation fault:
[bv_fp_crash.zip](https://github.com/Z3Prover/z3/files/161697/bv_fp_crash.zip)

If Z3 is not configured to use QF_BV (e.g. by using mk_solver without specifying a theory), the segmentation fault is gone. Of course, the configuration is incorrect for the problem. However, in other cases where the configured theory does not match the input problem, Z3 behaves more indulgently.

**Comment by wintersteiger** [comment]
Do I understand correctly the segfault is thrown when configured for QF_BV, but illegally using QF_FP, i.e., we should throw an error long before we get to the segfault?

**Comment by martin-neuhaeusser** [comment]
Yes, I think an error message or an exception would be better.

From my experiments, it seems as if the segmentation fault does not occur on the same problem when Z3 is configured for, e.g. QF_UFBV or when it runs without being configured for an explicit theory.
Somehow it occurs with QF_BV...

How is Z3 expected to behave in cases where the configured theory does not match the problem?

**Comment by wintersteiger** [comment]
In this case it will treat all non-QF_BV constraints as uninterpreted, and the segfault occurs during handling of uninterpreted sorts (with names FloatingPoint and RoundingMode) while constructing a model. I'll check how it behaves in other cases and I'll make it at least consistent with them.

**Comment by 4tXJ7f** [comment]
I just encountered a similar problem: When using quantifiers with QF_FP/QF_FPBV, z3 crashes with a segfault in `lackr::collect_terms()`:

```
$ cat out.txt
(assert (forall ((%rundef0 (_ FloatingPoint 11 53)))
  (fp.isNaN %rundef0)))
(apply qfbv)
$ z3 -smt2 out.txt
Segmentation fault: 11
```

**Comment by wintersteiger** [comment]
@4tXJ7f: Could you open a new issue for your segfault? This is a problem in lackr, which is unrelated to the issue #489.

**Comment by MikolasJanota** [comment]
lackr does not support quantifiers. So the issue's probably that qfbv is invoked on a quantified formula. I should make it more resilient because qfbv switches to standard smt when quantifiers are found. (even though they really shouldn't be there IMO).

**Comment by wintersteiger** [comment]
@MikolasJanota: Yes, quantifiers present; lackr should not segfault though, it should report an error or throw an exception.

**Comment by 4tXJ7f** [comment]
@wintersteiger @MikolasJanota Thanks for the replies, I opened a new issue (#544).

**Comment by wintersteiger** [comment]
This should now be fixed, it should treat all FP constraints as uninterpreted (which seems to be in line with what the other theories behave like).
