### ISSUE TITLE
Java API for mkLinearOrder and related

### ISSUE THREAD

**Issue by mmosko** [Z3Prover/z3#4892]
mk{Linear,Partial,...}Order are exposed in Native.java, but there is no way to use them.

They either need to be plumbed through to Context, or Z3Object needs to expose getNativeObject() so they can be called directly from Native.

**Comment by NikolajBjorner** [comment]
There is a more general issue with the Java API: It seals access to Native.java. This precludes power-users from dancing around the API or use not-yet-exposed features, but obviously is there to protect against random abuse.

I consider special relations as somewhat exotic features and are not exposed uniformly over APIs.
If you like to use this exotic feature, feel free to add a pull request to expose them.
