### ISSUE TITLE
UFBV logic misses obvious (?) unsatisfiability

### ISSUE THREAD

**Issue by Calvin-L** [Z3Prover/z3#4896]
```
$ z3 --version
Z3 version 4.8.9 - 64 bit
```

In this quantifier-free SMT-LIB input, the `UFBV` logic solver spins out while `QF_UFBV` has no trouble proving unsat almost immediately:

```SMT
(set-logic UFBV)        ; spins out
; (set-logic QF_UFBV)   ; finishes quickly

(define-sort Z () (_ BitVec 32))
(define-const zero Z (_ bv0 32))
(define-const one  Z (_ bv1 32))

(declare-const needle Z)
(declare-fun haystack (Z) Z)
(declare-const bound Z)
(declare-const index Z)

(assert (bvsge bound zero))
(assert (bvsge index zero))
(assert (bvslt index bound))

(assert (not (= (haystack (bvsub bound one)) needle)))                    ; A
(assert (=> (and (bvsge index zero) (bvslt index (bvsub bound one)))      ; B
            (not (= (haystack index) needle))))
(assert (= (haystack index) needle))                                      ; C

; UNSAT because either
;  (1) index = bound-1        ==>   unsat by A,C
;  (2) 0 <= index < bound-1   ==>   unsat by B,C
(check-sat)
```

------

(If I only cared about the input above, the right fix would be to just use QF_UFBV. However, the input above is a highly simplified version of a much larger input that I _actually_ care about, and the larger input includes quantifiers. Some of the assertions in the simplified input above actually appear underneath quantifiers in my real input. My original hope had been that after a few rounds of quantifier instantiation, Z3 could prove my big input unsatisfiable. It did not. After some back and forth I reduced it to the example above. I can supply the relevant parts of the larger input as well, if that would be useful.)

**Comment by NikolajBjorner** [comment]
This is an example where the current solver architecture is inadequate: The problem with QF_UFBV gets translated to ground SAT using a static ackerman reduction on the haystack function. With UFBV it doesn't get reduced and instead the solver has to learn an exponential number of lemmas. It is non-trivial to patch the current solver architecture to deal with this, so I am fixing it the hard way by adding a new solver core where dynamic ackerman lemmas are dealt with in a more tuned way. It is still months out to test fully, especially with quantifiers.
The example above is easy with the new core:

```
z3 4896.smt2 /v:10 tactic.default_tactic=sat sat.euf=true /st sat.drat.file=f.drat
```

and the proof trail validates using
```
z3 4896.smt2 f.drat
```
