### ISSUE TITLE
Provide option to link ``z3`` against ``libz3``

### ISSUE THREAD

**Issue by delcypher** [Z3Prover/z3#491]
This is a suggested enhancement (related to #279). It is likely that Linux distro packagers will want to have the z3 executable linked against the ``libz3`` shared library to reduce the size of the ``z3`` binary.

Neither the CMake nor the Python based build system can do this right now and I think it would be useful to look at what is blocking this and discuss whether or not it is worth addressing.

AFAICT these are the issues that prevent having the ``z3`` from linking against ``libz3`` directly.

* The ``api_dll`` (in ``libz3``), ``shell`` (not in ``libz3``) and ``test`` (not in ``libz3``) components all generate their own versions of ``gparams_register_modules.cpp``, ``install_tactic.cpp`` and ``mem_initializer.cpp``. In Python build system these are identical. In the CMake build system these aren't identical (due to order paths are searched) but this can be fixed. If ``z3`` was to link against ``libz3`` then the ``shell`` component shouldn't generate its own versions of these files to avoiding linking problems due to identical symbols being defined multiple times. Is there any reason why ``z3``, ``libz3`` and ``test-z3`` get their own versions of these files? To me it would be simpler if those files were just another component which ``libz3``, ``z3`` and ``test-z3`` all used.

* Symbol visibility. This is the biggest issue. Because most of ``libz3``'s symbols are hidden the ``z3`` sources (i.e. the ``shell`` component) can't link against ``libz3``. It is not as simple as removing ``-fvisibility=hidden`` because on Windows symbols are hidden by default. I don't really know how to go about fixing this.

On the usability front #279 raised the issue that on UNIX like platforms if ``z3`` did link against ``libz3`` that the user would have to set ``LD_LIBRARY_PATH`` or ``DYLD_LIBRARY_PATH`` manually for an ``z3`` to work. This is actually only an issue for the Python build system. The CMake build system will automatically set the ``rpath`` on the ``z3`` binaries so that the system linker automatically knows where to find ``libz3``. It is also very easy to set  ``LD_LIBRARY_PATH`` or ``DYLD_LIBRARY_PATH`` so I don't think this particular issue is a strong argument against supporting ``z3`` linking against ``libz3``.

Another argument might be the performance impact of having ``z3`` use ``libz3``. Then again if you really want to get rid of link time performance hits you should compile ``z3`` as a static binary so again this isn't a strong argument to not support an option to build ``z3`` against ``libz3``.

Any thoughts?

**Comment by nunoplopes** [comment]
I can't see any compeling argument to do this. Having a single binary is very convenient and enables link-time optimizations, for example.
So unless there's some reason to *additionally* support linking z3 to libz3 and a patch to do that, we are not going to waste time on that..

**Comment by delcypher** [comment]
@nunoplopes I think the only argument for this is reducing binary size for distributable packages. Closing this is fine. If someone really needs we can reopen this issue. At least this documents what would need to be fixed to support this.

**Comment by wintersteiger** [comment]
I agree, it's easy to do for anyone who really, really needs it (a couple flags in config.mk and perhaps the Makefile), but by default it doesn't make sense, because z3.exe + libz3.dll is pretty much the same size as before (perhaps even a tiny bit larger). 

At some point somebody mentioned that they "assumed" z3.exe would be linked to libz3.dll as an intentional example of how to link to the dll, but that is really what examples/* is for (and they should make this a bit more explicit, e.g., not by integrating them into the main build system, but by having separate, small Makefiles that can be used as example for linking to the dll).

**Comment by delcypher** [comment]
@nunoplopes @wintersteiger 
Okay. It would be nice to know an answer to one of the things that would cause problems for someone wanting to link the ``z3`` executable against ``libz3`` though.

The build system seems to generate three separate copies of

* gparams_register_modules.cpp
* install_tactic.cpp
* mem_initializer.cpp

for the ``shell`` (i.e the ``z3`` executable), ``api_dll`` and ``test`` (i.e. ``test-z3`` executable) components.

Currently each of those components get given identical files (e.g. ``src/shell/install_tactic.cpp``, ``src/api/dll/install_tactic.cpp`` and ``src/test/install_tactic.cpp``). This seems unnecessarily complicated. It seems to me it would be simpler to just have one copy of each of these three files and just build them as part of a component that ``shell``, ``api_dll``  and ``test`` all use.

Is there an intention to ever build executables (or libraries) using a subset of Z3's components? In that case I can see how generating different versions of the files might be necessary.

**Comment by NikolajBjorner** [comment]
The install_tactics.cpp files are identical and I don't see why they should diverge: in particular we would like the API and shell to offer compatible features. Test should simply include everything we build anyhow. Putting them in a common place makes sense, but I was never bothered by the two extra copies so far, and I have not examined if coalescing the occurrences would mean to add another build directory etc. and what other entropy it would lead to.

**Comment by yassinedon** [comment]
I can't install z3 Ubuntu 16.04

**Comment by delcypher** [comment]
@yassinedon Don't hijack this dead thread with your problems. Please open a new issue and also with a better description of the problem.
