### ISSUE TITLE
fpMinusZero is not equal to fpPlusZero

### ISSUE THREAD

**Issue by orsinium** [Z3Prover/z3#4914]
## Steps to reproduce

```python
>>> import z3
>>> z3.prove(z3.fpMinusZero(z3.Float64()) == z3.fpPlusZero(z3.Float64()))
counterexample
[]
>>> z3.prove(z3.fpMinusZero(z3.Float64()) != z3.fpPlusZero(z3.Float64()))
proved
```

## Expected

According to IEEE 754 "Standard for Floating-Point Arithmetic":

> −0 and +0 compare as equal.
> https://en.wikipedia.org/wiki/IEEE_754#Comparison_predicates

## Actual

-0.0 and +0.0 are not equal.

## Version

```bash
$ python3.9 -m pip show z3-solver
Name: z3-solver
Version: 4.8.9.0
```

**Comment by andrewvaughanj** [comment]
You're checking if two _SMT terms_ are equivalent -- if you want to check _floating point_ equivalence, you should use `z3.fqEQ`:

```
[avj@tempvm tmp]$ cat test.py
import z3

z3.prove(z3.fpEQ(z3.fpMinusZero(z3.Float64()), z3.fpPlusZero(z3.Float64())))
[avj@tempvm tmp]$ python test.py
proved
```

**Comment by orsinium** [comment]
Thank you!
