### ISSUE TITLE
qe_lite spends several hours on push_not

### ISSUE THREAD

**Issue by nunoplopes** [Z3Prover/z3#4916]
Alive2 has several benchmarks where qe_lite spends several hours on ast_util.cpp's `push_not` and it doesn't even finish.
`push_not` is recursive and the stack gets really deep (> 150 recursive calls).
I don't know how such a horrible formula is reaching qe_lite as we run the simplifier beforehand, but regardless, should we limit the recursion of `push_not` to some small arbitrary limit to avoid these explosive cases?

This part of the code doesn't check the resource limits, so it's important it gets tamed.

cf https://github.com/AliveToolkit/alive2/issues/632

**Comment by nunoplopes** [comment]
cc @LebedevRI @regehr

**Comment by LebedevRI** [comment]
@nunoplopes thank you for looking into it!

**Comment by NikolajBjorner** [comment]
I take push_not is mainly lipstick, for qe_lite you can use recursion depth 2. It is used for quantifiers. For some reason Alive generates quantified formulas with deeply nested and/ors.
