### ISSUE TITLE
Z3_OP_PR_REWRITE in the C API documentation contains HTML in the nicebox

### ISSUE THREAD

**Issue by jakevossen5** [Z3Prover/z3#4918]
Go to the `Z3_OP_PR_REWRITE` documentation here: https://z3prover.github.io/api/html/group__capi.html. It seems like there is some issue with the placment of the `nicebox` here: https://github.com/Z3Prover/z3/blob/374ae52d70b33d438190c15b905cafd411e731d5/src/api/z3_api.h#L529
<img width="1191" alt="Screen Shot 2020-12-27 at 2 34 59 PM" src="https://user-images.githubusercontent.com/16298666/103180198-b53a1c00-4850-11eb-85b2-7dff451f53bb.png">

**Comment by NikolajBjorner** [comment]
Must be a very naughty box. Santa will not be happy.

**Comment by NikolajBjorner** [comment]
should be updated by next documentation release
