### ISSUE TITLE
Convert float to string

### ISSUE THREAD

**Issue by zhiyufan** [Z3Prover/z3#4922]
Hi, I'm wondering if there is any way to convert a float to string in z3, just like what int.to.str did?

**Comment by rainoftime** [comment]
Here is a possible solution
1. Convert float to bit-vector: via `fp.to_ubv or `fp.to_sbv`
2. Convert bit-vector to int: via `bv2nat`
3. Convert int to string, int.to_str
BTW, in the SMT-LIB2 standard, int.to.str has been changed to int.to_str

**Comment by NikolajBjorner** [comment]
This answer is legal.
You could also start with the results from 1, then write a string concatentation of if-then-else expressions that test each bit and produces "1" or "0". For example, in SMTLIB lingo:
(define-fun mybv2str ((x (_ BitVec 2))) String (str.++ (if (= (_ bv 0) ((_ extract 1 1) x) "1" "0") (if (= (_ bv 1) ((_ extract 1 1) x) "1" "0")))
