### ISSUE TITLE
No model with incomplete-arithmetic unknown

### ISSUE THREAD

**Issue by RustanLeino** [Z3Prover/z3#4924]
Using the input below, Z3 v.4.8.9 reports `unknown` because of incomplete theory arithmetic. Boogie expects to still get a model from Z3, but in this case, Z3 says "model is not available". I'd like to suggest that is a bug in Z3. (Not having a model means the only thing Dafny can report is "there's an error _somewhere_ in this method", which is rather lame.)

Notes:
* I'm using `(set-option :smt.arith.solver 2)` (because the new default arithmetic mode causes Dafny to fail everywhere).
* I have also tried the input below with Z3 v.4.8.4, v.4.8.5, and v.4.8.8, and those versions of Z3 return `unsat` instead of `unknown`, so v.4.8.9 has regressed (even with `(set-option :smt.arith.solver 2)`) for this example.
* See also https://github.com/boogie-org/boogie/issues/321

```
(set-option :print-success false)
(set-info :smt-lib-version 2.6)
(set-option :auto_config false)
(set-option :type_check true)
(set-option :smt.phase_selection 0)
(set-option :smt.restart_strategy 0)
(set-option :smt.restart_factor |1.5|)
(set-option :smt.arith.random_initial_value true)
(set-option :smt.case_split 3)
(set-option :smt.qi.eager_threshold 100)
(set-option :smt.delay_units true)
(set-option :nnf.sk_hack true)
(set-option :smt.arith.solver 2)
(set-option :smt.mbqi false)
(set-option :model.compact false)
(set-option :model.v2 true)
(set-option :pp.bv_literals false)

(declare-fun ControlFlow (Int Int) Int)
(declare-fun a () Int)
(declare-fun b () Int)
(push 1)
(set-info :boogie-vc-id Test)
(set-option :timeout 0)
(set-option :rlimit 0)
(assert (not
 (=> (= (ControlFlow 0 0) 67) (let ((anon0_correct  (=> (= (ControlFlow 0 40) (- 0 90)) (<= a (* a b)))))
(let ((PreconditionGeneratedEntry_correct  (=> (<= 1 a) (=> (and (<= 1 b) (= (ControlFlow 0 67) 40)) anon0_correct))))
PreconditionGeneratedEntry_correct)))
))
; With Z3 4.8.9, the next command gives:
;   unknown
(check-sat)
; The next command gives:
;   (:reason-unknown "smt tactic failed to show goal to be sat/unsat (incomplete (theory arithmetic))")
(get-info :reason-unknown)
; The next command gives:
;   (error "line 39 column 31: model is not available")
; Changing the command to (get-model) gives the same error.
(get-value ((ControlFlow 0 0)))
```

**Comment by NikolajBjorner** [comment]
This does not reproduce with latest build (nightly).

**Comment by NikolajBjorner** [comment]
There are many cases where arith-solver=6 is far superior, but it is expected that it introduces regressions.
I would like to sunset arith-solver=2. Code-wise, it isn't extensible and it contains corner case bugs that are incredibly hard to fix and at best masked by ensuring certain rewriting flags.
So when confronted with regression reports I am asking users to collect representative 
instances that show usability difference and are as self-contained as possible.

arith-solver=6 uses a much more complete method for non-linear solving. It is possible we just want to disable this for Boogie examples because you want fast answers.

The part of returning models when the solver doesn't know the sat status might be possible to address, though it really should fail for all other sane users.

**Comment by RustanLeino** [comment]
Thanks for the new groovy option :), which we'll make use of in Boogie as soon as we can. Do you have an estimate for when the next official release will be out? (Like, in two weeks or several months from now?)

Indeed, for non-linear arithmetic, Dafny wants as little as possible (but no less). Knowing a few properties like distribution of * over +, squaring gives a non-negative number, and the basic relationship between *, /, and % would be great. Beyond that, fast, repeatable, and possibly "unknown" answers are better than complete answers that you have to wait for.

I'm trying to move Dafny from Z3 v.4.8.4 to something newer. I've tried v4.8.5, v.4.8.8, and v4.8.9, and of these, v.4.8.5 performs the best overall. I can supply test cases in .smt2 format where v.4.8.9 fails to prove what previous versions proved or where v.4.8.9 never comes back (or at least exceeds my patience by more than 2 orders of magnitude). What's a good way to communicate them to you? As Issues here, in email, or placed on some share somewhere?

> The part of returning models when the solver doesn't know the sat status might be possible to address, though it really should fail for all other sane users.

When sanity becomes part of my game, I'll let you know.

**Comment by NikolajBjorner** [comment]
The best process is to use a github issue and post a few (gist) links in it.

**Comment by NikolajBjorner** [comment]
Probably somewhere around noon EST on January 20th.
