### ISSUE TITLE
assert-soft: performance impact?

### ISSUE THREAD

**Issue by wuestholz** [Z3Prover/z3#493]
I noticed a relatively large increase in running time when using an assert-soft instead of a regular assert. Since the assertion is satisfiable for all checks I wasn't expecting such a big difference. (Changing the maxsat engine did not result in significant differences.) Any idea what might be the reason for this behavior? Is it using a very different solver or is this an expected overhead?

I have attached the input file ([log.soft.txt](https://github.com/Z3Prover/z3/files/162440/log.soft.txt)) with the soft-assert. Z3 produces the following statistics:

```
(:add-rows     3
 :added-eqs    30
 :assert-diseq 1
 :assert-lower 5
 :assert-upper 1
 :conflicts    1
 :del-clause   3813
 :eq-adapter   124
 :final-checks 1
 :fixed-eqs    1
 :max-memory   8.25
 :memory       7.93
 :mk-bool-var  2874
 :mk-clause    3813
 :num-allocs   5857804214.00
 :num-checks   2
 :pivots       2
 :propagations 71
 :rlimit-count 11248665
 :time         0.15
 :total-time   4.82)
```

When I replace `(assert-soft soft$$a0 :weight 1)` with `(assert soft$$a0)` I get a significantly different output:

```
(:add-rows        162146
 :added-eqs       257081
 :arith-conflicts 3672
 :assert-diseq    4172
 :assert-lower    32429
 :assert-upper    21013
 :bound-prop      2777
 :conflicts       4268
 :decisions       7495
 :del-clause      31751
 :eq-adapter      13728
 :final-checks    64
 :fixed-eqs       18035
 :max-memory      5.33
 :memory          4.93
 :minimized-lits  1890
 :mk-bool-var     39718
 :mk-clause       31751
 :num-allocs      9823789
 :num-checks      127
 :offset-eqs      6569
 :pivots          4397
 :propagations    281276
 :restarts        13
 :rlimit-count    493716
 :time            0.02
 :total-time      0.79)
```

**Comment by NikolajBjorner** [comment]
The solver is not incremental when used for optimization. 
So fresh state is created every time a separate check is made. 
This example can leverage incrementality.
I don't have plans to support incrementality for optimization because problem typically can use substantial pre-processing that isn't possible with incremental mode and the solver's last state may be inconsistent even though the optimal answer is in a consistent state.

**Comment by wuestholz** [comment]
@NikolajBjorner I see. Thank you for the explanation!
