### ISSUE TITLE
CHC with uninterpreted functions

### ISSUE THREAD

**Issue by WJ-Hong** [Z3Prover/z3#4936]
Hi,

I'm facing the problem with CHC solving. For the following smt2 file, it's expected to return a sat with a model like Inv(x, y) := x=y. However, it returns an unknown immediately. The z3's version here is 4.8.8. 

So I'm curious about whether the current CHC engine supports EUF theory. If not, I would like to ask: why does it show such results during the CHC solving process since Z3 supports uninterpreted functions very well? Is there any difficulty in the process? 

Thank you for your attention to this matter.

```
(set-logic HORN)

(declare-fun f (Int) Int)
(declare-fun g (Int) Int)
(declare-fun Inv (Int Int) Bool)

(assert
 (forall ((x Int) (y Int) (s Int) (t Int))
         (=> (= x y)
             (Inv x y)))
)

(assert
 (forall ((x Int) (y Int) (s Int) (t Int))
         (=> (and (= s t) (Inv x y))
             (Inv (f x) (f y))))
)


(assert
 (forall ((x Int) (y Int) (s Int) (t Int))
         (=> (and (not (= s t)) (Inv x y))
             (Inv (g x) (g y))))
)


(assert
 (forall ((x Int) (y Int) (s Int) (t Int))
         (=> (and (not (= x y)) (Inv x y))
             false))
)


(check-sat)
```

**Comment by agurfinkel** [comment]
spacer (the CHC engine of Z3) does not soundly support uninterpreted functions. For this reason, input that contains uninterpreted functions is flagged by pre-processor and `unknown` is returned by the solver.

If you are interested in extending spacer algorithms to uninterpreted functions, you can disable this check in the front end. If you are need to use UF in your CHCs, consider modelling them by relations or by arrays.
