### ISSUE TITLE
tactics for sorting clauses or goals?

### ISSUE THREAD

**Issue by Adorf** [Z3Prover/z3#494]
Are there tactics that could be used for sorting clauses or goals? 

If not, Id' like to suggest ones for consideration. I'm prepared to elaborate on my ideas, should no such tactics exist.

**Comment by NikolajBjorner** [comment]
There isn't. You can process goals over the api and sort them in your code according to your criteria.

**Comment by Adorf** [comment]
OK. I understand that we could manipulate the goals through the API. However, such a solution would not be generally available to others.

Since I have thought it through now, I go on to present my ideas about two sorting tactics that might generally be useful


Motivation
----------
The splitting tactic `split-clause` is and the hypothetical splitting tactic `partition` would be very useful for splitting a given goal (wrapping a CSP) into subgoals (each wrapping a sub-CSP). The combiners `then` and `par-then` are, and the hypothetical tactic `par-do` would be very useful for operating on subgoals, particularly when applying one of the solvers at the very end. However, the order of subgoals is arbitrary, depending on the order in which constraints were asserted.

Consider a strategy such as

`(check-sat-using (then split-clause smt))`

There are two points where we might wish to insert a sort tactic, namely before and after `split-clause.`.


sort-clauses
------------
Consider a hypothetical tactic `sort-clauses` as in the strategy 

`(check-sat-using (then sort-clauses split-clause smt))`

`sort-clauses` would sort the available clauses (within each goal) according to some criterion such as size. A simple metric measuring size would be to count the top-level constraints ci in the clause `(or c1 c2 ...)` that is picked by `split-clause`. Another useful parameter would be one controlling the sort direction in ascending or descending order.

So my base suggestion is a tactic

`(sort-clauses :ascending d)`

where the value of d could be true or false. Instead there could be two mutually exclusive parameters `:ascending` and `:descending`, which would make the tactic more readable.

If a tactic such as `sort-clauses` were in place, we could beneficially control the number of subgoals that are created by `split-clause`. We might be interested in splitting a small clause and consequently obtain only a few subgoals, or in splitting a large clause and obtain many subgoals.

Let us replace the tactic `then` by one of its parallel siblings.

`(check-sat-using (par-then (! sort-clauses :descending) split-clause smt))`

This strategy would pick one of the large clauses with a maximum number of elements and thereby create the maximum number n of subgoals. The tactic `par-then` would start n SMT-solvers working concurrently and competitvely on the subgoals. For this to work well, tactic `par-then` should probably have a parameter `:max-no-workers` that controls the maximum number or worker threads, as in

`(check-sat-using (! par-then (! sort-clauses :descending) :max-no-workers 6) split-clause smt))`

Thereby we would make full use of the computational power of our hardware (which in my case has 8 cores), without overloading it.


sort-goals
----------
Do we need anything else? I believe, yes.

After `split-clause` has done its work we might wish to intervene once more. `split-clause` produces a sequence of subgoals. The order of these subgoals is arbitrary, corresponding to the order of the elements in the clause that was split.

If we submit a sequence of subgoals to a bunch of solvers that concurrently and competitively work on the subgoals, as in the example above, we are interested in starting with easy to solve CSPs (subgoals) and work our way up to more difficult ones. Thus we increase our chances that an easy to solve CSP, wrapped into a subgoal, is solved early on, thereby cancelling the rest of the computations.

Let us threfore introduce a another hypothetical tactic dubbed `sort-goals`, as in

`(check-sat-using (par-then sort-clauses split-clause sort-goals smt))`

Of course, there is no metric that will tell us precisely how difficult a given CSP is for a given solver, expressed by how long it takes the solver to solve the CSP. However, in our experience the difficulty (in case of sat-CSPs) can reasonably well be estimated by computing a "size" of a CSP. 

Conceivable size metrics for goals are
- :no-of-constraints the number of constraints that make up the goal, counted at top-level (this number should be easy to get hold of)
- :no-of-variables the number of variables occuring in the constraints that make up the goal (requires to walk the constraints in order to collect the variables)
- :size some other metric measuring the size, e.g. a linear combination the two metrics above

Let us go with a linear parameter `:size`. Then it would be useful if there were two other parameters, namely
`:variable-weight` and `:constraint-weight`. The size of the CSP would be computed via

`:size = :variable-weight * :no-of-variables + :constraint-weight * :no-of-constraints`

Let us assume that the default values for the weights are 1 (which is what we always use).

Again a `:direction` parameter or equivalent would control whether the sorting should occur in ascending or descending order. 


Conclusion
----------
A strategy such as 

`(check-sat-using (par-then sort-clauses split-clause (! sort-goals :descending) smt))`

or, by using two other hypothetical tactics `partition` and `par-do`, a strategy such as  

`(check-sat-using (par-do partition (! sort-goals :descending) smt))`

would, in a few lines of concise "macro" code, accomplish a lot of what we have currently implemented in a lot of external Java code. Of course the sort tactics would first have to be implemented in Z3.

I believe that both sort tactics would be beneficial not only for the CSPs that we routinely solve, but for other Z3-users as well. Hopefully these will step forward and leave their encouraging comments.


Side remarks
------------
In our work we regularly partition a given CSP into minimal independent components, and usually want to try to solve the most difficult CSP-components first. Thereby we want to discover as early as possible whether these difficult components require human attention. The whole CSP-solution process may have to be halted, if the difficult components are too difficult for the solver. The process will be restarted only after we have suitably modified the CSP-components, so that the solver has a chance to solve them within some reasonable time limits.

**Comment by NikolajBjorner** [comment]
Seems like a somewhat specific feature request and would require significant domain engineering that is better done in scenarios you are exercising.
It would be problematic to reproduce without a decent way to evaluate the feature.
In particular, it is not clear that we have a proper way to know what comparison functions would work.

I certainly hope you could leverage the open source model that encourages pull 
requests for well-engineered features that you had a chance to test under your workload.
See also https://github.com/Z3Prover/z3/wiki/Contribution%20Guidelines
It could be a nice benefit for other users.

Is sort-goals a proper tactic? That is, is the signature one that takes a single goal and returns a list of goals? Seems it would be taking a list of goals and returning a list of goals.

**Comment by Adorf** [comment]
@NikolajBjorner: thanks for pointing out the contribution guidelines that I was unaware of so far. I had been considering to publish some of our hard problems (CSPs) somewhere, and wait and see what others have to say about how to solve them. From a quick glance at your guidelines I get the impression that we could publish a sample of our hard problems, suitably anonymised, of course.

Is sort-goals a proper tactic? If you define a tactic such that it takes a goal and returns a goal or a collection of goals, sort-goals certainly is not a tactic. My question is: why would one (want or have to) restrict oneself to only accept a single goal as input, rather than always accepting as input a collection of goals?
