### ISSUE TITLE
z3 is slower in assumption based incremental solving

### ISSUE THREAD

**Issue by usagitoneko97** [Z3Prover/z3#4941]
In my test case that have a lot of constraints added, and each check() invoke on the solver only check for few assumptions, it's running much slower, compared to a fresh solver if only those assumptions. E.g.:
```python
from z3 import *

s = Solver()
s.from_file("test.smt")  # ~70 constraints
i = Bools("assume13 assume22 assume26 assume20 assume76 assume29")
print(s.check(i))    # stuck
print(s.model())
```
running on:
[test.smt.txt](https://github.com/Z3Prover/z3/files/5792549/test.smt.txt)

Some options that I tried:

- Using `z3.Then('simplify', 'smt').solver()` the case above can be solve slightly quicker, but it's not incremental
- Setting `smt.auto_config = False` and `smt.relevancy = 0` seems to improve it, but still there is noticeable run time difference compared to a fresh solver.

Is there any way to optimize it?

**Comment by NikolajBjorner** [comment]
Currently, the only real way is to rely on auto_config=false and setting smt.relevancy=0.
An additional option that is useful for this class of benchmarks (pure QF_LIA formulas) is to set smt.arith.propagate_eqs=false.
It gives only a marginal improvement, though.

Performance should be improved noticeably with the new core, which in the works. 
In my tests I get incremental solving time down to under a second for most random seeds. 
Some random seeds still require a few seconds.

So for now, you are stuck with a slower incremental mode solver with the prospect of some improvements in the coming months (there are without doubt many bugs in the new core so I cannot yet advertise it for general purpose use).
For a preview, pull and try: z3 test.smt.txt sat.euf=true tactic.default_tactic=sat -st -v:10 and you might cry for what could have been.
