### ISSUE TITLE
Optimize for two objectives, model doesn't match the objectives

### ISSUE THREAD

**Issue by tompazourek** [Z3Prover/z3#4942]
I'm just learning Z3 and going through the [optimization tutorial](https://rise4fun.com/Z3/tutorial/optimization) and found a strange thing I cannot explain.

Consider the following SMT file:

```
; x1 from 0 to 1000
(declare-const x1 Int)(assert (<= 0 x1))(assert (<= x1 1000))

; x2 from 0 to 1000
(declare-const x2 Int)(assert (<= 0 x2))(assert (<= x2 1000))

; x2 - x1 <= 10
(assert (<= (- x2 x1) 10))

; first, expected to minimize x1 to 0
(minimize x1)

; after that, expected to maximize x2 to 10
(maximize (- x2 x1))

(check-sat)
(get-objectives)
(get-model)
```

### Actual behavior

When I execute Z3, I get this result (notice **the objectives don't match the model, x2 is 0 in the model**):

```
sat
(objectives
 (x1 0)
 ((- x2 x1) 10)
)
(model
  (define-fun x2 () Int
    0)
  (define-fun x1 () Int
    0)
)
```

### Expected behavior

What I'd expect instead would be:

```
sat
(objectives
 (x1 0)
 ((- x2 x1) 10)
)
(model
  (define-fun x2 () Int
    10)
  (define-fun x1 () Int
    0)
)
```

## Change to 0..100

The strangest thing is when I change the range of the values from 0..1000 to 0..100, I get the result I am looking for:

```
; x1 from 0 to 100
(declare-const x1 Int)(assert (<= 0 x1))(assert (<= x1 100))

; x2 from 0 to 100
(declare-const x2 Int)(assert (<= 0 x2))(assert (<= x2 100))

; x2 - x1 <= 10
(assert (<= (- x2 x1) 10))

; first, expected to minimize x1 to 0
(minimize x1)

; after that, expected to maximize x2 to 10
(maximize (- x2 x1))

(check-sat)
(get-objectives)
(get-model)
```

This results in:

```
sat
(objectives
 (x1 0)
 ((- x2 x1) 10)
)
(model
  (define-fun x2 () Int
    10)
  (define-fun x1 () Int
    0)
)
```

What's happening here? How can I get the model values matching the objectives in the first example? And why does the range of 0..100 behave differently to 0..1000?

**Comment by tompazourek** [comment]
@NikolajBjorner Why did you close the issue without any comment? Did I do something wrong? Sorry if I did, but I'd like to at least know what's wrong.

**Comment by NikolajBjorner** [comment]
I believe it was fixed https://github.com/Z3Prover/z3/commit/0aac7e54a91de423088f0f321b9eef1bbac87118

**Comment by NikolajBjorner** [comment]
I get
```
C:\z3\build>z3 4942.smt2
sat
(objectives
 (x1 0)
 ((- x2 x1) 10)
)
(
  (define-fun x2 () Int
    10)
  (define-fun x1 () Int
    0)
)
```

**Comment by NikolajBjorner** [comment]
The bug was that the returned model corresponded to the model obtained when optimizing the first objective, not the last, in the lex-order

**Comment by tompazourek** [comment]
@NikolajBjorner Oh, I see. That's great to hear that it was fixed and so fast. It's GitHub that didn't somehow link the issue correctly to the commit.

Thank you. Now I'm looking forward to the next release :)

**Comment by NikolajBjorner** [comment]
![image](https://user-images.githubusercontent.com/3085284/104285327-525b9e00-5468-11eb-95e4-41ec085d57c4.png)

**Comment by tompazourek** [comment]
@NikolajBjorner My bad, I must be blind or something. Sorry and thanks!

**Comment by NikolajBjorner** [comment]
quaranteenwhile, the build got broken and was updated.
You will be able to install from the Nightly.
