### ISSUE TITLE
How to use set-option from the .NET API?

### ISSUE THREAD

**Issue by tompazourek** [Z3Prover/z3#4943]
Is there a way of setting options using the .NET bindings?

The only workaround I could find was using `.FromString` and SMT string as follows:

```csharp
var optimize = ctx.MkOptimize();
optimize.FromString("(set-option :opt.priority pareto)");
```

Is there a better way?

**Comment by NikolajBjorner** [comment]
The optimize object has a Params property. It is settable. 
You can also set parameters one by one using the "Set" methods.
optimize.Set("priority","pareto");
