### ISSUE TITLE
Is IDE incompatible with x64 OS?

### ISSUE THREAD

**Issue by EinNarr** [Z3Prover/z3#495]
I tried to Z3 4.3 with ACIDE0.16 on my laptop with uses Windows 10(x64), but it doesn't work at all. Is there possible incompatibility with x64 systems?

**Comment by wintersteiger** [comment]
Could you provide us with some more details about what exactly isn't working? The IDE you are using shouldn't make a difference, but to compile the code you'll need Python and a compiler, on Windows that would usually come with Visual Studio. We provide both x86 and x64 binaries, so both are supported.

**Comment by delcypher** [comment]
Your question is incredibly vague.

I presume you're talking about this?

http://www.fdi.ucm.es/profesor/fernan/acide/index.html

Z3 can be built for Windows x64 so this sounds like an issue you should be asking the "acide" developers.

> but it doesn't work at all

You're going to have to give information than that for anyone to help you.

**Comment by EinNarr** [comment]
@wintersteiger @delcypher I am sorry for being not clear enough. Yes, I was using http://www.fdi.ucm.es/profesor/fernan/ACIDE/html/z3.html , found in the wiki. It reports nearly every command in SMT2, like `declare-const`, "not recognized as an internal or external command, operable program or batch file".
Thanks for your help.

**Comment by NikolajBjorner** [comment]
It is better to check with the ones behind that particular bundling what is going on.
You can download Z3 from https://github.com/Z3Prover/bin, which we maintain.
