### ISSUE TITLE
facility for reading goals?

### ISSUE THREAD

**Issue by Adorf** [Z3Prover/z3#496]
Is there a reader in Z3 by which one could read in goals of the syntactic form

```
(goals
  (goal 
    c11
    c12
    ...)
  (goal
    c21
    c22
    ..)
  ...
)
```

Here the cij are constraints that would normally be asserted.

**Comment by NikolajBjorner** [comment]
No there is no such facility

**Comment by Adorf** [comment]
The reason why I am asking is this: suppose I wanted to use Z3's rich assortment of tactics for preprocessing. Then I might want to sneak in a tactic (say partition) that hasn't made it yet into the Z3 basket. For this I would use apply and get hold of the external representation of Z3's goal structure. I could then use my own external preprocessor code, and afterwards read the modified goal structure back in into Z3.

Do you think a goal-structure reader might be relatively easy to implement in Z3, even for an outsider like me?
