### ISSUE TITLE
Assertion error at src/nlsat/nlsat_interval_set.cpp

### ISSUE THREAD

**Issue by rainoftime** [Z3Prover/z3#4961]
Hi, for the following formula
z3 2d1684bc2d26
[file.txt](https://github.com/Z3Prover/z3/files/5861885/file.txt)
~~~~
ASSERTION VIOLATION
File: ../src/nlsat/nlsat_interval_set.cpp
Line: 97
sign <= 0
(C)ontinue, (A)bort, (S)top, (T)hrow exception, Invoke (G)DB
~~~~

~~~~
(set-option :model_validate true)
(set-option :rewriter.arith_lhs true)
(set-option :nlsat.minimize_conflicts true)
(set-option :nlsat.shuffle_vars true)
~~~~

**Comment by NikolajBjorner** [comment]
There is a patch. It requires agreement of 10 decimal digits to hit the buggy Sturm code now. So it is for many practical purposes shielded. It will be a bit trickier to exercise the buggy code even though it is still reachable.
