### ISSUE TITLE
Combined solver and "canceled" exceptions

### ISSUE THREAD

**Issue by martin-neuhaeusser** [Z3Prover/z3#497]
In the combined solver (i.e. src/solver/combined_solver.cpp), exceptions that arise during the incremental solving with solver2 are not caught. The code seems to rely on the fact that the incremental solver returns l_undef when a timeout occurs. However, if a canceled exception occurs, the non-incremental solver is not triggered any more (the remainder of the check_sat function is skipped).

This has the effect that in an incremental solver with a short solver2_timeout and a larger value for the timeout parameter, entire calls to check_sat are aborted too early (i.e. much before the overall timeout actually has expired) due to an uncaught "canceled" exception from the incremental solver2.

A patch that solves the problem in my experiments is available here:
https://github.com/martin-neuhaeusser/z3/tree/incremental_fix

**Comment by NikolajBjorner** [comment]
Slightly different from your fix, but should be similar effect.
