### ISSUE TITLE
Difference in optimization results between V4.8.5 and V4.8.6~10

### ISSUE THREAD

**Issue by eto10** [Z3Prover/z3#4978]
Hi, I'm testing a lexicographic multi-objective optimization using BV and Boolean data types.
All the codes were working fine in V4.8.5.
However, the later releases including V4.8.10 produce different optimization results for the second objective.
The below link is a reproducible code.
[repro.smt2](https://github.com/eto10/repro/blob/master/repro.smt2)
For the above reproducible code, the results of the first/second objective should be 17 and 1, respectively.
V4.8.5 produces the right optimization results, however, the later versions of z3 produce the results of 17 and 0.
This probably not related to the lexicographic method because when we just run the code only with 
the second objective without using lexicographic optimization, the later versions still produce 
the result of 0 instead of 1 while V4.8.5 produces the result of 1.

**Comment by NikolajBjorner** [comment]
This is fixed. The regression appears to be introduction of unsound xor reduction. This code remains present but unreachable as xor reasoning is disabled.
The xor solver should also be separated.
