### ISSUE TITLE
make issue Cygwin

### ISSUE THREAD

**Issue by proteusGIT** [Z3Prover/z3#4988]
I believe to have followed the installation instructions for Windows/Cygwin but make fails.
How to provide more info?
Can you replicate the problem?

```
$ git clone https://github.com/Z3Prover/z3.git
(..)
$ CXX=x86_64-w64-mingw32-g++ CC=x86_64-w64-mingw32-gcc AR=x86_64-w64-mingw32-ar /usr/bin/python scripts/mk_make.py
(..)
Makefile was successfully generated.
  compilation mode: Release
Type 'cd build; make' to build Z3
$ cd build
$ make
(..)
src/ast/value_generator.cpp
src/ast/well_sorted.cpp
src/math/subpaving/subpaving.cpp
src/math/subpaving/subpaving_hwf.cpp
src/math/subpaving/subpaving_mpf.cpp
src/math/subpaving/subpaving_mpff.cpp
make: *** [Makefile:523: math/subpaving/subpaving_mpff.o] Error 1
```

**Comment by wintersteiger** [comment]
I can't reproduce this, but I haven't upgraded my Cygwin packages recently. Does the compiler segfault without producing any messages at all?

**Comment by proteusGIT** [comment]
This is everything I get.
If a log is produced, I do not where it could be. 
If a log could be produced, I do not know how.
I believe that my Cygwin installation is up to date.
We could compare versions of used tools: which would you recommend?

**Comment by wintersteiger** [comment]
I'm using 

    $ x86_64-w64-mingw32-g++ --version
    x86_64-w64-mingw32-g++ (GCC) 10.2.0

But, there are so many other tools and libraries involved that it probably doesn't mean mine behave the same way as yours.

When you try to `make`, does it always fail at the same file? If so, you can run, e.g. 

    make math/subpaving/subpaving_mpff.o -n

to see the exact command it tries to run. 

Also, check that you don't run out of memory or disk space, just in case.

**Comment by proteusGIT** [comment]
I also cannot replicate it anymore. It compiles now without any modification from my side. Thanks.
