### ISSUE TITLE
Reducing overhead of Python API

### ISSUE THREAD

**Issue by calebwin** [Z3Prover/z3#4993]
I'm experiencing significant overhead of creating symbolic variables and expressions with the Python API. The actual solving takes 600ms while creating variables and expressions takes 30+s (my goal is to get the whole process under 5-10s). Also, I'm only using qfnra-nlsat with integers and booleans. I understand that there isn't a whole lot I can do without switching to pySMT or working with the C API directly. And I am trying to reduce the amount of variables and expressions I need as there is quite a bit of redundancy. In general though, are there any ways I can optimize the way I submit constraints to the solver? Some ideas I had were:

- Cache variables and constraint expressions for use in a different solver (that has been reset)
- Use `z3.IntVal` instead of `z3.Int` followed by an assertion
- `solver.add` constraints separately instead of `z3.And`ing them (in general, avoid complex nested expressions)

Would be great to hear thoughts on this.

**Comment by NikolajBjorner** [comment]
This is a super high-level question. To start with, run a profiler. Try running python with debug assertions disabled.
Some high overhead issues have been because users walk a DAG as if it is a tree and therefore end up traversing the same nodes repeatedly.

**Comment by calebwin** [comment]
Thanks for your response. I understand, however, do you think these strategies make sense to reduce overhead?

> - Cache variables and constraint expressions for use in a different solver (that has been reset)
> - Use z3.IntVal instead of z3.Int followed by an assertion whenever it is possible to do so
> - solver.add constraints separately instead of z3.Anding them (in general, avoid complex nested expressions)

**Comment by NikolajBjorner** [comment]
Sure, if you avoid rebuilding expressions over Python you save the overhead within Python object wrappers.
