### ISSUE TITLE
Python API: The overhead of pop() has been increasing 

### ISSUE THREAD

**Issue by BinGuiEthan** [Z3Prover/z3#4995]
In the Python API, the pop() function of the incremental solver will become slower and slower during running，the number of constraints I push is the same every time.

I ran the same code repeatedly, the pop() only takes a few milliseconds in the beginning,  but the overhead of pop() will become hundreds of seconds in the end. If there are more iterations, I think the time will continue to increase.

**Comment by NikolajBjorner** [comment]
There is a performance bottleneck.
You can save your trail using Z3_open_log into a self-contained text file and then it is easier to run a profiler on top of the interaction.

**Comment by BinGuiEthan** [comment]
Thanks for your reply, so does that means rather than using Z3's built in pop() and push() to store the stack assertions, using my own external log file to keep the assertions?
Thanks!

**Comment by NikolajBjorner** [comment]
No, that is not what I meant. I asked if you could provide a repro for your scenario. In this way I can profile what is happening and maybe address the performance overhead.

**Comment by mmuesly** [comment]
I think this not specific to the Python API. I observed something similiar debugging a performance regression after updating jconstraints to Z3-4.8.10.

Incremental Solving and push/pop-operations seems to interfere significantly with the runtime of newer Z3 versions.

The following example:
```
(set-logic QF_S)
(set-option :produce-models true)
(set-info :status sat)

(declare-fun parameter () String)
(declare-fun a () String)
(declare-fun index () Int)
(declare-fun str1 () String)
(declare-fun index1 () Int)
(declare-fun sli () String)
(declare-fun index2 () Int)

(assert  (and (= parameter "eOfferCode")
         (= index (str.indexof a parameter 0) )
         (ite (not (= index (- 0 1) ) )
             (and (= str1 (str.substr a index (- (str.len a) index) ) )
                  (= index1 (str.indexof str1 "&" 0) )
                  (ite (= index1 (- 0 1) )
                       (and (= index2 (str.indexof str1 "=" 0) )
                            (= sli (str.substr str1 (+ index2 1) (- (str.len str1) (+ index2 1) ) ) )
                       )
                       (and (= index2 (str.indexof str1 "=" 0) )
                            (= sli (str.substr str1 (+ index2 1) (- index1 (+ index2 1) ) ) )
                       )
                  )
             )
             (= sli "")
        )
        (not (= sli "") )
        ))


(check-sat)
(get-model)

```

Could be extended by push and pop operations:

```
(set-logic QF_S)
(set-option :produce-models true)
(set-info :status sat)

(declare-fun parameter () String)
(declare-fun a () String)
(declare-fun index () Int)
(declare-fun str1 () String)
(declare-fun index1 () Int)
(declare-fun sli () String)
(declare-fun index2 () Int)


(push)

(assert  (and (= parameter "eOfferCode")
         (= index (str.indexof a parameter 0) )
         (ite (not (= index (- 0 1) ) )
             (and (= str1 (str.substr a index (- (str.len a) index) ) )
                  (= index1 (str.indexof str1 "&" 0) )
                  (ite (= index1 (- 0 1) )
                       (and (= index2 (str.indexof str1 "=" 0) )
                            (= sli (str.substr str1 (+ index2 1) (- (str.len str1) (+ index2 1) ) ) )
                       )
                       (and (= index2 (str.indexof str1 "=" 0) )
                            (= sli (str.substr str1 (+ index2 1) (- index1 (+ index2 1) ) ) )
                       )
                  )
             )
             (= sli "")
        )
        (not (= sli "") )
        ))


(check-sat)
(get-model)
(pop)
```

Observed runtimes: 
- Z3 in version 4.8.8 official osx build has small change in runtime: 4.5 -> 6.2 seconds
- Z3 in version 4.8.10 official osx build changes from : 16s -> 125s

I have seen some changes in the Commit log regarding string solving. Therefore I have a recent master build, but timing is still changed from 10s -> 20s.  Running through the Java API as used in jConstraints, solving times change from 10s -> 60s due to the usage of push/pop-operations.

I tried to model the Problem in the Java API in the same way, we encode the problem in jConstraints to reproduce the solving times. But apparently my handwritten model is not a perfect match from the jconstraints encoding.

With the mentioned recent Z3 build, timing changes the other way for my handwritten model from 10s (without push/pop) -> 1s (with push/pop)

Here is my Java Example:

```
import com.microsoft.z3.BitVecSort;
import com.microsoft.z3.BoolSort;
import com.microsoft.z3.Context;
import com.microsoft.z3.Expr;
import com.microsoft.z3.IntSort;
import com.microsoft.z3.Model;
import com.microsoft.z3.SeqSort;
import com.microsoft.z3.Solver;
import com.microsoft.z3.Status;

public class Appscan1Example {
    Context ctx = new Context();
    public static void main(String args[]){
      Appscan1Example c = new Appscan1Example();
      c.runExample();
    }

    public void runExample(){

      Solver s = ctx.mkSolver();

      s.push();
      //Var defs
      Expr<SeqSort<BitVecSort>> a = ctx.mkConst("a", ctx.getStringSort());
      Expr<SeqSort<BitVecSort>> param = ctx.mkConst("parameter", ctx.getStringSort());
      Expr<SeqSort<BitVecSort>> str1 = ctx.mkConst("str1", ctx.getStringSort());
      Expr<SeqSort<BitVecSort>> sli = ctx.mkConst("sli", ctx.getStringSort());

      Expr<IntSort> index = ctx.mkFreshConst("index", ctx.getIntSort());
      Expr<IntSort> index1 = ctx.mkFreshConst("index1", ctx.getIntSort());
      Expr<IntSort> index2 = ctx.mkFreshConst("index2", ctx.getIntSort());

      //Constants used
      Expr<IntSort> c0 = ctx.mkInt(0);
      Expr<IntSort> c1 = ctx.mkInt(1);
      Expr<SeqSort<BitVecSort>> sC1 = ctx.mkString("eOfferCode");

      //Assert One
      Expr<BoolSort> firstAssert = ctx.mkEq(param, sC1);

      //Assert Two
      Expr<IntSort> secondAssertPart2 = ctx.mkIndexOf(a, param, c0);
      Expr<BoolSort> secondAssert = ctx.mkEq(index, secondAssertPart2);

      //Assert Three
      //Condition outer ite
      Expr<IntSort> minus = ctx.mkSub(c0, c1);
      Expr<BoolSort> condition = ctx.mkEq(index, minus);
      condition = ctx.mkNot(condition);

      //then outer ite
      Expr<IntSort> strLenA = ctx.mkLength(a);
      Expr<IntSort> andPart1Sub = ctx.mkSub(strLenA, index);
      Expr<SeqSort<BitVecSort>> subStrPart1 = ctx.mkExtract(a, index, andPart1Sub);
      Expr<BoolSort> andPart1 = ctx.mkEq(str1, subStrPart1);

      Expr<IntSort> rightSidePart2 = ctx.mkIndexOf(str1, ctx.mkString("&"), c0);
      Expr<BoolSort> andPart2 = ctx.mkEq(index1, rightSidePart2);

      //inner condition
      Expr<BoolSort> innerCondition = ctx.mkEq(index1, minus);

      //inner then
      Expr<IntSort> thenIndexOf = ctx.mkIndexOf(str1, ctx.mkString("="), c0);
      Expr<BoolSort> thenPart1 = ctx.mkEq(index2, thenIndexOf);

      Expr<IntSort> strLenStr1 = ctx.mkLength(str1);
      Expr<IntSort> subStrToThen = ctx.mkSub(strLenStr1, ctx.mkAdd(index2, c1));
      Expr<SeqSort<BitVecSort>> substrThen = ctx.mkExtract(str1, ctx.mkAdd(index2, c1), subStrToThen);
      Expr<BoolSort> thenPart2 = ctx.mkEq(sli, substrThen);

      Expr<BoolSort> innerThen = ctx.mkAnd(thenPart1, thenPart2);

      //inner else
      Expr<IntSort> elseIndexOf = ctx.mkIndexOf(str1, ctx.mkString("="), c0);
      Expr<BoolSort> elsePart1 = ctx.mkEq(index2, thenIndexOf);

      Expr<IntSort> subStrToElse = ctx.mkSub(index1, ctx.mkAdd(index2, c1));
      Expr<SeqSort<BitVecSort>> substrElse = ctx.mkExtract(str1, ctx.mkAdd(index2, c1), subStrToElse);
      Expr<BoolSort> elsePart2 = ctx.mkEq(sli, substrElse);
      Expr<BoolSort> innerElse = ctx.mkAnd(elsePart1, elsePart2);

      Expr<BoolSort> andPart3 = ctx.mkITE(innerCondition, innerThen, innerElse);

      Expr<BoolSort> outerThen = ctx.mkAnd(andPart1, andPart2, andPart3);

      //else outer ite
      Expr<BoolSort> outerElse = ctx.mkEq(sli, ctx.mkString(""));

      Expr<BoolSort> outerIte = ctx.mkITE(condition, outerThen, outerElse);

      //Assert Four
      Expr<BoolSort> fourthAssert = ctx.mkNot(ctx.mkEq(sli, ctx.mkString("")));

      Expr<BoolSort> conjunction = ctx.mkAnd(firstAssert, secondAssert, outerIte, fourthAssert);
      s.add(conjunction);
      Status status = s.check();
      System.out.println("Result: " + status);
      Model m = s.getModel();
      s.pop();
      System.out.println(m.toString());
     }
}
```

Do you have any idea what causes these runtime differences?

**Comment by NikolajBjorner** [comment]
Z3 has vastly different runtimes on string benchmarks depending on starting points.
You can try to run z3 with different values of smt.random_seed. You will observe different runtimes.
It's likely that bug-fixes in the sequence solver also introduces runtime regressions, but I can't fix them on an ad-hoc basis.

The title of the issue seems missleading: you are only using a single invocation of pop. The time solving the example far exceeds the time taken in pop. When there is no push/pop, Z3 is able to take advantage of stronger pre-processing sometimes making a big difference.

**Comment by mmuesly** [comment]
Thank you for the clarification Nikolaj,

I was not aware of the differences in single query optimizations compared to incremental solving. I will keep this in mind for the design of solver interaction in the future.

**Comment by BinGuiEthan** [comment]
Thanks for your explanation Nikolaj,

I used the built-in Python3.7 in the Jupyter notebook before, and the time of pop() will increase with the increase of the number of calls. When I upgraded to Python 3.8, this problem disappeared.

Thanks for the information about smt.random_seed, I will pay attention to it.

Thanks for your time.

**Comment by BinGuiEthan** [comment]
Thanks for your explanation Nikolaj,

I used the built-in Python3.7 in the Jupyter notebook before, and the time of pop() will increase with the increase of the number of calls. When I upgraded to Python 3.8, this problem disappeared.

Thanks for the information about smt.random_seed, I will pay attention to it.

Thanks for your time.

**Comment by NikolajBjorner** [comment]
It is obviously possible that pop has internal overhead in Z3 for some classes of formulas. It just happens that your repro has nothing to do with such an observation.
