### ISSUE TITLE
Python API - Optimize.add_soft(): NameError: name 'iterable' is not defined

### ISSUE THREAD

**Issue by jecalles** [Z3Prover/z3#4997]
"iterable" should be "Iterable" (z3.py, line 7502). from collections.abc import Iterable
-----------------
From traceback: 
"""
~/.local/share/virtualenvs/{my_virtual_env_name}/lib/python3.8/site-packages/z3/z3.py in add_soft(self, arg, weight, id)
   7500             v = Z3_optimize_assert_soft(self.ctx.ref(), self.optimize, a.as_ast(), weight, id)
   7501             return OptimizeObjective(self, v, False)
-> 7502         if isinstance(arg, iterable):
   7503             return [asoft(a) for a in arg]
   7504         return asoft(arg)

NameError: name 'iterable' is not defined
"""

**Comment by NikolajBjorner** [comment]
fixed
