### ISSUE TITLE
Missing code in complex.py example

### ISSUE THREAD

**Issue by jerluc** [Z3Prover/z3#5]
Not sure if this is correct (it surely doesn't run for me as-is), but the complex.py code example is missing the body for the function `pow` @ [line 69](https://github.com/Z3Prover/z3/blob/master/examples/python/complex/complex.py#L69). I'd certainly love to provide a fix for this, but I have no clue what goes here :)

**Comment by wintersteiger** [comment]
This has been fixed some time ago in the unstable branch (by removing the function), but the unstable branch hasn't been released into master yet.
