### ISSUE TITLE
Quantifiers: unsolvable formulas with ForAll & Function

### ISSUE THREAD

**Issue by orsinium** [Z3Prover/z3#5019]
I'm not sure if it's kind of issues that should be reported but z3 (`z3-solver==4.8.10.0`) freezes on simple formulas using `ForAll` with `Function` in the body. For example:

```python
import z3
x = z3.Int('x')
f = z3.Function('f', z3.IntSort(), z3.IntSort())
z3.solve(z3.ForAll([x], f(x) > x))
```

The only solvable case I found is when you explicitly give the exact value for function using `==`. Even so, it fails to simplify such equations. For example:

```python
# solved
z3.solve(z3.ForAll([x], f(x) == x * 2))
# [f = [else -> 2*Var(0)]]

# freezes
z3.solve(z3.ForAll([x], f(x)/2 == x))
```

**Comment by NikolajBjorner** [comment]
You would have to feed Z3 with a template space of possible interpretations for f in order for the quantifier solver to figure out that there is an interpretation for f with an infinite range. The default quantifier reasoning only establishes satisfiability when functions can be interpreted with finite ranges.
