### ISSUE TITLE
C++ API Memory Leak

### ISSUE THREAD

**Issue by whaaswijk** [Z3Prover/z3#502]
I am running into some memory leaks using Z3 C++ API. For example, see this very simple program adapted from the C++ API examples:
`#include<vector>
#include"z3++.h"

using namespace z3;

int main(void) {
 std::cout << "de-Morgan example\n";

 context c;

 expr x = c.bool_const("x");
 expr y = c.bool_const("y");
 expr conjecture = !(x && y) == (!x || !y);

 solver s(c);
 // adding the negation of the conjecture as a constraint.
 s.add(!conjecture);
 std::cout << s << "\n";
 switch (s.check()) {
     case unsat:   std::cout << "de-Morgan is valid\n"; break;
     case sat:     std::cout << "de-Morgan is not valid\n"; break;
     case unknown: std::cout << "unknown\n"; break;
 }

 return 0;
}`

Running this through Valgrind reports 75 errors and about 25K memory lost. I'm using Apple LLVM 7.0.2 (clang-700.1.81) on OSX 10.10.5 and the latest revision of Z3's master branch. Am I using the API incorrectly here?

**Comment by nunoplopes** [comment]
Try calling Z3_finalize_memory() at the end to cleanup Z3's internal state.  In debug mode, it will also report mem leaks on the Z3 side.

**Comment by whaaswijk** [comment]
Great, this solved it!
