### ISSUE TITLE
Z3_get_numeral_double API gives different result in z3 version 4.8.10 compared to z3 version 4.8.4

### ISSUE THREAD

**Issue by chauhansantosh17** [Z3Prover/z3#5022]
we have been using c++ binding z3 version 4.8.4 for some time now for constraint satisfiability. Our constraints can also have floating number/double to representing propositional constraints. A Sample constraints would be:

CarModel=M1 implies chasisLength=999999999999999999999999999999999999999999999999999999.0 (assume very small unit of measure for chasisLength)

Based on our understanding of z3 public API, we identified one way of initializing real sort variable in z3 with double value and retrieve the double value from real sort z3::expr. However, our way doesn’t seems to be consistent across z3 version. The below c++ code snippet is trying to demonstrate the problem by running the same code snippet against different z3 versions(4.8.10 versus 4.8.4). Is this a known issue with Z3_get_numeral_double API?

Also Is there some better way of initializing real sort expr with double value and retrieving double value from real sort z3 expression?

    z3::context c;
    z3::solver z3Solver(c);

    z3::expr floatFam = c.real_const("Length");
    std::string floatValue("999999999999999999999999999999999999999999999999999999"); // 9 repeated 54 times
    char* endBuf = NULL;
    const double doubleValue = strtod(floatValue.c_str(), &endBuf); // strtod return 1.0 * 10e+54
    char buffer[100] = "";
    sprintf_s(buffer, 100, "%.16g", doubleValue);
    z3::expr floatValueExpr = c.real_val(buffer);
    z3::expr lengthBoolFlag = c.bool_const("lengthConst");

    z3Solver.add(lengthBoolFlag == (floatFam == floatValueExpr)); // assert that there is equivalencne relation between lengthConst=true and length=1.0 * 10e+54

    z3::expr modelFam = c.int_const("ModelConst");
    z3::expr value1 = c.int_val(1);
    z3::expr value2 = c.int_val(2);
    z3::expr value3 = c.int_val(3);

    z3Solver.add((modelFam == value1) || (modelFam == value2) || (modelFam == value3)); // add assert to solver stating ModelConst can have three possible values 1, 2, 3
    z3Solver.add(z3::implies((modelFam == value1), lengthBoolFlag)); // add assert stating if ModelConst=1 then lengthConst has be true
    z3Solver.add(modelFam == value1); // assert ModelConst=1

    z3::check_result satVerdict = z3Solver.check();

    if (z3::sat == satVerdict)
    {
        const z3::model z3Model = z3Solver.get_model();
        z3::expr realExpr = z3Model.eval(floatFam); // get the solution for length from the z3 model
        double z3DblValue = 0;
        if (realExpr.is_numeral(z3DblValue))
        {
            z3::expr numeratorExpr = realExpr.numerator(); // get the numerator expr from realExpr
            z3::expr denominatorExpr = realExpr.denominator(); // get the denominator expr from realExpr
            **double numerator = Z3_get_numeral_double(c, numeratorExpr); // When run with z3 version 4.8.10 this returns 9.999 * 10e+53 which is different what was set in the assert, however when run with z3 version 4.8.4 it returns 1.0 * 10e+54 which exactly what was set in the assert.**
            double denominator = Z3_get_numeral_double(c, denominatorExpr); // this returns 1.0
            z3DblValue = numerator / denominator; // 9.999 * 10e+53 is retrieved as solution which violates implies and equivalence assert above
        }
    }

**Comment by NikolajBjorner** [comment]
It doesn't repro on my side, but I found something fishy with converting to double. 
Behavior could potentially be sensitive to the architecture although I would assume modern architectures have resolved these things.

**Comment by NikolajBjorner** [comment]
I believe this is now settled.
