### ISSUE TITLE
Spacer - possible bug with multiple constructors in ADT declarations

### ISSUE THREAD

**Issue by zafer-esen** [Z3Prover/z3#5049]
When given the following input:
```
(set-logic HORN)

(declare-datatypes () ((T (mk_T1 (s1 Int)) (mk_T2 (s2 Int)))))
(define-fun x () T (mk_T1 42))

(assert (= 42 (s1 x)))
(check-sat)
```
Z3 / Spacer throws the error:
```
1.i.smt2 -v:1
Uninterpreted 's1' in <null>:
query!0() :- 
 (not (= 42 (s1 (mk_T1 42)))).

unknown
```
Z3 reports sat for the same input when set-logic is not specified.

The following input on the other hand works as expected:
```
(set-logic HORN)
(declare-datatypes () ((T (mk_T1 (s1 Int)))))
(define-fun x () T (mk_T1 42))
(assert (= 42 (s1 x)))
(check-sat)
```

**Comment by agurfinkel** [comment]
Spacer expects queries in HORN format and might return `unknown` when asked SMT queries that are not strictly HORN.
This is not limited to ADTs.

**Comment by zafer-esen** [comment]
Thanks for the quick response! 

The original problem was in Horn, I was trying to provide a minimal example that fails, I guess it ended up so minimal that it wasn't even Horn anymore :-)

Here is another example which is hopefully in Horn format that suffers from the same issue:

```
(set-logic HORN)

;(declare-datatypes () ((T (mk_T1 (s1 Int))))) ; sat
(declare-datatypes () ((T (mk_T1 (s1 Int)) (mk_T2 (s2 Int))))) ; error

(declare-fun I1 (Int) Bool)

(assert (forall ((y Int)) (or (not (= y (s1 (mk_T1 42)))) (I1 y))))

(check-sat)
```

**Comment by hgvk94** [comment]
The issue is that `s1` is a partial function. Spacer treats partial functions as uninterpreted functions. However, Spacer does not support uninterpreted function applications. Therefore, when Spacer detects uninterpreted function applications in CHC body, it returns unknown.  

This is intended behaviour until ADTs are fully supported. 

We are actively working on supporting ADTs here: https://github.com/hgvk94/z3/tree/racer.

**Comment by agurfinkel** [comment]
Note that in the commented code, `s1` happens to be total since there is only one constructor.

**Comment by zafer-esen** [comment]
That makes sense. I was hoping that maybe I had a mistake in the encoding or maybe some part of it could be reformulated to work-around the issue.

I was actually trying an encoding of heap using the theory of arrays and ADTs, where having partial functions obviously helps due to heap itself being partial, one can test what the object contains using the ADT testers and encode various type and memory safety properties this way. E.g. where an `Int` or a `node` can be used as heap objects:
```
(define-sort Addr() Int)
(declare-datatypes ((HeapObject 0) (node 0))
                   (((O_Int (getInt Int)) (O_node (getnode node)) (unallocated))
                   ((node (h Int) (n Addr)))))

```
Anyway, thank you both for the explanation, will keep an eye out for new versions!

**Comment by agurfinkel** [comment]
While this is reasonable way to encode heap, the current Horn solver does not support ADTs sufficiently well. It would be better to have a more direct encoding, by reducing ADTs (since they are not recursive) before producing Horn clauses.
