### ISSUE TITLE
uninterpreted function with (forall ((x Int)) ... mod x 3) appears to take forever

### ISSUE THREAD

**Issue by nlewycky** [Z3Prover/z3#5050]
This input takes forever:
```
(declare-datatypes () ((SET3 (A3) (B3) (C3))))
(declare-fun to_set3 (Int) SET3)
(declare-fun from_set3 (SET3) Int)
(assert (distinct (from_set3 A3) (from_set3 B3) (from_set3 C3)))
(assert (distinct (to_set3 (from_set3 A3)) (to_set3 (from_set3 B3)) (to_set3 (from_set3 C3))))
(assert (forall ((x3 SET3)) (= (to_set3 (from_set3 x3)) x3)))
(assert (forall ((xint Int)) (= (to_set3 xint) (to_set3 (mod xint 3)))))
(check-sat)
```

If you remove the final line `(assert (forall ((xint Int)) (= (to_set3 xint) (to_set3 (mod xint 3)))))`  then the model is:
```
sat
(
  (define-fun from_set3 ((x!0 SET3)) Int
    (ite (= x!0 C3) 2
    (ite (= x!0 B3) 1
    (ite (= x!0 A3) 0
      3))))
  (define-fun to_set3 ((x!0 Int)) SET3
    (ite (= x!0 1) B3
    (ite (= x!0 2) C3
      A3)))
)
```
I suspect that with the `mod` constraint it's continuously adding new `ite` for the integers. In theory it could instead include the mod as part of the ite expression if it knew that doing so partitioned the infinite integers a finite list of possibilities.

**Comment by NikolajBjorner** [comment]
This is outside the scope of the fragment that Z3's model-based quantifier instantiation engine produces models for.
There are some known results on how to handle a class of formulas where yours would probably fit in well, but they are not part of the supported procedure.
