### ISSUE TITLE
z3 Compile error on Redhat 7

### ISSUE THREAD

**Issue by sjreilly1960** [Z3Prover/z3#5052]
Hi,
I'm trying to compile z3 for Yosys on a Redhat 7 server.
python scripts/mk_make.py runs successfully, but when I cd in build and run make I get;

```
make
src/shell/mem_initializer.cpp
g++: error: unrecognized command line option ‘-std=c++17’
make: *** [shell/mem_initializer.o] Error 1
```

gcc is 4.8.5

Oddly, last week I did get z3 to compile using the same commands and looking back at config.mk file then shows that -std=c++11
I tried changing that in the latest compile and got;

```
make
src/shell/mem_initializer.cpp
In file included from ../src/util/params.h:22:0,
                 from ../src/util/gparams.h:21,
                 from ../src/shell/mem_initializer.cpp:3:
../src/util/vector.h: In member function ‘void vector<T, CallDestructors, SZ>::expand_vector()’:
../src/util/vector.h:82:17: error: ‘is_trivially_copyable’ is not a member of ‘std’
             if (std::is_trivially_copyable<T>::value) {
                 ^
../src/util/vector.h:82:45: error: expected primary-expression before ‘>’ token
             if (std::is_trivially_copyable<T>::value) {
                                             ^
../src/util/vector.h:82:46: error: ‘::value’ has not been declared
             if (std::is_trivially_copyable<T>::value) {
                                              ^
make: *** [shell/mem_initializer.o] Error 1
```

Steve

**Comment by wintersteiger** [comment]
This means Z3 requires C++17, but your compiler doesn't support that. Redhat 7 was released in 2014, so it may well be that it doesn't have a convenient package to get a more recent compiler.

**Comment by andrewvaughanj** [comment]
You could try using the Red Hat "Software Collections" to get GCC 8.3: https://www.softwarecollections.org/en/scls/rhscl/devtoolset-8/

Based on [this](https://gcc.gnu.org/projects/cxx-status.html), it seems that most of C++17 was implemented by the time GCC 7 came out.

**Comment by NikolajBjorner** [comment]
We are moving onwards to C++17 since last week, yes. 
Currently all code also compiles with C++11, but this will later change when starting to take advantage of useful language features introduced in C++17. C++17 was already around before 2017 so is already relatively old.

**Comment by rainoftime** [comment]
Many servers/IOT devices/etc. use older versions of OS, complilers😃

**Comment by NikolajBjorner** [comment]
and the intersection that are used for compiling z3 is...?

**Comment by rainoftime** [comment]
> and the intersection that are used for compiling z3 is...?

c++11😃 I am in favor of c++17 or newer features. But for some Centos/Redhat/etc users, it might be a bit inconvenient to update the tool chain.

**Comment by NikolajBjorner** [comment]
We already build nightly with centos for the python pip package.
The following version, manylinux2010_x86_64 seems content. 
The version manylinux1 stopped working well for independent reasons and I didn't hear about anybody missing it.

**Comment by sjreilly1960** [comment]
SOLVED
Thanks everyone.
I loaded module for GCC 6.4.0 and it compiled fine.
