### ISSUE TITLE
Install and Building Problem in Windows 

### ISSUE THREAD

**Issue by fred26** [Z3Prover/z3#5058]
Hi, I just followed the instructions to build z3 on Windows with Command Prompt for VS2019

[https://github.com/Z3Prover/z3/wiki/Using-Z3Py-on-Windows](url)

Everything ran smoothly with the python scripts/mk_make.py -x

`Writing build\Makefile
Copied Z3Py example 'all_interval_series.py' to 'build\python'
Copied Z3Py example 'example.py' to 'build\python'
Copied Z3Py example 'mini_ic3.py' to 'build\python'
Copied Z3Py example 'mini_quip.py' to 'build\python'
Copied Z3Py example 'parallel.py' to 'build\python'
Copied Z3Py example 'rc2.py' to 'build\python'
Copied Z3Py example 'socrates.py' to 'build\python'
Copied Z3Py example 'trafficjam.py' to 'build\python'
Copied Z3Py example 'union_sort.py' to 'build\python'
Copied Z3Py example 'visitor.py' to 'build\python'
Makefile was successfully generated.
  compilation mode: Release
  platform: x64`

When I do nmake, it starts compiling up to a point I receive the following error:

`NMAKE : fatal error U1071: cycle in dependency tree for target 'smt\seq_axioms.h.node' Stop`

I appreciate any help on this.

Thanks.

**Comment by Sotam** [comment]
I had the samen when I checked out master, after I switch to version 4.8.10 I was able to build is succesfully :-)

**Comment by fred26** [comment]
Ok thanks. Solved

**Comment by CatChenal** [comment]
> I had the same when I checked out master, after I switch to version 4.8.10 I was able to build is succesfully :-)
@Sotam, would you mind telling which command you use to 'switch to version 4.8.10'?
(I too got the same error because I clone the current master.)
