### ISSUE TITLE
Strange rewrite proof step

### ISSUE THREAD

**Issue by m-fleury** [Z3Prover/z3#5063]
I am trying to update the Z3 version used by Isabelle to the newest version. The following problem generates an odd proof: 

```
; smt.random_seed=1 smt.refine_inj_axioms=false -T:1000000 -smt2
(set-option :produce-proofs true)
(set-logic AUFLIA)
(declare-fun p$ () Bool)
(declare-fun q$ () Bool)
(declare-fun r$ () Bool)
(assert (! (not (=> (and (or p$ q$) r$) (or (and p$ r$) (and q$ r$)))) :named a0))
(check-sat)
(get-proof)
```

The proof (the strange rewrite is the same in 4.8.10 and in master):

```
unsat
((set-logic AUFLIA)
(proof
       (let (($x56 (not q$)))
        (let (($x29 (and q$ r$)))
        (let (($x42 (not $x29)))
        (let (($x38 (not (or (and p$ r$) $x29 (not (and (or p$ q$) r$))))))
        (let (($x32 (not (=> (and (or p$ q$) r$) (or (and p$ r$) $x29)))))
        (let ((@x36 (mp (asserted $x32) (rewrite (= $x32 $x38)) $x38)))
        (let ((@x43 (not-or-elim @x36 $x42)))
        (let (($x69 (not p$)))
        (let (($x28 (and p$ r$)))
        (let (($x37 (not $x28)))
        (let ((@x40 (not-or-elim @x36 $x37)))
        (let ((@x66 (monotonicity (iff-false (mp @x40 (rewrite (= $x37 $x69)) $x69) (= p$ false)) (iff-false (mp @x43 (rewrite (= $x42 $x56)) $x56) (= q$ false)) (= (or p$ q$) (or false false)))))
        (let ((@x50 (trans @x66 (rewrite (= (or false false) false)) (= (or p$ q$) false))))
        (let (($x25 (or p$ q$)))
        (let (($x27 (and $x25 r$)))
        (let ((@x44 (not-or-elim @x36 $x27)))
        (let ((@x45 (and-elim @x44 $x25)))
        (mp @x45 @x50 false))))))))))))))))))))
```

The step `rewrite (= $x37 $x69)` of `@x40` is odd. Unless I am mistaken, it means that `(not  (and p$ r$)) = (not p$)` which is incorrect (`p$` = True and `r$` = False).

I have two questions: 

1. am I misunderstanding the proof here?
2. is there an up-to-date description of what rules do? (I am looking for something more recent than Sascha Böhme's papers)

**Comment by NikolajBjorner** [comment]
The proof step is not well formed. It happens during constant propagation. Some variables are assigned constant values and this information is in the context. The rewrite proof step does not record this assumption. I have disabled value propagation in proof mode. The simplification was sound, but the proof was not well formed.

Generally, I would like to move away from these proof objects entirely and use some more modular approaches inspired by DRAT/DRUP and friends, We could call it DRUP(T) or DRAT(T). A proof checker for logs that extend DRAT with some SMT relevant information (logs which expressions are built and theory axioms) or a consumer of such logs into Isabelle tactics may be the way to go forward. A disclaimer is that current development does not include pre-processing where you found the issue. I will not have bandwidth to overhaul the preprocessor from its current structure for some time.

**Comment by m-fleury** [comment]
I saw the discussion on DRUP(T). I fear that it will move a lot of work into Isabelle (like tracking dependencies to reduce the proof size), but the whole idea is interesting. I am also not sure how hard reconstructing the theory tautologies will become however.

Anyway, as long as DRUP(T) does not support quantifiers, it does not make sense for me to implement support in Isabelle.


Thanks for fixing the issue so fast!

**Comment by NikolajBjorner** [comment]
Supporting quantifiers is not implemented yet, but then the code that creates this trace isn't ready for prime time either and dealing with quantifiers is straight-forward. So far we only use instantiation rules. So it would add axioms of the form 
(=> (forall (x) Phi(x)) Phi(t)) and probably for ease of post-processing list the binding t on the side like PR_QUANT_INST does.
