### ISSUE TITLE
`int.to.str` of negative integer results in the empty string

### ISSUE THREAD

**Issue by joukestoel** [Z3Prover/z3#5064]
The following formula returns `sat` because the `int.to.str` operation on a negative integer results in the empty string:

```
(assert (= "" (int.to.str (- 1))))
(check-sat)
```

This is the case for both string solvers (seq and z3str3)

**Comment by NikolajBjorner** [comment]
This complies with http://smtlib.cs.uiowa.edu/theories-UnicodeStrings.shtml

**Comment by joukestoel** [comment]
HI @NikolajBjorner, thanks for elaborating. 

I guess two custom str.to.int and int.to.str functions can bypass this problem like so:
```
(define-fun cus.int.to.str ((i Int)) String
  (ite (< i 0) (str.++ "-" (int.to.str (* -1 i) )) (int.to.str i))
)

(define-fun cus.str.to.int ((s String)) Int
  (ite (str.prefixof "-" s) (- (str.to.int (str.substr s (- (str.len s) 1) 1) )) (str.to.int s))
)
```

Is there any reason the theories of UnicodeStrings explicitly disallows this behaviour?

**Comment by NikolajBjorner** [comment]
The original implementation in z3 was signed, but the SMTLIB2 standard decided to use unsigned conversion. 
Given that you can create macros like the ones you describe there isn't a need for both macros.
Note that your second macro produces the result 1 for the input "-x". The SMTLIB2 standard differentiates strings that do not come from integers.

**Comment by joukestoel** [comment]
Thanks for your comments and for your remark on the custom str.to.int macro. I had indeed not seen this in de UnicodeString comments.
