### ISSUE TITLE
Z3 Static lib binaries too large

### ISSUE THREAD

**Issue by fred26** [Z3Prover/z3#5069]
I have compiled MDd libs for Windows.

The size of the static lib is around 662MB.

I just tried a simple barebone example (attached), but the size of the executable is 54MB (just couple of functions where called)

[Z3Example.zip](https://github.com/Z3Prover/z3/files/6076388/Z3Example.zip)

I read somewhere that is not possible to reduce the binaries files, is this correct?

Any hints on how to reduce the size of the binaries? I won't be able to ship such large files in the final product.

Thanks

**Comment by NikolajBjorner** [comment]
I can't speak for whether the information you read is correct or not.
As an experiment I tried disabling fixedpoint code using a compile time ifndef. The size of the release executable goes from 23MB to 20MB so roughly 10% reduction for fixedpoints. There is not too much more: optimization, and a new core that isn't accessible for users yet. Disabling these could carve a little more out. I am not sure how many need such a feature of disabling components even though the question was posed before. I will probably push the option for disabling fixedpoints but will have to leave it to OS contributions to experiment and develop a proper way. If it is important, I am sure this will inspire a pull request, if not, then it isn't important. 
Something odd with the report above: MDd would be debug build so saving space of a binary seems not an objective there.

**Comment by fred26** [comment]
Thanks @NikolajBjorner
I will try MT releases. MDd was just a test example as was my first build on windows, 
I will try your suggestions. Thanks
