### ISSUE TITLE
Optimization solver broken on current master branch?

### ISSUE THREAD

**Issue by joukestoel** [Z3Prover/z3#5075]
Running the following commands on a local build of the current master branch results in a Segmentation fault:
```
/z3/build$ ./z3 -smt2 -in
(declare-const i Int)
(minimize i)
Segmentation fault: 11
/z3/build$ 
```

Has this to do with my local build or is the optimization solver on master currently broken?
I am on OSx Mojave v10.14.6.

Clang version:
Apple clang version 11.0.0 (clang-1100.0.33.17)
Target: x86_64-apple-darwin18.7.0

**Comment by NikolajBjorner** [comment]
I added this as regression test, it seems to work fine in the build (two flavors of MacOS).

**Comment by joukestoel** [comment]
Okay, thanks for checking. It must be something on my side
