### ISSUE TITLE
possibly unsound fp.rem

### ISSUE THREAD

**Issue by florianschanda** [Z3Prover/z3#508]
Hi,

when using fp.rem I get some very odd results. See below:

(set-logic QF_FP)
(set-option :produce-models true)
(set-info :source |SPARK inspired floating point problems by Florian Schanda|)
(set-info :smt-lib-version 2.5)
(set-info :category crafted)
(declare-const a Float32)
(declare-const b Float32)
(assert (or (fp.isZero a) (fp.isNormal a) (fp.isSubnormal a)))
(assert (or (fp.isNormal b) (fp.isSubnormal b)))
(define-const lo Float32 (fp.neg (fp.abs b)))
(define-const hi Float32 (fp.abs b))
(assert (fp.isPositive a))
(assert (fp.isPositive b))
(define-const r Float32 (fp.rem a b))
(define-const in_bounds Bool (and (fp.leq lo r) (fp.leq r hi)))
(assert (not in_bounds))
(check-sat)
(get-value (in_bounds))
(exit)

And the model returned has in_bounds true. Seems wrong given the (not in_bounds) assertion :)

**Comment by wintersteiger** [comment]
Thanks for the report and the repro! There was indeed a bug in fp.rem when used on denormal numbers, which is now fixed.

**Comment by florianschanda** [comment]
Many thanks for the quick fix :)
