### ISSUE TITLE
Refutational soundness bug on real arithmetic formula 

### ISSUE THREAD

**Issue by wintered** [Z3Prover/z3#5083]
Commit: e804f77

```
$z3release bug.smt2
unsat
$cvc4 -q bug.smt2
sat
$cat bug.smt2
(declare-fun a () Real)
(assert (not (is_int (to_real a))))
(check-sat)
```

**Comment by NikolajBjorner** [comment]
Is this even defined in the standard http://smtlib.cs.uiowa.edu/theories-Reals_Ints.shtml?
The signature of to_real is Int -> Real.

The function to_real takes an integer, so z3 inserts a coercion, so it checks

```
(assert (not (is_int (to_real (to_int a)))))
```
which is unsat.

If you run z3 with the option smtlib2_compliant=true you get an error message.
(error "line 3 column 31: Sort mismatch at argument #1 for function (declare-fun to_real (Int) Real) supplied sort is Real")
