### ISSUE TITLE
get-model response does not start with "(model "

### ISSUE THREAD

**Issue by jwaldmann** [Z3Prover/z3#5109]
Hi. Z3 does not print "model" where other SMT solvers do,
```
 echo "(set-logic QF_LRA)(set-option :produce-models true)(declare-fun X () Real)(assert (< 1 X)) (check-sat) (get-model)" | ./z3 -in -smt2
sat
(      <------- the word "model" is missing here?
  (define-fun X () Real
    2.0)
)
```
Sure I can work around that when I am parsing (https://github.com/hgoes/smtlib2/issues/21)

**Comment by andrewvaughanj** [comment]
This is actually correct. The SMTLIB standard says it shouldn’t start with “model”.

**Comment by andrewvaughanj** [comment]
See: https://github.com/Z3Prover/z3/issues/4807#issuecomment-731551395

**Comment by jwaldmann** [comment]
Ah, I was not aware. Well, I "fixed" my parser to accept both versions, with "model", and without.
