### ISSUE TITLE
Install Z3 through opam failed

### ISSUE THREAD

**Issue by computereasy** [Z3Prover/z3#511]
Hi there, 

I tried to install `z3 ` through `OCaml` package manager `opam` but I got the following error:

`

 `=-=- Processing actions -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
 [ERROR] The compilation of Z3 failed at "python scripts/mk_make.py --ml --prefix  /home/shuai/.opam/4.02.1".
Processing  1/2: [Z3: ocamlfind remove]
 #=== ERROR while installing Z3.dev ============================================#
 # opam-version 1.2.2
 # os           linux
 # command      python scripts/mk_make.py --ml --prefix /home/shuai/.opam/4.02.1
 # path         /home/shuai/.opam/4.02.1/build/Z3.dev
 # compiler     4.02.1
 # exit-code    1
 # env-file     /home/shuai/.opam/4.02.1/build/Z3.dev/Z3-25837-d2c37b.env
 # stdout-file  /home/shuai/.opam/4.02.1/build/Z3.dev/Z3-25837-d2c37b.out
 # stderr-file  /home/shuai/.opam/4.02.1/build/Z3.dev/Z3-25837-d2c37b.err
 ### stderr ###
 # Traceback (most recent call last):
 #   File "scripts/mk_make.py", line 9, in <module>
 #     from mk_util import *
 #   File "/home/shuai/.opam/4.02.1/build/Z3.dev/scripts/mk_util.py", line 15, in <module>
 #     import mk_genfile_common
 #   File "/home/shuai/.opam/4.02.1/build/Z3.dev/scripts/mk_genfile_common.py", line 275
 #     exec(line.strip('\n '), exec_globals)
 # SyntaxError: unqualified exec is not allowed in function 'mk_install_tactic_cpp_internal' it contains a nested function with free variables

Could anyone help me on this issue? Thank you

**Comment by delcypher** [comment]
This is #510 . I'm working on fix but for now you need to build a slightly older version Z3 (e..g 9095d7db441723a1b7471851a1c50bc45ffb8483 ) or use Python 3

**Comment by computereasy** [comment]
@delcypher  Many thanks!

**Comment by delcypher** [comment]
A fix (#513 ) is now available.

**Comment by wintersteiger** [comment]
#513 has been merged; @computereasy could you try again to see whether everything works as expected now?

Aside: Are you a frequent/serious user of the OCaml API? The current version of that API in the master branch is buggy and I have a replacement at in the `new-ml-api` branch on my [fork](https://github.com/wintersteiger/z3/tree/new-ml-api). If you see any problems, could you give the new one a try? Thanks!

**Comment by wintersteiger** [comment]
Looks like this has been resolved; closing the issue.
