### ISSUE TITLE
minimize (something) doesn't.

### ISSUE THREAD

**Issue by tbandrowsky** [Z3Prover/z3#5114]
**Please see the below.  If you remove the constraint "(< endtime 99)", then, Z3 will produce the following output claiming that the minimized endtime is 101.**

**Input**

(declare-fun job (Int) Int)
(declare-fun start (Int) Int)
(declare-fun end (Int) Int)
(declare-const endtime Int)
(define-fun max ((a Int) (b Int)) Int (ite (> a b) a b))

(assert (and 
(= 11 (job 1))
(= 12 (job 2))
(= 13 (job 3))
(= 14 (job 4))
(= 15 (job 5))
(= 16 (job 6))
(= 17 (job 7))
(= 18 (job 8))
(= 19 (job 9))
(= 20 (job 10))

(= (+(start 1)(job 1))(end 1))
(= (+(start 2)(job 2))(end 2))
(= (+(start 3)(job 3))(end 3))
(= (+(start 4)(job 4))(end 4))
(= (+(start 5)(job 5))(end 5))
(= (+(start 6)(job 6))(end 6))
(= (+(start 7)(job 7))(end 7))
(= (+(start 8)(job 8))(end 8))
(= (+(start 9)(job 9))(end 9))
(= (+(start 10)(job 10))(end 10))

(>= (start 3) (end 1) (start 1) 0)
(>= (start 3) (end 2) (start 2) 0)
(>= (start 6) (end 2) (start 2) 0)
(>= (start 6) (end 4) (start 4) 0)
(>= (start 7) (end 1) (start 1) 0)
(>= (start 7) (end 4) (start 2) 0)
(>= (start 7) (end 5) (start 5) 0)
(>= (start 8) (end 3) (start 3) 0)
(>= (start 8) (end 6) (start 6) 0)
(>= (start 9) (end 6) (start 6) 0)
(>= (start 9) (end 7) (start 7) 0)
(>= (start 10) (end 8) (start 8) 0)
(>= (start 10) (end 9) (start 9) 0)

(>= (start 7) (start 8))
(< endtime 99)

(or 
    (<= (start 3) (end 3) (start 4) (end 4) (start 5) (end 5))
    (<= (start 3) (end 3) (start 5) (end 5) (start 4) (end 4))
    (<= (start 4) (end 4) (start 3) (end 3) (start 5) (end 5))
    (<= (start 4) (end 4) (start 5) (end 5) (start 3) (end 3))
    (<= (start 5) (end 5) (start 3) (end 3) (start 4) (end 4))
    (<= (start 5) (end 5) (start 4) (end 4) (start 3) (end 3))
)

(=(max (end 1) 
    (max (end 2) 
        (max (end 3) 
            (max (end 4) 
                (max (end 5) 
                    (max (end 6) 
                        (max (end 7) 
                            (max (end 8) 
                                (max (end 9) (end 10))
                            )
                        )
                    )
                )
            )
        )
    )
) endtime)

))

(minimize endtime)
(check-sat)
(get-model)
(get-value (endtime))

**Output**

endtime |-> 11
sat
(model
  (define-fun endtime () Int
    101)
  (define-fun job ((x!1 Int)) Int
    (ite (= x!1 1) 11
    (ite (= x!1 2) 12
    (ite (= x!1 3) 13
    (ite (= x!1 4) 14
    (ite (= x!1 5) 15
    (ite (= x!1 6) 16
    (ite (= x!1 7) 17
    (ite (= x!1 8) 18
    (ite (= x!1 9) 19
    (ite (= x!1 10) 20
      11)))))))))))
  (define-fun end ((x!1 Int)) Int
    (ite (= x!1 1) 11
    (ite (= x!1 2) 15
    (ite (= x!1 3) 45
    (ite (= x!1 4) 15
    (ite (= x!1 5) 32
    (ite (= x!1 6) 31
    (ite (= x!1 7) 62
    (ite (= x!1 8) 63
    (ite (= x!1 9) 81
    (ite (= x!1 10) 101
      15)))))))))))
  (define-fun start ((x!1 Int)) Int
    (ite (= x!1 1) 0
    (ite (= x!1 2) 3
    (ite (= x!1 3) 32
    (ite (= x!1 4) 1
    (ite (= x!1 5) 17
    (ite (= x!1 6) 15
    (ite (= x!1 7) 45
    (ite (= x!1 8) 45
    (ite (= x!1 9) 62
    (ite (= x!1 10) 81
      45)))))))))))
)
((endtime 101))

**Comment by NikolajBjorner** [comment]
maybe with a previous version of z3, but not reproducible with current master
