### ISSUE TITLE
Inconsistent effect of setting rlimit option

### ISSUE THREAD

**Issue by parno** [Z3Prover/z3#5123]
This [post](https://stackoverflow.com/questions/45457131/what-is-the-relation-between-options-rlimit-and-timeout) suggests it should be possible to set the `:rlimit` option more than once.  However, that doesn't seem to quite work in the example below.  In particular, the first check-sat returns unsat, but the second one fails with unknown.  However, if you uncomment the `:rlimit 1215752192` in the first push-pop context (or comment out the `:rlimit 1000`), then the second check-sat returns unsat.  Similarly, if you remove the first push-pop code entirely, the second returns unsat.  I've tested this with both 4.8.5 and with `master` as of b918f121e.

```
(set-option :smt.qi.eager_threshold 100)

(declare-fun x () Int)

(push 1)
(set-option :rlimit 1000)
; (set-option :rlimit 1215752192)   ; Second check-sat works if you uncomment this line
(assert (not (= (- x x) 0)))
(check-sat)
(pop 1)

(reset)


(set-option :smt.qi.eager_threshold 100)

(declare-fun f (Int Int) Int)
(assert (forall ((i Int) (j Int) ) (! (= (f i j) (ite (= i 0) 0 (+ (f (- i 1) (+ (* i j) 1)) (f (- i 1) (* (* 2 i) j)))))
 :pattern ( (f i j))
)))

(push 1)
(set-option :rlimit 1215752192)
(assert (not (= (f 13 5) 0)))
(check-sat)
(pop 1)
```

**Comment by NikolajBjorner** [comment]
Some work is performed during "push", so you want to reset rlimit before push.

```
(set-option :smt.qi.eager_threshold 100)

(declare-fun x () Int)

(push 1)
(set-option :rlimit 1000)
(assert (not (= (- x x) 0)))
(check-sat)
(pop 1)

(reset)


(set-option :smt.qi.eager_threshold 100)

(declare-fun f (Int Int) Int)
(assert (forall ((i Int) (j Int) ) (! (= (f i j) (ite (= i 0) 0 (+ (f (- i 1) (+ (* i j) 1)) (f (- i 1) (* (* 2 i) j)))))
 :pattern ( (f i j))
)))

(set-option :rlimit 1215752192)  ; Moved up
(push 1)
(assert (not (= (f 13 5) 0)))
(check-sat)
(pop 1)
```

**Comment by parno** [comment]
Thanks, that's helpful to know.  This was simplified from a Boogie file, so I'll talk to the Boogie folks about swapping the ordering of rlimit and push.
