### ISSUE TITLE
performance issue with bv + array

### ISSUE THREAD

**Issue by rod-lin** [Z3Prover/z3#5129]
Hello! I'm trying to understand a performance issue with the following two queries:

**common prelude**
```
(set-option :auto-config false)
(set-option :smt.mbqi false)

(define-sort MInt1 () (_ BitVec 1))
(define-sort MInt8 () (_ BitVec 8))
(define-sort MInt16 () (_ BitVec 16))
(define-sort MInt32 () (_ BitVec 32))
(define-sort MInt64 () (_ BitVec 64))

(define-sort MemoryMap () (Array MInt64 MInt8))

(define-fun select4 ((mem MemoryMap) (p MInt64)) MInt32
  (concat (select mem (bvadd p #x0000000000000003))
          (select mem (bvadd p #x0000000000000002))
          (select mem (bvadd p #x0000000000000001))
          (select mem p))
)

(define-fun store4 ((mem MemoryMap) (p MInt64) (v MInt32)) MemoryMap
  (store
  (store
  (store
  (store mem (bvadd p #x0000000000000003) ((_ extract 31 24) v))
             (bvadd p #x0000000000000002) ((_ extract 23 16) v))
             (bvadd p #x0000000000000001) ((_ extract 15  8) v))
                                        p ((_ extract  7  0) v))
)

(declare-const mem MemoryMap)
(declare-const a MInt64)
(declare-const b MInt64)
(declare-const c MInt64)
(declare-const d MInt64)
(declare-const tmp1 MInt32)
(declare-const tmp2 MInt32)
```

**query1**
```
(assert (not (=>
    (and
        (= a (concat tmp1 tmp2)) ; <- extra formula here
        (= ((_ extract 31 0) a)  ((_ extract 31 0) b))
    )
    (= (store4 (store4 mem d ((_ extract 31 0) a)) c (bvadd (select4 (store4 mem d ((_ extract 31 0) a)) c) #x00000020))
       (store4 (store4 mem d ((_ extract 31 0) b)) c (bvadd (select4 (store4 mem d ((_ extract 31 0) b)) c) #x00000020)))
)))

(check-sat)
```

**query2**
```
(assert (not (=>
    (and
        (= ((_ extract 31 0) a)  ((_ extract 31 0) b))
    )
    (= (store4 (store4 mem d ((_ extract 31 0) a)) c (bvadd (select4 (store4 mem d ((_ extract 31 0) a)) c) #x00000020))
       (store4 (store4 mem d ((_ extract 31 0) b)) c (bvadd (select4 (store4 mem d ((_ extract 31 0) b)) c) #x00000020)))
)))

(check-sat)
```

----

I tried z3 4.8.8, 4.8.9, and 4.8.10 and encountered the same issue.
The second one is much slower than the first one (in fact `(then simplify solve-eqs)` is enough to resolve the first query)
```
$ time z3-4.8.10 query1.smt2
unsat
(:eliminated-vars 1
 :max-memory      2.60
 :memory          2.60
 :num-allocs      191200
 :rlimit-count    1401
 :time            0.01)
(:reason-unknown "")

real    0m0.039s
user    0m0.035s
sys     0m0.004s

$ time z3-4.8.10 query2.smt2
unsat
(:added-eqs           29662060
 :arith-make-feasible 1
 :arith-max-columns   4
 :array-ax1           16
 :array-ax2           1253221
 :array-ext-ax        1
 :binary-propagations 4651929
 :bv-bit2core         17906710
 :bv-diseqs           23
 :bv-dynamic-diseqs   430604
 :bv-dynamic-eqs      43841
 :bv->core-eq         11250015
 :conflicts           1477784
 :decisions           2271827
 :del-clause          128486240
 :dyn-ack             18
 :max-memory          108.53
 :memory              43.95
 :minimized-lits      59151565
 :mk-bool-var         39841387
 :mk-clause           128496569
 :num-allocs          46393255243.00
 :num-checks          1
 :propagations        24226491
 :restarts            1406
 :rlimit-count        131239277
 :time                130.94)
(:reason-unknown "")

real    2m10.962s
user    2m10.896s
sys     0m0.044s
```

I'm not familiar with how the `solve-eqs` tactic or the bit-vector solver in z3 work,
but are there any flags/options that I can use to improve the performance of the second query without
adding the extra clause `(= a (concat tmp1 tmp2))`?

Any help is appreciated! Thank you!

**Comment by NikolajBjorner** [comment]
the problem gets really easy if it can replace (extract a) by (extract b) everywhere. However, preprocessing misses this rewrite.
I am not sure if it is useful to patch pre-processing to handle extract semantics with a heuristic. It is possible, but requires some efforts to support. The new core gobbles up this one:

unsat
(:euf-merge                      55
 :euf-propagations-eqs           1
 :euf-propagations-theory-diseqs 1
 :euf-propagations-theory-eqs    67
 :max-memory                     27.65
 :memory                         17.52
 :num-allocs                     610755
 :rlimit-count                   6862
 :sat-mk-clause-2ary             1794
 :sat-mk-clause-3ary             2126
 :sat-mk-clause-nary             2
 :sat-mk-var                     2238
 :sat-propagations-2ary          1
 :sat-units                      631
 :time                           0.02
 :total-time                     0.03)

**Comment by NikolajBjorner** [comment]
There are some approaches for simplifying bit-vector equations, but they are not integrated as pre-processing at this point.
https://link.springer.com/chapter/10.1007%2F3-540-63166-6_9
http://theory.stanford.edu/people/nikolaj/tacas98.ps.gz
http://citeseerx.ist.psu.edu/viewdoc/summary?doi=10.1.1.175.9922
