### ISSUE TITLE
(Not very important) switch tactic/strategy for this example?

### ISSUE THREAD

**Issue by DennisYurichev** [Z3Prover/z3#514]
Hi!

It's possible for compiler backend to replace slow division operation by multiplication (modulo inverse, etc).
I'm trying to prove one such equivalence:

```
(declare-const x (_ BitVec 64))
(assert 
    (forall ((x (_ BitVec 64)))
    (=
        ((_ zero_extend 64) (bvudiv x (_ bv17 64)))
        (bvlshr (bvmul ((_ zero_extend 64) x) #x0000000000000000f0f0f0f0f0f0f0f1) (_ bv68 128))
    )
        )
)
(check-sat)
(get-model)
```

But Z3 never terminates. Is it possible to switch tactic/strategy to prove this equivalence in reasonable time?

**Comment by NikolajBjorner** [comment]
Thanks for the example. I was wondering whether you really meant to pose the negation to do a satisifiability check. As it turns out, neither this, nor the negation of the formula (checking satisfiability of the negation is the same as proving validity of the original formula) is easy for Z3.

**Comment by dennis714** [comment]
Negation?

**Comment by wintersteiger** [comment]
@MikolasJanota might want to take a look at this example.
