### ISSUE TITLE
.NET Binding - Context.MkSub missing IEnumerable override

### ISSUE THREAD

**Issue by SMTStuck** [Z3Prover/z3#5143]
Within the .NET bindings, the Context class has the following methods:

public ArithExpr MkAdd(IEnumerable<ArithExpr> t);
public ArithExpr MkAdd(params ArithExpr[] t);
public ArithExpr MkMul(IEnumerable<ArithExpr> t);
public ArithExpr MkMul(params ArithExpr[] t);
public ArithExpr MkSub(params ArithExpr[] t);

MkSub does not have the override for an `IEnumerablt<ArithExpr>`. Is this an oversight or is there a reason for this?

**Comment by NikolajBjorner** [comment]
oversight
