### ISSUE TITLE
Invalid optimization model produced

### ISSUE THREAD

**Issue by taburet** [Z3Prover/z3#5148]
```
(declare-const a Int)
(assert (> a 0))
(assert (<= a 63))

(declare-const b Int)
(assert (> b 0))
(assert (<= b 63))

(declare-const c Int)
(assert (> c 0))
(assert (<= c 63))

(declare-const d Int)
(assert (> d 0))
(assert (<= d 63))

(assert (= 63 (+ a b c d)))
(maximize (+ (* a b) (* b c) (* c d)))

(check-sat)
(get-model)
```

The produced model is `a = 35, b = 1, c = 26, d = 1` while it should be `a = 1, b = 30, c = 31, d = 1`. Without the upper bound constraints (`(assert (<= a 63))`, ...) it takes really long time, but able to produce the correct model.

**Comment by NikolajBjorner** [comment]
in light of open nlsat labeled bugs I cannot take optimization bugs that use nlsat and therefore are likely to be related.
There is no specific tuning for non-linear constraints/objectives so it isn't a supported use-case.
