### ISSUE TITLE
ACIDE for MacOS X

### ISSUE THREAD

**Issue by ThisisJOY** [Z3Prover/z3#515]
I want to use ACIDE for MacOS X, but I did not find a zip file that is for OS X from this site: http://www.fdi.ucm.es/profesor/fernan/ACIDE/html/z3.html.

Do you have an ACIDE download for MacOS X?

Thanks.

**Comment by NikolajBjorner** [comment]
It's great that you are interested in Z3 on ACIDE, but I am not sure how we can support this form our side.
Could you use http://www.fdi.ucm.es/profesor/fernan/ACIDE/html/contact.html to report this request?

**Comment by NikolajBjorner** [comment]
Dear Fernando,

There are two recent requests for ACIDE/Z3. I am not sure how to process these requests from our side.
Possible good news may be that you can now build Z3 using cmake, thanks to @delcypher, if it helps.

Nikolaj

**Comment by ThisisJOY** [comment]
Thanks for your reply. Hopefully, I could run on an IDE in the near future. Personally, it would be more convenient to use IDE instead of configuring z3 with individual options and setting paths to enable other languages other than c and c++. That is kind of tricky for me.

**Comment by wintersteiger** [comment]
At the moment there seems to be no other way. Those paths have to be set up by someone, i.e., the ACIDE team or yourself, and at the moment the ACIDE team does not publish packages for OSX, so you'll have to do that yourself. (But I'm sure they'll think about publishing an OSX package if they get enough requests. 

Closing this as not a Z3 problem.

**Comment by NikolajBjorner** [comment]
Fernando asked regarding binary releases.
Note that binary releases, including Mac, are available from https://github.com/z3prover/bin
