### ISSUE TITLE
asking queries in smtlib2 format and parsing resultant models

### ISSUE THREAD

**Issue by SunBeomSo** [Z3Prover/z3#5159]
In OCaml, it is possible to export Z3 expressions into files in smtlib2 format (using api in https://z3prover.github.io/api/html/ml/Z3.SMT.html).

I wonder, whether Z3 provides OCaml apis for parsing resulting models (i.e., getting values for some variables or expressions) when queries in smtlib2 format are asked to Z3 (and the satisfying models are found by Z3).

**Comment by NikolajBjorner** [comment]
Models are printed as SMTLIB2 declarations. The provides a way to round-trip models.
Python example
```
from z3 import *

s1 = Solver()
x, y = Ints('x y')
s1.add(x > y)
s1.check()
m1 = s1.model()
print(m1.sexpr())
ms = m1.sexpr()

s2 = Solver()
s2.from_string(ms)
s2.check()
print(s2.model())
print(s2.model().eval(x))
```
