### ISSUE TITLE
Overloads no longer work in v4.8.9+

### ISSUE THREAD

**Issue by TimSoethout** [Z3Prover/z3#5164]
While rerunning older code with overloads on certain Integer comparisons I found that in the latest release overloads no longer seem to work as they did before.
I debugged it back to the specific versions.

Minimized example:
```smt
(declare-datatypes () (  ( Date (consDate (date Int) (month Int) (year Int)) (undefDate) ) ))

(define-fun > ( (d1 Date) (d2 Date)) Bool
  (and (>  (year  d1) (year  d2))
    (>  (month  d1) (month  d2))
    (>  (date  d1) (date  d2))))

(define-fun fun_int ( (int1 Int) (int2 Int)) Bool
  (> int1 int2))
```

Running in 4.8.9+:
```(error "line 9 column 14: Sort mismatch at argument #1 for function (declare-fun > (Date Date) Bool) supplied sort is Int")```

Output with 4.8.8-: (empty, no error, as what I was expecting)

I don't know if this is a regression or a feature? For now I will use 4.8.8.

On: OSX 10.15.7 using the release build from this repo.

**Comment by NikolajBjorner** [comment]
It will be fixed. Let's see if the attempt introduces regressions.

**Comment by TimSoethout** [comment]
Thanks a lot for the quick response and fix. :D
