### ISSUE TITLE
Timeout on a short file with ite, functions, bitvectors, datatypes

### ISSUE THREAD

**Issue by jad-hamza** [Z3Prover/z3#5168]
Hello, I just wanted to share this example which times out on master (100 seconds).
I guess the issue here is the mix of many features (as you explained here https://github.com/Z3Prover/z3/issues/5103), perhaps the new core will be able to handle that.

This is not really an issue (is there a better place to post such examples?), so feel free to close it.

```smt
(declare-datatypes () ((Wrap (W (n (_ BitVec 32))))))
(declare-fun w1 () Wrap)
(declare-fun w2 () Wrap)
(declare-fun cond () Bool)
(declare-fun prop ((_ BitVec 32)) Bool)
(assert (prop (bvsub (n w1) #b00000000000000000000000000000001)))
(assert (prop (bvsub (n w2) #b00000000000000000000000000000001)))
(assert (not (prop (bvsub (n (ite cond w1 w2)) #b00000000000000000000000000000001))))
(check-sat)
```

**Comment by NikolajBjorner** [comment]
I don't plan to address it in current core, but in the new core it is trivial. 
z3 5168.smt2 tactic.default_tactic=smt /v:1 /st sat.euf=true

**Comment by jad-hamza** [comment]
Perfect thanks, I didn't know about those
