### ISSUE TITLE
"test-z3 /a" fail with unaligned access

### ISSUE THREAD

**Issue by DerDakon** [Z3Prover/z3#5178]
I suspect the ```this``` pointer is somehow wrong when this fails, so I added a breakpoint in ```vector::expand_vector()``` and ran it from the beginning:

```
Breakpoint 1, vector<unsigned long long, false, unsigned int>::expand_vector (this=0xf7ffc068 <_rtld_global>) at /var/tmp/portage/sci-mathematics/z3-4.8.10/work/z3-z3-4.8.10/src/util/vector.h:62
62              if (m_data == nullptr) {
(gdb) bt
#0  vector<unsigned long long, false, unsigned int>::expand_vector (this=0xf7ffc068 <_rtld_global>) at /var/tmp/portage/sci-mathematics/z3-4.8.10/work/z3-z3-4.8.10/src/util/vector.h:62
#1  0xffffc630 in ?? ()
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
(gdb) n
63                  SZ capacity = 2;
(gdb)
64                  SZ * mem    = reinterpret_cast<SZ*>(memory::allocate(sizeof(T) * capacity + sizeof(SZ) * 2));
(gdb)
65                  *mem              = capacity;
(gdb)
66                  mem++;
(gdb)
67                  *mem              = 0;
(gdb)
68                  mem++;
(gdb)
69                  m_data            = reinterpret_cast<T *>(mem);
(gdb)
103         }
(gdb)
vector<unsigned long long, false, unsigned int>::push_back (this=0x7039fbd0 <memory::allocate(unsigned int)+512>, elem=<error reading variable>) at /var/tmp/portage/sci-mathematics/z3-4.8.10/work/z3-z3-4.8.10/src/util/vector.h:436
436             new (m_data + reinterpret_cast<SZ *>(m_data)[SIZE_IDX]) T(std::move(elem));
(gdb)

Program received signal SIGBUS, Bus error.
0x70431280 in vector<unsigned long long, false, unsigned int>::push_back (this=0x8, elem=@0x72b743dc: 0) at /var/tmp/portage/sci-mathematics/z3-4.8.10/work/z3-z3-4.8.10/src/util/vector.h:436
436             new (m_data + reinterpret_cast<SZ *>(m_data)[SIZE_IDX]) T(std::move(elem));
```

This is on Sparc, which is very picky about alignments. The problem seems to be that the size is an integer (4 byte), but the contents are ```unsigned long long``` (8 byte), so the first element is at offset 4 instead of 8 inside the allocated space.

**Comment by NikolajBjorner** [comment]
It can be fixed, but likely requires more than one change to vector. I used to use memcpy for access and updates for SPARC architectures. Maybe there is something cleaner with C++11.

**Comment by NikolajBjorner** [comment]
yes indeed. The prehistory is that std::vector pretends to treat the contents of the vector opaquely. 
&v[0] works on many but not all platforms when v is the empty vector.

**Comment by DerDakon** [comment]
What do you want? std::vector::data()?

**Comment by NikolajBjorner** [comment]
Wonderful! (vector is pre-historic, or at least pre C++11).

**Comment by nunoplopes** [comment]
Can't see the bug, sorry. In `expand_vector`, m_data is set to allocate + 2*sizeof(unsigned), which should hopefully be allocate+8, making the pointer aligned.
Can you print m_data in gdb so we confirm what's going on pls?

**Comment by DerDakon** [comment]
not at the point where it actually crashes, since the this-ptr is corrupted there

**Comment by nunoplopes** [comment]
then the bug is not in vector, but somewhere else before.

**Comment by NikolajBjorner** [comment]
side question is what it takes to get to class vector<T> : public std::vector<T, memory_manager> {}; (other than busy work).
The home made implementation has its own drawbacks. Saving the memory allocation on empty vectors was an objective so was avoiding destructors on simple classes. I assume this isn't any issue, at least any longer.

- size_t return for size() - large vectors are in almost all cases a bug and z3 catches this with an exception. Interleaving size_t and unsigned is seen as leading to clutter. 
- some mixins added in vector.h. Maybe they can be added to the subclass without additional hassle.

Another side question: is it important to support SPARC? I can imagine RISC5 with the activity around it, 
but last I heard was that SPARC is not pushed forward.
The bug would suggest that assigning 32 bit at a 4 byte miss-aligned address range isn't allowed.
There could be a few other places where either the architecture or available compiler causes a busy-loop.
It happens with random frequency to get one of these bugs from a non-mainstream compiler/platform and they end up being compiler bugs.

**Comment by NikolajBjorner** [comment]
Using "data" to access raw material is a reasonable convention. The code base now adapts this name so at least this would not need a change if moving to vector.

**Comment by DerDakon** [comment]
I only came about this as it was a dependency for enabling llvm builds in Gentoo/Sparc.

**Comment by DerDakon** [comment]
Btw., ARM also has at least performance penalties for unaligned accesses, so fixing this has benefits beyond Sparc.

**Comment by nunoplopes** [comment]
Sure, but as you said, it's the `this` pointer of vector that is corrupted, so the trace you posted doesn't point to the source of the bug. The bug is way before. Maybe in the caller of Z3, who knows.
I agree fixing unaligned memory operations is useful, but we need more information to make this report actionable.

**Comment by NikolajBjorner** [comment]
It's been 20 years since I compiled for SPARC specifically. A vague recollection is that 4 byte access within a 8 byte aligned address range is still allowed. It is the other way around and the 1, 2, 3 alignment issues that bite. Our own ARM pipeline build is a bit thin at the moment: it builds for ARM64 but doesn't run the tests.

**Comment by NikolajBjorner** [comment]
> but we need more information to make this report actionable
Moving to std::vector is a good action item :-).

**Comment by nunoplopes** [comment]
std::vector uses more memory (Z3's vector only takes 8 bytes). I don't know what the impact of that will be.
Plus Z3's vector uses Z3's allocator. I don't know if Z3's vectors get large somewhere, but I really need to tame Z3's memory.
(Of course it's possible to pass a custom allocator to std::vector)

**Comment by NikolajBjorner** [comment]
we would subclass with z3's allocator so we can use the established approach for memory tracking (std::string is the main exception where I wouldn't bother). The idea was 

```
class vector : public std::vector<T, memory_manager> {
   // extensions go here
}; 
```

We almost for sure have some "dirty" tricks that break abstractions that will haunt (home-made reversal).

Memory usage is like this: you run a SAT solver with watch lists for each variable. There are 10M variables. So each variable has a vector. Most vectors are empty. Overall overhead of +/- 16 bytes is still not much when these instances easily gobble up GBs.

**Comment by NikolajBjorner** [comment]
getting to std::vector is still significant work. I don't know of a slick way to approach the different signature of "size()" that returns size_t. Furthermore, code relies on svector semantics as exemplified with polynomial.h where vectors of mpz objects are used without allowing copy constructors. Whatever is the source of the bus error it should be possible to address without rat-holing into library maintainence.

**Comment by nunoplopes** [comment]
I've fixed an issue in buffer.h where we could end up with unaligned data (https://github.com/Z3Prover/z3/commit/79201e5ce693dcc36e3079b5f6b997add97da801) -- `std::aligned_storage` is awesome!

I've also added a static assert to vector.h to stop compilation if we were to get alignment wrong: https://github.com/Z3Prover/z3/commit/aef38099bf629ea5f371561c0404a62cf0a2b51a

Please reopen this if compilation fails for you. It shouldn't crash because of alignment in vector or buffer though.
