### ISSUE TITLE
Inconsistent result from Solver.consequences

### ISSUE THREAD

**Issue by timo92** [Z3Prover/z3#5179]
Hi,
I'm currently testing out the Solver.consequences API in python using z3 4.8.10 and am a bit confused by its results.
When running
```
solver.consequences([a], [b,c,d,e])
```
in my model I'm getting often just one consequence however when executing `solver.consequences` for each variable on their own I'm getting one consequence per variable.
Sometimes I'm even observing this behavior
```
solver.consequences([a], [b,c,d,e]) # (sat, [])
solver.consequences([a], [b]) # (sat, [Implies(a, Not(b)])
solver.consequences([a], [c]) # (sat, [Implies(a, c)])
solver.consequences([a], [b,c,d,e]) # (sat, [Implies(a, Not(b)), Implies(a, c)])
```

Is there some internal timeout or other flag they I may need to tweak? I tried setting timeout on the Context but since all calls return within less than 10s I wouldn't expect this to help.
If this turns out to be a bug and not a mistake on my end I can provide an example model.

Finally regarding the interpretation of the returned consequences I am sometimes getting `Implies(True, d)`. I'm currently assuming that this means that `d` is always True and its state is therefore not dependant on / influenced by `a`. Is this correct?

**Comment by NikolajBjorner** [comment]
> Is there some internal timeout or other flag they I may need to tweak?

No, variable behavior is much more likely to be a bug. There are in fact two implementations internally. One is for finite domains and has been debugged more, the other is for general SMT formulas and has few if any users. There have been fuzz bugs in this code path, but they don't check for semantics.

> Finally regarding the interpretation of the returned consequences I am sometimes getting Implies(True, d). I'm currently assuming that this means that d is always True and its state is therefore not dependant on / influenced by a. Is this correct?

Yes, correct
