### ISSUE TITLE
nuZ's minimized result does not match get-model's model

### ISSUE THREAD

**Issue by daniel-j-h** [Z3Prover/z3#52]
How can be that the minimize command returns a value that is not possible with the result from get-model? Or: how do I get a model for the minimized result?

In this example, minimize returns: 46 as (correctly) minimized result:
https://gist.github.com/daniel-j-h/1d661f6a7e299a47725f

But once I try to generate a model, i.e. using get-model or eval, the output is different.
In this case, the output is 83 for the model (take a look at the output; first line is minimized result, 6th line is actual schedule, from 0 to 83). The model is not the optimal one, as you can clearly see from the schedule and for example at the time from 3 to 38 where nothing is done.

Is this the correct behavior? Is it due to me not using soft-constraints for the intervals to be optimized?
Could you give a quick explanation how something like this could happen at all?

Thanks,
Daniel

**Comment by NikolajBjorner** [comment]
Thanks for the bug report. The model isn't being properly updated. nuZ isn't correctly handling model tuning when you have a mix of theories, such as tuples and arithmetic as in this case. So thanks for the example

**Comment by NikolajBjorner** [comment]
Fixed by a0f0b53
