### ISSUE TITLE
Feature variability 

### ISSUE THREAD

**Issue by hongjiawu** [Z3Prover/z3#520]
Dear Microsoft team,

I study Z3 from software architecture view. However, I have divergence with my tutor in feature variability of Z3. Personally, I think the theory Z3 can support, for example bit-vector, arrays, arithmetic etc, is the feature variability of Z3. Is that correct?

Thank you very much!

**Comment by wintersteiger** [comment]
Z3 supports all [SMT theories ](http://smtlib.cs.uiowa.edu/theories.shtml) and a few others or new ones like datatypes, sequences, strings. It also features some techniques that are not sound and complete (where possible) decision procedures, for instance, optimization techniques and incomplete procedures like local search (for some theories), and a tactic framework that allows you to construct your own procedures and integrate them. 

But, I'm not sure that's what feature variability means to you as Z3 always comes with all those features, some users might just chose not to use some of them.

**Comment by hongjiawu** [comment]
Thank you very much! I study Z3 from the software architecture view instead of functional view. But you give me clear idea from the overall figure of the project.
