### ISSUE TITLE
Timeout option not working

### ISSUE THREAD

**Issue by Marghrid** [Z3Prover/z3#5208]
The timeout option `(set-option :timeout 30000)` has no effect in [this formula](https://github.com/Z3Prover/z3/files/6358576/timeout_problem.txt). Z3 does not terminate after 30s. This happens in versions 4.8.9 and 4.8.10 (64 bit). In version 4.8.8 (64 bit), it returns unsat after about 2 seconds.

**Comment by NikolajBjorner** [comment]
@Marghrid - at this point use smt.arith.solver=2 to use the old solver, which does not suffer from this overhead.

@levnach - this is inside 
```
bool const_iterator_mon::get_factors(factor& k, factor& j, rational& sign) const
```
which is part of a busy loop enumerating a large set of combinations. 
There is no way to cancel this or bail out if this takes too many resources.
It is also likely that factorization can be improved. I see it reaches this code:
```
        if (!m_ff->find_canonical_monic_of_vars(k_vars, i)) {
            return false;
        }
```
in factorization.cpp and returns false in a fair number of cases (practically _all_).

**Comment by NikolajBjorner** [comment]
I think we can say this was fixed

**Comment by Marghrid** [comment]
Yes, it worked perfectly. Thank you for the quick reply!

**Comment by levnach** [comment]
Gröbner basis is a nice idea but in practice helps rarely, requires a lot of resources when running, not so simple to develop , and it seems many people are happy when you throttle it down. Maybe one of the issues is that our implementation of GB does not care about sparsity. https://arxiv.org/abs/1402.7205 seems to be interesting as they look at the sparsity.

**Comment by NikolajBjorner** [comment]
Note: factorization is used for incremental linearization.
