### ISSUE TITLE
z3 sometimes fails with "maximization suspended" error instead of `unknown` (smt2)

### ISSUE THREAD

**Issue by rixed** [Z3Prover/z3#5212]
Smt2lib specs suggests that `(check-sat)` should be answered by `unknown` whenever  limited resources prevent the solver to reach either sat or unsat state.

Sometimes though, instead of `unknown` z3 returns the generic error "maximization suspended".
What's the difference between the two ?

**Comment by NikolajBjorner** [comment]
It is the message from an exception that gets raised due to resource limits. This exception isn't caught like on other code-paths.
