### ISSUE TITLE
Z3 Build is Failing

### ISSUE THREAD

**Issue by Owlz** [Z3Prover/z3#524]
As of yesterday, I'm finding that the Z3 build is failing for me:

src/qe/qe_dl_plugin.cpp
src/qe/qe_datatypes.cpp
src/qe/qe_datatype_plugin.cpp
src/qe/qe_cmd.cpp
src/qe/qe_bv_plugin.cpp
src/qe/qe_bool_plugin.cpp
src/qe/qe_arrays.cpp
src/qe/qe_array_plugin.cpp
src/qe/qe_arith_plugin.cpp
src/qe/qe_arith.cpp
src/qe/qe.cpp
src/qe/nlqsat.cpp
In file included from ../src/nlsat/nlsat_solver.h:24:0,
from ../src/qe/nlqsat.cpp:22:
../src/nlsat/nlsat_types.h: In function std::ostream& nlsat::operator<<(std::ostream&, nlsat::atom::kind):
../src/nlsat/nlsat_types.h:116:20: error: nlsat::atom::kind is not a class or namespace
case atom::kind::EQ: return out << "=";
^
../src/nlsat/nlsat_types.h:117:20: error: nlsat::atom::kind is not a class or namespace
case atom::kind::LT: return out << "<";
^
../src/nlsat/nlsat_types.h:118:20: error: nlsat::atom::kind is not a class or namespace
case atom::kind::ROOT_EQ: return out << "= root";
^
../src/nlsat/nlsat_types.h:119:20: error: nlsat::atom::kind is not a class or namespace
case atom::kind::ROOT_LT: return out << "< root";
^
../src/nlsat/nlsat_types.h:120:20: error: nlsat::atom::kind is not a class or namespace
case atom::kind::ROOT_LE: return out << "<= root";
^
../src/nlsat/nlsat_types.h:121:20: error: nlsat::atom::kind is not a class or namespace
case atom::kind::ROOT_GT: return out << "> root";
^
../src/nlsat/nlsat_types.h:122:20: error: nlsat::atom::kind is not a class or namespace
case atom::kind::ROOT_GE: return out << ">= root";
^
make: *** [qe/nlqsat.o] Error 1

**Comment by Owlz** [comment]
Guessing this is the same problem that there's a pull request in for: https://github.com/Z3Prover/z3/pull/523

**Comment by delcypher** [comment]
@Owlz  Yes this is the same problem.

**Comment by NikolajBjorner** [comment]
thanks for the pull request, merged.
