### ISSUE TITLE
Optimization issue, quadratic function

### ISSUE THREAD

**Issue by tpaviot** [Z3Prover/z3#5254]
I try to find the minimum of a quadratic function using this python script (latest z3 release 4.8.10.0 installed with pip, ubuntu 20.04):
```python
from z3 import *

x = Int('x')
y = Int('y')

s = Optimize()
s.add(y == (x - 3) ** 2 + 8)
s.add(x <= 10)
s.minimize(y)
print(s.check())
print(s.model())
```
The expected result is ``x=3`` and ``y=8``, but running the script I get:
```bash
sat
[y = 9, x = 2]
```

If comment out the constraint ``x <=10``, then it gives the expected result:
```bash
[y = 8, x = 3]
```
I can't understand what is wrong with the assertion ``x<=10`` since it does not conflict with any other.

**Comment by NikolajBjorner** [comment]
The bug is how the optimization code handles non-linear objectives or generally objectives where local optimization doesn't give a valid result.

**Comment by NikolajBjorner** [comment]
The particular buggy code path, which is unfortunately also central, has been giving me some grief before.
Based on your example, I have now attempted to address the core issue 
(two separate buggy behaviors were identified, one perhaps benign).

**Comment by tpaviot** [comment]
Great!
