### ISSUE TITLE
Ranjit's Regression 

### ISSUE THREAD

**Issue by chadbrewbaker** [Z3Prover/z3#5259]
See https://twitter.com/RanjitJhala/status/1391486845435871233 for the thread.

For commit 7373946 here is a demangled perf stack trace:
 https://gist.github.com/chadbrewbaker/efd181e3dd2554b32a48411deea25a5c

**Comment by NikolajBjorner** [comment]
31a5bd7fd7dc401f0af99261900f0b706c18aba4

**Comment by chadbrewbaker** [comment]
Commit 31a5bd7 is better. It was at 96.06%.

    91.71%  z3       z3                   [.] (anonymous namespace)::th_rewriter_cfg::reduce_quantifier(quantifier*, expr*, expr* const*, expr* const*, obj_ref<expr, ast_manager>&, obj_ref<app, ast_manager>&)
     1.60%  z3       z3                   [.] used_vars::process(expr*, unsigned int)
     0.45%  z3       z3                   [.] ast_manager::register_node_core(ast*)
     0.30%  z3       z3                   [.] expr_substitution::erase(expr*)
     0.27%  z3       z3                   [.] expr_substitution::find(expr*, expr*&, app*&, dependency_manager<ast_manager::expr_dependency_config>::dependency*&)
     0.26%  z3       z3                   [.] expr_safe_replace::insert(expr*, expr*)
     0.24%  z3       z3                   [.] asserted_formulas::flatten_clauses()

**Comment by chadbrewbaker** [comment]
I'm noticing function/variable declarations like lq_karg$36$lq_anf$36$$35$$35$7205759403792832225$35$$35$da2Z$35$$35$k_$35$$35$8560 in the test file. Assuming the parser chucks these into an std::unordered_set/map and recodes them to 32/64 bit values so they can be extremely long without hurting cache efficiency of the solver? The master version is using 25% more memory.

 Command being timed: "./z3_old /tmp/review.smt2"
        User time (seconds): 12.16
        System time (seconds): 0.24
        Percent of CPU this job got: 99%
        Elapsed (wall clock) time (h:mm:ss or m:ss): 0:12.40
        Average shared text size (kbytes): 0
        Average unshared data size (kbytes): 0
        Average stack size (kbytes): 0
        Average total size (kbytes): 0
        Maximum resident set size (kbytes): 407124
        Average resident set size (kbytes): 0
        Major (requiring I/O) page faults: 0
        Minor (reclaiming a frame) page faults: 86515
        Voluntary context switches: 1
        Involuntary context switches: 123
        Swaps: 0
        File system inputs: 0
        File system outputs: 0
        Socket messages sent: 0
        Socket messages received: 0
        Signals delivered: 0
        Page size (bytes): 4096
        Exit status: 0

 Command being timed: "./z3_master /tmp/review.smt2"
        User time (seconds): 128.26
        System time (seconds): 0.30
        Percent of CPU this job got: 99%
        Elapsed (wall clock) time (h:mm:ss or m:ss): 2:08.57
        Average shared text size (kbytes): 0
        Average unshared data size (kbytes): 0
        Average stack size (kbytes): 0
        Average total size (kbytes): 0
        Maximum resident set size (kbytes): 516876
        Average resident set size (kbytes): 0
        Major (requiring I/O) page faults: 0
        Minor (reclaiming a frame) page faults: 82226
        Voluntary context switches: 1
        Involuntary context switches: 27
        Swaps: 0
        File system inputs: 0
        File system outputs: 0
        Socket messages sent: 0
        Socket messages received: 0
        Signals delivered: 0
        Page size (bytes): 4096
        Exit status: 0

**Comment by chadbrewbaker** [comment]
Look's good to me. About 25% more RAM than the older version but runtime is almost the same.

    20.99%  z3       z3                   [.] used_vars::process(expr*, unsigned int)
     8.58%  z3       z3                   [.] ast_manager::register_node_core(ast*)
     5.04%  z3       z3                   [.] expr_substitution::erase(expr*)
     3.64%  z3       z3                   [.] ast_table::push_erase(ast*)
     3.08%  z3       z3                   [.] asserted_formulas::flatten_clauses()
     2.99%  z3       z3                   [.] expr_substitution::contains(expr*)
     2.24%  z3       z3                   [.] ast_manager::delete_node(ast*)
     1.96%  z3       z3                   [.] act_cache::insert(expr*, unsigned int, expr*)
     1.87%  z3       z3                   [.] expr_substitution::find(expr*, expr*&, app*&, dependency_manager<ast_manager::expr_dependency_config>::dependency*&)
     1.87%  z3       z3                   [.] smt2::scanner::read_symbol_core()

**Comment by chadbrewbaker** [comment]
The custom vector type seems defaulted to CallDestructors=true, but the template definitions I saw set it to false.

https://github.com/Z3Prover/z3/blob/21e59f7c6e5033006265fc6bc16e2c9f023db0e8/src/ast/used_vars.cpp#L25

**Comment by chadbrewbaker** [comment]
You piqued my interest. I'll run strace and see where it is thrashing allocations.

How attached are you to the C++ hashtables? I was thinking about submitting a PR that replaced some of them with Rust hashtables - probably add an optional flag to the Cmake like Z3_ENABLE_RUST.

**Comment by NikolajBjorner** [comment]
I am very attached to _not_ create external dependencies.
I have a 20% speedup using some small tuning pending a push. I tried some other structural changes using ast_marking instead of hash-tables but this either ended up introducing bugs or slowed things down quite a bit because resets are more expensive on large bit-vectors than sparse hash-tables. 
Z3 hash-tables are inefficient, but have stable semantics across platforms that is useful for when we need to traverse tables in consistent orders (otherwise debugging regressions is a nightmare). For this particular module we can use unordered hash tables that were added to C++ after z3's hash tables were put in place.

**Comment by chadbrewbaker** [comment]
Understood. I view libstdc++ as an external dependency :)  Rust is another C to me, and any use of it would be via a C interface. Structs also have better tooling like Poke-a-hole https://lwn.net/Articles/335942/ - I would have to Godbolt to see if it is worth writing a ClangAST printer that re-writes C++ object data to C structs. No clue how Clang permutes object data or if LLVM does it's own re-orderings.

My other interest was using Rust to wrap ARM SIMD as to not pollute the C++ codebase.  Most of my Z3 jobs are targeting AWS Graviton and Apple M1.
