### ISSUE TITLE
range of multiplication with bitvectors

### ISSUE THREAD

**Issue by kanigsson** [Z3Prover/z3#5263]
[bv2nat.smt2.txt](https://github.com/Z3Prover/z3/files/6457822/bv2nat.smt2.txt)
[bvextend.smt2.txt](https://github.com/Z3Prover/z3/files/6457823/bvextend.smt2.txt)

Not really a bug, more a question/discussion/feature request. I have attached two different formulations of a simple goal that states that if (a-b) is smaller than some large constant divided by idx, then (a-b)*idx is smaller than the large constant. The first formulation checks against the large constant in mathematical integers, the second file does everything in bitvectors using extend. The second one is proved by z3 in roughly 5 minutes.

Is there any way to speed things up, or do you have other inputs on how to improve provability on this kind of goals?

**Comment by NikolajBjorner** [comment]
Currently you have to use integer formulations for these kinds of formulas to solve them. 
The current bit-vector solver relies on bit-blasting to solve these formulas and this doesn't scale with multiplication (and division).
Your example is a good unit test for polysat, but this solver will not be ready for several months.

**Comment by kanigsson** [comment]
Thanks for your answer.

**Comment by fruffy** [comment]
Hi, 
we are dealing with a similar problem and were intrigued by your comment on polysat. It seems that polysat is not released yet, but is there any material or comments we could take a look at? What is the current roadmap for this project? Is it this one? 
https://github.com/Z3Prover/z3/projects/1

**Comment by fruffy** [comment]
Thanks for letting us know!
