### ISSUE TITLE
Is the documentation for creating a statically built Z3 binary outdated?

### ISSUE THREAD

**Issue by zimmski** [Z3Prover/z3#5270]
According to contrib/ci/README.md one should use Z3_STATIC_BUILD=1 for "Build Z3 binaries and libraries statically". However, is it possible that this is outdated since only the library is built statically then?

E.g.

```bash
(
	export BUILD_DOCS=0
	export DOTNET_BINDINGS=0
	export JAVA_BINDINGS=0
	export PYTHON_BINDINGS=0
	export PYTHON_EXECUTABLE=$(which python3)
	export USE_LTO=0
	export Z3_BUILD_DIR=$BUILD_DIR/build
	export Z3_CMAKE_GENERATOR="Unix Makefiles"
	export Z3_SRC_DIR=$(pwd)
	export Z3_STATIC_BUILD=1
	export Z3_USE_LIBGMP=0
	source contrib/ci/scripts/ci_defaults.sh
	bash contrib/ci/scripts/build_z3_cmake.sh
)
```

Does not give me a statically built binary.

However, the following does:

```bash
python3 scripts/mk_make.py --staticbin
cd build
make -j4
```

**Comment by zimmski** [comment]
CC @krobelus

**Comment by NikolajBjorner** [comment]
1. Readme-cmake.md is the official doc. Readme files inside the Travis integration are not maintained. You are invited to add a pull request to fix the documentation inside contrib/ci, but otherwise should ignore it.
2. mk_make.py is a separate build system (legacy) that I would like to deprecate.
