### ISSUE TITLE
Unsound result with `define-fun-rec` and `declare-const`

### ISSUE THREAD

**Issue by Elarnon** [Z3Prover/z3#5305]
With the following input:

```lisp
(declare-const x Int)
(define-fun-rec y () Int x)
(assert (not (= y x)))
(check-sat)
```

Z3 (4.8.10 and nightly) answers:

```
sat
```

which is obviously incorrect.  This use of `define-fun-rec` without arguments (nor recursion) is not very interesting, but it is a MRE.  Here is a more interesting case which seems to trigger the same bug:

```lisp
(declare-const N Int)

(define-fun-rec C ((i Int)) Int
	(ite (< i N) (+ (C (+ i 1)) i) 0))

(declare-const i Int)
(assert (not (= (C i) (ite (< i N) (+ (C (+ i 1)) i) 0))))

(check-sat)
```

It might be interesting to note that when using `(assert (exists ((i Int)) (not (= (C i) (ite (< i N) (+ (C (+ i 1)) i) 0))))` instead, Z3 correctly answers `unsat`.

NB: This might be related to #5274 but I am not sure, hence the new issue.

**Comment by NikolajBjorner** [comment]
this was fixed
