### ISSUE TITLE
oserror: exception: access violation writing in wsl ubuntu Or "oserror: exception: access violation writing"

### ISSUE THREAD

**Issue by Tridu33** [Z3Prover/z3#5318]
the same problem as here: https://github.com/Z3Prover/z3/issues/1578 and here https://github.com/Z3Prover/z3/issues/1578  , this issue was closed before. But I still meet this problem, and reinstall does not work for me. the same source code runs well sometimes , but sometimes it just crashes saying "Oserror: exception: access violation writing".
then I try it in windows wsl ubuntu, it runs well sometime but sometime it just crashes saying"Segmentation fault (core dumped)"
and I do not understand why the same source code just works well sometimes.

**Comment by Tridu33** [comment]
```
File "d:\tridu33\Clear.py", line 137, in myprove
    if s.check() == unsat:
  File "D:\ProgramData\Anaconda3\lib\site-packages\z3\z3.py", line 6697, in check
    r = Z3_solver_check_assumptions(self.ctx.ref(), self.solver, num, _assumptions)
  File "D:\ProgramData\Anaconda3\lib\site-packages\z3\z3core.py", line 3807, in Z3_solver_check_assumptions
    r = _elems.f(a0, a1, a2, a3)
OSError: exception: access violation reading 0x0000021D25591CD8
```

**Comment by Tridu33** [comment]
windows wsl ubuntu 
```
Segmentation fault (core dumped)
```

**Comment by NikolajBjorner** [comment]
I don't see how to resolve this based on the information provided or environment being tried. The problem has to be external to Z3. The releases are tested under standard environments.

**Comment by Tridu33** [comment]
the same code run this time tell me this :
```
ASSERTION VIOLATION
File: D:\a\1\s\src\ast/rewriter/rewriter_def.h
Line: 213
UNEXPECTED CODE WAS REACHED.
Z3 4.8.10.0
Please file an issue with this message and more detail about how you encountered it at https://github.com/Z3Prover/z3/issues/new
```

**Comment by wintersteiger** [comment]
It's impossible to debug this without seeing the input to Z3. Please add a complete .smt2 or .py file when filing an issue.
