### ISSUE TITLE
Incorrect result for a non-linear optimization problem

### ISSUE THREAD

**Issue by martinjonas** [Z3Prover/z3#5339]
I think that the latest version of Z3 returns an incorrect result for the attached optimization problem over non-linear real arithmetic: [fn-counters-simp__instance_2_10.zip](https://github.com/Z3Prover/z3/files/6622487/fn-counters-simp__instance_2_10.zip).

Both Z3 release 4.8.10 and the latest Git version (082ec0f49988712c683b1737356e27f2d6416455) report `-oo` as the optimum:

```
> z3-4.8.10-x64-ubuntu-18.04/bin/z3 fn-counters-simp__instance_2_10.smt2

sat
(objectives
 (__rev_fv_cost_10 (* (- 1) oo))
)
```

However, when replacing the minimization clause by an additional assertion that the value of the objective function is less then zero, it becomes unsatisfiable (decided both by Z3 and MathSAT):

```
> sed "s/(minimize __rev_fv_cost_10)/(assert (< __rev_fv_cost_10 0))/" fn-counters-simp__instance_2_10.smt2 | z3-4.8.10-x64-ubuntu-18.04/bin/z3 -in

unsat
```

The optimum value `0` is also reported by the latest version of OptiMathSAT.

If it would be helpful for debugging, I have several more similar optimization problems where Z3 reports a wrong optimum `-oo`.

Thank you for the investigation.

**Comment by martinjonas** [comment]
A similar problem occurs for the following non-linear optimization problem: [fn-counters-simp__instance_4_15.zip](https://github.com/Z3Prover/z3/files/6622836/fn-counters-simp__instance_4_15.zip).

The optimum returned by Z3 4.8.10 is `epsilon`:

```
> z3-4.8.10-x64-ubuntu-18.04/bin/z3 fn-counters-simp__instance_4_15.smt2

sat
(objectives
 (__rev_fv_cost_15 epsilon)
)
```

The optimum returned by the latest development version of Z3 (082ec0f49988712c683b1737356e27f2d6416455) is `(/ 95.0 8.0)`:

```
> z3/build/z3 fn-counters-simp__instance_4_15.smt2

sat
(objectives
 (__rev_fv_cost_15 (/ 95.0 8.0))
)
```

However, the optimum returned by OptiMathSAT is `8`, which can be verified by Z3 (the formula with assertion cost=8 is SAT; the formula with assertion cost<8 is UNSAT):

```
> sed "s/(minimize __rev_fv_cost_15)/(assert (= __rev_fv_cost_15 8))/" fn-counters-simp__instance_4_15.smt2 | z3/build/z3 -in

sat
```

```
> sed "s/(minimize __rev_fv_cost_15)/(assert (< __rev_fv_cost_15 8))/" fn-counters-simp__instance_4_15.smt2 | z3/build/z3 -in

unsat
```

**Comment by NikolajBjorner** [comment]
optimization with non-linear constraints isn't a supported feature.
