### ISSUE TITLE
Visual Studio requirements

### ISSUE THREAD

**Issue by kanigsson** [Z3Prover/z3#5342]
Hello, I noticed that z3 doesn't build anymore with Visual Studio 14.0 (2015). I guess that's expected as you use C++17 features. Which is the current minimal/recommended version of Visual Studio to build z3? I couldn't find this info in the README.

**Comment by NikolajBjorner** [comment]
Yes it uses C++17, so suitable versions of VS are therefore needed (VS17, VS19, VS21,)

**Comment by kanigsson** [comment]
Thanks!
