### ISSUE TITLE
Universe constants from model can't be eval'd in SMT mode

### ISSUE THREAD

**Issue by djrenren** [Z3Prover/z3#5352]
Invocation: `z3 -smt2 input.txt`
Input:
```
(declare-sort Foo)
(declare-fun num (Foo) Int)
(assert (exists ((x Foo)) (= (num x) 4)))
(check-sat)
(get-model)
(eval Foo!val!0)
```

Output:
```
sat
(
  ;; universe for Foo:
  ;;   Foo!val!0 
  ;; -----------
  ;; definitions for universe elements:
  (declare-fun Foo!val!0 () Foo)
  ;; cardinality constraint:
  (forall ((x Foo)) (= x Foo!val!0))
  ;; -----------
  (define-fun num ((x!0 Foo)) Int
    4)
)
(error "line 6 column 6: unknown constant Foo!val!0")
```

It seems like the resolution of identifiers doesn't use the model.

**Comment by djrenren** [comment]
Looking at the spec it seems like the right way to support something like this is to use abstract values denoted with @, which it looks like z3 doesn't use for its models.

**Comment by NikolajBjorner** [comment]
Foo!val!0 is not declared but you can declare a constant and evaluate it.

```
(declare-sort Foo)
(declare-const x Foo)
(declare-fun num (Foo) Int)
(assert (exists ((x Foo)) (= (num x) 4)))
(check-sat)
(get-model)
(eval x)
```

**Comment by djrenren** [comment]
Thanks for taking the time to answer this, but I guess I overly reduced my problem.

This solution only works if you know the cardinality of the universe for Foo ahead of time, but if you're relying on the solver to find that cardinality and then you want to evaluate against each of the constants in Foo's universe, then it appears there's no way to do that through the text interface because you can't refer to those anonymous members.
