### ISSUE TITLE
Completeness regression in NIA with div

### ISSUE THREAD

**Issue by maurobringolf** [Z3Prover/z3#5357]
Maybe related to https://github.com/Z3Prover/z3/issues/5338 (but not fixed by its fix).

Commit: 2138ef2ad05bacf3bc488364d7f994d927e289cb
```
$ z3-4.8.10 unknown.smt2
unsat
$ z3 unknown.smt2
unknown
$ cat unknown.smt2
(assert (forall ((v Int)) (distinct 0 (div 0 v))))
(check-sat)
```

**Comment by maurobringolf** [comment]
And a variation:

```
$ z3-4.8.10 unknown.smt2
unsat
$ z3 unknown.smt2
unknown
$ cat unknown.smt2
(assert (forall ((_ Int)) (= 0 _)))
(assert (= 0 (div 0 0)))
(check-sat)
```

**Comment by NikolajBjorner** [comment]
these are butterflies too. 
I don't understand a rationale from these tests for dealing with them. 
They are out of scope of legacy MBQI completeness claims and they get handled by new core so take up resources to examine.
