### ISSUE TITLE
Array extensionality not always taken into account

### ISSUE THREAD

**Issue by simonr89** [Z3Prover/z3#5365]
The following problem is sat
```
(declare-const a (Array Bool Int))
(define-const b (Array Bool Int) ((as const (Array Bool Int)) 1))

(assert (= (select a false) 1))
;(assert (= (select a true) 1))

(assert (distinct (store a true 1) b))

(check-sat)
```
Array extensionality should make the problem unsat, but Z3 returns a model that violates the last assertion. If you add the commented assertion (which shouldn't matter), the problem becomes unsat.

**Comment by NikolajBjorner** [comment]
I get unsat with current head of master
