### ISSUE TITLE
z3 4.8.11 hangs in cex generation whereas 4.8.10 doesn't

### ISSUE THREAD

**Issue by leonardoalt** [Z3Prover/z3#5367]
Sample: https://gist.github.com/leonardoalt/2f44341789b6353ce300003ef7928902
Command: `z3 a.smt2 rewriter.pull_cheap_ite=true fp.spacer.q3.use_qgen=true fp.spacer.mbqi=false fp.spacer.ground_pobs=false`

Somewhat similar to https://github.com/Z3Prover/z3/issues/5363, but here the difference is that z3 4.8.10 solves and generates a cex quite quickly, whereas latest master (even after the fix to the other issue) hangs, so I'm wondering if there was some regression here. Please note that here I'm not disabling Spacer's inlining/slicing, and I don't have the `(Array Int Bool)` that generated the `lambda`s in the other proof (there are also no lambdas in the proof below).

Proof from z3 4.8.10: https://gist.github.com/leonardoalt/d623f11aef4bd2ab09e662cdfc96c88c

**Comment by NikolajBjorner** [comment]
you have bv2int and non-linear arithmetic spread around. 
While the dependency of running the solver on counter example traces still needs to be addressed, the example isn't in a fragment I would say is currently well supported.
