### ISSUE TITLE
Soundness bug in QF_NRA

### ISSUE THREAD

**Issue by merlinsun** [Z3Prover/z3#5373]
Hi,
z3 nightly build incorrectly gives unsat on the following file, while z3-4.8.10 gives sat:
[QF_NRA.zip](https://github.com/Z3Prover/z3/files/6716607/QF_NRA.zip)

OS: Ubuntu 20.04.2 LTS
Revision: [d5c6ab](https://github.com/Z3Prover/z3/commit/d5c6abe14d3edc18667e5828144816ec756289fb)

**Comment by NikolajBjorner** [comment]
For whatever reason you are using "dom-simplify" which makes the result different.
 @nunoplopes can you check if the rewrites by dom-simplify used here are sound?

**Comment by nunoplopes** [comment]
I checked every transform of dom-simplify on this test case and they are all correct (according to Z3 at least).

Here's the patch for translation validation I've used: https://gist.github.com/nunoplopes/179ed4f027e022190ae08daeea60cd54
(I printed the answer of the solver and it gives false the 4x times it gets called).

**Comment by NikolajBjorner** [comment]
gives sat. It relies on nlsat and there is an old open bug on nlsat.
