### ISSUE TITLE
`Z3_mk_string` returns a function declaration.

### ISSUE THREAD

**Issue by zwimer** [Z3Prover/z3#5374]
I compiled multiple recent versions of z3 from the master branch and have found that executing the following code produces the following output:

```C++
z3::context ctx;
auto exp { ctx.string_val("Hello") };
auto decl { exp.decl() };
std::cout << exp << " " << decl << std::endl;
```

Output: `"Hello" (declare-fun String () String)`

I tried this with the raw `Z3_mk_string` function as well and found the same result.

The API docs linked [here](https://z3prover.github.io/api/html/group__capi.html#gabf2fa2e9578b7b496b87cabf3a245ad8) state that:
> Create a string constant out of the string that is passed in.

I suspect there is a bug here; either that or the documentation is confusing.

Here are the `cmake` flags I used to compile `master` on macOS 11:
```
"-DZ3_SINGLE_THREADED:BOOL=FALSE"
"-DZ3_INCLUDE_GIT_HASH:BOOL=TRUE"
# Build Options
"-DCMAKE_BUILD_TYPE:STRING=Debug"
"-DZ3_LINK_TIME_OPTIMIZATION:BOOL=${FLTO}"
"-DZ3_BUILD_LIBZ3_SHARED:BOOL=TRUE"
"-DWARNINGS_AS_ERRORS:STRING=SERIOUS_ONLY"
# Install Options
"-DCMAKE_INSTALL_INCLUDEDIR:PATH=${Z3_INCLUDE_DIR}" # Absolute path
"-DCMAKE_INSTALL_LIBDIR:PATH=${Z3_DIR}/bin/"        # Absolute path
# This should never be used, but just in case:
"-DCMAKE_INSTALL_PREFIX:PATH=${Z3_DIR}"
# Disable Unwanted Options
"-DZ3_BUILD_EXECUTABLE:BOOL=FALSE"
"-DZ3_USE_LIB_GMP:BOOL=FALSE"
"-DZ3_INCLUDE_GIT_DESCRIBE:BOOL=FALSE"
"-DZ3_SAVE_CLANG_OPTIMIZATION_RECORDS:BOOL=FALSE"
"-DZ3_ENABLE_TRACING_FOR_NON_DEBUG:BOOL=FALSE"
"-DZ3_ENABLE_EXAMPLE_TARGETS:BOOL=FALSE"
"-DZ3_ENABLE_CFI:BOOL=FALSE"
"-DZ3_BUILD_DOCUMENTATION:BOOL=FALSE"
"-DZ3_BUILD_TEST_EXECUTABLES:BOOL=FALSE"
"-DZ3_BUILD_DOTNET_BINDINGS:BOOL=FALSE"
"-DZ3_BUILD_JAVA_BINDINGS:BOOL=FALSE"
"-DZ3_BUILD_PYTHON_BINDINGS:BOOL=FALSE"
```

**Comment by NikolajBjorner** [comment]
The expression "Hello" is printed as "Hello". 
It is a 0-ary function application of a function that creates a string constant. 
When you print a function declaration you will get the SMT declaration.
