### ISSUE TITLE
Listed versions on Opam website

### ISSUE THREAD

**Issue by hacdias** [Z3Prover/z3#5375]
Hello! I noticed the latest version listed on the [opam website](https://opam.ocaml.org/packages/z3/) is 4.8.9-1 and not the latest [release](https://github.com/Z3Prover/z3/releases). Is that expected?

Thank you!

**Comment by NikolajBjorner** [comment]
@c-cube is listed as maintainer of the package.

**Comment by c-cube** [comment]
updated!

**Comment by hacdias** [comment]
Thanks!
