### ISSUE TITLE
Cannot build Z3 on Windows using Visual Studio Command Prompt

### ISSUE THREAD

**Issue by plkumjorn** [Z3Prover/z3#538]
I try to build Z3 by following the instruction in README. However, performing nmake in build directory fails. Could you please suggest me the solution for this issue?

`C:\Users\Piyawat L Kumjorn\Downloads\z3-master\build>nmake

Microsoft (R) Program Maintenance Utility Version 14.00.23506.0
Copyright (C) Microsoft Corporation.  All rights reserved.

datalog_frontend.cpp
C:\Program Files (x86)\Windows Kits\8.1\include\um\winbase.h(8848): error C3861: '_InterlockedIncrement64': identifier not found
C:\Program Files (x86)\Windows Kits\8.1\include\um\winbase.h(8879): error C3861: '_InterlockedDecrement64': identifier not found
C:\Program Files (x86)\Windows Kits\8.1\include\um\winbase.h(8915): error C3861: '_InterlockedExchange64': identifier not found
C:\Program Files (x86)\Windows Kits\8.1\include\um\winbase.h(8969): error C3861: '_InterlockedExchangeAdd64': identifier not found
C:\Program Files (x86)\Windows Kits\8.1\include\um\winbase.h(8979): error C3861: '_InterlockedExchangeAdd64': identifier not found
C:\Program Files (x86)\Windows Kits\8.1\include\um\winbase.h(9026): error C3861: '_InterlockedAnd64': identifier not found
C:\Program Files (x86)\Windows Kits\8.1\include\um\winbase.h(9036): error C3861: '_InterlockedOr64': identifier not found
C:\Program Files (x86)\Windows Kits\8.1\include\um\winbase.h(9046): error C3861: '_InterlockedXor64': identifier not found
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\cl.EXE"' : return code '0x2'
Stop.` 

Now, I'm using Windows 10 and Microsoft Visual Studio 14.0
 
Thank you so much.

**Comment by NikolajBjorner** [comment]
configure the build with --x64 for the x64 architecture or configure the build without this option if your compiler is for 32 bit.

**Comment by plkumjorn** [comment]
It works!! Thank you.
