### ISSUE TITLE
possible bug with regular expressions and (Seq Int)

### ISSUE THREAD

**Issue by jrmcclurg** [Z3Prover/z3#5384]
Hello, I'm getting an unexpected error for the following code:
```
(define-fun good () (RegEx (Seq Int)) (re.++ (seq.to.re (seq.unit 3)) (as re.all (RegEx (Seq Int)))))
(assert (seq.in.re (seq.unit 3) good))
(check-sat)

(define-fun bad () (RegEx (Seq Int)) (re.++ (seq.to.re (seq.unit 4)) (as re.all (RegEx (Seq Int)))))
(assert (seq.in.re (seq.unit 3) bad))
(check-sat)
```
Z3 output:
```
sat
(error "line 6 column 36: incorrect first argument type Int")
sat
```
Note that if I change everything to `String` instead of `(Seq Int)`, and use the literals `"3"` and `"4"`, Z3 gives me the output `sat` followed by `unsat`, as expected.

**Comment by jrmcclurg** [comment]
Actually I guess it's not limited to `re.++`. The following example also results in a similar error:
```
(define-fun r5x () (RegEx (Seq Int)) (seq.to.re (seq.unit 3)))
(define-fun r6x () (RegEx (Seq Int)) (seq.to.re (seq.unit 3)))
(define-fun r2x () (RegEx (Seq Int)) (re.union r5x r6x) )
(assert (seq.in.re (seq.unit 3) r2x))
(check-sat)

(define-fun r5y () (RegEx (Seq Int)) (seq.to.re (seq.unit 3)))
(define-fun r6y () (RegEx (Seq Int)) (seq.to.re (seq.unit 4)))
(define-fun r2y () (RegEx (Seq Int)) (re.union r5y r6y) )
(assert (seq.in.re (seq.unit 3) r2y))
(check-sat)
```

**Comment by jrmcclurg** [comment]
I found a fix that appears to work, see pull request:
https://github.com/Z3Prover/z3/pull/5385

The issue seems to be that `char.<=` was being applied to elements of arbitrary sequences, in my case meaning it was being applied to `Int`. My fix simply uses `<=` instead.

**Comment by NikolajBjorner** [comment]
regular expressions over non-strings isn't working.
The proposed patch will run into other issues.
The culprit is the code

```
expr_ref seq_rewriter::mk_der_cond(expr* cond, expr* ele, sort* seq_sort) {
    STRACE("seq_verbose", tout << "mk_der_cond: "
        <<  mk_pp(cond, m()) << ", " << mk_pp(ele, m()) << std::endl;);
    sort *ele_sort = nullptr;
    VERIFY(u().is_seq(seq_sort, ele_sort));
    SASSERT(ele_sort == ele->get_sort());
    expr *c1 = nullptr, *c2 = nullptr, *ch1 = nullptr, *ch2 = nullptr;
    unsigned ch = 0;
    expr_ref result(m()), r1(m()), r2(m());
    if (m().is_eq(cond, ch1, ch2)) {
        r1 = u().mk_le(ch1, ch2);
        r1 = mk_der_cond(r1, ele, seq_sort);
        r2 = u().mk_le(ch2, ch1);
        r2 = mk_der_cond(r2, ele, seq_sort);
        result = mk_der_inter(r1, r2);
```
It uses u().mk_le without checking the sorts of the arguments.
mk_le is not necessarily defined for arbitrary sorts.

@veanes @cdstanford

**Comment by jrmcclurg** [comment]
Thanks @NikolajBjorner. BTW please note that the patch also attempts to fix a second unrelated issue -- `seq_decl_plugin::is_char` was being used both for testing whether an expression has character sort, and also whether a given sort is a character sort.

**Comment by NikolajBjorner** [comment]
Margus fixed this
