### ISSUE TITLE
How can I define sorts with parameters in C/C++ API?

### ISSUE THREAD

**Issue by LEAFERx** [Z3Prover/z3#5391]
I want to define sorts with parameters in C/C++ API, similar to SMT-LIB API:
```
(define-sorts A (T) (Array Int T))
```

How can I achieve this? I went through the document and did not find any interface for this.

**Comment by NikolajBjorner** [comment]
You cant. You can only define monomorphic datatypes.
What you can do from the API is to define a function that takes a type as argument and creates the array sort for the type that gets passed to your function.
