### ISSUE TITLE
new lines in log files

### ISSUE THREAD

**Issue by TigerThePro** [Z3Prover/z3#5392]
I have encountered some lines after [assing] that I don't think I have encountered before.
I think these are newly added, but I am unable to find what do they entail.

>  [assign] (not #6339) clause (not p3) p2
      (not (= z3.sk.3 -26::Int)) 
      (= z3.sk.3 -39::Int) `

**Comment by NikolajBjorner** [comment]
The proof logger is using the same pretty printer as debug tracing. That pretty printer was updated to show literals in detail for debugging.
