### ISSUE TITLE
Z3 make error; ../src/ast/ast.h:50:19: fatal error: variant: No such file or directory

### ISSUE THREAD

**Issue by sjoon2455** [Z3Prover/z3#5394]
Hi, I'm trying to install z3 on my ubuntu:16.04 docker.
The environment has g++ 7.5.0.
During following the steps;
```
python scripts/mk_make.py
cd build
make
sudo make install
```
, I have error in the make step.

The error says;
```
src/shell/main.cpp
In file included from ../src/ast/format.h:22:0,
                 from ../src/ast/pp.h:21,
                 from ../src/shell/main.cpp:25:
../src/ast/ast.h:50:19: fatal error: variant: No such file or directory
compilation terminated.
Makefile:4532: recipe for target 'shell/main.o' failed
make: *** [shell/main.o] Error 1
```
.
Could you help me with this?

If any further information for reproduction is needed, please tell me. 
Thanks in advance!

**Comment by andrewvaughanj** [comment]
`variant` is a C++17 header: https://en.cppreference.com/w/cpp/header/variant

My guess is that it doesn't exist in g++ 7.5.0 on Ubuntu 16.04; can you try with a later gcc?

**Comment by sjoon2455** [comment]
Updating g++ and gcc to v9.4.0 solved the problem. Thanks @andrewvaughanj !
