### ISSUE TITLE
Python shebang in scripts (pyg2hpppy) maybe not good?

### ISSUE THREAD

**Issue by christianparpart** [Z3Prover/z3#5397]
https://github.com/Z3Prover/z3/blob/master/scripts/pyg2hpp.py#L1

Hi, while updating z3 on my local machine i realized it's breaking at that script, because I do not have `/usr/bin/python` but `/usr/bin/python2` and `/usr/bin/python3`.

Since this project is cmake based, it could be actually auto-detected and then this script is using what cmake found (or reconfigured) as path instead of hardcoding `python` as executable.

My system is an Ubuntu 21.04 (latest updates as of writing this post).

**Comment by NikolajBjorner** [comment]
I am commenting these lines out. The various builds work without them.
