### ISSUE TITLE
Quantifier-free completeness regression with `str.from_int`

### ISSUE THREAD

**Issue by maurobringolf** [Z3Prover/z3#5398]
Commit: d5c6abe14d3edc18667e5828144816ec756289fb

```
$ z3-4.8.10 unknown.smt2
sat
$ z3 unknown.smt2
unknown
$ cat unknown.smt2
(declare-const x Int)
(assert (str.<= (str.from_int x) (str.from_int (+ 5118 (abs x)))))
(check-sat)
```

**Comment by NikolajBjorner** [comment]
this seems fixed since the commit

**Comment by NikolajBjorner** [comment]
generally, str.from_int is very fragile. Simple things, such as searching for solutions for bounded x are not tried.

**Comment by maurobringolf** [comment]
Okay I will limit the expectations on str.from_int. And sorry about the report on an outdated build.
