### ISSUE TITLE
Build failure on Mac

### ISSUE THREAD

**Issue by akshatgit** [Z3Prover/z3#5401]
I'm getting the following error when I try to make z3 on mac:
```
(base) ➜ build (master) ✗ make
src/shell/lp_frontend.cpp
clang: warning: argument unused during compilation: '-msse' [-Wunused-command-line-argument]
clang: warning: argument unused during compilation: '-msse2' [-Wunused-command-line-argument]
error: unknown FP unit 'sse'
make: *** [shell/lp_frontend.o] Error 1
```

I had generated the makefile using the following command: `python scripts/mk_make.py --java`

System information:
```
OS: Big Sur 11.4

(base) ➜ build (master) ✗ c++ --version
Apple clang version 12.0.5 (clang-1205.0.22.9)
Target: arm64-apple-darwin20.5.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```
Not sure if I'm doing following the right steps to build the z3 libs. 

Any help is appreciated!

**Comment by NikolajBjorner** [comment]
you should build for x64 so pass in the option to the build script that forces x64. See the README.md for instructions.
