### ISSUE TITLE
Unexpected behaviour change of tactic

### ISSUE THREAD

**Issue by HJLebbink** [Z3Prover/z3#5402]
The following tactic simplifies clauses just as expected (https://rise4fun.com/Z3/EO1p). When trying to reproduce this behaviour with the C API, I get different behaviour. After some trial-and-error I must conclude that somewhere between 4.8.6 and 4.8.11 something changed. See also [this](https://stackoverflow.com/questions/68307817/simplifying-subsumed-clauses-with-z3) question on SO.

```
(declare-fun x () Int)
(assert (or (>= x 2) (>= x 3)))
(apply (then ctx-solver-simplify propagate-values (par-then (repeat (or-else split-clause skip)) propagate-ineqs)))
```
yields:
```
(goals (goal (>= x 2)))
```
This works with 4.8.6; However, with 4.8.11 this simplifies to:
```
(goals (goal (>= x 2)) (goal (>= x 3)))
```
**Question**: Is this a regression or is this change intended? What would be a strategy to simplify this example in 4.8.11?

If it would help anyone, I could help narrow down the version in which this changed first occurred.

**Comment by NikolajBjorner** [comment]
ctx-solver-simplify apparently doesn't simplify the clause. ctx-solver-simplify doesn't by itself have any strong guarantees such as creating minimial clauses. If you have an application that depends on clause minimization, then something that targets this property would be more adequate. Otherwise, I say, you can't use syntactic properties for regression checks.

**Comment by rainoftime** [comment]
@HJLebbink The simplification procedure/algorithm in 
https://www.cs.utexas.edu/~isil/sas2010.pdf may work for your case.
You may consider implementing one:)

**Comment by HJLebbink** [comment]
@NikolajBjorner That makes sense (that simplify strategies do not guarantee syntactic optimization) I guess I just got used to the side-effect of some simplification. Please feel free to close this issue as "behaviour as intended" (although inconvenient)
@rainoftime Thanx for the pointer. If you are are aware of implementations (for Z3 as a tactic) please let me know.
