### ISSUE TITLE
Copy-pasted code: same code on then- and else- branch 

### ISSUE THREAD

**Issue by ustchcs-bugfinder** [Z3Prover/z3#5403]
https://github.com/Z3Prover/z3/blob/4c53655be7543555936bf6ded5a4c915a1c9c874/src/sat/smt/euf_proof.cpp#L37

Same as L39

https://github.com/Z3Prover/z3/blob/4c53655be7543555936bf6ded5a4c915a1c9c874/src/sat/smt/euf_proof.cpp#L39

**Comment by NikolajBjorner** [comment]
I want this there for later
