### ISSUE TITLE
Azure Demo in Wiki is a 404

### ISSUE THREAD

**Issue by colejohnson66** [Z3Prover/z3#5412]
The Azure Demo link in the main wiki page gives an “unknown notebook server” error.

https://z3examples-nbjorner.notebooks.azure.com/j/notebooks/guide.ipynb

**Comment by colejohnson66** [comment]
Should it be removed or fixed?

**Comment by NikolajBjorner** [comment]
I don't know where this link appears

**Comment by colejohnson66** [comment]
Under “Information” at the very top of the main page, it says “ Try it online on Azure using Jupyter.” with “Azure” being the broken link.

I’d remove this myself, but I didn’t want to if it would be preferred to fix it.

**Comment by NikolajBjorner** [comment]
ok done

**Comment by colejohnson66** [comment]
![B9208892-3E46-49CD-88B7-D682CEF48CFD](https://user-images.githubusercontent.com/11381599/125963533-2733eaa7-bc7b-4e47-b324-b5bc9f61ebf8.jpeg)
