### ISSUE TITLE
cannot install z3-solver

### ISSUE THREAD

**Issue by saramohammadinejad** [Z3Prover/z3#5418]
(base) saras-MacBook-Pro-3:LfD_STL_single_goal saramohamadi$ pip3 install z3-solver
Collecting z3-solver
  Downloading z3-solver-4.8.12.0.tar.gz (4.4 MB)
     |████████████████████████████████| 4.4 MB 3.6 MB/s 
Building wheels for collected packages: z3-solver
  Building wheel for z3-solver (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /Library/Frameworks/Python.framework/Versions/3.8/bin/python3.8 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/vl/x_fx4m791kj8wjpq4v0ggcqh0000gn/T/pip-install-1s0f5rqm/z3-solver_f84511ef6b5347fa9de024d32e6241ff/setup.py'"'"'; __file__='"'"'/private/var/folders/vl/x_fx4m791kj8wjpq4v0ggcqh0000gn/T/pip-install-1s0f5rqm/z3-solver_f84511ef6b5347fa9de024d32e6241ff/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /private/var/folders/vl/x_fx4m791kj8wjpq4v0ggcqh0000gn/T/pip-wheel-unhwrutb
       cwd: /private/var/folders/vl/x_fx4m791kj8wjpq4v0ggcqh0000gn/T/pip-install-1s0f5rqm/z3-solver_f84511ef6b5347fa9de024d32e6241ff/
  Complete output (193 lines):
  running bdist_wheel
  running build
  Configuring Z3
  -- The CXX compiler identification is AppleClang 10.0.1.10010046
  -- Detecting CXX compiler ABI info
  -- Detecting CXX compiler ABI info - done
  -- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ - skipped
  -- Detecting CXX compile features
  -- Detecting CXX compile features - done
  -- Z3 version 4.8.12.0
  -- Failed to find git directory.
  CMake Warning at CMakeLists.txt:51 (message):
    Disabling Z3_INCLUDE_GIT_DESCRIBE
  Call Stack (most recent call first):
    CMakeLists.txt:100 (disable_git_describe)
  
  
  CMake Warning at CMakeLists.txt:55 (message):
    Disabling Z3_INCLUDE_GIT_HASH
  Call Stack (most recent call first):
    CMakeLists.txt:101 (disable_git_hash)
  
  
  -- CMake generator: Unix Makefiles
  -- Build type: Release
  -- Found PythonInterp: /Users/saramohamadi/.pyenv/shims/python
  -- PYTHON_EXECUTABLE: /Users/saramohamadi/.pyenv/shims/python
  -- Detected target architecture: x86_64
  -- Platform: Darwin
  -- Not using libgmp
  -- Not using Z3_API_LOG_SYNC
  -- Thread-safe build
  -- Performing Test HAS_SSE2
  -- Performing Test HAS_SSE2 - Success
  -- Looking for C++ include pthread.h
  -- Looking for C++ include pthread.h - found
  -- Performing Test CMAKE_HAVE_LIBC_PTHREAD
  -- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
  -- Found Threads: TRUE
  -- Performing Test HAS__Wall
  -- Performing Test HAS__Wall - Success
  -- C++ compiler supports -Wall
  -- Treating only serious compiler warnings as errors
  -- Performing Test HAS__Werror_odr
  -- Performing Test HAS__Werror_odr - Success
  -- C++ compiler supports -Werror=odr
  -- Performing Test HAS__Werror_delete_non_virtual_dtor
  -- Performing Test HAS__Werror_delete_non_virtual_dtor - Success
  -- C++ compiler supports -Werror=delete-non-virtual-dtor
  -- Performing Test HAS__Werror_overloaded_virtual
  -- Performing Test HAS__Werror_overloaded_virtual - Success
  -- C++ compiler supports -Werror=overloaded-virtual
  -- Performing Test HAS__fvisibility_hidden
  -- Performing Test HAS__fvisibility_hidden - Success
  -- C++ compiler supports -fvisibility=hidden
  -- Performing Test HAS__fvisibility_inlines_hidden
  -- Performing Test HAS__fvisibility_inlines_hidden - Success
  -- C++ compiler supports -fvisibility-inlines-hidden
  -- Performing Test HAS__fPIC
  -- Performing Test HAS__fPIC - Success
  -- C++ compiler supports -fPIC
  -- LTO enabled
  -- Performing Test HAS_LTO
  -- Performing Test HAS_LTO - Success
  -- CMAKE_CXX_FLAGS: "-std=c++11 -Werror=odr  -Werror=delete-non-virtual-dtor  -Werror=overloaded-virtual "
  -- CMAKE_EXE_LINKER_FLAGS: ""
  -- CMAKE_STATIC_LINKER_FLAGS: ""
  -- CMAKE_SHARED_LINKER_FLAGS: ""
  -- CMAKE_CXX_FLAGS_RELEASE: "-O3 -DNDEBUG -flto"
  -- CMAKE_EXE_LINKER_FLAGS_RELEASE: " -flto"
  -- CMAKE_SHARED_LINKER_FLAGS_RELEASE: " -flto"
  -- CMAKE_STATIC_LINKER_FLAGS_RELEASE: " -flto"
  -- Z3_COMPONENT_CXX_DEFINES: $<$<CONFIG:Debug>:Z3DEBUG>;$<$<CONFIG:Release>:_EXTERNAL_RELEASE>;$<$<CONFIG:RelWithDebInfo>:_EXTERNAL_RELEASE>;-D_MP_INTERNAL;$<$<CONFIG:Debug>:_TRACE>
  -- Z3_COMPONENT_CXX_FLAGS: -mfpmath=sse;-msse;-msse2;-Wall;-fvisibility=hidden;-fvisibility-inlines-hidden;-fPIC
  -- Z3_DEPENDENT_LIBS: Threads::Threads
  -- Z3_COMPONENT_EXTRA_INCLUDE_DIRS: /private/var/folders/vl/x_fx4m791kj8wjpq4v0ggcqh0000gn/T/pip-install-1s0f5rqm/z3-solver_f84511ef6b5347fa9de024d32e6241ff/core/build/src;/private/var/folders/vl/x_fx4m791kj8wjpq4v0ggcqh0000gn/T/pip-install-1s0f5rqm/z3-solver_f84511ef6b5347fa9de024d32e6241ff/core/src
  -- Z3_DEPENDENT_EXTRA_CXX_LINK_FLAGS:
  -- CMAKE_INSTALL_LIBDIR: "lib"
  -- CMAKE_INSTALL_BINDIR: "bin"
  -- CMAKE_INSTALL_INCLUDEDIR: "include"
  -- CMAKE_INSTALL_PKGCONFIGDIR: "lib/pkgconfig"
  -- CMAKE_INSTALL_Z3_CMAKE_PACKAGE_DIR: "lib/cmake/z3"
  -- Adding component util
  -- Adding component polynomial
  -- Adding rule to generate "algebraic_params.hpp"
  -- Adding component dd
  -- Adding component hilbert
  -- Adding component simplex
  -- Adding component automata
  -- Adding component interval
  -- Adding component realclosure
  -- Adding rule to generate "rcf_params.hpp"
  -- Adding component subpaving
  -- Adding component ast
  -- Adding rule to generate "pp_params.hpp"
  -- Adding component params
  -- Adding rule to generate "arith_rewriter_params.hpp"
  -- Adding rule to generate "array_rewriter_params.hpp"
  -- Adding rule to generate "bool_rewriter_params.hpp"
  -- Adding rule to generate "bv_rewriter_params.hpp"
  -- Adding rule to generate "fpa_rewriter_params.hpp"
  -- Adding rule to generate "fpa2bv_rewriter_params.hpp"
  -- Adding rule to generate "pattern_inference_params_helper.hpp"
  -- Adding rule to generate "poly_rewriter_params.hpp"
  -- Adding rule to generate "rewriter_params.hpp"
  -- Adding rule to generate "seq_rewriter_params.hpp"
  -- Adding component rewriter
  -- Adding component normal_forms
  -- Adding rule to generate "nnf_params.hpp"
  -- Adding component macros
  -- Adding component model
  -- Adding rule to generate "model_evaluator_params.hpp"
  -- Adding rule to generate "model_params.hpp"
  -- Adding component tactic
  -- Adding rule to generate "tactic_params.hpp"
  -- Adding component substitution
  -- Adding component euf
  -- Adding component smt_params
  -- Adding rule to generate "smt_params_helper.hpp"
  -- Adding component parser_util
  -- Adding rule to generate "parser_params.hpp"
  -- Adding component grobner
  -- Adding component sat
  -- Adding rule to generate "sat_asymm_branch_params.hpp"
  -- Adding rule to generate "sat_params.hpp"
  -- Adding rule to generate "sat_scc_params.hpp"
  -- Adding rule to generate "sat_simplifier_params.hpp"
  -- Adding component nlsat
  -- Adding rule to generate "nlsat_params.hpp"
  -- Adding component core_tactics
  -- Adding component subpaving_tactic
  -- Adding component aig_tactic
  -- Adding component arith_tactics
  -- Adding component solver
  -- Adding rule to generate "combined_solver_params.hpp"
  -- Adding rule to generate "parallel_params.hpp"
  -- Adding rule to generate "solver_params.hpp"
  -- Adding component cmd_context
  -- Adding component extra_cmds
  -- Adding component smt2parser
  -- Adding component solver_assertions
  -- Adding component pattern
  -- Adding component bit_blaster
  -- Adding component lp
  -- Adding component mbp
  -- Adding component sat_smt
  -- Adding component sat_tactic
  -- Adding component nlsat_tactic
  -- Adding component ackermannization
  -- Adding rule to generate "ackermannization_params.hpp"
  -- Adding rule to generate "ackermannize_bv_tactic_params.hpp"
  -- Adding component proofs
  -- Adding component fpa
  -- Adding component proto_model
  -- Adding component smt
  -- Adding component bv_tactics
  -- Adding component smt_tactic
  -- Adding component sls_tactic
  -- Adding rule to generate "sls_params.hpp"
  -- Adding component qe
  -- Adding component muz
  -- Adding rule to generate "fp_params.hpp"
  -- Adding component dataflow
  -- Adding component transforms
  -- Adding component rel
  -- Adding component clp
  -- Adding component tab
  -- Adding component bmc
  -- Adding component ddnf
  -- Adding component spacer
  -- Adding component fp
  -- Adding component ufbv_tactic
  -- Adding component sat_solver
  -- Adding component smtlogic_tactics
  -- Adding rule to generate "qfufbv_tactic_params.hpp"
  -- Adding component fpa_tactics
  -- Adding component fd_solver
  -- Adding component portfolio
  -- Adding component opt
  -- Adding rule to generate "opt_params.hpp"
  -- Adding component api
  -- Adding component api_dll
  -- Emitting rules to build Z3 python bindings
  -- Emitting rules to install Z3 python bindings
  -- CMAKE_INSTALL_PYTHON_PKG_DIR not set. Trying to guess
  pyenv: version `my-venv-topic-classification' is not installed (set by /Users/saramohamadi/.pyenv/version)
  CMake Error at src/api/python/CMakeLists.txt:109 (message):
    Failed to determine your Python package directory
  
  
  -- Configuring incomplete, errors occurred!
  See also "/private/var/folders/vl/x_fx4m791kj8wjpq4v0ggcqh0000gn/T/pip-install-1s0f5rqm/z3-solver_f84511ef6b5347fa9de024d32e6241ff/core/build/CMakeFiles/CMakeOutput.log".
  error: Unable to configure Z3.
  ----------------------------------------
  ERROR: Failed building wheel for z3-solver

**Comment by NikolajBjorner** [comment]
I am not sure. Haven't seen this kind of error before.
The error message suggests your python installation is unable to determine where the package directory resides in the current environment.
