### ISSUE TITLE
usage help

### ISSUE THREAD

**Issue by hdarwin** [Z3Prover/z3#542]
```
#!/usr/bin/python
from z3 import *
eax=BitVec("eax", 32)
ecx=eax+0x1a
eax=eax+5
ecx=eax*ecx
edx=ecx
edx=edx >> 8
eax=edx ^ ecx
eax=eax >> 16
eax=eax ^ edx ^ ecx
s = Solver()
s.add(eax == 0x1c966f8d)
s.check()
m = s.model()
print m
print m[eax].as_long() # error
"""
Traceback (most recent call last):
  File "./sol.py", line 17, in <module>
    print m[eax].as_long()
  File "/usr/lib/python2.7/dist-packages/z3.py", line 5644, in __getitem__
    _z3_assert(False, "Integer, Z3 declaration, or Z3 constant expected")
  File "/usr/lib/python2.7/dist-packages/z3.py", line 86, in _z3_assert
    raise Z3Exception(msg)
z3types.Z3Exception: Integer, Z3 declaration, or Z3 constant expected
"""
```
i don't know what last line occur error.. what's the matter????

**Comment by NikolajBjorner** [comment]
In the last line, eax is a compound expression because you updated it in the previous lines from the first line declaration.

**Comment by hdarwin** [comment]
@NikolajBjorner ah I see, what can I use instead "m[eax]" do you have any suggestion?

**Comment by NikolajBjorner** [comment]
How about?

         from z3 import *
         eax0=BitVec("eax", 32)
         eax=eax0
         ecx=eax+0x1a
         ....
         s.add(eax == 0x1c966f8d)
         s.check()
         m = s.model()
         print m
         print m[eax0].as_long()

which produces:

       [eax = 1094795585]
       1094795585

**Comment by hdarwin** [comment]
@NikolajBjorner thanks a lot :) great!
