### ISSUE TITLE
Performance issues on UFLIA

### ISSUE THREAD

**Issue by merlinsun** [Z3Prover/z3#5421]
Hi, for the following SMT file containing some syntax errors:
[UFLIA.zip](https://github.com/Z3Prover/z3/files/6852341/UFLIA.zip)

Yieces2 can return error very quickly
But Z3 cannot be terminated 

OS: Ubuntu 18.04.5 LTS
Revision: [b84b5d](https://github.com/Z3Prover/z3/commit/b84b5d091e77724a3c842f7e5d7009be6552f041)

**Comment by NikolajBjorner** [comment]
it reports errors and skips the erroneous definitions and attempts solving
