### ISSUE TITLE
NNF tactic does not play well with existential quantification

### ISSUE THREAD

**Issue by cheshire** [Z3Prover/z3#543]
```python
x = Int('x')
f = Exists([x], x == 0)

// Results in `x!2 = 0`, the existential quantification root is lost.
nnfied = Tactic('nnf').apply(f).as_expr()
```

**Comment by NikolajBjorner** [comment]
By default NNF also skolemizes.
C:\z3\debug>z3 /pm:nnf
[module] nnf, description: negation normal form
    ignore_labels (bool) remove/ignore labels in the input formula, this option is ignored if proofs are enabled (default: false)
    max_memory (unsigned int) maximum amount of memory in megabytes (default: 4294967295)
    mode (symbol) NNF translation mode: skolem (skolem normal form), quantifiers (skolem normal form + quantifiers in NNF), full (default: skolem)
    sk_hack (bool) hack for VCC (default: false)
    skolemize (bool) skolemize (existential force) quantifiers (default: true)

You can change this behavior by setting the "skolemize" parameter to false.
