### ISSUE TITLE
Performance Java API vs. Command Line 

### ISSUE THREAD

**Issue by Potatofighter98** [Z3Prover/z3#5441]
If I want to prove the [attached benchmark](https://github.com/Z3Prover/z3/files/6898922/smt_comp_baby_53_reset_guest_std_unique_aug_gt_unsat_full_incomplete_quant.zip) according to the code snippet below with the Java API, I reach the timeout. If I use the command line, I get a proof immediately. I have this problem with other benchmarks as well, but with many the API also returns immediately. Do you have some suggestions on how to use the API to improve the performance?

		Map<String, String> context_settings = new HashMap<String, String>() { {
			put("auto-config", "false");
			put("proof", "true");}
		};
		Context context = new Context(context_settings);
		BoolExpr[] input = context.parseSMTLIB2File(path_to_file, null, null, null, null);
		
		Solver solver = context.mkSolver();
		Params solver_settings = context.mkParams();
		solver_settings.add("mbqi", true);
		solver_settings.add("proof", true);
		solver_settings.add("timeout", 600000);
		solver_settings.add("max_memory", 6000);
		solver.setParameters(solver_settings);
		solver.add(input);

		Status status = solver.check();
		assert(status.equals(Status.UNSATISFIABLE));

Thanks for your help in advance!

**Comment by NikolajBjorner** [comment]
You fix the random seeds inside of the file. It could depend on the seeds what works and what doesn't.
For sure, if you have auto_config=true, it will enable "cheap fourier-motzkin" elimination during pre-processing.
This seems essential for this benchmark. Unfortunately, this option isn't exposed as a toggle, nor is it invoked uniformly when it is an advantage.
