### ISSUE TITLE
Soundness bug in QF_ABV

### ISSUE THREAD

**Issue by merlinsun** [Z3Prover/z3#5447]
Hi,
For the following instance, all the formulas at every level in the assertion stack are satisfiable, but with specific tactics Z3 returns:
>unknown
>unknown
>unknown
>unknown
>unknown
>unknown
>unknown
>unknown
>unknown
>unknown
>unknown
>unsat

While Z3 can give correct answer with (check-sat).
[QF_ABV.zip](https://github.com/Z3Prover/z3/files/6912385/QF_ABV.zip)

Revison:[6dfaaa](https://github.com/Z3Prover/z3/commit/6dfaaa43cd329ba982a833ce9e1d8257cdcc31fc)

**Comment by merlinsun** [comment]
The problem disappeared in the latest commit.

**Comment by NikolajBjorner** [comment]
see commit message for comment
