### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by saramohammadinejad** [Z3Prover/z3#5450]
Hi, when I run the following code I get a segmentation fault 11:

from z3 import *
solver = Optimize()

Do you know how to resolve the issue?

I’m using Python 3.9 on Mac.

Thanks,
Sara

**Comment by NikolajBjorner** [comment]
I don't know how to address this. 
There is not enough information from your report to determine what is going on.
If this was a problem with the z3 release it would occur all the time for everybody.

It is possibly related to dll includes. At least, this is a common situation when encountering such crashes.
If your PATH is set to include a DLL for a different version of Z3 than your python installation has, it causes these errors.
