### ISSUE TITLE
arithmetic on mixed FP sorts

### ISSUE THREAD

**Issue by chloesack92** [Z3Prover/z3#5461]
I am wondering, does z3 support mixing or changing FP sorts? For example, is it possible to add an fpa(10, 20) to an fpa(15, 40), maybe by extending the former to be of the same sort as the latter, and then performing an fpa_add?

I'm using the C++ API and can't quite see any support for this sort of thing. Naively trying to perform arithmetic across different floating-point types fails, of course.

**Comment by chloesack92** [comment]
I see now that fpa_to_fpa() can be used for this purpose :smiley:  sorry to bother you!

**Comment by wintersteiger** [comment]
Yep, just convert the numbers via `Z3_mk_fpa_to_fp_float()` or `fpa_to_fpa()`. Note that the latter depends on the rounding mode in the context, be careful you set the up right, especially when converting to smaller sizes.
