### ISSUE TITLE
Incorrect result after applying Tactic('solve-eqs')

### ISSUE THREAD

**Issue by hwu71** [Z3Prover/z3#5462]
### Description
I was trying to use Tactic('solve-eqs') to get a simpler expression. When testing with 
```
expr = Extract(0,
         0,
         ZeroExt(63,
                 Extract(0,
                         0,
                         If(0 ==
                            y,
                            one,
                            zero)))) != 0
```
The expected result is `y == 0`, but I got `True`. 

### Code
The complete code is shown below.
```
from z3 import *
ctx = Context()
y = BitVec('y', 32, ctx)
one = BitVecVal(1,1, ctx)
zero = BitVecVal(0, 1, ctx)
expr = Extract(0,
         0,
         ZeroExt(63,
                 Extract(0,
                         0,
                         If(0 ==
                            y,
                            one,
                            zero)))) != 0
t_solve_eqs = Tactic('solve-eqs', ctx=ctx)
t_simplify = Tactic('simplify', ctx=ctx)

print("\nResult of Tactic 'solve-eqs'")
r = t_solve_eqs(expr) # type: z3.ApplyResult
expr_simplified = r.as_expr() # type: z3.BoolRef
print("expr's apply result", r)
print("simplified expr is:", expr_simplified)

print("\nResult of Tactic 'simplify'")
r = t_simplify(expr) # type: z3.ApplyResult
expr_simplified = r.as_expr() # type: z3.BoolRef
print("expr's apply result", r)
print("simplified expr is:", expr_simplified)
```
Output:
```
Result of Tactic 'solve-eqs'
expr's apply result [[]]
simplified expr is: True

Result of Tactic 'simplify'
expr's apply result [[y == 0]]
simplified expr is: y == 0
```

**Comment by NikolajBjorner** [comment]
The result of a tactic is a set of subgoals. Each "Goal" has a method called "convert_model". It can be used to convert a model generated for the subformulas in the sub-goal into a model for the original goal. The solve-eqs tactic eliminates 'y' from the subgoals. In doing so it registers a model conversion that ensures that y gets interpreted as 0. 
Thus, the constraint y == 0 is implicitly available in the model conversion functionality.

**Comment by hwu71** [comment]
Thanks for your explanation. It seems that I cannot just call r.as_expr() to merge the result of Tactic. What's the suggested way to collect the simplified result after Tactic('ctx-solver-simplify', 'solve-eqs')? Should I do `s = Solver(ctx=ctx); s.add(r[0]); s.check(); r[0] = r[0].convert_model(s.model())` whenever I see an empty subgoal?
