### ISSUE TITLE
Is there still a way to use smtlib1 for solving.

### ISSUE THREAD

**Issue by Applonce** [Z3Prover/z3#5464]
Hi, I am unsure if this is possible but is there an option to use SMTLIB1 language for solving? I am asking because i'm using SPF and SPF only has translators for SMTLIB1 but current Z3 seems to not support it anymore. If anyone knows if smtlib1 still can be used, do let me know how or the last z3 version to support it would help as well.

Thanks,

Arun

**Comment by NikolajBjorner** [comment]
The SMTLIB1 and SIMPLIFY parsers have been deprecated as noted in the release notes:
https://github.com/Z3Prover/z3/blob/master/RELEASE_NOTES
You would have to convert files to the new format.
