### ISSUE TITLE
reduce_args tactic produces models with a default value only

### ISSUE THREAD

**Issue by nunoplopes** [Z3Prover/z3#547]
The reduce_args tactic's model converter isn't playing very nicely. See the following example:

```Python
from z3 import *
f = Function('f', IntSort(), IntSort())

s = AndThen(Tactic('reduce-args'), Tactic('smt')).solver()
s.add(Or(f(1) == 2, f(2) == 3))
s.check()
print s.model()

s = Tactic('smt').solver()
s.add(Or(f(1) == 2, f(2) == 3))
s.check()
print s.model()
```

Outputs:
```
[f = [else -> If(Var(0) == 2, 0, 2)]]
[f = [1 -> 2, 2 -> 0, else -> 2]]
```

It would be nicer to get the map as we do without using the tactic, since then the API works properly (rather than potentially having to parse the "default" expression).

**Comment by wintersteiger** [comment]
In general the else expression can be arbitrarily complex, see for instance the macro-finder which detects function definitions, so that part we can't get rid of. For this particular case, we should push the `If` up though.

**Comment by wintersteiger** [comment]
I just added this sort of compression to the extension_model_converter. It works at least for the simple, obvious cases as described here.

**Comment by wintersteiger** [comment]
Actually, that was the wrong place to add that, I'm moving it to func_interp.
