### ISSUE TITLE
rise4fun.com web page is down

### ISSUE THREAD

**Issue by ftc** [Z3Prover/z3#5472]
I hope this is an appropriate place to post this. https://rise4fun.com has been down for the last two days. I have tried with different machines and different locations.

Work around:

The documentation is available on [archive.org](https://web.archive.org/web/20210119175613/https://rise4fun.com/Z3/tutorial/guide) (without the online interpreter).  

If someone is looking for a way to try Z3 without going through the build process, I am happy to upload a docker container with the latest version.

**Comment by NikolajBjorner** [comment]
It is pretty safe to assume that rise4fun will remain offline: the infrastructure used to build rise4fun is dated by about a decade and a complete overhaul would be required for rise4fun functionality to get it online with modern services and addressing any compliance issues.

Contributions for creating alternatives for using z3 install free (and maybe online) are highly welcome.
