### ISSUE TITLE
[Z3py] Segfault when invoking ZeroExt with invalid arguments

### ISSUE THREAD

**Issue by 4tXJ7f** [Z3Prover/z3#548]
The following code segfaults with Z3py:

```
>>> simplify(ZeroExt(-1, BitVecVal(5, 8)))
Segmentation fault: 11
```

Not a very important issue, just thought that I'd report it for completeness.

**Comment by wintersteiger** [comment]
Thanks for reporting this, it's now fixed (it now rejects negative zero-extension).
