### ISSUE TITLE
Got "unknown", but it can be proved that the formula is sat

### ISSUE THREAD

**Issue by user93702699** [Z3Prover/z3#5480]
Z3 version 4.8.12 - 64 bit

```
(declare-datatypes () ((N a1 a2 a3 a4 a5 a6 a7 a8 a9)))
(declare-fun grid (N N) N)

(assert (forall ((x1 N) (y1 N) (x2 N) (y2 N) (a N) (b N))
  (=>
    (and
      (= a (grid x1 y1))
      (= b (grid x2 y2))
      (not (and
        (= x1 x2)
        (= y1 y2)
      ))
      (or
        (= x1 x2)
        (= y1 y2)
      )
    )
    (not (= a b))
  )
))

(check-sat)
```

Z3 prints "unknown" for this code. If you leave only 4 elements in the definition of `N` (a1, a2, a3, a4), then Z3 prints "sat".

I don't see why Z3 doesn't keep searching. `N` is finite, `grid` is also finite, there is a finite amout of combinations, so it is decidable in first-order logic. Why does Z3 stop searching and gives up before checking all possibilities? Is there a way I can force Z3 to continue searching?

**Comment by NikolajBjorner** [comment]
Use (get-info :reason-unknown) It tells you that the maximal number of mbqi instantiation threshold was reached. You can configure z3 to up the threshold. 

```
z3 5480.smt2 /v:1 smt.relevancy=2   smt.mbqi.max_instantiations=10000000

(smt.stats 5605 1203096 2970886 57482104   715/0   243/121 11551 475244  168.11)
(smt.stats 5606 1203322 2971126 57499066   703/0   463/155 11552 475257  168.11)
sat
```

**Comment by user93702699** [comment]
@NikolajBjorner. Ok thanks, but the following code works without increasing mbqi, but it is equivalent to the above code:

```
(declare-datatypes () ((N a1 a2 a3 a4 a5 a6 a7 a8 a9)))
(declare-fun grid (N N) N)

(assert (forall ((x1 N) (y1 N) (x2 N) (y2 N))
  (=>
    (and
      (not (and
        (= x1 x2)
        (= y1 y2)
      ))
      (or
        (= x1 x2)
        (= y1 y2)
      )
    )
    (not (= (grid x1 y1) (grid x2 y2)))
  )
))

(check-sat)
```

Why is Z3 instantiating `a` and `b` in the original formula? Can't it just figure out that `(= a (grid x1 y1))` fixes `a` in terms of `x1` and `y1`? It's just an alias. Does it mean that if I want to add more aliases for expressions, Z3 will instantiate all of them in the quantifiers?

**Comment by NikolajBjorner** [comment]
Having destructive equality resolution happening in such cases could be nice, but it isn't the case.
