### ISSUE TITLE
Clang SAT with z3 failed on unsigned int constraints

### ISSUE THREAD

**Issue by tdnguyenND** [Z3Prover/z3#5481]
I'm trying to write a checker on llvm-clang with z3 solver for better accuracy.

It worked fine until I ran a test which had calculation on unsigned int. Here is the screenshot of constraints when I dump the error state.enter image description here 
![image](https://user-images.githubusercontent.com/49394863/129545237-87721f53-f806-43ca-9bba-7aa5b62b91d6.png)
These constraints are conflicted but z3 seems to ignored it.
Is there any way I can configure z3 to solve this constraint?

**Comment by NikolajBjorner** [comment]
you are using some tool on top of z3. File the bug against that tool.
