### ISSUE TITLE
Datatype constructors aren't visible

### ISSUE THREAD

**Issue by LeventErkok** [Z3Prover/z3#5486]
This script:

```
(set-logic ALL)

(declare-datatypes ((Pair 2)) ((par (X Y) ((pair (first X) (second Y))))))

; Uncomment the following line and it works!
; (define-fun x () (Pair Bool Bool) (pair true true))

(assert (= (first (pair true true))  true))
```

Causes z3 to say:

```
(error "line 8 column 33: unknown constant pair (Bool Bool) ")
```

Interestingly, if you uncomment the 6th line with `define-fun`, it goes through without any complaint.

**Comment by NikolajBjorner** [comment]
Type resolution by the parser is rudimentary: it searches through existing types to resolve for pair. It does not deduce the type of pair based on arguments (even if this is "just" a matter of matching). By default expect to have to type annotate. Luckily, SMTLIB2 has the facilities:


```
(assert (= (first ((as pair (Pair Bool Bool)) true true))  true))
```

**Comment by LeventErkok** [comment]
Thanks @NikolajBjorner I get tripped on this on a regular basis and always forget to annotate.
