### ISSUE TITLE
 ExprRef's __eq__  returns either Boolean or BoolRef

### ISSUE THREAD

**Issue by zell08v** [Z3Prover/z3#549]
Z3py's ExprRef is equipped with  \_\_hash\_\_, which should allow us to  use ExprRef  as a dictionary key; ExprRef also  implements \_\_eq\_\_, but apparently it returns either Boolean or BoolRef.  

So I am somewhat concerned about whether it is right and safe to use ExprRef in a hashtable ? Maybe something I misunderstand?

 follows:
   
    def __eq__(self, other):
        """Return a Z3 expression that represents the constraint `self == other`.

        If `other` is `None`, then this method simply returns `False`.

        >>> a = Int('a')
        >>> b = Int('b')
        >>> a == b
        a == b
        >>> a == None
        False
        """
        if other == None:
            return False
        a, b = _coerce_exprs(self, other)
        return BoolRef(Z3_mk_eq(self.ctx_ref(), a.as_ast(), b.as_ast()), self.ctx)

**Comment by NikolajBjorner** [comment]
This method could return BoolVal(False, self.ctx()) instead of just False.
