### ISSUE TITLE
python bindings of older version

### ISSUE THREAD

**Issue by kgoyal40** [Z3Prover/z3#5492]
Hi, Is it possible to get the python bindings of an older version (specifically 4.8.10)?

**Comment by andrewvaughanj** [comment]
Do the files attached to this release:

- https://github.com/Z3Prover/z3/releases/tag/z3-4.8.10

Particularly:

- https://github.com/Z3Prover/z3/releases/download/z3-4.8.10/z3_solver-4.8.10.0-py2.py3-none-manylinux1_x86_64.whl

not work for you?

**Comment by kgoyal40** [comment]
Hi, Thanks for the your answer. I know this is a bit late, but I was hoping to install z3-4.8.8 and the .whl file is not provided for that version.

**Comment by NikolajBjorner** [comment]
You would have to build the whl file yourself by pulling the appropriate sources. There is no support for downlevel versions.

**Comment by kgoyal40** [comment]
Hi, I have a project where I was using quantifiers over non-linear real arithmetic. Switching to 4.8.10 has made the solver very slow. I was using 4.8.8 before. Can you tell me if some default setting was changed in the arithmetic solver between 4.8.8 and 4.8.10?
