### ISSUE TITLE
z3 crashes python - trap divide error in libz3.so (mpz_manager::machine_div)

### ISSUE THREAD

**Issue by jpstotz** [Z3Prover/z3#5499]
Using z3-solver 4.8.12.0 I encountered several crashes because of libz3. Based on the instruction pointer and the base address of libz3 I end up at address 0x12FE074 which seems to belong to `mpz_manager<false>::machine_div(mpz const&, mpz const&, mpz&) _ZN11mpz_managerILb0EE11machine_divERK3mpzS3_RS1_ proc near`
That should be [Line 564 in mpz.cpp](https://github.com/diepbp/z3-trau/blob/16287478121985742f797c151d5501f2a6df92e3/src/util/mpz.cpp#L564)

from dmesg:
```
Sat Aug 21 20:43:21 2021] traps: pypy3[44177] trap divide error ip:7fea0d42d074 sp:7ffcb7fcb1b8 error:0 in libz3.so[7fea0c12f000+16a3000]
[Sat Aug 21 21:19:15 2021] traps: pypy3[24036] trap divide error ip:7f570b969074 sp:7fffca1caee8 error:0 in libz3.so[7f570a66b000+16a3000]
[Sun Aug 22 00:45:26 2021] traps: pypy3[10593] trap divide error ip:7f95c2d39074 sp:7ffd6b2ff758 error:0 in libz3.so[7f95c1a3b000+16a3000]
[Sun Aug 22 02:31:57 2021] traps: pypy3[15483] trap divide error ip:7f122842b074 sp:7ffc02616af8 error:0 in libz3.so[7f122712d000+16a3000]
[Sun Aug 22 03:31:29 2021] traps: pypy3[19854] trap divide error ip:7fbeffe12074 sp:7ffd7dd0f178 error:0 in libz3.so[7fbefeb14000+16a3000]
[Sun Aug 22 04:24:39 2021] traps: pypy3[24711] trap divide error ip:7faeebe02074 sp:7ffc8b211eb8 error:0 in libz3.so[7faeeab04000+16a3000]
[Sun Aug 22 07:11:10 2021] traps: pypy3[30620] trap divide error ip:7f25eb425074 sp:7ffd18afc488 error:0 in libz3.so[7f25ea127000+16a3000]
[Sun Aug 22 08:05:47 2021] traps: pypy3[39701] trap divide error ip:7f3e068e0074 sp:7ffd329b9bf8 error:0 in libz3.so[7f3e055e2000+16a3000]
```
I also tried version 4.8.11.0 but I also got trap divide errors, just the same error (just a slightly different address).

The used Python interpreter is `pypy3.7-v7.3.5-linux64`.

**Comment by NikolajBjorner** [comment]
so division by 0.
The issue should be above. Code should not call this code with a 0 divisor.
I can add checks and exceptions, but the more interesting question would be what triggers this.

**Comment by jpstotz** [comment]
Using version 4.8.10.0 the error seems to be gone. 

I am trying to set-up an environment where I can reproduce the error, then I can help to get more details to identify the trigger.

**Comment by NikolajBjorner** [comment]
added z3 exception for some cases of 0 division to ease localization.

**Comment by NikolajBjorner** [comment]
note that we _do_ have a way to record and replay almost all API interaction (Z3_open_log). 
Reproducing a bug with python in the loop is therefore not necessarily the only avenue.

**Comment by NikolajBjorner** [comment]
reopen when there is a repro

**Comment by fmagin** [comment]
I narrowed down the issue to minimal Python code of the framework that actually uses z3 (whose authors also maintain the z3 Python package AFAIK) and captured the API interactions:
[z3.log](https://github.com/Z3Prover/z3/files/7185033/z3.log)

I am not sure how I can run this log against a version of Z3 again, I hope that this already suffices to reproduce this issue.
