### ISSUE TITLE
How to use python to represent re.allchar?  z3-solver==4.8.12.0

### ISSUE THREAD

**Issue by Jupiter-19** [Z3Prover/z3#5500]
Is there a python function to represent re.allchar?
In z3-solver==4.8.10.0
```python
from z3 import *
allchar = Range(Unit(BitVecVal(0, 8)), Unit(BitVecVal(255, 8)))
allchar_txt = Concat(allchar, Re(".txt"))
```
is Ok, but in z3-solver==4.8.12.0, an error occurs when the code is running.
```
z3.z3types.Z3Exception: b"Sort of function 're.++' does not match the declared type. Given domain: (RegEx (Seq (_ BitVec 8))) (RegEx String)
```
And I already know that `Full(ReSort(StringSort()))` means `re.all` and `Empty(ReSort(StringSort()))` means `re.none`.

**Comment by NikolajBjorner** [comment]
Not too easy because characters are now Unicode. You would have to encode strings with the right characters, such as "\u{0}" and  "\u{2ffff}". I have added a shortcut

```
from z3 import *

re = ReSort(StringSort())
all_char = AllChar(re)
print(all_char)
```
