### ISSUE TITLE
Project description on pypi.org links to fork instead of main project

### ISSUE THREAD

**Issue by jpstotz** [Z3Prover/z3#5503]
The Description of the https://pypi.org/project/z3-solver/ contains the text

> In the event of technical difficulties related to configuration, compilation, or installation, please submit issues to https://github.com/angr/angr-z3

The link is in my understanding a (dead?) fork of z3. Therefore I was a bit confused when I noticed this description. 
Because the releases mentioned on pypi.org clearly are those from this main project.

**Comment by NikolajBjorner** [comment]
OK, will be updated to point to github.com/z3prover/z3.git next release
