### ISSUE TITLE
Allchar function in Python  is not entirely correct.

### ISSUE THREAD

**Issue by Jupiter-19** [Z3Prover/z3#5519]
Thank you so much for adding allchar function. https://github.com/Z3Prover/z3/issues/5500

However, I think something is going wrong and I write a piece of code to show this.

```python
# z3-solver==4.8.13.0
from z3 import *

r = String("r")
allchar = AllChar(ReSort(StringSort()))

s = Solver()
s.add(InRe(r, allchar))
s.add(Not(InRe(r, Range(chr(0), chr(127)))))

count = 0
while s.check() == sat and count < 100:
    model = s.model()
    print(model)
    s.add(Not(r == model[r]))
    count += 1
```
There are some strange solutions, such as
```
[r = "þ"]
[r = "\\u{40=<}"]
```
Paradoxically, `simplify(InRe("þ", allchar))` equals false cause StringVal function changes "þ" to "\u{fe}".

According to [smtlib2.6](https://smtlib.cs.uiowa.edu/theories-UnicodeStrings.shtml) or [smtlib3.0](http://smtlib.cs.uiowa.edu/version3.shtml), allchar means
```python
hex_char = Union(Range("0", "9"), Range("a", "f"))
allchar = Union(Range(chr(0), chr(127)), Concat(Re("\\u{"), Loop(hex_char, 2, 6), Re("}")))
```
But,  it doesn't show up as "re.allchar" when I use `to_smt2()` or `sexpr()`.

**Comment by NikolajBjorner** [comment]
This is at the python level. Can you propose a fix?

This is the function that takes a sequence of unsigned integers corresponding to character codes and attempt to print a unicode string in readable form:

```
    def as_string(self):
        """Return a string representation of sequence expression."""
        if self.is_string_value():
            string_length = ctypes.c_uint()
            chars = Z3_get_lstring(self.ctx_ref(), self.as_ast(), byref(string_length))
            return string_at(chars, size=string_length.value).decode("latin-1")
        return Z3_ast_to_string(self.ctx_ref(), self.as_ast())
```

This is the function that attempts to create escape sequences:

```

def StringVal(s, ctx=None):
    """create a string expression"""
    s = "".join(str(ch) if ord(ch) < 128 else "\\u{%x}" % (ord(ch)) for ch in s)
    ctx = _get_ctx(ctx)
    return SeqRef(Z3_mk_lstring(ctx.ref(), len(s), s), ctx)
```

Neither appear to be correct with respect to round-tripping special characters.
I am no more familiar with how to do this right with python libraries than anybody else.

**Comment by Jupiter-19** [comment]
It's easier to understand as_string function. When `[r = "\\u{40=<}"]`  at python level,  it means `[r = "\\u{40de}"]` by sexpr function. I do some experiments and confirm

```
chr(57) = "9"  ->  9
chr(58) = ":"  ->  a
chr(59) = ";"  ->  b
chr(60) = "<"  ->  c
chr(61) = "="  ->  d
chr(62) = ">"  ->  e
chr(63) = "?"  ->  f
```

I think this is because string theory is based on integer theory. Here's my test code:

```python
# z3-solver==4.8.13.0
from z3 import *
r = String("r")
s = Solver()
s.add(InRe(r, AllChar(ReSort(StringSort()))))
s.add(Not(InRe(r, Range(chr(0), chr(127)))))
count = 0
while s.check() == sat and count < 20:
    count += 1
    model = s.model()
    s.add(r != model[r])
    print(model, '\t', model[r].sexpr())
'''
# some result
[r = "\\u{40=>}"] 	 "\u{40de}"
[r = "\\u{40?>}"] 	 "\u{40fe}"
[r = "\\u{40??}"] 	 "\u{40ff}"
[r = "\\u{40=<}"] 	 "\u{40dc}"
[r = "\\u{40?<}"] 	 "\u{40fc}"
[r = "\\u{50?<}"] 	 "\u{50fc}"
[r = "\\u{51?<}"] 	 "\u{51fc}"
[r = "\\u{<1?<}"] 	 "\u{c1fc}"
[r = "\\u{<1?4}"] 	 "\u{c1f4}"
[r = "\\u{<1?6}"] 	 "\u{c1f6}"
[r = "\\u{2<1?6}"] 	 "\u{2c1f6}"
[r = "\\u{2<0?6}"] 	 "\u{2c0f6}"
'''
```

However, we can't quite tell whether it represents eight characters `\\u{40=>}` or a character `\u40de` at python level even we have  string_length.value.

**Comment by Jupiter-19** [comment]
The other problem is more difficult to handle, and I only get a slightly better approach,

```python
from functools import reduce

def StringVal(s, ctx=None):
    """create a string expression"""
    s = reduce(lambda x, y: x+y, (ch.encode("latin-1") if ord(ch) < 256 else ch.encode('utf8') for ch in s), bytes())
    ctx = _get_ctx(ctx)
    return SeqRef(Z3_mk_lstring(ctx.ref(), len(s), s), ctx)

print(simplify(InRe(chr(65), allchar)))  # True
print(simplify(InRe(chr(255), allchar)))  # True
print(simplify(InRe(chr(256), allchar)))  # False
```

Compared with the previous code, it  express `chr(128)~chr(255)` correctly when using StringVal cause len(s) equals 1 instead of 2. Still, I do not know how to deal with chr(256) even though len('\u0100') = len('\U00000100') = 1.

`len("\\u{%x}" % (ord(chr(255)))) = 6` means previous code changed the meaning of the characters.

**Comment by NikolajBjorner** [comment]
the first problem is internal to z3. Has been fixed.

**Comment by NikolajBjorner** [comment]
the second problem might be dealt with with the later update.
It shows I did not test the round-trip in any reasonable way.
One untested piece remains: I am returning the escaped string with a single \ before u.
It could appear this works, but I am running out of steam for strings for today.

**Comment by NikolajBjorner** [comment]
The single escape character appears to be correct.
