### ISSUE TITLE
QF_LIA solver: check 'unsat' with values taken directly from a 'sat' check + model

### ISSUE THREAD

**Issue by rupran** [Z3Prover/z3#5527]
I'm using the Python bindings for  z3 to iteratively generate solutions for a placement problem described by a number of inequalities over integers. A minimized stand-alone implementation is the following:

```python3
import time
import z3

end_var = z3.Int('end')
p = z3.IntVector('p', 28)
s = z3.SolverFor('QF_LIA', logFile='z3.log')
s.from_file('./model.txt')
cur_end = 369201
start = time.time()
while True:
    # Check for a solution with end < current minimal end
    res = s.check(end_var < cur_end)
    print('res {}'.format(res))
    if res != z3.sat:
        break
    # Get the assigned values
    model = s.model()
    print('new end: {}, time {:.3f} seconds'.format(model[end_var].as_long(), time.time() - start))
    # Collect all assumptions we just got from the checker...
    assumptions = []
    for i in range(28):
        assumptions.append(p[i] == model.eval(p[i], model_completion=True))
    # ... and check if their values can all be set at the same time
    res2 = s.check(z3.And(assumptions))
    print('res2 {}'.format(res2))
    if res2 != z3.sat:
        # In this case, the assigned values do not fit the model... why was res == z3.sat?
        print('buggy?')
        print(model)
        break
    # Try to push end_var lower
    cur_end = model.eval(end_var, model_completion=True)
```
with this [model.txt](https://github.com/Z3Prover/z3/files/7089542/model.txt).

z3 quickly comes up with a solution where e.g. `end_var = 209457` (<< 1s) and then spends a long time (2000 to 4000s on my machine) trying to generate an even better solution.  After that time, `res` (the first check) says 'sat' and `model[end_var]` is set to  e.g. `49713`  but when I feed all the values from `s.model()` back into `s.check()` (the check for `res2` with all assumptions taken from the current model) it fails with 'unsat'.

Am I misunderstanding something about the solving process or is this a bug?

I installed z3 from pip, z3.get_version() shows `4.8.12`

For the solution with `end_var = 49713`, these are the values in the model:
```
p__0 = 11,
p__1 = 40,
p__2 = 32,
p__3 = 12,
p__4 = 25,
p__5 = 25,
p__6 = 35,
p__7 = 35,
p__8 = 26,
p__9 = 38,
p__10 = 21,
p__11 = 43,
p__12 = 39,
p__13 = 36,
p__14 = 38,
p__15 = 31,
p__16 = 37,
p__17 = 43,
p__18 = 33,
p__19 = 39,
p__20 = 45,
p__21 = 37,
p__22 = 24,
p__23 = 30,
p__24 = 37,
p__25 = 27,
p__26 = 36,
p__27 = 12,
start = 46216,
end = 49713,
```
which clearly violates (among others) the last rule in model.txt:
```
(assert (> (+ (* p__27 4096) 383 178) (+ (* p__26 4096) 46 16146)))
```
which is equal to  `(assert (> 49713 163648))` with the model values.

**Comment by NikolajBjorner** [comment]
Not sure about the repro, seems to either take a very long time or not happening.
You can try the following as workaround, start the file as follows:

```
import time
import z3

z3.set_option("smt.arith.solver","2")
z3.set_option("smt.auto_config","false")
z3.set_option("smt.relevancy","0")

end_var = z3.Int('end')
```

Then it uses a different arithmetic solver, in case there is a bug in the new one that has escaped and affects you.

**Comment by rupran** [comment]
With the above options I also get `209457` after about 1 second. and while it did not give me any invalid values after that, it's still running after about 12 hours trying to prove unsatisfiability. I'll keep it running for now and see if it will terminate at some point.

Without the options (that is, with the newer solver) the wrong model is generated after about 45 minutes. Is there something else I can provide you with to follow up on the wrong values or is this model just too large to debug?
