### ISSUE TITLE
Newer version ctx-solver-simplify fails to simplify formula involving '=='

### ISSUE THREAD

**Issue by TodAmon** [Z3Prover/z3#5530]
For this script:
```
    y = z3.Int('y')
    f = z3.Or(z3.Not(3 <= y) == z3.Or(y >= -2, (-2 <= y) == (3 <= y)), 3==y)
    base_tactic = z3.Tactic("ctx-solver-simplify")
    repeat_tactic = z3.Repeat(base_tactic)
    try_tactic = z3.TryFor(repeat_tactic, 10000)
    result = try_tactic.apply(f)
```
Version 4.8.10.0 simplified to:
```
Or(Not(y >= 3), y == 3)
```
Whereas 4.8.12.0 now simplifies to:
```
Or(Not(y >= 3) == Or(y >= -2, (y >= -2) == (y >= 3)), y == 3)
```

**Comment by NikolajBjorner** [comment]
Some subtle bugs related to DAG traversal were exposed and I had to water down the functionality to something safe but less aggressive. As this tactic never came with a spec of what it should and should not simplify I am inclined to not consider it.
