### ISSUE TITLE
Misused unicode code points from 0x100000 to 0x10FFFF

### ISSUE THREAD

**Issue by Jupiter-19** [Z3Prover/z3#5533]
This is an unimportant issue, and I'm just telling you what I found.

```
# cat unicode.smt2 
(set-logic ALL)
(declare-fun r () String)
(assert
 (= r "\u{30000}"))
(check-sat)
# z3 -smt2 unicode.smt2 
(error "line 4 column 6: unicode characters outside of byte range are not supported")
# cvc4-1.8 --lang=smt2 unicode.smt2 
sat
```

z3 raises error when singleton string from '0x30000' to '0xfffff'. This is reasonable, according to smt2.6. 
However, paradoxical things arise when singleton string from '0x100000' to '0x10ffff'.

```
# cat unicode.smt2 
(set-logic ALL)
(declare-fun r () String)
(assert
 (= r "\u{10ffff}"))
(assert
 (str.in_re r re.allchar))
(check-sat)
# z3 -smt2 unicode.smt2 
unsat
# cvc4-1.8 --lang=smt2 unicode.smt2 
unsat
```
If I replace re.allchar with re.all, it's all sat.

**Comment by NikolajBjorner** [comment]
The spec isn't stringent whether it is to be considered an error, but "throwing less" seems reasonable.

**Comment by NikolajBjorner** [comment]
20a259cfaad77a41c9d2eb3db5c4a68377a52356
