### ISSUE TITLE
A strange behavior of the function int.to.str

### ISSUE THREAD

**Issue by alan23273850** [Z3Prover/z3#5537]
Here is a strange behavior!

1. The model of `(assert (= (int.to.str n) "-156"))` is `n == -156`. But,

2. The model of `(assert (= (int.to.str (- 156)) s))` is `s == ""` instead.

Is there something wrong or I've missed before?

According to my knowledge, negative numbers are not supported so the 1st problem should be UNSAT, and the 2nd problem is still correct.

**Comment by NikolajBjorner** [comment]
You are hitting a bug that was already fixed.
