### ISSUE TITLE
the index of variables in Fixedpoint.getAnswer()  is different from that in Fixedpoint.query() bound by ctx.mkBound

### ISSUE THREAD

**Issue by ikv163** [Z3Prover/z3#5542]
### query:
`
(ReachablePath (:var 26)
               (:var 21)
               (:var 0)
               (:var 1)
               (:var 2)
               (:var 3)
               (:var 4)
               (:var 5)
               (:var 6)
               (:var 7)
               (:var 8)
               (:var 9)
               (:var 10)
               (:var 11)
               (:var 12)
               (:var 13)
               (:var 14)
               (:var 15)
               (:var 16)
               (:var 17)
               (:var 18)
               (:var 19)
               (:var 20))`
### answer
`(or (and (= (:var 0) #x0002) (= (:var 1) #x0001) (= (:var 21) #xc0a80001))
    (and (= (:var 0) #x0001) (= (:var 1) #x0002) (= (:var 12) #xc0a80001)))`

so, I can not find the right order...

**Comment by ikv163** [comment]
the query index is meaningfull, but the answer is not, what can i do to  find the right index
srcNode -> {BitVecExpr@1458} "(:var 26)"
dstNode -> {BitVecExpr@1456} "(:var 21)"

**Comment by ikv163** [comment]
is there a way like the follow

`            /* create & assert quantifier */
            BoolExpr q = ctx.MkForall(
                types, /* types of quantified variables */
                **names, /* names of quantified variables */**
                eq,
                1,
                new Pattern[] { p } /* patterns */);`

**Comment by NikolajBjorner** [comment]
The order of variables in the answer follow the order in the signature of the relation.
The first argument has variable index 0, the second has variable index 1, etc.
It is unrelated to your query order.
