### ISSUE TITLE
How do I substitute Symbols in a expression?

### ISSUE THREAD

**Issue by Naville** [Z3Prover/z3#5543]
Hi:
Google showed me [this very old answer](https://stackoverflow.com/questions/15236450/substituting-function-symbols-in-z3-formulas) by Moura and I wonder if there is any formal API now, since that snippet didn't work for me.

Basically, I have a boolean expression, say ``Xor(Not(X), Y)`` where X and Y are defined as ``z3.Bool("X", z3Ctx)``.

I wonder if I could change X and Y to BitVector of some size I specify

**Comment by NikolajBjorner** [comment]
It would give a type error. You can't replace an expression of type Bool by an expression of type BitVec[n]

**Comment by Naville** [comment]
Thanks, another question would be how do I serialize such expressions and unserialize back from the C++ side of the API?
Google showed examples with adding them to a solver and get sexpr, which asserted out for some reason
