### ISSUE TITLE
User propagator - final callback

### ISSUE THREAD

**Issue by jmarmanis** [Z3Prover/z3#5546]
I'm using the C++ user propagator api to implement a theory.
When propagating a consequence inside the final callback,
it might be the case that no conflict is created, and thus the solver should stop.
However, I've noticed that this doesn't actually happen,
and even if no `pop` call is initiated because of the new consequence,
the solver calls the final callback again.

Even though it is easy for the user theory to detect this scenario
and avoid propagating anything else (in order to avoid an infinite loop),
I was expecting that the solver would do this.
Is this the expected behavior?

**Comment by NikolajBjorner** [comment]
The final check is re-invoked whenever some change happened:
- from self-propagation - it is not self-dampening. You have to check if the propagation is redundant before making it.
- from propagation by other theory

**Comment by jmarmanis** [comment]
I see, thank you.
Since keeping track of propagated consequences can be expensive in my scenario,
I'm propagating everything there is in the first `final` call, and I disregard possible
following `final` calls if there was no `pop` in between.

**Comment by NikolajBjorner** [comment]
We can try to see if it can be dampened.

The callback code is:

```

void user_propagator::propagate_cb(
    unsigned num_fixed, unsigned const* fixed_ids, 
    unsigned num_eqs, unsigned const* eq_lhs, unsigned const* eq_rhs, 
    expr* conseq) {
    m_prop.push_back(prop_info(num_fixed, fixed_ids, num_eqs, eq_lhs, eq_rhs, expr_ref(conseq, m)));
}
```
We can check if conseq is already assigned and then not push it on the stack.

**Comment by NikolajBjorner** [comment]
did this update help?

**Comment by jmarmanis** [comment]
Yes, now it seems to be fine.

**Comment by nunoplopes** [comment]
closing then.
