### ISSUE TITLE
z3py sometime hangs on formulas that it previously solved (strings)

### ISSUE THREAD

**Issue by abialystok** [Z3Prover/z3#5551]
Hello,
It seems like sometimes Solver.check() hangs on a formula that it previously solved in the past. This happened to me only in strings so it could be a specific issue there. 
Here is a minimal example: 
```
from z3 import *

def test_solve():
    s, s1, s2 = Strings('s s1 s2')
    i, t = Ints('i t')
    sl = Solver()
    start = datetime.now()
    sl.add(Not(Implies(And(i < t,
                           Contains(s, s1),
                           Not(SuffixOf(s1, s)),
                           Or(0 < i, PrefixOf(s1, s))),
                       Or(PrefixOf(s2, s), PrefixOf(s1, s)))))
    print(f"{attempt}: {sl.check()}. Solved in {datetime.now() - start}")

for attempt in range(20):
    test_solve()
```

And the output:
```
0: sat. Solved in 0:00:00.504905
1: sat. Solved in 0:00:01.313257
2: sat. Solved in 0:00:00.543546
3: sat. Solved in 0:00:00.137668
4: sat. Solved in 0:00:00.268307
5: sat. Solved in 0:00:00.189427
```

It always (as far as I tried) hangs on the 6th attempt indefinitely. 
I'm using python version 3.8.10, z3py version 4.8.12.0, on Ubuntu (WSL2)

Thank you.

**Comment by Jupiter-19** [comment]
As far as I know, adding Context can solve this problem.
```python 
from z3 import *
from datetime import datetime

def test_solve():
    ctx = z3.Context()
    s, s1, s2 = Strings('s s1 s2', ctx)
    i, t = Ints('i t', ctx)
    sl = Solver(ctx=ctx)
    start = datetime.now()
    sl.add(Not(Implies(And(i < t,
                           Contains(s, s1),
                           Not(SuffixOf(s1, s)),
                           Or(0 < i, PrefixOf(s1, s))),
                       Or(PrefixOf(s2, s), PrefixOf(s1, s)))))
    print(f"{attempt}: {sl.check()}. Solved in {datetime.now() - start}")
```

**Comment by abialystok** [comment]
Yeah it works. 
I'm pretty new to z3, could you elaborate on why this works please? I'd rather make sure I understand what's going on so that I can apply this solution to my program correctly, since my actual use case is more complex than the above exampe. 

Thank you!

**Comment by NikolajBjorner** [comment]
the underlying issue is that the string solver behaves differently depending on how formulas are created, not on what the formulas are. The string solver simply doesn't always converge (quickly). This isn't a correctness bug, but an instance that shows that the solver could be improved.
