### ISSUE TITLE
How to simplify boolean algebra?

### ISSUE THREAD

**Issue by gpf233** [Z3Prover/z3#5552]
For example,  how to get the expected simplification result "x" from the boolean algebra  "x * y + x * !y" ?

**Comment by nunoplopes** [comment]
`(simplify formula)`

You can also apply a sequence of tactics and print the result. see more here: https://rise4fun.com/z3/tutorialcontent/strategies
(the website is down, but you can see a cached copy here: https://cc.bingj.com/cache.aspx?d=4581171279760638&w=4jKkHDwVJCsjRuR65g5OoMVViEnottas)
