### ISSUE TITLE
rise4fun links broken

### ISSUE THREAD

**Issue by jfmc** [Z3Prover/z3#5554]
All rise4fun links are broken :(
This not only affects the online playgrounds, also the documentation and tutorials.

**Comment by NikolajBjorner** [comment]
see discussion thread.
Documentation is uploaded on z3prover/doc repository.

**Comment by jfmc** [comment]
There are many links to rise4fun from wiki and other markdown files. Is there any issue to follow the progress fixing this? Thanks
