### ISSUE TITLE
Regression in Boogie VCs involving a large number of map store operations

### ISSUE THREAD

**Issue by apetcher-amazon** [Z3Prover/z3#5556]
Boogie passes `:weight 0` to map select/store axioms to enable verification of programs with a large number of map operations. With Z3 4.8.12, this seems to have stopped working as expected. I know it worked in 4.8.5, but I haven't tracked down the exact version where this changed. Did something change related to weights, and is there some setting I can use to restore the previous behavior? I know I can increase `smt.qi.eager-threshold`, but I expect that will have unwanted side effects. 

I've attached a couple of files to illustrate the issue. The first is a simple Boogie program that does not verify with Z3 4.8.12. The second is the generated instance. 

[boogie_map.txt](https://github.com/Z3Prover/z3/files/7188179/boogie_map.txt)
[boogie_map_z3.txt](https://github.com/Z3Prover/z3/files/7188180/boogie_map_z3.txt)

**Comment by NikolajBjorner** [comment]
git bisect is a friend when looking for regressions.

**Comment by NikolajBjorner** [comment]
Bisect pointed to 5f90e72d856674730522dfcfc3a7ad0da5b3187a to address https://github.com/Z3Prover/z3/issues/2667.
The bug report indicates the reasons for the change. 

The cost of a quantifier instantiation is increased every time an instantiated term depends on a previous quantifier instantiation. Quantifiers are subject to an eager and a lazy threshold: smt.qi.lazy_threshold=20. If you set the lazy threshold to a higher number, the example will generate enough instances to produce unsat.

For reference, here is a script that bisects

```
import os
from subprocess import Popen, PIPE

os.system("git bisect start")
os.system("git bisect good z3-4.8.6")
os.system("git bisect bad z3-4.8.7")

file = "C:\\z3\\build\\bm.smt2"
while True:
    print("loop")
    # os.system("git bisect")
    os.system("pushd build & cmake -DCMAKE_BUILD_TYPE=Debug -G Ninja ..\\ & popd")
    os.system("pushd C:\\zb\\build & ninja & popd")
    p = Popen(['C:\\zb\\build\\z3.exe', file, '/v:1', '/T:80'], stdout=PIPE, stderr=PIPE)
    stdout, stderr = p.communicate()
    print(str(stdout))
    print(str(stderr))
    if "unknown" in str(stdout):
        os.system("git bisect bad")
    else:
        os.system("git bisect good")

```
