### ISSUE TITLE
build failed on ubuntu (fatal error: variant: No such file or directory compilation terminated.)

### ISSUE THREAD

**Issue by fzuo** [Z3Prover/z3#5557]
I am trying to build z3 on ubuntu 18.04, but got an error. Can anyone kindly let me know how to figure this out? 
~/z3/build$ make
src/shell/dimacs_frontend.cpp
In file included from ../src/tactic/goal.h:30:0,
                 from ../src/sat/tactic/goal2sat.h:31,
                 from ../src/shell/dimacs_frontend.cpp:28:
../src/ast/ast.h:50:19: fatal error: variant: No such file or directory
compilation terminated.
Makefile:4518: recipe for target 'shell/dimacs_frontend.o' failed
make: *** [shell/dimacs_frontend.o] Error 1

**Comment by andrewvaughanj** [comment]
What compiler? It is possible that 18.04’s default GCC doesn’t have `<variant>`

**Comment by fzuo** [comment]
> What compiler? It is possible that 18.04’s default GCC doesn’t have `<variant>`

$ gcc --version
gcc (Ubuntu 5.5.0-12ubuntu1) 5.5.0 20171010
Copyright (C) 2015 Free Software Foundation, Inc.

I think you are right. After using CXX=clang++ CC=clang python scripts/mk_make.py, build is successful. 
Thanks a lot.
