### ISSUE TITLE
z3 hangs on simple bitvector constraints encoding overflow condition

### ISSUE THREAD

**Issue by yiyuaner** [Z3Prover/z3#5558]
I am running z3 4.8.12, the following constraints cause z3 to hang:
```
(declare-fun udiv () (_ BitVec 32))
(declare-fun b () (_ BitVec 32))
(declare-fun x () (_ BitVec 32))
(assert (= udiv (bvudiv (_ bv4294967295 32) b)))
(assert (bvule x udiv))
(assert
(let ((res (bvmul ((_ zero_extend 32) b) ((_ zero_extend 32) x))))
(bvugt res (_ bv4294967295 64))))
(check-sat)
```
Basically, the above constraints encode a test for integer overflow:
```
// b and x are 32bits unsigned integers
if (x <= UINT32_MAX / b) { // check for integer overflow
  // b*x can not overflow, i.e., zero_extend(b,32) * zero_extend(x,32) can not exceed UINT32_MAX
  res = b *x; 
}
```
I am wondering why z3 can not figure out such a seemly easy constraint. Can you give some suggestions, e.g., good tactics to use in this case? Thanks! 

**update**
It takes z3 9m28s to figure out the above constraint is UNSAT. Can the performance be improved?

**Comment by NikolajBjorner** [comment]
It is very likely that the bit-blaster for quotient-remainder can be improved along the lines of the investigations into multiplier circuits (@jameysharp has been digging into the multiplier blaster). 
If you log -tr:tactic -v:10 you see the bit-blaster create sub-expressions with the shape:

```
 (ite a!1064 (not (= a!1025 (= k!39 a!1039))) a!1025)
```

It is equivalent to 

```
    (= a!105 (or (= k!39 a!1039) (not a!1064))
```

which has a smaller clausification.
In total of 20K clauses are generated, rather exorbitant.

The more scalable approach is some word level reasoning, but this is not going to be available within the immediate future.
