### ISSUE TITLE
Highly nondeterministic outcome when proving conjunction

### ISSUE THREAD

**Issue by rindPHI** [Z3Prover/z3#5559]
Dear all,

I am currently implementing a small symbolic execution engine for a Python subset, with z3 as the solver backend. Thus, I'm frequently trying to prove conjunctions in z3. When doing so, I encountered some strange behavior: It seems that the *order* of conjuncts influences whether or not z3 can prove a conjunction; furthermore, it seems to matter where a variable is declared, and there are some hidden nondeterministic factors which lead to different results for the same program.

You can witness this behavior when repeatedly executing the following Python program (sorry, couldn't reduce it more...):

```python
import itertools
import z3


def z3_sequence(name: str):
    ctx = z3.main_ctx()
    elem_sort = z3.IntSort(ctx)
    return z3.SeqRef(
        z3.Z3_mk_const(
            ctx.ref(),
            z3.to_symbol(name, ctx),
            z3.SeqSortRef(z3.Z3_mk_seq_sort(elem_sort.ctx_ref(), elem_sort.ast)).ast), ctx)


fromv, to = z3.Ints(["from", "to"])
# i, fromv, to = z3.Ints(["i", "from", "to"])
t = z3_sequence("t")
subseq = z3_sequence("subseq")

# Seems to be crucial to declare i here and not together with fromv / to, otherwise fails to prove unsat result...
i = z3.Int("i")

formulas = [
    i <= to,
    z3.Not(to <= i),
    0 <= fromv,
    fromv <= to,
    to <= z3.Length(t),
    i >= fromv,

    subseq == z3.SubSeq(t, fromv, i + -1 * fromv),
    z3.Not(z3.And(
        i >= -1 + fromv,
        i <= -1 + to,
        z3.SubSeq(t, fromv, 1 + i + -1 * fromv) ==
        z3.Concat(subseq, z3.Unit(t[i])))),
]

i = 0
for formulas in itertools.permutations(formulas):
    i += 1
    solver = z3.Solver()
    solver.set("timeout", 500)

    for conjunct in formulas:
        solver.add(conjunct)

    result = solver.check()

    if result != z3.unknown:
        print(f"{result} ({i})")
        print(formulas)
        break
    else:
        print(f"unknown ({i})...")
```

In my implementation, I resorted to checking all permutations for a conjunction as above, which eventually gives me the expected results. It would be great if there was another way, though, and also I think what I'm describing should be undesired behavior.

Best,
Dominic

**Comment by NikolajBjorner** [comment]
The sequence solver is rather unstable, especially when you mix integer constraints and sequence constraints. 
While improving search for the mixed sequence / integer scenario is desired it has been pending for a long while.
You can alternatively try z3 with different random seeds (set_param("smt.random_seed", N) and with shorter timeouts or in parallel.
