### ISSUE TITLE
z3 python solver copying

### ISSUE THREAD

**Issue by Owlz** [Z3Prover/z3#556]
Another question regarding my use of z3 in the python script symbolic execution engine. In longer examples of the engine, the script spends much of it's time re-creating the z3 solver when it state splits. My current implementation simply instantiates a new solver, and then copies over all the solver.assertions(). The obvious slowdown here is that I'm asking z3 the solve something it has already solved. This becomes a more serious problem (exponential in some cases) when it gets deeper into execution.

Is there any way to copy the solver without having this overhead?

**Comment by wintersteiger** [comment]
No there isn't, but you can use the incremental solving facilities for this purpose, i.e., solve with assumptions or push/pop parts of your problem.

**Comment by NikolajBjorner** [comment]
There is also the translate method (Z3_solver_translate or Solver.translate) that lets you clone a solver. This may work for your scenario.

**Comment by Owlz** [comment]
Nikolaj,

I think what you're talking about is what I'm trying to do. However, when I attempt that I get an error that I don't understand "translation of contexts is only supported at base level".

**Comment by NikolajBjorner** [comment]
This would mean that you did a push. You have to pop back everything.

**Comment by Kobzol** [comment]
Is there any way to translate/clone a solver in the C++ API? I only found the Z3_solver_translate method, but that returns the C object and I don't know how to transform it into the C++ z3::solver instance.
