### ISSUE TITLE
Confirm a bug: when `check-sat-assuming` returns `unkown` for the first time, it will return `unkown` forever.

### ISSUE THREAD

**Issue by chansey97** [Z3Prover/z3#5563]
See the following program:

```
$ z3 -in smt.arith.solver=2
(declare-fun x () Int)
(declare-fun y () Int)
(declare-fun z () Int)
(declare-fun xSquared () Int)
(declare-fun ySquared () Int)
(declare-fun zSquared () Int)
(declare-fun xSquaredPlusYSquared () Int)

(declare-const _a1 Bool)
(assert (=> _a1 (and (= xSquared (* x x))
                     (= ySquared (* y y))
                     (= zSquared (* z z))
                     (= xSquaredPlusYSquared (+ xSquared ySquared))
                     (> x 0)
                     (> y 0)
                     (> z 0)
                     (= xSquaredPlusYSquared zSquared))))

(declare-const _a2 Bool)
(assert (=> _a2 (= 1 1)))

(check-sat-assuming (_a2))
sat

(check-sat-assuming (_a1))
unknown

(check-sat-assuming (_a2))
unknown
```

Why does the 2nd `(check-sat-assuming (_a2))` return `unknown`?

The smt-lib-reference-v2.6-r2021-05-12 says that (p.64)

> Regardless of how it is implemented internally, a check-sat-assuming command should preserve the current context in the sense that at the end of the command’s execution the context should be the same as it was right before the execution.

So I think the 2nd `(check-sat-assuming (_a2))` should return `sat`, because the 1st `(check-sat-assuming (_a2))` returns `sat`. 

For the "check-sat-assuming with not" idiom, we may use `(check-sat-assuming (_a2 (not _a1)))` instead of `(check-sat-assuming (_a2))`. Then no problem. For example, the following program return `sat` normally:

```
$ z3 -in smt.arith.solver=2
(declare-fun x () Int)
(declare-fun y () Int)
(declare-fun z () Int)
(declare-fun xSquared () Int)
(declare-fun ySquared () Int)
(declare-fun zSquared () Int)
(declare-fun xSquaredPlusYSquared () Int)

(declare-const _a1 Bool)
(assert (=> _a1 (and (= xSquared (* x x))
                     (= ySquared (* y y))
                     (= zSquared (* z z))
                     (= xSquaredPlusYSquared (+ xSquared ySquared))
                     (> x 0)
                     (> y 0)
                     (> z 0)
                     (= xSquaredPlusYSquared zSquared))))

(declare-const _a2 Bool)
(assert (=> _a2 (= 1 1)))

(check-sat-assuming (_a2 (not _a1)))
sat

(check-sat-assuming (_a1 (not _a2)))
unknown

(check-sat-assuming (_a2 (not _a1)))
sat
```

Should we treat this issue as a bug? Or force this idiom?

Thanks.

PS. I am not sure if `smt.arith.solver=6` has the same problem because `smt.arith.solver=6` won't return `unknown` in the example above.

My test environment:

[z3-4.8.12-x64-win](https://github.com/Z3Prover/z3/releases/download/z3-4.8.12/z3-4.8.12-x64-win.zip).

**Comment by NikolajBjorner** [comment]
your formula contains non-linear integer arithmetic expressions (multiplication x * x, etc).
The solver is incomplete and does a best effort. For this scenario it is lucky to find a solution during the first try with _a2. The same solution is not found during the third try and it gives up.
