### ISSUE TITLE
Get model results in error

### ISSUE THREAD

**Issue by andrewjlawrence** [Z3Prover/z3#5564]
I am currently trying to solve some graph theory problems with Z3. The code I have produced so far looks correct as far as I can tell but is producing unexpected results e.g. paths through the graph are shorter than they should be. 

When I run Z3 it produces the following error on the get model command:
(error "line 431 column 10: Sort mismatch at argument #1 for function (declare-fun fold-rec-3 ((List Portion) Node) Edge) supplied sort is Node")

Does this indicate there is some underlying problem or bug in my code?

**Comment by wintersteiger** [comment]
This means that either you or Z3 are passing invalid arguments to `fold-rec-3`. Please submit a complete reproducible example, without that we can only speculate.
