### ISSUE TITLE
z3 modulo on Real type?

### ISSUE THREAD

**Issue by Owlz** [Z3Prover/z3#557]
It looks like there's a restriction on modulo to only being Int type. In my symbolic engine, i run into situations where a Real type would need to be modulo. Depending on how complicated the script is, the ToInt conversion to make modulo work will actually cause the program to be "unknown" state in a step or two, where if it were Real it should be decidable.

Is there any way to perform the modulo action on a Real type?

**Comment by NikolajBjorner** [comment]
This is a reasonable question. I don't recall it being posed before.
Suppose you do real modulus with a positive constant, then one would expect the quotient-remainder property:

      0 <= (X mod k) < k, 
      k*(X quot k) + (X mod k) = X,
      is_int(X quot k)

One thing you can do is to create new uninterpreted functions "mod" and "quot" that work on reals and instantiate these axioms every time you use "mod". This is what the linear arithmetic solver does
under the hood anyway for the integer versions of these functions.
It is not too likely we would add built-in support for this function given that it can be encoded and apparently rare to see a demand for.

**Comment by Owlz** [comment]
So I've attempted the following:

mod = z3.Function('mod', z3.RealSort(),z3.RealSort(), z3.RealSort())
quot = z3.Function('quot', z3.RealSort(),z3.RealSort(), z3.RealSort())
s = z3.Solver()
```python
X,k = z3.Reals('X k')
s.add(
 0 <= mod(X,k) < k,    
 k*quot(X,k) + mod(X,k) == X,
 z3.is_int(quot(X,k))
)
```

The problem being the last one there always turns to false since the output of the function is declared as a Real. If I use ToInt or change the mod/quot to return Int, I end up with that conversion function that was biting me previously.

**Comment by NikolajBjorner** [comment]
at least three things are wrong with this code:
1. Comparisons are binary, so you cant write ... <= ... < ..., you have to write .. <= ..., ... < ....
2. these axioms should be instantiated based on occurrences of X and k, where k is a positive numeral.
    If the value of k is not fixed (as in the example code above), then the proper axioms would be different.
3. The API function Z3_is_int is not exposed over Python directly. As you notice, z3.is_int just returns False, so this is useless. You would have to make sure to use Z3_is_int, which will require you to write a little wrapping code that is similar to how other API functions are wrapped in python.

**Comment by Owlz** [comment]
Thanks for the info. I've gotten the following to partially work:

```python
mod = z3.Function('mod', z3.RealSort(),z3.RealSort(), z3.RealSort())
quot = z3.Function('quot', z3.RealSort(),z3.RealSort(), z3.RealSort())
s = z3.Solver()

X,k,m = z3.Reals('X k m')
s.add(
 0 <= mod(X,k),
 mod(X,k) < k, 
 k*quot(X,k) + mod(X,k) == X,
 z3.BoolRef(z3.Z3_mk_is_int(quot(X,k).ctx_ref(),quot(X,k).as_ast())),
 m == mod(X,k)
)
```

It doesn't have any of those conversion functions which is great. As you mentioned, I'm actually trying to do this generally. Meaning I may not know what X or k are during time of execution, but would still like to create the modular relationship between them. As stated in the above code, it seems to give a correct return when I leave it wide open, fill in values of k, or both k and X. It goes undecidable if I only specify the value of X.

Guessing this is why you were mentioning that the axioms are different.

**Comment by NikolajBjorner** [comment]
I guess I should have been more explicit. The axioms that just say mod(X,k) < k are leads to inconsistencies if k cannot be positive. So a reasonable axiomatization would have to specify what you mean by mod for negative numbers. The integer mod/rem functions have semantics for negative numbers (I forgot which, but one can look it up on http://smtlib.org). Similarly, the axioms you specify
would have to deal with negative numerals if they happen to be possible.

Also, you can constrain the quotient function to be integer type just by specifying the range type, so there is no need for the extra IsInt function.

Below is sample code that axiomatizes mod/quot for instances X, k that you encounter during symbolic execution. The specification for negative k is a matter of what semantics your operators really have. I chose one arbitrary.


         from z3 import *

         mod = z3.Function('mod', z3.RealSort(),z3.RealSort(), z3.RealSort())
         quot = z3.Function('quot', z3.RealSort(),z3.RealSort(), z3.IntSort())
         s = z3.Solver()


         def mk_mod_axioms(X,k):
               s.add(0 <= mod(X,k),
                   Implies(k > 0, mod(X,k) < k),
                   Implies(k < 0, mod(X,k) < -k),
                   k*quot(X,k) + mod(X,k) == X)
        
         x, y = z3.Reals('x y')

         mk_mod_axioms(x, 3)
         mk_mod_axioms(y, 5)

         print s

**Comment by NikolajBjorner** [comment]
I take we are good

**Comment by Groostav** [comment]
For those like me scratching their heads wondering why similar java wont work, make sure you've got `k` declared as an int, the quickest fix being:

```py
     def mk_mod_axioms(X,k):
           s.add(Implies(k != 0, 0 <= mod(X,k)),
               Implies(k > 0, mod(X,k) < k),
               Implies(k < 0, mod(X,k) < -k),
               Implies(k != 0, k*quot(X,k) + mod(X,k) == X)),
               mkIsInteger(k)
```

**Comment by JohnHuynh** [comment]
Hello there, I'm trying to implement the modulo operation for the type RealExpr in Java. This is the code:


        public static RealExpr mkRealMod(RealExpr x, RealExpr k, Context ctx) {
            Solver solver = ctx.mkSolver();
            RealExpr remainder = ctx.mkRealConst("remainder");

            Sort[] domain = { ctx.getRealSort(), ctx.getRealSort() };
            FuncDecl mod = ctx.mkFuncDecl("mod", domain, ctx.getRealSort());
            FuncDecl quot = ctx.mkFuncDecl("quot", domain, ctx.getRealSort());

            RealExpr zero = ctx.mkReal(0);
            RealExpr minusK = (RealExpr) ctx.mkSub(zero, k);

            RealExpr[] xk = {x,k};
            RealExpr modxk = (RealExpr) ctx.mkApp(mod, xk);
            RealExpr quotxk = (RealExpr) ctx.mkApp(quot, xk);
        
            RealExpr calc = (RealExpr) ctx.mkAdd(ctx.mkMul(k, quotxk), modxk);

            // Implies(k != 0, 0 <= mod(X,k)),
            solver.add(ctx.mkImplies(ctx.mkNot(ctx.mkEq(k, zero)), ctx.mkLe(zero, modxk)));
            // Implies(k > 0, mod(X,k) < k),
            solver.add(ctx.mkImplies(ctx.mkGt(k,zero), ctx.mkLt(modxk, k)));
            // Implies(k < 0, mod(X,k) < -k),
            solver.add(ctx.mkImplies(ctx.mkLt(k,zero), ctx.mkLt(modxk, minusK)));
            // Implies(k != 0, k*quot(X,k) + mod(X,k) == X))
            solver.add(ctx.mkImplies(ctx.mkNot(ctx.mkEq(k, zero)), ctx.mkEq(calc, x)));
      
            return remainder;
    }


In the main method I've tried this:

        // Initialize Expressions
        RealExpr x = (RealExpr) ctx.mkAdd(ctx.mkReal(6), ctx.mkReal(1, 10));
        RealExpr k = ctx.mkReal(6);

        // Get the result
        RealExpr result = mkRealMod(x, k, ctx);
        solver.add(ctx.mkAnd(ctx.mkGt(result, ctx.mkReal(0)), ctx.mkLt(result, k)));


The calculation: `6.1 mod 6` is equal to `0.1`. But when I print the value of 'result' I get the value `1`. What did I miss here?

**Comment by NikolajBjorner** [comment]
the _remainer_ is not being constrained in your function mkRealMod.

**Comment by JohnHuynh** [comment]
Ok, I contrained the remainder correctly and the desired result came out. Nevertheless, it only works for pure constants. As soon as I try to calculate the remainder using variables it won't work and the solver status is "UNKNOWN". It seems that this problem is too hard for the solver.
