### ISSUE TITLE
z3 ctx.mkBVUGE (), reports an error of Guard expression is not handled(bvule #x0014 (:var 2))

### ISSUE THREAD

**Issue by ikv163** [Z3Prover/z3#5570]
(bvuge L #x0014)
(bvuge C #x0014))

com.microsoft.z3.Z3Exception: Guard expression is not handled(bvule #x0014 (:var 2))

**Comment by NikolajBjorner** [comment]
you are trying to pass an expression to tables for the Difference of Cubes (doc) representation that isn't in scope of what is supported. Only selected bit-wise expressions are supported.
