### ISSUE TITLE
Floating point condition not finding possible solution

### ISSUE THREAD

**Issue by fritzfs** [Z3Prover/z3#5572]
I am trying to convert the following calculation conditions, but my z3py is unable to find any option.

    def sum_mul_pi(values):
        val = 0
        for i in range(0, len(values)):
            val1 = float(i) * float(3.141592)
            val2 = float(ord(values[i])) * val1
            val += int(val2)
        return val

This is my z3 solution which prints nothing.

    from z3 import *
    set_param("parallel.enable", True)

    def sum_mul_pi(values):
        val = BitVecVal(0, 64)
        for i in range(0, len(values)):
            val1 = FPVal(float(i) * float(3.141592), Float(64))
            val2 = fpMul(RTZ(), fpBVToFP(values[i], Float64()), val1)
            val += fptoUBV(RTZ(), val2, BitVecSort(64))
        return val

    key = [BitVec("i%d" % i, 64) for i in range(19)]

    s = Solver()

    s.add(sum_mul_pi(key) == 39944)

    while s.check() == sat:
        m = s.model()
        ss = "".join([chr(m[x].as_long()) for x in key])
        print(ss)
        s.add(Or([ f() != m[f] for f in m.decls() if f.arity() == 0]))

**Comment by wintersteiger** [comment]
What does `s.check()` return?

**Comment by fritzfs** [comment]
Hey @wintersteiger! s.check() returns "unsat".

**Comment by wintersteiger** [comment]
Right, that means your encoding of `sum_mul_pi` does not have the semantics you're after. I don't know exactly what Python's `ord` does, but it seems to be some kind of unicode conversion, which isn't reflected in the BV/FP encoding.

**Comment by fritzfs** [comment]
The python ord() method returns an integer for a specified character - for example, 48 for the character "0". 

    def sum_mul_pi(values):
        val = 0
        for i in range(0, len(values)):
            val1 = float(i) * float(3.141592)
            val2 = float(ord(values[i])) * val1
            val += int(val2)
        return val

For example, variable "values" is string "ABCD".
- loop through each byte in a string (A, B, C, D)
- variable val1 = loop index (0, 1, 2, 3) * 3.141592 
- variable val2 = integer value (65 (=A), 66 (=B), 67 (=C), 68 (=D)) * val1 
- variable val = summary of all val2 values

**Comment by wintersteiger** [comment]
Yes, your encoding of `sum_mul_pi` does not perform that conversion. What's the type of `values`; is that a list of Z3 expressions?

**Comment by fritzfs** [comment]
I believe you're asking for just Python code (without z3). "values" is just string, sequence of characters, for example:
`values = "BFFDPGAEG0GWEA____D"`

Also, just to note again, in Python Z3 code "values" is BitVec array, defined as:
`values = [BitVec("i%d" % i, 64) for i in range(19)]`

**Comment by wintersteiger** [comment]
I assume this issue has been addressed in some way, so I'm closing it. If there are still related problems, please open a new issue. Just to summarize: there is at least one problem, which is the missing encoding of `ord`.
