### ISSUE TITLE
How to describe semantics of pointer type based on Z3

### ISSUE THREAD

**Issue by nuppt** [Z3Prover/z3#558]
Hi. I've been confused of some questions in Z3. 
Z3 provide a lot of types, such as Int, Bool, Array, even user-defined type by datatype interface.
As we all know, pointer type is a basic type in C programming language, then sometimes I find it too hard to express properties of pointer type, because I can't get the corresponding type in Z3. Is there a better way to do that?
And there is another question close to semantics of pointer type in Z3. Let me state briefly.
Usually we use structure type to construct some inductive type, such as singly linked list or binary tree, and I find in Z3 there is datatype interface to construct similar thing. But in C, we can state the expression p = q, that type of both is pointer of binary tree, and the semantics of this expression is that pointer p and q point to the same node on one same tree. But I'm not sure this meaning is equal in Z3 if I write the expression in Z3. So how should I see the expression of comparison operations (=, >, <, !=) on objects defined by datatype?

**Comment by NikolajBjorner** [comment]
You are basically asking about modeling program constructs in logic. Many people have spent many years fine-tuning various encodings of heaps that build on top of using arrays. For answers to such questions I would suggest that you take a deep look at some of the program verification tools that map their logics into SMT. Say, you could take a look at 
Boogie https://github.com/boogie-org/boogie, and Dafny https://github.com/boogie-org/boogie-friends
