### ISSUE TITLE
Linking to threads not required with non-thread-safe build

### ISSUE THREAD

**Issue by MichaelRawson** [Z3Prover/z3#5584]
Hi Z3 developers! We sometimes link Z3 into [Vampire](https://vprover.github.io), thanks for the great software.

We've been getting an issue recently where our CMake-based build fails due to a lack of suitable thread-support library, which is required because of Z3's CMake build [including threads unconditionally](https://github.com/Z3Prover/z3/blob/a3010c8875fb86db23891d517a0a8c542eb20473/CMakeLists.txt#L311) - but we don't need threading at all in Vampire and switch it off in your CMake build with `Z3_SINGLE_THREADED`.

I realise systems that don't support threads are a bit strange (we think there is some misconfiguration somewhere), but we can solve our issue and reduce our load time if Z3 doesn't require linking a thread support library when we don't need them. What do you think? I'm happy to supply a fix: I expect it will be something like

```cmake
if(NOT Z3_SINGLE_THREADED)
  set(THREADS_PREFER_PTHREAD_FLAG TRUE)
  find_package(Threads)
  list(APPEND Z3_DEPENDENT_LIBS Threads::Threads)
endif()
```

**Comment by NikolajBjorner** [comment]
scoped_timer uses <thread> it is not guarded under Z3_SINGLE_THREADED, which is mainly used for saving overhead during access to shared state (for efficiency).

**Comment by MichaelRawson** [comment]
OK, interesting about `scoped_timer`. We got it to link without threads somehow, looks like I need to investigate more on our end. Thanks!
