### ISSUE TITLE
customize expression simplification

### ISSUE THREAD

**Issue by Icegrave0391** [Z3Prover/z3#5592]
I'd like to customize the expression simplification method like:

I have an expression <stack_base - 0x38 - (0x17 + (concat_expr1))>, and I'd like to simplify it to the format: <stack_base - (0x4f + concat_expr1)>.

However, after z3's simplification, the expression turns to <0xffffffc8 + stack_base + 0xffffffff*(0x17 + concat_expr1)>.

If there is any way to simplify the expression as I wanted?

**Comment by Icegrave0391** [comment]
In other words, all I want is to remain `__sub__` operation in my simplifcation's result.

**Comment by NikolajBjorner** [comment]
There is no direct support for customizing the simplifier. The simplifier is used internally as pre-processing. It is then exposed for as an added service, but is not considered main functionality. A proper design of a customizable simplifier would involve a good way for you to supply rewrite rules (either as code or using rewrite rules and leverage matching). Maybe possible, but not in scope of z3 at this point.

What you can do with the API is to walk expressions returned by the simplifier and _fix_ them up on your own.
There are several examples on how to walk expressions (with shared sub-expressions), such as 
https://github.com/Z3Prover/z3/blob/7b341313d553e503acd1183106f27c04c0b34dd1/examples/python/visitor.py#L2
