### ISSUE TITLE
Z3 online interactive solver down?

### ISSUE THREAD

**Issue by zhoulaifu** [Z3Prover/z3#5597]
Hello, 

I am teaching satisfiability solving to Master's students today. We used to play a bit with Z3's interactive online solver: https://rise4fun.com/z3/tutorial. But this website seems to no more work, as of today. Is it due to maintenance, or is it shut down permanently?

Thanks,
- Zhoulai

**Comment by andrewvaughanj** [comment]
See: https://github.com/Z3Prover/z3/discussions/5473
