### ISSUE TITLE
several FP related issues

### ISSUE THREAD

**Issue by zhendongsu** [Z3Prover/z3#5598]
Assertion violation / segfault (regression from 4.8.12):
```
[679] % z3release small.smt2 
Segmentation fault
[680] % z3debug small.smt2 
ASSERTION VIOLATION
File: ../src/ast/ast.h
Line: 488
m_ref_count > 0
(C)ontinue, (A)bort, (S)top, (T)hrow exception, Invoke (G)DB
a
[681] % cat small.smt2 
(set-option :trace true)
(assert (forall ((a Float16)) (fp.eq a a)))
(check-sat)
[682] % 
```

**Comment by zhendongsu** [comment]
Solver hang:
```
[687] % cvc5 -q --fp-exp small.smt2 
unsat
[688] % timeout -s 9 10 z3release small.smt2 
Killed
[689] % cat small.smt2 
(assert (forall ((a Float16)) (exists ((b Float16)) (fp.eq a b))))
(check-sat)
[690] % 
```

**Comment by zhendongsu** [comment]
Assertion violation / segfault:
```
[706] % z3release small.smt2 
Segmentation fault
[707] % z3debug small.smt2 
ASSERTION VIOLATION
File: ../src/smt/theory_bv.cpp
Line: 553
!ctx.e_internalized(n)
(C)ontinue, (A)bort, (S)top, (T)hrow exception, Invoke (G)DB
a
[708] % cat small.smt2 
(set-option :trace true)
(assert (forall ((a Float16)) (exists ((b Float16)) (fp.eq a b))))
(check-sat)
[709] %
```

**Comment by zhendongsu** [comment]
> Who uses the trace option with floating points? The most recent updates to tracing were issued from ETHZ with code changes that left some cleanup to be desired. I will close this as I am not going to have bandwidth to deal with these from my end.

Okay, Nikolaj, that's alright, but the 2nd test is for a solver hang (w/o the trace option).

**Comment by NikolajBjorner** [comment]
second test just demonstrates that there isn't support for quantifiers + FP. There is at least one paper by Niemetz et al on solving this. It isn't implemented in Z3. I don't see the rationale in that the absence of functionality should be a filed as an issue.
