### ISSUE TITLE
Nondeterminism - random seed

### ISSUE THREAD

**Issue by imarmanis** [Z3Prover/z3#5606]
I'm using Z3 as part of an application and I would like to make it deterministic
in order to profile it.
I have tried setting the “:random-seed”, “:smt.random-seed”, and “:sat.random-seed” parameters to a fixed value,
but I'm still observing some nondeterminism.
I'm using the C++ API, and the nondeterminism is observed via the user propagator.

**Comment by NikolajBjorner** [comment]
Z3 should behave the same between runs unless it uses multiple threads.
Quite a bit of effort has gone into ensuring this. There could be bugs.
The user propagator is fairly new and as of yet not well documented (however this is going to change soon thanks to Clemens.
I tend to debug this using debug mode code and debug tracing. THe first place where debug traces differ points to where determinism is broken.

**Comment by NikolajBjorner** [comment]
It is definitely not intuitive that your use of unordered_map would be a root cause, but then I guess the contract on unordered_map is not saying anything about life-time of elements in the table or duplicates.
