### ISSUE TITLE
Segfault in smt::theory_arith<smt::mi_ext>::propagate_linear_monomial(int)

### ISSUE THREAD

**Issue by cheshire** [Z3Prover/z3#562]
Hi All,

I get a segfault within a linear arithmetic module.
The crash log is available at http://metaworld.me/segfault.log

**Comment by NikolajBjorner** [comment]
what is the git hash of the version of Z3 you are using? It seems not to replay with the current master branch.

**Comment by wintersteiger** [comment]
Bumping this. Does this problem still exist?

**Comment by cheshire** [comment]
Yes, my apologies for forgetting this.

http://metaworld.me/newsegfault.log

**Comment by NikolajBjorner** [comment]
could it be fixed now? I can't repro it on either windows nor Mac.

**Comment by cheshire** [comment]
Thanks, probably was fixed!
