### ISSUE TITLE
Solver (unexpectedly) returns unknown status 

### ISSUE THREAD

**Issue by cheshire** [Z3Prover/z3#563]
Hi All,

I have a number (~5 or so) benchmarks where the following happens:

1) On checking satisfiability with enabled unsat core tracking, solver returns UNKNOWN status with an explanation "incomplete (theory arithmetics)".
What exactly does this mean? The benchmarks do not use any theory constructs which are unique to them.

2) Checking satisfiability without unsat core seems to work immediately.
If possible I would also really appreciate any advice on how expensive is unsat core extraction over tracked assumptions compared to a simple satisfiability query.

An example benchmark with such a behavior can be found at http://metaworld.me/solver_returns_unknown.smt2

It does not seem to contain any untractable constructs.

**Comment by NikolajBjorner** [comment]
The formula has non-linear arithmetic. Some useful preprocessing may be disabled when you use tracking literals for cores and this could cause the arithmetic solver to fail solving he goal.

**Comment by cheshire** [comment]
@NikolajBjorner Thanks, did not realize that!
