### ISSUE TITLE
Context-wise or thread-wise random seed?

### ISSUE THREAD

**Issue by riscvare** [Z3Prover/z3#5636]
I am creating multiple Z3 contexts on multiple threads using C/C++ API. I see that I can set the global parameters "'smt.random_seed" and "sat.random_seed".

Is it possible to set these parameters at context level or at thread-level?

Is there some other way to enable deterministic behavior when creating and solving multiple contexts on parallel threads?

**Comment by NikolajBjorner** [comment]
You can set these parameters on the "solver" object. They will be local to each solver.
