### ISSUE TITLE
how to use bitVec as a list index

### ISSUE THREAD

**Issue by GUANCAIBAN** [Z3Prover/z3#5657]
here are my code
`
f2 = BitVec('f2', 32)
f3 = BitVec('f3', 32)
f4 = BitVec('f4', 32)
v11 = dword_405420[(v9&0xff00)] ^ dword_405820[(v8&0xff0000)] ^ dword_405C20[(0xff000000&v7)] ^ dword_405020[(0xff&i)]
`
it make a error that is:
TypeError: list indices must be integers or slices, not BitVecRef
 
I need to get the index by Z3,I used to use BV2Int ,but it can‘t work as well

**Comment by GUANCAIBAN** [comment]
when I used BV2Int,it made a error:

v11 = dword_405420[BV2Int(v9&0xff00)] ^ dword_405820[BV2Int(v8&0xff0000)] ^ dword_405C20[BV2Int(0xff000000&v7)] ^ dword_405020[BV2Int(0xff&i)]
TypeError: list indices must be integers or slices, not ArithRef

**Comment by andrewvaughanj** [comment]
What is `dword_405820`? A Python list? You cannot index into Python types with Z3 data-types.

Either `dword_405820` should be an SMT array, or what you're trying to do can't work.

**Comment by GUANCAIBAN** [comment]
Oh....
I have a loop like this:
`v11 = dword_405420[BYTE1(v9)] ^ dword_405820[BYTE2(v8)] ^ dword_405C20[HIBYTE(v7)] ^ dword_405020[BYTE0(i)];
    v13 = dword_405420[BYTE1(i)] ^ dword_405820[BYTE2(v9)] ^ dword_405C20[HIBYTE(v8)] ^ dword_405020[BYTE0(v7)];
    v15 = dword_405420[BYTE1(v7)] ^ dword_405820[BYTE2(i)] ^ dword_405C20[HIBYTE(v9)] ^ dword_405020[BYTE0(v8)];
    v9 = dword_405420[BYTE1(v8)] ^ dword_405820[BYTE2(v7)] ^ dword_405C20[HIBYTE(i)] ^ dword_405020[(BYTE0(v9)]
 `
 i want to use z3 to solve it... or how to convert my python list to smt array

**Comment by andrewvaughanj** [comment]
You really need to share a [MWE](https://en.wikipedia.org/wiki/Minimal_working_example) if you want help. We have no idea what  type you're using for `dword_405820` or what you think it might represent.

Are you trying to access individual bits in another bit-vector?
