### ISSUE TITLE
Wasm Artifact Linking

### ISSUE THREAD

**Issue by philzook58** [Z3Prover/z3#5664]
I attempted to use the Wasm build artifact from here <https://github.com/Z3Prover/z3/actions/workflows/wasm.yml> on a simple toy example

```C
#include <z3.h>

int main(){
    Z3_config config = Z3_mk_config();
    Z3_context context = Z3_mk_context(config);
    Z3_string output = Z3_eval_smtlib2_string(context, "(echo \"Hello World!\")");
    puts(output);
}
```

I got an error building this against the github action artifact.

```
philip@philip-XPS-13-7390-2-in-1:~/Documents/wasm/z3try$ emcc main.cpp libz3.a -I z3/src/api/ -s ALLOW_MEMORY_GROWTH=1
error: undefined symbol: _ZNSt3__212basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEEC1ERKS5_ (referenced by top-level compiled C/C++ code)
warning: Link with `-s LLD_REPORT_UNDEFINED` to get more information on undefined symbols
warning: To disable errors for undefined symbols use `-s ERROR_ON_UNDEFINED_SYMBOLS=0`
warning: __ZNSt3__212basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEEC1ERKS5_ may need to be added to EXPORTED_FUNCTIONS if it arrives from a system library
Error: Aborting compilation due to previous errors
emcc: error: '/home/philip/Downloads/emsdk/node/14.15.5_64bit/bin/node /home/philip/Downloads/emsdk/upstream/emscripten/src/compiler.js /tmp/tmpra1vqlan.txt' failed (returned 1)
```

Locally building the Wasm file with the same commands as here https://github.com/Z3Prover/z3/blob/master/.github/workflows/wasm.yml seems to work.

```
philip@philip-XPS-13-7390-2-in-1:~/Documents/wasm/z3try$ emcc main.cpp z3/build/libz3.a -I z3/src/api/ -s ALLOW_MEMORY_GROWTH=1
philip@philip-XPS-13-7390-2-in-1:~/Documents/wasm/z3try$ node ./a.out.js 
Hello World!
```

Maybe I've made a foolish mistake somewhere or perhaps one needs to have an identical tool chain as the github action build system? I downloaded the latest version of the emsdk. The two `libz3.a` do differ in size by a few megabytes.

```
philip@philip-XPS-13-7390-2-in-1:~/Documents/wasm/z3try$ emcc -v
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 2.0.34 (0d24418f0eac4828f096ee070dae8472d427edaa)
clang version 14.0.0 (https://github.com/llvm/llvm-project 3d39612b3dd3f6b67ee63da305d30606abbe7287)
Target: wasm32-unknown-emscripten
Thread model: posix
InstalledDir: /home/philip/Downloads/emsdk/upstream/bin
```

**Comment by wintersteiger** [comment]
I think the symbol it complains about is from the C++ standard library and it's likely that your version thereof uses different naming/name mangling, so you end up with a different symbol name. I can't tell from the error messages whether that relates to functions inside of `libz3.a` or your code, but in general I think it's a good idea to build the wasm version yourself, just to be sure that all the tools align.

**Comment by NikolajBjorner** [comment]
The WASM action still needs some work, specifically a BVT and double check if the binary really has to be 100MB. 
But yes, this has to be a linking issue based on incompatible C++ standard libraries. If you have an Action that fixes this please go ahead with a pull request. I can't otherwise take it as a work item to handle this.
