### ISSUE TITLE
SetSort missing in inheritance diagram of SortRef in Z3py reference.

### ISSUE THREAD

**Issue by pcarbonn** [Z3Prover/z3#5667]
It took me a while to discover the SetSort class in Z3py documentation.  The reason is that it is missing in the inheritance diagram of the [SortRef class](https://z3prover.github.io/api/html/classz3py_1_1_sort_ref.html).  Could it be added ?  There may be other missing sub-classes, I don't know.

**Comment by NikolajBjorner** [comment]
SetSort is just a shorthand for ArraySort where the range is BoolSort. So the automatically generated inheritance diagram does not have any SetSortRef class to refer to.
