### ISSUE TITLE
add support for SetHasSize

### ISSUE THREAD

**Issue by pcarbonn** [Z3Prover/z3#5672]
In so-called [generative configuration problems](https://www.google.com/search?q=generative+configuration+problems&oq=generative+configuration+problems), the number of components in a configuration is not known in advance . For example, a vehicle may have 1, 2, 3 or 4 wheels, subject to some constraints on cost and required functionality.

Such a problem could be represented in Z3 using an uninterpreted sort `WheelSort` for wheels, so that Z3 would generate identifiers for wheels as needed. A vehicle `v` would then be associated to a set of wheels, `wheelsOf(v)`, of type `SetSort(WheelSort())`, and the fact that a vehicle has 2 wheels would be represented using `SetHasSize`, e.g., `SetHasSize(wheelsOf(v), 2)`.

Unfortunately, `SetHasSize` is not supported anymore (#4700).  In view of the many applications, could it be supported again ?  Or, is there another approach to the problem ?

**Comment by NikolajBjorner** [comment]
Implementation was untested, slow and buggy. I proper implementation would be required.
