### ISSUE TITLE
Algebraic support for bv128

### ISSUE THREAD

**Issue by yannickmoy** [Z3Prover/z3#5687]
Currently, support for bv128 is very slow on many VCs such as this one which Z3 solves in 3 minutes:

```
(set-info :smt-lib-version 2.5)
(declare-const x (_ BitVec 128))
(declare-const s (_ BitVec 128))
(declare-const s1 (_ BitVec 128))
(assert (bvule s #x00000000000000000000000000000080))
(assert (bvule s1 #x00000000000000000000000000000080))
(assert (not (= (bvshl (bvshl x s) s1) (bvshl x (bvadd s s1)))))
(check-sat)
```

or this other one:

```
(set-info :smt-lib-version 2.5)
(declare-const x (_ BitVec 64))
(assert
  (not
  (= (* 18446744073709551616 (bv2int ((_ zero_extend 64) x)))
     (bv2int (bvmul #x00000000000000010000000000000000 ((_ zero_extend 64) x))))
  ))
(check-sat)
```

I have heard about upcoming algebraic support for bv128, does it improve the situation for these VCs? :-)

**Comment by NikolajBjorner** [comment]
The first example suggests that pre-processing could include a rule. I have added the rule and pushed an update.

The second example isn't clear to me why you claim it is unsat. 
The bit-vector #x00000000000000010000000000000000 encodes 2^32, but 18446744073709551616 requires more than 64 bits to represent.

**Comment by yannickmoy** [comment]
Thanks for the preprocessing! I'll use it.

For the second example, bit-vector #x00000000000000010000000000000000 encodes 2^64 (but it's true that I made a mistake in my original report and had the bit-vector for 2^32 instead), which is also the value of 18446744073709551616, and it's a case where we'd like to prove that multiplication commutes with the conversion bv2int.
