### ISSUE TITLE
Question about memory limitation.

### ISSUE THREAD

**Issue by TuoLi96** [Z3Prover/z3#5688]
I found that z3 in C++ consumes too much memory probably because the constraints in may code are very complex. Therefore, I want to limit the memory consumption using C++ API. But I have not found how to do it. I tried using context.set("max_memory_size", 1024) to limit the memory consumption to 1GB. Is it right?

By the way, where can I get all available parameters that can be set by context.set()?

Thanks very much!

**Comment by NikolajBjorner** [comment]
Use z3 -p to get _all_ parameters with descriptions including global.
