### ISSUE TITLE
Support for ASCII bytestrings and Unicode strings

### ISSUE THREAD

**Issue by let-def** [Z3Prover/z3#5689]
This input is accepted with Z3 4.8.9 but not with more recent version (>= 4.8.11, I haven't tested 4.8.10):
```
(declare-const a String)
(declare-const b (Seq (_ BitVec 8)))
(assert (= a "foo"))
(assert (= a b))
(check-sat)
(get-model)
```

I guess this is related to the new character theory: characters now have the built-in sort `Unicode` (and strings are therefore `(Seq Unicode)` and no longer `(Seq (_ BitVec 8))`).
I was hoping that the new `unicode` boolean configuration flag would allow to recover the old behavior, but characters remain Unicode.

- The documentation is not completely up to date: https://z3prover.github.io/api/html/group__capi.html#gaf85f3ec4cb347aa5cf5284fac5a73601 still refers to Ascii/8-bit strings. I guess it should be unicode.
- Is there some end-user documentation on this Unicode work? What is the purpose of the `unicode` configuration flag?
- For my use case (involving bytestrings), I think I can stop using the string API and build everything on top of sequences and bitvectors.
  Will there be a way to keep using 8-bit strings in the future (for convenience with string literals, string <-> integer conversion and lexicographic ordering)?

**Comment by NikolajBjorner** [comment]
Updated https://z3prover.github.io/api/html/group__capi.html#gaf85f3ec4cb347aa5cf5284fac5a73601
