### ISSUE TITLE
how to separate named expression and declaration's global-decls option?

### ISSUE THREAD

**Issue by cgcgbcbc** [Z3Prover/z3#569]
with or without `global-decls`, the following example will always be considered as error
```
;(set-option :global-decls true)
(push)
(declare-const x Bool)
(assert (! x :named f1))
(pop)
(assert (! x :named f1))
```

**Comment by NikolajBjorner** [comment]
That is a feature, not a bug.

**Comment by NikolajBjorner** [comment]
I am not sure other behavior makes sense:

1. With global-decls true, the expected behavior is that all names are global. This includes names of asserted formulas.
2. Without global-decls you get an error because the declaration of x is within a scope.
