### ISSUE TITLE
get the error (cannot convert ‘const vector<unsigned int>’ to ‘unsigned int*’ ) when I install z3

### ISSUE THREAD

**Issue by Ricardio609** [Z3Prover/z3#5691]
https://github.com/Z3Prover/z3/blob/06e48c89f241b254353c8665e36f4eb6b0ac6637/src/util/lp/permutation_matrix.h#L120

![image](https://user-images.githubusercontent.com/64991294/144344934-622c63a0-84a1-4cc7-b708-3fba452c0e82.png)

what should I do ?

**Comment by NikolajBjorner** [comment]
this is some old version of the code base. There is no support for downlevel code
