### ISSUE TITLE
UDIV of BitVec very slow

### ISSUE THREAD

**Issue by BaaBaaGoat** [Z3Prover/z3#5694]
sorry about poor english 

platform:z3py 4.18.3  on python 3.8.10 with jupyter notebook ,CPU:Intel E5 2680 V2,also tested on I9-9900KF and get similar result:

recurrent
[Untitled.ipynb.zip](https://github.com/Z3Prover/z3/files/7656524/Untitled.ipynb.zip)

import z3
u256 = z3.BitVecSort(256)
a=z3.BitVec("a",256)
s=z3.Solver()
s.add(a>1)
%time print(s.check()) #>>>>>Wall time: 47.5 ms
%time print(s.check(z3.UDiv(a*123,123)!=a)) # >>>>**Wall time: 48s**

**checking a multiply overflow by UDIV takes ~1min of time.**

for compare:pysmt on yices2 take only miliseconds:

import pysmt
import pysmt.shortcuts  as smt
from pysmt.logics import QF_AUFBV
name = "yices2" 
path = ["/usr/local/bin/yices-smt2"] 
logics = [QF_AUFBV] 
env = smt.get_env()
env.factory.add_generic_solver(name, path, logics)
u256=smt.BVType(256)
a=smt.Symbol("a",u256)
BVConst1=bin(123)[2:];BVConst1="0"*256+BVConst1;BVConst1=smt.BV(BVConst1[-256:])

%%time
with smt.Solver(name=name, logic=QF_AUFBV) as s:
    s.add_assertion(a>1)
    print(s.solve())
#>>>>>>>>>>>>>Wall time: 20.5 ms

%%time
with smt.Solver(name=name, logic=QF_AUFBV) as s:
    s.add_assertion(a>1)
    s.add_assertion(smt.BVUDiv(a*BVConst1,BVConst1).NotEquals(a))
    print(s.solve())

#>>>>>>>>>>>>>**Wall time: 239 ms**

is that a bug?

**Comment by NikolajBjorner** [comment]
thank you @BaaBaaGoat. It is not a bug. It is a difference in what is well tuned for. there will always be scenarios where z3 is not tuned. For bit-vector arithmetic over large worth lengths, yices has either better pre-processing simplification or the ability to use word level bit-vector reasoning, although the published algorithms don't cover your example.

**Comment by BaaBaaGoat** [comment]
> thank you @BaaBaaGoat. It is not a bug. It is a difference in what is well tuned for. there will always be scenarios where z3 is not tuned. For bit-vector arithmetic over large worth lengths, yices has either better pre-processing simplification or the ability to use word level bit-vector reasoning, although the published algorithms don't cover your example.

ok thx
