### ISSUE TITLE
Ext for Lambdas in python API

### ISSUE THREAD

**Issue by philzook58** [Z3Prover/z3#5704]
Is there a reason why the second argument of the Ext function cannot be a lambda term?

```python
x = Real("x")
Ext(Lambda([x],x),Lambda([x],2*x))
```

Throws an error because the second argument is not an `ArrayRef`
https://github.com/Z3Prover/z3/blob/0405a597d4b7c3997fa0aa2e670c808710093974/src/api/python/z3/z3.py#L4812

**Comment by NikolajBjorner** [comment]
not sure why the check is so strong. The extensionality expression is for some reason exposed but tends to be of internal use.
Here is some background: 
Ext makes sense only for one-dimensional arrays. Internally we create indexed versions for multi-dimensional arrays but opted to only first expose one dimensional array sorts over API to keep it manageable. Thus, the version of Ext for multi-dimensional arrays is not exposed and not supported. 
Ext is the Skolem function for the axiom:

forall a, b. a != b => exists ext . a[ext] != b[ext]

When you Skolemize this axiom, ext becomes a function that takes to arrays as arguments and produces an index where they are different (if they are not different the index is arbitrary). You can also think of it as a choice function.
