### ISSUE TITLE
Assertion violation ../src/ast/ast.cpp line 432

### ISSUE THREAD

**Issue by calebh** [Z3Prover/z3#5713]
I just finished moving my synthesis code over to using the .NET z3 bindings from Python. I was encountering this error in the Python bindings as well, except that for some reason it did not occur every run. Now that I am on .NET I am encountering this issue every run, no matter what:

```
ASSERTION VIOLATION
File: ..\..\src\ast\ast.cpp
Line: 432
UNEXPECTED CODE WAS REACHED.
Z3 4.8.10.0
```

The error appears to occur while I am building up the Z3 boolean expression AST inside the ToZ3 methods here: https://github.com/calebh/data-labeling/blob/master/DataLabeling/Ir.cs#L23

I have not been able to track down the source of the error any further due to extreme difficulties with getting Visual Studio to break when the error is thrown. Rather than sending me to a debug console the error appears to just terminate the program which is not that all helpful.

The Z3 AST that is being built is made up of implications, ands, ors, trues and falses. I do not understand why an error such as this would be thrown on such a simple construction. Here is an example of what the AST tends to look like:
```
(or (and (or v0 v2 v4 v6 v8 v10)
         (=> v0 false)
         (=> v2 true)
         (=> v4 true)
         (=> v6 false)
         (=> v8 false)
         (=> v10 true))
    (and (or v12 v14 v16 v18 v20 v22)
         (=> v12 false)
         (=> v14 true)
         (=> v16 true)
         (=> v18 false)
         (=> v20 false)
         (=> v22 true))
    (and (or v24 v26 v28 v30 v32 v34)
         (=> v24 false)
         (=> v26 true)
         (=> v28 true)
         (=> v30 false)
         (=> v32 false)
         (=> v34 true))
    (and (or v36 v38 v40 v42 v44 v46)
         (=> v36 false)
         (=> v38 true)
         (=> v40 true)
         (=> v42 false)
         (=> v44 false)
         (=> v46 true))
    (and (or v48 v50 v52 v54 v56 v58)
         (=> v48 false)
         (=> v50 true)
         (=> v52 true)
         (=> v54 false)
         (=> v56 false)
         (=> v58 true)))
```

Once again I will reiterate that the issue crops up while building up the Z3 expression, not running the actual solver. This is a big blocker to my project, and I either need a fix or a workaround.

**Comment by NikolajBjorner** [comment]
This is a bug in the C# API. It is addressed now. You can work around it as follows:

```
            if (form == Form.DNF) {
                if (ToggleVar == null) {
                    var ors = Inner.Select(x => x.ToZ3(ctx, form)).ToArray();
                    // This Or clause is in the outermost form, so we should ignore any toggle variable behaviour
                    return ctx.MkOr(ors);
                } else {
                    var ors = Inner.Select(x => x.ToZ3(ctx, form)).ToArray();
                    // This Or clause is embedded within an And clause as part of an "Any"
                    return ctx.MkImplies(ToggleVar, ctx.MkOr(ors));
                }
            } else if (form == Form.CNF) {
                if (ToggleVar == null) {
                    var ors1 = Inner.Select(x => x.ToggleVar).ToArray();
                    var ors2 = Inner.Select(x => x.ToZ3(ctx, form)).ToArray();

                    // This Or clause is embedded within an and clause, so we should compute an equivalent toggle variable
                    return ctx.MkOr(ctx.MkNot(ctx.MkOr(ors1)), ctx.MkOr(ors2));
                } else {
                    // This Or clause is embedded within an Or clause as part of an "Any"
                    var ors = Inner.Select(x => x.ToZ3(ctx, form)).ToArray();
                    return ctx.MkAnd(ToggleVar, ctx.MkOr(ors));
                }
```

That is, MkAnd and MkOr should not (in 4.8.10 and current release) be used with general enumerables because the expressions that are created underneath are garbage collected before the And/Or expression is built.

Your project uses 4.8.10. The newest version is 4.8.13. It is under Microsoft.Z3 and not Microsoft.Z3.x64.

For some reason I don't get the native z3lib.dll in my own installation when I load the nuget package. 
I could use some help in figuring out why this is so, and whether it is a local phenomenon. It isn't transparent to me why nuget doesn't install the native bindings. Maybe the package manager environment is set up in some strange way in my setting. I hope this is not the case generally.

**Comment by calebh** [comment]
@NikolajBjorner great, that fix worked!

It took several tries, but I did get the Microsoft.Z3 package to install. I do not understand exactly what the problem was during installation or why it took so many tries to get it to install. When I build now it does copy z3lib.dll and everything appears to work correctly. It could be the coffee shop wifi that I'm on, but I don't think that it's a particularly large package.
