### ISSUE TITLE
Integer check in extract does not allow long type

### ISSUE THREAD

**Issue by pgoodman** [Z3Prover/z3#572]
In Python 2.x, the following check does not allow `low` or `high` to be of type `long`:

```_z3_assert(isinstance(high, int) and high >= 0 and isinstance(low, int) and low >= 0, "First and second arguments must be non negative integers")```

You can fix this with `isinstance(high, (int, long))`, for example.

**Comment by NikolajBjorner** [comment]
we should use _is_int for all occurrences it seems.
