### ISSUE TITLE
Java API support for SMT-LIB regex functions (re.diff, str.replace_re,....) 

### ISSUE THREAD

**Issue by SebastianKuehne98** [Z3Prover/z3#5727]
Hi there! 

To my understanding, the java API does currently not support some SMT-LIB regex functions such as re.all, re.none, re.allchar, re.diff, str.replace_re and str.replace_re_all. 
  Is there any version of the java API that supports all these operations?

**Comment by NikolajBjorner** [comment]
I exposed allchar and introduced diff.

There is no reasoning support for str.replace_re and str.replace_re_all, and str.replace_all. So exposing API for building the expressions has no good use. Do you have any use case for these functions or is this a check-list bug?
