### ISSUE TITLE
New feature: JS bindings

### ISSUE THREAD

**Issue by aestriplex** [Z3Prover/z3#5736]
Hi @NikolajBjorner,

I wonder if I could start implementing Javascript/Typescript bindings for Z3. Node.js allows you to load C/C++ modules ordinary Node.js modules. 

So, the following is a sketch of my idea:

```
            +---------+
            |  z3.js  |  \ 
            +---------+    \      +-------------+
                            -->   |  z3core.js  |  -->  C++ functions
            +---------+    /      +-------------+ 
            |  z3.ts  |  /
            +---------+
```
As you can see, it follows the implementation of the Python bindings.
Could it worth the effort to implement such a thing?

Greetings,
Matteo

**Comment by aestriplex** [comment]
@NikolajBjorner I have just seen that there's an old issue about this topic (opened in 2017). Is still someone working on it?

**Comment by NikolajBjorner** [comment]
I don't know about js specific bindings. There were some stabs but no request to integrate a stable set of bindings.
The main attempt now is to get wasm builds shiny and stable as it allows using z3 from a client browser.
