### ISSUE TITLE
bitvector ops wth overflow

### ISSUE THREAD

**Issue by LeventErkok** [Z3Prover/z3#574]
There was a discussion a while ago adding overflow-checking variants of bitvector operations. And it seems @wintersteiger mentioned these are already implemented in Z3:

   http://www.cs.nyu.edu/pipermail/smt-lib/2015/000959.html

But a quick test suggests Z3 doesn't accept these functions (at least as they are named in that e-mail) from the SMTLib interface.

Are there any plans to add official support for these?

**Comment by NikolajBjorner** [comment]
When no logics are declared you get the following binary operators:  

     bvumul_noovfl  - unsigned multiplication no overflow
     bvsmul_noovfl  - signed multiplication no overflow
     bvsmul_noudfl  - signed multiplication no overflow

Example:

         (declare-const x (_ BitVec 14))
         (declare-const y (_ BitVec 14))
         (assert (bvumul_noovfl x y))
         (assert (bvsmul_noovfl x y))
         (assert (bvsmul_noudfl x y))
         (check-sat)

**Comment by NikolajBjorner** [comment]
Does this answer your question? Other overflow predicates are available for convenience over the API, but they expand into existing functions. Thus, Z3 doesn't build specific terms for these operators.

**Comment by LeventErkok** [comment]
Thanks Nikolaj.. I'm curious how the addition-overflow function expands into this though. The ones you mentioned seem to be only about multiplication. Is there a clever encoding trick one can use?

**Comment by NikolajBjorner** [comment]
The encodings are in src/api/api_bv.cpp and they are also described in:
Modular Bug-finding for Integer Overflows in the Large: Sound, Efficient, Bit-precise Static Analysis (MSR-TR-2009-57). Yannick Moy, Nikolaj Bjørner, Dave Sielaff. A workshop paper on the bit-precise aspects "Sound, Efficient, Bit-precise Static Analysis" appeared at CFV 2009.
http://research.microsoft.com/apps/pubs/?id=80722
They are not too advanced.

**Comment by LeventErkok** [comment]
@NikolajBjorner Nice. I didn't see a downloadable paper at that link however; is there a way to download the paper?

**Comment by NikolajBjorner** [comment]
weird, will add paper later
