### ISSUE TITLE
An issue about parameter settings of z3 tactic

### ISSUE THREAD

**Issue by zmylinxi** [Z3Prover/z3#5744]
Hi, we noticed that there may be something wrong in the parameter updating process of nlsat tactic.

Please see the attachment for details.

[an_issue_in_z3_en_final.pdf](https://github.com/Z3Prover/z3/files/7791564/an_issue_in_z3_en_final.pdf)

**Comment by NikolajBjorner** [comment]
Right, it needs some careful overhaul also elsewhere.
Append appears to be the way to go.

> Can parameters such as priority be introduced to control this detail when designing parameter
coverage?

Depends on intent. They are available through gparams so if some internal entity overwrites a parameter it can have the option to check gparams.

**Comment by NikolajBjorner** [comment]
The change went in two weeks ago. It was fixed.

**Comment by zmylinxi** [comment]
Thanks!
