### ISSUE TITLE
Python: Add binding for abs function

### ISSUE THREAD

**Issue by Tyilo** [Z3Prover/z3#5747]
It would make sense if the `abs` function from SMTLIB2 was exposed in the python bindings as `z3.Abs`.

**Comment by NikolajBjorner** [comment]
Added. It is shorthand for If(x > 0, x, -x)

**Comment by Tyilo** [comment]
The following code

```python
import z3
x = z3.Int('x')
solver = z3.Solver()
solver.add(x < 2, z3.Abs(x) == 2)
print(solver.sexpr())
```

produces

```
(declare-fun x () Int)
(assert (< x 2))
(assert (= (ite (> x 0) x (- x)) 2))
```

whereas I would expect it to produce:

```
(declare-fun x () Int)
(assert (< x 2))
(assert (= (abs x) 2))
```

@NikolajBjorner why don't we want to produce the SMTLIB2 `abs` function directly, instead of re-implementing it with `ite`?

**Comment by NikolajBjorner** [comment]
It always expands into if-then-else during pre-processing.

**Comment by jurek-n** [comment]
How would abs function look like using C# wrapper?
