### ISSUE TITLE
Compiling a statically linked Z3 4.8.12 release binary with Clang (LLVM) leads to different models and errors

### ISSUE THREAD

**Issue by zimmski** [Z3Prover/z3#5750]
I am posting this here as an already resolved bug report because the newest release (4.8.14) resolves the errors for us (Hence, will close the issue right away if i have the permission). But in case someone has the same problem, one can find it via the search engine of your choice.

We are currently in the process of compiling our own Z3 binaries but statically linked for Linux. Until now we used the official downloads which worked superb except for the problem that they are bound to a certain Glibc version.

We are compiling Z3 statically like this:

```
mkdir build
cd build
cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_EXE_LINKER_FLAGS:STRING='-static -Wl,--whole-archive -lrt -lpthread -Wl,--no-whole-archive'
make -j16
```

Which is working fine binary-wise. However, what is interesting is that the models changed (a lot, for different theories) and we receive errors for some of our cases. E.g. `Character range exhausted`. The last error especially triggered me to write this issue because Google gave me nothing.

We found the culprit of the problem to be compiling with Clang (LLVM). We tried 11 and 13. Both had the same problem with the statically linked binary but couldn't reproduce it with the dynamically one and we couldn't reproduce it with GCC (7.5 which is the default on this system... i know i know its old)

So if you are reading this: either update to 4.8.14 (which changes models for us as well but it looks like there are at least no errors) or use GCC

**Comment by NikolajBjorner** [comment]
One way to push the bug upstream (to z3) is to add a pull request with a GitHub action that contains your build steps and failing test. "Character range exhausted" is an exception raised by z3 during model construction for characters. 
Z3 is supposed to give the same results across compilers and architectures. When it doesn't, and it is z3's fault, there is typically something to do about it - if - it is possible to pin down the root cause.

**Comment by zimmski** [comment]
ot sure if that is worth anyone's time. Its fixed with the latest stable release, so my thought was at least post it in case someone searches for that problem.
