### ISSUE TITLE
Unable to solve string not equals utf-8 value via Java API

### ISSUE THREAD

**Issue by jaroslavlibak** [Z3Prover/z3#5755]
Java Solver API fails to solve very simple string not equals utf-8 value ("not(p1 == 'страна')"), yet works when ascii value is used instead.

Tested on z3 4.8.14. Reproducible in 4.8.12 as well.

Code snippet reproducing the issue:
```
  HashMap<String, String> cfg = new HashMap<String, String>();
  cfg.put("model", "true");
  Context ctx = new Context(cfg);
  Solver z3Solver = ctx.mkSolver();  

  Expr p1 = ctx.mkConst("p1", ctx.getStringSort());
  z3Solver.add(ctx.mkNot(ctx.mkEq(p1, ctx.mkString("страна"))));

  Status status = z3Solver.check();
  if (status == Status.SATISFIABLE) {
      System.out.println("SATISFIABLE");
      System.out.println(z3Solver.getModel().toString());
  } else if (status == Status.UNKNOWN) {
      System.out.println("UNKNOWN");
  } else {
      System.out.println("UNSATISFIABLE");
  }
```

Z3 fails to find solution for the above simple constraint "not(p1 == 'страна')" and the result is UNSATISFIABLE.

If I replace "страна" with "country" then it works fine and the solution is an empty string.
If I get rid of "ctx.mkNot" then it also works fine.

Interestingly exactly the same example works via z3.exe:
```
z3 -smt2 -in
(declare-const p1 String)
(assert (not(= p1 "страна")))
(check-sat)
sat
(get-model)
(
  (define-fun p1 () String
    "")
)
```

Alternatively:
```
z3 -smt2 -in
(declare-fun p1 () String)
(assert (not (= p1 "\u{ffffffd1}\u{ffffff81}\u{ffffffd1}\u{ffffff82}\u{ffffffd1}\u{ffffff80}\u{ffffffd0}\u{ffffffb0}\u{ffffffd0}\u{ffffffbd}\u{ffffffd0}\u{ffffffb0}")))
(check-sat)
sat
(get-model)
(
  (define-fun p1 () String
    "")
)
```

**Comment by NikolajBjorner** [comment]
It is the java front end. It doesn't understand unicode so the unicode characters are removed and you get an empty string.

**Comment by NikolajBjorner** [comment]
We would need to pre-process the string with something like
```
    s = "".join(str(ch) if 32 <= ord(ch) and ord(ch) < 127 else "\\u{%x}" % (ord(ch)) for ch in s)
```
in the Java, C# (and other) frontends. Currently only the Python front-end processes non-ascii strings.
