### ISSUE TITLE
Why do some APIs return `Z3_bool_opt`?

### ISSUE THREAD

**Issue by bakkot** [Z3Prover/z3#5757]
e.g. [`Z3_model_eval`](https://github.com/Z3Prover/z3/blob/7baa4f88b0cb4458461596d147e1f71853d77126/src/api/z3_api.h#L5267).

From what I can tell, `Z3_bool_opt` is [defined to be `Z3_bool`](https://github.com/Z3Prover/z3/blob/7baa4f88b0cb4458461596d147e1f71853d77126/src/api/z3_macros.h#L8), which in turn [is just `bool`](https://github.com/Z3Prover/z3/blob/7baa4f88b0cb4458461596d147e1f71853d77126/src/api/z3_api.h#L79). Why the indirection?

For context, I'm trying to figure out how to represent these types in TypeScript, and having three aliases for the same thing is confusing.

**Comment by NikolajBjorner** [comment]
Z3_bool_opt looks like a weird hack.

**Comment by NikolajBjorner** [comment]
It dates back to the "beginning of times" (https://github.githistory.xyz/z3prover/z3/blob/master/src/api/z3_macros.h) but is not referenced anywhere. So far I found no reference to Z3_bool_opt in code that depends.

**Comment by NikolajBjorner** [comment]
maybe some old versions of C that didn't have bool?

**Comment by NikolajBjorner** [comment]
Z3_ast_opt and Z3_sort_opt are used for documentation: the return value can be null and it is a legal return value.
Other functions that return Z3_ast cannot return null.
