### ISSUE TITLE
extract z3 ast to smtlib2 with java

### ISSUE THREAD

**Issue by doofin** [Z3Prover/z3#5775]
Hi
Is it possible to extract complete smtlib2 strings including definitions like `declare-datatypes` ? there's one for python but seems not present in java [https://github.com/Z3Prover/z3/issues/1451](https://github.com/Z3Prover/z3/issues/1451)

**Comment by NikolajBjorner** [comment]
I think the Solver.toString() should do the trick.

**Comment by doofin** [comment]
Thanks!
