### ISSUE TITLE
Question about get_assignment & mark_as_relevant

### ISSUE THREAD

**Issue by alan23273850** [Z3Prover/z3#5781]
I have some questions about the following code snippet in seq_eq_solver.cpp. (modified a little)

```cpp
literal lit1 = m_ax.mk_le(mk_sub(a, b), 0);
if (ctx.get_assignment(lit1) != l_true) {
    ctx.mark_as_relevant(lit1);
}
else {
    // do something
}
```

[Question 1 - get_assignment]
The code snippet expects `a ≤ b` to be true in order to "do something." Can `lit1 = m_ax.mk_le(mk_sub(a, b), 0);` be replaced with `lit1 = m_ax.mk_le(a, b);`? If this were true, all expressions with equivalent meanings have the same result from get_assignment (which extracts results from m_assignment), and this seems magical and little bit unreasonable. It means that I can query results of any expression I want to know via this function.

[Question 2 - mark_as_relevant]
Not sure if this mechanism is related to this paper: https://www.microsoft.com/en-us/research/wp-content/uploads/2016/02/tr-2007-140.pdf. May I know more about the details of usage? When should I use it, and is this just a heuristics or a necessary?
![image](https://user-images.githubusercontent.com/10044077/149914691-9a4490fd-b69a-42a5-a4b1-a30266943c17.png)

Thank you very much!

**Comment by NikolajBjorner** [comment]
The peculiar form of the inequality is for an internal reason: the arithmetic solver assumes that atoms are pre-simplified into the form t <= k or t >= k, where t is a term, k a numeral. 

You found the reference on relevancy. It explains the principles. The internals approximate the principles, sometimes overdoing what needs to be tagged as relevant. The high-level idea is to avoid theory propagation on atoms that don't matter for satisfying the formula. For example, if you have the clause (a or b or c) and assign a to true, then b, c don't matter relative to that clause. 

I am not sure if looking at the legacy solver is best use of bandwidth. The solver under sat/smt directory does not yet have a string solver, but I would port one to that directory on an occasion (and in the process fix some of the mistakes uncovered with the current theory_seq). The integration framework is overall cleaner in sat/smt. Also, the arithmetic solver does not have this assumption baked in about how the inequality is represented. The big drawback of sat/smt is that it isn't tuned overall as the legacy solver and needs some bake time to become stable.

**Comment by alan23273850** [comment]
@NikolajBjorner Thank you for your response and it's very detailed and helpful! But, may I have a follow-up question about relevancy? In fact, the piece of code
```cpp
if (ctx.get_assignment(lit1) != l_true ||
    ctx.get_assignment(lit2) != l_true) {
    ctx.mark_as_relevant(lit1);
    ctx.mark_as_relevant(lit2);
}
```
is extracted from https://github.com/Z3Prover/z3/blob/master/src/smt/seq_eq_solver.cpp#L387-L391 and it's indeed the latest version. Yesterday my collaborator and I inferred that the meaning of `ctx.mark_as_relevant(lit);` is to notify the SAT solver to assign a truth value (maybe true or false) to `lit` before the next round of `final_check_eh()`. If this inference were true, then the follow-up potential problem would be: It is possible for the SAT solver to always assign an unchanged truth value, say false, to `lit` before each round of `final_check_eh()`. In this case, the procedure would fall into an infinite loop since the if condition is always true and `final_check_eh()` always returns FC_CONTINUE. The loop then repeats again and again. Is there any mechanism to prevent this from happening?
