### ISSUE TITLE
How does Z3 handle SMT-LIB scripts with absent set-logic command ?

### ISSUE THREAD

**Issue by ossanha** [Z3Prover/z3#58]
It has been my experience that Z3 is able to work glitch-free with SMT-LIB scripts, even when they do not sport an initial (set-logic) command, even though this is mandated by the standard.

For example the minimal script below yields (correctly of course) unsat:

~~~~
;;(set-logic QF_IDL)
(assert (< 2 1))
(check-sat)
~~~~

What does Z3 do in such cases (they might be much more complicated) ? Does it try to infer the minimal logic needed ? Or does it load the most general capacities (such as treating AUFNIRA) and goes from there ?

**Comment by wintersteiger** [comment]
Yes, in those cases Z3 will try to figure out what the logic is, but there is no guarantee that it will always find a minimal logic. Also, it will perform only trivial simplifications beforehand. The part of the code that does this is in [default_tactic.cpp](https://github.com/Z3Prover/z3/blob/master/src/tactic/portfolio/default_tactic.cpp). Note that not all logics are probed there. If none of the probes matches, Z3 will run the most general tactic called simply "smt".

**Comment by ossanha** [comment]
Thanks for this quick answer. This helps!
