### ISSUE TITLE
Integer exponentiation

### ISSUE THREAD

**Issue by Baltoli** [Z3Prover/z3#5809]
We are generating a Z3 query that looks something like this (after being minimised):
```smt
(declare-fun X () Int )
(declare-fun Y () Int )

(assert
  (and
    (>= X 0)
    (>= Y 1)
    (< X (- (to_int (^ 2 Y)) 1))
  )
)

(check-sat)
(get-model)
```

A model that seems like it should satisfy the assertion is `X=0, Y=1`:
```
2^1 - 1 = 1
0 < 1
```

However, Z3 (version `4.8.14`) is unable to prove this (`unknown` rather than `sat`). If the constraint that `(>= X 0)` is removed from the conjunction, Z3 returns a model:
```smt
sat
(
  (define-fun Y () Int
    1)
  (define-fun X () Int
    0)
)
```

This model is consistent with `(>= X 0)`. Is there a reason that Z3 is unable to prove the assertion above?

I may well be missing something in my understanding of what's happening here; we've run into [other issues](https://github.com/Z3Prover/z3/issues/5243) with exponentiation (which I know is non-standard) in the past, but I don't know if it's related.

**Comment by NikolajBjorner** [comment]
when the lower bound on x is removed, the remaining literal on x is unconstrained so z3 can use pre-processing to solve the problem. With the lower bound, z3 is faced with 2^y, which is treated as an unsupported operation (the arithmetic decision procedure gives up).

**Comment by Baltoli** [comment]
Thanks @NikolajBjorner - much appreciated
