### ISSUE TITLE
Z3 does not respect timeout on QF_NRA script

### ISSUE THREAD

**Issue by Heizmann** [Z3Prover/z3#581]
When I run

    z3 -t:1000
or

    z3 -T:1000
(soft resp. hard timeout of 1000ms)  on the [attached script](https://github.com/Z3Prover/z3/files/243417InvariantSynthesis_Disjunctive02.bpl_Iteration1.smt2.txt) Z3 does not terminate (within several minutes).

**Comment by NikolajBjorner** [comment]
Do you mean to say it is somewhat tardy (which seems to be the case when I run it), but then CPU time != user time.

**Comment by Heizmann** [comment]
I just realized that the hard timeout is given in seconds. In fact, the hard timeout it seems to work.
However, for 

    z3 -t:10
I am already waiting for more than 10 minutes (and I presume that the soft timeout is given in milliseconds).

**Comment by Heizmann** [comment]
Even if I use

    z3 -t:1
I do not get any result (for the first check-sat) within two minutes.

**Comment by NikolajBjorner** [comment]
sorry for the discrepancy (legacy to blame) of metrics used for timeouts. 
10 minutes should not be the case. I have been trying to repro for -t, but get something tardier. Yet this is likely because I am abusing the CPU on my laptop while doing it.

**Comment by NikolajBjorner** [comment]
You are of course invited to break Z3 in a debugger after the soft timeout and record the stack trace in the bug/issue report :-)

**Comment by NikolajBjorner** [comment]
Got it. Bug with nested cancels.
