### ISSUE TITLE
The time-consuming of solver::check() increases under multi-threading

### ISSUE THREAD

**Issue by UESuperGate** [Z3Prover/z3#5811]
Hi there!

I am trying to create threads to solve assertions in parallel. To achieve that, I have to create `z3::context` and `z3::solver` for every single thread. The overview of the thread function should be like this:

```c
void solver_handler(...) {
    z3::context ctx;
    z3::solver sv(ctx, "QF_BV");
   
    /// Add constrants.
    ...

    uint64_t before = getTimeStamp();
    if (sv.check() == z3::sat) {
        uint64_t solve_time = getTimeStamp() - before;
        
        /// Generate final outputs.
        ...

        mutex_for_file_index.lock();
        
        /// Dump outputs to files.
        ...

        file_index++;
        std::cout << "time consuming at " << file_index << ": " << (double)solve_time / (double)kUsToS << std::endl;
        mutex_for_file_index.unlock();
    }
}
```

I use `thread pool` to specify how many threads should be created. But when I was testing, I found that the solving process seems to cost more time if I use more threads.

For 8 threads, file index ranging from 580 to 610:
<img width="167" alt="image" src="https://user-images.githubusercontent.com/45199886/152492199-b09e75c6-4cb1-4aea-94f2-b3458b5081e6.png">

For 16 threads, file index ranging from 580 to 610:
<img width="160" alt="image" src="https://user-images.githubusercontent.com/45199886/152492722-8ed6059d-9be4-4d60-ba45-21bdb638339f.png">

For 32 threads, file index ranging from 580 to 610:
<img width="148" alt="image" src="https://user-images.githubusercontent.com/45199886/152493088-97d6a229-302a-435d-bc72-cb744c93daf8.png">

I also replaced `solver::check()` with other time-consuming codes like `sleep(1)`, and it seems to run at normal tempo instead.

The `z3` commit is `4856581`.

**Comment by NikolajBjorner** [comment]
This is too open ended to be addressable. 
You can check for contention using performance profilers.
You should never run more threads than hyperthreads on your cores, typically 2x cores.
Short running queries may suffer from contention when they process shared state associated with symbol tables.
