### ISSUE TITLE
Invalid unsat with recursive functions and arrays

### ISSUE THREAD

**Issue by Elarnon** [Z3Prover/z3#5813]
On the following query, Z3 4.8.14 and current master 6a412f7f043690d0032a1c6cf742bdd1692df7d5 incorrectly answer `unsat`:

```lisp
(declare-fun sum ((Array Int Real)) Real)
(define-funs-rec
	((A ((i Int)) Real))
	((ite (<= i 0) 0. 
         (sum (lambda ((j Int)) (ite (and (>= j 0) (< j i)) (A j) 0.))))))
(assert (forall ((i Int)) (= (A i) 
	(ite (<= i 0) 0. 
         (sum (lambda ((j Int)) (ite (and (>= j 0) (< j i)) (A j) 0.)))))))
(check-sat)
```

Note that the definition of A is well-founded, and if `A` is declared as an uninterpreted constant instead, Z3 answers `sat`.  Z3 4.8.11 answers `unknown` as expected (a proof based on unfolding recursive functions would require an induction).

Git bisect points to 13da6a02a60282de54cfa8790fcc10cf22f6d263 as the culprit.

**Comment by NikolajBjorner** [comment]
Recursive functions within nested lambdas were never tested before.

**Comment by NikolajBjorner** [comment]
I will have to block nested lambdas in recursive definitions until there is meaningful support.
The legacy core is not well prepared for lambdas, but the new could be better positioned. 
Proper support with lambdas is a project in itself and therefore beyond a bug-fix. Maybe a topic for an internship.
