### ISSUE TITLE
z3 python not support Select with >=2 arguments 

### ISSUE THREAD

**Issue by gr8den** [Z3Prover/z3#5815]
I was trying call Select on Lambda with two arguments, but I found it not supported by python wrapper

Working smt2 example:
```smt2
(declare-fun x () Int)
(declare-fun y () Int)
(declare-fun z () Int)
(assert (= z (select (lambda ((i Int) (j Int)) (+ i j)) x y)))
(assert (= y 7))
(assert (= z 10))

(check-sat)
(get-model)
```

Python code with error:
```python
from z3 import *

x, y, z, i, j = Ints('x y z i j')

A = Lambda([i, j], i + j)
s = Solver()

s.add(z == Select(A, x, y)) # TypeError: Select() takes 2 positional arguments but 3 were given
s.add(y == 7)
s.add(z == 10)

print(s.sexpr())
assert s.check() == sat

```

**Comment by NikolajBjorner** [comment]
The python API does not support two/tree/... dimensional arrays. 

At this point you would have to write your own wrapper for Z3_mk_select_n or add a pull request with an overload of Select that allows multiple arguments. There is also Z3_mk_store_n for multi-argument stores.
