### ISSUE TITLE
Configuration failed by a non-Unicode file

### ISSUE THREAD

**Issue by nekketsuuu** [Z3Prover/z3#582]
Hello. I'm new to Z3. In order to install, I configured Z3 on Ubuntu by `python scripts/mk_make.py` after `git clone` as same as [README](https://github.com/Z3Prover/z3/blob/master/README.md#building-z3-using-make-and-gccclang) says. But it failed because of the string encoding. All logs is in [this gist](https://gist.github.com/nekketsuuu/267f4092fc6cf0e565b084acbcaa74d0). The main error is this:

```
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x92 in position 73: invalid start byte
```

0x92 is apostrophe in CP1252. I think this error is caused by `src/util/mpf.cpp`, whose encoding is not UTF-8.

```
z3$ nkf --guess ./src/util/mpf.cpp
Shift_JIS (LF)
```

In fact the configuration successed after converting `mpf.cpp` into UTF-8.

```
z3$ cp ./src/util/mpf.cpp ./src/util/mpf.cpp.shiftjis
z3$ nkf -w ./src/util/mpf.cpp.shiftjis > ./src/util/mpf.cpp
z3$ python scripts/mk_make.py 
(omit)
Makefile was successfully generated.
  compilation mode: Release
Type 'cd build; make' to build Z3
z3$
```

My environment is listed up below:

```
Ubuntu 14.04, bash
Python 3.5.1 :: Anaconda 4.0.0 (64-bit)
gcc (Ubuntu 4.8.4-2ubuntu1~14.04.1) 4.8.4
```

So my question is: is this conversion is OK?

**Comment by NikolajBjorner** [comment]
thanks, hope this is fixed now.

**Comment by wintersteiger** [comment]
Sorry my mistake, thanks for fixing it. I'm currently working on mpf and will be for a while, I'll make sure I check the encoding isn't changed back again the next time I push.

**Comment by nekketsuuu** [comment]
Thank you for a rapid responce!
