### ISSUE TITLE
Problem with the Z3 rewriter_def.h

### ISSUE THREAD

**Issue by ssc-dlxs-ms-valliammal** [Z3Prover/z3#5822]
While executing the mythril library, that calls the z3 and it creates an error in 
File ../src/ast/rewriter/rewriter_def.h in Line 224.

Unexpected Code was reached.

This Assertion comes suddenly. Please check for us and let us know what is the problem
Main process exited, code=exited, status=114/n/a

**Comment by NikolajBjorner** [comment]
There is too little information in the post to say anything. The bug can be due to interfacing, incompatible libraries, bugs in z3. Impossible to tell.
