### ISSUE TITLE
Result changes from sat to unsat after adding fp.xform.array_blast parameter

### ISSUE THREAD

**Issue by AnzhelaSukhanova** [Z3Prover/z3#5833]
Hello!

I have found a clause where a result changes from sat to unsat after adding fp.xform.array_blast parameter. I'm attaching an example that causes the bug (I tried to simplify it, but it's still quite big). 
In this example the Ackerman reduction simply removes an expression of the form (= var0 (select array var1)) since there is only one expression of this form. So from rule 
```
Pr11(#6,#0,#14,#2,#7,#8,#3,#9,#4,#10,#13,#15) :- 
Pr12(#6,#0,#1,#2,#7,#8,#3,#9,#4,#10,#11,#13),
Pr23(#11,#0,#13,#2,#7,#8,#3,#10,#4),
Pr9(#12,#0,#13,#2,#7,#8,#3,#11,#4,#10,#15),
(= (:var 5) (select (:var 0) (+ 164 (:var 4)))),
(not (<= (:var 12) (+ 1 (:var 11)))),
(not (<= (:var 12) (:var 11))),
(= (:var 1) (store (:var 14) (+ 4 (:var 5)) 2)).
```
we get new rule
```
Pr11(#5,#0,#13,#1,#6,#7,#2,#8,#3,#9,#12,#14) :- 
Pr12(#5,#0,#15,#1,#6,#7,#2,#8,#3,#9,#10,#12),
Pr23(#10,#0,#12,#1,#6,#7,#2,#9,#3),
Pr9(#11,#0,#12,#1,#6,#7,#2,#10,#3,#9,#14),
(not (<= (:var 11) (+ 1 (:var 10)))),
(not (<= (:var 11) (:var 10))),
(= (:var 15) (store (:var 13) (+ 4 (:var 4)) 2)).
```
I'm not sure but maybe the check if the rest of the rule depends on the array from the select expression is missed?
[bug.smt2.txt](https://github.com/Z3Prover/z3/files/8039982/bug.smt2.txt)

**Comment by NikolajBjorner** [comment]
it was used for experiments nearly a decade ago. Not worth fiddling with it in the current state.
