### ISSUE TITLE
Z3 crashes when dealing with complex computation

### ISSUE THREAD

**Issue by lucaslulu** [Z3Prover/z3#5836]
Hi everyone,

I am now trying to utlize Z3 on a logisticRegression model. So the thing I did is to extract coefficient of the model and then create a real vector: x =  [Real('x_{}'.format(k)) for k in range(k)]

Well, the computation is not too complex actually as my k is only 3. So f(x) = x[0]*coef[0] ... x[2] * coef[2] + intercept

My goal is to make something like: if x[0] > 5, f(x) > 0.5, so
cond = x[0] > 5
goal = x[0] * coef[0] + x[1] * coef[1] + x[2] * coef[2] + intercept >= 0.5
It is a naive example, later I would add more complex rules.

but Z3 crashes immediately on check() (because of memory issue).

I am new Z3 user, can anyone tell me how to fix it? Many thanks.

**Comment by NikolajBjorner** [comment]
there is too little information to figure out what the problem is.
Create a self-contained repro.
