### ISSUE TITLE
It seems that z3 return the wrong interpolant 

### ISSUE THREAD

**Issue by QiZhou1992** [Z3Prover/z3#584]
So we try to use z3 to calculate the interpolant.
so we try to calculate the terpolants I that A => I and I is inconsistant with B. However after we get the interpolant I.  A => I, but I is consistant with B. And Z3 give us a model, which will make A false. 
the A formula
(and (>= (+ i0Path0Copy1Level0index0 (\* (- 1) i0Path1Copy2Level0index0)) 0)
     (not (<= i0Path1Copy2Level0index0 0))
     (>= (+ i0Path1Copy2Level0index0 (\* (- 1) $i1Path1Copy2Level0index3)) (- 1))
     (<= (+ i0Path1Copy2Level0index0 (\* (- 1) $i1Path1Copy2Level0index3)) (- 1))
     (<= (+ i0Path0Copy1Level0index0 (\* (- 1) i0Path1Copy2Level0index0)) 0)
     (= $i2Path1Copy2Level0index4
        (\* i0Path1Copy2Level0index0 $i1Path1Copy2Level0index3)))
the B formula:
(and (not (and true (= i1Path0Copy1Level0index4 i3Path1Copy2Level0index5)))
     true
     (= i1Path0Copy1Level0index1 0)
     true
     (> i0Path0Copy1Level0index0 0)
     (= i1Path0Copy1Level0index4
        (+ i1Path0Copy1Level0index1 i0Path0Copy1Level0index0))
     (= i0Path0Copy1Level0index5 (+ i0Path0Copy1Level0index0 (- 1)))
     (not (> i0Path0Copy1Level0index5 0))
     true
     (= i3Path1Copy2Level0index5 (div $i2Path1Copy2Level0index4 2))
     true)
the interpolants:
(let ((a!1 (not (<= (+ (\* 4 i0Path0Copy1Level0index0)
                       (\* (- 1) $i1Path1Copy2Level0index3)
                       (\* $i1Path1Copy2Level0index3 i0Path1Copy2Level0index0)
                       (\* (- 1) $i2Path1Copy2Level0index4))
                    1)))
      (a!2 (<= (+ (\* (- 1)
                     (\* $i1Path1Copy2Level0index3 i0Path1Copy2Level0index0))
                  $i2Path1Copy2Level0index4
                  $i1Path1Copy2Level0index3)
               1)))
  (and a!1 (not a!2)))
the model
(define-fun i1Path0Copy1Level0index4 () Int
  1)
(define-fun i3Path1Copy2Level0index5 () Int
  2)
(define-fun $i1Path1Copy2Level0index3 () Int
  (- 1))
(define-fun i0Path1Copy2Level0index0 () Int
  (- 1))
(define-fun $i2Path1Copy2Level0index4 () Int
  4)
(define-fun i0Path0Copy1Level0index0 () Int
  1)
(define-fun i0Path0Copy1Level0index5 () Int
  0)
(define-fun i1Path0Copy1Level0index1 () Int
  0)

**Comment by NikolajBjorner** [comment]
Closing as the code that was exercised in this issue is no longer part of the code base, #1646.
