### ISSUE TITLE
Unexpected output from SolverFor("QF_BV")

### ISSUE THREAD

**Issue by gkrait** [Z3Prover/z3#5840]
Hello,
I have the Python  function 

```python
def bits_sum(X):
	size_X=X.size()
	if size_X<3: return (If(X ==0 ,0, (If(X==1,1,(If(X==2,1,(If(X==3,2,55))))))))  # Of course, 55 will never be the case. 
	else:
		half_X_size=int(size_X/2)
		X1=Extract(half_X_size-1,0,X)
		X2=Extract(X.size()-1,half_X_size,X)
		return bits_sum(X1) + bits_sum(X2)
```
which computes the sum of set all bits of a bit-vector X. 
However, using this function in adding constrains to  the solver (in the case of QF_BV) caused unexpected output. For example: 
 
```python
s1=Solver()
s2 = SolverFor("QF_BV")

X=BitVec("X",64)
Y=BitVec("Y",64)

s1.add(bits_sum(X)==5)
s1.check()
s2.add(bits_sum(Y)==5)
s2.check()


print("Default: ",  simplify(s1.model()[X]).as_binary_string())
print("QF_BV: ", simplify(s2.model()[Y]).as_binary_string())
```

I get the following results: 

```
Default: 10000000000000010000000000000001001010000000000000000000
QF_BV: 1010101010101010101010101010101010101010101010101010100110101010
```
The default solver result is good, but the QF_BV's is surprising. Any idea why ?.

Thank you in advance,
George

**Comment by NikolajBjorner** [comment]
QF_BV does not contain the theory of integers, so they are treated as uninterpreted. By specifying QF_BV you are also declaring to not reason about integers.
