### ISSUE TITLE
Build fails on certain ARMv7 linux environments demanding -fPIC

### ISSUE THREAD

**Issue by msullivan** [Z3Prover/z3#585]
On some but not all of my ARMv7 linux machines, linking fails with:

```
/usr/bin/ld: api/dll/mem_initializer.o: relocation R_ARM_THM_MOVW_ABS_NC against `a local symbol' can not be used when making a shared object; recompile with -fPIC
api/dll/mem_initializer.o: error adding symbols: Bad value
```

I get this failure on an Nvidia Jetson-TK1 devkit running their provided Ubuntu 14.04 and g++ 4.8.4 and on a https://www.scaleway.com/ server running Ubuntu 15.10 and g++ 5.2.1. It builds properly on a Raspberry Pi running Raspbian 8.0 (jessie) and g++ 4.9.2.

I have a patch that fixes it by adding -fPIC when building on armv7 but I want to think if there is a more fine-grained solution here, since it doesn't affect all my machines.

**Comment by msullivan** [comment]
Aha, the raspberry pi install seems like everything is built for armv6, even though my boards are actually armv7s: gcc was built with `--with-arch=armv6`.

And, annoyingly, if I compile with -fPIC on the raspberry pi with a toolchain that default to armv6, I also get a failure

**Comment by delcypher** [comment]
@msullivan Does this also affect the [CMake build](https://github.com/Z3Prover/z3/blob/master/README-CMake.md)? I suspect it does as on non windows systems ``-fPIC`` is applied. However we can make this a bit more sophisticated by detecting the target (in fact that needs doing anyway so that the CMake build can support the different ARM variants) in https://github.com/Z3Prover/z3/blob/master/contrib/cmake/cmake/target_arch_detect.cpp and then changing how the build behaves.

**Comment by msullivan** [comment]
I'll test it out with the cmake build.

Also, looks like I was mistaken about -fPIC causing failures on my armv6 toolchain machine. A new clean build worked fine. I think the problem was that the board crashed in the middle and must have left some corrupted state.

So that means we could probably get away with always adding -fPIC when we detect armv7

**Comment by delcypher** [comment]
@msullivan Note the python build system (i.e. ``python scripts/mk_make.py``) doesn't work properly if you use reuse an existing build directory or change parts of the build (e.g. change build flags or change a module parameter). It also can sometimes fail to rebuild correctly if updating the code to a newer version (e.g. ``git pull``).

The CMake build system doesn't suffer from these issues (which is why I created it) but you will need to teach it how to handle the ARM architectures. Look for uses of ``TARGET_ARCHITECTURE`` in the CMake files to see where it's currently being used and modify as necessary. You will also need to modify https://github.com/Z3Prover/z3/blob/master/contrib/cmake/cmake/target_arch_detect.cpp

**Comment by msullivan** [comment]
Weirdly, the cmake one seems to build on my ARM machines without any configuration needed

**Comment by delcypher** [comment]
@msullivan I forgot how I implemented this :p. Looks like I set up CMake to not error out when ``TARGET_ARCHITECTURE`` is set to ``unknown``. It probably shouldn't be that way but at least it worked for you out of the box :). If you could contribute the relevant entries into https://github.com/Z3Prover/z3/blob/master/contrib/cmake/cmake/target_arch_detect.cpp for the different ARM variants it would be appreciated. You could probably use https://github.com/Z3Prover/z3/blob/master/contrib/cmake/cmake/target_arch_detect.cpp as inspiration.

**Comment by NikolajBjorner** [comment]
Can we consider this resolved?

**Comment by msullivan** [comment]
Oh, I forgot about this. Probably the regular Makefile should be fixed to add -fPIC on armv7 or to error and direct people to cmake. The first is easy, so probably that? I can submit a PR for whichever people think is the right thing.

**Comment by wintersteiger** [comment]
I think that's a good idea. Thanks for offering to put together a PR, that would be great! I don't think I have any armv7 devices to test it around, but I do have an armv8 in an RPi 3, which I suppose would suffer from the same issue?

**Comment by frapik99** [comment]
Hi all,
I'm trying to install z3 on my tablet but I have the same problem with -fPIC is there an easy work around? On my env I don't have cmake. How can I pass -fPIC at compile time?

Thanks

**Comment by wintersteiger** [comment]
@frapik99: the quickest way is to add it manually to `CXXFLAGS` in `build/config.mk` after running `mk_make.py`.

**Comment by frapik99** [comment]
thanks I'll do it :)

**Comment by frapik99** [comment]
Hi,
can I create a pull request for this?

**Comment by NikolajBjorner** [comment]
Yes, it would be very good with a fix available to everyone.

**Comment by frapik99** [comment]
@NikolajBjorner Sure, the idea is just to add ```-fPIC``` to the ```build/config.mk```

**Comment by NikolajBjorner** [comment]
I guess you mean the scripts that create the files. Did you try the "cmake" based build system?

**Comment by delcypher** [comment]
@frapik99 
> On my env I don't have cmake. How can I pass -fPIC at compile time?

You have a C/C++ compiler so you could just build CMake from source. It is supposed to have very minimal dependencies so you should be able to build it fairly easily.

**Comment by NikolajBjorner** [comment]
I would suggest to use the cmake system going forward. Adapting the python scripts for different platforms is not easily sustainable. There is a good chance that cmake does this well. See the README-CMake.md file for instructions. It is kindly provided by @delcypher .

**Comment by frapik99** [comment]
Ok I'll try again.

Thanks

**Comment by NikolajBjorner** [comment]
You are certainly welcome to update mk_util.py in the proper place and add pull request.
Currently, it seems, Linux builds don't differentiate between ARM and non-ARM platforms. Maybe adding some detection around line 2473 in mk_util.py would do it, but then we have to make sure this does not break other platforms. So I suspect it is some hassle. Ensuring that the cmake system works for you and others, would mesh well with moving beyond the mk_make.py based build configuration.

**Comment by delcypher** [comment]
@frapik99 
FYI

Instructions for building CMake from scratch can be found at

https://github.com/Kitware/CMake#building-cmake-from-scratch

Although CMake uses CMake to build itself the bootstrap script just needs a working shell, compiler and `make`. The bootstrap script builds a minimal version of CMake which can then be used to build CMake proper. So doing

```
$ ./bootstrap && make && make install
```

should be fairly easy.
