### ISSUE TITLE
Segmentation Fault when using Z3 Python Bindings

### ISSUE THREAD

**Issue by Eric-Vin** [Z3Prover/z3#5853]
When using the Z3 Python bindings I get a segmentation fault. Since Z3 objects do not support pickling serialization in Python I'm trying to distribute a Z3 expression to multiple processes by converting it using .sexpr() and parsing it back into a Z3 object on the other side. To my understanding this should work but instead, I sometimes get segmentation faults, memory double free errors, and an assertion that unreachable code has been reached. Normally I'd assume there would be some concurrency issues but there's no shared memory between them that I know of, and I believe the different stringified formulas should not affect each other. 

I was originally using Z3 4.8.12, but the issues persist on Z3 version 4.8.14. I've included the different crash information for each version below. Parallelization is done using the Multiprocess library with Dill. Here's the code I'm using in Python for __getstate__ and __setstate__, where the crashes are originating. Please let me know if I'm doing something I shouldn't be or if I can provide any more info!

Python Code:
```
    def __getstate__(self):
        # Initialize state_dict
        state_dict = {}

        # Get the smt2 encoding of the actual formula
        solver_1 = z3.Solver()
        solver_1.add(self.formula)
        state_dict["formula"] = solver_1.sexpr()

        # Get the smt2 encoding of the original formula
        solver_2 = z3.Solver()
        solver_2.add(self.orig_formula)
        state_dict["orig_formula"] = solver_2.sexpr()

        # Encode the main variables to tuple representations
        packed_vars = []

        for main_var in self.main_variables:
            if isinstance(main_var, z3.z3.BoolRef):
                packed_vars.append((str(main_var), "Bool", 0))
            elif isinstance(main_var, z3.z3.BitVecRef):
                packed_vars.append((str(main_var), "BitVec", main_var.size()))

        state_dict["main_variables"] = packed_vars

        # Store the internal boolean formula spec, and main variables map.
        state_dict["bool_formula_spec"] = self.bool_formula_spec
        state_dict["main_variables_map"] = self.main_variables_map

        return state_dict

    def __setstate__(self, state):
        # Initialize super class
        super().__init__([0,1])

        # Unpack actual and original formula
        solver_1 = z3.Solver()
        solver_1.from_string(state["formula"])
        assert len(solver_1.assertions()) == 1
        self.formula = solver_1.assertions()[0]

        solver_2 = z3.Solver()
        solver_2.from_string(state["orig_formula"])
        assert len(solver_2.assertions()) == 1
        self.orig_formula = solver_2.assertions()[0]

        # Unpack main variables
        unpacked_vars = []

        for packed_vars in state["main_variables"]:
            if packed_vars[1] == "Bool":
                unpacked_vars.append(z3.Bool(packed_vars[0]))
            else:
                unpacked_vars.append(z3.BitVec(packed_vars[0], packed_vars[2]))

        self.main_variables = frozenset(unpacked_vars)

        # Unpack internal variables
        self.bool_formula_spec = state["bool_formula_spec"]
        self.main_variables_map = state["main_variables_map"]
```

Unreachable Code GDB Warning (4.8.12):
```
ASSERTION VIOLATION
File: ../src/ast/ast.cpp
Line: 414
UNEXPECTED CODE WAS REACHED.
Z3 4.8.12.0
```

Backtrace 1 (4.8.14): https://pastebin.com/yWbNw7ZB

Backtrace 2 (4.8.14): https://pastebin.com/arEK30md

**Comment by NikolajBjorner** [comment]
The python API gives the convenience of working with a fixed global context. 
So when you create Solver() it uses the implicit global context for managing state.
State within each context is not thread safe. You have to use separate contexts between different threads.
