### ISSUE TITLE
Java api support for str.<=

### ISSUE THREAD

**Issue by SebastianKuehne98** [Z3Prover/z3#5855]
Hi there, 
  To my understanding the str.<= (SMT-LIB) function is currently not supported by the java api. Would it be possible to add this function? 
  Furthermore while working with the java api I came across some weird behaviour. Getting the Z3_decl_kind by calling getFuncDecl().getFuncDeclKind() works fine for most regular expressions. But for re.comp and re.range it returns "Z3_OP_INTERNAL". Is this intentional?

**Comment by NikolajBjorner** [comment]
added, fixed
