### ISSUE TITLE
Bug in z3py LastIndexOf

### ISSUE THREAD

**Issue by hemx0147** [Z3Prover/z3#5856]
There seems to be a bug in z3py [`LastIndexOf`](https://z3prover.github.io/api/html/namespacez3py.html#aa4bf1a97f6d3fd3a1e21c19ec2561279); it returns incorrect results if the substring is located at the end of the string.

(First reported on Stackoverflow: https://stackoverflow.com/questions/71183324/z3-lastindexof-returns-wrong-result)

**Comment by NikolajBjorner** [comment]
fixed
