### ISSUE TITLE
incorrect model for fp.roundToIntegral

### ISSUE THREAD

**Issue by florianschanda** [Z3Prover/z3#586]
I believe -1.0 is not a sensible model to the below. Looks like (fp.roundToIntegral RTN -1.0) seems to be -2.0...

(set-logic QF_FP)
(set-info :source |SPARK inspired floating point problems by Florian Schanda|)
(set-info :smt-lib-version 2.5)
(set-info :category crafted)
(declare-const x Float32)
(assert (fp.eq (fp.sub RNE x (fp.roundToIntegral RTN x)) (fp.sub RNE (fp.roundToIntegral RTP x) x)))
(assert (not (=> (fp.isNegative x) (= (fp.roundToIntegral RNA x) (fp.roundToIntegral RTN x)))))
(check-sat)
(get-value (x))
(get-value ((fp.isNegative x)))
(get-value ((fp.roundToIntegral RNA x)))
(get-value ((fp.roundToIntegral RTN x)))
(get-value ((fp.roundToIntegral RTP x)))
(get-value ((fp.sub RNE x (fp.roundToIntegral RTN x))))
(get-value ((fp.sub RNE (fp.roundToIntegral RTP x) x)))
(exit)

sat
((x (fp #b1 #x7f #b10000000000000000000000)))
(((fp.isNegative x) true))
(((fp.roundToIntegral RNA x) (fp #b1 #x7f #b00000000000000000000000)))
(((fp.roundToIntegral RTN x) (fp #b1 #x80 #b00000000000000000000000)))
(((fp.roundToIntegral RTP x) (fp #b1 #x7f #b00000000000000000000000)))
(((fp.sub RNE x (fp.roundToIntegral RTN x)) (fp #b0 #x7e #b00000000000000000000000)))
(((fp.sub RNE (fp.roundToIntegral RTP x) x) (fp #b0 #x7e #b00000000000000000000000)))

**Comment by wintersteiger** [comment]
Thanks for the report. I'm working on fp.rem and fp.roundToIntegral at the moment, so this will be fixed soon.

**Comment by wintersteiger** [comment]
Actually, why is this not "sensible"? RTN means round to negative, i.e., it will pick the next negative integer, which, for x=-1.5 is indeed -2.0.

Adding `(set-option :pp.fp_real_literals true)` to make it more readable:

    ((x ((_ to_fp 8 24) RTZ -1.5 0)))
    (((fp.isNegative x) true))
    (((fp.roundToIntegral RNA x) ((_ to_fp 8 24) RTZ -1.0 0)))
    (((fp.roundToIntegral RTN x) ((_ to_fp 8 24) RTZ -1.0 1)))
    (((fp.roundToIntegral RTP x) ((_ to_fp 8 24) RTZ -1.0 0)))
    (((fp.sub RNE x (fp.roundToIntegral RTN x)) ((_ to_fp 8 24) RTZ 1.0 -1)))
    (((fp.sub RNE (fp.roundToIntegral RTP x) x) ((_ to_fp 8 24) RTZ 1.0 -1)))

**Comment by florianschanda** [comment]
Hm. It made sense when I submitted it. :/ Let me go back and check again :D

**Comment by florianschanda** [comment]
Oh dear! Off-by-1 in my brain. Sorry for wasting your time, and thanks for the fast reply.

**Comment by wintersteiger** [comment]
No worries, happens to all of us, even more so when floating-point numbers are involved :-)

**Comment by florianschanda** [comment]
Wait! for x = -1.5, I would expect roundToIntegral with RNA to give -2, RTN -2 and RTP -1.
But in the model above we get -1 for RNA.

In the opening message I mentioned RTN, but that is not actually the issue, it was RNA.

**Comment by wintersteiger** [comment]
Inndeed, that looks much more like a bug! I've tentatively fixed this in a separate branch for now, until my tests are through.

**Comment by wintersteiger** [comment]
This is no merged, so I'm closing the issue.

**Comment by florianschanda** [comment]
Great, thanks! :)
