### ISSUE TITLE
Model.getConstInterp "invalid argument" Z3Exception instead of null return value

### ISSUE THREAD

**Issue by hajduakos** [Z3Prover/z3#587]
According to the Z3 Java API [documentation](http://z3prover.github.io/api/html/classcom_1_1microsoft_1_1z3_1_1_model.html#aceef5d8c0c6804f696668ac5cc48d850), if a constant does not have an interpretation in a model, `Model.getConstInterp(Expr)` should return `null`. However, I get an "invalid argument" `Z3Exception` on the latest master (0286cee45026a1cf97ae9f001b4049496267f691) build on Windows. This also holds for `Model.getConstInterp(FuncDecl)`. This behavior is reproducible with the following code.

```
Context context = new Context();
Solver solver = context.mkSimpleSolver();

BoolExpr a = context.mkBoolConst("a");
BoolExpr b = context.mkBoolConst("b");
BoolExpr expr = context.mkOr(a, b);

solver.add(expr);
solver.check();
Model model = solver.getModel();

System.out.println(model.getConstInterp(a)); // value of 'a' is 'true'
System.out.println(model.getConstInterp(b)); // Z3Exception: invalid argument
```

**Comment by NikolajBjorner** [comment]
Thanks, fixed
