### ISSUE TITLE
Z3 unable to solve problem

### ISSUE THREAD

**Issue by pjljvandelaar** [Z3Prover/z3#589]
Hi Z3 developers,

When I run Z3 (version "4.4.2 - build hashcode 88f92660f01c") on Microsoft Windows [Version 6.1.7601]
with the following smt2 file (zipped to satisfy github website)
[performanceIssue.zip](https://github.com/Z3Prover/z3/files/254553/performanceIssue.zip)
Z3 is unable to solve the last step.
The problem is definitely solvable.

Could you please look into it.

Pierre van de Laar

**Comment by NikolajBjorner** [comment]
try now

**Comment by pjljvandelaar** [comment]
Do I have to build a specific branch, or will it be in tonight's nightly build?

**Comment by wintersteiger** [comment]
You can build the sources from the current master branch yourself, or you can wait for the next automatic nightly build. The nightly build fails frequently e.g., when tests fail, so the next nightly binaries might not be available today.

**Comment by pjljvandelaar** [comment]
Problem still present in z3-4.4.2.cb6d008da860-x64-win

**Comment by pjljvandelaar** [comment]
Problem simplified to attached file.
[example.zip](https://github.com/Z3Prover/z3/files/283655/example.zip)

Hopes this helps in solving the bug!

**Comment by pjljvandelaar** [comment]
Problem still present in 8c99d3c43182
Is commit not integrated into main branch?
Or is only a part solved and committed yet?

**Comment by NikolajBjorner** [comment]
waiting to integrate until further tests.

**Comment by NikolajBjorner** [comment]
tested, it does solve them. many improvements are still possible, but it is open ended when it comes to int.to.str.

**Comment by pjljvandelaar** [comment]
Yes some improvements, but in my real cases it still returns unknown ....

Why is it so difficult? 
I could imagine that str.to.int is difficult, since +000, -000, and 0 are all the same representation of 0
But imho int.to.str can return just a 'standardized string' that can be mechanically generated and
adheres to the regular expression 
   -? [0-9]^{n}
where
value == 0 => n = 1
value != 0  => n == upperbound (log_10 ( abs(value) ))

**Comment by pjljvandelaar** [comment]
The latest nightly build 4.4.2 - build hashcode 736f2bef46fd
yields _unknown_ on the following example (zipped smt2 file)
[example.zip](https://github.com/Z3Prover/z3/files/300635/example.zip)

**Note** it might be an unrelated bug, since
manually removing the assertion (= hReport report) and replacing hReport by report 
as is done in the attached similarExample (zipped smt2 file)
[similarExample.zip](https://github.com/Z3Prover/z3/files/300634/similarExample.zip)
yields _sat_

**Comment by NikolajBjorner** [comment]
the solver already contains axioms that relate values to string lengths, but did not solve equations between int.to.str over unknown integers with constant strings.

**Comment by pjljvandelaar** [comment]
Thanks for adding this functionality!
