### ISSUE TITLE
link atomic failed in non-x86

### ISSUE THREAD

**Issue by Rabenda** [Z3Prover/z3#5896]
```
/usr/lib/gcc/riscv64-unknown-linux-gnu/11.2.1/../../../../riscv64-unknown-linux-gnu/bin/ld: src/api/CMakeFiles/api.dir/api_algebraic.cpp
.o: in function `.LEHE20':
api_algebraic.cpp:(.text+0x782): undefined reference to `__atomic_exchange_1'
/usr/lib/gcc/riscv64-unknown-linux-gnu/11.2.1/../../../../riscv64-unknown-linux-gnu/bin/ld: src/api/CMakeFiles/api.dir/api_algebraic.cpp
.o:api_algebraic.cpp:(.text+0xd46): more undefined references to `__atomic_exchange_1' follow
collect2: error: ld returned 1 exit status
```

**Comment by Rabenda** [comment]
https://bugs.gentoo.org/835003

build failed on gentoo riscv

**Comment by Rabenda** [comment]
[cmake/modules/CheckAtomic.cmake](https://github.com/KDE/krita/blob/620fbcbdcb9b33a38de86641e6db333e98007bb3/cmake/modules/CheckAtomic.cmake)

A detection atomic-linking need method

**Comment by NikolajBjorner** [comment]
Not sure what the purpose of filing the bug here. Based on the link, this is just a way to exercise a bug in the build system for whether a platform supports one form of atomic operations or not. 
Are you planning to submit a GitHub Action to build for riscv?

**Comment by Rabenda** [comment]
> Not sure what the purpose of filing the bug here. Based on the link, this is just a way to exercise a bug in the build system for whether a platform supports one form of atomic operations or not. Are you planning to submit a GitHub Action to build for riscv?

https://github.com/riscv-collab/riscv-gcc/issues/12

According to this, I'd like to improve compatibility for different toolchains on z3

**Comment by NikolajBjorner** [comment]
Then it is external.
You are welcome to add GitHub actions to build on different tool chains similar to other actions added (e.g., for arm).

**Comment by Rabenda** [comment]
https://github.com/Rabenda/z3/runs/5528565978?check_suite_focus=true

Add riscv64 build but same problem.
