### ISSUE TITLE
Simulating a parse-only mode with Z3 for SMT-LIB v2

### ISSUE THREAD

**Issue by ossanha** [Z3Prover/z3#59]
This is not a bug and more a want for explanation. If there is a better medium fot that kind of exchange (e-mail?), please feel free to indicate it.

I am running some benchmarks on various tools about SMT-LIB. One of the measuring stick is of course Z3. I am mostly interested as of now in the parsing time / AST construction.

Am I mistaken if I say that I can simulate/approximate a parse-only mode for Z3/SMT-LIB v2 by commenting line 2017 in src/parsers/smt2/smt2parser.cpp ? This is this line:
~~~~
m_ctx.check_sat(expr_stack().size() - spos, expr_stack().c_ptr() + spos);
~~~~

I am trying to *not* trigger the SMT solving engine of Z3 and just have something close to simple AST construction.

**Comment by wintersteiger** [comment]
That change will disable check-sat commands in SMT2 input files (but not any other commands, or non-SMT2 input files). Alternatively, the API functions [`Z3_parse_smtlib2_string`](http://z3prover.github.io/api/html/group__capi.html#ga666126cb89d0cc64027e58d13960accf) or [`Z3_parse_smtlib2_file`](http://z3prover.github.io/api/html/group__capi.html#gab2b5e637145c7dcc22f8f221c61309dd) could be useful too.

Closing this as resolved, please reopen if more questions come up.
