### ISSUE TITLE
Problem installing z3 on Ubuntu 16.04

### ISSUE THREAD

**Issue by gessha** [Z3Prover/z3#590]
Hello,
I cloned the repository, built z3, installed it, but z3 doesn't work outside of the built directory.
Do you know a way to fix this?

**Comment by wintersteiger** [comment]
Depending on where you installed it to, you may have to add the directory containing the z3 binary to PATH, or the directory containing libz3.so to LD_LIBRARY_PATH.

**Comment by gessha** [comment]
I should've read the output of make thoroughly... I added the build directory to PYTHONPATH and the tests worked outside of the build directory. Sorry for the trouble and thank you for the quick response.

**Comment by ms140400344** [comment]
Would you like to tell me the Z3's installation procedure from scratch?

**Comment by wintersteiger** [comment]
@ms140400344 It depends on your environment and requirements; there are a multitude of different ways and options. The easiest is to download one of our releases, unzip it, and point your application to those locations (e.g. by setting the corresponding environment variables like PATH, LD_LIBRARY_PATH, PYTHONPATH, etc).
