### ISSUE TITLE
Disposing of Z3Objects in the dotnet API

### ISSUE THREAD

**Issue by Choc13** [Z3Prover/z3#5900]
Our application uses Z3 via the dotnet API. Recently we've been addressing issues with large memory consumption when we're running large programs and we wondered if someone could clarify for us the way that a `Z3Object` should be disposed of.

The `Z3Object` implements `IDisposable` and so usually we would expect to wrap these in a `using` statement to make sure that their `Dispose` method is called once they go out of scope. Maybe we've just not looked in the right place, but all of the usages of the Z3 dotnet API we have seen do *not* follow this pattern and instead just rely on the fact that the finalizer for `Z3Object` also calls `Dispose`. My first question therefore is, was it intended that users of the dotnet API should wrap each `Z3Object` in a `using` statement or not? 

Partially due to my initial naivety around the fact that I did not know that the finalizer for a `Z3Object` will call `Dispose`, I undertook the task of changing our code base such that each time a `Z3Object` was created it was wrapped in a `using` statement, as I believed we would be leaking each `Z3Object` that wasn't. 

It is my understanding from reading #5330 and #5043 that the native memory that a `Context` points to has allocated a large hash map and we were therefore keen to ensure that each `Context` was deterministically disposed to free this. Looking inside the [`Dispose`](https://github.com/Z3Prover/z3/blob/master/src/api/dotnet/Context.cs#L4934) method for `Context` the `refCount` must be `0` before it will free the native memory, and the `refCount` is only decremented when a `Z3Object` created by that `Context` is disposed. Hence my desire to ensure that each `Z3Object` created from that `Context` was also deterministically `Disposed` via a `using` statement.

This led us to some interesting findings that I wanted to share:

1. Using `using` statements gave us a much more stable memory profile, without this we found that the memory would jump around a lot, presumably because the GC can't actually see the native memory's size and so when it does finally do a GC collect it's already under a lot of pressure and the finalizer queue is full of a lot of pointers.
This was especially true when we created a fresh `Context` each time we needed one due to the fact that the native memory for the `Context` had allocated a large hash map. We are aware that, as mentioned in the issues linked above, the recommendation is to reuse them, but we were interested in whether this was still true when they were being deterministically disposed.

1. There are parts of the dotnet `Context` API that create intermediate `Z3Object`s (see [`MkConst`](https://github.com/Z3Prover/z3/blob/master/src/api/dotnet/Context.cs#L786) for example) which are not wrapped in a `using` statement and it therefore impossible to deterministically `Dispose` of these from the outside. This meant that the `Context.refCount` was not `0` at the time of disposal and so it wouldn't free the native memory and instead just call [`GC.ReRegisterForFinalize`](https://github.com/Z3Prover/z3/blob/master/src/api/dotnet/Context.cs#L4942). It is possible to work around this from the outside because it is just a helper method that calls other parts the public interface. Possibly this is the intended behaviour due to the design though.

1. The [`Context.Dispose`](https://github.com/Z3Prover/z3/blob/master/src/api/dotnet/Context.cs#L49300) method does not call `Dispose` on the `m_xxxSort` fields. Again this may be intentional if the design of the dotnet API is to rely on finalizers.

1. Related the previous point, the `m_charSort` field seems to be missing from the cleanup in `Context.Dispose`. 

From our experimentation it seems that explicit usage of `using` statements around each `Z3Object` and reusing `Context`s (in a threadsafe manner) gets the lowest and most stable memory footprint and the best CPU utilisation when being used in an intensive, highly multi-threaded, application. 

I would be interested to hear your thoughts on this and whether my understanding of the dotnet API and its disposal pattern is indeed correct. I'm also happy to create a PR which addresses any or all of the points I raised above.

**Comment by NikolajBjorner** [comment]
The understanding is correct.
For higher efficiency interaction I am adding NativeContext and NativeSolver. They don't work with long running contexts that require garbage collecting expressions while the context is live, but on the other hand this doesn't really work with the managed context as you notice (unless you use all these "using" statements).

I am not sure what is actionable from your description other than adding dispose calls for m_boolSort and other sorts in the Context object.

**Comment by Choc13** [comment]
Thanks for confirming my understanding @NikolajBjorner and it's nice to hear you're working on an alternative implementation that is more amenable to short lived contexts, I think this will be useful for our application.

The potential action points from my first comment are:

1. Add `m_charSort = null` to `Context.Dispose`. I think this is just an omission and should be there to make it consistent with the current way in which the other sort fields are disposed.

1. Call `m_boolSort.Dispose()`, `m_charSort.Dispose()` etc inside of `Context.Dispose()` as this will ensure they are cleaned up deterministically and make it more like that the `Context.refCount` is `0` which will then mean the native memory can be freed sooner rather than having to wait for the finalizers of those sorts to run first.

1. Modify methods like `MkBVConst` to be more like this

```csharp
public BitVecExpr MkBVConst(string name, uint size)
{
    using var symbol = MkSymbol(name);
    using var sort = MkBitVecSort(size);
    return (BitVecExpr) MkConst(symbol, sort);
}
```

I would be happy to add a PR for an or all of these items as with those changes we're able to then add explicit `using` statements to the places in our code and be confident that the `Context` will have a `refCount` or `0` when we try and `Dispose` it. (Obviously point 1, is somewhat superseded by 2 and 3). Equally, if you don't want to adopt this approach within `Context` itself then I'm happy to just address point 1 which I think is just a small mistake in the current implementation.

**Comment by NikolajBjorner** [comment]
I implemented some of these notes. For missing pieces, can you add pull requests?

**Comment by Choc13** [comment]
@NikolajBjorner thanks for making these changes and merging my PR for the remainder. Do you have a timeline on when these changes will make it into a stable release? Thanks.

**Comment by NikolajBjorner** [comment]
I can create releases on demand.
How about April 2nd?

**Comment by Choc13** [comment]
Yeah that would be great. If you're able to do it any sooner that would also be much appreciated. Thanks.

**Comment by NikolajBjorner** [comment]
> Do you have a timeline on when these changes will make it into a stable release?
There was one yesterday.

The nuget distribution of x86 bindings remains a bit older. It was initially created between 8.14 and 8.15 and was versioned 8.15. Nuget doesn't let me purge the old version and requires a version bump. 
Since I believe this is a minor nuisance for those who must distribute x86/Windows I am taking the approach to wait for 8.16 to synchronize these versions. If there is a real need to synchronize them, bumping to 8.16 is an option, but a release still requires some babysitting (less now that the CI/CD scripts were updated).
