### ISSUE TITLE
Z3 generates solution which it doesn't accept itself

### ISSUE THREAD

**Issue by pjljvandelaar** [Z3Prover/z3#592]
When I run z3 (version "4.4.2 - build hashcode 88f92660f01c") 
on Microsoft Windows [Version 6.1.7601]
with the attached example (zipped due to github limitations) 
[issue.zip](https://github.com/Z3Prover/z3/files/256527/issue.zip)
I get the following output:

(:name "Z3")
(:version "4.4.2 - build hashcode 88f92660f01c")
sat
((var (ExposureReport$C_ExposureReport
  (LotInfo$C_LotInfo (LotId$C_LotId 85) (LotSize$C_LotSize 4))
  (ExposureRecipeId$C_ExposureRecipeId 73)
  (Time$C_Time 13292))))
unsat

In words: Z3 comes to the (in my opinion incorrect) conclusion that the first problem can be satisfied and the value of the solution is printed.
However, when Z3 must solve the first problem with the additional constraint that the variable is equal to the printed value, Z3 comes to the conclusion that it cannot be satisfied.

The output that was expected is something like:
unsat
(error "Cannot get value unless immediately preceded by SAT/INVALID or UNKNOWN response.")

I hope you can solve this bug!

Pierre

**Comment by NikolajBjorner** [comment]
try now

**Comment by pjljvandelaar** [comment]
Yes this works!
