### ISSUE TITLE
Microsoft.Z3 nuget version is not updated to 4.8.15

### ISSUE THREAD

**Issue by GennadyGS** [Z3Prover/z3#5927]
Microsoft.Z3.x86 nuget is updated to 4.8.15 version, while Microsoft.Z3 is still on 4.8.14. 
Is it expected?
Thanks.

**Comment by NikolajBjorner** [comment]
It is 4.15 but from an earlier build than the release. 
I cannot update the x86 until next version since nuget.org does not allow overwriting releases.
You can obtain the release version of the nuget package from the github releases. Versions 4.16 will be in sync again.

**Comment by GennadyGS** [comment]
Great, thanks!
