### ISSUE TITLE
Question on simplify()

### ISSUE THREAD

**Issue by qingkaishi** [Z3Prover/z3#5929]
Z3's simplify() function simplifies `-4 + len <= 2` to `extract(-4 + len, 63, 2) = 0 && extract(len, 1, 0) ≤ #b10`.

Here, `len` is a 64bit bitvector, `<=` is unsigned. `extract(v, high, low)` just means extracting the bits from high to low.

I am wondering which simplification procedure does this simplification. I want to close it. I tried to use `simplify(params const & p)` but fail to find the correct options I need to pass into this API. Could you help?

**Comment by NikolajBjorner** [comment]
To disable this requires a new parameter.
