### ISSUE TITLE
API: add UF recognizer

### ISSUE THREAD

**Issue by nunoplopes** [Z3Prover/z3#593]
Right now, from the API there's no way to distinguish between a user-created UF and plugin UFs (such as "bvudiv_i" and friends).
In both cases, we get:
Z3_get_decl_kind(ctx, decl) == Z3_OP_UNINTERPRETED

It would be nice to have a way to distinguished between the two cases.

**Comment by wintersteiger** [comment]
@MikolasJanota and I recently had the same problem internally and we added [is_considered_uninterpreted](https://github.com/Z3Prover/z3/blob/master/src/ast/bv_decl_plugin.h#L271) to the decl_plugins. Would exporting this do the job for you?

**Comment by nunoplopes** [comment]
Uhm, not really. That function identifies symbols that can be considered as UFs. That's helpful for ackermannization.
But what I really need is to differentiate between user-defined UFs and internal stuff, since some transformations I'm doing are unsound for certain internal UFs.

**Comment by wintersteiger** [comment]
What certain internal UFs are those?

**Comment by nunoplopes** [comment]
In this case are all of them. I really need to know which UFs were created by me and which UFs are Z3's internal stuff.
Z3 has this information internaly; it's just a matter of exposing it somehow.

**Comment by wintersteiger** [comment]
What are "all" of them? There are functions that are UFs, but they belong to a family and therefore "look like" interpreted functions (e.g., bv*div0), so we have is_considered_uninterpreted so we can recognize them. The bv*div_i functions are interpreted (that's what _i stands for). I'm not aware of any functions that are uninterpreted internally but supposed to behave in any way different from general UFs. Can you give me some more information about the problem you're trying to solve? (This might require substantial changes, e.g., if you include uninterpreted constants then every temporary variable ever introduced would have to be labelled.)

**Comment by wintersteiger** [comment]
Just had a chat with @NikolajBjorner and we think we know what you want. I forgot that the family-ids aren't available in digestible form via the API. I think the best way to do this is to add two Boolean functions to check for builtin-interpreted and builtin-uninterpreted. Would that do the job for you?

**Comment by nunoplopes** [comment]
Interesting; I was just looking to the code of `Z3_get_decl_kind` and I found this:
```
            case OP_BSDIV0: return Z3_OP_BSDIV0;
....
            case OP_BSMUL_NO_OVFL:
            case OP_BUMUL_NO_OVFL:
            case OP_BSMUL_NO_UDFL:
            case OP_BSDIV_I:
            case OP_BUDIV_I:
            case OP_BSREM_I:
            case OP_BUREM_I:
            case OP_BSMOD_I:
                return Z3_OP_UNINTERPRETED;
```

I guess that's the reason why I can't distinguish these from UFs :)
So maybe fixing this function would be sufficient?  Then only the null family would return Z3_OP_UNINTERPRETED.  For my use case that's sufficient.

**Comment by NikolajBjorner** [comment]
Nuno, could you add the function you need?

**Comment by wintersteiger** [comment]
Indeed, that code fragment looks like pre-tactic-framework where the intention was that those operators are never visible on the outside. I think it would be safe to change `Z3_get_decl_kind` with minimal problems with applications though.

**Comment by nunoplopes** [comment]
Is something like  https://github.com/Z3Prover/z3/pull/597 ok?

**Comment by wintersteiger** [comment]
Yes, I think that's what we will have to do even if we don't like it :-) 

All those functions can be in the result of `(apply simplify)`, so we need to have all of them in the API, including those of the other decl plugins.
