### ISSUE TITLE
Exception thrown at 0x108AD29E (libz3.dll) in Test_z3.exe: 0xC0000005: Access violation reading location 0x00000006.

### ISSUE THREAD

**Issue by slutz14** [Z3Prover/z3#5930]
Hello,
I get the this error when using the newest release of z3 for c++ in Visusal Studio 2022 on Windows.

I was able to reproduce the error using a simple program:

#include "z3++.h"
int main()
{
    z3::context c;
    return 0;
}

The error occurs in line 171 of z3++.h : Z3_set_ast_print_mode(m_ctx, Z3_PRINT_SMTLIB2_COMPLIANT);

Greetings

**Comment by NikolajBjorner** [comment]
You may have an old version of the library on the path.
