### ISSUE TITLE
How to use sqrt and power in C++

### ISSUE THREAD

**Issue by Co1lin** [Z3Prover/z3#5931]
In Python, I can easily create a `Real` like `1.0 / z3.Sqrt(2)` . But I am confused by writing `z3.Sqrt(2)` or something like `3^(1.0/3)` in C++. What is the right way?

**Comment by Co1lin** [comment]
Oh, I tried `z3::pw(c.real_val("2"), c.real_val("1/2"));` and it seems working (without reported errors). It is right?

**Comment by NikolajBjorner** [comment]
Yes, pw will do.
