### ISSUE TITLE
Error after trying to run on a local server running Windows

### ISSUE THREAD

**Issue by geraw** [Z3Prover/z3#5934]
|

Timestamp|Level|Message|
|---|---|---|
|Mar 29, 2022, 12:08:49 PM|WARNING|WARNING:root:kernel 8922c419-a7e8-451f-b7e4-52f38e6b9fe8 restarted|
|Mar 29, 2022, 12:08:49 PM|INFO|KernelRestarter: restarting kernel \(1/5), keep random ports|
|Mar 29, 2022, 12:08:47 PM|WARNING|Please file an issue with this message and more detail about how you encountered it at https://github\.com/Z3Prover/z3/issues/new|
|Mar 29, 2022, 12:08:47 PM|WARNING|Z3 4\.8.15.0|
|Mar 29, 2022, 12:08:47 PM|WARNING|UNEXPECTED CODE WAS REACHED\.|
|Mar 29, 2022, 12:08:47 PM|WARNING|Line: 432|
|Mar 29, 2022, 12:08:47 PM|WARNING|File: \../src/ast/ast.cpp|
|Mar 29, 2022, 12:08:47 PM|WARNING|ASSERTION VIOLATION|
|Mar 29, 2022, 12:03:21 PM|INFO|Adapting to protocol v5\.1 for kernel 8922c419-a7e8-451f-b7e4-52f38e6b9fe8|
|Mar 29, 2022, 12:03:19 PM|INFO|Kernel started: 8922c419-a7e8-451f-b7e4-52f38e6b9fe8|
|Mar 29, 2022, 12:02:22 PM|INFO|Use Control-C to stop this server and shut down all kernels \(twice to skip confirmation).|
|Mar 29, 2022, 12:02:22 PM|INFO|http://172\.28.0.12:9000/|
|Mar 29, 2022, 12:02:22 PM|INFO|The Jupyter Notebook is running at:|
|Mar 29, 2022, 12:02:22 PM|INFO|0 active kernels|
|Mar 29, 2022, 12:02:22 PM|INFO|Serving notebooks from local directory: /|
|Mar 29, 2022, 12:02:22 PM|INFO|google\.colab serverextension initialized.|
|Mar 29, 2022, 12:02:22 PM|WARNING|    	/root/\.jupyter/jupyter_notebook_config.json|
|Mar 29, 2022, 12:02:22 PM|WARNING|    	/root/\.local/etc/jupyter/jupyter_notebook_config.json|
|Mar 29, 2022, 12:02:22 PM|WARNING|    	/usr/etc/jupyter/jupyter\_notebook_config.json|
|Mar 29, 2022, 12:02:22 PM|WARNING|    	/usr/local/etc/jupyter/jupyter\_notebook_config.json|
|Mar 29, 2022, 12:02:22 PM|WARNING|    	/usr/local/etc/jupyter/jupyter\_notebook_config.d/panel-client-jupyter.json|
|Mar 29, 2022, 12:02:22 PM|WARNING|    	/etc/jupyter/jupyter\_notebook_config.json|
|Mar 29, 2022, 12:02:22 PM|INFO|Writing notebook server cookie secret to /root/\.local/share/jupyter/runtime/notebook_cookie_secret|
|Mar 29, 2022, 12:02:22 PM|WARNING|  FutureWarning\)|
|Mar 29, 2022, 12:02:22 PM|WARNING|/usr/local/lib/python3\.7/dist-packages/traitlets/traitlets.py:2205: FutureWarning: Supporting extra quotes around strings is deprecated in traitlets 5.0. You can use '/content' instead of '"/content"' if you require traitlets >=5.|
|Mar 29, 2022, 12:02:22 PM|WARNING|  FutureWarning\)|
|Mar 29, 2022, 12:02:22 PM|WARNING|/usr/local/lib/python3\.7/dist-packages/traitlets/traitlets.py:2205: FutureWarning: Supporting extra quotes around strings is deprecated in traitlets 5.0. You can use '/' instead of '"/"' if you require traitlets >=5.|
|Mar 29, 2022, 12:02:22 PM|WARNING|  FutureWarning\)|
|Mar 29, 2022, 12:02:22 PM|WARNING|/usr/local/lib/python3\.7/dist-packages/traitlets/traitlets.py:2205: FutureWarning: Supporting extra quotes around strings is deprecated in traitlets 5.0. You can use '172.28.0.12' instead of '"172.28.0.12"' if you require traitlets >=5.|
|Mar 29, 2022, 12:02:22 PM|INFO|Use Control-C to stop this server and shut down all kernels \(twice to skip confirmation).|
|Mar 29, 2022, 12:02:22 PM|INFO|http://172\.28.0.2:9000/|
|Mar 29, 2022, 12:02:22 PM|INFO|The Jupyter Notebook is running at:|
|Mar 29, 2022, 12:02:22 PM|INFO|0 active kernels|
|Mar 29, 2022, 12:02:22 PM|INFO|Serving notebooks from local directory: /|
|Mar 29, 2022, 12:02:22 PM|INFO|google\.colab serverextension initialized.|
|Mar 29, 2022, 12:02:22 PM|WARNING|    	/root/\.jupyter/jupyter_notebook_config.json|
|Mar 29, 2022, 12:02:22 PM|WARNING|    	/root/\.local/etc/jupyter/jupyter_notebook_config.json|
|Mar 29, 2022, 12:02:22 PM|WARNING|    	/usr/etc/jupyter/jupyter\_notebook_config.json|
|Mar 29, 2022, 12:02:22 PM|WARNING|    	/usr/local/etc/jupyter/jupyter\_notebook_config.json|
|Mar 29, 2022, 12:02:22 PM|WARNING|    	/usr/local/etc/jupyter/jupyter\_notebook_config.d/panel-client-jupyter.json|
|Mar 29, 2022, 12:02:22 PM|WARNING|    	/etc/jupyter/jupyter\_notebook_config.json|
|Mar 29, 2022, 12:02:22 PM|INFO|Writing notebook server cookie secret to /root/\.local/share/jupyter/runtime/notebook_cookie_secret|
|Mar 29, 2022, 12:02:22 PM|WARNING|  FutureWarning\)|
|Mar 29, 2022, 12:02:22 PM|WARNING|/usr/local/lib/python3\.7/dist-packages/traitlets/traitlets.py:2205: FutureWarning: Supporting extra quotes around strings is deprecated in traitlets 5.0. You can use '/content' instead of '"/content"' if you require traitlets >=5.|
|Mar 29, 2022, 12:02:22 PM|WARNING|  FutureWarning\)|
|Mar 29, 2022, 12:02:22 PM|WARNING|/usr/local/lib/python3\.7/dist-packages/traitlets/traitlets.py:2205: FutureWarning: Supporting extra quotes around strings is deprecated in traitlets 5.0. You can use '/' instead of '"/"' if you require traitlets >=5.|
|Mar 29, 2022, 12:02:22 PM|WARNING|  FutureWarning\)|
|Mar 29, 2022, 12:02:22 PM|WARNING|/usr/local/lib/python3\.7/dist-packages/traitlets/traitlets.py:2205: FutureWarning: Supporting extra quotes around strings is deprecated in traitlets 5.0. You can use '172.28.0.2' instead of '"172.28.0.2"' if you require traitlets >=5.|

**Comment by NikolajBjorner** [comment]
You likely have incompatible versions side by side.

pip uninstall z3-solver
pip install z3-solver
