### ISSUE TITLE
solver.check becomes slower when using in omp parallel for

### ISSUE THREAD

**Issue by Co1lin** [Z3Prover/z3#5936]
Hi! I encountered a performance degradation when using z3 solver inside a OMP paralleled for loop.

My project uses multi-threading to speed up loops, and in each thread there's a context and a solver created on this context. I find that the performance significantly degraded when enabling OMP parallelization. I tried something like `z3::set_param("parallel.enable", true);` but it didn't work.

Here's my minimal example to reproduce the problem:

```cpp
#include <iostream>
#include <vector>
#include <chrono>
#include <omp.h>
#include "z3++.h"
using namespace std;
using namespace z3;

void read_and_solve(const std::string& file_path) {
    context c;
    auto exprs = c.parse_file(file_path.c_str());
    solver s(c);
    s.add(exprs);
//    cout << s.to_smt2() << endl;
    auto start_verify = std::chrono::high_resolution_clock::now();
    s.check();
    auto end_verify = std::chrono::high_resolution_clock::now();
    auto duration_verify = std::chrono::duration_cast<std::chrono::milliseconds>(end_verify - start_verify).count();
    std::cout << "-- end solver checking in " << duration_verify << " ms" << std::endl;
}

int main() {

    z3::set_param("parallel.enable", true);
    z3::set_param("parallel.threads.max", 16);

#pragma omp parallel for default(none)
    for (int i = 0; i < 100; i++) {
        read_and_solve("test.txt");
    }

    return 0;
}

```

Run in shell after compilation:

```shell
$ OMP_NUM_THREADS=1 ./cmake-build-debug/parallel_playground
-- end solver checking in 8 ms
-- end solver checking in 6 ms
-- end solver checking in 7 ms
-- end solver checking in 7 ms
...

$ OMP_NUM_THREADS=8 ./cmake-build-debug/parallel_playground
-- end solver checking in 108 ms  # SLOWER!
-- end solver checking in 112 ms
-- end solver checking in 114 ms
-- end solver checking in 121 ms
-- end solver checking in 121 ms
```

Content in `test.txt`:

```txt
;
(set-info :status unknown)
(declare-fun sin_1 () Real)
(declare-fun cos_1 () Real)
(declare-fun sin_0 () Real)
(declare-fun cos_0 () Real)
(declare-fun i_7 () Real)
(declare-fun r_7 () Real)
(declare-fun i_6 () Real)
(declare-fun r_6 () Real)
(declare-fun i_5 () Real)
(declare-fun r_5 () Real)
(declare-fun i_4 () Real)
(declare-fun r_4 () Real)
(declare-fun i_3 () Real)
(declare-fun r_3 () Real)
(declare-fun i_2 () Real)
(declare-fun r_2 () Real)
(declare-fun i_1 () Real)
(declare-fun r_1 () Real)
(declare-fun i_0 () Real)
(declare-fun r_0 () Real)
(assert
 (let (($x69 (= (+ (* cos_1 cos_1) (* sin_1 sin_1)) 1.0)))
 (let (($x70 (and (and true (= (+ (* cos_0 cos_0) (* sin_0 sin_0)) 1.0)) $x69)))
 (let ((?x52 (* i_7 i_7)))
 (let ((?x50 (* r_7 r_7)))
 (let ((?x46 (* i_6 i_6)))
 (let ((?x44 (* r_6 r_6)))
 (let ((?x40 (* i_5 i_5)))
 (let ((?x38 (* r_5 r_5)))
 (let ((?x34 (* i_4 i_4)))
 (let ((?x32 (* r_4 r_4)))
 (let ((?x28 (* i_3 i_3)))
 (let ((?x26 (* r_3 r_3)))
 (let ((?x22 (* i_2 i_2)))
 (let ((?x20 (* r_2 r_2)))
 (let ((?x16 (* i_1 i_1)))
 (let ((?x17 (+ (+ (+ (+ 0.0 (* r_0 r_0)) (* i_0 i_0)) (* r_1 r_1)) ?x16)))
 (let ((?x39 (+ (+ (+ (+ (+ (+ (+ ?x17 ?x20) ?x22) ?x26) ?x28) ?x32) ?x34) ?x38)))
 (let (($x55 (= (+ (+ (+ (+ (+ ?x39 ?x40) ?x44) ?x46) ?x50) ?x52) 1.0)))
 (and (and true $x55) $x70))))))))))))))))))))
(assert
 (let (($x311 (and (and (and (and (and true true) true) true) true) true)))
 (let (($x314 (and (and (and $x311 true) true) true)))
 (not $x314))))
(check-sat)
```

My environment:

```
Z3 version 4.8.16 - 64 bit
Apple clang version 13.0.0 (clang-1300.0.29.3)
Target: x86_64-apple-darwin21.4.0
CPU: 2.3 GHz 8-Core Intel Core i9
```

**Comment by Co1lin** [comment]
I just find that locking mechanism will bring such significant performance degradation. Multi-threaded operations such as `sum += i` with a lock takes more time when we use more threads, and the relationship between them can be linear. So I guess there are some lock in z3-solver that lead to this.

**Comment by NikolajBjorner** [comment]
You must be thrashing your cores.
parallel.enable uses a different strategy that can be high overhead.

**Comment by Co1lin** [comment]
@NikolajBjorner Thanks for your tips. I tried some other configurations, and got the results below.

First, I replaced the `c.parse_file` with a hard encoded equation to avoid potential I/O overhead when reading from file.

Then, I tried to remove `z3::set_param("parallel.enable", true);` .

When running with `OMP_NUM_THREADS=1` , each check operation takes 3 ms.

When running with `OMP_NUM_THREADS=32` and setting `parallel.enable` to be `true` , on a 128-core Linux server, each operation takes about 200 ms on average.

When running with `OMP_NUM_THREADS=32` and **setting `parallel.enable` to be `false`**, on the same 128-core Linux server, the fluctuation occurs. Some operations take about 6 ms, some take about 200 ms, and a majority of operations take 40~80 ms. This time there are enough physical cores, so I think the cores are not thrashed. But the performance still degrades, though better than when `parallel.enable=true`. So I think there are still some problems.

I wonder if it is the right way to invoke z3-solver in C++ with multi-threading?

**Comment by NikolajBjorner** [comment]
parallel.enable=true makes z3 do something completely different. You can't compare runtimes.

**Comment by Co1lin** [comment]
So... How about those 40-80 ms operations when setting parallel.enable=false ? Why can't they achieve the same performance as single thread version which is 3 ms ?

**Comment by Co1lin** [comment]
What's more, I also test the same equation in Python. I use multi-processing (32 processes) in Python, and each operation takes 6 ~ 13 ms (compared to stable 6 ms when using `mp.Pool(1)`) , which is way better than the cost in C++ multi-threading.

```python
import z3
import time
import multiprocessing as mp

def work(p=None):
    start = time.monotonic_ns()

    x = z3.Bool("x")
    y = z3.Bool("y")

    conj = z3.Not(z3.And(x, y)) == z3.Or(z3.Not(x), z3.Not(y))
    solver = z3.Solver()
    solver.add(z3.Not(conj))
    res = solver.check()

    end = time.monotonic_ns();
    print(f'time cost: { (end-start) / 1e6 } ms')
    assert(res == z3.unsat)
    return res

def main():
    with mp.Pool(32) as p:
        p.map(loop_work, [None for i in range(10000)])

if __name__ == '__main__':
    main()
```

Run in shell:

```shell
$ python mp.py
time cost: 6.557288 ms
time cost: 6.944907 ms
time cost: 13.153128 ms
time cost: 6.232077 ms
time cost: 7.186526 ms
time cost: 13.325555 ms
...
```

The difference between the performance under C++ multi-threading and Python multi-processing makes me wonder if there's any "conflict" when multi-threading. It seems like z3 has some shared objects or locks which make it worse in multi-threading, while in multi-processing the memory is not shared so z3 has better performance.

**Comment by NikolajBjorner** [comment]
There are conflicts, especially during parsing and initialization. So, if each thread starts parsing and this is a non-trivial part of the computation there can be conflicts. You should use a profiler and you can see what is happening. It is easier to profile a C++ application to avoid mixed-mode hoops. I have in the past tuned a little for contention during initialization and parsing, but it going to be inherent. Contention during solving is possible when the benchmarks use arithmetic (large constants).

If you are into this kind of profiling the recommendation is that you go beyond a single instance and profile instances that correspond to what benefits from parallelization. The small instances can be run in separate processes.

**Comment by Co1lin** [comment]
Hi! I did a simple profiling by `perf` , and observed that as the number of threads increases, some spinlock takes more and more overhead. What might be the possible reason?

```shell
# 4-thread
 # Overhead  Command  Shared Object        Symbol              
    14.91%  test2    libpthread-2.33.so   [.] __pthread_mutex_lock
    10.47%  test2    libc-2.33.so         [.] __strcmp_avx2
     6.20%  test2    libc-2.33.so         [.] malloc
     5.98%  test2    libz3.so             [.] ast_manager::ast_manager
     5.95%  test2    libz3.so             [.] ast_manager::ast_manager
     4.71%  test2    libpthread-2.33.so   [.] __pthread_mutex_unlock_usercnt
     4.14%  test2    libz3.so             [.] params_ref::get_bool
     3.92%  test2    libz3.so             [.] string_hash
     3.16%  test2    libc-2.33.so         [.] _int_free
     3.15%  test2    libz3.so             [.] symbol::symbol
     2.65%  test2    [kernel.kallsyms]    [k] native_queued_spin_lock_slowpath

# 64-thread

   85.66%  test2    [kernel.kallsyms]    [k] native_queued_spin_lock_slowpath
     1.72%  test2    [kernel.kallsyms]    [k] futex_wait_setup
     1.48%  test2    [kernel.kallsyms]    [k] futex_wake
     1.42%  test2    libpthread-2.33.so   [.] __pthread_mutex_lock
     1.40%  test2    [kernel.kallsyms]    [k] _raw_spin_lock
     0.53%  test2    libc-2.33.so         [.] __strcmp_avx2
     0.41%  test2    libpthread-2.33.so   [.] __pthread_mutex_unlock_usercnt
     0.37%  test2    libc-2.33.so         [.] malloc
     0.37%  test2    libz3.so             [.] ast_manager::ast_manager
     0.37%  test2    libz3.so             [.] params_ref::get_bool
     0.37%  test2    libz3.so             [.] ast_manager::ast_manager

```

Program:

```cpp
#include <iostream>
#include <vector>
#include <chrono>
#include <omp.h>
#include "z3++.h"
using namespace std;
using namespace z3;

void read_and_solve(const std::string& file_path) {
    context c;
    expr x = c.bool_const("x");
    expr y = c.bool_const("y");
    expr conjecture = !(x && y) == (!x || !y);
    solver s(c);
    s.add(!conjecture);
    auto start_verify = std::chrono::high_resolution_clock::now();
    s.check();
    auto end_verify = std::chrono::high_resolution_clock::now();
    auto duration_verify = std::chrono::duration_cast<std::chrono::milliseconds>(end_verify - start_verify).count();
    std::cout << "-- end solver checking in " << duration_verify << " ms" << std::endl;
}

int main() {
#pragma omp parallel for default(none)
    for (int i = 0; i < 1000; i++) {
        read_and_solve("");
    }
    return 0;
}
```

**Comment by NikolajBjorner** [comment]
likely use unique symbols (for parameters). You get more information by enabling a deeper stack.
The visual studio profiler does this very well. Not sure about your profiler.

Removing symbols from parameters is a possible remedy for this particular bottleneck.
Still, it could only be measuring a startup cost and not for overhead of solving longer running instances.

**Comment by Co1lin** [comment]
Hi! I profiled the code above using Intel vtune, and find the potential bottleneck.

As you can see from the flame graph below, function [`get_module`](https://github.com/Z3Prover/z3/blob/43f76368268ea14f19cd187c6999ed2cc475f332/src/util/gparams.cpp#L464) which uses a lock takes the major amount of time. The call stack shows that this function is called by `solver.check()` .

I am not familiar with the source code of z3 lib, so I have these questions. Why there are a global lock although I create independent contexts and solvers in each thread? What does this function do? Is there any method to fix this, or to avoid this? How can I get rid of this lock so as to achieve real parallelization? Looking forward to your attention, thanks!

<img width="1557" alt="Screen Shot 2022-04-07 at 14 55 48" src="https://user-images.githubusercontent.com/17642707/162140424-2e008788-cf1b-4948-baea-0fc677053bcd.png">

**Comment by NikolajBjorner** [comment]
The contention you see is because identifiers used for parameters are unique symbols (atoms). The hash-table for these symbols is global. 
https://github.com/Z3Prover/z3/blob/master/src/util/symbol.h

The parameters are defined here

https://github.com/Z3Prover/z3/blob/master/src/util/gparams.h
https://github.com/Z3Prover/z3/blob/master/src/util/params.h

You can see that they use symbols for keys (and in some cases values) https://github.com/Z3Prover/z3/blob/19531654227522416cd37d48e7407d1ae055ec4b/src/util/params.h#L52

There are some interactions with symbols used for identifying theories (family names)
https://github.com/Z3Prover/z3/blob/19531654227522416cd37d48e7407d1ae055ec4b/src/ast/ast.h#L1563

One possible way to avoid contention is to not use symbols for parameters and family names and instead use std::string.
The change is conceptually simple, but practically will take time and involve many modules and old assumptions (symbols are exposed over the API and tied to parameters, so the layer that sits between the implementation and API would translate back and forth).

Another possible way to avoid contention is to change the symbol class to avoid the hash-table for symbols of small size (128 bits) and just use string comparison. Then symbols are not unique, but take twice as much space. Using 64 bits is maybe possible, but a good encoding should use compression to the printable character range because otherwise it may not be able to represent symbols of a reasonable size (larger than 5-6 characters). 
This kind of re-coding of the symbol data-structure would need to also be compatible with how Z3_symbol is exposed over the API.

**Comment by Co1lin** [comment]
I see. So currently all of the contexts share the same symbol table for parameters like `bool_const` , and it's impossible to avoid this contention unless we change the internal implementation of z3, right?
