### ISSUE TITLE
Does Z3 supports String sort.

### ISSUE THREAD

**Issue by sureshgl** [Z3Prover/z3#594]
I am  experimenting the formal verification using Z3.
At present I am using Z3 4.4.1 version, and for me String theorem and List theorem are in the must list.

Z3 4.2 version is having String Theorem ( via Z3Str2) and not having the List theorem

Z3 4.4.1 is not having String Theorem and having List Theorem.  Looking inside the code , it appears that String Theorem is considered and for some reasons made it only "internal". 

Request you to let me know, how I can have  String Theorem in Z3 4.4.1 version.

Would like to know of a way that I can have both the "List" and "String"  sorts in any Z3 version.

**Comment by NikolajBjorner** [comment]
4.4.2 does have lists. 
Example:


      (declare-const l (List Int))
      (declare-const k (List Int))
      (assert (= (tail l) (insert 1 k)))
      (assert (not (= l nil)))
      (check-sat)

It is syntactic sugar for an algebraic data-type. 
Strings and sequence theories are very new features and are not be available in previous versions.
(get-model)

**Comment by sureshgl** [comment]
Thank you for your response, request you to consider that my issue is not addressed.

Please note that  the issue is 4.4.2 ( latest ) is not having String Sort exposed.

I am not able to run the following statements on Z3 ( 4.4.1 )

(declare-const a String)
(declare-const b String)
(assert (= (str.++ b a) (str.++ "abc" b)))
(check-sat)
(get-model)

>> z3 --version
Z3 version 4.4.1

>> z3 -in
(declare-const a String)
(error "line 1 column 18: unknown sort 'String'")

I am referring to the tutorial mentioned here [http://rise4fun.com/Z3/tutorial/sequences](Sequences). I guess that this tutorial is based on 4.2 version of Z3.

my ask is , how we can access the strings sort in 4.4.1, How can I run the above example on Z3 ( 4.4.1)

**Comment by wintersteiger** [comment]
4.4.1 does not have support for strings. Do you have a specific requirement for 4.4.1 that prevents you from using 4.4.2?

**Comment by wintersteiger** [comment]
Ah! Version confusion going on: @sureshgl is using Z3 4.1.1 + Z3Str2 and not Z3 4.4.1/2. 

Z3Str2 is based on Z3 4.1.1 (and may work with 4.2) but does not work with Z3 4.4.x yet; this is currently being implemented with the aim of getting full integration sometime in the near future. In the meanwhile, Z3 4.4.2 has been extended with it's own String sort, but we expect that to converge eventually.

I don't know by heart whether Z3 4.1.1 has Lists, but I would expect so, as they have been around for a long time. @NikolajBjorner: Does Z3 4.1.1 have Lists or can @sureshgl use the datatypes for that?

**Comment by NikolajBjorner** [comment]
If all else fails, use data-types for lists. It is just syntactic sugar. I can't speak to what old versions of Z3 do and cannot do and generally have to limit bw to current version. You can use strings natively in newer versions of Z3 using an implementation I put in since February. See http://rise4fun.com/z3/tutorial/sequences for syntax and examples. You may be able to use Z3str2 using newer versions of the code base, but I don't know the answers.

**Comment by sureshgl** [comment]
Thank you very much for your inputs. 
Another Z3 expert replied to my query, confirming that Z3 version 4.1.1 is supporting both the Lists and Strings. I also have verified the same. Don't know what stupid mistake I did, it did not work for me initially.

Thanks again for all your replies.
====== following is the msg cut & paste from my mail ===============
Hi Suresh,

Thanks for the message.

Currently Z3str2 works with Z3 4.1.1 but we are indeed working on the porting to make it work with latest Z3.

Re the list theory, it seems there are some supports in Z3 4.1.1. For example, the following constraint is from in the section of "Recursive datatypes" @ http://rise4fun.com/Z3/tutorial/guide

---
(declare-const l1 (List Int))
(declare-const l2 (List Int))
(declare-const l3 (List Int))
(declare-const x Int)
(assert (not (= l1 nil)))
(assert (not (= l2 nil)))
(assert (= (head l1) (head l2)))
(assert (not (= l1 l2)))
(assert (= l3 (insert x l2)))
(assert (> x 100))
(check-sat)
(get-model)
---

And the response from Z3str2

---
* v-ok
************************
>> SAT
------------------------
l3 : List -> (insert 101 (insert 0 (insert 1 nil)))
x : int -> 101
l1 : List -> (insert 0 nil)
l2 : List -> (insert 0 (insert 1 nil))
************************
>> etime(s) = 0.012838
---

Hope this helps. 

Thanks!
-Yunhui
