### ISSUE TITLE
ast_manager LEAKED for a simple instance

### ISSUE THREAD

**Issue by merlinsun** [Z3Prover/z3#5940]
Hi, 
For this simple instance, z3 https://github.com/Z3Prover/z3/commit/25feb0ebedbddb9c512d86243b292dfc02238af3 (debug build) occurs `ast_manager LEAKED`.
```
$ z3debug delta.smt2
(error "line 2 column 30: Sort mismatch at argument #1 for function (declare-fun xor (Bool Bool) Bool) supplied sort is Int")
ast_manager LEAKED: 5
Leaked: (xor false false)
id: 25
$ cat delta.smt2
(declare-fun b (Int) Int)
(assert (xor (b 1) false false))
```

**Comment by NikolajBjorner** [comment]
given that this is a warning that is triggered on bad input it is not a priority to fix
