### ISSUE TITLE
(rewriter.eq2ineq,nlsat.shuffle_vars) Refutational soundness issue on QF_NRA

### ISSUE THREAD

**Issue by KJongUk** [Z3Prover/z3#5945]
Hi, For this formula
<pre>
<code>
(declare-fun sk () Real)
(declare-fun k () Real)
(declare-fun X () Real)
(declare-fun s () Real)
(declare-fun p () Real)
(assert (< 0.0 sk))
(assert (and (or (= s 0.0) (= (/ 0.0 p) (/ sk (* k (- sk 5))))) 
            (= X (* sk sk)) 
            (= 1.0 (* sk k)) (= 2 X)))
(check-sat)
</code>
</pre>

z3(v-4.8.14) returns sat. But when nlsat.shffle_vars, rewrite.eq2ineq options are given, z3 returns unsat.

**Comment by NikolajBjorner** [comment]
duplicate
