### ISSUE TITLE
Python API: push makes model incomplete for boolean expressions

### ISSUE THREAD

**Issue by jonsim** [Z3Prover/z3#5954]
It looks like all BoolRef interpretations that are False are silently dropped from the model when push() is called on the Solver:

```
>>> from z3 import *
>>> a, b, c = Bools('a b c')
>>> s = Solver()
>>> s.add(Or(a, b, c))
>>> s.check()
sat
>>> s.model()
[b = False, a = True, c = False]
>>> s.push()
>>> s.check()
sat
>>> s.model()
[a = True]
```

I notice passing assumptions to check() exhibits similar behavior:

```
>>> from z3 import *
>>> a, b, c = Bools('a b c')
>>> s = Solver()
>>> s.add(Or(a, b, c))
>>> s.check()
sat
>>> s.model()
[b = False, a = True, c = False]
>>> s.check(b)
sat
>>> s.model()
[b = True]
>>> s.check(Not(a))
sat
>>> s.model()
[b = True, a = False]
```

In all cases I'd consider the output model to be incomplete - to my mind it should contain an entry for every variable in the input expression.

A quick play with Int types suggests they don't suffer from this problem - although I still see that calling push changes the ordering of the terms in the model. Not technically incorrect (as far as I can tell it makes no guarantee that the ordering is stable), but still slightly confusing:

```
>>> from z3 import *
>>> x, y = Ints('x y')
>>> s = Solver()
>>> s.add(x > 1, y < 1)
>>> s.check()
sat
>>> s.model()
[y = 0, x = 2]
>>> s.push()
>>> s.check()
sat
>>> s.model()
[x = 2, y = 0]
```

**Comment by NikolajBjorner** [comment]
It's a don't care - b can be True or False in the model where it is not mentioned.
You can evaluate b with model_completion=True ( call s.model().eval(b, model_compeltion=True) )

**Comment by jonsim** [comment]
Thanks for the very quick response! Okay, that's a satisfactory workaround for me - I can extract all the terms from the solver's input assertions and evaluate the model for each of them. Thanks again.
