### ISSUE TITLE
Slower runtime with multi-threading

### ISSUE THREAD

**Issue by mik226** [Z3Prover/z3#5955]
Hello,

I have checked the z3 (4.8.15) runtime with and without multi-threading but the run with multi-threading is a bit slower. Is this expected? (35min with a single thread, 44min with 4 threads)

I have attached the input (smt2) file which I used. Also, I used the options below to check the runtime.

Options: parallel.enable=true parallel.threads.max=4

[test.zip](https://github.com/Z3Prover/z3/files/8446643/test.zip)

**Comment by NikolajBjorner** [comment]
it depends
