### ISSUE TITLE
Are there any plans to include Z3 in .NET 6.0?

### ISSUE THREAD

**Issue by Sage-King** [Z3Prover/z3#5968]
I'm currently migrating a project to .NET 6.0 and Z3 doesn't seem to have a 6.0 version. Are there plans to migrate Z3 to .NET 6.0? If not, do you have any alternatives I can use for my migration?

**Comment by ptr1120** [comment]
Hello, .net is backwards compatible. I also use z3 from an app that targets net6 without problems.

**Comment by NikolajBjorner** [comment]
The nuget package is for .net core and platform so they can be consumed by up-level .Net.
