### ISSUE TITLE
Failed installation

### ISSUE THREAD

**Issue by fffarina** [Z3Prover/z3#5984]
Can't install the repository via pip, following error message prompted:

Installing collected packages: z3-solver
  Running setup.py install for z3-solver ... error
  error: subprocess-exited-with-error
  
  × Running setup.py install for z3-solver did not run successfully.
  │ exit code: 1
  ╰─> [4 lines of output]
      running install
      running build
      Configuring Z3
      error: [Errno 2] No such file or directory: 'cmake'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> z3-solver

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.

**Comment by NikolajBjorner** [comment]
Are you using M1/M2?

If I understand, it uses cmake to build z3 as the platform you are using isn't already available in binary form.
There is a recent fix - https://github.com/Z3Prover/z3/pull/5972
it adds cmake as a dependency when this build step is needed.

The fix hasn't propagated to pypi. 
You can install cmake using pip for now.

**Comment by fffarina** [comment]
It worked! Thanks for the help.
