### ISSUE TITLE
vc with rlimit taking too much time

### ISSUE THREAD

**Issue by kanigsson** [Z3Prover/z3#599]
Hello,

I have spent some time looking at the rlimit option. Overall it seems to work very well. On the vast majority of our VCs, we found that z3 consumes hundreds of thousands of rlimit units (steps) in less than a second.

But on the file [rlimit.smt2](https://gist.github.com/kanigsson/5e579a7a2701f6a8aa41ca400ce5f626), z3 consumes much less steps, so that even after running for 30 seconds, it only has consumed 100000 steps. As a consequence, z3 will run for a very long time on this VC with an rlimit that only lasts a second on other VCs.

 $ z3 -st -T:30 rlimit.smt2
timeout
(:max-memory   14.37
 :memory       11.41
 :num-allocs   192107538686.00
 :rlimit-count 102154
 :time         29.99
 :total-time   29.99)

So I suspect that the rlimit is not counted in some part of Z3 that consumes a lot of CPU time in this VC.

Note that we don't really care about the exact count of rlimit steps, or it's equivalence in time.

Thanks in advance

Johannes

**Comment by NikolajBjorner** [comment]
Yes, it spends a lot of time in Grobner basis computation. I will add limit checks there.

**Comment by NikolajBjorner** [comment]
It should be fixed now

**Comment by kanigsson** [comment]
Fix confirmed. Thank you! I will check if I can find other such cases.
