### ISSUE TITLE
time-consuming for smt solver

### ISSUE THREAD

**Issue by bodycoder101** [Z3Prover/z3#5991]
I have a smt problem solving , but very time consuming, after debug z3 source code; Surprised to find that in the code program could not jump out in context::bounded_search; 
So NikolajBjorner, Can you help me with that? @NikolajBjorner 
for explaining  the principles for bounded   search。

```c++
lbool context::bounded_search() {
        unsigned counter = 0;

        TRACE("bounded_search", tout << "starting bounded search...\n";);

        while (true) {
            while (!propagate()) {
                TRACE_CODE({
                    static bool first_propagate = true;
                    if (first_propagate) {
                        first_propagate = false;
                        TRACE("after_first_propagate", display(tout););
                    }
                });
```

**Comment by bodycoder101** [comment]
Looking forward to your reply，thank you very much~ @NikolajBjorner

**Comment by NikolajBjorner** [comment]
There is not enough information in your report to say anything actionable. 
What are the consequences being propagated? 
What kind of input triggers this (could happen if quantifiers, that are given weight 0, are instantiated eagerly).

**Comment by bodycoder101** [comment]
Our team is using SMACK to validate the company's large-scale code, but during the validation process we found that many validation units timed out and even exceeded the 8-hour validation time.

The bottom layer of the SMACK uses the corral and z3 solvers. Therefore, we want to explore which part causes the timeout. We trace the code and find that the smt solution process in the z3 solver is time-consuming. The code point is located in bounded search. Therefore, I would like to ask what the problem is solved by this code and why the search is performed multiple times.

Timeout SMT2-file can't be shared yet, I have to ask the company's permission first.

Thanks again for your reply~   @NikolajBjorner

**Comment by NikolajBjorner** [comment]
Sounds like a standard quantifier instantiation issue. You can try the "axiom profiler" to get an idea of what happens during search

**Comment by bodycoder101** [comment]
Do you have any recommended tools for "axiom profiler" ？

**Comment by NikolajBjorner** [comment]
https://github.com/viperproject/axiom-profiler

**Comment by bodycoder101** [comment]
thanks your reply，give guide to solve this problem ~ @NikolajBjorner
