### ISSUE TITLE
z3-wasm hangs browser on sat error

### ISSUE THREAD

**Issue by ViRb3** [Z3Prover/z3#5995]
I built a simple static page which allows you to run SMT2 queries using the official z3-wasm build and bindings. The page can be found here: https://virb3.github.io/z3-wasm/. All the build steps are completely automated and reproducible, check out all branches in https://github.com/ViRb3/z3-wasm. 

So, if you run the default expression, or anything else which has a solution, everything works fine:

```
(declare-fun x () Int)
(declare-fun y () Int)
(declare-fun z () Int)
(assert (>= (* 2 x) (+ y z)))
(declare-fun f (Int) Int)
(declare-fun g (Int Int) Int)
(assert (< (f x) (g x x)))
(assert (> (f y) (g x x)))
(check-sat)
(get-model)
(exit)
```

Result:

```
sat
(
  (define-fun z () Int
    1)
  (define-fun x () Int
    2)
  (define-fun y () Int
    3)
  (define-fun g ((x!0 Int) (x!1 Int)) Int
    0)
  (define-fun f ((x!0 Int)) Int
    (ite (= x!0 3) 1
      (- 1)))
)

-- Verification complete (518ms)
```

But if you use an expression which has an error, for example:
```
(simplify)
```

The browser hangs, and we get:

![Screen Shot 2022-04-24 at 02 50 25](https://user-images.githubusercontent.com/2650170/164952315-1763e35b-9e64-40a5-be74-ff5593c4da44.png)

An unofficial build of z3.wasm does not have this problem: https://people.csail.mit.edu/cpitcla/z3.wasm/z3.html

The Emscripten build options vastly differ between [the unofficial build](https://github.com/cpitclaudel/z3.wasm/blob/master/z3.sh) and the [official build](https://github.com/Z3Prover/z3/blob/master/src/api/js/build-wasm.sh). Maybe the problem lies within?

@bakkot pinging you since you worked on this implementation.

Many thanks!

**Comment by bakkot** [comment]
I suspect this has to do with how you're building things. I'm not so familiar with webpack, but it works fine with esbuild. E.g. [here is a trivial demo](https://github.com/bakkot/simple-z3-demo). Webpack is presumably messing up which thread is considered the main thread somehow?

(The unofficial build you link is completely broken: anything which requires threads won't work, which means anything which requires timers, including many solvers.)

**Comment by bakkot** [comment]
OK, an attempt to fix: https://github.com/Z3Prover/z3/pull/5996

**Comment by ViRb3** [comment]
The fix works great, thank you so much!

**Comment by ViRb3** [comment]
@bakkot can you please publish a new release of the npm package? Would save people having to build themselves.

**Comment by NikolajBjorner** [comment]
... "can you please publish a new release of"....
which points to that we haven't set up automatic npm publication through the action that prepares releases.

I looked at it shortly and determined it would take a little context switch and overhead to just publish a package manually; setting up the automatic pipeline is a must and make it a priority, but it will have to be when I have help by late June.
(we need to ensure npm is set up with an access token linked to Azure pipelines and I have the right script in release.yml to push the package similar to pypi).

**Comment by bakkot** [comment]
@NikolajBjorner I can also make it so that a release is triggered whenever you create a [release on GitHub](https://github.com/Z3Prover/z3/releases), if you would prefer. It's a one-line change to the [existing manual action](https://github.com/Z3Prover/z3/blob/master/.github/workflows/wasm-release.yml), which should already have all the right permissions (you can try it by [manually running it](https://docs.github.com/en/actions/managing-workflow-runs/manually-running-a-workflow)).

**Comment by NikolajBjorner** [comment]
doh, I forgot about the manual action.
One line change is good - I forget moving parts
