### ISSUE TITLE
smtfd returning sat (with empty model) but smt returning unsat - bug?

### ISSUE THREAD

**Issue by SamPruden** [Z3Prover/z3#6002]
I have some `Goal` that returns `sat` with the `smtfd` tactic, and `unsat` with `smt`. This seems like a Z3 bug to me, but perhaps there's something that I've misunderstood. Is this expected behaviour?

I'm not posting the full repro yet because it's a long and messy Python file with a mess of dependencies, but I can look at finding a more reasonable repro if one is needed.

The solver returning `sat`:
```
solver = z3.Then(
  "simplify",
  "ackermannize_bv",
  "bit-blast",
  "occf",
  "smtfd"
).solver()
```

When this returns `sat`, the model appears to be empty.

Returning `unsat`:
```
solver = z3.Then(
  "simplify",
  "ackermannize_bv",
  "bit-blast",
  "occf",
  "smt"
).solver()
```

I've tried this on some trivial problem instances, where the `unsat` result is definitely the correct one, so `smtfd` is behaving unexpectedly. I'm only trying `smtfd` because, by trial and error, it runs incredibly fast compared to `smt`. Suspiciously fast, I guess - 3 seconds vs >1 hour. Perhaps this is expected behaviour, and I've misunderstood its purpose? Is this a bug?

**Comment by NikolajBjorner** [comment]
There is no clear information in the description on the kind of formula you use. 
smtfd applies a partial filter on types of formulas it does not apply to. It is possible to bypass it, and then get incorrect results. Do not use smtfd unless you use only finite domain formulas.

**Comment by SamPruden** [comment]
Ah. I didn't realise that tactics were allowed to give incorrect results like that. I expected I would either get an error if the tactic wasn't compatible with the goal (as happens with some others) or a result of unknown.

Due to sparse documention of tactics, all I had to go on was finding it in `describe_tactics()` and giving it a go. The help text implies that it might be doing some clever transformation into FDF, so I didn't consider that the goal already being FDF was required.

> builtin strategy for solving SMT problems by reduction to FD.

This makes things a little tricky for those of us who fall into the camp of being engineers trying to make use of Z3 without knowing all of the theory. Having a rule that all tactics should always produce a correct result, an error, or unknown would help usability considerably. As it is, this feels like Z3 is able to lie to me sometimes, which is concerning because now I need significantly deeper theoretical knowledge to know when to trust the output.

I'm happy to for this to be closed on the grounds that I was incorrect to assume that conflicting results must imply a bug. However, I would argue that this should be considered a bug. At minimum, tactics able to give incorrect results should say so in their help text.

**Comment by agurfinkel** [comment]
Hey Sam, let me jump in. You are right in general, but z3 contains many experimental features that are useful to some people but are not ready for prime time. I might be the reason for why `smtfd` tactic is still in the code base. I find the tactic useful for my research, even though it is known to be buggy (it is trusted for unsat, but might return sat incorrectly). However, such things do cause problem to new users. If you stick to well documented features, they usually work a lot better than the undocumented hidden ones.

**Comment by SamPruden** [comment]
That's fair, thanks for clarifying. I would suggest that such features should be verbosely labelled as such, though. The help text should mention that it's unstable, and maybe even print something when used in Z3py.

Perhaps I've missed something, but are there any well documented features? `describe_tactics()` seems to be about all we have. I didn't notice anything that made `smtfd` seem less documented than anything else. Do you mean documented for SMT-Lib generally rather than Z3, ie https://smtlib.cs.uiowa.edu/logics.shtml?

**Comment by agurfinkel** [comment]
When using Z3 in smt-lib compatible mode (i.e., letting z3 auto configure its settings based on the input), it should be quite robust. Every other feature usually has a specific purpose for which it is tested, but might work in other scenarios. Using such features effectively requires an in-depth knowledge of what the feature is doing. Looking at the source, commit history, and discussions helps a lot.

I will let @NikolajBjorner reply about z3-specific documentation. There are number of them on the web, I am not sure which ones are considered to be supported.
