### ISSUE TITLE
Recursive datatypes with Seq

### ISSUE THREAD

**Issue by giltho** [Z3Prover/z3#6005]
Hi @NikolajBjorner ,

First of all, thank you for talking to us on Tuesday!

As we discussed, here's a tiny example of a smt2 file that uses recursive datatypes with Seq.

```smt2
(declare-datatypes
  ((Exp 0)) ((
    (iKind (ival Int))
    (fKind (fval Real))
    (lKind (lval (Seq Exp)))
)))

(declare-fun lexp () Exp)
(declare-fun l () (Seq Exp))
(declare-fun i () Exp)
(declare-fun f () Exp)
(assert ((_ is (fKind (Real) Exp)) f))
(assert ((_ is (iKind (Int) Exp)) i))
(assert ((_ is (lKind ((Seq Int)) Exp)) lexp))
(assert (= (lval lexp) l))
(assert (= l (seq.++ (seq.unit f) (seq.unit i))))
(check-sat)
(get-model)
```

If I'm correct, I'm expecting it to be sat, with the following as a potential model:
```smt2
  (define-fun lexp () Exp
    (lKind (seq.++
      (seq.unit (fKind 2.))
      (seq.unit (iKind 2))
    )))
  
  (define-fun f Exp
    (fKind 2.))
  (define-fun i Exp
    (iKind 2))
  
  (define-fun l (Seq Exp)
    (seq.++
      (seq.unit (fKind 2.))
      (seq.unit (iKind 2))
    ))
    
```

I am not 100% sure of my smt2 syntax, so here's the corresponding idea transcribed in simple OCaml 
```ml
(* Problem definition: *)

type exp =
  | IKind of { ival: int }
  | FKind of { fval: float }
  | LKind of { lval: exp list }
  
let is_list e =
  match e with
  | LKind _ -> true
  | _ -> false
  
let is_int e =
  match e with
  | IKind _ -> true
  | _ -> false
  
let is_float e =
  match e with
  | FKind _ -> true
  | _ -> false
  
let assertion (lexp: exp) (l: exp list) (f: exp) (i: exp) =
  assert (is_list lexp);
  assert (is_int i);
  assert (is_float f);
  assert (
    match lexp with
    | LKind { lval } when l = lval -> true
    | _ -> false
  );
  assert (l = [f; i])

(* Corresponding model: *)

let i = IKind { ival = 2 }
let f = FKind { fval = 2. }
let l = [ FKind { fval = 2. }; IKind { ival = 2 } ]
let lexp = LKind { lval = [ FKind { fval = 2. }; IKind { ival = 2 } ] }

```

If I can be of any help in the implementation or something else, I'd be happy to help!

**Comment by NikolajBjorner** [comment]
It was implemented and pushed Tuesday morning. Can you assemble test cases?
81d97a81af7aeaf1773d5c9569567e8b6dd8549f

**Comment by giltho** [comment]
Oh wow, I didn't even think to look if that was already done. Thank you for your efficiency!
I'm currently in the train, but I'll try to pull the latest version and build test cases

**Comment by giltho** [comment]
Do you want me to send a bunch of smt files, or should I add tests using the API directly in `src/test`?

**Comment by NikolajBjorner** [comment]
This has been open for some time. The feature is there. I fixed a bug in the implementation yesterday, so I guess it wasn't put to full test yet. One thing that isn't working is having doubly nested sequences within an algebraic datatype, but I will refrain from supporting this without a use case.
