### ISSUE TITLE
memory leaks in dotnet api (MkSolver/Solver?)

### ISSUE THREAD

**Issue by Trolldemorted** [Z3Prover/z3#6014]
This simple code block:

```c#
using Microsoft.Z3;
var z3Settings = new Dictionary<string, string> { { "model", "true" } };
while (true)
{
    using var ctx = new Context(z3Settings);
    using var solver = ctx.MkSolver();
}
```
causes a program that depends on Microsoft.Z3 (4.8.16) to gradually consume more memory, despite frequent GCs:
![grafik](https://user-images.githubusercontent.com/10261186/166329245-198b9d8d-5b4c-4785-91ce-b35a98975ae5.png)

Is there anything else that I need to call to free all used memory of a context? Adding `GC.Collect();` to the loop does not help.

**Comment by Trolldemorted** [comment]
Maybe a dup of https://github.com/Z3Prover/z3/issues/5043?

**Comment by NikolajBjorner** [comment]
Based on what I can observe it is not something under control of z3. There are no directly observable memory increases in either the managed or unmanaged allocations. This leaves more tricky options left: such as fragmentation.
There are ways to instrument VS to profile also unmanaged memory allocations but the snapshot mechanism seems not easily usable. I will have to close this as there seems nothing to do about it.
