### ISSUE TITLE
Slow solving of seq.len equations

### ISSUE THREAD

**Issue by giltho** [Z3Prover/z3#6016]
Hi!

I currently have a very simple smt2 file, which seems obviously sat, but z3 is being extremely slow there.
Here is the file 
```smt2
(declare-const t (Seq (Int)))

(assert (<= 2147483648 (seq.len t)))

(check-sat)
(get-model)
```

Supposedly, there exist a list that is long enough, even if we don't know it. But z3 seems to loop for a very long time and never spits out an answer

**Comment by NikolajBjorner** [comment]
The solver is based on building explicit solutions. It would take too much space/time to produce solutions to such bounds.
It would require a different approach (for example, pre-solving and a lazy sequence representation) to address such.
