### ISSUE TITLE
unexpected change of result with minor input change

### ISSUE THREAD

**Issue by kanigsson** [Z3Prover/z3#6017]
[timeout.smt2.txt](https://github.com/Z3Prover/z3/files/8609525/timeout.smt2.txt)
[unsat.smt2.txt](https://github.com/Z3Prover/z3/files/8609526/unsat.smt2.txt)

Dear Z3 team,

The two attached files differ minimally: the variant `timeout.smt2` introduces two extra constants. Despite this small difference, `unsat.smt2` is proved immediately, and `timeout.smt2` is not proved at all (I waited 1m30).
I can understand that extra declarations can lead to a different proof search, but here there are already lots of declarations in the same style as those two extra constants. Is there a reason for this particular behavior? I would appreciate if you could take a look. Thanks in advance.

**Comment by NikolajBjorner** [comment]
The constant ctx__split_fields2 gets solved for during pre-processing in unsat.smt2.txt, but in timeout.smt2.txt, the new definitions prevent the pre-processing module from solving for ctx__split_fields2. This is a conservative filter added to ensure simplification is sound (only eliminates constants in a well-founded way). You can replace the axiom H by a define-fun. In this way you don't depend on pre-processing to detect definitions like axiom H.

**Comment by kanigsson** [comment]
Thanks, that seems to work.
