### ISSUE TITLE
Statement and its complement both satisfyable

### ISSUE THREAD

**Issue by codesn1** [Z3Prover/z3#602]
I found that if you compare the value of bvmul with its arguments extended and the value of brmul with itself extended, the resulting formula is always satisfyable. For example:

`(= (bvmul ((_ sign_extend 7) %X) ((_ sign_extend 7) C1)) ((_ sign_extend 7) (bvmul %X C1)))`

Is satisfyable if asserted, but so is:

`(not (= (bvmul ((_ sign_extend 7) %X) ((_ sign_extend 7) C1)) ((_ sign_extend 7) (bvmul %X C1))))`

I've attached example *.smt2 files, one with signed bitvectors and one with unsigned: [examples.zip](https://github.com/Z3Prover/z3/files/263288/examples.zip)

Here's the output of --version:

```
$ ./z3 --version
Z3 version 4.4.1
```

And here's the command line I was using to solve the *.smt2 file (running on Ubuntu 14.04):

`$ ./z3 example1.smt2`

**Comment by MikolasJanota** [comment]
Hi, 
I'd be happy to look at this, but could you please indicate why you think that the formula(s) shouldn't  be satisfiable?
-MJ

**Comment by NikolajBjorner** [comment]
Both versions should be satisfiable. For some values of X, C1 the equality is true, for others the equality is false. I guess the expectation was that Z3 checks something for all values, but that is not the semantics. The semantics is that (check-sat) determines whether there is some interpretation (assignment of values to the free variable and assignment of function graphs to free functions) such that the assertions are true.
