### ISSUE TITLE
Z3Py statistics - rlimit-count keeps increasing

### ISSUE THREAD

**Issue by ganeshsankaran** [Z3Prover/z3#6022]
Hello,

I am using the `z3-solver` Python package (`v4.8.17.0`) to get some statistics, including `rlimit-count` from multiple executions of Z3 on an input formula. Here is an example of what I am trying to do:

```
from z3 import *

def call_z3(F):
    s = Solver()
    s.add(F)
    print(s.statistics()
           .get_key_value('rlimit count'))

for i in range(10):
    p, q = Bools('p q')
    call_z3(And(p, q))
```

The output of the code above is 
```
4
8
12
16
20
24
28
32
36
40
```

I have the following doubts:
1. Why does `rlimit-count` keep increasing monotonically? I would expect it to reset to 0 for each new call to `call_z3`.
2. Is there a way to reset `rlimit-count` for each new call to `call-z3`?

**Comment by NikolajBjorner** [comment]
- rlimit counts are scoped by the Context. If you use different contexts you get separate counts.
- There isn't a reset command.
