### ISSUE TITLE
Memory leak in Z3_solver_check_assumptions in 4.8.17

### ISSUE THREAD

**Issue by Trolldemorted** [Z3Prover/z3#6036]
Calling `Z3_solver_check_assumptions` consistently leaks memory in my tests. If I take this sample C code:
```C
#include "../include/z3.h"

void main() {
    Z3_config config = Z3_mk_config();
    Z3_context context = Z3_mk_context_rc(config);
    Z3_solver solver = Z3_mk_solver(context);
    Z3_solver_inc_ref(context, solver);

    Z3_sort bv_sort = Z3_mk_bv_sort(context, 32);
    Z3_ast a = Z3_mk_const(context, NULL, bv_sort);
    Z3_inc_ref(context, a);
    Z3_ast b = Z3_mk_const(context, NULL, bv_sort);
    Z3_inc_ref(context, b);
    Z3_ast eq = Z3_mk_eq(context, a, b);
    Z3_inc_ref(context, eq);

    while (1) {
        Z3_solver_check_assumptions(context, solver, 1, &eq);
    }
}
```
and build it with `cl .\tests.c libz3.lib` against your windows x64 binaries for z3-4.8.17, I get a binary that consumes more and more memory, quickly consuming several GB.

Am I doing something wrong? Do I need to calll cleanup code after `Z3_solver_check_assumptions` to dispose the model or internal state? The documentation of `Z3_solver_check_assumptions` and `Z3_solver_check` does not mention required cleanup steps.

I had a look at the python bindings, and they expose the same behaviour with with this sample:
```python
from z3 import *

x = z3.BitVec('x', 32)
a = z3.BitVec('a', 32)
solver=z3.Solver()
while True:
    solver.check(x!=a)
```

**Comment by NikolajBjorner** [comment]
It creates a fresh proxy Boolean variable for the equality atom on every call.

**Comment by Trolldemorted** [comment]
Can I free it somehow?

**Comment by NikolajBjorner** [comment]
will be fixed by using symbols

**Comment by NikolajBjorner** [comment]
ca2497eecb837205861179599ebaa0bf3ba98cf4
