### ISSUE TITLE
Relationship/Use of nlsat.randomize and nlsat.seed

### ISSUE THREAD

**Issue by wintered** [Z3Prover/z3#6039]
What is the relationship of the options `nlsat.randomize` (default:true) and `nlsat.seed` (default: 0), i.e. does the "0" mean (1) that Z3 nlsat is always running with a fixed seed, i.e. no randomness in nlsat or (2) that no random seed is set?

**Comment by NikolajBjorner** [comment]
Randomize is a Boolean, It is used in isolated places to control priorities.
https://github.com/Z3Prover/z3/blob/ca2497eecb837205861179599ebaa0bf3ba98cf4/src/nlsat/nlsat_solver.cpp#L1457
see is an unsigned, similar to smt.random_see and sat.random_seed (one day I just want to consolidate them all to a global parameter).
