### ISSUE TITLE
Optimize BitVec as is

### ISSUE THREAD

**Issue by r4dr3fr4d** [Z3Prover/z3#6040]
I'm looking to find the min/max values of bitvector expressions, but it would be helpful if I could build them on their own, without adding them to the solver, and then add a single one to the solver as is - eg:

```
o = Optimize()
bv1 = BitVec('bv1', 8)
bv2 = BitVecVal(5, 8)
bv3 = bv1 + bv2
o.add(bv3) # error
o.minimize(bv3)
o.check()
o.model()
```

I would think I could add bv3 to the solver on it's own, rather than specifying it's underlying expression (bv3 = bv1 + bv2).

Is there a way to do this so that I can arbitrarily optimize individual BV instances?

**Comment by NikolajBjorner** [comment]
You add _formulas_ that are Boolean typed expressions as assertions. 
Optimization objects are either integer, real, or Bit-vector typed expressions.
I believe you just want to remove the line with the o.add(bv3) and you get the optimization problem of minimizing bv3.
