### ISSUE TITLE
another VC taking too much time with rlimit

### ISSUE THREAD

**Issue by kanigsson** [Z3Prover/z3#605]
Hello,

This is the same as issue 599, however on 
[this file](https://gist.github.com/kanigsson/784f51eace823f7bc9e89414d8af4a94) even z3 with the fix for issue 599 still runs for a long time with a quite low rlimit:

$ z3 rlimit=100000 -T:30 runaway.smt2 -st
timeout
(:max-memory   461.31
 :memory       461.31
 :num-allocs   296952219
 :rlimit-count 40712
 :time         29.94
 :total-time   29.94)

All other VCs that I have looked at (more than 15000) run under 5 seconds now with this rlimit, so we should be good after that.

**Comment by NikolajBjorner** [comment]
yes, this required checking limits in a very different place.

**Comment by kanigsson** [comment]
Hello,

the fix is confirmed, with the rlimit of 100000 z3 now stops after 0.1 seconds.

Thank you!
