### ISSUE TITLE
WARNING: pattern does not contain all quantified variables.

### ISSUE THREAD

**Issue by nikswamy** [Z3Prover/z3#607]
Is there some way to get a more informative error message than the one above?

I have huge .smt2 files and occasionally get this warning. Figuring out which quantifier is guilty is extremely tedious. Line number or quantifier id would be most welcome.

**Comment by NikolajBjorner** [comment]
Sure, try if this helps

**Comment by NikolajBjorner** [comment]
Did this work?

**Comment by msprotz** [comment]
Yes this helped. Thanks @NikolajBjorner
