### ISSUE TITLE
Minimize/Maximize optimizations

### ISSUE THREAD

**Issue by illera88** [Z3Prover/z3#609]
Hi.

I know that z3 supports maximize and minimize optimizations but in which version is it implemented? 

I've tried the 4.4.1 (latest) and this formula and I get a unsupported error:
`(set-logic QF_AUFBV)(declare-fun SymVar_0 () (_ BitVec 32))(declare-fun SymVar_1 () (_ BitVec 8))(declare-fun SymVar_2 () (_ BitVec 8))(declare-fun SymVar_3 () (_ BitVec 8))(declare-fun SymVar_4 () (_ BitVec 8))(declare-fun SymVar_5 () (_ BitVec 8))(declare-fun SymVar_6 () (_ BitVec 8))(declare-fun SymVar_7 () (_ BitVec 8))(declare-fun SymVar_8 () (_ BitVec 8))(declare-fun SymVar_9 () (_ BitVec 8))(declare-fun SymVar_10 () (_ BitVec 8))(declare-fun SymVar_11 () (_ BitVec 8))(declare-fun SymVar_12 () (_ BitVec 8))(declare-fun SymVar_13 () (_ BitVec 8))(declare-fun SymVar_14 () (_ BitVec 8))(declare-fun SymVar_15 () (_ BitVec 8))(declare-fun SymVar_16 () (_ BitVec 8))(declare-fun SymVar_17 () (_ BitVec 8))(assert (= (ite (= ((_ extract 0 0) (ite (= ((_ extract 31 0) (bvsub (concat ((_ extract 7 0) ((_ extract 31 24) SymVar_0)) ((_ extract 7 0) ((_ extract 23 16) SymVar_0)) ((_ extract 7 0) ((_ extract 15 8) SymVar_0)) ((_ extract 7 0) ((_ extract 7 0) SymVar_0))) ((_ sign_extend 0) (_ bv2 32)))) (_ bv0 32)) (_ bv1 1) (_ bv0 1))) (_ bv1 1)) (_ bv4198495 32) (_ bv4198490 32)) (_ bv4198495 32)))(assert (bvsge SymVar_0 (_ bv1 32)))(minimize SymVar_0)`

It solve it fine in http://rise4fun.com/z3
Thank you

**Comment by illera88** [comment]
I've tried (get-info :version) in http://rise4fun.com/z3 and the version used seems to be 4.4.2 which is not released yet: https://github.com/Z3Prover/z3/releases

The latest release is the 4.4.1

**Comment by NikolajBjorner** [comment]
You can use the nightly builds to access the newest functionality. 
https://github.com/z3prover/bin/nightly

**Comment by illera88** [comment]
I've tried it and it works when I solve it using the command line and z3.exe but it doesn't when I use z3 as library.

```C
std::string *solveFormulaWithZ3(TCHAR *formula)
{
	z3::context ctx;
	z3::solver  solver(ctx);
	std::string *solution = new std::string();

	//printf("Formula received: %s\n", formula);

	Z3_ast ast = Z3_parse_smtlib2_string(ctx, (Z3_string)formula, 0, 0, 0, 0, 0, 0);
	z3::expr eq(ctx, ast);
	solver.add(eq);

	if (solver.check() == z3::sat){
		z3::model m = solver.get_model();

		/* Traversing the model */
		z3::expr_vector args(ctx);
		unsigned int length = 0;
		for (unsigned int i = 0; i < m.size(); i++) {

			z3::func_decl variable = m[i];
			std::string varName = variable.name().str();
			z3::expr exp = m.get_const_interp(variable);
			//unsigned int bvSize = exp.get_sort().bv_size();
			std::string svalue = Z3_get_numeral_string(ctx, exp);

			*solution += varName + '@' + svalue + '#';
		}
	}
	return solution;
}
```

What am I doing wrong?

**Comment by NikolajBjorner** [comment]
the maximize/minimize commands don't get parsed back. You have to use the "optimize" object and not the solver object and you will have to set optimization objectives on it as well. The tutorial on rise4fun.com/z3opt goes over calling the API functions from F#/.NET and python. The C++ functions are similar.

**Comment by illera88** [comment]
So does it mean that http://rise4fun.com/z3 is parsing the formula looking for (minimize SymVar_0) and creating an Optimize object before solving the formula? 

Is there any way to make z3 solve a "raw" formula just as we can do at http://rise4fun.com/z3 or using z3.exe?

Regards

**Comment by illera88** [comment]
Can you provide an example in C++. I have tried to make it works but it doesn't and the documentation is not clear at all.

Lets say that I need to maximize the symbolic variable with name "SymVar0".

thank you

**Comment by NikolajBjorner** [comment]
There is an example in: https://github.com/Z3Prover/z3/blob/master/examples/c%2B%2B/example.cpp
