### ISSUE TITLE
Tactic "sat-preprocess" fails to simplify a simple Xor

### ISSUE THREAD

**Issue by gukoff** [Z3Prover/z3#6090]
Depending on the order of the arguments, this tactic fails to simplify a combination of 2 Xor-s:

```python
from z3 import *
a, b = Bools('a b')
tactic = Tactic('sat-preprocess')

tactic(Xor(Xor(a, b), b)).as_expr()  # True <- expected result: a
tactic(Xor(Xor(a, b), a)).as_expr()  # b
tactic(Xor(a, Xor(a, b))).as_expr()  # b
tactic(Xor(b, Xor(a, b))).as_expr()  # a
```

**Comment by NikolajBjorner** [comment]
tactics are allowed to establish satisfiability and return a trivial subgoal (true). The sat-preprocess tactic happens to be incomplete.

**Comment by NikolajBjorner** [comment]
The result can be _equivalent_, it can be _equisatisfiable_, it can be weaker or stronger (the solver then only can answer unsat, respectively sat, for the result with certainty.
