### ISSUE TITLE
issues about refutational soundness bugs in QF_NRA

### ISSUE THREAD

**Issue by KJongUk** [Z3Prover/z3#6098]
Hi,
For this following instance, z3 2fa60aa43ce3cbf52696d185ecfca479be1fb292 returns unsat.
However it is satisfiable instance.

<pre>
<code>
$ z3 small.smt2 
unsat
$ cvc5 small.smt2 
sat
$ cat small.smt2
(set-logic QF_NRA)
(declare-fun m () Real)
(declare-fun v () Real)
(declare-fun v1 () Real)
(declare-fun v13 () Real)
(assert (and 
            (< 0 m) (= 0 (+ 1 (* v v) (* v1 v1 (- 1)))) 
            (= 0 (+ 1 (* v v) (* v13 v13 (- 1)))) 
            (= 0 (+ 1 (* m v13) (* m v1 (- 1))))
        ))
(check-sat)
</code>
</pre>

**Comment by KJongUk** [comment]
And for this formula.
<pre>
<code>
$ z3 small.smt2 
unsat
$ cvc5 small.smt2 
sat
$ cat small.smt2
(set-logic QF_NRA)
(declare-fun v () Real)
(declare-fun v2 () Real)
(declare-fun v3 () Real)
(declare-fun v5 () Real)
(declare-fun v8 () Real)
(declare-fun v10 () Real)
(declare-fun v1 () Real)
(define-fun h () Bool (= v1 0))
(assert (and 
            (= 0 (+ (* v3 v8) (* v10 v2 v3) (* v2 v3 v5) (* v3 v5 (- 1)) (* v2 v3 v8 (- 1)))) 
            (= 0 (+ v (* v3 v8) (* v10 v2 v3) (* v2 v3 v5) (* v3 v5 (- 1)) (* v v8 (- 1)) 
                 (* v2 v3 v8 (- 1)) (* v v1 v8 (- 1)))) 
            (< 0 (* v3 v3)) (> v2 0) (> v 0)))
(assert (= v1 (+ v 1.0)))
(check-sat)
</code>
</pre>

**Comment by KJongUk** [comment]
and nlsat.simplify_conflicts=false option is given, z3 returns unsat.
<pre>
<code>
$ z3 small_option.smt2 
sat
$ z3 nlsat.simplify_conflicts=false small_option.smt2
unsat
$ cat small_option.smt2
(declare-fun v1 () Real)
(declare-fun v17 () Real)
(declare-fun v () Real)
(declare-fun w () Real)
(assert (and 
            (< 0 v17) 
            (= 0 (+ v w 1)) 
            (= 0 (+ v17 (* v1 w))) 
            (= 0 (+ 1.0 1 (* v17 v17 (- 1)))) 
            (= 0 (+ 1 1.0 (* v17 v (- 1))))))
(check-sat)
</code>
</pre>

**Comment by KJongUk** [comment]
Yes, it is a fuzz bug, but it was not founded using pre-existing fuzz tools.

**Comment by KJongUk** [comment]
> I presume it is a fuzz bug. Specifically found using a pre-existing fuzz tool. Is this true?

Yes, it is a fuzz bug, but it was not founded using pre-existing fuzz tools.

**Comment by NikolajBjorner** [comment]
I have to shift at minimum triaging work to fuzz bug filers: there are duplicate bugs already and the bugs should be filed there not as new bugs unless there is some clear evidence this is different. See older bugs (colored red) in the issue list.
