### ISSUE TITLE
Nonterminating with QF_LIA, Success with LIA

### ISSUE THREAD

**Issue by Heizmann** [Z3Prover/z3#61]
On the following script z3 d01c3491a67d4a06ea1f6e57d385f04914529317 does not terminate. After changing the logic to (the more difficult!) LIA I obtain a result within a second.

	(set-option :produce-models true)
	(set-option :produce-unsat-cores true)
	(set-logic QF_LIA)
	(set-info :source |
		SMT script generated on 2015/04/26 by Ultimate. http://ultimate.informatik.uni-freiburg.de/
	|)
	(set-info :smt-lib-version 2.0)
	(set-info :category "industrial")
	(declare-fun |c___VERIFIER_nondet_int_#res| () Int)
	(declare-fun |c___VERIFIER_nondet_int_#res_primed| () Int)
	(declare-fun |c___VERIFIER_assert_#in~cond| () Int)
	(declare-fun |c___VERIFIER_assert_#in~cond_primed| () Int)
	(declare-fun c___VERIFIER_assert_~cond () Int)
	(declare-fun c___VERIFIER_assert_~cond_primed () Int)
	(declare-fun |c_main_#t~nondet0| () Int)
	(declare-fun |c_main_#t~nondet0_primed| () Int)
	(declare-fun |c_main_#t~nondet1| () Int)
	(declare-fun |c_main_#t~nondet1_primed| () Int)
	(declare-fun |c_main_#t~nondet2| () Int)
	(declare-fun |c_main_#t~nondet2_primed| () Int)
	(declare-fun c_main_~x~5 () Int)
	(declare-fun c_main_~x~5_primed () Int)
	(declare-fun c_main_~y~5 () Int)
	(declare-fun c_main_~y~5_primed () Int)
	(declare-fun c_main_~z~5 () Int)
	(declare-fun c_main_~z~5_primed () Int)
	(declare-fun main_~x~5_4 () Int)
	(declare-fun main_~y~5_4 () Int)
	(declare-fun main_~z~5_4 () Int)
	(declare-fun |main_#t~nondet0_3| () Int)
	(declare-fun |main_#t~nondet2_3| () Int)
	(declare-fun |main_#t~nondet1_3| () Int)
	(declare-fun |main_#t~nondet0_6| () Int)
	(declare-fun main_~x~5_6 () Int)
	(declare-fun main_~y~5_6 () Int)
	(declare-fun main_~z~5_6 () Int)
	(declare-fun |main_#t~nondet2_6| () Int)
	(declare-fun |main_#t~nondet1_6| () Int)
	(declare-fun |__VERIFIER_assert_#in~cond_7| () Int)
	(declare-fun __VERIFIER_assert_~cond_8 () Int)
	(declare-fun |main_#t~nondet0_13| () Int)
	(declare-fun main_~x~5_13 () Int)
	(declare-fun main_~y~5_13 () Int)
	(declare-fun main_~z~5_13 () Int)
	(declare-fun |main_#t~nondet2_13| () Int)
	(declare-fun |main_#t~nondet1_13| () Int)
	(declare-fun |__VERIFIER_assert_#in~cond_14| () Int)
	(declare-fun __VERIFIER_assert_~cond_15 () Int)
	(declare-fun |main_#t~nondet0_20| () Int)
	(declare-fun main_~x~5_20 () Int)
	(declare-fun main_~y~5_20 () Int)
	(declare-fun main_~z~5_20 () Int)
	(declare-fun |main_#t~nondet2_20| () Int)
	(declare-fun |main_#t~nondet1_20| () Int)
	(declare-fun |__VERIFIER_assert_#in~cond_21| () Int)
	(declare-fun __VERIFIER_assert_~cond_22 () Int)
	(declare-fun |main_#t~nondet0_27| () Int)
	(declare-fun main_~x~5_27 () Int)
	(declare-fun main_~y~5_27 () Int)
	(declare-fun main_~z~5_27 () Int)
	(declare-fun |main_#t~nondet2_27| () Int)
	(declare-fun |main_#t~nondet1_27| () Int)
	(declare-fun |__VERIFIER_assert_#in~cond_28| () Int)
	(declare-fun __VERIFIER_assert_~cond_29 () Int)
	(declare-fun |main_#t~nondet0_34| () Int)
	(declare-fun main_~x~5_34 () Int)
	(declare-fun main_~y~5_34 () Int)
	(declare-fun main_~z~5_34 () Int)
	(declare-fun |main_#t~nondet2_34| () Int)
	(declare-fun |main_#t~nondet1_34| () Int)
	(declare-fun |__VERIFIER_assert_#in~cond_35| () Int)
	(declare-fun __VERIFIER_assert_~cond_36 () Int)
	(declare-fun |main_#t~nondet0_41| () Int)
	(declare-fun main_~x~5_41 () Int)
	(declare-fun main_~y~5_41 () Int)
	(declare-fun main_~z~5_41 () Int)
	(declare-fun |main_#t~nondet2_41| () Int)
	(declare-fun |main_#t~nondet1_41| () Int)
	(declare-fun |__VERIFIER_assert_#in~cond_42| () Int)
	(declare-fun __VERIFIER_assert_~cond_43 () Int)
	(declare-fun |main_#t~nondet0_48| () Int)
	(declare-fun main_~x~5_48 () Int)
	(declare-fun main_~y~5_48 () Int)
	(declare-fun main_~z~5_48 () Int)
	(declare-fun |main_#t~nondet2_48| () Int)
	(declare-fun |main_#t~nondet1_48| () Int)
	(declare-fun |__VERIFIER_assert_#in~cond_49| () Int)
	(declare-fun __VERIFIER_assert_~cond_50 () Int)
	(declare-fun |main_#t~nondet0_55| () Int)
	(declare-fun main_~x~5_55 () Int)
	(declare-fun main_~y~5_55 () Int)
	(declare-fun main_~z~5_55 () Int)
	(declare-fun |main_#t~nondet2_55| () Int)
	(declare-fun |main_#t~nondet1_55| () Int)
	(declare-fun |__VERIFIER_assert_#in~cond_56| () Int)
	(declare-fun __VERIFIER_assert_~cond_57 () Int)
	(declare-fun |main_#t~nondet0_62| () Int)
	(declare-fun main_~x~5_62 () Int)
	(declare-fun main_~y~5_62 () Int)
	(declare-fun main_~z~5_62 () Int)
	(declare-fun |main_#t~nondet2_62| () Int)
	(declare-fun |main_#t~nondet1_62| () Int)
	(declare-fun |__VERIFIER_assert_#in~cond_63| () Int)
	(declare-fun __VERIFIER_assert_~cond_64 () Int)
	(declare-fun |main_#t~nondet0_69| () Int)
	(declare-fun main_~x~5_69 () Int)
	(declare-fun main_~y~5_69 () Int)
	(declare-fun main_~z~5_69 () Int)
	(declare-fun |main_#t~nondet2_69| () Int)
	(declare-fun |main_#t~nondet1_69| () Int)
	(declare-fun |__VERIFIER_assert_#in~cond_70| () Int)
	(declare-fun __VERIFIER_assert_~cond_71 () Int)
	(assert (! true :named ssa_precond_conjunct0))
	(assert (! (not false) :named ssa_postcond))
	(assert (! true :named ssa_0_GlobVarAssigCall_conjunct0))
	(assert (! true :named ssa_0_LocVarAssigCall_conjunct0))
	(assert (! true :named ssa_0_OldVarAssigCall_conjunct0))
	(assert (! true :named ssa_1_conjunct0))
	(assert (! true :named ssa_2_return_conjunct0))
	(assert (! true :named ssa_3_GlobVarAssigCall_conjunct0))
	(assert (! true :named ssa_3_LocVarAssigCall_conjunct0))
	(assert (! true :named ssa_3_OldVarAssigCall_conjunct0))
	(assert (! (<= main_~x~5_4 0) :named ssa_4_conjunct0))
	(assert (! (>= main_~x~5_4 0) :named ssa_4_conjunct1))
	(assert (! (<= main_~y~5_4 0) :named ssa_4_conjunct2))
	(assert (! (>= main_~y~5_4 0) :named ssa_4_conjunct3))
	(assert (! (<= main_~z~5_4 0) :named ssa_4_conjunct4))
	(assert (! (>= main_~z~5_4 0) :named ssa_4_conjunct5))
	(assert (! true :named ssa_5_conjunct0))
	(assert (! (<= main_~x~5_6 (+ main_~x~5_4 (* 2 |main_#t~nondet0_3|))) :named ssa_6_conjunct0))
	(assert (! (>= main_~x~5_6 (+ main_~x~5_4 (* 2 |main_#t~nondet0_3|))) :named ssa_6_conjunct1))
	(assert (! (<= main_~y~5_6 (+ main_~y~5_4 (* 4 |main_#t~nondet1_3|))) :named ssa_6_conjunct2))
	(assert (! (>= main_~y~5_6 (+ main_~y~5_4 (* 4 |main_#t~nondet1_3|))) :named ssa_6_conjunct3))
	(assert (! (<= main_~z~5_6 (+ main_~z~5_4 (* 8 |main_#t~nondet2_3|))) :named ssa_6_conjunct4))
	(assert (! (>= main_~z~5_6 (+ main_~z~5_4 (* 8 |main_#t~nondet2_3|))) :named ssa_6_conjunct5))
	(assert (! true :named ssa_7_GlobVarAssigCall_conjunct0))
	(assert (! (<= |__VERIFIER_assert_#in~cond_7| (ite (not (= (+ (+ (* 4 main_~x~5_6) (* 2 main_~y~5_6)) main_~z~5_6) 4)) 1 0)) :named ssa_7_LocVarAssigCall_conjunct0))
	(assert (! (>= |__VERIFIER_assert_#in~cond_7| (ite (not (= (+ (+ (* 4 main_~x~5_6) (* 2 main_~y~5_6)) main_~z~5_6) 4)) 1 0)) :named ssa_7_LocVarAssigCall_conjunct1))
	(assert (! true :named ssa_7_OldVarAssigCall_conjunct0))
	(assert (! (<= __VERIFIER_assert_~cond_8 |__VERIFIER_assert_#in~cond_7|) :named ssa_8_conjunct0))
	(assert (! (>= __VERIFIER_assert_~cond_8 |__VERIFIER_assert_#in~cond_7|) :named ssa_8_conjunct1))
	(assert (! (not (= __VERIFIER_assert_~cond_8 0)) :named ssa_9_conjunct0))
	(assert (! true :named ssa_10_conjunct0))
	(assert (! true :named ssa_11_return_conjunct0))
	(assert (! true :named ssa_12_conjunct0))
	(assert (! (<= main_~x~5_13 (+ main_~x~5_6 (* 2 |main_#t~nondet0_6|))) :named ssa_13_conjunct0))
	(assert (! (>= main_~x~5_13 (+ main_~x~5_6 (* 2 |main_#t~nondet0_6|))) :named ssa_13_conjunct1))
	(assert (! (<= main_~y~5_13 (+ main_~y~5_6 (* 4 |main_#t~nondet1_6|))) :named ssa_13_conjunct2))
	(assert (! (>= main_~y~5_13 (+ main_~y~5_6 (* 4 |main_#t~nondet1_6|))) :named ssa_13_conjunct3))
	(assert (! (<= main_~z~5_13 (+ main_~z~5_6 (* 8 |main_#t~nondet2_6|))) :named ssa_13_conjunct4))
	(assert (! (>= main_~z~5_13 (+ main_~z~5_6 (* 8 |main_#t~nondet2_6|))) :named ssa_13_conjunct5))
	(assert (! true :named ssa_14_GlobVarAssigCall_conjunct0))
	(assert (! (<= |__VERIFIER_assert_#in~cond_14| (ite (not (= (+ (+ (* 4 main_~x~5_13) (* 2 main_~y~5_13)) main_~z~5_13) 4)) 1 0)) :named ssa_14_LocVarAssigCall_conjunct0))
	(assert (! (>= |__VERIFIER_assert_#in~cond_14| (ite (not (= (+ (+ (* 4 main_~x~5_13) (* 2 main_~y~5_13)) main_~z~5_13) 4)) 1 0)) :named ssa_14_LocVarAssigCall_conjunct1))
	(assert (! true :named ssa_14_OldVarAssigCall_conjunct0))
	(assert (! (<= __VERIFIER_assert_~cond_15 |__VERIFIER_assert_#in~cond_14|) :named ssa_15_conjunct0))
	(assert (! (>= __VERIFIER_assert_~cond_15 |__VERIFIER_assert_#in~cond_14|) :named ssa_15_conjunct1))
	(assert (! (not (= __VERIFIER_assert_~cond_15 0)) :named ssa_16_conjunct0))
	(assert (! true :named ssa_17_conjunct0))
	(assert (! true :named ssa_18_return_conjunct0))
	(assert (! true :named ssa_19_conjunct0))
	(assert (! (<= main_~x~5_20 (+ main_~x~5_13 (* 2 |main_#t~nondet0_13|))) :named ssa_20_conjunct0))
	(assert (! (>= main_~x~5_20 (+ main_~x~5_13 (* 2 |main_#t~nondet0_13|))) :named ssa_20_conjunct1))
	(assert (! (<= main_~y~5_20 (+ main_~y~5_13 (* 4 |main_#t~nondet1_13|))) :named ssa_20_conjunct2))
	(assert (! (>= main_~y~5_20 (+ main_~y~5_13 (* 4 |main_#t~nondet1_13|))) :named ssa_20_conjunct3))
	(assert (! (<= main_~z~5_20 (+ main_~z~5_13 (* 8 |main_#t~nondet2_13|))) :named ssa_20_conjunct4))
	(assert (! (>= main_~z~5_20 (+ main_~z~5_13 (* 8 |main_#t~nondet2_13|))) :named ssa_20_conjunct5))
	(assert (! true :named ssa_21_GlobVarAssigCall_conjunct0))
	(assert (! (<= |__VERIFIER_assert_#in~cond_21| (ite (not (= (+ (+ (* 4 main_~x~5_20) (* 2 main_~y~5_20)) main_~z~5_20) 4)) 1 0)) :named ssa_21_LocVarAssigCall_conjunct0))
	(assert (! (>= |__VERIFIER_assert_#in~cond_21| (ite (not (= (+ (+ (* 4 main_~x~5_20) (* 2 main_~y~5_20)) main_~z~5_20) 4)) 1 0)) :named ssa_21_LocVarAssigCall_conjunct1))
	(assert (! true :named ssa_21_OldVarAssigCall_conjunct0))
	(assert (! (<= __VERIFIER_assert_~cond_22 |__VERIFIER_assert_#in~cond_21|) :named ssa_22_conjunct0))
	(assert (! (>= __VERIFIER_assert_~cond_22 |__VERIFIER_assert_#in~cond_21|) :named ssa_22_conjunct1))
	(assert (! (not (= __VERIFIER_assert_~cond_22 0)) :named ssa_23_conjunct0))
	(assert (! true :named ssa_24_conjunct0))
	(assert (! true :named ssa_25_return_conjunct0))
	(assert (! true :named ssa_26_conjunct0))
	(assert (! (<= main_~x~5_27 (+ main_~x~5_20 (* 2 |main_#t~nondet0_20|))) :named ssa_27_conjunct0))
	(assert (! (>= main_~x~5_27 (+ main_~x~5_20 (* 2 |main_#t~nondet0_20|))) :named ssa_27_conjunct1))
	(assert (! (<= main_~y~5_27 (+ main_~y~5_20 (* 4 |main_#t~nondet1_20|))) :named ssa_27_conjunct2))
	(assert (! (>= main_~y~5_27 (+ main_~y~5_20 (* 4 |main_#t~nondet1_20|))) :named ssa_27_conjunct3))
	(assert (! (<= main_~z~5_27 (+ main_~z~5_20 (* 8 |main_#t~nondet2_20|))) :named ssa_27_conjunct4))
	(assert (! (>= main_~z~5_27 (+ main_~z~5_20 (* 8 |main_#t~nondet2_20|))) :named ssa_27_conjunct5))
	(assert (! true :named ssa_28_GlobVarAssigCall_conjunct0))
	(assert (! (<= |__VERIFIER_assert_#in~cond_28| (ite (not (= (+ (+ (* 4 main_~x~5_27) (* 2 main_~y~5_27)) main_~z~5_27) 4)) 1 0)) :named ssa_28_LocVarAssigCall_conjunct0))
	(assert (! (>= |__VERIFIER_assert_#in~cond_28| (ite (not (= (+ (+ (* 4 main_~x~5_27) (* 2 main_~y~5_27)) main_~z~5_27) 4)) 1 0)) :named ssa_28_LocVarAssigCall_conjunct1))
	(assert (! true :named ssa_28_OldVarAssigCall_conjunct0))
	(assert (! (<= __VERIFIER_assert_~cond_29 |__VERIFIER_assert_#in~cond_28|) :named ssa_29_conjunct0))
	(assert (! (>= __VERIFIER_assert_~cond_29 |__VERIFIER_assert_#in~cond_28|) :named ssa_29_conjunct1))
	(assert (! (not (= __VERIFIER_assert_~cond_29 0)) :named ssa_30_conjunct0))
	(assert (! true :named ssa_31_conjunct0))
	(assert (! true :named ssa_32_return_conjunct0))
	(assert (! true :named ssa_33_conjunct0))
	(assert (! (<= main_~x~5_34 (+ main_~x~5_27 (* 2 |main_#t~nondet0_27|))) :named ssa_34_conjunct0))
	(assert (! (>= main_~x~5_34 (+ main_~x~5_27 (* 2 |main_#t~nondet0_27|))) :named ssa_34_conjunct1))
	(assert (! (<= main_~y~5_34 (+ main_~y~5_27 (* 4 |main_#t~nondet1_27|))) :named ssa_34_conjunct2))
	(assert (! (>= main_~y~5_34 (+ main_~y~5_27 (* 4 |main_#t~nondet1_27|))) :named ssa_34_conjunct3))
	(assert (! (<= main_~z~5_34 (+ main_~z~5_27 (* 8 |main_#t~nondet2_27|))) :named ssa_34_conjunct4))
	(assert (! (>= main_~z~5_34 (+ main_~z~5_27 (* 8 |main_#t~nondet2_27|))) :named ssa_34_conjunct5))
	(assert (! true :named ssa_35_GlobVarAssigCall_conjunct0))
	(assert (! (<= |__VERIFIER_assert_#in~cond_35| (ite (not (= (+ (+ (* 4 main_~x~5_34) (* 2 main_~y~5_34)) main_~z~5_34) 4)) 1 0)) :named ssa_35_LocVarAssigCall_conjunct0))
	(assert (! (>= |__VERIFIER_assert_#in~cond_35| (ite (not (= (+ (+ (* 4 main_~x~5_34) (* 2 main_~y~5_34)) main_~z~5_34) 4)) 1 0)) :named ssa_35_LocVarAssigCall_conjunct1))
	(assert (! true :named ssa_35_OldVarAssigCall_conjunct0))
	(assert (! (<= __VERIFIER_assert_~cond_36 |__VERIFIER_assert_#in~cond_35|) :named ssa_36_conjunct0))
	(assert (! (>= __VERIFIER_assert_~cond_36 |__VERIFIER_assert_#in~cond_35|) :named ssa_36_conjunct1))
	(assert (! (not (= __VERIFIER_assert_~cond_36 0)) :named ssa_37_conjunct0))
	(assert (! true :named ssa_38_conjunct0))
	(assert (! true :named ssa_39_return_conjunct0))
	(assert (! true :named ssa_40_conjunct0))
	(assert (! (<= main_~x~5_41 (+ main_~x~5_34 (* 2 |main_#t~nondet0_34|))) :named ssa_41_conjunct0))
	(assert (! (>= main_~x~5_41 (+ main_~x~5_34 (* 2 |main_#t~nondet0_34|))) :named ssa_41_conjunct1))
	(assert (! (<= main_~y~5_41 (+ main_~y~5_34 (* 4 |main_#t~nondet1_34|))) :named ssa_41_conjunct2))
	(assert (! (>= main_~y~5_41 (+ main_~y~5_34 (* 4 |main_#t~nondet1_34|))) :named ssa_41_conjunct3))
	(assert (! (<= main_~z~5_41 (+ main_~z~5_34 (* 8 |main_#t~nondet2_34|))) :named ssa_41_conjunct4))
	(assert (! (>= main_~z~5_41 (+ main_~z~5_34 (* 8 |main_#t~nondet2_34|))) :named ssa_41_conjunct5))
	(assert (! true :named ssa_42_GlobVarAssigCall_conjunct0))
	(assert (! (<= |__VERIFIER_assert_#in~cond_42| (ite (not (= (+ (+ (* 4 main_~x~5_41) (* 2 main_~y~5_41)) main_~z~5_41) 4)) 1 0)) :named ssa_42_LocVarAssigCall_conjunct0))
	(assert (! (>= |__VERIFIER_assert_#in~cond_42| (ite (not (= (+ (+ (* 4 main_~x~5_41) (* 2 main_~y~5_41)) main_~z~5_41) 4)) 1 0)) :named ssa_42_LocVarAssigCall_conjunct1))
	(assert (! true :named ssa_42_OldVarAssigCall_conjunct0))
	(assert (! (<= __VERIFIER_assert_~cond_43 |__VERIFIER_assert_#in~cond_42|) :named ssa_43_conjunct0))
	(assert (! (>= __VERIFIER_assert_~cond_43 |__VERIFIER_assert_#in~cond_42|) :named ssa_43_conjunct1))
	(assert (! (not (= __VERIFIER_assert_~cond_43 0)) :named ssa_44_conjunct0))
	(assert (! true :named ssa_45_conjunct0))
	(assert (! true :named ssa_46_return_conjunct0))
	(assert (! true :named ssa_47_conjunct0))
	(assert (! (<= main_~x~5_48 (+ main_~x~5_41 (* 2 |main_#t~nondet0_41|))) :named ssa_48_conjunct0))
	(assert (! (>= main_~x~5_48 (+ main_~x~5_41 (* 2 |main_#t~nondet0_41|))) :named ssa_48_conjunct1))
	(assert (! (<= main_~y~5_48 (+ main_~y~5_41 (* 4 |main_#t~nondet1_41|))) :named ssa_48_conjunct2))
	(assert (! (>= main_~y~5_48 (+ main_~y~5_41 (* 4 |main_#t~nondet1_41|))) :named ssa_48_conjunct3))
	(assert (! (<= main_~z~5_48 (+ main_~z~5_41 (* 8 |main_#t~nondet2_41|))) :named ssa_48_conjunct4))
	(assert (! (>= main_~z~5_48 (+ main_~z~5_41 (* 8 |main_#t~nondet2_41|))) :named ssa_48_conjunct5))
	(assert (! true :named ssa_49_GlobVarAssigCall_conjunct0))
	(assert (! (<= |__VERIFIER_assert_#in~cond_49| (ite (not (= (+ (+ (* 4 main_~x~5_48) (* 2 main_~y~5_48)) main_~z~5_48) 4)) 1 0)) :named ssa_49_LocVarAssigCall_conjunct0))
	(assert (! (>= |__VERIFIER_assert_#in~cond_49| (ite (not (= (+ (+ (* 4 main_~x~5_48) (* 2 main_~y~5_48)) main_~z~5_48) 4)) 1 0)) :named ssa_49_LocVarAssigCall_conjunct1))
	(assert (! true :named ssa_49_OldVarAssigCall_conjunct0))
	(assert (! (<= __VERIFIER_assert_~cond_50 |__VERIFIER_assert_#in~cond_49|) :named ssa_50_conjunct0))
	(assert (! (>= __VERIFIER_assert_~cond_50 |__VERIFIER_assert_#in~cond_49|) :named ssa_50_conjunct1))
	(assert (! (not (= __VERIFIER_assert_~cond_50 0)) :named ssa_51_conjunct0))
	(assert (! true :named ssa_52_conjunct0))
	(assert (! true :named ssa_53_return_conjunct0))
	(assert (! true :named ssa_54_conjunct0))
	(assert (! (<= main_~x~5_55 (+ main_~x~5_48 (* 2 |main_#t~nondet0_48|))) :named ssa_55_conjunct0))
	(assert (! (>= main_~x~5_55 (+ main_~x~5_48 (* 2 |main_#t~nondet0_48|))) :named ssa_55_conjunct1))
	(assert (! (<= main_~y~5_55 (+ main_~y~5_48 (* 4 |main_#t~nondet1_48|))) :named ssa_55_conjunct2))
	(assert (! (>= main_~y~5_55 (+ main_~y~5_48 (* 4 |main_#t~nondet1_48|))) :named ssa_55_conjunct3))
	(assert (! (<= main_~z~5_55 (+ main_~z~5_48 (* 8 |main_#t~nondet2_48|))) :named ssa_55_conjunct4))
	(assert (! (>= main_~z~5_55 (+ main_~z~5_48 (* 8 |main_#t~nondet2_48|))) :named ssa_55_conjunct5))
	(assert (! true :named ssa_56_GlobVarAssigCall_conjunct0))
	(assert (! (<= |__VERIFIER_assert_#in~cond_56| (ite (not (= (+ (+ (* 4 main_~x~5_55) (* 2 main_~y~5_55)) main_~z~5_55) 4)) 1 0)) :named ssa_56_LocVarAssigCall_conjunct0))
	(assert (! (>= |__VERIFIER_assert_#in~cond_56| (ite (not (= (+ (+ (* 4 main_~x~5_55) (* 2 main_~y~5_55)) main_~z~5_55) 4)) 1 0)) :named ssa_56_LocVarAssigCall_conjunct1))
	(assert (! true :named ssa_56_OldVarAssigCall_conjunct0))
	(assert (! (<= __VERIFIER_assert_~cond_57 |__VERIFIER_assert_#in~cond_56|) :named ssa_57_conjunct0))
	(assert (! (>= __VERIFIER_assert_~cond_57 |__VERIFIER_assert_#in~cond_56|) :named ssa_57_conjunct1))
	(assert (! (not (= __VERIFIER_assert_~cond_57 0)) :named ssa_58_conjunct0))
	(assert (! true :named ssa_59_conjunct0))
	(assert (! true :named ssa_60_return_conjunct0))
	(assert (! true :named ssa_61_conjunct0))
	(assert (! (<= main_~x~5_62 (+ main_~x~5_55 (* 2 |main_#t~nondet0_55|))) :named ssa_62_conjunct0))
	(assert (! (>= main_~x~5_62 (+ main_~x~5_55 (* 2 |main_#t~nondet0_55|))) :named ssa_62_conjunct1))
	(assert (! (<= main_~y~5_62 (+ main_~y~5_55 (* 4 |main_#t~nondet1_55|))) :named ssa_62_conjunct2))
	(assert (! (>= main_~y~5_62 (+ main_~y~5_55 (* 4 |main_#t~nondet1_55|))) :named ssa_62_conjunct3))
	(assert (! (<= main_~z~5_62 (+ main_~z~5_55 (* 8 |main_#t~nondet2_55|))) :named ssa_62_conjunct4))
	(assert (! (>= main_~z~5_62 (+ main_~z~5_55 (* 8 |main_#t~nondet2_55|))) :named ssa_62_conjunct5))
	(assert (! true :named ssa_63_GlobVarAssigCall_conjunct0))
	(assert (! (<= |__VERIFIER_assert_#in~cond_63| (ite (not (= (+ (+ (* 4 main_~x~5_62) (* 2 main_~y~5_62)) main_~z~5_62) 4)) 1 0)) :named ssa_63_LocVarAssigCall_conjunct0))
	(assert (! (>= |__VERIFIER_assert_#in~cond_63| (ite (not (= (+ (+ (* 4 main_~x~5_62) (* 2 main_~y~5_62)) main_~z~5_62) 4)) 1 0)) :named ssa_63_LocVarAssigCall_conjunct1))
	(assert (! true :named ssa_63_OldVarAssigCall_conjunct0))
	(assert (! (<= __VERIFIER_assert_~cond_64 |__VERIFIER_assert_#in~cond_63|) :named ssa_64_conjunct0))
	(assert (! (>= __VERIFIER_assert_~cond_64 |__VERIFIER_assert_#in~cond_63|) :named ssa_64_conjunct1))
	(assert (! (not (= __VERIFIER_assert_~cond_64 0)) :named ssa_65_conjunct0))
	(assert (! true :named ssa_66_conjunct0))
	(assert (! true :named ssa_67_return_conjunct0))
	(assert (! true :named ssa_68_conjunct0))
	(assert (! (<= main_~x~5_69 (+ main_~x~5_62 (* 2 |main_#t~nondet0_62|))) :named ssa_69_conjunct0))
	(assert (! (>= main_~x~5_69 (+ main_~x~5_62 (* 2 |main_#t~nondet0_62|))) :named ssa_69_conjunct1))
	(assert (! (<= main_~y~5_69 (+ main_~y~5_62 (* 4 |main_#t~nondet1_62|))) :named ssa_69_conjunct2))
	(assert (! (>= main_~y~5_69 (+ main_~y~5_62 (* 4 |main_#t~nondet1_62|))) :named ssa_69_conjunct3))
	(assert (! (<= main_~z~5_69 (+ main_~z~5_62 (* 8 |main_#t~nondet2_62|))) :named ssa_69_conjunct4))
	(assert (! (>= main_~z~5_69 (+ main_~z~5_62 (* 8 |main_#t~nondet2_62|))) :named ssa_69_conjunct5))
	(assert (! true :named ssa_70_GlobVarAssigCall_conjunct0))
	(assert (! (<= |__VERIFIER_assert_#in~cond_70| (ite (not (= (+ (+ (* 4 main_~x~5_69) (* 2 main_~y~5_69)) main_~z~5_69) 4)) 1 0)) :named ssa_70_LocVarAssigCall_conjunct0))
	(assert (! (>= |__VERIFIER_assert_#in~cond_70| (ite (not (= (+ (+ (* 4 main_~x~5_69) (* 2 main_~y~5_69)) main_~z~5_69) 4)) 1 0)) :named ssa_70_LocVarAssigCall_conjunct1))
	(assert (! true :named ssa_70_OldVarAssigCall_conjunct0))
	(assert (! (<= __VERIFIER_assert_~cond_71 |__VERIFIER_assert_#in~cond_70|) :named ssa_71_conjunct0))
	(assert (! (>= __VERIFIER_assert_~cond_71 |__VERIFIER_assert_#in~cond_70|) :named ssa_71_conjunct1))
	(assert (! (<= __VERIFIER_assert_~cond_71 0) :named ssa_72_conjunct0))
	(assert (! (>= __VERIFIER_assert_~cond_71 0) :named ssa_72_conjunct1))
	(assert (! true :named ssa_73_conjunct0))
	(check-sat)
	(get-unsat-core)

**Comment by wintersteiger** [comment]
In general this is unavoidable. There will always be problems on which the heuristics get lucky and others on which they don't. Using an "easier" logic declaration does not necessarily always mean that the solver will be quicker. Illustrated on this particular example problem, Z3 times out with the logic set to QF_LIA using smt.random_seed=0 (that's the default) and smt.random_seed=1.  Keeping the logic set to QF_LIA, but using random seeds 2-9 all terminate quickly, where 7 is a little bit slower than the others.
