### ISSUE TITLE
Issues with quantification over several variables

### ISSUE THREAD

**Issue by assaft** [Z3Prover/z3#610]
I'm not sure that the problems I encounter are problems in Z3 per se, but I assume or at least hope that there are ways to avoid them. I'm looking for help in doing that.

My goal is to model the occurrence of an event over a period of time in order to be able to determine if it happens at a certain point that I'm asked about. For example, assuming that it is given that the event:
starts at  2000-05-12, 10:45:12, and
ends at:  2010-08-12, 14:53:52
If I'm asked whether it takes place at 2003-1-12 10:46:22, I should return 'yes'. 
If I'm asked whether it takes place at 2020-8-12 10:46:22, I should return 'no'. 

I define a predicate - f - of 6 variables - year, month, day, hour, minute and second - and asserts that it returns 'true' in the range of times when the event takes place, and 'false' outside of that range. 

(declare-fun f (Int Int Int Int Int Int) Bool)

(assert (forall ((y Int) (m Int) (d Int) (h Int) (mi Int) (s Int)) 
(=> (and 

(or 
(> y 2000) 
(and (= y 2000) (> m 5)) 
(and (= y 2000) (= m 5) (> d 12)) 
(and (= y 2000) (= m 5) (= d 12) (> h 10)) 
(and (= y 2000) (= m 5) (= d 12) (= h 10) (> mi 45)) 
(and (= y 2000) (= m 5) (= d 12) (= h 10) (= mi 45) (>= s 12)))

(or 
(< y 2010) 
(and (= y 2010) (< m 8)) 
(and (= y 2010) (= m 8) (< d 22)) 
(and (= y 2010) (= m 8) (= d 22) (< h 14)) 
(and (= y 2010) (= m 8) (= d 22) (= h 14) (< mi 53)) 
(and (= y 2010) (= m 8) (= d 22) (= h 14) (= mi 53) (<= s 52))) 

)

(= (f y m d h mi s) true))))

(assert (forall ((y Int) (m Int) (d Int) (h Int) (mi Int) (s Int)) 
(=> (or 
(< y 2000) 
(and (= y 2000) (< m 5)) 
(and (= y 2000) (= m 5) (< d 12)) 
(and (= y 2000) (= m 5) (= d 12) (< h 10)) 
(and (= y 2000) (= m 5) (= d 12) (= h 10) (< mi 45)) 
(and (= y 2000) (= m 5) (= d 12) (= h 10) (= mi 45) (< s 12))) 
(= (f y m d h mi s) false))))

(assert (forall ((y Int) (m Int) (d Int) (h Int) (mi Int) (s Int)) 
(=> (or 
(> y 2010) 
(and (= y 2010) (> m 8)) 
(and (= y 2010) (= m 8) (> d 22)) 
(and (= y 2010) (= m 8) (= d 22) (> h 14)) 
(and (= y 2010) (= m 8) (= d 22) (= h 14) (> mi 53)) 
(and (= y 2010) (= m 8) (= d 22) (= h 14) (= mi 53) (> s 52))) 
(= (f y m d h mi s) false))))

Then I can check whether the event takes place at a particular point that I'm asked about, for example, for 2003-1-12 10:46:22 I'm asserting:
(assert (f 2003 1 12 10 46 22))
This should result in SAT, which indicates that the event takes place at that point.

But for  2020-8-12 10:46:22:
(assert (f 2020 8 12 10 46 22))
I should get UNSAT, which indicates that the event doesn't take place at that point.

My problem is that even without the assertion about a specific point in time, it takes Z3 about 15 **minutes** to give a SAT answer. I don't know if this is a bug in one of its heuristics or an unavoidable limitation of being in an undecidable logic, but I noticed that if I reduce the modeling to 5 variables (i.e. avoiding seconds), it takes about 15 **seconds** to give a SAT answer, and for 4 variables (avoiding minutes and seconds) it's almost immediate. So the processing time is definitely related to the number of variables being quantified, but I have to model all 6 variables.

I'm trying to find ways to optimize my modeling or Z3 settings in order to get a quicker response. As for Z3 - I tried various settings such as:
(set-option :smt.mbqi true)
(set-option :model.compact true)
which didn't make a difference, and
(set-option :smt.mbqi false)
which causes Z3 to return 'unknown' immediately. 

I'd really appreciate any feedback and suggestions how to optimize this modeling or how to configure Z3 for obtaining a quicker response in this use-case.

Attached: a script with 5 variables that returns SAT in 15 seconds and a script with 6 variables that returns SAT in about 15 minutes.

[tests.zip](https://github.com/Z3Prover/z3/files/269106/tests.zip)

**Comment by NikolajBjorner** [comment]
It is better to simply define f as a macro.
You can use (define-fun f ...) construct to define macros.
Then Z3 would not have to discover the interpretation.

**Comment by assaft** [comment]
Thanks, it works.
