### ISSUE TITLE
Memory 

### ISSUE THREAD

**Issue by fbrausse** [Z3Prover/z3#6100]
In https://github.com/esbmc/esbmc/issues/752 we observed a performance regression with our Z3 backend. Both, time and memory. While the time regression part of it seems to be fixed by changing our Z3 API usage in https://github.com/esbmc/esbmc/issues/760 (basically: destroy all cached z3::exprs before destroying the z3::context, otherwise z3::context::~context() will take unusually long time), the memory usage for this benchmark is still quite high: [gh-732-2-2.txt](https://github.com/Z3Prover/z3/files/8948970/gh-732-2-2.txt)

It is generated (in a probably improvable way) by ESBMC for <https://github.com/esbmc/esbmc/blob/master/regression/esbmc/github_732-2-2/main.c>, so I can also generate smaller ones if it helps in finding the cause.

What's interesting is that running `z3` (v4.8.17.0) on this example nearly all the time memory usage is ~100M and only at the very end it jumps up to more than 9G. Is it possible to reduce this? If not, could you maybe hint as to what causes these huge memory requirements?

Some context: we noticed this when moving from an unbalanced concat-chain like `(concat (select ..) (concat (select ..) [...]))` to a balanced one `(concat (concat [...]) (concat [...]))`. Not sure whether that's related.

**Comment by NikolajBjorner** [comment]
> While the time regression part of it seems to be fixed by changing our Z3 API usage in https://github.com/esbmc/esbmc/pull/760 (basically: destroy all cached z3::exprs before destroying the z3::context, otherwise z3::context::~context() will take unusually long time),

You are not supposed to have live expressions when deleting a context. The context is assumed to be the last thing out of scope.
It could be throwing internal exceptions. It is simply not a tested scenario. You are welcome to add a test file that exercises this to the bug report to make it easier to find the issue.

```
void main() {
    z3::context* c = new z3::context();
    z3::expr* a = ..
    z3::expr* b = ...
    delete c;
    delete a;
    delete b;
}
```

**Comment by NikolajBjorner** [comment]
> It is generated (in a probably improvable way) by ESBMC for

Could you run ESBMC on this example with either

1. Z3_open_log("z3.log") before any other calls to z3. The log should be possible to rerun using _the exact same version of z3_ (or at least something where the API hasn't been updated, which happened yesterday).
2. solver::set("smtlib2_log", "log.smt2"); immediately after you created the solver object you use?

Then share repros.

**Comment by NikolajBjorner** [comment]
This code
```
#include "../src/api/c++/z3++.h"

int main() {
    z3::context* c = new z3::context();
    z3::expr a = c->bool_const("a");
    z3::expr b = c->bool_const("b");
    delete c;
    return 0;
}
```
simply crashes: the expressions a, b have a pointer to c, which is invalid.
The contract that C++ clients should implement is that the context is the very last object to go out of scope.
Every object that depends on a context needs to be finalized before.

**Comment by fbrausse** [comment]
> You are not supposed to have live expressions when deleting a context. The context is assumed to be the last thing out of scope.

Thanks for confirming that this was a bug with ESBMC, which (unless I overlooked something) is taken care of for the following considerations. In particular, the example `gh-732-2-2.txt` mentioned in the initial post exhibits the memory blowup in the last few seconds of a `z3` run completely outside of ESBMC.

> Could you run ESBMC on this example with either

I've run ESBMC linked against the latest binary release z3-4.8.17-x64-glibc-2.31 with these log outputs:
1. [z3.log.gz](https://github.com/Z3Prover/z3/files/8950888/z3.log.gz)
2. [log.smt2.txt](https://github.com/Z3Prover/z3/files/8950831/log.smt2.txt)

Running the `z3` binary from that release on log.smt2 from 2. has a similarly huge memory footprint (only in the last few seconds) as initially :
```
$ /usr/bin/time z3-4.8.17-x64-glibc-2.31/bin/z3 log.smt2 
sat
92.20user 1.51system 1:33.76elapsed 99%CPU (0avgtext+0avgdata 9215836maxresident)k
0inputs+0outputs (0major+2315011minor)pagefaults 0swaps
```

**Comment by fbrausse** [comment]
Same for 1.:
```
/usr/bin/time z3-4.8.17-x64-glibc-2.31/bin/z3 z3.log
max. heap size:     10326.5 Mbytes
time:               60.2417
58.56user 1.95system 1:00.53elapsed 99%CPU (0avgtext+0avgdata 10670016maxresident)k
0inputs+0outputs (0major+2931217minor)pagefaults 0swaps
```

**Comment by fbrausse** [comment]
Same for current master of Z3.
1: [z3.log.gz](https://github.com/Z3Prover/z3/files/8951085/z3.log.gz)
```
$ /usr/bin/time /usr/local/bin/z3 z3.log
max. heap size:     10337.2 Mbytes
time:               60.8555
59.25user 1.86system 1:01.16elapsed 99%CPU (0avgtext+0avgdata 10668844maxresident)k
0inputs+0outputs (0major+2931350minor)pagefaults 0swaps
```
2: [log.smt2.txt](https://github.com/Z3Prover/z3/files/8951090/log.smt2.txt)
```
$ /usr/bin/time /usr/local/bin/z3 log.smt2
sat
92.07user 1.55system 1:33.68elapsed 99%CPU (0avgtext+0avgdata 9213444maxresident)k
0inputs+0outputs (0major+2314972minor)pagefaults 0swaps
```

@nunoplopes Many thanks for the tip with the debug build, I will do that! However, my concern here is the memory footprint. The above measurements are for plain Z3 w/o ESBMC. For nearly the entire 60-90sec it runs, it does so with roughly 100-150M memory usage, only in the last few seconds this goes way up to over 9G.

For ESBMC this causes problems running our regression suite due to memory constraints.

**Comment by nunoplopes** [comment]
I know it's not a real fix, but I use this in Alive2:
```c++
  Z3_global_param_set("memory_high_watermark", "2147483648"); // 2 GBs
```

It's a soft memory limit for Z3. I highly recommend to avoid Z3 running away. It's not surprising to see high memory consumption when quantifiers are used.

**Comment by fbrausse** [comment]
Great, many thanks!
