### ISSUE TITLE
NameError: name 'Optimize' is not defined

### ISSUE THREAD

**Issue by chadbrewbaker** [Z3Prover/z3#6108]
Name: z3-solver
Version: 4.8.9.0
Summary: an efficient SMT solver library
Home-page: https://github.com/Z3Prover/z3
Author: The Z3 Theorem Prover Project

M1  MacOS 
Python 3.9.13

```python
from z3 import *
s = Optimize()
# NameError: name 'Optimize' is not defined
```

Did the API change or am I doing something stupid?

**Comment by NikolajBjorner** [comment]
There is no bandwidth to look into older versions of z3.
But do a pip install https://github.com/Z3Prover/z3/releases/download/Nightly/z3_solver-4.8.18.0-py2.py3-none-macosx_11_0_arm64.whl for your M1.
