### ISSUE TITLE
another rlimit issue

### ISSUE THREAD

**Issue by kanigsson** [Z3Prover/z3#611]
Hi,

sorry for presenting things piecemeal like that, but here is another [VC](https://gist.github.com/kanigsson/1944aeb3fcddfe677de7ddbd7fd7e755) with a relatively low rlimit that takes over a minute to complete (see also issues 599 and 605):
$ z3 -st rlimit=1000000 rlimit2.smt2
unknown
( :rlimit-count         1000178
 :time                 60.00
 :total-time           60.01)

**Comment by NikolajBjorner** [comment]
If you profile the code you should see that Z3 spends time in groebner basis computation and checks the limits periodically. The data-structures are just larger than in other cases. Adding code to differentiate between low and high overhead groebner basis computation isn't going to be resilient and I don't think we can support it. You are welcome to dig in and suggest a pull request if this is really the way you want to go, but I don't see it as something valuable to address.

**Comment by kanigsson** [comment]
Hello,

That's fair. Thanks for letting us know!

Johannes

**Comment by NikolajBjorner** [comment]
So, would you allow me to close this as an issue?

**Comment by kanigsson** [comment]
It just occurred to me that a different solution to the problem would be to allow setting different steps counter for different modules. This is what CVC4 is doing, see e.g. `cvc4 --help | grep step`. This puts the problem on the user to set the various parameters to suitable values, but it's quite flexible.

Just wanted to mention that as a possible way forward, you can still close the issue.

**Comment by NikolajBjorner** [comment]
Internally we can control the step counter. The number of steps required by the module depends on the data it is processing. It may be possible to extract this information and use it for the limit check, but it requires some digging and I am not sure how high priority it is to do this kind of digging on my side. You are of course welcome to add a pull request with something that works for you. The relevant module is reslimit in util/rlimit.h/rlimit.cpp, which is accessible from ast_manager, which is accessible from the Groebner basis module. The reslimit::inc method has an overload that takes an offset (number of ticks to increment by).

**Comment by kanigsson** [comment]
OK, with your pointers I managed to find the hotspot at least for this VC: it's taking it's time in the "merge_monomials" function, which is called often and indeed can take quite large data structures. By incrementing the counter there depending on the number of loop iterations I managed to get to something more reasonable. However I need to do some more testing on other VCs to know by how much to increment, and if that doesn't affect other VCs negatively. I will come back to this ticket when I have something.

**Comment by NikolajBjorner** [comment]
fantastic! Probably one can just access the number of monomials instead of counting loops and use this as the increment. It's of course easier to guess this than actually act on it.

**Comment by kanigsson** [comment]
Yes I don't increment inside the loop, but using the `sz` variable which is set to `monomials.size()`. Just incrementing by `sz` is much too much, so I will have to do some testing to find a good value (e.g. `sz / 10`, etc).

**Comment by kanigsson** [comment]
Sorry for the long reaction time on this issue, I was away for over a week. I wanted to do some measurements over all our VCs to achieve some smooth curve for the relation time/steps. But this seems more complex than I thought and would require a lot of time, and the monomials stuff is probably not the only parameter.

So in the end I just did the simple fix and checked that it doesn't have a big impact on the steps for our other VCs.

I'm closing the issue.
