### ISSUE TITLE
Parallel threading with Optimize

### ISSUE THREAD

**Issue by FranciscoSedeno** [Z3Prover/z3#6110]
Hello, I am trying to optimize a program in Python using the Optimize() object, my goal is also to use multiple threads simultaneously but the statement `set_param("parallel.enable",True) ` doesn't seem to take more than one thread.

Is this the way to multi thread an Optimize problem? How can I check the number of threads being used by the code?

Thanks in advance.

**Comment by NikolajBjorner** [comment]
There isn't at the time any support for multi-threading together with optimization.
