### ISSUE TITLE
Release Date of 4.8.18

### ISSUE THREAD

**Issue by fkohlgrueber** [Z3Prover/z3#6111]
Hi,

I'd like to ask if there are plans to do another release of z3 soon. After the possible deadlock I was hitting has been fixed (see https://github.com/Z3Prover/z3/pull/6102), I could now update to the latest z3 version, but I'd prefer to use a regular release instead of a nightly version. I couldn't find any information on the release schedule or sth like that, that's why I'm asking. I don't want to put any pressure on you, it'd just be good for me to know some estimate. Thanks in advance!

**Comment by NikolajBjorner** [comment]
the release date for 4.8.18 never came, but there is 4.9.1
