### ISSUE TITLE
different smt enodes for the same expr

### ISSUE THREAD

**Issue by joe-hauns** [Z3Prover/z3#6119]
Hello! 

I just came across the following issue when using z3 via the c++ interface in vampire for avatar. 
Somewhere in the run z3 generates two distinct enodes for the same root expression.
(i.e. two enodes with the root expression `-2147483647` (different `app*` pointers but same content), and different `get_owner_id()`). 
Due to this fact in `smt_context.cpp` a conflict is reported and z3 falsely reports unsat.
https://github.com/Z3Prover/z3/blob/12e7b4c3d622923e91e575403a0e1432bbb187dd/src/smt/smt_context.cpp#L484-L488

I could not reprodce the bug outside of vampire (yet), but due to time pressure due to the upcoming POPL deadline we want to make I thought I'd ask for help straight away as there might be something obvious going on. And with some help i could find the issue myself.

So my first question is: Is it allowed to have two `enode`s with the same `app` content at this point? 
If so I reckon the issue is that they should be merged at this point. If not i have to identiy the reason why they were generated in the first place.

I tested this with the latest version of master as well as the release `4.8.17`

**Comment by joe-hauns** [comment]
Yes this is indeed what I found out one minute ago. 
Indeed they are both integers, but one of them is small (`m_kind == mpz_small`) and one of them is big `(m_kind == mpz_small`).
Therefore they are being hashed differently.

**Comment by NikolajBjorner** [comment]
this is with or without GMP enabled?

**Comment by NikolajBjorner** [comment]
If the repro is short, use the Z3_open_log("z3.log") feature before any other z3 calls to dump a log.
Then run the log with z3 where you instrument an assertion violation in the code that makes the wrong conclusion.
Share the log. The next step is to pin down (1) why are hashes different (leading 0 bits?, GMP?, something I don't see) (2) where is the conversion to big-num happening (this should not be a hard requirement because the places of conversion cannot be controlled and would make overall coding too fragile).

**Comment by joe-hauns** [comment]
> If the repro is short, use the Z3_open_log("z3.log") feature before any other z3 calls to dump a log. Then run the log with z3 where you instrument an assertion violation in the code that makes the wrong conclusion. Share the log. The next step is to pin down (1) why are hashes different (leading 0 bits?, GMP?, something I don't see) (2) where is the conversion to big-num happening (this should not be a hard requirement because the places of conversion cannot be controlled and would make overall coding too fragile).

Alright i will do that.

**Comment by joe-hauns** [comment]
No that piece of code is never being hit in the whole run.

**Comment by joe-hauns** [comment]
[z3.log](https://github.com/Z3Prover/z3/files/9012195/z3.log)

**Comment by joe-hauns** [comment]
[z3.log](https://github.com/Z3Prover/z3/files/9012343/z3.log)
This one panics at the point in `smt_context`. But I'm I think it's pretty long so it won't much help i fear.

**Comment by joe-hauns** [comment]
The hash for the small represenation is
`2147483652`
and the one for the big one is
`2147483650`

**Comment by joe-hauns** [comment]
The hash of the small one is `unsigned(-2147483647)` which is `2147483649`, and the one for the big one is `2147483647`, as `digits(a)[0]` is an unsigned anyways.

**Comment by NikolajBjorner** [comment]
yes, this is the corner case.

**Comment by joe-hauns** [comment]
Great! I tried replacing 
```
    if (is_small(a))
        return a.m_val;

```
by
```
    if (is_small(a))
        return ::abs(a.m_val);
```
and I don't hit the unsoudness anymore :)
I don't know if that'd b your prefered fix.
