### ISSUE TITLE
parse_smt2_string() wastes time creating copies of symbols and functions

### ISSUE THREAD

**Issue by kosarev** [Z3Prover/z3#6123]
The definition of `parse_smt2_string()` reads like it calls `_dict2sarray()` for the passed symbols and functions, which causes significant delays on large dictionaries -- a huge problem when you have hundreds of expressions to parse. Would it possible to introduce a `Dict2DArray` kind of class that implements storing such arrays in a ready-to-use form and allow its instances along with ordinary dictionaries for the `sorts` and `decls` parameters so `parse_smt2_string()` doesn't need to translate them on every call?

**Comment by NikolajBjorner** [comment]
sorry, this is very vague. To start with what is dict2sarray?
Is the comment based on running an instance in a profiler and observing where you see overhead?

**Comment by kosarev** [comment]
I didn't use any profilers, but I think from just reading the definition of `parse_smt2_string()` it's pretty obvious what's going on.

Here's where we call `_dict2sarray()` and `_dict2darray()`:
https://github.com/Z3Prover/z3/blob/ea2a84332513a7823e8e5c96f039fd048cb43dc5/src/api/python/z3/z3.py#L9212

And here's a reproducer that should hopefully demonstrate the problem:
```
$ python3
Python 3.8.10 (default, Mar 15 2022, 12:22:08) 
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import z3
>>> decls = {f'x{i}': z3.Bool(f'x{i}') for i in range(10000)}
>>> def foo():
...   z3.parse_smt2_string('(assert true)', decls=decls)
... 
>>> timeit.timeit("foo()", globals=globals(), number=5)
1.0481350090003616
>>> decls = {f'x{i}': z3.Bool(f'x{i}') for i in range(100)}
>>> timeit.timeit("foo()", globals=globals(), number=5)
0.017926508000073227
>>> 
```

**Comment by NikolajBjorner** [comment]
Alright, this is about the python API (and not inside of z3) and the ask is to make it lazy.

**Comment by kosarev** [comment]
Caching translated symbols and functions unfortunately wouldn't help where we have to amend the dictionary. A better solution might be to introduce a couple classes that store symbols and functions in a form that can be passed to `parse_smt2_string()` without any additional translation.

**Comment by NikolajBjorner** [comment]
In that case, the underlying API is not suitable. 
It would be more suitable with an API that took a vector of sort and declarations. 
The ast-vector object supports mutation.

**Comment by NikolajBjorner** [comment]
I have added a separate mechanism for parsing incrementally.
It allows adding sort and function declarations (but not with alternative names, just the names used by the sorts and functions).
It handles the symbol table additions incrementally.
It should address use cases like yours (I don't really like it as it implies that you are parsing a string instead of using the programmatic API to build expressions, so your downstream infrastructure is probably "an area for improvement").

**Comment by kosarev** [comment]
Will give a try, thanks!

Regarding using the API for building expressions, the aim is to serialise expressions and then load them back. I know there is `z3.deserialize()`, but it's painfully slow when the number of expressions to parse is large and then traversing expressions by means of using `BoolRef.arg()` is even slower. So I eventually ended up with `z3.parse_smt2_string(f'(assert {expr})', decls=decls)[0]` as the fastest approach discovered so far.

If I take it right that `parse_smt2_string()` is able to parse multiple assertions, that might help in some cases. But in other cases this is just not an option, either because you have to deal with individual expressions or because it's not practical to put all expressions into a single string.

**Comment by NikolajBjorner** [comment]
you can parse multiple expressions by adding multiple assertions. Each assertion is an element in the vector that is returned.

**Comment by NikolajBjorner** [comment]
Closing, as feature is there to support incremental parsing.
