### ISSUE TITLE
ASSERTION VIOLATION: File: ../src/ast/ast.cpp, Line: 1468

### ISSUE THREAD

**Issue by zhendongsu** [Z3Prover/z3#6124]
Unsure how useful this test is (as it involves trace and arith.solver=2), but in case:
```
[553] % z3debug small.smt2
unsat
ast_manager LEAKED: 11
ASSERTION VIOLATION
File: ../src/ast/ast.cpp
Line: 1468
!roots.empty()
(C)ontinue, (A)bort, (S)top, (T)hrow exception, Invoke (G)DB
a
[554] % 
[554] % cat small.smt2
(set-option :smt.arith.solver 2)
(set-option :rewriter.eq2ineq true)
(set-option :trace true)
(declare-fun a (Int) Int)
(assert (forall ((b Int) (c Int)) (< b c)))
(assert (forall ((d Int)) (> 0 (div d (a d)))))
(check-sat-using ctx-solver-simplify)
```

**Comment by NikolajBjorner** [comment]
You can check out of hotel ETHZ, but you can never leave ... @alexanderjsummers

**Comment by alexanderjsummers** [comment]
Hi there :)

No, I haven't contributed any code for Z3 (unfortunately). I assume this is code that Nils Becker contributed? I remember that he discussed the design and plans with Nikolai and myself, but I'm afraid I can't recall much about the details.

I'd be interested to have an intern or other student work on the Axiom Profiler again; hopefully they could improve this code too (actually, I'd hoped to have such a student this summer, but they didn't materialise). It would be helpful to talk (I guess with you, Nikolai) about how the logging should actually be done, which I think was somewhat subtle - I don't know if you remember more than I do about the discussions with Nils (but I guess you know much better how the interaction *should* work with Z3's internals). I'd like to try to get down to Seattle sometime this summer, so maybe that would be an opportunity to understand that a little better, at least!

**Comment by NikolajBjorner** [comment]
So, I presume professor claims not to be liable and other professor files bugs but does not file fix. 
@Nils-Becker can reopen if this is going to be addressed.

**Comment by alexanderjsummers** [comment]
Personally I'd be very happy to try to get this code fixed; for the moment I don't know enough about what needs doing or the codebase to come up with any clear plan. I don't think it's likely that @Nils-Becker will reappear on this after several years, but if you'd be willing to talk together about how we can improve the interactions with the tracing code, Nikolaj, I'd be very interested.

**Comment by NikolajBjorner** [comment]
Bugs like these are not hard to fix, so overhead on discussions isn't optimal. 
It should be possible even for fuzz tools to get some idea.

- Open a debugger.
- Run the example in the debugger.
- Identify the break-point
- observe that pointers are garbage because the caller doesn't maintain ownership.
- ensure that pointer life-time remains valid within function body.
- add pull request (or as I do push to repository).
