### ISSUE TITLE
How to construct Empty BitVec

### ISSUE THREAD

**Issue by chason0528** [Z3Prover/z3#6131]
Algorithm:
`if BitVecA > 0
    BitVecB = Concat(BitVecA, BitVecB)`

I want to Concat two conditional bitvec  and with no else condition by using If

**Comment by chason0528** [comment]
I want to using 
`BitVecB = Contact(BitVecA, If(BitVecA>0, BitVecA, EmptyBitVec ))`
but len of BitVec cannot be zero

**Comment by NikolajBjorner** [comment]
bit-vectors of size 0 are not supported. You will have to write your expressions in a different way.
