### ISSUE TITLE
ConanCenter's `z3` depends rigidly on `mpir`

### ISSUE THREAD

**Issue by victorpaleologue** [Z3Prover/z3#6138]
Hello,
I am trying to compile a project that uses both `z3` and `gmp` with `conan`, but I face this error message:
```
ERROR: At least two recipes provides the same functionality:
 - 'gmp' provided by 'mpir/3.0.0', 'gmp/6.2.1'
```
But I can read in the README that `z3` can be built with `gmp`, or even without neither `gmp` nor `mpir`.

I would like to do so and improve the `conan` recipe for `z3`, but I fail to find it.
Where is it?
Could we make a build with no dependency for ConanCenter?

**Comment by victorpaleologue** [comment]
Also, is it correct that `mpir` says it provides `gmp`?

**Comment by victorpaleologue** [comment]
FTR I found the `conan` recipe for `z3` here: https://github.com/conan-io/conan-center-index/blob/8acb1a35a96260bce62b029b2b5c824ae804a060/recipes/z3/all/conanfile.py
I reported an issue to make the change there: https://github.com/conan-io/conan-center-index/issues/11583

**Comment by NikolajBjorner** [comment]
If there is something to change/fix on the z3 side add note.
Though, sometimes "fixes" end up breaking others (for example, there is an open issue on file paths for fedora).
