### ISSUE TITLE
Performance drop when switching from C# binding to typescript binding

### ISSUE THREAD

**Issue by KarimGhallab** [Z3Prover/z3#6142]
# Context
Hello, I am developing a typescript application in which I need to check some properties on models. As there was no TS binding at the time, I developed a small side program based on the C# binding that I call from my TS application.
I recently saw that there is now a TS binding for Z3. So I saw here the opportunity to remove this C# side program so that everything is in TS.

# Problem
However, during my tests, I noticed that the execution times of the TS binding are much higher than those of the CS binding. By running both bindings on the same examples, the TS binding takes on average 4 times longer to return the expected result.
Is this a known problem of the TS binding or is it a possible misuse on my part?

Regarding the TS binding, i used the [latest version](https://www.npmjs.com/package/z3-solver) available provided by npm

Thanks in advance for your help

**Comment by NikolajBjorner** [comment]
The target for C# bindings is native x64. The target for ts is web assembly. Different targets.
Do you expect different compilers for very different target to produce equally performant object code?
This as an issue seems pretty open-ended quest and most likely beyond z3, so closing it.
