### ISSUE TITLE
Odd behavior difference Windows and MacOS

### ISSUE THREAD

**Issue by mrkmarron** [Z3Prover/z3#6149]
Running the attached file on Windows and MacOS has very different behavior. On Windows it immediately returns SAT (as expected) while on MacOS (M1 ARM64) it runs until a timeout hits. Additionally, if line 700 is changed to replace the constant `@BLENMAX` with the literal value `32` the solver can immediately find the SAT solution. Further this function is never referenced anywhere else in the file (so could be deleted entirely and is clearly semantically irrelevant).

Given these behaviors I am suspicious there is more going on here (like an ARM64 bug) than just bad luck with heuristics or solver ordering.

Build configuration for M1 is:
`CXX=clang++ CC=clang FPMATH_ENABLED=False python scripts/mk_make.py --arm64=true --staticlib`

[_build_.smt2.txt](https://github.com/Z3Prover/z3/files/9075410/_build_.smt2.txt)

**Comment by mrkmarron** [comment]
This example might also be relevant as it fails with a timeout  (or "smt tactic failed to show goal to be sat/unsat (incomplete quantifiers)") when the lambdas on lines 958 and 1643 are replaced by the empty list values. These clauses are not meaningful to the result as they are always successful given the structure of the formula.

(Behavior appears on both Windows and MacOS).

[unknown.smt2.txt](https://github.com/Z3Prover/z3/files/9075481/unknown.smt2.txt)

**Comment by NikolajBjorner** [comment]
For the first one, some bisection debugging would be useful.
- build debug version on M1, or at least with trace enabled
- build debug version on your x64 platform
- run both version with -tr:mk_var_bug or -tr:context or -tr:seq to identify first place where traces differ
- narrow with breakpoints and other traces

Perhaps it is easier than that and pre-processing is where the platform dependency comes in.
The first few lines of verbose -v:10 gives an idea if this is the case.

C:\z3\build>..\release\z3 _build_.smt2 /v:1 smt.random_seed=6 /v:10
(simplifier :num-exprs 821 :num-asts 5249 :time 0.00 :before-memory 19.70 :after-memory 19.70)
(simplifier :num-exprs 821 :num-asts 5248 :time 0.00 :before-memory 19.70 :after-memory 19.70)
(propagate-values :num-exprs 661 :num-asts 5183 :time 0.00 :before-memory 19.70 :after-memory 19.82)
(ctx-simplify :num-steps 6776)
(ctx-simplify :num-exprs 780 :num-asts 5914 :time 0.00 :before-memory 19.82 :after-memory 19.91)
(simplifier :num-exprs 780 :num-asts 5578 :time 0.00 :before-memory 19.82 :after-memory 19.82)
(solve_eqs :num-exprs 724 :num-asts 5708 :time 0.00 :before-memory 19.82 :after-memory 19.82)
(:num-elim-vars 23)
(elim-uncnstr :num-exprs 724 :num-asts 5708 :time 0.00 :before-memory 19.82 :after-memory 19.82)

Note that _build_.smt2.txt behaves differently depending on the random seed. 
However, we do want the solver to produce the same results regardless of platforms (so not use certain std features that are platform dependent).

**Comment by mrkmarron** [comment]
After some investigation I am noticing 2 interesting things.

1)  The solver gets stuck in the search looping trying to complete the arith model but failing in the `final_check` loop. Seems to be some issues with how map and contains interact and it (seems?) like it keeps trying to extend the model even though the sequence size is fixed as a constant 3 elements.

2) If I replace the use of the lambdas _or_ the seq.contains in the attached smt2 file (957/963 and 1646/1652) with the manually unrolled versions then the proof will terminate with `unknown` and a report of unhandled quantifiers. The unknown quantifiers do not exist explicitly in the SMT file but are introduced as `forall` expressions in the internalize_assertions that the solver generates and have a `qid` of `:lambda-def`. 

I am wondering if these quantifiers are also causing the instability in (1) and am not sure why/how they are getting created as I thought map/lambda were processed as rewrites.

[unknown2.smt2.txt](https://github.com/Z3Prover/z3/files/9097510/unknown2.smt2.txt)

**Comment by NikolajBjorner** [comment]
the "unknown" result turns out to be subtle: there is an internal model check call that is invoked. It determines somehow that the model built doesn't satisfy the assignment to a ground literal so it bails out. Needs investigation.

**Comment by NikolajBjorner** [comment]
There were several bugs related to incomplete handling of map/fold operations and even creation of ill-formed terms.
A sequence of commits tries to address the issues:

809838fedeedbba84545a5e4bbc84c1ffdd8f977
53611f47df768c6018fbd1e357ba9d5d473c221b
7a55bd568730df527b742d4ea9adcf07dc6f11a5
3900c03b72720d4283adce274f903692558c2b51
6df711254b39190fdb726058626b32026b338d67
831152547211a4d21d5c1bc3dff2a5a991e26bb2
0629353fdc36f7f97d5f219c202bdf19877f96a4

I also added initial unit tests for map/mapi/fold/foldi. 
It would be great to add more tests at this level (and not relying purely on end-to-end testing).

https://github.com/Z3Prover/z3test/commit/d32176e5f37a6e998ce922336ffef45eee0d906f

**Comment by mrkmarron** [comment]
Just built this and ran tests. It looks like all the issues I had found have been cleared up. I'll plan to workup some tests for these features too.
