### ISSUE TITLE
Memory Leak in Theory of FP with Multiple check-sat Commands

### ISSUE THREAD

**Issue by kyledewey** [Z3Prover/z3#615]
On the `master` branch at commit cb6d008da8606e6d7fcbe54c3e7eb10b3f24f01f, consider the following input:

```
(set-logic QF_FP)
(check-sat)
(declare-fun x1 () (_ FloatingPoint 2 3))
(assert (not (fp.isNaN (fp.min (fp.div RTN (fp.abs x1) (fp.add RNE (fp.mul RTP x1 (fp.min (fp.mul RTP x1 (fp #b0 #b00 #b01)) x1)) x1)) x1))))
(check-sat)
```

Placing this into a file `test.smtlib2` and running with command-line `z3 -smt2 test.smtlib2` yields the following output, truncating to the first 11 lines (there are many pages of output):

```
sat
sat
ast_manager LEAKED: 35592
Leaked: decl x1 :: FloatingPoint[2:3]
#50 := (bv_wrap x1)
#74 := (extract[1:0] #50)
#75 := (extract[3:2] #50)
#76 := (extract[4:4] #50)
#77 := (fp #76 #75 #74)
#141 := (concat bv[1:1] #74)
```

Removing the first `(check-sat)` command makes this leak appear to go away.  I can provide the full output if so requested.

**Comment by wintersteiger** [comment]
Thanks for reporting this issue, it should now be fixed!
