### ISSUE TITLE
Performance anomaly in computing permutations

### ISSUE THREAD

**Issue by cemcebeci** [Z3Prover/z3#6154]
I have used the following input file to express "p is a permutation of s".
The functions p and s model ordered lists where `p(-1)` is the length of the list and `p(0), p(1),..., p(p(-1))` are the elements in it.

```smt
(declare-fun s (Int) Int)
(declare-fun p (Int) Int)

; define s
(assert (= (s -1) _Cardinality_))
(assert (forall ((i Int)) (=> (> i -1) (= (s i) i))))

; same cardinality, p contains every element of s.
(assert (= (s -1) (p -1)))
(assert
  (forall
       ((i Int))
       ( =>
           (and (>= i 0) (< i (s -1)))
           (exists ((j Int))
               (and
                   (>= j  0)
                   (< j (s -1))
                   (= (s i) (p j))
               )
           )
       )
   )
)

(check-sat)
(get-model)
```
I have tested this for varying cardinalities of s, below are the executions times.
A `-` means it took longer than several minutes for Z3 to return an answer.
| Cardinality | Time                              |
|-------------|-----------------------------------|
| 10          | 0.05s                             |
| 12          | 0.05s                             |
| 14          | 0.15s                             |
| 15          | 0.08s                             |
| 16          | -                                 |
| 17          | 1.97s                             |
| 18          | -                           |
| 19          | -                                 |
| 20          | 0.52s                             |

My question is, why can Z3 handle a sequence of 20 elements in half a second but fails to return an answer for 16, 18 and 19 elements?
I thought the nested quantifiers might be pushing the bounds of Z3's capabilities but that does not explain why some cardinalities are handled so quickly.

**Comment by NikolajBjorner** [comment]
it also depends on the value you set to smt.random_seed=<value>
So, overall, it isn't a formula that z3 solves with every order of the search.
This happens, generally, for formulas involving quantifiers and arithmetic and functions.
