### ISSUE TITLE
[Consolidated] Segfaults

### ISSUE THREAD

**Issue by wintered** [Z3Prover/z3#6158]
[b81f70f](https://github.com/Z3Prover/z3/commit/b81f70f6fcc7850369c3131ebc11a4ffca9da393)
```
$z3release bug.smt2 
[1]    650136 segmentation fault  z3release bug.smt2
$cat bug.smt2 
(assert (forall ((a Bool) (b Bool) (d (_ BitVec 1)) (e (_ BitVec 1)) (f (_ BitVec 1)) (g Bool)) 
        (= (= f (ite a (_ bv0 1) (ite true (_ bv0 1) (ite b e e)))) g)))
(check-sat-using horn)
```

**Comment by wintered** [comment]
```
$z3release bug.smt2
[1]    3178503 segmentation fault  z3release bug.smt2
$cat bug.smt2
(declare-fun a () Bool)  
(set-option :proof true)
(assert (and  (not (not (= 0 0)) ) (not (= 0 0)))) 
(check-sat-using qfufbv_ackr)
```

**Comment by agurfinkel** [comment]
the first example is not `HORN`, please do not use `horn` tactic on it.

**Comment by wintered** [comment]
>the first example is not HORN, please do not use horn tactic on it.
thanks, marked it by 👎 .

**Comment by levnach** [comment]
z3 from the Nightly build crashes on the following input file(s).

**z3 Nightly build:** tag `Nightly`, commit [`241c6211d`](https://github.com/Z3Prover/z3/commit/241c6211d6e0da7dd4ef8904314aa3db0775db30) (`Z3 version 4.17.0`)

**Crashing input(s):**
- [`inputs/issues/iss-6158/bug.smt2`](https://github.com/Z3Prover/bench/blob/main/inputs/issues/iss-6158/bug.smt2)
- [`inputs/issues/iss-6158/bug-4.smt2`](https://github.com/Z3Prover/bench/blob/main/inputs/issues/iss-6158/bug-4.smt2)

z3 crashes when run on the file(s) above.

The crash is observed on Ubuntu 24.04.4 LTS (x86_64).

**Comment by NikolajBjorner** [comment]
fixed
