### ISSUE TITLE
Unsat to Sat with Theory of FP Without Variables

### ISSUE THREAD

**Issue by kyledewey** [Z3Prover/z3#616]
On the `master` branch at commit cb6d008da8606e6d7fcbe54c3e7eb10b3f24f01f, consider the following input:

```
(set-logic QF_FP)
(assert (fp.eq (fp.sqrt RTN (fp.max (fp.abs (fp #b1 #b00 #b00)) (fp.neg (fp.neg (fp.max (fp.sqrt RTZ (fp #b0 #b00 #b00)) (fp.sqrt RTP (fp.min (fp.max (fp #b1 #b00 #b01) (fp #b0 #b10 #b01)) (fp #b1 #b00 #b00)))))))) (fp #b0 #b00 #b11)))
(check-sat)
(assert true)
(check-sat)
```

Placing this into a file test.smtlib2 and running with command-line `z3 -smt2 test.smtlib2` yields the following output:

```
unsat
sat
```

Replacing the large FP expression with a simple `false` makes this correctly return `unsat` twice.

It's likely possible to further minimize the expression; I can take another attempt at it myself if desired.

**Comment by wintersteiger** [comment]
Haven't solved the problem yet, but I managed to minimize the test case just by syntactic means to get

    (declare-fun X () (_ FloatingPoint 2 3))

    (assert (= X (fp.max
                     (_ -zero 2 3)
                     (fp.max (_ +zero 2 3) (_ -zero 2 3)))))

    (assert (fp.eq  X (fp #b0 #b00 #b11)))

So, it's obviously a problem with the unspecified semantics of fp.max. Would be nice if your fuzzer would do that sort of minimization automatically. In this particular case it was super easy to minimize by replaceing `(sqrt rm arg)` with just `arg`, and similar for the other operators.
