### ISSUE TITLE
Unexpected large table warning, occurring sporadically

### ISSUE THREAD

**Issue by jcreedcmu** [Z3Prover/z3#619]
When I put 
https://gist.github.com/anonymous/bacabff86b15923bf482feb22c54456a
in `/tmp/test.smt2`
and run
`z3 /tmp/test.smt2`
I reliably get the warning
`WARNING: creating large table of size 4294967296 for relation acl-rule-must-match-tcp-udp`
which I don't expect. Moreover, when I change every occurrence of `acl-rule-must-match-tcp-udp` to `bar`, the warning usually goes away --- but still occurs about 1% of the time, when I run a bash loop repeatedly doing `z3 /tmp/test.smt2`.

Most of my attempts at making this counterexample smaller also make the warning go away ~100% of the time, up to the limits of my patience while testing.

**Comment by jcreedcmu** [comment]
(I'm compiling from source, running at commit https://github.com/Z3Prover/z3/commits/c20b391cf78be4f29210ff7b08d3125a34113b3a on OSX)

**Comment by seanmcl** [comment]
To clarify a bit, the declaration is

`
(declare-rel acl-rule-must-match-tcp-udp (acl rule-num action cidr proto port))
`

and the component sorts have the following sizes:

- acl: 2 bits
- rule-num: 2 bits
- action: 1 bit
- cidr: 3 bits
- proto: 2 bits
- port: 3 bits

which should have a maximum size of 2^13 = 8192

**Comment by NikolajBjorner** [comment]
Still trying to figure out if there is a way to address it.

A workaround is to avoid the fact that CidrMask2 becomes unsafe as a side-effect of the join planner shuffling predicates and constraints around to the point where the inlined cidrs-subset relation exposes the variables from its constraints before they get fixed.

     (declare-rel atom/cidr/mask (cidr bits/32 bits/32 bits/32))
     (rule (forall ((x bits/32) (y bits/32) (z bits/32)) (=> (and (atom/cidr x y) (= z (bvand x y))) (atom/cidr/mask x y z))))

     ;(rule (forall ((CidrBase2 bits/32) (CidrMask2 bits/32) (CidrBase1 bits/32) (Cidr2 cidr) (Cidr1 cidr) (CidrMask1 bits/32))
     ;  (=> (and (= (bvand CidrBase2 CidrMask2) (bvand CidrBase1 CidrMask2))
     ;           (atom/cidr Cidr2 CidrBase2 CidrMask2)
     ;           (atom/cidr Cidr1 CidrBase1 CidrMask1))
     ;      (cidrs-subset Cidr1 Cidr2))))

    (rule (forall ((CidrBase2 bits/32) (CidrMask2 bits/32) (CidrBase1 bits/32) (m bits/32) (Cidr2 cidr) (Cidr1 cidr) (CidrMask1 bits/32))
       (=> (and (atom/cidr/mask Cidr2 CidrBase2 CidrMask2 m)
                (atom/cidr/mask Cidr1 CidrBase1 CidrMask1 m))
           (cidrs-subset Cidr1 Cidr2))))

**Comment by seanmcl** [comment]
Thanks for looking into this.  Is the join planner non-deterministic?  We're puzzled why it's only exhibiting this behavior once in awhile.

**Comment by NikolajBjorner** [comment]
yes, sure I am wondering too, but don't yet have an answer on that. non-determinism is a bug.

**Comment by NikolajBjorner** [comment]
non-determinism bug is fixed. It happens to now handle original problem, but this is more likely an effect of traversal order. The join planner could still generate plans that cause memory overhead because it works on top of inlined rules. You can disable inlining using the parameter:
fixedpoint.xform.inline_eager=false
Then the join planner would not be presented with pitfalls.

**Comment by seanmcl** [comment]
Thanks for taking the time to fix this and telling us how to turn off the inliner. It really helps us out!

**Comment by NikolajBjorner** [comment]
As it is now, the join planner could possibly still produce plans with free variables in the side-constraints. 
With the facility to tame the planner by disabling inlining users have a way to avoid this bug. 
I would prefer to move on from here as  @nunoplopes may have a much better overall join planner up his sleves.

**Comment by seanmcl** [comment]
Fine by me. I consider the issue resolved, and look forward to trying the new planner.
