### ISSUE TITLE
Un-inlined definition of a constructor in z3++.h

### ISSUE THREAD

**Issue by kix6lj** [Z3Prover/z3#6193]
There is a un-inlined constructor of `constructor_list` in z3++.h. When z3++.h is included in multiple sources, this causes a "multiple definition" error. Inline the definition should solve the problem.

**Comment by sjunges** [comment]
Just to confirm, I run into the same issue when linking against z3 with 4.10.1, but not with 4.9.1.

**Comment by ekilmer** [comment]
Relevant comment here about the same issue in vcpkg while building Triton https://github.com/Z3Prover/z3/commit/5b219aab76a7443687d4a36846eaa80e43dfe348#r79292178
