### ISSUE TITLE
Memory leaks on exception

### ISSUE THREAD

**Issue by rhelmot** [Z3Prover/z3#6197]
### Discussed in https://github.com/Z3Prover/z3/discussions/6184

<div type='discussions-op-text'>

<sup>Originally posted by **rhelmot** July 21, 2022</sup>
Whenever a check is interrupted by a call to interrupt(), a timeout, or even a memory limit, it seems like z3 leaks an awful lot of memory. Presumably this is because it is managing raw pointers on the stack and they are not being destroyed on unwind. Is this sort of thing considered a bug, or should I be running z3 in a separate process if I want to be able to recover from exceptional cases like this?</div>

Reproduction script for the above issue:

```python
#!/usr/bin/env python3

import z3

for rounds, limit in reversed([(100, 500), (3, 32), (2, 32)]):
    s = z3.Solver()
    a = z3.BitVec('a', 32)
    for i in range(rounds):
        b = z3.BitVec('b' + str(i), 32)
        a = (a + b - (b / z3.BitVecVal(3, 32))) ^ z3.RotateRight(b, 17)
    s.add(a == 1234)
    s.set(max_memory=limit)
    print(s.check())
```

This script produces `sat sat unknown`. However, when you remove the `reversed`, it produces `unknown unknown unknown`, indicating that the memory from the largest solve is being leaked.

**Comment by rhelmot** [comment]
I did some more testing and found that I'm full of shit - moving each solver to its own context causes everything to work correctly, and bumping the 500mb memory limit to 600mb in the one-context case makes the results `sat unknown unknown`, which indicates that there is no memory leak, just context-global cached data. Let's move discussion back to #6184.

**Comment by NikolajBjorner** [comment]
It is very likely that there can be leaks: memory allocation throws exceptions and then intermediary allocations are garbage. 
My attempted repro didn't show anything:

```

#include "z3++.h"
#include <iostream>

void run(unsigned rounds, unsigned limit) {
    z3::context c;
    z3::solver s(c);
    auto a = c.bv_const("a", 32);
    for (unsigned i = 0; i < rounds; ++i) {
        std::string name;
        name += "b";
        name += std::to_string(i);
        auto b = c.bv_const(name.c_str(), 32);
        a = (a + b) - (b / c.bv_val(3, 32)) ^ b.rotate_right(17);
    }
    s.add(a == 1234);
    s.set("max_memory", limit);
    std::cout << s.check() << "\n";
}

int main() {
    run(3, 26);
    run(3, 26);
    run(4, 32);
    run(5, 32);
    run(6, 32);
    run(7, 31);

    run(3, 32);
    return 0;
}

```

but perhaps because of the local contexts.
(debugging pure C++ code is easier from VS)
