### ISSUE TITLE
How to run Z3 in parallel?

### ISSUE THREAD

**Issue by WuHao1988** [Z3Prover/z3#620]
I want to check a  formula by Z3 faster，So
Does Z3 suport parallel? And how?

**Comment by NikolajBjorner** [comment]
It does not expose parallel solving, only parallel disjoint tactics that try different strategies (and don't interoperate).

**Comment by wintersteiger** [comment]
See also the par-or example in the [strategies tutorial](http://rise4fun.com/Z3/tutorial/strategies).

**Comment by WuHao1988** [comment]
OK thank you
