### ISSUE TITLE
Storing Z3 expressions inside python sets and maps is quite slow

### ISSUE THREAD

**Issue by dwightguth** [Z3Prover/z3#6200]
One thing I noticed while tinkering with the python API is that if the code you are writing stores and retrieves a lot of Z3 expressions inside python sets or the keys of maps, the code is noticeably rather slow. It turns out this is because the `__eq__` method of `ExprRef` constructs a `=` expression and then the code that calls `__eq__` has to call `__bool__` which in turn calls `is_true` and `is_false` before eventually deferring to `eq`.

The ideal solution to this problem would be to make `__eq__` call `eq` directly and then create separate `Equal` and `Distinct` functions to replace the current way Z3 equalities are expressed in python. This is definitely a huge breaking change to the API, however. You might be able to get some rather sizeable performance improvements just by micro-optimizing the `__bool__` function, however, if you don't want to change the API.

**Comment by NikolajBjorner** [comment]
I am not sure how ExprRef.__eq__ would be invoked from using maps/sets. ExprRef.__eq__ creates an expression.

**Comment by dwightguth** [comment]
If you put the ExprRef in a set or as the key of a map, it gets invoked on every insert, deletion, and lookup as part of the internal implementation of hashtables.

**Comment by NikolajBjorner** [comment]
I tried to repro this, I didn't get it to hit those places

```
from z3 import *
x, y, z = Ints('x y z')
print(x.eq(y))
map = { x : 1, y : 2 }
print(z in map)
print(map[x])
print(map[y])
```

**Comment by dwightguth** [comment]
If I had to guess, the `in` invocation didn't invoke `__eq__` because the hash function hashed `z` to an empty bucket, and the map lookup invocations didn't invoke `__eq__` because `x is x` returned True, so it had no reason to call `__eq__`. That doesn't necessarily mean that `__eq__` doesn't get called in the general case to test equality inside hashtables, or that when that happens repeatedly, it's slow. Writing a custom wrapper around my expressions that delegated `__eq__` to `eq` substantially sped up the application I was testing.

**Comment by NikolajBjorner** [comment]
It happens if maps / sets can't rely on reference equality and have to call into equality.
A workaround is to use map[AstRef(e.ast)] for indexing.
