### ISSUE TITLE
User propagator reports unassigned variable during final callback

### ISSUE THREAD

**Issue by dwightguth** [Z3Prover/z3#6201]
First of all, thanks for the bug fix relating to push/pop and eq, I was actually running into it and then realized it got fixed in the latest master of z3.

However, on that same branch, when I try to run a larger example of the same python code you wrote here: https://microsoft.github.io/z3guide/programming/Programming%20Z3/Using%20Z3%20from%20Python/User%20Propagator

I actually get the result `Unassigned` during the process of solving the quantifier. I wasn't sure if maybe this was expected during certain instances of the `final` callback, so I disabled that assertion, after which I get either `unknown` or `unsat` despite the fact that the formula ought to be satisfiable.

I am attaching the python script in question, which, as I said, has been tested on the master branch of z3 (since the latest release, 4.10.1, still has outstanding issues with respect to push/pop).

Is the problem with the python script? Or is this a bug in Z3? 

Note that the python script is rather slow to run. If you want, I can provide C++ source code that makes use of the C Z3 API that you can use instead, which has much less overhead.
[bug-report.tar.gz](https://github.com/Z3Prover/z3/files/9213620/bug-report.tar.gz)

**Comment by NikolajBjorner** [comment]
Unassigned is not necessarily a bug: the datatype solver might be scheduled to later provide values.
The situation never happened with the smaller example, so I kept the bailout in place. 
You should be able to remove the bailout.

**Comment by NikolajBjorner** [comment]
I think I address this issue with the reply above.
