### ISSUE TITLE
If it's a z3py issue,  am i supposed to open an issue in some other place?

### ISSUE THREAD

**Issue by maverick-xinwei** [Z3Prover/z3#6208]
If it's a z3py issue,  am i supposed to open an issue in some other place? 

If this is the right place,  is the issue already a known one and is tracked by some other ticket?  

_Originally posted by @maverick-xinwei in https://github.com/Z3Prover/z3/issues/6206#issuecomment-1199175122_

**Comment by maverick-xinwei** [comment]
The reply in #6206 is 
> Most likely it is that z3py isn't strictly deterministic: whenever you have maps it uses different salts to initialize the hash function and the GC does not behave the same across runs.

Does it mean it's some limitation that won't be solved ?

**Comment by NikolajBjorner** [comment]
You are out of luck with deterministic repros when using Z3 over a GC'ed language (and combining hash-tables with runtime initialization salts with traversal and other features that introduce run-time dependent behavior).
For deterministic repros use C, C++ (or Rust).
