### ISSUE TITLE
"python scripts/mk_make.py" fails

### ISSUE THREAD

**Issue by 1214465750** [Z3Prover/z3#6212]
Attempted to use
python scripts/mk_make.py
 I use vs2022
![image](https://user-images.githubusercontent.com/74165863/181904708-f717ffc7-2cf5-4c40-a2c1-ed30f55edbad.png)
nothing happen 
so I use python run  mk_make.py
and then
D:\ANACONDA\python.exe D:/下载/z3-master/scripts/mk_make.py
Traceback (most recent call last):
  File "D:\下载\z3-master\scripts\mk_make.py", line 14, in <module>
    API_files = init_project_def()
  File "D:\下载\z3-master\scripts\mk_project.py", line 100, in init_project_def
    set_z3py_dir('api/python')
  File "D:\下载\z3-master\scripts\mk_util.py", line 840, in set_z3py_dir
    raise MKException("Python bindings directory '%s' does not exist" % full)
mk_exception.MKException: "Python bindings directory 'src\\api\\python' does not exist"
New component: 'util'
New component: 'polynomial'
New component: 'interval'
New component: 'dd'
New component: 'simplex'
New component: 'hilbert'
New component: 'automata'
New component: 'realclosure'
New component: 'subpaving'
New component: 'ast'
New component: 'euf'
New component: 'params'
New component: 'smt_params'
New component: 'grobner'
New component: 'sat'
New component: 'nlsat'
New component: 'lp'
New component: 'rewriter'
New component: 'macros'
New component: 'normal_forms'
New component: 'model'
New component: 'tactic'
New component: 'substitution'
New component: 'parser_util'
New component: 'proofs'
New component: 'solver'
New component: 'cmd_context'
New component: 'smt2parser'
New component: 'pattern'
New component: 'aig_tactic'
New component: 'ackermannization'
New component: 'fpa'
New component: 'bit_blaster'
New component: 'core_tactics'
New component: 'arith_tactics'
New component: 'mbp'
New component: 'qe_lite'
New component: 'solver_assertions'
New component: 'sat_smt'
New component: 'sat_tactic'
New component: 'nlsat_tactic'
New component: 'subpaving_tactic'
New component: 'proto_model'
New component: 'smt'
New component: 'bv_tactics'
New component: 'fuzzing'
New component: 'smt_tactic'
New component: 'sls_tactic'
New component: 'qe'
New component: 'sat_solver'
New component: 'fd_solver'
New component: 'muz'
New component: 'dataflow'
New component: 'transforms'
New component: 'rel'
New component: 'spacer'
New component: 'clp'
New component: 'tab'
New component: 'ddnf'
New component: 'bmc'
New component: 'fp'
New component: 'smtlogic_tactics'
New component: 'ufbv_tactic'
New component: 'fpa_tactics'
New component: 'portfolio'
New component: 'opt'
New component: 'api'
New component: 'extra_cmds'
New component: 'shell'
New component: 'test'
New component: 'api_dll'
New component: 'dotnet'
New component: 'java'
New component: 'ml'
New component: 'cpp'

**Comment by NikolajBjorner** [comment]
run it from the src directory (the directory below scripts)

```
python scripts/mk_make -x
```

**Comment by 1214465750** [comment]
sorry nothing happen
![image](https://user-images.githubusercontent.com/74165863/182005007-e1f56050-18ac-4b60-bad2-64e097949454.png)

**Comment by 1214465750** [comment]
thank you for&nbsp; your reply
however

still nothing happen




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Z3Prover/z3"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月31日(星期天) 凌晨1:02
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Z3Prover/z3] "python scripts/mk_make.py" fails (Issue #6212)





 
run it from the src directory (the directory below scripts)
 python scripts/mk_make -x
