### ISSUE TITLE
unsat core API (Java)

### ISSUE THREAD

**Issue by classicwuhao** [Z3Prover/z3#6214]
Hi, I use Z3 Java API to read in an smt2 file, and create a solver as follows
 `cfg.put("unsat_core","true");`
`Context ctx = new Context(cfg);`
`solver = ctx.mkSolver();`
`solver.add(ctx.mkAnd(ctx.parseSMTLIB2File(sample,null, null, null, null)));`
However, after solving `sample`, `solver.getUnsatCore()` returns no cores. The `sample` contains at least one unsat core, but 'solver.getUnsatCore()' always returns no cores. If I add '(set-option :produce-unsat-cores true)' to my `sample` smt2 file, solver returns 'sat' rather than 'unsat'. Remove '(set-option :produce-unsat-cores true)' returns 'unsat' as expected but no unsat core from API.

I would prefer using API to retrieve unsat cores rather than reading bytes from STDIN or STDOUT.

**Comment by NikolajBjorner** [comment]
The easiest is probably that you pass the assertions that you parse as _assumptions_ to the solver.check call.
Recall that solver.check takes optional sequence of formulas that serve the role of assumptions. 
Unsat cores are formed over these assumptions.
