### ISSUE TITLE
"python scripts/mk_make.py" fails

### ISSUE THREAD

**Issue by 1214465750** [Z3Prover/z3#6215]
Attempted to use
python scripts/mk_make.py
I use vs2022
![image](https://user-images.githubusercontent.com/74165863/182054614-7e14acea-9edf-435f-8438-9a8ecaa32f0b.png)
I run it from the src directory
however nothing happen

**Comment by 1214465750** [comment]
1

**Comment by NikolajBjorner** [comment]
Check your python installation?
You can always just download the z3 release instead of trouble shooting.

**Comment by waywardmonkeys** [comment]
@1214465750 You might also give building with cmake a try.
