### ISSUE TITLE
getting Z3 version 

### ISSUE THREAD

**Issue by classicwuhao** [Z3Prover/z3#6218]
Hi, I don't know if `Version.getString()` (Java API) method has been disabled but I am getting the following message: 

libz3java.so: undefined symbol: Z3_get_version.

It works fine for both Windows and MacOS, but fails to retrieve z3 version on linux (Ubuntu 20.04)
Don't if this is a bug or not or `Z3_get_version` disabled intentionally on linux. This has been appearing since version 4.9.2.0

**Comment by waywardmonkeys** [comment]
I'm using cmake, so on current `master`, I had to do a couple of extra steps for things that aren't in the cmake build system, but after that, I got this when running the `examples/java/JavaExample.java`:

```
Z3 Major Version: 4
Z3 Full Version: 4.11.0.0
Z3 Full Version String: 4.11.0.0 fe1e3017354768e7761ad1db0805fb54b5d4f333 z3-4.8.4-6540-gfe1e30173
```

And apart from that, it looked like things were wired up correctly and haven't changed ... is your code finding the right `libz3.so` and loading it correctly?

If so, check things like: `ldd -r libjava.so` to see what `libz3.so` it is pointing to ... and check `nm libz3.so | grep Z3_get_version` to make sure it is defined ...

**Comment by classicwuhao** [comment]
I just recompiled z3 and getting the same message. I change `export LD_LIBRARY_PATH=.` to the current directory where libz3.so is. Major version, Full Version, etc all is fine except for `Version.getString()`. My cmake version is 3.16.3 Don't know where went wrong, it was all fine till 4.9.2.0. If I replace it with older version libz3.so say 4.18.0 it is fine.

**Comment by waywardmonkeys** [comment]
That's odd though ... `src/api/java/Version.java` hasn't changed in years, and `Version.getString` is implemented as:

```
    public static String getString()
    {
        Native.IntPtr major = new Native.IntPtr(), minor = new Native.IntPtr(), build = new Native.IntPtr(), revision = new Native.IntPtr();
        Native.getVersion(major, minor, build, revision);
        return Integer.toString(major.value) + "." + Integer.toString(minor.value) + "."
                + Integer.toString(build.value) + "." + Integer.toString(revision.value);
    }
```

And `Version.getMajor` is implemented as:

```
    public static int getMajor()
    {
        Native.IntPtr major = new Native.IntPtr(), minor = new Native.IntPtr(), build = new Native.IntPtr(), revision = new Native.IntPtr();
        Native.getVersion(major, minor, build, revision);
        return major.value;
    }
```

So they're both calling into `Native.getVersion`, which calls `Z3_get_version`:

```
DLL_VIS JNIEXPORT void JNICALL Java_com_microsoft_z3_Native_INTERNALgetVersion(JNIEnv * jenv, jclass cls, jobject a0, jobject a1, jobject a2, jobject a3) {
  unsigned _a0;
  unsigned _a1;
  unsigned _a2;
  unsigned _a3;
  Z3_get_version(&_a0, &_a1, &_a2, &_a3);
  {
     jclass mc    = jenv->GetObjectClass(a0);
     jfieldID fid = jenv->GetFieldID(mc, "value", "I");
     jenv->SetIntField(a0, fid, (jint) _a0);
  }
  {
     jclass mc    = jenv->GetObjectClass(a1);
     jfieldID fid = jenv->GetFieldID(mc, "value", "I");
     jenv->SetIntField(a1, fid, (jint) _a1);
  }
  {
     jclass mc    = jenv->GetObjectClass(a2);
     jfieldID fid = jenv->GetFieldID(mc, "value", "I");
     jenv->SetIntField(a2, fid, (jint) _a2);
  }
  {
     jclass mc    = jenv->GetObjectClass(a3);
     jfieldID fid = jenv->GetFieldID(mc, "value", "I");
     jenv->SetIntField(a3, fid, (jint) _a3);
  }
}
```

So ... it is odd that `Version.getMajor` would work while `Version.getString` would fail with an error about an undefined symbol ...

**Comment by classicwuhao** [comment]
I don't know what exactly cause this but I don't think it has to do with source code. Possibly the build system. I have just tested the following versions (by downloading .so files from release without recompiling source myself).

4.9.0 - fine
4.9.1 - fine
4.9.2 - libz3java.so: undefined symbol: Z3_get_version.
4.10.0 - libz3java.so: undefined symbol: Z3_get_version.
4.10.1 - libz3java.so: undefined symbol: Z3_get_version.
4.10.2 - libz3java.so: undefined symbol: Z3_get_version.

All is tested on ubuntu 20.04 (local machine). For Windows, and MacOS, they look fine ( based on my own project CI on github).

**Comment by waywardmonkeys** [comment]
Okay, so I'm pulling releases from github and I've found something interesting:

```
$ ldd z3-4*/bin/libz3java.so
z3-4.10.2-x64-glibc-2.31/bin/libz3java.so:
	linux-vdso.so.1 (0x00007ffcb7f40000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f34c6e36000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f34c7080000)
z3-4.9.0-x64-glibc-2.31/bin/libz3java.so:
	linux-vdso.so.1 (0x00007ffcea360000)
	libz3.so => /lib/x86_64-linux-gnu/libz3.so (0x00007f1d1f536000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f1d1f344000)
	libstdc++.so.6 => /lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f1d1f162000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f1d1f013000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f1d1eff8000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f1d1efd5000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f1d20b2e000)
```

so, something changed in how it is built / linked for the release on Linux where the `libz3java.so` is not correctly linking against `libz3.so` any longer ...

This might need someone else's input as to how those artifacts are created, etc.

**Comment by NikolajBjorner** [comment]
This line:

[                out.write('\t$(SLINK) $(SLINK_OUT_FLAG)libz3java$(SO_EXT) $(SLINK_FLAGS) $(SLINK_EXTRA_FLAGS) %s$(OBJ_EXT) libz3$(SO_EXT)\n' %](https://github.com/Z3Prover/z3/blob/2c2ab0d57a5aed0480dda3e0d98ae4c2590d35ba/scripts/mk_util.py#L1834)

was changed to include $(SLINK_EXTRA_FLAGS) recently.

**Comment by waywardmonkeys** [comment]
If `SLINK_EXTRA_FLAGS` is picking up `SLIBEXTRAFLAGS`, then on Linux and FreeBSD, it would be getting:

```
             SLIBEXTRAFLAGS = '%s -Wl,-soname,libz3.so' % SLIBEXTRAFLAGS
```

Which wouldn't be correct for linking `libz3java.so`

That change was done for #5848 for macOS ... maybe it would be better if we got the distributed binaries to be built with cmake instead of the legacy build system?

**Comment by NikolajBjorner** [comment]
The CMAKE system would be much preferred. The use of legacy python make is due to stickiness. 
The release scripts were never upgraded. Mainly as it is an area I have low competencies.
They are also required for ocaml/linux.

**Comment by waywardmonkeys** [comment]
The homebrew formula on macOS also uses the legacy scripts as well. Let's track this somewhere outside of this bug and I can help. I'm good at this.

**Comment by NikolajBjorner** [comment]
>  I'm good at this.

That did not escape my attention

**Comment by classicwuhao** [comment]
Thanks guys, let me know if you need extra help. I can also help on this.

**Comment by waywardmonkeys** [comment]
@NikolajBjorner pushed 774ce3d7ab40ce3e77587882b3aa72db9d0e5d3d which looks to me like it should fix it.

There's probably somewhere that has the build artifacts available, so I'll let him say if that's the case or not. Otherwise, it looks like it should be fixed in the next release.

**Comment by classicwuhao** [comment]
Yes, that line should fix the problem.
