### ISSUE TITLE
Segmentation fault with (check-sat-using (par-or qflia smt))

### ISSUE THREAD

**Issue by dstaple** [Z3Prover/z3#623]
Calling Z3 on this SMT-LIB 2 input will cause a segmentation fault:
```
(declare-fun n () Int)
(assert (not (< n 1)))
(check-sat-using (par-or qflia smt))
```
The message with the current version of the master branch is:
```
NOT IMPLEMENTED YET!
Segmentation fault (core dumped)
```
Recompiling a debug build with CMake gives more information:
```
dstaple@gloucester:~/z3/build$ ./z3 ~/segfault.smt2
NOT IMPLEMENTED YET!
ASSERTION VIOLATION
File: /home/dstaple/z3/src/tactic/arith/pb2bv_model_converter.cpp
Line: 101
UNREACHABLE CODE WAS REACHED.
(C)ontinue, (A)bort, (S)top, (T)hrow exception, Invoke (G)DB
```

I've verified that this error is present on the following systems:
1)
Z3 master, also Z3 4.4.1
Ubuntu 14.04.4 LTS
6-core i7 with hyperthreading

2)
Z3 4.4.1
Fedora Core 22
2-core i5 with hyperthreading

Surprisingly (to me) the bug does not manifest on a third system:
3)
Z3 4.4.1
OS X 10.9.5
2-core i5 with hyperthreading

**Comment by wintersteiger** [comment]
Thanks for the report! AST translation for the pb2bv model converter was missing, but it's now been added and the example works as expected.

**Comment by dstaple** [comment]
Thanks, nice work!
