### ISSUE TITLE
Segfault on smt2 input

### ISSUE THREAD

**Issue by jcreedcmu** [Z3Prover/z3#624]
Running z3 on 
https://gist.github.com/jcreedcmu/447b068508d2b784446f898951ff6012
(same as https://github.com/Z3Prover/z3/issues/619 I am running on OSX, on commit c20b391cf78)
gives a segfault.

I haven't compiled with `-g` so all I have from gdb at the moment is that it's happening in `ast_manager::mk_app(func_decl*, unsigned int, expr* const*) ()`

**Comment by seanmcl** [comment]
Reproduced on Ubuntu 16.04

**Comment by NikolajBjorner** [comment]
Thanks, 

For reference:

z3 dl.smt2 /tr:dl
ASSERTION VIOLATION
File: ..\src\muz\transforms\dl_mk_unbound_compressor.cpp
Line: 195
UNREACHABLE CODE WAS REACHED.

The code probably does not anticipate clauses that only have negative predicates in the body or something along those lines. I will look probably Saturday.

**Comment by jcreedcmu** [comment]
Ah, interesting. I realize that I indeed am outside the traditional datalog fragment by having those only negated literals. However, I observe
```
(set-option :fixedpoint.engine datalog)

(define-sort state () (_ BitVec 2))
(define-fun state0 () state #b00)

(define-sort token () (_ BitVec 1))
(define-fun token0 () token #b0)

(define-sort az () (_ BitVec 2))
(define-fun az0 () az #b00)

(declare-rel az-ok (az))

(rule (forall ((Az az)) (az-ok Az)))

(declare-rel fol$0 (az az))
(rule (forall ((X1 az) (X2 az))
  (=> (not (az-ok X2)) (az-ok X2)
      (fol$0 X1 X2))))
(rule (forall ((X1 az) (X2 az))
  (=> (not (az-ok X1)) (az-ok X1)
      (fol$0 X1 X2))))

(declare-rel foo (token))
(rule
 (forall ((A az) (B az))
         (=> (fol$0 A B)
             (not (fol$0 A B))
             (foo token0))))

(query foo)
```
still segfaults for me.
```shell
$ ../z3  db.z3 verbose=100
(query)
(transform N7datalog13mk_coi_filterE...no-op 0s)
(transform N7datalog25mk_interp_tail_simplifierE...no-op 0s)
(transform N7datalog15mk_rule_inlinerE...no-op 0s)
(transform N7datalog34mk_partial_equivalence_transformerE...no-op 0s)
(transform N7datalog25mk_separate_negated_tailsE...no-op 0s)
(transform N7datalog24mk_similarity_compressorE...no-op 0s)
(transform N7datalog15mk_filter_rulesE...no-op 0s)
(transform N7datalog15mk_simple_joinsE...no-op 0s)
(transform N7datalog21mk_unbound_compressorE...Segmentation fault: 11
```

**Comment by NikolajBjorner** [comment]
This bug is now fixed.

**Comment by jcreedcmu** [comment]
Thanks for the very quick response!
