### ISSUE TITLE
python mk_api_doc.py fail

### ISSUE THREAD

**Issue by 1214465750** [Z3Prover/z3#6240]
I install doxygen ,however
![image](https://user-images.githubusercontent.com/74165863/182580306-ab72fd23-a607-40a1-afa6-1169f712d83d.png)

by the way,how to use z3 on c++,is there any example or course?

**Comment by waywardmonkeys** [comment]
Is `doxygrn` on the path?

**Comment by NikolajBjorner** [comment]
Go instead to 
https://z3prover.github.io/api/html/index.html
