### ISSUE TITLE
Seg fault with par-or on QFNIA problem

### ISSUE THREAD

**Issue by dstaple** [Z3Prover/z3#625]
The following seg faults approximately 50% of the time on my 6-core Ubuntu 14.04 system with Z3 master:
```
(declare-fun x () Int)
(declare-fun y () Int)
(assert (= y (abs x)))
(assert (distinct y (abs x)))
(check-sat-using (par-or
    smt smt smt smt smt
    smt smt smt smt smt
    smt smt smt smt smt
))
```
The above is the best I've found to minimize the problem and maximize the probability of the seg fault.  With a current debug build, the messages are:
```
dstaple@gloucester:~$ ./z3/build/z3 segfault_par-or_qfnia_2016_05_27_2046.smt2
ASSERTION VIOLATION
File: /home/dstaple/z3/src/smt/smt_internalizer.cpp
Line: 219
UNREACHABLE CODE WAS REACHED.
(C)ontinue, (A)bort, (S)top, (T)hrow exception, Invoke (G)DB
```
Again, the seg fault does _not_ occur on my dual-core OS X machine.  I'm sorry that I haven't managed to distill something that fails 100% of the time.

On the meta-level, my impression is that both the strategy API and specifically the parallel combinators are not as mature as the rest of Z3.  My suspicion is that there are a lot of opportunities for seg faults and the like in this part of the code.  I don't want to overflow you folks with bug reports.  Nonetheless, I'm happy to fill out bug reports at a controlled rate, if this is constructive to you.

**Comment by NikolajBjorner** [comment]
It was easy to repro. The bug appears to be about properly detecting cancellation and recovering from this. Cancellation causes some of the simplifications to be bypassed and then the internalizer sees formulas it does not expect. A more reliable repro is to use the resource limit feature and pound on that., 
The multi-threaded piece wasn't bug free in the past, but I have addressed any issues we were
made aware of. 
There is always the question about dealing with incoming bug-rates. The more a reporter can do to narrow the cause and even suggest fixes the better.
