### ISSUE TITLE
"double free or corruption (fasttop)" error when running multiple threads

### ISSUE THREAD

**Issue by cheshire** [Z3Prover/z3#626]
Hi,

This is probably going to be another "hard to reproduce" bug, but I would like to file it for reference (and maybe to figure out a better way to communicate failures).

Using JavaSMT I was testing running solvers with multiple threads, and I get the bug shown in the issue title when running the following piece of code:

``` java
  private class SolverRunner extends Thread {
    @Override
    public void run() {
      try {
        // Creates a new Z3 context.
        SolverContext localContext = factory.generateContext(solverToUse());
        for (int i=0; i<5; i++) {
          try (ProverEnvironment pe = localContext.newProverEnvironment()) {
            Fuzzer f = new Fuzzer(localContext.getFormulaManager(), new Random(i));
            pe.push(f.fuzz(10000, 3));
            pe.isUnsat();
          }
        }
      } catch (InvalidConfigurationException|InterruptedException|SolverException pe3) {
        throw new UnsupportedOperationException("Fail");
      }
    }
  }

  @Test
  public void testMultithreading() throws InterruptedException {
    List<Thread> threads = new ArrayList<>();
    int noThreads = 4;
    for (int i=0; i<noThreads; i++) {
      threads.add(new SolverRunner());
    }
    threads.forEach(Thread::start);
    for (Thread t : threads) {
      t.join();
   }
 }
```

Though the JavaSMT API is used, I think the intent is obvious: fuzzer generates a random formula, and then it's checked for satisfiability.
Due to interleavings, the failure is non-deterministic and happens about 1/2 of the time.

**Comment by cheshire** [comment]
Java gives me the following log: http://metaworld.me/error_report.log

**Comment by wintersteiger** [comment]
This seems to be related to the resource limits as the segfault happens in reslimit::set_cancel; possibly also related to #625 which was fixed very recently.

**Comment by NikolajBjorner** [comment]
Is this a continuation of #595? In case it would help with the Z3 log file (not java dump) because I can set rlimit to increasing values and use this to weed out bugs. Sure, I can also set up my own fuzzing and do this, but it would speed up things and save some bandwidth and also ensure that we cover what you care about.

**Comment by cheshire** [comment]
@NikolajBjorner Are writes to Z3 log file serialized correctly in the presence of multiple threads?

**Comment by NikolajBjorner** [comment]
I assume you are of course using separate contexts. So before allocating the separate context, open a separate log file. I was also assuming that you call interrupts asynchronously per #595.

**Comment by NikolajBjorner** [comment]
I should stand corrected: the log files have no thread affinity so you can't open multiple log files. 
Furthermore, logging is not atomic so it will all be garbled. Using logging in multi-threaded contexts, whether internal multi-threading or external is not going to work.

Still, just checking: you are not using the same context in different threads?
This is unsafe.

**Comment by cheshire** [comment]
@NikolajBjorner no, the call `factory.generateContext(solverToUse())` in the code above creates a new Z3 context.

**Comment by NikolajBjorner** [comment]
this isn't going to be reproducible with current bits. Open a new bug for fresh instances. 
Multi-threading still depends on OMP, which is not enabled on some OSX setups.
