### ISSUE TITLE
Some ill-typed terms cause no error

### ISSUE THREAD

**Issue by AdrienChampion** [Z3Prover/z3#6273]
I'm not sure what's going on, but this is not expected, right?

```smt
; test.smt2
(declare-fun boolean () Bool)

(assert
    (<= 0 boolean)
)

(check-sat)
(get-model)
```

```
> z3 test.smt2
sat
(
  (define-fun boolean () Bool
    false)
)
> z3 -version
Z3 version 4.10.2 - 64 bit
```

I get this behavior on macos 12.4 (Apple M1) in case that's relevant.

Changing `0` to, for instance, `2` causes z3 to answer `unsat`.

**Comment by NikolajBjorner** [comment]
z3 inserts coercions automatically for Booleans in such contexts.
The coercion is into "(if boolean 1 0)" as you can expect.
It makes writing down Pseudo-Boolean constraints much easier.

**Comment by AdrienChampion** [comment]
Thank you for the answer, I guess I missed it in the release notes 🐱

**Comment by NikolajBjorner** [comment]
It was in the release notes of STeP in 1994.

**Comment by AdrienChampion** [comment]
> It was in the release notes of STeP in 1994.

Feel free to ignore this as it's not very important, but I don't understand. This coercion is relatively new in Z3, isn't it?

```
❯ cat test.smt2
(declare-fun boolean () Bool)

(assert (<= 0 boolean))

(check-sat)
(get-model)

❯ ./z3 -version
Z3 version 4.8.12 - 64 bit

❯ ./z3 test.smt2
(error "line 3 column 21: Sort mismatch at argument #2 for function (declare-fun <= (Int Int) Bool) supplied sort is Bool")
sat
(
  (define-fun boolean () Bool
    false)
)
```

I had tests in [rsmt2](https://github.com/kino-mc/rsmt2) for quite a while that actually check for this behavior (though with `=` instead of `<=`).

**Comment by NikolajBjorner** [comment]
relatively new in z3. It isn't SMTLIB standard but treating Bool as 0/1 is very common many other places.

**Comment by AdrienChampion** [comment]
Oh I see, sorry for the confusion. Thank you for the explanation!
