### ISSUE TITLE
Performance regression (mod/div)

### ISSUE THREAD

**Issue by saltion** [Z3Prover/z3#6286]
Hi, the following does not seem to not terminate in 4.11.0, but it instantly returns sat in 4.10.2:

```
(set-logic QF_LIA)
(declare-fun a () Int)
(declare-fun b () Int)
(assert (or (< (mod a 710) (mod a (- 375))) (>= (mod a (- 441)) (div a 214))))
(assert (not (xor (not (< (+ b a) (div b (- 232)))) (= (mod a 249) (mod b 990)))))
(check-sat)
(exit)
```

**Comment by NikolajBjorner** [comment]
it never performed well in average. 
Set smt.arith.branch_cut_ratio=100 or similar to avoid the expensive cuts. Overall, the cut strategy would need to be tuned, but it is not a regression.
