### ISSUE TITLE
Performance regression on trivial floating point solve

### ISSUE THREAD

**Issue by rhelmot** [Z3Prover/z3#6294]
The following smt2 file (trying to solve sqrt(x) == 2.0) solves in about 5 seconds on z3 4.10.2.0 but takes at least 5 minutes (I have never observed it terminate) on z3 4.11.0.0:

```
(declare-fun FP_v_0_32 () (_ FloatingPoint 8 24))
(check-sat
(fp.eq (fp.sqrt roundNearestTiesToEven FP_v_0_32)
       (fp #b0 #x80 #b00000000000000000000000)))
```

I know in the past you've said that there are no performance guarantees in terms of this stuff, but this seems like something nastier than just a seed changing and the solver no longer getting lucky.

**Comment by nunoplopes** [comment]
Fixed by https://github.com/Z3Prover/z3/commit/916d1dbb137cb5192ec9099f1e5487c68844fbed AFAICT

**Comment by nunoplopes** [comment]
(I also caught this regression in Alive2's benchmarks)
