### ISSUE TITLE
z3 cannot solve some problems

### ISSUE THREAD

**Issue by zxt539** [Z3Prover/z3#6298]
I am trying to use z3 solve some smt problems. Some problems are satisfiable only if the sort is infinite, for example:
```
(declare-sort A 0)
(declare-fun F (A) A)
(declare-const a0 A)
(assert (not (exists ((a A)) (= (F a) a0) ) ) )
(assert (forall  ((a A) (b A)) (or (= a b) (not (= (F a) (F b))))  ) )
(check-sat)
```
But z3 cannot solve this problem, another example z3 cannot solve:
```
(declare-fun F (Int) Int)  
(assert (forall ((x Int) (y Int)) (or (= x y) (not (= (F x) (F y))))))
(check-sat)
```
Obviously, f(x) = x + 1 is a model to satisfy this problem.
So I want to ask about the reason that z3 got stuck on these problems, and is there any features to tell if z3 can solve a certain problem?

**Comment by NikolajBjorner** [comment]
Se bottom of this page:

https://microsoft.github.io/z3guide/docs/logic/Quantifiers

**Comment by zxt539** [comment]
thanks!
