### ISSUE TITLE
Not installable via `pip` or `easy_install`

### ISSUE THREAD

**Issue by zachriggle** [Z3Prover/z3#63]
It seems that it should not be impossible for Z3 to be available in an automatable, one-click manner via PyPI.  Native libraries and extensions can be built on-target for all operating systems, Linux and OSX being the easiest among them.

Are there any plans to make Z3 available via PyPI?

**Comment by wintersteiger** [comment]
It's impossible for us to maintain packages in all relevant package repositories, so early on we decided to treat everybody equally and thus not to maintain packages for any of them. With the recent change in license, it is possible for others to publish packages for their respective community, so if anybody would like to volunteer some of their time for this task, we'd be very supportive and happy!

**Comment by wintersteiger** [comment]
Superseded by #288, so I'll close this issue.
