### ISSUE TITLE
z3 hangs when push/pop is used

### ISSUE THREAD

**Issue by SeanHeelan** [Z3Prover/z3#632]
Hi,

I've come across the following issue in z3 (built from master/HEAD): when solving the following formula, z3 prints 'unsat' immediately on the first check-sat call, but then hangs on the second one. STP is able to quickly generate an unsat result for both, and I don't think the issue is one of complexity in the formula itself. 

```
(set-logic QF_BV)

(declare-const ZERO32 (_ BitVec 32))
(assert (= ZERO32 #x00000000))
(declare-const MAXU32 (_ BitVec 64))
(assert (= MAXU32 #x00000000ffffffff))

(declare-fun elementByteSize () (_ BitVec 32))
(declare-fun numElements () (_ BitVec 32))
(declare-fun div_res () (_ BitVec 32))
(declare-fun totalSize () (_ BitVec 32))
(declare-fun big_ElementByteSize () (_ BitVec 64))
(declare-fun big_NumElements () (_ BitVec 64))
(declare-fun calloc_size () (_ BitVec 64))

(assert (not (= elementByteSize ZERO32)))

(assert (and
	(= big_NumElements ((_ zero_extend 32) numElements))
	(= big_ElementByteSize ((_ zero_extend 32) elementByteSize))
	(= calloc_size (bvmul big_NumElements big_ElementByteSize))
	(bvugt calloc_size MAXU32)
))

(push)
(assert (= numElements ZERO32))
(check-sat)

(pop)
(assert (and
	(not (= numElements ZERO32))
	(= totalSize (bvmul numElements elementByteSize))
	(= div_res (bvudiv totalSize numElements))
	(= div_res elementByteSize)
))
(check-sat)
```

If I'm doing something obviously wrong let me know =) 

Thanks,
Sean

**Comment by NikolajBjorner** [comment]
Fine example that shows that one can do better with equality propagation in incremental mode. Reasoning with bvmul and bvudiv and bvrem is super expensive.
In non-incremental mode (pass the two check-sat in separate files) Z3 does much better.

**Comment by SeanHeelan** [comment]
Hi Nikolaj,

I didn't realise incremental mode would have drastically different behaviour in this instance. Thanks for the explanation!
