### ISSUE TITLE
Unneeded ToReal cast in the python pow operator

### ISSUE THREAD

**Issue by tpaviot** [Z3Prover/z3#6328]
```python
>>> from z3 import *
>>> x, y, z = Ints('x y z')
>>> s = Solver()
>>> s.add(y == x ** 2)
>>> s.add(z == x * x)  # same assertion under an expanded form
>>> s
[ToReal(y) == x**2, z == x*x]
```
As far as I understand, the pow operator uncondionnaly casts the result to the Real type. However, if both x and the exponent are integers, there's no need for this cast since the result actually *is* an integer. Or did I miss something ?

**Comment by NikolajBjorner** [comment]
```
1 ** -2
```
is a fraction so the type of pow cannot be int.

**Comment by tpaviot** [comment]
Thank you for your answer. Of course it cannot be int in general, but here the exponent is > 0, and in this specific case the result is an int. My concern is that the ToReal cast might affect the solver performances (in terms of memory consumption and/or time), am I wrong ?

**Comment by NikolajBjorner** [comment]
arguments can be arbitrary terms not constants. The signature of a function, for simple types, is fixed across all arguments of the same type.
