### ISSUE TITLE
Internalization of exists is not supported

### ISSUE THREAD

**Issue by Joshua27** [Z3Prover/z3#6330]
Hi,
I noted a performance regression when solving lambda functions that have an existential quantifier on the top-level.
The behavior started to change from version 4.8.15.
For instance, Z3 4.8.14 is able to prove the following formula's unsatisfiability:
```
(declare-fun A () (Array Int Bool))
(assert
 (let ((?x29 (lambda ((__RANGE_LAMBDA__ Int) )(exists ((x Int) )(let (($x22 (select A x)))
 (and $x22 (= __RANGE_LAMBDA__ (* x 1)))))
 )
 ))
 (let (($x30 (= A ?x29)))
 (let (($x31 (not $x30)))
 (let ((?x6 ((as const (Array Int Bool)) false)))
 (let ((?x9 (store ?x6 0 true)))
 (let (($x10 (= A ?x9)))
 (let (($x7 (= A ?x6)))
 (let (($x11 (or $x7 $x10)))
 (and $x11 $x31))))))))))
(check-sat)
```
The formula cannot be solved with Z3 version 4.8.15 up to version 4.11.2.
Z3 answers "unknown" and states that an "internalization of exists is not supported".

I know that Z3 is not particularly tailored towards solving such formulas. Yet, I am wondering why the behavior has changed.

Is it possible to add support for the internalization of an existential quantifier on the top-level of a lambda function?
Is this more difficult than internalizing a universal quantifier?

Kind regards,
Joshua

**Comment by NikolajBjorner** [comment]
> Is it possible to add support for the internalization of an existential quantifier on the top-level of a lambda function?
it is possible, but requires testing and debugging

**Comment by Joshua27** [comment]
Do you know why Z3 version 4.8.14 doesn't need to internalize the existential quantifier but version 4.8.15 and later does?
It seems to be needed more often now. Maybe this can easily be improved since it used to work.

**Comment by NikolajBjorner** [comment]
nested existentials under lambdas were not tested and not sound in earlier versions.
