### ISSUE TITLE
Query regarding unknown symbols in the interpolant

### ISSUE THREAD

**Issue by mayanksolanki393** [Z3Prover/z3#6335]
reproducible on Z3 version 4.4.1

I am using an earlier version of z3 that supports interpolation queries. The problem is that the output of `(get-interpolant *)` call contains some unknown/unexpected symbols. For example in the interpolant given below. I cannot figure out what `@sum`,`@rotsum`,`@contra` etc refer to. As per my understanding of the syntax they should be some kind of operations. However, I am not able to find anything about it on the z3 guide or online.

```
...
(let ((a!1 (@sum (<= 2 (+ (* 3 SIV@9593) (* (- 8) SIV@9669) (* 5 SIV@9557)))
                 1
                 @p!101))
      (a!3 (<= (- 2)
               (+ (* 3 SIV@8717)
                  (* (- 1) SIV@8852)
                  (* (- 1) SIV@8964)
                  SIV@9123
                  (* (- 1) SIV@9199)
                  SIV@9358
                  (* (- 1) SIV@9434)
                  SIV@9669))))
(let ((a!2 (@rotsum (<= (- 12)
                        (+ (* 24 SIV@8717)
                           (* (- 8) SIV@8852)
                           (* (- 8) SIV@8964)
                           (* 8 SIV@9123)
                           (* (- 8) SIV@9199)
                           (* 8 SIV@9358)
                           (* (- 8) SIV@9434)
                           (* 8 SIV@9669)))
                    a!1)))
(let ((a!4 (and (@contra (@sum a!2 8 @p!102) false)
                (@contra (@rotsum a!3 (@sum a!2 8 @p!102)) a!3))))
  (or (= SIV@9593 SIV@9632)
      (not SIV@9514)
      (<= (- 1) (+ (* (- 1) SIV@8756) SIV@9593))
      (not (= SIV@9632 SIV@8756))
      a!4))))
```

Please find below the input .smt2 file and its respective result.

[input.smt2.txt](https://github.com/Z3Prover/z3/files/9535184/input.smt2.txt)
[output.txt](https://github.com/Z3Prover/z3/files/9535185/output.txt)

**Comment by NikolajBjorner** [comment]
there is no support for previous versions of z3
