### ISSUE TITLE
z3 says "sat" for query with variables, but "unsat" when vars are instantiated with solution

### ISSUE THREAD

**Issue by jcreedcmu** [Z3Prover/z3#634]
Consider the following program:
```
(define-sort az () (_ BitVec 1))
(define-fun az0 () az #b0)
(define-fun az1 () az #b1)

(define-sort instance () (_ BitVec 1))
(define-fun i0 () instance #b0)

(declare-rel a/az (az))
(rule (a/az az0))
(rule (a/az az1))

(declare-rel a/instance (instance))
(rule (a/instance i0))

(declare-rel test-one (az))
(declare-rel test-two (az instance))


(rule (forall ((X1 az) (Y instance))
              (=> (and (not (test-two X1 Y))
                       (a/az X1))
                  (test-one X1))))
(rule (forall ((X1 az) (X2 instance))
              (=> (and
                   (a/az X1)
                   (a/instance X2))
                  (test-two X1 X2))))

(declare-rel out (az))
(declare-var Var az)
(rule (=> (test-one Var) (out az0)))
(query out :print-answer true)

(declare-rel out2 (az))
(rule (=> (test-one az0) (out2 az0)))
(query out2)
```

If I run z3 against it I get 
```
sat
(= (:var 0) #b0)
unsat
```

Which I find surprising. It's telling me that `test-one Var` has one solution for `Var`, namely `az0`, but if I query that specific solution, it doesn't accept it. Is this a bug, or something wrong with my expectations?

**Comment by jcreedcmu** [comment]
@seanmcl reminded me to try adding
```
(set-option :fixedpoint.engine datalog)
(set-option :fixedpoint.xform.inline_eager false)
```
but the behavior remains the same.

**Comment by NikolajBjorner** [comment]
seems like the filtering transformations are unsound under negations.

**Comment by seanmcl** [comment]
Is there any way to turn them off with options?

**Comment by seanmcl** [comment]
Thanks for the ridiculously quick fix.  I left a comment earlier but didn't see your commit.

**Comment by NikolajBjorner** [comment]
I submitted what I believe is a fix.

We don't have a flag to disable the filter transformation, furthermore the join phase makes some assumptions that this transformation was used.
