### ISSUE TITLE
Incorrect range of array when queried through Java API

### ISSUE THREAD

**Issue by kevin-dp** [Z3Prover/z3#6344]
I'm querying the domain and range of arrays using the Java API (tested on Z3 4.8.14.0 and Z3 4.11.2.0) from Scala.
But the range seems wrong for multidimensional arrays:

```
val ctx = new Context()
val arrSort: ArraySort[_, _] = ctx.mkArraySort[IntSort](Array(ctx.mkIntSort(), ctx.mkIntSort()), ctx.mkIntSort())
val dom = arrSort.getDomain()
val range = arrSort.getRange()
println(s"sort: $arrSort\ndomain: $dom\nrange: $range")
```

The above snippet prints:

> sort: (Array Int Int Int)
> domain: Int
> range: Int

The array is basically a function from Integer to Integer to Integer and so the printed sort is correct.
However, when querying the domain and range it says it is a function from Int to Int, which it is not.
I understand the domain and range return a single sort, so functions with multiple arguments (i.e. multidimensional arrays) need to be represented as curried functions. Therefore, I expected the range to be `(Array Int Int)` but not `Int`.

Is this a bug? If not, how can I query the API to get the complete function signature?

**Comment by NikolajBjorner** [comment]
you created a multi-dimensional array, not a nested array. 
the Java API does not expose functions for retrieving all domain sorts, it is 

```
    /**
       \brief Return the i'th domain sort of an n-dimensional array.

       \pre Z3_get_sort_kind(c, t) == Z3_ARRAY_SORT

       \sa Z3_mk_array_sort
       \sa Z3_get_sort_kind
       \sa Z3_get_array_sort_domain

       def_API('Z3_get_array_sort_domain_n', SORT, (_in(CONTEXT), _in(SORT), _in(UINT)))
       
     */
    Z3_sort Z3_API Z3_get_array_sort_domain_n(Z3_context c, Z3_sort t, unsigned idx);
```

I can add this to the Java API so you can retrieve both integers, but maybe not too interesting.
You can call mkArraySort twice to create one-dimensional nested arrays that are the curried forms of the multi-dimensional arrays.

**Comment by kevin-dp** [comment]
Thanks for adding this to the API, it will definitely be useful for our use case!
