### ISSUE TITLE
Invalid Model -- Int Div 

### ISSUE THREAD

**Issue by mrkmarron** [Z3Prover/z3#6354]
Hit an odd set of results with Integer division (using constants). 

The first is very unusual results with negative values.
```
(declare-const yy Int)
(assert (= yy (div 3 2)))

(declare-const zz Int)
(assert (= zz (div -3 2)))

(declare-const pp Int)
(assert (= pp (div 3 -2)))

(check-sat)
(get-model)
```

The resulting model has which is either wrong or a very unusual semantics:
```
  (define-fun pp () Int
    (- 1))
  (define-fun zz () Int
    (- 2))
  (define-fun yy () Int
    1)
```

The next result is in the attached file, [int_div_model.smt2.txt](https://github.com/Z3Prover/z3/files/9610260/int_div_model.smt2.txt), where it seems the solver builds a model where `37 = (div -3 2)` (the value for `x` and the computation on line 789.

I checked these results on Linux and Windows with the master head from yesterday.

**Comment by NikolajBjorner** [comment]
For the adapted semantics of integer arithmetic operations: http://smtlib.cs.uiowa.edu/theories-Ints.shtml.
I don't reproduce the issue with 37 = (div -3 2).

**Comment by mrkmarron** [comment]
Ah, that is my mistake, you are right. I updated my code to match the semantics from the theories docs and all the issues I had are resolved.

Thanks and sorry about the noise.
