### ISSUE TITLE
question sum bitvec

### ISSUE THREAD

**Issue by 1214465750** [Z3Prover/z3#6365]

**Comment by 1214465750** [comment]
```
from z3 import *
if __name__ == '__main__':
    m=Optimize()
    a=BitVec("a",1)
    b = BitVec("b", 1)
    c = BitVec("c", 1)
    d = BitVec("d", 1)
```
question
how can I make e==sum(a,b,c,d)
if a=b=c=d=1 I hope e can be 4
because I can't do like this
```
from z3 import *
if __name__ == '__main__':
    m=Optimize()
    a=BitVec("a",1)
    b = BitVec("b", 1)
    c = BitVec("c", 1)
    d = BitVec("d", 1)
    e = BitVec("d", 32) 
    m.add(e==sum(a,b,c,d))

```
the sort are not match
is there any function that can convert bitvec(1) to bitvec(32)?
is there any mathed to e==sum(a,b,c,d)?

**Comment by nunoplopes** [comment]
All variables in a sum must be of the same type. You need to zero- or sign-extend the smaller variables or truncate the larger ones.
Anyway, it's a good moment to pause and figure out the number of bits you need for the output to avoid overflows (if important).
