### ISSUE TITLE
converting floats: single to double

### ISSUE THREAD

**Issue by kooshan** [Z3Prover/z3#637]
I have two 32 bit-width bit vectors in ieee 754-2008 format which i translate them to floating-point  variables:

`Z3_ast fp_a_32 = Z3_mk_fpa_to_fp_bv(ctx, bv_a, Z3_mk_fpa_sort_32(ctx));
Z3_ast fp_b_32 = Z3_mk_fpa_to_fp_bv(ctx, bv_b, Z3_mk_fpa_sort_32(ctx));`

next, due to some operations with double precision numerals, I want to convert those sort_32 ast constructs  to sort_64; Therefore I go with
`
Z3_ast rm = Z3_mk_fpa_rtz(ctx); //also tried with: rne rna rtp rtn
Z3_ast fp_a_64 = Z3_mk_fpa_to_fp_float(ctx, rm, fp_a_32, Z3_mk_fpa_sort_64(ctx));
Z3_ast fp_b_64 = Z3_mk_fpa_to_fp_float(ctx, rm, fp_b_32, Z3_mk_fpa_sort_64(ctx));
`
the issue is that, I get stuck with a segmentation fault. I used debugging mode for Z3 and it turned out that **is_rm(to_expr(rm))** in function call  **Z3_mk_fpa_to_fp_float** is triggering the problem; which also traces back to **is_sort_of()** and **get_family_id()** calls.

Is there anything here that I've got it wrong? Did I missed something before doing the conversion?

**Comment by wintersteiger** [comment]
A segfault in this context is either a proper bug, or your reference counting isn't done correctly, such that Z3 deletes intermediate ASTs too early, with the effect that they are invalid while you still want to use them. Could you provide a self-contained example (perhaps as a [gist](https://gist.github.com/))?

**Comment by kooshan** [comment]
Thanks for your response. I've mainly used C++ API in my code, so that I could dismiss with the pain of reference counting. I noticed that there are no such API available for FPA. So this is actually the first line of code which I have fallen back to C API. Although there is not much code beforehand which directly relates to this floating point operation, I will figure out a sefl-contained example  as soon as possible to cast some light on this issue. Thank you.

**Comment by kooshan** [comment]
You were totally right. It happened to be the case that I skipped increasing reference to my rounding mode ast term. feeling so sorry for wasting your time.

**Comment by NikolajBjorner** [comment]
Generally speaking, two ideas when we don't have C++ API for functions :

 - Create a C++ wrapper for the missing function in your code, and use the C++ API for the rest. Don't fall back to C for the rest. The C API is super error prone. We have been bitten ourselves.
 - Add a pull request with functions that are missing :-) .
