### ISSUE TITLE
Inconsistency in Python API when checking with assumptions in QF_FD and QF_LIA

### ISSUE THREAD

**Issue by Marghrid** [Z3Prover/z3#6376]
`SolverFor('QF_FD')` does not support assumptions of the form var == value.

I'm using Python 3.10.6 and Z3 4.11.2 API installed with pip.

The following 2 snippets of code work as intended -- both output `sat`

```
solver = z3.SolverFor('QF_FD')

var = z3.Int('ex_int')
guard = z3.Bool('guard')

solver.add(var >= 0)
solver.add(var < 64)
solver.add(guard == (var == 33))

print(solver.check(guard))  # sat
```

```
solver = z3.SolverFor('QF_LIA')

var = z3.Int('ex_int')

solver.add(var >= 0)
solver.add(var < 64)

print(solver.check(var == 33))  # sat
```

However, if the assumption is expressed as in the second snippet, the QF_FD solver will not handle it. The following snippet ouputs `unknown` and the reason is `(sat.giveup interpreted functions sent to SAT solver (declare-fun = (Int Int) Bool))`.

```
solver = z3.SolverFor('QF_FD')

var = z3.Int('ex_int')

solver.add(var >= 0)
solver.add(var < 64)

print(solver.check(var == 33))  # unknown
print(solver.reason_unknown())
```

**Comment by aytey** [comment]
`QF_FD` means "quantifier free, finite domain"; terms of the sort `Int` are not "finite domain" (they're infinite domain), so `SolverFor('QF_FD')` does not know how to solve `var == 33`.

**Comment by Marghrid** [comment]
`QF_FD` also works with `Int`s as long as they are bounded, and it does solve the assertion `var == 33` in the first snippet. It just does not work when I put the expression directly as an assumption.

**Comment by NikolajBjorner** [comment]
It should reject assumptions that are not propositional literals
