### ISSUE TITLE
A question about the semantic of the negation

### ISSUE THREAD

**Issue by DerZc** [Z3Prover/z3#6389]
Hi,

I find a problem which about negation that the same program produces different results in z3 and Souffle.

This is the program:
```
Z 64

a(A:Z, B:Z) input
b(A:Z, B:Z) input
c(A:Z) printtuples

a(1, 2).
b(3, 4).

c(A) :- a(A, B), !b(_, _).
```
The result is `1`.

I run the same program in Souffle:
```
.decl a(A:number, B:number)
.decl b(A:number, B:number)
.decl c(A:number)

.input a
.input b

c(A):- a(A, B), !b(_, _).
.output c
```
The input of `a` is `1 2`, the input file of `b` is `3 4`. But the result of `c` is empty. 

So there maybe a question of negation?

**Comment by NikolajBjorner** [comment]
The example uses unsafe negation. Not sure this is within the scope of what z3 deals with.
