### ISSUE TITLE
Small example that doesn't terminate

### ISSUE THREAD

**Issue by charles-rs** [Z3Prover/z3#6397]
#6363 seems to be relevant again: example pasted below

(declare-fun f (Int Int Int) Bool)
(assert (forall ((x Int) (y Int) (z Int))
(= (and (= x 0) (= y z)) (f x y z))))

(check-sat)

**Comment by NikolajBjorner** [comment]
I can't repro this

**Comment by charles-rs** [comment]
ah, so sorry. The example is actually slightly differnt


(declare-fun f (Int Int Int) Bool)
(assert (forall ((x Int) (y Int) (z Int))
	(= (and (not (= x 0)) (<= y z)) (f x y z))))

(check-sat)

**Comment by NikolajBjorner** [comment]
I am still not getting it to loop. It converges on my end.
Z3 is supposed to detect that f is a macro and solve the quantifier as a macro.
So whenever you write the quantifier body of the form f(x,y,z) = body(x,yz) where body does not use f it should solve for f.
