### ISSUE TITLE
iZ3 - Segmentation faults

### ISSUE THREAD

**Issue by PhilippWendler** [Z3Prover/z3#64]
We use Z3 with the C interface as a library inside CPAchecker (for solving and interpolation). We have several cases where Z3 segfaults. Here are Z3 logfiles for three of them:

http://students.fim.uni-passau.de/~wendler/Problem14_label50_true-unreach-call.c.z3.log.bz2
http://students.fim.uni-passau.de/~wendler/elevator_spec13_product23_true-unreach-call.cil.c.z3.log.bz2
http://students.fim.uni-passau.de/~wendler/s3_srvr_8_true-unreach-call.cil.c.z3.log.bz2

When replaying, each of the log files gives the message "invalid pointer", thus it seems like a bug in Z3 to us.
The Z3 version used was 7f6ef0b6c0813f2e9e8f993d45722c0e5b99e152.

**Comment by NikolajBjorner** [comment]
Are the segfaults still appearing? Several fixes when into the interpolation facilities that may have addressed them.

**Comment by kenmcmil** [comment]
The logs are not replaying because the values of the out parameters of Z3_compute_interpolant are not being recorded. Perhaps logging just doesn't handle out parameters that are objects?

**Comment by NikolajBjorner** [comment]
Phillip, can you comment on whether the crashes still happen. If not (if no comment or no repro) I will close this as a no repro.

**Comment by PhilippWendler** [comment]
We are currently investigating whether it still happens, I will report back when I know.

**Comment by PhilippWendler** [comment]
It seems that these segfaults indeed have gone away. Thank you for fixing them! We are not yet sure if everything is working fully, but we would open another ticket if we find something else.
