### ISSUE TITLE
ParseSMTLIB2String does not support or throw on maximize/minimize

### ISSUE THREAD

**Issue by duncanawoods** [Z3Prover/z3#640]
If an SMT string contains objective functions, they are swallowed silently leading to incorrect optimisation results. The parser should throw an exception to indicate they are not supported because looking at examples and guide from http://www.rise4fun.com/Z3Opt its easy to assume they are part of the model.

Ideally the parser would support objective functions allowing complete models to be parsed. If standard compliance is an issue then consider making it optional or as a ParseOptString or some such. Its desirable because if we have a text definition, we have to write a complete custom SMT parser just to parse the objective function. As far as I can see the API doesn't expose a way to parse arithmetic expressions, only bool.

[1] http://rise4fun.com/Z3Opt/tutorial/guide
_"The SMT-LIB 2.0 standard is extended with three commands for expressing optimization objectives. The (maximize t) command instructs check-sat to produce a model that maximizes the value of term t."_

**Comment by duncanawoods** [comment]
>> we have to write a complete custom SMT parser

Ah, thinking about it, defining a variable equal to the objective function lets you use the existing parser. You then only need the name for adding the maximise/minimise goal.

**Comment by wintersteiger** [comment]
In general, `ParseSMTLIB2String` does not parse anything other than the expressions in (assert ...) commands in the SMT2 file, no other commands whatsover. For instance, it also ignores all (check-sat) commands. The reason for this is that SMT2 is a command language, but while parsing the file we do not want to execute any commands. 

You can however parse arbitrary expressions (e.g., before you pass them to the optimization engine); if you provide it with existing sorts and func_decls (from the previous parts of the problem), then it will match them variables/functions up correctly (see for instance the .NET version of [ParseSMTLIBString](http://z3prover.github.io/api/html/class_microsoft_1_1_z3_1_1_context.html#a29e251ed7a6013f7abcc6d099c0ef359); the 4 arguments after the filename define the symbol table).

**Comment by duncanawoods** [comment]
Should it be considered as a command? I would assume goals are a special flavour of constraint unlike commands like get-model.
