### ISSUE TITLE
(get-interpolant) fails with: Overflow encountered when expanding vector

### ISSUE THREAD

**Issue by daniel-larraz** [Z3Prover/z3#6404]
The `(get-interpolant)` command in this SMTLIB script ([traffic.txt](https://github.com/Z3Prover/z3/files/9804063/traffic.txt)) returns the following error:
```
(error "line 921 column 57: Overflow encountered when expanding vector")
```
z3 version: d4885ab
Operating system: Ubuntu 20.04

**Comment by NikolajBjorner** [comment]
appears fixed. Interpolant happens to be trivial.
