### ISSUE TITLE
Incremental Solver Problem with fp.max

### ISSUE THREAD

**Issue by kyledewey** [Z3Prover/z3#642]
On the `master` branch at commit 9b91e6ff0aa6d3ca759a61b701f987e71eb04540, consider the following input:

```
(set-logic QF_FP)
(declare-fun x0 () (_ FloatingPoint 2 3))
(check-sat)
(assert (= (fp.neg (fp.max (fp #b0 #b00 #b00) x0)) (fp.max (fp.max (fp #b0 #b00 #b00) x0) x0)))
(check-sat)
```

Placing this into a file `test.smtlib2` and running with command-line `z3 -smt2 test.smtlib2` yields the following output:

```
sat
sat
```

If the first `(check-sat)` is removed, Z3 reports `unsat`.  Based on my understanding, this should be `unsat`.  If the model produced from the second `(check-sat)` instance is fed back into the original formula (replacing the variables with their assignments), Z3 reports `unsat` for the second `(check-sat)` instance.

On a tangential note, the above input was derived from a larger input via an experimental delta debugger.  If the input can be further minimized, let me know so I can improve the delta debugger.

**Comment by wintersteiger** [comment]
Thanks for the report, this is now fixed.
