### ISSUE TITLE
error during make under Cygwin64

### ISSUE THREAD

**Issue by stefanleue** [Z3Prover/z3#6427]
I am following the instructions on how to install Z3 under Windows / Cygwin64. during the make, I am getting the following error:

Stefan Leue@Yoga-soft-2 ~/z3/build
$ make
src/shell/datalog_frontend.cpp
In file included from ../src/ast/arith_decl_plugin.h:21:0,
                 from ../src/shell/datalog_frontend.cpp:25:
../src/ast/ast.h:50:19: schwerwiegender Fehler: variant: No such file or directory
 #include <variant>
                   ^
Kompilierung beendet.
make: *** [Makefile:4630: shell/datalog_frontend.o] Fehler 1

Any thoughts on what may be wrong?

**Comment by LeventErkok** [comment]
Your C compiler is too old. See here: https://stackoverflow.com/questions/40177006/c-variant-no-such-file-or-directory

**Comment by stefanleue** [comment]
Solved the issue, thanks.
