### ISSUE TITLE
cmake configuration problem on Ubuntu 14.04 x86

### ISSUE THREAD

**Issue by wintersteiger** [Z3Prover/z3#644]
When attempting to build Z3 on Ubuntu 14.04 x86 I get the following error:

    In file included from [...]/z3/src/util/hwf.cpp:54:0:
    [...]include/emmintrin.h:31:3: error: #error "SSE2 instruction set not enabled"

I suspect that's because `-mfpmath=sse -msse -msse2` is not added to the compiler options. @delcypher, could you take a look at that?

**Comment by delcypher** [comment]
I cannot reproduce this on Ubuntu 14.04LTS (using gcc (Ubuntu 4.8.4-2ubuntu1~14.04) 4.8.4). You will need to give more detailed reproduction steps for me to reproduce this.

FYI the sse stuff is handled in the ``CMakeLists.txt`` file in this code

```
################################################################################
# FP math
################################################################################
# FIXME: Support ARM "-mfpu=vfp -mfloat-abi=hard"
if ("${TARGET_ARCHITECTURE}" STREQUAL "x86_64")
  if (("${CMAKE_CXX_COMPILER_ID}" MATCHES "GNU") OR ("${CMAKE_CXX_COMPILER_ID}" MATCHES "Clang"))
    set(SSE_FLAGS "-mfpmath=sse" "-msse" "-msse2")
    # FIXME: Remove "x.." when CMP0054 is set to NEW
  elseif ("x${CMAKE_CXX_COMPILER_ID}" STREQUAL "xMSVC")
    set(SSE_FLAGS "/arch:SSE2")
  else()
    message(FATAL_ERROR "Unknown compiler ${CMAKE_CXX_COMPILER_ID}")
  endif()
  CHECK_CXX_COMPILER_FLAG("${SSE_FLAGS}" HAS_SSE2)
  if (HAS_SSE2)
    list(APPEND Z3_COMPONENT_CXX_FLAGS ${SSE_FLAGS})
  endif()
  unset(SSE_FLAGS)
endif()
```

**Comment by wintersteiger** [comment]
The error is from our build VM, which is a clean Ubuntu 14.04 with all required packages installed, but not necessarily up to date with yesterday's distribution. 

    ...:~/z3/build$ lsb_release -a
    No LSB modules are available.
    Distributor ID: Ubuntu
    Description:    Ubuntu 14.04.4 LTS
    Release:        14.04
    Codename:       trusty
    ...:~$ uname -a
    Linux ubuntu-x86 3.13.0-86-generic #130-Ubuntu SMP Mon Apr 18 18:29:07 UTC 2016 i686 i686 i686 GNU/Linux
    ...:~$ gcc --version
    gcc (Ubuntu 4.8.4-2ubuntu1~14.04.1) 4.8.4
    ...$ python --version
    Python 2.7.6
    ...:~/z3$ git clean -fx src
    ...:~/z3$ python contrib/cmake/bootstrap.py create
    ...:~/z3$ mkdir build
    ...:~/z3$ cd build
    ...:~/z3/build$ cmake -G "Unix Makefiles" ../
    ...:~/z3/build$ make -j4
    ...
    # error "SSE2 instruction set not enabled"

**Comment by delcypher** [comment]
@wintersteiger What version of CMake are you using?

**Comment by wintersteiger** [comment]
I'm using the default Ubuntu package for cmake, it says: 

    ...:~$ cmake --version
    cmake version 2.8.12.2

**Comment by delcypher** [comment]
Okay I've figured out the problem. Your VM is 32-bit and I have never tested the build system with for 32-bit x86. I've only tested x86_64. The fp math flags are currently only passed for ``x86_64``.

Changing

```cmake
################################################################################
# FP math
################################################################################
# FIXME: Support ARM "-mfpu=vfp -mfloat-abi=hard"
if ("${TARGET_ARCHITECTURE}" STREQUAL "x86_64")
```

to something like

```cmake
################################################################################
# FP math
################################################################################
# FIXME: Support ARM "-mfpu=vfp -mfloat-abi=hard"
if (("${TARGET_ARCHITECTURE}" STREQUAL "x86_64") OR ("${TARGET_ARCHITECTURE}" STREQUAL "i686"))
...
```

should fix the issue.

**Comment by delcypher** [comment]
I would have noticed this earlier but when I see ``x86`` I don't think 32-bit. I think it means ``x86_64`` or ``i686``.

**Comment by wintersteiger** [comment]
Confirmed, this change makes the build go through. Is there a reason we shouldn't merge that into master yet?

**Comment by delcypher** [comment]
@wintersteiger There is no reason not to make a change similar to the above into master. I am not currently in a position to contribute code to Z3 so I can't make the change so someone else needs to do it.

**Comment by wintersteiger** [comment]
Oh, I see! No worries, fix merged.
