### ISSUE TITLE
Java API: My java program core dump while call api::context::del_object

### ISSUE THREAD

**Issue by jerry-tom** [Z3Prover/z3#6452]
My java program do optimizer check with z3, but sometimes the program core dump.
Here are some excerpts from the error report message
``` text
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007fa1428b8935, pid=7, tid=0x00007fa13ddd0700
#
# JRE version: OpenJDK Runtime Environment (8.0_322-b01) (build 1.8.0_322-b1)
# Java VM: OpenJDK 64-Bit Server VM (25.322-b1 mixed mode, sharing linux-amd64 compressed oops)
# Problematic frame:
# C  [libz3.so+0x25e935]  api::context::del_object(api::object*)+0x125
#
# Core dump written. Default 
```
The possible reason is that a null pointer was passed in to api::context::del_object. We have made pointer null judgment protection, which has been verified for 7 days, and has not appeared again so far.

Is the following code modification  the correct way?
![WeChatWorkScreenshot_3734c80a-739c-4c23-967d-11e4e632f065](https://user-images.githubusercontent.com/5044158/201676740-1ee5a902-8033-43e7-b7a1-dbd79ec3a827.png)

Note: the version of z3 is [z3-4.11.2](https://github.com/Z3Prover/z3/releases/tag/z3-4.11.2)

**Comment by NikolajBjorner** [comment]
it is a reasonable change, but it basically masks a bug in the Java layer. 
The "hard fix" is to migrate object management to use the same method as .Net and OCaml bindings (get rid of the z3object gc queues because they can be handled internally).
