### ISSUE TITLE
Feature Request: convert string to bitvector

### ISSUE THREAD

**Issue by Sun-C0ffee** [Z3Prover/z3#6455]
I found that Z3 can only convert string to integer type through the function StrToInt() or StrToCode(). There isn't a straightforward way to convert a string to a bitvector, I think it would be useful to add a few such conversion functions.

**Comment by NikolajBjorner** [comment]
Added paragraph to tutorial - https://microsoft.github.io/z3guide/docs/theories/Bitvectors/#bitvectors-and-integers
