### ISSUE TITLE
`pp.single_line=true` has no effect

### ISSUE THREAD

**Issue by qaristote** [Z3Prover/z3#6461]
Here's a simple `.smt2` file:
```
(set-option :produce-models true)
(declare-fun pir_greaterThan1 (Int) Bool)
(declare-fun pir_greaterThan0 (Int) Bool)
(declare-fun pir_add1 (Int) Int)
(declare-fun pir___result () Int)
(declare-fun pir_x () Int)
(assert (= pir___result (+ pir_x 1)))
(assert (< 0 pir___result))
(assert (not (< 0 pir_x )))
(check-sat)
(get-value (pir___result pir_x))
(exit)
```
Running `z3 pp.single_line=true` (with `Z3 version 4.12.0`) on it outputs
```
sat
((pir___result 1)
 (pir_x 0))
```
As you can see, the model is spread between two lines. Yet, I would have expected the `pp.single_line=true` option to force the model to be written on a single line, i.e. i was expecting
```
sat
((pir___result 1) (pir_x 0))
```

Am I misunderstanding what this option is supposed to do ? If so, is there a way to force Z3 to print its output on a single line ? I also tried combinations of `pp.max_num_lines` and `pp.max_width` but to no avail. Not being able to force this makes it harder to parse Z3's output.

**Comment by NikolajBjorner** [comment]
single-line is just within an expression. It doesn't affect other output that combines multiple expressions.
It isn't difficult to read multiple lines: you maintain a count of matching parentheses to close expressions. There are many examples of reading LISP s-expressions availble.
