### ISSUE TITLE
Remainder on negative numbers

### ISSUE THREAD

**Issue by BramVerb** [Z3Prover/z3#6462]
I have the following model for doing `-1 % 3`:
```
(declare-const modulo Int)
(declare-const remainder Int)
(assert (= modulo (mod -1 3)))
(assert (= remainder (rem -1 3)))
(check-sat)
(get-model)
```

When looking up the difference between the remainder and the modulo, I keep seeing that the remainder keeps the sign of the original number, whereas in Z3 this is not the case, as both `rem` and `mod` produce a positive output for a negative number. Whereas I expected the remainder be `-1` and the modulo to be `2`.

Is this done intentional? Or is this a bug?
When quickly searching through the code I could not find tests for the remainder operator, whereas I did find some for the modulo.

If this is intentional, I am happy to create a PR to include in the documentation, as I think it is somewhat confusing when using it.

**Comment by NikolajBjorner** [comment]
"rem" isn't part of SMTLIB2 standard. I therefore don't have a reference to a shared semantics.
Changes to "rem" can be quite intrusive. 
The adapted semantics is:

```
(rem x y) == (if (>= y 0) (mod x y) (- (mod x y))
```

Any change to the semantics would require quite some regression testing.
It is referenced in purify_arith_tactic.cpp

**Comment by BramVerb** [comment]
Okay, thank you for clarifying! 
Although I might have been a bit unclear, I think the adapted semantic should be:

```(rem x y) == (if 
    (>= y 0)
    (mod x y)
    (- (mod x y) y)
)```

However I had to adapt it work for my case where the remainder can also produce zero: `-3 rem 3` should be `0` . (So in fact not strictly sign preserving.)

```
(rem x y) == (if
    (or (>= y 0) (= (mod x y) 0)
    (mod x y)
    (- (mod x y) y)
)
```

Should I create a PR to add to the docs that the `rem` operator in z3 will always produce a non-negative int?

**Comment by NikolajBjorner** [comment]
I am not sure about a pull request to change rem. It will likely cause support-calls down the line for reasons that are not understood at this point. This is a common experience.
The easier way is you introduce a macro myrem that has the appropriate definition using mod.
Anyway, this is basically how rem is handled.
