### ISSUE TITLE
Status of Sequences and `mapi` in API

### ISSUE THREAD

**Issue by avery-laird** [Z3Prover/z3#6466]
Hello,

I am wondering about the status of sequences in the APIs (either python or C++). Most of the functionality documented [here](https://microsoft.github.io/z3guide/docs/theories/Sequences/) is accessible from the python API, except for functions like `seq.mapi`. Specifically, I want to use this to model the behaviour of `Store` on arrays, but using a structure (list/sequence) that is more amenable to inductive reasoning. 

Are functions like `seq.mapi` accessable from the python or c++ API? Thanks for any help.

**Comment by NikolajBjorner** [comment]
not yet accessible, but if you are in a hurry, you can add a pull request with updates to the API to expose them.
These functions were added relatively recently and were so far tested with Bosque.

**Comment by avery-laird** [comment]
sounds good, I have done so in #6468 .
