### ISSUE TITLE
z3 is built with "lib" prefixed on Windows when installed with vcpkg

### ISSUE THREAD

**Issue by xxr0ss** [Z3Prover/z3#6469]
Hi, I installed the latest version 4.11.0 with vcpkg. After the installation, I got `[vcpkg root]\installed\x64-windows\bin\libz3.dll`  and `[vcpkg root]\installed\x64-windows\lib\libz3.lib`.

This brings trouble when I write `CMakeLists.txt`s, 
```cmake
# I have to write
link_libraries(libz3)

# instead of
link_libraries(z3)
```

Normally, many packages is installed without `lib` prefix on Windows. Such prefix is more commonly seen on *nix systems.
Is it designed to be suffixed as well on windows?

**Comment by NikolajBjorner** [comment]
the naming convention has been used for more than a decade. I don't understand from the post a reason to change it.
