### ISSUE TITLE
Inconsistent assumptions between unmanaged/ml vs .NET and Java bindings on lock around context creation

### ISSUE THREAD

**Issue by cheshire** [Z3Prover/z3#647]
Hi, a quick question: Z3 Java API (Context.java, InterpolationContext.java) grabs a lock before creating a context.
Is that what a law-abiding API has to do? I haven't looked much into the C++ code, and such a behavior makes sense, but it currently isn't documented anywhere (the documentation just says that different threads must operate on different contexts).

**Comment by NikolajBjorner** [comment]
Both Java and .NET have locks, the C++ and C do not. I don't see anything specific to the managed APIs that require locks. There are locks to protect memory management initialization inside of Z3 already. The basic assumption should be that any required synchronization that has to do with Z3 specific functionality is implemented at the C API level. There is no mention the mk_context is not re-entrant in z3_api.h, so users should assume it is. So from what I can see, the locks are not required and possibly a left-over from a time when context creation used non-reentrant functions. (I assume that GC.SuppressFinalize(this) in Context.cs is reentrant as it is a static .NET function).

**Comment by cheshire** [comment]
Hi Nikolaj,

Can we change this ticket to "fix .NET and Java bindings not to lock around context creation"?

**Comment by NikolajBjorner** [comment]
right, something along that direction (leaving a conclusion out of the title).

**Comment by cheshire** [comment]
with new Java bindings this should be closed now.
