### ISSUE TITLE
Performance Issue in C++ API vs Binary

### ISSUE THREAD

**Issue by rafaelsamenezes** [Z3Prover/z3#6479]
Hello,

In [ESBMC](https://github.com/esbmc/esbmc) we are noticing some performance issues when calling Z3 from the API vs calling Z3 binary. Solving the smt formula takes less than 1 second, I am attaching the `z3.log` and `log.smt2` files.

Could you please advise?

[files.zip](https://github.com/Z3Prover/z3/files/10153269/files.zip)

**Comment by NikolajBjorner** [comment]
Are you using home made API wrappers?

Your code calls Z3_mk_ast_vector immediately followed by Z3_ast_vector_resize.
You need to increment a reference count on the vector.

For example, in the C++ wrapper the init function ensures that m_vector is live.

```
    template<typename T>
    class ast_vector_tpl : public object {
        Z3_ast_vector m_vector;
        void init(Z3_ast_vector v) { Z3_ast_vector_inc_ref(ctx(), v); m_vector = v; }
    public:
        ast_vector_tpl(context & c):object(c) { init(Z3_mk_ast_vector(c)); }
        ast_vector_tpl(context & c, Z3_ast_vector v):object(c) { init(v); }
        ast_vector_tpl(ast_vector_tpl const & s):object(s), m_vector(s.m_vector) { Z3_ast_vector_inc_ref(ctx(), m_vector); }
        ast_vector_tpl(context& c, ast_vector_tpl const& src): object(c) { init(Z3_ast_vector_translate(src.ctx(), src, c)); }

        ~ast_vector_tpl() { Z3_ast_vector_dec_ref(ctx(), m_vector); }
        operator Z3_ast_vector() const { return m_vector; }
        unsigned size() const { return Z3_ast_vector_size(ctx(), m_vector); }
        T operator[](unsigned i) const { Z3_ast r = Z3_ast_vector_get(ctx(), m_vector, i); check_error(); return cast_ast<T>()(ctx(), r); }
        void push_back(T const & e) { Z3_ast_vector_push(ctx(), m_vector, e); check_error(); }
        void resize(unsigned sz) { Z3_ast_vector_resize(ctx(), m_vector, sz); check_error(); }
```

**Comment by rafaelsamenezes** [comment]
Hi @NikolajBjorner,

Could you please elaborate? We are not invoking `Z3_mk_ast_vector` and neither `Z3_ast_vector_resize` directly. Running with a debugger shows that we are only calling those methods through the api.

```
1) z3::expr_vector args(z3_ctx);
2) ast_vector_tpl(context & c):object(c) { init(Z3_mk_ast_vector(c)); }
3) void init(Z3_ast_vector v) { Z3_ast_vector_inc_ref(ctx(), v); m_vector = v; }
```

We are using the vectors in two places: [first](https://github.com/esbmc/esbmc/blob/master/src/solvers/z3/z3_conv.cpp#L972-L997) and [second](https://github.com/esbmc/esbmc/blob/master/src/solvers/z3/z3_conv.cpp#L84-L120)

Also, all Z3 functions that we use are at [this](https://github.com/esbmc/esbmc/blob/master/src/solvers/z3/z3_conv.cpp) file. 

Do you have any suggestions on how to debug this issue?

**Comment by rafaelsamenezes** [comment]
The issue was how the solver was instantiated. Specifically, we were setting the parameter "relevancy"  to 0.

**Comment by NikolajBjorner** [comment]
I don't yet understand why the replay log was bogus. It blocked me. 
The replay log indicates you are using version 11.0. The exception stack within the log doesn't look like it comes from your bindings.
