### ISSUE TITLE
Question about a method to use re.^ in z3py

### ISSUE THREAD

**Issue by hagozaebii** [Z3Prover/z3#6493]
Hello, I am a novice in z3py. Recently, I've tried to use re.^ through z3py.
However, it's very hard for me to find out what function is for re.^ in z3py.
Is there any way to use re.^ in z3py?
Thanks for your time!

**Comment by NikolajBjorner** [comment]
It isn't exposed over Python. 
Use Loop(r, n, n) to encode re.^(r, n)
