### ISSUE TITLE
Failed to install using command:pip3 install z3-solver

### ISSUE THREAD

**Issue by begierde** [Z3Prover/z3#6494]
Trying to install z3-solver on a m1 based kali and get failed.

Tried z3_solver-4.11.2.0-py2.py3-none-macosx_11_0_arm64.whl also get failed

Please help

![Screenshot_2022-12-16_14-12-36](https://user-images.githubusercontent.com/54112668/208035130-cec8fbf8-d311-4167-a5c8-e6b986f74f07.png)

![Screenshot_2022-12-16_14-12-37](https://user-images.githubusercontent.com/54112668/208035504-4ac2a5d9-ac65-440f-be6c-69a2f3d96eac.png)

**Comment by NikolajBjorner** [comment]
there is a dependency on cmake for the second option.
Somehow your system didn't establish a cmake dependency. It should have been derived from the package distribution.
