### ISSUE TITLE
Cannot find Z3Config.cmake

### ISSUE THREAD

**Issue by sillydan1** [Z3Prover/z3#6496]
I'm not sure if this is the right place to submit this issue, but it seems that there's an issue with the cmake package config files in the official [debian release](https://packages.debian.org/bullseye/libz3-dev) of `libz3-dev`.

## Minimal example
 - OS: `Debian bullseye` (issue also exists on `Ubuntu 22.04.1`)
 - Packages installed: `z3 libz3-dev`
 - CMakeLists.txt:
```cmake
# CMakeLists.txt
find_package(Z3 REQUIRED)
```

When `cmake` is invoked, I get:
```shell
...
CMake Error at CMakeLists.txt:1 (find_package):
  By not providing "FindZ3.cmake" in CMAKE_MODULE_PATH this project has asked
  CMake to find a package configuration file provided by "Z3", but CMake did
  not find one.

  Could not find a package configuration file provided by "Z3" with any of
  the following names:

    Z3Config.cmake
    z3-config.cmake

  Add the installation prefix of "Z3" to CMAKE_PREFIX_PATH or set "Z3_DIR" to
  a directory containing one of the above files.  If "Z3" provides a separate
  development package or SDK, be sure it has been installed.
...
```

I _have_ double and triple-checked that the package is installed. The linker can find the `.so` file and C++ include headers are also located where they should be.

This issue does _not_ happen on MacOS (homebrew package). The arch-linux community package also works just fine.

**Comment by NikolajBjorner** [comment]
It isn't the right place, but maybe somebody who has a clue sees this.

**Comment by sillydan1** [comment]
It seems that [this](https://salsa.debian.org/pkg-llvm-team/z3/-/blob/master/debian/not-installed) might be the issue. I might take a stab at it, but I am not very versed in Debian packaging (this is a good opportunity to learn though)

**Comment by NikolajBjorner** [comment]
It is also bandwidth and your expressed interest to look into this on your own is admirable. 
I ditched my local docker installation and forgot the steps to get a debian 
setup so it takes several cycles just to get to the repro stage.

**Comment by NikolajBjorner** [comment]
I believe this bug is external and not directly tied to this repository. At any rate, I have no specific context to address it.
