### ISSUE TITLE
[Question] How to expand limitation of recursion depth in z3py?

### ISSUE THREAD

**Issue by hagozaebii** [Z3Prover/z3#6498]
Hello, Recently, I faced an error `Runtime error at /usr/local/lib/python3.8/dist-packages/z3_solver-4.11.2.0-py3.8-linux-x86_64.egg/z3/z3core.py,  Line : 1473, Error Message : argument 1: <class 'RecursionError'>: maximum recursion depth exceeded` while using z3. 
I know the error from recursion limit of Python. But I don't know how to eliminate the limitation of recursion depth. I added 'sys.setrecursionlimit(..)' in z3 core path that is mentioned above. However, it does not look work well. Is there any way to solve this issue?
Thanks for your time!

**Comment by NikolajBjorner** [comment]
I have no idea how to address this question. The runtime error comes from Python. I don't know what code is using recursion based on the excerpt. The python runtime should be able to convey this information.
