### ISSUE TITLE
qe returns LIA formula with quantifiers

### ISSUE THREAD

**Issue by daniel-larraz** [Z3Prover/z3#6505]
Consider this SMTLIB script: [qe.txt](https://github.com/Z3Prover/z3/files/10288088/qe.txt)

After applying the `qe` tactic, z3 returns a formula with existential quantifiers. Is this expected?

In comparison, cvc5 is able to return a quantifier-free formula for the same input formula.

**Comment by NikolajBjorner** [comment]
qe doesn't handle division "div" at this point.
