### ISSUE TITLE
Question about const and val

### ISSUE THREAD

**Issue by seohyunbae** [Z3Prover/z3#6507]
hello.
I have a question about variable type in z3 library(C++ api).

my question is 1). what is difference between x_const and x_val? (e.g. int_const vs int_val)

in detail, when I define variable like below,
    expr x1 = int_const("x");
    expr x2 = int_const("x");
then, 2). I think that I can access same expression object through both x1 and x2. is it right?
in addition, 3). duplication is allowed for int_const?

then, when I define variable like below again,
    expr y1 = int_val(0);
    expr y2 = int_val(0);
in this situation, 4). Can I also access same expression object by both y1 and y2?
in addition, 5). duplication is allowed for int_val?

at last, if there is for loop like below,
    context c;
    optimize opt(c);
    for(int I=0; I<10; ++i){
        expr x = int_val(i);
        opt.add(x!=-1); //this expression is meaningless formulation but for example in my question
    }
then, 6). for loop makes new expression object(int_val) for each loop?
(e.g. opt.add(int_val(0)!=-1); opt.add(int_val(1)!=-1); ... opt.add(int_val(9)!=-1);)

I'm sorry for bothering you.

**Comment by nunoplopes** [comment]
You can duplicate expressions as many times as you want. They are referenced counted and hash consed internally.
A constant in SMT parlance is what one would call a variable (aka a function with zero inputs). You also have variables, which are meant to be used with quantifiers (De Bruijn indexes).
