### ISSUE TITLE
z3_api.h: `Z3_mk_seq_last_index` second argument missing name

### ISSUE THREAD

**Issue by callendorph** [Z3Prover/z3#6508]
I'm looking at this line: 

https://github.com/Z3Prover/z3/blob/b9c4f5d4fafcace3968eb3a5c5489a4c881628a0/src/api/z3_api.h#L3766

The second argument of this function is missing the name of the argument declaration. Judging by the other methods, I would assume it needs a `s` here.

**Comment by callendorph** [comment]
I found the following additional cases:

https://github.com/Z3Prover/z3/blob/b9c4f5d4fafcace3968eb3a5c5489a4c881628a0/src/api/z3_api.h#L3896

https://github.com/Z3Prover/z3/blob/b9c4f5d4fafcace3968eb3a5c5489a4c881628a0/src/api/z3_api.h#L5884

https://github.com/Z3Prover/z3/blob/b9c4f5d4fafcace3968eb3a5c5489a4c881628a0/src/api/z3_api.h#L7032

**Comment by tw42pi** [comment]
the change at line 5884 now misses a , between both parameters

**Comment by NikolajBjorner** [comment]
3e8cbb66112aaa58710e8e23719ab864b51ad0fe

**Comment by callendorph** [comment]
Thank you!
