### ISSUE TITLE
Model has interpretation for undeclared function

### ISSUE THREAD

**Issue by 108anup** [Z3Prover/z3#6524]
For the SMT formula attached below, the model produced by z3 contains the interpretation:
```
  (define-fun /0 ((x!0 Real) (x!1 Real)) Real
    (ite (and (= x!0 (/ 5135.0 32.0)) (= x!1 0.0)) 0.0
    (ite (and (= x!0 100.0) (= x!1 0.0)) (- (/ 1543.0 16.0))
    (ite (and (= x!0 (/ 3.0 8.0)) (= x!1 0.0)) (- (/ 1535.0 16.0))
    (ite (and (= x!0 (/ 797.0 8.0)) (= x!1 0.0)) 100.0
      (- (/ 1539.0 16.0)))))))
```
This function is never declared in the input.
Why might this be happening? Is this my misunderstanding or a bug in z3?

I am using `Z3 version 4.8.17 - 64 bit`

Formula: https://drive.google.com/file/d/1d1rDoqb28JUI9PPTAwcD3uRql_1EtmQe/view?usp=sharing
Model: https://drive.google.com/file/d/15thJUj0GExR4Hd87LQW0OzAcqPi0LeHm/view?usp=sharing

Please let me know if there is a better way to share the formula/model (currently linked through google drive).

**Comment by 108anup** [comment]
Never mind. I had a constraint that had division by 0. Somehow, z3 interpretted that as a function? Is this expected behavior?

**Comment by NikolajBjorner** [comment]
Division by 0 is not fixed and it can be anything that is consistent with your formula. 

So z3 introduces a function /0 that tells what division by 0 is for various values. 
It satisfies the property 

```
     forall x . x / 0 = x /0 0
```
