### ISSUE TITLE
Z3 NuGet Package

### ISSUE THREAD

**Issue by veleek** [Z3Prover/z3#653]
There is a NuGet package available that packages up the Z3 binaries but it's a little out of date.  It would be nice to see an 'official' package available that includes both the 32 and 64 bit binaries.

I have a project/package like this and can provide details if anyone is interested.

**Comment by veleek** [comment]
Well... kinda.  Even if you're not publishing nightly builds, we should probably publish beta versions of the packages (essentially anything with a dash in the version, e.g. 1.2.3-beta1) and then only publish release versions for the actual releases.  

For nightly builds you could look into using another NuGet repository like MyGet to avoid cluttering the main NuGet repo, the discussion here is good: https://stackoverflow.com/questions/23753880/nuget-and-nightly-builds

All that being said, I'm constructing a NuGet package myself and trying to figure out if there's a reasonable way deal with the 32/64 bit stuff.  Right now I'm using [a build target in the package](https://docs.nuget.org/create/creating-and-publishing-a-package#import-msbuild-targets-and-props-files-into-project) to automatically reference the 32-bit or 64-bit depending on the projects build platform.  This works, except that it the reference doesn't show up in Visual Studio because the reference is added at build time.  Still researching if there's a way around this (maybe using a .props file).

**Comment by veleek** [comment]
Okay, I've got this working.  I'm still browsing around the source to see if I can find the appropriate place to put this (and work it into the build scripts), but I'm not super familiar with the build system, so pointers would be appreciated.

Just so that it's available here, this is the .props and .nuspec I'm using.

### Microsoft.Z3.props
```
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <Use64BitZ3Lib>false</Use64BitZ3Lib>
  </PropertyGroup>

  <Choose>
    <When Condition="'$(Platform)' == 'x64' or $(Use64BitZ3Lib) == 'true'">
      <ItemGroup>
        <Reference Include="Microsoft.Z3">
          <HintPath>$(MSBuildThisFileDirectory)lib\x64\Microsoft.Z3.dll</HintPath>
          <Private>false</Private>
        </Reference>
      </ItemGroup>
    </When>
    <Otherwise>
      <ItemGroup>
        <Reference Include="Microsoft.Z3">
          <HintPath>$(MSBuildThisFileDirectory)lib\x86\Microsoft.Z3.dll</HintPath>
          <Private>false</Private>
        </Reference>
      </ItemGroup>
    </Otherwise>
  </Choose>
</Project>
```

### Microsoft.Z3.nuspec
```
<?xml version="1.0" encoding="utf-8"?>
<package xmlns="http://schemas.microsoft.com/packaging/2010/07/nuspec.xsd">
    <metadata>
        <id>Microsoft.Z3</id>
        <version>4.4.1</version>
        <title>Z3</title>
        <authors>benran</authors>
        <owners>Microsoft</owners>
        <licenseUrl>https://github.com/Z3Prover/z3/blob/master/LICENSE.txt</licenseUrl>
        <projectUrl>https://github.com/Z3Prover/z3</projectUrl>
        <requireLicenseAcceptance>true</requireLicenseAcceptance>
        <description>Z3 is a high-performance theorem prover being developed at Microsoft Research.</description>
        <summary>Z3 is a high-performance theorem prover being developed at Microsoft Research.</summary>
        <tags>Z3, Theorem Prover, SMT, Constraint Satisfaction</tags>
    </metadata>
    <files>
        <file src="build\" target="build\" />
        <file src="license.txt" target="license.txt" />
    </files>
</package>
```

The `build` folder has a lib subfolder with x86 and x64 folders which contain the appropriate libz3.dll and Microsoft.Z3.dll for their platform.  I fiddled around with VS and you can change the platform and everything get's picked up properly.

**Comment by ahelwer** [comment]
Official Microsoft Z3 NuGet packages have now been released! https://www.nuget.org/profiles/z3prover
