### ISSUE TITLE
Problem with Z3-Opt and opt.priority box parameter 

### ISSUE THREAD

**Issue by zverlov** [Z3Prover/z3#654]
Hey,

I get an error in my JRE when i try to optimize a large deployment problem using z3 JAVA-API and opt.priority box parameter. This problem doesnt occur, when I am searching for pareto fronts though. (i my example i use 3 contradicting criteria)
The following message i get in my eclipse console:

    

> !MESSAGE [Z3] solving problem with parameters (params priority box timeout 10000)
> 
>     A fatal error has been detected by the Java Runtime Environment:
> 
>     SIGSEGV (0xb) at pc=0x0000000135a4b3f4, pid=678, tid=2571
> 
>     JRE version: Java(TM) SE Runtime Environment (8.0_60-b27) (build 1.8.0_60-b27)
>     Java VM: Java HotSpot(TM) 64-Bit Server VM (25.60-b23 mixed mode bsd-amd64 compressed oops)
>     Problematic frame:
>     C [libz3.dylib+0xc03f4] opt::context::execute_box()+0x34
> 
>     Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before > starting Java again
> 
>     An error report file with more information is saved as:
>     /Users/zverlov/Documents/Development/currentworkspace/plugins/org.fortiss.af3.efficientdeployment.ui >/hs_err_pid678.log
> 
>     If you would like to submit a bug report, please visit:
>     http://bugreport.java.com/bugreport/crash.jsp
>     The crash happened outside the Java Virtual Machine in native code.
>     See problematic frame for where to report the bug.

Also a huge log file gets generated, that can be found [here](http://download.fortiss.org/public/zverlov/hs_err_pid674.log):

I am using MacOS, Java 1.8 and the nightly build of Z3 (https://github.com/Z3Prover/bin/tree/master/nightly).

best

Sergey

**Comment by wintersteiger** [comment]
The JVM log seems to indicate that there are 4 worker threads running. Are those yours and, if so, are they using their own Context objects?

**Comment by zverlov** [comment]
Hey,

thanks for the fast reply.
No, everything is running within one thread and we are using only one context.
We running the optimization within an academic CASE tool. I guess the other threads are created by it.

One thing, which is maybe also important to mention: the boxed parameter works for smaller deployment problems just fine. But with larger ones  it leads to this error.

Nevertheless this problem doesnt occur if we use the pareto parameter.


best


Sergey

**Comment by NikolajBjorner** [comment]
Try one or two of the following:
1. Generate a Z3 log file by calling Log.open("z3.log") and share it.
2. Use Z3 in debug mode (and make sure symbols are accessible) and report the stack

**Comment by NikolajBjorner** [comment]
If possible, the least painful way to work with repros is to use the toString method on the opt class. This should print an SMT-LIB formatted benchmark. Try to see if the crash reproduces with the benchmark file. T

**Comment by zverlov** [comment]
Hey,

thanks for the fast reply.

1. so i created a Log file, which you can find [here](http://download.fortiss.org/public/zverlov/z3.log).
2. I didnt quite figure out, how to run z3 (using the java api) in the debug mode. Could you give me a hint?
3. I wasn't sure, what "repos" meant but i just made a toString on the solver and created a smt2 file of this problem, which can be found [here](http://download.fortiss.org/public/zverlov/problem.smt2).
Did u mean this by benchmark or something else?

When I try to run z3 in the terminal together with this smt file, for some reason, the timeout of 1 min doesnt work. Therefore I didnt get a result.

Also I tried to solve this problem using java-api on a MacOS and on Windows. On both systems i got the same error.


best

Sergey

**Comment by NikolajBjorner** [comment]
Note: The :opt.timeout option should be replaced by :timeout. I will remove this option altogether. There is just the main timeout parameter that will be used by opt.

**Comment by NikolajBjorner** [comment]
I have had some trouble reproducing the reported bug. I was unable to replay the log.
Sometimes users run into the situation where the dll that the Java/C# code links against is an older version, but the report that you have error on two systems seems to rule this out.
I have added a version line so that I can slightly easier track version compatibility issues for log files.

**Comment by zverlov** [comment]
Hey,

we used the new nightly build of the java-api (OSX) and created a new log file. [here](download.fortiss.org/public/zverlov/z3_new.log)
The problem still persists.


best


Sergey

**Comment by NikolajBjorner** [comment]
Thanks, that helped. A timeout triggered cancellation, then retrieving models crashed. It should be a bit more resilient towards cancellation, but generally check the return status and if Z3 returns undef, there is no assurance that models are available. Still, Z3 should not crash, of course, even if you call it to retrieve the box models.

**Comment by NikolajBjorner** [comment]
Can I close the issue?

**Comment by NikolajBjorner** [comment]
Closing, I believe I fixed the reported issue.
