### ISSUE TITLE
Unexpected Unknown answer instead of a SAT on certain inputs

### ISSUE THREAD

**Issue by esteffin** [Z3Prover/z3#6542]
Hi,
I'm a developer of [CBMC](https://github.com/diffblue/cbmc) using Z3 as a backend.

I noticed that when solving the attached (and other similar) SMT system Z3 hangs and then returns an `unknown` result instead of `sat`.

This behaviour happens on Z3 versions newer than `4.8`, while on `4.8` the correct `sat` answer is given in few milliseconds.

Input SMT file: [sat-unknown.txt](https://github.com/Z3Prover/z3/files/10438402/sat-unknown.txt)

Is there any explanation for this?

OS: at least MacOS, Ubuntu.

**Comment by NikolajBjorner** [comment]
A further investigation should use bisect to learn digression push. 

Note that z3 sat-unknown.txt -v:2 smt.ematching=false works

only mbqi will allow establishing sat. ematching works against mbqi (maybe useful to use this example 
to investigate whether it can be made to not work against it).

**Comment by NikolajBjorner** [comment]
You can avoid quantifiers

```
(assert (= ( (as const (Array (_ BitVec 64) (_ BitVec 8))) #x01) array_2))
(assert (= ( (as const (Array (_ BitVec 64) (_ BitVec 8))) #x00) array_0))
```

this also helps.

ematching introduces an instantiation that uses extensionality for the two arrays.
This messes up finite model building.

**Comment by NikolajBjorner** [comment]
Use one of the prescriptions described above to resolve the issue on your side.
