### ISSUE TITLE
Spacer (global guidance): assertion failed

### ISSUE THREAD

**Issue by corwin-of-amber** [Z3Prover/z3#6543]
I stumbled upon this situation:
```
ASSERTION VIOLATION
File: /Users/corwin/var/ext/z3/master/src/muz/spacer/spacer_global_generalizer.cpp
Line: 331
UNEXPECTED CODE WAS REACHED.
4.12.0.0 ca6fed8b25331cd6a472d3296b4b28b73c0c993b z3-4.8.4-7099-gca6fed8b2
Please file an issue with this message and more detail about how you encountered it at https://github.com/Z3Prover/z3/issues/new
```

This is the file that caused it.
[assertion_failed_in_globalgen.smt2.txt](https://github.com/Z3Prover/z3/files/10443728/assertion_failed_in_globalgen.smt2.txt)
```
z3 fp.spacer.global=true assertion_failed_in_globalgen.smt2
```

**Comment by NikolajBjorner** [comment]
What should be done about the bug reported by the second son of Oberon and father of Merlin?

**Comment by hgvk94** [comment]
Thanks for reporting it. I am looking into it. 
Sorry, it's been a month.  I was in paper deadline mode and didn't notice the time.

**Comment by corwin-of-amber** [comment]
Hurray go Hari 🎉
