### ISSUE TITLE
[Question] Is const-array possible to use in QF_ALIA?

### ISSUE THREAD

**Issue by hagozaebii** [Z3Prover/z3#6545]
Hello

Recently, I saw a result that I did not understand. examples are as follows:

```
(set-logic QF_ALIA)
(assert (= 1 (select ((as const (Array Int Int)) 1) 1)))
(check-sat)
```

z3 would give an error (error "line 2 column 50: unknown constant const (Int) (Array Int Int) ") about the file. However, z3'd give 'sat' when deleting set-logic

```
(assert (= 1 (select ((as const (Array Int Int)) 1) 1)))
(check-sat)
```

For now, I don't know how to understand this situation. const-array('K' in python API) is forbidden to use in QF_ALIA?
If so, could I know logics where const-array would be admitted?

Thanks for reading

**Comment by NikolajBjorner** [comment]
"const" is not part of SMTLIB2 arrays. 
Just don't set the logic.
