### ISSUE TITLE
help wanted to about simplify tactics

### ISSUE THREAD

**Issue by QiZhou1992** [Z3Prover/z3#655]
Hi,I post here try to get some help about simplify tactics
For formula has the following patterns.
First 
(= (term1) + (* -1 term2) 0), is there any tactics that can simplify this formula to (= term1 term2)
Second
(>= (+ (* -1 term1) (* -1 term2)) -1 ), is there any tactics that can simplify this formula to (<= (+ term1 term1) 1) ? 
Thank you for the help.

**Comment by NikolajBjorner** [comment]
The answer would be no. 
The simplification tactic we expose apply basic simplifications. They don't ensure that the output corresponds to any particular intent.
