### ISSUE TITLE
Z3-4.12.1 doesn't build (OS X 13.2) : undefined symbol ast_smt2_pp

### ISSUE THREAD

**Issue by solas** [Z3Prover/z3#6555]
g++  -o z3  shell/lp_frontend.o ...  util/util.a -lpthread 
Undefined symbols for architecture x86_64:
  "ast_smt2_pp(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, func_decl*, expr*, smt2_pp_environment&, params_ref const&, unsigned int, char const*)", referenced from:
      model_converter::display_add(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, smt2_pp_environment&, ast_manager&, func_decl*, expr*) in tactic.a(model_converter.o)
     (maybe you meant: ast_smt2_pp(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, func_decl*, expr*, smt2_pp_environment&, params_ref const&, unsigned int, char const*, bool))
ld: symbol(s) not found for architecture x86_64

Same result with clang++

**Comment by NikolajBjorner** [comment]
looks like a compiler issue around overload and default argument resolution. 
I have changed the signature of the function it complains about to work around it.
