### ISSUE TITLE
order in (and) expression changes evalutation value

### ISSUE THREAD

**Issue by vovan1** [Z3Prover/z3#656]
Hi,
i found a bug which comes up than using online solver: http://rise4fun.com/z3/
i tried 2 formulas only with a different order of arguments in the AND-clause 

http://rise4fun.com/Z3/h2HI
vs. 
http://rise4fun.com/Z3/Ezslf

both result in different solutions, thought both calls are equivalent. Any ideas?

Greetings

**Comment by NikolajBjorner** [comment]
Z3 does not need to produce equal models for equivalent formulas.
This is common to essentially all search-based constraint solvers.

**Comment by vovan1** [comment]
to be precise here, one evaluates the formula correctly, the 2nd is evaluated as unknown.

**Comment by NikolajBjorner** [comment]
Z3 isn't complete for non-linear integer arithmetic so sometimes it will find an assignment other times not.

**Comment by vovan1** [comment]
did you even open it?
if thats not a linear  integer arithmetic for you guys, then i give up
actually it's a simple linear optimization program which worked on Z3 even for much harder cases!

The reason i consider it as a bug, is since Z3 in my opinion orders the elements at least somehow before evaluating. I changed constraint order in and expression ,it failed to find solution. 

I just wanted to let you guys know, if Z3 should be incomplete in this feature is fine by me,
i dont profit or loose anything if you leave it like that :)

**Comment by NikolajBjorner** [comment]
line 37: (* prev1_TO_prev1 prev1) (* prev2 prev2_TO_prev1)
