### ISSUE TITLE
Invalid model issue on QF_SLIA

### ISSUE THREAD

**Issue by fwangdo** [Z3Prover/z3#6563]
Greetings,
For this instance, an invalid bug occurred.
We tried to make this instance as small as possible. We sincerely hope that our report would be helpful for the z3 team.

commit: [304b316](https://github.com/Z3Prover/z3/commit/304b316314c91fdb759def38df38ca47149b5ae0)

```
$ ./z3 ./small.smt2 model_validate=true
sat
(error "line 4 column 10: an invalid model was generated")

$ cat ./small.smt2
(declare-fun v () String)
(declare-fun m () Int)
(assert (< 0 (- (- (seq.last_indexof "JH" v)) m)))
(check-sat)
```

**Comment by NikolajBjorner** [comment]
File fuzz bugs into appropriate consolidated bugs (there is one for sequences).

**Comment by fwangdo** [comment]
@NikolajBjorner Thanks for letting me know. I'll do it however, I do not know what is 'appropriate consolidated bugs' that you mentioned. I found some issues in this repo related to z3str. But those issues were not found in default mode differently from this instance. Could I know which one is the issue that I need to file?

**Comment by NikolajBjorner** [comment]
https://github.com/Z3Prover/z3/issues/6346
