### ISSUE TITLE
Parametric datatype inference

### ISSUE THREAD

**Issue by BillHallahan** [Z3Prover/z3#6568]
The below SMT-LIB formula:
```
(declare-datatypes (a) ((bracket_dt (bracket (i Int)))))

(declare-fun g ((bracket_dt Real)) (Bool))
(declare-fun f ((bracket_dt Int)) (Bool))

(assert (f (bracket 1)))

(check-sat)
(get-model)
```
results in the error:
```
(error "line 6 column 22: unknown constant f ((bracket_dt Real)) 
declared: (declare-fun f ((bracket_dt Int)) Bool) ")

```
Removing the line declaring `g` causes the error to stop occurring, so I suspect that somehow the sort of bracket is being "fixed" by `g`.  I would expect to not get an error at all, as my understanding is that the sort of bracket is parametric.

**Comment by NikolajBjorner** [comment]
```
(declare-datatypes (a) ((bracket_dt (bracket (i Int)))))

(declare-fun g ((bracket_dt Real)) (Bool))
(declare-fun f ((bracket_dt Int)) (Bool))

(assert (f ((as bracket (bracket_dt Int)) 1)))

(check-sat)
(get-model)

```

The range of bracket is ambiguous, you have to use type ambiguation.

**Comment by NikolajBjorner** [comment]
The context of f is not available when inferring the type of the argument: f could be overloaded too.

**Comment by BillHallahan** [comment]
Ah great thanks- sorry for the false report!
