### ISSUE TITLE
Evaluation of BV multiplication overflow/underflow operators not working

### ISSUE THREAD

**Issue by fabian-r** [Z3Prover/z3#657]
When handed to the evaluation on a model, expressions containing operators for checking for (un)signed over/underflow of bitvector multiplication are not evaluated to a boolean constant as one would expect. Instead, just its arguments are evaluated.

These operators are:
```
bvsmul_noovfl
bvumul_noovfl
bvsmul_noudfl
```

The problem can be reproduced e.g. with the following SMT 2 specification (but also occurs for similar expressions constructed and evaluated using C/C++ bindings):
```
(declare-const a (_ BitVec 8))
(declare-const b (_ BitVec 8))
(declare-const c (_ BitVec 8))
(assert (and (= a #x04) (= b #x05) (= c #x74)))
(check-sat)
(get-model)
(eval (bvsmul_noovfl a b)) ; should be true
(eval (bvsmul_noovfl c b)) ; should be false
(eval (bvumul_noovfl a b)) ; should be true
(eval (bvsmul_noudfl a b)) ; should be true
```

**Comment by wintersteiger** [comment]
Thanks for the report! These have now been added to the rewriter, which should evaluate them all.
