### ISSUE TITLE
Z3 Nuget package: missing libz3.so for linux

### ISSUE THREAD

**Issue by ptr1120** [Z3Prover/z3#6570]
Hello,

since version 4.12.0 the Z3 Nuget package misses the native `libz3.so` for the linux-x64 runtime.

![image](https://user-images.githubusercontent.com/582627/216828810-ee8f67c2-3320-440b-a7ce-29d299c9e6f1.png)

**Comment by NikolajBjorner** [comment]
Can you check https://github.com/Z3Prover/z3/releases/download/Nightly/Microsoft.Z3.4.12.2.4717-Nightly.nupkg

**Comment by ptr1120** [comment]
Now it contains also linux-x64 libz3.so. Thank you very much!

<img width="400" alt="image" src="https://user-images.githubusercontent.com/582627/216921349-b995347c-e735-45b6-8029-19096f9ea90f.png">

**Comment by benharri** [comment]
This is missing again starting in 4.12.0 nuget
