### ISSUE TITLE
Linux release builds of 4.12.x depend on very new distributions

### ISSUE THREAD

**Issue by atomb** [Z3Prover/z3#6572]
The Linux binaries for 4.12.0 and 4.12.1 on the releases page depend on glibc 2.35 (released Feb 2022), rather than the glibc 2.31 (released Feb 2020) that previous recent releases have depended on. This prevents them from running on distributions more than a year old. I suspect that this may have been accidental, and a consequence of building on `ubuntu-latest` instead of `ubuntu-20.04`, since `ubuntu-latest` just recently switched to `ubuntu-22.04`.

Would it be possible to have binaries on the releases page that work with glibc 2.31, as well? It would be possible to build them independently, but I suspect many Linux users would be happy to have pre-built binaries that can run on slightly older distributions.

**Comment by NikolajBjorner** [comment]
I updated nightly.
Take a look and see if this will be workable for release bits

**Comment by atomb** [comment]
> I updated nightly. Take a look and see if this will be workable for release bits

Thanks for the quick response!

**Comment by atomb** [comment]
Where are nightly builds located these days? I can't seem to find them.

**Comment by NikolajBjorner** [comment]
https://github.com/Z3Prover/z3/releases/tag/Nightly

**Comment by atomb** [comment]
The nightly builds work very nicely for our purposes (GitHub workflows on `ubuntu-20.04` runners). Do you think there's any chance it'd be feasible to update the 4.12.1 release with a similar glibc 2.31 build?

**Comment by atomb** [comment]
We've migrated toward [building our own solver binaries](https://github.com/dafny-lang/solver-builds), so this isn't so critical for the Dafny project, as least. I suspect other Linux users might appreciate it, though.

**Comment by NikolajBjorner** [comment]
The newer releases have a down-level Ubuntu as well
