### ISSUE TITLE
Documentation discrepancy: seq.fold_left/seq.foldl

### ISSUE THREAD

**Issue by LeventErkok** [Z3Prover/z3#6573]
https://microsoft.github.io/z3guide/docs/theories/Sequences/

lists the function as `seq.fold_left`. However, playing with a recently built z3, I believe the actual name used is `seq.foldl`.

**Comment by NikolajBjorner** [comment]
it is overloaded, I have updated documentation to mention this

https://microsoft.github.io/z3guide/docs/theories/Sequences/

**Comment by LeventErkok** [comment]
@NikolajBjorner Thanks. I guess I'm not sure what "overloaded" means in this context. I couldn't get z3 to recognize any scripts that had the word `seq.fold_left` in it. Was that supposed to work at all?
