### ISSUE TITLE
Sequence of character are coming as unicode character rather than ascii characters

### ISSUE THREAD

**Issue by vikas-sapientai** [Z3Prover/z3#6574]
Hi Team,

I am using a java Z3 solver version "4.10.1".

I am creating Context by passing "encoding": "ascii" in the context params map.

```
        Map<String, String> paramsMap = new HashMap<>();
        paramsMap.put("encoding", "ascii");
       Context context = new Context(paramsMap);
```

Then I created an exp for sequence of characters i.e. 

```
Expr<SeqSort<CharSort>> firstExpression = context.mkConst("abcd",
            context.mkSeqSort(context.mkCharSort()));

```

Subsequently, I tried to solve the expression but the model is giving unicode characters.

```
(define-fun abcd () String
  "\u{4100}") 
```

Is there something that I am missing in my code for expression to generate only ascii characters.

Also, the above unicode character is evaluated to integer value 16640.  Can someone pls explain how the unicode character "\u{4100}" is evaluated to value 16640 by z3?

```
(define-fun abcd_int1 () Int
  16640)

```

**Comment by vikas-sapientai** [comment]
@NikolajBjorner -- any inputs from your side?

**Comment by NikolajBjorner** [comment]
See https://github.com/Z3Prover/z3/issues/6490 reported dec 2022
I can't support downlevel z3. 10.1 is from Jul 22, 2022.
