### ISSUE TITLE
QF_BV Incremental solving disjoint clauses performance

### ISSUE THREAD

**Issue by GreenBeard** [Z3Prover/z3#6578]
I'm not really sure if this warrants an issue, but it seems like a serious enough performance delta to be worth mentioning. Feel free to close this issue if you feel it isn't appropriate, if it is a known issue, or I'm just incorrect.

Multiple independent/disjoint `assert`ions in QF_BV with incremental solving seem to solve much more slowly when they are checked with a single `check-sat` as opposed to associating each one with a `check-sat`. It is possible that I am misdiagnosing the issue, but that is what I am starting to suspect after poking, and prodding a larger smtlib2 problem into a smaller one that still exhibits unusually slow performance. The delta in performance seems a lot smaller on "Z3 version 4.12.0 - 64 bit" than "Z3 version 4.11.2 - 64 bit".

I have attached an example below that takes half the time on 4.12.0 with the first `check-sat` uncommented than with it commented out.

```
(set-info :smt-lib-version 2.6)
(set-option :produce-models false)
(set-option :print-success true)
(set-option :smtlib2_compliant true)
(set-option :global-declarations true)
(set-logic QF_BV)

(declare-fun v!176 () (_ BitVec 107))
(declare-fun v!175 () (_ BitVec 107))
(declare-fun v!174 () (_ BitVec 107))
(declare-fun v!173 () (_ BitVec 107))
(declare-fun v!172 () (_ BitVec 107))
(declare-fun v!171 () (_ BitVec 107))
(declare-fun v!170 () (_ BitVec 107))
(declare-fun v!188 () (_ BitVec 70))
(declare-fun v!187 () (_ BitVec 70))
(declare-fun v!186 () (_ BitVec 70))
(declare-fun v!185 () (_ BitVec 70))
(declare-fun v!184 () (_ BitVec 70))
(declare-fun v!183 () (_ BitVec 70))
(declare-fun v!182 () (_ BitVec 69))
(declare-fun v!181 () (_ BitVec 1))
(declare-fun v!180 () (_ BitVec 67))
(declare-fun v!179 () (_ BitVec 67))
(declare-fun v!178 () (_ BitVec 67))
(declare-fun v!177 () (_ BitVec 38))
(push 1)
(assert (let ((a!1 (bvnot (bvor (bvnot (bvudiv v!174 v!175)) (bvnot v!176)))) (a!2 (bvlshr (bvnot (bvor (bvnot v!170) (bvnot v!171))) (bvudiv v!172 v!173)))) (not (bvule a!1 a!2))))
(echo "check-sat a")
;(check-sat)
(push 1)
(assert (let ((a!1 (bvurem (concat v!181 v!182) (bvnot (bvor (bvnot v!183) (bvnot v!184)))))) (or (= (bvudiv (concat #b00000000000000000000000000000 v!177) v!178) (bvshl v!179 v!180)) (bvule (bvurem (bvudiv v!185 v!186) (bvurem v!187 v!188)) a!1))))
(echo "check-sat b")
(check-sat)
```

**Comment by NikolajBjorner** [comment]
This has to do with pre-processing. Some useful preprocessing isn't applied in incremental mode with current z3. Making these useful preprocessing directives available requires some structural changes. 
They can be accessed from a new core, which is not yet generally tuned, but you can see the effect:

remove (set-logic QF_BV) and run with the option
z3 6578.smt2 -v:10 sat.smt=true

The verbose output shows that it applies elim-unconstrained to remove subterms and make the problem easier to solve.
