### ISSUE TITLE
Windows x64 bit build is broken.

### ISSUE THREAD

**Issue by clovett** [Z3Prover/z3#658]
using windows 10 sdk bits you get these errors:

```
C:\Program Files (x86)\Windows Kits\10\include\10.0.10586.0\um\winbase.h(8842): error C2065: 'InterlockedIncrement64': undeclared identifier
C:\Program Files (x86)\Windows Kits\10\include\10.0.10586.0\um\winbase.h(8874): error C2065: 'InterlockedDecrement64': undeclared identifier
C:\Program Files (x86)\Windows Kits\10\include\10.0.10586.0\um\winbase.h(8910): error C3861: 'InterlockedExchange64': identifier not found
C:\Program Files (x86)\Windows Kits\10\include\10.0.10586.0\um\winbase.h(8964): error C3861: 'InterlockedExchangeAdd64': identifier not found
C:\Program Files (x86)\Windows Kits\10\include\10.0.10586.0\um\winbase.h(8974): error C3861: 'InterlockedExchangeAdd64': identifier not found
C:\Program Files (x86)\Windows Kits\10\include\10.0.10586.0\um\winbase.h(9021): error C3861: 'InterlockedAnd64': identifier not found
C:\Program Files (x86)\Windows Kits\10\include\10.0.10586.0\um\winbase.h(9031): error C3861: 'InterlockedOr64': identifier not found
C:\Program Files (x86)\Windows Kits\10\include\10.0.10586.0\um\winbase.h(9041): error C3861: 'InterlockedXor64': identifier not found
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\cl.EXE"' : return code '0x2'
```

I think the right fix is to define this flag before including windows.h:
```
#define NOWINBASEINTERLOCK
#include <windows.h>
```

**Comment by NikolajBjorner** [comment]
I am not sure what setup is referred to.

Our own nightly build is 11 hours old: https://github.com/Z3Prover/bin/blob/master/nightly/z3-4.4.2.628a6378c2b7-x64-win.zip
and not broken.

**Comment by wintersteiger** [comment]
This looks like the build was configured for one platform but then built for a different one (which doesn't support intrinsics or OpenMP). I'm pretty sure the Windows 10 SDK did not introduce any new mandatory macros. The NOWINBASEINTERLOCK in particular is used to disable those Interlocked operations, so that most likely all hell will break loose if you try to use Z3 in any kind of parallel context later.

How are you building Z3? E.g., command line, if so which VS command line prompt, what version of the tools, or the VS configuration of your solution, especially which macros are defined? Also, what's your flavour of Windows and are you trying to cross-compile?

**Comment by clovett** [comment]
Just following the build instructions on your wiki using VS 2015 Developer Command Prompt and Python 2.7.

python scripts/mk_make.py -x
cd build
nmake

**Comment by NikolajBjorner** [comment]
Did you try the approach described in README-CMake.md?
We are not building for the SDK, so have no insight into what your environment requires, but the cmake systems offers an alternative build.

**Comment by wintersteiger** [comment]
When building with -x you want to use a 64-bit development environment, ideally including a 64-bit Python. The "Developer Command Prompt for VS2015" sets your compiler up to compile 32-bit binaries. I'm not sure whether you can switch that prompt over to x64, but you should also have the "VS2015 x64 Native Tools Command Prompt" that should definitely work.

**Comment by clovett** [comment]
The "VS2015 x64 Native Tools Command Prompt" works!  I should have thought of that, thanks.

**Comment by wintersteiger** [comment]
Fantastic, thanks for reporting back!

**Comment by techvoltage** [comment]
Can you please add this to install page as well. I came here through google.
This might help [How to: Enable a 64-Bit Visual C++ Toolset on the Command Line](https://msdn.microsoft.com/en-us/library/x4d2c09s.aspx)

**Comment by alexchandel** [comment]
To future googlers seeing this in your x86 build: make sure you didn't somehow accidentally define `WIN64` in your x86 build.  Check your props, and your `Directory.Build.props` and `Directory.Build.targets` if you have them.
