### ISSUE TITLE
Solutions that do not live up to the constraints

### ISSUE THREAD

**Issue by majaadall** [Z3Prover/z3#6589]
Hi
I am using z3 to make an SMT problem, do bit blasting, solve it and uniformly sample from the possible solutions in a SAT solver and then reverse the values back to integers. However, I am finding that the solutions I end up with do not live up to the contraints. I have tried with the following problem

x1 = BitVec('x1', 2)
x2 = BitVec('x2', 2)
g = Goal()
bitmap = {}
for i in range(2):
    bitmap[(x1,i)] = Bool('x1'+str(i))
    mask = BitVecSort(2).cast(math.pow(2,i))
    g.add(bitmap[(x1,i)] == ((x1 & mask) == mask))
    bitmap[(x2,i)] = Bool('x2'+str(i))
    mask = BitVecSort(2).cast(math.pow(2,i))
    g.add(bitmap[(x2,i)] == ((x2 & mask) == mask))
    
g.add(x1 + x2 == 2)
t = Then('simplify', 'bit-blast', 'tseitin-cnf')
subgoal = t(g)

Which gave the following solutions (x1=0, x2=2), (x1=2, x2=0), (x1=1, x2=1), (x1=3, x2=3).
The first solutions are fine, but I do not understand how I can get the last one. 
I tried to change the constraint to g.add(x1 + x2 == 4), and it found the exact same solutions.

Any idea about what I am doing wrong?

**Comment by NikolajBjorner** [comment]
The bit-vectors have size 2, so the valid bits are 00, 01, 10, 11, 
Also 11 + 11 = 10

**Comment by majaadall** [comment]
Thank you,
However, this still does not explain why I got the same results for the contraint (x1 + x2 ==4).
I also tried to use a bitVec of size 3 and again use the constraint (x1+x2==4), which, among other, gave the result (x1=6, x2=0).

Any idea what is happening?

**Comment by NikolajBjorner** [comment]
You can print SMT2 version of your goal and see what kind of conversions it made to 4, which does not fit in 2 bits.

**Comment by majaadall** [comment]
Thank you again.
However, I still do not understand how I can get solutions such as (x1=2, x2=6) when using 3 bit vecs and x1+x2 == 4?
