### ISSUE TITLE
Does Z3 support scientific notation for real type in smt2 code.md

### ISSUE THREAD

**Issue by nuppt** [Z3Prover/z3#659]
Hi, at first, I want to know whether Z3 supports scientific notation like 1.234E5 or 0.35e2 or any other syntax in smt2 code.

I've searched it on google and only found one sentence describing as "*- Added support for numbers in scientific notation at Z3_ast Z3_mk_numeral(__in Z3_context c, __in Z3_string numeral, __in Z3_sort ty).*", which is in Z3/RELEASE_NOTES.
It seems as a C API of Z3 but no specification with regard to scientific notation when I checked the Z3_mk_numeral item in C API document.

So I'm confused now that whether Z3 supports scientific notation for real type in smt2 code? If not, any other API gives the support?

**Comment by NikolajBjorner** [comment]
Thanks for the feedback on improving the documentation.
The good news is that the Z3 executables and libraries are also available so it is possible to try directly.

tryit.py:

    from z3 import *
    print RealVal("1.234E5")
    print RealVal("0.35e2")

Produces

123400
35
