### ISSUE TITLE
Refutational Soundness issue on default mode

### ISSUE THREAD

**Issue by fwangdo** [Z3Prover/z3#6593]
Greetings,
For this instance, a refutation soundness bug occurred. Also, we checked that this instance should be "SAT". We truly hope that this instance will be helpful for the z3 team.

```
$ ./z3 ./small.smt2
unsat

$ cvc5 ./small.smt2
sat

$ cat ./small.smt2
(set-logic ALL)
(declare-fun c () RoundingMode)
(declare-fun m () Float32)
(assert (and (fp.eq (fp (_ bv0 1) (_ bv0 8) (_ bv0 23)) (fp.div c m (fp (_ bv0 1) (_ bv255 8) (_ bv0 23)))) (not (fp.eq (fp (_ bv0 1) (_ bv0 8) (_ bv0 23)) (fp.div c m ((_ to_fp 8 24) c (/ (ite (fp.geq (fp (_ bv0 1) (_ bv255 8) (_ bv0 23)) m) 1.0 0.0) 2)))))))
(check-sat)
```

This bug looks similar to what we reported before(https://github.com/Z3Prover/z3/issues/6553). Both instances caused bugs in the commit version but "unknown" in the release version(4.12.1). However, we decided to report this instance since what we reported was an invalid model bug but this one is a refutation soundness bug. Hope that this report is meaningful to the z3 team.

commit: [7c08e53](https://github.com/Z3Prover/z3/commit/7c08e53e944f806af7db74cc512a197c4d76c7f6)

**Comment by NikolajBjorner** [comment]
move to #6553
