### ISSUE TITLE
Removing Z3_get_error_msg_ex breaks backwards compatibility

### ISSUE THREAD

**Issue by iagoabal** [Z3Prover/z3#660]
I develop unofficial Haskell bindings for Z3's API and one my users have noticed that you have removed ```Z3_get_error_msg_ex```. This change was made by commit bea68cd194b0 ("remove deprecated API functionality").

I know that ```Z3_get_error_msg``` has been deprecated for some time, and consequently I replaced it with ```Z3_get_error_msg_ex```. Removing ```Z3_get_error_msg``` it's fine, or even making it a synonym of ```Z3_get_error_msg_ex```. But removing ```Z3_get_error_msg_ex``` breaks backwards compatibility of Z3 4.4.2 with respect to 4.4.1, which is not nice. One would like to assume that any 4.4.y version will be backwards compatible with 4.4.x for y > x.

Could you instead deprecate ```Z3_get_error_msg_ex``` and remove it in Z3 4.5 or later?

Thanks,

**Comment by wintersteiger** [comment]
As far as I remember `Z3_get_error_msg` was deprecated and has been removed, but then `Z3_get_error_msg_ex` was renamed to `Z3_get_error_msg`. @NikolajBjorner: was there a motivation for this renaming other than makeing the names nicer? I suppose we could just re-introduce `Z3_get_error_msg_ex` as an alias.

**Comment by NikolajBjorner** [comment]
Motivation was to remove deprecated naming idiosyncrasies.

**Comment by iagoabal** [comment]
If you could add ```Z3_get_error_msg_ex``` back as an alias of the newer ```Z3_get_error_msg``` that would maintain backwards compatibility, and would be very much appreciated.

**Comment by NikolajBjorner** [comment]
let us know if the re-inclusion helps

**Comment by iagoabal** [comment]
It fixed the problem, my bindings now build and work perfectly using latest Z3 dev snapshot, thank you!
