### ISSUE TITLE
Surprising response to `get-value`

### ISSUE THREAD

**Issue by LeventErkok** [Z3Prover/z3#6603]
Given:

```
(set-logic ALL)
(declare-fun s0 () (Seq Int))
(define-fun  s1 () Int (seq.foldl (lambda ((x Int) (y Int)) (+ x y)) 0 s0))
(check-sat)
(get-value (s1))
```

I'm getting:

```
sat
(error "line 5 column 14: invalid get-value term, term must be ground and must not contain quantifiers")
```

I'm wondering why this is the case. I have the mental model that `define-fun` is equivalent to a sequence of `declare-fun` and an `assert`, but that doesn't seem to be the case:

```
(set-logic ALL)
(declare-fun s0 () (Seq Int))
(declare-fun s1 () Int)
(assert (= s1 (seq.foldl (lambda ((x Int) (y Int)) (+ x y)) 0 s0)))
(check-sat)
(get-value (s1))
```

I get:

```
sat
((s1 0))
```

Wondering if it'd be easy enough to support the first use case as well.

**Comment by NikolajBjorner** [comment]
I guess it is some error that got added when users started asking for values of proper quantifiers and were expecting z3 to fully evaluate quantifiers. Lambda terms ended up as quantifiers as well so they are treated the same relative to this error.

**Comment by NikolajBjorner** [comment]
4aa05b2b5759a1049464e9ff453c9b448d82b835
