### ISSUE TITLE
Question about paralell SMT solving engines in Z3

### ISSUE THREAD

**Issue by rainoftime** [Z3Prover/z3#6629]
### Discussed in https://github.com/Z3Prover/z3/discussions/6622

<div type='discussions-op-text'>

<sup>Originally posted by **rainoftime** March  6, 2023</sup>
I notice that there are several source files related to parallel solving.

1.  `z3/src/smt/smt_parallel.cpp`, which seems to be controlled by the following parameters

![image](https://user-images.githubusercontent.com/2357273/223030978-9fddd233-dbd7-49b9-8dba-4484f2873010.png)

2. `src/solver/parallel_tactical.cpp`, which is controlled by  the following parameters

![image](https://user-images.githubusercontent.com/2357273/223031093-feba7f1d-2d3e-4e62-9e10-22b31b806267.png)

Are the above files two independent engines? 
It seems that both of them are elated to cube-and-conquer? (Besides, only `z3/src/smt/smt_parallel.cpp` relies on lookahead in `/src/sat/sat_lookahead.cpp`)? 

Thanks!</div>

**Comment by NikolajBjorner** [comment]
There are three sources:

- The cube and conquer solver: https://z3prover.github.io/papers/programmingz3.html#sec-parallel-z3
- SAT core co-processing: https://z3prover.github.io/papers/programmingz3.html#sec-co-processing
- SMT core co-processing.

The SMT core co-processing uses a rounds-based algorithm. It runs N solvers with increasing timeouts. In each round, each thread assumes a distinct literal (selected by a weak lookahead heuristic). If a thread is unsat, but the core uses the assumed literal, the assumed literal is added as unit to the other threads. Units are shared among threads between rounds.

THe SAT core co-processing uses clause sharing during restarts. It also lets you run local search in separate threads.

**Comment by rainoftime** [comment]
Thanks!
