### ISSUE TITLE
Segmentation fault in smt::theory_arith<smt::mi_ext>::internalize_term_core(app*)

### ISSUE THREAD

**Issue by PhilippWendler** [Z3Prover/z3#663]
I have found a case where I get a segmentation fault in `smt::theory_arith<smt::mi_ext>::internalize_term_core(app*)` when I call `solverPush` in the Java API of Z3. I can reproduce it with the command-line version of Z3 in revision with this [replay log](https://github.com/Z3Prover/z3/files/339436/z3-segmentation-fault-internalize_term_core.txt).
Does this seem to be a bug in Z3 or in my calling code? How could I distinguish between these two cases?

I also have a [file from the original crash with more information dumped by the JVM
](https://github.com/Z3Prover/z3/files/339454/hs_err_pid21134.txt) and I can provide a core dump from the replay if you would like to see it.

**Comment by PhilippWendler** [comment]
Forgot to mention that the segfault is reproducible with the replay log in revision 37c9a31296c9bf17b835efd507997f1064427620.

**Comment by NikolajBjorner** [comment]
Z3 should not crash, of course, but seems your formula contains a free variable:

      (= PRED3 (= (+ |__ADDRESS_OF_main::array| (* (- 1) (:var 0))) 0))

**Comment by PhilippWendler** [comment]
Thank your for fixing the segmentation fault!
