### ISSUE TITLE
[Question] When model of sat bit-vector formula would be an empty list?

### ISSUE THREAD

**Issue by hagozaebii** [Z3Prover/z3#6630]
Hello, recently, I tried to solve the below formula with z3 py.
```
>>> cpx
8 <= (x | 1) << 2
>>> solver = Solver()
>>> solver.add(cpx)
>>> solver.check()
sat
>>> solver.model()
[]
>>> solver.sexpr()
'(declare-fun x () (_ BitVec 4))\n(assert (bvsle #x8 (bvshl (bvor x #x1) #x2)))\n'
```
The result was sat however, the model of the formula was an empty list. I was embarrassed since I had thought that z3 would give a model about 'x'.
I tried to know what was going on and I also found there is a bit-vector formula that z3 gives a model that is not an empty list. However, I still do not know what difference between the two formulae decides whether a model would be an empty list or not.
So, I hope to know when z3 would give an empty list as a model for a bit-vector formula.

Thanks for your time.

**Comment by nunoplopes** [comment]
By default, models produced by Z3 may be partial, i.e., where "don't care" variables aren't set.
You can force it by using, for example, `solver.model().eval(x, model_completion=True)`.

You can also set the global parameter `model.partial=false`.

**Comment by hagozaebii** [comment]
Thanks, @nunoplopes . It is what I want exactly.
Thanks again.
