### ISSUE TITLE
`optimize` - inconsistency between model value and `lower` value

### ISSUE THREAD

**Issue by Tomaqa** [Z3Prover/z3#6638]
I do not attach a minimal example yet, because I am not sure whether I'm just missing something elementary.

I am using `optimize` class, not `solver`.

First of all, what is the relationship of values that I get from `model` and `optimize::handle` ?
After any `check` call with `sat` result, are the values supposed to be consistent, or not?
Can I freely use `get_model` as in the case of `solver`, or is it somewhat different here in the case of `optimize` ?

Is `model_validate` parameter supposed to have any effect on this?

In most of my cases, the behavior is expected and the values are the same. Unfortunately, not always.

Also, I use `optimize` incrementally, i.e. with `push` and `pop`.
I observed that `incremental` parameter has an effect on the runtime and on appearance of the mentioned inconsistencies, but it is happening in both settings of the parameter, it just may happen with different instances.

I followed the `optimize` examples in `example.cpp`, but they are trivial and it is not clear how the class should be used when more than one call to `check` is required.

**Comment by NikolajBjorner** [comment]
unsure what you are facing. Sounds like a bug, but the description is a level of indirection from something reproducible.
optimize::handle has to do some coordination to populate the objective values from the model. Pre-processing could interfere.
Closing without repro

**Comment by Tomaqa** [comment]
I managed to construct a "minimal" [example](https://github.com/Z3Prover/z3/files/11071964/z3_bug.zip).

I observed that there are multiple ways how to "avoid" (hide) the bug - it appears only under certain circumstances.
I marked the areas which can hide the bug with `//!!` comments in the code.

`z3 --version` gives `Z3 version 4.12.2 - 64 bit`.
Compiled with `g++ z3_bug.cpp -lz3`.
The behavior seems to be the same with `g++ z3_bug.cpp -lz3 -O3 -DNDEBUG`, and also if using `clang`.

**Comment by NikolajBjorner** [comment]
Your constraints contain strict inequalities. So it uses infinitesimals to determine optimality. The infinitesimals are replaced by values computed during model completion. Alignment between the model and the handle values was untested for this situation. 
Given the scenario I am not sure it makes sense to change this. The handles are allowed to contain symbolic expressions for infinitesimals and infinity.

**Comment by Tomaqa** [comment]
I'm not sure if I fully understand, but in any case, I verified that when all strict inequalities are replaced by non-strict versions in the attached example, the inconsistency still appears, only with different values (now it is "lower != model: 0.000000 != 4.000000").

**Comment by Tomaqa** [comment]
I could not reproduce the inconsistency using an `*.smt2` file... For example, when I printed out the resulting solver from the example, I always got consistent values of `get-value (totaltime)` and `get-objectives`.

**Comment by Tomaqa** [comment]
I slightly reduced the example and examined it a bit further.
See [this](https://gitlab.com/Tomaqa/mapf_r/-/tree/dev/misc/bugs/z3_model_inconsistency) where there is a description in `README.md`.

Also, I would like to kindly ask whether this bug is currently a priority for you.
Thank you.
