### ISSUE TITLE
Question about optimize and runtime

### ISSUE THREAD

**Issue by seohyunbae** [Z3Prover/z3#6649]
Hello. I have a question about optimize and runtime.

When i run the z3, there is runtime difference with different optimize option sequence
(e.g. min A -> min B : 20min but min B -> min A : 5hour)

So i guess
 1. z3 solver will search whole solution space
 2. but priority of search space(order of solution that z3 visit or find) is dependent on sequence of optimize options.
 3. so runtime will be different when we use different sequence of optimize options.
 4. (good optimize order reduce runtime, but bad optimize order increase runtime) 

Is it right?

Is the order of finding solution dependent on order of optimize option?

**Comment by NikolajBjorner** [comment]
runtime depends on search traversal that depends on the input state. If the input state changes through incremental use or random seeds search time can vary
