### ISSUE TITLE
Interpolant contains free variable

### ISSUE THREAD

**Issue by PhilippWendler** [Z3Prover/z3#665]
I have an interpolation query with quantifiers over UFs and integers, and in one case the interpolant produced by Z3 contains a free variable `(:var 0)`. This causes problems for me when using the interpolant later on (#663), and I guess this is not intended.

It is reproducible with Z3 in revision e518d4a5fe3b824d5e9deb3d16eb1faa248a52d8 with [this query](https://github.com/Z3Prover/z3/files/341005/z3-interpolant-with-free-variable.txt) and with the online version ([see here](http://rise4fun.com/Z3/Mekf)).

**Comment by NikolajBjorner** [comment]
Closing as the code that was exercised in this issue is no longer part of the code base, #1646.
