### ISSUE TITLE
Getting values from a transitive closure

### ISSUE THREAD

**Issue by LeventErkok** [Z3Prover/z3#6657]
For this benchmark:

```
(declare-sort U 0)
(declare-fun a () U)
(declare-fun b () U)
(declare-fun c () U)
(declare-fun R (U U) Bool)
(assert (R a b))
(assert (R b c))
(check-sat)
(eval ((_ transitive-closure R) a c))
```

z3 prints:

```
sat
((_ transitive-closure R) U!val!0 U!val!2)
```

I was simply expecting to get `true` as the result. Is there a reason why the output doesn't get reduced to a simple boolean?

**Comment by NikolajBjorner** [comment]
TC is treated similar to quantifiers. There isn't a way to evaluate them.
It connects with the quantifier bug: z3 can't use model based quantifier instantiation to decide satisfiability of quantified formulas that use TC. Z3 would have to detect that a quantified formula contains TC and then 'give up'.
