### ISSUE TITLE
invalid model issue with tactics under AUFNIRA 

### ISSUE THREAD

**Issue by zhendongsu** [Z3Prover/z3#6667]
Commit: https://github.com/Z3Prover/z3/commit/479f8442009987726e3c03fe5618b250acca383a
OS: Ubuntu 18.04

```
[656] % z3release model_validate=true small.smt2
sat
sat
(error "line 13 column 56: an invalid model was generated")
[657] % cat small.smt2
(set-logic ALL)
(declare-fun a (Int) Int)
(declare-fun b () Int)
(assert (= 1 (- (+ b (a b)))))
(check-sat-using (then simplify add-bounds qffd default))

(reset)

(set-logic AUFNIRA)
(declare-fun a (Int) Int)
(declare-fun b () Int)
(assert (= 1 (- (+ b (a b)))))
(check-sat-using (then simplify add-bounds qffd default))
```

**Comment by NikolajBjorner** [comment]
wont fix: qffd converts problem to finite domain using bit-vector. The solver doesn't load bit-vector solvers if you specify AUFNIRA. 

set-logic + tactics -> not a supported scenario. set-logic is an SMTLIB artifact to annotate benchmarks. tactics is not SMTLIB.
