### ISSUE TITLE
make z3 solver (python) deterministic

### ISSUE THREAD

**Issue by zhiqi-0** [Z3Prover/z3#6679]
Hi Team,

I wonder whether there is a way to make z3 solver deterministic.

I mainly use these interfaces to find a solution for a satisfied problem:

```py
import z3

solver = z3.Solver()

# problem statement
var1 =  z3.Int(...),
var2 = z3.If(...)
var3 = ...
...

assert solver.check() == z3.sat
model = solver.model()

var1_solution = model.eval(var1).as_long()
var2_solution = model.eval(var2).as_long()
...
```
I want to make the output of model.eval(), e.g., the value of `var1_solution`, to be deterministic among different re-runs of the program. How can I achieve this?

**Comment by NikolajBjorner** [comment]
python isn't a great interface for determinism: as soon as you use python hash sets/dictionaries the salt changes from run to run. 
I am not sure whether the gc is influenced, but it is outside your control.

Default strategies for z3 in some cases use timeouts. Maybe not for your specific use case, but could be. 
You should use SimpleSolver to be safe, or roll your own tactics.

Overall, don't use python for full determinism. 
You can use file I/O: write your python solver object to an smt2 file "print(solver.sexpr())" and then run the file over popen.
