### ISSUE TITLE
Interpolation: Proof Error!

### ISSUE THREAD

**Issue by PhilippWendler** [Z3Prover/z3#668]
The interpolation query from [this replay log](http://students.fim.uni-passau.de/~wendler/z3-interpolation-proof-error.log) produces the error "Proof Error!" with revision
0d0d504 of Z3. Is this a bug or an expected case of incomplete interpolation? (The error message sounds more like a bug, that's why I am asking).

**Comment by NikolajBjorner** [comment]
Closing as the code that was exercised in this issue is no longer part of the code base, #1646.
