### ISSUE TITLE
Term div0 appearing in interpolant leading to segmentation fault in Z3_get_decl_kind

### ISSUE THREAD

**Issue by PhilippWendler** [Z3Prover/z3#669]
I have an interpolation query over UFs plus integers that I give to Z3 via the Java API, and in the resulting interpolant the term `(div0 0)` appears. I then iterate recursively through the AST using the API, and when I reach this term I get a segmentation fault. `getAstKind` returns `Z3_APP_AST` for this tem, but `getDeclKind(ctx, getAppDecl(ctx, term))` segfaults in `getDeclKind`.

I have two questions here:
First: What is this div0 term and is it expected to appear in interpolants? I only found references to something like this for the theory of bitvectors, but I have only integers. When I try to parse the interpolant that Z3 itself produced with Z3, it tells me that `div0` is an unknown function.

Second: How can I avoid the segmentation fault during formula traversal? What else can I check before calling `getDeclKind` to ensure that the call is legal, if `getAstKind` has told me it is a `Z3_APP_AST`? I believe it crashes because it hits the UNREACHABLE assertion in line 992 of `api_ast.cpp` for this term. Is a case for `div0` missing here?

Interestingly, when dumping the interpolation query to SMTLIB2 format and running the command-line version, I get a different interpolant without this term. (This dump is here: [z3-interpolation-query-div0-smt2.txt](https://github.com/Z3Prover/z3/files/346194/z3-interpolation-query-div0-smt2.txt).)

However, I can reproduce the segmentation fault with [this replay log](https://github.com/Z3Prover/z3/files/346196/z3-interpolation-query-div0.txt).

**Comment by NikolajBjorner** [comment]
Closing as the code that was exercised in this issue is no longer part of the code base, #1646.
