### ISSUE TITLE
How to use the dotnet binding on macOS of arm64 architecture?

### ISSUE THREAD

**Issue by namasikanam** [Z3Prover/z3#6691]
I tried this [nightly built nuget package (4.12.2.4719-nightly)](https://dev.azure.com/z3build/Z3Build/_artifacts/feed/Z3-Nightly-Builds/NuGet/Microsoft.Z3/overview/4.12.2.4719-Nightly). 
However, I met the following error:
```bash
Unhandled exception. System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Z3, Version=4.12.2.4719, Culture=neutral, PublicKeyToken=9c8d792caae602a2'. The system cannot find the file specified.

File name: 'Microsoft.Z3, Version=4.12.2.4719, Culture=neutral, PublicKeyToken=9c8d792caae602a2'
```
I tried to copy the needed `libz3.dylib` to `bin/Debug/net7.0/`. It does not work.

[Here](https://drive.google.com/file/d/1VOeqYZ7IA5ULt0t7qd-61BqbDg0bqJ31/view?usp=sharing) is a minimal example to reproduce.

**Comment by NikolajBjorner** [comment]
there are no dotnet NuGet releases for ARM at this time.

**Comment by NikolajBjorner** [comment]
The build pulls ARM64 for osx into the nuget package. 
It sholud be for .net core (platform) I don't have a way to test it.
So a Mac user could help by buildling appropriate packaging and determine what to do.

**Comment by namasikanam** [comment]
> The build pulls ARM64 for osx into the nuget package. It sholud be for .net core (platform) I don't have a way to test it. So a Mac user could help by buildling appropriate packaging and determine what to do.

Thanks for replying. Maybe I could help, but I am unclear about what the Nuget package should be. Do you mean that the `libz3.dylib` in the build is incorrect? How could I build appropriate packaging?

**Comment by NikolajBjorner** [comment]
The nuget package is set up to include unmanaged code from different runtimes. 
It combines all 64bit versions into a single nuget package (potential issue is that ARM64 may not be compatible with x64 mixed mode .net)
It pulls the ARM64 dll from macos into a folder: runtimes\osx-arm64\native

The scripts are here:

https://github.com/Z3Prover/z3/blob/master/scripts/mk_nuget_task.py
https://github.com/Z3Prover/z3/blob/master/scripts/nightly.yaml

**Comment by NikolajBjorner** [comment]
I will note that I had some hit and miss experiences with loading the dlls for Windows platforms. Sometimes the unmanaged dll from the nuget package isn't fully extracted. It is possible that you are encountering this issue. This is outside of z3. 
You could try compiling with z3 outside of the nuget packaging, adding dependencies directly to your project. If the ARM64 binaries don't work even in this case, it is more likely an issue with z3's build. Otherwise, you can chase how runtime dependencies are extracted in your environment.
