### ISSUE TITLE
[Help Wanted!]Z3 executable too large

### ISSUE THREAD

**Issue by kumori123** [Z3Prover/z3#6698]
Hi, I'm trying to compile a z3 executable on ubuntu Linux, ARM64, which end up with a nearly 700M z3 executable, while the release versions are 40M.
Could you tell me the reason and give me some suggestions on how to make the executable smaller?
Thank you in advance!

**Comment by NikolajBjorner** [comment]
The issue report is not specific enough to allow assistance.
To give a chance for any feedback you should at minimum specify your build options.

Take for instance the Android ARM64 github action used on every commit. The uploaded artifacts are small and don't inflate much when decompressed (below 30MB).

https://github.com/Z3Prover/z3/actions/runs/4734282881

There are also independent linux builds of z3; 
https://koji.fedoraproject.org/koji/buildinfo?buildID=2137978
