### ISSUE TITLE
common module not found for python interface (when importing z3util)

### ISSUE THREAD

**Issue by g2graman** [Z3Prover/z3#67]
After cloning the repository and a successful build, I moved a script named `get_proof.py` into the build directory and invoked it. Note that my only imports from `get_proof.py` are

    from z3 import *
    from z3util import *

 but even after a successful build, importing `z3util` fails. The following is the traceback from invoking `get_proof.py`:

    $ python get_proof.py
    Traceback (most recent call last):
      File "get_proof.py", line 2, in <module>
        from z3util import *
      File ".../z3/build/z3util.py", line 6, in <module>
        import common as CM
    ImportError: No module named common

**Comment by g2graman** [comment]
Update: 

    $ find . -name '*common*'
    ./z3/build-dist/util/common_msgs.o
    ./z3/build-dist/util/common_msgs.h.node
    ./z3/build/util/common_msgs.o
    ./z3/build/util/common_msgs.h.node
    ./z3/src/util/common_msgs.cpp
    ./z3/src/util/common_msgs.h

Conclusion: the repository is missing the module. After searching for a bit I think I've found it, since the author's name, as cited by @leodemoura in [this StackOverflow answer](http://stackoverflow.com/questions/14080398/z3py-how-to-get-the-list-of-variables-from-a-formula), matches that of [this google code repository](https://code.google.com/p/common-python-vu/). So, I believe the `common` module is really the same as [this file](https://code.google.com/p/common-python-vu/source/browse/vu_common.py) from the last link, before it was renamed to `vu_common.py`

**Comment by wintersteiger** [comment]
Thanks for figuring out all the details of this problem! I removed the external import by adding the vset function and it now works fine for me. The fix is currently only available in the contrib branch, but it will be import into master soon.
