### ISSUE TITLE
Z3 str.to.int

### ISSUE THREAD

**Issue by pjljvandelaar** [Z3Prover/z3#670]
With the latest Z3 [version 4.4.2 - 64 bit - build hashcode 0d0d504d6273],
a smt2 file containing:
(declare-fun s$$1004() String)
(assert (= (str.to.int s$$1004) 7))
(check-sat)
(get-value (s$$1004))

results in wrong output:
sat
((s$$1004 ""))

Sat is correct, be the value should be "7"!

**Comment by pjljvandelaar** [comment]
Tianyi Liang has nicely documented how string to int and int to string can be realized in a problem solver:
see e.g. http://ir.uiowa.edu/etd/1478/
and http://link.springer.com/chapter/10.1007/978-3-319-08867-9_43

**Comment by NikolajBjorner** [comment]
I see, the semantics is that non-integer strings map to -1. In this case only the string "7" is possible.
I have updated the handling of str.to.int to take this into account.

**Comment by pjljvandelaar** [comment]
Thanks for the quick solution!
