### ISSUE TITLE
get_kind returns an invalid type

### ISSUE THREAD

**Issue by reteps** [Z3Prover/z3#6704]
https://github.com/Z3Prover/z3/blob/master/src/ast/ast.cpp#L407

```
ASSERTION VIOLATION
File: ../src/ast/ast.cpp
Line: 415
UNEXPECTED CODE WAS REACHED.
Z3 4.12.1.0
```

I am running z3 hooked up to a Flask server.

```
Python 3.9.2
Flask 2.2.3
Werkzeug 2.2.3
```

Pretty sure it is related to the Flask multi-threading.

**Comment by NikolajBjorner** [comment]
This error happens when users have stale versions of z3 in their python paths.
