### ISSUE TITLE
API request: computing MUS

### ISSUE THREAD

**Issue by cheshire** [Z3Prover/z3#671]
Hi,

Z3 is capable of computing an MUS (cf. src/solver/mus.h), but this functionality is not exposed through the C API.
Is it possible to expose it?
Or am I missing something and it's trivial to perform an MUS computation using soft constraints?

Thanks!

**Comment by NikolajBjorner** [comment]
You can get the mus if you use the smt or sat solver. Use smt.core.minimize=true and a similar configuration for sat. The mus is over assumptions and tracked assertions (assertandtrack). Not all modes give you mus (yet). For composite tactics, the core is not necessarily minimal.

**Comment by NikolajBjorner** [comment]
Can I close this?

**Comment by cheshire** [comment]
sure!
