### ISSUE TITLE
Cannot find variables in model.

### ISSUE THREAD

**Issue by hagozaebii** [Z3Prover/z3#6711]
Hello, 

Recently, while solving the bit vector formula with z3, I found an interesting fact.
The formula I used is as follows:
[13580.txt](https://github.com/Z3Prover/z3/files/11411923/13580.txt)

When this formula is solved using z3py, z3 gives the following model.
```
[T1@540 = 0,
 T1@440 = 102,
 T1@438 = 0,
 T1@437 = 0,
 T1@541 = 0,
 T1@539 = 0,
 T1@439 = 0,
 T1@542 = 0]
```
This result puzzled me a bit. This is because some variables (e.g T1@0, T1@1, T1@2..) used in the assert did not exist in the model.

How should we interpret these results?

Thanks for reading.

**Comment by NikolajBjorner** [comment]
variables not mentioned in the model are don't cares.
The SMTLIB2 interface will print model values also of don't cares, but the binary API does not.
