### ISSUE TITLE
Segmentation fault with fun-rec

### ISSUE THREAD

**Issue by brutalsavage** [Z3Prover/z3#6713]
**Description**:  Segmentation fault with `func-rec`

small code `small.smt2` to reproduce:
```
(declare-fun x () Int)
(declare-fun z () Int)

(define-fun-rec fib-odd ((n Int)) Int
  (ite (<= n 0)
       0
     (ite (= n 1)
          1
        (+ (fib-even (- n 1)) (fib-odd (- n 2))))))

(define-fun-rec fib-even ((n Int)) Int
  (ite (<= n 0)
           0
     (ite (= n 1)
              0
          (+ (fib-odd (- n 1)) (fib-even (- n 2))))))

(assert (= (mod (+ (fib-even x)) 13) z))

(check-sat)
```

output 
```
(error "line 9 column 28: unknown constant fib-even (Int) ")
Segmentation fault (core dumped)
```

Note: changing code to `define-fun` instead of `define-fun-rec ` no longer segfaults

**Command**: running z3 (6c24a70) with debug build `z3 small.smt2`

**Comment by NikolajBjorner** [comment]
these are fuzz bugs for malformed input. It isn't clear spending bandwidth on these helps anybody.
I may be closing such bugs without further comments in the future.
