### ISSUE TITLE
z3 building java binding error

### ISSUE THREAD

**Issue by PaulMeng** [Z3Prover/z3#672]
Move my stackoverflow question here. [http://stackoverflow.com/questions/38103771/z3-building-java-binding-error](url)
I got the error message below when compiling the z3 source code (37c9a31 commit) for Java binding on Mac El Captain(10.11.5). My Java version is 1.8.0_91. 
The commands used to compile the sources are: python scripts/mk_make.py --java; cd build; make; 

"/usr/bin/javac" ../src/api/java/enumerations/*.java -d api/java/classes

"/usr/bin/javac" -cp api/java/classes ../src/api/java/*.java -d api/java/classes

../src/api/java/Sort.java:134: error: an enum switch case label must be the unqualified name of an enumeration constant
        case Z3_SEQ_SORT:
             ^

../src/api/java/Sort.java:136: error: an enum switch case label must be the unqualified name of an enumeration constant
        case Z3_RE_SORT:
             ^
../src/api/java/Expr.java:2179: error: an enum switch case label must be the unqualified name of an enumeration constant
        case Z3_SEQ_SORT:
             ^

../src/api/java/Expr.java:2181: error: an enum switch case label must be the unqualified name of an enumeration constant
        case Z3_RE_SORT:
             ^

4 errors
make: *** [com.microsoft.z3.jar] Error 1

**Comment by cheshire** [comment]
@PaulMeng just to be sure, is it a clean build? (fresh checkout, "build" directory removed).
Incremental build does not always work.

Also could you try an earlier version, e.g. 736f2bef46fdf1ead7925bdf3e9af85eb54828dd ?

A possible hacky workaround is to compile without Java bindings on your Mac, then compile with `--java` on Linux virtual machine, and then transfer the JAR from the virtual machine to your computer.

**Comment by PaulMeng** [comment]
@cheshire Yes, it is a fresh check out. 
I'll try an earlier version and see if it works or not. 
Thanks for suggesting the workaround.

**Comment by cheshire** [comment]
@PaulMeng I still suspect issues with your checkout.
The error message indicates that the enum is missing items `Z3_SEQ_SORT` and `Z3_RE_SORT`.
Can you look at the file `../src/api/java/enumerations/Z3_sort_kind.java` and confirm that they are indeed there?
If they are there, and the error message persists, I think you have a stale `.class` file somewhere.
Just to be completely sure, can you go to e.g. /tmp/ dir, make another fresh checkout, and try to build that?

**Comment by PaulMeng** [comment]
@cheshire Yes, Z3_SEQ_SORT and Z3_RE_SORT are in Z3_sort_kind.java.
I just downloaded the latest z3 and still failed to compile with the same error.

**Comment by cheshire** [comment]
@PaulMeng I think you have something strange in your environment.
Is your classpath environment variable empty?

**Comment by PaulMeng** [comment]
@cheshire there might be something strange with my environment since my Mac is brand new and I am not sure if I have everything needed to compile z3.

Yes, the calsspath env variable($CALSSPATH) is empty. Do I need to set it to something?

**Comment by dstaple** [comment]
Yes, I just verified that Z3 compiles fine with Java bindings on my OS X 10.9.5 system with Java 1.8.0_20 and Z3 commit cf48eb5.  The exact instructions I used were:
```
git clone https://github.com/z3prover/z3.git
cd z3
python scripts/mk_make.py --java
cd build
make -j4
```

So I think this is a system-dependent issue.

**Comment by NikolajBjorner** [comment]
I don't think anybody could repro the reported problem. Furthermore, the error message indicates that there is an older version of Z3_sort_kind byte-code floating around that gets picked up by the java compiler. Therefore closing as no repro.
