### ISSUE TITLE
what is the background theory that Z3 uses to prove constraints unsat

### ISSUE THREAD

**Issue by qingyangcx** [Z3Prover/z3#6725]
As I think z3 may use some search algorithms like heuristic search to get a solution, but I can't imagine how z3 decision constraints like x > 2 && x < 2 unsat. Could you recommend some related articles about it? Thanks very much!

**Comment by NikolajBjorner** [comment]
https://microsoft.github.io/z3guide
https://z3prover.github.io/papers/programmingz3.html
https://z3prover.github.io/papers/z3internals.html
