### ISSUE TITLE
MBP from API returns wrong result

### ISSUE THREAD

**Issue by Columpio** [Z3Prover/z3#6726]
I make a call `Z3_qe_model_project(ctx, model, n, consts, formula)` via C API.
Here:
- `ctx` is a properly built context of type `Z3_context`
- `model` is the following model of `formula` obtained from `Z3_solver_get_model` of type `Z3_model`
```smt2
k!1 -> (- 1)
k!7 -> 0
k!0 -> 0
k!5 -> 0
k!4 -> (- 1)
k!6 -> nil
k!3 -> nil
k!2 -> nil
```
- `n = 13` is a size of `consts` array
- `consts` is an array of the following `Z3_ast` elements (made through `Z3_mk_const`): `{k!0, k!1, k!2, k!6, k!7, k!8, k!9, k!10, k!11, k!12, k!13, k!14, k!15}` (all `k` but 3 to 5)
- `formula` is the following formula of type `Z3_ast`
```smt2
(and true
     (= k!3 k!2)
     (= k!4 k!1)
     (= k!5 k!0)
     (= k!6 k!2)
     (= k!7 k!0)
     (< k!1 0)
     true)
```

What I get from the call `Z3_qe_model_project(ctx, model, n, consts, formula)` is the following formula:
```smt2
(and (not (<= 0 k!4)) (= k!3 k!2) (= k!5 k!0) (= k!6 k!2))
```
For some reason `k!0`, `k!2`, `k!6` are still there: from MBP I expect a formula *without* them.
My Z3 version is 06ea765b8229ea784fe6f805379c9e508eb9fed6.

I assume @agurfinkel might help on that one.

**Comment by NikolajBjorner** [comment]
Can you furnish a self-contained repro (Python or using z3.log)? The Z3_open_log facility lets you trace interaction in a text file.

**Comment by Columpio** [comment]
[Log](https://pastebin.com/X76YekGC) with `Z3_open_log`

**Comment by NikolajBjorner** [comment]
you will need to call Z3_open_log _before_ any other call into z3. It has to be before you create a context.
You can validate the log by running z3.exe on it (give it the ".log" file extension).

**Comment by hgvk94** [comment]
@Columpio I cannot reproduce the issue. It might be because I am using the wrong sorts for the constants. I tried with Lists of Int and with Lists of uninterpreted sort. Maybe you have something different?

You can call mbp directly using the `mbp` debug command. I have attached my attempt at reproducing the issue.
[6726-ghub.zip](https://github.com/Z3Prover/z3/files/12074494/6726-ghub.zip)

**Comment by hgvk94** [comment]
@Columpio maybe #6820 fixes the issue?
