### ISSUE TITLE
Z3_solver_from_string can read in the middle of context

### ISSUE THREAD

**Issue by arshiamoeini** [Z3Prover/z3#6727]
# Hi,

I want `Z3_solver_from_string` to work properly by taking into account previous assumptions. For example, it should work correctly in the following Rust code:

```rust
let cfg = Config::new();
let ctx = Context::new(&cfg);
let x = ast::Int::new_const(&ctx, "x");
let y = ast::Int::new_const(&ctx, "y");
let problem = r#"
    (assert (=( (+ x y) 1))
"#;
let solver = Solver::new(&ctx);
solver.from_string(problem);
assert_eq!(solver.check(), SatResult::Unsat);
```

Please add this feature. Currently, we cannot directly use `Z3_parse_smtlib2_string` in z3 crate.

**Comment by NikolajBjorner** [comment]
Sorry. This feature will not be added
