### ISSUE TITLE
[Question] How can I know terms binding with let after parsing in z3py?

### ISSUE THREAD

**Issue by hagozaebii** [Z3Prover/z3#6732]
Hello,

Recently, I parsed seed below with `parse_smt2_file` in z3py.
```
(set-info :smt-lib-version 2.6)
(set-logic QF_BV)
(set-info :source |
 Patrice Godefroid, SAGE (systematic dynamic test generation)
 For more information: http://research.microsoft.com/en-us/um/people/pg/public_psfiles/ndss2008.pdf
|)
(set-info :category "industrial")
(set-info :status sat)
(declare-fun T1_111979 () (_ BitVec 8))
(declare-fun T1_111988 () (_ BitVec 8))
(declare-fun T1_112009 () (_ BitVec 8))
(declare-fun T1_112021 () (_ BitVec 8))
(assert (let ((?v_0 ((_ zero_extend 24) (_ bv1 8))) (?v_6 (bvand (bvand ((_ zero_extend 24) T1_111979) (_ bv255 32)) (_ bv31 32)))) (let ((?v_1 (bvadd ?v_6 ?v_0))) (let ((?v_5 (bvadd ?v_1 (_ bv282 32))) (?v_4 (bvand (bvor (bvshl (bvand ((_ zero_extend 24) T1_111988) (_ bv255 32)) ((_ zero_extend 24) (_ bv4 8))) (_ bv10 32)) (_ bv127 32))) (?v_3 (bvand (bvshl (bvand ((_ zero_extend 24) T1_112009) (_ bv255 32)) ((_ zero_extend 24) (_ bv2 8))) (_ bv7 32))) (?v_2 (bvand (bvshl (bvand ((_ zero_extend 24) T1_112021) (_ bv255 32)) ?v_0) (_ bv127 32)))) (and true (bvsle ?v_1 (_ bv23 32)) (not (= ?v_4 (_ bv4294967295 32))) (not (= ?v_3 (_ bv4294967295 32))) (not (= ?v_2 (_ bv4294967295 32))) (bvsle ?v_5 (bvadd (bvadd (bvadd ?v_2 (_ bv11 32)) (bvadd (bvadd (bvadd ?v_3 (_ bv3 32)) (bvadd ?v_4 (_ bv78 32))) (_ bv32 32))) (_ bv50 32))) (bvslt (_ bv0 32) ?v_5) (not (= ?v_6 (_ bv4294967295 32))) (bvslt (_ bv0 32) ?v_1) (bvsle ?v_1 (_ bv30 32)))))))
(check-sat)
(exit)
```
The result of applying `parse_smt2_file` removed `let` binding. However, I wanna know what terms were bound by let. I guess there is a function or arg to know what is in `let` but, I cannot find it in z3py source code. Would you let me know how to know the information that is what `let` consists of after parsing in z3py?

Thank you.

**Comment by NikolajBjorner** [comment]
within z3, there are no "let" term constructors. Let expressions are expanded. The reason why this works is that terms within z3 use shared pointers. So you can write let x = y + y let z = x + x in let u = z + z in u and the term named u has only 5 subterms.
If you write u out directly you have: 
u := ((y + y) + (y + y)) + ((y + y) + (y + y))
But the subterm y + y will be represented by a pointer. The pointer is reused everywhere. 
Similarly, the sub-term x + x is also a pointer. The pointer is reused twice, and within the pointer for x + x, the pointer into y + y is used twice.

**Comment by hagozaebii** [comment]
@NikolajBjorner That's why z3 does not show information about `let`. I understand it. Thanks for your explanation.
