### ISSUE TITLE
Patterns: segfault in Z3 using OCaml binding, wrong SMT2 using Python binding

### ISSUE THREAD

**Issue by bensmrs** [Z3Prover/z3#6737]
Hi,
While playing with (I think illegal) Z3 patterns, I found several strange bugs.

### Environment
Z3 4.11.2 installed via OPAM on a Mac.

### Steps to reproduce (OCaml)
Compile and execute the following code
```ocaml
let ctx = Z3.mk_context [] in
let solver = Z3.Solver.mk_solver ctx None in
let boolsort = Z3.Boolean.mk_sort ctx in
let a = Z3.Expr.mk_const_s ctx "a" boolsort in
let b = Z3.Expr.mk_const_s ctx "b" boolsort in
let exists = Z3.Quantifier.mk_exists_const ctx [b] (Z3.Boolean.mk_eq ctx a b) None [] [] None None in
let forall = Z3.Quantifier.(mk_forall_const ctx [a] (expr_of_quantifier exists) None [mk_pattern ctx [a]] [] None None) in
Z3.Solver.add solver [Z3.Quantifier.expr_of_quantifier forall];
Z3.Solver.check solver [] (* SEGFAULT *)
```

### Additional informations
Before triggering the `check-sat`, the solver has the following assertion: `(assert (forall ((a Bool)) (! (exists ((b Bool)) (= a b)) :pattern (pattern a))))`, which seems rather strange, as the function `pattern` does not exist, as confirmed by running Z3 directly on the command line.

Using Z3Py works:
```python
from z3 import *
B = BoolSort()
(a, b) = Bools('a b')
s = Solver()
s.add(ForAll(a, Exists(b, a == b), patterns=[a]))
s.check() # SAT
```
but generates the following assertion: `(assert (forall ((a Bool)) (! (exists ((b Bool)) (= a b)) :pattern (a))))`, which also seems strange because it’s invalid (Z3 triggers an exception when executed directly).

**Comment by NikolajBjorner** [comment]
I am adding some sanity checking to the API so that your OCaml code gets rejected.
Both versions are not valid patterns. A pattern cannot have a bound variable at top-level.

**Comment by bensmrs** [comment]
Great, thanks for the reply!
