### ISSUE TITLE
Solver().check() seems like deadlocked

### ISSUE THREAD

**Issue by EmpRamses** [Z3Prover/z3#6738]
I'm trying to use z3 to analyze binary code, taking a z3 solver to judge whether the software can run along a series of conditional branch instructions. The solver always block the analysis process once a slightly complicated BoolRef expression assigned as a constraint to the solver when we execute the check() method. However, if I construct the same solver with the same constraint independently in another python interpreter, we can get the check() result immediately.
An example constraint shown as follow: 
'(let ((a!1 (concat #b00000\n                   ((_ extract 63 37)\n                     (bvmul #x00000000504f885f (concat #x00000000 x))))))\n(let ((a!2 (bvadd x\n                  (bvmul #xffffff81 a!1)\n                  (bvmul #x00000064\n                         (concat #b0000000000000000000000000000000\n                                 ((_ extract 31 31) x))))))\n  (bvslt a!2 #x00000000)))'

**Comment by NikolajBjorner** [comment]
Try to run with verbose set to 10 and you will see whether it is really "deadlocked" or just busy searching. 64 bit bit-vector multiplication can be expensive.

**Comment by EmpRamses** [comment]
In my experiments, both solvers working in analyzer and tested alone contain the same one constraint shown before. While we can get the check() result from the solver tested alone in a moment, the solver in the analyzer run the check() method for hours or even more than a day without any result because I interrupted it with keyboard. I think my experiments can prove that the process is not simply busy searching.
You can reimplement the stand alone test with following codes
```
from z3 import *
slv = Solver()
x, y, z = BitVecs("x y z", 32)
f = x + BitVecVal(4294967169, 32) * Concat(BitVecVal(0, 5), Extract(64, 37, BitVecVal(1347389535, 64) * Concat(BitVecVal(0, 32), x))) + BitVecVal(100, 32) * Concat(BitVecVal(0, 31), Extract(31, 31, x))
f = simplify(f)
g = f < 0
slv.add(g)
slv.check()
```
Since my analyzer is designed based on z3, an important difference between two environments inside and outside the analyzer is the amount of bit-vectors without relation with the solver. Could these bit-vectors stored in RAM cause the busy searching for solvers? 
I have set a 1 sec timeout for the solver and a constraint exclusion strategy for the analyzer. And now it works well. But this could introduce false positive instruction series for the analyzer. So I still hope that this problem could be solved.

**Comment by NikolajBjorner** [comment]
extract at bit position 64 is illegal for 64 bit bit-vectors. Your python code throws an exception.

**Comment by EmpRamses** [comment]
> extract at bit position 64 is illegal for 64 bit bit-vectors. Your python code throws an exception.

Sorry, that's my fault on code copying. You can try the code following:

```
from z3 import *
slv = Solver()
x = BitVec("x", 32)
f = x + BitVecVal(4294967169, 32) * Concat(BitVecVal(0, 5), Extract(63, 37, BitVecVal(1347389535, 64) * Concat(BitVecVal(0, 32), x))) + BitVecVal(100, 32) * Concat(BitVecVal(0, 31), Extract(31, 31, x))
f = simplify(f)
g = f < 0
slv.add(g)
slv.check()
```

**Comment by NikolajBjorner** [comment]
the example is solved very quickly.

**Comment by NikolajBjorner** [comment]
This is the faster solver

```
from z3 import *
for i in range(10):
    set_option("sat.random_seed",i)
    slv = SimpleSolver()
    x = BitVec("x", 32)
    f = x + BitVecVal(4294967169, 32) * Concat(BitVecVal(0, 5), Extract(63, 37, BitVecVal(1347389535, 64) * Concat(BitVecVal(0, 32), x))) + BitVecVal(100, 32) * Concat(BitVecVal(0, 31), Extract(31, 31, x))
    f = simplify(f)
    g = f < 0
    slv.add(g)
    print(slv.check())
    print(slv.statistics())
```

Using slv = Solver(), then it is a bit slower.

**Comment by EmpRamses** [comment]
@NikolajBjorner Thanks for your help. I found that my analyzer could introduce much more complicated constraint like the following one. It seems that I have to facilitate some compromise strategy on the constraint check().

`'(let ((a!1 (bvadd ((_ extract 1 1)\n                    (bvadd reg_03834\n                           (concat #x00000000000000 CF_03830)\n                           reg_03835))\n                  ((_ extract 0 0) reg_03835)\n                  ((_ extract 0 0) CF_02530)))\n      (a!2 (bvadd (concat (bvadd ((_ extract 0 0) reg_03834)\n                                 ((_ extract 0 0) CF_03830)\n                                 ((_ extract 0 0) reg_03835))\n                          ((_ extract 63 1) (bvadd reg_03832 reg_03833)))\n                  (bvmul #xffffffffffffffff reg_03833))))\n(let ((a!3 (bvadd #xffffffffffffffff\n                  (bvmul #x0000000000000008\n                         reg_03833\n                         (concat #x00000000000000 phi_03912))\n                  (bvmul #xffffffffffffffe4\n                         reg_03833\n                         (concat #x00000000000000 phi_03912)\n                         (concat #x00000000000000 phi_03912)\n                         (concat a!1 ((_ extract 63 1) a!2)))\n                  (bvmul #x0000000000000038\n                         reg_03833\n                         (concat #x00000000000000 phi_03912)\n                         (concat #x00000000000000 phi_03912)\n                         (concat #x00000000000000 phi_03912)\n                         (concat a!1 ((_ extract 63 1) a!2))\n                         (concat a!1 ((_ extract 63 1) a!2)))\n                  (bvmul #xffffffffffffffba\n                         reg_03833\n                         (concat #x00000000000000 phi_03912)\n                         (concat #x00000000000000 phi_03912)\n                         (concat #x00000000000000 phi_03912)\n                         (concat #x00000000000000 phi_03912)\n                         (concat a!1 ((_ extract 63 1) a!2))\n                         (concat a!1 ((_ extract 63 1) a!2))\n                         (concat a!1 ((_ extract 63 1) a!2)))\n                  (bvmul #x0000000000000038\n                         reg_03833\n                         (concat #x00000000000000 phi_03912)\n                         (concat #x00000000000000 phi_03912)\n                         (concat #x00000000000000 phi_03912)\n                         (concat #x00000000000000 phi_03912)\n                         (concat #x00000000000000 phi_03912)\n                         (concat a!1 ((_ extract 63 1) a!2))\n                         (concat a!1 ((_ extract 63 1) a!2))\n                         (concat a!1 ((_ extract 63 1) a!2))\n                         (concat a!1 ((_ extract 63 1) a!2)))\n                  (bvmul #xffffffffffffffe4\n                         reg_03833\n                         (concat #x00000000000000 phi_03912)\n                         (concat #x00000000000000 phi_03912)\n                         (concat #x00000000000000 phi_03912)\n                         (concat #x00000000000000 phi_03912)\n                         (concat #x00000000000000 phi_03912)\n                         (concat #x00000000000000 phi_03912)\n                         (concat a!1 ((_ extract 63 1) a!2))\n                         (concat a!1 ((_ extract 63 1) a!2))\n                         (concat a!1 ((_ extract 63 1) a!2))\n                         (concat a!1 ((_ extract 63 1) a!2))\n                         (concat a!1 ((_ extract 63 1) a!2)))\n                  (bvmul #x0000000000000008\n                         reg_03833\n                         (concat #x00000000000000 phi_03912)\n                         (concat #x00000000000000 phi_03912)\n                         (concat #x00000000000000 phi_03912)\n                         (concat #x00000000000000 phi_03912)\n                         (concat #x00000000000000 phi_03912)\n                         (concat #x00000000000000 phi_03912)\n                         (concat #x00000000000000 phi_03912)\n                         (concat a!1 ((_ extract 63 1) a!2))\n                         (concat a!1 ((_ extract 63 1) a!2))\n                         (concat a!1 ((_ extract 63 1) a!2))\n                         (concat a!1 ((_ extract 63 1) a!2))\n                         (concat a!1 ((_ extract 63 1) a!2))\n                         (concat a!1 ((_ extract 63 1) a!2)))\n                  (bvmul #xffffffffffffffff\n                         reg_03833\n                         (concat #x00000000000000 phi_03912)\n                         (concat #x00000000000000 phi_03912)\n                         (concat #x00000000000000 phi_03912)\n                         (concat #x00000000000000 phi_03912)\n                         (concat #x00000000000000 phi_03912)\n                         (concat #x00000000000000 phi_03912)\n                         (concat #x00000000000000 phi_03912)\n                         (concat #x00000000000000 phi_03912)\n                         (concat a!1 ((_ extract 63 1) a!2))\n                         (concat a!1 ((_ extract 63 1) a!2))\n                         (concat a!1 ((_ extract 63 1) a!2))\n                         (concat a!1 ((_ extract 63 1) a!2))\n                         (concat a!1 ((_ extract 63 1) a!2))\n                         (concat a!1 ((_ extract 63 1) a!2))\n                         (concat a!1 ((_ extract 63 1) a!2))))))\n  (bvsle a!3 #x0000000000000000)))'`
