### ISSUE TITLE
Unexpected behaviour of PartialOrder (and similar functions)

### ISSUE THREAD

**Issue by wijnanduu** [Z3Prover/z3#6743]
### Discussed in https://github.com/Z3Prover/z3/discussions/6724

I am running into some unexpected behaviour and errors related to the `PartialOrder` and its siblings `LinearOrder` etc. 

When I run the code 
``` 
from z3 import *
s = Solver()
R = PartialOrder(IntSort(), 0)
S = PartialOrder(IntSort(), 1)
s.add(R(1, 2))
s.add(Not(S(1, 2)))
s.check()
m = s.model()
print(m[R])
print(m[S])
```
both print statements give the same output; namely
```
[else ->
 Or(connected(cons(Var(0), nil), Var(1), cons(Var(0), nil)),
    Var(0) == Var(1))]
```
I don't understand why S and R receive the same interpretation when they disagree on the pair (1, 2)? 

I'm asking this in the context of an error that I'm getting. As part of a bigger piece of code I'm using Z3 to define multiple instances of these partial orders on enum sorts. What happens is roughly as follows. 

1. I start with a solver `s` containing constraints for a series of `PartialOrder`'s, each defined on an `EnumSort`.
2. I calculate a model for `s` using `s.check()`, and then inspect `s.model()`. The interpretations look like the code I list above with `else`, `or`, `connected`, etc. 
3. Then I make a checkpoint with `s.push()`, add some other formulas and compute a model, after which I go back to the checkpoint with `s.pop()`. 
4. Directly after the pop I calculate a model again for the set of point 1. This works but the resulting model seems to have more complex interpretations for the orders than the first time I asked for a model. 
5. Doing this repeatedly, I eventually get a `sat` result for `s.check()` but Z3 will crash when I run `s.model()` with an error about incompatible sorts (two of the enum sorts on which I define the PartialOrders). 

I would like to post a MWE for this behaviour but it would take me a while to extract from my code. I'm wondering if it has something to do with my question related to the `R` and `S` above; if not, I will try to post a MWE for the crash. 

As an aside; I'm wondering why these functions take an integer index to distinguish between them instead of the usual string identifier? In other words, why do we write `R = PartialOrder(IntSort(), 0)` instead of `R = PartialOrder('R', IntSort())`?

**Comment by NikolajBjorner** [comment]
this was fixed
