### ISSUE TITLE
Unable to print Expressions

### ISSUE THREAD

**Issue by pattersonz** [Z3Prover/z3#6744]
Using Z3 with Java, I have been unable to print out any of my BoolExpr.

All attempts end with the same message:
```
ASSERTION VIOLATION
File: /home/pattersonz/z3/src/api/api_ast.cpp
Line: 1005
UNEXPECTED CODE WAS REACHED.
4.12.2.0
Please file an issue with this message and more detail about how you encountered it at https://github.com/Z3Prover/z3/issues/ne
```
I've tried things like:
```
BoolExpr t = context.mkTrue();
System.out.println( t.toString() );
```
and making symbols or other expressions like ands and nots, and none of them will print.
However if I add the expression as a constraint to a solver, I can print out the solver perfectly fine and it has the expression displayed correctly.
If I get the expression from solver.getAssertions() and try and print that, I get the same error I had before.

Can someone tell me if this is a bug, or intended? And if so how I can get around it.

**Comment by NikolajBjorner** [comment]
These kinds of bugs happen typically when users have two versions of z3 on their systems. 
The unit test in examples/java should also crash for you.

**Comment by pattersonz** [comment]
Thanks for your help. I uninstalled all versions of Z3, reinstalled 4.12 and updated my classpath, and that fixed it.
