### ISSUE TITLE
Questions related to high-order functions

### ISSUE THREAD

**Issue by duytai** [Z3Prover/z3#6745]
I am using the z3-py library in my project and I want to find the formula that satisfies a high-order function. 
For example,

```python
from z3 import *
x, y, z = Ints('x, y, z')
add = Function('add', IntSort(), IntSort(), IntSort())
s = Solver()
s.add(
  ForAll(
    [x, y, z],
    Implies(z == x + y, z == add(x, y))
  )
)
s.check()
s.model() # [add = [else → ν1 + ν0]]
```
The code above gives me the formula of high-oder function `add`, which is `add(v0, v1) == v0 + v1`
However, if I change `x` and `y` to elements of an array then the solver will hang.

```python
from z3 import *
x, y, z = Ints('x, y, z')
balances = Const('balances', ArraySort(IntSort(), IntSort()))
add = Function('add', IntSort(), IntSort(), IntSort())
s = Solver()
s.add(
  ForAll(
    [x, y, z, balances],
    Implies(
      z == balances[x] + balances[y],
      z == add(balances[x], balances[y])
     )
  )
)
s.check() # hang
```
Can you provide any suggestions on how to obtain the formula of `add` in this scenario ?

Thanks in advance !

**Comment by NikolajBjorner** [comment]
the quantifier engine is not tuned for quantifiers over arrays. It will not find models like the ones you have in the simple case.
