### ISSUE TITLE
"scripts/mk_make.py" works very slow in wsl2

### ISSUE THREAD

**Issue by Michael-LiangAnze** [Z3Prover/z3#6752]
I encounted the same problem as #6042 . I run "python3 scripts/mk_make.py" in wsl2 and it stayed at "Writing build/Makefile" for more than 4 hours after which I had to stop it.  When its running my cpu usage had been consistently 0%. 

My environment is as follows:
- Windows10 22H2
- Ubuntu 22.04.2 LTS(WSL2)
- Python 3.10.6

Is there any way to solve is? Its really important for me to work it out as early as possible.

**Comment by NikolajBjorner** [comment]
wsl2 behavior is external to z3. I can't debug what appears to be a deadlock in the file system interaction. 
You can debug it on your own by hitting CTL-C and find the stack where it is stuck. Then add diagnostic prints as appropriate.
In the end wsl2 behavior is out of scope of z3.

**Comment by Michael-LiangAnze** [comment]
> wsl2 behavior is external to z3. I can't debug what appears to be a deadlock in the file system interaction. You can debug it on your own by hitting CTL-C and find the stack where it is stuck. Then add diagnostic prints as appropriate. In the end wsl2 behavior is out of scope of z3.

Thank you.
