### ISSUE TITLE
lp_primal_core_solver<T, X>::sort_non_basis() violates strict weak ordering

### ISSUE THREAD

**Issue by baylesj** [Z3Prover/z3#6753]
One of rules of using std::sort is that the comparator absolutely must follow strict weak ordering, otherwise unexpected errors may occur in production and be very difficult to debug. The comparator used for sort_non_basis() violates strict weak ordering, verified using the techniques outlined in: https://github.com/danlark1/quadratic_strict_weak_ordering.

For more information on strict weak ordering, see:
https://www.boost.org/sgi/stl/StrictWeakOrdering.html

**Comment by baylesj** [comment]
I fully intend on fixing this issue myself, and wanted to get an issue for it as soon as possible. Currently investigating the most tightly scoped fix.

**Comment by NikolajBjorner** [comment]
@levnach

**Comment by NikolajBjorner** [comment]
I guess the intent is that all 0-s be sorted after the non-0s.
The numbers are unsigned, so it is similar to subtracting 1 from all numbers and comparing. (?)

**Comment by levnach** [comment]
Yes, this is the intent. I think subtracting 1 is going to work. 
The code below should also work. Not sure what is better.
`if (ca == 0 && cb != 0) return false; 
if (cb == 0 && ca != 0) return true; 
    return ca < cb;`

**Comment by levnach** [comment]
Fixed, hopefully, by https://github.com/Z3Prover/z3/commit/f7ec5c5c646da2d660afcdc7e2d4c1dca8747766.
