### ISSUE TITLE
Segmentation fault in python3

### ISSUE THREAD

**Issue by DanielWaterworth** [Z3Prover/z3#676]
test.py:

```python
import z3

Data = z3.DeclareSort('Data')

Operation = z3.Datatype('Operation')
Operation.declare('set', ('key1', Data), ('value', Data))
Operation.declare('delete', ('key2', Data))
Operation.declare('get', ('key3', Data))
Operation = Operation.create()

# This is necessary for some reason
class Foo:
    def __init__(self):
        pass
```

GDB backtrace:

    #0  0x00007ffff78261c7 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:55
    #1  0x00007ffff7827e2a in __GI_abort () at abort.c:89
    #2  0x00007ffff7869ba3 in __libc_message (do_abort=do_abort@entry=1, fmt=fmt@entry=0x7ffff79820f8 "*** Error in `%s': %s: 0x%s ***\n") at ../sysdeps/posix/libc_fatal.c:175
    #3  0x00007ffff78703b8 in malloc_printerr (ptr=<optimised out>, str=0x7ffff797e285 "corrupted double-linked list", action=1) at malloc.c:4965
    #4  malloc_consolidate (av=av@entry=0x7ffff7bb5c00 <main_arena>) at malloc.c:4150
    #5  0x00007ffff7871e68 in _int_free (av=0x7ffff7bb5c00 <main_arena>, p=<optimised out>, have_lock=0) at malloc.c:4042
    #6  0x00007ffff78757ec in __GI___libc_free (mem=<optimised out>) at malloc.c:2950
    #7  0x000000000056e4b9 in dict_tp_clear.lto_priv.287 (op=<optimised out>) at ../Objects/dictobject.c:2495
    #8  0x00000000005204fe in delete_garbage (old=<optimised out>, collectable=<optimised out>) at ../Modules/gcmodule.c:866
    #9  collect.lto_priv () at ../Modules/gcmodule.c:1032
    #10 0x00000000005f3597 in _PyGC_CollectNoFail () at ../Modules/gcmodule.c:1638
    #11 0x0000000000500340 in PyImport_Cleanup () at ../Python/import.c:487
    #12 0x00000000005f8836 in Py_Finalize () at ../Python/pythonrun.c:616
    #13 0x0000000000619043 in Py_Main () at ../Modules/main.c:771
    #14 0x00000000004c27df in main () at ../Modules/python.c:69
    #15 0x00007ffff7811ac0 in __libc_start_main (main=0x4c2700 <main>, argc=2, argv=0x7fffffffdd48, init=<optimised out>, fini=<optimised out>, rtld_fini=<optimised out>, stack_end=0x7fffffffdd38) at libc-start.c:289
    #16 0x00000000005bdf09 in _start ()

Installed versions:

    $ z3 --version
    Z3 version 4.4.2
    # The sha of the checkout was 0d0d504d62735616bf38c8b2671ea91d68fb5fd2

    $ python3 --version
    Python 3.4.3+
    # The plus is because I installed a version with debugging symbols.

**Comment by wintersteiger** [comment]
Confirmed reproducible on OSX, Ubuntu, Windows, but intermittent. I can only make it fail repeatedly on Ubuntu, on the other systems it happens only very rarely. Haven't managed to make it fail with Python 2, seems to be 3.x only (I've seen 3.5.1 fail as well). @nbjorner: possibly another problem of the recent changes to context cleanup? On my VM it complains about leaks with very large (or negative) AST ids, e.g.: Leaked: id: 2147483795.

**Comment by NikolajBjorner** [comment]
Function declarations have IDs that look like negative / large numerals.
The tactic "bv" should really fail when the benchmark has function symbols.

**Comment by NikolajBjorner** [comment]
Got it, the ast nodes in parameters were not included when collecting GC roots.
There is apparently a race condition where the context gets shut down but affiliated data isn't.
