### ISSUE TITLE
Error in evaluating bitvector expressions

### ISSUE THREAD

**Issue by luo8979061** [Z3Prover/z3#6796]
When I calculate using the following code:

import z3
a = z3.BitVec("a",8)
opt = z3.Optimize()
min_value = opt.minimize(a)
max_value = opt.maximize(a)
opt.set('priority', 'box')
opt.check()
min = min_value.value().as_long()
max = max_value.value().as_long()
print(min,max)

I can get the following result：
0 255

But when I add a condition, the code looks like this：

import z3
a = z3.BitVec("a",8)
opt = z3.Optimize()
conditions = [a>=0,a<=0xff]
for condition in conditions:
    opt.add(condition)
min_value = opt.minimize(a)
max_value = opt.maximize(a)
opt.set('priority', 'box')
opt.check()
min = min_value.value().as_long()
max = max_value.value().as_long()
print(min,max)

I can get the following result：
0 0
It seems like an unexpected result, why not 0, 255

**Comment by NikolajBjorner** [comment]
Note that in python, the <= overload on bit-vectors has signed semantics.

**Comment by NikolajBjorner** [comment]
The constraints are therefore unsat because you assert that a is both >= 0 and <= -1.

```
print(opt.check())
```
prints
```
unsat
```
