### ISSUE TITLE
Decidable fragment of trigonometry

### ISSUE THREAD

**Issue by dstaple** [Z3Prover/z3#680]
I am interested in adding a decidable fragment of trigonometry to Z3.

In the situation where real variables theta only appears as an argument of the sine and cosine operators, i.e. sin(theta) and cos(theta), these variables can be eliminated by moving to Cartesian coordinates, defining two new real variables x and y such that y = sin(theta), x = cos(theta).  Subject to the constraint x^2 + y^2 = 1, x and y can be treated as ordinary real variables.

I realize this is somewhat trivial, but the advantage is that with x and y as real variables, and x^2 + y^2 = 1, any trigonometry problem involving arbitrarily complex sums and products of sin(theta) and cos(theta) can be mapped onto a problem in QF_NRA, which is decidable and can be solved using nlsat.  This transformation can be applied as long as sin, cos, and theta only appear in the combinations sin(theta) and cos(theta), and never with theta on its own or sin or cos applied to something more complicated.  A surprisingly large family of trig problems can be solved using nlsat with the above trick.  If other simplifications and trig identities (some of which are implemented in the Z3 arith_rewriter class), the class of decidable trig problems grows even more.

I would be very interested in adding this to Z3, but unfortunately it's still outside of my skill level with regards to the Z3 implementation.  Would any of you be interested / willing to advise me on the implementation of the above idea?  My high-level impression for how this should work is that there should be a tactic with a model converter for eliminating AST of the form sin(theta) or cos(theta) using new variables y and x, together with the assertion x^2 + y^2 = 1.  It would be really helpful to know if I'm on the right track, and any other implementation details or advice would be much appreciated.

**Comment by NikolajBjorner** [comment]
Cool, yes, this would be a tactic. The approach is to probe 
for trigonometric variables, and perform the transformation on goals. Model converters take values for x, y and produce values for theta (in the range 0-pi).

Can you add some test cases to this thread? It will then be easier to get off the ground.

With the fragment you hint at there would be no way to distinguish sin from cos. They would be symmetric. This seems like a somewhat very special case, so one question is whether it is more appropriate to encode problems using x, y in the first place. Would a more general fragment include bounds on theta?

**Comment by dstaple** [comment]
OK, fantastic.  For starts, here is the simplest trig problem I can think of that would be solved with such a tactic, which Z3 cannot already solve:
```
(declare-fun theta () Real)
(assert (= (sin theta) (cos theta)))
(check-sat-using qfnra-nlsat)
(get-model)
```
This would be converted to the equivalent of
```
(declare-fun x () Real)
(declare-fun y () Real)
(assert (= x y))
(assert (= (+ (* x x) (* y y)) 1))
(check-sat-using qfnra-nlsat)
(get-model)
```
which returns
```
sat
(model 
  (define-fun y () Real
    (root-obj (+ (* 2 (^ x 2)) (- 1)) 1))
  (define-fun x () Real
    (root-obj (+ (* 2 (^ x 2)) (- 1)) 1))
)
```

Regarding the symmetric nature of x and y in the fragment, besides the fact that `sin(0) = 0`, the other thing this fragment will never get is the 2*pi periodicity.  However, I think the symmetry breaking is only an issue when actual values are to be returned.  I think this can be worked around by returning models where `x` and `y` are left as `(cos theta)` and `(sin theta)`.  This allows us to benefit from the completeness of nlsat while maintaining the rigor of Z3 by avoiding numerical approximations of sin and cos that might come up otherwise.  I'm not completely sure how this would look when viewed with `(get-model)`.  I expect either statements that `(= (sin theta) (root-obj (+ (^ x 2) (- 2)) 1))` and `(= (cos theta) (root-obj (+ (^ x 2) (- 2)) 1))`, or perhaps a model containing temporary variables with appropriate definitions.

It would indeed be possible to encode the problem using `x` and `y` to begin with, but I think the number of trig problems that can be pushed into this category is larger than one might initially expect, if other rewriting rules and trig identities are used.  In the end, Mathematica and Maple are able to solve many trig problems that Z3 cannot solve.  I would love to close that gap, and I think this is a good first step.  In particular, statements about 3D vectors in spherical coordinates can be solved using this tactic alone.

I will build up a number of test cases of increasing difficulty and post them here.  If and when the tactic gets off the ground, we can clean them up and add them to the z3test repo.

**Comment by dstaple** [comment]
Here's the next example:
```
(declare-fun x () Real)
(declare-fun y () Real)
(declare-fun z () Real)
(declare-fun r () Real)
(declare-fun theta () Real)
(declare-fun phi () Real)
(assert (= x (* r (* (sin theta) (cos phi)))))
(assert (= y (* r (* (sin theta) (sin phi)))))
(assert (= z (* r (cos theta))))
(assert (distinct (* r r) (+ (* x x) (+ (* y y) (* z z)))))
(check-sat-using qfnra-nlsat)
```
This should be converted to something equivalent to:
```
(declare-fun x () Real)
(declare-fun y () Real)
(declare-fun z () Real)
(declare-fun r () Real)
(declare-fun cos_theta () Real)
(declare-fun sin_theta () Real)
(declare-fun cos_phi () Real)
(declare-fun sin_phi () Real)
(assert (= 1 (+ (* sin_theta sin_theta) (* cos_theta cos_theta))))
(assert (= 1 (+ (* sin_phi sin_phi) (* cos_phi cos_phi))))
(assert (= x (* r (* sin_theta cos_phi))))
(assert (= y (* r (* sin_theta sin_phi))))
(assert (= z (* r cos_theta)))
(assert (distinct (* r r) (+ (* x x) (+ (* y y) (* z z)))))
(check-sat-using qfnra-nlsat)
```

The original problem returns unknown.  The converted problem returns unsat, proving that the transformation to spherical coordinates preserves the magnitude of the vector.

Should `1` be replaced by `1.0` in these examples for type safety?  I would normally do this in production.

**Comment by NikolajBjorner** [comment]
You can use "1". Z3 inserts coercions by default.

**Comment by NikolajBjorner** [comment]
Can you give it a spin?

**Comment by dstaple** [comment]
Fantastic!  Is seems to be working well.  I pushed up three regression tests to my own branch here: https://github.com/dstaple/z3test/commit/e64de45b10f375aba5bac64aa0ea1440fd87ed4a

The only problem so far is that one of these examples is failing when I run `python ./scripts/smalltest.py` from the testing repo.  The generated error looks like this:
```
Testing regressions/smt2/trig-intersection.smt2
EXPECTED
sat
(model 
  (define-fun theta () Real
    (asin (root-obj (+ (* 2 (^ x 2)) (- 1)) 1)))
)

======================
PRODUCED
sat
(error "line 8 column 28: an invalid model was generated")
(model 
  (define-fun theta () Real
    (asin (root-obj (+ (* 2 (^ x 2)) (- 1)) 1)))
)

======================
Failed
Z3 (/home/dstaple/z3/build/master/debug/z3) produced unexpected output for regressions/smt2/trig-intersection.smt2
```

The strange thing is that when I run Z3 manually on this file, it gives the expected output.  Any idea what's going on here?

**Comment by wintersteiger** [comment]
Looks like the model validation fails (which is enabled in smalltest.py). When you add `model_validate=true` on the command line you should get that same error too.

**Comment by dstaple** [comment]
Yes, I see it now.  The error is thrown in `cmd_context::validate_model()`.  Presumably the model evaluation routines don't exist for `asin`, so this model can't be validated.  Given that there's no way in general to exactly evaluate models involving asin or acos, one way out would be to check for these in `cmd_context::validate_model()`, around line 1650 there are similar exceptions for array expressions.

Another limitation with representing this model using `asin` is that it won't be possible to distinguish between the 1st and 4th quadrants, or the 2nd and 3rd.  For example, these two problems give the same model:
```
(define-fun sqrt2over2 () Real (root-obj (+ (* 2 (^ x 2)) (- 1)) 2))
(declare-fun theta () Real)
(assert (= (sin theta) sqrt2over2))
(assert (= (cos theta) sqrt2over2))
(check-sat-using qfnra-nlsat)
(get-model)

(reset)

(define-fun sqrt2over2 () Real (root-obj (+ (* 2 (^ x 2)) (- 1)) 2))
(declare-fun theta () Real)
(assert (= (sin theta) sqrt2over2))
(assert (= (cos theta) (- sqrt2over2)))
(check-sat-using qfnra-nlsat)
(get-model)
```

**Comment by dstaple** [comment]
A clean way to get the whole unit circle would be to return the angle in terms of the two-argument arc-tangent, atan2, with the first argument being the sine of the angle, and the second being the cosine.  E.g., for `trig-intersection.smt2`, the result would be
```
(model 
  (define-fun theta () Real
    (atan2
      (root-obj (+ (* 2 (^ x 2)) (- 1)) 1)
      (root-obj (+ (* 2 (^ x 2)) (- 1)) 1)
    )
  )
)
```

**Comment by NikolajBjorner** [comment]
model validation is very stringent and requires the assertions to evaluate to true in the model. 
We don't have utilities to compute algebraic numerals over trigonometric functions, so generating models using the non-constant terms seems like the current best option to me. You can disable model validation inside the unit tests by adding a command: (set-option :model-validate false).

**Comment by NikolajBjorner** [comment]
Commit 247e94a  hopefully addresses the bug that  trig-intersection.smt2 points out, modulo the intended starting point for theta.

**Comment by dstaple** [comment]
OK, my mistake, I see now the way you've done it will work mod 2*pi.  I think there still a small mistake in that region, this should give 5 * pi / 4, but gives 7 * pi / 4:
```
(define-fun sqrt2over2 () Real (root-obj (+ (* 2 (^ x 2)) (- 1)) 2))
(declare-fun theta () Real)
(assert (= (cos theta) (- sqrt2over2)))
(assert (= (sin theta) (- sqrt2over2)))
(check-sat-using qfnra-nlsat)
(get-model)
(reset)
```

**Comment by dstaple** [comment]
Here's the full test file:
```
;; Copyright (c) 2016 Microsoft Corporation
(set-info :source |Written by D. B. Staple for GitHub issue #680.|)
(set-info :status sat)

(set-option :pp.decimal true)
(set-option :model_validate false)

; pi / 4
(define-fun sqrt2over2 () Real (root-obj (+ (* 2 (^ x 2)) (- 1)) 2))
(declare-fun theta () Real)
(assert (= (cos theta) sqrt2over2))
(assert (= (sin theta) sqrt2over2))
(check-sat-using qfnra-nlsat)
(get-model)
(reset)

; 3 * pi / 4
(define-fun sqrt2over2 () Real (root-obj (+ (* 2 (^ x 2)) (- 1)) 2))
(declare-fun theta () Real)
(assert (= (cos theta) (- sqrt2over2)))
(assert (= (sin theta) sqrt2over2))
(check-sat-using qfnra-nlsat)
(get-model)
(reset)

; 5 * pi / 4
(define-fun sqrt2over2 () Real (root-obj (+ (* 2 (^ x 2)) (- 1)) 2))
(declare-fun theta () Real)
(assert (= (cos theta) (- sqrt2over2)))
(assert (= (sin theta) (- sqrt2over2)))
(check-sat-using qfnra-nlsat)
(get-model)
(reset)

; 7 * pi / 4
(define-fun sqrt2over2 () Real (root-obj (+ (* 2 (^ x 2)) (- 1)) 2))
(declare-fun theta () Real)
(assert (= (cos theta) sqrt2over2))
(assert (= (sin theta) (- sqrt2over2)))
(check-sat-using qfnra-nlsat)
(get-model)
```
Right now the last two cases are swapped around

**Comment by NikolajBjorner** [comment]
You should be able to turn model validation back on. 
Probably we can add some additional reduction rules for trigonometric operators.

**Comment by dstaple** [comment]
Nice work.  I've pushed the new test (trig-quadrants.smt2) and updated the test output for trig-intersection.smt2.  Now that all four tests are passing, I created a [PR](https://github.com/Z3Prover/z3test/pull/6).  I'll run several more tests and see if I can find any bugs.

**Comment by NikolajBjorner** [comment]
Can we close this as an issue? 
My guess is that there are other trigonometric properties that can be transformed, 
so this is potentially open ended. The experience with the cos/sin transformation was that
(1) we could mostly use a tactic called purify_arith to perform formula transformations
(2) augment simplification of trigonometric functions by encoding identities (in this case sin(acos(x)) = (1 - x^2)^(1/2)). 
I didn't consider other possible trigonometric identities, e.g., cos(asin(x)) = ... yet, as I could risk introducing bugs and it may be best to take a systematic sweep if it turns out to be useful.

**Comment by dstaple** [comment]
Yes, we can close this as an issue.  You implemented the specific suggestion and the more general problem of improved trig handling is definitely open-ended.  I'll take a look at your commits and see if I can build off them systematically and with full test coverage.  Thank you for your help.
