### ISSUE TITLE
Z3 does not respect timeout

### ISSUE THREAD

**Issue by msooseth** [Z3Prover/z3#6801]
The SMT2 query [b.smt2.gz](https://github.com/Z3Prover/z3/files/11982073/b.smt2.gz)  has a timeout set of 1000ms via:

```
(set-option :timeout 1000)
```

but z3 does not quit after 1000ms. Instead, it runs for 25 seconds, violating the timeout. It violates any timeout given in this way. It does respect the `-T:1` command line option, but violates `-t:1`.  I am using Z3 version:

```
[nix-shell:~/development/hevm]$ z3 --version
Z3 version 4.8.15 - 64 bit
```

After what likely is a long preprocessing run, it exits with unknown:

```
[nix-shell:~/development/hevm]$ z3 -t:1 b.smt2 
unknown
```

The SMT2 has only one `(check-sat)` at the end, and no intermediate push/pop/etc. So it's a quite straightforward query. Hence, it may be easy to debug.

Unfortunately, the newest Z3 cannot not reproduce this bug, because it solves this instance in under 1 second. However, if the timeout was not fixed since, the bug is likely still present.

I hope this bugreport helps find the underlying bug which may still be present in Z3,

Mate

**Comment by msooseth** [comment]
Yeah, that's understandable not to support older versions. We'll see if we can reproduce something similar on a newer Z3. Have a nice weekend,

Mate

**Comment by NikolajBjorner** [comment]
or you uploaded the wrong file. I guess life is tough in Sardinia.

**Comment by msooseth** [comment]
Hahah, wish I was in Sardinia! Well, at the model counting competition we won some awards, so I was mentally there a bit, but we'll do better next year! :D

**Comment by msooseth** [comment]
Hi,

I have now a file that reproduces the bug with the newest Z3. File here: [bug-timeout.smt2.gz](https://github.com/Z3Prover/z3/files/12028429/bug-timeout.smt2.gz)

```
$ /usr/bin/time --verbose z3 but-timeout.smt2
unknown
        Command being timed: "z3 stuff.smt2"
        User time (seconds): 4.67
        System time (seconds): 0.30
        Percent of CPU this job got: 99%
        Elapsed (wall clock) time (h:mm:ss or m:ss): 0:04.99
        Average shared text size (kbytes): 0
        Average unshared data size (kbytes): 0
        Average stack size (kbytes): 0
        Average total size (kbytes): 0
        Maximum resident set size (kbytes): 847552
        Average resident set size (kbytes): 0
        Major (requiring I/O) page faults: 0
        Minor (reclaiming a frame) page faults: 44768
        Voluntary context switches: 4
        Involuntary context switches: 12
        Swaps: 0
        File system inputs: 0
        File system outputs: 0
        Socket messages sent: 0
        Socket messages received: 0
        Signals delivered: 0
        Page size (bytes): 4096
        Exit status: 0
```

Version:
```
$ z3 --version
Z3 version 4.12.2 - 64 bit
```


As above, the bug is reproducible with `-t:1` but not with `-T:1`. Hence, it's likely the same bug but now we hit it with the newest solver :) Yay! I hope this helps fixing it!

**Comment by NikolajBjorner** [comment]
Note the following:

z3 --help

```
Resources:
  -T:timeout  set the timeout (in seconds).
  -t:timeout  set the soft timeout (in milli seconds). It only kills the current query.
```

So -t:1 is for one millisecond. -T:1 is for one second.
-T:1 kills the process, -t:1 cancels whatever is currently running.
Cancelation is supposed to allow resuming the solver so it has to be very careful where it can safely cancel search not to mess up resuming the state. Specifically, it wasn't safe to cancel initial compilation of formulas into internal search format and during unit propagation. This means the timeout can only be tested at "safe" intervals. For your formula bit-blasting appears to take time and specifically for internalizing signed remainder. The internalize function for bvsrem could likely be improved in itself (just in case if you feel understimulated in your day job...).

**Comment by msooseth** [comment]
Wow, thanks for the detailed analysis. I was expecting something similar. CryptoMiniSat has similar issues sometimes for inprocessing -- we can't just abandon, we have to finish up/clean up. I might actually look at that thing you mentioned. Maybe not a bad first issue to work on :)

Thank you Nikolaj!

Mate
