### ISSUE TITLE
Inconsistent expression in Java API when using mkFreshConst

### ISSUE THREAD

**Issue by enifeder** [Z3Prover/z3#6805]
generating new expressions using mkFreshConst and mkConst in Java API would end up with two expressions with the same name and sort but inconsistent.
e.g.
```
    public static void main(String[] args) {
        Context context = new Context();
        IntExpr a = (IntExpr) context.mkFreshConst("a", context.mkIntSort());
        IntExpr b = context.mkIntConst(a.toString());
        IntExpr c = context.mkIntConst("c");
        IntExpr d = context.mkIntConst("d");
        BoolExpr expr = context.mkEq(c, context.mkAdd(a, context.mkInt(1)));
        System.out.println(expr);
        expr = (BoolExpr) expr.substitute(b, d);
        System.out.println(expr);
    }
```
in this case, int expression a and b should be the same, yet is not recognized by substitution, leading to result:
![image](https://github.com/Z3Prover/z3/assets/65483484/0b008cd7-fe34-4f09-96e1-8783055081ed)

**Comment by NikolajBjorner** [comment]
It is not the same: when you use the API to create a fresh constant it is marked as internal. You should not use strings with !NNN in the suffix to overlap with internal strings if you want the pretty printer to be unambiguous.

**Comment by NikolajBjorner** [comment]
external fresh declarations are actually not marked as skolem/internal. The lack of round-tripping over strings is due to another reason:
