### ISSUE TITLE
ASSERTION VIOLATION, File: ../src/math/lp/int_solver.cpp, Line: 163

### ISSUE THREAD

**Issue by zhendongsu** [Z3Prover/z3#6812]
Commit: https://github.com/Z3Prover/z3/commit/3849f665d620f823b405e5cfcfad0f04e5ca95fa
OS: Ubuntu 22.04 

```
[541] % z3debug small.smt2 
ASSERTION VIOLATION
File: ../src/math/lp/int_solver.cpp
Line: 163
i != v || new_val.is_int()
(C)ontinue, (A)bort, (S)top, (T)hrow exception, Invoke (G)DB
a
[542] % cat small.smt2 
(declare-fun x () Real)
(check-sat-assuming ((and (< x 0.0) (> (div (to_int x) (to_int (/ 1 x))) 1.0))))
```

**Comment by levnach** [comment]
The assertion was too strong. We just need to assert that new_val.x+m_delta*new_val.y is integral, since we are patching this linear combination. Fixed by https://github.com/Z3Prover/z3/commit/fd5902f76eb312d81bcd12ef7fd140a80e31670a.
