### ISSUE TITLE
Z3 can't prove things with 'ite'

### ISSUE THREAD

**Issue by j123123** [Z3Prover/z3#682]
For example, this code:
```
(declare-fun myf (Int Int Int) Int)

(assert
  (forall ((x Int) (y Int) (z Int))
    (ite (= z 0) (= (myf x y z) (+ x y))
    (ite (= z 1) (= (myf x y z) (- x y))
    (ite (= z 2) (= (myf x y z) (* x y))
    (= (myf x y z) (div x y))
  ))))
)

(assert (= (myf 2 2 0) 4)) ;; 2+2 = 4

(check-sat)
(get-model)
(exit)
```
Z3 can't prove it. Maybe I miss something(need to add some strategy etc)?

**Comment by NikolajBjorner** [comment]
Try instead encodings of the form:

     (define-fun myf ((x Int) (y Int) (z Int)) Int
          (if (= z 0) (+ x y)
             (if (= z 1) (- x y)
               (if (= z 2) (* x y)
                   (div x y)))))

**Comment by j123123** [comment]
But Why3 output uses 'ite', not 'if'-s. Here is sample, trying to prove 2 + 2 = 2 ? 2 where '?' can be '-' '*' '/' but not '+' in WhyML language:
```
theory Test "Why3 test"
use import int.Int
use import int.EuclideanDivision

type operator = Plus | Minus | Mult | Divid

function myf (x y : int) (z : operator) : int = match z with
  | Plus  -> x + y
  | Minus -> x - y
  | Mult  -> x * y
  | Divid -> div x y
  end

  goal G1: exists y : operator. (myf 2 2 Plus = myf 2 2 y) /\ (y <> Plus)

end
```
SMT2 output for Z3:
```
;;; generated by SMT-LIB2 driver
;;; SMT-LIB2 driver: bit-vectors, common part
;;; SMT-LIB2: integer arithmetic
;; CompatOrderMult
  (assert
  (forall ((x Int) (y Int) (z Int))
  (=> (<= x y) (=> (<= 0 z) (<= (* x z) (* y z))))))

(declare-fun abs1 (Int) Int)

;; abs_def
  (assert
  (forall ((x Int)) (ite (<= 0 x) (= (abs1 x) x) (= (abs1 x) (- x)))))

;; Abs_le
  (assert
  (forall ((x Int) (y Int)) (= (<= (abs1 x) y) (and (<= (- y) x) (<= x y)))))

;; Abs_pos
  (assert (forall ((x Int)) (<= 0 (abs1 x))))

;; Div_unique
  (assert
  (forall ((x Int) (y Int) (q Int))
  (=> (< 0 y) (=> (and (<= (* q y) x) (< x (+ (* q y) y))) (= (div x y) q)))))

;; Div_bound
  (assert
  (forall ((x Int) (y Int))
  (=> (and (<= 0 x) (< 0 y)) (and (<= 0 (div x y)) (<= (div x y) x)))))

;; Div_inf
  (assert
  (forall ((x Int) (y Int)) (=> (and (<= 0 x) (< x y)) (= (div x y) 0))))

;; Div_inf_neg
  (assert
  (forall ((x Int) (y Int))
  (=> (and (< 0 x) (<= x y)) (= (div (- x) y) (- 1)))))

;; Mod_0
  (assert (forall ((y Int)) (=> (not (= y 0)) (= (mod 0 y) 0))))

;; Div_1_left
  (assert (forall ((y Int)) (=> (< 1 y) (= (div 1 y) 0))))

;; Div_minus1_left
  (assert (forall ((y Int)) (=> (< 1 y) (= (div (- 1) y) (- 1)))))

;; Mod_1_left
  (assert (forall ((y Int)) (=> (< 1 y) (= (mod 1 y) 1))))

;; Mod_minus1_left
  (assert (forall ((y Int)) (=> (< 1 y) (= (mod (- 1) y) (- y 1)))))

;; Div_mult
  (assert
  (forall ((x Int) (y Int) (z Int))
  (! (=> (< 0 x) (= (div (+ (* x y) z) x) (+ y (div z x)))) :pattern ((div (+ (* x y) z) x)) )))

;; Mod_mult
  (assert
  (forall ((x Int) (y Int) (z Int))
  (! (=> (< 0 x) (= (mod (+ (* x y) z) x) (mod z x))) :pattern ((mod (+ (* x y) z) x)) )))

(declare-datatypes () ((operator (Plus) (Minus) (Mult) (Divid))))
(declare-fun myf (Int Int operator) Int)

;; myf_def
  (assert
  (forall ((x Int) (y Int) (z operator))
  (ite (is-Plus z) (= (myf x y z) (+ x y)) (ite (is-Minus z) (= (myf x y z) (- x y)) 
                                           (ite (is-Mult z) (= (myf x y z) (* x y)) (= 
                                           (myf x y z) (div x y)))))))

(assert
;; G1
 ;; File "check2/../check2.why", line 14, characters 7-9
  (not
  (exists ((y operator))
  (and (= (myf 2 2 Plus) (myf 2 2 y)) (not (= y Plus))))))
(check-sat)
```
here it uses 'ite', not 'if'. And if I understand correctly, code with 'if' and 'ite' have same meaning. Why Z3 can't handle with 'ite'?

**Comment by j123123** [comment]
@NikolajBjorner can you confirm it as a bug? Or you think this is why3 issue?

**Comment by NikolajBjorner** [comment]
Perhaps there is some misunderstanding: Z3 doesn't do your example because it is unable to establish a model for the function myf. The formula is satisfiable. Why3 could have created a more Z3 friendly version of myf_def by using either the approach I describe above using "define-fun", or by putting (myf x y z) in a single occurrence, on the left side of an equality. For example: 

        
            (assert              
                (forall ((x Int) (y Int) (z Int))
                (= (myf x y z) 
                  (ite (= z 0) (+ x y)
                   (ite (= z 1) (- x y)
                    (ite (= z 2) (* x y)
                      (div x y))))))
             )

And then use z3 with the option smt.macro_finder=true

You would then see:

C:\z3\build>z3 why.smt2 /v:10 smt.macro_finder=true
(simplifier :num-exprs 24 :num-asts 205 :time 0.00 :before-memory 1.21 :after-memory 1.21)
(smt.propagate-booleans)
(smt.constant-propagation)
(smt.find-macros)
(smt.reducing)
(smt.nnf)
(smt.eliminating-and)
(smt.lifting ng ite)
(smt.reducing)
(smt.refine-injectivity)
(smt.find-macros)
(smt.reducing)
(smt.cheap-fourier-motzkin)
(smt.pattern-inference)
(smt.simplifier-done)
(smt.searching)
sat
(model
  (define-fun myf ((x!0 Int) (x!1 Int) (x!2 Int)) Int
    (ite (= x!2 0)
         (+ x!0 x!1)
         (ite (= x!2 1)
              (+ x!0 (* (- 1) x!1))
              (ite (= x!2 2) (* x!0 x!1) (div x!0 x!1)))))
)
