### ISSUE TITLE
Nuget package no longer includes Linux binaries

### ISSUE THREAD

**Issue by James-LG** [Z3Prover/z3#6822]
Starting in version 4.12.0 the nuget package no longer includes the Linux runtime binaries, meaning Linux users will get a `DllNotFoundException`.

```
System.DllNotFoundException : Unable to load shared library 'libz3' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: liblibz3: cannot open shared object file: No such file or directory
Stack Trace:
  at Microsoft.Z3.Native.LIB.Z3_mk_config()
  at Microsoft.Z3.Context..ctor(Dictionary`2 settings)
```

By opening the nuget packages with 7zip, I can see v4.11.2 has a `runtimes/linux-x64/native/libz3.so` file, but then starting in v4.12.0 the `linux-x64` path is missing.

Was this file intentionally removed?

**Comment by NikolajBjorner** [comment]
Try now: https://github.com/Z3Prover/z3/releases/tag/Nightly

**Comment by James-LG** [comment]
Thanks for the quick response. Unfortunately I'm still getting the same exception with the nightly build.

I'm wondering if it has to do with `liblibz3: cannot open shared object file`; more specifically `liblibz3` seems incorrect, I would expect it to be looking for `libz3` shared object file based on the file included in the nuget package.

**Comment by NikolajBjorner** [comment]
the nuget package has libz3, not liblibz3. I don't know/recall what would cause anything to look for liblibz3. This would be the root cause of the load failure.

**Comment by James-LG** [comment]
Is there a way to build the nuget package locally? Then I might be able to narrow down the change that caused the failure.

**Comment by James-LG** [comment]
Took a lot of fiddling, but I've narrowed down the issue to glibc 2.35. When I build the package with a version of Ubuntu that uses glibc 2.31, it works, but when I build it with the latest Ubuntu that has glibc 2.35 it fails with `Unable to load shared library 'z3' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libz3: cannot open shared object file: No such file or directory` even though the `libz3.so` file is right there in the package.

I can even take the package built with glibc 2.35 and copy over the `runtimes\linux-x64\native\libz3.so` file from the package built with glibc 2.31 and it will work. So the *only* difference is the Linux binary being built with glibc 2.35.

I tried tracking down what exactly caused this but unfortunately I didn't come up with anything, so I'm still at a loss on how to fix this short of downgrading the Ubuntu version.

**Comment by aytey** [comment]
You didn't say what glibc version you're trying to _run on_ (only where you're trying to _build_).

```
ldd --version
```

on the system you're want to run on is probably the easiest way.

Anyway, the point is the same: glibc is not backwards compatible. If you build on a 2.35 system, it isn't going to run on a 2.31 system (unless you force gcc to compile with versioned symbols at 2.31 *or* you get lucky and your binary doesn't link any 2.35 versioned symbols). Typically the solution here would be to build z3 on the earliest glibc you need to support (which might be 2.31).

**Comment by aytey** [comment]
Oh, also, if you set `LD_DEBUG=all` in your shell on the system where things "don't work", then the glibc log will likely tell you what symbols were unable to be resolved (which results in your "Unable to load shared library ..." message).

**Comment by NikolajBjorner** [comment]
will update thread when nightly is fixed

**Comment by aytey** [comment]
> I also build oslib31 after a different request, but it doesn't get pulled into the nuget package. 

Yep; minumum glibc for what's now in the nightly is 2.34 (due to a versioned `pthread_mutex_clocklock`).

**Comment by NikolajBjorner** [comment]
Is there anything I should change for the nuget packaging?

**Comment by James-LG** [comment]
Well in that case, glibc 2.31 please :)

**Comment by James-LG** [comment]
The latest Nuget package is missing the Linux binaries entirely

![image](https://github.com/Z3Prover/z3/assets/1709432/6e2ad420-1bd5-4a07-9454-88980fb83f50)

**Comment by aytey** [comment]
Looks good for 2.31 users; the minimum glibc for the latest package is 2.29 (for exp, log and pow).

**Comment by James-LG** [comment]
Yep, confirmed working. Thanks guys!
