### ISSUE TITLE
Non-annotated tags in the build version

### ISSUE THREAD

**Issue by MichaelRawson** [Z3Prover/z3#6823]
If you do a CMake build (probably the Python build too, based on [this](https://github.com/Z3Prover/z3/blob/3479cdc10b94d9fd09437e093bcd9755a573d070/scripts/mk_util.py#L2870), but I haven't tested this hypothesis), it [runs](https://github.com/Z3Prover/z3/blob/3479cdc10b94d9fd09437e093bcd9755a573d070/cmake/git_utils.cmake#L201) `git describe --long` to get a string that goes in `z3_version.h`, that eventually ends up in `Z3_get_full_version`.

Unfortunately on current master, `git describe --long` gives `z3-4.8.4-7624-g3479cdc10`, i.e. version 4.8.4 + 7,624 commits (!). This is because 4.8.4 was the last release to use an annotated (rather than lightweight) tag, which can produce the confusing situation where you build your application against Z3 4.12 and it reports
```
Linked with Z3 4.12.2.0 e417f7d78509b2d0c9ebc911fee7632e6ef546b6 z3-4.8.4-7517-ge417f7d78
```

Naturally this isn't especially urgent, but I think there are two possible fixes:
1. Use annotated tags for new releases (...and historical releases?). I believe this is the recommendation.
2. Invoke `git describe --tags --long` instead. I believe this to be a two-line fix, so I won't bother you with a PR. This gives `z3-4.12.2-107-g3479cdc10`, i.e. version 4.12.2 + 107 commits, which seems more reasonable.

Best wishes, and thanks for the quality software!

**Comment by NikolajBjorner** [comment]
I am a bit unsure what action I should take to address this.
I did a manual tracked tag update recently. It could also be added to a CI/CD process?

**Comment by MichaelRawson** [comment]
Git tags confuse me and apparently GitHub's support for them is [not great](https://github.com/orgs/community/discussions/4924), so if it were me I'd go with option 2 and add `--tags` to `git describe` so we get the other type of tags too.
