### ISSUE TITLE
Z3 Optimizer Unsatisfiability with Real Constraints

### ISSUE THREAD

**Issue by chriswailes** [Z3Prover/z3#683]
I'm having an issue where the optimizer declares that a set of constraints is unsatisfied if a constraint contains a real value that isn't reducible to an integer.

Specifically, the following code will report 'unsat':

```
(declare-datatypes () ((PartID (P0) (P1))))

(declare-fun n3_p () PartID)
(declare-fun n2_p () PartID)
(declare-fun n1_p () PartID)
(declare-fun n0_p () PartID)

(declare-fun imbalance () Int)

(assert
  (let ((a!1 (+ 0
                (ite (= n0_p P0) 4 0)
                (ite (= n1_p P0) 2 0)
                (ite (= n2_p P0) 1 0)
                (ite (= n3_p P0) 1 0)))
        (a!2 (+ 0
                (ite (= n0_p P1) 4 0)
                (ite (= n1_p P1) 2 0)
                (ite (= n2_p P1) 1 0)
                (ite (= n3_p P1) 1 0))))
       (= imbalance (ite (> a!1 a!2) (- a!1 a!2) (- a!2 a!1)))))

(assert (<= (to_real imbalance) (/ 2.0 25.0)))
(minimize imbalance)
(check-sat)
```

I have found three independent modifications that cause Z3 to declare the system satisfiable and produce a valid model:

1. Commenting out `(minimize imbalance)` or
2. Commenting out `(assert (<= (to_real imbalance) (/ 2.0 25.0)))` or
3. Making the bound on `imbalance` reducible to an integer (e.g. `(/ 2.0 2.0)`)

If, in the original system, you replace `(minimize imbalance)` with `(minimize 0)` Z3 still reports `unsat`.

Am I using Z3 incorrectly, is there a subtle bug in my program, or is this an actual issue with Z3?

**Comment by NikolajBjorner** [comment]
It was a bug in Z3. Thanks for reporting it and the repro.

**Comment by chriswailes** [comment]
Thanks for the fix!
