### ISSUE TITLE
str.contains with symbolic string as first argument failing beyond equality

### ISSUE THREAD

**Issue by tlringer** [Z3Prover/z3#684]
(I know string support is preliminary, so maybe this isn't completely implemented yet.)

When I use a symbolic string as the first argument in str.contains, the only string I can get back is one that's equal to the second argument. If I constrain this not to be true, then I get back the string with !0! at the beginning and !1! at the end. Here is an example:

```
(declare-const c0 String)
(define-fun e1 () Bool (= "barbar" c0))
(define-fun e2 () Bool (not e1))
(define-fun e3 () Bool (str.contains c0 "barbar"))
(assert e2)
(assert e3)
(check-sat)
(get-model)
```

`sat (model (define-fun c0 () String "!0!barbar!1!") )`

If I then constrain against that, assuming it is just the string that Z3 happened to generate, then it does not generate a distinct string, but instead generates the same string again. So I assume there is something happening on the back-end. Here is an example of that:

```
(declare-const c0 String)
(define-fun e1 () Bool (= "barbar" c0))
(define-fun e2 () Bool (not e1))
(define-fun e3 () Bool (str.contains c0 "barbar"))
(define-fun e4 () Bool (not (= "!0!barbar!1!" c0)))
(assert e2)
(assert e3)
(assert e4)
(check-sat)
(get-model)
```

`sat (model (define-fun c0 () String "!0!barbar!1!") )`

**Comment by NikolajBjorner** [comment]
thanks
