### ISSUE TITLE
Bit Vector tactic leads to exit code 139 in Z3Py

### ISSUE THREAD

**Issue by abforce** [Z3Prover/z3#685]
_cross posted from: http://stackoverflow.com/q/38409443/1841194_

This is a simple bit vector problem:

    import z3

    s = z3.Tactic('bv').solver()
    m = z3.Function('m', z3.BitVecSort(32), z3.BitVecSort(32))
    a, b = z3.BitVecs('a b', 32)

    axioms = [
        a == m(12432),
        z3.Not(a == b)
    ]

    s.add(axioms)
    print(s.check())

Python crashes with error code 139. Please note that, this is not my real problem, so I _must_ use `bv` tactic in my project, though it doesn't have any problem with `smt` tactic or even `qfbv` tactic.

**Comment by wintersteiger** [comment]
I can't reproduce this problem on any of the usual systems and versions of Python. Could you check whether this is still a problem using the latest source from the master branch, and if so provide is with the version numbers of all of the tools you are using?

**Comment by abforce** [comment]
You're right. In 4.4.2 it's fixed, however in 4.4.0 the bug exists.
