### ISSUE TITLE
(rewriter.flat=false) Soundness bug

### ISSUE THREAD

**Issue by wintered** [Z3Prover/z3#6853]
[a932e59](https://github.com/Z3Prover/z3/commit/a932e596eb9b1733ec953c9a8ee9d6cfb2f38195)
```
$z3release model_validate=true bug.smt2                    
unsat
$z3release model_validate=true rewriter.flat=false bug.smt2
sat
$cat bug.smt2 
(declare-fun a () Int)  
(assert (exists ((b Int)) (and (<= 2 a) (= (mod b (+ a a))(+ b 7)) ))) 
(check-sat)             
$
```

**Comment by wintered** [comment]
a932e596eb9b1733ec953c9a8ee9d6cfb2f38195
```
$z3release model_validate=true bug.smt2 
sat
$z3release rewriter.flat=false model_validate=true bug.smt2
sat
(error "line 6 column 10: an invalid model was generated")
$cat bug.smt2 
(declare-fun a () Int) 
(declare-fun b () Int) 
(assert (and  (<= 6 (* (* 6 b) a)) )) 
(assert (not (and  (exists ((c Int)) 
        (and  (<= c 6))) (<= b 0)))) 
(check-sat)              
$
```

**Comment by NikolajBjorner** [comment]
it is not a new bug.
it relies on toggling rewriter.flat to false: arith.solver=2 makes strong assumptions that monomials are normalized in a way that is ensured by rewriter.flat=true. 
Given the tradeoffs of introducing new bugs by touching this assumption and the obscurity of the exposed parameter I can't say it makes sense to address this bug. I will leave it as won't fix.
Using rewriter.flat=false as a useful way to explore fuzz corner cases seems to have run its course.

**Comment by wintered** [comment]
Okay @NikolajBjorner, in that case I will no longer test `rewriter.flat=false`
