### ISSUE TITLE
Performance issue regular expression and int.to.str

### ISSUE THREAD

**Issue by pjljvandelaar** [Z3Prover/z3#686]
Dear Z3 developers,

When I try to solve this problem with Z3, I don't get an answer within an hour
and Z3 use a huge amount of memory (over 13 GB)
[performanceIssue.zip](https://github.com/Z3Prover/z3/files/368526/performanceIssue.zip)

The problem can be solved faster, since 
with another problem solver, I get an answer within seconds.

I hope you can improve the performance of Z3!

Success in advance,

Pierre

**Comment by NikolajBjorner** [comment]
I think this was fixed.
