### ISSUE TITLE
dl_query test fails on armel and armhf

### ISSUE THREAD

**Issue by FabianWolff** [Z3Prover/z3#687]
Hi,

building z3 for Debian currently fails on ARM 32-bit architectures (arm64 works, weirdly). The reason is a failure of (I think) the dl_query test.

Here are the full build logs (scroll to the bottom):
https://buildd.debian.org/status/fetch.php?pkg=z3&arch=armel&ver=4.4.1-0.1&stamp=1468851849
https://buildd.debian.org/status/fetch.php?pkg=z3&arch=armhf&ver=4.4.1-0.1&stamp=1468851878

Unfortunately, I don't have access to any ARM machines myself, so I can't provide a stacktrace or anything like that.

Building z3 on some other architectures failed for unrelated reasons, so there might be more architectures affected by this problem. The ones known to work are amd64, i386 and arm64.

Regards,
Fabian

**Comment by NikolajBjorner** [comment]
Thanks,
The dl_query test is basically a no-op, and it seems to complete fine.
The next unit test is "quant_solve", invoked using "test-z3 quant_solve". It works on my environment, however.

**Comment by FabianWolff** [comment]
I see. Thanks for having a look! I disabled the failing tests in the Debian package, so it now builds fine with the majority of tests still enabled (and passing).

The reason it says 4.4.1 is because I packaged the last officially tagged release from here:
https://github.com/Z3Prover/z3/releases

Unless there is a good reason for it, we usually do not package development snapshots in Debian. Once there is a proper 4.4.2 release, we will upgrade to that one.

I think you can close this issue if you believe the problem has already been fixed since the 4.4.1 release.

**Comment by NikolajBjorner** [comment]
It is quite possibly a latent problem then: the 4.4.1 unit test exercises dl_query, the newer versions do not as the dl_query unit test wasn't up to standards. I just don't presently have an ARM machine handy to debug this. Maybe I should pick up a raspberry pi for my teenage son and introduce him to the glory of CS by debugging this. :-).
We need to update the master branch in the next few weeks anyhow. It has been quite a while by now. Current efforts are around fixing bug reports that come in.
