### ISSUE TITLE
broken links in API documentation

### ISSUE THREAD

**Issue by polgreen** [Z3Prover/z3#6870]
There are lots of broken links in the API documentation, e.g.,

https://z3prover.github.io/api/html/classcom_1_1microsoft_1_1z3_1_1_bit_vec_expr.html

This page says that the definition of getSortSize is at line 32 of https://z3prover.github.io/api/html/_bit_vec_expr_8java_source.html, which does not exist anymore

This seems to be true for all the links to definitions

**Comment by NikolajBjorner** [comment]
appears to be a Jekyll default to not serve pages starting with _. I don't have any prior idea of configuring Jekyll/github pages to comply with underscore names.
As a workaround you can download the doc and browse it locally.

**Comment by NikolajBjorner** [comment]
I don't know how to tweak jekyll. So the workaround is you download the docs locally from the release.
