### ISSUE TITLE
Performance issue with inc. number of string constraints into solver of Z3.

### ISSUE THREAD

**Issue by singh-harish** [Z3Prover/z3#6872]
Hi developers,

Facing a hug performance issue while dealing with string constraint solving using Z3.

For example:

For the constraint below(in SMT format):
```
(declare-fun str () String)
(assert (str.contains str "a"))
(assert (str.contains str "b"))
(assert (str.contains str "c"))
(assert (str.contains str "d"))
(assert (str.contains str "e"))
(assert (str.contains str "f"))
(assert (str.contains str "g"))
(assert (str.contains str "h"))
```

The CPU time take by Z3 java and Z3 python are as follows:
```
Z3 JAVA API: 
	The formula is satisfiable!
	Model: (define-fun str () String
	  "gedcahbf")
	Aug 23, 2023 11:52:46 AM pkg.Z3DemoClass main
	INFO: *** Elapsed CPU time in milliseconds (Z3-Module) : 1,503.525 == 1.5 seconds


Z3 Python API:
	(.venv) sh-5.1$ /home/harish/Desktop/Python/.venv/bin/python /home/harish/Desktop/Python/Z3-Demo.py
	The formula is satisfiable!
	Model: [strVar = "fahegcdb"]
	CPU Execution time: 3.793655818 seconds
```

Now let us move one step, now adding one more constraint to the solver object and trying to get solitions:
```
(declare-fun str () String)
(assert (str.contains str "a"))
(assert (str.contains str "b"))
(assert (str.contains str "c"))
(assert (str.contains str "d"))
(assert (str.contains str "e"))
(assert (str.contains str "f"))
(assert (str.contains str "g"))
(assert (str.contains str "h"))
(assert (str.contains str "i"))
```

Here it takes a huge amount of time to solve which i believe is not normal:
```
Z3 JAVA API:
	The formula is satisfiable!
	Model: (define-fun str () String
	  "aedgbifch")
	Aug 23, 2023 12:00:58 PM pkg.Z3DemoClass main
	INFO: *** Elapsed CPU time in milliseconds (Z3-Module) : 401,622.367 == 401.622 seconds


Z3 Python API:
	(.venv) sh-5.1$ /home/harish/Desktop/Python/.venv/bin/python /home/harish/Desktop/Python/Z3-Demo.py
	The formula is satisfiable!
	Model: [strVar = "bgihdcfea"]
	CPU Execution time: 556.938318174 seconds
``` 

- My requirement and expectations from Z3 solver is to solve around 50 to 60 constraints for a single string variable and we will have more than 20 to 30 such variables.
- All in all, expectation is to solve atleast more than 100 to 500 constraints pushed into solver object of Z3.
- It is taking 401 sec in Java to solve around 9 constraints pushed to solver. How is it going to handle 100 or 500 such constraints. It is going to stuck at solver.check() stage.

- Please help me with this. Whats the solution to it.?  or Is their something wrong with my approach.

**Comment by NikolajBjorner** [comment]
it is faster if you constrain the length of the strings to be equal to some number of characters.
If you have information from the domain to set lengths it is much faster, otherwise the current solver doesn't handle them well.
Your example also comes with lots of symmetries. Front-ends would do well with breaking symmetries whenever they can.
