### ISSUE TITLE
Do not segfault on unknown function declaration in Z3_get_decl_kind

### ISSUE THREAD

**Issue by PhilippWendler** [Z3Prover/z3#688]
The API function [`Z3_get_decl_kind`](https://github.com/Z3Prover/z3/blob/d30ba3f1adfb84d00b5db660d30da4748a28ff6a/src/api/api_ast.cpp#L901) segfaults when a function declaration is passed that is not known to this method. This is very problematic when traversing formulas, especially because Z3 itself creates formulas that contain functions that trigger these segfaults (example in #669, but there are more than that, for example `bit2bool`).

There are also several cases where the function returns `Z3_OP_UNINTERPRETED` as a default value, where I am not sure whether this is valid.

So I would like to ask you, to please never let this method segfault, and to never let it return a wrong answer.

I suggest to either make sure that all functions that are created by Z3 are known to this method, or to return some error code, or at least to add a value like `Z3_OP_UNKNOWN` and return this as default.

**Comment by NikolajBjorner** [comment]
Yes, this makes sense

**Comment by NikolajBjorner** [comment]
Can you review the change and for feedback? I use the name "Z3_OP_INTERNAL" for standard cases, but retain UNINTERPRETED in a catch all case to limit the entropy of the change.

**Comment by nunoplopes** [comment]
I'm not sure I agree with this change.  If there's some decl missing, it should be added, but a Z3_OP_INTERNAL catch-all is not optimal.  At least for applications that need to traverse formulas and maybe do some preprocessing themselves, they likely need to be exposed to the internal symbols.
Z3 already exports quite a few internal decls like OP_BUREM_I or OP_FPA_INTERNAL_MIN_I.

**Comment by wintersteiger** [comment]
I second that, we should just export all symbols instead of trying to hide some of them. Since the introduction of the tactic infrastructure, users may want to run existing tactics and then process whatever comes out of that and even an innocent `(apply simplify)` will introduce some of those functions considered as uninterpreted. This will likely cause some disruption to existing applications, but I think those issues would be easy to fix.

**Comment by NikolajBjorner** [comment]
1. INTERNAL is much more graceful than crashing (in debug mode) when a case is not covered.
2. You always have the function declaration symbol to dispatch on in user code.
3. Add a pull request with additional operators that you would like to include.

**Comment by cheshire** [comment]
@NikolajBjorner as a general note, I would like to add that from Java perspective we really don't mind crashing that much, as stack traces are relatively easy to deal with.
We do mind segmentation faults a lot, as they just kill the process with no trace, and there's no way to recover from them.

I've noticed that many segfaults go away in the debug mode, as some assertion is often violated before that, which gives a chance to get a clean exception trace.
How expensive are these assert statements? Would it be possible to get a reasonably fast binary with them enabled?

**Comment by NikolajBjorner** [comment]
The intent is that assertions track internal inconsistencies. That is, code bugs. Some assertions are really expensive. So I would try to solve the parameter validation issues outside of assertions.

**Comment by PhilippWendler** [comment]
@NikolajBjorner Thanks! This fix works nicely for us. Z3_OP_INTERNAL is no problem for us because we don't need the semantics of the more obscure functions and threat them as "OTHER" in our code anyway. I also agree with your arguments.
