### ISSUE TITLE
The z3py polynomial solver returned incorrect results

### ISSUE THREAD

**Issue by frankeyjin** [Z3Prover/z3#6885]
# my code
from z3 import *

x = BitVec('x',32)
y = BitVec('y',32)

solver = Solver()
solver.add(x\*x\*x + x\*x + x - 10 > 0)
solver.add(y\*y\*y + y\*y + y - 10 <= 0)
solver.add(x==y+1)
solver.add(y>=2147483648)

if solver.check() == sat:
&nbsp;&nbsp;&nbsp;&nbsp;model = solver.model()
&nbsp;&nbsp;&nbsp;&nbsp;print(model)

print(get_version_string())

### The printed results are as follows
[y = 2033076409, x = 2033076410]
4.12.1

# another code
from z3 import *

x = BitVec('x',32)
y = BitVec('y',32)

solver = Solver()
solver.add(x\*x\*x + x\*x + x - 10 > 0)
solver.add(y\*y\*y + y\*y + y - 10 <= 0)
solver.add(x==y+1)
solver.add(y==1)

while solver.check() == sat:
&nbsp;&nbsp;&nbsp;model = solver.model()
&nbsp;&nbsp;&nbsp;d=model[x].as_long();
&nbsp;&nbsp;&nbsp;print(d," ",model)
&nbsp;&nbsp;&nbsp;solver = Solver()
&nbsp;&nbsp;&nbsp;solver.add(x\*x\*x + x\*x + x - 10 > 0)
&nbsp;&nbsp;&nbsp;solver.add(y\*y\*y + y\*y + y - 10 <= 0)
&nbsp;&nbsp;&nbsp;solver.add(x==y+1)
&nbsp;&nbsp;&nbsp;solver.add(y >= d)

print(get_version_string())

### The printed results are as follows
2   [x = 2, y = 1]
1166016494   [y = 1166016493, x = 1166016494]
2127337577   [y = 2127337576, x = 2127337577]
2143412224   [y = 2143412223, x = 2143412224]
2145515772   [y = 2145515771, x = 2145515772]
2146040457   [y = 2146040456, x = 2146040457]
2147090346   [y = 2147090345, x = 2147090346]
2147483564   [y = 2147483563, x = 2147483564]
2147483578   [y = 2147483577, x = 2147483578]
2147483648   [y = 2147483647, x = 2147483648]
3291367610   [y = 3291367609, x = 3291367610]
3848567253   [y = 3848567252, x = 3848567253]
1725181533   [y = 1725181532, x = 1725181533]
1861500896   [y = 1861500895, x = 1861500896]
2130706425   [y = 2130706424, x = 2130706425]
2147483642   [y = 2147483641, x = 2147483642]
2147483646   [y = 2147483645, x = 2147483646]
2147483648   [y = 2147483647, x = 2147483648]
263077878   [y = 263077877, x = 263077878]
800047095   [y = 800047094, x = 800047095]
1626341376   [y = 1626341375, x = 1626341376]
1778102704   [y = 1778102703, x = 1778102704]
2147482109   [y = 2147482108, x = 2147482109]
2147483646   [y = 2147483645, x = 2147483646]
2147483648   [y = 2147483647, x = 2147483648]
2109023970   [y = 2109023969, x = 2109023970]
2113875708   [y = 2113875707, x = 2113875708]
2117681078   [y = 2117681077, x = 2117681078]
2119139326   [y = 2119139325, x = 2119139326]
2136997888   [y = 2136997887, x = 2136997888]
2138368186   [y = 2138368185, x = 2138368186]
2139484596   [y = 2139484595, x = 2139484596]
2144862135   [y = 2144862134, x = 2144862135]
2147483644   [y = 2147483643, x = 2147483644]
2147483646   [y = 2147483645, x = 2147483646]
2147483648   [y = 2147483647, x = 2147483648]
3318841341   [y = 3318841340, x = 3318841341]
688480046   [y = 688480045, x = 688480046]
1610702848   [y = 1610702847, x = 1610702848]
2008923134   [y = 2008923133, x = 2008923134]

**Comment by NikolajBjorner** [comment]
Note that in python > and >= are signed bit-vector comparisons.

https://microsoft.github.io/z3guide/programming/Z3%20Python%20-%20Readonly/Introduction#machine-arithmetic
