### ISSUE TITLE
z3 2.7 the option is not supported by the solver

### ISSUE THREAD

**Issue by zhanghv** [Z3Prover/z3#689]
Hi, i use z3 under ubuntu, and the version is 2,7. When i set the option produce-models,the solver respond unsupported. Please help me to resolve this case.

**Comment by NikolajBjorner** [comment]
Sorry, but this is a potentially imprecise description of a scenario with no clear repro and furthermore, version 2.7 so a rather old version of Z3. Newer versions are compiled daily and available from this GitHub repository. I doubt it is possible to provide support for a very outdated version like the one you mention.

**Comment by zhanghv** [comment]
Thanks for your kindly,early,fast reply.  I replaced a new version,and it work now!
