### ISSUE TITLE
ThirdParty Memory Allocators still causes crash

### ISSUE THREAD

**Issue by Naville** [Z3Prover/z3#6890]
From our internal project that uses Z3 and [snmalloc](https://github.com/microsoft/snmalloc/blob/7b597335aedc2c60b0174f6e67a7f7560f841760/src/snmalloc/override/malloc.cc#L6), we see some weird crash at [this line](https://github.com/Z3Prover/z3/blob/3aea4ebf42dd2b26261657e9a4823f91f9b3e736/src/util/memory_manager.cpp#L307)

Going to the top of the file, one can see that:

```
#elif defined(_WINDOWS)
# include <malloc.h>
# define HAS_MALLOC_USABLE_SIZE
# define malloc_usable_size _msize
#endif
```

While I havn't take deeper look into it, but apparently snmalloc doesn't provide overrides for ``_msize``. So in this case, the program would try to malloc from snm's heap, and uses WinCRT to query the usable size.

# Proposed fix
Make ``HAS_MALLOC_USABLE_SIZE`` an user configurable parameter

**Comment by nunoplopes** [comment]
They just need to provide an override for _msize.

BTW, I would be very curious to see perf results of using Z3 with snmalloc, including replacing all of Z3's hand-made allocators.

**Comment by Naville** [comment]
I'm not a memallocators expert (or expert in general). But is malloc() + ``msize()`` sort of like mixing usage of different APIs?

**Comment by nunoplopes** [comment]
> I'm not a memallocators expert (or expert in general). But is `malloc()` + `msize()` sort of like mixing usage of different APIs?

No: https://learn.microsoft.com/en-us/cpp/c-runtime-library/reference/msize?view=msvc-170#remarks

**Comment by NikolajBjorner** [comment]
How about 

```
#elif defined(_WINDOWS) && defined(_msize)
# include <malloc.h>
# define HAS_MALLOC_USABLE_SIZE
# define malloc_usable_size _msize
#endif
```

**Comment by nunoplopes** [comment]
_msize is not a macro on windows. At least the documentation doesn't say so. So that `#if` trick won't work.

**Comment by Naville** [comment]
Any reason we can't revert #6321 and disable related code on Windows?
Though, I agree that wait for snmalloc to fix the issue would be a equally good if not better idea :)

**Comment by nunoplopes** [comment]
> Any reason we can't revert #6321 and disable related code on Windows? Though, I agree that wait for snmalloc to fix the issue would be a equally good if not better idea :)

Yes, it will degrade performance. It doesn't make sense to make things worse for everyone.

**Comment by aytey** [comment]
@Naville: are you building with CMake or the "legacy" scripts? It would be "straightforward" to add an additional option to z3's CMakeLists.txt to say "no HAS_MALLOC_USABLE_SIZE", which could then guard the code as per https://github.com/Z3Prover/z3/issues/6890#issuecomment-1712317572

**Comment by Naville** [comment]
> @Naville: are you building with CMake or the "legacy" scripts? It would be "straightforward" to add an additional option to z3's CMakeLists.txt to say "no HAS_MALLOC_USABLE_SIZE", which could then guard the code as per [#6890 (comment)](https://github.com/Z3Prover/z3/issues/6890#issuecomment-1712317572)
> 
> As a note: I did check snmalloc and couldn't see any "you're using snmalloc" defines.

Yes that's exactly the Op was asking for. But as mentioned above the maintainers think it degrades the performance too much

**Comment by Naville** [comment]
While we're at it, [mimalloc](https://github.com/microsoft/mimalloc/blob/4e50d6714d471b72b2285e25a3df6c92db944593/include/mimalloc-override.h#L32) also provides only source-code level override for ``_msize``, which is next to use-less at least in our use-case

**Comment by Naville** [comment]
So does [rpmalloc](https://github.com/mjansson/rpmalloc)

**Comment by aytey** [comment]
> Yes that's similar to what I originally asked for. But as mentioned above @nunoplopes thinks it degrades the performance too much?

This would be a "build-time" change that would only apply _for you_ (so you'd have to explicitly opt-in). For everyone else, z3 would be unchanged. For you, you could have a build that uses `snmalloc` without using `msize`.
