### ISSUE TITLE
Z3 solver BitVec  URem performace 

### ISSUE THREAD

**Issue by antonper** [Z3Prover/z3#6891]
Following piece of code run for >1hour.

```python
from z3 import *

# Initialize the Z3 variables
var1 = BitVec('var1', 256)
var2 = BitVec('var2', 256)
array_storage = Array('array_storage', BitVecSort(256), BitVecSort(256))

# Constraints
s = Solver()

s.add(ULT(100, var1))
s.add(var2 < 100000)
s.add(URem(array_storage[var2], 100000) == var2)

# Storage modification
new_array_storage = Store(array_storage, URem(var1, 100000), var1)
s.add(Not(URem(new_array_storage[var2], 100000) == var2))

# Check if the constraints are solvable
if s.check() == sat:
    m = s.model()
    print("Found a model:\n", m)
else:
    print("No solution found.")

```

```smt2
; benchmark generated from python API
(set-info :status unknown)
(declare-fun var1 () (_ BitVec 256))
(declare-fun var2 () (_ BitVec 256))
(declare-fun array_storage () (Array (_ BitVec 256) (_ BitVec 256)))
(assert
 (bvult (_ bv100 256) var1))
(assert
 (bvslt var2 (_ bv100000 256)))
(assert
 (= (bvurem (select array_storage var2) (_ bv100000 256)) var2))
(assert
 (let ((?x53 (bvurem (select (store array_storage (bvurem var1 (_ bv100000 256)) var1) var2) (_ bv100000 256))))
 (not (= ?x53 var2))))
(check-sat)
```

>z3.get_version_string()
'4.12.1'

Code rewritten using z3.Int terminates in seconds.
Can you please let me know if this is an expected behavior?

**Comment by nunoplopes** [comment]
Arithmetic over 256 bits won't be fast any time soon. It requires different algorithms.

Why do you say the model is invalid? Did you try with another solver?

**Comment by NikolajBjorner** [comment]
QF_BV doesn't know about arrays. So in QF_BV array semantics is not enforced.

**Comment by antonper** [comment]
@nunoplopes as @NikolajBjorner  told the model was not respecting the array Store operation semantics.
I tried default solver and QF_BV only. Any suggestions about what other solvers can work for this?
The only arithmetic operation I am using is URem, but the query does not rely on any semantics of it.
The query where instead of URem I use : `Function('f', BitVecSort(256), BitVecSort(256), BitVecSort(256))` finishes in less than second. 


``` python
from z3 import *

# Initialize the Z3 variables
a = BitVec('a', 256)
b = BitVec('b', 256)
array_storage = Array('array_storage', BitVecSort(256), BitVecSort(256))

f = Function('f', BitVecSort(256), BitVecSort(256), BitVecSort(256))
# f = URem

# Constraints
s = Solver()


s.add(f(array_storage[a], 100000) == a)

# Storage modification
new_array_storage = Store(array_storage, f(b, 100000), b)
s.add(Not(f(new_array_storage[a], 100000) == a))

open('min.smt2', 'w').write(s.to_smt2())
# Check if the constraints are solvable
if s.check() == sat:
    m = s.model()
    print("Found a model:\n", m)
else:
    print("No solution found.")
```

**Comment by nunoplopes** [comment]
Z3 uses bit-blasting for bit-vector operations. The size of a 256-bit urem is gigantic. There's nothing to do here, I'm sorry.
Z3 may introduce new algorithms in the future, but right now either you shrink the number of bits, or try to use UFs if possible as you've done here.

**Comment by antonper** [comment]
Ok so we are doing now:
Treat URem as a UF and try to find a model. If  there is no model - finish.
If there is a model - treat URem as default z3.URem. Bitblast and try to find solution. 
As you told - this works. The question is: why won't z3 default solver do this out of box itself

**Comment by nunoplopes** [comment]
> Ok so we are doing now: Treat URem as a UF and try to find a model. If there is no model - finish. If there is a model - treat URem as default z3.URem. Bitblast and try to find solution. As you told - this works. The question is: why won't z3 default solver do this out of box itself

Patches welcome! 🙂
This approach is good for some problem kinds, but not all.
That said, there's a new SMT solver under development. It may do what you are proposing.
