### ISSUE TITLE
[Question] How to use `rotate_right` in z3py?

### ISSUE THREAD

**Issue by hagozaebii** [Z3Prover/z3#6893]
Hello,

Recently I had to use smtlibv2's `rotate_right` function via z3py. To accomplish this I used z3py's `RotateRight` function.
However, I found out that z3py's `RotateRight` function is not exactly the same as smtlibv2's `rotate_right` function.
First, the s-expression of `RotateRight` in z3py is `ext_rotate_right`, which does not work with `set-logic QF_BV`.
Could you let me now what to do if I want to use smtlibv2's `rotate_right` in smtlibv2?
Thanks for reading.

**Comment by NikolajBjorner** [comment]
You can write your own wrapper

```
def MyRotateRight(a, b):
    return BitVecRef(Z3_mk_rotate_right(a.ctx_ref(), a.as_ast(), b.as_ast()), a.ctx)
```

**Comment by hagozaebii** [comment]
@NikolajBjorner 

Always thanks for your answer. If you are okay with taking other questions, could I ask you something more?
1. `rotate_left` can be defined in the same way? for example,
```
def MyRotateLeft(a, b):
    return BitVecRef(Z3_mk_rotate_left(a.ctx_ref(), a.as_ast(), b.as_ast()), a.ctx)
```
2. What is the difference between `rotate_right` and `ext_rotate_right`? And why `ext_rotate_right` cannot be used in `QF_BV`?

Thank you again.

**Comment by NikolajBjorner** [comment]
1. Yes of course. See z3.py and z3_api.h 
2. The SMTLIB2 theory QF_BV specifies very specific set of operations. It does not understand any other built-in symbols. Any other symbols we introduce are outside of QF_BV.

**Comment by hagozaebii** [comment]
@NikolajBjorner 
I would like to thank your kindness.
