### ISSUE TITLE
Provide static version of prebuilt z3 library in GitHub Release

### ISSUE THREAD

**Issue by TheVeryDarkness** [Z3Prover/z3#6897]
Hello, I'm using z3 in Rust with [z3.rs](https://github.com/prove-rs/z3.rs), and I want to use a prebuilt version of z3 so that I don't need to  
 wait a long time to compile it. But it's not recommended to use dynamic library in most cases in Rust, especially for non-system library, and some binaries in cargo (such as documentation tests) just can't find the dynamic library.
So, can z3 provide a static version in every release in the future? It will be a great help.

**Comment by NikolajBjorner** [comment]
I suggest that you add a pull request to z3.rs that updates the release github action to include binaries that work with z3.rs.
The variant/platform matrix for z3 releases is already sufficiently elaborate.
