### ISSUE TITLE
fp.roundToIntegral issue

### ISSUE THREAD

**Issue by LeventErkok** [Z3Prover/z3#69]
For the following benchmark:

```
(set-option :produce-models true)
(set-logic QF_FP)
(declare-fun s0 () (_ FloatingPoint 8 24))
(assert (= s0 (fp.roundToIntegral roundNearestTiesToEven ((_ to_fp 8 24) roundNearestTiesToEven (/ 9 10)))))
(check-sat)
(get-value (s0))
```

Z3 responds:

```
sat
((s0 (_ +zero 8 24)))
```

i.e., ` +0` as the nearest integral value to `0.9` as a single-precision float. I think the correct answer should be `+1`.

**Comment by wintersteiger** [comment]
Thanks for the report! RoundToIntegral is indeed broken, no idea how that passed any of the fuzzers tests.

**Comment by LeventErkok** [comment]
@wintersteiger: Should I wait till you merge these back to z3/unstable to give them a try; or should I be using your personal branch?

I've no preference either way; just don't want to bug you further with issues that may be present in not-yet-ready code.

**Comment by wintersteiger** [comment]
This specific case is handled better in the update code, but the general case isn't ready yet. The semantics of roundToIntegral differ between SMT, IEEE754 and my SSE2 CPU, and I haven't decided whether I should change the benchmarks, the standard, or the implementation. Currently busy with non-FP things, so this will have to wait a little, at the very least until end of next week.

**Comment by LeventErkok** [comment]
Thanks! I'll wait till you actually "close" the tickets to pull then.

**Comment by wintersteiger** [comment]
This bug is now fixed, so I'm closing the issue. I replaced the old implementation of roundToIntegral with what is essentially a completely new one. If that proves to be buggy too, please reopen this or open a new issue.
