### ISSUE TITLE
Running Z3 using c++ in Ubuntu 20.04

### ISSUE THREAD

**Issue by anirjoshi** [Z3Prover/z3#6900]
I have installed Z3 from the source following all the steps, but I am unable to run the `examples/c++/examples.cpp` file.
Running the command `g++ examples.cpp` gives me a long error message mainly involving `/usr/bin/ld`. Is there anything that I should do after the installation to run Z3 in c++?

**Comment by aytey** [comment]
Try adding `-lz3` to the end of your `g++` command

**Comment by anirjoshi** [comment]
It doesn't seem to work even with adding `lz3`. The command `g++ examples.cpp -lz3`  returns the following:
```
/usr/bin/ld: /tmp/ccaHoFaV.o: in function `z3::expr::get_u32string[abi:cxx11]() const':
example.cpp:(.text._ZNK2z34expr13get_u32stringB5cxx11Ev[_ZNK2z34expr13get_u32stringB5cxx11Ev]+0x72): undefined reference to `Z3_get_string_length'
/usr/bin/ld: example.cpp:(.text._ZNK2z34expr13get_u32stringB5cxx11Ev[_ZNK2z34expr13get_u32stringB5cxx11Ev]+0xd1): undefined reference to `Z3_get_string_contents'
/usr/bin/ld: /tmp/ccaHoFaV.o: in function `z3::context::datatype_sort(z3::symbol const&)':
example.cpp:(.text._ZN2z37context13datatype_sortERKNS_6symbolE[_ZN2z37context13datatype_sortERKNS_6symbolE]+0x3b): undefined reference to `Z3_mk_datatype_sort'
/usr/bin/ld: /tmp/ccaHoFaV.o: in function `z3::context::real_val(long, long)':
example.cpp:(.text._ZN2z37context8real_valEll[_ZN2z37context8real_valEll]+0x33): undefined reference to `Z3_mk_real_int64'
collect2: error: ld returned 1 exit status
```

**Comment by NikolajBjorner** [comment]
This would be a problem with the path. The header file includes newer functions, your lib path points to an older version of z3. Check your path environment and references to libz3
