### ISSUE TITLE
Z3PY hangs on formula containing Int and Bool variables

### ISSUE THREAD

**Issue by aric-fowler** [Z3Prover/z3#6921]
I'm using Python Z3 to conduct SAT attacks on encrypted netlists to evaluate security. When I run one of my Z3 scripts though, the Python shell hangs. The script is supposed to return SAT or UNSAT, but it does neither. It just hangs. The formula is very long, but I have run scripts with longer formulas and I haven't had any problem with those, so I'm not convinced that I'm encountering some kind of size limit. The only thing that I thought might be causing a problem is how Z3 treats clauses that contain both Int and Bool variables. I found a [similar thread](https://github.com/Z3Prover/z3/issues/5551) where someone's issue stemmed from using String variables.

These scripts are fairly long, so I'm attaching them as .txt files, but they are Python scripts. The script that hangs is miter.txt. 
[miter.txt](https://github.com/Z3Prover/z3/files/12718780/miter.txt)

There are two, shorter versions of this script, where the formulas are similar. I'm attaching these two as well. Z3 does take a second or two to solve either of these, but it can solve both.

[miter_cp1.txt](https://github.com/Z3Prover/z3/files/12718855/miter_cp1.txt)
[miter_cp2.txt](https://github.com/Z3Prover/z3/files/12718858/miter_cp2.txt)

**Comment by NikolajBjorner** [comment]
It is just harder for z3.

Try changing your script

	print(s.sexpr() + "\n(check-sat)\n")
	exit(0)

	try:
		return s.check(), s.model()
	except:
		return s.check(), None

Then save the output in a file, miter.smt2
Then run z3 with -v:2 on miter.smt2
You will see it is busy searching

**Comment by aric-fowler** [comment]
Thank you
