### ISSUE TITLE
Segmentation Fault with pb2bv tactic

### ISSUE THREAD

**Issue by DiegoMyGit** [Z3Prover/z3#6923]
Hello,

First, thanks for making this library open source; it's very useful!

When I have too many constraints in a Goal (around 2^18) and try to apply the tactic pb2bv, it results in a segmentation fault (I have tried in both Python and C++). I am pretty sure it is not a memory problem, as I have tracked the memory used by the program, and I was only using 14% (70 GB out of 500 GB) of memory when the program crashed.

Is it a known problem when the number of clauses is too high? I can share a minimal code reproducing the problem if needed.

Thank you

**Comment by NikolajBjorner** [comment]
a repro would be required to close this.

**Comment by DiegoMyGit** [comment]
[main.zip](https://github.com/Z3Prover/z3/files/12752931/main.zip)
Here is the code that reproduces the problem in c++, it takes about 5 minutes to run into the segmentation fault.
The code is not super minimal but after some tests but I needed to make the clauses complex enough to trigger the segmentation fault

Thank you

**Comment by NikolajBjorner** [comment]
it isn't a segmentation fault on my side. It is an out-of-memory exception that isn't caught in the code.

    try {
        apply_result res = t(g);
    }
    catch (z3::exception const& e) {
        cout << e << "\n";
    }

**Comment by DiegoMyGit** [comment]
As you recommanded I added

```
try {
    apply_result res = t(g);
}
catch (z3::exception const& e) {
    cout << e << "\n";
}
```

To give you the configuration I use, I am on linux with gcc 11 and I am using a calculation cluster

The error I get depends on the memory I allow the job to have but in both cases it is not caught by z3::exception.
For instance when setting 8GB, I get an out-of-memory error
```
/var/spool/slurm/d/job1742306/slurm_script: line 11:  8515 Killed                  ./main.exe > ./data.txt
slurmstepd: error: Detected 1 oom-kill event(s) in StepId=1742306.batch cgroup. Some of your processes may have been killed by the cgroup out-of-memory handler.
```
But when allowing 40GB, I get a segmentation fault.
```/var/spool/slurm/d/job1740855/slurm_script: line 11: 16759 Segmentation fault      ./main.exe > ./data.txt```

**Comment by NikolajBjorner** [comment]
Not sure where the virtual memory issue would be. Maybe as benign as when it accesses std::cerr to print it is out of memory.

You can add

    set_param("memory_max_size", 40000);

So it runs out of allocated memory before virtual memory.
