### ISSUE TITLE
`symbol lookup error` when trying to run `cpp_example`

### ISSUE THREAD

**Issue by anirjoshi** [Z3Prover/z3#6926]
I am using `Ubuntu 20.04`, and am getting the following error when I try to execute `cpp_example` in the build directory.
`./cpp_example: symbol lookup error: ./cpp_example: undefined symbol: Z3_get_string_contents`

I believe this `cpp_example` was build after running `make examples` in the build directory.

I intend to use `c++` interface in the `Z3` tool, is this the correct way to do this?

**Comment by NikolajBjorner** [comment]
It is typically resolved as follows: there is a stale version of libz3 on your path.

**Comment by anirjoshi** [comment]
I see, is there any way to uninstall the older packages? Some specific command?

**Comment by nunoplopes** [comment]
You can use `-rpath` to set the library path in the binary.
