### ISSUE TITLE
Z3 Fails to Find Optimal Model

### ISSUE THREAD

**Issue by chriswailes** [Z3Prover/z3#693]
I'm using Z3 to partition graphs, and in the process of doing that I discovered that Z3 will produce sub-optimal results for values it is asked to minimize.  The attached archive contains a graph file in the METIS/CHACO graph file format, the encoding of the graph partitioning problem for this graph as a Z3 formula (minimizing the edge cut), and the results of partitioning the graph using METIS and Z3.  Both tools find a solution with equal partition weights (13:13), but METIS finds a solution with an edge cut of 16 and Z3 finds a solution with an edge cut of 24.

For the result files, each line represents the partition assignment for the node corresponding to the line number.

[z3-sub-optimal-results.zip](https://github.com/Z3Prover/z3/files/377064/z3-sub-optimal-results.zip)

**Comment by NikolajBjorner** [comment]
The sls method is a local search heuristic and does not ensure optimality.
It is better to ensure that the constraints end up being Boolean or Bit-vectors. So replace the first lines with:

        ;(declare-datatypes () ((PartID (P1) (P0))))
        (define-sort PartID () Bool)
        (define-const P1 Bool true)
        (define-const P0 Bool false)

You then get the result along the lines of (after a minute or two):

(opt.maxres [16:16])
is-sat: l_true
Satisfying soft constraints
(not (not (= n1_p n0_p))) |-> false
(not (not (= n2_p n0_p))) |-> true
(not (not (= n3_p n0_p))) |-> true
(not (not (= n4_p n0_p))) |-> true
(not (not (= n5_p n1_p))) |-> true
(not (not (= n6_p n1_p))) |-> true
(not (not (= n7_p n1_p))) |-> true
(not (not (= n8_p n2_p))) |-> false
(not (not (= n9_p n2_p))) |-> true
(not (not (= n10_p n2_p))) |-> true
(not (not (= n11_p n3_p))) |-> true
(not (not (= n12_p n3_p))) |-> false
(not (not (= n13_p n3_p))) |-> false
(not (not (= n14_p n4_p))) |-> false
(not (not (= n15_p n4_p))) |-> true
(not (not (= n16_p n4_p))) |-> true
(not (not (= n17_p n5_p))) |-> true
(not (not (= n17_p n8_p))) |-> true
(not (not (= n17_p n11_p))) |-> false
(not (not (= n17_p n14_p))) |-> true
(not (not (= n18_p n5_p))) |-> false
(not (not (= n18_p n9_p))) |-> true
(not (not (= n18_p n12_p))) |-> false
(not (not (= n18_p n15_p))) |-> true
(not (not (= n19_p n5_p))) |-> false
(not (not (= n19_p n10_p))) |-> true
(not (not (= n19_p n13_p))) |-> false
(not (not (= n19_p n16_p))) |-> true
(not (not (= n20_p n6_p))) |-> true
(not (not (= n20_p n8_p))) |-> true
(not (not (= n20_p n13_p))) |-> true
(not (not (= n20_p n15_p))) |-> false
(not (not (= n21_p n6_p))) |-> false
(not (not (= n21_p n9_p))) |-> true
(not (not (= n21_p n11_p))) |-> true
(not (not (= n21_p n16_p))) |-> true
(not (not (= n22_p n6_p))) |-> true
(not (not (= n22_p n10_p))) |-> false
(not (not (= n22_p n12_p))) |-> true
(not (not (= n22_p n14_p))) |-> true
(not (not (= n23_p n7_p))) |-> true
(not (not (= n23_p n8_p))) |-> true
(not (not (= n23_p n12_p))) |-> true
(not (not (= n23_p n16_p))) |-> false
(not (not (= n24_p n7_p))) |-> true
(not (not (= n24_p n9_p))) |-> false
(not (not (= n24_p n13_p))) |-> true
(not (not (= n24_p n14_p))) |-> true
(not (not (= n25_p n7_p))) |-> false
(not (not (= n25_p n10_p))) |-> true
(not (not (= n25_p n11_p))) |-> true
(not (not (= n25_p n15_p))) |-> true
sat
(objectives
 ((+ 0
   (ite (= n1_p n0_p) 0 1)
   (ite (= n2_p n0_p) 0 1)
   (ite (= n3_p n0_p) 0 1)
   (ite (= n4_p n0_p) 0 1)
   (ite (= n5_p n1_p) 0 1)
   (ite (= n6_p n1_p) 0 1)
   (ite (= n7_p n1_p) 0 1)
   (ite (= n8_p n2_p) 0 1)
   (ite (= n9_p n2_p) 0 1)
   (ite (= n10_p n2_p) 0 1)
   (ite (= n11_p n3_p) 0 1)
   (ite (= n12_p n3_p) 0 1)
   (ite (= n13_p n3_p) 0 1)
   (ite (= n14_p n4_p) 0 1)
   (ite (= n15_p n4_p) 0 1)
   (ite (= n16_p n4_p) 0 1)
   (ite (= n17_p n5_p) 0 1)
   (ite (= n17_p n8_p) 0 1)
   (ite (= n17_p n11_p) 0 1)
   (ite (= n17_p n14_p) 0 1)
   (ite (= n18_p n5_p) 0 1)
   (ite (= n18_p n9_p) 0 1)
   (ite (= n18_p n12_p) 0 1)
   (ite (= n18_p n15_p) 0 1)
   (ite (= n19_p n5_p) 0 1)
   (ite (= n19_p n10_p) 0 1)
   (ite (= n19_p n13_p) 0 1)
   (ite (= n19_p n16_p) 0 1)
   (ite (= n20_p n6_p) 0 1)
   (ite (= n20_p n8_p) 0 1)
   (ite (= n20_p n13_p) 0 1)
   (ite (= n20_p n15_p) 0 1)
   (ite (= n21_p n6_p) 0 1)
   (ite (= n21_p n9_p) 0 1)
   (ite (= n21_p n11_p) 0 1)
   (ite (= n21_p n16_p) 0 1)
   (ite (= n22_p n6_p) 0 1)
   (ite (= n22_p n10_p) 0 1)
   (ite (= n22_p n12_p) 0 1)
   (ite (= n22_p n14_p) 0 1)
   (ite (= n23_p n7_p) 0 1)
   (ite (= n23_p n8_p) 0 1)
   (ite (= n23_p n12_p) 0 1)
   (ite (= n23_p n16_p) 0 1)
   (ite (= n24_p n7_p) 0 1)
   (ite (= n24_p n9_p) 0 1)
   (ite (= n24_p n13_p) 0 1)
   (ite (= n24_p n14_p) 0 1)
   (ite (= n25_p n7_p) 0 1)
   (ite (= n25_p n10_p) 0 1)
   (ite (= n25_p n11_p) 0 1)
   (ite (= n25_p n15_p) 0 1)) 16)
)

**Comment by chriswailes** [comment]
Thank you for responding.  After posting this I realized I should have first asked for clarification of the guarantees provided by the optimization engines.  I could have sworn that I had tested this formula using maxres, wmax, and sls and that all three produced the same result, but trying this this morning I'm no longer seeing this behavior, so I guess I didn't do all of my due diligence.

If you don't mind, I have a couple of followup questions:

1. The new encoding that you provided works well for bi-partitioning (partitioning into two sets), but doesn't extend to arbitrary number of partitions.  Do you have a recommendation on how to deal with arbitrary numbers of partitions?

2. Over the weekend my Linux distribution updated Z3.  This new version appears to have some recent patches in it, and now it finds the optimal solution with the first encoding using SLS.  Did a patch land that helped address this issue?  Do I no longer need to use the encoding that you recommended?

3. My goals are to A) get a globally optimal solution and B) do it as quickly as possible.  Which of the maxsat engines is the best to use?

4. Is there a way to parallelize the work being done by either the solver or the maxsat engine?

Thanks again for your help.

**Comment by NikolajBjorner** [comment]
I removed support for SLS because it was bit-rotting and your bug report indicated that it was confusing to use. I also added internal support for translating enumeration types to bit-vectors, so that you can use enumeration sorts in the specification and Z3 internally translates constraints. So in this case you may be able to use an enumeration sort with three values P0, P1, P2. For example. You can use bit-vectors to encode finite domains on your own. 
The default engine, maxres, tends to offer the best support. Your rather small example is surprisingly difficult. If you have additional domain knowledge you may be able to add symmetry breaking predicates to cut out symmetric solutions from the search space. 
There is no internal parallelism in the maxsat solvers. You can run multiple jobs in parallel, of course, as long as you use different contexts.
