### ISSUE TITLE
Make bug

### ISSUE THREAD

**Issue by xebelleDerrel** [Z3Prover/z3#6933]
I building Z3 using make and GCC/Clang following the prescribed steps, but when I executed the make command, I encountered the following bug:
make
process_begin: CreateProcess(NULL, cl /c /nologo /Zi /D WIN32 /D _WINDOWS /EHsc /GS /Gd /std:c++17 /Zi /WX- /O2 /Oy- /D _EXTERNAL_RELEASE /D NDEBUG /D _CONSOLE /D ASYNC_COMMANDS /Gm- /arch:SSE2 /MD -I..\src\api -I..\src\tactic\portfolio -I..\src\tactic\smtlogics -I..\src\ackermannization -I..\src\model -I..\src\ast\macros -I..\src\ast\rewriter -I..\src\ast -I..\src\util -I..\src\math\polynomial -I..\src\math\interval -I..\src\math\automata -I..\src\params -I..\src\solver -I..\src\smt\params -I..\src\tactic -I..\src\ast\simplifiers -I..\src\ast\euf -I..\src\ast\normal_forms -I..\src\ast\rewriter\bit_blaster -I..\src\ast\converters -I..\src\ast\substitution -I..\src\qe\lite -I..\src\qe\mbp -I..\src\math\simplex -I..\src\ast\proofs -I..\src\sat\sat_solver -I..\src\tactic\core -I..\src\ast\pattern -I..\src\parsers\smt2 -I..\src\cmd_context -I..\src\parsers\util -I..\src\tactic\aig -I..\src\tactic\bv -I..\src\tactic\arith -I..\src\sat -I..\src\math\dd -I..\src\math\grobner -I..\src\sat\tactic -I..\src\sat\smt -I..\src\smt -I..\src\smt\proto_model -I..\src\solver\assertions -I..\src\ast\fpa -I..\src\math\lp -I..\src\nlsat -I..\src\nlsat\tactic -I..\src\smt\tactic -I..\src\muz\fp -I..\src\muz\base -I..\src\qe -I..\src\muz\clp -I..\src\muz\transforms -I..\src\math\hilbert -I..\src\muz\dataflow -I..\src\muz\tab -I..\src\muz\rel -I..\src\muz\bmc -I..\src\tactic\fd_solver -I..\src\muz\ddnf -I..\src\muz\spacer -I..\src\tactic\ufbv -I..\src\tactic\fpa -I..\src\tactic\sls -I..\src\math\subpaving\tactic -I..\src\math\subpaving -I..\src\math\realclosure -I..\src\opt -I..\src\cmd_context\extra_cmds -I..\src /Foshell\datalog_frontend.obj ..\src\shell\datalog_frontend.cpp, ...) failed.
How can I solve this problem?

**Comment by NikolajBjorner** [comment]
It is not possible to troubleshoot the issue from this end. 
Based on the information it appears to be external to z3.

**Comment by wintersteiger** [comment]
It's not trying to run GCC/Clang, but `cl`, which is the Visual C/C++ compiler.

**Comment by NikolajBjorner** [comment]
so, presumably cl is not installed.

**Comment by xebelleDerrel** [comment]
ok, thanks
