### ISSUE TITLE
how to sum an array or list of bool in z3py

### ISSUE THREAD

**Issue by zhanghv** [Z3Prover/z3#694]
Hi, I am new to z3py and SMT. I have a constraint like ∑i bi > 10 ,  and i =200, bi is a Boolean value. I want represent this constraint in python , but i don't find any good methods to achieve it.Please help me to resolve this case.Thank you !

**Comment by NikolajBjorner** [comment]
Here are two ways to say ∑i bi <= 10.

s = Solver()
s.add(Sum([If(Bool('b%i' % i),1,0) for i in range(200)]) <= 10)
print s
print s.check()
print s.model()

s = Solver()
s.add(PbLe([(Bool('b%i' % i),1) for i in range(200)], 10))
print s
print s.check()
print s.model()

**Comment by zhanghv** [comment]
Thank you very much.This

**Comment by zhanghv** [comment]
Thank you very much.

**Comment by marcelwa** [comment]
Hi and sorry for commenting on such an old post. I'm currently needing exactly the same functionality but in C++. AFAIK there is no Sum() function for C++. So is there any other solution like the one you described here?

**Comment by NikolajBjorner** [comment]
Do you need "sum" or really "pble"?
I will add this shorthand in the next commit:

    inline expr sum(expr_vector const& args) {
        assert(args.size() > 0);
        context& ctx = args[0].ctx();
        array<Z3_ast> _args(args);
        Z3_ast r = Z3_mk_add(ctx, _args.size(), _args.ptr());
        ctx.check_error();
        return expr(ctx, r);
    }

**Comment by marcelwa** [comment]
I need "sum" and had built a similar function on my own. Thank you so much for adding this shortcut!

**Comment by raghavsood33** [comment]
And how to do that in java?

Following code obviously gives ArrayStoreException at the last line
        ```
        int n=5; //total no of boolean variables
        int k=3; //no of boolean variables needed to be true
        
        Map<String, String> contextmap = new HashMap<>();
        contextmap.put("model", "true");
        contextmap.put("unsat_core", "true");
        Context ctx = new Context(contextmap);
        Solver solver = ctx.mkSolver();
        
        List<BoolExpr> addList = new ArrayList<>(n);
        for (int i = 0; i < n; i++) {
            String varname = "var_" + i;
            addList.add(ctx.mkBoolConst(varname));
        }
        solver.add(ctx.mkEq(ctx.mkAdd(addList.toArray(new ArithExpr[addList.size()])), ctx.mkInt(k)));
```

**Comment by krypt-n** [comment]
You could use a `(ITE bexpr 1 0)` to convert from the BoolExprs to ArithExprs. The Java api currently does not expose mkPbeq, however you can access it via reflection, if you really need to use it.

**Comment by michaela-egger** [comment]
I would need a function in z3 to sum up a list of BoolExpr, is there by now a possibility to use something like mkPbeq in java? 

I tried it like this but I found no possibility to go through the list x inside the mkAdd
` solver.add(ctx.mkEq(ctx.mkAdd((x[k].isTrue() ? ctx.mkInt(1) : ctx.mkInt(0)) , ctx.mkInt(1)));`

(i think in python it can be done like And(x[i]) for i in range (0, length))
