### ISSUE TITLE
Optimization issue 

### ISSUE THREAD

**Issue by nnarek** [Z3Prover/z3#6941]
I want to formalize [this ](https://www.youtube.com/watch?v=2QJ2L2ip32w) riddle and found that the Optimizer returns different values almost every time when I run script․ It should maximize **m** but I get 0 or 1 or 8 values for **m**.
I am using 4.12.2.0 version of z3-solver python module 

```

from z3 import *

m = Int('m')
s = Optimize()
a,b,c = Ints('a b c')
x,y,z = Ints('x y z')
s.add([x>=0,y>=0,z>=0])
t1,t2 = Ints('t1 t2')
possible_values = [a+b+c==30,a>=2,b>=2,c>=2,Exists([t1,t2],And([Or([t1==a,t1==b,t1==c]),Or([t2==a,t2==b,t2==c]),t1==t2+6]))]
s.add(ForAll([a,b,c],Implies(And(possible_values),(If(x<=a,x,0)+If(y<=b,y,0)+If(z<=c,z,0))>=m) ))

s.add(m<30)
s.maximize(m)

print(s.check())
print(s.model())
```

**Comment by NikolajBjorner** [comment]
The warning printed to stderr says:

WARNING: optimization with quantified constraints is not supported

You can roll your own optimization loop to find the largest m below 30 that satisfies the constraints.

```

while True:
    s0 = Solver()
    s0.add(s.assertions())
    is_sat = s0.check()
    if is_sat == unsat:
        break
    if is_sat == unknown:
        print("unknown")
        break
    mdl = s0.model()
    val = mdl.eval(m)
    print(m,"=",val)
    s.add(m > val)
    
```

The reason to create a fresh solver s0 inside the loop is to allow z3 create a custom tactic that works well for the assertions.
