### ISSUE TITLE
ArithRef instance has no attribute '__float__'

### ISSUE THREAD

**Issue by zhanghv** [Z3Prover/z3#696]
Hi, I need a solver for a entropy formula: ∑plog(1/p)>a.My python code is:`from z3 import * import math Sum([(Real('p%s'%j)*math.log(1/Real('p%s'%j),2)) for j in range(20)])>=10`.
When i run this code, there is a AttributeError:ArithRef instance has no attribute '__float__'. It seems z3py does not support math.log. P is a probability value,and it's range is (0,1). How can i represent the p correctly and the whole formula.Any comment is appreciated. Thanks.

**Comment by NikolajBjorner** [comment]
The file z3.py contains the methods for accessing numerals. 
The relevant methods are in the subclass RatNumRef. Of course you cannot retrieve a numeral corresponding to a symbolic expression, unless that expression represents a numeral.
So what you are trying to do here is to create a symbolic expression denoting log(1/p_j). Z3 does not support reasoning with logarithms. At best you can create an uninterpreted function representing logarithm and axiomatize it appropriately.

**Comment by zhanghv** [comment]
Thank you for reply.I have tried other methods.But i stii have no idea how
to represent logatithm  appropriately.I am new to z3, and this problem has
been bothered me for a few days.Could you help me.Thanks anyway.

2016-07-26 1:20 GMT+08:00 Nikolaj Bjorner <notifications@github.com>:

**Comment by NikolajBjorner** [comment]
from z3 import * 
    import math

    log2 = Function('log', RealSort(), RealSort(), RealSort())

   def log(e, basis):
       return log2(e, basis)

   print Sum([(Real('p%s'%j)* log(1/Real('p%s'%j),2)) for j in range(20)])>=10
