### ISSUE TITLE
Version identifier for development versions

### ISSUE THREAD

**Issue by PhilippWendler** [Z3Prover/z3#697]
We use Z3 in a version that is always compiled from a recent git revision instead of a stable release. It would be convenient for us if a Z3 (library) binary could provide more precise information about its version, such that we can for example check whether we actually used the desired version from our log afterwards. Currently, Z3 reports the version "4.4.2.1", which does not point to a specific commit.

Many projects use a version string that is based on `git describe`, which is very convenient (currently this would be `z3-4.4.1-1594-g56c7875`). It contains the name of the latest stable release, it is globally unique because of the git hash, and strictly monotone in many use cases (as long as always building from master), because the `1594` is the number of commits since the `z3-4.4.1` tag. It would be great if Z3 could report this or a similar string.

I found the `--githash` parameter for the build system, which seems to accept not only hashes, but arbitrary strings, so I could simply always build Z3 with `--githash=$(git describe)`. Unfortunately, however, I did not find a way to retrieve this string via the API. It seems to be reported only when calling `z3 -h`. So one solution would be to add an API function for retrieving this string.

**Comment by wintersteiger** [comment]
That sounds like a good idea. We have `--githash` to include the commit hash in the binary version, but the API doesn't provide that information yet. In smt2 files we can also get it via `(get-info :version)`.

Git hashes seem to be too long to fit into an unsigned, so we probably can't push that into the revision number in `Z3_get_version` and we'll instead need a new function.

**Comment by wintersteiger** [comment]
This is now done, I added a function called `Z3_get_full_version` which returns a long string with all the necessary information (as of 3587baaf24e001e3d88d49395357a826f743a189).
