### ISSUE TITLE
Any reason why pypi does not have version 4.12.3 ?

### ISSUE THREAD

**Issue by pcarbonn** [Z3Prover/z3#6987]
[pypi](https://pypi.org/project/z3-solver/) currently has 4.12.2.

**Comment by NikolajBjorner** [comment]
the current release is 4.12.2. The working master branch is 4.12.3. It is not released. See the github release bar on the right of the page https://github.com/Z3Prover/z3. You will find the current release. It says 4.12.2 and not 4.12.3.
