### ISSUE TITLE
Z3 sometimes does not surround sort names containing double-quotes with | | in SMTLIB

### ISSUE THREAD

**Issue by ryandancy** [Z3Prover/z3#6989]
I'm running Z3 version 4.12.2 - 64 bit.

I would expect that every time Z3 prints out SMTLIB (e.g. from `(get-model)`), it would quote identifiers containing `"` with `| |`, e.g. `|S"|`. Usually it does so, but it appears not to at least in `define-fun` declarations.
```
(declare-datatypes () ((|S"| s1)))
(declare-fun p (|S"|) Bool)
(check-sat)
(get-model)
```
Running Z3 on the above model produces the following:
```
sat
(
  (define-fun p ((x!0 S")) Bool
    false)
)
```
`S"` is unquoted in the function definition, which causes my SMTLIB parser to choke.

**Comment by NikolajBjorner** [comment]
@CEisenhofer  already fixed this in the current master
