### ISSUE TITLE
Wrong bias returned for denormal floating point numbers

### ISSUE THREAD

**Issue by martin-neuhaeusser** [Z3Prover/z3#699]
The attached [example](https://github.com/Z3Prover/z3/files/388462/fp_bias.zip) constructs the largest denormal 32 bit floating point number and checks the returned exponent with Z3's API functions, e.g. with Z3_fpa_get_numeral_exponent_string. 

As a 32bit FP has a bias of 127, we'd expect to receive -127; however, Z3 returns -126. If we use an exponent of 2 (as a counter-check), we correctly receive -125.

As far as we have looked into the code, there seems to be a special case in [api_fpa.cpp](https://github.com/Z3Prover/z3/blob/b7de813c6386a5625c5570c99d8daf0b00e245f8/src/api/api_fpa.cpp#L1025), where mk_min_exp is used to compute the exponent for denormal numbers. However, [that computation](https://github.com/Z3Prover/z3/blob/b7de813c6386a5625c5570c99d8daf0b00e245f8/src/util/mpf.cpp#L1742-L1746) seems to correctly compute the result first, and then adds another 1; at least, we cannot see the reason for doing that last addition.

**Comment by wintersteiger** [comment]
Our mpf numbers don't use a biased representation for exponents, which is why the code looks a bit different. Will be an easy fix though.

**Comment by martin-neuhaeusser** [comment]
This is a bit unrelated, but nevertheless:

Could you perhaps provide an API function that allows to obtain the significand of a floating point numeral as an integer string whose binary representation equals the significand's bits? This would help the user in interpreting floating point numerals via the API and (as far as I have seen) such a function is missing: 
* get_numeral_significand_string returns a string with the real number and 
* get_numeral_significand_uint64 is limited to at most 64 bits...

Currently when we read back FP numerals from Z3's API, we have to resort to extracting the binary representation of the significand from the string obtained by Z3.Expr.to_string - which is inefficient and somehow ugly.

**Comment by wintersteiger** [comment]
Just to make sure I understand you: Do you want an array of 8-bit characters '0' and '1', or do you want an big-integer representation, i.e., an array of 32-bit values, each bit representing one bit of the significand?

**Comment by wintersteiger** [comment]
Getting back to the original problem: the bias for 32-bit floats is 127, but the exponent of denormal 32-bit floats is -126 (see e.g. [Wikipedia](https://en.wikipedia.org/wiki/Single-precision_floating-point_format)), so I think Z3 is right here. Note that the significand is 0.x, i.e., this is not normalized.

**Comment by martin-neuhaeusser** [comment]
@wintersteiger: You (and Z3) are right, there is no off-by-one error. Sorry again!

I guess I got confused as I expected Z3's API functions get_numeral_exponent_string and get_numeral_exponent_int to return an integer whose binary representation matches that of the IEEE 754 exponent bits. However, if I understand correctly, the API functions instead return the integer which may serve as the exponent in deriving the actual real value.

The two are nearly the same - apart from the transition from normal to denormal numbers. For very small normals, both have a "mathematical" exponent of -126 (for 32 bit floats), as you stated. However, in the binary IEEE 754 format, these two cases differ: Denormals have only zero bits in the exponent field, whereas small normals have one as an exponent. This is where I got trapped - I expected to receive -127 (with bias) or 0 (without bias) for denormals. But not -126.

That brings me back to my previous remark: For us, it would be very nice to have API functions that allow to extract the IEEE 754 bit-wise representation of a floating point numeral. That would allow us to use results obtained from Z3 in our own IEEE 754 softfloat library directly, i.e. without having to first convert into an arbitrary precision Q and then back to IEEE 754... 

Something like get_exponent_bits and get_significand_bits both taking a floating point numeral and returning a string containing an unsigned decimal whose binary representation matches that of the IEEE 754 encoding would be great:

Example:
get_exponent_bits (fp #b0 #b00000000 #b11111111111111111111111) = "0"
get_exponent_bits (fp #b0 #b00000001 #b11111111111111111111111) = "1"
get_exponent_bits (fp #b0 #b00000011 #b11111111111111111111111) = "3"
get_significand_bits (fp #b0 #b00000001 #b11111111111111111111111) = "8388607"

What do you think? I would volunteer and try to implement these, provided you think that such functions make sense.

**Comment by martin-neuhaeusser** [comment]
That sounds very good. For us, the most important information is the bit-wise contents of the exponent. A function such as Z3_fpa_get_numeral_exponent that returns the bitvector (as a Z3_ast) of the exponent part of the IEEE754 value would be great. It would allow us to distinguish between small normals with exponent -126 and subnormals.

Of course, an analogous function for extracting the significand bits (such as the above Z3_fpa_get_numeral_significand) would be nice as well. Together, they could complement the mk_fp function.

**Comment by wintersteiger** [comment]
Alright, this is now added in PR #760. It's not tested at all, so I won't merge it yet. Testing on your end (e.g., the ML parts) highly appreciated if you have time!

**Comment by martin-neuhaeusser** [comment]
Thanks a lot for the changes! 

I just read the comments of the new API functions and have a minor question:
I would have expected that NaN numerals raise exceptions, as their IEEE 754 bit-representation is not uniquely determined (their sign and significand bits remain under-specified). However, I do not see why +inf and -inf are underspecified, as well? According to the floating point paper ("An automatable formal semantics for IEEE-754 floating-point arithmetic"), +inf and -inf have a significand that consists entirely of 0 bits and an exponent with only 1 bits (see Sec. V.A, p. 7).

How could one detect a NaN numeral? Shouldn't we introduce another API function for that case (i.e. something like is_nan_numeral)? Otherwise, we have to rely on, e.g. catching exceptions of get_numeral_sign_bv to detect the NaN case.

We are going to adapt our Z3 layer to the new API and report back as soon as we have some test results.

**Comment by wintersteiger** [comment]
Hmm, NaNs do raise exceptions; see:

    ...
    is_app_of(e, fid, OP_FPA_NAN)) {  
    SET_ERROR_CODE(Z3_INVALID_ARG);
    ...

Is there anything else that is unclear or contradicts this?

I just checked the semantics paper and I agree, it should be in line with that to return all-zero and all-one bit-vectors for +/-oo. 

I suppose it would be OK to add a function to check for NaN numerals. It's not strictly required, but will make it easier to use.

**Comment by martin-neuhaeusser** [comment]
I agree; while not necessary, having a function to test if a FP numeral is NaN would make the API easier to use.

**Comment by wintersteiger** [comment]
Done, but completely untested so far.

**Comment by wintersteiger** [comment]
Continued in PR #760, so I'm closing this issue.
