### ISSUE TITLE
fp.rem should produce NaN for 0/0 

### ISSUE THREAD

**Issue by LeventErkok** [Z3Prover/z3#70]
For the following benchmark:

```
(set-option :produce-models true)
(set-logic QF_FP)
(define-fun zero () (_ FloatingPoint 11 53) (_ +zero 11 53))
(declare-fun s0 () (_ FloatingPoint 11 53))
(assert (= s0 (fp.rem zero zero)))
(check-sat)
(get-value (s0))
```

Z3 responds:

```
sat
((s0 (_ +zero 11 53)))
```

i.e., `0` as the remainder of division of `0` by `0`. I do believe the correct result should be `NaN`

**Comment by wintersteiger** [comment]
Is this based on assumption, or is there a document clearly stating that? I skimmed over the relevant parts of IEEE754 which says that the result should be a quiet NaN (Sec 7.2), so that's what I changed to implementation to. The current SMT theory definition isn't clear about this though, so I'll get one of the semantics people to look at this.

**Comment by LeventErkok** [comment]
It's based on the semantics given in http://smt-lib.org/papers/BTRW14.pdf, towards the end of section 4.c.

Well, I should say, it's based on "my understanding" of the definition in there, it says:

```
remε,σ : RM × Fε,σ × Fε,σ → Fε,σ
remε,σ(rm, f, g) = f                            if  g ∈ FIε,σ
                   NaN                          if  f ∈ FIε,σ ∪ {NaN}
                   NaN                          if  g ∈ FZε,σ ∪ {NaN}
                   rnd(v, rm, isNeg(f), x)      if  x = v(f) − (v(g) ∗ y),
                                                    y = rnd(in, rm, 0, v(f)/v(g))
```

Here, f = g = +0. So, The last clause would kick in; and y would be NaN. Thus, x would be NaN. And rounding it again would give us a NaN. Am I reading this correctly?

I remember you mentioning there might be some changes to this document as well; but I'm assuming this one would remain the same.

**Comment by wintersteiger** [comment]
Yes, there will be changes, but I'm expecting them to only make things clearer, not to drastically change anything. I've asked them to clarify this particular issue as well.

**Comment by wintersteiger** [comment]
This is now also in unstable, so I'm closing the issue.
