### ISSUE TITLE
Segfault in Solver#toString in java binding

### ISSUE THREAD

**Issue by BossyMr** [Z3Prover/z3#7000]
Whilst debugging a program, the program crashes with the following error:

```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x00007ffc11698fd3, pid=3008, tid=25240
#
# JRE version: OpenJDK Runtime Environment JBR-17.0.6+10-829.5-jcef (17.0.6+10) (build 17.0.6+10-b829.5)
# Java VM: OpenJDK 64-Bit Server VM JBR-17.0.6+10-829.5-jcef (17.0.6+10-b829.5, mixed mode, tiered, compressed oops, compressed class ptrs, g1 gc, windows-amd64)
# Problematic frame:
# C  [libz3.dll+0xbc8fd3]
#
# No core dump will be written. Minidumps are not enabled by default on client versions of Windows
#
# If you would like to submit a bug report, please visit:
#   https://youtrack.jetbrains.com/issues/JBR
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#

---------------  T H R E A D  ---------------

Current thread (0x000001aa3a6147c0):  JavaThread "AWT-EventQueue-0" [_thread_in_native, id=25240, stack(0x0000009b5b900000,0x0000009b5ba00000)]

Stack: [0x0000009b5b900000,0x0000009b5ba00000],  sp=0x0000009b5b9fc228,  free space=1008k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
C  [libz3.dll+0xbc8fd3]

Java frames: (J=compiled Java code, j=interpreted, Vv=VM code)
j  com.microsoft.z3.Native.INTERNALsolverToString(JJ)Ljava/lang/String;+0
j  com.microsoft.z3.Native.solverToString(JJ)Ljava/lang/String;+2
j  com.microsoft.z3.Solver.toString()Ljava/lang/String;+11
j  com.intellij.rt.debugger.BatchEvaluatorServer.evaluate([Ljava/lang/Object;)Ljava/lang/String;+44

```

The Solver instance prior to it crashing resembles the following:

```

(declare-fun k!0 () (_ FloatingPoint 8 24))
(declare-fun k!1 () (_ FloatingPoint 8 24))
(declare-fun k!2 () (_ FloatingPoint 8 24))
(declare-fun null () RoundingMode)
(declare-fun k!3 () (_ FloatingPoint 8 24))
(declare-fun k!4 () (_ FloatingPoint 8 24))
(assert (= k!0 (_ +zero 8 24)))
(assert (= k!1 (fp #b0 #x7f #b00000000000000000000000)))
(assert (= (fp.gt k!2 (_ +zero 8 24)) true))
(assert (= k!3 (fp.mul null k!2 k!1)))
(assert (= k!4 (fp.sub null k!3 (fp #b0 #x7f #b00000000000000000000000))))
(assert (= (fp.gt k!4 (_ +zero 8 24)) true))

```

The last call to the solver is Solver#check(), which succeeds, since the cursor is seen jumping to the next instruction. However, the program crashes immediately after since the debugger tries to call Solver#toString().

The dll is built manually using the instructions in the projects README using the latest commit on master (Z3 4.12.3.0). The exact commit is unkown, but the file was built on the 14th of September, so it's most probably commit cbad61ba2e157b86abaf03dfb4db0d3c912f5988.

**Comment by BossyMr** [comment]
The same error also occurs when calling Model#toString()

`Java frames: (J=compiled Java code, j=interpreted, Vv=VM code)
j  com.microsoft.z3.Native.INTERNALmodelToString(JJ)Ljava/lang/String;+0
j  com.microsoft.z3.Native.modelToString(JJ)Ljava/lang/String;+2
j  com.microsoft.z3.Model.toString()Ljava/lang/String;+11`

**Comment by NikolajBjorner** [comment]
typically these bugs are due to stale library/header paths from older versions of z3.

**Comment by NikolajBjorner** [comment]
This does not reproduce for me. Steps:
- download nightly https://github.com/Z3Prover/z3/releases/tag/Nightly
- unzip
- copy over https://github.com/Z3Prover/z3/blob/master/examples/java/JavaExample.java
- javac -cp com.microsoft.z3.jar JavaExample.java
- java -cp com.microsoft.z3.jar;. JavaExample

JavaExample contains multiple uses of pretty printing Solver objects.
