### ISSUE TITLE
Integration Issue: Z3 Solver Warning in Hardhat Compilation on OpenSUSE Leap 15.4

### ISSUE THREAD

**Issue by MaryemHadjWannes** [Z3Prover/z3#7005]
When I execute the command `` **npx hardhat compile** `` on my Linux OpenSUSE Leap 15.4 system, I encounter the following warning:

`` Warning: Solver z3 was selected for SMTChecker but it is not available. libz3.so.4.11 was not found. ``

Despite having **Z3** installed with **version 4.12.1 (64-bit)**, it appears that the required library **libz3.so.4.11** is not found. This discrepancy is causing the warning to be displayed. I seek assistance in resolving this issue and ensuring the correct integration of Z3 for SMTChecker in the Hardhat compilation process.

**Comment by NikolajBjorner** [comment]
This is not the right place to file the issue. You mention a tool that depends on z3. I can't support their compilation processes.
