### ISSUE TITLE
Suggestion: short-circuit `and` and `or` operators when of the operators is a constant

### ISSUE THREAD

**Issue by cheshire** [Z3Prover/z3#701]
Hi,

I suggest adding the following trivial transformation when creating disjunctions and conjunctions when one argument is a boolean constant:
- `and(x, true) -> x`
- `and(x, false) -> false`
- `or(x, true) -> true`
- `or(x, false) -> x`

Many other solvers do it already, and I think such a transformation is:
- very cheap.
- allows for nicer introspection: currently without (sometimes very expensive) simplification there is no easy way to check that the formula `and(true, true, true, true)` is just `true`.
- creates more human-readable formulas in the end, omitting redundant information.

I can try to write a pull request if this is a good idea.

**Comment by NikolajBjorner** [comment]
We tried in a separate branch to add an option to apply one-step rewriting for all term constructors. 
The takeaway was that this somehow slowed down the application we were interested in tuning so we didn't integrate this feature.

You may find src/ast/ast_util.h or src/ast/rewriter/bool_rewriter useful in the case of and/or simplification.

**Comment by cheshire** [comment]
Are you still interested in tuning that said application? Do you mean more general rewriting, or the specific rules above, applied in the constructor? It's practically a couple of machine instructions overhead.

**Comment by NikolajBjorner** [comment]
@nunoplopes - what do you think (and Happy birthday)?

**Comment by nunoplopes** [comment]
Thanks; sorry for the delay.
I think that keeping the structure of the formula without simplifications by default is a good thing, and some applications need to preserve this syntactic structure.
However, I'm all for having an option that knows about local simplifications.  All serious applications are all duplication this effort (simplifying arith as well, such as a+0, a*0, cannonicalizing expresions, etc). All my applications do this.

The effort that Nikolaj mentioned that failed was maybe doing too much. It was running the whole theory rewriter on the new expression, as far as I remember.  We probably need something in between.
What I don't support is a feature that *only* knows how to do the simplifications proposed here; it would be fairly useless.

**Comment by cheshire** [comment]
@nunoplopes Thanks for your reply! Not sure what do you mean by an "option": do you mean auto-transformation (as soon as the formula is created) or a tactic?
I was suggesting the former.

I agree that grouping trivial O(1) local simplifications makes sense, but I'm not in a position to now all of those.
We do find the simplification proposed in the first post very useful, as it:

 - Makes resulting formulas much smaller and more readable.
 - Makes "isTrue" and "isFalse" testing much easier.
 - Speeds up the traversal for visitors.

All other solvers we have tried perform this simplification, and some others.
In any case, feel free to close, we can just implement it on our level.

**Comment by nunoplopes** [comment]
I meant at creation time, yes.  By option I meant a configuration option at the context/global level so that it is opt-in.
