### ISSUE TITLE
Incorrect model involving array and quantifiers

### ISSUE THREAD

**Issue by facanferff** [Z3Prover/z3#702]
Hi, I'm currently working on a testing tool that makes use of Z3 to generate models that respect several constraints.
I found that when trying to generate models that contain arrays (of Int to any sort) Z3 fails to provide a model, returning as status UNKNOWN and giving as the reason "incomplete quantifiers" however, it seems to generate a model almost correct, with just a slight error.

For instance, imagine the scenario in which I want to generate a model that contains an array of integers in increasing order of length at least 4 and whose elements are greater than 0, smaller than 40 and multiple of 8. When looking on these constraints we see there is just one possible solution (i.e. [8, 16, 24, 32]).

The code I have is the following:

```
(set-option :produce-proofs true)

(declare-datatypes () ((ArrayWithLength.Int (ArrayWithLength.Int_IT (items (Array Int Int)) (length Int)))))
(declare-datatypes () ((Test (Test_IT (array_integer ArrayWithLength.Int)))))
(declare-fun R.request.body () Test)
(assert (let ((a!1 (forall ((i Int))
             (let ((a!1 (and (< 0 i)
                             (< i (length (array_integer R.request.body)))))
                   (a!2 (< (select (items (array_integer R.request.body))
                                   (- i 1))
                           (select (items (array_integer R.request.body)) i))))
               (and (=> a!1 a!2) (>= (length (array_integer R.request.body)) 0)))))
      (a!2 (forall ((__i_1__ Int))
             (let ((a!1 (and (<= 0 __i_1__)
                             (< __i_1__ (length (array_integer R.request.body)))))
                   (a!2 (> (select (items (array_integer R.request.body))
                                   __i_1__)
                           0))
                   (a!3 (< (select (items (array_integer R.request.body))
                                   __i_1__)
                           40))
                   (a!4 (mod (select (items (array_integer R.request.body))
                                     __i_1__)
                             8)))
               (=> a!1 (and a!2 a!3 (= a!4 0)))))))
  (and (>= (length (array_integer R.request.body)) 4) a!1 a!2)))

(check-sat)
(get-info :reason-unknown)
(get-model)
```

(set-option :produce-proofs true) is there so when running in command line Z3 returns a model with (get-model).

ArrayWithLength.Int is a datatype I created so I can control the length of the array, I know Array is an infinite structure but in this way when reading the generated model I know the array is of a specific length (I'm considering indexing starts at 0).

When running that in command line Z3 returns:

```
 unknown
 (:reason-unknown (incomplete quantifiers))
 (model 
   (define-fun R.request.body () Test
     (Test_IT (ArrayWithLength.Int_IT (_ as-array k!4999) 4)))
   (define-fun k!4999!5001 ((x!0 Int)) Int
     (ite (= x!0 2) 24
     (ite (= x!0 1) 16
     (ite (= x!0 0) 8
     (ite (= x!0 3) 32
       24)))))
   (define-fun k!5000 ((x!0 Int)) Int
     (ite (>= x!0 1) (ite (>= x!0 3) 3 1) 0))
   (define-fun k!4999 ((x!0 Int)) Int
     (k!4999!5001 (k!5000 x!0)))
```

When looking in the generated model k!4999!5001 seems absolutely correct (the important indexes for me 0 to 3 map to the expected integers, other indexes return to 24, that is no problem for me, I just ignore all those indexes outside 0 to 3).
The problem is k!5000 which is used to map the index I provide when I want to obtain the value at a specific index into a different index, that is no problem, but (ite (>= x!0 3) 3 1) is the problem, it is saying that all indexes greater than or equal to 3 will just point to 3 (absolutely ok) but the else says that all indexes between [1, 3[ will point into 1 (e.g. the function will make 2 map to 1) which in this scenario would return me the array [8, 16, 16, 32] which is incorrect.

Please note that the first code I generated using the Java API of Z3.

Note: I'm using the commit cb2d8d21071b9e895158adc4b0a3e8dd052e41a4 of master branch.

May you provide some feedback about this? Am I doing something wrong or is it a bug of Z3?

**Comment by NikolajBjorner** [comment]
Sorry, when Z3 returns "unknown" the result of retrieving a model is almost never going to be a model of the formulas. Z3 only claims that models satisfy the constraints when it returns SAT.
