### ISSUE TITLE
Invalid model for str.replace "" with symbolic src and dst

### ISSUE THREAD

**Issue by tlringer** [Z3Prover/z3#703]
This again may be something not yet supported, but I figure I will submit this regardless, since I don't see anything about the limitations of str.replace in the documentation.

The following, which (by the typical semantics of string replace methods) should be unsat, is apparently sat and gives me an invalid model:

```
(set-option :model_validate true)

(declare-fun c0 () String)
(declare-fun c1 () String)
(define-fun e2 () String (str.replace "" c0 c1))
(assert (not (= "" e2)))
(check-sat)

(get-model)
```

```
sat
(error "line 7 column 10: an invalid model was generated")
(model 
  (define-fun c0 () String
    "")
  (define-fun c1 () String
    "!0!")
)
```

In case it's informative: Similar queries which should be satisfiable give me the same model, which looks like a consequence of a bug in string generation again, similar to the [contains bug we saw earlier](https://github.com/Z3Prover/z3/issues/684):

```
(set-option :model_validate true)

(declare-fun c0 () String)
(declare-fun c1 () String)
(define-fun e2 () String (str.replace "a" c0 c1))
(assert (not (= "a" e2)))
(check-sat)

(get-model)
```

```
sat
(model 
  (define-fun c0 () String
    "")
  (define-fun c1 () String
    "!0!")
)
```

This model works for this query, but it looks like it may be another bug in model generation from what we saw earlier.

**Comment by tlringer** [comment]
Here is another query that produces an invalid model:

```
(set-option :model_validate true)

(declare-fun c0 () String)
(declare-fun c1 () String)
(define-fun e2 () String (str.++ c0 c1))
(define-fun e3 () String (str.replace c1 "" c0))
(assert (not (= e2 e3)))
(check-sat)

(get-model)
```

```
sat
(error "line 16 column 10: an invalid model was generated")
(model 
  (define-fun c0 () String
    "!0!")
  (define-fun c1 () String
    "\x00\x00")
)
```

**Comment by NikolajBjorner** [comment]
Thanks, Seems I am not axiomatizing str.replace appropriately.
I presume it should require:

  (str.replace "" X Y) = ""
  
  (str.replace X "" Y) = X

The first equality is now enforced, the second not yet.

**Comment by tlringer** [comment]
Out of curiosity, what is the treatment when you have the following:

(str.replace "" "" X)

I'm not sure if this is documented - but should this be "" or X?

**Comment by NikolajBjorner** [comment]
At this point I have the following:
    (str.replace "" b c) = ""
    (str.contains b c) or (str.replace a b c) = a
    (str.replace a "" c) = a
    ~(str.contains b c) or a = "" or b = "" or exists x y, a = xby and (str.replace a b c) = xcy and ~(str.contains b (str.++ x (str.extract b 0 (str.length b)-2)))

The smt-ization initiative has:

  ; Replace 
  ; (str.replace s t t') is the string obtained by replacing the first occurrence 
  ; of t in s, if any, by t'. Note that if t is empty, the result is to prepend
  ; t' to s.
  ; Total
  (str.replace String String String String)

   o (str.replace String String String String)

     [[str.replace]](w, w1, w2) is the (unique) word w' such that 
     for some u1, u2
     - w  = u1w1u2
     - w' = u1w2u2
     - |u1| is minimal
     if [[str.contains]](w, w1) = true

     [[str.replace]](w, w1, w2) = w  if [[str.contains]](w, w1) = false

Thus, I currently use a different definition and the smtization draft is consistent with what you describe for Racket. I will therefore change the semantics in Z3 to align with the smtization description once I understand how to do it in a reasonable way.

**Comment by NikolajBjorner** [comment]
Semantics of replace has been changed to be consistent with smtization 76cf28d..d74e618
