### ISSUE TITLE
Unexpected divergence on String Theory + UF + Linear Arithmetic

### ISSUE THREAD

**Issue by nikivazou** [Z3Prover/z3#704]
Hello, I run z3 on the following file and it diverges: 

http://goto.ucsd.edu/~nvazou/tmp/string_diverge.smt2

I should not diverge thought as it only uses Strings + UF + Linear Arithmetic. 
More strangely, when I started simplification of the file I just renamed the binder `VV$35$$35$F$35$$35$4` to `ll` and `z3` quickly answered immediately (instead of diverging as before).

**Comment by NikolajBjorner** [comment]
This is now solved very quickly.
