### ISSUE TITLE
Arm64 binaries for Windows

### ISSUE THREAD

**Issue by Xazax-hun** [Z3Prover/z3#7050]
It would be nice to have binaries for arm64 windows.

**Comment by NikolajBjorner** [comment]
I would need help to accomplish this.
The current release pipelines for Windows binaries uses a brittle set of scripts that have not been ported/tested for Windows ARM64. A better way is to use cmake, where target architecture configurations are handled more systematically.

There is a GitHub action for building debug builds of Z3 here:
https://github.com/Z3Prover/z3/actions/workflows/Windows.yml

The script currently used for Windows releases is here:
https://github.com/Z3Prover/z3/blob/master/scripts/mk_win_dist.py

It is invoked from:
https://github.com/Z3Prover/z3/blob/master/scripts/build-win-signed.yml

which is invoked from 
https://github.com/Z3Prover/z3/blob/master/scripts/release.yml

The script mk_win_dist.py predates pipelines / actions.
It would be more useful, it seems, to port mk_win_dist.py to a pipeline (such as move functionality to build-win-signed.yml).

To accomplish this requires some competencies and patience in moving stuff around with pipelines and bandwidth.
It isn't something I particularly excel at and therefore z3 would greatly benefit from contributions to on this front.

**Comment by NikolajBjorner** [comment]
ARM binaries are now available in nightly builds: https://github.com/Z3Prover/z3/releases/tag/Nightly

**Comment by NikolajBjorner** [comment]
latest release includes ARM64 Windows.
https://github.com/Z3Prover/z3/releases/download/z3-4.12.6/z3-4.12.6-arm64-win.zip
