### ISSUE TITLE
Proofs without Abbreviation

### ISSUE THREAD

**Issue by Ceilican** [Z3Prover/z3#706]
Z3's proofs contain many subformula abbreviations, through let statements that introduce new names of the form "$x..." . While this has the advantage of making the proof more compact, it also has the disadvantage of making the proof harder for humans to read. Is there an option to disable these abbreviations in the proof production? If not, could you implement it?

**Comment by NikolajBjorner** [comment]
I added an option to let you see somewhat nicer terms:
             z3 <file>.smt2 pp.pretty-proof=true
