### ISSUE TITLE
Incorrect result for (^ x 0.0) with positive x

### ISSUE THREAD

**Issue by dstaple** [Z3Prover/z3#707]
The following input returns `unsat` with Z3 4.4.1, but `sat` with master:
```
(declare-fun x () Real)
(declare-fun y () Real)
(assert (> x 0.0))
(assert (= y (^ x 0.0)))
(assert (distinct y 1.0))
(check-sat)
```

The model should be `unsat`, given the fact that `x` is positive.  This regression was introduced with this bugfix https://github.com/Z3Prover/z3/commit/035f2bb0dae81519e550a9c865c2aab93eac2dc2.  The issue is that the y.is_zero() case in purify_arith_tactic::process_power is currently only applied if `(y.is_zero() && complete())`, which causes a fall-through in the case that `y.is_zero()` is true but `complete()` is false.

Based on the way a similar problem with even root handling was changed in https://github.com/Z3Prover/z3/commit/ee0dbf34f0d1bbded0512aef5168ea8c92e30df0, my guess is that the fix for should look like this: https://github.com/dstaple/z3/commit/87b767424582b08b7df6814e12c5d96e29227164.  If this is correct, let me know and I'll put in a pull request and submit a regression test.

**Comment by dstaple** [comment]
This was resolved with https://github.com/Z3Prover/z3/issues/708 and https://github.com/Z3Prover/z3test/issues/7

**Comment by NikolajBjorner** [comment]
Thanks!
