### ISSUE TITLE
/usr/local/include/z3++.h:2458: error: undefined reference to 'Z3_is_seq_sort'

### ISSUE THREAD

**Issue by XiaoXiaofanzi** [Z3Prover/z3#7072]
/usr/local/include/z3++.h:2458: error: undefined reference to 'Z3_is_seq_sort'
/usr/local/include/z3++.h:2460: error: undefined reference to 'Z3_mk_seq_concat'
/usr/local/include/z3++.h:1743: error: undefined reference to 'Z3_mk_re_union'
/usr/local/include/z3++.h:2462: error: undefined reference to 'Z3_is_re_sort'
/usr/local/include/z3++.h:2464: error: undefined reference to 'Z3_mk_re_concat'

Z3 version 4.10.1 - 64 bit

**Comment by NikolajBjorner** [comment]
You need to synchronize the versions of your headers and libz3.dll files. Check your path settings.
