### ISSUE TITLE
How to reduce the size of the generated dynamic library file libz3.dll

### ISSUE THREAD

**Issue by xebelleDerrel** [Z3Prover/z3#7078]
I now use z3 constraint solver to do some aspect of the application, due to the file size limit, normal situation to the generated libz3 .dll file is too large, can not meet my system needs, I want to achieve my purpose by removing the unused functions in the library, I am currently just using some functions in the C/C++ api, because I am not very familiar with z3 as a whole, I hope to give me a specific suggestion how to delete the library file, or is there a better idea to provide me

**Comment by NikolajBjorner** [comment]
this is not supported
