### ISSUE TITLE
Wrong or no results on reversing xorshift128+

### ISSUE THREAD

**Issue by LeoUschi232** [Z3Prover/z3#7079]
Given the xorshift128+ algorithm for generating random values, which uses 2 internal states to do so, the solver either does not or incorrectly solves a set of 2 constraints. You can reproduce my issue using the python code:

```
from z3 import *


def to_int64(x):
    return x & 0xffffffffffffffff


def xorshift_manual(p0, p1):
    return to_int64(p1 + ((((p0 ^ to_int64(p0 << 23)) ^ ((p0 ^ to_int64(p0 << 23)) >> 17)) ^ p1) ^ (p1 >> 26)))


def xorshift128plus():
    global state0
    global state1
    local0 = state1
    local1 = state0
    state0 = local0
    local1 = local1 ^ to_int64(local1 << 23)
    local1 = local1 ^ (local1 >> 17)
    local1 = local1 ^ local0
    local1 = local1 ^ (local0 >> 26)
    state1 = local1
    return to_int64(state0 + state1)


# Start here
state0 = 1
state1 = 2
for i in range(10):
    xorshift128plus()
print(state0)
print(state1)
x1 = to_int64(state0 + state1)
x2 = xorshift_manual(state0, state1)


s0 = BitVec("s0", 64)
s1 = BitVec("s1", 64)
solver = Solver()

solver.add(s0 + s1 == x1)
solver.add(xorshift_manual(s0, s1) == x2)
solver.add(s0 >= 0)
solver.add(s1 >= 0)

if solver.check() != sat:
    print("No solution found")
    exit(-1)
model = solver.model()
result0 = model[s0].as_long()
result1 = model[s1].as_long()
print(result0)
print(result1)
if result0 != state0:
    print("state0 not reproduced")
if result1 != state1:
    print("state1 not reproduced")
```

The solver should be able to calculate the state state0 and state1 backwards from the variables x1 and x2. However, depending on the original states, it either gives a wrong result or none at all.

At the time of the issue I was using: z3-solver version 4.12.4.0
My operating system is: Arch Linux x86_64

**Comment by LeventErkok** [comment]
This is a common gotcha in z3py bindings. `>>` is arithmetic shift-right. For logical shift-right, you should use `LShR`. See https://z3prover.github.io/api/html/namespacez3py.html#a6bffa9a3debf2b93f9407ee7eced222f
