### ISSUE TITLE
How to set time limit for Z3_tactic_apply(ctx(), m_tactic, g) function?

### ISSUE THREAD

**Issue by ArpitaDutta** [Z3Prover/z3#7091]
I have the following z3 expr: 
```
z3::expr e = (let ((a!1 (* a132 (+ (- 27340) (rem (* a109 a132) 14999)))))
(let ((a!2 (div (+ (- 26000) (* 10 (rem a!1 14999))) 9)))
  (and (= 2 c) (<= a!2 3347))))
```

On trying to solve this expression with "ctx-solver-simplify" tactic, every time the process got stuck and ultimately need to kill that.
So is there any way to give a time bound to the `Z3_tactic_apply(ctx(), m_tactic, g) function`?

**Comment by NikolajBjorner** [comment]
There is

    /**
       \brief Return a tactic that applies \c t to a given goal for \c ms milliseconds.
       If \c t does not terminate in \c ms milliseconds, then it fails.

       def_API('Z3_tactic_try_for', TACTIC, (_in(CONTEXT), _in(TACTIC), _in(UINT)))
     */
    Z3_tactic Z3_API Z3_tactic_try_for(Z3_context c, Z3_tactic t, unsigned ms);
