### ISSUE TITLE
Performance regression on NIA

### ISSUE THREAD

**Issue by merlinsun** [Z3Prover/z3#7094]
Hi,
For this following instance, z3 https://github.com/Z3Prover/z3/commit/d2706bab649b966170189d25090284c21cce7186 fails to provide an answer within the timeframe of 120 seconds, while z3 4.8.1 yields `unsat` quickly.
```
$ cat small.smt2
(declare-fun v () Int)
(assert (forall ((V Int)) (= 0 (ite (= 1 (mod 7 V)) 1 0))))
(assert (= 0 (ite (= 1 (+ v v (mod 0 0))) 1 0)))
(assert (= 0 (ite (= 0 (mod 1 v)) 1 0)))
(check-sat)
$ time z3-4.8.1 small.smt2
unsat

real	0m0.208s
user	0m0.148s
sys	0m0.060s
$ timeout 120s z3 small.smt2
```
It appears that `(= 0 (ite (= 0 (mod 1 v)) 1 0))` could potentially be rewritten to enhance solving efficiency, considering that `(= 0 (mod 1 v))` is always `false` in this context.

**Comment by NikolajBjorner** [comment]
It is a good idea to add the rewrite, but it doesn't address this. The instance is out of scope for any of the existing methods, so all is best effort and it doesn't make sense to establish an SLA for such formulas. It solves with sat.smt=true.
