### ISSUE TITLE
Z3 ignores certain :named annotations during generation of unsat-core

### ISSUE THREAD

**Issue by iwob** [Z3Prover/z3#711]
For the following code:

```
(set-option :produce-unsat-cores true)
(set-logic QF_UF)

(declare-fun p () Bool)
(declare-fun q () Bool)
(declare-fun r () Bool)
(declare-fun s () Bool)
(declare-fun t () Bool)

(assert (and (! (=> p q) :named PQ) (! (=> q r) :named QR)))
(assert (! (=> r s) :named RS))
(assert (! (=> s t) :named ST))
(assert (! (not (=> q s)) :named NQS))

(check-sat)
(get-unsat-core)
```

solver returned: 
```
unsat
(RS NQS)
```

while it should return:
```
unsat
(QR RS NQS)
```

What is interesting, after separating `(assert (and (! (=> p q) :named PQ) (! (=> q r) :named QR)))` into `(assert (! (=> p q) :named PQ))` and `(assert (! (=> q r) :named QR))` result is correct. What is the cause of this behavior? Is it a bug or perhaps error on my side?

(executed on Ubuntu, built from e8141aaa84bb47a927282ce0318686fd12c7b2f9, used command: `z3 -smt2 -file:unsat_tests.smt`)

**Comment by NikolajBjorner** [comment]
Assertions are only tracked at top-level when using the :named feature. The :named feature works at any level for reusing expressions, but it only operates on top-level for assertion tracking (you can have any kind of logical connectives at lower levels, so the meaning of tracking such assertions would be ill defined).  As you observe, you get the expected result when using separate assertions for tracking.
