### ISSUE TITLE
Soundness issue on QF_NRA

### ISSUE THREAD

**Issue by merlinsun** [Z3Prover/z3#7114]
Hi,
For this following instance, z3 https://github.com/Z3Prover/z3/commit/a2fa4ff1bcefaf6499a200185c1c5500bcb20a13 gives 
```
sat
unsat
```
However, when I remove the first `(check-sat)` command, z3 returns `sat` correctly.
I also tested several older versions of z3 and found that they were able to solve the instance correctly.

```
$ cat bug.smt2
(declare-fun a () Real)
(declare-fun b () Real)
(check-sat)
(assert (< 0 a))
(assert (= (- b) (* a (+ a b))))
(assert (= 1 (+ (* a a) (* b b))))
(check-sat)
$ z3 bug.smt2 
sat
unsat
$ cat xx.smt2 
(declare-fun a () Real)
(declare-fun b () Real)
(assert (< 0 a))
(assert (= (- b) (* a (+ a b))))
(assert (= 1 (+ (* a a) (* b b))))
(check-sat)
$ z3 xx.smt2 
sat
```

**Comment by NikolajBjorner** [comment]
https://github.com/Z3Prover/z3/commit/730f9ad9b7186137f9f6280c686399bb572ae5c5
