### ISSUE TITLE
c++ api obtain extract operator's indexes.

### ISSUE THREAD

**Issue by ShlKan** [Z3Prover/z3#7120]
Bit-vector operator `extract`, like `((_ extract i j) (_ BitVec m) (_ BitVec n))`  is defined in z3 as an unary function of the type `(declare-fun extract ((_ BitVec 32)) (_ BitVec 29))`. I am using z3 C++ API. I want to get the value of `i` and `j`, but cannot find APIs for them.

**Comment by wintersteiger** [comment]
Those are not arguments to a function call, but parameters to the function decl. It does indeed appear that there isn't a general function for getting parameters off of a `func_decl` in the `C++` API (only `func_decl::num_parameters`). It looks like somebody added `unsigned hi()` and `unsigned lo()` to `expr` though, which should get you those numbers (first and second parameter of type int).
