### ISSUE TITLE
Incorrect unsat output in c++

### ISSUE THREAD

**Issue by anirjoshi** [Z3Prover/z3#7122]
When I run the following c++ code:

```
#include <iostream>
#include <sstream>
#include<vector>
#include"z3++.h"

using namespace z3;


int main() {
    z3::config cfg;
    cfg.set("auto_config",true);
    z3::context c(cfg);
    z3::solver s = z3::tactic(c, "smt").mk_solver();
    s.set("smt.arith.nl.nra", false);
    
    
    z3::expr x = c.real_const("x");
    z3::expr y = c.real_const("y");
    z3::expr ct = c.real_const("c");

    z3::expr mt = c.real_val("-2");
    
    z3::expr const1 = (x*x)+(y*y)+(ct*ct);
    z3::expr const2 = (x*x)+(y*y)+(mt*x)+ct;

    s.add(const1<c.real_val("0"));
    s.add(const2<c.real_val("0"));

    if (!(s.check()==z3::sat))
        std::cout << "unsat\n";

    return 0;
}
```

I get an output: `unsat`

The constraints are satisfiable when `x=0, y=0, c=-1`

Why is this issue occurring and how to go about resolving it?

Thanks

**Comment by wintersteiger** [comment]
Is it possible that the result of `s.check()` is `z3::unknown`?

**Comment by anirjoshi** [comment]
> ```
> #include <iostream>
> #include <sstream>
> #include<vector>
> #include"z3++.h"
> 
> using namespace z3;
> 
> 
> int main() {
>     z3::config cfg;
>     cfg.set("auto_config",true);
>     z3::context c(cfg);
>     z3::solver s = z3::tactic(c, "smt").mk_solver();
>     s.set("smt.arith.nl.nra", false);
>     
>     
>     z3::expr x = c.real_const("x");
>     z3::expr y = c.real_const("y");
>     z3::expr ct = c.real_const("c");
> 
>     z3::expr mt = c.real_val("-2");
>     
>     z3::expr const1 = (x*x)+(y*y)+(ct*ct);
>     z3::expr const2 = (x*x)+(y*y)+(mt*x)+ct;
> 
>     s.add(const1<c.real_val("0"));
>     s.add(const2<c.real_val("0"));
> 
>     if (!(s.check()==z3::sat))
>         std::cout << "unsat\n";
> 
>     return 0;
> }
> ```

the output of s.check() is `unsat`
