### ISSUE TITLE
Incorrect unsat output in c++

### ISSUE THREAD

**Issue by anirjoshi** [Z3Prover/z3#7125]
This is in reference to a previous issue [here](https://github.com/Z3Prover/z3/issues/7122#issue-2135463511).

 When I run the following c++ code:

```
#include <iostream>
#include <sstream>
#include<vector>
#include"z3++.h"

using namespace z3;


int main() {
    z3::config cfg;
    cfg.set("auto_config",true);
    z3::context c(cfg);
    z3::solver s = z3::tactic(c, "smt").mk_solver();
    s.set("smt.arith.nl.nra", false);
    
    
    z3::expr x = c.real_const("x");
    z3::expr y = c.real_const("y");
    z3::expr ct = c.real_const("c");

    z3::expr mt = c.real_val("-2");
    
    z3::expr const1 = (x*x)+(y*y)+(ct*ct);
    z3::expr const2 = (x*x)+(y*y)+(mt*x)+ct;

    s.add(const1<c.real_val("0"));
    s.add(const2<c.real_val("0"));

    std::cout << s.check() << std::endl;

    return 0;
}
```

I get an output: `unsat`

The constraints are satisfiable when `x=0, y=0, c=-1`

Why is this issue occurring and how to go about resolving it?

Thanks

**Comment by NikolajBjorner** [comment]
const1 is a sum of squares, it cannot be negative. UNSAT

**Comment by anirjoshi** [comment]
Oops! Had mistaken the program, sorry! Have fixed it in and filed another issue [here](https://github.com/Z3Prover/z3/issues/7126#issue-2138264532).
