### ISSUE TITLE
Documentation: inequalities

### ISSUE THREAD

**Issue by turibe** [Z3Prover/z3#7129]
It looks like some comparisions between `{bool, int, real}` are allowed, even though the API documentation says otherwise.

For example, for `mk_le`: "The nodes t1 and t2 must have the same sort, and must be int or real."

But in practice, `(bool, bool), (bool, int), (int, bool), ...` seem to work.  Hidden feature? :-)

**Comment by NikolajBjorner** [comment]
Coercions are inserted automatically by default. 
b -> if b then 1 else 0
r -> to_real r
