### ISSUE TITLE
Corner case ambiguity in Z3_model_to_string

### ISSUE THREAD

**Issue by turibe** [Z3Prover/z3#7130]
After asserting `f(a,b) = 2` and `f(c) = 3`, `Z3_model_to_string` produces this output:
```
f -> {
  2
}
f -> {
  3
}
```
It is not clear which one is `f/1` and which one is `f/2`.

**Comment by NikolajBjorner** [comment]
You can set the output format to be SMTLIB2, then the format of the model uses declarations.

See the python bindings for an example:

        Z3_set_ast_print_mode(self.ctx, Z3_PRINT_SMTLIB2_COMPLIANT)
