### ISSUE TITLE
Proof log has mismatched predicate in `quant-inst` inference rule

### ISSUE THREAD

**Issue by someplaceguy** [Z3Prover/z3#7154]
The `quant-inst` proof inference rule as it appears in Z3 proof logs seems to be described here:

https://github.com/Z3Prover/z3/blob/e873664fe804ac5bc3831340928fa40d4816887a/src/api/z3_api.h#L555

However, I've ran into some instances where the inference rule does not follow this form. Consider the following example (minimized by [ddsmt](https://ddsmt.readthedocs.io/en/master/)):

```smt2
(declare-fun v (Real Real) Real)
(assert (forall ((b1 Real)) (= b1 (v b1 b1))))
(declare-sort t)
(declare-fun v (t) Int)
(declare-fun v (t t) Bool)
(assert (forall ((b t) (b1 t)) (= (v b b1) (< (v b) (v b1)))))
(declare-fun v14 (t t) t)
(assert (forall ((b1 t)) (= b1 (v14 b1 b1))))
(declare-fun v1 () t)
(assert (v v1 (v14 v1 v1)))
(check-sat)
(get-proof)
```

When I run `z3 proof=true <file.smt2>`, it produces a proof log containing the following expression (after `let` expansion):

```smt2
((_ quant-inst v1 (v14 v1 v1))
  (or (not (forall ((b t) (b1 t))
        (not (= (>= (+ (v b) (* (- 1) (v b1))) 0) (v b b1)))))
      (= (not (>= (+ (v v1) (* (- 1) (v (v14 v1 v1)))) 0)) (v v1 (v14 v1 v1)))))
```

i.e. the quantified `P x` starts with `(not (= ... ))` while the instantiated `P a` starts with `(= (not ...))`.

Logically, I believe the inference rule is still valid, but since it takes a different form than expected, it makes it more difficult (although not impossible) to replay this proof in HOL4, especially if we don't know the exact forms the inference rule can take.

I've looked at the Z3 code and found these lines suspiciously relevant:

https://github.com/Z3Prover/z3/blob/e873664fe804ac5bc3831340928fa40d4816887a/src/ast/macros/macro_manager.cpp#L321-L329

These were introduced in commit e6264a80ffae5eff061ece2dcdf26506b3da9625. I've tried to revert this commit on top of Z3 4.12.5 and I no longer see the mismatched predicate in proof logs (although I'm sure this commit was introduced for a reason, so reverting it doesn't seem like a long-term fix).

I'm wondering, are issue reports like this one something you're interested in having a look at? I've been working on [proof replay in HOL4](https://github.com/HOL-Theorem-Prover/HOL/pull/1194) so I have a few more similar issues that I'd be happy to report.

**Comment by NikolajBjorner** [comment]
can you try the added patch?

**Comment by someplaceguy** [comment]
Thanks for getting back so quickly!

> can you try the added patch?

It worked perfectly, thank you! Closing the issue...
