### ISSUE TITLE
Would C++ Standard Library and robustness PRs accepted?

### ISSUE THREAD

**Issue by veikkoeeva** [Z3Prover/z3#716]
Hi!

I'm what one might call a casual code reader. With a quick glimpse, it looks there are issues with 32-bit and 64-bit portability (e.g. see at http://www.viva64.com/en/a/0050/ on using `for(int i ` instead of `for(ptrdiff_t i`, http://en.cppreference.com/w/cpp/types/ptrdiff_t) and maybe a possibility to introduce more C++ Standard Library usage. Would such PRs be accepted? Would the test base be exhaustive enough (or should one be created)? Just in case I get time to contribute something by next summer. :)

**&lt;edit:** 
Taking cues from my perhaps too hasty comments from #715, maybe it would be more accurate to ask if there is information on:

1. What quality to target? I'm probably biased from a practical engineering standpoint, but I see strictly standards compliant and paying attention to https://github.com/isocpp/CppCoreGuidelines. Otherwise it is rather difficult for the more casual readers make small quality improvements and consequently both prevent bit-rot and keep difficult-to-reproduce bugs cropping up. This could allow other kinds of improvements which would attract more people.
2. What C++ standard to target? Maybe put otherwise, which platforms or which compilers? This would help to perhaps improve automated testing suites such as in g++, VC++ and Clang.
3. To attract more people with less or no contraint-solver experience, a clear set of guidelines on what is desired and accepted as contributions (you could encourage starting a PR early on to discuss and/or have a Gitter channel) and a buttery smooth setup (maybe something that could be improved too?) would be most helpful.
4. Maybe the juiciest target for a novice to this codebase, would a testing framework be welcomed? It looks like the test suite is [here](https://github.com/Z3Prover/z3/tree/master/src/test). It might be possible to add a more rigorous suite and if it were OK, introduce a suite for performance testing too. I'm more familiar with something such as [BenchmarkDotNet (BDN)](https://perfdotnet.github.io/BenchmarkDotNet/Overview.htm) than any C++ tools in this space. Which brings again one question, would it be OK to introduce something like this if it is cross-platform, but on another framework? It could be used in the .NET project already existing. In this particular case, the dependencies are only a few megabytes. // On another note, I see there's https://github.com/Z3Prover/z3test, but the same question applies. Additional one is that if the tests should be easily consumed from the same repo, say if someone works on VC++ and iterates over changes.

Looking at #715 rather superficially, I got the impression the memory management, for instance, might rely on behaviour that is undefined (pointer packing) or introduce alignment errors (not sure, just looking at it).
In addition to grokking the codebase

Maybe it'd be useful to detail the constraints and perhaps a roadmap in Readme.md.

**Comment by NikolajBjorner** [comment]
The case of #715 is somewhat of an outlier: some rather machine dependent assumptions are made for x64 bit. One can observe that this code is super non-portable. It is somewhat unclear what happens for ARM 64 under various endianess.
So far Z3 compiles on many platforms and environments and we don't yet require C++11. This will have to change in some months. We catch typical abuse with the various compilers. Maybe my fixes for #715 introduce some fresh abuse and we can iterate over the pull.

The contribution guidelines are described here: https://github.com/Z3Prover/z3/wiki/Contribution%20Guidelines

Yes, we use z3test for unit testing, and then run daily regression tests over larger sets of benchmarks. Unit tests are totally welcome. I find the current unit test setup usable, even though I could add more tests compared to the churn I add.

**Comment by veikkoeeva** [comment]
@NikolajBjorner Thanks for keeping this open and give a chance to write a few words still. You know the clientele better and how they can upgrade compilers, but perhaps instead of an ambiguous feature set, perhaps targeting some major versions of compilers would be a good approach. Terms such as "C++11" are somewhat ambiguous since compilers support them partially (one chart [here](https://msdn.microsoft.com/en-us/library/hh567368.aspx)).

As for tests, I see there's an explicit mention of having usage examples and test coverage in language binding projects, such as the .NET one. Perhaps it should be taken so that one is more free to work in that space.

Thanks for your considerate input.
