### ISSUE TITLE
UNEXPECTED CODE WAS REACHED for recursive function 

### ISSUE THREAD

**Issue by nnarek** [Z3Prover/z3#7168]
getting "UNEXPECTED CODE WAS REACHED" warning when run [galaxies_game_solver.py](https://gist.github.com/nnarek/576b525c7a06f0926c05100b713f85e4#file-galaxies_game_solver-py)

found issue by using latest z3py solver and Python 3.10.12

**Comment by NikolajBjorner** [comment]
you need to use "if" to guard recursive calls. 
For example, 

```
(define-funs-rec ( ( is_connected
                     ((x!1 Int) (x!2 Int) (x!3 Int) (x!4 Int))
                     Bool))
                 ( if (= (field x!1 x!2) (field x!3 x!4))
                        (or (and (= x!1 x!3) (= x!2 x!4))
                            ((_ is_connected 0) x!1 (+ x!2 1) x!3 x!4)
                            ((_ is_connected 0) x!1 (- x!2 1) x!3 x!4)
                            ((_ is_connected 0) (+ x!1 1) x!2 x!3 x!4)
                            ((_ is_connected 0) (- x!1 1) x!2 x!3 x!4))
			    false))
```

Your python uses "(and a b)" instead of (if a b false). The rewriter assumes recursive definitions are guarded by conditionals. For other operators it doesn't assume any evaluation order.

**Comment by nnarek** [comment]
another issue in my code is that I am trying to use field(which is Function) inside is_connected(which is RecFunction)
in this case I am getting infinite loop
using 2D array instead of Function and passing it to RecFunction as parameter solved problem

Thank you
