### ISSUE TITLE
Dynamic library error

### ISSUE THREAD

**Issue by xebelleDerrel** [Z3Prover/z3#7172]
I used G++ to generate a dynamic library libz3.dll for Z3 in a Windows environment, and then I needed to build a project in Virtual Studio and use Z3 for special needs, I added the dynamic library I generated earlier to the linker, but I ran the program with an error: G:vs projectstest4test4srclibz3.dll : fatal error LNK1107 Invalid or corrupted file: Cannot be read at 0x200

**Comment by NikolajBjorner** [comment]
Interoperability between g++ and cl appears not to be specific to z3.
