### ISSUE TITLE
questions about the architecture of some release versions

### ISSUE THREAD

**Issue by Bri1987** [Z3Prover/z3#7178]
I would like to know that there are some compressed packages like z3-4.13.0-arm64-glibc-2.35.zip exist in versions 4.13.0 and earlier,  why do their decompressed libz3. so and z3 files all use x86-64 architecture? Shouldn't it be the aarch64 architecture? Do I have any misunderstandings about arm64 ?

**Comment by NikolajBjorner** [comment]
must be incorrect build setup. Build scripts are updated, but new nightly will not be ready for some days until some signing keys are updated.

**Comment by Bri1987** [comment]
Thanks !
