### ISSUE TITLE
Nested construction terms problem

### ISSUE THREAD

**Issue by Muxucao0812** [Z3Prover/z3#7191]
<img width="1732" alt="image" src="https://github.com/Z3Prover/z3/assets/76735846/70ce7639-c2d5-475e-a751-e7f96b4e0560">
I used Z3 to construct the model of logic circuit, and I met one problem. In the picture, when I print the term, it is right, but when in the left column, it is wrong, and when I use it after, the term is wrong as you saw in the left column, so can you help me to solve this problem? Thanks

**Comment by NikolajBjorner** [comment]
this looks like a feature of your debugger: it chops off new-lines. The z3/python pretty printer adds a newline before 0 == voto3.

**Comment by Muxucao0812** [comment]
How can I cancel the line wrapping of terms? I want all terms to be on the same line, please. Because I will print the term in the text, and newline would influence the correctness.

**Comment by NikolajBjorner** [comment]
Not sure you are using your tool correctly. 
But you can try to set  

```
set_pp_option("max_width", 200000)
``` 
then the Python pretty printer will use long line lengths.

**Comment by NikolajBjorner** [comment]
https://microsoft.github.io/z3guide/programming/Z3%20Python%20-%20Readonly/advanced#formatter

**Comment by Muxucao0812** [comment]
Thank you very much, this problem has been solved!!!
