### ISSUE TITLE
z3 solver check call hangs when solver is created with smt tactic

### ISSUE THREAD

**Issue by chauhansantosh17** [Z3Prover/z3#7193]
Hello,

We are currently using z3 version 4.8.10 in our C++ based application. In our application, we are facing a situation where z3 solver check call hangs for a given set of constraints. Out constraint set is summarized in the below smtlib2 format:

(declare-fun |Result| () Int)
(declare-fun |Constraint1| () Bool)
(declare-fun |Type2Qty| () Int)
(declare-fun |Constraint2| () Bool)
(declare-fun |Type3Qty| () Int)
(declare-fun |Constraint3| () Bool)
(declare-fun |Type2Height| () Int)
(declare-fun |Constraint4| () Bool)
(declare-fun |Type4Height| () Int)
(declare-fun |Constraint5| () Bool)
(declare-fun |Type4Qty| () Int)
(declare-fun |Constraint6| () Bool)
(declare-fun |Type3Height| () Int)
(declare-fun |Constraint7| () Bool)
(declare-fun |Type1Qty| () Int)
(declare-fun |Constraint8| () Bool)
(declare-fun |Type1Height| () Int)
(declare-fun |Constraint9| () Bool)
(declare-fun |Constraint10| () Bool)
(declare-fun |Result_NF| () Bool)
(assert (= |Constraint1| (distinct |Result| 0)))
(assert (= |Constraint2| (distinct |Type2Qty| 0)))
(assert (= |Constraint3| (distinct |Type3Qty| 0)))
(assert (= |Constraint4|
   (or (= |Type2Height| 100) (= |Type2Height| 200))))
(assert (= |Constraint5|
   (or (= |Type4Height| 100) (= |Type4Height| 200))))
(assert (= |Constraint6| (distinct |Type4Qty| 0)))
(assert (= |Constraint7|
   (or (= |Type3Height| 100) (= |Type3Height| 200))))
(assert (= |Constraint8| (distinct |Type1Qty| 0)))
(assert (= |Constraint9|
   (or (= |Type1Height| 100) (= |Type1Height| 200))))
**(assert (let ((a!1 (and (= |Result|
                   (+ (* |Type1Height| |Type1Qty|)
                      (* |Type2Height| |Type2Qty|)
                      (* |Type3Height| |Type3Qty|)
                      (* |Type4Height| |Type4Qty|))))))
  (= |Constraint10| a!1)))**
(assert (= |Result_NF| (distinct |Result| 100)))
(assert |Constraint1| )
(assert |Constraint2| )
(assert |Constraint3| )
(assert |Constraint4| )
(assert |Constraint5| )
(assert |Constraint6| )
(assert |Constraint7| )
(assert |Constraint8| )
(assert |Constraint9| )
(assert |Constraint10| )
(assert |Result_NF| )

Our hunch is the above highlighted Constraint10 is somehow causing the hang because if we remove the constraint then, check call returns instantaneously.

We have some more observations in context of how the solver object is created within our application. Sample code representing z3 consumption in our application is:

    z3::context c;
    z3::tactic t = z3::tactic(c, "smt");
    // Create a solver with the tactic                
    z3::solver s = t.mk_solver();

    // Open the Z3 file containing the above asserts
    std::ifstream file("Z3SMT.txt");

    // Read the file into a string
    std::stringstream buffer;
    buffer << file.rdbuf();
    std::string z3_dump = buffer.str();

    // Get the assertions from the parsed SMT-LIB2 string
    Z3_ast_vector av = Z3_parse_smtlib2_string(c, z3_dump.c_str(), 0, NULL, NULL, 0, NULL, NULL);

    // Add the parsed constraints to the solver
    unsigned sz = Z3_ast_vector_size(c, av);
    for (unsigned i = 0; i < sz; i++) {
        Z3_ast a = Z3_ast_vector_get(c, av, i);
        s.add(z3::expr(c, a));
    }

    // Check if the constraints are satisfiable
    if (s.check() == z3::sat) // check call hangs at this point
    {
          std::cout << "The constraints are satisfiable.\n";
    }
    else
    {
        std::cout << "The constraints are not satisfiable.\n";
    }

Observation
The z3 solver check call in the above code snippet hangs.
If the solver is created with different tactic as mentioned below, then check call does not hang.

    z3::tactic t = z3::tactic(c, "default");
    // Create a solver with the tactic         
    z3::solver s = t.mk_solver();
 
Our Queries:
1. Can you help us understand the reason for the hang (in case of “smt” tactic)?
2. If we do not want to switch to “default” tactic: What other tactics can be combined with the “smt” tactic to solve the given problem without a hang state?
3. If we have no option but to switch to the “default” tactic, can we expect any functional/performance regressions in our app (for any given problem) by switching to the “default” tactic?

**Comment by NikolajBjorner** [comment]
1. This does not reproduce. Maybe your old version of z3 suffered from a non-termination bug for some cases of integers.
2. You could try the QF_LIA tactic, or you could use tactics that include pre-processing. When you run the default solver it uses equality and constant propagation. You compose tactics using "then". Tactics are documented here https://microsoft.github.io/z3guide/docs/strategies/tactics/ and here https://microsoft.github.io/z3guide/docs/strategies/summary
3. the default solver is all-round what most applications should use. I tune for default solver behavior. Tactics should be overkill for most cases, or indicate that default solver behavior could be improved.
