### ISSUE TITLE
Z3 isn't pip-installable

### ISSUE THREAD

**Issue by zardus** [Z3Prover/z3#72]
Most python packages nowadays can be installed via pip. For z3, this would look like:

```ShellSession
# pip install z3
```

This is super awesome not only because it makes it super easy to install z3, but also because it lets people easily put z3 in the requirements.txt of their packages, so that pip will automatically install it as a dependency, which will be cool beyond belief!

There are two steps required to support this:

1. Create a `setup.py` that installs the package.
2. Register and upload a build to https://pypi.python.org

I'll submit a pull request for 1 shortly. I don't think it's my place to do 2, but once 1 is done, it's a matter of a few commands that you can run to register and upload to pypi.

**Comment by zardus** [comment]
Opened PR #73 that implement part 1.

**Comment by NikolajBjorner** [comment]
This issue is super-seeded by #288
