### ISSUE TITLE
Linux arm64 build is actually an x86_64 build

### ISSUE THREAD

**Issue by Robert42** [Z3Prover/z3#7201]
I tried executing the newest z3 release on my raspberry pi, but the executable seems to be built for x86_64

## How to Reproduce the issue

```sh
wget https://github.com/Z3Prover/z3/releases/download/z3-4.13.0/z3-4.13.0-arm64-glibc-2.35.zip
unzip z3-4.13.0-arm64-glibc-2.35.zip
file z3-4.13.0-arm64-glibc-2.35/bin/z3
```

I get 
```
z3-4.13.0-arm64-glibc-2.35/bin/z3: ELF 64-bit LSB pie executable, x86-64, version 1 (GNU/Linux), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, BuildID[sha1]=e211ea9ab79d498c87b8dd8ff895a58f525efe59, for GNU/Linux 3.2.0, not stripped
```

**Comment by thpani** [comment]
I also ran into this, it should be fixed thru 648e05754c37220f1fbb5943b4e69545d82b7bae

**Comment by thpani** [comment]
@NikolajBjorner Is there any chance of cutting a release soon?

All published Linux/aarch64 releases are actually x86_64, and the Nightly pipeline [hasn't been publishing](https://dev.azure.com/z3build/Z3Build/_build?definitionId=11) since March 7.

**Comment by NikolajBjorner** [comment]
We are currently blocked on reviving code signing after a forced password reset. There is no ETA.

**Comment by NikolajBjorner** [comment]
would be addressed with newest release
