### ISSUE TITLE
Last package available for Ubuntu via apt is 3.8.12

### ISSUE THREAD

**Issue by sethahrenbach** [Z3Prover/z3#7202]
Running `sudo apt install z3` after ensuring that Microsoft repository is added via 
```sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 55F96FCF8231B6DD
echo "deb [arch=amd64] https://packages.microsoft.com/ubuntu/20.04/prod focal main" | sudo tee /etc/apt/sources.list.d/microsoft-prod.list
```
and running `sudo apt update`
results in Z3 version 4.8.12. However, the latest version is 4.13.0 at this time. Does this team maintain the Ubuntu apt repository?

**Comment by NikolajBjorner** [comment]
It is not maintained from this end. It is not part of our build pipelines. If there is a pipeline/action that can be added here as part of release processes, we are open to pull requests (without backdoors :-)), but it is entirely up to others. There can be very good reasons to maintain independent processes.
