### ISSUE TITLE
SAT solver runtime changes depending on Z3 version

### ISSUE THREAD

**Issue by LeeJaKang** [Z3Prover/z3#7211]
Hello. I am working on solving SAT problems using Z3.

Meanwhile, I found out that the runtime of the SAT solver changes significantly depending on the Z3 version.

The results of my experiment are as follows.

4.13.1 | 9.946s
4.12.6 | 9.504s
4.11.2 | 0.933s
4.10.2 | 0.924s
4.9.1 | 0.947s
4.8.17 | 1.422s
4.8.5 | 1.229s

As you can see, from versions 4.9 to 4.11 the runtime for SAT operations is very small. 

However, starting from version 4.12.6, the SAT calculation time suddenly increases significantly. 

Could you please tell me why?

Thank you..

**Comment by NikolajBjorner** [comment]
Run a profiler? There is not enough information here to provide a useful answer.
