### ISSUE TITLE
Remaining deprecated `distutils` in Python scripts.

### ISSUE THREAD

**Issue by arbipher** [Z3Prover/z3#7228]
https://github.com/Z3Prover/z3/blob/8fe357f1f213b88a679f72e3d575cae2d3e47b3a/src/api/python/setup.py#L10-L14

Searching in the code base shows a tiny remaining code using `distutils` that is already deprecated in Python 3.12.

p.s. I have no idea how the code will be loaded, so I cannot trigger the error.

**Comment by NikolajBjorner** [comment]
fixed with latest release
