### ISSUE TITLE
rlimit fails to stop z3

### ISSUE THREAD

**Issue by hmijail** [Z3Prover/z3#7247]
I have a generated file that keeps z3 working "forever" even if I give it a rlimit.
```
$ z3-4.13.0/bin/z3 1717648676-Impl__name.__default.block__0__0x0128_split20.smt rlimit=6900000
...
```

Interestingly, making the rlimit slightly lower causes z3 to finish in ~1 second.
```
$ z3-4.13.0/bin/z3 1717648676-Impl__name.__default.block__0__0x0128_split20.smt rlimit=6700000
unknown
(:reason-unknown "canceled")
(:rlimit 6722629)
```

* I have seen comments about z3's resource count not being necessarily easily mapped to time spent, so I wonder if this a bug or not? Though it looks a bit extreme...
* If it isn't, is there a way to make z3 stop gracefully? (as opposed to killing it) I'm hoping this would allow me to continue using the layers over z3 (boggie and dafny).

This is on macOS 14.5 (ARM), z3 4.13.0. Also reproducible with previous z3 versions (4.12.6... 4.12.1).

[1717648676-Impl__name.__default.block__0__0x0128_split20.smt.zip](https://github.com/user-attachments/files/15629055/1717648676-Impl__name.__default.block__0__0x0128_split20.smt.zip)

**Comment by NikolajBjorner** [comment]
35c1cacf44951787e1427a4b76941f961aff4584
