### ISSUE TITLE
Incorrect model under soft constraints

### ISSUE THREAD

**Issue by gowthamk** [Z3Prover/z3#725]
I built z3 with from the master branch commit [882c3bd](https://github.com/Z3Prover/z3/commit/882c3bd0cdcfbaa0f8d0d7a04cee3009e151bb1e), and used it on the following input:

    ;; Command to run: 
    ;; z3 -smt2 smt.mbqi=true smt.macro-finder=true -T:20 bug.z3
    (declare-datatypes () ((Oper GB WD DP NOP)))
    (declare-datatypes () ((Eff e1 e2 e3 e4 e5)))
    (declare-fun oper (Eff) Oper)
    (declare-fun rval (Eff) Int)
    (assert (= (oper e3) GB))
    ;; e4 may be WD or NOP
    (assert (or (= (oper e4) WD) (= (oper e4) NOP)))
    ;; e5 may be WD or NOP
    (assert (or (= (oper e5) WD) (= (oper e5) NOP)))
    ;; assert soft constraints
    (declare-const b Bool)
    (assert-soft (not b))
    (check-sat) 
    (get-model)
    (eval (oper e1))
    (eval (oper e2))
    (eval (oper e3))
    (eval (oper e4))
    (eval (oper e5))

I get what appears to be an incorrect model:

```
$ z3 -smt2 smt.mbqi=true smt.macro-finder=true -T:20 bug.z3
sat
(objectives
 ( 0)
)
(model 
  (define-fun b () Bool
    false)
  (define-fun oper ((x!0 Eff)) Oper
    GB)
)
GB
GB
GB
GB
GB
```

Observe that `oper(e4)=GB` and `oper(e5)=GB` in the model, although hard constraints explicitly prohibit this. I also tried Z3 v4.4.1, but it throws a segmentation fault on the above input (my system is Mac OS X 10.9.5). Z3 behind the web interface seems to behave well, though.

**Comment by NikolajBjorner** [comment]
Thanks, fixed
