### ISSUE TITLE
conflicts with libgc

### ISSUE THREAD

**Issue by KuiWei004** [Z3Prover/z3#7253]
I use z3-solver as a library in my c++ project, but it crashed occasionally. The crash point is always the destructor in z3-ast or z3-solver.
I think the reason may be that before the destructor works, the libgc has collected the corresponding mem, so when the destructor works, it will delete a null pointer.

**Comment by KuiWei004** [comment]
Is there any way to disable the mem-manager of z3? I'd like to let z3 use the `malloc` function overrided by libgc.

**Comment by NikolajBjorner** [comment]
memory manager code is here:

https://github.com/Z3Prover/z3/blob/master/src/util/memory_manager.cpp

it uses different libraries depending on compilation flags.
