### ISSUE TITLE
`unstable` branch does not exist

### ISSUE THREAD

**Issue by kayceesrk** [Z3Prover/z3#726]
Not sure if this is the best place for the issue, but the z3opt tutorial [0], points to a non-existent `unstable` branch in this repo:

> Note: This feature currently part of the unstable branch. To reach the opt branch go to https://github.com/Z3Prover/z3, then select the unstable branch.

[0] http://rise4fun.com/z3opt/tutorial/

**Comment by NikolajBjorner** [comment]
Sorry, I need to update the text. Z3opt is now part of the master branch. Binaries are in z3prover/bin nightly builds.

**Comment by kayceesrk** [comment]
Excellent. Thanks!
