### ISSUE TITLE
Incorrect solution regarding data type conversion

### ISSUE THREAD

**Issue by Heaven2024** [Z3Prover/z3#7272]
Hi!
Z3 [version 4.13.1 - 64 bit]
ubuntu:22.04

```
cat test.smt2
(declare-fun B () Real)
(assert (not (is_int (to_real (* 2 B)))))
(check-sat)
(exit)

cvc5 test.smt2  --check-models
sat
```

but for z3 :

```
z3 test.smt2
unsat
```

**Comment by NikolajBjorner** [comment]
to_real should really only be used on integer arguments.
https://smt-lib.org/theories-Reals_Ints.shtml
Z3 makes a choice to add a "to_int" conversion to arguments that are real when the argument should be int.

**Comment by NikolajBjorner** [comment]
C:\z3\build>z3 7272.smt2 /v:10 /tr:asserted_formulas /tr:rewriter /tr:th_rewriter_step smtlib2_compliant=true
success
(error "line 2 column 36: Sort mismatch at argument #2 for function (declare-fun * (Int Int) Int) supplied sort is Real")
