### ISSUE TITLE
Uncollected memory

### ISSUE THREAD

**Issue by Flians** [Z3Prover/z3#7283]
Dear,

When I used `z3::expr_vector` in C++, I met the following errors after the program exited. I did not use any C++ pointers and only used `std::unordered_map<std::string, std::vector<z3::expr_vector>>` to record variables. Could you please tell me how to solve this problem? Thank you.

```
WARNING: Uncollected memory: 5: 17Z3_ast_vector_ref
ASSERTION VIOLATION
File: /Users/flynn/workplace/RQFPLS/third-party/z3/src/api/api_context.cpp
Line: 41
m_ref_count > 0
(C)ontinue, (A)bort, (S)top, (T)hrow exception, Invoke (G)DB
```

```
std::vector<z3::expr_vector> cur_pnodes;
z3::expr &root_node = ...;
z3::context &ctx = root_node.ctx();
cur_pnodes.emplace_back(ctx);
cur_pnodes.back().push_back(root_node);
```

**Comment by NikolajBjorner** [comment]
The life-time of cur_pnodes should not exceed the life-time of ctx.

**Comment by Flians** [comment]
Thank you.
