### ISSUE TITLE
ASSERTION VIOLATION File: ../src/ast/ast.cpp Line: 388 UNEXPECTED CODE WAS REACHED. Z3 4.13.1.0

### ISSUE THREAD

**Issue by Sunshien-CC** [Z3Prover/z3#7284]
The program works fine when I use the following code.
//------
    expr_vector a = c.parse_string("my expression");
    expr result = a[0];
    std::cout <<result << "\n-----------\n";
    expr I0 = c.bool_const("I0");
    expr I1 = c.bool_const("I1");
    expr I2 = c.bool_const("I2");
    expr I3 = c.bool_const("I3");
    expr I4 = c.bool_const("I4");
    expr I5 = c.bool_const("I5");
    expr f = c.bool_val(true);
    std::vector<Z3_ast> from;
    std::vector<Z3_ast> to;
    
    from.emplace_back(I0);
    from.emplace_back(I1);
    from.emplace_back(I2);
    from.emplace_back(I3);
    from.emplace_back(I4);
    from.emplace_back(I5);
    
    to.emplace_back(f);
    to.emplace_back(f);
    to.emplace_back(f);
    to.emplace_back(f);
    to.emplace_back(f);
    to.emplace_back(f);
    to.emplace_back(f);
    to.emplace_back(f);
    to.emplace_back(f);
    result = to_expr(c, Z3_substitute(c, result, 6, from.data(), to.data()));
    std::cout <<result << "\n-----------\n";
    std::cout<<result.simplify()<<std::endl;
//----

When I use the following code, I get an error.  ASSERTION VIOLATION File: ../src/ast/ast.cpp Line: 388 UNEXPECTED CODE WAS REACHED. Z3 4.13.1.0
//----
std::cout << "parse example\n";
    context c;
    expr_vector a = c.parse_string("my expression");
    expr result = a[0];
    std::cout <<result << "\n-----------\n";
    expr f = c.bool_val(false);
    std::vector<Z3_ast> from;
    std::vector<Z3_ast> to;
    from.emplace_back(c.bool_const("dataa"));
    from.emplace_back(c.bool_const("datab"));
    from.emplace_back(c.bool_const("datac"));
    from.emplace_back(c.bool_const("datad"));
    from.emplace_back(c.bool_const("datae"));
    from.emplace_back(c.bool_const("dataf"));
    from.emplace_back(c.bool_const("datag"));
    from.emplace_back(c.bool_const("datah"));
    from.emplace_back(c.bool_const("cin"));
    to.emplace_back(f);
    to.emplace_back(f);
    to.emplace_back(f);
    to.emplace_back(f);
    to.emplace_back(f);
    to.emplace_back(f);
    to.emplace_back(f);
    to.emplace_back(f);
    to.emplace_back(f);
    expr  from2 = to_expr(c, from.data()[0]);
    expr  to2   = to_expr(c, to.data()[0]);

    result = to_expr(c, Z3_substitute(c, result, 9, from.data(), to.data()));
    std::cout <<result << "\n-----------\n";
    std::cout<<result.simplify().to_string()<<std::endl;
//----

Why did this error occur?

**Comment by NikolajBjorner** [comment]
You should definitely avoid mixing Z3_ast and z3::expr. When using the C++ API stick with z3::expr and if you are using functions not exposed over the C++ API, then create a wrapper for that function that creates expr objects and not just raw Z3_ast. Extra bonus, add pull requests if the C++ API does not support your function.
