### ISSUE TITLE
"mbp to_real" when using spacer with global guidance

### ISSUE THREAD

**Issue by mmsbrggr** [Z3Prover/z3#7285]
I modeled a version of the "temperature control system" using Horn clauses and trying to prove deadlock-freedom. For certain initial values (max/min temperature, etc.) I noticed that Spacer gets stuck in generating similar invariants that just differ in one integer. Therefore, I enabled the global guidance option "spacer.global". However, after enabling the option Z3 terminates with "unknown" and reason "mbp to_real".

There are only integers (and enums) in the encoding. Moreover, even enabling "rewriter.elim_to_real" didn't solve the problem.

Here is the exported smt-lib encoding:
[temperature.smt2.txt](https://github.com/user-attachments/files/16195886/temperature.smt2.txt)

**Comment by hgvk94** [comment]
I have solved this problem in my local branch: https://github.com/hgvk94/z3/commit/aad4cac4b83378a45230d550c2fead0561c3aa94 
I will merge it soon. 
However, even after the fix, global guidance doesn't solve this instance. It identifies that the common pattern but doesn't know how to generalize it.

**Comment by mmsbrggr** [comment]
Thank you! I will test it with your branch.
