### ISSUE TITLE
Possibly a bug - Int type

### ISSUE THREAD

**Issue by DennisYurichev** [Z3Prover/z3#7286]
```
#!/usr/bin/python3

# Z3 4.13.0

from z3 import *

x,y,n = Ints('x y n')
s=Solver()
s.add(n==4)
s.add(x>0)
s.add(y>0)
s.add(x>y)
s.add((1/x) + (1/y) == (1/n))

print (s.check())
print (s.model())
```

Weird result:

```
sat
[n = 4,
 x = 3,
 y = 2,
 div0 = [else -> 0],
 mod0 = [else -> 0]]
```

**Comment by LeventErkok** [comment]
`1/x`  translates to `(div 1 x)` in SMTLib, which is integer division. (See https://smt-lib.org/theories-Ints.shtml)

So, `1/3`, `1/2`, and `1/4` all evaluate to `0`. And the equality `0 + 0 = 0` holds. Hence the model you get, which is perfectly fine.

Of course, you meant `1/x` to be a real value, so you should write:

```
s.add((1.0/x) + (1.0/y) == (1.0/n))
```

and you'll get:

```
sat
[x = 20, y = 5, n = 4, /0 = [(1, 20) -> 1/20, else -> 1/5]]
```

You didn't ask, but z3 will also tell you how it interpreted division and modulus by 0 in this case. (SMTLib leaves this unconstrained, i.e., solvers are free to interpret division and modulus by 0 as whatever value they please. See https://smt-lib.org/theories-Reals.shtml.) In this case Z3 is telling you how it interpreted division/modulus by 0. (Not that it matters in this particular case.)

So, this isn't a bug; but I do agree it's rather confusing. Unfortunately the untyped-nature of Python and the fast-and-loose translation in z3py bindings (which isn't always consistent) lead to such gotchas occasionally.

**Comment by NikolajBjorner** [comment]
Thanks, 

Inspecting the solver assertions can sometimes help.

print(s.sexpr())

produces

```
(declare-fun n () Int)
(declare-fun x () Int)
(declare-fun y () Int)
(assert (= n 4))
(assert (> x 0))
(assert (> y 0))
(assert (> x y))
(assert (= (+ (div 1 x) (div 1 y)) (div 1 n)))
```

**Comment by DennisYurichev** [comment]
Ah yes, sorry for being innatentive.

**Comment by DennisYurichev** [comment]
But the reason I did this is the following.
Project Euler 108:
```
In the following equation x, y, and n are positive integers.
$$\dfrac{1}{x} + \dfrac{1}{y} = \dfrac{1}{n}$$
For n = 4 there are exactly three distinct solutions:
...
```
By the statement of problem, x, y, n are integers.
Is it possible to model this problem in Z3?
Is this mixed integer linear programming? MILP?
Can I declare x as integer and 1/x as real?

**Comment by LeventErkok** [comment]
As mentioned above, you either write:

```python
s.add((1.0/x) + (1.0/y) == (1.0/n))
```

or

```python
s.add((1/ToReal(x)) + (1/ToReal(y)) == (1/ToReal(n)))
```

Do these not work for you?
