### ISSUE TITLE
Invalid model for (str.to.int (int.to.str ... ))

### ISSUE THREAD

**Issue by tlringer** [Z3Prover/z3#731]
The following query:

```
(set-option :model-validate true)

(declare-fun c0 () Int)
(assert (not (= c0 (str.to.int (int.to.str c0)))))
(check-sat)
(get-model)
```

Gives me the following invalid model:

```
sat
(error "line 5 column 10: an invalid model was generated")
(model 
  (define-fun c0 () Int
    0)
)
```

If this isn't a bug because of the ground rewriting restriction for now then I understand, but maybe it is something that can be special-cased.

**Comment by NikolajBjorner** [comment]
The bug was due to axioms for str.to.int(int.to.str(x)) = x missing when x wasn't given a constant value in the final interpretation. So the bug would be masked if there were other linear inequalities on x. The rewriter also wasn't handling this case, but that is only an optimization.

**Comment by NikolajBjorner** [comment]
I believe fixed with check-in, modulo if int.to.str should become under-specified for negative numerals.
