### ISSUE TITLE
Z3 does not terminate on a simple problem

### ISSUE THREAD

**Issue by Ceilican** [Z3Prover/z3#732]
If I execute Z3 on the following problem, it terminates and says "sat":

```
(declare-sort B 0)
(declare-sort W 0)

(declare-fun mnot (B) B)
(declare-fun mand (B B) B)

(declare-fun T (B W) Bool)

(assert (forall ((w W) (p B)) 
  (iff (T (mnot p) w) 
       (not (T p w))   )
))

(check-sat)
```

However, if I execute Z3 on the following slightly different problem (with one additional assertion), Z3 seems to loop forever:

```
(declare-sort B 0)
(declare-sort W 0)

(declare-fun mnot (B) B)
(declare-fun mand (B B) B)

(declare-fun T (B W) Bool)

(assert (forall ((w W) (p B)) 
  (iff (T (mnot p) w) 
       (not (T p w))   )
))

(assert (forall ((w W) (p B) (q B)) 
  (iff (T (mand p q) w) 
       (and (T p w) (T q w)) )
))

(check-sat)
```

The second problem does not seem to be much harder than the first problem, and I know that it is satisfiable too. I wonder why Z3 cannot terminate and find a model for the second problem.  I hope that this simple example may help to improve Z3's model search.

(By the way, I haven't tried, but I suspect that Isabelle's Nitpick would be able to find a model.)

**Comment by NikolajBjorner** [comment]
You could restrict the domains to be finite, then the model-based quantifier instantiation engine converges.

      (declare-datatypes () ((B (b1) (b2) (b3)) (W (w1) (w2) (w3))))
