### ISSUE TITLE
Calculating division, obtaining an incorrect solution; the divisor is 0

### ISSUE THREAD

**Issue by frankeyjin** [Z3Prover/z3#7325]
I want to calculate the solution for a/(b-1) == 4, but I'm got b=1, I don't understand why.

from z3 import *
s=Solver();
a, b = Ints('a b')
s.add(a/(b-1) == 4)
print(s.check())
print(s.model())

The Result:
sat
[b = 1, a = -1, div0 = [else -> 4], mod0 = [else -> 0]]

**Comment by LeventErkok** [comment]
In SMTLib division-by-zero is "uninterpreted." That is, the solver is free to assign any value it wants to a term of the form `a/b` where `b = 0`. And this is what it's telling you in the model, `div0 = [else -> 4]`, meaning, it decided to assign the value `4` for division by 0.  (Similarly, it assigned modulus-by-0 the value `0`, but that's irrelevant here.)

See the comment regarding division-by-0 in https://smt-lib.org/theories-Reals.shtml for details.

To avoid such interpretations, simply add an extra constraint:

```python
s.add((b-1) != 0)
```

to avoid division-by-0. This should give you a model that's in line with your expectations.

As a side note, questions such as these are more appropriate for stack-overflow. See: https://stackoverflow.com/questions/tagged/z3+z3py
