### ISSUE TITLE
Latest versions of NuGet package does not include Linux binaries

### ISSUE THREAD

**Issue by 89netraM** [Z3Prover/z3#7366]
The latest versions of [the NuGet package](https://www.nuget.org/packages/Microsoft.Z3) (versions 4.12.0 and up) does not include Linux runtime binaries. Only Windows and MacOS runtime binaries are included.

**Comment by 89netraM** [comment]
On  [the Releases tab](https://github.com/Z3Prover/z3/releases) here on GitHub there are more releases than on [nuget.org](https://www.nuget.org/packages/Microsoft.Z3) and these releases contain NuGet package with the Linux binaries. Would it be possible to publish them to the NuGet repository? Or are they published to another NuGet repository?

**Comment by NikolajBjorner** [comment]
nuget.org changed the requirements for packages and I have been unable to include the newly required file without failing packet checksum validation in the build.  Nuget distribution is therefore on hold until there is any bandwidth / competencies to figure this out. You can download packages from the github releases.
