### ISSUE TITLE
Soundness issue on arithmetic

### ISSUE THREAD

**Issue by merlinsun** [Z3Prover/z3#7368]
Hi,
for this following instance, z3 https://github.com/Z3Prover/z3/commit/8061765574aa9224e5f1d572b08c0881efe51285 incorrectly gives  `unsat`.
```
$ z3 small.smt2 
unsat
$ z3-4.8.10-x64-ubuntu-18.04/bin/z3 small.smt2 
sat
$ cvc5 small.smt2 
sat
$ cat small.smt2 
(set-logic ALL)
(declare-const x7 Int)
(declare-const x Bool)
(declare-fun s () Real)
(assert (or x (< 1 (+ s (/ x7 1) (/ (to_int (* s (/ s (+ s (* s (ite false 0.0 (/ 0.0 (* s s)))))))) 1)))))
(check-sat)
```
After investigating the instance, I noticed that if the term `(ite false 0.0 (/ 0.0 (* s s)))` is rewritten to `(/ 0.0 (* s s))`, the instance is solved correctly:
```
$ cat pass.smt2 
(set-logic ALL)
(declare-const x7 Int)
(declare-const x Bool)
(declare-fun s () Real)
(assert (or x (< 1 (+ s (/ x7 1) (/ (to_int (* s (/ s (+ s (* s (/ 0.0 (* s s))))))) 1)))))
(check-sat)
$ z3 pass.smt2 
sat
```

**Comment by benjaminfjones** [comment]
FWIW, I could not reproduce this problem on the commit you mention, nor on HEAD, 4.12.6, or 4.12.1.

I'm using a default build configuration on Linux/x86_64

```
❯ uname -a
Linux 5.10.224-190.876.x86_64 #1 SMP Fri Aug 23 01:22:37 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
```

How is the version of z3 that reports "unsat" configured during the build? What platform are you on?

**Comment by NikolajBjorner** [comment]
z3 7368.smt2 /v:10 /st smt.arith.validate=true

**Comment by levnach** [comment]
nlsat::simple_checker::imp::check() returns false, reporting a conflict, and does not explain the conflict.
