### ISSUE TITLE
Java api: the call to com.microsoft.z3.Native.INTERNALdelContext(Native Method) never ends

### ISSUE THREAD

**Issue by freeideo** [Z3Prover/z3#7369]
I used z3 to solve the problem in a multithreaded environment, where each thread creates its own Context object. I call Context.close() to release the resource if there are some errors during the solving process, but occasionally I run into a situation where calling the native method while releasing the resource never ends.

The following is a record of thread monitoring using visualvm:

<img width="1330" alt="vm1" src="https://github.com/user-attachments/assets/ebfa89cb-b108-45c5-b9f2-f4ca26d0b131">

and the thread 5 is executing the Context.close() method:

<img width="960" alt="vm2" src="https://github.com/user-attachments/assets/03a13769-542c-42a1-82ac-2ca42acef2c8">

the thread dump is as follows:

<img width="835" alt="vm3" src="https://github.com/user-attachments/assets/7baf9ee1-94fa-4b1e-a860-c81eac1a4df5">

**version:**

z3-turkey 4.8.15

**Comment by NikolajBjorner** [comment]
There is no support for downlevel z3. Use the newest version.
