### ISSUE TITLE
Release policy?

### ISSUE THREAD

**Issue by Naville** [Z3Prover/z3#7378]
Hi Nikolaj:
18365907a27e03a99092238646b1d7a65fc20ca3 and #7318 fixes build issues on certain build configurations, namely ClangCL on Windows and Clang cross-compiling for Windows.

Is it possible to draft a new release with those changes so downstream package managers could inherit such patches?

**Comment by NikolajBjorner** [comment]
OK, next week

**Comment by Naville** [comment]
ping
