### ISSUE TITLE
Datalog evaluation appears to hang

### ISSUE THREAD

**Issue by jpgallagher** [Z3Prover/z3#738]
The attached example [ex1.txt](https://github.com/Z3Prover/z3/files/473341/ex1.txt) is a small set of Datalog clauses over a two valued domain in the bddbddb syntax.  It appears to hang in z3 though bddbddb completes in a few ms. Not sure what it is doing but with verbose mode it generates the following output.
$ z3 -dl -v:1 ex1.txt

Z3 Datalog Engine
parsing finished
running saturation...
(transform N7datalog13mk_coi_filterE...no-op 0s)
(transform N7datalog25mk_interp_tail_simplifierE...no-op 0s)
(transform N7datalog15mk_rule_inlinerE...no-op 0s)
(transform N7datalog34mk_partial_equivalence_transformerE...no-op 0s)
(transform N7datalog25mk_separate_negated_tailsE...no-op 0s)
(transform N7datalog24mk_similarity_compressorE...no-op 0s)
(transform N7datalog15mk_filter_rulesE...29 rules 0s)
(transform N7datalog15mk_simple_joinsE...87 rules 0.0885336s)
(transform N7datalog21mk_unbound_compressorE...

If I remove the "printtuples" annotation from the "state" predicate declaration then it completes quickly but it is not clear from the output whether it has done anything.

**Comment by NikolajBjorner** [comment]
The unbound compression transformation seems to explode on these higher-arity cases. I added an option to disable this pass: 
 
         z3 jpg.datalog /v:1 fixedpoint.xform.compress_unbound=false

It then finishes quickly.

Note however, that the default table representation in nuZ is based on sparse hash-tables. 
We don't have BDD based tables. The closest is a table representation based on ternary bit-vectors, which is used for network dataplane analysis in some applications, but generally it is not going to be suitable for datalog programs extracted from circuit-like scenarios.
So for this example, disable the unbound compression as illustrated above and it works, but if the set of reachable tuples explodes, the hash-table representation will not be adequate.

**Comment by jpgallagher** [comment]
Thanks Nikolaj, much appreciated.
