### ISSUE TITLE
Error during make due to invalid Makefile entry for `tactic.cpp`

### ISSUE THREAD

**Issue by WangYihang** [Z3Prover/z3#7385]
Issue Description:

When attempting to build Z3 using the generated Makefile, I encountered the following error:

```bash
Makefile:2261: *** missing separator.  Stop.
```

This seems to be caused by an invalid entry in the Makefile related to tactic.cpp:

```bash
includes_28 = -I../src/ast/simplifiers -I../src/ast/euf -I../src/ast -I../src/util -I../src/math/polynomial -I../src/ast/normal_forms -I../src/ast/rewriter -I../src/math/interval -I../src/math/automata -I../src/params -I../src/ast/rewriter/bit_blaster -I../src/ast/converters -I../src/model -I../src/ast/macros -I../src/ast/substitution -I../src
tactic/.#tactic$(OBJ_EXT): ../src/tactic/.#tactic.cpp
	@echo src/tactic/.#tactic.cpp <----- invalid Makefile entry
```

The file ./src/tactic/.#tactic.cpp appears to be a temporary or lock file, as it contains the following header:

```bash
$ find . -name '*tactic.cpp' | grep '#'
./src/tactic/.#tactic.cpp

$ cat ./src/tactic/.#tactic.cpp
nbjorner@LAPTOP-04AEAFKH.32880:1726092166
```

This entry is likely being included in the Makefile erroneously, causing the build process to fail. It would be helpful to investigate why this file is being referenced and to implement a solution to exclude it from the Makefile generation process.

Steps to reproduce:

+ Run python scripts/mk_make.py to generate the Makefile.
+ Execute make in the build directory.

```bash
$ python scripts/mk_make.py   
Set Assembly Version (DEFAULT): 4 13 1 0
New component: 'util'
New component: 'polynomial'
New component: 'interval'
...
Copied Z3Py example 'proofreplay.py' to 'build/python'
Makefile was successfully generated.
  compilation mode: Release
Type 'cd build; make' to build Z3

$ make
Makefile:2261: *** missing separator.  Stop.
```

Expected behavior: 

The build process should complete without errors.

Thank you for looking into this issue!

**Comment by NikolajBjorner** [comment]
I think it is fixed. I pushed a temporary file.
