### ISSUE TITLE
Missing tab in makefile

### ISSUE THREAD

**Issue by LeventErkok** [Z3Prover/z3#7386]
I usually build z3 out of sources with:

```
python3 scripts/mk_make.py --prefix=/usr/local --python --java
cd build
make
```

This started failing recently:

```
Makefile:2275: *** missing separator.  Stop.
```

Looking at the `Makefile`:

```
2275 tactic/.#tactic$(OBJ_EXT): ../src/tactic/.#tactic.cpp
```

And that line does look weird indeed. Though I don't think it's a tab issue. Feels like the correct line should be:

```
2275 tactic/tactic$(OBJ_EXT): ../src/tactic/tactic.cpp
```

Somehow `.#tactic` gets output there; which trips up `make`.

Looking at the `Makefile` further, I see couple of other places where `.#tactic` appears, all of which should be `tactic` I think.

I'm on MacOS if that makes a difference.

**Comment by NikolajBjorner** [comment]
temporary file removed
