### ISSUE TITLE
Simplification rule suggestions (Extract and ULEQ)

### ISSUE THREAD

**Issue by Notselwyn** [Z3Prover/z3#7397]
Hello, I noticed my program can spit out simplified z3 statements (indirectly) derived from `49 U<= bv8 U<= 58`, in the following manner:

```python3
Or(Not(Or(Not(And(Extract(7, 6, bv8) == 0,
                  Extract(7, 7, bv8) == 0)),
          And(Extract(7, 6, bv8) == 0,
              Extract(7, 7, bv8) == 0,
              ULE(Extract(5, 0, bv8), 48)),
          ULE(58, Extract(5, 0, bv8)))),
   bv8 == 58)
 ```
 
 Hence I wonder: would it be possible to recover and simplify this to the output below?
 
 ```py
And(Extract(7, 6, bv8) == 0,
    ULE(49, Extract(5, 0, bv8)),
    ULE(Extract(5, 0, bv8), 58))
```

I understand some of these rules may be trickier to implement than others, but I would love to know your opinion. Unfortunately I don't understand enough about the z3 codebase to create a PR.

### rule 1: deduplicating extract overlaps

To achieve it, you could add a rule which checks for overlapping `Extract` assertions within an `And` statement, such as:
```py
And(Extract(7, 6, bv8) == 0,
    Extract(7, 7, bv8) == 0,
    ...),
```
to
```py
And(Extract(7, 6, bv8) == 0, ...),
```

This would refactor the first assertion into:
```py
Or(Not(Or(Not(Extract(7, 6, bv8) == 0),
          And(Extract(7, 6, bv8) == 0,
              ULE(Extract(5, 0, bv8), 48)),
          ULE(58, Extract(5, 0, bv8)))),
   bv8 == 58)
```

### rule 2: `Or(Not(x), And(x, y)) -> Or(Not(x), y)`

```py
Or(Not(Or(Not(Extract(7, 6, bv8) == 0),
          And(Extract(7, 6, bv8) == 0,
              ULE(Extract(5, 0, bv8), 48)),
          ULE(58, Extract(5, 0, bv8)))),
   bv8 == 58)
```

can be simplified to:
```py
Or(Not(Or(Not(Extract(7, 6, bv8) == 0),
          ULE(Extract(5, 0, bv8), 48),
          ULE(58, Extract(5, 0, bv8)))),
   bv8 == 58)
```

### rule 3: `Not(Or(...)) -> And(...)`

```py
Or(Not(Or(Not(Extract(7, 6, bv8) == 0),
          ULE(Extract(5, 0, bv8), 48),
          ULE(58, Extract(5, 0, bv8)))),
   bv8 == 58)
```
to
```py
Or(And(Extract(7, 6, bv8) == 0,
       ULE(49, Extract(5, 0, bv8)),
       ULE(Extract(5, 0, bv8), 57)),
   bv8 == 58)
```

### rule 4: `Or(x==y, And(..., ULE(x, y-1)))` -> `And(..., ULE(x, y))`
```py
Or(And(Extract(7, 6, bv8) == 0,
       ULE(49, Extract(5, 0, bv8)),
       ULE(Extract(5, 0, bv8), 57)),
   bv8 == 58)
```
to
```py
And(Extract(7, 6, bv8) == 0,
    ULE(49, Extract(5, 0, bv8)),
    ULE(Extract(5, 0, bv8), 58))
```

**Comment by NikolajBjorner** [comment]
The simplifier is necessarily never going to canonize formulas into some minimal form.
You can write your own simplifier on top of z3:

https://microsoft.github.io/z3guide/programming/Example%20Programs/Formula%20Simplification
