### ISSUE TITLE
`opt.solution_prefix` & `opt-dump_models` not working

### ISSUE THREAD

**Issue by bruderj15** [Z3Prover/z3#7402]
Hello.

When playing around with the optimizer I stumbled on similar issues as in #1463 .
On `Ctrl-C` responding with `unknown` and the best known intermediate solution unfortunately does not yield any value.
Why can't it be `sat` instead?
Although not optimal, the model clearly is supposed to satisfy the constraints.

When trying to write intermediate solutions or dumping intermediate models nothing happens.
Should be reproducible with this: [foo.txt](https://github.com/user-attachments/files/17147013/foo.txt)

Version: 4.13.0

**Comment by NikolajBjorner** [comment]
The option :opt.solution_prefix had been bit-rotting. It wasn't enabled.
I have re-enabled it and put it in a place where the models get dumped to files.
There are some other ways to retrieve models:
- :opt.dump_models = true - prints the models to the console
- Using the programmatic API you can attach a callback when the solver has a model.
-
I would prefer to return unknown even if there is a model in this case to distinguish optimality from feasibility in the optimization scenario. The optimal remains "unknown".
