### ISSUE TITLE
Missing Java bindings for Linux on ARM64 in release 4.13.2

### ISSUE THREAD

**Issue by kfriedberger** [Z3Prover/z3#7406]
Dear Z3 developers,
I wanted to kindly suggest two improvements for your releases, especially for the Java bindings in your artifacts:

- always include Java bindings for all platforms (Java bindings are missing in the [artifact for Linux on ARM64 in release 4.13.2](https://github.com/Z3Prover/z3/releases/download/z3-4.13.2/z3-4.13.2-arm64-glibc-2.34.zip)).
- use a consistent directory structure (Java bindings for Windows are located in `/bin/java/` in the [ARM64 artifact](https://github.com/Z3Prover/z3/releases/download/z3-4.13.2/z3-4.13.2-arm64-win.zip) and in `/bin/` in the [x64 artifact](https://github.com/Z3Prover/z3/releases/download/z3-4.13.2/z3-4.13.2-x64-win.zip)).

Thank you for considering this in the next release, and for your great work on Z3!
Best.

**Comment by NikolajBjorner** [comment]
The current nightly should have it https://github.com/Z3Prover/z3/releases/tag/Nightly.
I will roll another release this week to get this in.

**Comment by kfriedberger** [comment]
Release [4.13.3](https://github.com/Z3Prover/z3/releases/tag/z3-4.13.3) seems to contain all wanted files. Thanks.

The file `Microsoft.Z3.dll` is included in both the Linux and macOS releases, but it's technically not required for those platforms, correct? Better to have an extra file than to miss one! :smile:

**Comment by NikolajBjorner** [comment]
Microsoft.Z3.dll is for .Net.
