### ISSUE TITLE
Z3py Solver.to_smt2() does not include recursive function definitions

### ISSUE THREAD

**Issue by keikun555** [Z3Prover/z3#7409]
Using 4.13.0.0
```
❯ pip freeze | grep z3
z3-solver==4.13.0.0
❯
```
Minimal example
```python
import z3

x = z3.Real("x")
func = z3.RecFunction(
    "func", z3.RealSort(), z3.RealSort()
)
z3.RecAddDefinition(func, [x], x)

solver = z3.Solver()
solver.add(func(0) > 0)

print(solver.to_smt2())
```
This does not define the recursive function `func`
```
❯ python3 temp.py
; benchmark generated from python API
(set-info :status unknown)
(assert
 (> ((_ func 0) 0.0) 0.0))
(check-sat)

❯
```
If we change `to_smt2` to `sexpr` we get the recursive definition
```
❯ python3 temp.py
(define-funs-rec ( ( func ((x!1 Real)) Real)) ( x!1))
(assert (> ((_ func 0) 0.0) 0.0))

❯
```

Is `define-funs-rec` not supported in `to_smt2`?

**Comment by NikolajBjorner** [comment]
Use the current release. It was fixed
C:\z3\build\python>type 7409.py
import z3

x = z3.Real("x")
func = z3.RecFunction(
    "func", z3.RealSort(), z3.RealSort()
)
z3.RecAddDefinition(func, [x], x)

solver = z3.Solver()
solver.add(func(0) > 0)

print(solver.to_smt2())

C:\z3\build\python>python 7409.py
; benchmark generated from python API
(set-info :status unknown)
(define-funs-rec ( ( func ((x!1 Real)) Real)) ( x!1))
(assert
 (> ((_ func 0) 0.0) 0.0))
(check-sat)
