### ISSUE TITLE
Simplification Parameters Not Restricting as Expected in Parallel Mode

### ISSUE THREAD

**Issue by stormckey** [Z3Prover/z3#7421]
When running z3 through `z3 parallel.enable=true parallel.threads.max=8 **.smt2"` , the function `simplify` in https://github.com/Z3Prover/z3/blob/62478db7d52c8fe20f4c67dd6101832634dee392/src/solver/parallel_tactical.cpp#L547 is called first. However, it appears that the parameters set to restrict the simplification process sometimes fail to work as expected.
For example, if I set the restart.max to 20 in https://github.com/Z3Prover/z3/blob/62478db7d52c8fe20f4c67dd6101832634dee392/src/solver/parallel_tactical.cpp#L357
Then run z3 with the `-v:2` verbose flag, I can easily observe that the simplification process continues even the restart count significantly exceeds 20.

A related issue is that the default behavior for simplification seems overly eager. For example, when running Z3 on a problem in the QF_SLIA logic, the first simplification step takes more than 20 minutes, effectively causing the parallel algorithm to behave like a sequential one due to the prolonged simplification.

**Comment by NikolajBjorner** [comment]
You are welcome to investigate and add pull request to resolve issues you encounter or tuning
