### ISSUE TITLE
Success response to check-sat command

### ISSUE THREAD

**Issue by Heizmann** [Z3Prover/z3#743]
When I apply Z3 to the [attached script](https://github.com/Z3Prover/z3/files/488468/20160923-SuccessResponseToCheckSat.smt.txt) the response to the check-sat command is not only ``unsat`` but more than 100 lines of ``success`` followed by ``unsat``.

**Comment by NikolajBjorner** [comment]
C:\z3\build>..\release\z3 hz.smt2
success
success
success
success
success
success
success
unsat

**Comment by Heizmann** [comment]
Sorry, I did not had the latest version of z3. I did an update, now I get the correct result.

**Comment by Heizmann** [comment]
Sorry again, my last comment was probably not correct. The problem is still there but you need the argument ``SMTLIB2_COMPLIANT=true`` to reproduce it.
(By the way, I think I do not need this argument. Without it, z3 seems to be sufficiently SMT-LIB compliant for the interaction with our software verifier)

**Comment by NikolajBjorner** [comment]
OK, thanks then. Fixed.
