### ISSUE TITLE
Z3 crashed: "pointer being freed was not allocated"

### ISSUE THREAD

**Issue by qsphan** [Z3Prover/z3#745]
I'm using Z3 via the Java API, there is an error that I do not know how to investigate.

    java(23878,0x10aea2000) malloc: *** error for object 0x7fb9db5526e0: pointer being freed was not allocated
    *** set a breakpoint in malloc_error_break to debug

I tried to update the latest version of Z3 from source, then this error disappeared on the program I was testing. However, it appeared again on a different program.

Could you please give me a hint what is the problem and how to fix it?

**Comment by wintersteiger** [comment]
This is too little information to pin down any one problem. I can only see that Java had some sort of problem, but this may be completely unrelated to Z3. When Java crashes it usually generates some sort of crash file, e.g., `hs_err_pid*.log` as discussed [here](http://stackoverflow.com/questions/8008558/how-to-set-location-of-jvm-crash-log-files). 

To replicate the error we'd need some problem input, e.g., your Java application (if small enough) or an API log file (see [Log.open(...)](http://z3prover.github.io/api/html/classcom_1_1microsoft_1_1z3_1_1_log.html#ad57f9410a40ded1858176a544ee0944d)).

**Comment by wintersteiger** [comment]
Closing this as too little information to debug.
