### ISSUE TITLE
Java api: the call to com.microsoft.z3.Native.INTERNALdelContext(Native Method) never ends

### ISSUE THREAD

**Issue by Scrates1** [Z3Prover/z3#7455]
Hi, I have updated the z3-turnkey to 4.13.0. And encountered this problem again：

I used z3 to solve the problem in a multithreaded environment, where each thread creates its own Context object. I call Context.close() to release the resource if there are some errors during the solving process, but occasionally I run into a situation where calling the native method while releasing the resource never ends.

The following is a record of thread monitoring using visualvm:

![image](https://github.com/user-attachments/assets/9fae7db6-feeb-40c8-92a5-16b3fe33eb80)

Thanks.

**Comment by NikolajBjorner** [comment]
Is this with the nightly build? 4.13.4?
I believe it was addressed in the current master but not yet the release.

**Comment by Scrates1** [comment]
Okay. It sometimes appears during normal use. I am using the Maven repository version, with the latest version being 4.13.0. (Here is the [link](https://mvnrepository.com/artifact/tools.aqua/z3-turnkey))After the latest version is released, I will try the latest version. (May I ask when the expected time is？) Thanks！

**Comment by NikolajBjorner** [comment]
4.13.4 is out
