### ISSUE TITLE
simple uninterpreted function solve runs forever

### ISSUE THREAD

**Issue by nlewycky** [Z3Prover/z3#7456]
Testcase:
```
(set-option :produce-models true)

(declare-fun g2 ((Int)(Int)) Int)
(assert (exists ((id Int)) (forall ((x Int)) (and
    (= (g2 x id) x)
    (= (g2 id x) x)
))))

(check-sat)
(get-model)
```

If you comment out either of the two `(= ...)` expressions, then the solve is immediate, it solves that the function ignores its parameters and produces 0. With both enabled, I've left it running over two hours to nothing.

Tested with `Z3 version 4.13.3 - 64 bit` and current git 4b72e517b7b37affe410390b242fc6d56032e855 .

**Comment by NikolajBjorner** [comment]
this is out of scope of the quantifier satisfiability module.
The model where g(0,0) = 0 and g(x,0) = x and g(0,x) = x and g(x,y) for x != 0, y != 0 can be anything has an infinite range.
If there is just one equation, g(id, x) = x it is possible to eliminate g using pre-processing.

**Comment by nlewycky** [comment]
I removed the other constraints to simplify the testcase, but are you saying that if I constrain the problem further then it should work?
