### ISSUE TITLE
Segmentation fault with Z3 in Python on Cygwin

### ISSUE THREAD

**Issue by houseofwealth** [Z3Prover/z3#7470]
I encountered a segmentation fault when running a Python program using Z3 4.8.4 where it was applying a tactic to an expression. So I installed the latest version 4.13.3 (well specifically I downloaded the Windows binary and set PATH and PYTHONPATH as shown below). I've had no problems running python and z3 from cygwin before but i'm on a different machine now. But now I get a segfault for the most trivial example:

```
$ python
Python 3.9.16 (main, Mar  8 2023, 22:47:22)
[GCC 11.3.0] on cygwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from z3 import *
>>> x = Int('x')
Segmentation fault
```

My PYTHONPATH and PATH are set as they were before
```
$ echo $PYTHONPATH
/cygdrive/c/ProgramFiles/z3-4.13.3/bin/python:..
$ echo $PATH
/cygdrive/c/ProgramFiles/z3-4.13.3/bin:...
```
Could someone let me know what the problem might be?

**Comment by NikolajBjorner** [comment]
This is typical for an installation where you invoke a stale DLL of z3. Check your python installations for z3lib/libz3.

**Comment by houseofwealth** [comment]
Sorry I don't understand how I could be using a stale DLL - I have a completely up to date installation of z3 (4.13.3) i just downloaded yesterday and both my PATH and PYTHONPATH point to it. There's a libz3.dll in there dated 10/10/2024

**Comment by houseofwealth** [comment]
Just to be sure I reinstalled cygwin64 but I still get the same segfault
