### ISSUE TITLE
Equation ordering is sometimes swapped

### ISSUE THREAD

**Issue by philzook58** [Z3Prover/z3#7476]
When building equation expressions, the order of the left hand side and right hand side of returned expression is sometimes swapped. Maybe when only one side has simplifications possible? While this isn't logically unsound, it is desirable for my application for the AST returned to closely match the way it was built and I don't recall having run into this before. Is this a bug or the intended behavior?

```python
import z3
x,y = z3.Ints("x y")
(x >= 14) == z3.Exists([y], x == 2 * y) # swaps order of equation (exists y, x == 2*y) == (x >= 14) 
(x >= 14) == z3.ForAll([y], x == 2 * y) # swaps order of equation  (forall y, x == 2*y) == (x >= 14) 
z3.IntVal(1) + z3.IntVal(2) == z3.IntVal(3) # swapped 3 == 1 + 2
z3.IntVal(3) == z3.IntVal(1) + z3.IntVal(2) # not swapped 3 == 1 + 2
z3.IntVal(2) + z3.IntVal(5)  == z3.IntVal(1) + z3.IntVal(2)  # not swapped 2 + 5 == 1 + 2
z3.get_version_string()  # '4.13.3'
```

**Comment by NikolajBjorner** [comment]
It is a python feature. The operator __eq__ is overloaded and apparently works with self being either on left or right side of equation. The operator __eq__ is defined in the ExprRef class and inherited to BoolRef and QuantifierRef. The order inheritance may play a role here. You can update z3.py to experiment.

**Comment by philzook58** [comment]
Thank you for the swift response, I was looking in the wrong places.

This is a workaround from outside of z3 which is sufficient for my purposes, albeit less efficient than what could be done from inside of z3py.

```python
def Eq(x,y):
    """Python __eq__ resolution rules flips the order if y is a subclass of x. This function corrects that."""
    e = (x == y)
    if issubclass(type(y), type(x)):
        return e.decl()(e.arg(1), e.arg(0))
    else:
        return e

assert Eq(IntVal(2) + IntVal(3), IntVal(5)).arg(1).eq(IntVal(5))
assert Eq((x >= 14), z3.Exists([y], x == 2 * y)).arg(0).eq(x >= 14)
```

These two cases occurs because IntVal(5) is `IntNumRef` whereas `2 + 3` is `ArithRef`. 

`QuantifierRef` is also a subclass of `BoolRef`. This is a bit of an odd choice since the addition of `Lambda` as quantifier.

I suppose changing this in `__eq__` would be fighting against python conventions, even if I think in this case they are a bit odd.
