### ISSUE TITLE
Z3 generates incorrect solution for string problem

### ISSUE THREAD

**Issue by pjljvandelaar** [Z3Prover/z3#748]
On the following problems

```
(set-option :produce-models true)
(set-info :smt-lib-version 2.5)
; regex = 0|(-?[1-9][0-9]*)
(define-fun ValidIntString ((s String)) Bool (str.in.re s (re.union (str.to.re "0") (re.++ (re.opt (str.to.re "-")) (re.range "1" "9") (re.* (re.range "0" "9"))))))
(define-fun IntToString ((i Int)) String (ite (< i 0) (str.++ "-" (int.to.str (- i))) (int.to.str i)))
(define-fun IntFromString ((s String)) Int (ite (= "-" (str.at s 0) )
                                                (- (str.to.int (str.replace s "-" ""))) 
                                                (str.to.int s) ))

(declare-fun int1() Int)
(declare-fun strInt1() String)
(assert (= int1 (IntFromString strInt1)))
(assert (ValidIntString strInt1))
(check-sat)
(get-value (int1 strInt1))

(declare-fun int2() Int)
(declare-fun strInt2() String)
(assert (= strInt2 (IntToString int2)))
(assert (ValidIntString strInt2))
(check-sat)
(get-value (int2 strInt2))
```

Z3 produces 

```
sat
((int1 (- 1))
 (strInt1 "0"))
```

and than doesn't produce a solution within a hour on my system.

In my opinion the provided answer to the first problem is wrong:, since ("0"<> "-") and (str.to.int "0" == 0)

Note: if I add

```
(declare-fun strInt() String)
(assert (= 0 (str.to.int strInt)))
(check-sat)
(get-value (strInt))
```

before these problems I get partially a better answer:

```
sat
((strInt "0"))
sat
((int1 (- 2))
 (strInt1 "-2"))
```

**Comment by NikolajBjorner** [comment]
I have addressed some bugs that have been causing incorrect model generation. 
The constraints remain elusive, though. Something that is simpler is the case of non-negative numbers.
Then a string corresponds to an integer if (= s (int.to.str (str.to.int s))). This can replace the regular expression. The expression that extracts sign bits would also be replaced by str.to.int, which makes the biggest difference.

**Comment by pjljvandelaar** [comment]
Thanks for the bug fixes.

**Comment by NikolajBjorner** [comment]
@mtrberzi: z3str3 reports unsat on this one. Seems they should be sat.
