### ISSUE TITLE
z3 does not turn (<= (+ (ite foo1 1 0) ...) n) into at-most n

### ISSUE THREAD

**Issue by jbosboom** [Z3Prover/z3#7483]
[10000_at-most.txt](https://github.com/user-attachments/files/18174366/10000_at-most.txt)
[10000_tree.txt](https://github.com/user-attachments/files/18174365/10000_tree.txt)

Both of these files declare 10000 bools and assert that at most 20 of them are true.  10000_at-most.txt uses the z3-specific `((_ at-most 20) r0 r1 ...)`, while 10000_tree.txt's assertion uses the portable expression `(<= (+ (ite r0 1 0) (ite r1 1 0) ...) 20)`.  I expect z3 to preprocess the latter into the former and thus perform similarly on both problems, but in fact z3 solves 10000_at-most.txt in less than a second and 10000_tree.txt in about 25 seconds.

Adding `(set-logic QF_LIA)` to 10000_tree.txt does not change the performance, but adding `(set-logic QF_NIA)` to 10000_tree.txt improves the time to about 1.5 seconds, still slower than at-most but faster than the linear solver (?).

My actual problem ([actual-problem.txt.gz](https://github.com/user-attachments/files/18174717/actual-problem.txt.gz)) asserts a boolean expression in addition to the arithmetic assertion implementing at-most.  When I used ddSMT to reduce that problem, it threw away the boolean assertion.  I then manually created the two examples in this issue.

**Comment by NikolajBjorner** [comment]
added lia2card tactic to default
