### ISSUE TITLE
Segfault with sat.smt=true, quantifiers and cardinality constraint

### ISSUE THREAD

**Issue by jbosboom** [Z3Prover/z3#7485]
Crash with z3 2f5c0a6985065cf161e9fb3298586214223dc3c8
[ddSMT-reduced.txt](https://github.com/user-attachments/files/18179596/fifth-reduced.txt)
This can be reduced further, but ddSMT is getting stuck slowly trying one mutation at a time even though I have 32 cores.  Do you use any other reduction tools?

Original [problem.txt](https://github.com/user-attachments/files/18179601/problem.txt), which also includes an enumeration datatype that ddSMT was able to eliminate.

**Comment by NikolajBjorner** [comment]
114cae50a57b52ac143f1476bcea60f14928018e
