### ISSUE TITLE
(Not important, Z3Py) Feature request: AtMin() as opposed to AtMost()

### ISSUE THREAD

**Issue by dennis714** [Z3Prover/z3#749]
Will it be?
Or there is another feature already exist which can be used instead?

**Comment by NikolajBjorner** [comment]
AtMost(a, b, c, 2) means a + b + c <= 2.
If you want to say a + b + c >= 2, then you can say so in the following way:

    a + b + c >= 2
iff
   -a - b - c <= -2
iff 
   (1 - a) + (1 - b) + (1 - c) <= -2 + 3
iff
   !a + !b + !c <= 1
iff
   AtMost(Not(a), Not(b), Not(c), 1)

In general, you can use a shorthand, along the lines of:

def AtLeast(vars, k):
      return AtMost([Not(v) for v in vars], len(vars) - k)

**Comment by dennis714** [comment]
Thanks!
