### ISSUE TITLE
smt.relevancy=0 produces wrong result

### ISSUE THREAD

**Issue by nunoplopes** [Z3Prover/z3#7491]
This commit makes the input below return SAT, while it should say UNSAT: https://github.com/Z3Prover/z3/commit/db9f45dfec790f6d83fb49b47b4795fb56712b79
(this commit was later reverted in https://github.com/Z3Prover/z3/commit/78ce6c1c6cb15a25363c921ffde9cccef15e3e6d)

```smt2
(declare-fun %s () (_ BitVec 12))
(declare-fun init_mem_1 () (Array (_ BitVec 10) (_ BitVec 4)))

(assert (let ((a!9 (select init_mem_1 ((_ extract 11 2) (bvadd #x280 %s)))))
(let ((a!13 (select (store init_mem_1 ((_ extract 11 2) %s) #x0)
                    ((_ extract 11 2) (bvadd #x280 %s)))))
  (not (= a!13 a!9)))))
(check-sat)
```
Running on the console with `smt.relevancy=0` (and auto_config=false) doesn't reproduce the problem, so there is something else weird going on.

**Comment by NikolajBjorner** [comment]
See fb5bbb8074d394865fb71ee11da9b2b5dfaa622d
It now is back to automatically setting relevancy=0 during auto-config.
All measurements have been that relevancy=2 works against benchmarks with bit-vectors.
If your measurements contradict this, I will have to revert this auto-config option.

**Comment by nunoplopes** [comment]
Seems to be working great, thank you!
The number of timeouts went down overall.
