### ISSUE TITLE
Z3 produces "unknown" on simple problem

### ISSUE THREAD

**Issue by ciobaca** [Z3Prover/z3#756]
Z3 produces unknown on the following problem:

(declare-const I Int)
(declare-const J Int)
(declare-const S Int)
(declare-const SP Int)
(declare-const N Int)
(assert (<= 0 I)) 
(assert (<= 0 J))
(assert (= S (/ (\* J (+ J 1)) 2)))
(assert (= SP (/ (\* (+ (- N I) 1) (+ I N)) 2)))
(assert (= (+ I J) (+ N 1)))
(check-sat)

By commenting out _any_ of the assertions, Z3 is able to find a model.

For example, commenting out the first assertion produces the following model:

(model 
  (define-fun S () Int
    0)
  (define-fun J () Int
    0)
  (define-fun SP () Int
    0)
  (define-fun I () Int
    1)
  (define-fun N () Int
    0)
)

But note that the first assertion holds in this model. Furthermore, assertions 3 and 4 are superfluous, since S and SP do not appear anywhere else.

I understand of course that Z3 cannot be complete, but I suspect that this behaviour is indeed a bug.

**Comment by NikolajBjorner** [comment]
maybe you mean to use "div" instead of "/"?
Z3 is best effort for non-linear integer arithmetic so will give up after exhausting resource bounds.

**Comment by ciobaca** [comment]
Using "div" makes it work better, thank you for the hint.

**Comment by wintersteiger** [comment]
Closing as resolved.
