### ISSUE TITLE
Z3 returns an incorrect model

### ISSUE THREAD

**Issue by letonchanh** [Z3Prover/z3#758]
I tried the following example with the latest source code as well as the recent nightly build  z3-4.4.2.5d9820f3e2d4 of Z3

    (declare-fun a () Int)
    (declare-fun b () Int)
    (declare-fun c () Int)
    (declare-fun l1 () Int)
    (declare-fun l2 () Int)
    (declare-fun l3 () Int)
    (declare-fun l4 () Int)

    (define-fun absolute ((x Int)) Int
        (ite (>= x 0) x (- x)))

    (assert (>= l1 0))
    (assert (>= l2 0))
    (assert (>= l3 0))
    (assert (>= l4 0))

    ;; |a| + |b| > 0
    (assert (> (+ (absolute a) (absolute b)) 0)) 

    ;; -l1 + l2 + a*l3 = 0
    (assert (= (+ (+ (- 0 l1) l2) (* a l3)) 0))
    ;; l1 - l2 + b*l3 = 0
    (assert (= (+ (+ l1 (- 0 l2)) (* b l3)) 0))
    ;; c*l3 + l4 = 0
    (assert (= (+ (+ (* c l3) l4) 1) 0))

    (minimize (+ (+ (absolute a) (absolute b)) (absolute c)))
    (check-sat)
    (get-model)

and the returned model is

    (a, -1), (b, 0), (c, -1), (l1, 0), (l2, 0), (l3, 1), (l4, 0)

which, I think, is incorrect because the model does not satisfy the assertion

    -l1 + l2 + a*l3 = 0

A possible model is

    (a, 1), (b, -1), (c, -1), (l1, 1), (l2, 0), (l3, 1), (l4, 0)

Could you please help to investigate the problem? Thank you.

**Comment by NikolajBjorner** [comment]
seems non-linear side-conditions are ignored during local optimization. Sorry, while I will try to address the soundness problem, you are unlikely to use Z3 in a constructive way when optimizing with non-linear integer constraints.

**Comment by letonchanh** [comment]
Thank you for your answer. I hope the bug will be fixed soon.

**Comment by NikolajBjorner** [comment]
fixed
