### ISSUE TITLE
cmake: libz3.so: undefined reference to __gmpz_*

### ISSUE THREAD

**Issue by jirislaby** [Z3Prover/z3#763]
@delcypher INTERFACE does not play well on my system. When I try to link against shared libz3, I get a lot of:

```
/usr/lib64/gcc/x86_64-suse-linux/6/../../../../lib64/libz3.so: undefined reference to `__gmpz_add'
/usr/lib64/gcc/x86_64-suse-linux/6/../../../../lib64/libz3.so: undefined reference to `__gmpn_popcount'
/usr/lib64/gcc/x86_64-suse-linux/6/../../../../lib64/libz3.so: undefined reference to `__gmpz_get_str'
```

I have to do this:

```
--- a/contrib/cmake/src/CMakeLists.txt
+++ b/contrib/cmake/src/CMakeLists.txt
@@ -138,7 +138,7 @@ endif()
 
 # Using INTERFACE means that targets that try link against libz3 will
 # automatically link against the libs in Z3_DEPENDENT_LIBS
-target_link_libraries(libz3 INTERFACE ${Z3_DEPENDENT_LIBS})
+target_link_libraries(libz3 ${Z3_DEPENDENT_LIBS})

```

to fix that. What's the purpose of INTERFACE actually?

```
$ ldd /usr/lib64/libz3.so
        linux-vdso.so.1 (0x00007ffe59dcb000)
        libstdc++.so.6 => /usr/lib64/libstdc++.so.6 (0x00007f4e172df000)
        libm.so.6 => /lib64/libm.so.6 (0x00007f4e16fdb000)
        libgomp.so.1 => /usr/lib64/libgomp.so.1 (0x00007f4e16dac000)
        libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007f4e16b95000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f4e16978000)
        libc.so.6 => /lib64/libc.so.6 (0x00007f4e165d7000)
        /lib64/ld-linux-x86-64.so.2 (0x0000556dfcd84000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00007f4e163d3000)
```
With the fix I see also:
`        libgmp.so.10 => /usr/lib64/libgmp.so.10 (0x00007ff5c5087000)`

**Comment by delcypher** [comment]
@jirislaby In what context are you trying to link against Z3?

> to fix that. What's the purpose of INTERFACE actually?
The `PUBLIC`, `INTERFACE` and `PRIVATE` keywords specify [usage requirements](https://cmake.org/cmake/help/v3.0/manual/cmake-buildsystem.7.html#transitive-usage-requirements).

However reading the docs I may have got this wrong.

```
Generally, a dependency should be specified in a use of target_link_libraries() with the PRIVATE keyword if it is used by only the implementation of a library, and not in the header files. If a dependency is additionally used in the header files of a library (e.g. for class inheritance), then it should be specified as a PUBLIC dependency. A dependency which is not used by the implementation of a library, but only by its headers should be specified as an INTERFACE dependency.
```

that probably means I should have used `PRIVATE` rather than `INTERFACE`. Although I'm curious. In changing from `INTERFACE` to `PRIVATE` what changes happen to the command line to the linker?

> ```
ldd /usr/lib64/libz3.so
        linux-vdso.so.1 (0x00007ffe59dcb000)
        libstdc++.so.6 => /usr/lib64/libstdc++.so.6 (0x00007f4e172df000)
        libm.so.6 => /lib64/libm.so.6 (0x00007f4e16fdb000)
        libgomp.so.1 => /usr/lib64/libgomp.so.1 (0x00007f4e16dac000)
        libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007f4e16b95000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f4e16978000)
        libc.so.6 => /lib64/libc.so.6 (0x00007f4e165d7000)
        /lib64/ld-linux-x86-64.so.2 (0x0000556dfcd84000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00007f4e163d3000)
```

With the current master branch of CMake. On my system if I run `ldd` on the installed `libz3.so` I see

```
ldd install/lib64/libz3.so
	linux-vdso.so.1 (0x00007ffe331c5000)
	libstdc++.so.6 => /usr/lib/libstdc++.so.6 (0x00007fb1d01c0000)
	libm.so.6 => /usr/lib/libm.so.6 (0x00007fb1cfebc000)
	libgomp.so.1 => /usr/lib/libgomp.so.1 (0x00007fb1cfc8e000)
	libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0x00007fb1cfa77000)
	libpthread.so.0 => /usr/lib/libpthread.so.0 (0x00007fb1cf85a000)
	libc.so.6 => /usr/lib/libc.so.6 (0x00007fb1cf4bc000)
	/usr/lib64/ld-linux-x86-64.so.2 (0x00005616ba5fd000)
	libdl.so.2 => /usr/lib/libdl.so.2 (0x00007fb1cf2b6000)
```

So on my system the linker knows where to find `libgomp`.

**Comment by delcypher** [comment]
Oh. Now I'm more confused on my system `${Z3_DEPENDENT_LIBS}` is `-lpthread`.

Changing `INTERFACE` to `PRIVATE` adds `-lpthread` to the end of the link command line.

What does libgmp have to do with this?

**Comment by jirislaby** [comment]
On 10/17/2016, 04:06 PM, Dan Liew wrote:
> So on my system the linker knows where to find |libgomp|.

gomp and gmp are two different libs :).


-- 
js

**Comment by jirislaby** [comment]
On 10/17/2016, 04:11 PM, Dan Liew wrote:
> Oh. Now I'm more confused on my system |${Z3_DEPENDENT_LIBS}| is
> |-lpthread|.

Maybe your system does not support gmp?

> Changing |INTERFACE| to |PRIVATE| adds |-lpthread| to the end of the
> link command line.

btw, -lpthread is not the documented way (see man pthreads). -pthread
should be used because gcc will do other things than just a linking to
libpthread.

-- 
js

**Comment by delcypher** [comment]
> gomp and gmp are two different libs :).
@jirislaby: Facepalm. You're right. You must be using the libgmp support. I've not tested it all that much.

**Comment by delcypher** [comment]
> btw, -lpthread is not the documented way (see man pthreads). -pthread
should be used because gcc will do other things than just a linking to
libpthread.

This comes from 

```cmake
find_package(Threads)
list(APPEND Z3_DEPENDENT_LIBS ${CMAKE_THREAD_LIBS_INIT})
```

The `Threads` package needs to be fixed upstream if you want to correct this.

**Comment by delcypher** [comment]
@jirislaby Okay I've tested building with libgmp support enabled. You're right this is a mistake on my part. I'm just testing the static library build now and I'll create a PR once I've tested a little more.

**Comment by delcypher** [comment]
@jirislaby #764 fixes this bug and a few others I found during brief testing.
