### ISSUE TITLE
Sort mismatch at argument #1 for function (declare-fun = (Real Real) Bool)

### ISSUE THREAD

**Issue by cocreature** [Z3Prover/z3#766]
When running z3 build at commit fefd00aa4980dd7410f2315a6e3033c349f6b266 on the input file shown below, I get the error message:

```
(error "query failed: Sort mismatch at argument #1 for function (declare-fun = (Real Real) Bool) supplied sort is Int")
```

Judging by the error messages I received for other input files it seems like `duality` doesn’t support mixing reals and integers, so this is probably just a confusing error message rather than an actual bug. This example doesn’t use `=` anywhere. (I removed everything possible from the example so it’s pretty meaningless at this point).

``` smt
(set-logic HORN)
(set-option :fixedpoint.engine duality)
(set-option :int-real-coercions false)
(declare-var HEAP (Array Int Int))
(declare-var a Int)
(declare-var i Int)
(declare-var n Int)
(declare-var s Real)
(declare-rel QUERY ())
(declare-rel Inv (Int Int Int Real (Array Int Int)))
(rule
 (=> (not (<= n 0))
     (Inv 0 a n 0.0 HEAP)))
(rule
 (=> (and (Inv i a n s HEAP) (>= i n))
     QUERY))
(rule
 (=> (Inv i a n s HEAP)
     (Inv i a n (/ (to_real (select HEAP a)) (to_real n)) HEAP)))
(query QUERY)
```

**Comment by NikolajBjorner** [comment]
Closing as the code that was exercised in this issue is no longer part of the code base, #1646.
