### ISSUE TITLE
Problem when setting timeout for Z3 with OCaml interface

### ISSUE THREAD

**Issue by tddsg** [Z3Prover/z3#769]
Hi there,

I'm using Z3 with OCaml interface and when trying to set a timeout for Z3, I encounter the following problem:

> WARNING: unknown parameter 'timeout'
> Legal parameters are:
>   auto_config (bool) (default: true)
>   debug_ref_count (bool) (default: false)
>   dump_models (bool) (default: false)
>   model (bool) (default: true)
>   model_validate (bool) (default: false)
>   proof (bool) (default: false)
>   rlimit (unsigned int) (default: 4294967295)
>   smtlib2_compliant (bool) (default: false)
>   timeout (unsigned int) (default: 4294967295)
>   trace (bool) (default: false)
>   trace_file_name (string) (default: z3.log)
>   type_check (bool) (default: true)
>   unsat_core (bool) (default: false)
>   well_sorted_check (bool) (default: false)

According to the error message, I think that the "timeout" parameter is correct, as it is reported that "timeout (unsigned int) (default: 4294967295)"

Do you know why Z3 reports this error?

I'm using Z3 4.4.1 on Linux, and the OCaml code that I used to set timeout is:

```
  let ctx_config = [("model", "false");
                    ("proof", "false");
                    ("timeout", "10000")] in
  let ctx = Z3.mk_context ctx_config in
  ...
```

Thanks for taking your time to look at this issue!

**Comment by wintersteiger** [comment]
I can't reproduce that; it seems to work fine using the latest code. Version 4.4.1 was the last binary release, which is over a year old and many changes have been made since (including changes to the ML API). Please compile Z3 from the lastest master source instead.

**Comment by tddsg** [comment]
Thanks for your feedback. I tried the newest code of Z3 and encountered the following error:

`undefined symbol: Z3_get_full_version`

The revision that I tried is:

```

46a4bc6030df3aa764400268159f6de6bb3efeb1
Author: Nikolaj Bjorner <nbjorner@microsoft.com>  2016-11-02 22:15:05
Committer: Nikolaj Bjorner <nbjorner@microsoft.com>  2016-11-02 22:15:05
Parent: f61600d1d833fff241376ad340244068fe7ece21 (fixing unsat core extraction for tactics)
Parent: c8689ed796cf5e3e0c183ec6aee8039215e2bcf4 (Merge branch 'master' of https://github.com/Z3Prover/z3)
Branches: master, remotes/origin/master
Follows: z3-4.4.1
Precedes: 

    Merge branch 'master' of https://github.com/Z3Prover/z3
```

This issue is also mentioned here: https://github.com/angr/claripy/issues/26

I wonder if it is fixed for Z3 Ocaml?

**Comment by wintersteiger** [comment]
Note that angr-z3 is a modified version of Z3 and I can't see how this particular issue is related to angr, but it probably means that something in your build has gone wrong. `Z3_get_full_version` has been there for a very long time, but for your local build you may have to re-run `mk_make.py` to re-generate the updated API layer files (z3native.ml for the OCaml API). The .dll/.so/.dylib has to be accessible as well of course.

**Comment by NikolajBjorner** [comment]
issue seem stale
