### ISSUE TITLE
fp - Weird float behavior around conversions?

### ISSUE THREAD

**Issue by LeventErkok** [Z3Prover/z3#77]
I've the following benchmark:

```
(set-option :produce-models true)
(set-logic QF_FP)

; A free variable x
(declare-fun x () (_ FloatingPoint 11 53))

; Let y be the ulp
(define-fun  y () (_ FloatingPoint 11 53) (fp #b0 #b00000000000 #x0000000000001))

; Assert that x and y are floating-point equal.
(assert (fp.eq x y))

; Compute the conversion from double-to-float for each
(define-fun xf () (_ FloatingPoint 8 24) ((_ to_fp 8 24) roundNearestTiesToEven x))
(define-fun yf () (_ FloatingPoint 8 24) ((_ to_fp 8 24) roundNearestTiesToEven y))

; Results should be precisely the same float; so the following should be unsat
(assert (not (= xf yf)))

(check-sat)

(get-model)
```

It looks hairy; but it's essentially creating the smallest double value in `y`, and then asserts that `x` is floating-point equal to `y`. Which would only be satisfiable when `x` is also the smallest double. Then it goes ahead and casts them both to single-precision values; and asserts that the result should be the different. That query should be unsatisfiable; as both conversions should yield `+0`.

But when run, Z3 produces:

```
sat
(model
  (define-fun x () (_ FloatingPoint 11 53)
    (fp #b0 #b00000000000 #x0000000000001))
)
```

What's weird is that it says the model is satisfiable; but then suggests `x` must be the smallest double itself; i.e., in the model it created, the conversion to single-precision through `xf` and `yf` should be patently equal; thus making the query itself `unsat`.

**Comment by wintersteiger** [comment]
I can't replicate this problem and it's quite possible that one of the other recent FP fixes accidentally also fixed this one. Could you confirm that the problem still exists?

**Comment by LeventErkok** [comment]
@wintersteiger I can't replicate it either; but given #102, I'm not sure if this problem is really gone or just hidden..

**Comment by wintersteiger** [comment]
Thanks for reporting this, there was indeed a bug in the float-to-float conversion. I've committed a fix for this and will close this tomorrow once the tests are through.
