### ISSUE TITLE
Presence of lblpos or lblneg changes the outcome of a query

### ISSUE THREAD

**Issue by nikswamy** [Z3Prover/z3#771]
I have been experiencing unpredictable behavior with Z3 version 4.4.1.
I'm attaching four files (very large, sorry). 

Basically, the problem I have is something like this:

A formula like this one is deemed valid:

```
(implies (forall ((x Term)). (! (implies (p x) (q x) :pattern ((q x)))))
              (q x))
```

But, a formula like this times out (for some uninterpreted boolean `l`).

Case 1:
```
(implies (forall ((x Term)) (! (implies (or l (p x)) (q x) :pattern ((q x)))))
              (q x))
```

If I try variants like

Case 2:
```
(implies (forall ((x Term)) (! (implies (! (or l (p x)) :lblpos xx) (q x) :pattern ((q x)))))
              (q x))
```

or
 
Case 3:
```
(implies (forall ((x Term)) (! (implies (! (or l (p x)) :lblneg xx) (q x) :pattern ((q x)))))
              (q x))
```

Then I start to see behavior that is very hard to predict for some examples. 

The four files below:

[q4-no-lbl-fails.smt2.txt](https://github.com/Z3Prover/z3/files/565079/q4-no-lbl-fails.smt2.txt) This is analogous to case 1, above. There are some disjuncts introduced and the query times out.

[q4-ok.smt2.txt](https://github.com/Z3Prover/z3/files/565068/q4-ok.smt2.txt) This query should be equivalent to the previous one, except some terms are marked with a lblpos and it succeeds quickly.

[q4-fails-lblpos.smt2.txt](https://github.com/Z3Prover/z3/files/565070/q4-fails-lblpos.smt2.txt) This query is identical to the previous one, except more terms are marked lblpos and it times out. 

[q4-ok-lblneg.smt2.txt](https://github.com/Z3Prover/z3/files/565071/q4-ok-lblneg.smt2.txt) This one is identical to the previous one, but some lblpos are turned into lblneg and the query succeeds quickly. 

Any hints as to what's going on and how I might avoid this unpredictability would be much appreciated. 

Thanks!

**Comment by NikolajBjorner** [comment]
For diagnostics, I try to use different random seeds to determine if the fluctuation is related to how the search order proceeds. Sometimes, random seeds have an effect.
On the latest code, also q4-fails-lblpost.smt2, succeeds pretty quickly, but changing the random seed does have an effect. Use "smt.random_seed=<num>" as a command-line option.

The other things one can observe is use of expensive features, such as Groebner basis computation for non-linear formulas. This is visible when running with verbosity set to some suitably high value, e.g. /v:10. Groebner features can be turned off using the parameters in the smt namespace.
