### ISSUE TITLE
5.downto(1) { |i| print (81 + 7.3 * Math::sin(i - 5.75)).floor.chr } in Ruby

### ISSUE THREAD

**Issue by 0xor** [Z3Prover/z3#772]
Is possible to using Z3 for other function than + or - ?
for example Sin() cos() floor abs() etc.

is possible to generating 'word' similar in title?

**Comment by NikolajBjorner** [comment]
Yes

**Comment by NikolajBjorner** [comment]
But transcendental functions are only partially interpreted
