### ISSUE TITLE
Compilation failure on Windows 10

### ISSUE THREAD

**Issue by SeanHeelan** [Z3Prover/z3#773]
After using the following command line to produce the build directory:

```c:\Users\sean\Source\Repos\z3>c:\Python27\python.exe scripts/mk_make.py --dotnet --python --pypkgdir=C:\Users\Sean\Source\Repos\src\env\Lib\site-packages --parallel=8 -x```

I get the following error when running `nmake` from the Visual Studio command line terminal:

```C:\Program Files (x86)\Windows Kits\8.1\include\um\winbase.h(8848): error C3861: '_InterlockedIncrement64': identifier not found (compiling source file ..\src\shell\datalog_frontend.cpp)```

I am on a 64-bit version of Windows 10. If there's any further information required let me know!

**Comment by Evilcry** [comment]
Probably it's the same case: http://stackoverflow.com/questions/35286374/error-when-building-64-bit-z3-on-windows

**Comment by wintersteiger** [comment]
When building on Windows make sure that you are using the right Visual Studio Command Prompt. If the command prompt (and thus the compiler) is set up for 32-bit, then using the -x flag will throw errors. For your configuration you want to use the "VS2015 x64 Native Tools Command Prompt".

**Comment by SeanHeelan** [comment]
Ah, that would indeed seem like the problem.
