### ISSUE TITLE
print out the symbolic formulas with Python binding

### ISSUE THREAD

**Issue by computereasy** [Z3Prover/z3#774]
I am using the `z3 Python` to analysis some programs. Currently, I would like to print out some (large) symbolic formulas out. However, it seems that such formulas are always **cut** to some degree..

For example:

    print f            <--------- f is a very large formula!
    
    2969415988 +
    Concat(Concat(0,
              Extract(5,
                      5,
                      4294967295*
                      Concat(0,
                             If(Extract(31,
                                        1,
                                        LShR(Concat(0,
                                        Extract(31,
                                        27,
                                        2*
                                        (symbol1 <<
                                        Concat(0,
                                        ~If(... == ...,   <------ it is omitted for some reason.
                                        31,
                                        If(..., ..., ...)))) <<
                                        Concat(0,
                                        ~If(Extract(31,
                                        31,
                                        ...*(...)) ==  <------ it is omitted for some reason.
                                        1,
                                        31,
                                        If(Extract(30,
                                        30,
                                        ...) ==  <------ it is omitted for some reason.
                                        1,
                                        2*
                                        (symbol1 <<
                                        Concat(..., ...)) <<  <------ it is omitted for some reason.
                                        Concat(0,
                                        ~If(..., ..., ...))) ==  <------ it is omitted for some reason.
                                        1,
                                        1,
                                        If(Extract(29,
                                        29,
      ...          <------ it is omitted for some reason.

As you can see from the above example, many places in the formula is omitted for some reason... Here is my question, **is there any way that I can fully print out a large formula in `z3 Python`?** 

I also posted a question on the stackoverflow. Sorry about this but this is really important to me, I am in rush for a deadline soon... I really appreciate if anyone can give me some help on this.

**Comment by NikolajBjorner** [comment]
There are two ways:

1. You can use print f.sexpr(). This prints the formula in the SMT-LIB2 syntax. It uses let-expressions to compress common sub-expressions.
2. You can use set_pp_option(max_visited=10000000) set_pp_option(max_depth=1000000) to avoid elipses.

Generally speaking, the python pretty printer takes more overhead than the native SMT-LIB2 pretty printer, and is really best targeted at small formulas.

You can also create a solver object, assert the formula, and then use the sexpr() method on the solver object to pretty print the asserted formulas as a benchmark.

**Comment by disconnect3d** [comment]
> You can use set_pp_option(max_visited=10000000) set_pp_option(max_depth=1000000) to avoid elipses.

The `z3-solver-4.8.5.0` doesn't have those kwargs in `set_pp_option`. Is there any other way to get this behavior?
