### ISSUE TITLE
Updates to optimize module in ML interface

### ISSUE THREAD

**Issue by NikolajBjorner** [Z3Prover/z3#776]
The signature of get_lower and get_upper can be improved.
It currently has signature:

  (** Retrieve lower bound in current model for handle *)
  val get_lower : handle -> int -> Expr.expr

  (** Retrieve upper bound in current model for handle *)
  val get_upper : handle -> int -> Expr.expr

And the implementation is:
  let get_lower (x:handle) (idx:int) = Z3native.optimize_get_lower (gc x.opt) x.opt idx
  let get_upper (x:handle) (idx:int) = Z3native.optimize_get_upper (gc x.opt) x.opt idx

The intent with the handle is to encode opaquely the index that gets passed.
The implementation should be along the lines of:

  (** Retrieve lower bound in current model for handle *)
  val get_lower : handle -> Expr.expr

  (** Retrieve upper bound in current model for handle *)
  val get_upper : handle -> Expr.expr

with:

  let get_lower (x:handle)  = Z3native.optimize_get_lower (gc x.opt) x.opt x.h
  let get_upper (x:handle)  = Z3native.optimize_get_upper (gc x.opt) x.opt x.h

A few newer APIs can also be added:

val  from_file : optimize -> string -> unit
val  from_string : optimize -> string -> unit
val get_assertions : optimize -> Expr.expr list
val get_objectives : optimize -> Expr.expr list

**Comment by wintersteiger** [comment]
Done, both added. It compiles, so I assume it's correct :)

**Comment by NikolajBjorner** [comment]
Amazing, this is what I would call a super advanced cloud service. I don't have the right OCaml installation to compile this myself, so I invoke a cloud service as a GitHub issue. The botnet picks up the spec and automatically invokes its deep neural network to turn the NLP spec into code. OCaml for Z3 in the cloud blows me away!

**Comment by wintersteiger** [comment]
Lol!
