### ISSUE TITLE
Muz PDR engine wrongly concludes that some definition is unsat

### ISSUE THREAD

**Issue by mlemerre** [Z3Prover/z3#777]
The attached file is wrongly proved as UNSAT by the PDR engine in latest master. If I replace PDR with CLP, then z3 concludes "SAT", which I believe is the right answer

[debug.txt](https://github.com/Z3Prover/z3/files/574226/debug.txt)

**Comment by NikolajBjorner** [comment]
Thanks, this should be fixed.

**Comment by mlemerre** [comment]
Thanks, I think that fixes all the unsoundness cases that I have seen.
