### ISSUE TITLE
Literature discussing how the simplify works

### ISSUE THREAD

**Issue by computereasy** [Z3Prover/z3#778]
Hi there,

I am sorry if this question is off-topics. I am wondering if there is any literature **high-levelly** explaining how to `Z3` simplify works? We heavily leverage this command to simplify some formulas (`Z3Py`) in our research work, and we would like to refer to the design of this `simplify` command to explain how it works....

Could you send me some pointers on this topic? Thank you!

**Comment by wintersteiger** [comment]
There is no high-level literature, but the source code is not particularly hard to read. See [th_rewriter.cpp](https://github.com/Z3Prover/z3/blob/master/src/ast/rewriter/th_rewriter.cpp), which applies some theory-independent simplification rules and then calls out to the various theory-rewriters, for instance `m_b_rw`, the [bool_rewriter](https://github.com/Z3Prover/z3/blob/master/src/ast/rewriter/bool_rewriter.cpp).
