### ISSUE TITLE
expr substitution returns z3::exception "type error"

### ISSUE THREAD

**Issue by mm95** [Z3Prover/z3#783]
I use z3 c++ api. I create a copy from exprs in expr_vector1 and store them in new expr_vector2 and then call

         for(unsigned j = 0; j < exprs_vector1.size();++j){
            expr v = exprs_vector1[j];
            uint32_t size; // it is initialized somehow.

            std::stringstream name;
            name << v <<"_"<< i;
            expr var(ctx);
            if(v.is_bool())
                var = sctx->ctx.bool_const(name.str().c_str());
            else if(v.is_bv())
                var = sctx->ctx.bv_const(name.str().c_str(), size);
            exprs_vector2.push_back(var);

            }    
       formula.substitute( expr_vactor1, expr_vector2); // this line causes error
but I get z3 exception with message "type error". Note that these two vector have the same size and their expressions correspondingly have the same sort and exprs are kind of bool or bitvector.
the z3 log file was attached too.

[z3.docx](https://github.com/Z3Prover/z3/files/583696/z3.docx)

**Comment by NikolajBjorner** [comment]
Could you call the Z3_open_log command:
- _before_ any other calls to Z3? The current log file does not replay because it refers to pointers created before the log file was created.
- preferably with a suffix different than "docx". The suffix "log" is understood by z3 by default.

**Comment by mm95** [comment]
I called z3_open_log command before any other call to z3 and attached  the log file.
thanks for your help.[
[z3.log.zip](https://github.com/Z3Prover/z3/files/584030/z3.log.zip)
](url)

**Comment by NikolajBjorner** [comment]
The log file indicates that you are creating two separate contexts. You can't mix expressions from different contexts. This causes the type checker to believe that there are two different versions of 32 bit bit-vectors.
There are facilities for translating expressions between contexts if you need this for spawning threads. Typically you just want to use a single context.
