### ISSUE TITLE
Segfault in optimizer

### ISSUE THREAD

**Issue by chadbrewbaker** [Z3Prover/z3#785]
Fresh build. Segfaults on this input, but not 100% of the time:

(declare-fun |ku'0'| () Int)
(declare-fun |ku'1'| () Int)
(declare-fun |ku'4'| () Int)
(declare-fun |ku'3'| () Int)
(declare-fun |ku'2'| () Int)
(assert (and (>= |ku'0'| 0) (<= |ku'0'| 1)))
(assert (= |ku'0'| 1))
(assert (and (>= |ku'1'| 0) (<= |ku'1'| 1)))
(assert (>= (+ |ku'1'| |ku'2'| |ku'3'| |ku'4'|) 1))
(assert (and (>= |ku'2'| 0) (<= |ku'2'| 1)))
(assert (>= (+ |ku'2'| |ku'3'|) 1))
(assert (and (>= |ku'3'| 0) (<= |ku'3'| 1)))
(assert (>= (+ |ku'3'| |ku'2'|) 1))
(assert (and (>= |ku'4'| 0) (<= |ku'4'| 1)))
(assert (>= (+ |ku'4'| |ku'2'| |ku'3'|) 1))
(minimize (+ |ku'0'| |ku'1'| |ku'2'| |ku'3'| |ku'4'|))
(check-sat)

---core dump--
* thread #1: tid = 0x0000, 0x00007fff8d5ecdda libsystem_kernel.dylib`__pthread_kill + 10, stop reason = signal SIGSTOP
  * frame #0: 0x00007fff8d5ecdda libsystem_kernel.dylib`__pthread_kill + 10
    frame #1: 0x00007fff8d6d8787 libsystem_pthread.dylib`pthread_kill + 90
    frame #2: 0x00007fff8d503497 libsystem_c.dylib`raise + 26
    frame #3: 0x00007fff8d6cbbba libsystem_platform.dylib`_sigtramp + 26
    frame #4: 0x000000010e085f30 libz3.dylib`sat::solver::get_reachable(sat::literal, sat::literal_set const&, sat::literal_set&) + 336
    frame #5: 0x000000010e085b6a libz3.dylib`sat::solver::find_mutexes(svector<sat::literal, unsigned int> const&, vector<svector<sat::literal, unsigned int>, true, unsigned int>&) + 858
    frame #6: 0x000000010d54fc0c libz3.dylib`inc_sat_solver::find_mutexes(ref_vector<expr, ast_manager> const&, vector<ref_vector<expr, ast_manager>, true, unsigned int>&) + 380
    frame #7: 0x000000010d506ee4 libz3.dylib`maxres::process_mutex() + 52
    frame #8: 0x000000010d506873 libz3.dylib`maxres::mus_solver() + 83
    frame #9: 0x000000010d50fa47 libz3.dylib`opt::maxsmt::operator()() + 455
    frame #10: 0x000000010d5170d4 libz3.dylib`opt::context::execute_maxsat(symbol const&, bool, bool) + 260
    frame #11: 0x000000010d5159ab libz3.dylib`opt::context::optimize() + 459
    frame #12: 0x000000010d4ecb77 libz3.dylib`Z3_optimize_check + 183
    frame #13: 0x00007fff8c51bf1c libffi.dylib`ffi_call_unix64 + 76
    frame #14: 0x00007fff8c51c7b1 libffi.dylib`ffi_call + 937
    frame #15: 0x000000010ce3979a _ctypes.so`_ctypes_callproc + 591
    frame #16: 0x000000010ce33de9 _ctypes.so`___lldb_unnamed_symbol18$$_ctypes.so + 1054
    frame #17: 0x000000010c80475b Python`PyObject_Call + 99
    frame #18: 0x000000010c87f7eb Python`PyEval_EvalFrameEx + 11223
    frame #19: 0x000000010c8834d5 Python`___lldb_unnamed_symbol1476$$Python + 264
    frame #20: 0x000000010c87feae Python`PyEval_EvalFrameEx + 12954
    frame #21: 0x000000010c8834d5 Python`___lldb_unnamed_symbol1476$$Python + 264
    frame #22: 0x000000010c87feae Python`PyEval_EvalFrameEx + 12954
    frame #23: 0x000000010c87ca1e Python`PyEval_EvalCodeEx + 1617
    frame #24: 0x000000010c883442 Python`___lldb_unnamed_symbol1476$$Python + 117
    frame #25: 0x000000010c87feae Python`PyEval_EvalFrameEx + 12954
    frame #26: 0x000000010c8834d5 Python`___lldb_unnamed_symbol1476$$Python + 264
    frame #27: 0x000000010c87feae Python`PyEval_EvalFrameEx + 12954
    frame #28: 0x000000010c87ca1e Python`PyEval_EvalCodeEx + 1617
    frame #29: 0x000000010c87c3c7 Python`PyEval_EvalCode + 48
    frame #30: 0x000000010c89c63d Python`___lldb_unnamed_symbol1599$$Python + 53
    frame #31: 0x000000010c89c6e0 Python`PyRun_FileExFlags + 133
    frame #32: 0x000000010c89c231 Python`PyRun_SimpleFileExFlags + 702
    frame #33: 0x000000010c8adbca Python`Py_Main + 3094
    frame #34: 0x00007fff8d4be255 libdyld.dylib`start + 1
    frame #35: 0x00007fff8d4be255 libdyld.dylib`start + 1

**Comment by NikolajBjorner** [comment]
This should be the location of the bug that was supposedly fixed. 
Either check if the dll the script is running against is up to date, or open a log file before any other calls to Z3 by invoking Z3_open_log("z3.log"). The log file should then be able to reproduce the bug assuming you are not using threads. If you are using threads, then of course be careful to not use the same context across threads.

**Comment by chadbrewbaker** [comment]
Shelling out in a Haskell script that calls the Z3 python bindings, not the SMT2 stdio interface. 

https://github.com/chadbrewbaker/endoscope/blob/master/src/min_dom_z3.py

Will try again with a nightly build to make sure it isn't a problem with my compile.

**Comment by chadbrewbaker** [comment]
Seems to be fixed on 6204f67.  Think it can be closed.
