### ISSUE TITLE
kind() of uninterpreted function

### ISSUE THREAD

**Issue by pennyan** [Z3Prover/z3#786]
Hi, I'm using kind() function to test the kind of an uninterpreted function declaration and I'm puzzled at what I got. I'm using the Python interface. Here is the code:

```
from z3 import *
f = Function('f', IntSort(), IntSort())
f.kind() == Z3_OP_UNINTERPRETED
```

This piece of code returns False. Shouldn't that be True instead?

Printing the two constants I got:

```
>>> Z3_OP_UNINTERPRETED
2093
>>> f.kind()
2352L
```
Thanks for the help!

**Comment by NikolajBjorner** [comment]
Testing on the current version of Z3 and it produces "True", and use the number 3553 of Z3_OP_UNINTERPRETED.

**Comment by pennyan** [comment]
Thanks for checking! I've found the problem. My z3 isn't properly installed and Python is picking up an older version of z3 I installed long time ago.
