### ISSUE TITLE
Python 2 installation issue: UnicodeEncodeError: 'ascii' codec can't encode character u'\xa9' in position 35: ordinal not in range(128)

### ISSUE THREAD

**Issue by legendtang** [Z3Prover/z3#787]
```
Traceback (most recent call last):
  File "scripts/mk_make.py", line 21, in <module>
    mk_makefile()
  File "/home/legend/bitbucket/z3-git/scripts/mk_util.py", line 2567, in mk_makefile
    mk_config()
  File "/home/legend/bitbucket/z3-git/scripts/mk_util.py", line 2434, in mk_config
    if is_CXX_clangpp():
  File "/home/legend/bitbucket/z3-git/scripts/mk_util.py", line 885, in is_CXX_clangpp
    return is_clang_in_gpp_form(CXX)
  File "/home/legend/bitbucket/z3-git/scripts/mk_util.py", line 881, in is_clang_in_gpp_form
    return str(version_string).find('clang') != -1
UnicodeEncodeError: 'ascii' codec can't encode character u'\xa9' in position 35: ordinal not in range(128)
```

when running `python scripts/mk_make.py` command. I've found that the CXX env refers to `g++` with native language characters (e.g. Chinese one is `g++ (GCC) 6.2.1 20160830
Copyright © 2016 Free Software Foundation, Inc.
本程序是自由软件；请参看源代码的版权声明。本软件没有任何担保；
包括没有适销性和某一专用目的下的适用性担保。`) thus it cannot resolve non-ASCII characters by default. Manually insert `sys.setdefaultencoding('utf-8')` works fine.

**Comment by NikolajBjorner** [comment]
I don't see sys.setdefaultencoding in python 2.7.11. v3 and v2 have slightly different conventions here, so fixing this issue would require testing on both versions.

**Comment by legendtang** [comment]
@NikolajBjorner Yes, you have [this](https://docs.python.org/2.7/library/sys.html#sys.setdefaultencoding). Python v3 already use Unicode by default so it works fine. But apparently, simply setting `sys.setdefaultencoding` is also harmful.

**Comment by NikolajBjorner** [comment]
update_api.py uses an auxiliary function, 

   def _to_ascii(s):
     if isinstance(s, str):
       return s.encode('ascii')
     else:
       return s

If this works to fix the issue, we could apply this as it seems to have passed the test of different pythons.

**Comment by legendtang** [comment]
@NikolajBjorner That seems to work fine, though I don't know how to use `update_api.py`.
