### ISSUE TITLE
Missing VCOMP110.DLL for Z3 version 4.5.0

### ISSUE THREAD

**Issue by agacek** [Z3Prover/z3#788]
When I try to run Z3 version 4.5.0 on some of my windows machines, I get an error that it is missing the file VCOMP110.DLL. It looks like previous releases of Z3 used to include this and a couple other DLLs (msvcp110.dll, msvcr110.dll). Is it intentional that they are no longer included in the releases?

**Comment by wintersteiger** [comment]
vcomp*.dll is the Visual C OpenMP runtime library and if your machine had other applications installed that depend on this, then it is already present and Z3 doesn't need its own. Our scripts should have included this and the other DLLs, but apparently they didn't. I'll take a look and update the .zip release files.

**Comment by wintersteiger** [comment]
This is now done, thanks for reporting this issue!
