### ISSUE TITLE
Semantic change for TIMEOUT option between 4.4.1 and 4.5?

### ISSUE THREAD

**Issue by delcypher** [Z3Prover/z3#791]
I'm currently trying out [Boogie](https://github.com/boogie-org/boogie) with Z3 4.5 and Boogie currently isn't working because Z3 is behaving differently when it sees

```
(set-option :TIMEOUT 0)
```

Previously Z3 would treat this as there being no timeout. Now Z3 treats this as being no time being allowed for solving which is pretty useless. So now Boogie makes no progress because all solver queries return `unknown` with the reason `canceled`.

I strongly suspect (but haven't checked) that this change is related to this change

https://github.com/Z3Prover/z3/commit/a6e1c70eab988de59560c34a4222c99ce80e2feb

which was made in response to an issue I reported a while back ( https://github.com/Z3Prover/z3/issues/445 ).

I can work around this in Boogie but this change might need rethinking. Why would anyone ever want to give Z3 no time to solver a query?

**Comment by NikolajBjorner** [comment]
it's a bit arbitrary here, but it is reasonable to revert behavior by changing scoped_timer to be a no-op when passing in a timeout of 0.

**Comment by delcypher** [comment]
@NikolajBjorner Thanks for fixing. It's a shame this made it into the release but at least we have the old behaviour back.
