### ISSUE TITLE
Z3 fails on recursive str.replace

### ISSUE THREAD

**Issue by pjljvandelaar** [Z3Prover/z3#793]
I need a str.replaceAll function.
Unfortunately, currently only a str.replace is supported fro strings,
so I needed to make a recursive function.

Z3 doesn't produce a result for the latter problems of the attached file.
[replaceAll.zip](https://github.com/Z3Prover/z3/files/600076/replaceAll.zip)

The problem is definitely solvable (and is solved by other smt solvers).

I would expect the output for the last two problems as
sat
((str "aaaaaaaa"))
sat
((str2 "aaaa"))

details:
(:name "Z3")
(:version "4.4.2 - build hashcode 46c4fdaae553")

**Comment by NikolajBjorner** [comment]
this is solved fast and correct with the newest bits

**Comment by pjljvandelaar** [comment]
Checked with Z3 version 4.8.4 - 64 bit - build hashcode b40c2b2926ed

I get the expected output
```
(:name "Z3")
(:version "4.8.4 - build hashcode b40c2b2926ed")
sat
((strReplaceAllHoek_OeAa "haak"))
sat
((strReplaceAllOe_OeAa "aa"))
sat
((strReplaceAllOeOeOe_OeAa "aaaaaa"))
sat
((strReplaceAllOeOeOe_OeoeAaaa "aaaaoe"))
sat
((str "aaaaaaaa"))
sat
((str2 "aaaa"))
```
and I get it fast!

**Comment by pjljvandelaar** [comment]
Thanks for all your hard work!
