### ISSUE TITLE
Z3 fails on implicit inverse function

### ISSUE THREAD

**Issue by pjljvandelaar** [Z3Prover/z3#794]
For my ADT, BoolList, I defined a ToString.
Furthermore, I declared FromString
and specified that FromString.ToString is the identity.

Surprisingly, Z3 is unable to solve even the most trivial case
to related a string to my ADT.

details:
(:name "Z3")
(:version "4.4.2 - build hashcode 46c4fdaae553")
and see [fromString.zip](https://github.com/Z3Prover/z3/files/600144/fromString.zip)

Am I doing something wrong?
Is Z3 not targeted at these kind of problems?

**Comment by pjljvandelaar** [comment]
Note : simpler problems are solved
1. Booleans to String is defined, and fromString is declared.
[BoolFromString.zip](https://github.com/Z3Prover/z3/files/603719/BoolFromString.zip)
2. Enumeration (of color) to String is defined, and fromString is declared.
[ColorFromString.zip](https://github.com/Z3Prover/z3/files/603722/ColorFromString.zip)

A slightly more difficult problem works only for the first problem:
3. Cartesian product of Bool and Enum (Color) to String is defined. FromString is declared.
[CPBoolEnumFromString.zip](https://github.com/Z3Prover/z3/files/603726/CPBoolEnumFromString.zip)
Depending of the order of the problems one gets either
```
(:name "Z3")
(:version "4.4.2 - build hashcode 46c4fdaae553")
sat
((cpy (cp false blue)))
unknown
((cpx (cp true white)))
```
or
```
(:name "Z3")
(:version "4.4.2 - build hashcode 46c4fdaae553")
sat
((cpx (cp true white)))
unknown
((cpy (cp false white)))
```
yet, surprisingly Z3 doesn't seem able to solve both problems, i.e. 
```
sat
((cpx (cp true white)))
sat
((cpy (cp false blue)))
```

Am I pushing the limits of Z3 (and if so, which particular limits)?
Or is this a bug?

**Comment by NikolajBjorner** [comment]
Thanks, I will look into this, but it may take a little.

**Comment by NikolajBjorner** [comment]
It is an interesting and succinct example.
In a sense you are asking Z3 to establish a parser for a context free language. The model finding features of Z3 look for essentially finite models. These models are represented in a constructive way, so would have to encode such a parser. Z3 is therefore not sufficient to establish such structures.

**Comment by pjljvandelaar** [comment]
Thanks for the info.

Summarizing:  Z3 is currently not capable of solving this kind of problems.
