### ISSUE TITLE
Cannot build API Docs on Mac or Fedora

### ISSUE THREAD

**Issue by ramsdell** [Z3Prover/z3#799]
I pulled this morning.  Built and installed z3 without a problem, but...

$ cd rep/z3/doc/
$ python mk_api_doc.py 
ERROR: failed to generate documentation: [Errno 2] No such file or directory: '../src/api/python/z3.py'
$ 

It appears the script has not been updated for the new directory structure for the z3 python files.

**Comment by wintersteiger** [comment]
Thanks for reporting this, it's now fixed and the documentation builds as expected for me.

**Comment by ramsdell** [comment]
Builds for me too. Thanks for the quick fix.

John
