### ISSUE TITLE
fp - fpRem on infinities

### ISSUE THREAD

**Issue by LeventErkok** [Z3Prover/z3#80]
Github doesn't allow me to re-open #70, but this is in the same vein.

Based on this definition from the "spec":

```
remε,σ : RM × Fε,σ × Fε,σ → Fε,σ
remε,σ(rm, f, g) = f                            if  g ∈ FIε,σ
                   NaN                          if  f ∈ FIε,σ ∪ {NaN}
                   NaN                          if  g ∈ FZε,σ ∪ {NaN}
                   rnd(v, rm, isNeg(f), x)      if  x = v(f) − (v(g) ∗ y),
                                                    y = rnd(in, rm, 0, v(f)/v(g))
```

I do believe `fp.rem` should simply return the first argument if the second argument is an infinity.

Currently Z3 is returning `NaN` when the first argument is `+oo`; instead of the argument itself. That is, `fp.rem +oo +oo` should evaluate to `+oo`, but Z3 is currently producing `NaN`.

Same issue with `fp.rem +oo -oo`; `fp.rem -oo +oo`; and `fp.rem -oo -oo`.

**Comment by wintersteiger** [comment]
I'm looking at the IEEE standard, and they say that remainder(+oo, y) is a (quiet) NaN (Sec 7.2) and that remainder(x, +-oo) is x for _finite_ x (Sec 5.3.1). I'll ask the semantics people to clarify this one, until then I'll keep this issue open.

**Comment by wintersteiger** [comment]
I have confirmation from Martin Brain that they will try to change this to IEEE754 semantics, so the current implementation should match that.

**Comment by LeventErkok** [comment]
Thanks @wintersteiger That indeed makes sense. [I'll let you close this ticket as you see fit.]

Any news on the status of #114?

**Comment by wintersteiger** [comment]
Closing this as fixed then. 

Had no time to look at #114 yet and probably won't have time to do so this week.
