### ISSUE TITLE
push changes solution of problem from sat to unknown

### ISSUE THREAD

**Issue by PierreVDL** [Z3Prover/z3#801]
On Microsoft Windows [Version 6.1.7601]
when I run the latest nightly build of the 64 bits version of z3
with the attached file:
[CPEnumEnumFromString.zip](https://github.com/Z3Prover/z3/files/606039/CPEnumEnumFromString.zip)
I get 
```
(:name "Z3")
(:version "4.5.1 - build hashcode 03f8b871a1ad")
unknown
((cpx (cp white white)))
```
However, when I remove/outcomment the (push 1) statement on line 23, I get
```
(:name "Z3")
(:version "4.5.1 - build hashcode 03f8b871a1ad")
sat
((cpx (cp white red)))
```

Given the semantics of push I did not expect this change in behaviour.
Is this a bug, or is my understanding of push wrong?

**Comment by NikolajBjorner** [comment]
It seems to consistently produce sat at this point.
