### ISSUE TITLE
Segmentation fault error with max-smt

### ISSUE THREAD

**Issue by quochuydo** [Z3Prover/z3#802]
I use z3 to solve a max-smt problem as below:

;==========SORTS==========
(define-sort IntB () (_ BitVec 5))
;==========FUNCTIONS==========
(declare-fun self_p () IntB)

(declare-fun C0 () Bool)
(assert (= C0 (bvsle
 self_p
 (_ bv5 5)
)))
(assert-soft C0 :weight 2)

(declare-fun C1 () Bool)
(assert (= C1 (bvsgt
 self_p
 (_ bv5 5)
)))
(assert-soft C1 :weight 1)

;==========ASSERTIONS==========
(assert (and
 (bvsge
  (bvxor
   self_p
   (_ bv2 5)
  )
  (_ bv10 5)
 )
 (bvsge
  self_p
  (_ bv0 5)
 )
 (bvsle
  self_p
  (_ bv9 5)
 )
))
(check-sat)
(get-value (C0))
(get-value (C1))

z3 returns "Segmentation fault: 11". I think the correct result should be:
sat
(objectives
 ( 1)
)
((C0 true))
((C1 false))

because actually there are two values of self_p that satisfy C0 (b01010 and b01011). Is it a bug in z3 or maybe I am wrong somewhere?

**Comment by NikolajBjorner** [comment]
Sorry, this is a regression in 4.5.0. It is fixed in the current builds.

**Comment by quochuydo** [comment]
The problem has gone. Thanks!
