### ISSUE TITLE
Segmentation fault with RegEx reasoning

### ISSUE THREAD

**Issue by jcreedcmu** [Z3Prover/z3#804]
I expect `unsat`, but get a segfault on the following input:

```
(assert (not (str.in.re "" (re.++ re.allchar))))
(check-sat)
```

It correctly yields `unsat` if I remove the `re.++`, or if I change it to `(re.++ re.allchar re.allchar)`. Maybe `re.++` just doesn't like vacuously having one argument?

**Comment by NikolajBjorner** [comment]
Thanks, fixed
