### ISSUE TITLE
Unexpected results from `str.indexof` with offset argument

### ISSUE THREAD

**Issue by jcreedcmu** [Z3Prover/z3#806]
When I do
```
(declare-const action String)
(assert (>= (str.indexof action "abc" 1) 0))
(check-sat)
(get-model)
```
I get
```
sat
(model 
  (define-fun action () String
    "")
)
```
which doesn't seem right. I would expect a solution to look like `"?abc"` or `"???abc"` or something like that. Indeed, checking that I understood the semantics of `str.indexof` when the offset argument is bigger than the length of the string itself, I tried substituting `""` for `action` and
```
(assert (>= (str.indexof "" "abc" 1) 0))
(check-sat)
```
yields `unsat`, as I would expect.

---

Just for a more precise counterexample,
```
(declare-const action String)
(assert (= (str.indexof action "abc" 1) 1))
(check-sat)
(get-model)
```
also yields a model with `action` being the empty string.

**Comment by NikolajBjorner** [comment]
Indeed. Fixed bug in axiomatization of indexof.

**Comment by jcreedcmu** [comment]
Thanks again! Always appreciate your outstanding responsiveness fixing bugs :)
