### ISSUE TITLE
Use mkLt to compare two bit vectors in Z3 Java

### ISSUE THREAD

**Issue by computereasy** [Z3Prover/z3#807]
Hello,

I am trying to perform the following semantics in `Z3 Java` (note that the code is indeed written in `Scala` so the syntax looks different):

       val a = ctx.mkBV(12, 32).asInstance[BitVecExpr]
       val b = ctx.mkBV(5, 32).asInstance[BitVecExpr]

       ctx.mkLt(a, b)      
      // I want to compare a and b, and the comparison results are used for future reasoning.  Note that a/b could be bit vectors of complex symbolic formulas. 
   
It seems that function `mkLt` only accepts `ArithExpr` as parameters, so I type cast the above code into: 

        ctx.mkLt(a.asInstrance[ArithExpr], b.asInstance[ArithExpr])   

This code can be compiled, however, during runtime, I got an exception as:

    Exception in thread "main" java.lang.ClassCastException: com.microsoft.z3.BitVecExpr cannot be cast to com.microsoft.z3.ArithExpr

I suppose compare two bit vectors seems a reasonable operation, and I am not sure why it is not allowed. Am I missed anything here? Could anyone give me some help on this issue? Thank you!

**Comment by krypt-n** [comment]
I think ctx.mkBVSLT (for bitvectors that represent signed values) or ctx.mkBVULT (for bitvectors that represent unsigned values) are what you are looking for.

**Comment by wintersteiger** [comment]
Yes, what @krypt-n said: mkLt is only for ArithExprs, for Bit-vectors you have to chose signed or unsigned comparison.
