### ISSUE TITLE
Speedup constraint solving process

### ISSUE THREAD

**Issue by computereasy** [Z3Prover/z3#808]
Hello,

I am working on a symbolic executor to analyze some program, and I am writing to ask for help on speeding up the constraint solving of `Z3 Java`. 

What I am basically trying to do is to iterate the whole program, symbolize some variables, and collect certain path conditions along the code. When encountering certain criteria, I will pause my symbolic executor and put all the collected path conditions (they are `BoolExpr`) into the solver and let it check whether there exist a satisfiable solution regarding the symbolized variables. (of course it is indeed more complex but I try to simplify the presentation..)

 I give one path condition example below, in which `symbol1` is the symbolized variable. As you can see, the formula itself is not that large, but according to my observation, when I have have around 10~20 such kind of formulas, the solver takes several seconds to check the satisfiability.

    `(134821342,(let ((a!1 (ite (= ((_ extract 2 2) symbol1) #b1)
                #x00000002
                (ite (= ((_ extract 1 1) symbol1) #b1) #x00000001 #x00000000))))
    (let ((a!2 (ite (= ((_ extract 4 4) symbol1) #b1)
                #x00000004
                (ite (= ((_ extract 3 3) symbol1) #b1) #x00000003 a!1))))
    (let ((a!3 (ite (= ((_ extract 6 6) symbol1) #b1)
                #x00000006
                (ite (= ((_ extract 5 5) symbol1) #b1) #x00000005 a!2))))
    (let ((a!4 (ite (= ((_ extract 8 8) symbol1) #b1)
                #x00000008
                (ite (= ((_ extract 7 7) symbol1) #b1) #x00000007 a!3))))
    (let ((a!5 (ite (= ((_ extract 10 10) symbol1) #b1)
                #x0000000a
                (ite (= ((_ extract 9 9) symbol1) #b1) #x00000009 a!4))))
    (let ((a!6 (ite (= ((_ extract 12 12) symbol1) #b1)
                #x0000000c
                (ite (= ((_ extract 11 11) symbol1) #b1) #x0000000b a!5))))
    (let ((a!7 (ite (= ((_ extract 14 14) symbol1) #b1)
                #x0000000e
                (ite (= ((_ extract 13 13) symbol1) #b1) #x0000000d a!6))))
    (let ((a!8 (ite (= ((_ extract 16 16) symbol1) #b1)
                #x00000010
                (ite (= ((_ extract 15 15) symbol1) #b1) #x0000000f a!7))))
    (let ((a!9 (ite (= ((_ extract 18 18) symbol1) #b1)
                #x00000012
                (ite (= ((_ extract 17 17) symbol1) #b1) #x00000011 a!8))))
    (let ((a!10 (ite (= ((_ extract 20 20) symbol1) #b1)
                 #x00000014
                 (ite (= ((_ extract 19 19) symbol1) #b1) #x00000013 a!9))))
    (let ((a!11 (ite (= ((_ extract 22 22) symbol1) #b1)
                 #x00000016
                 (ite (= ((_ extract 21 21) symbol1) #b1) #x00000015 a!10))))
    (let ((a!12 (ite (= ((_ extract 24 24) symbol1) #b1)
                 #x00000018
                 (ite (= ((_ extract 23 23) symbol1) #b1) #x00000017 a!11))))
    (let ((a!13 (ite (= ((_ extract 26 26) symbol1) #b1)
                 #x0000001a
                 (ite (= ((_ extract 25 25) symbol1) #b1) #x00000019 a!12))))
    (let ((a!14 (ite (= ((_ extract 28 28) symbol1) #b1)
                 #x0000001c
                 (ite (= ((_ extract 27 27) symbol1) #b1) #x0000001b a!13))))
    (let ((a!15 (ite (= ((_ extract 30 30) symbol1) #b1)
                 #x0000001e
                 (ite (= ((_ extract 29 29) symbol1) #b1) #x0000001d a!14))))
    (let ((a!16 (bvxor #x0000001f
                   (ite (= ((_ extract 31 31) symbol1) #b1) #x0000001f a!15))))
    (let ((a!17 (bvshl symbol1
                   (bvand (concat #x000000 ((_ extract 7 0) a!16)) #x0000001f))))
    (let ((a!18 (ite (= (bvand (bvadd a!17 a!17) (bvadd a!17 a!17)) #x00000000)
                 #b1
                 #b0)))
      (= a!18 #b0))))))))))))))))))))
`

Of course seconds are acceptable, however, eventually the path conditions could grow quite large, and there exists hundreds or even thousands of them.. I do observed that the solver becomes much slower regarding those more challenging situations... 

So here is my question, given my situation (solving hundreds median/large size constrains with one or several symbols),  how should I start to speedup the solving process? I can come up with several options:

1. Cache the already solved constrains to save the re-solving time ==> I implemented such strategy in my tool

2. Substitute some large composite formulas with multiple symbols into a fresh new symbol ==> this can speedup the process in sacrifice of false positive.

3. some other things..?

I do not know much about theory proving and constraint solving, and I am sorry if these seems too naive.. I am writing to ask, could you please sled light on some general approaches to speedup the solving process in my case? Any suggestion is appreciated. Thank you!

**Comment by computereasy** [comment]
Sorry but it seems that I have to reopen this issue. After optimizing the #809 substitution, I did more test regarding large data set. During the test, I do find that the `check` function of the solver can takes too much time to finish. 

Currently, I am trapped in finding the satisfiable solution of around two hundred path conditions, each of which has a comparable size of the formula above. There are around 50 different symbols in these path condition formula in total, and each formula contains less than 10 symbols. 

The `check` function has been running for over 5 hours, and it never returns. I paste the profiling results below:

<img width="941" alt="screen shot 2016-11-29 at 12 12 58 am" src="https://cloud.githubusercontent.com/assets/5838310/20697749/9f0d8b60-b5c9-11e6-83e4-a75f4c85a854.png">

Besides, the memory usage seems normal, I guess it should not be some "GC" issue..

<img width="1115" alt="screen shot 2016-11-29 at 12 16 00 am" src="https://cloud.githubusercontent.com/assets/5838310/20697762/b6103dee-b5c9-11e6-961d-9515e17ec20c.png">
  

So given my situation, may I ask if there is any suggestion, or "best practice" in optimizing the `check` function of the solver? I would really appreciate for any advice. Thank you in advance!

**Comment by wintersteiger** [comment]
Depending on the input, the `check` function may solve some very hard problems, so this may be completely expected. There may be ways to optimize that from your side (make the input problem easier) or for us (make the solver faster), but for both of those we'll have to look into the details of your problems and how they are encoded. Do you have any idea which types of query from your application are easy or hard for Z3?

**Comment by computereasy** [comment]
@wintersteiger  Hi Christoph, I upload one sample formula [here](https://docs.google.com/document/d/1x75h58O0ueG-Dh-1gMIIIyAmz-1W_DK3WaFicqhv4Xg/edit?usp=sharing). 

Given one formula (named as `F`) like this, I will collect all the variables named as `symbolXXX`, substitute them into fresh symbols, and produce a new formula (named as `F1`). Then put these formula pair into the solver to check the satisfiability ` F != F1`.  For the formula in the google doc, I have been waiting for quite a long time but the `check` function never returns.

Note that this is just one example (one path condition), and during my experience, I could have hundreds of even thousands of such formulas (similar size, similar amount of variables.)

Could you please shed some light on any general approach I can simplify the checking procedure? As I posted before, since I am doing symbolic execution towards the program, I suppose "replace" a segment of formulas (with multiple variables) into a new symbolic variable could be one strategy to reduce the complexity... But this brings in false positive, and I am not aware of any literature discussing such topics...

**Comment by wintersteiger** [comment]
I'm afraid this type of formula is simply very hard to solve. I can see 766 64-bit multiplications (bvmul), while in practice even a single one of them can cause the solver to be too slow. I'd recommend looking into alternative encodings of your problems or into abstraction strategies, e.g., replacing multipliers with fresh variables, and only add those multiplication constraints that are actually necessary to get the result you need.

**Comment by NikolajBjorner** [comment]
In the long run, we will always attempt to improve performance.
Unfortunately, it is entirely open-ended and there isn't a particular actionable fix that we can associate with this as a bug. I would therefore mark this as closed/enhancement.
