### ISSUE TITLE
String contains substring validity times out

### ISSUE THREAD

**Issue by tlringer** [Z3Prover/z3#812]
Hello, 

I'm adding strings to Rosette. I currently am working on some simplifications. One simplification that I make is that a string should always contain all of its substrings. 

I'm testing my simplifications against Z3 to make sure we don't disagree on anything. This simplification works in Z3 with a bounded length, but currently times out for me (I wait a few minutes) when I try with an unbounded length. I understand validity in some fragments of the theory of strings is undecidable with unbounded lengths, but I think this case is simple enough that it might be worth considering separately. 

If it isn't, or if you try not to special-case too many things, then feel free to ignore this.

Here's the query: 

```
(set-option :model_validate true)

(declare-fun c0 () String)
(declare-fun c1 () Int)
(declare-fun c2 () Int)
(assert (not (str.contains c0 (str.substr c0 c1 (- c2 c1)))))
(assert (and (<= 0 c1) (<= c1 c2) (<= c2 (str.len c0))))
(check-sat)

(get-model)
```

**Comment by NikolajBjorner** [comment]
It's a good point: the properties of str.substr are such that the following property holds:

           (str.contains s (str.substr s offset length))

forall s, offset, length

I will add this as part of the facts that get instantiated when processing str.substr. 
There is a risk that this additional fact cause overhead as the new term "occurs" also gets expanded.

**Comment by NikolajBjorner** [comment]
I added a rewrite rule instead of additional instantiation. It is ad-hoc in a sense that syntactic variants will not be covered.
