### ISSUE TITLE
Expose register_variable in fixedpoint API?

### ISSUE THREAD

**Issue by calebvoss** [Z3Prover/z3#813]
I'm invoking Duality through the (OCaml) API, but I can't find one of the API functions that I need.

In SMT-LIBv2, we can register our relations and the universally quantified variables using `(declare-rel A)` and `(declare-var x)` respectively. I see `Z3_fixedpoint_register_relation` in `src/api/api_datalog.cpp`, and it is exposed in OCaml as `register_relation` in `src/api/ml/z3.mli`.

However I cannot find a corresponding `Z3_fixedpoint_register_variable` in the API. I tried to write my own. Is this right?
```
void Z3_API Z3_fixedpoint_register_variable(Z3_context c, Z3_fixedpoint d, Z3_func_decl f) {
    Z3_TRY;
    to_fixedpoint_ref(d)->ctx().register_variable(to_func_decl(f));
    Z3_CATCH;
}
```

And then, of course, a little extra boilerplate is needed to expose it through the OCaml bindings.

**Comment by wintersteiger** [comment]
That looks correct to me. @NikolajBjorner: should we add register_variable and register_finite_sort to the API as well?

**Comment by NikolajBjorner** [comment]
register variable is a feature of the text-based interface. It instructs the parser that a variable is to be treated as universally quantified. Over the binary API we can use z3_mk_bound to create variables that should be treated as universally quantified in rules, or the code can use the API methods for creating universally quantified formulas.

**Comment by calebvoss** [comment]
Oh I see. Yes, that works. Thanks!

**Comment by NikolajBjorner** [comment]
seems this is resolved
