### ISSUE TITLE
Bug in wmax + lexicographic combinations [2]

### ISSUE THREAD

**Issue by PatrickTrentin88** [Z3Prover/z3#815]
On the attached _lexicographic combination_ formula ([formula.zip](https://github.com/Z3Prover/z3/files/621254/formula.zip)), **z3** returns different results.

**WMax**:

`unsat`

**MaxRes**:

```
sat
(objectives
 (weight.Auto 287)
 (workTime.Auto 12)
 (cost.Auto 120)
)
```

---

**Notes:**
- The formula is the same as that in issue #782 , it appears that after the **bugfix** *z3* returns a different incorrect result. 
- Independent checks certify that the result obtained with **MaxRes** is correct.

**Comment by NikolajBjorner** [comment]
indeed, thanks. This module has been regressing heavily.
