### ISSUE TITLE
Bug in Bellman-Ford implementation

### ISSUE THREAD

**Issue by nateyazdani** [Z3Prover/z3#816]
Hi,

Z3 generates invalid models for some queries in the `QF_UFIDL` logic when using the decision procedure based on Bellman-Ford. The model's interpretation of a function maps the same element of the domain to several different values. Below is the smallest example that I could find to demonstrate this behavior.

```lisp
(set-option :auto-config false)
(set-option :smt.arith.solver 1)
(set-option :model_validate true)

(declare-fun f (Int) Int)
(declare-fun g (Int) Int)

; g inverts f over [0, 4)
(assert (= 0 (g (f 0))))
(assert (= 1 (g (f 1))))
(assert (= 2 (g (f 2))))
(assert (= 3 (g (f 3))))

; Bound the range of g to [0, 4) over the domain [0, 4)
(assert (<= 0 (g 0)))
(assert (<= 0 (g 1)))
(assert (<= 0 (g 2)))
(assert (<= 0 (g 3)))
(assert (< (g 0) 4))
(assert (< (g 1) 4))
(assert (< (g 2) 4))
(assert (< (g 3) 4))

; f over [0, 2) is bounded to [2, 4)
(assert (<= 2 (f 0)))
(assert (<= 2 (f 1)))
(assert (< (f 0) 4))
(assert (< (f 1) 4))

(check-sat)
(get-model)
```

This is the output Z3 version 4.5.0 gives me:

```lisp
sat
(error "line 30 column 10: an invalid model was generated")
(model 
  (define-fun f ((x!0 Int)) Int
    (ite (= x!0 0) 3
    (ite (= x!0 1) 3
    (ite (= x!0 2) 4
    (ite (= x!0 3) 5
      3)))))
  (define-fun g ((x!0 Int)) Int
    (ite (= x!0 3) 0
    (ite (= x!0 3) 1
    (ite (= x!0 4) 2
    (ite (= x!0 5) 3
    (ite (= x!0 0) 3
    (ite (= x!0 1) 3
    (ite (= x!0 2) 3
    (ite (= x!0 3) 3
      3)))))))))
)
```

**Comment by NikolajBjorner** [comment]
The difference logic solvers don't have support theory combinations with foreign functions.
If you would like to add support for this, then you should make sure the solver would need to propagate implied equalities or perform case splitting on equalities, say based on the model in the final state.

**Comment by nateyazdani** [comment]
Ah, bummer. I'll take a look and see if I can make that change. Thank you for the clarification.
