### ISSUE TITLE
com.microsoft.z3.Z3Exception: out of memory

### ISSUE THREAD

**Issue by computereasy** [Z3Prover/z3#818]
Hello,

I got the `z3` out of memory exception when trying to solve some, probably, large formulas. 

    com.microsoft.z3.Z3Exception: out of memory
        at com.microsoft.z3.Native.solverCheck(Native.java:4292)
        at com.microsoft.z3.Solver.check(Solver.java:206)
        at com.microsoft.z3.Solver.check(Solver.java:233)
        at analysis.FormulaAnalysis$.check_formulas(FormulaAnalysis.scala:98)

I suppose it should not be possible to avoid such exception by increasing the `JVM` heap size, since it is in the native code. So I am wondering what should I do to handle such cases? Thank you.

**Comment by NikolajBjorner** [comment]
Chances are meager that Z3 would solve the problem if it hits memory pressure. 
You can always use 64 bit address spaces by using 64 bit versions of Z3/JVM.

**Comment by yangchao46** [comment]
Have your resolved the problem? I have met a similar problem when I use Z3. Thanks!
