### ISSUE TITLE
Java Compute Interpolant tries to use out parameters

### ISSUE THREAD

**Issue by MarcusVoelker** [Z3Prover/z3#82]
The function `public Z3_lbool ComputeInterpolant(Expr pat, Params p, ASTVector interp, Model model)`
of the java api tries to return the interpolant via the interp paramter, but Java has no way of using an output parameter (https://stackoverflow.com/questions/40480/is-java-pass-by-reference-or-pass-by-value)

Therefore, the function is unusable.

Possible workaround: Add the following function to InterpolationContext
```java
public Expr[] ComputeInterpolant(Expr pat)
{
    checkContextMatch(pat);

    Params p = mkParams();

    Native.LongPtr n_i = new Native.LongPtr();
    Native.LongPtr n_m = new Native.LongPtr();
    int r = Native.computeInterpolant(nCtx(), pat.getNativeObject(), p.getNativeObject(), n_i, n_m);
    ASTVector seq = new ASTVector(this, n_i.value);
    int n = seq.size();
    Expr[] res = new Expr[n];
    for (int i = 0; i < n; i++)
        res[i] = Expr.create(this, seq.get(i).getNativeObject());
    return res;
}
```

**Comment by wintersteiger** [comment]
Thanks for reporting this issue! I've fixed that by introduction of special return value classes that hold all the required bits and pieces.
