### ISSUE TITLE
Build static z3 lib with --noomp fails: undefined reference

### ISSUE THREAD

**Issue by Bletchley13** [Z3Prover/z3#820]
I want to build static z3 lib without enabling openMP. 
I use the following command to configure and build z3.
`./configure --staticlib --noomp`  
`cd build`
`make -j8`

But get the following result

> shell/opt_frontend.o: In function `on_ctrl_c(int)':
> opt_frontend.cpp:(.text+0x32d): undefined reference to `GOMP_critical_name_start'
> opt_frontend.cpp:(.text+0x33a): undefined reference to `GOMP_critical_name_end'
> shell/opt_frontend.o: In function `on_timeout()':
> opt_frontend.cpp:(.text+0x37c): undefined reference to `GOMP_critical_name_start'
> shell/opt_frontend.o: In function `parse_opt(std::istream&, bool)':
> opt_frontend.cpp:(.text+0x4b4): undefined reference to `GOMP_critical_name_start'
> opt_frontend.cpp:(.text+0x4d3): undefined reference to `GOMP_critical_name_end'
> opt_frontend.cpp:(.text+0xdbc): undefined reference to `omp_set_nest_lock'
> opt_frontend.cpp:(.text+0xdde): undefined reference to `omp_unset_nest_lock'
> opt_frontend.cpp:(.text+0xe05): undefined reference to `omp_set_nest_lock'
> opt_frontend.cpp:(.text+0xe27): undefined reference to `omp_unset_nest_lock'
> opt_frontend.cpp:(.text+0x10ac): undefined reference to `omp_set_nest_lock'
> opt_frontend.cpp:(.text+0x10ce): undefined reference to `omp_unset_nest_lock'
> opt_frontend.cpp:(.text+0x10f5): undefined reference to `omp_set_nest_lock'
> opt_frontend.cpp:(.text+0x1117): undefined reference to `omp_unset_nest_lock'
> shell/opt_frontend.o: In function `rational::~rational()':

**Comment by Bletchley13** [comment]
I fix the problem by redo in the fresh environment, maybe it is some temporary file that are not clear.

**Comment by delcypher** [comment]
@Bletchley13 The problem is the build system does not correctly rebuild source files if the build flags change. If you want to avoid this you need to either build in a fresh build directory (like you did) or use the [CMake build system](https://github.com/Z3Prover/z3/blob/master/README-CMake.md).

**Comment by Bletchley13** [comment]
@delcypher  Thanks for your reply, I will also try to use cmake.
