### ISSUE TITLE
ImportError: No module named z3

### ISSUE THREAD

**Issue by parulkhanna** [Z3Prover/z3#821]
Hi,

I have installed z3 through this github repository. I am trying to run a script that uses z3. I am getting this error.

**Traceback (most recent call last):
  File "./txx.py", line 4, in <module>
    import TriggerInput
  File "./TI.py", line 10, in <module>
    from z3 import *
**ImportError: No module named z3****

Can anyone help me with this. I know this is related to path setting. But I am not able to fix this. 

TIA

below is the screenshot of the script I am using 

![screenshot from 2016-12-05 00 11 20](https://cloud.githubusercontent.com/assets/6426212/20870404/8633a0d0-ba55-11e6-8f1f-996d84730bf9.png)

**Comment by wintersteiger** [comment]
The error message means that your Python installation can't find the Z3 library. This may be related to your PATH settings as you suggest, but it could also be your Python installation (and it's paths). How did you install Z3 and on what platform do you see this problem?

**Comment by parulkhanna** [comment]
Hi,

Thanks for the reply, I am using Ubuntu 14.x.

1) I installed python by sudo apt-get install command.

2) I installed z3by cloning from github repository and following the
instructions to compile using make command from the homepage.

I gave a try to export the path of z3 from build folder, but still the
error is not resolved.

Thanks,
P

**Comment by wintersteiger** [comment]
Did you install it by running `sudo make install'?

**Comment by parulkhanna** [comment]
Yes !

**Comment by wintersteiger** [comment]
After recent changes to the Python API package, it may be that the reason for your problems is that the Python pkg_resources module is not installed by default. Could you try running `sudo apt-get install --reinstall python-pkg-resources` to check whether this is the problem?

**Comment by delcypher** [comment]
@parulkhanna 
At configure time both Z3 build system decide where the Z3 modules will be installed. For the python build system you'll see this output like this (it will vary depending on your Python version, install prefix and where your Python chooses to put its packages).

```
$ python scripts/mk_make.py --python
...
Python pkg dir: /usr/lib/python3.5/site-packages
```

Assuming that you built and installed Z3 without error you should check that the Python package ended up where it was supposed to **and** that it is in a directory that is python's search path for packages/modules.

```python
$ python
Python 3.5.2 (default, Nov  7 2016, 11:31:36) 
[GCC 6.2.1 20160830] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> sys.path
['',  '/usr/lib/python35.zip', '/usr/lib/python3.5', '/usr/lib/python3.5/plat-linux', '/usr/lib/python3.5/lib-dynload', '/usr/lib/python3.5/site-packages']
```

You can see here that `sys.path` contains `/usr/lib/python3.5/site-packages`. So on my system if the Python package was installed into `/usr/lib/python3.5/site-packages` python should be able to find the `z3` package.

**Comment by parulkhanna** [comment]
Thanks @wintersteiger and @delcypher. I used both of your approaches to reinstall and verify the path for site packages. It worked. Thanks for your valuable comments.

**Comment by wintersteiger** [comment]
Fantastic, thanks for letting us know!
