### ISSUE TITLE
Bug in wmax/maxres + lexicographic combinations

### ISSUE THREAD

**Issue by PatrickTrentin88** [Z3Prover/z3#824]
_>> Follows from bug report #815, it reports a different inconsistent result within the same general set of formulas_ 

On the attached _lexicographic problem_ ([formulas.zip](https://github.com/Z3Prover/z3/files/630942/formulas.zip)), both **wmax** and **maxres** return the following optimum combination:

**f_maxres.smt2/f_wmax.smt2:**
```
sat
(objectives
 (weight.Auto 506)
 (workTime.Auto 23)
 (cost.Auto 336)
)
```

However, if one expands _assert-soft into ite_ statements _[a necessary step, because assert-soft ids are not terms in z3]_ and checks the satisfiability of the returned solution by adding

```
;; Check optimum value
(assert (and
 (= weight.Auto 506)
 (= workTime.Auto 23)
 (= cost.Auto 336)
))
```

to the expanded formula, then **z3** returns _unsat_:

**e_maxres.smt2/e_wmax.smt2**:

```
unsat
```

Previous versions of **z3+maxres**, returned the correct optimal solution on the same formula:

```
sat
(objectives
 (weight.Auto 509)
 (workTime.Auto 23)
 (cost.Auto 336)
)
```

The version of **z3** tested in this bug report corresponds to commit f1a704484b56555311b52dad2ab4146a5577f257 .

**Comment by NikolajBjorner** [comment]
Fixed, should have referenced this issue in 2307a7ffa73fb06c80b206503b03d0c4af4fb12b.
The bug had to do with incorrect handling of duplicate soft constraints, it does not depend on lexicographic combinations.
