### ISSUE TITLE
segmentation fault occurred

### ISSUE THREAD

**Issue by kanigsson** [Z3Prover/z3#826]
Dear Z3 team,

On the attached file (please rename .txt into .smt2):
[p.adb_4_13_range_check.txt](https://github.com/Z3Prover/z3/files/636153/p.adb_4_13_range_check.txt)

we get a segmentation fault quite quickly.

Best,

Johannes

**Comment by wintersteiger** [comment]
This was caused by the same problem as #828, which was fixed just now. The example now runs correctly, although it does return 'unknown'.

**Comment by kanigsson** [comment]
Thanks a lot! Indeed the issue is fixed now.
