### ISSUE TITLE
incorrect fp rounding

### ISSUE THREAD

**Issue by florianschanda** [Z3Prover/z3#827]
Hi,

I have this testcase:
```
(set-logic QF_FP)
(set-info :source |Random FP test by Florian Schanda|)
(set-info :category random)
(set-info :status sat)
(declare-const x Float32)
(assert (= x ((_ to_fp 8 24) #x807140a7)))
(declare-const result Float32)
(assert (= result (fp.roundToIntegral roundNearestTiesToAway x)))
(assert (= result ((_ to_fp 8 24) #xbf800000)))
(check-sat)
(exit)
```

I am trying to round -1.040060e-38f away from zero, so I expect the result to be -1, not -0.

**Comment by delcypher** [comment]
I'm not sure the rounding mode you're using in the query matches what you wrote in your text.

If you want to always round away from zero in this situation then you could use `roundTowardNegative`.

`roundNearestTiesToAway` will round to the nearest value (which is not necessarily away from zero) but will round away from zero in the event of a tie. There is no tie in this situation ` -1.040060e-38f` is  much closer to `0` than `-1` so `0` is the correct answer.

**Comment by florianschanda** [comment]
Hm, yes maybe you're right. :/

I used MPFR rounding mode away from zero, but of course this doesn't actually correspond to IEEE RNA.

**Comment by wintersteiger** [comment]
Indeed, what @delcypher said! RNA only rounds away if it's exactly a tie. IEEE754 says: 'roundTiesToAway, the floating-point number _nearest_ ... equally near, the one with larger magnitude'.

IEEE754 defines dedicated integer conversion functions that don't depend on the rounding mode currently set; here that's convertToIntegerTiesToAway and convertToIntegerExactTiesToAway, both are defined as '... the _nearest_ integer ...' . Those functions do not exist in SMT, which instead has roundToIntegral that takes a rounding mode, but the semantics are the same.

MPFR's MPFR_RNDA is an extension and according to their documentation (Sec 4.4) it's 'experimental' :-)
