### ISSUE TITLE
No `clean` target for `make` (minor issue)

### ISSUE THREAD

**Issue by Hibou57** [Z3Prover/z3#830]
I noticed there seems to be no `make clean` available. Is this on purpose or an omission?

I was just surprised as it's a standard pseudo‑target.

**Comment by delcypher** [comment]
[The CMake build system for Z3](https://github.com/Z3Prover/z3/blob/master/README-CMake.md) has a `clean` target. Not sure about the Python/Makefile build system.

**Comment by wintersteiger** [comment]
I think this is simply a case of nobody needing it until now. I frequently just erase all .o/.obj files or the whole build directory when I want to start over.

**Comment by Hibou57** [comment]
@wintersteiger , I indeed first did `find . -name "*.o" -exec rm {}\;`, but it seems to leave more than object files, after the repository size.

That said, I just learned, as it's a git repository, I can achieve the same as `make clean` with `git clean -df`

**Comment by NikolajBjorner** [comment]
OK, there are workarounds and solutions using cmake.
