### ISSUE TITLE
Cannot find Regex Range in C API

### ISSUE THREAD

**Issue by jawline** [Z3Prover/z3#831]
Hi,

I cannot find the regex range ((re.range ch1 ch2) The range of characters between ch1 and ch2.) in the C API. I assume this is because it is achieved in SMT through a string of C function calls but I can't find any documentation on which this relates to.

Could somebody let me know how to do a regex range in the C API.

Regards,
Blake Loring

**Comment by NikolajBjorner** [comment]
Ups, it's missing.

**Comment by jawline** [comment]
Can't spot loop either, not sure if thats missing too

**Comment by NikolajBjorner** [comment]
To finish the list: Empty and full regular expressions, intersections (and complements) are also not exposed.
If anybody have applications that benefit from range or so, then I would definitely add them. Otherwise, regular expressions are so far a niche feature.

**Comment by jawline** [comment]
The application we are building tries to model (wherever possible) JavaScript regular expressions as Z3 regular expressions & we're using the C API so they would be very useful for us as things like /a{0, 9}/ need them

**Comment by NikolajBjorner** [comment]
I now have exposed a number of regular expression features not previously available.

**Comment by jawline** [comment]
That's brilliant, thank you!
