### ISSUE TITLE
Erroneous sort mismatch during (push), possible segfault after (pop)

### ISSUE THREAD

**Issue by deeglaze** [Z3Prover/z3#832]
The following script exhibits the problem

    (declare-sort S 0)   
    (declare-fun g (Int S Int) Int)
    (declare-fun f (Int S Int Int) Bool)
    (assert
     (forall ((j Int)
             (i Int)
             (st S)
             (w Int)
             (wf Int))
      (let ((Ex (not (exists ((__a Int)) (= (g i st w) __a)))))
        (=> (and Ex (= wf 0))
            (f i st w j)))))
    (push)
The error is 

> (error "line 13 column 9: Sort mismatch at argument #1 for function (declare-fun __a!0 (Int S Int) Int) supplied sort is S")

The error disappears if `Ex` is the antecedent on its own (not within the `and`), or if `wf` is not a quantified variable and is replaced with `w`.

**Comment by deeglaze** [comment]
I tried absorbing the exception in my use of the library, but the push error corrupts some state that (pop) fails to restore. Append the following to the above script and you get a segfault, not an exception
    (pop)
    (assert (forall ((s S)) (f 0 s 0 0)))
    (push)

**Comment by NikolajBjorner** [comment]
It looks like the code in macro_util::normalize_expr does not verify that the variable renaming is well sorted. It creates a substitution that renames bound variables.

**Comment by wintersteiger** [comment]
Thanks for reporting this issue, this is now fixed.
