### ISSUE TITLE
Segmentation fault for a simple problem

### ISSUE THREAD

**Issue by iwob** [Z3Prover/z3#837]
Hello,

I ran the following example on 32c63ce4cdae0e244c2b01ac0f0e0637035ec6d3 and it produced segmentation fault. I also checked and this problem is solved correctly by binaries of the 4.4.1 release.

```
(declare-fun H1SBool1_r1 () Int)
(define-fun H1SBool1 ((x Int)(y Int)) Bool
    (ite (= H1SBool1_r1 0) (> x y) false))

(assert (forall ((x Int)(y Int)(res Int))
	(=>
		;PROGRAM:
		(= res (ite (H1SBool1 x y) x y))
		;POSTCONDITION:
		(and (>= res x) (>= res y) (or (= res x) (= res y)))
	)
))
(check-sat)
```

**Comment by NikolajBjorner** [comment]
It's a bug in how quantifier sat module deals with nested ite expressions.
A workaround is to write 		(ite (H1SBool1 x y) (= res x) (= res y)) 
instead of (=res (ite H1SBool1 x y) x y)))

**Comment by NikolajBjorner** [comment]
A fix is checked in

**Comment by iwob** [comment]
Thank you very much for quick fix!
