### ISSUE TITLE
scoped_timer not firing?

### ISSUE THREAD

**Issue by delcypher** [Z3Prover/z3#839]
I'm trying to debug instances where it appears that Z3's solver timeout is not firing on Linux in my application. I'm struggling to debug this as it doesn't seem to always happen and I'm also using very large timeouts (~1600 seconds) which makes repeating this problem rather slow. When I've tried to observe this using gdb because every time I've attached to the process the timer appears to have fired when expected.

I believe that the `scoped_timer` is used for enforcing the timeout. I was looking over the code and saw something that might be the culprit.

```c++
#elif defined(_LINUX_) || defined(_FREEBSD_)
    static void* thread_func(void *arg) {
        scoped_timer::imp *st = static_cast<scoped_timer::imp*>(arg);

        struct timespec end_time;
        clock_gettime(CLOCK_REALTIME, &end_time);
        end_time.tv_sec  += st->m_ms / 1000u;
        end_time.tv_nsec += (st->m_ms % 1000u) * 1000000ull;
        // check for overflow
        if (end_time.tv_nsec >= 1000000000) {
            ++end_time.tv_sec;
            end_time.tv_nsec -= 1000000000;
        }

        pthread_mutex_lock(&st->m_mutex);
        st->m_initialized = true;
        int e = pthread_cond_timedwait(&st->m_cond, &st->m_mutex, &end_time);
        ENSURE(e == 0 || e == ETIMEDOUT);

        pthread_mutex_unlock(&st->m_mutex);
        if (e == ETIMEDOUT)
            st->m_eh->operator()();
        return 0;
    }
```

According to the documentation of `pthread_cond_timedwait()`

```
When using condition variables there is always a Boolean predicate involving
shared variables associated with each condition wait that is true if the thread
should proceed. Spurious wakeups  from  the pthread_cond_timedwait()  or
pthread_cond_wait()  functions may occur. Since the return from
pthread_cond_timedwait() or pthread_cond_wait() does not imply anything about
the value of this predicate, the predicate should be re-evaluated upon such
return.
```

My interpretation of this is that `pthread_cond_timedwait()` could be spuriously woken up and this **does not imply** that the condition variable was signalled. It seems there should be some other predicate that should be checked after `pthread_cond_timedwait()` to check if a signal was actually sent.

The current implementation of `scoped_timer` for Linux does not do this. It presumes that if `pthread_cond_timedwait()` returns 0 that it was signalled and the thread exits.

I'm guessing that `pthread_cond_timedwait()` should be called in a loop and if `0` is returned it should be checked (probably by reading some `bool` that is set by the code that calls `pthread_cond_signal()`) that we were signalled.

Also see http://stackoverflow.com/questions/8594591/why-does-pthread-cond-wait-have-spurious-wakeups

**Comment by delcypher** [comment]
Also see http://softwareengineering.stackexchange.com/questions/186842/spurious-wakeups-explanation-sounds-like-a-bug-that-just-isnt-worth-fixing-is

**Comment by wintersteiger** [comment]
It's quite possible that there's a rarely occurring problem in the timer itself. However, due to recent changes to the resource limit handling (see reslimit class), I think it's more likely that Z3 enters an expensive computation which doesn't check whether the limits have been reached for too long a time. This would look exactly like the timer has fired, but Z3 would continue regardless, because another piece of code doesn't check their reslimit often enough. Of course, in the debugger everythings takes longer so it never gets there.

I'd recommend attaching a debugger after the timeout has expired, so that the stack trace would tell us what it was busy with at the time.

**Comment by delcypher** [comment]
@wintersteiger Thanks for the hint. I've sketched a fix for the timer in #841 and I'll try modifying the timer in my local copy so I know when it has fired and I'll attach gdb when it appears like the timer has had no effect.

**Comment by delcypher** [comment]
@wintersteiger So I spent some time debugging this and it's a bug in KLEE (https://github.com/klee/klee/issues/544) rather than a bug in Z3. The scoped timer is firing roughly when expected.

**Comment by wintersteiger** [comment]
Fantastic, thanks for the debugging work, that's good to know!
