### ISSUE TITLE
Unable to install z3

### ISSUE THREAD

**Issue by parulkhanna** [Z3Prover/z3#840]
Hi everyone,

I was using z3 from longtime and after I restarted my machine. I started getting this error

`<module>
    from z3 import *
ImportError: No module named z3
`

I try to recompile z3 using following command 

`python scripts/mk_make.py --python`

and got this error
```
Copied 'z3num.pyc'
Copied 'z3util.pyc'
Copied 'z3core.pyc'
Testing ar...
Testing /usr/local/bin/g++...
Testing g++...
Testing clang++...
Traceback (most recent call last):
  File "scripts/mk_make.py", line 21, in <module>
    mk_makefile()
  File "/home/viau/andp/z3/scripts/mk_util.py", line 2575, in mk_makefile
    mk_config()
  File "/home/viau/andp/z3/scripts/mk_util.py", line 2398, in mk_config
    CXX = find_cxx_compiler()
  File "/home/viau/andp/z3/scripts/mk_util.py", line 528, in find_cxx_compiler
    raise MKException('C++ compiler was not found. Try to set the environment variable CXX with the C++ compiler available in your system.')
mk_exception.MKException: 'C++ compiler was not found. Try to set the environment variable CXX with the C++ compiler available in your system.'
```
My system has gcc. g++ installed. I have checked my paths also

 `viau@viau-All-Series:~/andp/z3$ echo $CXX
`
`/usr/local/bin/g++`

but the error is not going away. any suggestions please

**ERROR**
```
Testing ar...
Testing /usr/local/bin/g++...
Testing g++...
Testing clang++...
Traceback (most recent call last):
  File "scripts/mk_make.py", line 21, in <module>
    mk_makefile()
  File "/home/viau/andp/z3/scripts/mk_util.py", line 2575, in mk_makefile
    mk_config()
  File "/home/viau/andp/z3/scripts/mk_util.py", line 2398, in mk_config
    CXX = find_cxx_compiler()
  File "/home/viau/andp/z3/scripts/mk_util.py", line 528, in find_cxx_compiler
    raise MKException('C++ compiler was not found. Try to set the environment variable CXX with the C++ compiler available in your system.')
mk_exception.MKException: 'C++ compiler was not found. Try to set the environment variable CXX with the C++ compiler available in your system.'

```

**Comment by wintersteiger** [comment]
Thanks for lettings us know by closing the issue! I presume everything is working again?

**Comment by greninja** [comment]
@wintersteiger I am still facing the same issue. Could you help?

**Comment by NikolajBjorner** [comment]
There is something unusual with your paths. My suggestion is that you try using the CMAKE based system. Read the instructions in README-cmake.md for all details. CMAKE is widely used so any issues you may face would likely have been replicated by other users of cmake.

**Comment by greninja** [comment]
Hi,
This is what I did to resolve the issue:
1) Located where exactly C++ compiler sits in the my machine using : 
`whereis g++`
and used the '/usr/....'  path to set the CXX environment variable : 
`$~ CXX=/usr/....
 $~ export CXX`

Although it went through here, it showed a similar exception for C compiler. But following the above steps worked for that too. 
Cheers!

**Comment by igor98045** [comment]
Hello guys, recently I want to install z3 python in AstraLinux (based on Debian) and I faced with the same problem. I can find the way to solve it. So, you need to download z3-master from github, unpack it on your computer. Then, you have to execute commands listed below:
1.sudo aptitude install gcc g++
2.(in z3-top-directory) sudo scripts/mk_make.py
3.wait and get the sweet :)

**Comment by NikolajBjorner** [comment]
There is a pip package for z3. It is called z3-solver. It installs under a folder called z3. This clashes with a folder used by the "z3" package (the ZFS file system for S3) which is completely unrelated except for the name. This could be one reason why a "pip install z3-solver" doesn't work for you. You can delete the local installation folder to avoid the overlapping installations.

**Comment by NikolajBjorner** [comment]
Well, it is good then that Z3 doesn't require internet access. An early version of Z3 was a thin Perl wrapper that would send the file to our inboxes, then we would quickly solve the problem, or just toss a coin, and send back an answer. We had to type really quickly, and eventually getting fed up not getting any sleep, so we replaced the Perl wrapper by a working solver.
