### ISSUE TITLE
Access Duality's counterexample when query fails

### ISSUE THREAD

**Issue by calebvoss** [Z3Prover/z3#845]
I know that one can see the counterexample generated by Duality to refute a query using the option `:print-certificate true` in the `query` command. But is there currently a way to retrieve this as a model over the API? (I'm using OCaml)

I found the function `display_certificate_non_const` in `src/muz/duality/duality_dl_interface.cpp`, which basically does what I want, but it doesn't seem to be exposed over the API and it prints the model as a string instead of returning it. There didn't seem to be any obstacles to writing a function that just returns this model, so I tried it and it works for me. Is this something we can add to the API?

**Comment by NikolajBjorner** [comment]
Closing as the code that was exercised in this issue is no longer part of the code base, #1646.
