### ISSUE TITLE
What type of constraints can help in reducing optimization time for z3

### ISSUE THREAD

**Issue by pacific0009** [Z3Prover/z3#846]
I am constructing  rectilinear minimum steiner tree on grid graph.
The grid points which will be in the path of tree will be 1 (by asserting some constraints continuity is insured ).
for minimizing the tree length the sum of grid points is optimize/minimize
but for grid size more than 28X28 it is taking very much time time so is there any heuristics which will power to the optimization.
(for eg. i inserted some upper and lower bounds for length but seems it doesn't help in improving time. i thought it may reduce the searching region. 
)

**Comment by nunoplopes** [comment]
spring cleanup: old question.
