### ISSUE TITLE
Identifying solver timeout from Z3's C API

### ISSUE THREAD

**Issue by delcypher** [Z3Prover/z3#848]
I just received this bug report from @SeanHeelan  for KLEE when using Z3

https://github.com/klee/klee/issues/550

and it looks like we're hitting a case where Z3 is not being consistent about the message it returns when a timeout occurs.

Currently KLEE handles this like so.

https://github.com/klee/klee/blob/f997712d5ccac6714e57d87626e37bb762491784/lib/Solver/Z3Builder.cpp#L42

This is kind of a hack because we just look for the string `canceled` that comes from `Z3_get_error_msg()` and assuming it means solver timeout.

The reporter of the above bug is seeing Z3 returning `(resource limits reached)` which KLEE is failing to handle. KLEE of course needs to be taught to handle this but looking at this raises the following questions.

* Why is Z3 not returning a consistent message regarding timeouts?
* Why is there no C API that can be used to make it easier to check for this?
* Looking at `src/smt/smt_context.cpp` I see code that does this

```c++
            if (resource_limits_exceeded() && !inconsistent()) {
                m_last_search_failure = RESOURCE_LIMIT;
                return l_undef;
            }

```

This code is overwriting `m_last_search_failure` which `resource_limits_exceeded()` sets. This looks like it might be a bug (although `resource_limits_exceeded()` sounds like something that shouldn't change state... even though it does).

**Comment by NikolajBjorner** [comment]
The solver now sets the return status to indicate the source of interrupt. For timeouts, the message should be "timeout".

**Comment by nunoplopes** [comment]
All fixed I think.
