### ISSUE TITLE
src/math/polynomial/polynomial_factorization appears to be dead.

### ISSUE THREAD

**Issue by delcypher** [Z3Prover/z3#852]
I just noticed while building Z3 on macOS that `lib/polynomial_factorization.cpp` (and its header file) appears to be dead code and has been since 2012.

**Comment by NikolajBjorner** [comment]
correct, I would prefer to keep it even though git provides time travel.

**Comment by delcypher** [comment]
@NikolajBjorner Sure. I prefer to not keep dead code lying around but it is up to you at the end of the day. I just wanted to draw attention to it just in case core devs weren't aware of this.

**Comment by NikolajBjorner** [comment]
after getting assurances that digging into this would require more work than reproducing it, it makes sense to remove.

**Comment by wintersteiger** [comment]
I further removed the associated test cases as the build was broken after removing `polynomial_factorization.cpp`.
