### ISSUE TITLE
Replayer bug: Missing 'else' in else-if chain?

### ISSUE THREAD

**Issue by calebvoss** [Z3Prover/z3#855]
I had an issue replaying a log file, getting the error message "unsupported array type" early on. Some quick debugging suggests there is potentially a missing 'else' [right here](https://github.com/Z3Prover/z3/blob/master/src/api/z3_replayer.cpp#L360), which causes arrays of UINT64 to get erroneously flagged as unsupported [down here](https://github.com/Z3Prover/z3/blob/master/src/api/z3_replayer.cpp#L393).

**Comment by NikolajBjorner** [comment]
yes
