### ISSUE TITLE
Segmentation fault in z3 optimize

### ISSUE THREAD

**Issue by mm95** [Z3Prover/z3#856]
Hi,
I call z3::optimize to solve and also optimize sum of some integers.below, you could see my sudocode and z3-log was attached too. with some program i get answer from above and with some other, i received segmentation fault.

         optimize opt(ctx);
         opt.add(formula);
         opt.minimize(sumof_some_integers_expr);
         opt.check(); // segmentation fault happens here

[z3.log.txt](https://github.com/Z3Prover/z3/files/671811/z3.log.txt)

**Comment by ntu-juking** [comment]
您好，
    您的来信我已收到，我将在稍晚的时候阅读您的来信。

----
Best Regards
Xiaolin JU
==========================================
School of Computer Science and Technology
Nantong University
==========================================
No.9 Seyuan Road,
Nantong,JiangSu Province, 226019
P.R.China

**Comment by mm95** [comment]
could I ask you to write in English, please?

**Comment by NikolajBjorner** [comment]
bing.translate.com and google.translate.com give me: 
"Hello
I have received your letter, I will at a later time to read your letter"
SO I have deleted the comment.

**Comment by NikolajBjorner** [comment]
The log file indicates you are using the following version of Z3: "4.4.2.1 Nov  4 2016"
Could you try 4.5 or the latest version in the master branch, 4.5.1?
I am not able to rerun your log file using the latest versions of Z3 because rerunning is sensitive to the set of calls exposed in the API.

**Comment by mm95** [comment]
Thanks so much, I tried version 4.5 and doesn't have any problem with my test cases.
