### ISSUE TITLE
Duality bug: overflow encountered when expanding vector

### ISSUE THREAD

**Issue by calebvoss** [Z3Prover/z3#858]
I've been tracking down this Heisenbug for a while. It kept plaguing my invocations of Duality over the API, but every time I asked for the smtlib dump of the problematic CHC system and copy-pasted it directly into the smtlib interpreter, the bug would disappear. I finally caught one that fails in the interpreter, and I was able to whittle it down into the following minimal example. For some extra puzzlement, the comments indicate a few transformations one can do that will make the bug vanish.

```
(set-option :fixedpoint.engine duality)

(declare-rel R_1 ())
(declare-rel R_2 (Int Int Int))
(declare-rel R_3 (Int Int Int))

(declare-var A Int)
(declare-var B Int)
(declare-var C Int)
(declare-var D Int)
(declare-var E Int)
(declare-var F Int)

(rule R_1)

(rule (=> (and R_1 ; <-- bug disappears if we eliminate R_1
               (not (= F E)) ; <-- bug disappears if these two vars are in lexicographical order, as far as I can tell (try other names)
               (= D F))
      (R_2 D E F)))

(rule (=> (and (R_2 D E F)
               (or (= 0 D) (= C D))
               (or (= B E) (= C E))
               (or (= B F) (= 0 F))
               (= A 0)) ; <-- bug disappears if we eliminate var A
          (R_3 A B C)))

(query R_3)
```

**Comment by NikolajBjorner** [comment]
This seems related to #864. It seems not to reproduce now.
