### ISSUE TITLE
Crash in solver API

### ISSUE THREAD

**Issue by nunoplopes** [Z3Prover/z3#86]
So that I don't lose this, Miguel Neves sent me this test cases that crashes on Cygwin (32 bit version only):
```
from z3 import *

myc = BitVec('myc', 2)
mad = BitVec('mad', 2)
out = BitVec('out', 2)

zero = BitVecVal(0, 2)
one = BitVecVal(1, 2)
two = BitVecVal(2, 2)

solv = Solver()

solv.add(Or(myc != zero, out == zero))
solv.add(Or(myc != one, mad != two, out == zero))
solv.add(Or(myc != one, Not(ULT(mad, two)), out == one))
solv.add(Or(myc != two, Not(UGT(mad, zero)), out == one))
solv.add(Or(myc != two, mad != zero, out == two))
solv.add(UGE(myc, zero), ULE(myc, two))
solv.add(UGE(mad, zero), ULE(mad, two))
solv.add(UGE(out, zero), ULE(out, two))

print solv.check()
```

**Comment by NikolajBjorner** [comment]
doesn't repro on win-x86

**Comment by nunoplopes** [comment]
I traced down this bug to libffi. In summary, newer gcc versions assume a 16-byte aligned stack, while libffi only guarantees a 4-byte aligned stack (on x86). Hence the crashes.
The issue is already documented in, e.g., http://bugs.python.org/issue17423
There's a work around, though, which would be to mark all API functions as potentially misaligned on 32-bit gcc platforms, but I guess it's not worth the effort.  Compiling with -O2, or disabling compilation with SSE "solves" the issue.
