### ISSUE TITLE
Z3 timeout in a simple query

### ISSUE THREAD

**Issue by nikivazou** [Z3Prover/z3#866]
`Z3` timeout in the following simple query:

http://rise4fun.com/Z3/u5tyC

In the above query: 
1. I assert an axiom that I do not need to use
2. then I assert a formula and its contradiction (using 2 different assertions) and 
3. check-sat (of both assertions).

Z3 timeouts even though I have `:smt.mbqi` set to `false`. 
Is there a flag I can use to check the above query or did I just hit a bug?

Thanks, 
Niki

**Comment by wintersteiger** [comment]
When `auto-config` is enabled, Z3 will enable MBQI when it sees a quantifier, so definitely disable it if you need to manually configure options. 

In this particular case however, MBQI is not the problem, instead e-matching simply starts producing lots of quantifier instances that clog the solver (it produces more and more deeply nested applications of `int_apply`). While not always possible, we can fix this particular example by adding a `no-pattern` annotation to the first quantifier, which tells Z3 not to instantiate this type of term, for instance like so:

```
(assert 
	(forall ((f Int) (g Int) (x Int)) 
        (!
            (= (int_apply (int_apply (int_apply compose f) g) x) 
                (int_apply f (int_apply g x)))
            :no-pattern (int_apply f (int_apply g x))
            ))
    )
```

This produces the desired result quickly, regardless of whether MBQI is on or off. (For more info on (no-)patterns see the [quantifier section of the tutorial](http://rise4fun.com/Z3/tutorialcontent/guide#h28).)

**Comment by nikivazou** [comment]
Thanks @wintersteiger! Very helpful! 
Is there a way to print - debug the qualifier instances that at produced?

**Comment by wintersteiger** [comment]
I usually dump debug traces directly from Z3 in debug mode, e.g., adding the command line option `-tr:qi_queue` (and lots of other trace names, see source code) will add diagnostic output to a file called `.z3-trace`, but this may be a bit uncomfortable if you're not familiar with Z3's internals. Others also use the axiom profiler (an external tool, see e.g. [here](http://stackoverflow.com/questions/35015628/where-can-the-z3-axiom-profiler-be-found)), which interprets and visualizes a trace specially defined for this purpose.
