### ISSUE TITLE
Enabling proofs per solver instance

### ISSUE THREAD

**Issue by PhilippWendler** [Z3Prover/z3#868]
We use Z3 via the API with a single context in which we put all our formulas. We create multiple solver instances, in some of which we need proofs for interpolation. Thus we have to set the option `PROOF` globally with `setParamValue`.

I assume that solving is more efficient if proof generation is turned off. Thus it would be good for our use case if we could enable it individually for each solver instance, and not just globally for the whole context.

**Comment by cheshire** [comment]
@PhilippWendler stupid question: are we sure that the proofs mentioned in that option are the same ones that Z3 uses for interpolation?

**Comment by PhilippWendler** [comment]
@cheshire Yes, if I disable this option interpolation fails immediately because `solverGetProof` produces the error "invalid usage".

**Comment by cheshire** [comment]
@PhilippWendler OK right, I don't know whether there is such an option right now. Maybe `:proofs` or something.

**Comment by NikolajBjorner** [comment]
I agree this would be nice, but proof mode is currently too deeply interwoven with how expressions are built and contexts are managed. This is mostly a by-product of how contexts were used as holistically maintaining assertions. This is a while ago, but changing this infrastructure would at most give the benefit you are seeking and there may be another workable solution as follows:
 
My recommendation for something usable is to create two contexts: one for proofs/interpolants, and the other for calls that don't require proofs. You can use the "translate" methods to import expressions from one context to another, thereby keeping solver states in sync where appropriate. Of course, your infrastructure can also build terms twice, but it is not required. The Z3_translate function translates expressions from one context to another. There are also functions for translating solvers and goals.

**Comment by PhilippWendler** [comment]
Thanks for mentioning the translate function, we will investigate this.
