### ISSUE TITLE
Confusing result when combining regular expressions and string results

### ISSUE THREAD

**Issue by jawline** [Z3Prover/z3#871]
Hi,

The following problem

```
(declare-const st (String))
(declare-const capture1 (String))
(declare-const capture2 (String))

(define-fun regexPortion1 () (RegEx String) (str.to.re "abcdefg"))
(define-fun in_portion_1 ((a String)) Bool (str.in.re a regexPortion1))

(define-fun regexPortion2 () (RegEx String) (re.++ regexPortion1 regexPortion1))
(define-fun in_portion_2 ((a String) (b String)) Bool (and (str.in.re a regexPortion2) (str.in.re b regexPortion1) (= a (str.++ b b))))

(define-fun regexPortion3 () (RegEx String) (re.* regexPortion2))
(define-fun in_portion_3 ((a String) (b String) (c String)) Bool (and (str.in.re a regexPortion3) (or (= a "") (and (in_portion_2 b c) (str.in.re a (re.+ (str.to.re b)))))))

(assert (in_portion_3 st capture1 capture2))

(check-sat)
(get-model)
(get-info :reason-unknown)
```

Fails to solve, with the message
```

unknown
(error "line 17 column 10: model is not available")
(:reason-unknown "smt tactic failed to show goal to be sat/unsat (incomplete (theory seq))")

```
However if I remove the or

(or (= a "") (and (in_portion_2 b c) (str.in.re a (re.+ (str.to.re b))))

and just have (and (in_portion_2 b c) (str.in.re a (re.+ (str.to.re b))) in its place, I get a solution. Is there any obvious reason for this?

I'm trying to create the regular expression ((SomeStuff)SomeStuffRepeated)*, which should leave 
st as a whole string accepted by the regular expression and capture1 and capture2 as portions of it, or st capture1 and capture2 as the empty string.

Thanks

**Comment by NikolajBjorner** [comment]
@mtrberzi: using z3str3 we get:
z3 test.smt2 smt.string_solver=z3str3
Failed to verify: regexNFA.is_valid()

**Comment by mtrberzi** [comment]
It looks like there's a term in this instance that's constructing a regex based on other terms found while solving -- Z3str3 doesn't have support for "non-constant" regex terms. For example we don't handle terms such as `(str.to.re capture1)` in this instance because `capture1` is not a string constant.

(But the error message could be improved. I'll add that to my list of small regex fixes in an upcoming PR.)

**Comment by NikolajBjorner** [comment]
@mtrberzi , thanks.
Neither solver support regular expressions with string variables (and the constraints aren't regular either when using variables).

**Comment by NikolajBjorner** [comment]
Murphy should address the non-graceful exit in z3str3, but otherwise, there is little to do here as the constraints use string variables in regular expressions. Perhaps generate warnings?

**Comment by NikolajBjorner** [comment]
behavior has changed. both solvers seem to handle it.
