### ISSUE TITLE
This shouldn't be satisfiable (strings)

### ISSUE THREAD

**Issue by pfdietz** [Z3Prover/z3#874]
(declare-const s String)
(declare-const s2 String)
(declare-const i Int)

(assert (= (str.len s) 1))
(assert (= (str.indexof "abcdefghijklmnopqrstuvwxyz" s) i))
(assert (or (and (= s s2) (< i 0))
            (and (= (str.at "ABCDEFGHIJKLMNOPQRSTUVWXYZ" i) s2)
                 (>= i 0))
	    ))
(assert (= s2 "a"))
(check-sat)
(get-model)

;;; This should be unsatisfiable, but Z3 4.5.0 reports it is satisfiable, with this invalid model:
(model 
  (define-fun i () Int
    (- 1))
  (define-fun s () String
    "a")
  (define-fun s2 () String
    "a")
)

**Comment by NikolajBjorner** [comment]
Thanks, a smaller example is:
(set-option :model-validate true)

(declare-const s String)
(declare-const s2 String)
(declare-const i Int)
(assert (= (str.len s) 1))
(assert (= (str.indexof "a" s) i))
(assert (or (and (= s s2) (< i 0)) (and (= (str.at "A" i) s2) (>= i 0))))
(assert (= s2 "a"))
(check-sat)
(get-model)

**Comment by NikolajBjorner** [comment]
with other fixes Z3 now reports unsat on these
