### ISSUE TITLE
String formatting error in update_api.py

### ISSUE THREAD

**Issue by jwilk** [Z3Prover/z3#879]
`scripts/update_api.py` contains the following statement:
```python
error ("unsupported parameter for %s, %s" % (ty, name, p))
```
There are two conversions, but 3 arguments for the `%` operator, so this will cause:
```
TypeError: not all arguments converted during string formatting
```

Found using [pydiatra](https://github.com/jwilk/pydiatra).

**Comment by NikolajBjorner** [comment]
Thanks
