### ISSUE TITLE
Segmentation fault on Linux

### ISSUE THREAD

**Issue by Heizmann** [Z3Prover/z3#880]
I get a segmentation fault on the attached script.
Z3 version 962979b09c991fc47a02e10afb07d68a353308ff
My system ``Linux x86_64``
Z3 was not called with any additional parameters.
I did not had this problem with a version that I compiled at the beginning of January.
[Script_BoogieIcfgContainer_array02-alloca_true-valid-memsafety.i_Iteration11.smt2.txt](https://github.com/Z3Prover/z3/files/735207/Script_BoogieIcfgContainer_array02-alloca_true-valid-memsafety.i_Iteration11.smt2.txt)

**Comment by NikolajBjorner** [comment]
Thanks, odd it wasn't triggered before.

**Comment by Heizmann** [comment]
Thanks, your commit solved our problem.
