### ISSUE TITLE
An interface like the web one.

### ISSUE THREAD

**Issue by k53sc** [Z3Prover/z3#883]
Hi All,

Hope you all are doing well,
Is there any way I can build Z3 interface like the one at http://rise4fun.com/z3/ locally at my machine,
I understand there are Python and C++ etc binding but I find that while debugging in ( C++ )  It would be really helpful if we can copy paste Z3 statements ( declare-fun, assert ) and reproduce a situation.

Thanks for reading.
Ayush

**Comment by wintersteiger** [comment]
If you use Python for other tasks, you may find it easy to use that API (see e.g. [here](https://github.com/Z3Prover/z3/wiki/Using-Z3Py-on-Windows)). 

Personally, I use emacs to edit SMT2 files with a customized [smtlib mode](https://github.com/chsticksel/smtlib-mode). There are multiple other emacs interfaces, but I didn't try those yet (e.g. [this](https://github.com/zv/z3-mode), which also comes via MELPA package). These also allow you to run the solver within emacs, with error highlighting, etc.

**Comment by NikolajBjorner** [comment]
See also
https://notebooks.azure.com/nbjorner/projects/z3examples
