### ISSUE TITLE
Wrong sat result when optimizing

### ISSUE THREAD

**Issue by jordicollcaballero** [Z3Prover/z3#884]
Hi,

I'm using z3 optimization feature from SMTLibv2 files. When I try to minimize the attached problem (which is unsatisfiable), z3 says 'sat' with objective value x_4=4. If I comment the line '(minimize x_4)' line, then z3 says unsat.

Am I doing something wrong?

[file.txt](https://github.com/Z3Prover/z3/files/739534/file.txt)

Thanks!

**Comment by NikolajBjorner** [comment]
Thanks, the optimization mode got side-tracked from the (set-logic QF_LIA) designation. If you take it away it works correctly. I have updated the solver to ensure it gets on the right track.
