### ISSUE TITLE
Java api memory leak?

### ISSUE THREAD

**Issue by varming** [Z3Prover/z3#886]
I was looking at the JNI code for the java api (in Native.cpp) and noticed a number of calls to `GetStringUTFChars` without corresponding calls to `ReleaseStringUTFChars`. At best that will result in a memory leak. I haven't tracked down the use of the resulting allocated array, but there is no guarantee that the JVM returns a piece of memory obtained from `malloc`, thus you cannot safely free the memory. Furthermore, if the JVM is running with native memory tracking turned on, then the memory allocated by `GetStringUTFChars` will not be safe to pass to `free`.

**Comment by wintersteiger** [comment]
What is the right point in time at which the strings can be safely released? I don't think any of those pointers are passed to `free` at the moment, are they?

**Comment by cheshire** [comment]
The Java bindings we were previously using for Z3 were calling `ReleaseStringUTFChars` after every `GetStringUTFChars`, and that was working. Let me check this again and submit a pull request.

**Comment by cheshire** [comment]
@varming @wintersteiger I think this commit should be sufficient.
