### ISSUE TITLE
z3 report model unavailable wrongly

### ISSUE THREAD

**Issue by cfuxiang** [Z3Prover/z3#887]
Hi,

I'm passing the following constraint to z3py, which is making use of z3. z3 outputs that the model is unavailable. I'm assuming it is UNSAT in z3's view.

However, I am able to solve this constraint using the below set of values. 

Constraint: (i5 + i6) < ((i5 * i8) - (i6 * i8)) , 0 != (i5 * (i13 - i8)) , 1 != (i5 * (i13 - i8)) , 2 != (i5 * (i13 - i8)) , 3 != (i5 * (i13 - i8)) , 4 != (i5 * (i13 - i8)) , 5 != (i5 * (i13 - i8)) , 6 != (i5 * (i13 - i8)) , 7 != (i5 * (i13 - i8)) , ((i0 * i6) - (i7 - i0)) < ((i6 % 963) + (441 * i7))

z3 says that the model is unavailable.

Values solvable: i5 = -1, i6 = 1, i8 = -1, i13 =1, i0 = -1, i7 = 0

Substituting the values into the constraint, we get

(-1 + 1) < ((-1 * -1) - (1 * -1)) , 0 != (-1 * (1 - -1)) , 1 != (-1 * (1 - -1)) , 2 != (-1 * (1 - -1)) , 3 != (-1 * (1 - -1)) , 4 != (-1 * (1 - -1)) , 5 != (-1 * (1 - -1)) , 6 != (-1 * (1 - -1)) , 7 != (-1 * (1 - -1)) , ((0 * 1) - (0 - 0)) < ((1 % 963) + (441 * 0))

=> (further simplifying, we get)
 
(0) < (2) , 0 != (-2) , 1 != (-2) , 2 != (-2)) , 3 != (-2) , 4 != (-2) , 5 != (-2) , 6 != (-2) , 7 != (-2) , (0) < (1)

As you can see, this is indeed satisfiable.

I also try to incrementally test each subconstraint one at a time. The issue seems to be at the last subconstraint ((0 * 1) - (0 - 0)) < ((1 % 963) + (441 * 0))

If I change the % operator to a +, then it works.

This seems like a bug to me.

**Comment by wintersteiger** [comment]
Could you provide us with the exact source code that lets us reproduce the problem? Very often, the problem is a subtle point about the encoding that triggers the wrong result, instead of an actual bug.

**Comment by cfuxiang** [comment]
Sure. The exact source code is shown below:

`
from z3 import *

i0 = Int('i0')
i5 = Int('i5')
i6 = Int('i6')
i7 = Int('i7')
i13 = Int('i13')

s = Solver()
s.add((i5 + i6) < ((i5 * i8) - (i6 * i8)) , 0 != (i5 * (i13 - i8)) , 1 != (i5 * (i13 - i8)) , 2 != (i5 * (i13 - i8)) , 3 != (i5 * (i13 - i8)) , 4 != (i5 * (i13 - i8)) , 5 != (i5 * (i13 - i8)) , 6 != (i5 * (i13 - i8)) , 7 != (i5 * (i13 - i8)) , ((i0 * i6) - (i7 - i0)) < ((i6 % 963) + (441 * i7)))

print(s.check())
print(s.model())
`

**Comment by NikolajBjorner** [comment]
This is not a bug: Z3 is unable to find the solution in the first place. It uses non-linear arithmetic and Z3 is highly incomplete for non-linear integer arithmetic. 
So Z3 reports "unknown". No model is produced in this case.
