### ISSUE TITLE
check-sat-using ignores smt.core.minimize

### ISSUE THREAD

**Issue by chstdu** [Z3Prover/z3#888]
For our SMT2 problems in QF_LRA we are using z3 version 4.5.0 with the tactics proposed at [StackOverflow](http://stackoverflow.com/a/34770475) with `check-sat-using` instead of the default solver to massively speed up the solving. However, we recognized that the unsat-core we get from `(set-option :produce-unsat-cores true)` and `(get-unsat-core)` is not always inclusion-minimal, not even if we additionally set `(set-option :smt.core.minimize true)` at the beginning.

If we omit the tactics and only use `check-sat`, the unsat-cores in our examples are inclusion-minimal. Therefore, we suppose, that `check-sat-using` ignores the `smt.core.minimize` setting. Can we change this somehow?

**Comment by NikolajBjorner** [comment]
sure, sounds like a bug. Do you have a (sufficiently simple) repro I can use?

**Comment by chstdu** [comment]
We now tried to make one of our problems sufficiently simple. If we apply `check-sat-using` the unsat-core contains all 10 constraints. However, if we use only `check-sat`, we get an unsat-core with only 6 constraints. We have `(set-option :smt.core.minimize true)` in both cases.

[short.smt2.txt](https://github.com/Z3Prover/z3/files/750172/short.smt2.txt)

**Comment by chstdu** [comment]
Here are the two examples in rise4fun:
- [`check-sat-using` ](http://rise4fun.com/Z3/vvOI)
- [`check-sat` ](http://rise4fun.com/Z3/XEplS)

**Comment by NikolajBjorner** [comment]
This is unfortunately a bit tricky. Mainly, when using tactics, assumptions are tracked as dependencies and some of the transformations over-approximate them. Even after adding core minimization inside of the tactic that calls the smt end-game solver, I don't get minimal cores.

**Comment by VotingTool** [comment]
Unfortunately, this bug is still not solved in the latest nightly build (https://git.io/JeWsE), although flagged as closed. A compromise could be to first run z3 without core minimization but using tactics and then automatically run z3 again taking only the unsat-core as input and this time ignoring the tactics but minimizing the core.

**Comment by NikolajBjorner** [comment]
It is a won't fix. The tactics prevent core minimization. It works for incremental solvers.
