### ISSUE TITLE
Check-sat with assumptions on non-linear real arithmetic

### ISSUE THREAD

**Issue by AdrienChampion** [Z3Prover/z3#89]
I noticed differences in how z3 behaves when using the `(check-sat)` and `(check-sat <assumptions>)` commands on non-linear real arithmetic problems.

The latter returns `unknown` on most satisfiable problems when the former is able to answer just fine (see example below).

While I could use push/pop to get the same features as check-sat with assumptions, my understanding is that this impacts performance significantly which was confirmed by my experiments (on linear arithmetic).

Is this a bug, a consequence of the way check-sat with assumptions is implemented, a problem I could avoid with a clever option, or something else?

    ;; Using the "unstable" branch.
    (declare-fun x () Real)
    (declare-fun y () Real)
    (declare-fun act_1 () Bool)
    (declare-fun act_2 () Bool)
    
    ;; This is fine.
    ( assert (=> act_1 (= (* x y) 0.0)) )
    (check-sat act_1)
    ;; sat
    
    ;; This is also fine with a regular check-sat...
    ( assert (= (* x y) 42.0) )
    (check-sat)
    ;; sat
    
    ;; ...but not with check-sat with assumptions.
    ( assert (=> act_2 (= (* x y) 42.0)) )
    (check-sat act_2)
    ;; unknown

**Comment by leodemoura** [comment]
Z3 contains several solvers. One of them is `nlsat`, a solver for non-linear real arithmetic. However, `nlsat` does not support assumptions, it is not incremental, and it is not integrated with the other theories. `nlsat` is implemented here: https://github.com/Z3Prover/z3/tree/master/src/nlsat
The general purpose solver (which is incremental, supports assumptions, many theories, ...) is implemented here: https://github.com/Z3Prover/z3/tree/master/src/smt

The general purpose solver uses incomplete methods for non-linear arithmetic. 
There are some posts about that at stackoverflow:
http://stackoverflow.com/search?q=%5Bz3%5D+nonlinear

**Comment by AdrienChampion** [comment]
I though check-sat with assumption simply forces some decisions at DPLL level and does not change anything in the solving at theory level. My view was too simplistic.

So the problem is that assumptions prevent z3 from using `nlsat`, and the query is handled completely differently.

Anyway the bottom line is that I should use push/pop instead so that `nlsat` is used and I get an answer, with the cost of more or less restarting when I pop.

Thank you for your answer :)

By the way, I should have mentioned that I use the unstable branch of z3 (edited original post).

**Comment by leodemoura** [comment]
`nlsat` is not based on the standard DPLL approach used in SMT.
It uses its own model constructing search engine. The calculus implemented by `nlsat` is described here: http://leodemoura.github.io/files/IJCAR2012.pdf

BTW, you can use the command 
```
(check-sat-using qfnra-nlsat)
````
to force Z3 to use `nlsat`
