### ISSUE TITLE
C API considerably slower then z3 -smt2 FILE on string queries

### ISSUE THREAD

**Issue by jawline** [Z3Prover/z3#890]
Hi,

Executing several string queries takes ms in the Z3 client, but up to 30-40s when invoked by the C API for some tests I am running.

The binary client and the libz3.dylib where built at the same time, from the same version.

An example of one such query is

```
(declare-fun Arg () String)
(declare-fun |2 Fill 4| () String)
(declare-fun Arg2 () String)
(assert (let ((a!1 (re.++ (re.++ (str.to.re "-") (str.to.re "-"))
                  (re.+ (re.union (re.range "\x00" "\x09") (re.range "\v" "y"))))))
(let ((a!2 (re.++ (re.++ a!1 (str.to.re "="))
                  (re.* (re.union (re.range "\x00" "\x09") (re.range "\v" "y"))))))
  (str.in.re Arg a!2))))
(assert (let ((a!1 (re.+ (re.inter (re.union (re.range "\x00" "\x09")
                                     (re.range "\v" "y"))
                           (re.complement (str.to.re "="))))))
(let ((a!2 (re.++ (re.++ (re.++ (str.to.re "-") (str.to.re "-")) a!1)
                  (str.to.re "="))))
(let ((a!3 (re.++ a!2 (re.* (re.union (str.to.re "s") (str.to.re "S"))))))
  (str.in.re Arg a!3)))))
(assert (not (= Arg "")))
(assert (let ((a!1 (re.++ (str.to.re "0x")
                  (re.+ (re.union (re.range "0" "9") (re.range "a" "f"))))))
  (not (str.in.re |2 Fill 4| a!1))))
(assert (let ((a!1 (re.union (str.to.re "")
                     (re.++ (str.to.re ".") (re.* (re.range "0" "9")))))
      (a!4 (re.++ (str.to.re "e")
                  (re.union (str.to.re "")
                            (re.union (str.to.re "-") (str.to.re "+"))))))
(let ((a!2 (re.union (re.++ (re.+ (re.range "0" "9")) a!1)
                     (re.++ (str.to.re ".") (re.+ (re.range "0" "9")))))
      (a!5 (re.union (str.to.re "") (re.++ a!4 (re.+ (re.range "0" "9"))))))
(let ((a!3 (re.++ (re.union (str.to.re "")
                            (re.union (str.to.re "-") (str.to.re "+")))
                  a!2)))
  (not (str.in.re |2 Fill 4| (re.++ a!3 a!5)))))))
(assert (let ((a!1 (re.++ (re.++ (str.to.re "-") (str.to.re "-"))
                  (re.+ (re.union (re.range "\x00" "\x09") (re.range "\v" "y"))))))
(let ((a!2 (re.++ (re.++ a!1 (str.to.re "="))
                  (re.* (re.union (re.range "\x00" "\x09") (re.range "\v" "y"))))))
  (not (str.in.re Arg2 a!2)))))
(assert (let ((a!1 (re.++ (re.++ (re.++ (str.to.re "-") (str.to.re "-no"))
                         (str.to.re "-"))
                  (re.+ (re.union (re.range "\x00" "\x09") (re.range "\v" "y"))))))
(let ((a!2 (re.++ a!1
                  (re.* (re.union (re.range "\x00" "\x09") (re.range "\v" "y"))))))
  (not (str.in.re Arg2 a!2)))))
(assert (let ((a!1 (re.++ (re.++ (str.to.re "-") (str.to.re "-"))
                  (re.+ (re.union (re.range "\x00" "\x09") (re.range "\v" "y"))))))
(let ((a!2 (re.++ a!1
                  (re.* (re.union (re.range "\x00" "\x09") (re.range "\v" "y"))))))
  (not (str.in.re Arg2 a!2)))))
(assert (let ((a!1 (re.+ (re.inter (re.union (re.range "\x00" "\x09")
                                     (re.range "\v" "y"))
                           (re.complement (str.to.re "-"))))))
(let ((a!2 (re.++ (re.++ (str.to.re "-") a!1)
                  (re.* (re.union (re.range "\x00" "\x09") (re.range "\v" "y"))))))
  (str.in.re Arg2 a!2))))
(assert (not (= Arg2 "")))
```

Does invoking z3 -smt set up any specific solver or defaults which could be slowing me down in the C API?

Thanks

**Comment by NikolajBjorner** [comment]
It could be flakiness. trying with smt.random_seed=114 from the command line makes the solver spend 8 seconds instead of 0.3.

**Comment by NikolajBjorner** [comment]
From the API, we can observe flakiness from different seeds as follows.

`from z3 import *
from time import *

fml = parse_smt2_file("flaky.smt2")


for i in range(100):
   print i
   s = Solver()
   s.add(fml)
   s.set("smt.random_seed", i+1) 
   t = time()
   print s.check()
   print time() - t
   print s.statistics()`

**Comment by jawline** [comment]
Hi Nicolaj,

Thanks for your quick response

Is it possible to set the random seed via C API to perform the same experiment.
Also how is this generated in the C API, is it per solver, per query etc?

Cheers,
Blake

**Comment by NikolajBjorner** [comment]
The Python API calls into the C API. So anything done from Python can be done from C. You basically set parameters.

**Comment by jawline** [comment]
That's great, Thanks. I will explore whether this is caused by changing the random seed.

**Comment by jawline** [comment]
I'm still confused by the issue. Are there any special rules for the random seed on smt2 files? Or does it have a fixed seed different to the C API default?

Changing the random seed does indeed change the time taken to solve, however the problem always solves within a second on my local machine z3 binary. I can execute it repeatedly and it never takes particularly long.

In my application calling the solver through an API with some randomly generated seed number or with no specific seed generally takes a significant amount of time, way longer then with the binary.

I'm testing them by printing the solver to SMT and testing that output in the binary against the time it takes to perform those operations with the C API.

The code I'm using to set up my solver instance is something similar to
```
        let config = Z3.Z3_mk_params(this.ctx);
        Z3.Z3_params_inc_ref(this.ctx, config);
        Z3.Z3_params_set_uint(this.ctx, config, Z3.Z3_mk_string_symbol(this.ctx, "smt.random_seed"), SOME_NUMBER);
        
        this.slv = Z3.Z3_mk_simple_solver(this.ctx);
        Z3.Z3_solver_set_params(this.ctx, this.slv, config);
        Z3.Z3_solver_inc_ref(this.ctx, this.slv);
```

**Comment by NikolajBjorner** [comment]
Using the C++ front-end would help avoiding bugs. 
It is potentially dangerous to defer the Z3_solver_inc_ref. 
It should be immediately after the return of Z3_mk_simple_solver.
By default, the python front-end uses Z3_mk_solver, but I tried also with SimpleSolver, and get the same results.

**Comment by jawline** [comment]
Woops, yes. Good spot. Unfortunately we can't use the cpp api as we call in from JavaScript. 

Thanks for your help,  it does seem to be flakyness that's causing the issue so we will work around it for now.

Cheers,
