### ISSUE TITLE
Confusing performance when combining reals and string length

### ISSUE THREAD

**Issue by jawline** [Z3Prover/z3#892]
Hi,

When I run the following query I get really poor performance, however if I run it with to_int 256.0 or just 256 it works fine.

If I run it through the simplifier it seems to be doing to_real (str.len Arg1) rather than casting the other half (256.0) to an int. This seems to be causing problems, especially in solutions where the other side resolves to a constant.

Is there any way to make reduce this issue within Z3? I can cast all the queries against to_int before involving them in string operations on my end but I'm not sure if its the best solution.

```
(declare-fun Switcher () Real)
(declare-fun Arg1 () String)
(assert (not (= Switcher 0.0)))
(assert (= Switcher 1.0))
(assert (not (= Arg1 "")))
(assert (not (<= (str.len Arg1) 256.0)))

(check-sat)
(get-model)
```

Thanks

**Comment by NikolajBjorner** [comment]
Correct, mixed integer linear solving could be improved.
You can solve this example by enabling some pre-prossing simplification, which is not on by default.
Use the option: rewriter.elim_to_real=true

**Comment by jawline** [comment]
Ah brilliant, pre processing will probably work well enough for our use cases.

Thanks for the help
