### ISSUE TITLE
Get 'low' and 'high' variables from Extract expression  -- Python API

### ISSUE THREAD

**Issue by 0-14N** [Z3Prover/z3#896]
Hi guys,

I am using Python to traversal expressions, but when I wanted to traversal the Extract expression, I cannot get the 'low' and 'high' variables because the function 'num_args' returns 1, and 'arg(0)' returns the expression to be extracted. I am wondering how to get those two variables?
Thanks in advance!

**Comment by NikolajBjorner** [comment]
Try using the "params()" method on expressions. It should return a tuple of size 2.

**Comment by sanpang-kim** [comment]
Hi Nikolaj, thanks for replying, but I cannot find either function or attribute named "params" on the expression.

**Comment by 0-14N** [comment]
Hi Nikolaj, thanks for replying, but I cannot find either function or attribute named "params" on the expressions. "BitVecRef instance has no attribute 'params'"

**Comment by NikolajBjorner** [comment]
Try:

    from z3 import *
    x = BitVec('x', 10)
    y = Extract(8, 3, x)
    print y.decl().params()

I have also updated the master branch now so that you can write y.params()

**Comment by 0-14N** [comment]
It works! Thank you so much!
