### ISSUE TITLE
Bug with recursive function models?

### ISSUE THREAD

**Issue by LeventErkok** [Z3Prover/z3#898]
I'm trying recursive functions in z3, and I'm curious if there's a bug with model construction. Consider:

    (define-fun-rec f ((x Int)) Int
                      (ite (> x 1)
                           (f (- x 1))
                           1))
    (check-sat)
    (get-value ((f 0)))

Here `f` is actually the constant function `1`, just defined in a silly way. For this input, z3 prints:

    sat
    (((f 0) 0))
   
This seems incorrect, since `f 0` should equal `1`.

What's interesting is if I assert what z3 proposes as the result, then I get the correct `unsat` answer:

    (define-fun-rec f ((x Int)) Int
                      (ite (> x 1)
                           (f (- x 1))
                           1))
    (assert (= (f 0) 0))
    (check-sat)

I get:

    unsat

So, it looks like z3 actually does now that `f 0` cannot be `0`; even though it produced that very model in the previous case.

Taking this one step further, if I issue:

    (define-fun-rec f ((x Int)) Int
                      (ite (> x 1)
                           (f (- x 1))
                           1))
    (assert (= (f 0) 1))
    (check-sat)
    (get-model)

Then z3 responds:

    sat
    (model
      (define-fun f ((x!0 Int)) Int
        1)
    )

which is indeed a reasonable answer.

So, it seems perhaps there's a bug with recursive function models under certain conditions?

**Comment by NikolajBjorner** [comment]
The models may lie. 
If you plan to evaluate f on 0, then include it in the constraints you want to check.

     (define-fun-rec f ((x Int)) Int
                  (ite (> x 1)
                       (f (- x 1))
                       1))
     (declare-fun I-want-to-evaluate (Int) Bool)
     (assert (I-want-to-evaluate (f 0)))

    (check-sat)
    (get-model)
    (get-value ((f 0)))

**Comment by NikolajBjorner** [comment]
Of course, in a reasonable sense it is a bug. The evaluator should know about the recursive functions.

**Comment by LeventErkok** [comment]
Thanks @NikolajBjorner 

Of course, I may *not* know ahead of time what values I'll evaluate the model on; especially in a programmatic API that can use the model downstream in some fashion.

I'll leave this here so you can either close it or address it somehow. (Maybe the model function should return an uninterpreted constant of some sort to be safe?)

Also note that there's a stackoverflow question for the same: http://stackoverflow.com/questions/42171470/bug-with-recursive-functions

If you respond there, I'd be happy to accept that answer so others can benefit and not be confused similarly.

**Comment by NikolajBjorner** [comment]
I plan to check in updated Z3 and address comments this week.

**Comment by NikolajBjorner** [comment]
sorry this slipped. It is a potentially intrusive change. I have to short-circuit simplification of if-then-else terms in order to ensure that the evaluator terminates.

**Comment by NikolajBjorner** [comment]
can we close this? I believe the models now are more intuitive as they would correspond to the recursive function definitions.

**Comment by LeventErkok** [comment]
I'm still seeing some weird behavior. I modified the definition slightly, but otherwise ran the exact same experiment with the following input:

```
(define-fun-rec f ((x Int)) Int
     (ite (> x 1)
          (+ x (f (- x 1)))
          1))
; (assert (= (f 5) 0))
(check-sat)
(get-value ((f 5)))
```

With this, z3 says:

```
sat
(((f 5) 0))
```

If I uncomment the `(assert (= (f 5) 0))` line, I get:

```
unsat
```

So, precisely the same kind of confusing behavior is observed when the function is a bit more complicated.

**Comment by NikolajBjorner** [comment]
touché. It now pretends the function returns 15 = 5 + 4 + 3 + 2 + 1.

**Comment by LeventErkok** [comment]
Fantastic! (I threw fibonacci at it, and worked like a charm 👍 )
