### ISSUE TITLE
Wrong model when using re.complement

### ISSUE THREAD

**Issue by facanferff** [Z3Prover/z3#899]
Hi, I'm trying to generate a string value given a very simple regular expression, such as [^A], which I would expect any string of length 1 of any character except A (e.g. "B"), but instead of that Z3 is generating an empty string.

I tried for this the following code:
```
(declare-fun string () String)

(assert (str.in.re 
    string
    (re.complement (str.to.re "A"))
))


(check-sat)
(eval string)
```

But this generates an empty string ("").

Even if I try with re.+:
```
(declare-fun string () String)

(assert (str.in.re 
    string
    (re.+ (re.complement (str.to.re "A")))
))


(check-sat)
(eval string)
```

The string is always empty.

Am I doing something wrong here?

Thanks.

**Comment by NikolajBjorner** [comment]
The language of (re.complement (str.to.re "A")) is the set of strings:
     Sigma* \ { "A" } = { "", "B", "C", "AA", "AB", .... }
where Sigma is the set of characters (8 -bit bit-vectors).
This language includes the empty string.
Similarly the second example, you can take a non-zero number of repetitions of the empty string and you still get the empty string. so the empty string is also in (re.+ (re.complement (str. to.re "A")))
