### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [Z3Prover/z3#9]
I would like to point out that identifiers like "[`_API_AST_MAP_H_`](https://github.com/Z3Prover/z3/blob/dcf778a2875daad739cec466defb37d1a6c4ad67/src/api/api_ast_map.h#L18)" and "[`_SOLVER_H_`](https://github.com/Z3Prover/z3/blob/904ab4bf9e1cf9f147218b88bbfd8ecc8b1a8a0e/src/solver/solver.h#L19)" [do eventually not fit](https://www.securecoding.cert.org/confluence/display/cplusplus/DCL51-CPP.+Do+not+declare+or+define+a+reserved+identifier#DCL51-CPP.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28HeaderGuard%29 "Do not use identifiers that are reserved for the compiler implementation.") to the expected naming convention of the C++ language standard.
Would you like to adjust your selection for unique names?

**Comment by elfring** [comment]
Are there [any more update candidates](https://github.com/Z3Prover/z3/blob/5e5758bb25e080cb45ae0bd7c6e0a3593e1f6606/src/ast/ast_smt2_pp.h#L22 "Reconsider identifier selection?") left over?

**Comment by nunoplopes** [comment]
The fix was done on the unstable branch, not on master. I did a grep and there's nothing fundamental left behind.

**Comment by elfring** [comment]
How do think about to clean-up [the use of double underscores in more identifiers](http://stackoverflow.com/questions/228783/what-are-the-rules-about-using-an-underscore-in-a-c-identifier#answer-228797 "What are the rules about using an underscore in a C++ identifier?")?
Would you like to tamper with the reserved name space even less in your code base?

**Comment by nunoplopes** [comment]
Of course we aim to have fully well-defined code, which I'm sure we don't have at the moment.
Please feel to give concrete suggestions about what needs fixing.  Thanks!

**Comment by elfring** [comment]
Examples for further update candidates:
* `DDNF__H_`
* `SCOPED_PROOF__H_`
* `Z3_PRIVATE__H_`
