### ISSUE TITLE
QF_ALIA not recognized

### ISSUE THREAD

**Issue by DavidDeharbe** [Z3Prover/z3#90]
Hi,

When calling z3 with option `-smt2`
```
(set-logic QF_ALIA)
```
results in the following output:
```
WARNING: unknown logic, ignoring set-logic command
```

Although QF_ALIA is not explicitly listed in the “Logics” section in the smt-lib.org web site, it appears in the graph of logics in that same page. Also there is definitely a QF_ALIA category in the 2014-06-03 SMT-LIB benchmark repository.

Best regards,

-- David Déharbe.

**Comment by wintersteiger** [comment]
Thanks for reporting this. I've now added that to the supported logics, so it doesn't complain anymore.

**Comment by wintersteiger** [comment]
Closing this as fixed, please reopen if problems remain.
