### ISSUE TITLE
Converting string at index to int

### ISSUE THREAD

**Issue by jawline** [Z3Prover/z3#903]
Is there any existing mechanism to get a single char from a string and convert it to an integer, something that would be equivalent to say 'x'.charCodeAt(0).

**Comment by NikolajBjorner** [comment]
It's a good point. Z3's functions follows pretty much what the SMT-LIB2 efforts around strings are taking. There is str.at/seq.at, but it returns a string/sequence of length 1. My understanding is that the SMT-LIB2 efforts preferred to keep character types opaque. So accessing a character code would break this.

In Z3 there is one way to break the abstraction: Strings are sequences of 8 bit characters.
You can then define a relation and use it for accessing the character code.

    (define-fun char_at ((s String) (index Int) (ch (_ BitVec 8))) Bool
              (= (str.at s index) (seq.unit ch)))

    (declare-const s0 String)
    (declare-const i0 Int)
    (declare-const ch0 (_ BitVec 8))
    (assert (char_at s0 i0 ch0))
    (assert (<= 0 i0))
    (assert (<= i0 (str.len s0)))
    (check-sat) 
    (get-model)

If you want a function (charCodeAt), then for every occurrence of that function (charCodeAt s1 i1) add the assertion 

            (=> (and (<= 0 i1) (< i1 (str.len s1)) (char_at s1 i1 (charCodeAt s1 i1))

**Comment by jawline** [comment]
Ah, that's great. Thank you.
