### ISSUE TITLE
fp.rem (-0) (0.5) should be -0, but Z3 produces +0

### ISSUE THREAD

**Issue by LeventErkok** [Z3Prover/z3#91]
Happy to provide an SMTLib benchmark if that'd help; but the subject says it all. The semantics of fp.rem is such that the output should follow the sign of the first argument, but Z3 is violating that in this particular case. Note that this is similar to (but not the same as) #80 at it pertains to the smt-lib semantics of fp.rem (and the corresponding C function fmodf.)

**Comment by wintersteiger** [comment]
Hmm. (-0) (0.5) is a negated real, i.e., a sign-less 0, so I think Z3 is right on this one. fp.rem does indeed produce the sign of the first argument for these:

`(assert (= x (fp.rem (_ -zero 11 53) (fp #b0 #b01111111111 #x0000000000000))))`
`(assert (= x (fp.rem (_ +zero 11 53) (fp #b0 #b01111111111 #x0000000000000))))`

**Comment by LeventErkok** [comment]
Maybe there's something else going on here. But, here's my benchmark:

```
(set-option :produce-models true)
(set-logic QF_FP)
(define-fun s2 () (_ FloatingPoint  8 24) ((_ to_fp 8 24) roundNearestTiesToEven (/ 1 2)))
(define-fun s4 () (_ FloatingPoint  8 24) (fp.neg ((_ to_fp 8 24) roundNearestTiesToEven (/ 0 1))))
(declare-fun s0 () (_ FloatingPoint  8 24))
(declare-fun s1 () (_ FloatingPoint  8 24))
(assert
   (let ((s3 (fp.eq s1 s2)))
   (let ((s5 (fp.rem s4 s1)))
   (let ((s6 (= s0 s5)))
   (let ((s7 (and s3 s6)))
   s7)))))
(check-sat)
(get-value (s0))
```

It's a bit convoluted due to its machine generated nature; but you can see that the value of `s0` should be `fpRem (-0) (0.5)` in any model that satisfies this query. (Also not the explicit use of `=` in `s6` to avoid `-0 equals +0` trap; so I should really get a `-0` as the answer.)

This is what z3 gives me:

```
sat
((s0 (_ +zero 8 24)))
```

That tells me that the result is `+0` not `-0`.

Am I misreading this?

**Comment by wintersteiger** [comment]
Aha! Yes, there was more to this. The special case detection for literals was right, but if the -zero emerged as a result of the computation the rounder put the wrong sign on it. This is now fixed, so I'm closing the issue.

**Comment by LeventErkok** [comment]
Fantastic, it works as expected now. I belive #80 is the only remaining one on fp.rem semantics that I have a gripe with. Did you get a chance to look at that one?
