### ISSUE TITLE
Cheap simplification option?

### ISSUE THREAD

**Issue by cheshire** [Z3Prover/z3#911]
Hi,

when using the optimizing solver, the calls to `upper`/`lower` may return AST objects with `epsilon` formula inside. I get rid of those by performing substitution followed by the simplification (assuming I know what epsilon can be safely replaced by) in order to be able to convert it to number by using `get_numeral_string`.
Yet that has some disadvantages: Z3 default simplification is rather heavy-weight, and can be interrupted.
Is there possibly simpler and lighter approach? Could be my best bet simply turning off all (almost all) options inside the `simplify` call

**Comment by NikolajBjorner** [comment]
The format is a*infinity +b + c*epsilon, where the first and last component vanish when a resp. c are 0.
So kludge 1 is to rely on this format.
Perhaps the feedback is basically that we need to redesign the format of the output. 
We could, for instance expose an API that returns a, b, c directly.
In most uses a, c would be zero.

**Comment by cheshire** [comment]
> We could, for instance expose an API that returns a, b, c directly.

That would solve my problem. Currently I rely on manually detecting the string `"oo"`, and manually creating and substituting the variable `epsilon`. And I don't even want to think what happens when my optimization problem already contains the variable `epsilon`.

**Comment by NikolajBjorner** [comment]
try this (if you can also port to the Java API it will be appreciated)

**Comment by cheshire** [comment]
OK great I think can be closed now!
