### ISSUE TITLE
Incorrect model when combining str.in.re and str.replace

### ISSUE THREAD

**Issue by dschoepe** [Z3Prover/z3#912]
It seems that Z3 returns a faulty model when mixing str.in.re and str.replace. Here's a somewhat minimal example for this behavior:

```
(declare-const s String) 
(declare-const t String) 
(assert (= t (str.replace s "A" "b"))) 
(assert (str.in.re t (re.++ (re.* (re.range "B" "Z")) (str.to.re "A")))) 
(check-sat) 
(get-model) 
```

This yields the output
```
sat
(model 
  (define-fun t () String
    "A")
  (define-fun s () String
    "A")
)
```

However, this seems to violate the first assertion; for example, `(simplify (str.replace "A" "A" "b"))` prints `"b"`, which is not the same as `"A"`. The behavior disappears when changing the second assertion to `(assert (str.suffixof "A" t))`. While the manual states that the procedures for `str.in.re` are incomplete, this seems to be a soundness problem.

**Comment by NikolajBjorner** [comment]
The example is unsat. With the fixes, Z3 is not returning a faulty model, but loops as it does not know how to close the search branch (yet).

**Comment by NikolajBjorner** [comment]
The unsoundness bug has been fixed. Not sure if this helps you achieve what you want as it now times out instead.

**Comment by dschoepe** [comment]
Thanks! It's still a useful fix since one doesn't need to check the model for correctness separately now.
