### ISSUE TITLE
SMT tactic inconsistencies

### ISSUE THREAD

**Issue by dwoos** [Z3Prover/z3#913]
My understanding is that `(check-sat-using smt)` should be equivalent to `(check-sat)`. This seems not to always be the case. I've found a couple of examples where they actually return different results (attached here: [z3-tactic-bug.zip](https://github.com/Z3Prover/z3/files/800453/z3-tactic-bug.zip)). For the first test case (`bug1.smt2` and `bug1-tactic.smt2`), `(check-sat)` returns `unknown`, while `(check-sat-using smt)` returns `unsat`. For bug 2 (`bug2.smt2` and `bug2-tactic.smt2`), the situation is reversed (though `(check-sat-using smt)` takes an extremely long time, around 8 minutes on my machine, to return `unknown`.

I ran Z3 with `-v:10` on bug 1, and observed some differences:

Using `(check-sat)`:
```
(smt.simplifier-done)
(smt.simplifier-done)
(smt.searching)
(smt.simplifying-clause-set :num-deleted-clauses 235)
(smt.restarting :propagations 9602 :decisions 421 :conflicts 101 :restart 150 :agility 0.080781)
(smt.simplifying-clause-set :num-deleted-clauses 17)
(smt.giveup quantifiers)
unknown
```

Using `(check-sat-using smt)`:
```
(smt.simplifier-done)
(smt.simplifier-done)
(smt.searching)
(smt.simplifying-clause-set :num-deleted-clauses 36)
(smt.restarting :propagations 7663 :decisions 537 :conflicts 101 :restart 150 :agility 0.0522954)
(smt.simplifying-clause-set :num-deleted-clauses 13)
unsat
```

It seems surprising that simplification is behaving so differently, and I wonder whether this is causing the difference in results.

I'm opening a separate issue about timing differences (`(check-sat-using smt)`) seems to be significantly slower in many cases).

**Comment by NikolajBjorner** [comment]
This could also be related to seed flickleness:

C:\z3\release>z3 bug1.smt2 /v:1
z3 bug1.smt2 /v:1
(smt.restarting :propagations 9602 :decisions 421 :conflicts 101 :restart 150 :agility 0.080781)
(smt.giveup quantifiers)
unknown

C:\z3\release>z3 bug1.smt2 /v:1 smt.random_seed=1
z3 bug1.smt2 /v:1 smt.random_seed=1
(smt.restarting :propagations 9744 :decisions 459 :conflicts 101 :restart 150 :agility 0.0750721)
unsat

C:\z3\release>z3 bug1.smt2 /v:1 smt.random_seed=2
z3 bug1.smt2 /v:1 smt.random_seed=2
(smt.restarting :propagations 11740 :decisions 364 :conflicts 101 :restart 150 :agility 0.091282)
unsat

C:\z3\release>z3 bug1.smt2 /v:1 smt.random_seed=4
z3 bug1.smt2 /v:1 smt.random_seed=4
(smt.restarting :propagations 11719 :decisions 467 :conflicts 101 :restart 150 :agility 0.071897)
(smt.restarting :propagations 62063 :decisions 1294 :conflicts 252 :restart 225 :agility 0.0722412)
unsat
