### ISSUE TITLE
cmake Z3Config not installed

### ISSUE THREAD

**Issue by jirislaby** [Z3Prover/z3#915]
@delcypher z3 cannot be found by find_package in cmake currently. This is at least used by https://github.com/hoangmle/metaSMT/blob/qf_abv/CMakeLists.txt#L96 at least. You have to do this hack in klee due to that for example:
https://github.com/klee/klee/blob/master/.travis/metaSMT.sh#L24

Could you prepare Z3Config.cmake based on something like this:
https://github.com/agra-uni-bremen/dependencies/blob/development/Z3-2.19/Z3Config.cmake
and let it install?

**Comment by delcypher** [comment]
@jirislaby This is something I intend to do when I have free time to work on Z3's CMake build system.

There is a `FIXME` about it in the existing code.

https://github.com/Z3Prover/z3/blob/7d37203653cffaab97d5cc75ca99cf0a6d662727/contrib/cmake/examples/c/CMakeLists.txt#L1
