### ISSUE TITLE
Windows Installation

### ISSUE THREAD

**Issue by CMCDragonkai** [Z3Prover/z3#916]
Just wanted to clarify some things since I successfully built and installed on Windows 10 and this wasn't mentioned in the README.

Even though the build instruction says use `python scripts/mk_make.py -x --python`, this can build a package that works in python3.

The building should take place inside the Visual C++ 2015 x64 Native Build Tools Prompt`.

The `z3.exe` appears to be independent and can work anywhere, you can copy the built version wherever. The `libz3.dll` needs to be discoverable on the PATH. So you can copy both `build/z3.exe` and `build/libz3.dll` into somewhere on the PATH.

Then the `build/python/z3` directory should be copied into the site-packages directory of Python. On Windows, this isn't done automatically, instead you have to find your Windows site-packages: like `python3 -c 'import site; print(site.getsitepackages())'`, then copy the entire directory there.

Then to test if it finally all works run:

```
from z3 import *
Int('x')
```

All of this is fairly simple to automate with pip, the native build can be distributed as a binary wheel, and the result is just a storage of the z3 library along with the libz3.dll somewhere in the site-packages for Python to lookup. At the same time, the z3.exe can be put into the `Scripts` directory.

**Comment by NikolajBjorner** [comment]
Thanks, sounds like we can update the README file somehow to help.
Some of these issues may be handled more gracefully with the cmake build. 
It is a much improved build environment thanks to @delcypher.

**Comment by NikolajBjorner** [comment]
I added notes to the readme.md file. Still the experience with cmake may be the way to go.

**Comment by CMCDragonkai** [comment]
Cool that's great, however I think I had a typo above, and also the addition to README.md is missing the code for testing z3 working inside python3.

**Comment by NikolajBjorner** [comment]
ups, I left your notes in the end of the file.
