### ISSUE TITLE
get-value for array equality: solver doesn't make up his mind

### ISSUE THREAD

**Issue by cliffordwolf** [Z3Prover/z3#917]
I have the following SMT2 input: [test.smt2.txt](https://github.com/Z3Prover/z3/files/802418/test.smt2.txt)

This is what z3 produces:

```
unsat
sat
(((= (|memory1_m mem| (|memcmp_h mem1| s1)) (|memory2_m mem| (|memcmp_h mem2| s1))) (= (_ as-array k!1) (_ as-array k!3)))
 ((= (|memcmp_n rdata1| s1) (|memcmp_n rdata2| s1)) false))
```

I think instead of `(= (_ as-array k!1) (_ as-array k!3))` it should print `true` or `false`.

**Comment by NikolajBjorner** [comment]
Try this

**Comment by cliffordwolf** [comment]
I can confirm this fixes the problem. Thank you!
