### ISSUE TITLE
unabled nested data-type expression / unable to handle nested data-type expression

### ISSUE THREAD

**Issue by domoritz** [Z3Prover/z3#918]
This program (part of a [larger program](https://github.com/domoritz/vis-constraints) so the names don't make sense)

```smt
(declare-datatypes () ((AggFunc 
  Foo
)))

(declare-datatypes () ((Encoding
  (mk-enc (field String) (agg AggFunc))
)))

(declare-const e0 Encoding)(assert (= (field e0) "str1"))

(assert-soft (= (agg e0) Foo) :weight 1)

(check-sat)
(get-model)
```

Throws the following error

```
(objectives
 ( 0)
)
(error "line 13 column 10: unabled nested data-type expression (agg e0)")
(error "line 14 column 10: model is not available")
```

Note that I don't get this error when I convert the `assert-soft` to an `assert`.

```
sat
(model
  (define-fun e0 () Encoding
    (mk-enc "str1" Foo))
)
```

@NikolajBjorner already fixed the typo in https://github.com/Z3Prover/z3/commit/996c0f0666f18ad4719135aa3e964fb6c9103c35

**Comment by NikolajBjorner** [comment]
Thanks, it is fixed now.

**Comment by domoritz** [comment]
Awesome! Will there be a release soon or is there a way for me to change my program so that the problem does not occur? If not, I will build my own z3.

**Comment by NikolajBjorner** [comment]
Binaries should be available soon from the nightly builds.
