### ISSUE TITLE
Using Uninterpreted functions in LIA results in non-termination.

### ISSUE THREAD

**Issue by bj2015** [Z3Prover/z3#919]
(set-option :print-success true)
(set-option :produce-models true)

(set-logic LIA)

(declare-fun f (Int ) Int)
(assert (forall ((x Int) ) (=> (or (< x 1) (> x 0)) (= (f x) 0))))

(assert (forall ((x Int) ) (=> (and (and (> x 0) (< x 3))) (> 1 2))))

(check-sat)

**Comment by bj2015** [comment]
Above Problem uses Uninterpreted Functions. When setting the correct logic UFLIA or not setting the logic at all (thus using Z3's AUTO_CONFIG feature), Z3 (version 4.5.0 - 64 bit) correctly solves it in a matter of milliseconds.

When, like in above example, setting a logic that does not support Uninterpreted Functions (like LIA), I would have expected an error similar to "logic does not support reals". However, passing above axample to Z3 results in non-termination.

**Comment by NikolajBjorner** [comment]
try now

**Comment by bj2015** [comment]
The current master returns "unsat" - as it should. Hence, the issue is resolved. Thanks!
