### ISSUE TITLE
optimization results reverse

### ISSUE THREAD

**Issue by mm95** [Z3Prover/z3#928]
Hello,
I use z3::optimization to get min and max value for one declaration, distinctly. I mean, 
```
z3::optimize minopt (ctx);
z3::optimize maxopt(ctx);

minpt.add(formula) ;
minopt.minimize(x);

maxopt.add(formula);
maxopt.maximize(x);

check_result rc = minopt.check();
if(minopt == sat)
   print minopt.get_model().eval(x);
rc = maxopt.check();
if(maxopt == sat)
  print maxopt.get_model().eval(x);

```
My problem is that minopt.get_model() returns a bigger value then maxopt.get_model() for variable x. 
I used Z3 c++ API and updated Z3 source code with last commit. The log file is attached. 
[z3.log.txt](https://github.com/Z3Prover/z3/files/819234/z3.log.txt)

 Thanks.

**Comment by cheshire** [comment]
It does seem like a bug in model generation, but normally I would advise to use `upper`/`lower` functions to get the value of the objective. Moreover, with "box" objective ordering mode, you can do this in a single context: set two objectives, get two handles, get values for each.

**Comment by NikolajBjorner** [comment]
The bug was a missing case for when the objective is a bit-vector. Should be fixed now.

**Comment by mm95** [comment]
Thanks so much from cheshire and NikolajBjorner for their attention.
Now, I have a question.
Suppose that I want maximize a bitvector value. 
The "upper/lower" functions returns "int". Does it mean that z3::optimization can just determine the min and max value of bitvectors with length of an int. 
In fact, I want to know that which scalability z3::optimization can support? 

Thanks.

**Comment by NikolajBjorner** [comment]
When given a bit-vector to optimize, Z3 uses a reduction to Maxsat. It treats each bit as a weighted soft constraint. This reduction allows me to use the maxsat engine.
There is a smarter way to optimize bit-vectors, though (see papers by Martin Soule resp. Alex Nadel).
If enough use cases come along I will add this or go through how I handle lexicographic orderings, which lets me solve for the bits one by one starting from the high-order bits.

**Comment by NikolajBjorner** [comment]
Can we close this as an issue?

**Comment by mm95** [comment]
Of course. Thanks so much.
