### ISSUE TITLE
Python  "qfbv-sls" API error

### ISSUE THREAD

**Issue by rainoftime** [Z3Prover/z3#929]
I built z3 4.5.0 a few days ago. 
While runing the following code, 
~~~~
def test():
    s = Tactic("qfbv-sls").solver()
    s.set("timeout", 1000)
    f = parse_smt2_file("file.smt2")
    s.add(f)
    print s.check()

test()
~~~~

it fails with the message:
~~~~
      ...
  File "/usr/lib/python2.7/dist-packages/z3/z3core.py", line 4116, in Z3_solver_assert
    raise Z3Exception(lib().Z3_get_error_msg(a0, err))
z3.z3types.Z3Exception: unknown parameter 'timeout'
Legal parameters are:
  algebraic_number_evaluator (bool) (default: true)
  arith_lhs (bool) (default: false)
  bit2bool (bool) (default: true)
        ...
~~~~

But when I replace `s = Tactic("qfbv-sls").solver()` with `s = Tactic("qfbv").solver()`, 
the above piece of code works well.  

Is z3's Python API "out-of date"?(as the sls based QF_BV engine is available only since Version 4.4.0)

I can use `Tactic(qfbv-sls)`  only without setting timeout. 
~~~~
def test():
    s = Tactic("qfbv-sls").solver()
    # without timeout,  it works
    # s.set("timeout", 1000),
    f = parse_smt2_file("file.smt2")
    s.add(f)
    print s.check()

test()
~~~~

**Comment by wintersteiger** [comment]
That's correct, the qfbv-sls tactic does not have it's own timeout parameter (like many tactics). Instead, we can use the global one:

```
set_param("timeout", 1000) 
s = Tactic("qfbv-sls").solver()
...
s.add(f)
print(s.check())
```

**Comment by rainoftime** [comment]
@wintersteiger  If it is necessary for my application to add timeout parameter for qfbv-sls or other tactics, any advices for doing that? Thank you!

**Comment by wintersteiger** [comment]
You can update the global parameter setting for the timeout between tactic calls or you could use the `try-for` tactic combinator (from Python, use `TryFor(tactic, milliseconds)`), which allows you to set a timeout on any tactic.
