### ISSUE TITLE
Bad model produced with datatype accessors

### ISSUE THREAD

**Issue by Muon** [Z3Prover/z3#931]
Running

```
(declare-datatypes () ((Val undefined null (Num (num Real)))))
(declare-const foo Val)
(assert (= 1.0 (num foo)))
(check-sat)
(get-model)
```

produces

```
sat
(model
  (define-fun foo () Val
    null)
)
```

using the current Windows release of Z3. This should be false, since `(num null)` can't be unified with `1.0`. Still, running the following produces `sat`:

```
(declare-datatypes () ((Val undefined null (Num (num Real)))))
(assert (= 1.0 (num null)))
(check-sat)
```

**Comment by NikolajBjorner** [comment]
It is confusing for sure, but this is the semantics: the accessor functions, as are all functions, are total functions. They are defined on all possible elements of Val. So what is the value of (num null)? It is under-specified. This means that one possible interpretation of (num null) is 1.0. Another possible interpretation is 2.0. Of course it can only have one of such interpretations in any given model.
