### ISSUE TITLE
Z3 SMTLIB parser does not recognise `fp.to_ieee_bv`.

### ISSUE THREAD

**Issue by delcypher** [Z3Prover/z3#932]
The attached query
[x.smt2.txt](https://github.com/Z3Prover/z3/files/825193/x.smt2.txt) is produced by calling `Z3_solver_to_string()` inside a tool I am working on. In many cases the output (when a `(check-sat)` call is appended) produces a query that Z3 can parse.

However Z3 fails to parse this particular query. It outputs

```
(error "line 37 column 74: unknown function/constant fp.to_ieee_bv")
(error "line 72 column 74: unknown function/constant fp.to_ieee_bv")
sat
```

It seems that Z3's parser expects `to_ieee_bv` rather than `fp.to_ieee_bv`. This inconsistency seems unnecessary and should be fixed.

For reference I did this using Z3 @ 4c664f1c05786a479e016ffac0d0c6a2e00ab64d

**Comment by wintersteiger** [comment]
That's a rather old commit (Dec 2016). `to_ieee_bv` was the old name, pre-dating the `fp.*` definitions of the SMT FP standard. The [decl-plugin](https://github.com/Z3Prover/z3/blob/master/src/ast/fpa_decl_plugin.cpp#L918) knows both of them and my Z3 is happy with x.smt2.txt; it says "sat" after 11 seconds.

**Comment by delcypher** [comment]
@wintersteiger Apologies. I had the wrong commit (face palm). I was actually running deed85b26014b69efbc275e07671547aa108cd41 but I was meant to be running 4c664f1c05786a479e016ffac0d0c6a2e00ab64d. In the newer commit and on the current master Z3 works fine.

Sorry for the noise.

**Comment by wintersteiger** [comment]
No worries, thanks for reporting back!
