### ISSUE TITLE
kind() of uninterpreted constant does not match Z3_OP_UNINTERPRETED

### ISSUE THREAD

**Issue by sedrews** [Z3Prover/z3#933]
This is the same issue as #786, but as far as I can tell I do not have an error in my installation.  Specifically, on 4.5.1 I get
```
>>> from z3 import *
>>> z3.get_version_string()
'4.5.1'
>>> Real('x').decl().kind()
2354L
>>> Z3_OP_UNINTERPRETED
2351
```
Whereas on 4.4.1 I would get
```
>>> from z3 import *
>>> z3.get_version_string()
'4.4.1'
>>> Real('x').decl().kind()
2349L
>>> Z3_OP_UNINTERPRETED
2349
```

**Comment by NikolajBjorner** [comment]
Your applications should use the symbolic names. The compiler generated numerals are not guaranteed to remain between calls.

**Comment by sedrews** [comment]
I want to use the symbolic names so that `x.decl().kind() == Z3_OP_UNINTERPRETED` distinguishes between variables and numeric constants in a formula.  Specifically, right now https://github.com/Z3Prover/z3/blob/master/examples/python/visitor.py does not function correctly because these things are not equal.

**Comment by NikolajBjorner** [comment]
This sounds like a bug. Is there a simple repro?

**Comment by sedrews** [comment]
This is a small, reproducible example:

```
from z3 import *

print z3.get_version_string()

def vc(c):
    assert(is_const(c))
    if c.decl().kind() == Z3_OP_UNINTERPRETED:
        print c, "is a variable"
    else:
        print c, "is a constant"

two = RealVal(2)
ex = Real('x')

vc(two)
vc(ex)
```
Whose output differs depending on the version:
```
4.5.1
2 is a constant
x is a constant
```
versus
```
4.4.1
2 is a constant
x is a variable
```

**Comment by NikolajBjorner** [comment]
I don't get this with 4.5.1.
Is there a chance that your python installation is using the old version of z3consts.py but the nee libz3.dll?

**Comment by wintersteiger** [comment]
Most likely a configuration problem. Note that between versions 4.4.1 and 4.5.1, the default installation directory for Z3 changed (it was moved into another directory called "z3" for package management reasons). I can very well imagine that we get some sort of mixed state if you simply run "make install" for each of them without the right "make uninstall"s between them.

**Comment by sedrews** [comment]
It was, in fact, a configuration error as you described. Thanks for your time.
