### ISSUE TITLE
on nondeterminism and model counting

### ISSUE THREAD

**Issue by kooshanabedian** [Z3Prover/z3#934]
I use this code to count all models of a formula:
```
        while(rc == sat){
			model m = zsol->get_model();
			expr b = sctx->ctx.bool_val(0);
                        mpz_int n(1);
                        for(unsigned i = 0; i < vctx->exprs.size(); ++i) {
                             expr var = vctx->exprs[i];
	                     expr r = m.eval(var);
	                     if(eq(var,r)){
	                           n *= 2;
	                     }
	                     else{
		                    b = b || !(var == r);
	                     }
                        }
                        zsol->add(b);
                        number += n;
                        rc = zsol->check();
          }
```
Which checks for each `var` not being evaluated. Such variables are left nondeterministic which boost counting by a two factor multiplication. If `var` has been evaluated it simply constructs a blocking clause, adds it to solver context and counts one.

Now, consider this simple program, which copies an input variable _i_ into an output variable _v_:
```
int copy(int i){
	int v = i; 
	assert(0);
	return v;	
}
```
Which translates into

```
(declare-fun |_start::i!0#1| () (_ BitVec 32))
(define-fun |copy::i!0@1#1| () (_ BitVec 32) |_start::i!0#1|)
(define-fun |copy::1::v!0@1#2| () (_ BitVec 32) |copy::i!0@1#1|)
(define-fun |B0| () Bool (= |_start::i!0#1| |_start::i!0#1|))
(declare-fun |copy::1::v!0@1#1| () (_ BitVec 32))
(define-fun |B1| () Bool (= |copy::1::v!0@1#1| |copy::1::v!0@1#1|))
(assert (not false))
(declare-fun |symex::io::0| () (_ BitVec 32))
(assert (= |_start::i!0#1| |symex::io::0|))

(check-sat)

```

Clearly `|_start::i!0#1|` is declared as a nondeterministic variable. The actual assignment instruction is embodied in line 3 of smt description. I assume that `|copy::1::v!0@1#2|` is now **semantically** a nondeterministic variable. However, since

```
(define-fun |copy::1::v!0@1#2| () (_ BitVec 32) |copy::i!0@1#1|)
```
is rewritten as

```
(declare-fun |copy::1::v!0@1#2| () (_ BitVec 32))
(assert (= |copy::1::v!0@1#2| |copy::i!0@1#1|))
```
regardless of our intuition, Z3 chooses to eagerly populate all 2^32 bitwise models of `|copy::1::v!0@1#2|` variable. Which means that no nondeterministic expression would appear during model counting procedure to satisfy `eq(var,r)` condition and all models have to be enumerated just one by one. Is there a way to surpass such eager model generation mod equations or propagate the _property_ of being "nondetermninistic" over equivalencies?

**Comment by NikolajBjorner** [comment]
Efficiently counting models for propositional formulas is not quite 
trivial. An incremental improvement over your algorithm is to
run dual propagation: take each equality from the model, 
assrt (=> tracking-predicate-i (= var-i value-of-var-i-in-model)),
and assert the negation of the formula you are checking.
In this case you end up with an unsatisfiable formula 
modulo the tracking-predicates. An (minimal) unsatisfiable core is a
reduced set of equalities that are required to evaluate the formula to true.
variables that don't participate in the core are don't cares and you can
multiply the counter by 2^DomainSize for these variables.

Unfortunately, this alone will do little for you. 
If this was a SAT solver, it would be able to leverage
equivalence finding procedures inside of the solver to factor out
equivalent literals. For bit-vectors and other domains, you 
do have the option to convert this to a pure propositional formula
and then count models for this. 

An ad hoc approach, but not so easy, is to leverate a feature
in Z3 that allows to learn implied equalities. It is not mainstream
so currently only exposed over the C API.


    Z3_lbool Z3_API Z3_get_implied_equalities(Z3_context c,
                                              Z3_solver  s,
                                              unsigned num_terms,
                                              Z3_ast const terms[],
                                              unsigned class_ids[]);

You can use this to find equal variables, and therefore only count
models for one variable in each class.

I am going to close this as an "issue". It isn't a bug and the ways to address it are open ended.
