### ISSUE TITLE
Z3 hangs on query, small changes fix it

### ISSUE THREAD

**Issue by agacek** [Z3Prover/z3#944]
Z3 hangs on the second check-sat query in this file:

  https://gist.github.com/agacek/a1889aab466101b3f1b9652146688a06

Small changes to the file fix the issue. If I remove push/pop pairs or renumber variables the query goes through instantly.

**Comment by delcypher** [comment]
@agacek IIRC using `push` and `pop` causes Z3 to use a different (incremental) SAT solver internally which has different performance characteristics to the non-incremental SAT solver used internally.

**Comment by agacek** [comment]
@delcypher There are multiple push/pop pairs in the file, so if I remove just one it should still be using the incremental solver. Also, I can get it to work just by removing the first check-sat call. So I think everything is in the same solver.

**Comment by NikolajBjorner** [comment]
The same solver exhibits different runtime on this. The benchmark uses mixed integer linear programming so the arithmetic solver ends up doing branch and bound. Depending on the value of smt.random_seed, the benchmark is either instantaneous or forever. I have not been able to dig into exactly where the discrepancy is rooted and what can potentially fix it (and a real fix is not going to be soon, but eventual)

**Comment by delcypher** [comment]
@agacek You're right. Sorry I missed that. Please ignore my previous comment.

**Comment by NikolajBjorner** [comment]
It is pretty instant now
