### ISSUE TITLE
Difficult QF_FPABV query

### ISSUE THREAD

**Issue by delcypher** [Z3Prover/z3#945]
This isn't really an issue with Z3 but I thought @wintersteiger and others might find this interesting.

I've been collecting solver queries from a tool I'm working so I can turn them into benchmarks for SMT-COMP and I thought I'd share this one. Both Z3 and mathsat 5 really struggle with this query. I gave mathsat 5 an hour and it didn't give an answer. I ran Z3 for ~~15 minutes (I'm re-running now for a larger amount of time)~~ 3 hours and it didn't find an answer.

I don't know if this query is `sat` or `unsat`. Is there anything obvious here that I'm missing that suggests why this query is so difficult to solve?

```smtlib
(declare-fun a_ackermann_0 () (_ BitVec 64))
(assert (not (fp.isNaN ((_ to_fp 11 53) a_ackermann_0))))
(assert (not (fp.eq (fp.mul roundNearestTiesToEven
                    ((_ to_fp 11 53) a_ackermann_0)
                    (fp #b0 #b01111111111 #x0000000000000))
            (_ +zero 11 53))))
(assert (let ((a!1 (fp.add roundNearestTiesToEven
                   (_ +zero 11 53)
                   (fp.mul roundNearestTiesToEven
                           (fp.mul roundNearestTiesToEven
                                   ((_ to_fp 11 53) a_ackermann_0)
                                   (fp #b0 #b01111111111 #x0000000000000))
                           (fp #b0 #b10000001000 #xf980000000000))))
      (a!2 (fp.add roundNearestTiesToEven
                   (fp.add roundNearestTiesToEven
                           (fp.mul roundNearestTiesToEven
                                   ((_ to_fp 11 53) a_ackermann_0)
                                   (fp #b0 #b10000001000 #xf980000000000))
                           (fp #b0 #b10000000101 #xea147ae147ae1))
                   (fp #b0 #b10000000110 #x0c0f5c28f5c29))))
  (not (fp.eq (fp.add roundNearestTiesToEven
                      (fp.add roundNearestTiesToEven
                              a!1
                              (fp #b0 #b10000000101 #xea147ae147ae1))
                      (fp #b0 #b10000000110 #x0c0f5c28f5c29))
              a!2))))
(check-sat)
```

**Comment by wintersteiger** [comment]
Z3 translates this to SAT and the multiple (and wide) multipliers in this problem are likely hard for any SAT solver. MathSAT also has an ACDCL engine that might perhaps be able to solve this query quicker, but I wouldn't bet on it.

**Comment by delcypher** [comment]
@wintersteiger Thanks for the information.
