### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by gdcurt** [Z3Prover/z3#946]
I've been getting a segmentation fault when running this file (and other instances of similar size -- it works fine with some smaller problems):

https://gist.github.com/gdcurt/50eaa6bece58b50bf7f92ffa9ba107a0

I have version 4.5.1 and I'm calling z3 from python. I run it out of curiosity with version 4.4.1 and didn't get a segmentation fault.

**Comment by NikolajBjorner** [comment]
It exposes a non-termination or performance bug.
Until I figure out the right fix, to use the more useful solver for now do: z3 seg.smt2 /v:1 smt.auto_config=false smt.arith.solver=2

**Comment by NikolajBjorner** [comment]
I have added a more systematic fix so the solver goes through directly with the difference logic solver and without changing configuration options.

**Comment by NikolajBjorner** [comment]
I believe we can close this issue now
