### ISSUE TITLE
Combining selecting and storing for arrays with pdr engine

### ISSUE THREAD

**Issue by ClaraS** [Z3Prover/z3#947]
Hi, 
I have been observing strange behaviour in z3 when combining select and store commands for arrays using the pdr fixed point engine. 

The following example is satisfiable although this should not be the case: 

```
(set-option :fixedpoint.engine pdr)

(declare-rel P ((Array Int Int)))
(declare-rel Q ((Array Int Int)))
(declare-rel R ())

(declare-var a (Array Int Int))
(declare-var x Int)

(rule (=> (= (select a 0) 1) (Q a)))
(rule (=> (and (Q a) (=  x (select a 0)) ) (P (store a 0 (+ x 1)))))
(rule( => (and (P a) (= (select a 0) 42)) R))

(query R 
       :print-certificate true
)
```

Arrays satisfying the predicate Q should have value '1' at position 0 (by rule 1)
By rule 2, arrays satisfying P should have value '2' at position 0. 
Still it holds that an array satisfying P can have value '42' at position 0. 

It seems that when using the select in the premise to store the value in a variable, all constraints on this variable are dropped when it is used as part of a store expression in the conclusion.  

In contrast, a direct nesting as in the following example seems to work: 

```
(set-option :fixedpoint.engine pdr)


(declare-rel P ((Array Int Int)))
(declare-rel Q ((Array Int Int)))
(declare-rel R ())

(declare-var a (Array Int Int))
(declare-var x Int)

(rule (=> (= (select a 0) 1) (Q a)))
(rule (=> (Q a) (P (store a 0 (+ (select a 0) 1)))))
(rule( => (and (P a) (= (select a 0) 42)) R))

(query R 
       :print-certificate true
)
```

**Comment by NikolajBjorner** [comment]
seems one of the transformations was unsound

**Comment by ClaraS** [comment]
Cool, thank you a lot! Now it is working!
