### ISSUE TITLE
Inconsistency when mixing integers and bitvectors

### ISSUE THREAD

**Issue by Muon** [Z3Prover/z3#948]
When mixing integers and bitvectors, an inconsistency can occur. See

```smt2
(define-fun UInt32ToInt ((x Int)) Int (ite (>= x 2147483648) (- x 4294967296) x))
(define-fun ToInt32 ((x Int)) (_ BitVec 32) ((_ int2bv 32) x))

(define-fun f ((a Int)) Int (UInt32ToInt (bv2int (bvor (ToInt32 (- 50)) (ToInt32 a)))))

(simplify (f 3))

(declare-const x Int)
(assert (= (- 49) (f x)))
(check-sat)
```
produces
```smt2
(- 49)
unsat
```

which is clearly contradictory. This can be run here: http://rise4fun.com/Z3/V4eI If you rearrange it so `f` just returns a bitvector rather than an integer (and we search for the bitvector equivalent to -49), we get `sat`, however. This suggests the problem is with `bv2int`.

**Comment by NikolajBjorner** [comment]
Here is a smaller example:

        (define-fun ToInt ((x Int)) (_ BitVec 4) ((_ int2bv 4) x))
        (define-fun h ((a Int)) (_ BitVec 4) (bvor (ToInt (- 5)) (ToInt a)))
        (define-fun g ((a Int)) Int (bv2int (h a)))
        (declare-const x Int)
        (simplify (h 3))
        (simplify (g 3))
        (assert (= 11 (g x)))
        (check-sat)
        (reset)

**Comment by NikolajBjorner** [comment]
should be addressed now
