### ISSUE TITLE
Inconsistency in string theory

### ISSUE THREAD

**Issue by jcreedcmu** [Z3Prover/z3#949]
Feeding z3 (compiled from commit 71ca355 from late November, I'm about to try a newer version to see if it goes away) the input
```
(declare-const x String)

(assert (not (str.prefixof "prefix:" x)))

(assert (or
         (str.prefixof "prefix:a" x)
         (str.prefixof "prefix:b" x)
         (str.prefixof "prefix:c" x)))
(check-sat)
(get-model)
```
yields 
```
sat
(model 
  (define-fun x () String
    "prefix:b")
)
```
which clearly doesn't satisfy the first assertion  `(assert (not (str.prefixof "prefix:" x)))`.

This goes away (i.e. z3 says "unsat" as expected) if I shorten "prefix:" to just "x" or have fewer than three alternatives in the disjunction
```
 (or
         (str.prefixof "prefix:a" x)
         (str.prefixof "prefix:b" x)
         (str.prefixof "prefix:c" x))
```
if that helps debugging.

**Comment by NikolajBjorner** [comment]
Thanks, this was due to an unsound rewrite for prefix.

**Comment by jcreedcmu** [comment]
This resolved the issue we were having, thanks.
