### ISSUE TITLE
Quantifier instantiation not happening

### ISSUE THREAD

**Issue by wintersteiger** [Z3Prover/z3#95]
Mate Schwerhoff previously reported a bug on codeplex (see [here](http://z3.codeplex.com/workitem/190)), migrating this to the new issue tracker. In his own words:

Given the program below, Z3 4.3.2 and 4.4.0 55ca6ce44b2f (both Win x64) immediately report unknown, despite the fact that the given terms and patterns should allow it to instantiate each forall once, thereby showing that the goal is unsat.
(set-option :auto_config false) ; IMPORTANT
(set-option :smt.mbqi false)    ; IMPORTANT
(set-option :smt.qi.profile true)

(declare-fun fun (Int) Int)
(declare-fun funLim (Int) Int)

(declare-const x Int)

(assert (forall ((x Int)) (!
  (= (fun x) (+ 1 (funLim x)))
  :pattern ((fun x)))))

(assert (forall ((x Int)) (!
  (= (fun x) (funLim x))
  :pattern ((fun x)))))
  
(assert (not ; goal
  (= (fun x) (+ 1 (fun x))))) ; Change second fun to funLim and Z3 reports unsat
  
(check-sat) ; unknown
(get-info :all-statistics) ; no forall instantiated (if funLim is used, both are instantiated once)
Am I missing something here that would explain why Z3 doesn't perform the instantiation, or is this a bug in the triggering code?

**Comment by NikolajBjorner** [comment]
To assertion (not (= (fun x) (+ 1 (fun x))) simplifies to "true", so there are no ground terms to pattern match against. To enforce such grounding, users who disable MBQI can manually create seeding instances of universally quantified formulas. 
So it is not really a bug in the triggering code, but an artifact of its operational behavior.
