### ISSUE TITLE
when. I. use. make.   it was error！

### ISSUE THREAD

**Issue by letitbezh** [Z3Prover/z3#950]
when. I. use. make.   it was error!!!   what can I do?

```shell
angr@ubuntu:~/Desktop/z3/build$ make
src/util/hwf.cpp
In file included from ../src/util/hwf.cpp:55:0:
/usr/lib/gcc/x86_64-linux-gnu/4.8/include/smmintrin.h:31:3: error: #error "SSE4.1 instruction set not enabled"
 # error "SSE4.1 instruction set not enabled"
   ^
make: *** [util/hwf.o] Error 1
```

**Comment by Aftern00nTea** [comment]
Me too!!! When I use "make" it was also error, the same error:#error "SSE4.1 instruction set not enabled".
How to solve it？

**Comment by letitbezh** [comment]
I solve it。
only use ./configure ,then cd build ,make and sudo make install  ,you will install..
but you should. first  sudo make uninstall z3.  before
