### ISSUE TITLE
Segmentation fault with TRACE=true

### ISSUE THREAD

**Issue by nikswamy** [Z3Prover/z3#952]
```
$ uname -a
CYGWIN_NT-10.0 nikhil-Z820 2.6.1(0.305/5/3) 2016-12-16 11:55 x86_64 Cygwin

$ z3 --version
Z3 version 4.5.0 - 64 bit

$ z3 -smt2 small-context-no-hints.smt2.txt TRACE=true
Segmentation fault
```

It does not appear to be an out-of-memory issue ... it crashes when using only about 45MB on my machine.

[small-context-no-hints.smt2.txt](https://github.com/Z3Prover/z3/files/865517/small-context-no-hints.smt2.txt)

**Comment by NikolajBjorner** [comment]
try now

**Comment by NikolajBjorner** [comment]
can we close this?

**Comment by wintersteiger** [comment]
Yes, thanks!
