### ISSUE TITLE
seq.at without length constraints sometimes produces incorrect models

### ISSUE THREAD

**Issue by dschoepe** [Z3Prover/z3#953]
Using seq.at in equality assertions seems to sometimes result in incorrect models, for example when there is no assertion about the length of the target sequence:

```
(declare-fun xs () (Seq Int))
(assert (= (seq.at xs 0) (seq.unit 42)))
;; Adding the following assertion results in a correct model:
;; (assert (> (seq.len xs) 0))
(check-sat)
(get-model)
```

The above program results in the following model:
```
(model 
  (define-fun xs () (Seq Int)
    (as seq.empty (Seq Int)))
)
```

However, `seq.empty` will not satisfy the above assertion. Interestingly, adding a length constraint like `(assert (= (seq.len xs) 0))` still yields `sat` as the result, with the same model. Is this a bug or did I miss some assumption about the use of sequence operations?

**Comment by NikolajBjorner** [comment]
This one should be fixed now

**Comment by dschoepe** [comment]
Indeed, seems to work as expected now. Thanks for the quick fix!
