### ISSUE TITLE
How to query models for boxed objectives?

### ISSUE THREAD

**Issue by LeventErkok** [Z3Prover/z3#955]
Is there a way to query z3 so I can get the satisfying models for a specific objective in case I have boxed (or pareto) objectives?

This is what I'm trying:

```
(declare-fun a () Int)

(assert (>  a  2))
(assert (<= a 10))

(minimize (+ (* 4 a) 2))
(maximize (+ 5 (* 2 a)))

(set-option :opt.priority box)

(check-sat)
(get-value (a))
```

This returns:

```
sat
(objectives
 ((+ (* 4 a) 2) 14)
 ((+ 5 (* 2 a)) 25)
)
((a 3))
```

I interpret this as the first goal `4a+2` optimized to a minimal value of `14` under the assignment `a=3`; which is nicely returned by the `(get-value (a))` call.

Similarly, `2a+5` has been maximized at value `25`, when `a=10`.

But, how do I query z3 for the `a=10` value, i.e., the assignment for the second objective?

In general, if I have `box` objectives, which goal does a `get-value` call refer to? It seems the answer is the very first goal from my experiments: Is that always true? How do I access the values for other goals? (Or better yet, is there a way to specify which objective `get-value` should refer to?)

I also have a very similar question for `pareto` optimization: How do I obtain values of model values for different objective values in that case? (But that seems to be a slightly different request I guess; so I can file a different ticket for that if necessary.)

**Comment by NikolajBjorner** [comment]
For box objectives it will be as follows:

    (declare-fun a () Int)
    (assert (>  a  2))
    (assert (<= a 10))
    (minimize (+ (* 4 a) 2))
    (maximize (+ 5 (* 2 a)))
    (set-option :opt.priority box)
    (check-sat) 
    (get-model 0)
    (get-model 1)
    (help eval)
    (eval a :model-index 1)
    (eval a :model-index 0)

So far, for Pareto, we retrieve a stream of models. So one simply re-issues the check-sat query to get the next model. The potential number of Pareto fronts and time between retrieving them makes saving models somewhat dubious.

**Comment by LeventErkok** [comment]
Fantastic! Thank you.

**Comment by LeventErkok** [comment]
Hi Nikolaj.. I'm finally getting around to using this feature, and it appears the following is **not** supported:

     (get-value (s0) :model-index 0)

I prefer this variant over the `eval` call, since the downstream parser has an easier time interpreting the output as it contains the variable name in the output.

I found that I can sort of _fake_ it by sending the following down:

      (echo "((s0")
      (eval s0 :model-index 0)
      (echo ")")

But that's not quite the same and feels quite like the kludge that I'd rather avoid.

Would it be possible to change `get-value` to support indexes as well?

**Comment by NikolajBjorner** [comment]
try now.

(declare-const x Int)
(declare-const y Int)
(assert (<= (+ x y) 10))
(assert (>= x 0))
(assert (>= y 0))
(maximize x)
(maximize y)
(set-option :opt.priority box)
(check-sat)
(get-value (x y) :model_index 0)
(get-value (x y) :model_index 1)

**Comment by LeventErkok** [comment]
Fantastic! One minor thing, for `eval` you spelled it `model-index`, for `get-value` it is `model_index`. Probably best to use the same option? (Note the hypen vs underscore.) I don't have a preference as to which one.

**Comment by NikolajBjorner** [comment]
Seems closable.

**Comment by LeventErkok** [comment]
Yes! The only issue I have is that in a Pareto-model extraction, is there any way to know ahead of time how many pareto-fronts will be? I understand this number might be _infinite_, but wondering if there's any indication we can get from Z3 what the count will be (or that it will be infinite), before we start reading the models.

I understand this may not be possible, so not a hard requirement. Just curious if there's a trick I can do.
