### ISSUE TITLE
int2bv with bvand causes hang

### ISSUE THREAD

**Issue by Muon** [Z3Prover/z3#958]
The following snippet causes Z3 to hang and eat a bunch of memory:

```smt2
(declare-const x Int)
(define-fun ToInt32 ((x Int)) (_ BitVec 32) ((_ int2bv 32) x))
(assert (= (ToInt32 2) (bvand (ToInt32 x) (ToInt32 50))))
(check-sat)
```

**Comment by wintersteiger** [comment]
Just in case: `int2bv` is not always fully interpreted, see also [Z3 questions about int2bv](http://stackoverflow.com/questions/27914582/z3-questions-about-z3-int2bv).

On this particular input, Z3 is very unlucky and it keeps enumerating lots of potential models without finding a good one. If we change the heuristics in some way, it gets lucky again. For instance, with `smt.random_seed=2` it solves it quickly and with `smt.relevancy=0` it solves it even quicker. Another way to approach this is to set `smt.bv.enable_int2bv=false`, which has the effect that int2bv fully uninterpreted and it will report x=0 as a model.
