### ISSUE TITLE
Wrong optimization result

### ISSUE THREAD

**Issue by cheshire** [Z3Prover/z3#959]
For integral `x`,
optimizing for `x` in `x <= 1 + 4 * ((x + 2) / 4)`
produces a model `x = 1`. Yet adding a constraint `x  > 1` gives a new model `x = 4`,
so clearly the initial model is not at an optimum.

**Comment by NikolajBjorner** [comment]
I get the result that x is unbounded from above, so it settles on some arbitrary model.

**Comment by cheshire** [comment]
ah, apologies, I have looked at the wrong output. Thanks!
