### ISSUE TITLE
Is there a way to access PbEq/PbLe/PgGe via smt-lib?

### ISSUE THREAD

**Issue by LeventErkok** [Z3Prover/z3#960]
As discussed here: http://stackoverflow.com/questions/43081929/k-out-of-n-constraint-in-z3py

Curious if there's a way to access this functionality via the SMT-Lib interface. (Perhaps via some tactic and named asserts of some form?)

**Comment by NikolajBjorner** [comment]
The SMT-LIB syntax is 

           ((_ at-most k) x y z u v), 
           ((_ at-least k) x y z u v), 
           ((_ pbge c1 c2 c3 c4 c5 k) x y z u v), 
           ((_ pble c1 c2 c3 c4 c5 k) x y z u v), 
           ((_ pbeq c1 c2 c3 c4 c5 k) x y z u v), 

If you only use bit-vectors and PB constraints, then set the logic to QF_FD (quantifier-free finite domains). It then uses the SAT solver.  

For example, you can write:

        (declare-const p_0_0 Bool)
        (declare-const p_0_1 Bool)
        (assert ((_ at-most 1)  p_0_0 p_0_1))
        (assert (or  p_0_0 p_0_1))
        (check-sat)
        (get-model)

**Comment by LeventErkok** [comment]
Fantastic! This'll definitely help with mutex constraints.

**Comment by LeventErkok** [comment]
Hi Nikolaj.. I'm experimenting with these constructs, but having trouble understanding the semantics.

I tried:

```
(declare-const a Bool)
(declare-const b Bool)
(assert ((_ pbge 1 2 3) a b))
(check-sat)
(get-model)
```

I take this to mean `a + 2b >= 3`. But z3 responds:

```
sat
(model
  (define-fun b () Bool
    false)
  (define-fun a () Bool
    true)
)
```

which I take it to mean `1 >= 3`, i.e., false.

Am I misinterpreting the meaning of these functions?

**Comment by NikolajBjorner** [comment]
It's roundabout: it means 2a + 3b >= 1
Same for (_ pble 1 2 3) a b means 2a + 3b <= 1

**Comment by LeventErkok** [comment]
Ah, the way you put the `k` in your very first comment threw me off, where you said:

            ((_ pble c1 c2 c3 c4 c5 k) x y z u v)

I hope that wasn't a cut-paste from somewhere else!

Thanks..
