### ISSUE TITLE
Strange regression between 4.5.0 and current master (4.5.1)

### ISSUE THREAD

**Issue by kostis** [Z3Prover/z3#961]
We are using z3 in a concolic testing tool, called [CutEr](https://github.com/aggelgian/cuter/) and are heavily relying on it -- thanks for all your excellent work, by the way!

We have noticed various regressions between v4.5.0, which we use on Travis, and the current `master` branch, which we use for local testing on our own machines (and so that we can notice problems before it is too late).

One of them, perhaps the simplest one, is shown below:
```sh
$ z3 -version
Z3 version 4.5.0 - 64 bit
$ z3 -smt2 -T:2 cuter1.smt2 
sat
$ z3 -smt2 -T:2 cuter2.smt2
sat

$  z3 -version
Z3 version 4.5.1 - 64 bit
$ z3 -smt2 -T:2 cuter1.smt2 
unknown
$ z3 -smt2 -T:2 cuter2.smt2
sat
```

Files can be [found here](https://gist.github.com/aggelgian/61d82ff30a6d3700dee060d85dc020c2).  Seems it's not possible to attach `.smt2` files on GitHub.

Thanks to @aggelgian for minimizing the examples.

PS. There are various other regressions between v4.5.0 and master, but we'll leave these for after this one is fixed.

**Comment by wintersteiger** [comment]
Renaming problem similar to https://github.com/Z3Prover/z3/issues/930, but with quantifiers hidden datatype declarations. 

We're striving to resolve these issues, but in general it's not always possible to do so. Renaming a constant/variable changes the internal order of terms which causes various heuristics to produce different behavior.

**Comment by kostis** [comment]
The problem in this case is that the behavior between 4.5.0 and current master has _deteriorated_.  This has broken our test suite in various ways and we are not able to be test with the current master for quite a while now.  Still, we understand that this breakage was not intentional.  Perhaps a `git bisect` may identify the culprit and it may turn out to be something which is quite easy to restore.

**Comment by NikolajBjorner** [comment]
Btw, changing the random seed has some influence on this.

**Comment by aggelgian** [comment]
Hello!

I hope the following helps!
I've traced the deviance to the commits of March 11 and March 12.

The last commit where the model was satisfiable was 509f7409badc0e7834968511ca3c6b6f97fdaed6.
For the next 3 commits (228111511c8293c7a4b35743b141693d4a3b6415, 559c5e5ae63e13a0fbb18b7b6589d8a0b111debe, 7272d3f480e0a6b9559580e862cdbb2414b5d709), a segmentation fault was occuring.
From the 4th commit (8bec1e25a83e8e3f8c9b48f1641b68b6df841f08) onwards, the satisfiability is uknown.

```
aggelgian@sandy:~/git-repos/z3$ git log -1
commit 509f7409badc0e7834968511ca3c6b6f97fdaed6
Author: Nikolaj Bjorner <nbjorner@microsoft.com>
Date:   Fri Mar 10 23:01:43 2017 +0100

    adding fixedpoint object to C++ API
    
    Signed-off-by: Nikolaj Bjorner <nbjorner@microsoft.com>
aggelgian@sandy:~/git-repos/z3$ ./build/z3 -smt2 -T:2 ~/cuter1.smt2 
sat

aggelgian@sandy:~/git-repos/z3$ git log -1
commit 228111511c8293c7a4b35743b141693d4a3b6415
Author: Nikolaj Bjorner <nbjorner@microsoft.com>
Date:   Sat Mar 11 18:41:36 2017 +0100

    fixing build break, addressing #935
    
    Signed-off-by: Nikolaj Bjorner <nbjorner@microsoft.com>
aggelgian@sandy:~/git-repos/z3$ ./build/z3 -smt2 -T:2 ~/cuter1.smt2 
Segmentation fault

aggelgian@sandy:~/git-repos/z3$ git log -1
commit 559c5e5ae63e13a0fbb18b7b6589d8a0b111debe
Author: James Bornholt <bornholt@cs.washington.edu>
Date:   Sat Mar 11 16:03:09 2017 -0800

    z3py: With tactical should not try to use context as a parameter
aggelgian@sandy:~/git-repos/z3$ ./build/z3 -smt2 -T:2 ~/cuter1.smt2 
Segmentation fault

aggelgian@sandy:~/git-repos/z3$ git log -1
commit 7272d3f480e0a6b9559580e862cdbb2414b5d709
Merge: 2281115 559c5e5
Author: Nikolaj Bjorner <nbjorner@microsoft.com>
Date:   Sun Mar 12 08:25:53 2017 +0100

    Merge pull request #936 from jamesbornholt/z3py-with
    
    z3py: With tactical should not try to use context as a parameter
aggelgian@sandy:~/git-repos/z3$ ./build/z3 -smt2 -T:2 ~/cuter1.smt2 
Segmentation fault

aggelgian@sandy:~/git-repos/z3$ git log -1
commit 8bec1e25a83e8e3f8c9b48f1641b68b6df841f08
Author: Nikolaj Bjorner <nbjorner@microsoft.com>
Date:   Sun Mar 12 08:32:06 2017 +0100

    move restore relevancy until after literals have been replayed
    
    Signed-off-by: Nikolaj Bjorner <nbjorner@microsoft.com>
aggelgian@sandy:~/git-repos/z3$ ./build/z3 -smt2 -T:2 ~/cuter1.smt2 
unknown
```

**Comment by PierreVDL** [comment]
@kostis About Seems it's not possible to attach  .smt2  files on GitHub: when you zip them you can attach them....

**Comment by NikolajBjorner** [comment]
I am no longer getting unknown results for this.
