### ISSUE TITLE
Behavior of set-option

### ISSUE THREAD

**Issue by zvonimir** [Z3Prover/z3#962]
I have observed strange behaviors related to using `set-option` from Boogie, and hence I have two quick questions that would be helpful to clarify:
1. Are option names case sensitive or not? Meaning, is for example `(set-option :smt.MBQI false)` the same as `(set-option :smt.mbqi false)`?
2. What happens when the same option is set twice but to different values? For example, if we have `(set-option :smt.MBQI false)` followed by `(set-option :smt.MBQI true)`?

**Comment by NikolajBjorner** [comment]
It is case insensitive.

Try:

    (get-option :smt.mbqi)
    (set-option :smt.MBQI false) 
    (get-option :smt.mbqi)
    (set-option :smt.mbqi true)
    (get-option :smt.mbqi)
    (set-option :smt.mbqi false)
    (get-option :smt.mbqi)

Try

   (set-option :smt.blah)

and you get an error message

**Comment by wintersteiger** [comment]
For the special case of smt.mbqi: be aware that Z3 may overwrite that setting if auto_config=true.
