### ISSUE TITLE
Invalid model generated for smallish (2k bytes) file of string, bool and int constraints

### ISSUE THREAD

**Issue by juliandolby** [Z3Prover/z3#963]
I have been generating various sets of constraints using Rosette with Talia Ringer's string support, and I just came across one set of constraints that seems to trigger bad behavior in z3.  I am attaching the set of constraints.

Thanks,
   Julian

[constraints.zip](https://github.com/Z3Prover/z3/files/891320/constraints.zip)

**Comment by krypt-n** [comment]
I removed some parts of the instance that are not necessary for the invalid model.

```
(set-option :model_validate true)

(declare-fun c2 () Int)

(assert (<= 0 c2))
(assert (<= c2 8))
(assert (not (<= 0 (str.indexof "a123cdef" (str.substr "a123cdef" 0 c2) 0))))
(check-sat)
(get-model)
```
Z3 finds a solution with `c2 = 6` for this instance and reports an invalid model. However a slight modification of the third assertion (e.g. changing `<= 0` to `< 1`) makes Z3 find a valid assignment with `c2 = 8`.

**Comment by NikolajBjorner** [comment]
It should be addressed by now

**Comment by NikolajBjorner** [comment]
seems theory_seq has regressed

**Comment by NikolajBjorner** [comment]
it works properly at this point
