### ISSUE TITLE
Simple equations with products of array elements return "unknown"

### ISSUE THREAD

**Issue by dgenin** [Z3Prover/z3#968]
The following code results in "unknown" in Z3 v 4.5.0

(declare-const a (Array Int Real))
(assert (= (* (select a 1) (select a 1)) 1))
(check-sat)
(get-model)

**Comment by wintersteiger** [comment]
Confirmed and half expected. Due to non-linearity the (bare SMT) solver gives up and due to the theory combination with arrays we can't use a specialized solver (eg qfnra-nlsat tactic). When * is replaced with + everything works fine and quickly. If it is only about this very particular case, we can make it work by using the nlsat tactic like so:

```
(check-sat-using qfnra-nlsat)
```

which does produce the model

```
(model 
  (define-fun a () (Array Int Real)
    ((as const (Array Int Real)) (- 1.0)))
)
```

but that strategy quickly fails if the queries become more complex, e.g. by adding a second array element:

```
(assert (= (* (select a 1) (select a 2)) 1))
```

**Comment by dgenin** [comment]
I used the above code just as an example. I was hoping to implement general matrix operations for weakest precondition analysis by using built-in arrays. It seems the only way to handle matrices is to instantiate each entry as a separate variable, correct? How hard would it be to extend the non-linear solver to operate on expressions with array elements?

**Comment by wintersteiger** [comment]
Very hard. We have a little bit of non-linear reasoning the default solver (smt, theory arith) but that will give up very early; and we have qfnra-nlsat, which does only arithmetic and no arrays (or other theories), it's essentially a completely different solver, disjoint from the implementation of the SMT solver. 

Note that SMT2 arrays are of infinite size. If the size of your matrices is fixed (and not huge), introducing new variables for each matrix entry will definitely create fewer problems down the road.

**Comment by dgenin** [comment]
Interesting, I didn't realize qfnra-nlsat was so completely divorced from all other theories.

My matrices aren't big but for weakest precondition analysis I need to implement operations on entries whose positions are determined by variables in the code being analyzed which is impossible if matrices are encoded by independent variables.

Thank you for the explanation.

**Comment by krypt-n** [comment]
> My matrices aren't big but for weakest precondition analysis I need to implement operations on entries whose positions are determined by variables in the code being analyzed which is impossible if matrices are encoded by independent variables.

I have no idea how well qfnra-nlsat would be able to work with that, but you could model indexing of the independent variables with a bunch of nested ITEs.

**Comment by dgenin** [comment]
That is a terrific idea. I think, you may have just solved my matrix problem. Thank you!
