### ISSUE TITLE
Issue with QF_FD

### ISSUE THREAD

**Issue by sfrank** [Z3Prover/z3#971]
Hi,

it appears that the new QF_FD solver does not calculate the correct values for me (or I'm doing something completely wrong).

I started to investigate since I had some unexplained behavior with my own model and arrived at the attached standard Sudoku example from the z3py user guide. When solving with the default solver we get the expected result, with QF_FD there is no solution, though this model instance should be manageable by QF_FD as well, as far as I understand.

The investigation of my own model problems suggests, that inequalities (!=, i.e. not equal) are not handled correctly since I see a lot of equalities between variables in the constraint store that should be negated (i.e. not equal)

Thank you and kind regards,
Stephan
[sudoku.txt](https://github.com/Z3Prover/z3/files/908442/sudoku.txt)

**Comment by NikolajBjorner** [comment]
It's a limitation with QF_FD. It doesn't recognize that the problem is finite domain so it returns unknown.
Not all problems with integers are recognized as finite domain. It does some limited best effort.

**Comment by NikolajBjorner** [comment]
I have fixed the code to avoid the limitation.
