### ISSUE TITLE
Encoding of Z3 input and output error

### ISSUE THREAD

**Issue by PierreVDL** [Z3Prover/z3#975]
When I execute the file EscapeUTF8.smt2 with Z3,
I get the following output:
```
sat
((s "Ç"))
unsat
unsat
```
EscapeUTF8.smt in Notepad++ in ANSI encoding is:
![notepad encodinginansi](https://cloud.githubusercontent.com/assets/13330317/24961756/1f46c17c-1f9a-11e7-82f9-2585252db7c1.jpg)

EscapeUTF8.smt in Notepad++ in UTF-8 encoding is:
![notepad encodinginutf-8](https://cloud.githubusercontent.com/assets/13330317/24961789/3b155af8-1f9a-11e7-9dde-69e56e37bdc1.jpg)

So I would have expected that at least one of the two latest results should be sat!

Note: 
I used Z3 version 4.5.1 - 64 bit - build hashcode 4140afa4cb27
zipped file: 
[EscapeUTF8.zip](https://github.com/Z3Prover/z3/files/916773/EscapeUTF8.zip)

**Comment by NikolajBjorner** [comment]
It should be fixed now

**Comment by PierreVDL** [comment]
Thanks!
