### ISSUE TITLE
Doxygen link on wiki is broken

### ISSUE THREAD

**Issue by fritzo** [Z3Prover/z3#976]
Is there an updated link to the doxygen documentation pointed to by https://github.com/Z3Prover/z3/wiki/Documentation ?

**Comment by NikolajBjorner** [comment]
Thanks for notifying this. I have now removed the stale link. We are unable to serve the doxygen pages from the previous location and they were last updated in 2015 so would be relatively useless. A solution to documentation indexing within the context of GitHub will be more suitable.

**Comment by wintersteiger** [comment]
The API documentation is hosted [GitHub](https://github.com/Z3Prover/z3prover.github.io) and theoretically we could also publish the code documentation there. I didn't do that when we moved to GitHub because it's rather large (GBs) and the repositories are limited in size (but fuzzy rules).

**Comment by NikolajBjorner** [comment]
The documentation resides on z3prover.github.io and is lined from 
https://github.com/Z3Prover/z3/wiki/Documentation. 
It is updated (manually) to the current master state.
