### ISSUE TITLE
Missing regular expression's operation in Java API

### ISSUE THREAD

**Issue by facanferff** [Z3Prover/z3#977]
Hi, when trying to write a simple example involving the range operation (re.range) I found that the operation is not available in the Java API.

Given the operation
(re.range ch1 ch2)	The range of characters between ch1 and ch2.
is specified at http://rise4fun.com/z3/tutorialcontent/sequences, is the Java API missing the corresponding operation?

Thanks.

**Comment by facanferff** [comment]
((_ re.loop lo hi) r)	from lo to hi number of repetitions of r.
is also missing.

**Comment by facanferff** [comment]
I see you added the requested operations, thanks.
Meanwhile I found two more operations missing:
re.complement
and
re.inter

**Comment by NikolajBjorner** [comment]
I have added the mentioned functions.

**Comment by facanferff** [comment]
I confirm they are working as intended, thanks.
