### ISSUE TITLE
z3 python: LShR fails for args with different bit-sizes

### ISSUE THREAD

**Issue by mkow** [Z3Prover/z3#978]
LShR fails when both args (BitVecs) have different size, resulting in an ugly exception.

Example code:

```python
import z3

p = z3.BitVec('p', 8)
k = z3.BitVec('k', 16)
z3.LShR(k, p)
```

This results in:

```
Traceback (most recent call last):
  File "z3_test.py", line 5, in <module>
    z3.LShR(k, p)
  File "/usr/lib/python2.7/dist-packages/z3/z3.py", line 3873, in LShR
    return BitVecRef(Z3_mk_bvlshr(a.ctx_ref(), a.as_ast(), b.as_ast()), a.ctx)
  File "/usr/lib/python2.7/dist-packages/z3/z3core.py", line 1996, in Z3_mk_bvlshr
    raise Z3Exception(lib().Z3_get_error_msg(a0, err))
z3.z3types.Z3Exception: Argument p at position 1 does not match declaration (declare-fun bvlshr ((_ BitVec 16) (_ BitVec 16)) (_ BitVec 16))
```

I think it should be possible to use LShR with BitVectors of different sizes, the shift count bit-size is most of the time much smaller than first argument's bit-size.
If it's not possible to fix it, it would be nice to at least have a nicer exception message that a lisp listing ;)

My z3 version: 4.5.1 (at commit 66e61b8a31a04a858af570e0665fcdd61fc0c2d2)

**Comment by NikolajBjorner** [comment]
Bit-widths should be the same. You can zero-extend bits to have them aligned. 
There is no auto-alignment to second-guess user intent.
Exception messages are shared among all interfaces and uses the SMT2 syntax in this case.
