### ISSUE TITLE
ambiguities in README

### ISSUE THREAD

**Issue by fspegni** [Z3Prover/z3#979]
Hi,
I share this because I tried to execute the install instructions contained in your README and faced two issues because of ambiguous instructions/small mistakes (or you are free to think that I'm too dumb :)):

- in the section title "Building Z3 using make and GCC/Clang" you suggest to change the `mk_make.py` line prepending `CXX=... CC=... python mk_make.py`; somehow, when first reading, I understood that I was supposed to change a line in the file `scripts/mk_make.py` to specify the content of the two variables; later I realized it couldn't work. Perhaps just a small rephrasing would help people not to fall in the same mistake

- in the very same section, you say that by default the `mk_make.py` looks for the `gcc` compiler; to my surprise I had it installed, but it was not happy with that, until I installed `g++` and run the `python mk_make.py` line again. Even though they are sometimes considered as "the same compiler", I think it's preferable to state that your tool looks for `g++` by default

Thanks for all your work.

**Comment by delcypher** [comment]
@fspegni 
> in the section title "Building Z3 using make and GCC/Clang" you suggest to change the mk_make.py line prepending CXX=... CC=... python mk_make.py; somehow, when first reading, I understood that I was supposed to change a line in the file scripts/mk_make.py to specify the content of the two variables; later I realized it couldn't work. Perhaps just a small rephrasing would help people not to fall in the same mistake

Setting `CXX` and `CC` as environment variables is a very common practice for build systems so I implicitly assumed the reader would understand this. I was wrong.

I've made some tweaks based on your suggestions in https://github.com/Z3Prover/z3/pull/980 . Please check you are happy with them.

**Comment by fspegni** [comment]
Thanks. I think it's clearer now. I close the issue.
