### ISSUE TITLE
Why `-fno-strict-aliasing` applied to all UNIX like systems apart from Darwin?

### ISSUE THREAD

**Issue by delcypher** [Z3Prover/z3#987]
This is something I noticed when implementing the CMake build system but I forgot to ask about.

In the python/Makefile build system it seems that the `-fno-strict-aliasing` flags is passed to the compiler for all UNIX like systems apart from Darwin.

See https://github.com/Z3Prover/z3/blob/69aa5ca877f5de0a2c00515d0fe86a797b95701a/scripts/mk_util.py#L2445 .

* Why is the `-fno-strict-aliasing` flag being used?
* Why is that flag not used Darwin?

For the CMake build system [I just copied the behaviour of the existing build system](https://github.com/Z3Prover/z3/blob/69aa5ca877f5de0a2c00515d0fe86a797b95701a/CMakeLists.txt#L219).

I'm not sure if this behaviour is intentional so I thought it would be best to ask just in case this is a bug.

**Comment by wintersteiger** [comment]
I think this was added for performance reasons, but that was a very long time ago. At the time, gcc/g++ was the default compiler for OSX and it had `-fno-strict-aliasing` enabled by default. I'm not sure that clang/LLVM support that flag at all now.

**Comment by delcypher** [comment]
@wintersteiger Huh. I would of thought disabling strict aliasing would be for correctness reasons (e.g. see http://stackoverflow.com/questions/2958633/gcc-strict-aliasing-and-horror-stories ). If you do type punning with strict aliasing enabled I'm not sure you'll get correct results.

**Comment by wintersteiger** [comment]
@delcypher That's right, it shouldn't be there. It seems like the git history is missing a commit that I remember. Originally @leodemoura had added that flag in 2012 ([here](https://github.com/Z3Prover/z3/commit/b94edf8fe68b6658b2a6a31e8835759525265ed2)) and I remember @nunoplopes removing (not adding) the flag, which he did [here](http://z3.codeplex.com/SourceControl/changeset/f07647f966af7307f34ed72132d51480d950f62a), [here](http://z3.codeplex.com/SourceControl/changeset/aa42905be7f454946de059a5746d02a5a6ed3935), and [here](http://z3.codeplex.com/SourceControl/changeset/3dfd6a1f7bad2632fce3f6b8300e721067f7c73f), but none of those commits made it off of Codeplex when we moved to GitHub. @nunoplopes: Was there a reason for this change not making it into master or did something go wrong here and we could be missing some related changes made at the time?

**Comment by nunoplopes** [comment]
I removed it from my old branch in codeplex.  The reason we didn't remove it here was that the fix to ast.h needs C++11 (unions of non PODs).  I guess now we can apply that fix and get rid of no strict aliasing.
It's on my todo list..  Essentially we need to port the relevant bits of this: http://z3.codeplex.com/SourceControl/changeset/f71fd3d0827dedd3b167782efab13f39144e4517

**Comment by NikolajBjorner** [comment]
See also #1210 which discusses a commit by Nuno to address this issue.
