### ISSUE TITLE
z3 installs into the non-standard dist-packages

### ISSUE THREAD

**Issue by asmeurer** [Z3Prover/z3#99]
z3 installs the Python bindings into dist-packages, which is non-standard (see http://stackoverflow.com/a/9388115/161801), and not in the `sys.path` by default on most platforms. Ideally z3 should be using distutils and a setup.py to install its Python bindings, but regardless, it should install to a standard location (i.e., site-packages). 

It would also be better to install z3 as a module rather than as several flat files, to avoid namespace conflicts. I don't know if this can be done without breaking the API however.

**Comment by wintersteiger** [comment]
Just a note: As stated in the stackoverflow post referred to, dist-packages is not non-standard, it's just a Debian/Ubuntu convention. 

The installation process for the Python API will change soon to enable automatic packaging, and that will also resolve the current problem. (See also #63, #72, #73.)
