### ISSUE TITLE
[CMake] Broken debug info in RelWithDebInfo build mode

### ISSUE THREAD

**Issue by delcypher** [Z3Prover/z3#990]
Taken from #986 

Stated by @NikolajBjorner 
For starters, I get these kind of warnings (RelWithDebInfo) on my various machines.

api_log_macros.cpp.obj : warning LNK4099: PDB 'vc140.pdb' was not found with 'api_log_macros.cpp.obj' or at 'C:\z3\build\vc140.pdb'; linking object as if no debug info
api_commands.cpp.obj : warning LNK4099: PDB 'vc140.pdb' was not found with 'api_commands.cpp.obj' or at 'C:\z3\build\vc140.pdb'; linking object as if no debug info
z3_replayer.cpp.obj : warning LNK4099: PDB 'vc140.pdb' was not found with 'z3_replayer.cpp.obj' or at 'C:\z3\build\vc140.pdb'; linking object as if no debug info
api_tactic.cpp.obj : warning LNK4099: PDB 'vc140.pdb' was not found with 'api_tactic.cpp.obj' or at 'C:\z3\build\vc140.pdb'; linking object as if no debug info
api_stats.cpp.obj : warning LNK4099: PDB 'vc140.pdb' was not found with 'api_stats.cpp.obj' or at 'C:\z3\build\vc140.pdb'; linking object as if no debug info
api_solver.cpp.obj : warning LNK4099: PDB 'vc140.pdb' was not found with 'api_solver.cpp.obj' or at 'C:\z3\build\vc140.pdb'; linking object as if no debug info
api_seq.cpp.obj : warning LNK4099: PDB 'vc140.pdb' was not found with 'api_seq.cpp.obj' or at 'C:\z3\build\vc140.pdb'; linking object as if no debug info

I am not sure where "vc140.pdb" gets pinned by the build system and where I would fetch it from.
The post http://stackoverflow.com/questions/33292241/generating-pdb-files-correctly-for-a-native-dll-using-visual-studio-2013 indicates it is entirely handled by the build system.

About repros
C:\z3>cmake --version
cmake version 3.5.2
C:\z3>ninja --version
1.6.0
C:\z3>cl --version
Microsoft (R) C/C++ Optimizing Compiler Version 19.00.24215.1 for x86
Repro scenario: take some smt2 file that takes more than 10 seconds to run. Select sampling based profiling from the VS profiling wizard, configure the profiler to run z3.exe on the appropriate long running input. The stack trace information in the profiler is going to be inaccurate (compared to what gets generated by python/nmake).

**Comment by delcypher** [comment]
@NikolajBjorner I've been unable to reproduce your warnings about `vc140.pdb`. The set up I used was

* Windows 8
* Visual Studio 2015 Community Edition
* Ninja 1.6.0
* CMake 3.5.2

1. Clone latest sources and bootstrap CMake build

```
git clone https://github.com/Z3Prover/z3.git
cd z3.git
python contrib/cmake/boostrap.py create
```

2. In windows command prompt prepare the environment to use MSVC (x86 rather than x64 to reproduce your set up)

```
cd "c:\Program Files (x86)\Microsoft Visual Studio 14.0\VC"
vcvarsall.bat x86
cl
Microsoft (R) C/C++ Optimizing Compiler Version 19.00.24215.1 for x86 
Copyright (C) Microsoft Corporation.  All rights reserved.

usage: cl [ option... ] filename... [ /link linkoption... ]
```

3. Now change into the directory containing Z3 git repository and do the build

```
cd \path\to\z3
mkdir build_ninja_x86
cd build_ninja_x86
cmake -G Ninja -DCMAKE_BUILD_TYPE=RelWithDebInfo ..
ninja
```

I don't see any warnings about missing pdb files.

4. Check pdb files can be found (I do this in my git prompt that has the UNIX `find` command)

```
$ find . -iname '*.pdb'
./libz3.pdb
./src/ackermannization/CMakeFiles/ackermannization.dir/vc140.pdb
./src/api/CMakeFiles/api.dir/vc140.pdb
./src/api/dll/CMakeFiles/api_dll.dir/vc140.pdb
./src/ast/CMakeFiles/ast.dir/vc140.pdb
./src/ast/fpa/CMakeFiles/fpa.dir/vc140.pdb
./src/ast/macros/CMakeFiles/macros.dir/vc140.pdb
./src/ast/normal_forms/CMakeFiles/normal_forms.dir/vc140.pdb
./src/ast/pattern/CMakeFiles/pattern.dir/vc140.pdb
./src/ast/proof_checker/CMakeFiles/proof_checker.dir/vc140.pdb
./src/ast/rewriter/bit_blaster/CMakeFiles/bit_blaster.dir/vc140.pdb
./src/ast/rewriter/CMakeFiles/rewriter.dir/vc140.pdb
./src/ast/simplifier/CMakeFiles/simplifier.dir/vc140.pdb
./src/ast/substitution/CMakeFiles/substitution.dir/vc140.pdb
./src/cmd_context/CMakeFiles/cmd_context.dir/vc140.pdb
./src/cmd_context/extra_cmds/CMakeFiles/extra_cmds.dir/vc140.pdb
./src/duality/CMakeFiles/duality.dir/vc140.pdb
./src/interp/CMakeFiles/interp.dir/vc140.pdb
./src/math/automata/CMakeFiles/automata.dir/vc140.pdb
./src/math/euclid/CMakeFiles/euclid.dir/vc140.pdb
./src/math/grobner/CMakeFiles/grobner.dir/vc140.pdb
./src/math/hilbert/CMakeFiles/hilbert.dir/vc140.pdb
./src/math/interval/CMakeFiles/interval.dir/vc140.pdb
./src/math/polynomial/CMakeFiles/polynomial.dir/vc140.pdb
./src/math/realclosure/CMakeFiles/realclosure.dir/vc140.pdb
./src/math/simplex/CMakeFiles/simplex.dir/vc140.pdb
./src/math/subpaving/CMakeFiles/subpaving.dir/vc140.pdb
./src/math/subpaving/tactic/CMakeFiles/subpaving_tactic.dir/vc140.pdb
./src/model/CMakeFiles/model.dir/vc140.pdb
./src/muz/base/CMakeFiles/muz.dir/vc140.pdb
./src/muz/bmc/CMakeFiles/bmc.dir/vc140.pdb
./src/muz/clp/CMakeFiles/clp.dir/vc140.pdb
./src/muz/dataflow/CMakeFiles/dataflow.dir/vc140.pdb
./src/muz/ddnf/CMakeFiles/ddnf.dir/vc140.pdb
./src/muz/duality/CMakeFiles/duality_intf.dir/vc140.pdb
./src/muz/fp/CMakeFiles/fp.dir/vc140.pdb
./src/muz/pdr/CMakeFiles/pdr.dir/vc140.pdb
./src/muz/rel/CMakeFiles/rel.dir/vc140.pdb
./src/muz/tab/CMakeFiles/tab.dir/vc140.pdb
./src/muz/transforms/CMakeFiles/transforms.dir/vc140.pdb
./src/nlsat/CMakeFiles/nlsat.dir/vc140.pdb
./src/nlsat/tactic/CMakeFiles/nlsat_tactic.dir/vc140.pdb
./src/opt/CMakeFiles/opt.dir/vc140.pdb
./src/parsers/smt/CMakeFiles/smtparser.dir/vc140.pdb
./src/parsers/smt2/CMakeFiles/smt2parser.dir/vc140.pdb
./src/parsers/util/CMakeFiles/parser_util.dir/vc140.pdb
./src/qe/CMakeFiles/qe.dir/vc140.pdb
./src/sat/CMakeFiles/sat.dir/vc140.pdb
./src/sat/sat_solver/CMakeFiles/sat_solver.dir/vc140.pdb
./src/sat/tactic/CMakeFiles/sat_tactic.dir/vc140.pdb
./src/shell/CMakeFiles/shell.dir/vc140.pdb
./src/smt/CMakeFiles/smt.dir/vc140.pdb
./src/smt/params/CMakeFiles/smt_params.dir/vc140.pdb
./src/smt/proto_model/CMakeFiles/proto_model.dir/vc140.pdb
./src/smt/tactic/CMakeFiles/smt_tactic.dir/vc140.pdb
./src/solver/CMakeFiles/solver.dir/vc140.pdb
./src/tactic/aig/CMakeFiles/aig_tactic.dir/vc140.pdb
./src/tactic/arith/CMakeFiles/arith_tactics.dir/vc140.pdb
./src/tactic/bv/CMakeFiles/bv_tactics.dir/vc140.pdb
./src/tactic/CMakeFiles/tactic.dir/vc140.pdb
./src/tactic/core/CMakeFiles/core_tactics.dir/vc140.pdb
./src/tactic/fpa/CMakeFiles/fpa_tactics.dir/vc140.pdb
./src/tactic/nlsat_smt/CMakeFiles/nlsat_smt_tactic.dir/vc140.pdb
./src/tactic/portfolio/CMakeFiles/portfolio.dir/vc140.pdb
./src/tactic/sls/CMakeFiles/sls_tactic.dir/vc140.pdb
./src/tactic/smtlogics/CMakeFiles/smtlogic_tactics.dir/vc140.pdb
./src/tactic/ufbv/CMakeFiles/ufbv_tactic.dir/vc140.pdb
./src/test/fuzzing/CMakeFiles/fuzzing.dir/vc140.pdb
./src/util/CMakeFiles/util.dir/vc140.pdb
./z3.pdb
```

**Comment by delcypher** [comment]
@NikolajBjorner However I found in a bug in the way the CMake build sets compilers flags so I'd advise that you let me fix that first and once that is accepted remove your existing build directory and do a fresh build using the steps I describe above.

**Comment by NikolajBjorner** [comment]
thanks, I currently see many vc140.pdb files, but not all directories have them.

**Comment by delcypher** [comment]
@NikolajBjorner PR #993 changes the CMake build system to be much more similar to what the python/Make system. Once that's merged I suggest creating a brand new build directory and trying a new build.

One thing you didn't mention is how you configuring the old build system. If you were using `--optimize` configure flag from the python/Makefile build system then you can now do the same thing with the CMake build system by passing `-DLINK_TIME_OPTIMIZATION=TRUE` to the cmake command when configuring.

Note I have very low confidence in using `LINK_TIME_OPTIMIZATION` with gcc/clang so I don't advise using it with those compilers yet. When I tried I got a bunch of warnings about one-definition rule violations so there's like some latent bugs in Z3 that need to be fixed.

**Comment by NikolajBjorner** [comment]
With the latest updates to the cmake scripts I get very nice stacks from within the profiler! 
Perhaps related to the frame-pointer directives.

**Comment by delcypher** [comment]
@NikolajBjorner Thanks for testing. If you believe the flag that fixed this is related to the frame pointer then we probably should fix the slightly broken logic here.

```cmake
# FIXME: This doesn't make a huge amount of sense but the old
# build system kept the frame pointer for all configurations
# except x86_64 release (I don't know why the frame pointer
# is kept for i686 release).
if ("${TARGET_ARCHITECTURE}" STREQUAL "x86_64")
  list(APPEND Z3_COMPONENT_CXX_FLAGS
    $<$<CONFIG:Debug>:${NO_OMIT_FRAME_POINTER_MSVC_FLAG}>
    $<$<CONFIG:MinSizeRel>:${NO_OMIT_FRAME_POINTER_MSVC_FLAG}>
  )
else()
  list(APPEND Z3_COMPONENT_CXX_FLAGS ${NO_OMIT_FRAME_POINTER_MSVC_FLAG})
endif()
```

The code above is passing `/Oy-` only for `Debug` and `MinSizeRel` configurations (i.e. not for `Release` or `RelWithDebInfo` configurations) for 64-bit x86 and for 32-bit x86 the flag is passed for all configurations. Right now if you did a 64-bit using the `RelWithDebInfo` configuration `/Oy-` is not passed to the compiler and you might find this breaks profiling.

This (sort of) mimics the old build systems behaviour but it's probably wrong. Do you know in what situations we should and should not be passing this flag?
