### ISSUE TITLE
z3 4.5.0 incorrectly returns unsat for model

### ISSUE THREAD

**Issue by hallba** [Z3Prover/z3#991]
See the attached zip file for an SMT file that reproduces the problem; this was tested in z3 4.4.1 (returns sat, and the correct model) and z3 4.5.0 (returns unsat) using the 64 bit windows binaries available here. The bug arose in testing of the BMA (https://github.com/Microsoft/BioModelAnalyzer)

The model has three variables, vA vB and vO. All three are integers, constrained to be equal to 1 through simple assertions. O is also constrained to be 1 by a formula dependent on the values of A and B converted to reals. 

In testing with z3 4.5.0 Deletion of either assertion that constrains vO causes z3 to return sat and the correct model (vA=1,vB=1,vO=1), but with both assertions present the model returns unsat. Additionally, replacing instances of vA or vB with 1 in the complex constraint on vO causes z3 to return sat.

[problem.zip](https://github.com/Z3Prover/z3/files/965002/problem.zip)

**Comment by NikolajBjorner** [comment]
Here is a slightly smaller version of the repro:

(declare-fun vO () Int)
(declare-fun vA () Int)
(declare-fun vB () Int)

(assert (= vB 1))
(assert (= vA 1))
(assert (= vO 1))

(assert 
 (let ((a!2 (ite (< (to_real vA) 1. ) (to_real vB) (to_real vA))))
 (let ((a!3 (* a!2 (to_real vA))))
 (= (to_int (+ a!3 (/ 1.0 2.0))) vO))))


(check-sat)
(get-model)

**Comment by hallba** [comment]
Git bisect reveals that the first commit that introduces the issue is 20cfbcd66b680bad0973c88963b1b19ed2264920

**Comment by wintersteiger** [comment]
@hallba did you try whether Nikolaj's fix resolves this problem? Both your repros are sat according to my z3 (latest master).

**Comment by hallba** [comment]
Tested with both the SMT and the original (BMA) example. Latest master no longer has this issue. Thanks!
