### ISSUE TITLE
Segmentation fault on a few BV benchmarks

### ISSUE THREAD

**Issue by Heizmann** [Z3Prover/z3#996]
Using the current z3 version aceee3fac8912629e0d1e3568bb0788f184138d6 on Linux, I get a sementation fault on the following SMT scripts.
https://xayn.heizmann.name/nextcloud/index.php/s/H8kpYvOeJcB7LPz

**Comment by NikolajBjorner** [comment]
As added bonus, could you use a proper certificate?

ERROR: The certificate of ‘xayn.heizmann.name’ is not trusted.
ERROR: The certificate of ‘xayn.heizmann.name’ hasn't got a known issuer.

**Comment by NikolajBjorner** [comment]
I do have the files, btw, so no hurry

**Comment by NikolajBjorner** [comment]
Can I close this?

**Comment by Heizmann** [comment]
Yes.
(Sorry, I forgot to check. I just did an update of z3. For Ultimate Automizer the problem is fixed. Thanks.)
