### ISSUE TITLE
Previous version of z3

### ISSUE THREAD

**Issue by MiaoDX** [Z3Prover/z3#997]
I am trying to use a program which uses z3 version 2.19, the link provided in [FAQ](https://github.com/Z3Prover/z3/wiki/FAQ) a.k.a [the download page on codeplex](http://z3.codeplex.com/wikipage?title=Older%20Versions) seems down.

And the [stackoverflowanswer](http://stackoverflow.com/questions/11122735/previous-version-of-z3-for-linux) are also unusable now.

So, could it be possible to provide the previous version of z3 (or links) in this repo?

Thanks a lot.

**Comment by NikolajBjorner** [comment]
The unmanaged web sites are no longer accessible from outside. 
I copied a couple of 2.19 files over to:
https://github.com/Z3Prover/bin/tree/master/legacy
I wonder, if your application is using 2.19 it must be quite outdated and not maintained.
Hopefully needless to say: we can't address any bugs in 2.19 at this point.

**Comment by MiaoDX** [comment]
Ah! Sorry for the very late reply, I was tring to use [angelix](https://github.com/mechtaev/angelix), a semantics-based automated program repair tool for C programs. Which is using both v2.19 and latest version of z3. Thanks for your kindness help to upload the files and it really helped a lot.
